MystenLabs/sui

- crates/sui-core/src/checkpoints/mod.rs
Logging and scope around the actual wait
> Fix checkpoint builder tx sequence wait logging

- crates/sui-config/src/lib.rs
- crates/sui-config/src/node_config_metrics.rs
- crates/sui-config/src/transaction_deny_config.rs
- crates/sui-core/src/transaction_signing_filter.rs
- crates/sui-node/src/lib.rs
Cherry-pick https://github.com/MystenLabs/sui/pull/11495
> Add node config metrics (cherry pick)

- apps/wallet/src/ui/app/staking/validators/ValidatorLogo.tsx
Disable linking to explorer from validator list
https://user-images.githubusercontent.com/126525197/235381735-24dacc40-6bcd-46ea-90bf-795b8a58794c.mov
> Disable linking to explorer from validator list

- .github/workflows/nightly-narwhal.yml
- .github/workflows/rust.yml
Otherwise CIs will often OOM during linking.
CI
---
> Cherrypick CI fix into 1.0.0 release branch

- crates/sui-config/src/builder.rs
- crates/sui-config/src/node.rs
- crates/sui-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/consensus_adapter.rs
- crates/sui-core/src/unit_tests/consensus_tests.rs
- crates/sui-node/src/lib.rs
Cherry-pick https://github.com/MystenLabs/sui/pull/11517
---
---
> cherry pick resubmission logic changes

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/clob.md
- crates/sui-framework/packages/deepbook/sources/clob.move
- crates/sui-framework/packages/deepbook/sources/math.move
- crates/sui-framework/packages/deepbook/tests/clob_tests.move
Replaces #11550, adds snapshots.
-
---------
Co-authored-by: wiggins-dev <zlnju@outlook.com>
---
> [deepbook] Cherry Pick: Deepbook snapshots patch (#11562)

- .github/workflows/nightly-narwhal.yml
- .github/workflows/rust.yml
- crates/sui-benchmark/src/fullnode_reconfig_observer.rs
- crates/sui-benchmark/src/lib.rs
- crates/sui-config/src/builder.rs
- crates/sui-config/src/lib.rs
- crates/sui-config/src/node.rs
- crates/sui-config/src/node_config_metrics.rs
- crates/sui-config/src/transaction_deny_config.rs
- crates/sui-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/consensus_adapter.rs
- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/quorum_driver/reconfig_observer.rs
- crates/sui-core/src/quorum_driver/tests.rs
- crates/sui-core/src/safe_client.rs
- crates/sui-core/src/test_utils.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-core/src/transaction_signing_filter.rs
- crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
- crates/sui-core/src/unit_tests/consensus_tests.rs
- crates/sui-core/src/unit_tests/execution_driver_tests.rs
- crates/sui-node/src/lib.rs
- crates/sui/tests/reconfiguration_tests.rs
> [cherry pick] 11548

- crates/sui-core/src/consensus_adapter.rs
To avoid another metrics disruption, we add new metrics and will delete old ones later.
---
> use mysten histogram in consensus adapter

- doc/src/learn/cryptography/sui-multisig.md
change `sui client execute-signed-tx --tx-bytes $TX_BYTES --signature $SERIALIZED_MULTISIG` to `sui client execute-signed-tx --tx-bytes $TX_BYTES --signatures $SERIALIZED_MULTISIG`
> Change --signature to --signatures

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/clob.md
- crates/sui-framework/packages/deepbook/sources/clob.move
> [deepbook] Adds paranoid checks for quantity

- crates/sui-core/src/consensus_adapter.rs
To avoid another metrics disruption, we add new metrics and will delete old ones later.
---
---
> [cherry-pick] use mysten histogram in consensus adapter (#11553)

- apps/wallet/src/ui/app/pages/approval-request/transaction-request/index.tsx
> [wallet-ext] fix typo in the UI

- crates/sui-core/src/consensus_adapter.rs
It seems currently observed latency is < 5s most of the time, so their actual values are not exposed via metrics. Re-using the `sequencing_estimated_latency` metric to expose the observed latency, so we can tune the threshold for resubmission better.
CI.
---
> [ConsensusAdapter] monitor observed latency and submission interval separately

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
Sui version bump to `v1.1.0`
👀
> Sui version bump `v1.1.0`

- apps/wallet/src/ui/app/components/ledger/ConnectLedgerModal.tsx
Will update this to the Ledger help center article when it's ready.
- Manual testing (I clicked the link lol)
---
N/A
> [wallet-ext] update Ledger tutorial link to point to our Github docs for the time being

- apps/explorer/src/components/module/PkgModulesWrapper.tsx
Package view is broken on all mobile view 
---
> Fix module error on mobile

- apps/wallet/src/ui/app/components/ledger/ConnectLedgerModal.tsx
> [wallet-ext] update Ledger tutorial URL one more time

- apps/wallet/src/shared/constants.ts
> Update TOS link

- doc/src/learn/cryptography/sui-signatures.md
closes https://github.com/MystenLabs/sui/issues/11627
n/a
---
> doc: use github link

- doc/src/learn/cryptography/index.md
Better ordering on cryptography learn subitems
---
> [learn] order cryptography menu items

- apps/core/src/utils/transaction/getGroupByOwner.ts
- apps/explorer/src/pages/transaction-result/transaction-summary/ObjectChanges.tsx
> [explorer]: Fix getGroupByOwner

- crates/sui-json-rpc/src/governance_api.rs
change APY calculation to use 30 days average of daily APY, also exclude data point before `stake_subsidy_start_epoch`
Manual testing on testnet
```
{
"result": {
"apys": [
{
"address": "0x44b1b319e23495995fc837dafd28fc6af8b645edddff0fc1467f1ad631362c23",
"apy": 0.06367719923107278
},
{
"address": "0x3d618b03660f4e8b4ec99c52af08a814f5248154937782d22b5a8f2e44ba15fc",
"apy": 0.0644859486532715
},
{
"address": "0x24e8511a01aa7ab06eb8ce61d6c002ac5b8b7e0fde809554ca3662fb184ce257",
"apy": 0.06389054258577678
},
{
"address": "0x4c05f4f76ed81d210e9a29ac0756c7a3129e4b9ecacbbb9fc1579505947630cf",
"apy": 0.06450673689670251
},
{
"address": "0x6881875df60daf5528d66a62b66dc5710bf06b220fa9266ffdfeeb9cd8d6ed94",
"apy": 0.06450271281790321
},
{
"address": …
```
> change APY calculation to include stake_subsidy_start_epoch

- crates/sui-adapter/src/adapter.rs
- crates/sui-adapter/src/execution_engine.rs
- crates/sui-adapter/src/programmable_transactions/linkage_view.rs
> Cherry pick #11648

- apps/explorer/src/components/footer/Footer.tsx
- apps/explorer/src/components/footer/Legal.tsx
- apps/explorer/src/components/footer/footerLinks.tsx
- Add responsive styles for the updated Footer
- Went back to using `footerLinks` to keep the markup a bit more tidy
- Note: It was non-trivial to get the order of items to reverse between Desktop / Mobile, so I compromised for the sake of time
---
> [explorer] - responsive footer update

- Cargo.lock
- crates/sui-adapter/Cargo.toml
- crates/sui-core/src/authority.rs
- crates/sui-core/src/execution_driver.rs
These monitored scopes provide more information on execution, e.g. time spent on reading input and actual executions, vs committing the results.
CI. Deployed more detailed version to private testnet.
---
> Add additional monitored scopes for timing executions

- apps/explorer/src/components/network/Network.tsx
- apps/explorer/src/utils/api/DefaultRpcClient.ts
- sdk/wallet-adapter/wallet-standard/src/chains.ts.rej
> [explorer] - update network list

- RELEASES.md
Update RELEASES.md with Sui `v1.0.0` release
👀
> Update RELEASES.md with Sui `v1.0.0` release

- apps/explorer/src/components/footer/footerLinks.tsx
Change docs link  to https://github.com/MystenLabs/mysten-app-docs/blob/main/mysten-sui-explorer.md 
---
> change docs link

- doc/src/build/snapshot.md
updates snapshot docs with new buckets, a bit more detail on fetching the snapshot
> update snapshot docs with new buckets

- apps/explorer/src/context.ts
- apps/wallet/configs/environment/.env.defaults
> [explorer/wallet-ext] - set default network

- apps/wallet/src/ui/app/pages/home/onramp/useOnrampProviders.ts
> [wallet-ext] - enable supported flag for transak on-ramp

- apps/explorer/src/components/node-map/index.tsx
Label change
locally
---
Node map label
> [explorer] update node map label

- apps/wallet/src/ui/app/pages/home/onramp/useOnrampProviders.ts
> [wallet-ext] - update moonplay flag

- apps/explorer/src/components/GasPriceCard/index.tsx
- apps/explorer/src/components/HomeMetrics/OnTheNetwork.tsx
- apps/explorer/src/components/SuiTokenCard.tsx
- apps/explorer/src/hooks/useSuiCoinData.ts
- apps/explorer/src/pages/home/Home.tsx
Doing some last-minute tweaks before we turn on the Sui token card :)
- Manual testing on all breakpoints
---
N/A
> [explorer] do some style tweaks / remove the percent change / etc.

- apps/core/src/utils/transaction/getGasSummary.ts
- apps/explorer/src/components/GasBreakdown/index.tsx
- apps/explorer/src/components/transactions/ProgTxnBlockCard.tsx
- apps/explorer/src/pages/transaction-result/TransactionData.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/TransactionsCard.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/ObjectChanges.tsx
- apps/wallet/src/ui/app/shared/transaction-summary/cards/ObjectChanges.tsx
- Clean up code after TXN v2 merged
---
> [explorer]: clean up/refactor code

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
- Remove capitalization for contents
- Add flex wrap to wrap better on mobile view
---
> [explorer]: fix scroll bar mobile

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
- Add `word-break: break-all;` 
---
> [explorer]: break all word

- apps/explorer/src/pages/object-result/views/PkgView.tsx
Locally
---
Transactions paginated on package view
> [explorer] paginated package transactions

- apps/wallet/src/ui/app/pages/home/onramp/useOnrampProviders.ts
- Bump moonpay up to the preferred provider 
- add FF so we can turn on/off onramp providers individually as they become stable
---
> [wallet-ext] - add separate FF for onramp providers

- .github/workflows/trigger-builds.yml
Adding more branch patterns to trigger builds
👀
> Adding more branch patterns to trigger builds

- apps/explorer/src/components/TransactionBlocksForAddress/TransactionBlocksForAddress.tsx
- apps/explorer/src/pages/object-result/views/PkgView.tsx
Updated default filter for package view
Locally
---
Updated default filter for package view
> [explorer] default filter for package view

- apps/explorer/src/ui/CoinsStack.tsx
- apps/explorer/src/ui/TransactionBlockCard.tsx
- use `Image` component to render coin images
---
> [Explorer]: Fix coin image

- apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx
- apps/wallet/src/ui/app/pages/home/nfts/index.tsx
Clear  react query caches after sending NFT
https://user-images.githubusercontent.com/126525197/236018956-5f962bbf-ae96-4a02-adac-18555b130759.mov
> Clear  react query caches after sending NFT

- crates/sui-core/src/consensus_adapter.rs
> update tags for consensus adapter

- crates/sui-verifier-transactional-tests/tests/id_leak/infinite_loop.exp
- crates/sui-verifier-transactional-tests/tests/id_leak/infinite_loop.mvir
As in title
```
crates/sui-verifier-transactional-tests$ cargo nextest run -- id_leak/infinite_loop.mvir
```
> [sui-verifier] Additional tests

- crates/sui-benchmark/src/fullnode_reconfig_observer.rs
- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/test_utils.rs
- crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
> use validator display name in metrics reporting

- apps/wallet/src/ui/app/pages/home/onramp/index.tsx
> [wallet-ext] - kick onramp providers to new tab

- apps/wallet/src/ui/app/pages/home/onramp/useOnrampProviders.ts
> [wallet-ext] - move transak to first provider position

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/validator.md
- crates/sui-framework/packages/sui-system/sources/validator.move
- crates/sui-framework/packages/sui-system/tests/rewards_distribution_tests.move
- crates/sui-framework/packages/sui-system/tests/sui_system_tests.move
- crates/sui-protocol-config/src/lib.rs
Change the max commission rate to 20%.
---
> [sui-system] update max commission rate cap

- apps/wallet/src/ui/app/shared/delegated-apy/index.tsx
Fixes edge cases where wallet  APY is not available for inactive validator
> Fixes edge cases where APY is not available for inactive validator

- apps/wallet/src/ui/app/pages/home/onramp/index.tsx
Small adjustment to the onramp logic
---
> [wallet-ext] - clean up onramp logic

- apps/explorer/src/components/validator-map/index.tsx
remove unneeded param from validator map query
locally
---
> [explorer] remove cache param

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-types/src/sui_serde.rs
- crates/sui-types/tests/serde_tests.rs
struct tag serialization should not trim leading zeros
added unit test
> [bug fix] - struct tag serialization should not trim leading zeros

- apps/explorer/src/components/checkpoints/CheckpointsTable.tsx
Calculation doesn't work for ongoing epoch, needs a special case
Locally
---
Fix checkpoint count for ongoing epoch
> [explorer] fix ongoing epoch checkpoint count

- crates/sui-replay/src/replay.rs
Fixes issue due to not being able to find objects at some protocol versions
Regression
---
> fix resolution issue

- nre/config/validator.yaml
> remove json-rpc and reduce max-checkpoints-in-batch

- apps/explorer/src/components/validator-map/ValidatorLocation.tsx
- apps/explorer/src/components/validator-map/index.tsx
- apps/explorer/src/components/validator-map/types.ts
Some minor type changes to seamlessly revisit validator map backend with appropriate caching :)
Locally. Should work with existing & future map endpoint implementation
---
> [explorer] changes for validator map followups

- apps/explorer/src/components/GasPriceCard/index.tsx
| before | after | 
| - | - |
| <img width="294" alt="Screenshot 2023-05-05 at 17 59 43" src="https://user-images.githubusercontent.com/10210143/236494664-de257756-760e-4459-b04e-01d6142c3189.png"> | <img width="294" alt="Screenshot 2023-05-05 at 17 59 26" src="https://user-images.githubusercontent.com/10210143/236494716-d4fe13ff-b3de-464d-8bdf-f8b9b28c111d.png"> |
> explorer: show epoch num in hover tooltip

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
- apps/explorer/src/ui/stories/CoinsStack.stories.tsx
- Add max width to right side content of Inputs card
---
> [explorer]: add max width

- crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql
I found triggers on Epoch table often failed over the past several epochs, adding retrials here
Tested locally to make sure that with retrials the trigger can still work;
It's hard to test when the case when first several trials failed but following ones work.
> indexer: add retrial to epoch view refresh

- crates/sui-protocol-config-macros/src/lib.rs
- crates/sui-surfer/tests/smoke_tests.rs
Formatting nits from https://github.com/MystenLabs/sui/pull/11510
N/A
---
> [nits/chore] fix prot cfg macro  fmt nits

- apps/core/tailwind.config.ts
- apps/explorer/src/components/HomeMetrics/CurrentEpoch.tsx
- apps/explorer/src/pages/epochs/stats/EpochProgress.tsx
- apps/explorer/src/ui/ProgressBar.tsx
- apps/explorer/src/ui/stories/ProgressBar.stories.tsx
- Add glowing progress bar 
- https://www.figma.com/file/kSD0qXCIDZA4KQVNepA5hR/02-Explorer?node-id=95-26657&t=gX7cw0vmupRsveiA-0
---
> [Explorer]: glowing progress bar

- Cargo.lock
- Cargo.toml
- crates/mysten-network/src/codec.rs
- crates/workspace-hack/Cargo.toml
Migrates codecs to the modified anemo codec interface
> Update sui to current anemo

- crates/sui-proxy/src/consumer.rs
- crates/sui-proxy/src/handlers.rs
- crates/sui-proxy/src/middleware.rs
Summary:
* missed the middleware for metrics
* instrument some basic counters for visibility in these layers
Test Plan:
cargo test/build
---
> [sui-proxy/add metrics to middleware]

- apps/core/tailwind.config.ts
- apps/explorer/src/ui/ProgressBar.tsx
current one is a little intense
---
> [explorer] - make glow animation more subtle

- apps/explorer/src/ui/ProgressBar.tsx
> [explorer]: update progress with floor %

- scripts/rotate_snapshots.py
> Fix typo in rotate_snapshots.py

- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-json-rpc/src/governance_api.rs
- crates/sui-json-rpc/src/indexer_api.rs
- crates/sui-storage/src/indexes.rs
- crates/sui-tool/src/db_tool/db_dump.rs
Cherrypick of https://github.com/MystenLabs/sui/pull/11789
Fixes dynamic field pagination/cursor issue: https://github.com/MystenLabs/sui/issues/7686
Manual testing
---
---
> Fix Dynamic Field Cursor Index Bug (#11789)

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/clob.md
- crates/sui-framework/packages/deepbook/sources/clob.move
- crates/sui-framework/packages/deepbook/sources/math.move
- crates/sui-framework/packages/deepbook/tests/clob_tests.move
- enhance overflow check for mathematical calculations
- explain why underflow is permitted code clean in test code
- add test to cover corner case in match_bid
- add test to cover corner case in match_bid
- add test to successfully place a limit order of type POST OR ABORT
- add test to place limit order of type invalid restrictions
- add test to cover ask side in batch cancel order
- add test to get single  order status on bid side
- add test to get level2 book status when time expired
---
> [Deepbook ] Enhancement

- apps/explorer/src/components/Activity/utils.tsx
Looks like this was accidentally changed when doing table pagination work
---
> [explorer] - fix net inflow on epochs table

- Cargo.lock
- Cargo.toml
- crates/sui-rosetta/src/types.rs
- crates/sui-types/src/crypto.rs
- crates/sui-types/src/multisig.rs
- crates/sui-types/src/unit_tests/crypto_tests.rs
- crates/sui-types/src/unit_tests/multisig_tests.rs
- crates/sui/src/keytool.rs
- crates/workspace-hack/Cargo.toml
Closes https://github.com/MystenLabs/sui/issues/10402
Closes https://github.com/MystenLabs/sui/issues/9994
Depends on https://github.com/MystenLabs/fastcrypto/pull/577
Existing tests 
---
> crypto: Use pubkey as bytes

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-open-rpc/src/examples.rs
Adding some of the documentation for dynamic fields apis
```
No example found for method: sui_getLoadedChildObjects
No example found for method: sui_getMoveFunctionArgTypes
No example found for method: sui_getNormalizedMoveFunction
No example found for method: sui_getNormalizedMoveModule
No example found for method: sui_getNormalizedMoveModulesByPackage
No example found for method: sui_getNormalizedMoveStruct
No example found for method: sui_tryMultiGetPastObjects
No example found for method: suix_getStakes
No example found for method: suix_getStakesByIds
No example found for method: suix_resolveNameServiceAddress
No example found for method: suix_resolveNameServiceNames
No example found for method: suix_subscribeEvent
No example found for method: suix_subscribeTransaction
No example …
```
> [docs] dynamic object documentation

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui `v1.2.0` version bump

- crates/transaction-fuzzer/tests/replay_fuzzer.rs
Disable test for now.
Seems to be connecting to flaky FN
---
> disable test

- crates/sui-replay/src/replay.rs
This allows tool work for devnet
manual
---
> fix for devnet

- apps/explorer/src/pages/transaction-result/TransactionData.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/TransactionsCard.tsx
- apps/explorer/tests/transaction.spec.ts
https://mysten.atlassian.net/browse/APPS-885
---
> [explorer]: add e2e tests for Transactions and Inputs Cards

- crates/sui-adapter/src/execution_engine.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-rosetta/src/types.rs
- crates/sui-test-transaction-builder/src/lib.rs
- crates/sui-transaction-builder/src/lib.rs
- crates/sui-types/src/lib.rs
- crates/sui-types/src/transaction.rs
- crates/sui-types/src/unit_tests/messages_tests.rs
- crates/sui/src/fire_drill.rs
- crates/sui/src/validator_commands.rs
- crates/sui/tests/dynamic_committee_tests.rs
- crates/sui/tests/full_node_tests.rs
- crates/sui/tests/reconfiguration_tests.rs
- crates/sui/tests/shared_objects_tests.rs
Change all direct init of the system object CallArg using CallArg constant.
Similar for clock. Non-functional change.
> Clean up system object CallArg

- Cargo.lock
- Cargo.toml
- crates/sui/Cargo.toml
- crates/sui/src/keytool.rs
- crates/sui/src/sui_commands.rs
- crates/sui/src/unit_tests/keytool_tests.rs
- crates/workspace-hack/Cargo.toml
Cherry picking #11822 #11283
---
Extend Keytool to Enable Signing with AWS KMS
> Cherry Pick AWS KMS signing

- external-crates/move/move-bytecode-verifier/src/meter.rs
Fixes wrong assignment
Next steps:
Introduce `Package` and `Transaction` scopes for metering.
Existing
---
> fix meter assignment

- narwhal/primary/src/certificate_fetcher.rs
- narwhal/primary/src/metrics.rs
- narwhal/primary/src/primary.rs
- narwhal/primary/src/synchronizer.rs
- narwhal/primary/src/tests/primary_tests.rs
- narwhal/primary/src/tests/synchronizer_tests.rs
- narwhal/types/src/error.rs
Bake the change in testnet. Should introduce no compatibility issue.
---
> Cherrypick "[Narwhal] deduplicate missing parents in vote requests (#11835)"

- doc/src/build/dev_cheat_sheet.md
> Updating main from doc branch

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/clob.md
- crates/sui-framework/packages/deepbook/sources/clob.move
- crates/sui-framework/packages/deepbook/tests/clob_tests.move
Change min bid id from 0 to 1, leave 0 as invalid order id
---
> [Deepbook] Leave 0 as invalid order id

- apps/wallet/src/background/connections/index.ts
context [here](https://mysten-labs.slack.com/archives/C0539KV6AV7/p1683020616514389)
> wallet-ext: allow UI connections only from same origin

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/custodian.md
- crates/sui-framework/packages/deepbook/sources/custodian.move
Upgrade the logic of query function of account balance
---
> [Deepbook] Upgrade account_balance

- doc/src/build/programming-with-objects/ch2-using-objects.md
- doc/src/build/programming-with-objects/ch3-immutable-objects.md
- doc/src/build/programming-with-objects/ch4-object-wrapping.md
Fixes errors in the code from docs
> Fix errors in the docs

- crates/sui-adapter/src/execution_engine.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/consensus_tests.rs
- crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs
- crates/sui-core/src/unit_tests/transaction_manager_tests.rs
- crates/sui-cost/tests/empirical_transaction_cost.rs
- crates/sui-framework/src/lib.rs
- crates/sui-open-rpc/src/examples.rs
- crates/sui-replay/src/replay.rs
- crates/sui-rosetta/src/operations.rs
- crates/sui-rosetta/src/types.rs
- crates/sui-test-transaction-builder/src/lib.rs
- crates/sui-transaction-builder/src/lib.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/lib.rs
- crates/sui-types/src/programmable_transaction_builder.rs
- crates/sui-types/src/transaction.rs
- crates/sui/src/fire_drill.rs
- crates/sui/src/validator_commands.rs
- crates/sui/tests/dynamic_committee_tests.rs
- crates/sui/tests/protocol_version_tests.rs
- crates/sui/tests/reconfiguration_tests.rs
- crates/test-utils/tests/network_tests.rs
- crates/transaction-fuzzer/src/type_arg_fuzzer.rs
> Rename OBJECT_ID to PACKAGE_ID for framework

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-open-rpc/src/examples.rs
Added examples for RPC API. Changed verbs to match singular subject (the example request) based on agreement with @healthydeve previous suggestion.
Local
---
> Added examples and made verbs singular 

- crates/sui-config/src/genesis.rs
- crates/sui-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Change the decrease rate to actually 10% and period length to 10 epochs.
---
> update default stake subsidy parameters to match testnet

- doc/src/learn/architecture/validators.md
> Fixed link

- .github/workflows/trigger-builds.yml
Modifying branches and tags to trigger builds on branches
👀
> Modifying branches and tags to trigger builds on branches

- doc/src/build/fullnode.md
update pruning docs for fullnodes
> update fullnode pruner docs

- apps/explorer/src/components/network/Network.tsx
- apps/explorer/src/components/validator/StakeButton.tsx
- apps/explorer/src/utils/growthbook.ts
- apps/wallet/src/background/NetworkEnv.ts
- apps/wallet/src/shared/experimentation/features.ts
- apps/wallet/src/ui/app/ApiProvider.ts
This removes feature flags that are fully rolled out.
Ran locally.
---
> [apps] Remove unused feature flags

- apps/core/tailwind.config.ts
- apps/wallet/src/ui/app/pages/home/tokens/TokenIconLink.tsx
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
- apps/wallet/src/ui/app/shared/LargeButton.tsx
- https://mysten.atlassian.net/browse/APPS-824
- FIGMA Link: https://www.figma.com/file/m1wFK3XLrjyfnwtqGXxgJe/01-Components-%3A-Wallet?type=design&node-id=0-1&t=HGqJWcmaMytrwlHv-0
---
> [wallet]: update wallet button

- apps/core/package.json
- apps/core/src/api/SentryRpcClient.ts
- apps/explorer/package.json
- apps/explorer/src/utils/sentry.ts
- apps/wallet/package.json
- apps/wallet/src/shared/sentry.ts
- apps/wallet/src/ui/app/ApiProvider.ts
- pnpm-lock.yaml
> [wallet-ext] Add sentry monitoring for mainnet

- apps/explorer/src/ui/Banner.tsx
https://mysten.atlassian.net/browse/APPS-975
Slack for context: https://mysten-labs.slack.com/archives/C032676BWGN/p1683856189080719
---
> [Explorer]: fix banner overflow

- crates/sui-rosetta/docker/sui-rosetta-local/Dockerfile
- docker/sui-indexer/Dockerfile
- docker/sui-node/Dockerfile
- docker/sui-tools/Dockerfile
This directory now contains the execution-specific crates.
Run actions in CI.
> [docker] Add sui-execution top-level directory

- apps/wallet/src/ui/app/components/explorer-link/Explorer.ts
Point the explorer link to the right environment
> Fix explorer link environment

- crates/sui-core/src/db_checkpoint_handler.rs
- crates/sui-node/src/lib.rs
Add metrics to track the first epoch with missing db snapshot so we can alert on it.
Added unit tests
> Add metrics for db snapshots

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Transaction.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/BalanceChanges.tsx
- apps/explorer/src/ui/CoinsStack.tsx
https://mysten.atlassian.net/browse/APPS-982
- Fix coins overlap with relative positioning
- Update text fonts for Transaction Card
---
> fix coin overlap and transaction texts

- Cargo.lock
- Cargo.toml
- crates/sui-core/Cargo.toml
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/sui-core/src/authority/authority_store_types.rs
- crates/sui-core/src/db_checkpoint_handler.rs
- crates/sui-snapshot/Cargo.toml
- crates/sui-snapshot/src/lib.rs
- crates/sui-snapshot/src/tests.rs
- crates/sui-snapshot/src/writer.rs
- crates/sui-storage/Cargo.toml
- crates/sui-storage/src/object_store/util.rs
- crates/workspace-hack/Cargo.toml
This PR adds the ability to start producing state snapshots in our own storage format. Next PR is going to add the ability to read this format. 
Added some basic sanity tests. Next PR adds more tests.
> StateSnapshot writer for writing state snapshot

- crates/sui-json/src/lib.rs
- crates/sui-json/src/tests.rs
fix incorrect string vec json -> bcs conversion
added unit tests
> [bugfix] - fix incorrect string vec json -> bcs conversion

- apps/core/src/hooks/useFormatCoin.ts
> Truncate name and symbols

- apps/wallet/src/shared/qredo-api.ts
> wallet-ext: initial api client for qredo

- apps/core/src/hooks/useTransactionSummary.ts
- apps/explorer/src/index.css
- apps/explorer/src/pages/transaction-result/TransactionData.tsx
- apps/explorer/src/pages/transaction-result/TransactionView.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/TransactionDetailCard.tsx
- apps/explorer/src/pages/validators/Validators.tsx
- apps/explorer/src/ui/Modal/ImageModal.tsx
Continuation of [11753](https://github.com/MystenLabs/sui/pull/11753), which I closed in order to break up the work. 
- Adds Sender, Executed Epoch, Timestamp, to the transaction page
- Fixes a few styling / layout issues including mobile footer issues
---
> [explorer] - add details to tx page, fix some styling bugs

- dapps/offline-signer-helper/.gitignore
- dapps/offline-signer-helper/index.html
- dapps/offline-signer-helper/package.json
- dapps/offline-signer-helper/postcss.config.cjs
- dapps/offline-signer-helper/src/App.tsx
- dapps/offline-signer-helper/src/index.css
- dapps/offline-signer-helper/src/main.tsx
- dapps/offline-signer-helper/src/vite-env.d.ts
- dapps/offline-signer-helper/tailwind.config.ts
- dapps/offline-signer-helper/tsconfig.json
- dapps/offline-signer-helper/tsconfig.node.json
- dapps/offline-signer-helper/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
add offline signing helper
---
> Add offline signing helper

- Cargo.lock
- crates/sui-faucet/Cargo.toml
- crates/sui-faucet/src/faucet/simple_faucet.rs
Fix for https://mysten.atlassian.net/browse/SUI-1731
locally, and will use staging to bake
---
> [faucet] Adding recursive async call so that faucet auto selects next coin

- apps/wallet/src/background/keyring/Vault.ts
- apps/wallet/src/background/keyring/VaultStorage.ts
- apps/wallet/src/background/keyring/index.ts
- apps/wallet/src/background/qredo/index.ts
- apps/wallet/src/background/qredo/storage.ts
- apps/wallet/src/background/qredo/types.ts
- apps/wallet/src/background/qredo/utils.ts
* adds storage util functions for qredo connections
* keyring now loads qredo accounts from accepted qredo connections
* stores qredo token encrypted in vault
part of APPS-760
> wallet-ext: keyring add support for qredo accounts

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
RT
run with public end point which has rate limiting and verify err msg
---
> indexer easy: better err msg for checkpoing download

- crates/sui-config/src/node.rs
- crates/sui-core/src/test_utils.rs
- crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/batch_transaction_tests.rs
- crates/sui-core/src/unit_tests/gas_tests.rs
- crates/sui-core/src/unit_tests/pay_sui_tests.rs
- crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs
- crates/sui-types/src/transaction.rs
- Fixed sui-core tests with RGP of 1
- Updated tests 
---
> [tests] Fix reference gas price for sui-core tests

- .github/workflows/release.yml
Triggering workflow when a release gets published
> Triggering workflow when a release gets published

- .github/workflows/trigger-builds.yml
Add branch name as part of client payload
👀
> Add branch name as part of client payload

- crates/sui-replay/src/fuzz.rs
> fix fuzz loop

- .changeset/clean-brooms-wink.md
Add missing changeset.
N/A
---
> Add missing changeset

- crates/sui-core/src/transaction_input_checker.rs
Runs tx filter before verifier.
> Fix transaction filter check ordering

- crates/sui-replay/src/fuzz.rs
- crates/sui-replay/src/replay.rs
Small PR to cleanup some of the unwraps
Normal tests.
---
> easy nit: remove unwrap, improve replay error

- apps/wallet/src/ui/app/pages/home/tokens/TokenList.tsx
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
Minor design feedback tweaks
ran locally
---
> [wallet-ext] Token list tweaks

- .github/workflows/release.yml
Removing release publishing trigger for now, since it's not working as expected.
Re-running this from my branch
> Removing release publishing trigger for now

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v1.3.0 version bump

- apps/explorer/src/components/validator-map/index.tsx
- apps/explorer/src/components/validator-map/types.ts
- sdk/typescript/src/types/epochs.ts
Use the correct node count on validator map.
Ran locally.
---
> [explorer] Correct node count

- apps/core/tailwind.config.ts
Change the default line height of text styles.
Previews
---
> [apps] Change default line height

- crates/sui-json-rpc/src/metrics.rs
> remove println

- apps/explorer/src/components/validator-map/index.tsx
Adds a cache bust header to nuke out all of browser caches
Ran locally
---
> [explorer] Add cache bust header

- .github/PULL_REQUEST_TEMPLATE.md
Adding protocol change checkbox to commit template
👀
> Adding protocol change checkbox to commit template

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
Prev. b/c indexer temp. disabled object content population, it had to fetch FN for epoch data, however FN does not keep historic system state data, indexer would always skip old epochs and started from latest.
After recent PRs, indexer now re-populates local object store, thus indexer epoch processing can use the local epoch store now.
Tested locally and make sure that even following a FN that has been updated, indexer populates epoch starting from 0
```
cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --rpc-client-url http://lax-mnt-rpc-12.mainnet.sui.io:9000 --fullnode-sync-worker --rpc-server-url 127.0.0.1 --rpc-server-port 3030 --reset-db
```
---
If your changes are not user-facing and not a breaking change, you can skip the following section. …
> indexer: epoch population with local object store

- Cargo.lock
- Cargo.toml
- crates/anemo-benchmark/Cargo.toml
- crates/anemo-benchmark/README.md
- crates/anemo-benchmark/build.rs
- crates/anemo-benchmark/src/lib.rs
- crates/anemo-benchmark/src/main.rs
- crates/anemo-benchmark/src/server.rs
- crates/workspace-hack/Cargo.toml
Adds a new binary that can be used for manual anemo benchmarking.
Manual use.
> Add synthetic anemo benchmarking tool

- .github/workflows/external.yml
> ci: unblock non-rust builds

- .changeset/twelve-ducks-melt.md
- sdk/kiosk/package.json
Adds prepublish script to pnpm.
--
> [kiosk, sdk] fixes publishing

- apps/core/src/hooks/nameService.ts
- apps/core/src/index.ts
- apps/explorer/package.json
- apps/explorer/src/hooks/useSearch.ts
- apps/explorer/src/pages/address-result/AddressResult.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/TransactionDetailCard.tsx
- apps/explorer/src/ui/InternalLink.tsx
- apps/explorer/src/ui/PageHeader.tsx
- apps/explorer/vite.config.ts
- apps/wallet/src/ui/app/components/AccountAddress.tsx
- apps/wallet/src/ui/app/components/AccountBadge.tsx
- apps/wallet/src/ui/app/components/AccountListItem.tsx
- apps/wallet/src/ui/app/components/AccountSelector.tsx
- apps/wallet/src/ui/app/components/address-input/index.tsx
- apps/wallet/src/ui/app/components/address-input/validation.ts
- apps/wallet/src/ui/app/components/ledger/LedgerAccountRow.tsx
- apps/wallet/src/ui/app/components/menu/content/Account.tsx
- apps/wallet/src/ui/app/components/menu/content/MenuList.tsx
- apps/wallet/src/ui/app/components/receipt-card/TxnAddress.tsx
- apps/wallet/src/ui/app/components/receipt-card/TxnAddressLink.tsx
- apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx
- apps/wallet/src/ui/app/pages/home/nft-transfer/validation.ts
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
- apps/wallet/src/ui/app/pages/home/transfer-coin/SendTokenForm.tsx
- apps/wallet/src/ui/app/pages/home/transfer-coin/validation.ts
- apps/wallet/src/ui/app/shared/ButtonConnectedTo.tsx
- pnpm-lock.yaml
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/index.ts
- sdk/typescript/src/types/name-service.ts
This integrates SuiNS into our TS SDK, wallet and explorer, using the new RPC methods.
Tested locally with mocking.
---
> [explorer][wallet] suins integration

- SECURITY.md
This updates the bug bounty scope to match the official Bug Bounty Program Info: https://immunefi.com/bounty/sui/ which was updated at the end of April
* doc change--no test plan required
---
> [doc] update security bug bounty scope info

- .changeset/two-houses-vanish.md
- sdk/wallet-adapter/wallet-kit/src/ConnectButton.tsx
> wallet-kit: fix key warning for accounts list

- apps/wallet/src/shared/experimentation/features.ts
- apps/wallet/src/ui/app/pages/home/tokens/TokenIconLink.tsx
- apps/wallet/src/ui/app/shared/delegated-apy/index.tsx
- apps/wallet/src/ui/app/staking/delegation-detail/DelegationDetailCard.tsx
- apps/wallet/src/ui/app/staking/home/index.tsx
- apps/wallet/src/ui/app/staking/validators/ValidatorsCard.tsx
- Only show average APY after staking 
- Remove staking feature flag
https://github.com/MystenLabs/sui/assets/126525197/5730d1f6-3262-4b39-8120-70c114bf0c76
---
> Wallet - Only show average APY after staking and remove staking feature flag

- apps/explorer/src/pages/validators/Validators.tsx
- pnpm-lock.yaml
Explorer - make APY, Commission, Last epoch rewards and Voting power sortable
> Explorer - make APY, Commission, Last epoch rewards and Voting power sortable

- narwhal/network/src/client.rs
- narwhal/primary/src/proposer.rs
- narwhal/primary/src/synchronizer.rs
Remove or reduce spamminess of a few log statements.
Clean up comments in proposer.rs a bit.
CI.
---
> [Narwhal] cleanup logs and comments

- apps/explorer/src/pages/transaction-result/transaction-summary/ObjectDisplay.tsx
- apps/wallet/src/ui/app/shared/transaction-summary/cards/CoinStack.tsx
- apps/wallet/src/ui/app/shared/transaction-summary/cards/objectSummary/ObjectChangeDisplay.tsx
> [wallet-ext] - use existing coin icon component

- apps/wallet/src/ui/app/hooks/useGetAllCoins.ts
- apps/wallet/src/ui/app/pages/home/transfer-coin/SendTokenForm.tsx
Fix zero balance bug
https://github.com/TanStack/query/issues/532#issuecomment-636334312
---
> fix zero balance bug

- crates/sui-json-rpc/src/indexer_api.rs
cherry pick of #12239 
test on testnet with and without overriding
> Pick suins default to 1.2

- apps/explorer/src/components/footer/footerLinks.tsx
- doc/src/explore/sui-explorer.md
- doc/src/explore/wallet-browser.md
> Point to new docs site

- .changeset/healthy-chairs-hope.md
- sdk/kiosk/README.md
- sdk/kiosk/src/query/kiosk.ts
- sdk/kiosk/src/utils.ts
- Improves the way `fetchKiosk` works to return results in a more intuitive way. 
- Cleans up the codebase.
- Adds some README content for purchase flow.
---
> [Kiosk SDK] Refactoring of `fetchKiosk`, include `Lock` status

- nre/download_private.sh
- nre/sui_for_node_operators.md
Updates docs to reflect update private security fix folder
---
> Update private security fix docs

- crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
Add a timeout to make it more reliable. I think there was a sleep previously, which got removed accidentally in a refactoring.
cargo simtest
---
> Fix transaction orchestrator test

- apps/wallet/src/shared/qredo-api.ts
> wallet-ext: remove temp prefix from qredo api path

- crates/sui-json-rpc/src/indexer_api.rs
see title.
tested on testnet FN:
to make sure that success lookups still return values
```
curl --location --request POST http://ord-exp-val-01.experiments.sui.io:9000 \
--data-raw '{
"id": 1,
"method": "suix_resolveNameServiceAddress",
"params": ["manos2.sui"]
}'
{"jsonrpc":"2.0","result":"0xe0b97bff42fcef320b5f148db69033b9f689555348b2e90f1da72b0644fa37d0","id":1}%                                                 
curl --location --request POST http://ord-exp-val-01.experiments.sui.io:9000 \
--data-raw '{
"id": 1,
"method": "suix_resolveNameServiceNames",
"params": ["0xe0b97bff42fcef320b5f148db69033b9f689555348b2e90f1da72b0644fa37d0"]
}' …
```
> sui ns: null if valid address or name is not set

- crates/sui-json-rpc/src/indexer_api.rs
> sui ns: null if valid address / name is not set

- Cargo.lock
- Cargo.toml
- crates/sui-archival/Cargo.toml
- crates/sui-archival/src/lib.rs
- crates/sui-archival/src/tests.rs
- crates/sui-archival/src/writer.rs
- crates/sui-config/src/node.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
- crates/sui-e2e-tests/tests/snapshots/snapshot_tests__basic_read_cmd_snapshot_tests.snap
- crates/sui-network/src/state_sync/mod.rs
- crates/sui-network/src/state_sync/tests.rs
- crates/sui-node/Cargo.toml
- crates/sui-node/src/lib.rs
- crates/sui-snapshot/src/lib.rs
- crates/sui-snapshot/src/reader.rs
- crates/sui-snapshot/src/writer.rs
- crates/sui-storage/Cargo.toml
- crates/sui-storage/src/lib.rs
- crates/sui-storage/src/object_store/util.rs
- crates/sui-swarm-config/src/lib.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-swarm-config/src/test_utils.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-types/src/messages_checkpoint.rs
- crates/workspace-hack/Cargo.toml
PR adds archival writer and uploader code. Will add some tests to this soon.
> Add state archival writer and uploader

- sdk/kiosk/package.json
> [Kiosk SDK] Revert back to 0.1.0 version

- nre/download_and_verify_private_binary.sh
- nre/sui_for_node_operators.md
Adds an additional way to download and verify specific binaries
> Add additional download script for binaries and update readme

- crates/sui-proxy/build.rs
- crates/sui-proxy/src/admin.rs
- crates/sui-proxy/src/lib.rs
- crates/sui-proxy/src/main.rs
> sui-proxy: move version const to main.rs

- crates/sui-framework/docs/critbit.md
- crates/sui-framework/packages/deepbook/sources/critbit.move
- crates/sui-framework/packages/deepbook/sources/math.move
- crates/sui-framework/packages/deepbook/tests/critbit_tests.move
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Refactor the test code of critbit tree
Unify the code style of the critbit module
---
---
> [Deepbook] Refactor test of critbit tree

- .github/workflows/sui-protocol-version-monitor.yml
Update `framework/${environment}` branch when the protocol version changes
Going to test this once it lands
> Update `framework/${environment}` branch when the protocol version changes

- apps/explorer/src/components/footer/Footer.tsx
- apps/explorer/src/components/footer/footerLinks.tsx
Add FAQ to explorer footer.
---
> add FAQ to explorer footer

- apps/wallet/src/shared/constants.ts
- apps/wallet/src/ui/app/components/menu/content/MenuList.tsx
- apps/wallet/src/ui/app/components/menu/content/MenuListItem.tsx
> Add wallet FAQ

- crates/sui-e2e-tests/tests/reconfiguration_tests.rs
> Remove unused variable in simtest

- Cargo.lock
- Cargo.toml
- crates/sui-types/src/zk_login_authenticator.rs
- crates/sui/src/keytool.rs
- crates/workspace-hack/Cargo.toml
> chore: update fastcrypto

- crates/sui-framework/docs/staking_pool.md
- crates/sui-framework/docs/validator_set.md
- crates/sui-framework/packages/sui-system/sources/staking_pool.move
- crates/sui-framework/packages/sui-system/sources/validator_set.move
- crates/sui-protocol-config/src/lib.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- `request_withdraw_stake_preactive` was never used so it's removed.
- In `derive_reference_gas_price` we are using voting power, not stake.
---
> [sui-system] remove unused code and correct variable naming

- crates/sui-framework/docs/clob.md
- crates/sui-framework/packages/deepbook/sources/clob.move
- crates/sui-framework/packages/deepbook/sources/math.move
- crates/sui-framework/packages/deepbook/tests/clob_tests.move
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Minor adjustment to function "match_bid_with_quote_quantity" 
Add more test to module clob
---
---
> [Deepbook] Minor adjustments to matching logic when match bid with quote quantity

- doc/src/build/sui-kiosk.md
Minor fix on a link in the kiosk docs.
---
> Fix link in kiosk docs

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui `v1.4.0` version bump

- .github/workflows/docs.yml
Fix CI by using the correct version
CI
---
> [Doc] update crate-ci/typos version in CI

- apps/explorer/src/components/Activity/utils.tsx
- apps/explorer/src/components/Table/HighlightedTableCol.tsx
- apps/explorer/src/components/checkpoints/utils.tsx
- apps/explorer/src/components/top-validators-card/TopValidatorsCard.tsx
- apps/explorer/src/components/transactions/TxCardUtils.tsx
https://mysten.atlassian.net/browse/APPS-974
---
> [explorer]: add hilighted column and update address column

- doc/src/build/move/index.md
Reword a few sentences to make them easier to understand.
CI
---
> [Doc] update intro to sui move

- .changeset/weak-schools-deny.md
- apps/explorer/src/utils/objectUtils.ts
- package.json
- pnpm-lock.yaml
- sdk/suins-toolkit/.eslintrc.js
- sdk/suins-toolkit/.prettierrc.json
- sdk/suins-toolkit/README.md
- sdk/suins-toolkit/package.json
- sdk/suins-toolkit/src/client.ts
- sdk/suins-toolkit/src/index.ts
- sdk/suins-toolkit/src/types/index.ts
- sdk/suins-toolkit/src/types/objects.ts
- sdk/suins-toolkit/src/utils/constants.ts
- sdk/suins-toolkit/src/utils/parser.ts
- sdk/suins-toolkit/src/utils/queries.ts
- sdk/suins-toolkit/tests/app.test.ts
- sdk/suins-toolkit/tsconfig.json
- sdk/suins-toolkit/vitest.config.ts
- sdk/typescript/src/types/objects.ts
> [suins] Migrate SuiNS Toolkit

- crates/sui-core/src/test_authority_clients.rs
Refactor the test implementation to become closer to the actual implementation.
CI
---
> [TestAuthorityClient] execute via TransactionManager

- crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql
Before this change, the TPS was calculated over time window of 10 seconds, which was not able to catch spike of one checkpoint with many tx.
Changing this to be checkpoint based, which will catch a spike checkpoint and also the max consistent TPS we can get.
More details can be found in thread:  https://mysten-labs.slack.com/archives/C032676BWGN/p1685996135421019?thread_ts=1685996115.167529&cid=C032676BWGN
This change has been on production mainnet. 
---
> indexer: update TPS calculation to be checkpoint based

- doc/src/build/event_api.md
> update event doc: removed all system events from the docs and updated outputs

- RELEASES.md
Adding a permanent link to releases
👀
> Adding a permanent link to releases

- apps/explorer/src/components/top-validators-card/TopValidatorsCard.tsx
> [explorer]: add label for ValidatorLink

- crates/sui-benchmark/src/drivers/bench_driver.rs
> Add metric for command per sec

- .github/CODEOWNERS
need access to nested folders, existing rules only impact the apps folder itself
---
> apps codeowners rules

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Transaction.tsx
- Add missing bracket around type args
- https://mysten.atlassian.net/browse/APPS-1239
---
> [Explorer]: update type args

- apps/wallet/src/ui/app/components/AccountSelector.tsx
- apps/wallet/src/ui/app/components/active-coins-card/CoinItem.tsx
- apps/wallet/src/ui/app/components/address-input/index.tsx
- apps/wallet/src/ui/app/components/menu/content/MenuListItem.tsx
- apps/wallet/src/ui/app/components/navigation/index.tsx
- apps/wallet/src/ui/app/components/number-input/index.tsx
- apps/wallet/src/ui/app/components/overlay/index.tsx
- apps/wallet/src/ui/app/components/transactions-card/index.tsx
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
- apps/wallet/src/ui/app/pages/home/transfer-coin/SendTokenForm.tsx
- apps/wallet/src/ui/app/shared/faucet/FaucetRequestButton.tsx
- apps/wallet/src/ui/app/shared/utils/ButtonOrLink.tsx
- apps/wallet/tests/balanceChanges.spec.ts
- apps/wallet/tests/utils/auth.ts
- apps/wallet/tests/utils/localnet.ts
- Add tests for balance changes
- Add `data-testid` for easier test selectors
---
> [Wallet]: add e2e test for balance changes

- doc/src/build/sui-object-display.md
Updated URL for suifrens
Local
---
> Updated url for suifrens

- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/quorum_driver/tests.rs
- crates/sui-core/src/test_authority_clients.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
cherry pick transaction orchestrator timeout related PRs: https://github.com/MystenLabs/sui/pull/12358 , https://github.com/MystenLabs/sui/pull/12372 and https://github.com/MystenLabs/sui/pull/12408
CI
---
cherry pick transaction orchestrator timeout related PRs: https://github.com/MystenLabs/sui/pull/12358 , https://github.com/MystenLabs/sui/pull/12372 and https://github.com/MystenLabs/sui/pull/12408
> Cherry pick timeout commits

- Cargo.lock
- crates/sui-core/src/quorum_driver/reconfig_observer.rs
- crates/sui-e2e-tests/tests/reconfiguration_tests.rs
- crates/sui-node/src/handle.rs
- crates/sui-node/src/lib.rs
- crates/sui-proc-macros/Cargo.toml
- crates/sui-proc-macros/src/lib.rs
- crates/sui-simulator/Cargo.toml
- crates/sui-simulator/src/lib.rs
- crates/test-utils/src/authority.rs
- crates/test-utils/src/network.rs
- crates/typed-store/Cargo.toml
- scripts/simtest/cargo-simtest
@longbowlu for some reason my previous attempt at this did not work, even though I remember staring at a memory profile showing that I had fixed it.
> Fix memory leak in simtests, detect future leaks automatically

- external-crates/move/tools/move-bytecode-utils/src/layout.rs
Updates to layout calculation
Current tests
---
> Updates to Move layout calculation

- crates/sui-framework/docs/clob_v2.md
- crates/sui-framework/docs/custodian_v2.md
- crates/sui-framework/packages/deepbook/sources/clob_v2.move
- crates/sui-framework/packages/deepbook/sources/critbit.move
- crates/sui-framework/packages/deepbook/sources/custodian_v2.move
- crates/sui-framework/packages/deepbook/sources/math.move
- crates/sui-framework/packages/deepbook/tests/clob_tests.move
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Add client-defined order id to the fields of order
Add original_quantity to the fields of order to record initial quantity of order
Add owner address to fileds of account_cap to enable parallel use of funds
Minor adjustment to query api
Abort create_account and create_pool in module clob
---
---------
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please …
> [Deepbook] Introduce new module of clob and custodian

- Cargo.lock
- Cargo.toml
- crates/sui-metric-checker/Cargo.toml
- crates/sui-metric-checker/README.md
- crates/sui-metric-checker/example/config.yaml
- crates/sui-metric-checker/src/lib.rs
- crates/sui-metric-checker/src/main.rs
- crates/sui-metric-checker/src/query.rs
- crates/workspace-hack/Cargo.toml
> Cherry-pick sui-metric-checker crate

- .github/workflows/release.yml
Trigger binaries build when release gets published
👀
> Trigger binaries build when release gets published

- crates/typed-store/src/rocks/mod.rs
> cherrypick PR 12453: use proper options

- crates/sui-config/data/fullnode-template-with-path.yaml
- crates/sui-config/data/fullnode-template.yaml
- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-tool/src/db_tool/mod.rs
- doc/src/build/fullnode.md
- nre/config/validator.yaml
remove point delete method from the pruner
---
> [pruner] remove point delete option

- apps/explorer/src/components/Layout/index.tsx
https://mysten.atlassian.net/browse/APPS-1266
---
> [Explorer]: update toast

- apps/core/src/utils/transaction/getObjectChangeLabel.ts
- apps/explorer/src/components/Layout/index.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/BalanceChanges.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/ObjectChanges.tsx
- apps/explorer/src/ui/Divider.tsx
https://mysten.atlassian.net/browse/APPS-1257
---
> [Explorer]: update object to type

- apps/explorer/src/pages/validators/Validators.tsx
> fix APY sorting bug

- crates/sui-adapter-transactional-tests/tests/size_limits/deleted_id_limits_tests.exp
- crates/sui-adapter-transactional-tests/tests/size_limits/event_limits_tests.exp
- crates/sui-adapter-transactional-tests/tests/size_limits/move_object_size_limit.exp
- crates/sui-adapter-transactional-tests/tests/size_limits/new_id_limits_tests.exp
- crates/sui-adapter-transactional-tests/tests/size_limits/object_runtime_limits.exp
- crates/sui-adapter-transactional-tests/tests/size_limits/transfered_id_limits_tests.exp
- crates/sui-adapter-transactional-tests/tests/size_limits/vector_len_limits.exp
- crates/sui-types/src/gas.rs
- crates/sui-types/src/gas_model/gas_v2.rs
Actually enable rounding
current tests
---
> Enable rounding for gas

- apps/explorer/src/pages/transaction-result/Events.tsx
- apps/explorer/src/pages/transaction-result/TransactionView.tsx
- apps/explorer/src/ui/InternalLink.tsx
https://mysten.atlassian.net/browse/APPS-1238
---
> [Explorer]: update events

- crates/sui-surfer/src/lib.rs
- crates/sui-surfer/tests/move_building_blocks/sources/objects.move
Add a few cases, including unwrap (but not re-wrap), and create-and-wrap.
CI
---
> Add a few more functions to move_building_blocks

- Cargo.lock
- crates/sui-archival/src/lib.rs
- crates/sui-archival/src/reader.rs
- crates/sui-storage/Cargo.toml
- crates/sui-storage/src/blob.rs
- crates/sui-storage/src/object_store/mod.rs
- crates/sui-tool/Cargo.toml
- crates/sui-tool/src/commands.rs
- crates/sui-tool/src/lib.rs
By passing in the remote store config, a node operator can choose to manually sync the node from archive.
Executed on testnet fullnodes, and found it to be working as expected.
> Add sui tool to sync node from an archive

- apps/explorer/src/components/GasPriceCard/index.tsx
- apps/explorer/src/ui/ListboxSelect.tsx
* fix overflowing price figures
* change color of selected epochs check mark
| - | - |
| <img width="466" alt="Screenshot 2023-06-15 at 13 20 46" src="https://github.com/MystenLabs/sui/assets/10210143/915ae0d4-644f-42f3-a175-10bb6801faa3"> | <img width="466" alt="Screenshot 2023-06-15 at 13 20 30" src="https://github.com/MystenLabs/sui/assets/10210143/172be6fe-2c51-4012-b65f-f2c00007375c"> |
| <img width="311" alt="Screenshot 2023-06-15 at 13 23 27" src="https://github.com/MystenLabs/sui/assets/10210143/8a09f2ef-4f59-4236-acaf-61ac7ca15ba6"> | <img width="292" alt="Screenshot 2023-06-15 at 13 22 54" src="https://github.com/MystenLabs/sui/assets/10210143/7716203b-de84-4304-8082-75cff8839ec5"> |
Manual testing
---
If your changes are not user-facing and not a breaking …
> explorer: gas price graph improvements

- apps/explorer/src/pages/transaction-result/Events.tsx
- apps/explorer/src/pages/transaction-result/Signatures.tsx
- apps/explorer/src/pages/transaction-result/TransactionView.tsx
- apps/explorer/src/ui/DescriptionList.tsx
https://mysten.atlassian.net/browse/APPS-1309
Update spacing and alignment on Signature tab
---
> [Explorer]: update signatures tab styling

- apps/wallet/src/manifest/manifest.json
- apps/wallet/src/ui/app/components/nft-display/NftImage.tsx
- apps/wallet/src/ui/app/components/nft-display/index.tsx
- apps/wallet/src/ui/app/hooks/useResolveVideo.ts
- apps/wallet/src/ui/app/pages/home/nft-details/index.tsx
> [wallet] video object support

- apps/explorer/src/pages/transaction-result/Events.tsx
> [Explorer]: update alignment

- .github/CODEOWNERS
> Add SDK Reviewers

- crates/sui-framework/docs/table_vec.md
- crates/sui-framework/packages/sui-framework/sources/table_vec.move
- crates/sui-protocol-config/src/lib.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Added drop function to the  table_vec.move
It would be useful to have such functionality. 
Otherwise it takes too much time to destroy `TableVec`
> Added drop function to the  table_vec.move

- apps/wallet/src/ui/styles/utils/index.scss
https://mysten.atlassian.net/browse/APPS-1201
---
> [Wallet]: remove extra padding on padding bottom

- doc/src/learn/cryptography/sui-wallet-specs.md
Updates docs related to the `keytool import` CLI command. 
No need for tests. 
---
Updates docs related to the `keytool import` CLI command.
> Update docs for the CLI and keytool import command

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui `v1.5.0` version bump

- sui-execution/cut/README.md
Adding a brief readme to explain this internal tool.
:eyes:
---
> [sui-execution][EASY] README

- .github/workflows/e2e.yml
- apps/wallet/playwright.config.ts
- apps/wallet/src/ui/app/components/receipt-card/index.tsx
- apps/wallet/src/ui/app/pages/home/tokens/TokenIconLink.tsx
- apps/wallet/src/ui/app/staking/delegation-detail/DelegationDetailCard.tsx
- apps/wallet/src/ui/app/staking/home/StakedCard.tsx
- apps/wallet/src/ui/app/staking/stake/StakeForm.tsx
- apps/wallet/src/ui/app/staking/validators/SelectValidatorCard.tsx
- apps/wallet/tests/balanceChanges.spec.ts
- apps/wallet/tests/staking.spec.ts
> [wallet]: E2e staking changes spec

- apps/explorer/src/pages/transaction-result/Signatures.tsx
- sdk/typescript/CHANGELOG.md
- sdk/typescript/src/cryptography/multisig.ts
- sdk/typescript/src/cryptography/signature.ts
- sdk/typescript/src/utils/verify.ts
- sdk/typescript/test/e2e/raw-signer.test.ts
> crypto: decode multisig for explorer

- apps/wallet/src/ui/app/wallet/forgot-password-page/index.tsx
https://github.com/MystenLabs/sui/assets/10210143/8178aaa3-7df1-4a50-b13d-81ae766b9dc6
closes APPS-1088
Manual testing
---
> wallet-ext: fix forgot password flow

- doc/src/learn/tokenomics/gas-in-sui.md
Change gas docs and release notes for gas changes
no really
---
> Gas doc revised

- .github/workflows/rust.yml
- narwhal/primary/src/proposer.rs
Fixing release notes check cmd
👀
> Fixing release notes check cmd

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/lib.rs
Fix clippy errors on methods not found
---
> chore: fix feature flags

- apps/wallet/src/ui/app/shared/ButtonConnectedTo.tsx
- apps/wallet/src/ui/app/shared/dapp-status/index.tsx
https://mysten.atlassian.net/browse/APPS-1305
---
> [wallet]: truncate long texts on header

- doc/src/build/event_api.md
We don't support this today.
---
> [doc] remove recipient from the event filter doc

- apps/wallet/src/ui/app/components/nft-display/NftImage.tsx
- apps/wallet/src/ui/app/pages/home/nft-details/index.tsx
- apps/wallet/src/ui/app/shared/collapse/index.tsx
- apps/wallet/src/ui/app/shared/text/index.tsx
- https://mysten.atlassian.net/browse/APPS-979
- Update `Collapse` component
---
> [wallet]: Update collapsible panel component and styling

- .github/workflows/rust.yml
Fixing checking for release notes
👀
> Fixing checking for release notes

- dapps/multisig-toolkit/index.html
- dapps/multisig-toolkit/package.json
- dapps/multisig-toolkit/src/components/header.tsx
- dapps/multisig-toolkit/src/components/ui/card.tsx
- dapps/multisig-toolkit/src/index.css
- dapps/multisig-toolkit/src/main.tsx
- dapps/multisig-toolkit/src/routes/index.tsx
- dapps/multisig-toolkit/src/routes/offline-signer.tsx
- dapps/multisig-toolkit/src/routes/signature-analyzer.tsx
- dapps/multisig-toolkit/tailwind.config.ts
- pnpm-lock.yaml
> Add signature analyzer to multisig toolkit

- dapps/kiosk-cli/.gitignore
- dapps/kiosk-cli/README.md
- dapps/kiosk-cli/index.js
- dapps/kiosk-cli/package.json
- pnpm-lock.yaml
Adds the `kiosk-cli` demo application to the `dapps/` folder.
Extensively tested on testnet.
- none
> [dapps] adds kiosk-cli dapp

- crates/sui-replay/src/data_fetcher.rs
Fixes an issue in local transaction replay where we weren't properly paging epoch change events.
Before:
```
Protocol Version  |                Epoch Change TX               |      Epoch Range     |   Checkpoint Range
---------------------------------------------------------------------------------------------------------------
1           | 7CuBm1AnLgkBMB6GiEn5d3RizznF5LbawjJTs8A5dcXF |     0     -    0     |     0     -   9768
4           | 8eBMXpC8Np7RNDwwiGwSmeev1cSoc7w3fPXdikhH7RZo |     1     -    8     |    9769   -  621931
5           | 4WmGHKKACJhh93CvCgL8QHKnZLjVcwim95T9nBjX19tn |     9     -    9     |   621932  -  699408
6           | EZL7zPeRtYwH321n19k6RwSpaQiRUsMk7zR5hV3NihLn |     10    -    16    |   699409  - 1256189
7           | …
```
> [transaction-replay] Handle paging of epoch change events

- .github/workflows/ci-docs.yml
Temporary fix for crate docs, had to remove sui-benchmark for now
Tested on fork
---
> Temporary fix for crate docs

- Cargo.lock
- crates/sui-source-validation-service/Cargo.toml
- crates/sui-source-validation-service/src/lib.rs
- crates/workspace-hack/Cargo.toml
See title. https://github.com/MystenLabs/sui/pull/12633#discussion_r1239831668 for context
Covered by existing test
> move: source service uses axum

- crates/x/src/lint.rs
> x: add lint for actixs or warp webframeworks

- crates/sui-core/src/authority/authority_store_pruner.rs
As title says, these tests fail on macos due too misaligned pointer exception.
Existing tests
> Move pprof based tests out into a non-macos enabled mod

- apps/explorer/src/components/GasBreakdown/index.tsx
- update Gas & Storage Fee section
- https://mysten.atlassian.net/browse/APPS-1231
---
> [explorer]: update Gas & Storage Fee section

- turbo.json
> Fix turbo caching

- apps/wallet/src/ui/app/shared/dapp-status/index.tsx
| -- | -- |
| <img width="359" alt="Screenshot 2023-06-26 at 12 54 06" src="https://github.com/MystenLabs/sui/assets/10210143/0e1bfece-c388-453d-9e5e-c4098c8e0e91"> | <img width="359" alt="Screenshot 2023-06-26 at 13 04 31" src="https://github.com/MystenLabs/sui/assets/10210143/44e45214-0d67-4ea1-8a89-c602f5affb36"> |
manual testing
---
> wallet-ext: fix dapp status button width/alignment

- apps/explorer/src/components/validator/ValidatorStats.tsx
Fix validator  details card height 
Before 
After
> Fix validator details card height

- crates/sui-json-rpc/src/api/read.rs
- crates/sui-open-rpc/spec/openrpc.json
Explain what the chain identifier is in its docs.
:eyes:
> [RPC][EASY] Clarify docs for getChainIdentifier

- apps/explorer/src/components/transactions/TransactionsForAddress.tsx
- apps/explorer/src/hooks/useGetTransactionBlocks.ts
Removing as these don't seem to be used.
---
> [exlporer] Remove balance change for query txns

- apps/wallet/src/ui/app/pages/home/nft-details/index.tsx
Adds FF for Kiosk links in wallet. 
Based on the readiness of our marketplace partners, we may want to link directly to a marketplace instead of the directory 
---
> [wallet-ext] - feature flag marketplace links

- crates/sui-config/src/node.rs
- crates/sui-tool/src/commands.rs
- crates/sui-tool/src/db_tool/db_dump.rs
- crates/sui-tool/src/db_tool/mod.rs
Add db tool commands to trigger object and checkpoint pruning.
> Add pruning db tool commands

- .github/dependabot.yml
Disable non-security dependabot updates for npm packages
---
> Dependabot change for npm packages

- apps/explorer/package.json
- apps/explorer/src/components/OwnedCoins/OwnedCoinView.tsx
- apps/explorer/src/pages/transaction-result/Events.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/ObjectChanges.tsx
- apps/explorer/src/ui/DisclosureBox.tsx
- apps/explorer/src/ui/TransactionBlockCard.tsx
- pnpm-lock.yaml
Removes usage of headless disclosure in the explorer.
---
> [explorer] Remove headless disclosure

- crates/sui-e2e-tests/tests/dynamic_committee_tests.rs
- crates/sui-test-transaction-builder/src/lib.rs
- crates/test-utils/src/network.rs
> Use TestCluster in dynamic_committee_tests

- apps/explorer/src/components/header/Header.tsx
- apps/explorer/src/components/search/Search.tsx
- apps/explorer/src/ui/Search.tsx
https://mysten.atlassian.net/browse/APPS-1362
---
> [Explorer]: sticky header and updated search box

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/lib.rs
- crates/sui-core/src/verify_indexes.rs
- crates/sui-node/src/lib.rs
- crates/sui-storage/src/indexes.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
This just adds a function for verifying coin and owner indexes, further work will need to be done to use it.
---
> indexes: add verification logic for coin and owner indexes

- crates/sui-types/src/object.rs
This just adds some helpers for querying balance totals for all Coin/Balance<T> in an object.
---
> types: add functions for getting balances for Coin<T> for all T

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-e2e-tests/tests/full_node_tests.rs
- crates/sui-e2e-tests/tests/shared_objects_tests.rs
- crates/sui-types/src/messages_grpc.rs
> Cherrypick #12717 into release 1.3.0

- crates/sui-core/src/authority.rs
- crates/sui-e2e-tests/tests/full_node_tests.rs
- crates/sui-storage/src/indexes.rs
- crates/sui-tool/src/db_tool/index_search.rs
> cherry pick 12669 to 1.4

- crates/sui-core/src/authority.rs
- crates/sui-e2e-tests/tests/full_node_tests.rs
- crates/sui-storage/src/indexes.rs
- crates/sui-tool/src/db_tool/index_search.rs
cherry pick https://github.com/MystenLabs/sui/pull/12669/ to 1.3
---
> cherry pick 12669 to 1.3

- apps/wallet/src/ui/app/components/DAppInfoCard.tsx
- apps/wallet/src/ui/app/components/SummaryCard.tsx
- apps/wallet/src/ui/app/components/WalletListSelect.tsx
- apps/wallet/src/ui/app/components/user-approve-container/UserApproveContainer.module.scss
- apps/wallet/src/ui/app/components/user-approve-container/index.tsx
- apps/wallet/src/ui/app/pages/approval-request/SignMessageRequest.tsx
- apps/wallet/src/ui/app/pages/approval-request/transaction-request/SummaryCard.tsx
- apps/wallet/src/ui/app/pages/site-connect/SiteConnectPage.module.scss
- apps/wallet/src/ui/app/pages/site-connect/index.tsx
- apps/wallet/src/ui/app/shared/heading/index.tsx
- apps/wallet/src/ui/styles/themes/dark.scss
- apps/wallet/src/ui/styles/themes/light.scss
- apps/wallet/src/ui/styles/variables/shadows.scss
based on https://www.figma.com/file/xu2VnyPAuruNi74UQzGigW/02-Wallet?type=design&node-id=8612-197309&mode=design&t=P5CLQQ15WK69MwI6-0
Locally
---
> [wallet-ext] sign message modal updates

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
bumping sui release to 1.3.2
copying https://github.com/MystenLabs/sui/pull/12327
> bump release to 1.3.2

- apps/wallet/src/ui/app/components/filters-tags/Filters.module.scss
hiding the scrollbar here 
locally
---
> [wallet-ext] hide app filters scrollbar

- crates/x/src/lint.rs
> x: turn on direct duplicate dependency lint

- apps/explorer/src/pages/transaction-result/TransactionView.tsx
> [Explorer]: add error boundary

- apps/wallet/src/ui/app/components/transactions-card/TxnIcon.tsx
- apps/wallet/src/ui/app/components/transactions-card/index.tsx
Show receive icon in wallet activity
> show receive icon in wallet activity

- narwhal/primary/src/proposer.rs
This can help us debug issues in validators, when header creation rate has a lot of jitters.
CI
---
> [Narwhal] add more logging to proposer

- apps/explorer/src/pages/transaction-result/Signatures.tsx
- sdk/typescript/src/cryptography/utils.ts
> explorer: fix signatures view

- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
- sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
- sui-execution/v0/sui-move-natives/src/object_runtime/object_store.rs
- The effective owner map was used in an early version of the previous PR (#12055) and was not properly removed
- Ran existing tests
---
> [move] Remove dead code from MVCC support

- sui-execution/README.md
Internal documentation for working with `sui-execution`
:eyes:
> [sui-execution] README

- .changeset/pretty-geese-confess.md
- package.json
- pnpm-lock.yaml
- sdk/typescript/package.json
add explicit dependency on events package
fixes #12714 
---
> [ts-sdk] add explicit dependency on events package

- doc/src/build/snapshot.md
> clarify aws snapshot docs

- apps/wallet/src/ui/app/components/address-input/index.tsx
- apps/wallet/src/ui/app/components/alert/index.tsx
- apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx
https://mysten.atlassian.net/browse/APPS-1366
---
> [wallet]: UI polish for sending NFT

- crates/sui-core/src/authority_aggregator.rs
as title
---
remove lengthy logs in authority aggregator for past investigations
> remove lengthy logs in authority aggregator for past investigations

- crates/sui-core/src/db_checkpoint_handler.rs
The current workflow of uploading db checkpoint only uploads in sequence i.e. it would wait forever if there could be gaps in epoch snapshot on the remote storage. This is not a requirement and more often, we really want to upload latest epochs and don't care if older epoch snapshots are there or not.
This PR now makes it such that if there is a db checkpoint which is present local but not on remote, it will upload it. Besides, it also improves how garbage collection runs by making it not dependent on upload.
Added uni tests
> Improve db checkpoint handling

- apps/wallet/src/ui/app/components/navigation/index.tsx
- Extra scroll bar issue https://mysten-labs.slack.com/archives/C0393DWJD7X/p1688075782029939
---
> [wallet]: remove extra scrollbar

- sdk/suins-toolkit/tests/app.test.ts
> remove flaky test

- crates/sui-indexer/src/store/pg_indexer_store.rs
Duplicate digests would happen when tx sender also has their own as recipients.
testing on address `0x0000000000000000000000000000000000000000000000000000000000000000`
```
--data-raw '{
"id": 1,
"method": "suix_queryTransactionBlocks",
"params": [
{
"filter": {
"FromOrToAddress": {"addr": "0x0000000000000000000000000000000000000000000000000000000000000000"}
}
},
null,
5,
false
]
}' | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   984  100   667  100   317   1978    940 --:--:-- --:--:-- --:--:--  2972
{
"result": {
"data": [
{
"digest": …
```
> indexer: de-dup fromOrToAddress digests

- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/consensus_handler.rs
- Avoid logging for every certificate broadcast in authority aggregator, to reduce noise.
- Add more logging to help debug checkpoint and consensus issues.
CI
---
> Adjust debug logging

- crates/sui-core/src/verify_indexes.rs
`fn object` actually returns dead objects.
---
Use live object iter in index verification
> use live object iter in index verification

- apps/wallet/tests/staking.spec.ts
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/transaction_manager.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-e2e-tests/tests/full_node_tests.rs
- crates/sui-types/src/messages_grpc.rs
Avoids issues in devnet fullnodes.
CI.
---
> Pick two fixes into temporary 1.5

- apps/wallet/src/ui/app/components/filters-tags/index.tsx
- apps/wallet/src/ui/app/pages/home/apps/index.tsx
- If the selection is beyond the scroll bar, we will automatically scroll to the tab
---
> [wallet]: Scroll to previously selected tab on APPS page

- crates/sui-core/src/consensus_handler.rs
Avoid writing forked data to storage when there are problems that prevent a validator from parsing a transaction.
n/a
---
---
> Cherrypick #12810 to 1.4

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v1.6.0 version bump

- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/typed-store/src/rocks/mod.rs
extends periodic compaction functionality to SST files of cfs affected by effects pruning
> periodic compaction for effects

- crates/sui-json-rpc/src/logger.rs
- crates/sui-json-rpc/src/transaction_execution_api.rs
1. don't log success queries and user error queries
2. log queries (success + failed) when it takes longer than the threshold to finish.
CI
---
Log slow queries. Don't log success queries or user input errors.
> log slow queries. Don't log success queries or user input errors.

- apps/wallet/src/ui/app/components/filters-tags/index.tsx
- apps/wallet/src/ui/app/components/navigation/Navigation.module.scss
- apps/wallet/src/ui/app/components/navigation/index.tsx
- apps/wallet/src/ui/app/pages/home/apps/index.tsx
https://mysten.atlassian.net/browse/APPS-1391
- Update border radius
- Make pills scrollable to the edges
- Add margins to first and last elements in the list
---
> [wallet]: update APPS page scrollable area

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
Slack for context: https://mysten-labs.slack.com/archives/C03RN2241LP/p1688415096186709
https://mysten.atlassian.net/browse/APPS-1395
---
> [Explorer]: add bignumber support for input

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
Downgrading to sui v1.5.0 since we need to re-cut the branch
👀
> Downgrading to sui v1.5.0

- crates/sui-source-validation-service/src/lib.rs
- crates/sui-source-validation-service/tests/tests.rs
Eagerly reads and hydrates source code on server start. Doing this eagerly is reasonable right now since source is small (we might opt for gzip later too):
```
244K    sui-framework/packages/deepbook/sources
72K    sui-framework/packages/move-stdlib/sources
348K    sui-framework/packages/sui-framework/sources
240K    sui-framework/packages/sui-system/sources
```
The type is set up with `Option` to allow hydrating source on first request too, but I didn't want to go that route because then we need to implemented a writer lock and seems pretty overkill given scope right now.
---
For fun I looked at the local latency difference before/after this PR. This isn't really meaningful on a local setup, but I've got the tooling set up with `vegeta` for testing eventual deployment so figured to look …
> move: source service eagerly hydrates modules in memory

- Cargo.lock
- Cargo.toml
- crates/sui-json-rpc/src/error.rs
- crates/sui-json/src/lib.rs
- crates/sui-oracle/Cargo.toml
- crates/sui-oracle/README.md
- crates/sui-oracle/src/config.rs
- crates/sui-oracle/src/lib.rs
- crates/sui-oracle/src/main.rs
- crates/sui-oracle/src/metrics.rs
- crates/sui-types/src/quorum_driver_types.rs
- crates/sui/src/client_commands.rs
- crates/workspace-hack/Cargo.toml
- docker/sui-tools/Dockerfile
This PR implements the off chain part of an oracle Proof of Concept. 
Tested in different networks.
---
This PR implements the off chain part of an oracle Proof of Concept.
> Reference Oracle Implementation

- pnpm-workspace.yaml
> ignore faucet package in workspace config

- crates/sui-core/src/checkpoints/metrics.rs
as title
eyes
---
Remove unused checkpoint metrics
> Remove unused checkpoint metrics

- crates/sui-core/src/transaction_orchestrator.rs
Remove tx from pending logs
---
Remove tx from pending logs
> Remove tx from pending logs

- crates/sui-core/src/transaction_orchestrator.rs
> [cherrypick 12889] remove tx from pending logs

- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
- crates/sui-node/src/lib.rs
Help fix fullnodes with a backlog in pending_tx_log.
---
> Cherrypick #12887 into 1.4

- apps/core/tailwind.config.ts
- apps/explorer/package.json
- apps/explorer/src/components/Activity/TransactionsActivityTable.tsx
- apps/explorer/src/components/Activity/index.tsx
- apps/explorer/src/ui/DropdownMenu.tsx
- apps/explorer/src/ui/Toggle.tsx
- apps/explorer/src/ui/stories/DropdownMenu.stories.tsx
- apps/explorer/src/ui/stories/Toggle.stories.tsx
- pnpm-lock.yaml
* allow user to filter out system transactions (enabled by default)
* currently only enabled for mainnet and local (API doesn't support TransactionKind filtering on devnet and testnet yet)
| -- | -- |
| <img width="711" alt="Screenshot 2023-07-03 at 13 35 58" src="https://github.com/MystenLabs/sui/assets/10210143/cfb1adb1-51e1-4912-932f-b8f7e71f7b0f"> | <img width="711" alt="Screenshot 2023-07-03 at 13 36 15" src="https://github.com/MystenLabs/sui/assets/10210143/685d466c-2850-43c4-8fcb-97a9b58b7623"> |
| - | <img width="711" alt="Screenshot 2023-07-03 at 13 36 29" src="https://github.com/MystenLabs/sui/assets/10210143/4f8ac4b1-0943-4a87-af79-6a1bf8c14ab1"> |
| - | <img width="711" alt="Screenshot 2023-07-03 at 13 36 24" …
> explorer: filter system transactions

- crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql
- crates/sui-indexer/migrations/2023-03-20-042226_system_state/up.sql
See title, change real time TPS to be checkpoint based for consistency with peak TPS, also refactor peak TPS query for better readability.
- real time TPS: test locally & on devnet by creating testing views and make sure the numbers roughly match with the current formula
- peak TPS: test on devnet by creating a testing view and make sure the numbers match existing view definition
---
> indexer: consistent formula for real time TPS and peak TPS

- sdk/typescript/src/builder/TransactionBlock.ts
This changes Error message on TransactionBlock.ts when invalid objects are used as invalid.
> [ts-sdk] fix error message on TransactionBlock.ts

- sdk/typescript/api/package.json
- sdk/typescript/package.json
> fix client export

- apps/explorer/src/ui/PlayPause.tsx
- apps/explorer/src/ui/stories/PlayPause.stories.tsx
- Add animation for playpause
---
> [Explorer]: update playpause animation

- narwhal/primary/src/primary.rs
- narwhal/primary/src/synchronizer.rs
- narwhal/primary/src/tests/certificate_fetcher_tests.rs
- narwhal/primary/src/tests/certifier_tests.rs
- narwhal/primary/src/tests/primary_tests.rs
- narwhal/primary/src/tests/synchronizer_tests.rs
- narwhal/storage/src/certificate_store.rs
Use more efficient batched existence checks for certificates.
Also, remove DAG from Synchronizer.
CI
---
> [Narwhal] add batched existence check to certificate store

- apps/explorer/src/components/TransactionBlocksForAddress/TransactionBlocksForAddress.tsx
fixing the logic
locally. /object/0xbf1431324a4a6eadd70e0ac6c5a16f36492f255ed4d011978b2cf34ad738efe6?network=mainnet
---
> [explorer] back pagination fix

- crates/sui-indexer/src/store/pg_indexer_store.rs
> indexer: increase cache time for network metrics by 10x

- crates/sui-json-rpc/src/lib.rs
> json-rpc: add request id to span

- crates/sui-source-validation-service/src/lib.rs
- crates/sui-source-validation-service/tests/tests.rs
Server recognizes a version header `X-Sui-Source-Validation-Version`. The policy is:
- Reject the request if an unsupported version is specified (currently only the version `0.0.1` is recognized).
- Accept the request if a recognized version is specified
- Accept the request if _**no**_ version is specified. I went with this default, but perhaps this is too permissive, and we should enforce specifying the version header. Thoughts?
Follow up of https://github.com/MystenLabs/sui/pull/12832#pullrequestreview-1512601489. Note that I found we use slightly unexpected header conventions like:
```
--header 'client-sdk-type: typescript' \
--header 'client-sdk-version: 0.36.0' \
--header 'client-target-api-version: 1.5.0' \
```
instead of the more conventional (?) `X-Camel-Kebab-Case`. So based on …
> move: version header for source service API

- crates/sui-indexer/benches/indexer_benchmark.rs
- crates/sui-indexer/src/errors.rs
- crates/sui-indexer/src/main.rs
- crates/sui-indexer/src/models/addresses.rs
- crates/sui-indexer/src/models/packages.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/test_utils.rs
> indexer: properly call sync db functions from async code

- sdk/typescript/src/client/index.ts
- sdk/typescript/src/client/network.ts
> [ts-sdk] add getFullnodeUrl helper to client

- crates/sui-indexer/benches/indexer_benchmark.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/main.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/test_utils.rs
- crates/sui-indexer/tests/integration_tests.rs
> indexer: configure db connection and statement timeouts

- apps/explorer/src/components/AccountCardGraph.tsx
* Total -> Number of accounts that have sent or received transactions since network genesis## Test Plan 
* Total Active -> Total number of accounts that have signed transactions since network genesis
* Daily Active -> Number of accounts that have sent or received transactions in the last epoch
https://github.com/MystenLabs/sui/assets/10210143/7de75da2-0a2a-4ff6-8d9c-1764aeb5058a
---
> explorer: accounts graph card update tooltips

- apps/core/tailwind.config.ts
- apps/explorer/src/components/AccountCardGraph.tsx
- apps/explorer/src/components/HomeMetrics/CurrentEpoch.tsx
- apps/explorer/src/components/HomeMetrics/OnTheNetwork.tsx
- apps/explorer/src/components/SuiTokenCard.tsx
- apps/explorer/src/components/TransactionsCardGraph.tsx
- apps/explorer/src/ui/Card.tsx
- apps/explorer/src/ui/Divider.tsx
- apps/explorer/src/ui/Stats.tsx
- Minor changes
- https://mysten.atlassian.net/browse/APPS-1436
---
> [Explorer]: Home page updates

- .github/workflows/release-notes-monitor.yml
- .github/workflows/tag.yml
Release Monitor Workflow work
[Testing via my branch](https://github.com/MystenLabs/sui/actions/runs/5556887258)
See https://mysten-labs.slack.com/archives/C05GQ6T4W1M channel for messages
> Release Monitor Workflow work

- .github/workflows/release-notes-monitor.yml
Fixing saving outputs
[Testing via my branch](https://github.com/MystenLabs/sui/actions/runs/5557320957/jobs/10150957227)
> Fixing saving outputs

- crates/sui-archival/src/lib.rs
- crates/sui-archival/src/reader.rs
- crates/sui-archival/src/tests.rs
- crates/sui-core/src/authority.rs
- crates/sui-network/src/state_sync/tests.rs
- crates/sui-node/src/lib.rs
- crates/sui-tool/src/lib.rs
Cherry pick of the existing PR to add metrics
> cherry-pick: Add metrics for archive readers

- apps/explorer/src/components/Activity/index.tsx
> Remove filter by ProgrammableTransaction from TransactionKind

- sui-execution/latest/sui-adapter/src/execution_engine.rs
This is a refactor of the execute transaction code to prepare for shared object deletion work that will call the refactored functions.
---
> refactor execute transaction for shared object deletion

- doc/src/build/fullnode.md
- doc/src/learn/exchange-integration-guide.md
Docs update
Updated the suggested storage requirement for Sui Full Nodes to 4 TB SSD.
> update fn storage spec

- apps/wallet/src/shared/analytics/ampli/index.ts
- apps/wallet/src/ui/app/pages/home/nfts/index.tsx
> [wallet-ext] hide asset tracking

- crates/sui-core/src/authority/authority_store_pruner.rs
switch effects pruning to point delete method for vast majority of cfs.
During first iteration of pruning mysten-1 validator OOMed.
Looks like range delete structures do not respect pinned block cache limits.
Comparable point delete run doesn't have the same problem. Affected cfs don't use iterators so implication of tombstones should be minimal.
Note that it still requires smart compaction to reclaim the space
> [effects pruner] switch to point delete

- crates/mysten-network/src/multiaddr.rs
- crates/sui/src/sui_commands.rs
- crates/sui/tests/cli_tests.rs
cherry-pick https://github.com/MystenLabs/sui/pull/12530 to 1.5 so I unbreak ci
> write genesis config files with hostname:port (#12530)

- apps/wallet/src/ui/app/components/navigation/Navigation.module.scss
fixing a minor bug where the overlay component is showing up below the nav module
Locally
---
> [wallet-ext] fix navigation and overlay layering

- apps/explorer/src/components/validator-map/WorldMap.tsx
https://mysten.atlassian.net/browse/APPS-1456
---
> [Explorer]: center map on home page

- apps/explorer/src/components/top-packages/TopPackagesCard.tsx
- apps/explorer/src/components/top-packages/TopPackagesTable.tsx
- apps/explorer/src/ui/Tabs.tsx
> [explorer] popular packages tooltip

- crates/sui-source-validation-service/src/lib.rs
- crates/sui-source-validation-service/src/main.rs
Some logging improvements as I'm working on Dockerfile for deployments
N/A non-functional change
---
> move: source service logging

- crates/sui-source-validation-service/Cargo.toml
As in title
Stacked on https://github.com/MystenLabs/sui/pull/13065
N/A semantics-preserving
---
> move: source service uses Cargo workspaces

- doc/src/build/fullnode.md
Add blobs for pruning and archive fallback
> Update fullnode documentation to include pruning and archive fallback

- apps/wallet/.storybook/main.js
> [wallet-ext] - fix broken storybook

- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-tool/src/lib.rs
- narwhal/config/src/lib.rs
- narwhal/config/tests/snapshots/config_tests__parameters.snap
- narwhal/config/tests/snapshots/config_tests__parameters_import.snap
- narwhal/network/src/p2p.rs
- narwhal/network/src/traits.rs
- narwhal/test-utils/src/lib.rs
- narwhal/types/build.rs
- narwhal/types/src/worker.rs
- narwhal/worker/src/batch_fetcher.rs
- narwhal/worker/src/handlers.rs
- narwhal/worker/src/metrics.rs
- narwhal/worker/src/tests/handlers_tests.rs
- narwhal/worker/src/worker.rs
`request_batches` endpoint have replaced all existing usages of `request_batch`.
CI
---
> [Narwhal] cleanup request_batch endpoint

- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
- sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
> Don't add new ids if they are also delete

- apps/explorer/src/components/TransactionsCardGraph.tsx
https://mysten.atlassian.net/browse/APPS-1482
---
> [Explorer]: add last epoch total transactions

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v1.7.0 version bump

- crates/sui-json-rpc/src/error.rs
As title
eyes
---
make SuiError::UsreInputError client error
> make SuiError::UsreInputError client error

- apps/core/src/hooks/useTransactionSummary.ts
- apps/core/src/utils/transaction/getBalanceChangeSummary.ts
- apps/explorer/src/pages/transaction-result/TransactionData.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/BalanceChanges.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/index.tsx
- apps/explorer/src/ui/Banner.tsx
- apps/wallet/src/ui/app/components/alert/index.tsx
- apps/wallet/src/ui/app/components/receipt-card/index.tsx
- apps/wallet/src/ui/app/components/transactions-card/index.tsx
- apps/wallet/src/ui/app/pages/approval-request/transaction-request/index.tsx
- apps/wallet/src/ui/app/shared/transaction-summary/cards/BalanceChanges.tsx
- apps/wallet/tests/balanceChanges.spec.ts
> Add unrecognized token flag

- .github/workflows/release-notes-monitor.yml
Add Ronny to release notes monitor process
👀
> Add Ronny to release notes monitor process

- .github/workflows/release-notes-monitor.yml
> Add @ to Ronny handle

- sdk/docs/pages/typescript-sdk/connect.mdx
- sdk/docs/pages/typescript-sdk/cryptography/keypairs.mdx
- sdk/docs/pages/typescript-sdk/index.mdx
- sdk/docs/pages/typescript-sdk/transaction-building/_meta.json
- sdk/docs/pages/typescript-sdk/transaction-building/basics.mdx
- sdk/docs/pages/typescript-sdk/transaction-building/gas.mdx
- sdk/docs/pages/typescript-sdk/transaction-building/offline.mdx
- sdk/docs/pages/typescript-sdk/transaction-building/sponsored-transactions.mdx
> [sdk-docs] Add transaction build and keypair docs

- dapps/multisig-toolkit/src/routes/multisig-address.tsx
> update imports in multisig tool

- sdk/docs/pages/typescript-sdk/cryptography/_meta.json
- sdk/docs/pages/typescript-sdk/cryptography/keypairs.mdx
- sdk/docs/pages/typescript-sdk/cryptography/mnemonics.mdx
- sdk/docs/pages/typescript-sdk/cryptography/multisig.mdx
> [docs] add docs for multisig support in the typescript SDK

- crates/sui-config/src/node.rs
- crates/sui-json-rpc/src/indexer_api.rs
- crates/sui-node/src/lib.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
> Limit number of active subscriptions to protect the full node

- crates/sui-config/src/node.rs
- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-json-rpc/src/indexer_api.rs
- crates/sui-node/src/lib.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
> [Cherry-pick] Limit number of active subscriptions to protect the full node (#13145)

- apps/wallet/package.json
- apps/wallet/src/shared/validation.ts
- apps/wallet/src/ui/app/components/accounts/ImportPrivateKeyForm.tsx
- apps/wallet/src/ui/app/components/menu/content/ImportPrivateKey.tsx
- apps/wallet/src/ui/app/helpers/validation/privateKeyValidation.ts
- apps/wallet/src/ui/app/pages/accounts/ImportPrivateKeyPage.tsx
- apps/wallet/src/ui/app/staking/stake/utils/validation.ts
- pnpm-lock.yaml
This PR builds the new `Import Private Key` UI screen that's accessible from the "Add Account" page. I re-built the form using react-hook-form (eventually we'll move off of Formik completely) and updated Yup since we were using a super old version of it that wasn't compatible with react-hook-form.  One note is that we're punting on the password input style masking because there isn't a standardized way to implement this in Chrome without writing a bunch of extra JavaScript.
(I'm still working on creating proper form abstractions, that will likely come in a follow-up PR with the next set of forms we're building)
Figma: https://www.figma.com/file/dCHKynDnLAAQyoYSU6G16Y/02-Enoki-Shared?node-id=1%3A7791&mode=dev
- Manually tested the new flow, form submission, navigation, etc.
- Tested that …
> [wallet-ext] build new "Import Private Key" screen

- crates/sui-sdk/src/apis.rs
- crates/sui-sdk/src/lib.rs
Add API comments for the Rust SDK. 
Only comments added. 
---
> [rust-sdk] Add doc comments for the Rust SDK

- crates/sui-replay/src/lib.rs
Replay batches of TXs specified in file
Manual
---
> replay batch from file

- crates/sui-core/src/transaction_orchestrator.rs
add an env var to skip loading pending tx log
---
add an env var to skip loading pending tx log
> add an env var to skip loading pending tx log

- crates/sui-types/src/temporary_store.rs
When executing advance epoch transaction, if we are also publishing a new system package, we would be calling the execution engine twice, and hence calling `save_loaded_child_objects` twice. We cannot just override loaded_child_objects otherwise it will override the results of the first execution.
In general, we cannot assume that we are only calling the execution engine once.
Once we depend on this in #13175, tests will cover it.
---
> Fix a bug in loaded child objects

- apps/wallet/src/ui/app/components/sui-apps/index.tsx
- apps/wallet/src/ui/app/pages/home/bullshark-quests-notification/index.tsx
> [wallet-ext] update quests blog post link

- doc/src/learn/architecture/consensus.md
Fixing the references to the Bullshark paper.
> Fixing consensus documentation

- .changeset/itchy-phones-promise.md
- .changeset/sweet-ligers-deny.md
- sdk/docs/pages/typescript-sdk/index.mdx
> [ts-sdk] add changeset for SDK refactor

- doc/src/build/sui-transfer-policy.md
- doc/src/navconfig.json
> Add Transfer Policy topic

- sdk/docs/pages/typescript-sdk/index.mdx
Adding content around migration concerns from earlier SDK versions
Local
---
> Added migration info

- Cargo.lock
- Cargo.toml
- crates/sui-config/src/node.rs
- crates/sui-kvstore/Cargo.toml
- crates/sui-kvstore/src/client.rs
- crates/sui-kvstore/src/lib.rs
- crates/sui-kvstore/src/writer.rs
- crates/sui-node/Cargo.toml
- crates/sui-node/src/lib.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-types/src/digests.rs
- crates/workspace-hack/Cargo.toml
initial implementation of writer pipeline to key value store
it's a draft. Contains most of the boilerplate code and checkpoint tailer.
Key value store itself is mocked for now.
Test coverage and kv dynamodb backend will be added shortly
> [kv store] initial implementation

- Cargo.lock
- Cargo.toml
- crates/sui-config/src/node.rs
- crates/sui-kvstore/Cargo.toml
- crates/sui-kvstore/src/client.rs
- crates/sui-kvstore/src/lib.rs
- crates/sui-kvstore/src/writer.rs
- crates/sui-node/Cargo.toml
- crates/sui-node/src/lib.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-types/src/digests.rs
- crates/workspace-hack/Cargo.toml
> [kv store] initial implementation (#13136)

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/metrics.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
title.
local run and experiment on Vultr and aws
---
> indexer: fix cp counter & add tx commit latency

- .changeset/gentle-mugs-hang.md
- sdk/typescript/src/cryptography/keypair.ts
- sdk/wallet-adapter/site/tsconfig.json
> [ts-sdk] Update signature methods on keypairs to return bytes as a base64 encoded strings

- sdk/docs/pages/cryptography/keypairs.mdx
- sdk/docs/pages/hello-sui.mdx
- sdk/docs/theme.config.jsx
- sdk/typescript/README.md
- sdk/typescript/package.json
> Add link to typescript SDK docs

- apps/core/tailwind.config.ts
- apps/explorer/src/components/Layout/PageLayout.tsx
- apps/explorer/src/pages/address-result/AddressResult.tsx
- apps/explorer/src/pages/home/Home.tsx
- apps/explorer/src/pages/transaction-result/TransactionResult.tsx
- apps/explorer/src/ui/PageHeader.tsx
- apps/explorer/src/ui/StatusIcon.tsx
https://mysten.atlassian.net/browse/APPS-1517
---
> [Explorer]: add gradient header for address page

- apps/explorer/src/components/Layout/PageLayout.tsx
- apps/explorer/src/pages/address-result/AddressResult.tsx
> [Explorer]: add loading to address and fix resolving to Suins name

- docker/sui-node/Dockerfile
Adding ca-cert installation to a dockerfile to resolve issue reported by validators upon upgrading to v1.6.2
---
> adding ca certs

- Cargo.lock
- crates/sui-core/src/authority.rs
- crates/sui-json-rpc/src/indexer_api.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-node/src/lib.rs
- crates/sui-storage/src/bin/http_kv_tool.rs
- crates/sui-transactional-test-runner/Cargo.toml
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/digests.rs
> Use TransactionKeyValueStore in query_events

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> version bump 1.6.3

- crates/sui-core/src/authority.rs
- crates/sui-storage/src/bin/http_kv_tool.rs
- crates/sui-storage/src/http_key_value_store.rs
- crates/sui-storage/src/key_value_store.rs
- crates/sui-storage/tests/key_value_tests.rs
Support for fetching both summaries and contents by sequence or digest
> Complete checkpoint fetching code

- apps/core/src/hooks/useElementHeight.ts
- apps/core/src/index.ts
- apps/core/tailwind.config.ts
- apps/explorer/src/components/Layout/PageLayout.tsx
> [Explorer]: Fix text wrapping on banner

- apps/explorer/src/components/transactions/ProgTxnBlockCard.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/TransactionsCard.tsx
- apps/explorer/src/ui/TransactionBlockCard.tsx
- apps/explorer/tests/transaction.spec.ts
> [Explorer]: initial collapse for Input and Txn cards

- apps/explorer/src/components/top-packages/TopPackagesTable.tsx
Slack for ref https://mysten-labs.slack.com/archives/C032676BWGN/p1691094864154589
https://mysten.atlassian.net/browse/APPS-1537
Current
Updated
---
> [Explorer]: Right align the Txn count column

- crates/sui-faucet/src/main.rs
- crates/sui-replay/src/replay.rs
Changing faucet request_status to get
Faucet change is a change in requests type
---
> [Faucet] Changing faucet request_status to GET

- apps/explorer/src/ui/Tabs.tsx
> [Explorer]: add bottom border for tab list

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v1.8.0 version bump

- apps/core/src/api/SentryRpcClient.ts
Ignore known non-performant methods from RPC data collection.
---
> Ignore some methods in RPC

- apps/core/src/hooks/useTransactionSummary.ts
- apps/explorer/src/pages/transaction-result/transaction-summary/UpgradedSystemPackages.tsx
- apps/explorer/src/pages/transaction-result/transaction-summary/index.tsx
Show upgraded system packages in a transaction [APPS-1465](https://mysten.atlassian.net/browse/APPS-1465)
> Show package upgrade in transaction

- doc/src/build/custom-upgrade-policy.md
- doc/src/build/prog-trans-ts-sdk.md
- sdk/docs/pages/transaction-building/basics.mdx
> [docs] cleanup a few references to the deprecated JsonRpcProvider

- sdk/docs/package.json
> [ci] stop trying to publish sdk docs to npm

- crates/sui-indexer/src/store/pg_indexer_store.rs
[indexer] Chunk commits for huge checkpoints/batch that otherwise would fail.
tested in testnet prod.
---
[indexer] Chunk commits for huge checkpoints/batch.
> [indexer] Chunk commits for huge checkpoints/batch.

- dapps/multisig-toolkit/src/components/header.tsx
- dapps/multisig-toolkit/src/routes/combine-sigs.tsx
- dapps/multisig-toolkit/src/routes/index.tsx
Add MultiSig Combined Signature to multisig toolkit
With love and care, create a musig addres and signatures from the individual addresses.
Add to form, and hit 'submit'
Should see results like:
---
> Add Combined MultiSig tool to MultiSig toolkit

- crates/sui-graphql-rpc/schema/draft_schema.graphql
- crates/sui-graphql-rpc/src/lib.rs
Fixes typos and non-compliances in schema definition
Also replaced the `U64` type with `BigInt` for `gasPrice`
Schema validation util
---
> [graphql/rpc] fix draft schema nits

- crates/sui-core/src/authority/authority_store.rs
- crates/sui-snapshot/src/reader.rs
This PR ensures that we no longer need to access iterator which uses BufRead across await point.
Existing tests
> Ensure iterator is not used across await

- docker/sui-source-service/Dockerfile
- make sure git is installed
- include config.toml with the container
Container builds and can run the server successfully
---
> [source-service][docker] deployment improvements

- Cargo.lock
- Cargo.toml
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-config/src/node.rs
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-indexer/src/fetcher.rs
- crates/sui-indexer/src/framework/fetcher.rs
- crates/sui-indexer/src/framework/interface.rs
- crates/sui-indexer/src/framework/mod.rs
- crates/sui-indexer/src/framework/runner.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/interface.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/models/checkpoints.rs
- crates/sui-indexer/src/models/events.rs
- crates/sui-indexer/src/models/objects.rs
- crates/sui-indexer/src/models/packages.rs
- crates/sui-indexer/src/types.rs
- crates/sui-node/Cargo.toml
- crates/sui-node/src/lib.rs
- crates/sui-rest-api/Cargo.toml
- crates/sui-rest-api/src/checkpoints.rs
- crates/sui-rest-api/src/client.rs
- crates/sui-rest-api/src/headers.rs
- crates/sui-rest-api/src/lib.rs
- crates/sui-rest-api/src/objects.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-types/src/transaction.rs
> indexer: indexing framework with experimental node rest api

- apps/explorer/src/components/Layout/PageLayout.tsx
> [explorer] Add feature flag override for the banner

- .github/workflows/release.yml
Add macos build to releases
https://github.com/MystenLabs/sui/actions/runs/5837121779/job/15832052364
> Add macos binaries to releases

- crates/sui-graphql-rpc/src/lib.rs
- crates/sui-graphql-rpc/src/server/data_provider.rs
- crates/sui-graphql-rpc/src/types/object.rs
- crates/sui-graphql-rpc/src/types/owner.rs
- crates/sui-graphql-rpc/src/types/query.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Implements changes to `Owner` introduced in https://github.com/MystenLabs/sui/pull/13375
Manual, Snapshot
---
> [graphql/rpc] impl owner refactor

- apps/explorer/src/components/TransactionsCardGraph.tsx
> [explorer] add optional chaining for epoch metrics

- Cargo.lock
- crates/sui-graphql-rpc/Cargo.toml
- crates/sui-graphql-rpc/src/commands.rs
- crates/sui-graphql-rpc/src/main.rs
- crates/sui-graphql-rpc/src/server/data_provider.rs
- crates/sui-graphql-rpc/src/types/address.rs
- crates/sui-graphql-rpc/src/types/balance.rs
- crates/sui-graphql-rpc/src/types/base64.rs
- crates/sui-graphql-rpc/src/types/big_int.rs
- crates/sui-graphql-rpc/src/types/date_time.rs
- crates/sui-graphql-rpc/src/types/object.rs
- crates/sui-graphql-rpc/src/types/owner.rs
- crates/sui-graphql-rpc/src/types/query.rs
- crates/sui-graphql-rpc/src/types/sui_address.rs
- crates/sui-graphql-rpc/src/types/transaction_block.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Some unit tests
Picks up Owner changes
Support negative BigInt
Typos
Snapshot, unit
---
> [graphql/rpc] cleanups

- sdk/docs/pages/typescript/index.mdx
- sdk/docs/pages/typescript/sui-client.mdx
- sdk/docs/pages/typescript/transaction-building/gas.mdx
> Fix SDK docs

- .changeset/nine-bags-run.md
- .eslintrc.js
- apps/wallet/configs/ts/tsconfig.common.json
- apps/wallet/package.json
- apps/wallet/src/background/accounts/zk/ZkAccount.ts
- apps/wallet/src/background/accounts/zk/utils.ts
- pnpm-lock.yaml
- sdk/zklogin/README.md
- sdk/zklogin/package.json
- sdk/zklogin/src/address.ts
- sdk/zklogin/src/bcs.ts
- sdk/zklogin/src/index.ts
- sdk/zklogin/src/nonce.ts
- sdk/zklogin/src/poseidon.ts
- sdk/zklogin/src/utils.ts
- sdk/zklogin/tsconfig.json
> zklogin ts sdk

- .changeset/tough-garlics-deny.md
- pnpm-lock.yaml
- sdk/zklogin/package.json
- sdk/zklogin/src/address.ts
- sdk/zklogin/tsconfig.esm.json
- sdk/zklogin/tsconfig.json
> Migrate zklogin to internal build tooling

- crates/sui-core/src/authority.rs
- crates/sui-types/src/coin.rs
- crates/sui-types/src/temporary_store.rs
> Remove a few unused functions in temp store/coin

- crates/sui-indexer/src/models/checkpoints.rs
- crates/sui-indexer/src/utils.rs
As title.
cargo 
---
Remove unused functions
> remove unused util functions

- crates/sui/src/client_commands.rs
- doc/src/build/dev_cheat_sheet.md
- doc/src/learn/cryptography/sui-offline-signing.md
Pushed to the wrong branch.
CI
---
> [Doc] fix flag name in docs and comments

- .changeset/stupid-seas-boil.md
- sdk/zklogin/src/index.ts
- sdk/zklogin/src/poseidon.ts
- sdk/zklogin/src/utils.ts
> Polishing zkLogin SDK

- crates/sui-source-validation-service/Cargo.toml
Follow up of https://github.com/MystenLabs/sui/pull/13376#discussion_r1295685790
👀 
---
> move: simplify dev only deps for source service (easy)

- crates/sui-graphql-rpc/src/types/sui_address.rs
`0x` prefix for adress values
Gui
---
> [graphql/rpc] nit: fix address output

- .changeset/eighty-hotels-agree.md
- sdk/zklogin/tsconfig.json
Fix generated ZK types so that they're correct.
---
> Fix zk types

- crates/sui-network/src/state_sync/mod.rs
Only log state sync failure to sync a checkpoint if peers contain the checkpoint the node is trying to sync. Otherwise sync is handled by archive fallback
Existing tests
> Make state sync not log state sync failures if peers have no data

- .changeset/dry-candles-drive.md
- sdk/zklogin/src/utils.ts
> [zklogin SDK] Change function signature of genAddressSeed

- Cargo.lock
- Cargo.toml
- crates/workspace-hack/Cargo.toml
- deny.toml
- narwhal/consensus/Cargo.toml
- narwhal/consensus/benches/process_certificates.rs
> cargo-deny: deny copyleft licenses

- crates/sui-graphql-rpc/src/types/base64.rs
- crates/sui-graphql-rpc/src/types/sui_address.rs
Some unit tests for scalar types
---
> [graphql] unit tests for scalar types

- crates/sui-sdk/README.md
Update the advanced example section to point to the right file. 
No need to test. 
---
> [rust_sdk_examples] Fix path to example file in README

- apps/core/src/hooks/useLocalStorage.ts
- apps/core/src/index.ts
- apps/explorer/src/components/OwnedObjects/index.tsx
> [explorer]: add localstorage cache for view mode

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> [version] 1.9.0 version bump

- crates/sui-types/src/temporary_store.rs
This PR makes two changes:
1. Refactor `check_sui_conserved`. This function had a lot of redundant code, where it iterates through writes and deletes, and for each of them it operates on the input and output. Instead of duplicating code, this PR introduces a function that returns the list of inputs/outputs for the function to operate on. The operation then becomes much simpler.
2. Instead of reading DB for input objects, this PR reads from the metadata that's already in the temporary store, avoiding unnecessary DB reads.
CI
---
> Refactor check_sui_conserved

- .changeset/plenty-shirts-wash.md
- apps/wallet/src/background/accounts/zk/ZkAccount.ts
- apps/wallet/src/background/accounts/zk/utils.ts
- sdk/zklogin/src/address.ts
- sdk/zklogin/src/utils.ts
* rename pin to salt
* update salt service api and path
* update proofs server url path
* fix nonce to include the flag of the public key
closes APPS-1558
---
> wallet-ext: zk api update

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
> indexer: be defensive about duplicate object commits

- .changeset/silver-shrimps-retire.md
- sdk/zklogin/src/nonce.ts
* include ephemeral public key flag
---
> zklogin-sdk: update nonce calculation

- Cargo.lock
- Cargo.toml
- crates/sui-storage/src/object_store/mod.rs
- crates/sui-tls/src/acceptor.rs
- crates/sui-tls/src/certgen.rs
- crates/sui-tls/src/verifier.rs
- crates/workspace-hack/Cargo.toml
- deny.toml
- external-crates/move/move-ir-compiler/move-ir-to-bytecode/Cargo.toml
- narwhal/node/Cargo.toml
- narwhal/node/src/generate_format.rs
- narwhal/node/src/main.rs
This updates a number of dependencies in order to fix some advisories, as well as temporarily ignores some advisories in order to unblock CI while we fix them.
---
> fix a number of advisories

- sui-execution/src/suivm.rs
Pushed a change to sui-execution without updating suivm. Fixing the build.
---
> Fix suivm build

- crates/sui/src/zklogin_commands_util.rs
Use a different demo address. 
---
> fix: use another default address

- .github/workflows/rust.yml
Disabled CI that is no longer needed. 
---
> chore: disable Rosetta validation

- doc/src/build/install.md
update Sui binaries installation docs with instructions on how to upgrade the binaries.
NA
---
Docs: add Sui binaries upgrade instructions
> Docs: add Sui binaries upgrade instructions

- .changeset/gorgeous-wombats-kiss.md
- sdk/typescript/src/client/http-transport.ts
- sdk/typescript/src/rpc/websocket-client.ts
> [ts-sdk] fix defaults not being applied correctly in websocket client

- crates/sui-indexer/src/framework/builder.rs
- crates/sui-indexer/src/framework/mod.rs
- crates/sui-indexer/src/lib.rs
> indexer: add ergonomic IndexerBuilder

- apps/core/src/hooks/useElementDimensions.ts
- apps/core/src/index.ts
- apps/core/tailwind.config.ts
- apps/explorer/src/components/Activity/TransactionsActivityTable.tsx
- apps/explorer/src/components/Layout/PageLayout.tsx
- apps/explorer/src/components/OwnedCoins/CoinIcon.tsx
- apps/explorer/src/components/OwnedCoins/CoinItem.tsx
- apps/explorer/src/components/OwnedCoins/OwnedCoinView.tsx
- apps/explorer/src/components/OwnedCoins/OwnedCoinsPanel.tsx
- apps/explorer/src/components/OwnedCoins/index.tsx
- apps/explorer/src/components/OwnedObjects/ListView.tsx
- apps/explorer/src/components/OwnedObjects/index.tsx
- apps/explorer/src/components/top-packages/TopPackagesTable.tsx
- apps/explorer/src/components/transactions/TransactionsForAddress.tsx
- apps/explorer/src/pages/address-result/AddressResult.tsx
- apps/explorer/src/pages/transaction-result/TransactionView.tsx
- apps/explorer/src/ui/SplitPanes.tsx
- apps/explorer/src/ui/TableCard.tsx
Vertical panels for Address page
https://mysten.atlassian.net/browse/APPS-1575
---
> [Explorer]: Address vertical panel

- apps/explorer/src/pages/transaction-result/TransactionData.tsx
https://mysten.atlassian.net/browse/APPS-1576
Minor fixes for TXN page mobile view
---
> [Explorer]: update TXN page mobile view

- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
Explained in the comment. Some child objects are deleted without having an entry in the child object effects. We need to account for them, otherwise we may incorrectly mark deleted object as unwrapped_then_deleted.
I need to look into how to write PT to uncover this. Fixing this asap to make sure no bugs are shipped.
---
> Properly mark deleted child object as modified

- apps/core/tailwind.config.ts
- apps/explorer/src/components/OwnedCoins/OwnedCoinView.tsx
- apps/explorer/src/components/OwnedCoins/OwnedCoinsPanel.tsx
- apps/explorer/src/components/OwnedObjects/index.tsx
- Default open panel for Sui coin
- https://mysten.atlassian.net/browse/APPS-1606
---
> [Explorer]: default open for SUI coin

- crates/sui-faucet/src/faucet/mod.rs
> faucet: allow --batch-enabled flag to take [true, false]

- sdk/docs/pages/typescript/index.mdx
- sdk/docs/pages/typescript/install.mdx
> [docs] fix installation instructions to not install as dev dependency

- crates/sui-benchmark/src/options.rs
> stress: allow some boolean flags to take [true, false]

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_22.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_22.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_22.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- sui-execution/latest/sui-move-natives/src/event.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
> Cherry pick 13554

- crates/sui-rest-api/src/checkpoints.rs
> Cherry pick 13555 to 1.8

- apps/wallet/src/ui/app/components/accounts/AccountListItem.tsx
Fixes an issue where clicking lock / unlock would also select an accoujnt.
---
> [wallet-ext] - fix issue where clicking lock / unlock selects an account

- crates/sui/src/client_commands.rs
Sort enums alphabetically.
No tests needed.
---
> [cli] sort enums alphabetically in the cli client

- crates/sui-graphql-rpc/src/server/data_provider.rs
- crates/sui-graphql-rpc/src/server/sui_sdk_data_provider.rs
- crates/sui-graphql-rpc/src/types/checkpoint.rs
- crates/sui-graphql-rpc/src/types/committee_member.rs
- crates/sui-graphql-rpc/src/types/end_of_epoch_data.rs
- crates/sui-graphql-rpc/src/types/query.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
add checkpoint connection function and glue it to Query
---
> [graphql] add checkpoint connection function and glue it to Query

- apps/wallet/src/ui/app/components/accounts/EditNickname.tsx
- apps/wallet/src/ui/app/components/accounts/NicknameDialog.tsx
- apps/wallet/src/ui/app/index.tsx
- apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx
- apps/wallet/src/ui/app/shared/Dialog.tsx
> [wallet-ext] nickname improvements

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-rest-api/src/checkpoints.rs
- crates/sui-rest-api/src/lib.rs
> indexer,rest: include input as well as output objects for handlers

- apps/explorer/src/pages/address-result/AddressResult.tsx
- apps/explorer/src/pages/transaction-result/TransactionView.tsx
- apps/explorer/src/ui/SplitPanes.tsx
- Save split panes position for txn page
---
> [Explorer]: add caching for splitpanes txn

- crates/sui-indexer/migrations/2023-03-05-165748_transaction_index/up.sql
- crates/sui-indexer/migrations/2023-03-20-041133_epoch/down.sql
- crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql
- crates/sui-indexer/src/store/pg_indexer_store.rs
> Cherry pick 13536

- sdk/typescript/src/cryptography/intent.ts
- sdk/typescript/src/cryptography/keypair.ts
- sdk/typescript/src/cryptography/multisig.ts
- sdk/typescript/src/cryptography/signature.ts
- sdk/typescript/src/cryptography/utils.ts
- sdk/typescript/src/multisig/publickey.ts
- sdk/typescript/test/e2e/multisig.test.ts
- sdk/typescript/test/unit/cryptography/intent.test.ts
- sdk/typescript/test/unit/cryptography/keypair.test.ts
- sdk/typescript/test/unit/cryptography/multisig.publickey.test.ts
- sdk/typescript/test/unit/cryptography/multisig.test.ts
- sdk/typescript/test/unit/cryptography/publickey.test.ts
- sdk/typescript/test/unit/cryptography/signature.test.ts
- sdk/typescript/test/unit/cryptography/utils.test.ts
As part of the audit, added scenario and unit tests for multisig and cryptography.
Updated the TS-SDK according to the audit findings.
Fixed issues:
- Medium-1;
- Low-1;
- Info-4;
- Info-5;
- Info-6;
- Info-7;
- Info-8.
---
> [ts-sdk] Patch from Blaize Security auditing team for multisig and cryptography

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v1.10.0 version bump

- crates/sui-core/src/authority_aggregator.rs
HashSet on Object is unnecessarily expensive as it computes the hash each time.
Use ObjectID instead.
CI
---
> Avoid HashSet<Object>

- crates/sui-json-rpc/src/error.rs
In authority aggregator we treat ObjectNotFound and DependentPackageNotFound as retryable, but they have special treatment than other retryable errors. When we return the error to users, whether these two types of error is retryable depends. In this PR we choose a safer route, always treat them as non-retryable. We also sort the errors by total stake, to make clients see the most prominent errors first.
---
In RPC response processing, treat ObjectNotFound and DependentPackageNotFound as non-retryable
> treat ObjectNotFound and DependentPackageNotFound as non-retryable

- crates/sui-json-rpc/src/error.rs
cherry pick https://github.com/MystenLabs/sui/pull/13608 to release 1.9
---
> Cherry pick 13608 to 1.9

- crates/sui-core/src/authority.rs
> remove unused function read_table_value

- crates/sui-json-rpc/src/error.rs
cherry pick #13608 to release 1.8
---
> Cherry pick 13608 to 1.8

- sui-execution/latest/sui-adapter/src/temporary_store.rs
When collecting storage rebate of input objects for mutations, currently we read from DB for each child object. This is inefficient and unnecessary.
Change it to call a helper function that we already have to read from in-memory metadata instead.
This conflicts with https://github.com/MystenLabs/sui/pull/13519 on this function as they both got rid of the extra writes. @dariorussi let me know whether you would prefer to take this into your PR.
---
> Do not read DB for storage rebate collection

- doc/src/learn/cryptography/hashing.md
Fix a typo in documentation
---
> [Doc] Update typo for blake2b

- Cargo.lock
- Cargo.toml
- crates/sui-analytics-indexer/Cargo.toml
- crates/sui-analytics-indexer/src/analytics_handler.rs
- crates/sui-analytics-indexer/src/analytics_metrics.rs
- crates/sui-analytics-indexer/src/csv_writer.rs
- crates/sui-analytics-indexer/src/errors.rs
- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/main.rs
- crates/sui-analytics-indexer/src/tables.rs
- crates/sui-analytics-indexer/src/writer.rs
Initial implementation of the analytics pipeline. 
I am thinking it would be best to start reviewing this and committing sooner as opposed to get this in a great shape and put it up for review only then. It's getting bigger and there is still quite a bit to do and it will only get bigger and bigger, so we better start moving.
The overall idea is here though. So please take a look and let me know if you see issues that you want solved or done differently, or just broken.
@sadhansood, @bschwab and I talked about this and trying to get it in seems important, so others can work on it as well, and we can iterate.
Nothing uses it for now. Last I tried it, on my machine, with a local fullnode, it collect checkpoints and runs. So it's usable.
Next step is to write a csv writer and start the task …
> Analtics pipeline

- crates/sui-graphql-rpc/src/types/sui_address.rs
> [graphql/rpc] allow short addresses on input

- .changeset/curly-lemons-act.md
- apps/wallet/src/background/accounts/zk/ZkAccount.ts
- sdk/zklogin/src/address.ts
- sdk/zklogin/src/bcs.ts
- sdk/zklogin/src/index.ts
This will simplify a decent amount of the process.
---
> Add method to get a ZK signature instead of relying on BCS

- apps/core/tailwind.config.ts
- apps/explorer/src/components/GraphTooltipContent.tsx
- apps/explorer/src/components/header/Header.tsx
- apps/explorer/src/ui/Card.tsx
- apps/explorer/src/ui/DropdownMenu.tsx
https://mysten.atlassian.net/browse/APPS-1640
---
> [Explorer]: Update shadow & box-shadow values in tailwind

- .github/workflows/release.yml
Start building macOS `arm64` binaries
[Testing via my branch](https://github.com/MystenLabs/sui/actions/runs/6100897051/job/16556132942)
> Start building Macos `arm64` binaries

- narwhal/primary/src/synchronizer.rs
Regardless of if the content of the certificate is known.
I did not reproduce the issue in simtest but I believe this should fix the problem.
CI
---
> [Narwhal] always try to accept children of GC'ed missing certificate

- apps/core/tailwind.config.ts
- apps/wallet/src/ui/app/components/coin-icon/index.tsx
- apps/wallet/src/ui/app/components/sui-apps/SuiApp.tsx
- apps/wallet/src/ui/app/shared/image-icon/index.tsx
- apps/wallet/src/ui/app/staking/validators/ValidatorLogo.tsx
- Update wallet app images from circle to square
- https://mysten.atlassian.net/browse/APPS-1535
---
> [Wallet]: update wallet image

- .changeset/gentle-trainers-flow.md
- sdk/zklogin/src/address.ts
- sdk/zklogin/src/utils.ts
> [zkLogin] move aud to the inner hash in address derivation

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_23.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_23.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_23.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
Cherry pick v23 from #13664
- ran tests
---
> Cherry pick part of #13664

- apps/wallet/src/background/connections/UiConnection.ts
- apps/wallet/src/background/storage-migration.ts
- apps/wallet/src/shared/messaging/messages/payloads/MethodPayload.ts
- apps/wallet/src/ui/app/background-client/index.ts
- apps/wallet/src/ui/app/components/menu/content/MoreOptions.tsx
https://github.com/MystenLabs/sui/assets/10210143/e4cdbcf6-a173-4e6d-b4d0-12976260733f
closes APPS-1555
👀 
---
> wallet-ext: implement wallet logout

- .changeset/cool-snails-peel.md
- sdk/zklogin/src/index.ts
- sdk/zklogin/src/utils.ts
> [zkLogin] Update hashASCIIStr logic and constants

- crates/sui-storage/src/http_key_value_store.rs
> kvstore: fix typo ts2c -> tx2c

- apps/explorer/src/components/Object/utils.ts
https://mysten.atlassian.net/browse/APPS-1550
BEFORE
AFTER
---
> [explorer]: fix nested object render for Fields

- .changeset/honest-dodos-shave.md
- apps/wallet/src/background/accounts/zk/utils.ts
- doc/src/build/zk_login.md
- sdk/zklogin/src/index.ts
- sdk/zklogin/src/nonce.ts
- sdk/zklogin/src/poseidon.ts
> Add randomness generation to zklogin sdk

- sdk/dapp-kit/test/hooks/useWallet.test.tsx
- sdk/dapp-kit/test/mockWallet.tsx
- sdk/dapp-kit/test/test-utils.tsx
I didn't write tests for https://github.com/MystenLabs/sui/pull/13651 because I was lazy and trying to get this wrapped up 😆, but then I realized these are pretty important to have for all the various edge cases and pieces of functionality that come with managing wallet and account connections. 
- Automated tests pass
---
> [dapp-kit] write tests for the new WalletProvider component / hook

- crates/sui-benchmark/tests/simtest.rs
The test that upgrading from the version of the package currently running on a production network to the max version in `main` previously assumed that there would always be a snapshot available for `max_ver - 1`.  This may not be the case, if a release goes out with multiple protocol version bumps.
All other tests that reference snapshots do so via the snapshot manifest, so this change updates the upgrade compatibility test to do the same: It finds the largest version strictly less than `max_ver` that we have a snapshot for.
```
sui simtest test_upgrade_compatibility
```
> [framework-snapshots] Don't assume there's a max_ver - 1 snapshot

- apps/explorer/src/ui/image/Image.tsx
- Use `framer-motion` directly with div container to fix long img aspect ratio
BEFORE
AFTER
---
> fix image fadein

- crates/sui-move/src/build.rs
- crates/sui-move/src/coverage.rs
- crates/sui-move/src/disassemble.rs
- crates/sui-move/src/new.rs
- crates/sui-move/src/prove.rs
- crates/sui-move/src/unit_test.rs
> sui-move: fix clap argument groups for clapv4

- apps/wallet/src/ui/app/components/accounts/EditableAccountName.tsx
> [wallet-ext] inline nickname edit submit handling

- doc/src/build/zk_login.md
> Update zk_login.md to add OpenID providers

- Cargo.lock
- crates/sui-analytics-indexer/Cargo.toml
- crates/sui-analytics-indexer/src/analytics_handler.rs
- crates/sui-analytics-indexer/src/csv_writer.rs
- crates/sui-analytics-indexer/src/tables.rs
- crates/sui-analytics-indexer/src/writer.rs
Add move calls table
Nothing so far
---
> Add Move calls tables

- SECURITY.md
Updates References for Bug Bounty Program
N/A
---
> update references to HackenProof For Bug Bounty

- apps/wallet/src/background/accounts/zk/providers.ts
* fb app is not public yet so only registered test users can use it
https://github.com/MystenLabs/sui/assets/10210143/5c1a487e-99eb-47e6-a982-b94da94dbd65
👀 
---
> wallet-ext: enable facebook zklogin

- sdk/dapp-kit/src/hooks/rpc/useDevInspectTransactionBlock.ts
- sdk/dapp-kit/src/hooks/rpc/useDryRunTransactionBlock.ts
- sdk/dapp-kit/src/hooks/rpc/useExecuteTransactionBlock.ts
- sdk/dapp-kit/src/hooks/useSuiClientMutation.ts
- sdk/docs/pages/_meta.json
- sdk/docs/pages/dapp-kit/_meta.json
- sdk/docs/pages/dapp-kit/index.mdx
- sdk/docs/pages/dapp-kit/rpc-hooks.mdx
- sdk/docs/pages/dapp-kit/sui-client-provider.mdx
- sdk/typescript/scripts/hooks.ts
- sdk/typescript/src/client/types/generated.ts
> [docs] Add initial docs for dapp-kit

- apps/wallet/src/ui/app/hooks/useCreateAccountMutation.ts
https://github.com/MystenLabs/sui/assets/10210143/92f2a495-65ca-4c38-bba4-09a208ca7268
closes APPS-1636
---
> wallet-ext: create account switches to the new account

- crates/sui-aws-orchestrator/README.md
- crates/sui-aws-orchestrator/assets/grafana-dashboard-narwhal.json
- crates/sui-aws-orchestrator/assets/requirements.txt
Updating the orchestrator documentation and adding a Narwhal dashboard to be used when running the benchmarks.
---
> [docs] Update docs and add narwhal dashboard for orchestrator

- sdk/docs/pages/typescript/_meta.json
- sdk/docs/pages/typescript/cryptography/keypairs.mdx
- sdk/docs/pages/typescript/index.mdx
- sdk/docs/pages/typescript/sui-client.mdx
- sdk/docs/pages/typescript/utils.mdx
- sdk/typescript/src/utils/index.ts
This adds docs for a few missing use cases in the SDK
---
> [docs] add more docs for various utils in the typescript SDK

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/unit_tests/utils.rs
- crates/sui-types/src/zk_login_authenticator.rs
- crates/sui/src/keytool.rs
- crates/sui/src/zklogin_commands_util.rs
- crates/workspace-hack/Cargo.toml
Update address derivation, and camelCase inputs and added some util for testing. 
---
> fix: update zkLogin authenticator

- narwhal/primary/src/synchronizer.rs
We have observed simtest failures with messages like:
```
2023-09-12T06:16:20.2666876Z [31;1m--- [0m[31;1mSTDERR:              [0m[35;1msui-e2e-tests::reconfiguration_tests[0m [34;1mtest_reconfig_with_failing_validator[0m[31;1m ---[0m
2023-09-12T06:16:20.2667858Z thread '<unnamed>' panicked at 'Parent kXWcgU8cKSUnG1gL5MAjirFbd/pdLhfgpLDMsFOtTHk= not found for HFG7pP2s799ogJy1: C2(3, HFG7pP2s799ogJy1, E1)!', narwhal/primary/src/synchronizer.rs:163:21
2023-09-12T06:16:20.2668367Z stack backtrace:
2023-09-12T06:16:20.2668639Z    0: rust_begin_unwind
2023-09-12T06:16:20.2669009Z              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
2023-09-12T06:16:20.2669710Z    1: core::panicking::panic_fmt
2023-09-12T06:16:20.2670103Z              at …
```
> [fix] narwhal synchronizer to gc certificates up to gc_round

- Cargo.lock
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/rocks/tests.rs
- crates/typed-store/src/sally/mod.rs
- crates/typed-store/src/test_db.rs
- crates/typed-store/src/traits.rs
Rename delete_all in typed store library to schedule_delete_all and add more documentation around it.
Existing tests
> Rename delete_all to schedule_detele_all

- crates/sui-graphql-rpc/src/server/builder.rs
Tests for query depth limiting
In pr
---
> [graphql/rpc] query depth limit test

- doc/src/learn/cryptography/sui-move-signatures.md
Fix typo on the example code snippets for move signatures.
---
> fix: fix sui move signatures example

- apps/explorer/src/pages/transaction-result/transaction-summary/ObjectChanges.tsx
https://mysten.atlassian.net/browse/APPS-1681
---
> [Explorer]: update font mono for Type

- doc/src/build/zk_login.md
> fix: zklogin doc fixes

- crates/sui-snapshot/src/uploader.rs
The path used during snapshot creation is missing store prefix. This PR fixes it
> Fix db path for state snapshot creation

- crates/sui-oracle/src/lib.rs
When FN returns error, wait for a bit and update gas object reference.
---
(reference oracle) sleep and refresh gas obj ref upon error
> [reference oracle] sleep and refresh gas obj ref upon error

- apps/wallet/src/background/accounts/zk/utils.ts
* [use latest prover url](https://mysten-labs.slack.com/archives/C05Q4FNS31A/p1694709286254319) (still not the prod one)
---
> wallet-ext: update zklogin prover url

- apps/explorer/src/components/OwnedObjects/index.tsx
- Fix loading state so it is dependent on viewMode
---
> [Explorer]: Fix loading state

- apps/wallet/src/background/Window.ts
- apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx
- apps/wallet/src/ui/app/pages/accounts/WelcomePage.tsx
- apps/wallet/src/ui/app/pages/layout/index.tsx
- apps/wallet/src/ui/styles/values/sizing.scss
- apps/wallet/tailwind.config.ts
* now wallet can expand to 680px if there is available room
https://github.com/MystenLabs/sui/assets/10210143/b9e7ed20-e618-4fcf-b181-da91e150bdc9
closes APPS-1637
👀 
---
> wallet-ext: update max height

- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/diesel.toml
- crates/sui-indexer/migrations_v2/00000000000000_diesel_initial_setup/down.sql
- crates/sui-indexer/migrations_v2/00000000000000_diesel_initial_setup/up.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044020_events/down.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044020_events/up.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/down.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/up.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044026_transactions/down.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044026_transactions/up.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044035_tx_indices/down.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044035_tx_indices/up.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044044_checkpoints/down.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044044_checkpoints/up.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044052_epochs/down.sql
- crates/sui-indexer/migrations_v2/2023-08-19-044052_epochs/up.sql
- crates/sui-indexer/migrations_v2/2023-08-19-060729_packages/down.sql
- crates/sui-indexer/migrations_v2/2023-08-19-060729_packages/up.sql
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/schema_v2.patch
- crates/sui-indexer/src/schema_v2.rs
- crates/sui-indexer/src/types_v2.rs
- crates/sui-types/src/object.rs
Breaking [this](https://github.com/MystenLabs/sui/pull/13574) into smaller pieces.
This is first PR to define schemas and basic data models. Addressed most comments in #13574 
Stack:
3. https://github.com/MystenLabs/sui/pull/13775
4. https://github.com/MystenLabs/sui/pull/13778
Testing is done in a live indexer with the big PR.
---
[indexer-v2 1/n] add schemas and types
> [indexer-v2 1/n] add schemas and typesadd schemas and types

- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/safe_client.rs
- crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
- crates/sui-json-rpc/src/error.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/quorum_driver_types.rs
See the comment in authority_aggregator.rs for description
---
> fix the latent invalid sig bug

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v1.11.0 version bump

- doc/src/build/zk_login.md
Clarifications for zklogin properties.
N/A
---
> zklogin docs clarifications

- crates/sui-snapshot/src/lib.rs
- crates/sui-snapshot/src/reader.rs
- crates/sui-snapshot/src/uploader.rs
- crates/sui-snapshot/src/writer.rs
Fixes to make state snapshot and upload work
Existing tests are confirmed to be working
> Chunk reference files for formal snapshot

- .github/workflows/release.yml
Fix macOS x86_64 builds
[Testing via my branch](https://github.com/MystenLabs/sui/actions/runs/6228766416/job/16906077464)
> Fix macos x86_64 builds

- apps/explorer/src/components/Object/DynamicFieldsCard.tsx
- apps/explorer/src/pages/object-result/views/ObjectView.tsx
Minor fixes for object page
- Backdrop filter for image icon
- Flatmap data
- Render description as title when title missing
---
> [Explorer]: Object page minor fixes

- doc/src/build/rpc-best-practices.md
Added a missing space in the RPC best practices page.
---
> [docs] Updated RPC Best Practice page

- doc/src/build/zk_login.md
> zklogin: update prover url

- doc/src/build/zk_login.md
> Update prover URI with https

- sdk/wallet-kit/example/src/QredoConnectButton.tsx
> wallet-kit: example app fix qredo connect button

- apps/wallet/src/background/accounts/zk/utils.ts
> wallet-ext: update zklogin proving server API

- apps/explorer/src/pages/object-result/views/ObjectView.tsx
- apps/explorer/src/ui/PageHeader.tsx
- Fix error rendering for Object page
BEFORE
AFTER
---
> [Explorer]: Fix error render on Object page

- crates/sui-faucet/src/faucet/simple_faucet.rs
Faucet calls have been missing a couple logging statements that make a bit harder to track exactly what code was called from grafana logs, so we updated these logs here.
---
> [Faucet ]logging only change

- apps/wallet/src/ui/app/pages/accounts/AddAccountPage.tsx
- apps/wallet/src/ui/app/shared/ButtonUI.tsx
- apps/wallet/src/ui/app/shared/SocialButton.tsx
* Button component had the wrong size now it's fixed
| -- | -- |
| <img width="364" alt="Screenshot 2023-09-20 at 13 44 56" src="https://github.com/MystenLabs/sui/assets/10210143/9dcb4a97-a510-4b1e-bc79-4c4e3f33e8c9"> | <img width="364" alt="Screenshot 2023-09-20 at 13 41 42" src="https://github.com/MystenLabs/sui/assets/10210143/87f6e67e-8717-43cc-8319-4892e4a0253e"> |
closes [APPS-1697](https://mysten.atlassian.net/browse/APPS-1697)
---
> wallet-ext: fix font size in add accounts page

- apps/explorer/src/components/Object/ObjectFieldsCard.tsx
- apps/explorer/src/ui/Description.tsx
- Change max height
BEFORE
AFTER
---
> [Explorer]: Change max height of fields section

- nre/sui_for_node_operators.md
> add requirements to sui for node operators documentation

- sdk/bcs/src/bcs-type.ts
- sdk/bcs/src/index.ts
- sdk/bcs/tests/array.type.test.ts
- sdk/bcs/tests/builder.test.ts
> Add SerializedBcsClass

- sdk/docs/pages/_meta.json
- sdk/docs/pages/bcs/_meta.json
- sdk/docs/pages/bcs/index.mdx
- sdk/docs/pages/typescript/index.mdx
> [docs] bcs rewrite docs

- doc/src/build/zk_login.md
- Tighten up the first paragraph
- Make the point titles and text punchier
- Emphasize 2FA feature
- Add bullet for security
- Clarify verified identity feature
> [docs] adjust zklogin intro

- apps/wallet/src/ui/app/shared/forms/FormField.tsx
- apps/wallet/src/ui/app/shared/forms/controls/Input.tsx
- apps/wallet/src/ui/app/shared/forms/controls/Select.tsx
before 
https://github.com/MystenLabs/sui/assets/10210143/6269190f-ceab-468d-984c-02b58cb38c59
after
https://github.com/MystenLabs/sui/assets/10210143/c0e773c7-b16e-48a7-a7d8-71ca8eeb5c83
closes [APPS-1693](https://mysten.atlassian.net/browse/APPS-1693)
---
> wallet-ext: fix auto-lock selector inputs styling

- apps/wallet/src/background/accounts/zk/providers.ts
> wallet-ext: use new fb client id

- apps/explorer/src/pages/transaction-result/TransactionData.tsx
> [Explorer]: Fix section not stretching full width

- sdk/bcs/src/bcs.ts
- sdk/bcs/tests/builder.test.ts
- sdk/docs/pages/bcs/index.mdx
- sdk/typescript/src/bcs/index.ts
> [bcs] remove some builtins

- sdk/bcs/src/bcs-type.ts
- sdk/bcs/src/index.ts
- sdk/bcs/src/types.ts
- sdk/docs/pages/bcs/index.mdx
> [bcs] Add helpers for inferring types

- apps/wallet/src/ui/app/components/accounts/EditableAccountName.tsx
https://github.com/MystenLabs/sui/assets/10210143/4a17be08-6736-4d23-bd87-f1f22ef8116c
closes [APPS-1695](https://mysten.atlassian.net/browse/APPS-1695)
---
> wallet-ext: select account nickname on focus

- apps/wallet/src/ui/app/components/IconButton.tsx
- apps/wallet/src/ui/app/components/accounts/AccountItem.tsx
- apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx
- apps/wallet/src/ui/app/pages/accounts/manage/ManageAccountsPage.tsx
- apps/wallet/src/ui/app/shared/ButtonUI.tsx
before
https://github.com/MystenLabs/sui/assets/10210143/76a88a1f-612f-4e24-9e47-9dd1be1a67ce
after
https://github.com/MystenLabs/sui/assets/10210143/1c46901e-0201-40ea-99d2-c2679a2c7ffb
closes [APPS-1705](https://mysten.atlassian.net/browse/APPS-1705)
---
> wallet-ext: manage accounts & account ui polishing

- apps/wallet/src/ui/app/pages/accounts/ImportLedgerAccountsPage.tsx
- apps/wallet/src/ui/app/pages/home/transfer-coin/index.tsx
- apps/wallet/src/ui/app/staking/validators/SelectValidatorCard.tsx
- apps/wallet/src/ui/app/staking/validators/index.tsx
| -- | -- |
| <img width="372" alt="Screenshot 2023-09-21 at 23 47 48" src="https://github.com/MystenLabs/sui/assets/10210143/964dd14f-eaad-4677-85e7-02e989c55511"> | <img width="372" alt="Screenshot 2023-09-22 at 00 34 20" src="https://github.com/MystenLabs/sui/assets/10210143/938b1344-d299-4c75-b1ae-1d464e8e70a9"> |
| <img width="372" alt="Screenshot 2023-09-21 at 23 48 02" src="https://github.com/MystenLabs/sui/assets/10210143/9dfdd9c0-854b-4b93-a8f0-358d375e10bd"> | <img width="372" alt="Screenshot 2023-09-22 at 00 35 44" src="https://github.com/MystenLabs/sui/assets/10210143/3f96dac6-32cd-46f0-b690-be72f4da15ad"> |
| <img width="372" alt="Screenshot 2023-09-21 at 23 50 36" src="https://github.com/MystenLabs/sui/assets/10210143/f7adfd26-c43f-4426-8464-22f9825346b8"> …
> wallet-ext: overlay fix cta buttons position

- apps/explorer/src/components/Layout/PageLayout.tsx
https://mysten.atlassian.net/browse/APPS-1552
---
> [Explorer]: update testnet banner

- apps/wallet/src/background/accounts/zk/providers.ts
- apps/wallet/src/ui/app/components/accounts/ZkLoginButtons.tsx
close [APPS-1668](https://mysten.atlassian.net/browse/APPS-1668)
---
> wallet-ext: hide fb zkLogin button

- apps/core/package.json
- apps/core/vite.config.ts
- pnpm-lock.yaml
Fixes `pnpm test` on `apps/core`.
---
> Fix tests failing on `apps/core` project

- sdk/docs/pages/_meta.json
- sdk/docs/pages/kiosk/_meta.json
- sdk/docs/pages/kiosk/advanced-examples.mdx
- sdk/docs/pages/kiosk/from-v1.mdx
- sdk/docs/pages/kiosk/index.mdx
- sdk/docs/pages/kiosk/kiosk-client/_meta.json
- sdk/docs/pages/kiosk/kiosk-client/introduction.mdx
- sdk/docs/pages/kiosk/kiosk-client/kiosk-transaction/_meta.json
- sdk/docs/pages/kiosk/kiosk-client/kiosk-transaction/examples.mdx
- sdk/docs/pages/kiosk/kiosk-client/kiosk-transaction/kiosk-transaction.mdx
- sdk/docs/pages/kiosk/kiosk-client/kiosk-transaction/managing.mdx
- sdk/docs/pages/kiosk/kiosk-client/kiosk-transaction/purchasing.mdx
- sdk/docs/pages/kiosk/kiosk-client/querying.mdx
- sdk/docs/pages/kiosk/kiosk-client/transfer-policy-transaction/_meta.json
- sdk/docs/pages/kiosk/kiosk-client/transfer-policy-transaction/introduction.mdx
- sdk/docs/pages/kiosk/kiosk-client/transfer-policy-transaction/using-the-manager.mdx
> Kiosk SDK V2 Docs

- crates/sui-indexer/src/apis/coin_api_v2.rs
- crates/sui-indexer/src/apis/governance_api_v2.rs
- crates/sui-indexer/src/apis/indexer_api_v2.rs
- crates/sui-indexer/src/apis/mod.rs
- crates/sui-indexer/src/apis/read_api_v2.rs
- crates/sui-indexer/src/apis/transaction_builder_api_v2.rs
- crates/sui-indexer/src/apis/write_api_v2.rs
Add skeleton API files so people can start to grab and work on them.
Stack:
10. https://github.com/MystenLabs/sui/pull/13892
--- …
> [indexer-v2 10/n] add api files

- apps/explorer/src/pages/transaction-result/transaction-summary/BalanceChanges.tsx
- apps/wallet/src/ui/app/shared/transaction-summary/cards/BalanceChanges.tsx
[APP https://mysten.atlassian.net/browse/APPS-1645?atlOrigin=eyJpIjoiM2I4OTA2YWY0MjgzNGE2Yjg1NmRmMjczZjMxZGQ0NzkiLCJwIjoiaiJ9](https://mysten.atlassian.net/browse/APPS-1645)
before 
After
> Remove extra line for only unrecognized coin

- crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
This test always fail with simtest. Splitting it to two seems to fix the issue.
---
> Improve test_process_transaction_fault_fail

- crates/sui-adapter-transactional-tests/tests/dynamic_fields/remove_add_back_and_remove.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/remove_add_back_and_remove.move
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/remove_add_back_and_remove_type.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/remove_add_back_and_remove_type.move
- Added missing tests for dynamic field add/remove/add cases
- Ran them
---
> [tests] Added more dynamic field tests

- .changeset/config.json
> Make kiosk-demo and kiosk-cli private for changeset

- apps/wallet/src/background/accounts/zk/utils.ts
> wallet-ext: update salt server api url

- crates/sui-analytics-indexer/src/analytics_handler.rs
- crates/sui-analytics-indexer/src/csv_writer.rs
- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/tables.rs
- crates/sui-analytics-indexer/src/writer.rs
A raw data for packages is now published as it is easy to find that data.
Added a non refundable fee for checkpoints (it got lost) and some cleanup
No test so far
---
> Adding a package table and some cleanup

- crates/sui-adapter-transactional-tests/tests/dynamic_fields/receive_remove_add_back_and_remove_type.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/receive_remove_add_back_and_remove_type.move
> [transfer-to-object/dynamic-fields] Add additional receiving/dynamic field tests

- crates/sui-core/src/authority/test_authority_builder.rs
> Remove unused API in test_authority_builder

- sdk/bcs/src/bcs.ts
> [bcs] Add more validation

- .changeset/khaki-fishes-live.md
- .changeset/tame-pumas-obey.md
- sdk/bcs/README.md
> [bcs] add changesets and update readme with for new BCS api

- Cargo.lock
- Cargo.toml
- crates/sui-graphql-rpc/Cargo.toml
- crates/sui-graphql-rpc/src/types/owner.rs
- crates/workspace-hack/Cargo.toml
Use latest version of lib which has some fixes and features
Manual, unit
---
> [graphql/rpc] chore/easy: update graphql lib

- apps/wallet/src/background/accounts/zk/utils.ts
> wallet-ext: fix salt server api path

- crates/sui-graphql-rpc/src/server/builder.rs
Makes test expectation more specific/explicit
Unit
---
> [graphql/impl] easy/chore: improve test specificity

- crates/sui-indexer/src/apis/mod.rs
- crates/sui-indexer/src/apis/move_utils_v2.rs
- crates/sui-indexer/src/indexer_reader.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/store/mod.rs
- crates/sui-indexer/src/store/module_resolver.rs
- crates/sui-indexer/src/store/module_resolver_v2.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store_v2.rs
> indexer: implement MoveUtils JsonRPC api for indexer v2

- crates/sui-graphql-rpc/docker/Dockerfile
- crates/sui-graphql-rpc/docker/build.sh
Initial docker support
Manual
---
> [graphql/rpc] initial docker image

- crates/sui-indexer/src/apis/governance_api_v2.rs
- crates/sui-indexer/src/indexer_reader.rs
- crates/sui-indexer/src/models_v2/epoch.rs
- crates/sui-json-rpc-types/src/sui_extended.rs
> indexer: implement part of the governance api

- apps/wallet/configs/ts/tsconfig.common.json
- apps/wallet/package.json
- apps/wallet/src/shared/deepbook-client.ts
- apps/wallet/src/ui/app/hooks/useDeepbook.ts
- pnpm-lock.yaml
- sdk/deepbook/src/client.ts
https://mysten.atlassian.net/browse/APPS-1775
---
> [Wallet]: Add hooks to query data from deepbook

- doc/src/build/zk_login.md
- update salt server endpoint
- ceremony description (post finalization)
- link updates
---
> zkLogin: update doc

- pnpm-lock.yaml
- sdk/dapp-kit/src/hooks/useSuiClientQuery.ts
Fixed incorrect enabled status
---
> Quick SDK fix

- crates/sui-graphql-rpc/examples/chain_id/chain_id.graphql
- crates/sui-graphql-rpc/examples/protocol_configs/all_configs.graphql
Create examples dir and samples to encourage more 
Manual
---
> [graphql/impl] Graphql impl initial examples

- crates/sui-node/src/lib.rs
- crates/sui-node/src/main.rs
- crates/sui-node/src/metrics.rs
- Add JWK fetch metrics
- Remove unnecessary AsyncOnceCell
> Add jwk-fetching related metrics

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v1.12.0 version bump

- apps/wallet/src/background/accounts/zk/utils.ts
> wallet-ext: add request-id header for salt and prove requests

- apps/explorer/src/components/SyntaxHighlighter/index.tsx
https://mysten.atlassian.net/browse/APPS-1771
Before 
https://github.com/MystenLabs/sui/assets/126525197/31e6fca0-6373-49aa-9c84-7b7adb7ecfc6
After 
https://github.com/MystenLabs/sui/assets/126525197/9d8e1481-0653-4aa5-b946-56ffde3a4ada
> Address performace issue with large code block by paginating the rendered blocks

- Cargo.lock
- crates/simulacrum/src/epoch_state.rs
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-config/src/transaction_deny_config.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/transaction_deny_tests.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-transaction-checks/Cargo.toml
- crates/sui-transaction-checks/src/deny.rs
- crates/sui-transaction-checks/src/lib.rs
Add to denylist config with zklogin_disabled and zklogin_disabled_providers
unit test
---
> denylist: zklogin kill switch

- apps/explorer/src/components/Layout/PageLayout.tsx
- Requested by Sean. We will have a different banner altogether in the near future. This is a minor change only.
---
> [Explorer]: Update testnet message

- Cargo.lock
- crates/simulacrum/src/epoch_state.rs
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-config/src/transaction_deny_config.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/transaction_deny_tests.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-transaction-checks/Cargo.toml
- crates/sui-transaction-checks/src/deny.rs
- crates/sui-transaction-checks/src/lib.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/zk_login_authenticator.rs
mirror: (https://github.com/MystenLabs/sui/pull/14051/commits)
also: https://github.com/MystenLabs/sui/pull/13986/commits
---
> fix: remove unwrap from address derive

- crates/sui-replay/src/tests.rs
> Disable replay test while debugging

- crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs
Fixes a dumb mistake.
tested locally and made sure the fix is good.
---
[indexer] fix epoch total tx counting
> [indexer] fix epoch total tx counting

- apps/core/src/components/KioskClientProvider.tsx
- apps/core/src/hooks/useGetKioskContents.ts
- apps/core/src/hooks/useKioskClient.ts
- apps/explorer/src/components/Layout/index.tsx
- apps/wallet/src/ui/app/pages/home/nft-transfer/useTransferKioskItem.ts
- apps/wallet/src/ui/index.tsx
closes [APPS-1747](https://mysten.atlassian.net/browse/APPS-1747)
---
> wallet-ext,explorer,core: add context for kiosk client

- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/src/apis/read_api_v2.rs
- crates/sui-indexer/src/indexer_reader.rs
- crates/sui-indexer/src/models_v2/events.rs
- crates/sui-indexer/src/models_v2/transactions.rs
- crates/sui-json-rpc-types/src/sui_checkpoint.rs
- crates/sui-types/src/sui_serde.rs
implement a number of ReadAPI methods for indexer v2
---
> indexer: implement a number of ReadAPI methods for indexer v2

- crates/sui-types/src/effects/effects_v2.rs
> Fix release build unused import

- .github/workflows/rust.yml
use secrets for graphql ci tests
---
> [graphql] use url

- .changeset/forty-actors-move.md
- pnpm-lock.yaml
- sdk/dapp-kit/package.json
- sdk/dapp-kit/src/components/WalletProvider.tsx
- sdk/dapp-kit/src/components/styling/InjectedThemeStyles.tsx
- sdk/dapp-kit/src/index.ts
- sdk/dapp-kit/src/themes/lightTheme.ts
- sdk/dapp-kit/src/themes/themeContract.ts
This PR sets up the basic theming definitions for dapp-kit. I learned that theming is actually pretty hard to get right, and I looked thoroughly at Radix UI themes, PandaCSS, Tamagui, Shadcn, Rainbow Kit, and ConnectKit for inspiration 😅.
I settled on the premise that a theme should just be a collection of mostly specific CSS variable definitions (e.g., the background color for the modal) with some generic definitions (e.g., there's a scale of small - xlarge border radii). For someone to theme the UI in the short term, they'll need to manually pass through a `Theme` object which is this big collection of variables (we can provide helpers for overriding existing themes to make this not a PITA). In the long term, I think there are opportunities to build on this by using a color scale/system …
> [dapp-kit] set up basic theming definitions

- crates/sui-graphql-rpc/src/client/simple_client.rs
Allow specifying the headers in client. Will be used for features gated by headers
TBD
---
> [graphql/rpc] easy: headers support client

- .changeset/light-swans-taste.md
- apps/wallet/src/dapp-interface/WalletStandardInterface.ts
- apps/wallet/src/shared/messaging/messages/payloads/transactions/ExecuteTransactionRequest.ts
- sdk/typescript/README.md
- sdk/typescript/src/builder/TransactionBlock.ts
> [wallet] Fix bug that was attempting to serialize transaction blocks

- dapps/multisig-toolkit/src/main.tsx
This is not useful because the unsafe burner is just for dev
---
> Remove unsafe burner wallet for multisig toolkit

- .changeset/heavy-eels-walk.md
- sdk/dapp-kit/package.json
> Dapp Kit Side effects fix

- apps/wallet/src/ui/app/hooks/useDeepBook.ts
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
- apps/wallet/src/ui/app/pages/swap/BaseAssets.tsx
- apps/wallet/src/ui/app/pages/swap/QuoteAssets.tsx
- Fixing comments from https://github.com/MystenLabs/sui/pull/14059 and https://github.com/MystenLabs/sui/pull/14007
---
> [Wallet]: fix comments

- .changeset/good-jobs-bathe.md
- pnpm-lock.yaml
- sdk/build-scripts/src/utils/buildPackage.ts
- sdk/dapp-kit/src/components/connect-modal/ConnectModal.css.ts
- sdk/typescript/src/bcs/index.ts
- sdk/typescript/src/builder/__tests__/bcs.test.ts
> [sdk] register Option enum to legacy bcs registry

- .changeset/quiet-coats-live.md
- sdk/typescript/src/builder/TransactionBlock.ts
- sdk/typescript/src/builder/export.ts
> [sdk] export TransactionResult type from SDK

- doc/src/build/zk_login.md
> Update zk_login.md to suggest using Base64 instead of BigInt

- external-crates/move/move-model/src/model.rs
- Add utility functions for finding objects shared, transferred, or frozen by a function/module. These functions let you ask both about direct and transitive shares/transfers/freezes.
- Add a similar utility function for showing events emitted by a function/module
- Provide a function for asking about the object types returned by a function/module
These functions are useful for tools that are trying to do high-level reasoning about Move packages, or codegen of various frontend queries.
It's not currently easy to test such changes. I think it would be great to have a `sui client package` CLI command that lets you ask various questions about an on-chain package + uses `move-model` utility functions like this under the hood.
> [move tools] add some utility functions to move model

- crates/sui-graphql-rpc/examples/checkpoint/checkpoint.graphql
- crates/sui-graphql-rpc/schema/current_progress_schema.graphql
- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
- crates/sui-graphql-rpc/src/context_data/sui_sdk_data_provider.rs
- crates/sui-graphql-rpc/src/error.rs
- crates/sui-graphql-rpc/src/types/checkpoint.rs
- crates/sui-graphql-rpc/src/types/query.rs
- crates/sui-graphql-rpc/src/types/transaction_block.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Implements postgres resolvers for Checkpoint and also completes implementation for Checkpoint type
Manual queries, added to examples
---
> [graphql] resolvers for Checkpoint type

- crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
- crates/sui-graphql-rpc/src/metrics.rs
> [graphql/rpc] easy: add metric to track payload size

- crates/sui-graphql-rpc/src/server/builder.rs
Adds unit test for metrics collection.
Will add integration test in subsequent PR
Unit test
---
> [graphql/rpc] easy: test query complexity metrics collection

- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
- crates/sui-graphql-rpc/src/types/address.rs
- crates/sui-graphql-rpc/src/types/checkpoint.rs
- crates/sui-graphql-rpc/src/types/object.rs
- crates/sui-graphql-rpc/src/types/owner.rs
- crates/sui-graphql-rpc/src/types/query.rs
Cleans up some logic
Manual
---
> [graphql/rpc] easy/chore: cleanup data provider logic

- doc/src/build/zk_login.md
> Update zk_login.md with instructions to run their own prover service

- crates/sui-graphql-rpc/src/server/builder.rs
Fixes a test which doesnt load the PG properly
Unit
---
> [graphql/rpc] fix test: add pg conn in test

- crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/up.sql
- crates/sui-indexer/src/apis/extended_api_v2.rs
- crates/sui-indexer/src/apis/governance_api_v2.rs
- crates/sui-indexer/src/apis/indexer_api_v2.rs
- crates/sui-indexer/src/apis/mod.rs
- crates/sui-indexer/src/indexer_reader.rs
- crates/sui-indexer/src/models_v2/objects.rs
- crates/sui-indexer/src/schema_v2.rs
- crates/sui-indexer/src/store/pg_indexer_store_v2.rs
- crates/sui-json-rpc/src/governance_api.rs
> indexer-v2: implement get_epochs, validator-apys, and get_stakes_by_ids

- crates/sui-indexer/src/store/pg_indexer_store_v2.rs
> [indexer] a small typo fix

- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
- crates/sui-graphql-rpc/src/context_data/mod.rs
- crates/sui-graphql-rpc/src/context_data/sui_sdk_data_provider.rs
Use explicit const page limit and avoid magic numbers
Unit
---
> [graphql/rpc] easy/chore: use const limit

- crates/sui-indexer/migrations_v2/2023-10-07-160139_display/down.sql
- crates/sui-indexer/migrations_v2/2023-10-07-160139_display/up.sql
- crates/sui-indexer/src/apis/extended_api_v2.rs
- crates/sui-indexer/src/apis/indexer_api_v2.rs
- crates/sui-indexer/src/apis/read_api_v2.rs
- crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs
- crates/sui-indexer/src/handlers/committer.rs
- crates/sui-indexer/src/handlers/mod.rs
- crates/sui-indexer/src/indexer_reader.rs
- crates/sui-indexer/src/models_v2/display.rs
- crates/sui-indexer/src/models_v2/mod.rs
- crates/sui-indexer/src/schema_v2.rs
- crates/sui-indexer/src/store/indexer_store_v2.rs
- crates/sui-indexer/src/store/pg_indexer_store_v2.rs
- crates/sui-json-rpc/src/indexer_api.rs
- crates/sui-json-rpc/src/lib.rs
- crates/sui-json-rpc/src/name_service.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-node/src/lib.rs
- crates/sui-types/src/display.rs
* indexer: implement name service apis 
* name-service: simplify querying name service records
* indexer: implement get_object JsonRPC api
* indexer: return MethodNotFound for apis we don't plan to support
* indexer: track display object updates
---
> indexer: finish implementing ReadAPI and name-service api

- crates/sui-core/src/authority.rs
metrics to count sigs, currently we just care about zklogin and multisig
---
> metric: add count for zklogin and multisig

- crates/sui-types/src/error.rs
- crates/sui-types/src/transaction.rs
- crates/sui/src/keytool.rs
- doc/src/build/zk_login.md
> zklogin: add more useful logs and debug tools

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-single-node-benchmark/Cargo.toml
> add back cfg for process_consensus_transactions_for_tests

- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/src/apis/governance_api_v2.rs
- crates/sui-indexer/src/apis/mod.rs
- crates/sui-indexer/src/apis/move_utils_v2.rs
- crates/sui-indexer/src/apis/read_api_v2.rs
- crates/sui-indexer/src/apis/transaction_builder_api_v2.rs
- crates/sui-indexer/src/indexer_v2.rs
- crates/sui-json-rpc/src/transaction_builder_api.rs
> indexer: implement Transaction Builder and register completed modules

- crates/sui-source-validation-service/src/main.rs
Stacked on https://github.com/MystenLabs/sui/pull/14064.
Causes the server to shutdown if we see a fatal error when watching for on-chain upgrades (e.g., a fatal error such as losing a subscription connection). This PR is prep for follow up. See inline comment for details.
Tested manually since it's difficult to test forcing a connection drop to observe the server crashes as expected. I ran a local network and killed it to see the source server also die. In follow up PR there is additional testing for the functionality we care about most: invalidating sources if we observe a upgrade transaction in the network..
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes …
> move: improve source service error handling

- crates/simulacrum/src/lib.rs
- crates/sui-swarm-config/src/network_config_builder.rs
simulacrum: ensure determinism when using a seeded rng
---
> simulacrum: ensure determinism when using a seeded rng

- crates/sui-single-node-benchmark/src/benchmark_context.rs
- crates/sui-single-node-benchmark/src/command.rs
- crates/sui-single-node-benchmark/src/execution.rs
- crates/sui-single-node-benchmark/src/lib.rs
- crates/sui-single-node-benchmark/src/main.rs
- crates/sui-single-node-benchmark/src/workload.rs
- crates/sui-single-node-benchmark/tests/smoke_tests.rs
This PR introduces the concept of Workload, and wraps all workload related code/data into it. It cleans up the command interface to make it more extensible.
CI
---
> [benchmark] Add concept of workload

- crates/sui-graphql-rpc/src/commands.rs
- crates/sui-graphql-rpc/src/config.rs
- crates/sui-graphql-rpc/src/main.rs
- crates/sui-graphql-rpc/src/server/simple_server.rs
As title, so we can config db url in test
TBD when test suite comes online
---
> [graphql/rpc] add db url to server conn config

- sdk/dapp-kit/README.md
- sdk/docs/pages/dapp-kit/index.mdx
- sdk/docs/pages/dapp-kit/sui-client-provider.mdx
> [docs] fix incorrect import in dapp-kit docs

- pnpm-workspace.yaml
> [ci] ignore dapp templates in workspace config

- sdk/docs/pages/dapp-kit/wallet-hooks/useSignAndExecuteTransactionBlock.mdx
- sdk/docs/pages/dapp-kit/wallet-hooks/useSignTransactionBlock.mdx
> [dapp-kit] tidy the docs for the "chain" param

- apps/wallet/src/ui/app/components/sui-apps/Banner.tsx
- apps/wallet/tests/utils/auth.ts
> [wallet-ext] apps page banner container

- sdk/create-dapp/src/index.ts
> Add --template arg to create-dapp cli

- .changeset/cold-ducks-try.md
- sdk/create-dapp/src/index.ts
> [create-dapp] fix dependency mapping

- crates/sui-indexer/src/apis/governance_api_v2.rs
- crates/sui-indexer/src/apis/indexer_api_v2.rs
- crates/sui-indexer/src/indexer_reader.rs
- crates/sui-indexer/src/models_v2/objects.rs
indexer: fix bug and optimize loading dynamic objects when calculating pool exchange rates
---
> indexer: fix bug and optimize loading dynamic objects when calculating pool exchange rates

- Cargo.lock
- crates/sui-graphql-rpc/Cargo.toml
- crates/sui-graphql-rpc/schema/current_progress_schema.graphql
- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
- crates/sui-graphql-rpc/src/error.rs
- crates/sui-graphql-rpc/src/types/gas.rs
- crates/sui-graphql-rpc/src/types/query.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
1. ProtocolConfig
2. Gas -> getObj, multiGetObj
---
> [graphql] remove sui-sdk usage

- crates/sui-graphql-rpc/src/commands.rs
- crates/sui-graphql-rpc/src/config.rs
- crates/sui-graphql-rpc/src/main.rs
- crates/sui-graphql-rpc/src/server/builder.rs
- crates/sui-graphql-rpc/src/server/mod.rs
Needed for easier deploys
Manual
---
> [graphql/rpc] easy: allows loading cfg from path

- crates/sui-graphql-rpc/src/commands.rs
> [graphql/impl] fix short cmd collision

- crates/sui-indexer/migrations_v2/2023-10-04-161058_tx_count_metrics/down.sql
- crates/sui-indexer/migrations_v2/2023-10-04-161058_tx_count_metrics/up.sql
- crates/sui-indexer/migrations_v2/2023-10-04-161107_move_call_metrics/down.sql
- crates/sui-indexer/migrations_v2/2023-10-04-161107_move_call_metrics/up.sql
- crates/sui-indexer/migrations_v2/2023-10-04-161115_address_metrics/down.sql
- crates/sui-indexer/migrations_v2/2023-10-04-161115_address_metrics/up.sql
- crates/sui-indexer/migrations_v2/2023-10-04-161244_network_metrics/down.sql
- crates/sui-indexer/migrations_v2/2023-10-04-161244_network_metrics/up.sql
- crates/sui-indexer/src/indexer_v2.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/main.rs
- crates/sui-indexer/src/models_v2/address_metrics.rs
- crates/sui-indexer/src/models_v2/mod.rs
- crates/sui-indexer/src/models_v2/move_call_metrics.rs
- crates/sui-indexer/src/models_v2/network_metrics.rs
- crates/sui-indexer/src/models_v2/transactions.rs
- crates/sui-indexer/src/models_v2/tx_count_metrics.rs
- crates/sui-indexer/src/processors_v2/address_metrics_processor.rs
- crates/sui-indexer/src/processors_v2/mod.rs
- crates/sui-indexer/src/processors_v2/move_call_metrics_processor.rs
- crates/sui-indexer/src/processors_v2/network_metrics_processor.rs
- crates/sui-indexer/src/processors_v2/processor_orchestrator_v2.rs
- crates/sui-indexer/src/schema_v2.rs
- crates/sui-indexer/src/store/indexer_analytical_store.rs
- crates/sui-indexer/src/store/mod.rs
- crates/sui-indexer/src/store/pg_indexer_analytical_store.rs
the data prep parts of the analytical endpoints in extended APIs.
the reading queries are relatively straight-forward, this PR is big enough so I split that into a following PR.
local run and make sure that data can be populated properly
> indexer v2: analytical endpoints, write path

- crates/sui-graphql-rpc/src/commands.rs
Fixes the short flag conflicts in the graphql cli server.
---
> [graphql/rpc] fix short flags

- crates/sui-graphql-rpc/schema/current_progress_schema.graphql
- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
- crates/sui-graphql-rpc/src/types/mod.rs
- crates/sui-graphql-rpc/src/types/transaction_block.rs
- crates/sui-graphql-rpc/src/types/transaction_signature.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Add transaction signatures as a base64 value. 
---
> [graphql/rpc] tx sigs

- sdk/docs/package.json
> [docs] fix nextra/vercel caching issue

- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
Fix bug and small cleanup. 
---
> [graphql/rpc] fix bug and cleanup

- .changeset/tall-doors-guess.md
- sdk/zklogin/src/nonce.ts
- sdk/zklogin/src/utils.ts
- sdk/zklogin/test/nonce.test.ts
> Fix string values in zk

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui `v1.12.0` version bump

- crates/sui-snapshot/src/uploader.rs
Formal snapshot creation starts as soon as it notices a db checkpoint directory. And tries to open the db to create a live object set iterator. But because we also do pruning and compaction on the db checkpoint before we upload, a different thread tries to open the db to do pruning and compaction at the same time and panics.
The fix is for formal snapshot creation workflow to wait until db checkpoint is already uploaded before it will consider it.
> Make formal snapshot creation wait until db checkpoint is uploaded

- .changeset/friendly-rocks-eat.md
- sdk/zklogin/src/checks.ts
- sdk/zklogin/src/nonce.ts
> Nonce length check fix in zkLogin SDK

- crates/sui-json-rpc/src/error.rs
> Treat unsupported error as client error

- pnpm-lock.yaml
- sdk/zklogin/vitest.config.ts
> Add source resolution to zklogin tests

- .changeset/many-readers-hide.md
- sdk/create-dapp/templates/react-e2e-counter/move/counter/sources/counter.move
> [create-dapp] remove entry keyword from counter template

- .changeset/slimy-coats-admire.md
- apps/wallet/src/background/accounts/index.ts
- apps/wallet/src/dapp-interface/WalletStandardInterface.ts
- apps/wallet/src/shared/messaging/messages/payloads/account/GetAccountResponse.ts
- apps/wallet/src/shared/messaging/messages/payloads/wallet-status-change/index.ts
- sdk/dapp-kit/src/components/AccountDropdownMenu.tsx
- sdk/dapp-kit/src/hooks/useResolveSuiNSNames.ts
- sdk/dapp-kit/src/walletStore.ts
> [dapp-kit] Show suiNS name or account label in ConnectButton

- crates/sui-graphql-rpc/examples/transaction_block_effects/transaction_block_effects.graphql
- crates/sui-graphql-rpc/schema/current_progress_schema.graphql
- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
- crates/sui-graphql-rpc/src/context_data/sui_sdk_data_provider.rs
- crates/sui-graphql-rpc/src/types/balance.rs
- crates/sui-graphql-rpc/src/types/mod.rs
- crates/sui-graphql-rpc/src/types/object.rs
- crates/sui-graphql-rpc/src/types/object_change.rs
- crates/sui-graphql-rpc/src/types/transaction_block.rs
- crates/sui-graphql-rpc/src/types/transaction_block_kind.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
> [graphql/rpc] transaction block effects

- .changeset/shiny-buses-knock.md
- .eslintrc.js
- sdk/zklogin/src/address.ts
- sdk/zklogin/src/checks.ts
- sdk/zklogin/src/jsonprocessor.ts
- sdk/zklogin/src/nonce.ts
- sdk/zklogin/src/utils.ts
> Fix zklogin ESM

- sdk/docs/pages/kiosk/kiosk-client/querying.mdx
> Kiosk extensions querying docs

- crates/sui-replay/src/replay.rs
- crates/sui-replay/src/types.rs
Fix issue due to skipped protocol versions
Manual
---
> fix system package resolution

- sdk/dapp-kit/src/components/AccountDropdownMenu.tsx
- sdk/dapp-kit/src/hooks/useResolveSuiNSNames.ts
- sdk/dapp-kit/src/index.ts
- sdk/docs/pages/dapp-kit/rpc-hooks.mdx
- sdk/docs/tsconfig.json
> [dapp-kit] export useResolveSuiNSName and show SuiNS name in account dropdown

- crates/sui-rest-api/src/lib.rs
Allows specifying where to nest
Manual
---
> easy/chore: support nesting in starting res-api

- crates/sui-graphql-rpc/schema/current_progress_schema.graphql
- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
- crates/sui-graphql-rpc/src/types/address.rs
- crates/sui-graphql-rpc/src/types/object.rs
- crates/sui-graphql-rpc/src/types/owner.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
When coin type not specified, default to sui
Manual
---
> [graphql/rpc] default to sui coin in balance

- apps/explorer/src/components/OwnedObjects/index.tsx
Before
https://suiexplorer.com/address/0xffc5fa8edc2066f3a6ce9a7b481ac120ace2d21965cd9a44a70ddcfa13724d15
After 
https://explorer-git-gj-explorer-fix-hidden-assets-mysten-labs.vercel.app/address/0xffc5fa8edc2066f3a6ce9a7b481ac120ace2d21965cd9a44a70ddcfa13724d15
> Fix explorer not showing  objects/NFTs

- crates/sui-graphql-rpc/src/types/move_object.rs
Fixes breakage from this pr https://github.com/MystenLabs/sui/pull/14294
Existing
---
> easy: fix broken logic

- crates/sui-transactional-test-runner/src/args.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
Adds ability to advance checkpoint, clock, epoch
---
> data sim 5/x: more test fns

- crates/sui-transactional-test-runner/src/test_adapter.rs
Separates out the executor creator logic to make it easy to inject other executors
Existing adapter tests
---
> [data-sim/easy]: refactor out executor creator

- .changeset/smooth-cups-heal.md
- sdk/dapp-kit/src/hooks/useSuiClientInfiniteQuery.ts
> [dapp-kit] fix typing of useSuiClientInfiniteQuery

- crates/sui-graphql-rpc/schema/current_progress_schema.graphql
- crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
- crates/sui-graphql-rpc/src/types/epoch.rs
- crates/sui-graphql-rpc/src/types/query.rs
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
implement resolvers + apply sorting 
existing tests
---
> [graphql] implement checkpoint and transaction connection resolvers on epoch

- crates/sui-graphql-rpc/examples/epoch/checkpoint_connection.graphql
- crates/sui-graphql-rpc/examples/epoch/transaction_block_connection.graphql
- crates/sui-graphql-rpc/src/types/epoch.rs
as title 
lots of manual tests and these examples will also serve as them
---
> [graphql] examples for epoch.transactionBlockConnection

- crates/sui-graphql-rpc/src/extensions/timeout.rs
Increase for time limit for query.
Manual
---
> [graphql/rpc] increase timeout time to 20s

- Cargo.lock
- crates/simulacrum/Cargo.toml
- crates/simulacrum/src/store.rs
Addresses comment from [PR](https://github.com/MystenLabs/sui/pull/14328/files#r1365924980)
existing
---
> [data-sim] easy: use sync over async for store

- crates/sui-graphql-rpc/src/cluster.rs
- crates/sui-graphql-rpc/src/config.rs
- crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
- crates/sui-graphql-rpc/src/main.rs
- crates/sui-graphql-rpc/src/server/builder.rs
- crates/sui-graphql-rpc/src/server/simple_server.rs
- crates/sui-graphql-rpc/src/types/big_int.rs
- crates/sui-graphql-rpc/src/types/move_object.rs
- crates/sui-graphql-rpc/src/types/move_package.rs
- crates/sui-graphql-rpc/src/types/stake.rs
Chore to cleanup some unwraps in graphql code.
Should largely be NFC.
Existing.
---
> [graphql/rpc] chore: cleanup usage of unwraps

- doc/src/build/zk_login.md
> Update zk_login.md to fix zkey download instructions

- sdk/docs/pages/kiosk/from-v1.mdx
- sdk/docs/pages/kiosk/kiosk-client/kiosk-transaction/managing.mdx
- sdk/docs/pages/typescript/faucet.mdx
- sdk/docs/pages/typescript/sui-client.mdx
> fix some typos in doc

- crates/sui-config/src/certificate_deny_config.rs
- crates/sui-config/src/transaction_deny_config.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Rename fields properly
Tested locally
---
> Make sure tx/cert deny configs use hyphen instead of underscore

- crates/sui-source-validation-service/src/lib.rs
- crates/sui-source-validation-service/tests/tests.rs
Stacked on https://github.com/MystenLabs/sui/pull/14358.
Previously our map is represented in the server by a flattened `(address, symbol)` key for looking up sources.
```json
{ "mainnet" : { "address, symbol" : "source" } }
```
Now the lookup becomes:
```json
{ "mainnet" : { "address" : { "symbol" : "source" } } }
```
This proper nesting simplifies / deduplicates printable representations of our sources map for clients to consume.
Mechanical change covered by existing tests.
---
> move: nest source service map lookups

- crates/sui-config/src/certificate_deny_config.rs
- crates/sui-config/src/transaction_deny_config.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Rename fields properly
Tested locally
---
---
> [Cherypick] Make sure tx/cert deny configs use hyphen instead of underscore (#14393)

- crates/sui-replay/src/lib.rs
Sets the default path for exec sandbox to the "sui-replay/tests/sandbox_snapshots" used in tests.
This way its easy to add sandboxes to track.
Manual
---
> replay: default sandbox path

- external-crates/move-execution/vm-rework/move-vm/runtime/src/interpreter.rs
> fix complaint about unused gas_meter in vm-rework branch

- apps/wallet/src/ui/app/components/accounts/AccountsList.tsx
- apps/wallet/src/ui/app/shared/collapse/index.tsx
https://mysten.atlassian.net/browse/APPS-1845
---
> [Wallet]: Auto collapse SWITCH TO section after selection

- apps/wallet/src/ui/app/components/accounts/AccountsList.tsx
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
- apps/wallet/src/ui/app/shared/collapse/index.tsx
https://mysten.atlassian.net/browse/APPS-1741
---
> [Wallet]: Update text for default

- crates/sui-indexer/src/apis/coin_api_v2.rs
- crates/sui-indexer/src/indexer_reader.rs
Implement get_coin_metadata in the coin api.
Tested locally
---
> [indexer] add get coin metadata

- .github/workflows/release-notes-monitor.yml
Remove randall from mentions for release notes
👀
> Remove randall from mentions for release notes

- crates/sui-framework-tests/src/unit_tests.rs
Fixes breakage due to https://github.com/MystenLabs/sui/pull/14429
Existing
---
> fix broken test dir

- crates/sui-graphql-rpc/src/config.rs
- crates/sui-graphql-rpc/tests/examples_validation_tests.rs
Makes sure bad examples are caught by validator 
e2e
---
> [graphql/rpc] verify invalid cases for examples

- Cargo.lock
- crates/sui-tool/Cargo.toml
- crates/sui-tool/src/db_tool/index_search.rs
For now we have to manually added support for each of them.
---
> [db-tool] add some support for index search

- apps/explorer/src/components/transactions/ProgTxnBlockCard.tsx
- apps/explorer/src/pages/transaction-result/TransactionData.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/TransactionsCard.tsx
- apps/explorer/src/ui/collapsible/CollapsibleCard.tsx
https://mysten.atlassian.net/browse/APPS-1736
- Update to get larger clickable areas on header section
---
> [Explorer]: change default for cards

- crates/sui-indexer/src/apis/extended_api_v2.rs
- crates/sui-indexer/src/apis/indexer_api_v2.rs
- crates/sui-indexer/src/apis/write_api.rs
- crates/sui-indexer/src/indexer_v2.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/store/module_resolver_v2.rs
- Remove allow(dead_code) annotations in a few places
- Registr WriteApi which forwards to a fullnode
- implements the get_total_transactions api
---
> indexerv2: few cleanups

- crates/sui-analytics-indexer-derive/src/lib.rs
- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/tables.rs
- crates/sui-analytics-indexer/src/writers/parquet_writer.rs
- added support for enums and other remaining types
- simplified macro
> [analytics] support all required parquet types

- crates/sui-graphql-rpc/src/config.rs
- crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
add limit on number of variables
manual, unit coming soon
---
> [graphql/rpc] limit variables

- narwhal/primary/src/consensus/bullshark.rs
- narwhal/primary/src/consensus/tests/bullshark_tests.rs
- narwhal/primary/src/consensus/tests/consensus_tests.rs
- narwhal/primary/src/consensus/tests/leader_schedule_tests.rs
- narwhal/primary/src/consensus/tests/randomized_tests.rs
Some additional clean up on top of https://github.com/MystenLabs/sui/pull/14462/files
CI
---
> [Narwhal] additional consensus clean up

- crates/sui-single-node-benchmark/move_package/sources/benchmark.move
> [benchmark] Fix Move warning

- apps/explorer/src/pages/object-result/views/ObjectView.tsx
> [Explorer]: truncate address on objectView

- crates/sui-core/src/authority.rs
- crates/sui-core/src/execution_driver.rs
- crates/sui-core/src/transaction_manager.rs
- crates/sui-core/src/unit_tests/transaction_manager_tests.rs
Reverts MystenLabs/sui#13433
High TPS variance was detected by @lxfind in single node benchmark.
> Revert "[Sui] Roll forward parallelizing spawning tasks to execute transactions"
