apps/core/src/utils/transaction/getObjectChangeSummary.ts, apps/explorer/src/components/GasBreakdown/index.tsx, apps/explorer/src/pages/transaction-result/transaction-summary/BalanceChanges.tsx, apps/explorer/src/pages/transaction-result/transaction-summary/ObjectChanges.tsx, apps/explorer/src/ui/CoinsStack.tsx, apps/explorer/src/ui/TransactionBlockCard.tsx
- Added `Published` module - Slack ref here https://mysten-labs.slack.com/archives/C032676BWGN/p1683072202860129?thread_ts=1683057960.874759&cid=C032676BWGN
- Refactor code to use `Disclosure` for Object open/close panel
- Wrap texts on ipad viewport
- Add `relative` to fix random white space on bottom of txn page
- Address link for recipient
---
=> [explorer]: Refactor code to use Disclosure + Add Published in Summary view

crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/consensus_handler.rs
Getting better visibility to the type of transactions send via consensus adapter. Currently we can't differentiate the volume which in some cases is helpful.
---
=> [refactor] add transaction type to consensus_adapter metrics

crates/sui-tool/src/db_tool/mod.rs
Enables short form of options to make commands less verbose.
```
Usage: sui-tool db-tool --db-path <DB_PATH> dump [OPTIONS] --store <STORE_NAME> --table-name <TABLE_NAME> --page-size <PAGE_SIZE> --page-num <PAGE_NUMBER>
Options:
-s, --store <STORE_NAME>       The type of store to dump [possible values: validator, index, epoch]
-t, --table-name <TABLE_NAME>  The name of the table to dump
-p, --page-size <PAGE_SIZE>    The size of page to dump. This is a u16
-n, --page-num <PAGE_NUMBER>   The page number to dump
-e, --epoch <EPOCH>            The epoch to use when loading AuthorityEpochTables
-h, --help                     Print help
```
Manual test
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, …
=> [easy] allow short commands for db dump

apps/wallet/src/ui/app/wallet/locked-page/index.tsx
Saw someone ask for this in Discord and thought it would be a nice addition so users can just type in their password after clicking to open the extension! Let me know if there are any objections here @mystie711 😄 
https://user-images.githubusercontent.com/7453188/236563681-4d529934-e9d3-4194-9cbd-d7244e6145c3.mov
---
N/A
=> [wallet-ext] auto-focus the password input on the locked screen

crates/mysten-metrics/src/lib.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/synchronizer.rs
Add more metrics to help locate certificate handler latency spikes.
---
=> [Narwhal] enhance latency metrics for certificate handler

crates/sui-adapter/src/adapter.rs, crates/sui-core/src/transaction_input_checker.rs, crates/sui-core/src/unit_tests/move_package_tests.rs, crates/sui-types/src/metrics.rs
Adds timer histogram metrics for success and timeout scenarios, for both PTB level and module level verificaiton.
[do we want package level too?] 
Unit tests
---
=> [verifier] add prom histogram metrics for verifier

Cargo.lock, crates/sui-faucet/src/faucet/simple_faucet.rs, crates/sui-tool/Cargo.toml, crates/sui-tool/src/commands.rs, crates/sui/src/client_commands.rs, crates/sui/src/unit_tests/cli_tests.rs, crates/sui/tests/full_node_tests.rs, crates/test-utils/src/transaction.rs
This PR adds two features:
1. In sui client, extend the ability to serialize a transaction to support both unsigned and signed transaction.
2. In sui-tool, add a new command sign-transaction that would ask all validators to sign a transaction, but not execute the cert.
=> Add sign-transaction to sui-tool

crates/sui-core/src/authority.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-json-rpc/src/governance_api.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-storage/src/indexes.rs, crates/sui-tool/src/db_tool/db_dump.rs, crates/sui-tool/src/db_tool/mod.rs
Fixes: https://github.com/MystenLabs/sui/issues/7686
Manual testing
---
=> Fix Dynamic Field Cursor Index Bug

apps/explorer/src/components/GasBreakdown/index.tsx, apps/explorer/src/ui/DescriptionList.tsx, apps/explorer/src/ui/Link.tsx, apps/explorer/src/ui/TransactionBlockCard.tsx, apps/explorer/src/ui/stories/SplitPanes.stories.tsx
- Update link fonts to `body`, requested by @mystie711 
- Update alignment for Gas card
---
=> [explorer]: update link fonts

crates/sui-faucet/src/bin/merge_coins.rs
Added a script to do merge/split coins instead of having to use CLI
---
=> [Faucet] Adding merge/ split coin functions from rust script

narwhal/consensus/benches/process_certificates.rs
`make_consensus_store` doesn't exist anymore and is making build fail https://github.com/MystenLabs/sui/actions/runs/4910003494
---
=> [fix] failing build due to missing import

Cargo.lock, crates/sui-core/src/checkpoints/checkpoint_executor/metrics.rs, crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs, crates/sui-core/src/checkpoints/metrics.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-network/src/state_sync/metrics.rs, crates/sui-network/src/state_sync/mod.rs, crates/sui-types/Cargo.toml, crates/sui-types/src/messages_checkpoint.rs
as title
CI
---
Eecord last executed timestamp age v.s. the timestamp itself
=> record last executed timestamp age v.s. the timestamp itself

.changeset/young-seals-mix.md, apps/wallet/src/ui/app/pages/approval-request/transaction-request/TransactionDetails/Command.tsx, sdk/typescript/src/builder/Transactions.ts, sdk/typescript/test/e2e/object-vector.test.ts
Fix a bug where there is a type mismatch in the user input and BCS schema
Added an e2e test to add `type` hint for `makeMoveVec`, without the changes in this PR the test will fail with the following error
```
FAIL  test/e2e/object-vector.test.ts > Test Move call with a vector of objects as input > Test object vector
Error: Incorrect data passed into enum "TypeTag", expected object with properties: "bool | u8 | u64 | u128 | address | signer | vector | struct | u16 | u32 | u256".
Received: ""0x60c831c44574dab69122c964cedc03bf18a23680a713c3ea41240b066187e26d::entry_point_vector::Obj""
❯ _BCS.encodeEnum ../bcs/src/index.ts:1269:17
1267|         }
1268|         if (typeof data !== "object") {
1269|           throw new Error(
|                 ^
1270|             `Incorrect data passed into …
```
=> [ts-sdk] Fix type definition for MakeMoveVec

Cargo.lock, crates/sui-proxy/src/admin.rs, crates/sui-proxy/src/consumer.rs, crates/sui-proxy/src/middleware.rs, crates/workspace-hack/Cargo.toml
Summary:
* raise the metrics post limit to 5 MB from 2 MB.
* added instrumentation and also an additional header check for content-length
* move the mimir decode/encode to a dedicated spawn blocking pool to prevent (potentially) blocking the async runtime
Test Plan:
local testing and testnet
---
=> [sui-proxy/increase post body limit to 5 MB]

crates/sui-proxy/src/admin.rs
Summary:
* mimir is getting close to 15 seconds for posting in the p95 graphs.
* bump this timeout to 30 to buy us time to root cause
Test Plan:
locally & cargo build
---
=> [sui-proxy/increase mimir timeout]

narwhal/primary/src/certificate_fetcher.rs, narwhal/primary/src/metrics.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/synchronizer.rs, narwhal/primary/src/tests/primary_tests.rs, narwhal/primary/src/tests/synchronizer_tests.rs, narwhal/types/src/error.rs
We have observed correlations among spikes in certificates in votes, send certificate handler p95 latency, and observed average latency when submitting to consensus. This issue can be observed in many validators on testnet and private-testnet too. It seems the logic to request missing parent certificates from header proposer is problematic, where it is easy to cause a surge of certificates and overwhelm Narwhal, e.g. with requests to certificate stores.
In this PR, a limit is added to request a missing parent certificate only from one header proposer. Additional protections against byzantine primaries sending unrequested parent certificates and overwhelming the system have also been added.
This change weakens the guarantee of certificate propagation via header proposal and voting. A …
=> [Narwhal] deduplicate missing parents in vote requests

crates/sui-json-rpc/src/error.rs, crates/sui-json-rpc/src/logger.rs, crates/sui-json-rpc/src/read_api.rs
Most of the errors we return in `sui-json-rpc` are `anyhow::Error`s that then get converted to `RpcError`. Or, if we keep things in `sui_json_rpc::Error`, there is a catch-all `From` implementation that converts all variants to `CallError::Failed`.
In this PR, the `From` implementation is expanded to map some variants to `RpcError::Call(CallError::InvalidParams` instead, so that we can return different error codes rather than defaulting to `-32000` for everything.
This will help w/ differentiating server from client errors, and we can make use of this for alerting on error logs. 
Start with `UserInputErrors`, which now map to error code `-32602`. Also log error code if available.
In terms of performance, there shouldn't be any impact since we do the same number of conversions. Only, …
=> 1/n improve sui-json-rpc error codes and handling

crates/sui-open-rpc/spec/openrpc.json, crates/sui-open-rpc/src/examples.rs
Adding examples to JSON RPC reference. Changing suix_getownedobjects to return an objectspage.
Locally
---
=> Adding examples to RPC API ref

crates/sui-tool/src/db_tool/index_search.rs, crates/sui-tool/src/db_tool/mod.rs
Enables searching DB by key and range
Example
This searches the `transactions_from_addr` index for 3 items starting from key `(0x0, 0)`
```
sui-tool db-tool --db-path $INDEX_STORE_PATH index-search-count -t "transactions_from_addr" -s " 0x0000000000000000000000000000000000000000000000000000000000000000  , 0 "  -c 3
(0x0000000000000000000000000000000000000000000000000000000000000000, 0): TransactionDigest(Cgww1sn7XViCPSdDcAPmVcARueWuexJ8af8zD842Ff43)
(0x0000000000000000000000000000000000000000000000000000000000000000, 1): TransactionDigest(ENSA1UVsdNfa66Hifs8YmELAPMUraTkMLnb5vBma7yjG)
(0x0000000000000000000000000000000000000000000000000000000000000000, 2): TransactionDigest(6JrvQmai4CfoepqArnJYa4sRQbRAY4bSXc5tY7ub4HzJ)
```
While this searches the `transactions_from_addr` index for all keys …
=> Index store search debug util

.github/auto-merge.yml, .github/dependabot.yml, .github/workflows/dependabot-auto-merge.yml
Otherwise it takes effort to approve individual github workflow action updates.
Also, make dependabot run more frequently to catch up on backlogs.
CI
---
=> [CI] allow automatic merging of github action updates

crates/mysten-metrics/src/lib.rs, crates/sui-node/src/main.rs, crates/sui-proxy/src/main.rs
As title. This will be a useful thing to watch during testnet wipe
tested locally
---
Expose chain identifier as a metric
=> expose chain identifier as a metric

crates/sui-tool/src/commands.rs, crates/sui-tool/src/lib.rs, crates/sui-types/src/error.rs, crates/typed-store/src/rocks/errors.rs
As title. Also remove some stale implementations and use concise keys.
Example:
```
./sui-tool fetch-object --id 0xa577f89fcadd5805f2a9ae0b12670d3051d938e34c702484d2a5b15dd92bc057   --fullnode-rpc https://rpc.mainnet.sui.io:443
```
locally tested sui-tool
---
Allow some sui tool commands to take a fullnode-rpc arg and use the latest committee. Also remove some stale implementations and use concise keys.
=> allow some sui tool commands to take a fullnode-rpc arg and use the latest committee

Cargo.lock, crates/sui-benchmark/src/workloads/adversarial.rs, crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/test_utils.rs, crates/sui-indexer/tests/integration_tests.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-json-rpc/tests/subscription_tests.rs, crates/sui-sdk/src/wallet_context.rs, crates/sui-source-validation/Cargo.toml, crates/sui-source-validation/src/tests.rs, crates/sui-test-transaction-builder/src/lib.rs, crates/sui/tests/full_node_tests.rs, crates/test-utils/src/transaction.rs, sui_programmability/examples/nfts/sources/devnet_nft.move
First step towards moving functions in `test-utils/transaction` to places where they belong better. This PR deals with some of functions that take in a `WalletContext`. Some of them are moved to `wallet_context.rs` and a few are moved to the caller site. More wallet context functions will be moved in following PRs.
It's all tests.
---
=> [1/x] move some test util functions to wallet context

crates/mysten-metrics/src/lib.rs
Fix uptime metrics by providing the right label names.
Tested locally by starting a node and see it not crash.
---
Fix uptime metrics by providing the right label names.
=> Fix uptime metrics

crates/sui-protocol-config/src/lib.rs, scripts/compatibility/check-protocol-compatibility.sh
Usage:
```
$ API_USER=incoming_metrics API_KEY=xxxxxxxx ./scripts/compatibility/check-protocol-compatibility.sh mainnet
Found following versions on mainnet:
87 1.0.0-ae1212baf
10 1.0.0-ae1212baf8
1 1.0.0-ae1212baf-dirty
1 1.0.0-ae1212b
1 1.0.0-92d2c16dc
Using most frequent version 1.0.0-ae1212baf for compatibility check
Checking protocol compatibility with mainnet (ae1212baf)
Checking out mainnet snapshot files
Checking for changes to snapshot files
Running snapshot tests...
Finished test [unoptimized + debuginfo] target(s) in 0.61s
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 459`
Running unittests …
```
=> Check for any changes to protocol config snapshots relative to deployed commits

Cargo.lock, crates/sui-node/Cargo.toml, crates/sui-node/src/metrics.rs, crates/sui-proxy/src/middleware.rs
Summary:
* add snappy encoding to the sui-node/proxy
Test Plan:
data suggests that it would be worthwhile compressing this for transport between the sui-node and sui-proxy
---
=> [metrics/add snappy compression to sui-node/sui-proxy]

crates/sui-adapter-transactional-tests/tests/upgrade/dep_override.move, crates/sui-adapter-transactional-tests/tests/upgrade/linkage.exp, crates/sui-adapter-transactional-tests/tests/upgrade/linkage.move, crates/sui-adapter-transactional-tests/tests/upgrade/new_types.move, crates/sui-adapter-transactional-tests/tests/upgrade/transitive_linkage.exp, crates/sui-adapter-transactional-tests/tests/upgrade/transitive_linkage.move, crates/sui-transactional-test-runner/src/test_adapter.rs
Implements logic to map the most recent upgraded dependency to the original dependency's address for compilation, then restores dependency addresses when upgrading. We need the logic so that compilation succeeds in test setup (otherwise the compiler shouts about duplicate defined modules).
When a package is upgraded, we store an entry that maps to the original package name for that upgraded package. For those upgraded packages that are later used as dependencies, we substitute the address of the original package before compiling, and restore it after compiling and before upgrading.
Ran tests.
=> move: improve upgrade transactional test setup for dependencies

crates/sui-indexer/benches/indexer_benchmark.rs, crates/sui-indexer/migrations/2022-11-28-204251_addresses/down.sql, crates/sui-indexer/migrations/2022-11-28-204251_addresses/up.sql, crates/sui-indexer/migrations/2022-12-01-034426_objects/up.sql, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/models/addresses.rs, crates/sui-indexer/src/schema.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/src/types.rs
For feature requests of `addresses` and `active_addresses` tables, also logging he first and last tx & timestamp for daily active address later.
run locally to make sure that 
- addresses table and active_addresses table can be populated properly
- last_appearance_tx|time is updated but first_appearance_tx|time is static
=> indexer: address & active address tables

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_handler.rs
Latest mainnet epoch has this flag [on](https://metrics.sui.io/explore?left=%7B%22datasource%22:%22e6b9ae38-5a18-477b-bd96-c67b655dd4aa%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22e6b9ae38-5a18-477b-bd96-c67b655dd4aa%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22epoch_flags%7Bnetwork%3D%5C%22mainnet%5C%22%7D%22,%22hide%22:false,%22interval%22:%2260s%22,%22range%22:true,%22refId%22:%22C%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D&orgId=1) (and it has been for a while now)
=> [checkpoints] Remove legacy code before InMemoryCheckpointRoots feature

crates/sui-storage/src/indexes.rs, crates/sui-types/src/object.rs
transactions_to_addr now includes both address and object IDs.
Related posts are 
https://mysten-labs.slack.com/archives/C04FG4Q7YJ3/p1682369162080879
https://mysten-labs.slack.com/archives/C04HS54LHUM/p1682039873458439
CI test
run local FN + Explorer and make sure 0x5 is not showing as address any more.
=> fn: remove object IDs from transactions_to_addr index

.cargo/config, crates/sui-indexer/tests/integration_tests.rs, narwhal/node/src/benchmark_client.rs
clippy seems to be ignoring files when those depend on features that aren't enabled when it runs. This is leading to build failures (ex [this](https://github.com/MystenLabs/sui/actions/runs/4942463072/jobs/8836005749) and [this](https://github.com/MystenLabs/sui/actions/runs/4910003494)) frequently as our rust CI is passing but when it comes to build CI it fails and mostly goes undetected.
The PR is enabling `--all-features` so we align the rust & build CI. It is also fixing some linter failures.
Did run locally
---
=> [chore] clippy to run with all features enabled

apps/explorer/src/pages/transaction-result/programmable-transaction-view/InputsCard.tsx, apps/explorer/src/pages/transaction-result/transaction-summary/ObjectChanges.tsx
- Right alignment for texts 
- Slack for context: https://mysten-labs.slack.com/archives/C032676BWGN/p1683650782815109
- We are getting ObjectType as these format
```
0x2::coin::Coin<0x2::sui::SUI>
```
or 
```
0x6e8afef4fe19f8981ca0b651b2ca4e60191790b7cef2ba8664f0f2e073803f3d::suicat::Global
```
With the original way to split, we will only get `Coin` as the `typeName`
---
=> [explorer]: fix render for object type

crates/sui-json-rpc/src/transaction_execution_api.rs
Add `error_span!`s to the fullnode write paths to distinguish error messages due to execution, dev-inspect and dry-run.
Dry run a transaction that would cause an invariant violation, and note that the error that is produced by the fullnode mentions `dev_inspect_transaction_block` in its span:
Test move package:
```move
module example::example {
use sui::dynamic_object_field as ofield;
use sui::object::{Self, UID};
use sui::transfer;
use sui::tx_context::TxContext;
struct S has key, store { id: UID  }
fun init(ctx: &mut TxContext) {
let parent = S { id: object::new(ctx) };
let child  = S { id: object::new(ctx) };
ofield::add(&mut parent.id, 0, child);
transfer::share_object(parent);
}
entry fun f(_s: &S) {}
}
```
JS to dry-run the transaction:
```js
const PACKAGE_ID = /* ... */;
const …
```
=> [sui-json] Spans for fullnode write paths

crates/sui-core/src/authority/authority_per_epoch_store.rs
Full node might restore from some old snapshot - this is fine and does not need to check for InMemoryCheckpointRoots flags
=> [checkpoints] do not assert InMemoryCheckpointRoots on full nodes

crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui-framework/docs/clob.md, crates/sui-framework/packages/deepbook/sources/clob.move
Add taker_commission and maker_rebate into OrderFilled events
---
---------
---
=> [Deepbook] Add commission and rebates into event of OrderFilled

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/transaction_input_checker.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-storage/src/indexes.rs, crates/sui-types/src/error.rs
Update `authority.rs` to use `SuiResult` instead of `anyhow::Error`. Some places that depended on `anyhow::Error` needed to be updated. Most noticeably, previously, because of `anyhow::Error`, there's no need to convert the underlying `SuiError` into `Error` (`SuiJsonRpcError`) where Rust can then do the conversion into `Error` (`RpcError`), as RpcError supports `from anyhow::Error`. Now though, we need to explicitly convert into the intermediary, causing instances where we have `.map_err(Error::from)?.map_err(Error::from)?`. One thought is to have an `_internal()` fn for all methods that rely on calls to state and other services.
Existing unit + integration tests. Manually call each api endpoint and verify that success and error responses are as expected
---
If your changes are not …
=> 2/n improve sui-json-rpc error codes and handling

crates/sui-config/src/node.rs, crates/sui-core/src/authority/authority_store_pruner.rs
PR adds an option to enable periodic background compactions for the objects table, ensuring that all SST files periodically go through the compaction process. This feature helps address the issue where we observe a large number of L4 SST files consisting mostly of range deletes but not undergoing the compaction process due to internal RocksDB heuristics.
This approach is intended to be used as a complement to aggressive pruning and is disabled by default. 
It is somewhat equivalent to RocksDB's `periodic_compaction_seconds` setting, but the latter is not very flexible and can cause dramatic resource consumption once enabled. The approach implemented in the PR processes one SST file at a time
=> periodic compaction of sst files

crates/sui-replay/src/data_fetcher.rs, crates/sui-replay/src/replay.rs, crates/sui-replay/src/types.rs
Since we reset testnet, no need for testnet-specific logic we had to get around the epoch speedrun during safemode.
Manual
---
=> Remove testnet specific logic in replay

apps/wallet/src/ui/app/components/active-coins-card/CoinItem.tsx, apps/wallet/src/ui/app/components/coin-icon/index.tsx, apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx, apps/wallet/src/ui/app/pages/home/tokens/coin-balance/index.tsx, apps/wallet/src/ui/app/shared/indented-title/index.tsx
- Use coin coinUrl from coinMetaData fallback to default icon
- Use coin Name from coinMetaData instead of symbol
---
=> use coinMetada in wallet

apps/explorer/src/components/validator/ValidatorMeta.tsx, apps/explorer/src/hooks/useSearch.ts, apps/explorer/src/pages/validator/ValidatorDetails.tsx, apps/explorer/src/pages/validators/Validators.tsx
- Search by validator pool ID, or validator address 
- Get to the validator details page by the Pool ID or Address
- Show `--` for validators with unavailable epoch data/rewards 
---
=> Adds support for validator pool ID 

sdk/typescript/README.md
There was a typo in the [`Transfer SUI`](https://github.com/coccoinomane/sui/blob/1090c2d487c574b7f5b58c8775a3b0060c4dee19/sdk/typescript/README.md#transfer-sui) section of the README of the SDK.
The error prevented the example code to work properly, resulting in the following error:
```
StructError: At path: amounts -- Expected an array value, but received: [object Object]
```
The error was reported by several users on Discord, e.g. https://discord.com/channels/916379725201563759/955861929346355290/1098875792873762857
=> docs-sdk: fixed typo in README splitCoins example

crates/sui-indexer/src/handlers/checkpoint_handler.rs
The was turned off temp. in case mainnet traffic went crazily high, which turns out not necessary, also these tables are useful to serve tx queries;
Also requested by partner here https://mysten-labs.slack.com/archives/C047ZSH8KV5/p1683882143957239
local run and to make sure that `input_objects` and `recipients` population are back on
=> indexer: re-populate input objects & recipients

crates/sui-core/Cargo.toml, crates/sui-core/src/transaction_input_checker.rs, crates/sui-core/src/unit_tests/move_package_tests.rs, external-crates/move/move-bytecode-verifier/src/meter.rs, sui-execution/latest/sui-verifier/src/lib.rs, sui-execution/latest/sui-verifier/src/meter.rs
* Add `Package` and `Transaction` metering scope. Not used yet though to keep functionality same. Will iterate on this in subsequent PR.
* Implement our own meter in Sui so we can fine-tune, log, etc as needed.
---
=> Add tx, package scope. Use Sui meter for verifier

crates/sui-cluster-test/src/cluster.rs, crates/sui-config/src/builder.rs, crates/sui-config/src/genesis_config.rs, crates/sui-config/src/node.rs, crates/sui-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm/src/memory/swarm.rs, crates/sui/src/sui_commands.rs
This PR makes the following clean ups in genesis configs:
1. Removes grpc related fields from genesis config because they are never set differently other than the default value
2. Remove committee_size from genesis config because it's never used.
3. Merge ValidatorConfigInfo and ValidatorGenesisInfo, rename to ValidatorGenesisConfig.
4. Move some initializers into constructors, for clarity
=> Some cleanups in GenesisConfig

crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-tool/src/db_tool/mod.rs, crates/sui-types/src/base_types.rs, crates/typed-store-derive/src/lib.rs, crates/typed-store/src/rocks/mod.rs
There are needs to repair corrupted databases sometimes. Adding a few commands to remove transaction and its outputs, and remove lock.
Tested on fullnodes.
---
=> [DbTool] add a few commands to modify database with minimal safety checks

external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/binary_samples.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/code_unit_tests.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/dependencies_tests.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/large_type_test.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/limit_tests.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/locals.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/many_back_edges.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/negative_stack_size_tests.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/reference_safety_tests.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs, external-crates/move/move-bytecode-verifier/bytecode-verifier-tests/src/unit_tests/vec_pack_tests.rs, external-crates/move/move-bytecode-verifier/fuzz/fuzz_targets/code_unit.rs, external-crates/move/move-bytecode-verifier/fuzz/fuzz_targets/compiled_module.rs, external-crates/move/move-bytecode-verifier/fuzz/fuzz_targets/mixed.rs, external-crates/move/move-vm/integration-tests/src/tests/instantiation_tests.rs, external-crates/move/move-vm/integration-tests/src/tests/invariant_violation_tests.rs, external-crates/move/move-vm/integration-tests/src/tests/leak_tests.rs
`verify_module` no longer exists -- fixing the build by using `verify_module_unmetered`.
This would fail before this change, and now does not:
```
external-crates/move/move-bytecode-verifier/fuzz$ cargo build
```
=> [move/fuzz] Fix up verifier fuzz targets after metering changes

apps/core/src/hooks/useGetOriginByteKioskContents.ts, apps/core/src/index.ts, apps/wallet/src/ui/app/hooks/useGetNFTs.ts, apps/wallet/src/ui/app/hooks/useOwnedNFT.ts, apps/wallet/src/ui/app/pages/home/nfts/index.tsx
Adds some rudimentary support for displaying OB Kiosk items on mainnet. There's definitely some improvements we can make here, as we currently have to merge lists of objects with one being a paginated API to `getOwnedObjects` and the other being a series of RPC requests in order to fetch the contents of a kiosk
adapted from #11505 
---
=> [wallet-ext] - add support for displaying OriginByte kiosk

Cargo.lock, crates/sui/Cargo.toml, crates/sui/src/client_commands.rs, sui-execution/latest/sui-verifier/src/meter.rs
As described. Example
`sui client verify-bytecode-meter  crates/sui-framework/packages/sui-framework/`
```
Running bytecode verifier for 41 modules
|     Module      |    Function    
------------------------------------------------
Max       |    16000000     |    16000000    
Used       |     1393870     |      4130    
```
Manual
---
=> verifier: CLI show meter ticks used

crates/sui-cluster-test/src/test_case/shared_object_test.rs, crates/sui-core/src/unit_tests/transaction_deny_tests.rs, crates/sui-cost/tests/empirical_transaction_cost.rs, crates/sui-sdk/src/wallet_context.rs, crates/sui/tests/full_node_tests.rs, crates/sui/tests/simulator_tests.rs, crates/test-utils/src/transaction.rs
This PR moves all the tests in test-utils/transaction that use `WalletContext` to elsewhere.
---
=> move more functions from test util to wallet context

Cargo.lock, crates/sui-types/Cargo.toml
The `VERSION` constant that populates the output from `sui -V` was recently moved to crate `sui-types` (with fixed version `0.1.0`), from crate `sui` which inherited its version from the workspace (which gets bumped to match the release version).
Have `sui-types` inherit version from workspace as well, to fix the version output.
```
sui$ cargo run --bin sui -- -V
sui 1.2.0-f6494ee216-dirty
```
Where previously it was:
```
sui 0.1.0-f6494ee216
```
---
Fix the output from `sui -V`, which was incorrectly reporting version `0.1.0`.
=> [sui] Fix version output by CLI

crates/sui-json-rpc/src/coin_api.rs
The current implementation of `get_coin_metadata` relies on `get_past_object_read`, which stops working if the fullnode has pruning enabled. This is unnecessary because we only need the latest version of the coinmetada object(if it is wrapped, then it's okay to return null).
tested locally
```
curl --location 'https://mainnet.sui.rpcpool.com' \
--data '{
"jsonrpc":"2.0",
"id":1,
"method":"suix_getCoinMetadata",
"params":["0x2::sui::SUI"]
}'
```
```
{
"result": {
"decimals": 9,
"name": "Sui",
"symbol": "SUI",
"description": "",
"iconUrl": null,
"id": "0x9258181f5ceac8dbffb7030890243caed69a9599d2886d957a9cb7656af3bdb3"
},
"id": 1
}
```
---
If your changes are not user-facing and not a breaking change, you can skip the following …
=> [rpc][bugfix] Remove the usage of get_past_object_read from get_coin_metadata

.github/workflows/turborepo.yml, apps/explorer/package.json, apps/wallet/package.json, dapps/sponsored-transactions/package.json, package.json, pnpm-lock.yaml, sdk/wallet-adapter/site/package.json
This adds [manypkg](https://github.com/Thinkmill/manypkg), which will now run in CI to validate package versions are consistent across the monorepo.
locally + new CI
---
=> Add Manypkg

apps/wallet/src/background/Permissions.ts, apps/wallet/src/background/index.ts
* when deleting accounts (will be supported for Qredo) make sure we clear permissions so we don't report wrong accounts to dapps
part of APPS-760
=> wallet-ext: update accounts in permissions when they change

Cargo.lock, crates/sui-move/Cargo.toml, crates/sui-types/Cargo.toml
We have refactored enough code such that we can get rid of the dependency to test-utils in sui-types.
Removing it here will significantly speed up our builds, because for arbitrary changes we don't have to always rebuild sui-types and sui-framework.
The last bit of the circular dependency is in sui-core, which isn't yet ready to be removed.
=> Remove test-utils dep from sui-types and sui-move

crates/sui-json-rpc/src/error.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-sdk/src/error.rs
Today, when we make an executeTransactionBlock call, we get an rpc error that looks like 
```{"jsonrpc":"2.0","error":{"code":-32000,"message":"Transaction has non recoverable errors from at least 1/3 of validators: [(UserInputError { error: ObjectNotFound { object_id: 0x8ef76f56c399633a2eb310bca9124e5f2f38ce739eaacbb6600688804e078448, version: Some(SequenceNumber(2)) } }, 7500, [k#8dcff6d1.., k#99f25ef6.., k#addeef94..])]."},"id":1}%```
This is difficult to work with: for example, if in the faucet, we want to stop retrying if we receive a `ObjectVersionUnavailableForConsumption` error, we'd need to parse it from the message string.
The source of this comes from transaction orchestrator https://github.com/MystenLabs/sui/blob/main/crates/sui-core/src/transaction_orchestrator.rs#L155 …
=> for errors that consist of vectors of errors, return all errors as an object array so downstream clients can handle as desired

apps/core/tailwind.config.ts, apps/explorer/src/components/GasBreakdown/index.tsx, apps/explorer/src/pages/transaction-result/TransactionData.tsx
- Update gas payment section so it will always display at least 2 items
- When there are over 10 items, it will become scollable
- https://mysten.atlassian.net/browse/APPS-460
- DEMO: https://explorer-66hwh2ogf-mysten-labs.vercel.app/txblock/J4zaDNsMTAMrpFe5epDPzRwVR9TwNmLQx8mzKBvxvkA9?network=testnet
---
=> [explorer]: update gas payment section

apps/wallet/src/background/keyring/Account.ts, apps/wallet/src/background/keyring/DerivedAccount.ts, apps/wallet/src/background/keyring/QredoAccount.ts, apps/wallet/src/ui/app/components/AccountBadge.tsx, apps/wallet/src/ui/app/components/BadgeLabel.tsx, apps/wallet/src/ui/app/components/menu/content/AccountActions.tsx, apps/wallet/src/ui/app/redux/slices/account/index.ts
* implements only the display part, the actual work on Keyring side will follow
* to test now just add a mock qredo account in keyring
part of APPS-760
=> wallet-ext: add support for displaying qredo accounts

apps/core/src/hooks/useGetOwnedObjects.ts
* reduce it to 10 seconds to avoid issue with not showing new objects in nfts page
fixes https://mysten-labs.slack.com/archives/C04SPGVSPM5/p1684185722179829
=> wallet-ext: update useGetOwnedObjects stale time

apps/core/src/hooks/useGetOriginByteKioskContents.ts, apps/explorer/src/components/OwnedObjects/index.tsx, apps/explorer/src/ui/Modal/ImageModal.tsx, apps/explorer/src/ui/Radio.tsx
Adds basic support for displaying kiosk items on the Owned Object page. To be improved in the future when we have better RPC support
This is an alternate to #11943 which tried to hack around the pagination logic
[Sample URL](https://explorer-git-mamos-explorer-kiosk-tabs-mysten-labs.vercel.app/address/358d9a1e0b99296a4560ef98f88565b8dcce7d33c7c3d46f75c5058c3a0e524f?network=mainnet)
---
=> [explorer] - support for kiosk display 

.changeset/early-dancers-walk.md, crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/error.rs, crates/sui-json-rpc/src/governance_api.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-json-rpc/src/move_utils.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, sdk/typescript/test/e2e/object-display-standard.test.ts
Replace anyhow errors with Error enum on sui-json-rpc where possible
---
[API behavioral changes] - rpc methods that result in errors of variant `UserInputError`, `SuiRpcInputError`, `SuiError::TransactionNotFound` or `SuiError::TransactionsNotFound` now return error code `-32602` instead of `-32000`.
=> 3/n improve sui-json-rpc error codes and handling

Cargo.lock, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-types/src/storage.rs, crates/typed-store/Cargo.toml, crates/typed-store/src/rocks/mod.rs, crates/typed-store/src/rocks/tests.rs, crates/typed-store/src/test_db.rs, crates/typed-store/src/traits.rs
Specify iter range keys with `std::ops::RangeBounds`
Next PR cleans up parts of the code that could use more constrained bounds
Unit tests
---
=> add explicit iter range specifications

crates/sui-core/src/unit_tests/move_package_tests.rs, crates/sui-core/tests/staged/sui.yaml, crates/sui-types/src/execution_status.rs, sui-execution/latest/sui-adapter/src/adapter.rs, sui-execution/latest/sui-verifier/src/id_leak_verifier.rs, sui-execution/latest/sui-verifier/src/lib.rs, sui-execution/latest/sui-verifier/src/verifier.rs
Previously the metered verifier did not disambiguate Sui verifier errors when blocking at signing.
This PR changes that such that we only block when meter timesout.
Normal 
---
=> only block sui verifier on timeouts

crates/sui-framework-tests/src/lib.rs
Run deepbook test among other `sui-framework-tests`.  Also separate framework tests each into their own test so that it's possible to run the tests for just one package.
```
sui/crates/sui-framework-tests$ cargo nextest run -- run_deepbook_tests
```
=> [sui-framework] Add deepbook tests

crates/sui-core/src/authority/authority_test_utils.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/unit_tests/authority_tests.rs, external-crates/move/move-vm/runtime/src/interpreter.rs
Make paranoid mode for native calls work correctly.
We may or may not enable paranoid mode but the change seems safe
Added test
---
=> Push types to type stack when calling a native

crates/sui-swarm-config/src/network_config_builder.rs, crates/sui/src/unit_tests/validator_tests.rs, crates/sui/src/validator_commands.rs
This PR adds a validator command that prints out the base64 representation of a transaction that updates a validator's gas price quote to a new value. I considered making this part of the original `UpdateGasPrice` command but decided it's different enough to be its own command, primarily because the active address of the wallet context can be someone other than the transaction sender in the case of the new command.
Added a test.
---
=> [sui cli] add validator command to print out raw gas price setting txn

apps/wallet/src/ui/app/background-client/index.ts, apps/wallet/src/ui/app/helpers/queryClient.ts, apps/wallet/src/ui/app/hooks/useQredoAPI.ts, apps/wallet/src/ui/app/hooks/useQredoInfo.ts, apps/wallet/src/ui/app/pages/qredo-connect/hooks.ts, apps/wallet/src/ui/app/pages/qredo-connect/utils.ts, apps/wallet/src/ui/index.tsx
* update bg client for new messages
* use hooks for api and data from bg service - use queries for that data that invalidate using messages from bg service
* allow queries bypass persisted data using metadata
part of APPS-760
=> wallet-ext: ui hooks for qredo

Cargo.lock, crates/sui-json-rpc-types/src/sui_move.rs, crates/sui-json-rpc/Cargo.toml, crates/sui-json-rpc/src/move_utils.rs
Given the recent changes to error handling and error response codes on rpc, adding some unit tests so we can expect behavior without having to reproduce potentially difficult error states through integration/ e2e tests.
1. `MoveUtils` previously took `AuthorityState`, now has field `MoveUtilsInternalTrait` trait object. Moved most implementation of MoveUtils input the trait object so we can mock various states and expect the correct success or error response.
2. Two unit tests for `get_normalized_move_module` for success and error responses.
Existing tests + new unit tests
--- …
=> [1/n] [sui-json-rpc] unit testing

crates/sui-indexer/migrations/2022-11-28-204251_addresses/down.sql, crates/sui-indexer/migrations/2022-11-28-204251_addresses/up.sql, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/lib.rs, crates/sui-indexer/src/models/addresses.rs, crates/sui-indexer/src/processors/address_processor.rs, crates/sui-indexer/src/processors/mod.rs, crates/sui-indexer/src/processors/processor_orchestrator.rs, crates/sui-indexer/src/schema.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
The related metrics are:
- cumulative address count: address that ever sent or received a tx
- cumulative active address count: address that ever sent a tx
- daily active address: address that has sent tx over the previous day based on current checkpoint's timestamp
local run against testnet
=> indexer: address async processor for address metrics

crates/sui-snapshot/Cargo.toml
Avoid the build warning `version requirement `0.12.3+zstd.1.5.2` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion`
CI.
---
=> Remove semver metadata

crates/sui-adapter-transactional-tests/tests/upgrade/type_names.exp, crates/sui-adapter-transactional-tests/tests/upgrade/type_names.move, crates/sui-framework/docs/package.md, crates/sui-framework/packages/move-stdlib/sources/type_name.move, crates/sui-framework/packages/sui-framework/sources/package.move, crates/sui-protocol-config/src/lib.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, external-crates/move/move-stdlib/docs/type_name.md, external-crates/move/move-stdlib/sources/type_name.move, external-crates/move/move-stdlib/src/natives/type_name.rs
Address follow-ups from #12026, related to a typo in a doc comment, and an improvement to the function name.
```
sui$ cargo simtest
sui$ env SUI_SKIP_SIMTESTS=1 cargo nextest run
```
---
Renaming `std::type_name::get_original` (introduced to the framework as protocol version 11) to `std::type_name::get_with_original_ids`.
=> [move-stdlib/type_name] rename get_original to get_with_original_ids

Cargo.lock, Cargo.toml, crates/sui-core/src/generate_format.rs, crates/sui-enum-compat-util/Cargo.toml, crates/sui-enum-compat-util/src/lib.rs, crates/sui-json-rpc-types/Cargo.toml, crates/sui-json-rpc-types/src/sui_move.rs, crates/sui-json-rpc-types/src/unit_tests/sui_move_tests.rs, crates/sui-json-rpc-types/tests/staged/sui_move_struct.yaml, crates/sui-json-rpc-types/tests/staged/sui_move_value.yaml, crates/sui-proc-macros/Cargo.toml, crates/sui-proc-macros/src/lib.rs, crates/sui-types/Cargo.toml, crates/sui-types/src/unit_tests/execution_status_tests.rs
Similarly to this [PR](https://github.com/MystenLabs/sui/pull/12036)
For some enums we require that variants are appended to the end of an enum to ensure backward compat for SDK etc.
We currently use comments like [this](https://github.com/MystenLabs/sui/blob/25678de7f57438f7b9a6af8f908e3051d1505205/crates/sui-types/src/execution_status.rs#L180-L181)
```
// NOTE: if you want to add a new enum,
// please add it at the end for Rust SDK backward compatibility.
```
to inform folks to append but we dont actually enforce it.
This PR adds enforcement test on `ExecutionFailureStatus` and will add for other types as I discover them.
Example test failure from swapping variants
```
panicked at 'Enum variant SuiMoveVerificationTimedout has been swapped with SuiMoveVerificationTimedoutNew at position …
```
=> [hardening] Add enum snapshot tests to `SuiMoveValue` and `SuiMoveStruct`

crates/sui-indexer/src/apis/extended_api.rs, crates/sui-indexer/src/models/addresses.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-json-rpc-types/src/sui_extended.rs, crates/sui-json-rpc/src/api/extended.rs
Add address metrics to extended RPC
local run indexer as rpc server and verify that the new endpoints can return expected response
```
cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --rpc-client-url   http://ord-exp-val-01.experiments.sui.io:9000 --rpc-server-worker --rpc-server-url 127.0.0.1 --rpc-server-port 3030
--data-raw '{
"id": 1,
"method": "suix_getLatestAddressMetrics",
"params": []
}'
{"jsonrpc":"2.0","result":{"checkpoint":9199,"epoch":1,"timestampMs":1683821111335,"cumulativeAddresses":16086,"cumulativeActiveAddresses":104,"dailyActiveAddresses":104},"id":1}% 
--header …
```
=> rpc: address metrics

.changeset/forty-rockets-cheer.md, sdk/typescript/src/types/__tests__/common.test.ts, sdk/typescript/src/types/common.ts
Requested to do easier equality checks around structs, and have more robust parsing of struct tags in general.
Added tests.
---
=> [ts-sdk] Add struct tag helpers

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/src/unit_tests/pay_sui_tests.rs, crates/transaction-fuzzer/src/account_universe/account.rs, crates/transaction-fuzzer/src/executor.rs, crates/transaction-fuzzer/src/type_arg_fuzzer.rs
Make dev inspect honor RGP and gas price to be more consistent and also remove as much as possible `RGP = 1` in testing
Added a test for gas price and see what tests fail
---
=> Make checks for RPG more consistent

sdk/typescript/src/providers/json-rpc-provider.ts, sdk/typescript/src/types/objects.ts, sdk/typescript/test/e2e/objects.test.ts
Adds `tryGetPastObject` to the TS SDK
Added tests
---
=> [ts-sdk] add try get past object support

crates/sui-replay/src/fuzz.rs, crates/sui-replay/src/fuzz_mutations.rs, crates/sui-replay/src/fuzz_mutations/drop_random_command_suffix.rs, crates/sui-replay/src/fuzz_mutations/drop_random_commands.rs, crates/sui-replay/src/fuzz_mutations/shuffle_command_inputs.rs, crates/sui-replay/src/fuzz_mutations/shuffle_commands.rs, crates/sui-replay/src/fuzz_mutations/shuffle_transaction_inputs.rs, crates/sui-replay/src/fuzz_mutations/shuffle_types.rs, crates/sui-replay/src/lib.rs
Adds a bunch of new mutations to the transaction replay fuzzer, and also adds a way to random select a different mutators from a set of them.
Ran them locally
=> [replay-fuzz] Add additional mutations to the transaction-replay fuzzer

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/src/unit_tests/pay_sui_tests.rs, crates/transaction-fuzzer/src/account_universe/account.rs, crates/transaction-fuzzer/src/executor.rs, crates/transaction-fuzzer/src/type_arg_fuzzer.rs
Make dev inspect honor RGP and gas price to be more consistent and also remove as much as possible `RGP = 1` in testing
Added a test for gas price and see what tests fail
---
---
=> Make checks for RPG more consistent (#12073)

crates/sui-core/src/authority.rs, crates/sui-indexer/src/apis/read_api.rs, crates/sui-json-rpc/src/api/read.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-node/src/main.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-sdk/src/apis.rs, crates/sui-telemetry/src/lib.rs, crates/sui-types/src/digests.rs, crates/sui/src/client_commands.rs
Sometimes it's easy to mistake two networks (testnet v.s. mainnet), this adds a way to query the rpc to see which network the node is in. Also add a CLI option.
tested locally.
---
=> expose chain identifier in rpc

Cargo.lock, crates/sui-replay/Cargo.toml, crates/sui-replay/src/config.rs, crates/sui-replay/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-replay/src/types.rs, crates/sui-tool/src/commands.rs
Allows for loading and writing default configs for replay to `~/.sui-replay/network-config.yaml`
This way we can omit specifying the RPC endpoint on each operation.
Also adds a command for generating a default file
Example
```
./target/debug/sui-tool replay  tx -t jgE26bo5ZWhGJbEq8brC8TrmFu8W4d2UDvyhdATvFwq
2023-05-18T22:45:26.858972Z  INFO sui_replay: Executing tx: jgE26bo5ZWhGJbEq8brC8TrmFu8W4d2UDvyhdATvFwq
2023-05-18T22:45:26.859350Z  INFO sui_replay::replay: Attempting to replay with network rpc:  https://fullnode.testnet.sui.io:443/
2023-05-18T22:45:28.992366Z  INFO sui_replay: Execution finished successfully. Local and on-chain effects match.
```
File generated
```
base-network-configs:
- name: testnet
epoch-zero-start-timestamp: 0
epoch-zero-rgp: 0
public-full-node: …
```
=> add sticky network config for replay system

crates/sui-faucet/src/faucet/simple_faucet.rs, crates/sui-faucet/src/faucet/write_ahead_log.rs, crates/sui-faucet/src/main.rs
Turning back on WAL retry logic with a flag that checks that its already an in_flight request. This way the separate worker thread will never attempt to try the same requests that are already inflight and resulting in a corrupted WAL.
Proof: 
Unit testing + CI/CD
---
=> [faucet] Adding Retry Logic for WAL

sdk/typescript/src/types/transactions.ts, sdk/typescript/test/e2e/read-transactions.test.ts
This resolves an issue where we hit RPC validation warnings for some users. Fixes #12061.
Ran locally.
---
=> [ts-sdk] RPC validation error fix

crates/sui-protocol-config-macros/src/lib.rs, crates/sui-protocol-config/src/lib.rs
Each field `X` will now have getter `X_as_option` which returns `Option<T>` instead of panicking when `T` is `None`.
Unit test
---
=> add option getters

apps/core/src/hooks/useGetOriginByteKioskContents.ts
* wallet was always showing the loading spinner when the address doesn't own any origin byte kiosk objects
before
https://github.com/MystenLabs/sui/assets/10210143/7302a2b8-9e8f-4666-b51f-8035f2bfc8f2
after
https://github.com/MystenLabs/sui/assets/10210143/ea98f980-d093-43a1-be7e-90606f00d9e1
context [here](https://mysten-labs.slack.com/archives/C0393DWJD7X/p1684523802991629)
=> wallet-ext: fix always showing loading spinner in nfts page

crates/sui-replay/src/lib.rs, crates/sui-replay/src/transaction_provider.rs
Allows specifying start of fuzz as either checkpoint or tx digest
Manual
---
=> [fuzz] replay fuzz from tx digest start

apps/explorer/src/components/validator-map/index.tsx
removed the useEffect in favor of useQuery
Locally
---
=> [explorer] validator map followup

.changeset/rotten-shrimps-enjoy.md, sdk/typescript/src/types/transactions.ts
Previously, `effects` had an `unwrapped_then_deleted` field on ts-sdk. This is an issue since jsonrpc returns the field as `unwrappedThenDeleted`.
Locally built ts-sdk and explorer. Verified that visiting this page: http://localhost:3000/txblock/3T2AYzJTvW5Hg4JhZaTgeFaTPSetyEBYZ44bVzScfibS?network=mainnet did not result in any errors printed to console.
---
=> use camelCase for `unwrappedThenDeleted`

Cargo.lock, crates/sui-cluster-test/Cargo.toml, crates/sui-indexer/Cargo.toml, crates/sui-json-rpc/Cargo.toml, crates/sui-json-rpc/src/metrics.rs, crates/sui-move/Cargo.toml, crates/sui-replay/Cargo.toml, crates/sui-sdk/Cargo.toml, crates/sui/Cargo.toml, crates/test-utils/Cargo.toml, crates/workspace-hack/Cargo.toml
Corresponding change in the forked repo: https://github.com/wlmyng/jsonrpsee/pull/1
---
=> Point jsonrpsee to forked version to support error metrics by error code

crates/sui-framework/docs/clob.md, crates/sui-framework/packages/deepbook/sources/clob.move, crates/sui-framework/packages/deepbook/tests/clob_tests.move, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Add api for query market price of the order book
---
---
=> [Deepbook] Add api for query market price

apps/explorer/src/components/validator-map/ValidatorLocation.tsx, apps/explorer/src/components/validator-map/WorldMap.tsx, apps/explorer/src/components/validator-map/index.tsx, apps/explorer/src/components/validator-map/types.ts, apps/explorer/src/hooks/useAppsBackend.ts, apps/explorer/src/hooks/useSuiCoinData.ts
Updates the validator map logic to support the new API structure. Not consuming the new data yet, just changing this to read from the correct path.
Ran locally.
---
=> [explorer] Support new validator map API

apps/explorer/src/utils/growthbook.ts, apps/wallet/src/shared/experimentation/features.ts, apps/wallet/src/ui/app/experimentation/feature-gating.ts
New cached API.
Ran locally.
---
=> [apps] Update growthbook to use new API

.changeset/rotten-shrimps-enjoy.md, Cargo.lock, crates/sui-cluster-test/Cargo.toml, crates/sui-indexer/Cargo.toml, crates/sui-json-rpc/Cargo.toml, crates/sui-json-rpc/src/metrics.rs, crates/sui-move/Cargo.toml, crates/sui-replay/Cargo.toml, crates/sui-sdk/Cargo.toml, crates/sui/Cargo.toml, crates/test-utils/Cargo.toml, crates/workspace-hack/Cargo.toml, sdk/typescript/src/types/transactions.ts
1. Point jsonrpsee to forked version to support error metrics by error code
2. [bug fix] previously, effects had an unwrapped_then_deleted field on ts-sdk. This is an issue since jsonrpc returns the field as unwrappedThenDeleted, and caused errors on making certain get transaction block requests. 
---
=> [cherrypick] Point jsonrpsee to forked version to support error metrics and use camelCase for unwrappedThenDeleted

apps/core/src/hooks/useAppsBackend.ts, apps/core/src/index.ts, apps/explorer/src/components/Layout/index.tsx, apps/explorer/src/components/validator-map/index.tsx, apps/explorer/src/hooks/useSuiCoinData.ts, apps/explorer/src/index.tsx, apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx, sdk/typescript/src/types/epochs.ts
This shuffles our network monitoring from being a manual feature flag to be endpoint-driven.
One side-effect is that when running locally, the apps backend _always_ uses the local API. Curious if folks are okay with this.
Ran locally.
---
=> Network monitor tweak

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_12.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
To fix protocol config snapshot test which is (correctly) complaining that the framework bytes being packaged in the binary no longer matches the snapshot for the max protocol version, after #12088.
```
cargo nextest run -- check_framework_change_with_protocol_upgrade
```
=> [protocol-config] Bump protocol version to 12

apps/wallet/src/shared/constants.ts, apps/wallet/src/ui/app/shared/faucet/FaucetRequestButton.tsx, apps/wallet/src/ui/app/staking/delegation-detail/DelegationDetailCard.tsx, apps/wallet/src/ui/app/staking/stake/StakingCard.tsx
Add request SUI coins from the faucet whenever SUI balance is less than or equal to 1 and if the network is not mainnet 
https://github.com/MystenLabs/sui/assets/126525197/35e6d53b-065d-45b7-b563-d51f22fc07e1
---
=> add fallback button request coins from faucet if only one coin

crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui/tests/snapshots/snapshot_tests__basic_read_cmd_snapshot_tests.snap
when `epoch_duration_ms` < 2000, `tick_duration` may be `0` which makes `tokio::time::interval_at` panic. The fix is to use `Duration::from_millis(`
`cargo nextest run test_passive_reconfig` passes now which fails otherwise
---
=> use miliescond to avoid underflow when setting up pruner

sdk/bcs/README.md
BCS deserialization example in README used a value named "bcsBytes" where the name of value for the serialized object is "bytes".
---
=> Fix typo in README example

apps/core/src/hooks/useTimeAgo.ts, apps/explorer/src/components/tx-time/TxTimeType.tsx, apps/explorer/src/pages/epochs/utils.ts, apps/wallet/src/ui/app/shared/countdown-timer/index.tsx
Removing days from the countdown `timeAgo`  helper. The wallet `Staking Rewards Redeemable` was the only place this is visible, and this should be in hours, not days. 
---
=> Remove days from countdown timeAgo 

.changeset/sharp-mangos-sleep.md, sdk/typescript/src/providers/json-rpc-provider.ts
This adds a chain identifier method to the TS SDK, currently backed by it's own logic that we'll just port to the new API method once it's available.
---
=> [ts-sdk] Add chain identifier method

.github/actions/diffs/action.yml, .github/workflows/external.yml, .github/workflows/rust.yml
Since external crates tests + prover tests and Sui tests are independent, we can run them in parallel and save time.
This reduces test time from ~27 mins to ~22 mins
Once this goes in I'll work with @ebmifa to make the new tests required in CI
---
=> [ci] reduce test time: run external-crates tests concurrently with Sui tests

apps/core/src/hooks/useOnScreen.ts, apps/wallet/src/shared/qredo-api.ts, apps/wallet/src/shared/utils/index.ts, apps/wallet/src/ui/app/QredoSigner.ts, apps/wallet/src/ui/app/components/transactions-card/NoActivityCard.tsx, apps/wallet/src/ui/app/components/transactions-card/TxnIcon.tsx, apps/wallet/src/ui/app/hooks/useGetQredoTransaction.tsx, apps/wallet/src/ui/app/hooks/useGetQredoTransactions.tsx, apps/wallet/src/ui/app/index.tsx, apps/wallet/src/ui/app/pages/approval-request/SignMessageRequest.tsx, apps/wallet/src/ui/app/pages/home/transactions/CompletedTransactions.tsx, apps/wallet/src/ui/app/pages/home/transactions/QredoPendingTransactions.tsx, apps/wallet/src/ui/app/pages/home/transactions/QredoTransaction.tsx, apps/wallet/src/ui/app/pages/home/transactions/index.tsx
* when a qredo account is selected in user's activity view show an extra filter to allow user to switch between completed and pending (qredo) transactions
* use qredo api to load all transactions and filter out all completed
* for each visible transaction load extra details
* based on the Intent scope show if qredo transaction is sign message request or actual transaction
* transactions and transaction details refetch every 5s
Loading
No transactions
Error loading transactions
Transactions
Transaction that failed to load details
https://github.com/MystenLabs/sui/assets/10210143/99ee7e8b-4453-478a-aaa1-6346737bb2c4
closes APPS-796
=> wallet-ext: show pending qredo transactions

.changeset/sharp-yaks-hammer.md, .changeset/sixty-zebras-mix.md, pnpm-lock.yaml, sdk/typescript/README.md, sdk/typescript/package.json, sdk/typescript/src/providers/json-rpc-provider.ts, sdk/typescript/src/rpc/client.ts, sdk/typescript/src/rpc/websocket-client.ts, sdk/typescript/src/types/events.ts, sdk/typescript/src/types/index.ts, sdk/typescript/src/types/subscriptions.ts, sdk/typescript/src/utils/errors.ts, sdk/typescript/test/e2e/object-vector.test.ts, sdk/typescript/test/e2e/subscribe.test.ts, sdk/typescript/test/unit/rpc/client.test.ts
This updates the internals of the ts-sdk to use `@open-rpc/client-js`. This package supports different transports natively and is smaller than our previous `jayson` / `rpc-websockets` implementation. As part of this I also cleaned up a lot of our websocket code to make it easier to add new methods, changed the API to return an unsubscribe function (which is easier for most folks to reason about), and added the missing `subscribeTransaction` method.
Added new tests for `subscribeTransaction`.
---
=> [ts-sdk] Update SDK to use new internals, add `subscribeTransaction`

crates/sui-test-transaction-builder/src/lib.rs
This allows putting move examples in any directory, unrelated to where they were at build time.
Specified `MOVE_EXAMPLES_DIR` on stress binaries in private testnet.
---
=> [Test] Allow specifying custom examples dir

narwhal/primary/src/synchronizer.rs
Looking over on some mainnet logs (before the recent improvements on the proposer certificate requests) it seems that nodes were re-processing same certificate after this has been enqueued for processing in the `rx_certificate_acceptor` channel. Ex:
```
2023-05-09T20:52:32.430427Z DEBUG narwhal_consensus::bullshark: Processing KCS+7qgt4aRBk05R: C27294(24, KCS+7qgt4aRBk05R, E27)
2023-05-09T20:52:32.432573Z DEBUG request{route=/narwhal.PrimaryToPrimary/RequestVote remote_peer_id=e1b69e22 direction=inbound}: narwhal_primary::synchronizer: Processing certificate KCS+7qgt4aRBk05R: C27294(24, KCS+7qgt4aRBk05R, E27) round:27294
2023-05-09T20:52:32.449009Z DEBUG request{route=/narwhal.PrimaryToPrimary/RequestVote remote_peer_id=f6dee950 direction=inbound}: narwhal_primary::synchronizer: …
```
=> [refactor] exit early on certificate processing when already processed

crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
It was split before mainnet for better backfill speed on testnet, it's no longer urgent b/c TPS is not super high today, but this split is very error-prune and caused issues and affected reliability in the past, thus 
To improve peak TPS handling capability, it's planned to rewrite object commit via replacing upsert with append-only.
running locally agains both testnet and mainnet to make sure 
- all obj handler related tables are all populated as expected including `objects`, `epochs`, `packages`, `input_objects`, `move_calls` and `recipients`.
- compared commit speeds over first 10k checkpoints and the obj is still the bottle-neck and it's not any faster
- testnet with change: 650s <> testnet without changes: 1) tx: 510s 2) obj: 670s
- mainnet with change: 150s <> mainnet without …
=> indexer: merge tx and object in checkpoint handler

crates/sui-framework/docs/kiosk.md, crates/sui-framework/docs/transfer_policy.md, crates/sui-framework/packages/sui-framework/sources/kiosk/kiosk.move, crates/sui-framework/packages/sui-framework/sources/kiosk/transfer_policy.move, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
For an easy CLI setup (it does not support PTBs yet), adds an entry function which shares the Kiosk and transfers the KioskOwnerCap to the tx sender. This is the most common setup for the Kiosk.
---
- adds `sui::kiosk::default()` function for easy Kiosk setup
=> [kiosk] Adds 'default' entry function to Kiosk

crates/sui-core/src/authority.rs, crates/sui-node/src/lib.rs
update anemo to https://github.com/MystenLabs/anemo/commit/1bfa7842f66a85d35345b5ada358df90c3efd579 which includes the `alternate_server_name` change. Set primary server name as `sui-{chain-id}`. 
tested in labnet.
---
update anemo to https://github.com/MystenLabs/anemo/commit/1bfa7842f66a85d35345b5ada358df90c3efd579 which includes the `alternate_server_name` change. Set primary server name as `sui-{chain-id}`.  Note that if node starts to run this version in testnet/mainnet before the update is officially rolled out, it's likely the node won't be able to state sync.
=> set alt server name for anemo

apps/core/src/hooks/useTimeAgo.ts, apps/explorer/src/components/checkpoints/CheckpointsTable.tsx, apps/explorer/src/hooks/useGetCheckpoints.ts, apps/explorer/src/pages/epochs/EpochDetail.tsx
Fix Epoch checkout is missing the latest 
Before checkoutpoint ends at 
https://suiexplorer.com/epoch/41
After 
https://explorer-git-gj-explorer-epoch-checkpoint-bug-mysten-labs.vercel.app/epoch/41
=> fix epoch missing the latest checkoutpoint

apps/wallet/src/ui/app/hooks/useGetAllCoins.ts
Fix the validation showing a 0 balance issue. Setting stale time to 5000 fixes it.  useQuery queryFn
before
https://github.com/MystenLabs/sui/assets/126525197/41cd560d-03a5-4ce7-bfed-83374e6a94ea
after 
https://github.com/MystenLabs/sui/assets/126525197/058f6e17-46b2-4cc9-928e-6624a4442c06
---
=> fix big amount bug and 0 balance validation

Cargo.lock, crates/sui-benchmark/Cargo.toml, crates/sui-core/Cargo.toml, crates/sui-faucet/Cargo.toml, crates/sui-rosetta/Cargo.toml, crates/sui-rpc-loadgen/Cargo.toml, crates/sui-storage/Cargo.toml, crates/sui-tool/Cargo.toml, crates/sui/Cargo.toml, crates/typed-store-derive/Cargo.toml, crates/typed-store/Cargo.toml, crates/typed-store/src/rocks/mod.rs, crates/workspace-hack/Cargo.toml
updates rust rocksdb dependency to 0.21.0
---
=> update rust rocksdb to 0.21.0

doc/src/build/custom-upgrade-policy.md
Compatible UpgradeCap can't change `public` function signature.
Compatible UpgradeCap can't change `public` function signature.
=> Fix typo in UpgradeCap

apps/explorer/src/utils/api/DefaultRpcClient.ts, apps/wallet/src/ui/app/ApiProvider.ts
This changes the Sentry RPC instrumentation to only apply to mainnet. Other networks are too low volume to effectively monitor, and just end up adding noise for our instrumentation.
Ran locally.
---
=> [wallet][explorer] Only monitor RPC for mainnet

crates/sui-core/src/checkpoints/mod.rs
It's not causing any problems today but in case in the future we mistakenly assume these inserts happen atomically.
CI
---
update self.checkpoint_sequence_by_contents_digest atomically along with other cfs
=> update self.checkpoint_sequence_by_contents_digest atomically along with other cfs

Cargo.lock, crates/sui-core/Cargo.toml, crates/sui-core/src/lib.rs, crates/sui-open-rpc/Cargo.toml, crates/sui-open-rpc/src/generate_json_rpc_spec.rs, crates/sui-test-transaction-builder/Cargo.toml, crates/sui-types/Cargo.toml
A few crates don't/shouldn't inherit workspace version. Give them individual versions.
Also the open-json-rpc is generating version using sui-core's version, which is always the workspace version. This is wrong to me. This PR is a short-term fix to just use workspace version directly in open-json-rpc, but we should make it a real version.
cargo build
---
=> Remove unnecessary workspace versions

crates/sui-e2e-tests/tests/protocol_version_tests.rs, crates/sui-indexer/tests/integration_tests.rs, crates/sui-json-rpc/src/unit_tests/rpc_server_tests.rs, crates/sui-json-rpc/src/unit_tests/transaction_tests.rs, crates/sui-json-rpc/tests/balance_changes_tests.rs, crates/sui-json-rpc/tests/subscription_tests.rs, crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs, crates/sui-rosetta/tests/end_to_end_tests.rs, crates/sui-surfer/src/default_surf_strategy.rs, crates/sui-surfer/src/surfer_task.rs, crates/test-utils/src/network.rs
TestCluster.accounts can be obtained from the wallet context within, and hence it's redundant.
Since it's a testing method we don't particularly care much about efficiency considering that the typical number of accounts in a cluster is small. If we really want to cache it, we should cache inside wallet context instead of the cluster.
Removing it from TestCluster.
This will set up the code better for consolidating TestCluster and Swarm.
cargo test
---
=> Remove accounts from TestCluster

crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-snapshot/src/lib.rs, crates/sui-snapshot/src/reader.rs, crates/sui-snapshot/src/tests.rs, crates/sui-snapshot/src/writer.rs
This PR adds the ability to read state snapshot from a remote object store. The storage format allows to pre-fetch object references first and start state accumulator. In parallel, we start the object download and abort it if computed state root hash doesn't match the one in checkpoint.
Added some basic tests.
=> Add a state snapshot reader

narwhal/network/src/retry.rs, narwhal/primary/src/synchronizer.rs, narwhal/worker/src/handlers.rs, narwhal/worker/src/tests/handlers_tests.rs
Currently worker `synchronize()` handler is responsible for
- Fetching header payloads, which does not need to broadcast
- Fetching certificate payloads asynchronously, which is non-critical
- BlockWaiter, which will be removed
So it seems to we can simplify `synchronize()` by removing internal broadcast and retries. Fetching payloads via `synchronize()` are still retried at a higher level at `Synchronize::sync_batches_internal()`.
Also, since `Synchronize::sync_batches_internal()` will get retried for voting, add a timeout to the retry logic.
We can see if this helps with the spikes of futures trying to fetch batches:
`request_batch()` handler and messages can be cleaned up after BlockWaiter is removed.
---
If your changes are not user-facing and not a breaking …
=> [Narwhal] remove broadcast and retries from worker synchronize() handler

crates/sui-json-rpc/src/indexer_api.rs
before this PR, FN config is required to make sui NS work, this PR added default mainnet sui ns config so that
- without extra setup, sui ns on mainnet should just work
- if RPC provider wants to override with custom ones, they still can
- on other *nets, overriding is still required.
Test on testnet with & without overriding.
---
=> sui ns: add default configs

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_test_utils.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/unit_tests/consensus_tests.rs, crates/sui-protocol-config/src/lib.rs
This has seen considerable testing in private testnet at this point. The one major issue identified (degrading narwhal performance) appears to have been caused by the insufficient udp socket buffers identified by @aschran - i test this code with his fix and there is no longer any degradation caused by this change, and the improvement in consensus handler utilization appears to be close to 2x.
=> Use a single db batch per narwhal commit in consensus task.

apps/core/src/hooks/useGetOriginByteKioskContents.ts, apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx, apps/wallet/src/ui/app/pages/home/nft-transfer/index.tsx, apps/wallet/src/ui/app/pages/home/nft-transfer/useTransferKioskItem.ts
Enables transfer of items contained within an OriginByte kiosk. There's some duplicate effort in finding the Kiosk for a given object, but wanted to get this in so that transfers work. 
Tested transfers to addresses both with + without existing kiosks
---
=> [wallet-ext] - enable transfer of ob kiosk items

.changeset/giant-flowers-collect.md, apps/wallet/src/dapp-interface/WalletStandardInterface.ts, sdk/wallet-adapter/wallet-kit-core/src/index.ts
* this seems like a chrome issue, when dapp preloads and then user visits the page the port disconnects but content script never gets notified
* we avoid creating a port until the document is visible and that seems to solve the issue
* auto connect gets delayed and wait for the document to be visible
* wallet interface delay loading accounts until a dapp connects
fixes: 
https://github.com/MystenLabs/sui/assets/10210143/4a354026-1682-4e7a-b2fb-5539af8e7247
https://github.com/MystenLabs/sui/assets/10210143/cde9852f-b26f-46ff-a2f6-3dc2169002f6
closes APPS-1036
=> wallet-ext:wallet-kit: fix port disconnection when dapp preloads

crates/sui-core/src/storage.rs, crates/sui-network/src/state_sync/mod.rs
There are two noticeable changes for `fn handle_checkpoint_from_consensus` in this PR:
1. if the checkpoint sent by consensus is ahead of `highest_verified_checkpoint`, we will try to fill the gap. One thing we do here is `store.insert_checkpoint` if `store.get_checkpoint_by_sequence_number` returns `Some`. This is not needed because it's only possible for `store.get_checkpoint_by_sequence_number` to return `Some` when we already have `store.insert_checkpoint` happened before. Particularly, these two functions update/check cf `certified_checkpoints`.
2.  when `if` in line 462-463 fails, and the checkpoint sequence number match, it means we have a fork, `assert_eq` is not needed.
unit tests.
---
If your changes are not user-facing and not a breaking change, you can skip the following …
=> do not insert_checkpoint when get_checkpoint_by_sequence_number returns data

.changeset/early-seas-tap.md, sdk/typescript/src/types/objects.ts
Matches the RPC definition when "withBcs" is used.
Manually verified this dependency against RPC.
---
- sui.js now has correct response type definition for the RPC "withBcs" call
=> [sdk, sui.js] Patches the response so it matches the RPC definition

crates/sui-e2e-tests/tests/onsite_reconfig_observer_tests.rs
As described in the comment
cargo simtest
---
=> Fix test_onsite_reconfig_observer_basic

crates/sui-indexer/benches/indexer_benchmark.rs, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/processors/address_processor.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/src/types.rs
Move processing of `addresses` table and `active_addresses` table to async processor.
The motivations are:
- address stats were not accurate, b/c both `addresses` and `active_addresses` are updated each checkpoint before this change and will not wait for `address_stats`; this is especially bad when we backfill `address_stats` with populated address tables
- updating `addresses` and `active_addresses` each checkpoint oftentimes caused concurrent writes and sometimes even dead_lock on PG commit; the deadlock is not end of world b/c PG can somehow recover from it.
After this change:
- the addresses and active_addresses tables are updated each 100 checkpoints, and wait for address_stats to update before moving for next 100 checkpoints
- such that it solves both problems above, we can adjust …
=> indexer: move address to async processor

apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx
Didn't catch this in testing, if you hit the cache at the wrong time a Kiosk NFT will stick around the NFT page. This adds an invalidation after successful transfer. 
---
=> [wallet-ext] - invalidate kiosk query after transfer

Cargo.lock, Cargo.toml, crates/sui-node/src/lib.rs, crates/sui-proc-macros/Cargo.toml, crates/sui-simulator/Cargo.toml, crates/typed-store/Cargo.toml, crates/workspace-hack/Cargo.toml, narwhal/primary/src/primary.rs, narwhal/worker/src/worker.rs, scripts/simtest/cargo-simtest
Increases size of UDP socket buffers for sui, primary, and worker Anemo networks. This improves performance under high load.
Manual benchmarks & testing on private-testnet.
---
Increases size of UDP socket buffers for sui, primary, and worker Anemo networks. This improves performance under high load.
**NOTE:** the buffer sizes requested after this change are larger than the default maximum buffer allowed by many operating systems. If the sui node binary logs errors about failure to set UDP socket buffer size, you may need to increase the maximum allowed by your OS. …
=> Increase UDP socket buffer sizes for Anemo networks

crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-node/src/lib.rs, crates/sui-types/src/base_types.rs, crates/sui-types/src/crypto.rs, crates/sui-types/src/error.rs, crates/sui-types/src/message_envelope.rs, crates/sui-types/src/messages_checkpoint.rs, crates/sui-types/src/multisig.rs, crates/sui-types/src/signature.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/multisig_tests.rs
store google jwk as a global value for envelope to access during sig verify. spawn a task in sui node to update it every 1 hour. 
---
=> authority: inject google jwk bytes global value

crates/sui-benchmark/src/bin/stress.rs, crates/sui-benchmark/src/system_state_observer.rs, crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/scoring_decision.rs, crates/sui-core/src/unit_tests/move_package_tests.rs, crates/sui-e2e-tests/tests/reconfiguration_tests.rs, crates/sui-framework-snapshot/tests/compatibility_tests.rs, crates/sui-genesis-builder/src/lib.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-move-build/src/lib.rs, crates/sui-node/src/lib.rs, crates/sui-open-rpc/src/examples.rs, crates/sui-protocol-config/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-transactional-test-runner/src/test_adapter.rs, crates/sui-types/src/digests.rs, narwhal/node/src/main.rs, narwhal/test-utils/src/lib.rs, narwhal/types/src/primary.rs
The goal is to be able to roll out features for certain chains and not others.
To accomplish this, we introduce a `Chain` enum, with a getter function to map the hard coded checkpoint identifier (i.e. the digest of the genesis checkpoint) to the `Chain`, and have all callsites where the protocol config is materialized to provide the chain identifier. 
With the `Chain` being available in the `ProtocolConfig::get_for_version`, we can then make use of this in the protocol version map.
Tested against a Mainnet node to ensure that the chain is correctly identified. Also locally enabled a feature for all chains but mainnet in the highest protocol version, and saw that the feature was active.
---
If your changes are not user-facing and not a breaking change, you can skip the following section. …
=> [Core] Add support for chain-specific configs

doc/src/learn/sui-bridging.md
Wormhole docs references object IDs for two of the packages, instead of the package IDs. Updates to reference the correct package IDs.
---
=> Fix wormhole doc references

apps/core/src/hooks/useGetBinaryVersion.ts, apps/core/src/index.ts, apps/explorer/src/components/network/Network.tsx, apps/explorer/src/ui/header/NetworkSelect.tsx
Add Sui binary version to NetworkSelect
---
=> Add Sui binary version to NetworkSelect

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_12.snap
As in title
`test_passive_reconfig` simtest exercises the enabled feature. 
---
=> [StateAccumulator] Commit root state digest on non-mainnet chains

apps/core/src/hooks/useAppsBackend.ts
This is just a small improvement to the `request` interface in `useAppsBackend`. If you have an endpoint with no query parameters, you have to do `request(path, {})` which leads to the URL having an extra `?` at the end of it. This only affects one endpoint right now, but I'm adding another endpoint that doesn't have query parameters so I figured I'd go ahead and make this change 😄 
- Existing endpoints work on Sui Explorer and Sui Wallet
- Tested with prod URL and localhost URL
- /coins/sui URL is formatted properly (`http://localhost:3003/coins/sui` vs `http://localhost:3003/coins/sui?`)
- Other apps-backend endpoints are formatted properly (e.g. `http://localhost:3003/validator-map?network=mainnet&version=2`)
---
If your changes are not user-facing and not a breaking change, you can …
=> [apps] allow no query parameters to be passed when making apps-backend requests

crates/sui-indexer/migrations/2023-03-05-165748_transaction_index/up.sql, crates/sui-indexer/src/apis/indexer_api.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-open-rpc/spec/openrpc.json
This PR added a tx filter
```
/// Query txs that have a given address as sender or recipient.
FromOrToAddress { addr: SuiAddress },
```
such that on Explorer etc. the address page could fetch "related txs" efficiently.
Local run network + indexer, query tx with new filter.
---
=> indexer: FromOrTo tx filter

crates/sui-archival/src/tests.rs, crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/storage.rs, crates/sui-network/src/state_sync/mod.rs, crates/sui-network/src/state_sync/tests.rs, crates/sui-types/src/storage.rs
Based on feedback, now this PR simplifies `handle_checkpoint_from_consensus`. Previously there is a branch to handle when the checkpoint is too new (newer than the highest_verified_checkpoint). I think this case wouldn't happen because consensus sends checkpoint in order. So we consolidate the two cases into one, which is, whenever consensus sends a checkpoint, we do the following things:
1. check the previous digest matches. This is to ensure state sync and consensus do not brain-split.
2. if the checkpoint is older, ignore and exit
3. update metrics and bump watermark
4. notify others
--------------------------
When consensus sends checkpoint y, it means all prior checkpoints are verified and sent, so `highest_verified_checkpoint` can be safely updated without looking at the checkpoint …
=> Simplify `handle_checkpoint_from_consensus`

crates/sui-e2e-tests/tests/checkpoint_tests.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/reconfiguration_tests.rs, crates/sui-e2e-tests/tests/simulator_tests.rs, crates/sui-sdk/src/wallet_context.rs, crates/sui-source-validation/src/tests.rs, crates/sui-surfer/src/surfer_state.rs, crates/sui/src/client_commands.rs, crates/sui/src/unit_tests/validator_tests.rs, crates/test-utils/src/network.rs
Always check transaction execution result in TestCluster and WalletContext.
For cases where we expect the transaction may fail (typically non-testing cases), we add another API explicitly for it.
CI
---
=> Test cluster/WalletContext always check execution result

crates/sui-core/src/authority/authority_per_epoch_store.rs
Fixes a bug where txns that are ignored due to end of epoch are not reverted during reconfig
=> Do not notify about ignored certificates

.changeset/nervous-eels-hammer.md, sdk/kiosk/CHANGELOG.md, sdk/kiosk/README.md, sdk/kiosk/src/bcs.ts, sdk/kiosk/src/constants.ts, sdk/kiosk/src/index.ts, sdk/kiosk/src/query/kiosk.ts, sdk/kiosk/src/query/transfer-policy.ts, sdk/kiosk/src/tx/kiosk.ts, sdk/kiosk/src/tx/transfer-policy.ts, sdk/kiosk/src/types/env.ts, sdk/kiosk/src/types/index.ts, sdk/kiosk/src/types/kiosk.ts, sdk/kiosk/src/types/transfer-policy.ts, sdk/kiosk/src/utils.ts
In this PR: 
- (breaking) Change signature of `purchaseAndResolvePolicies` to a) support environments (e.g. mainnet, testnet) and b) accept `extraParams` (_to support kiosk_lock_rule_).
- Support for `kiosk_lock_rule`, enabling the SDK to fully support `strong royalties enforcement`.
- (breaking) Change return of `purchaseAndResolvePolicies` to include the item + `canTransfer` flag (whether it can be transferred or not, based on the ruleset).
- Isolate the Types of the Kiosk SDK and export them all properly (from `./types` directory).
- Reuse types in bcs definitions.
- Convert functions to plain format (instead of arrow fns) for consistency.
- Fixes `withdrawFromKiosk` and `withdrawFromPolicy` call amount params.
Right now the changes are …
=> [Kiosk SDK] Support `kiosk_lock_rule` and environments

crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-storage/src/indexes.rs, crates/typed-store/src/rocks/mod.rs
There have been reports of fullnode operators seeing data corruptions, where fullnodes are running in evictable pods. Add an option to ensure rocksdb writes are flushed to disk, so operators can experiment with its effectiveness.
Eventually we want to make sync to disk the default behavior, but right now this slows down maximum write throughput a bit too much.
---
=> [rocksdb] allow setting sync to disk on WriteOptions

crates/sui-network/src/state_sync/mod.rs
In https://github.com/MystenLabs/sui/pull/12212, we refactored `handle_checkpoint_from_consensus`. The PR missed one thing: when a last checkpoint of an epoch is certified in consensus and sent to state sync, we do not update the committee store. This is problematic because state sync does not reconfig. It means if a validator is slow in reconfiguration (where committee store would also be updated) and gets checkpoints in the next epoch from peers, it will panic in that it couldn't find the committee. This PR fixes it. 
```
for f in `seq 1 20`; do MSIM_TEST_NUM=5 MSIM_TEST_SEED=98$f RUST_LOG=off simt test_simulated_load_reconfig_restarts --no-capture > log-$f 2>&1 &; done
```
```
grep FAIL log-*
```
---
If your changes are not user-facing and not a breaking change, you can skip the …
=> insert committee when handling checkpoint from consensus

crates/sui-archival/src/tests.rs, crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs, crates/sui-core/src/storage.rs, crates/sui-network/build.rs, crates/sui-network/src/state_sync/builder.rs, crates/sui-network/src/state_sync/mod.rs, crates/sui-network/src/state_sync/server.rs, crates/sui-network/src/state_sync/tests.rs, crates/sui-swarm-config/src/test_utils.rs, crates/sui-tool/src/lib.rs, crates/sui-types/src/messages_checkpoint.rs, crates/sui-types/src/storage.rs
This PR adds the checkpoint low watermark for state sync. This lets a node to know who to query checkpoint contents according to the watermarks, once checkpoint pruning is enabled.
* It adds a new state sync method `get_peer_latest_checkpoint_info`. This call will eventually replace `GetCheckpointSummaryRequest::Latest` request and is called between every tick in `get_latest_from_peer`. The response include the highest synced checkpoint summary and the lowest available checkpoint content watermark.
* To deal with the upgrade, we first query `get_peer_latest_checkpoint_info`, if it's 404 then we query `get_checkpoint_summary` and set the low watermark to 0 (if the node hasn't upgraded, they will have all the checkpoint content up to genesis).
* this low watermark is then updated in …
=> add checkpoint low watermark for state sync

narwhal/primary/src/certificate_fetcher.rs, narwhal/primary/src/certifier.rs, narwhal/worker/src/metrics.rs, narwhal/worker/src/quorum_waiter.rs, narwhal/worker/src/tests/quorum_waiter_tests.rs, narwhal/worker/src/worker.rs
This is going to be compared against `header_to_certificate_latency` to understand the quorum latencies of each validator.
---
=> [Narwhal] measure batch broadcast quorum latency

crates/sui-benchmark/tests/simtest.rs, crates/sui-config/src/node.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-storage/src/indexes.rs, crates/sui-types/src/digests.rs, crates/sui-types/src/unit_tests/base_types_tests.rs, crates/typed-store/src/rocks/mod.rs, crates/typed-store/src/rocks/tests.rs
Initial version of the checkpoint pruner:
Similar to the existing objects pruner (i.e., tails checkpoints from the past epochs and removes relevant data).
Notes:
* current approach employs rocksdb's `delete_range` API. Point-delete tombstones have a negative performance impact on reads. It may still suffer from the same issue where deleted data occupies space in SST files, so alternative solutions like FIFO compaction style should be considered in the future
* each pruning batch affects both the perpetual DB and the checkpoint DB. We can't have an atomic batch between those two, so ordering is important. The perpetual DB batch must be committed first. Its changes are idempotent. Because of this, the pruning watermark is stored in the checkpoint DB
* the checkpoint pruner is blocked by the …
=> [pruner] initial version of checkpoints pruner

crates/sui-indexer/src/apis/extended_api.rs, crates/sui-indexer/src/models/addresses.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-json-rpc/src/api/extended.rs
Add endpoints for DAU over epochs.
```
--data-raw '{
"id": 1,
"method": "suix_getAllEpochAddressMetrics",
"params": [true]
}'
{"jsonrpc":"2.0","result":[{"checkpoint":36799,"epoch":1,"timestampMs":1683849325183,"cumulativeAddresses":84280,"cumulativeActiveAddresses":1218,"dailyActiveAddresses":1218},{"checkpoint":5499,"epoch":0,"timestampMs":1683817158611,"cumulativeAddresses":690,"cumulativeActiveAddresses":5,"dailyActiveAddresses":5}],"id":1}%             
--data-raw '{
"id": 1,
"method": "suix_getAllEpochAddressMetrics",
"params": []
}' …
```
=> rpc: DAU chart endpoint

apps/wallet/src/background/qredo/index.ts, apps/wallet/src/background/qredo/types.ts, apps/wallet/src/background/qredo/utils.ts, apps/wallet/src/dapp-interface/WalletStandardInterface.ts, apps/wallet/src/ui/app/pages/qredo-connect/QredoConnectInfoPage.tsx, pnpm-lock.yaml, sdk/wallet-adapter/example/src/QredoConnectButton.tsx
* add organization field in injected inputs
* this changes the way wallet identifies that 2 connections are different (to be the same must also have the same organization)
* this fixes the issue when injecting accounts with the same service and apiUrl, but different organization was replacing the existing connected wallets
closes APPS-1215
=> wallet-ext: qredo connect add organization field

apps/wallet/src/ui/app/QredoSigner.ts
* wait for the wallet rpc to return the transaction result before completing a qredo sign and execute transaction
| tx result before | tx result after |
| -- | -- |
| <img width="440" alt="Screenshot 2023-06-05 at 16 39 25" src="https://github.com/MystenLabs/sui/assets/10210143/6a004bae-dbb8-4dfd-aa81-789680d16f82"> | <img width="883" alt="Screenshot 2023-06-05 at 16 38 32" src="https://github.com/MystenLabs/sui/assets/10210143/6357eca5-9ba5-4d14-b769-43f7e0ff0398"> |
NOTE: this adds some extra time since we wait for the FN of the wallet to receive the transaction + some polling delays
closes APPS-1058
=> wallet-ext: poll rpc for tx result of qredo transaction

crates/sui-core/src/scoring_decision.rs, crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs, narwhal/benchmark/benchmark/config.py, narwhal/config/src/committee.rs, narwhal/config/tests/snapshots/config_tests__committee.snap, narwhal/consensus/src/bullshark.rs, narwhal/consensus/src/metrics.rs, narwhal/consensus/src/tests/bullshark_tests.rs, narwhal/consensus/src/tests/consensus_tests.rs, narwhal/consensus/src/utils.rs, narwhal/node/src/generate_format.rs, narwhal/primary/tests/integration_tests_proposer_api.rs, narwhal/test-utils/src/lib.rs
This PR is doing mainly two things:
* extending Narwhal committee with the hostname as given by SUI
* exposing the hostname to consensus metrics to identify successful and failed leader elections
---
=> [narwhal] expose hostname to consensus metrics

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/transaction_manager.rs
- Cache available and unavailable objects in TransactionManager.
- ~~Use existing missing object information as additional cache~~ this turned out to cause a subtle race since we temporarily release the lock while reading from the db.
- Simplify and optimize enqueue
- Use multi-get when hitting the db, when possible.
=> TransactionManager optimizations:

Cargo.lock, crates/sui-config/src/node.rs, crates/sui-e2e-tests/tests/reconfiguration_tests.rs, crates/sui-node/src/lib.rs, crates/sui-swarm-config/src/genesis_config.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm/src/memory/swarm.rs, crates/sui-test-transaction-builder/Cargo.toml, crates/sui-test-transaction-builder/src/lib.rs, crates/test-utils/src/network.rs
This PR makes it easy to introduce new validators and remove validators from a test cluster:
1. Added `with_validator_candidates` function in TestCluster to make sure we give enough tokens to them in genesis.
2. Added a few functions in TestTransactionBuilder to generate validator management related transactions, such as validator candidate, activating candidate, staking, leaving and etc.
3. Some cleanups in validator genesis config to make config construction easier.
Update all dynamic committee change tests in reconfiguration_tests to use the new way.
--- …
=> [TestCluster] Add validator management

Cargo.lock, crates/sui-config/src/node.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/protocol_version_tests.rs, crates/sui-e2e-tests/tests/reconfiguration_tests.rs, crates/sui-e2e-tests/tests/simulator_tests.rs, crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs, crates/sui-node/src/lib.rs, crates/sui-surfer/src/surfer_task.rs, crates/sui-swarm-config/src/genesis_config.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm/src/memory/node.rs, crates/sui-swarm/src/memory/swarm.rs, crates/sui-test-transaction-builder/Cargo.toml, crates/sui-test-transaction-builder/src/lib.rs, crates/sui/src/sui_commands.rs, crates/test-utils/src/network.rs
They are all nodes managed by the swarm, and whether a node is validator/fullnode is rather dynamic depending on its state. Merge them. (TODO: Add API to return currently active validators)
Also renamed a few functions to make it more clear:
- start_fullnode -> spawn_new_fullnode
- get_validator_address -> get_validator_pubkeys
CI
---
=> Merge validator and fullnode list in swarm

apps/wallet/src/ui/app/components/address-input/index.tsx, apps/wallet/src/ui/app/components/alert/index.tsx
This adds warnings when an address has no transactions or is an object. It's non-blocking.
---
=> [wallet-ext] Add send warnings

narwhal/primary/tests/nodes_bootstrapping_tests.rs
`test_loss_of_liveness_without_recovery` test has been failing lately in the Narwhal nightly https://github.com/MystenLabs/sui/actions/runs/5184155035 . I've added some extra threshold in the acceptable commits as some node might be a little bit faster than the others - still valid though.
---
=> [fix] fix failing test in the long running suite

crates/sui-archival/src/lib.rs, crates/sui-archival/src/tests.rs, crates/sui-archival/src/writer.rs, crates/sui-node/src/lib.rs
Right now we always assume the underlying storage format is blob. This allows us to migrate to with other storage formats in the future without needing to migrate older data to newer format. We would be able to just add a new enum value and start writing newer checkpoints with newer storage format.
Existing tests
=> Add storage format enum to file metadata in archive manifest

crates/sui-archival/src/lib.rs, crates/sui-archival/src/tests.rs, crates/sui-archival/src/writer.rs, crates/sui-storage/src/lib.rs, crates/sui-storage/src/object_store/util.rs
Without manually flushing the buffer, we may not be guaranteed to read the right data. Also, fix the manifest read/write api and make it simpler
Added unit test
=> [easy] Flush write buffer when writing manifest before computing checksum

apps/wallet/src/shared/analytics/amplitude.ts, apps/wallet/src/shared/utils/index.ts, apps/wallet/src/ui/app/components/DAppInfoCard.tsx, apps/wallet/src/ui/app/components/explorer-link/Explorer.ts, apps/wallet/src/ui/app/components/sui-apps/SuiApp.tsx
When someone clicks out to a Mysten-owned app from the wallet extension, we want to be able to tie together user actions from the extension and Sui Explorer/SuiNS/SuiFrens (https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#cross-domain-tracking).
- The Explorer link is structured correctly: https://suiexplorer.com/address/0x8be60572d904409dbe7978ea6c7bce11974f54362b8c0c5afb71a24f9fba81bd?network=mainnet&deviceId=0cae5482-de65-4e70-8fc9-c17795cd7a83
- The SuiFrens link is structured correctly: https://suifrens.com/?deviceId=0cae5482-de65-4e70-8fc9-c17795cd7a83
- The SuiNS link is structured correctly: https://suins.io/?deviceId=0cae5482-de65-4e70-8fc9-c17795cd7a83
- Other apps (e.g. Wormhole) are structured correctly: https://www.portalbridge.com/sui
- Tested that Sui …
=> [wallet-ext] set the deviceId param when linking out to Mysten-owned applications

crates/sui-json-rpc/src/api/indexer.rs, crates/sui-open-rpc/spec/openrpc.json
See title.
Side question: is there a command to generate `openrpc.json` from the `indexer.rs` file, because it looks like `openrpc.json` descriptions are generated from there? I didn't discover one and just made the manual corresponding changes.
Just a doc link fix (manually checked the correct link works at https://docs.sui.io/build/event_api#event-filters)
Doc fix for broken link.
=> docs: fix link to event filter anchor

crates/sui-core/src/authority_aggregator.rs, crates/sui-core/src/quorum_driver/mod.rs, crates/sui-core/src/test_authority_clients.rs, crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
Currently, if a tx has a lot of conflicts, it's likely that we don't exit until we talk to every validator, which isn't effective, most times than not. This PR adds an early exit point, when the stake of most staked tx  + retryable stake is less than the quorum stake, we know for sure this object is equivocated. One example it tackles with is, when one obj has two txes, each with f+1 stake. 
---
Authority Aggregator exits early when there are too many conflicting txes
=> Authority Aggregator exits early when there are too many conflicting txes

crates/sui-benchmark/src/options.rs, crates/sui-benchmark/src/workloads/shared_counter.rs, crates/sui-benchmark/src/workloads/workload_configuration.rs, crates/sui-benchmark/tests/simtest.rs
This PR adds an option to `sui-benchmark` allowing us to pass in a max tip amount for shared counter workloads. Each shared counter transaction picks a random gas price increment between 0 and this max amount, and use RGP + the picked increment as the gas price. This will be useful for experimenting later. Following PRs will add metrics exposing the rank correlation between gas price and txn processing order. We may also introduce separate workloads with specific gas price behavior later.
---
=> [benchmark] add option to use different gas price in shared counter txns

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs
Use `range_iter ` over `unbounded_iter ` in parts of authority
Normal tests
---
=> [easy/chore] Use `range_iter ` over `unbounded_iter `

external-crates/move/move-vm/runtime/src/interpreter.rs
Moves out the interpreter instr match into a func so its simpler to add pre/post hooks, and overall cleaner.
existing unit tests
---
=> move out interpreter match

crates/sui-core/src/storage.rs
Wire things up.
---
State sync now answer checkpoint availability inquiry by calling checkpoint_store.get_highest_pruned_checkpoint_seq_number
=> call get_highest_pruned_checkpoint_seq_number to get the lowest available checkpoint for state sync

crates/sui-core/src/transaction_orchestrator.rs
The timeout metric is worth alerting on.
👀 
---
add wait for finality times out metrics in transaction orchestrator
=> add wait for finality times out metrics in transaction orchestrator

crates/sui-core/src/quorum_driver/tests.rs
Now we don't exhaust every response when the tx is deadlock, the returned conflicting txes list may look different depending on the order validators respond. In this PR we relax the assertion conditions adaptively.
cargo test
---
Fix test flakiness introduced with early return upon many conflicts
=> fix test flakiness introduced with early return upon many conflicts

.changeset/fair-bags-shout.md, sdk/kiosk/src/tx/transfer-policy.ts
Updated the type argument in the programmable transaction command that transfers the `TransferPolicy` on method `createTransferPolicy`
---
=> [Kiosk SDK] Fixed typeArguments on createTransferPolicy method

doc/src/build/package-upgrades.md
Remove the bullet that indicates that adding abilities to structs during upgrades is supported -- it is not possible to support this without struct version constraints.
👀 , also spot checked other locations that mention upgrades and abilities to make sure they are also up-to-date -- they already were, we must have just missed this reference.
=> [docs/package-upgrades] Cannot add abilities to structs

Cargo.lock, Cargo.toml, crates/workspace-hack/Cargo.toml, sui-execution/cut/Cargo.toml, sui-execution/cut/src/args.rs, sui-execution/cut/src/main.rs, sui-execution/cut/src/plan.rs
The scaffolding deals with argument parsing, and building a "plan" of which packages to duplicate based on that.
```
sui/sui-execution/cut$ cargo nextest run
```
Running the plan that would create a new sui-execution cut:
```
sui$ cargo run --bin cut -- --feature v1 \
-d sui-execution/latest:sui-execution/v1:-latest \
-d external-crates/move:external-crates/move-execution \
-p sui-adapter-latest \
-p sui-move-natives-latest \
-p sui-verifier-latest \
-p move-bytecode-verifier \
-p move-stdlib \
-p move-vm-runtime
```
Which produces the following output (locally):
```
Cutting directories: [
Directory {
src: "/Users/ashokmenon/sui/sui-execution/latest",
dst: "/Users/ashokmenon/sui/sui-execution/v1",
suffix: Some(
"-latest",
),
},
Directory {
src: …
```
=> [sui-execution] Scaffold script to automate cutting new features

crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
Before this PR, tx count was updated within an epoch. This is problematic on backfill when data racing happens, as a result, epoch tx count is not accurate.
Also removed the epoch updating on each checkpoint b/c it has caused constant DB commit errors like
```
2023-06-07T23:13:27.759942Z  INFO sui_indexer::store::pg_indexer_store: Persisting epoch 19
2023-06-07T23:13:36.865246Z  WARN sui_indexer::handlers::checkpoint_handler: Indexer epoch commit failed with error: PostgresWriteError("could not serialize access due to read/write dependencies among transactions"), retrying after 100 milli-secs...
2023-06-07T23:13:36.965945Z  INFO sui_indexer::store::pg_indexer_store: Persisting epoch 19
2023-06-07T23:13:46.059553Z  WARN sui_indexer::handlers::checkpoint_handler: Indexer epoch commit failed …
```
=> indexer: exact epoch tx count

crates/sui-config/src/lib.rs, crates/sui-swarm-config/src/genesis_config.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui/src/sui_commands.rs
Adding state sync fullnodes to internal test networks means needing a set of up-to-date peer ids within both validator configs and ssfn configs, eg:
**ssfn-config-0.yaml**
```
p2p-config:
listen-address: "0.0.0.0:8084"
external-address: /dns/lax-ssfn-2.ci.sui.io/udp/8084
seed-peers:
- peer-id: 61ff2d5b789815986984f132404bc81ca7e0d7aedfb5d6dea94d477ee2dfbd2a
address: /dns/lax-suival-f9471.ci.sui.io/udp/8084
- peer-id: a1df08a64bec30bddfed076c038d5104b0dcb03932c58128c4aa073c1a068f2f
address: /dns/lax-suival-add2f.ci.sui.io/udp/8084
- peer-id: c7cd54ebfed347df9831ebbf690711ba628cf9ca02aa2e5388907b918be6de8f
```
**validator-config-0.yaml**
```
p2p-config:
listen-address: "0.0.0.0:8084"
external-address: /dns/lax-suival-f9471.ci.sui.io/udp/8084
seed-peers:
- peer-id: …
```
=> sui cli: support ssfn config generation

Cargo.lock, Cargo.toml, crates/sui-metric-checker/Cargo.toml, crates/sui-metric-checker/README.md, crates/sui-metric-checker/example/config.yaml, crates/sui-metric-checker/src/lib.rs, crates/sui-metric-checker/src/main.rs, crates/sui-metric-checker/src/query.rs, crates/workspace-hack/Cargo.toml
The sui-metric-checker crate is used for querying prometheus metrics and validating the results. It will primarily be used to check for performance regressions in nightly deployments. Requires api_key, api_user & prometheus url which can be found in sui-ops repo or by asking the PE team.
Example usage:
```
RUST_LOG=debug cargo run --package sui-metric-checker --bin sui-metric-checker  -- --api-key xxxxxx --api-user incoming_metrics --config  private-testnet-performance-test.yaml
```
Example .yaml contents: 
```
queries:
- query: 'max(current_epoch{network="private-testnet"})'
type: Instant
- query: 'histogram_quantile(0.50, sum by(le) (rate(batch_execution_latency_bucket{network="private-testnet"}[15m])))'
type: !Range
start: "now-8h"
end: "now"
step: 60.0
validate_result:
threshold: 3.0 …
```
=> Add sui-metric-checker crate

.changeset/tame-carpets-battle.md, sdk/bcs/src/index.ts, sdk/bcs/tests/alias.test.ts, sdk/bcs/tests/array.type.test.ts, sdk/bcs/tests/config.test.ts, sdk/bcs/tests/generics.test.ts, sdk/bcs/tests/inline-definition.test.ts, sdk/bcs/tests/nested.object.test.ts, sdk/bcs/tests/readme.test.ts, sdk/bcs/tests/utils.ts, sdk/bcs/tests/vector.generics.test.ts
Fixes an issue reported by @kklas: incorrect vector deserialization when T is passed through a higher-type generic.
The case is covered with tests.
---
- @mysten/bcs - fixes nested vector generic in deserialization
=> [sdk] fixes nested generic vector reading

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/Cargo.toml, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_13.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_13.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_13.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui-transactional-test-runner/src/test_adapter.rs, crates/sui-types/src/gas.rs, crates/sui-types/src/gas_model/gas_v2.rs
Use a round up function instead of buckets to charge for gas
Tests passing, I am also going to run a node to see the gas charged
---
Complete release note will be tracked in https://github.com/MystenLabs/sui/pull/12429 because there is more than one change coming and it makes more sense to track them all in one place.
We are changing bucket computation for gas charges. 
Before this protocol version gas for computation was put into buckets in order to group transactions that were roughly similar into the same price/cost. 
That, however, has created an inconsistency in …
=> Use steps to charge for gas instead of buckets

nre/dashboards/sui_mainnet_validators.json
The current public sui mainnet validator dashboard source is being published here to share with those node operators and community members who want to leverage it for their own internal monitoring purposes.
Public dashboard: https://metrics.sui.io/d/e3f62ded-4845-497c-b879-3f958b8561c2/sui-mainnet-validators
Data sources will need to be changed, some metrics will not be available at the node level, and some queries are not suitable for a single node.
This is intended to be a reference and/or stop gap solution until a more mature visibility solution into network metrics is built.
=> add sui mainnet validators dashboard json source

crates/sui-move-build/src/lib.rs, external-crates/move/move-analyzer/src/diagnostics.rs, external-crates/move/move-compiler/src/cfgir/ast.rs, external-crates/move/move-compiler/src/cfgir/borrows/mod.rs, external-crates/move/move-compiler/src/cfgir/cfg.rs, external-crates/move/move-compiler/src/cfgir/liveness/mod.rs, external-crates/move/move-compiler/src/cfgir/locals/mod.rs, external-crates/move/move-compiler/src/cfgir/mod.rs, external-crates/move/move-compiler/src/cfgir/optimize/constant_fold.rs, external-crates/move/move-compiler/src/cfgir/optimize/eliminate_locals.rs, external-crates/move/move-compiler/src/cfgir/optimize/inline_blocks.rs, external-crates/move/move-compiler/src/cfgir/optimize/mod.rs, external-crates/move/move-compiler/src/cfgir/optimize/simplify_jumps.rs, external-crates/move/move-compiler/src/cfgir/remove_no_ops.rs, external-crates/move/move-compiler/src/cfgir/translate.rs, external-crates/move/move-compiler/src/cfgir/visitor.rs, external-crates/move/move-compiler/src/command_line/compiler.rs, external-crates/move/move-compiler/src/diagnostics/codes.rs, external-crates/move/move-compiler/src/diagnostics/mod.rs, external-crates/move/move-compiler/src/expansion/ast.rs, external-crates/move/move-compiler/src/hlir/ast.rs, external-crates/move/move-compiler/src/lib.rs, external-crates/move/move-compiler/src/parser/ast.rs, external-crates/move/move-compiler/src/shared/mod.rs, external-crates/move/move-compiler/src/sui_mode/id_leak.rs, external-crates/move/move-compiler/src/sui_mode/mod.rs, external-crates/move/move-compiler/src/to_bytecode/translate.rs, external-crates/move/move-model/src/lib.rs
- Added a notion of visitors to the compiler, but it is only currently implemented for the abstract interpreter 
- Added a Helper trait for simple abstract interpreter passes 
- Implemented the ID leak verifier as an example of that interpreter
- Will hook it up in a future PR
Example output (when I turned off the filtering)
```
error[Sui E01001]: invalid object construction
┌─ /Users/tmn/sui/crates/sui-framework/packages/sui-framework/sources/clock.move:42:32
│  
42 │           transfer::share_object(Clock {
│ ╭────────────────────────────────^
43 │ │             id: object::clock(),
│ │             --  --------------- Non fresh UID from this position
│ │             │    
│ │             
The UID must come directly from sui::object::new. Or for tests, it can come from …
```
=> [move-compiler] Beginnings of a visitor framework. Expose Abstract Interpreter framework 

.changeset/brown-candles-suffer.md, dapps/kiosk/src/hooks/kiosk.ts, sdk/kiosk/src/query/kiosk.ts, sdk/kiosk/src/types/kiosk.ts, sdk/kiosk/src/utils.ts
- Adds `getOwnedKiosks` to Kiosk SDK to simplify finding kiosks owned by an address.
- Moves some types to the correct place.
- Updates the kiosk demo to reflect these changes.
---
=> [Kiosk SDK] Adds `getOwnedKiosks` query

sdk/typescript/src/utils/format.ts
https://mysten.atlassian.net/browse/APPS-1276
- For string at 6 chars or less, the formatting currently truncates incorrectly
- ie: '123456' will be truncated to '123...456', '123' will be truncated to '123...123'
---
=> [APPS-1267]: fix format address for str less than 6 chars

crates/sui-framework/docs/clob_v2.md, crates/sui-framework/docs/custodian_v2.md, crates/sui-framework/packages/deepbook/sources/clob_v2.move, crates/sui-framework/packages/deepbook/sources/critbit.move, crates/sui-framework/packages/deepbook/sources/custodian_v2.move, crates/sui-framework/packages/deepbook/sources/math.move, crates/sui-framework/packages/deepbook/tests/clob_tests.move, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_13.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Add client-defined order id to the fields of order Add original_quantity to the fields of order to record initial quantity of order Add owner address to fileds of account_cap to enable parallel use of funds Minor adjustment to query api
Abort create_account and create_pool in module clob
---
Introduce new modules: `clob_v2` and `custodian_v2` and deprecate `clob` and `custodian`.
=> [Deepbook] Cherrypick Introduce new module of clob and custodian (#12359)

.changeset/grumpy-owls-float.md, .changeset/hip-bananas-occur.md, crates/sui-protocol-config/src/lib.rs, sdk/typescript/src/builder/Inputs.ts, sdk/typescript/src/builder/TransactionBlock.ts, sdk/typescript/src/builder/TransactionBlockData.ts, sdk/typescript/src/providers/json-rpc-provider.ts, sdk/typescript/src/types/common.ts, sdk/typescript/test/e2e/protocol-config.test.ts
- Adds `getProtocolConfig()`
- Reworks the hard-coded limits to instead use the protocol config. As a performance optimization, a `protocolConfig` option can be used instead of having it fetch whenever it builds the transaction. Additionally, you can hard-code `limits` if you wish, to entirely avoid working with protocol config (not recommended, but can be used to override protocol config if you wanted to for whatever reason).
- I had to rework the limit for pure inputs so that it happens as validation instead of during serialization to bytes. This means that pure inputs are completely unlimited (can grow to infinity).
- Some things that previously errored during setting properties will now error during transaction construction to bytes (for example, setting payment coins).
How did you …
=> [ts-sdk] Use protocol config in transaction builder

crates/sui-archival/src/lib.rs, crates/sui-archival/src/tests.rs, crates/sui-archival/src/writer.rs, crates/sui-node/src/lib.rs, crates/sui-snapshot/src/reader.rs, crates/sui-snapshot/src/writer.rs, crates/sui-storage/src/blob.rs, crates/sui-storage/src/lib.rs
This PR mostly cleans up some existing code. Primarily the main changes are:
1. Move `blob` related code to blob.rs
2. Have one single file format which is used for both summary and content files. It is already written as blobs, so just introduce a common abstraction
3. Stop writing individual file's storage format and file compression in manifest. It can be read from the file header directly
5. ## Test Plan 
Existing tests
=> Multiple small refactor to blob related code

.changeset/fresh-fishes-relax.md, Cargo.lock, crates/sui-core/src/generate_format.rs, crates/sui-core/tests/staged/sui.yaml, crates/sui-open-rpc/spec/openrpc.json, crates/sui-types/src/base_types.rs, crates/sui-types/src/crypto.rs, crates/sui-types/src/lib.rs, crates/sui-types/src/multisig.rs, crates/sui-types/src/multisig_legacy.rs, crates/sui-types/src/signature.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/crypto_tests.rs, crates/sui-types/src/unit_tests/multisig_tests.rs, crates/sui/src/keytool.rs, crates/workspace-hack/Cargo.toml, doc/src/learn/cryptography/sui-multisig.md, sdk/typescript/README.md, sdk/typescript/src/builder/bcs.ts, sdk/typescript/src/cryptography/ed25519-publickey.ts, sdk/typescript/src/cryptography/multisig.ts, sdk/typescript/src/cryptography/publickey.ts, sdk/typescript/src/cryptography/secp256k1-publickey.ts, sdk/typescript/src/cryptography/secp256r1-publickey.ts, sdk/typescript/src/cryptography/signature.ts, sdk/typescript/src/index.ts, sdk/typescript/test/unit/cryptography/multisig.test.ts
This PR 1) updates serialization for multisig signature format and still maintain MultisigLegacy 2) add typescript support for the latest multisig. 
Due to the incompatibility of roaring bitmap in typescript (no broswer support), we decide to upgrade the bitmap in multisig format to use plain bitmap instead of roaring bitmap in sui protocol. This results in more compact serialization of a multisig: the bitmap field is reduced from 37 bytes to at most 10 bytes (max number of signers = 10). 
In addition, we upgrade the public key serialization to use plain bytes instead of string. This also reduce each pubkey serialization in multisig. 
The typescript sdk and rust keytool introduced in this PR follows the new protocol. MultisigLegacy is still supported in the sui protocol to provide …
=> crypto: Multisig support in typescript

crates/sui-framework/docs/clob_v2.md, crates/sui-framework/docs/custodian_v2.md, crates/sui-framework/packages/deepbook/sources/clob_v2.move, crates/sui-framework/packages/deepbook/sources/custodian_v2.move, crates/sui-framework/packages/deepbook/tests/clob_tests.move, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Using the sender address makes it possible to create `AccountCap`'s that can access the same pool of funds in a tx that does not require an `AccountCap` as input. This is dangerous because it makes it easier for a malicious app to trick a user into signing a tx that creates an `AccountCap` that can access an existing pool of funds.
New unit tests
---
Tweaked authentication model for DeepBook `AccountCap`
=> [deepbook] Use fresh object ID rather than sender address in AccountCap

.changeset/friendly-plums-promise.md, sdk/bcs/src/index.ts, sdk/bcs/tests/serde.test.ts
fixes #12470
When parsing u128 and u256 values we were incorrectly padding the lower bits.  This resulted in incorrectly decoding values in the following ranges:
* u128 values with bytes 9-16 being 0x00
* u256 values with bytes 17-32 all being 0x00
* u256 values with bytes 9-16 all being 0x00
Updated a couple test cases that triggered this issue
---
=> [bcs] Fix a bcs decoding bug for u128 and u256 values

Cargo.lock, crates/sui-cluster-test/Cargo.toml, crates/sui-cluster-test/src/faucet.rs, crates/sui-faucet/Cargo.toml, crates/sui-faucet/src/errors.rs, crates/sui-faucet/src/faucet/mod.rs, crates/sui-faucet/src/faucet/simple_faucet.rs, crates/sui-faucet/src/faucet/write_ahead_log.rs, crates/sui-faucet/src/main.rs, crates/sui-faucet/src/metrics.rs, crates/sui-faucet/src/requests.rs, crates/sui-faucet/src/responses.rs, crates/sui-test-validator/src/main.rs, crates/workspace-hack/Cargo.toml
This PR adds the `/v1/gas` api to the faucet which is the batch send request. The request gets put into a MCSP queue which another thread pulls routinely from to serve up to 500 paysui transactions at once. 
This also adds the `/v1/status` api to the faucet which checks on the status of the request based on a Uuid that is generated from the initial gas request. The status of any given Uuid is cached for 5 minutes after the request completes, and if it is deleted the user will get nothing back.
Adding batch request on faucet: 
In Progress:
Success:
Follow up items:
Change wallet to use new API
Local Testing / CI / CD / Will redirect discord devnet faucuet, and then testnet faucet onto this endpoint
---
If your changes are not user-facing and not …
=> [Faucet] Adding batch request to sui faucet

Cargo.lock, crates/sui-core/Cargo.toml, crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
The last use is in narwhal manager tests. Removing it as it just creates a config.
CI
---
=> Remove sui-core's dep to test-utils

Cargo.lock, crates/sui-benchmark/tests/simtest.rs, crates/sui-config/src/node.rs, crates/sui-e2e-tests/Cargo.toml, crates/sui-e2e-tests/tests/reconfiguration_tests.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm/src/memory/swarm.rs, crates/test-utils/src/network.rs
* Enable pruning in `msim`
* Introduce builder methods for setting n validators in a `TestCluster`/ `Swarm` / `NetworkConfig` to be unpruned
* Fixes up committe change stress test to keep 2/7 validators unpruned in order to allow new validators to catchup via state sync (without use of archival node)
Existing tests
---
=> Enable simtests for checkpoint pruning

.changeset/beige-sheep-draw.md, .changeset/forty-games-yawn.md, sdk/bcs/src/index.ts, sdk/bcs/tests/parse-type-name.test.ts, sdk/typescript/src/signers/txn-data-serializers/type-tag-serializer.ts, sdk/typescript/src/types/__tests__/common.test.ts, sdk/typescript/src/types/common.ts
This is a small cleanup of the PR originally opened by @kklas (#12373)
Fixed a problem in parseTypeName method in BCS where it naively assumes that type's type args aren't nested and just splits them by , causing the nested types to be improperly split.
E.g. parsing the type `0x5::foo::Foo<0x5::bar::Bar, 0x6::amm::LP<0x2::sui::SUI, 0x7::example_coin::EXAMPLE_COIN>> `would result in:
```js
{
name: '0x5::foo::Foo',
params: [
'0x5::bar::Bar',
'0x6::amm::LP<0x2::sui::SUI',
'0x7::example_coin::EXAMPLE_COIN>',
],
}
```
instead of
```js
{
name: "0x5::foo::Foo",
params: [
"0x5::bar::Bar",
"0x6::amm::LP<0x2::sui::SUI, 0x7::example_coin::EXAMPLE_COIN>"
]
}
````
---
If your changes are not user-facing and not a breaking change, you can skip the following …
=> [ts][bcs] fix nested type parsing in BCS 

crates/sui-adapter-transactional-tests/tests/size_limits/deleted_id_limits_tests.exp, crates/sui-adapter-transactional-tests/tests/size_limits/event_limits_tests.exp, crates/sui-adapter-transactional-tests/tests/size_limits/move_object_size_limit.exp, crates/sui-adapter-transactional-tests/tests/size_limits/new_id_limits_tests.exp, crates/sui-adapter-transactional-tests/tests/size_limits/object_runtime_limits.exp, crates/sui-adapter-transactional-tests/tests/size_limits/transfered_id_limits_tests.exp, crates/sui-adapter-transactional-tests/tests/size_limits/vector_len_limits.exp, crates/sui-cost-tables/src/tier_based/tables.rs, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_14.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_14.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_14.snap, crates/sui-types/src/gas_model/gas_v2.rs
Change gas cost tables to reduce cost of transactions.
Rationale: 
- instructions start affecting time of execution on the upper end. Some natives are more important than instructions. Also the change is still protecting against DOS attacks by making the cost rise abruptly after a certain point
- stack height does not seem to have a strong correlation to execution time, so we are making it matter less
- for memory size we are going with the intuition that up to approx 1M cost is pretty linear. 1k transaction executing concurrently at the same time (which we do not do and it's pretty foolish requiring 1k threads) would take up to 1G of RAM. All those numbers do not seem problematic
Going to evaluate the impact against existing transactions
Existing tests and manual checks against …
=> Change cost tables for gas

.github/actions/diffs/action.yml
Treat changes to `sui-execution` as rust changes to trigger the appropriate CI.  This directory contains all crates that are relevant to the execution layer plus utilities to create copies of those crates.
CI
---
=> [sui-execution] Add to isRust check in CI

sui-execution/cut/src/main.rs, sui-execution/cut/src/path.rs, sui-execution/cut/src/plan.rs
Utility functions for working with paths:
- `normalize_path` to get rid of redundant `.` and `..` components.
- `path_relative_to` to describe one path relative to another.
- `shortest_new_prefix` to find the shortest path prefix that doesn't exist (i.e. needs to be created).
- `deep_copy` to recursively copy files and directories with filtering by path.
These will be used when actually executing a plan.
```
sui-execution/cut$ cargo nextest run
```
---
=> [sui-execution] Path utilities

crates/sui/src/keytool.rs, crates/sui/src/unit_tests/keytool_tests.rs
The Sui CLI `keytool import` command now accepts either a MNEMONIC or a private key (from the Sui Wallet). The user exports a private key associated with an account in the Wallet, and uses that private key in the `keytool import` command in the CLI to import the account in the CLI. 
There is a new function to test the new private key code (`test_private_keys_ed25519`)
---
Add support to the `keytool import` command to allow for importing a private key (from the wallet) in addition to the existing support of importing an account via a mnemonic.
=> [CLI] Import wallet private key

crates/sui-benchmark/tests/simtest.rs, crates/sui-cluster-test/src/cluster.rs, crates/sui-e2e-tests/tests/checkpoint_tests.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/onsite_reconfig_observer_tests.rs, crates/sui-e2e-tests/tests/protocol_version_tests.rs, crates/sui-e2e-tests/tests/reconfiguration_tests.rs, crates/sui-e2e-tests/tests/simulator_tests.rs, crates/sui-e2e-tests/tests/snapshot_tests.rs, crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs, crates/sui-faucet/src/faucet/simple_faucet.rs, crates/sui-indexer/tests/integration_tests.rs, crates/sui-json-rpc/src/unit_tests/rpc_server_tests.rs, crates/sui-json-rpc/src/unit_tests/transaction_tests.rs, crates/sui-json-rpc/tests/balance_changes_tests.rs, crates/sui-json-rpc/tests/subscription_tests.rs, crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs, crates/sui-rosetta/tests/end_to_end_tests.rs, crates/sui-sdk/tests/stream_tests.rs, crates/sui-source-validation/src/tests.rs, crates/sui-surfer/src/lib.rs, crates/sui/src/unit_tests/validator_tests.rs, crates/sui/tests/cli_tests.rs, crates/test-utils/src/network.rs, crates/test-utils/tests/network_tests.rs
There is no point to return Result and then always unwrap.
CI
---
=> TestClusterBuilder::build() do not return Result

.changeset/strong-ways-dance.md, sdk/typescript/src/types/events.ts
`TimeRange` expects its parameters to be given in `camelCase` and accepts its numeric arguments as strings.
The following should work:
```
const provider = new JsonRpcProvider(mainnetConnection);
console.log(await provider.queryEvents({
query: {
TimeRange: {
startTime: "1686050221271",
endTime: "1686690000000",
},
},
limit: 1000
}));
```
=> [sdk] Fix `TimeRange` event query type

Cargo.lock, sui-execution/cut/Cargo.toml, sui-execution/cut/src/args.rs, sui-execution/cut/src/path.rs, sui-execution/cut/src/plan.rs
Use anyhow to introduce context to errors, to make them easier to debug.
Existing unit tests:
```
sui-execution/cut$ cargo nextest run
```
---
=> [sui-execution] Add context to errors from CLI

sui-execution/cut/src/args.rs, sui-execution/cut/src/main.rs, sui-execution/cut/src/plan.rs
Add a flag to display the cut plan without executing it.
```
sui$ cargo run --bin cut -- --dry-run --feature v1          \
-d sui-execution/latest:sui-execution/v1:-latest       \
-d external-crates/move:external-crates/move-execution \
-p sui-adapter-latest                                  \
-p sui-move-natives-latest                             \
-p sui-verifier-latest                                 \
-p move-bytecode-verifier                              \
-p move-stdlib                                         \
-p move-vm-runtime
Copying packages in: /Users/ashokmenon/sui
new [workspace] members:
- to:   sui-adapter-v1
sui-execution/v1/sui-adapter
from: sui-adapter-latest
sui-execution/latest/sui-adapter
- to:   sui-move-natives-v1
sui-execution/v1/sui-move-natives
from: …
```
=> [sui-execution] Add dry-run option

Cargo.lock, narwhal/consensus/Cargo.toml, narwhal/consensus/benches/process_certificates.rs, narwhal/consensus/src/bullshark.rs, narwhal/consensus/src/consensus.rs, narwhal/consensus/src/tests/bullshark_tests.rs, narwhal/consensus/src/tests/consensus_tests.rs, narwhal/consensus/src/tests/randomized_tests.rs, narwhal/executor/tests/consensus_integration_tests.rs, narwhal/node/src/primary_node.rs, narwhal/types/src/consensus.rs
As part of the leader election schedule change epic https://www.notion.so/mystenlabs/Leader-election-schedule-31e9abd06477436b9a38fd3282879093?pvs=4 , the first step is to build a "swap" table based on the calculated reputation scores. As a reminder we do calculate the leader reputation scores every K commit rounds. Our goal is based on those scores to come up with a set of good & bad nodes. Then for next K commit rounds we do swap the occurrences of leaders of the bad nodes with the ones of the good nodes. 
This PR is the first step. As part of the upcoming work we'll need to 
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the …
=> [narwhal] introduce the LeaderSwapTable

apps/core/src/hooks/useTransactionSummary.ts, apps/core/src/utils/transaction/getObjectChangeSummary.ts, apps/wallet/src/ui/app/shared/transaction-summary/cards/ObjectChanges.tsx, pnpm-lock.yaml
Fixes padding when Object Changes has multiple entries, some with display fields.
Also removes an Address filter than isn't really needed
Before: 
After: 
---
=> [wallet-ext] - Transaction Summary - fix padding when object changes has multiple entries with display

narwhal/primary/src/proposer.rs
Currently `min_delay_timer` is reset in proposer for the next round, after skipping rounds because of receiving higher round parents. The network mostly increments rounds at an interval of `min_header_delay`. So the following can happen,
- Primary A receives parents from round 15, skips proposing round 14.
- Primary A waits for min_header_delay=0.5s to propose at round 15.
- Primary A receives parents from round 16, skips proposing round 15.
This change avoids the additional wait in `min_delay_timer` when the proposer skips rounds, to help the lagging primary become get in sync with the network.
This change is intentionally simplified. A bigger refactor along with some fixes to proposer will be done in a future PR.
Also, fix an issue where `advance`, `min_delay_timed_out`, …
=> [Narwhal] disable min_delay_timer after skipping rounds in proposer

crates/sui-archival/src/tests.rs, crates/sui-archival/src/writer.rs, crates/sui-node/src/lib.rs
The checkpoint tailer task does blocking file i/o in tight loop and yet it was being invoked in the async context. This would cause the receiver to not receive mpsc channel messages (or receive them after a very long delay) as it was likely assigned to the same thread as tailer (the one invoking blocking calls) and the tailer would not yield the thread (since it tails checkpoints in a loop). This was causing the archive files to wait a long time on local fs before they could get uploaded to s3.
The fix is simple - just move the tailer to `spawn_blocking` instead of `spawn` and that fixes the problem. After this change, I see no such issue and receiver receives channel messages instantly and files are getting uploaded without any delay.
As an added bonus, the code is a little simpler too …
=> Switch to tokio::spawn_blocking for archive task which does blocking file i/o

crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/mod.rs
Move EffectsV1 to a separate file from the trait.
Trivial refactoring.
---
=> Separate effects_v1 file

narwhal/primary/src/proposer.rs
Cherry-pick the change to 1.4.0 to help improve testnet and mainnet validators' certificate creation rates.
Currently `min_delay_timer` is reset in proposer for the next round, after skipping rounds because of receiving higher round parents. The network mostly increments rounds at an interval of `min_header_delay`. So the following can happen,
- Primary A receives parents from round 15, skips proposing round 14.
- Primary A waits for min_header_delay=0.5s to propose at round 15.
- Primary A receives parents from round 16, skips proposing round 15.
This change avoids the additional wait in `min_delay_timer` when the proposer skips rounds, to help the lagging primary become get in sync with the network.
This change is intentionally simplified. A bigger refactor along with some fixes to …
=> Cherrypick #12580 to 1.4.0

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-node/src/lib.rs, crates/test-utils/src/network.rs
This is just to be extra sure that we are testing the worst case tx/fx pruning in order to maximize hitting edge cases. At epoch boundary, after the epoch store has been swapped, we prune all eligible transactions and effects (which should be all existing transactions and effects at that point), and ensure that we can continue. This more strongly confirms that the protocol does not depend on prune-eligible transactions and effects at any point.
All reconfig simtests will exercise this
---
=> Perform full checkpoint pruning at epoch boundary in simtests

crates/sui-adapter-transactional-tests/tests/child_count/unwrap_never_stored.exp, crates/sui-adapter-transactional-tests/tests/dynamic_fields/unwrap_object.exp, crates/sui-adapter-transactional-tests/tests/sui/unwrap_then_delete.exp, crates/sui-adapter-transactional-tests/tests/sui/unwrap_then_delete.move, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-core/src/authority/authority_test_utils.rs, crates/sui-core/src/state_accumulator.rs, crates/sui-core/src/test_utils.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/src/unit_tests/move_integration_tests.rs, crates/sui-e2e-tests/tests/unwrapped_then_deleted_tests.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_16.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_16.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_16.snap, crates/sui-sdk/src/wallet_context.rs, crates/sui-snapshot/src/tests.rs, crates/sui-snapshot/src/writer.rs, crates/sui-surfer/src/surfer_task.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui-types/src/storage.rs, crates/sui-types/src/temporary_store.rs, crates/test-utils/src/network.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
This PR cherry-picks the change to enable simplified_unwrapped_then_delete.
CI + devnet
---
Prior to this change, unwrapped_then_deleted field in TransactionEffects only contain unwrapped then deleted objects that previously existed in the store (i.e. was once unwrapped in its lifetime). If an object was always wrapped since creation and was never unwrapped ever, it wouldn't show up in unwrapped_then_deleted. This this change, we no longer makes such distinction. As long as an object is unwrapped then deleted in a transaction, it would show up in effects regardless of …
=> Cherry pick unwrapped then deleted simplification to release branch

Cargo.lock, Cargo.toml, crates/sui-source-validation-service/Cargo.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs, crates/workspace-hack/Cargo.toml
This adds a basic server (with `actix`) for serving source. The intent is just to get the package and directory structure sorted out. I:
- added a `main.rs` for the binary
- `lib.rs` where the main implementation will go
- `tests/tests.rs` for tests
- placed in `crates/sui-source-validation-service` tomirror `crates/sui-source-validation`
Feedback welcome on this structure.
See [reference doc](https://www.notion.so/mystenlabs/Move-Source-Provider-Service-91ec291be3b94c0f8133e981b76988c0) for background on this work.
Thanks to @mystenmark for unblocking `actix` dependency with https://github.com/MystenLabs/sui/pull/12583!
Added a basic test that will exercise end-to-end functionality later.
---
If your changes are not user-facing and not a breaking change, you can skip the following …
=> move: source service scaffolding

crates/sui-benchmark/tests/simtest.rs, crates/sui-framework/docs/clob_v2.md, crates/sui-framework/packages/deepbook/sources/clob_v2.move, crates/sui-framework/packages/deepbook/tests/clob_tests.move, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_16.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_16.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_16.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
The self-matching prevention mechanism ensures that the matching engine
takes measures to avoid unnecessary trades
when matching a user's buy/sell order with their own sell/buy order.
There are four Self-Trade Prevention Options.
1. Decrement & cancel: Cancel smaller order and decrement larger order by the smaller size.
If the same size, cancel both.
2. Cancel oldest: Cancel older (resting) order in full.
Continue to execute the newer taking order.
3. Cancel newest: Cancel newer (taking) order in full.
Let the old resting order remain on the order book.
4. Cancel both: Cancel both orders immediately.
For now, we have only implemented the behavior of canceling the oldest order.
However, we have reserved the self_matching_prevention option as a parameter
in case we need to implement other …
=> [deepbook] Introducing the implementation of self-matching prevention. 

dapps/kiosk/src/components/Inventory/OwnedObject.tsx, dapps/kiosk/src/components/Inventory/OwnedObjects.tsx, dapps/kiosk/src/components/Kiosk/FindKiosk.tsx, dapps/kiosk/src/components/Kiosk/KioskData.tsx, dapps/kiosk/src/components/Kiosk/KioskItem.tsx, dapps/kiosk/src/components/Kiosk/KioskItems.tsx, dapps/kiosk/src/components/Kiosk/KioskSelector.tsx, dapps/kiosk/src/components/Modals/ListPrice.tsx, dapps/kiosk/src/hooks/kiosk.ts, dapps/kiosk/src/hooks/useKioskSelector.ts, dapps/kiosk/src/mutations/kiosk.ts, dapps/kiosk/src/routes/Home.tsx, dapps/kiosk/src/routes/SingleKiosk.tsx, dapps/kiosk/src/routes/index.tsx, dapps/kiosk/src/utils/utils.ts, dapps/kiosk/vercel.json
- Searching a kiosk by an `address`, instead of just using a `kioskId`
- Adds support for multiple kiosks (You can select which kiosk to view, if an address has more than one).
- Manage multiple kiosks (list/delist/take/withdraw from any of the addresses' owned kiosks)
---
=> [dapps] Kiosk demo - search by address & support multiple owned kiosks

apps/wallet/src/background/connections/UiConnection.ts, apps/wallet/src/background/qredo/index.ts, apps/wallet/src/shared/messaging/messages/payloads/QredoConnect.ts, apps/wallet/src/ui/app/background-client/index.ts, apps/wallet/src/ui/app/hooks/useQredoAPI.ts, apps/wallet/src/ui/app/hooks/useQredoInfo.ts, apps/wallet/src/ui/app/pages/qredo-connect/SelectQredoAccountsPage.tsx
* when injecting a new qredo connection show any existing connected accounts as selected
https://github.com/MystenLabs/sui/assets/10210143/ad12cb42-f7a8-4419-aee4-2aa3ae3b30a7
Manual testing
---
=> wallet-ext: preselect already connected qredo accounts

apps/explorer/src/components/GasPriceCard/index.tsx, apps/explorer/src/components/GasPriceCard/utils.ts
show only 30 epochs and remove the select box
| - | - |
| <img width="461" alt="Screenshot 2023-06-21 at 11 48 45" src="https://github.com/MystenLabs/sui/assets/10210143/4a0fb410-cdfa-4f23-b7a5-7c3e7a85f44e"> | <img width="461" alt="Screenshot 2023-06-21 at 11 48 57" src="https://github.com/MystenLabs/sui/assets/10210143/988c5ec8-5547-4bda-881b-71c0f7a16f77"> |
Manual testing 
---
=> explorer: gas reference price graph hide epochs select

apps/wallet/src/background/connections/ContentScriptConnection.ts, apps/wallet/src/background/index.ts, apps/wallet/src/background/keyring/Account.ts, apps/wallet/src/background/keyring/DerivedAccount.ts, apps/wallet/src/background/keyring/ImportedAccount.ts, apps/wallet/src/background/keyring/LedgerAccount.ts, apps/wallet/src/background/keyring/QredoAccount.ts, apps/wallet/src/background/keyring/accounts.tsx, apps/wallet/src/background/keyring/index.ts, apps/wallet/src/dapp-interface/WalletStandardInterface.ts, apps/wallet/src/shared/messaging/messages/payloads/account/GetAccountResponse.ts, apps/wallet/src/shared/messaging/messages/payloads/keyring/index.ts, apps/wallet/src/shared/messaging/messages/payloads/wallet-status-change/index.ts, apps/wallet/src/ui/app/background-client/index.ts, apps/wallet/src/ui/app/components/ledger/SuiLedgerClientProvider.tsx, apps/wallet/src/ui/app/components/ledger/useDeriveLedgerAccounts.ts
* silently migrate storage to save the public key of the wallet accounts when the wallet unlocks (only the first time when no public keys are stored)
* save public keys when adding new accounts
* try to get the public keys of ledger accounts every time the wallet loads or when user switches active account or tries to sign with a ledger account etc and there are ledger accounts without public key
closes APPS-1293
manual testing
---
=> wallet-ext: expose public key of account to dapps

crates/sui-adapter-transactional-tests/tests/child_count/unwrap_never_stored.exp, crates/sui-adapter-transactional-tests/tests/dynamic_fields/unwrap_object.exp, crates/sui-adapter-transactional-tests/tests/sui/unwrap_then_delete.exp, crates/sui-core/src/unit_tests/move_integration_tests.rs, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_16.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_16.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_16.snap
This PR adds protocol config version 16, and enables a new feature flag simplified_unwrap_then_delete.
Under this new feature flag, we no longer consult the object store when constructing unwrapped_then_deleted in the effects, and no longer include wrapped tombstones in state accumulator. It will require a re-accumulation at epoch change during the upgrade.
Added tests in previous CI.
Will also sync testnet, and deploy this upgrade on devnet.
---
Prior to this change, unwrapped_then_deleted field in TransactionEffects only contain unwrapped then deleted objects that …
=> Enable simplified_unwrap_then_delete

Cargo.lock, crates/sui-source-validation-service/Cargo.toml, crates/sui-source-validation-service/config.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs
This adds a basic config file to initialize the server with. It takes a list of `Packages`, where `Packages` comprise a repository and one or more paths to Move package in that repository. 
Added a basic test to parse a config file.
---
=> move: source service config

crates/sui-indexer/benches/indexer_benchmark.rs, crates/sui-indexer/migrations/2023-03-05-165748_transaction_index/down.sql, crates/sui-indexer/migrations/2023-03-05-165748_transaction_index/up.sql, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/models/transaction_index.rs, crates/sui-indexer/src/schema.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/src/types.rs
Before this change, tx query via changed object needed to scan the whole transactions table, b/c changed objects is a vector, which cannot be indexed for querying an element in the vector.
1. local indexer writer to make sure tables including newly added changed_objects can be populated properly;
2. spot check tx query endpoints to make sure endpoints can return consistent results with reasonable latency;
3. repro steps 1 & 2 with testing indexer writer-2 k8 pod.
```
--data-raw '{
"id": 1,
"method": "suix_queryTransactionBlocks",
"params": [
{
"filter": {
"FromOrToAddress": {"addr": "0x3dc7a8a21f5d3bc17337260079688d8aefb76f27978e7ec082a5fb0d06bc8b39"}
}
},
null,
10,
false
] …
```
=> indexer: changed objects for tx query migrations

crates/sui-benchmark/tests/simtest.rs, crates/sui-framework/docs/clob_v2.md, crates/sui-framework/packages/deepbook/sources/clob_v2.move, crates/sui-framework/packages/deepbook/tests/clob_tests.move, crates/sui-protocol-config/src/lib.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Cherry-pick https://github.com/MystenLabs/sui/pull/12464 to release branch.
The self-matching prevention mechanism ensures that the matching engine
takes measures to avoid unnecessary trades
when matching a user's buy/sell order with their own sell/buy order.
There are four Self-Trade Prevention Options.
Decrement & cancel: Cancel smaller order and decrement larger order by the smaller size.
If the same size, cancel both.
Cancel oldest: Cancel older (resting) order in full.
Continue to execute the newer taking order.
Cancel newest: Cancel newer (taking) order in full.
Let the old resting order remain on the order book.
Cancel both: Cancel both orders immediately.
For now, we have only implemented the behavior of canceling the oldest order.
However, we have reserved the …
=> Cherry pick 652fa40 (deep book change) to release

Cargo.lock, crates/sui-source-validation-service/Cargo.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs
Stacked on https://github.com/MystenLabs/sui/pull/12552
On start, the server clones repositories and does sparse-checkout for package paths as specified in config. Tasks are spawned separately for each repository.
Example: The sequence of `git` commands for the `mystenlabs/sui` repo and its packages look as follows:
```
git clone -n --depth=1 --filter=tree:0 https://github.com/mystenlabs/sui $TMPDIR
git sparse-checkout -C $TMPDIR set --no-cone crates/sui-framework/packages/deepbook crates/sui-framework/packages/move-stdlib crates/sui-framework/packages/sui-framework crates/sui-framework/packages/sui-system
git -C $TMPDIR checkout
```
I ended up using `std::process::Command` after investigating:
- `libgit2` -- appears to have [no sparse-checkout …
=> move: source service clone packages

Cargo.lock, crates/sui-source-validation-service/Cargo.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs
Stacked on https://github.com/MystenLabs/sui/pull/12590
Adds telemetry dependency with basic `info` logging as we clone repos. Running the binary you'll now see like
Tested manually, not straightforward to unit test and also overkill for logging
---
=> move: add basic telemetry to source service

crates/sui-e2e-tests/tests/zklogin_tests.rs, crates/test-utils/src/network.rs
Use TestCluster in zklogin tests.
CI
---
=> Use TestCluster in zklogin tests

crates/sui-config/src/p2p.rs, crates/sui-network/src/discovery/builder.rs, crates/sui-network/src/discovery/mod.rs, crates/sui-network/src/discovery/tests.rs, crates/sui-network/src/utils.rs
This PR adds support segmented discovery network. Now with `AccessType::Private`  a node could declare its being private. Other nodes would not contact it unless it's in their `allowlisted_peers` list. `allowlisted_peers` differs from `seed_peers` in that it only treat the specified peers as `PeersAffinity::High`, but won't necessarily proactively contact them for state sync.
`AccessType` is configurable in `DiscoveryConfig` and defaults to public.
Extensive unit test case.
---
This PR adds support segmented discovery network.
=> support segmented network with access type and allowlisted peers

crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/protocol_version_tests.rs, crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-e2e-tests/tests/zklogin_tests.rs, crates/test-utils/src/authority.rs, crates/test-utils/src/network.rs
This PR replaces many uses of `spawn_test_authorities` with TestCluster. There are still a few left but they require some more dedicated effort to remove, so will do in a separate PR.
CI
---
=> Always use test cluster for tests

.changeset/thick-bottles-repeat.md, apps/wallet/src/background/keyring/Vault.ts, apps/wallet/src/background/keyring/VaultStorage.test.ts, apps/wallet/src/background/keyring/VaultStorage.ts, apps/wallet/src/background/keyring/index.test.ts, apps/wallet/src/background/keyring/index.ts, apps/wallet/src/test-utils/vault.ts, sdk/typescript/src/cryptography/ed25519-keypair.ts
minimise usage of mnemonic phrase and use the mnemonic seed instead to derive wallet key pairs
* sdk add method to created Ed25519Keypair from a mnemonic seed
* wallet store the mnemonic seed in storage to avoid generating the mnemonic to derive key pairs
* this will minimise the times that mnemonic phrase exists in memory
closes [APPS-1098](https://mysten.atlassian.net/browse/APPS-1098)
---
=> wallet-ext: use mnemonic seed to derive accounts

apps/wallet/src/ui/app/pages/approval-request/transaction-request/index.tsx
in transaction request view, don't show the confirmation modal when user rejects the transaction
Before
https://github.com/MystenLabs/sui/assets/10210143/3529df6a-2c72-4e74-95a8-3ad67a44497d
After
https://github.com/MystenLabs/sui/assets/10210143/e29bc9cb-c3b8-4719-9a3a-23db6386fdc3
closes APPS-1331
Manual testing
---
=> wallet-ext: fix showing confirmation modal when rejecting a transaction request

crates/sui-indexer/src/apis/indexer_api.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
IIRC there was a time we returned full contents for query tx, but now only digests are returned.
Test with local reader + remote testing mainnet DB
---
=> indexer: query tx returns digests only

crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-e2e-tests/tests/shared_objects_version_tests.rs, crates/test-utils/src/network.rs
Use TestCluster in shared_objects_version_tests
CI
---
=> Use TestCluster in shared_objects_version_tests

Cargo.lock, crates/sui-archival/src/reader.rs, crates/sui-archival/src/tests.rs, crates/sui-config/src/node.rs, crates/sui-core/Cargo.toml, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-network/src/state_sync/mod.rs, crates/sui-network/src/state_sync/tests.rs, crates/sui-node/src/lib.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui-tool/src/lib.rs
Ensure that checkpoints pruner never prunes checkpoints beyond the latest archived checkpoint. A node can mark certain archives as the ones to use for archival watermark computation by setting the flag `use_for_pruning_watermark: true`. 
1. A node may have multiple archives that it can read checkpoints from but only mark certain ones to use for watermark calculation
2. If none of the archive configs have the flag `use_for_pruning_watermark: true` set, pruning works as is (it doesn't take into consideration any archive watermark)
3. Nodes who are just users of other archives (and not actually the ones archiving the data for examples validators, community run full nodes, etc) will not need to set `use_for_pruning_watermark: true` and for them pruning works as is. Whereas mysten run …
=> Make checkpoints pruner archival watermark aware

apps/core/package.json, apps/core/src/hooks/useGetKioskContents.ts, apps/core/tsconfig.json, apps/explorer/src/components/OwnedObjects/index.tsx, apps/explorer/tsconfig.json, apps/wallet/configs/ts/tsconfig.common.json, apps/wallet/package.json, apps/wallet/src/ui/app/hooks/useGetNFTs.ts, apps/wallet/src/ui/app/hooks/useOwnedNFT.ts, apps/wallet/src/ui/app/pages/home/nft-details/index.tsx, apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx, pnpm-lock.yaml, sdk/kiosk/src/utils.ts, sdk/typescript/src/types/index.ts
As part of the work for supporting SuiFrens updates,  we are adding Kiosk / Marketplace links for items contained within a Sui Kiosk on the NFT Transfer page since Bullsharks will be locked in a Kiosk.
I started going down the route of adding support for transferring non-locked items, as well as re-working things to reduce some duplicate logic, but due to time constraints I will add that in a follow-up PR. 
---
=> [wallet-ext] - suifrens / kiosk - add marketplace links for kiosk items

apps/wallet/src/background/Alarms.ts, apps/wallet/src/background/Transactions.ts, apps/wallet/src/background/index.ts
* setup an alarm to clean up stale transaction requests
* stop storing approved transactions
closes APPS-956
Manual testing
---
=> wallet-ext: clean up transaction requests storage

crates/sui-faucet/src/faucet/mod.rs, crates/sui-faucet/src/faucet/simple_faucet.rs, crates/sui-faucet/src/main.rs, crates/sui-faucet/src/responses.rs
Addition of a feature flag to gate the batch api behavior
Unit testing to make sure the send UUID can be found.
---
=> [Faucet] Adding new API with old function call for fallback

crates/sui-core/src/authority.rs, crates/sui-core/src/transaction_manager.rs
This avoids fullnodes from crashing when it is lagging behind and executing a transaction using clock input.
CI
---
=> Cherrypick #12682 to v1.4.0 release

crates/sui-core/src/authority/authority_store_tables.rs
BlobDB needs to be disabled (and the node needs to be resynced from scratch) before enabling effects pruning. 
The combination of BlobDB and pruning leads to high CPU utilization on the host, to the extent that the node stops making any progress. 
This happens because once a range delete is observed by a compaction job, RocksDB needs to deserialize the blob, remove the entry, serialize it again, and create a new blob multiple times
=> disable blobdb

crates/sui/src/keytool.rs, doc/src/learn/cryptography/sui-multisig.md
Add a keytool to optionally verify the multisig against tx data. 
```
target/debug/sui keytool multi-sig-combine-partial-sig --pks ADaQdaIciOWgJW5OJA2thgNqdZVpxhIuOwf1cdaqkSv+ AQO4mqrF7ivphT0dZrfLzlsbik69uWDRsHaTmeR26cFXHg== AgOPrEEZEEkA684HidCE7Gs4UVFiZ4LqqMrzIt52gCFQFw== --weights 1 2 3 --threshold 3 --sigs AOANKYYgDFcU94E//oQ/GQ2cUJc5yzA/P4tTKsB1+kZGrxX9t3Xab37pgnG+LpNu3QHOlkGtuoY90j+SXGSYSgw2kHWiHIjloCVuTiQNrYYDanWVacYSLjsH9XHWqpEr/g== AQg68A6ExNRI2k7E9L4JWdp16lufhFYUScESMSvqf/B69ws31u94kTei73fz4YfvkVmuC2vF1YmPdkbpLxPy3TwDuJqqxe4r6YU9HWa3y85bG4pOvblg0bB2k5nkdunBVx4= --tx-byt
es AAABAAgCAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDcGF5D2RpdmlkZV9hbmRfa2VlcAEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDc3VpA1NVSQACAAEAAHcz9q8NRvbeKdQliqr4M6vNibf0qFjcQN4KKtebPMqaAR8uJNV17ycsTxV …
```
=> multisig: add tool to verify a multisig locally

apps/explorer/package.json, apps/explorer/src/components/Activity/index.tsx, apps/explorer/src/components/Object/DynamicFieldsCard.tsx, apps/explorer/src/components/Object/ObjectFieldsCard.tsx, apps/explorer/src/components/module/PkgModulesWrapper.tsx, apps/explorer/src/components/top-packages/TopPackagesCard.tsx, apps/explorer/src/components/transactions/TransactionsForAddress.tsx, apps/explorer/src/pages/checkpoints/CheckpointDetail.tsx, apps/explorer/src/pages/epochs/EpochDetail.tsx, apps/explorer/src/pages/home/Home.tsx, apps/explorer/src/pages/object-result/views/PkgView.tsx, apps/explorer/src/pages/object-result/views/TokenView.tsx, apps/explorer/src/pages/transaction-result/Signatures.tsx, apps/explorer/src/pages/transaction-result/TransactionView.tsx, apps/explorer/src/ui/FilterList.tsx, apps/explorer/src/ui/Tabs.tsx, apps/explorer/src/ui/stories/Tabs.stories.tsx, pnpm-lock.yaml
This moves the explorer to use Radix tabs instead of headless. This will be our new a11y solution that we can use everywhere.
Ran locally.
---
=> Remove headless tabs from explorer

Cargo.lock, crates/sui-source-validation-service/Cargo.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/tests/fixture/sui/move-stdlib/Move.toml, crates/sui-source-validation-service/tests/fixture/sui/move-stdlib/sources/address.move, crates/sui-source-validation-service/tests/tests.rs, crates/sui-source-validation/src/tests.rs
This hooks up package source verification on server start, for repos in `config`. Each package is processed async. Go by commit for an easier review, the second commit just factors out common code to a helper.
Note on test: we check whether a known-bad variety of `move-stdlib` fails. This is convenient because (a) `move-stdlib` is published in the test cluster setup without any dependencies (b) we can just use a small dummy package to verify against (i.e., not copy, build, and verify something large in the test) (c) it is resilient to changes to `movestdlib` or other `sui-framework` packages published on the test cluster chain.
If we also test against known-good packages, we have to do a lot of test setup similar to what `sui-source-validation` tests already do, which is why I feel …
=> move: source service verifies packages

crates/sui-source-validation-service/src/lib.rs
Stacked on https://github.com/MystenLabs/sui/pull/12665
Simple fix, noticed `stderr` printed the byte array and not a string.
Manually tested for this strictly debugging feature--we don't want to exercise the actual `git clone` commands in automated tests at this stage.
=> move: fix source service stderr format

crates/sui-indexer/src/apis/indexer_api.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
- I was dumb and thought that we only need digests, but playing production traffic showed otherwise :(
this PR is essentially reverting #12657 other than some minor changes.
- also fixed the issue that tx fetched from `transactions` table does not follow the input digest order
- also changed `valdiate_limit` to `cap_page_limit` to be consistent with FN.
compare Explorer traffic hitting FN RPC and testing indexer RPC
```
curl --location --request POST https://explorer-rpc.mainnet.sui.io:443 \
--data-raw '{
"id": 1,
"method": "suix_queryTransactionBlocks",
"params": [
{
"filter": {
"ToAddress": "0x64c86d82898f3baf4078034cf7a49ba2cab5e21eda043c9e30c509a9dcfbcbbc"
},
"options": {
"showInput": true,
"showEffects": true
}
},
null,
1, …
```
=> indexer: populate queried tx based on options again

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-types/src/messages_grpc.rs
The logic is incompatible with TransactionManager AvailableObjectCache. Populating objects in AvailableObjectCache is essential for correctness in TransactionManager::enqueue(), so disabling AvailableObjectCache for any or all objects requires refactoring TransactionManager. Also, fullnode local execution itself is disabled now.
CI.
---
=> Disable fullnode local execution object fast path

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-types/src/messages_grpc.rs
The previous workaround for the object fast path needs to be fixed.
CI
---
=> Cherrypick #12717 into release 1.4.0

Cargo.lock, crates/sui-framework/build.rs, crates/sui-move-build/Cargo.toml, crates/sui-move-build/src/lib.rs, crates/sui-move-build/src/linters/mod.rs, crates/sui-move-build/src/linters/share_owned.rs, crates/sui-move-build/tests/linter/share_owned.exp, crates/sui-move-build/tests/linter/share_owned.move, crates/sui-move-build/tests/linter_tests.rs, crates/sui-move/src/build.rs, crates/sui-move/src/unit_test.rs, crates/sui-source-validation-service/src/lib.rs, crates/sui/src/client_commands.rs, crates/sui/tests/cli_tests.rs, external-crates/move/move-compiler/src/command_line/compiler.rs, external-crates/move/move-compiler/tests/move_check_testsuite.rs
Added support for writing linters:
- integration with Sui CLI
- a simple testing harness
- an example linter to signal sharing of potentially owned objects
Additional testing framework being part of this PR can be used to test individual linters.
---
Developers may now opt into running linters when building/testing/publishing/upgrading packages via CLI by specifying the `--lint` flag.
=> [move-compiler] Added preliminary support for writing linters

crates/sui-core/src/authority.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-storage/src/indexes.rs, crates/sui-tool/src/db_tool/index_search.rs
1. move post processing before critical commits. This makes sure the post processing wouldn't run out of causal order.
2. change some `continue`s to panic so bugs will scream loudly.
3. pass `inner_temp_store.written` to post processing code such that latest objects become accessible without looking into DB (which is not ready at that point)
4. deprecates `timestamps` indexer column which is not meaningful and in use.
Apply this to 1.4.0 and resync from genesis. 
---
This change is fullnode only and does not impact validator. If a fullnode serves RPC requests based on …
=> move post processing before critical commits

.changeset/quick-monkeys-hang.md, sdk/build-scripts/src/build-package.ts, sdk/typescript/keypairs/ed25519/package.json, sdk/typescript/keypairs/secp256k1/package.json, sdk/typescript/keypairs/secp256r1/package.json, sdk/typescript/package.json, sdk/typescript/src/cryptography/keypair.ts, sdk/typescript/src/cryptography/multisig.ts, sdk/typescript/src/cryptography/publickey.ts, sdk/typescript/src/cryptography/signature.ts, sdk/typescript/src/cryptography/utils.ts, sdk/typescript/src/index.ts, sdk/typescript/src/keypairs/ed25519/index.ts, sdk/typescript/src/keypairs/ed25519/keypair.ts, sdk/typescript/src/keypairs/ed25519/publickey.ts, sdk/typescript/src/keypairs/secp256k1/index.ts, sdk/typescript/src/keypairs/secp256k1/keypair.ts, sdk/typescript/src/keypairs/secp256k1/publickey.ts, sdk/typescript/src/keypairs/secp256r1/index.ts, sdk/typescript/src/keypairs/secp256r1/keypair.ts, sdk/typescript/src/keypairs/secp256r1/publickey.ts, sdk/typescript/src/signers/raw-signer.ts, sdk/typescript/src/utils/verify.ts, sdk/typescript/test/unit/cryptography/secp256k1-publickey.test.ts, sdk/typescript/test/unit/cryptography/secp256r1-publickey.test.ts
This moves implemtations for various keypairs into a new `src/keypairs` directory and allows the associated classes to be imported directly (eg. `import { Ed25519Keypair } from '@mysten/sui.js/keypairs/ed25519';`
Exporting these files required some refactoring because there were several utility functions defined in files needed by the keypair implementations.  These utils have been moved to a new `cryptography/utils.ts` so that the keypair implementations do not automatically import all other keypair implementations via indirect imports.
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during …
=> [ts-sdk] add modular exports for keypairs

apps/wallet/src/ui/app/shared/transaction-summary/cards/GasSummary.tsx
Fixes the 'You Paid' label showing in Gas Summary when wallet owner did not actually pay. 
Also addresses a few small styling tweaks
---
=> [wallet-ext] - fix incorrect label in gas summary

crates/sui-core/src/authority/authority_store_tables.rs
BlobDB needs to be disabled (and the node needs to be resynced from scratch) before enabling effects pruning.
The combination of BlobDB and pruning leads to high CPU utilization on the host, to the extent that the node stops making any progress. This happens because once a range delete is observed by a compaction job, RocksDB needs to deserialize the blob, remove the entry, serialize it again, and create a new blob multiple times
=> disable blobdb (#12626)

crates/sui-core/src/authority/authority_store_tables.rs
BlobDB needs to be disabled (and the node needs to be resynced from scratch) before enabling effects pruning. 
The combination of BlobDB and pruning leads to high CPU utilization on the host, to the extent that the node stops making any progress. 
This happens because once a range delete is observed by a compaction job, RocksDB needs to deserialize the blob, remove the entry, serialize it again, and create a new blob multiple times
=> [cherry pick] disable blobdb

pnpm-workspace.yaml
The changeset-version script is failing because of new package.json files created for modular exports in the typescript sdk. This will hopefully fix the issue.
Test Plan
Merge the PR and see if it fixes the issue, this has not been reproduced locally.
The error on main only complains about sdk/typescript/builder/package.json, and does not have issues with the packages inside keypairs, which makes me think there is a difference between how glob patterns are matched locally vs CI for manypkg check.
---
=> [ci] fix changeset-version script

Cargo.lock, crates/sui-json-rpc-types/src/sui_coin.rs, crates/sui-json-rpc/Cargo.toml, crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/error.rs, crates/sui-types/src/coin.rs, crates/sui-types/src/object.rs
Map client-side errors to standard client error code: namely, invalid `coin_type` inputs to `coin_api` now yields a client `-32602` `CannotParseSuiStructTag` error instead of a `-32000` internal server error. Similarly, invalid cursors will also yield a -32602 if the provided cursor cannot be found or is not a coin.
Unit tests to cover user-facing errors and some internal errors.
As part of error handling improvements, I'd like to write unit tests that simulate different error scenarios to validate that appropriate errors are being generated and propagated correctly. This requires some refactoring.
To enable unit tests on our jsonrpc apis, I refactored the existing implementation such that there is a `StateServiceWrapper` wrapping `AuthorityState`, and a `CoinReadInternalTrait` that …
=> refactor coin_api for unit tests around error handling

crates/sui-adapter-transactional-tests/tests/dev_inspect/load_old_object.exp, crates/sui-adapter-transactional-tests/tests/dev_inspect/load_old_object.move, crates/sui-core/src/authority/authority_test_utils.rs, crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
- Added minimal dev-inspect support for programmable transactions
- Added a new test. 
- I will use more extensively in #12055 
---
=> [move][transactional tests] Add dev-inspect support

Cargo.lock, crates/sui-cost/Cargo.toml, crates/sui-cost/tests/empirical_transaction_cost.rs
Simplify the gas cost tests to use TestCluster.
CI
---
=> Use TestCluster in gas cost tests

crates/sui-core/src/checkpoints/checkpoint_executor/metrics.rs, crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
This one is more reliable to use by HAProxy to determine FN health (e.g., in case a node is stuck)
---
=> [tiny] Add a gauge with last_executed_checkpoint_timestamp_ms value

crates/sui-benchmark/src/benchmark_setup.rs, crates/sui-benchmark/src/options.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui-types/src/object.rs
This PR changes benchmark setup to use TestCluster when running locally. `server_metric_port` option was removed to make this easier. Instead available ports will be picked by the code and different for each node. Some other unused test functions for generating gas objects were removed too since we want to discourage inserting genesis objects in tests.
existing tests
---
=> [benchmark] use TestCluster in local setup

crates/sui-replay/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-replay/src/types.rs
Print diag info in replay. For now it only prints loaded child object versions
Manual
---
=> add diag printing in local replay

crates/sui-replay/src/data_fetcher.rs, crates/sui-replay/src/lib.rs, crates/sui-replay/src/replay.rs
When a package is upgraded we dont have all the packages in its linkage table so we might need to fetch that over rpc. This PR adds a backup rpc url option for fetching data when its absent in node state dump.
Manual
---
=> use backup url for dump replay

apps/wallet/src/ui/app/staking/useGetDelegatedStake.tsx, apps/wallet/tests/staking.spec.ts
Current problem. The button does not dynamically refetch.
https://mysten-labs.slack.com/archives/C042YF60NH2/p1687923874438029
https://mysten.atlassian.net/browse/APPS-1370
---
=> [wallet]: add refetchInterval to useGetDelegatedStake

apps/explorer/src/ui/CopyToClipboard.tsx, apps/explorer/src/ui/PageHeader.tsx, apps/icons/src/Copy18.tsx, apps/icons/src/index.ts, apps/icons/svgs/copy_18.svg
https://mysten.atlassian.net/browse/APPS-1375
- Update `CopyToClipboard` with `lg` being Copy18
---
=> [Explorer]: Update CopyToClipboard Icon

crates/sui-protocol-config/src/lib.rs, crates/sui-replay/src/fuzz.rs, crates/sui-replay/src/lib.rs, crates/sui-replay/src/replay.rs, external-crates/move/move-vm/profiler/src/lib.rs, external-crates/move/move-vm/runtime/src/session.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/src/lib.rs
**Added two features:**
1. When hovering, the full function name is displayed. See image.
2. Specify the executor version in replay. Negative number means use latest executor version.
```
env MOVE_VM_PROFILE=1 ./target/debug/sui-tool replay tx -t AbfBmKgsx4SaMY3XuNgqZ1DAxD5riLvos6B4hhaMb8y8 -e -1
```
Manual
---
=> show full function name in hover; specify exec version in replay

crates/sui-tool/src/db_tool/mod.rs, crates/sui-types/src/digests.rs
Adds two commands, PrintCheckpoint and PrintCheckpointContent. Both are by digest.
Tested on local db.
---
=> Add checkpoint printing to db-tool

crates/sui-tool/src/db_tool/mod.rs, crates/sui-types/src/digests.rs
Adds two commands, PrintCheckpoint and PrintCheckpointContent. Both are by digest.
Tested on local db.
---
---
=> [Cherry-pick] Add checkpoint printing to db-tool (#12768)

apps/explorer/src/pages/transaction-result/Signatures.tsx
A bug fix to show all user sigs if its not sponsored tx. 
---
=> fix: multisig list view

crates/sui-source-validation-service/config.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/tests/tests.rs
Introduce a `branch` field in `config` when cloning repositories. If we run the server on our code today, it won't verify source successfully (mismatch of `v1.5` framework packages `deepbook` and `sui-framework` due to changes). We'll need this in general for other repositories.
We could also consider supporting commit SHA additionally in future, though that will need a bit of a different translation to `git` commands, so punting for now.
Added test
=> move: source service requires repo branch

.changeset/honest-scissors-clap.md, sdk/typescript/src/types/sui-bcs.ts, sdk/typescript/test/e2e/txn-serializer.test.ts
=> [ts-sdk] Fix deserialization of expiration epoch in transaction builder

crates/sui-framework-tests/src/metered_verifier.rs, crates/sui-move-build/src/lib.rs, crates/sui-protocol-config/src/lib.rs, crates/sui-types/src/move_package.rs, crates/sui/src/client_commands.rs, sui-execution/latest/sui-adapter/src/adapter.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/linkage_view.rs, sui-execution/latest/sui-adapter/src/type_layout_resolver.rs, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/latest/sui-move-natives/src/test_scenario.rs, sui-execution/latest/sui-verifier/src/entry_points_verifier.rs, sui-execution/latest/sui-verifier/src/verifier.rs, sui-execution/src/latest.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/execution.rs
We can't get rid of the alternate implementation of digest calculation
until we drop support for protocol version 16 and below, but this is
one of the steps towards that.
Existing tests
- #12740
- #12741 
- #12742 
- #12774 
- #12776 
- #12784
=> [sui-execution/v1] Hard code pack digest hash modules

apps/wallet/src/ui/app/components/filters-tags/index.tsx, apps/wallet/src/ui/app/pages/home/apps/index.tsx
- https://mysten.atlassian.net/browse/APPS-1374
- Add saved navigation when navigating away from Apps Tab and back
---
=> [wallet]: add saved navigation

crates/sui-indexer/migrations/2022-12-01-034426_objects/up.sql
title
local run and make sure object history will be populated.
TODO:
- will set up testing DB on mainnet & testnet to see the storage consumption
---
=> indexer easy: re-enable object history population

apps/wallet/src/ui/app/components/menu/content/MenuList.tsx, apps/wallet/src/ui/app/components/menu/content/MenuListItem.tsx, apps/wallet/src/ui/app/components/sui-apps/SuiApp.tsx, apps/wallet/src/ui/app/shared/ButtonUI.tsx
- Add explorer button to wallet setting 
- Fix Sui Apps description line height
- Switch the secondary button color to `bg-gray-40 `
=> Add explorer link to Wallet Settings 

apps/explorer/src/components/GasPriceCard/Graph.tsx
* fix rendering the graph when there is only one epoch data available
| -- | -- |
| <img width="476" alt="Screenshot 2023-06-30 at 13 02 50" src="https://github.com/MystenLabs/sui/assets/10210143/67c0ee14-682f-4e54-8f20-cb64d680e738"> | <img width="476" alt="Screenshot 2023-06-30 at 13 03 42" src="https://github.com/MystenLabs/sui/assets/10210143/98e59571-6acd-4b64-8ae6-34b115fb4560"> |
---
=> explorer: fix gas reference price graph

.changeset/quick-rocks-begin.md, sdk/typescript/src/providers/json-rpc-provider.ts, sdk/typescript/test/e2e/read-transactions.test.ts
**Initially described here:** https://mysten-labs.slack.com/archives/C03GYL579PD/p1688117346350449
**What was the issue:** Timeout error is thrown after the timeout period has ended while block has been successfully received.
This PR contains a potential fix for the `waitForTransactionBlock` method.
Additions:
- Introduced a new `blockRetrieved` boolean
- If the block has been retrieved does no longer reject
- Additional condition for loop re-entrance to ensure that the block has not been already retrieved
---
=> [TS SDK] fix for waitForTransactionBlock method

apps/wallet/src/ui/app/pages/home/nft-details/index.tsx
Updates the Marketplace link for items in a Kiosk to link directly to the asset on Hyperspace instead of the landing
---
=> [wallet-ext] - update marketplace link to link directly to asset

Cargo.lock, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-tool/Cargo.toml, crates/sui-tool/src/db_tool/mod.rs, narwhal/storage/src/consensus_store.rs
Two commits related to debugging consensus:
1. Add a command in db_tool to read last consensus index and consensus commit.
2. Fix recovering consensus index on restart.
CI. Ran command on validator.
---
=> Add tool for reading consensus index; fix recover consensus index

sdk/typescript/src/cryptography/keypair.ts, sdk/typescript/src/keypairs/ed25519/keypair.ts, sdk/typescript/src/keypairs/secp256k1/keypair.ts, sdk/typescript/src/keypairs/secp256r1/keypair.ts
This adds new keypair methods.
- All sign methods will be async for the best compatibility with keypair types. This makes it possible to implement things like a Ledger Keypair.
- Add new `signTransactionBlock` and `signMessage` methods to make keypairs more useful on their own, and centralize intent logic alongside signing.
- Move keypair to be an abstract class so that it can include base methods that don't need to be implemented in every keypair.
---
=> [ts-sdk] Add new keypair methods

crates/sui-core/src/consensus_handler.rs
A fork can happen if the failure is ignored and the process should not continue.
n/a
---
=> [ConsensusHandler] panic on deserialization failure

external-crates/move/move-compiler/src/typing/translate.rs, external-crates/move/move-compiler/tests/move_check/typing/unused_functions.move, external-crates/move/move-compiler/tests/move_check/typing/unused_functions.unused.exp
This is a temporary workaround (until we can do this properly on the Sui side) to avoid signaling that a module initializer is unused (and thus implying that it is not called by the runtime).
A test has been added
---
No longer signal that a module initializer function is unused.
=> [move-compiler] A workaround to avoid spurious warning for module initializers

crates/sui-node/src/lib.rs
Now that we are a couple of protocol upgrades ahead of introducing `alternate_server_name`, it's safe to remove it.
CI
---
Do not use alternate server name on Sui Node
=> Do not use alternate server name on Sui Node

external-crates/move/move-compiler/src/typing/translate.rs, external-crates/move/move-compiler/tests/move_check/typing/unused_functions.move, external-crates/move/move-compiler/tests/move_check/typing/unused_functions.unused.exp
This is a temporary workaround (until we can do this properly on the Sui side) to avoid signaling that a module initializer is unused (and thus implying that it is not called by the runtime).
A test has been added
---
No longer signal that a module initializer function is unused.
=> [move-compiler] Cherry-pick #12820

crates/sui-storage/src/lib.rs
This PR adds a library function to recursively hard link a directory. This is going to be useful for scenarios where we want to restore a db from a state snapshot without compromising the consistency of the original db. If the restore fails on hard linked db, node can fall back to state sync based catchup.
Added a unit test
=> Add library function to hard link a dir

crates/sui-core/src/authority_server.rs, crates/sui-e2e-tests/tests/multisig_upgrade_test.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_18.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_18.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_18.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui-types/src/signature.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/multisig_tests.rs, crates/sui-types/src/unit_tests/utils.rs
1.4.0 accepts both legacy and upgraded multisig. 1.3.0 only accepts legacy multisig. this is to make upgraded multisig enabled only for protocol version >= 18 when all validators upgrade. 
---
=> fix: add protocol version for upgraded multisig

crates/sui-rosetta/src/construction.rs
On epoch change, a transaction that will be retried might fail due to having too low reference_gas_price set. This increases the gas_price slightly. Today there is no other consequence, in the future this might mean that the gas payed for the transaction will be slightly higher than lowest possible.
---
=> Increase reference gas price slightly to avoid failure after epoch change

crates/sui-source-validation-service/src/lib.rs
Just a quick fix up to get better errors (avoids hard panic on build errors if we don't find deps).
Manual, does not functionally changing feature behavior.
=> move: remove unwrap in source service

crates/sui-framework/docs/clob_v2.md, crates/sui-framework/packages/deepbook/sources/clob_v2.move, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Add entry function for creating pool with customized taker fee rete and maker rebate rate.
No extra test needed since it is just a simple wrapper function.
Run deepbook unit test.
---
- [✅] protocol change
- [✅] breaking change for validators or node operators (must upgrade binaries)
=> [Deepbook] Support creating customized pool

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_17.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_17.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_17.snap
to match with https://github.com/MystenLabs/sui/pull/12837, execution_version will go out with v18 (in 1.5.0) whereas the multisig feature flag will be released with 1.4.2 in v17. 
---
=> chore: reorder protocol version 17, 18

crates/sui-framework/docs/kiosk.md, crates/sui-framework/packages/sui-framework/sources/kiosk/kiosk.move, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
PurchaseCap functionality is created specifically for extensions and logic which may or may not be considered trading. And emitting an event when "purchasing" with the Cap breaks indexers and makes little sense - ItemListed is not emitted, ItemDelisted as well.
Currently, all extensions rely on custom events for this purpose.
Changes the body of the `kiosk::purchase_with_cap` to NOT emit the ItemPurchased event. Everything else is left intact.
Current tests pass.
- The `kiosk::purchase_with_cap` method for [Sui Kiosk](https://docs.sui.io/build/sui-kiosk) no longer emits the `ItemPurchased` event. This is a network optimization update that should have minimal impact. If the logic of your application does rely on this event, you must change it to leverage custom events instead.
=> [framework] don't emit event on purchase with PurchaseCap

external-crates/move/move-vm/profiler/src/lib.rs
The short function name was being used as the internal frame identifier, however different functions can have the same short name which can cause clobbering.
For example `a::b::add` and `q::w::add` would've both resolved to `add`. This would mess up the statistics.
PR changes frame identifier to use the unique fully qualified name. 
Also cleanup unnecessary drop restructure and constants 
Manual
---
=> [easy] fix name clobbering

crates/sui-types/src/transaction.rs
this change (from #12676) broke compatibility since it was not gated - if the change was necessary we will have to put in a feature flag
=> Revert change to system transaction gas data

crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/unit_tests/narwhal_manager_tests.rs, narwhal/executor/src/subscriber.rs, narwhal/node/src/execution_state.rs, narwhal/types/src/consensus.rs, narwhal/types/src/primary.rs
Currently there is no simple way to check the consistency of ConsensusOutput among validator. The integrity hash is only calculated after some processings in consensus handler. Add a way to calculate ConsensusOutput digest and log it for every consensus commit.
After having more confidence in the value, we can commit to the digest in CheckpointSummary.
CI
---
=> [Narwhal] compute and log ConsensusOutput digest

crates/sui-core/src/checkpoints/mod.rs
because clear() drops and re-creates the table without holding a lock, it can cause crashes if other threads happen to try to write to or read from the table being cleared. I don't think it makes sense to add locking to every DBMap access just to fix this case, so I'm just going to avoid calling clear().
=> Use delete_range instead of clear() to avoid race condition

crates/sui-e2e-tests/tests/framework_upgrades/add_key_ability/Move.toml, crates/sui-e2e-tests/tests/framework_upgrades/add_key_ability/sources/modules.move, crates/sui-e2e-tests/tests/framework_upgrades/add_struct_ability/sources/modules.move, crates/sui-e2e-tests/tests/framework_upgrades/base/sources/modules.move, crates/sui-e2e-tests/tests/framework_upgrades/change_public_function_signature/sources/modules.move, crates/sui-e2e-tests/tests/framework_upgrades/change_struct_ability/sources/modules.move, crates/sui-e2e-tests/tests/framework_upgrades/change_struct_layout/sources/modules.move, crates/sui-e2e-tests/tests/framework_upgrades/change_type_constraint/sources/modules.move, crates/sui-e2e-tests/tests/framework_upgrades/compatible/sources/modules.move, crates/sui-e2e-tests/tests/protocol_version_tests.rs, crates/sui-framework/src/lib.rs
Relax the restriction on adding new abilities to types introduced during system package upgrades -- only the `key` ability remains restricted.
This change is not guarded by a protocol config, because it is in the codepath that decides whether an system package upgrade is compatible in the first place -- i.e. if a quorum of validators do not have this change, the proposal to upgrade to a package where an existing type has additional abilities will not succeed.  This codepath is also not run on fullnodes (who assume that if a system package upgrade proposal was executed successfully, validators confirmed that the upgrade was compatible), so again, there is not a need for a feature gate in the protocol config to coordinate the launch of this change -- it is self-coordinating.
Updated …
=> [protocol-upgrades] Add ability to add abilities

Cargo.lock, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, narwhal/consensus/Cargo.toml, narwhal/consensus/benches/process_certificates.rs, narwhal/consensus/src/bullshark.rs, narwhal/consensus/src/consensus.rs, narwhal/consensus/src/tests/bullshark_tests.rs, narwhal/consensus/src/tests/consensus_tests.rs, narwhal/consensus/src/tests/randomized_tests.rs, narwhal/consensus/src/utils.rs, narwhal/executor/tests/consensus_integration_tests.rs, narwhal/node/src/primary_node.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/proposer.rs, narwhal/primary/src/tests/primary_tests.rs, narwhal/primary/src/tests/proposer_tests.rs, narwhal/primary/tests/integration_tests_proposer_api.rs, narwhal/primary/tests/integration_tests_validator_api.rs, narwhal/types/src/consensus.rs, narwhal/worker/Cargo.toml, narwhal/worker/src/tests/worker_tests.rs
Follow up of https://github.com/MystenLabs/sui/pull/12465
This PR is:
* Introducing a new `protocol_config` feature flag `narwhal_new_leader_election_schedule` , so we keep all the new changes disabled until we decide to enable on a new protocol version
* Introducing the `LeaderSchedule` which from now on will be responsible for crafting the leader schedule and used to perform the leader election. 
* Is updating the leader schedule with the new scores every `K` commit rounds
* Is injecting the `LeaderSchedule` to the primary node so it can be used from the `proposer` module as well since the schedule now can be updated 
Next steps:
Added unit tests
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what …
=> [narwhal] use the LeaderSwapTable in the leader schedule

crates/sui-core/src/authority_server.rs
When transactions are congested on the same shared object, the cheapest transaction types (e.g. incrementing a shared counter) support 50 ~ 100 transaction/sec per-object from testing. We need to reduce the transaction queue length limit to a more reasonable value, to avoid delaying checkpoint building and epoch change too much when an object is congested.
It is still possible to cause congestion on an object with more expensive transactions locking the object for > 0.1s. In future, a limit will be added for the max queueing time, e.g. do not sign new transactions touch a shared object when there is a transaction waiting for the object for >= 2s.
CI
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what …
=> [Congestion] reduce per-object transaction queue length limit from 1000 to 200

crates/sui-core/src/authority/authority_store.rs
We would like to track the application level object set size vs db level object set size (which we already have from rocksdb metrics i.e. objects + indirect objects sst table size).
Adding this as a part of the expensive checks.
Existing tests
=> Track live object set size during expensive checks

apps/explorer/src/ui/Card.tsx
* hide Card overflow to avoid content being visible outside of the rounded corners of the Card
| -- | -- |
| <img width="471" alt="Screenshot 2023-07-06 at 15 34 23" src="https://github.com/MystenLabs/sui/assets/10210143/f8c00187-154c-4ad8-a553-9493b4094617"> | <img width="471" alt="Screenshot 2023-07-06 at 15 34 40" src="https://github.com/MystenLabs/sui/assets/10210143/cf6c6fcf-91a7-4b74-b26e-c13d9532bf3b"> |
| <img width="35" alt="Screenshot 2023-07-06 at 15 39 28" src="https://github.com/MystenLabs/sui/assets/10210143/44f78546-afe9-45d7-a61c-fccacbc23bc5"> | <img width="35" alt="Screenshot 2023-07-06 at 15 39 16" src="https://github.com/MystenLabs/sui/assets/10210143/64473eff-f271-471f-84d4-cdf60c96db5d"> |
👀 👀 
---
If your changes are not user-facing and not a …
=> explorer: fix gas price graph overflowing rounded card

Cargo.lock, crates/sui-transactional-test-runner/Cargo.toml, crates/sui-transactional-test-runner/src/test_adapter.rs
Previously when you specified a specific protocol version in a transactional test this wouldn't change or select the correct framework for that protocol version. This now fetches the correct framework objects based on the protocol version from the framework snapshots.
Make sure existing tests still pass, and that the tests that were failing because of this in the transfer-to-object PR are passing.
=> [transactional-tests] Publish correct framework based on protocol version in the transactional test runner

apps/wallet/src/shared/analytics/ampli/index.ts, apps/wallet/src/ui/app/components/sui-apps/index.tsx, apps/wallet/src/ui/app/hooks/useLedgerNotification.tsx, apps/wallet/src/ui/app/pages/home/apps/index.tsx, apps/wallet/src/ui/app/pages/home/bullshark-quests-notification/index.tsx, apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx, apps/wallet/tests/balanceChanges.spec.ts, apps/wallet/tests/onboarding.spec.ts, apps/wallet/tests/tabs.spec.ts, apps/wallet/tests/utils/auth.ts
some behavior changes
Locally
---
=> [wallet-ext] bullshark modal followups

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/consensus_validator.rs, crates/sui-node/src/lib.rs
On a local cluster this appears to reduce checkpoint_summary_age_ms p50 from ~2000ms to ~600ms
=> Use checkpoint sigs from batches without waiting for a commit

crates/sui-node/src/lib.rs
Reducing the max file size to 256 MB so we can have fast startup time when reading archive. Otherwise sometimes files could get large enough that it takes a while to download them.
=> Reduce archive file size for fast startup

crates/sui-snapshot/src/tests.rs, crates/sui-snapshot/src/writer.rs
Use spawn_blocking for the task which iterates in tight loop over the db (instead of running it in async context). Without this we see the uploader not receive updates on the receiver channel sometimes.
Existing tests
=> Refactor state snapshot writer to use spawn_blocking for file writer task

crates/sui-protocol-config/src/lib.rs
As titled, things got out of sync
This is it
---
=> Fix comment about protocol config versions

sdk/typescript/src/framework/framework.ts, sdk/typescript/src/types/checkpoints.ts, sdk/typescript/src/types/coin.ts
Removing coin_locked_until_epoch field from SDK since we no longer use it. 
---
=> [Ts sdk] Removing coin_locked_until_epoch from SDK since it is no longer in usage

crates/sui-source-validation-service/config.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/tests/tests.rs
Previously the source service config only supports cloning a repository containing packages. This PR creates a variant on the type of source input to also support verifying and service packages directly from a local directory. 
I'm adding this after it got tedious to keep cloning repo paths, and as we move forward to trigger syncing / re-verifying upgraded packages, it's handed to have the source service to additionally accept a local path as well. At this point it's mostly intended for ease of testing and debugging.
There is a small increase in config schema complexity for specifying the kind of source input, and worth the hassle IMO.
Updated unit test to parse variant.
=> move: source service supports standalone directory

crates/sui-core/src/quorum_driver/mod.rs, crates/sui-core/src/transaction_orchestrator.rs, crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs, crates/sui-node/src/lib.rs
Currently `QuorumDriver` has a few queue length limits, but they are not effective at e2e back pressure. A Semaphore is added to rate limit # of inflight transactions in QuorumDriver.
The limit is set to be the same as TASK_QUEUE_LIMIT. This limit is decreased from 10k to 2k. It can be increased after AuthorityAggregator stores less duplicated data. And it can be turned into an environment variable in future.
Move TransactionOrchestrator recovery into an async task, since recovery should not block other parts of the system.
CI. Deployed to a fullnode with large backlog in TransactionOrchestrator and helped it recover.
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release …
=> [QuorumDriver] Limit inflight transactions

crates/sui-move-build/src/lib.rs, crates/sui-move-build/src/linters/mod.rs, crates/sui-move-build/src/linters/self_transfer.rs, crates/sui-move-build/tests/linter/self_transfer.exp, crates/sui-move-build/tests/linter/self_transfer.move, crates/sui-move-build/tests/linter_tests.rs, external-crates/move/move-ir/types/src/location.rs, sui_programmability/examples/basics/sources/lock.move, sui_programmability/examples/basics/sources/object_basics.move, sui_programmability/examples/basics/sources/sandwich.move
This implements a linter warning to be displayed when a function transfers an object to the sender of the transaction instead of returning it from a function. 
It brings linter support based on the Move compiler to the same level as the initial attempt to implement linters based on the Move model (https://github.com/MystenLabs/sui/pull/11212)
A test has been added
---
When building Move code, additional linter warnings related to transferring objects to the transaction sender may appear. The goal of this linter is to encourage developers to return object from …
=> [move-compiler] Added self transfer linter

Cargo.lock, crates/sui-source-validation-service/Cargo.toml, crates/sui-source-validation-service/src/lib.rs
Main motivation for this is to unblock any frontend development against the service and make talking to it convenient, like I did in [a POC](https://github.com/MystenLabs/sui/commit/252c00ccccbf83fdd166c8d704d728f4681456a8). Based on [FE folk's recommendation](https://mysten-labs.slack.com/archives/C032676BWGN/p1688675848596469?thread_ts=1688675490.432769&cid=C032676BWGN) we don't need to restrict CORS for this service (it is unauthed). My own sense is that we can leave it open to start and in prod (without explicitly encouraging third-party use).
Tested in [POC branch](https://github.com/MystenLabs/sui/commit/252c00ccccbf83fdd166c8d704d728f4681456a8) with frontend code. Bit of a hassle to do in a unit test, but maybe possible with some `reqwest` wangling, which I punted on.
=> move: source service defaults to open CORS policy

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/test-cluster/src/lib.rs
The current implementation of `get_object_read` reads the latest version of an object, computes its reference and then make another call to db to read the object by that version. While this is inefficient, it also can result in inconsistent behavior when aggressive pruning is enabled. After reading the latest version of an object, it could've gotten pruned and we will end up returning a user input error (while it is not really a user error). The current PR does a few small things:
1. Rename existing functions which return object reference appropriately (they all are named like `get_object_or_tombstone` while `get_object_ref_or_tombstone` makes more sense)
2. Adds a new function which return latest object i.e. `get_latest_object_or_tombstone`
3. Makes `get_object_read` return the result in …
=> Refactor get_object_read to return object with a single call to store

crates/sui-indexer/migrations/2022-11-18-195259_transactions/up.sql, crates/sui-indexer/src/apis/indexer_api.rs, crates/sui-indexer/src/models/transactions.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-open-rpc/spec/openrpc.json
Per @pchrysochoidis 's feature request, we want to change the tx kind to support a vector of tx kinds, such that on Explorer homepage, we can filter out "system txes"
To be backward compatible, I leave the existing filter and added a new one.
test locally by running
```
cargo run --bin sui-indexer -- --db-url "postgres://vultradmin:AVNS_89ViETEZVMEu8DAs7vB@vultr-prod-b2e14800-a4aa-42f4-a3cb-b383940eb14b-vultr-prod-628e.vultrdb.com:16751/defaultdb" --rpc-client-url http://ewr-mnt-rpc-03.mainnet.sui.io:9000 --rpc-server-worker --rpc-server-url 127.0.0.1 --rpc-server-port 3030 --migrated-methods query_transaction_blocks
```
```
--data-raw '{
"id": 1,
"method": …
```
=> rpc & indexer: add tx query filter for multi tx kinds

crates/sui-indexer/migrations/2023-07-06-182806_checkpoint_metrics/down.sql, crates/sui-indexer/migrations/2023-07-06-182806_checkpoint_metrics/up.sql, crates/sui-indexer/src/models/checkpoint_metrics.rs, crates/sui-indexer/src/models/checkpoints.rs, crates/sui-indexer/src/models/mod.rs, crates/sui-indexer/src/processors/checkpoint_metrics_processor.rs, crates/sui-indexer/src/processors/mod.rs, crates/sui-indexer/src/processors/processor_orchestrator.rs, crates/sui-indexer/src/schema.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-json-rpc/src/api/read.rs, crates/sui-open-rpc/spec/openrpc.json
This PR added a new async processor for checkpoint metrics, it will be useful
- 30D peak TPS will be updated each 100 checkpoints instead of one epoch
- we will have TPS & peak TPS time series data, which can be used for TPS charts
- tx block count -> tx count, which will show higher numbers that are consistent with TPS formula
local run and make sure that the new table can be populated as expected.
cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --rpc-client-url http://ewr-suifn-y71v1.devnet.sui.io:9000 --fullnode-sync-worker --reset-db
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the …
=> indexer: checkpoint metrics processor

apps/wallet/src/ui/app/pages/home/nft-transfer/useTransferKioskItem.ts
- Updates the package ID for OriginByte transfers to an updated version
- Also adds the ID to Growthbook for future updates
---
=> [wallet-ext] - update originbyte package id for transfers

crates/sui-benchmark/src/drivers/bench_driver.rs
Bench driver only terminates when a response comes back (it checks for duration elapsed only in the response handler). However, quorum driver has internal retries with exponential backoff and a response may not even come back or come very late when there are errors. We can fix the above by checking for duration elapsed in request tick handler.
Existing tests
=> Make bench driver terminate on time

doc/src/learn/about-sui.md, doc/src/learn/architecture/consensus.md, doc/src/learn/sui-compared.md, doc/src/learn/sui-glossary.md, narwhal/benchmark/README.md
I noticed that various places in the documentation still link to the archived [MystenLabs/narwhal](https://github.com/MystenLabs/narwhal) repository. Where applicable, I've updated the link to point towards <https://github.com/MystenLabs/sui/tree/main/narwhal> instead.
Only documentation changes, no tests required.
=> docs: update links to archived narwhal repository

scripts/execution_layer.py, sui-execution/cut/src/args.rs, sui-execution/cut/src/plan.rs
Adds two commands to `execution_layer.py` -- `patch` and `rebase`.  The former prints the patch of all changes that were applied to a cut after it was created, and the latte builds rebasing on top of that by saving that patch, re-generating the feature based on `latest` and then applying that patch (merging if necessary).
This change also required an update to the `cut` binary, to allow for the creation of a cut without updating the workspace (the relevant modules would already be part of the workspace expect in the complicated edge case of rebasing over a new execution layer being added to `latest` which should be rare enough to handle manually).
```
sui$ ./scripts/execution_layer.py patch v0
sui$ ./scripts/execution_layer.py patch doesnt_exist
sui$ ./scripts/execution_layer.py cut test …
```
=> [sui-execution/execution_layer] rebase and patch sub-commands

scripts/execution_layer.py, sui-execution/README.md
New sub-command for script to take the changes made to one feature/snapshot since it was cut, and apply them on top of another cut.
Note: This process leaves the cut being merged in-place (doesn't delete it), and is generally less robust than the `rebase` command, because it can't do three-way merging -- it's doing straight patch application.  This is because three-way merging requires being able to identify a common ancestor which may not exist.
```
sui$ ./scripts/execution_layer.py cut test_cut
sui$ git add -A && git commit -m "Test Cut"
sui$ echo "// Making a change" >> sui-execution/test_cut/sui-adapter/src/lib.rs
sui$ git add -A && git commit -m "Making a change"
sui$ ./scripts/execution_layer.py merge latest test_cut
sui$ git diff sui-execution/latest/sui-adapter/src/lib.rs
```
--- …
=> [sui-execution/execution_layer] Merge sub-command

crates/sui-swarm-config/tests/snapshot_tests.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, narwhal/Docker/validators/parameters.json, narwhal/benchmark/README.md, narwhal/benchmark/fabfile.py, narwhal/config/src/lib.rs, narwhal/config/tests/config_tests.rs, narwhal/config/tests/snapshots/config_tests__parameters.snap, narwhal/config/tests/snapshots/config_tests__parameters_import.snap, nre/config/validator.yaml
Remove configs that are no longer used.
CI.
Deployed to private testnet, restarted sui-node (no longer supporting consensus grpc api and block synchronizer settings) with the deleted settings added back.
---
=> [Narwhal] remove config for external consensus

crates/sui-move-build/src/lib.rs, crates/sui-move-build/src/linters/self_transfer.rs, crates/sui-move-build/src/linters/share_owned.rs, external-crates/move/move-compiler/src/cfgir/translate.rs, external-crates/move/move-compiler/src/cfgir/visitor.rs, external-crates/move/move-compiler/src/command_line/compiler.rs, external-crates/move/move-compiler/src/expansion/translate.rs, external-crates/move/move-compiler/src/shared/mod.rs, external-crates/move/move-compiler/src/sui_mode/id_leak.rs, external-crates/move/move-compiler/src/sui_mode/mod.rs, external-crates/move/move-compiler/tests/move_check_testsuite.rs, external-crates/move/move-compiler/tests/sui_mode/id_leak/direct_leak_through_call.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/indirect_leak_through_call.exp, external-crates/move/move-compiler/tests/sui_mode/id_leak/indirect_leak_through_call.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/infinite_loop.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/loop.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_call_with_borrow_field.exp, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_call_with_borrow_field.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_direct_return.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_indirect_return.exp, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_indirect_return.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_pack.exp, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_pack.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_reference.exp, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_reference.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/through_vector.move, external-crates/move/move-compiler/tests/sui_mode/id_leak/transmute.exp, external-crates/move/move-compiler/tests/sui_mode/id_leak/transmute.move, external-crates/move/move-symbol-pool/src/lib.rs
- Integrated existing ID leak verifier to sui mode
- Added sui-mode tests
- Ported MVIR tests
#12868
#12614
---
The Move compiler will now error for improper usage of sui::object::UID when destroying objects. Before this change, the error occurred when checking the bytecode of the module after compilation, so this change is intended to improve the user experience around these errors.
=> [move-compiler] Add ID leak verifier to sui mode

crates/sui-move/src/unit_test.rs, external-crates/move/move-stdlib/tests/move_unit_test.rs, external-crates/move/tools/move-cli/src/base/test.rs
This fixes a problem when the test runner stops running tests in presence of compiler warnings which is quite annoying for the developers.
As an added bonus, with this PR we will no longer print compilation results twice (also annoying).
All existing tests must pass.
---
When running Move unit tests, the presence of warnings no longer prevents tests from running and the compilation results are now printed only once when executing the `sui move test` command.
=> [move-compiler] Keep running tests in presence of compiler warnings

.changeset/lovely-clocks-visit.md, apps/explorer/src/pages/transaction-result/Signatures.tsx, sdk/typescript/src/cryptography/publickey.ts, sdk/typescript/src/keypairs/ed25519/publickey.ts, sdk/typescript/src/keypairs/secp256k1/publickey.ts, sdk/typescript/src/keypairs/secp256r1/publickey.ts, sdk/typescript/test/unit/cryptography/ed25519-publickey.test.ts, sdk/typescript/test/unit/cryptography/secp256k1-publickey.test.ts, sdk/typescript/test/unit/cryptography/secp256r1-publickey.test.ts
Context in https://mysten-labs.slack.com/archives/C032676BWGN/p1689180202585399?thread_ts=1689178418.872779&cid=C032676BWGN
- I confirmed the toSuiPublicKey output matches the output from the Sui Signature Analyzer
- Automated tests
---
=> [explorer][ts-sdk] add new toSuiPublicKey method and show the Sui Public Key in the signatures tab

crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/consensus_validator.rs, crates/sui-core/src/quorum_driver/mod.rs, crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-node/src/lib.rs
This exposed some weird test issues (reconfig tests could end up taking forever due to ever-increasing QD retry delays), hence the test and QD changes.
=> Schedule owned-object transactions for execution from consensus validator to reduce latency

crates/sui-archival/src/lib.rs, crates/sui-archival/src/reader.rs, crates/sui-archival/src/tests.rs, crates/sui-core/src/authority.rs, crates/sui-network/src/state_sync/tests.rs, crates/sui-node/src/lib.rs, crates/sui-tool/src/lib.rs
Add metrics to track transactions and checkpoints being served from archives.
Existing tests
=> Add metrics to track data read from archives

dapps/multisig-toolkit/src/components/connect.tsx, dapps/multisig-toolkit/src/routes/offline-signer.tsx
- Adds a preview effects button to run a `devInspect` for the tx data (helpful to verify there are no errors & check the expected outcome).
- Adds a logout option.
---
=> [Multisig dapp] Adds a preview effects button

Cargo.lock, crates/sui-benchmark/tests/simtest.rs, external-crates/move/Cargo.lock, external-crates/move/tools/move-cli/tests/build_tests/disassemble_module/args.exp, external-crates/move/tools/move-cli/tests/build_tests/disassemble_module/sources/m.move, external-crates/move/tools/move-cli/tests/sandbox_tests/package_basics/args.exp, external-crates/move/tools/move-disassembler/Cargo.toml, external-crates/move/tools/move-disassembler/src/disassembler.rs
Improves the readability of constants in the disassembler.
Tested locally, and updated existing Move CLI tests.
---
Readability of constants in the disassembled output of modules has been improved.
=> [small] Improve readability of constants

external-crates/move/move-compiler/src/command_line/compiler.rs, external-crates/move/move-compiler/src/shared/mod.rs, external-crates/move/move-compiler/src/typing/mod.rs, external-crates/move/move-compiler/src/typing/translate.rs, external-crates/move/move-compiler/src/typing/visitor.rs
- Simple hook for adding visitors on the typed AST
Not yet used
---
=> [move-compiler] Simple typed AST visitor

Cargo.lock, crates/sui-benchmark/tests/simtest.rs, external-crates/move/Cargo.lock, external-crates/move/tools/move-cli/tests/build_tests/disassemble_module/args.exp, external-crates/move/tools/move-cli/tests/build_tests/disassemble_module/sources/m.move, external-crates/move/tools/move-cli/tests/sandbox_tests/package_basics/args.exp, external-crates/move/tools/move-disassembler/Cargo.toml, external-crates/move/tools/move-disassembler/src/disassembler.rs
Cherry-pick of PR #12998
---
Improve readability of constants in the disassembled output of modules.
=> cherry-pick: Improve readability of constants (#12998)

kiosk/sources/extensions/owned_kiosk.move, kiosk/sources/extensions/personal_kiosk.move, kiosk/sources/rules/owned_kiosk_rule.move, kiosk/sources/rules/personal_kiosk_rule.move, kiosk/tests/extensions/personal_kiosk_tests.move
- Adds a "personal_kiosk" extension which locks the Kiosk at the address making the KioskOwnerCap non-transferable.
- Only updates the Mysten Kiosk package, no changes to the Framework required
- This approach gives more certainty for marketplaces when they want to show the seller's address
- Gives a guaranteed way to check the owner through the Kiosk
- Optional requirement by creators, assumed to be added by default together with the lock policy in the strong-enforcement scenario
- features tests for the extension
-
=> [kiosk] Adds a "personal kiosk" extension and a rule

crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/consensus_validator.rs, crates/sui-core/src/quorum_driver/mod.rs, crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-node/src/lib.rs
It seems 57099fc1bc7fcd5c4adacb1eb9e9127d38024c09 unexpectedly broke epoch change, which resulted in `test_upgrade_compatibility` timing out.
CI
`MSIM_TEST_NUM=10 cargo simtest test_upgrade_compatibility`
---
=> Fix and reenable test_upgrade_compatibility

kiosk/sources/rules/floor_price_rule.move, kiosk/tests/rules/floor_price_rule_tests.move
Adds a `floor price` rule for Rules package.
Tests are included in the PR.
---
=> [Kiosk Rules] Adds floor price rule

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/checkpoints/causal_order.rs, crates/sui-core/src/safe_client.rs, crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/mod.rs
In effects V2 we won't have a field called shared_objects anymore, hence we cannot return a list reference.
Unfortunately enum_dispatch doesn't work with trait methods that return trait (impl Iterator) types. Here we must return a vector instead.
This is a non-functional-change.
CI
---
=> [EffectsV2] shared_objects return vec instead of ref

crates/sui-benchmark/src/lib.rs, crates/sui-json-rpc/src/balance_changes.rs, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/mod.rs
In effects v2 we may use index offset to reference gas object, and we also store lamport sequence number separately. 
Hence we won't be able to return a reference to gas object. Return value instead.
This is a non-functional change.
CI
---
=> [EffectsV2] effects gas_object() return value instead of ref

crates/sui-benchmark/src/bin/stress.rs, crates/sui-core/src/test_utils.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/src/unit_tests/gas_tests.rs, crates/sui-core/src/unit_tests/move_package_tests.rs, crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs, crates/sui-e2e-tests/tests/protocol_version_tests.rs, crates/sui-framework-tests/src/metered_verifier.rs, crates/sui-node/src/main.rs, crates/sui-protocol-config/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-snapshot/src/tests.rs, crates/sui-surfer/src/surfer_state.rs, crates/sui-transactional-test-runner/src/test_adapter.rs, crates/sui-types/src/object.rs, crates/sui-types/src/unit_tests/base_types_tests.rs, crates/sui-types/src/unit_tests/messages_tests.rs, crates/sui/src/client_commands.rs, crates/transaction-fuzzer/src/account_universe/transfer_gen.rs, crates/transaction-fuzzer/src/lib.rs, crates/transaction-fuzzer/src/programmable_transaction_gen.rs
See main comment in `crates/sui-protocol-config/src/lib.rs` for reasons. This is currently in use in places that it shouldn't be. Migration will take more work, but for now, this should stop new incorrect usage.
`cargo build`
---
=> [Protocol Config] Mark get_for_max_version as unsafe

Cargo.lock, crates/sui-source-validation-service/Cargo.toml, crates/sui-source-validation-service/config.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs
Adds support for multiple networks (`mainnet`, `testnet`, `devnet`, `localnet`) with a top-level lookup to case out on sources. Some notes:
- RPC clients for networks are constructed during verification, we no longer use `sui-config` or local wallet context (yay!).
- Schema change to `config.toml`: a `network` field is optional and defaults to `mainnet`. If multiple network packages need to be served from a single repository, the config needs a separate entry that fully qualifies the repository, branch, and network. This is for simplicity of spec and implementation--basically, we just duplicate a previous entry for any additional networks and change the `network` field (and/or change corresponding package paths for flexibility if these differ across networks). I anticipate it is going to …
=> move: source service supports multiple networks

crates/sui-config/src/local_ip_utils.rs, narwhal/types/src/consensus.rs
1. Print `ConsensusOutputDigest` properly.
2. Include error when `get_available_port()` panics.
CI
---
=> Two miscellaneous fixes

crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui-tool/src/lib.rs, narwhal/benchmark/README.md, narwhal/config/src/lib.rs, narwhal/config/tests/snapshots/config_tests__parameters.snap, narwhal/config/tests/snapshots/config_tests__parameters_import.snap, narwhal/network/src/p2p.rs, narwhal/network/src/traits.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/tests/certificate_fetcher_tests.rs, narwhal/primary/src/tests/primary_tests.rs, narwhal/test-utils/src/lib.rs, narwhal/types/build.rs, narwhal/types/src/primary.rs, narwhal/worker/src/worker.rs
After removal of external consensus, `GetCertificates` and `GetPayloadAvailability` handlers can be removed now.
CI
---
=> [Narwhal] cleanup more unused handlers

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/typed-store/src/rocks/iter.rs, crates/typed-store/src/rocks/mod.rs, crates/typed-store/src/rocks/tests.rs, crates/typed-store/src/test_db.rs, crates/typed-store/src/traits.rs, narwhal/storage/src/certificate_store.rs, narwhal/storage/src/consensus_store.rs
Add documentation for `clear` method in typed store and a `safe_clear` method. The method `safe_clear` takes a simple approach to prevent race from happening by letting the user pass in the lock to guard the critical section
Existing tests
=> Add documentation for clear method and a safe clear method

crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/tests/tests.rs
Various cleanups to source service bundled together, see inline comments.
Semantics-preserving / tests pass.
---
=> source service (easy): clean up pass

crates/sui-json-rpc/src/governance_api.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-json-rpc/src/logger.rs, crates/sui-json-rpc/src/move_utils.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-json-rpc/src/transaction_execution_api.rs
Currently, when we hit the `with_tracing!` macro, the error is already an `RpcError`. Down the line, if/ when we want to replace internal errors with a generic error string, we'll lose the debug information in our error logs. This PR modifies the macro to log and map the original error instead.
---
=> [rpc] logging macro logs original error instead of RpcError

.changeset/short-pugs-obey.md, dapps/kiosk-cli/README.md, pnpm-workspace.yaml, sdk/typescript/package.json, sdk/typescript/src/cryptography/intent.ts, sdk/typescript/src/cryptography/keypair.ts, sdk/typescript/src/cryptography/publickey.ts, sdk/typescript/src/cryptography/signature.ts, sdk/typescript/src/keypairs/ed25519/publickey.ts, sdk/typescript/src/keypairs/secp256k1/publickey.ts, sdk/typescript/src/keypairs/secp256r1/publickey.ts, sdk/typescript/src/signers/signer-with-provider.ts, sdk/typescript/src/utils/verify.ts, sdk/typescript/src/verify/index.ts, sdk/typescript/test/e2e/keypairs.test.ts, sdk/typescript/test/unit/cryptography/ed25519-keypair.test.ts, sdk/typescript/test/unit/cryptography/secp256k1-keypair.test.ts, sdk/typescript/test/unit/cryptography/secp256r1-keypair.test.ts, sdk/typescript/verify/package.json
fix a bug that the signMessage in rust vs typescript has a discrepancy. this is make typescript use bcs serialization for a vector instead of just a plain vector. 
```
PersonalMessage {
message: Vec<u8>
}
```
existing tests in ts still passes (bc verify and sign are both changed to the new format). 
tested against rust that a ts produced sig now verifies in rust. 
---
=> sdk: fix personal message to use bcs

.github/workflows/ci-docs.yml
There seems to be a build issue with a dependency not supporting Rust 1.72 or nightly.
According to https://substrate.stackexchange.com/a/9069, we can pin the nightly toolchain version for now until the main repo has upgraded.
https://github.com/MystenLabs/sui/actions/runs/5602870164
---
=> [CI] fix doc build

.changeset/lovely-plums-live.md, .changeset/short-pugs-obey.md, pnpm-workspace.yaml, sdk/typescript/multisig/package.json, sdk/typescript/package.json, sdk/typescript/src/cryptography/multisig.ts, sdk/typescript/src/cryptography/publickey.ts, sdk/typescript/src/cryptography/signature.ts, sdk/typescript/src/cryptography/utils.ts, sdk/typescript/src/keypairs/ed25519/publickey.ts, sdk/typescript/src/keypairs/secp256k1/publickey.ts, sdk/typescript/src/keypairs/secp256r1/publickey.ts, sdk/typescript/src/multisig/index.ts, sdk/typescript/src/multisig/publickey.ts, sdk/typescript/src/verify/index.ts, sdk/typescript/test/unit/cryptography/ed25519-keypair.test.ts, sdk/typescript/test/unit/cryptography/ed25519-publickey.test.ts, sdk/typescript/test/unit/cryptography/multisig.test.ts, sdk/typescript/test/unit/cryptography/secp256k1-keypair.test.ts, sdk/typescript/test/unit/cryptography/secp256k1-publickey.test.ts, sdk/typescript/test/unit/cryptography/secp256r1-keypair.test.ts, sdk/typescript/test/unit/cryptography/secp256r1-publickey.test.ts
Closes https://github.com/MystenLabs/sui/issues/12931. Add feature to verify a multisig in typescript. depends on https://github.com/MystenLabs/sui/pull/12997
unit tests. 
---
=> multisig: Add multisig verify support in typescript

crates/sui-benchmark/src/lib.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/state_accumulator.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/src/unit_tests/gas_tests.rs, crates/sui-core/src/unit_tests/move_integration_tests.rs, crates/sui-indexer/src/utils.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-json-rpc/src/balance_changes.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/object_changes.rs, crates/sui-tool/src/db_tool/mod.rs, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/mod.rs, crates/transaction-fuzzer/tests/pt_fuzz.rs, crates/transaction-fuzzer/tests/type_arg_fuzzer.rs
Make all of created, mutated, unwrapped, wrapped, deleted, unwrapped_and_deleted return Vec instead of list ref, since effects V2 won't be able to return list ref.
This is a non-functional change.
CI
---
=> [EffectsV2] created, mutated and etc all return Vec

kiosk/sources/extensions/personal_kiosk.move, kiosk/tests/extensions/personal_kiosk_tests.move
Adds a better error on not-owned Kiosk, not a serious issue.
Features the test for the new abort a code.
- personal_kiosk now emits a nicer local abort code
=> [kiosk] Post-audit patches

apps/explorer/src/components/GasBreakdown/index.tsx, apps/explorer/src/pages/transaction-result/transaction-summary/BalanceChanges.tsx, apps/explorer/src/pages/transaction-result/transaction-summary/ObjectChanges.tsx
- https://mysten.atlassian.net/browse/APPS-1372
- https://explorer-git-apps-1372-mysten-labs.vercel.app/txblock/BuwodPXcBAR2kNRdxovM5S4S3praGppChuFCdbt44ZMo
---
=> [explorer]: add suins domain name to txn page

crates/sui-move-build/src/lib.rs, crates/sui-move-build/src/linters/mod.rs, crates/sui-move-build/src/linters/self_transfer.rs, crates/sui-move-build/src/linters/share_owned.rs, crates/sui-move-build/tests/linter/self_transfer.exp, crates/sui-move-build/tests/linter/self_transfer.move, crates/sui-move-build/tests/linter/share_owned.exp, crates/sui-move-build/tests/linter/share_owned.move, crates/sui-move-build/tests/linter_tests.rs, external-crates/move/move-compiler/src/cfgir/translate.rs, external-crates/move/move-compiler/src/command_line/compiler.rs, external-crates/move/move-compiler/src/diagnostics/codes.rs, external-crates/move/move-compiler/src/diagnostics/mod.rs, external-crates/move/move-compiler/src/expansion/ast.rs, external-crates/move/move-compiler/src/expansion/translate.rs, external-crates/move/move-compiler/src/shared/mod.rs
This implements the ability to add suppression of external warnings, particularly warnings coming from Sui linters.
Must pass all existing tests plus updated linter tests.
---
Developers can now selectively suppress linter warnings. Linter warnings now also feature an additional message describing how they can be suppressed.
=> [move-compiler] Added support for linter warning suppression

crates/sui-framework/docs/staking_pool.md, crates/sui-framework/docs/sui_system.md, crates/sui-framework/docs/sui_system_state_inner.md, crates/sui-framework/docs/validator.md, crates/sui-framework/docs/validator_set.md, crates/sui-framework/packages/sui-system/sources/staking_pool.move, crates/sui-framework/packages/sui-system/sources/sui_system.move, crates/sui-framework/packages/sui-system/sources/sui_system_state_inner.move, crates/sui-framework/packages/sui-system/sources/validator.move, crates/sui-framework/packages/sui-system/sources/validator_set.move, crates/sui-framework/packages/sui-system/tests/delegation_tests.move, crates/sui-framework/packages/sui-system/tests/validator_set_tests.move, crates/sui-framework/packages/sui-system/tests/validator_tests.move, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_19.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_19.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_19.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Implemented [SIP-6](https://github.com/AftermathFinance/sips/blob/main/sips/sip-6.md):
- Added `store` ability to `StakedSui` object
- Added a PTB-friendly version of `request_add_stake`
- Added getters for pool token exchange rates and active validator addresses
existing tests
---
This release adds the `store` ability to the `StakedSui` object. With `store` ability, stake objects can be transferred freely and wrapped in other objects, making it possible to implement liquid staking derivatives. To make staking more atomically composable with other on-chain actions, …
=> [sui-system] add store to StakedSui and PTB friendly staking fun

crates/sui-core/src/consensus_validator.rs, narwhal/executor/src/subscriber.rs, narwhal/network/src/client.rs, narwhal/network/src/traits.rs, narwhal/node/src/generate_format.rs, narwhal/node/tests/staged/narwhal.yaml, narwhal/primary/src/primary.rs, narwhal/types/build.rs, narwhal/types/src/primary.rs, narwhal/types/src/tests/batch_serde.rs, narwhal/worker/src/batch_fetcher.rs, narwhal/worker/src/batch_maker.rs, narwhal/worker/src/handlers.rs, narwhal/worker/src/tests/handlers_tests.rs, narwhal/worker/src/tests/worker_tests.rs, narwhal/worker/src/tx_validator.rs
We have moved past protocol version 12 so we can remove this old code.
Unit Tests + Deploy to private-testnet
=> Remove BatchV1 and related code gating BatchV2

crates/sui-archival/src/lib.rs, crates/sui-archival/src/reader.rs, crates/sui-storage/src/lib.rs, crates/sui-tool/src/commands.rs, crates/sui-tool/src/lib.rs
The current archive consistency check downloads and iterates over every single checkpoint and transaction from genesis. This is really slow for daily runs and over time this will get even worse. Adding an inexpensive consistency check mode where we verify consistency using stored sha3 checksums in manifest for every file.
Existing tests and running in testnet
=> Add an inexpensive archive consistency check mode

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-types/src/temporary_store.rs
Renames variable `runtime_read_objects` to `runtime_packages_loaded_from_db` which better describes the variable functionality.
Also improves comments.
N/A
---
=> [chore/nit] improve command and var name

crates/sui-core/src/consensus_validator.rs, narwhal/executor/src/subscriber.rs, narwhal/network/src/client.rs, narwhal/network/src/traits.rs, narwhal/node/src/generate_format.rs, narwhal/node/tests/staged/narwhal.yaml, narwhal/primary/src/primary.rs, narwhal/types/build.rs, narwhal/types/src/primary.rs, narwhal/types/src/tests/batch_serde.rs, narwhal/worker/src/batch_fetcher.rs, narwhal/worker/src/batch_maker.rs, narwhal/worker/src/handlers.rs, narwhal/worker/src/tests/handlers_tests.rs, narwhal/worker/src/tests/worker_tests.rs, narwhal/worker/src/tx_validator.rs
Causes panics when upgrading validators because RocksDB schema will not be updated until epoch change
=> Revert "Remove BatchV1 and related code gating BatchV2"

sdk/typescript/src/builder/TransactionBlock.ts
Just noticed these statics were floating here and not really needed. I originally added these to avoid needing more imports but:
1. That's dumb.
2. We added aliases on the transaction block builder itself so it's not really useful to have the alias.
3. Just import it.
---
=> Deprecate un-needed statics

crates/sui-core/src/transaction_input_checker.rs, crates/sui-macros/src/lib.rs, crates/sui-proc-macros/src/lib.rs, crates/sui-types/src/gas.rs, crates/sui-types/src/gas_coin.rs, crates/sui-types/src/gas_model/gas_v2.rs, sui-execution/latest/sui-adapter/src/adapter.rs, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/v0/sui-adapter/src/adapter.rs, sui-execution/v0/sui-adapter/src/execution_engine.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/execution.rs
Usage of the `checked_arithmetic` macro was causing a number of quality-of-life issues for development around formatting and LSP support. However, converting to an attribute-based procedural macro for adding checked arithmetic operations solves all of these issues (LSPs and autoformatters should now work with it).
Note that this only works on explicitly declared modules due to (current) Rust restrictions, and you cannot annotate a file-based module with this attribute macro.
This also required expanding the applicability of the `with_checked_arithmetic` macro to work over more forms than it previously handled, however the change is pretty straightforward.
The one downside to it is that this introduces some slight boilerplate of
```rust
pub use checked::*;
mod checked {
// what was …
```
=> [macros] Update `with_checked_arithmetic` macro, and convert usage of `checked_arithmetic` macro to attribute macro

crates/sui-indexer/src/apis/extended_api.rs, crates/sui-indexer/src/apis/read_api.rs, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/processors/address_processor.rs, crates/sui-indexer/src/processors/checkpoint_metrics_processor.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/tests/integration_tests.rs
- Split object ingestion and tx ingestion b/c object ingestion is getting much slower with grown TPS.
- also added counters for DB commits of tx and objects tables.
local run and test writer on indexer branch
---
=> indexer: split obj and tx ingestion

narwhal/primary/src/certifier.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/synchronizer.rs, narwhal/primary/src/tests/synchronizer_tests.rs, narwhal/storage/src/certificate_store.rs
Cancel header proposal less eagerly, by waiting until a higher round certificate has been created locally, instead of immediately observing a higher round certificate. Orphaned certificates can still be useful as votes on previous leaders. Transactions in the orphaned certificates will be retried, same as those in cancelled headers.
The main goal is to make the system behavior more intuitive. Also this change may help keeping latency consistent when headers are proposed more frequently for any reason.
CI
Deployed to private test and observed no change in p50 latency, p95 jitter and validator scores.
--- …
=> [Narwhal] wait to cancel header proposal after higher round certificates have been created

crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/error.rs, crates/sui-json-rpc/src/governance_api.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-json-rpc/src/move_utils.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-json-rpc/src/transaction_execution_api.rs
Transparently group RPC-level client errors together without modifying existing error response text. This will help us later w/ standardizing error strings as we now have an overview of possible errors, and can quickly jump to locations with `SuiRpcInputError`.
1. Gather client-fault errors under `SuiRpcInputError`
2. In `transaction_execution_api`, split out client input validation logic/ preparation into its own function to capture various client errors under one method.
3. Implement `From<SuiRpcInputError> to RpcError` so we can reduce scenarios where we need to convert into `Error` then into `RpcError`. This makes it clearer when a client error occurs on the rpc
4. Add some more `coin_api` tests to make sure we hit all `SuiRpcInputError` scenarios
How did you test the new or updated …
=> [rpc][structured-error-handling][1/n] Group rpc-level client errors

apps/core/src/hooks/useOnScreen.ts, apps/wallet/src/ui/app/components/nft-display/Kiosk.tsx, apps/wallet/src/ui/app/pages/home/kiosk-details/index.tsx, apps/wallet/src/ui/app/pages/home/nfts/index.tsx
Fixes a few issues that I noticed with the assets page / kiosks that didn't present themselves in local development for some reason (maybe due to minifying / webpack config 🤨)
- While debugging, I noticed that `useOnScreen` was triggering a large amount of re-renders, so I cleaned it up a bit and it seems to be happy now :) 
- Removed sorting by `display` as this was causing inconsistencies in rendering between the Asset page and Kiosk detail page. This wasn't really needed in the first place
- Added a loading spinner to the Kiosk detail page
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted …
=> [wallet-ext] - assets page fixes

crates/sui-framework/packages/sui-framework/sources/display.move, crates/sui-framework/packages/sui-framework/sources/kiosk/kiosk.move, crates/sui-framework/packages/sui-framework/sources/kiosk/transfer_policy.move, crates/sui-framework/packages/sui-framework/sources/package.move, crates/sui-framework/packages/sui-framework/sources/pay.move
Recently added support for suppressing linter warnings (https://github.com/MystenLabs/sui/pull/13012) allows us to suppress linter warning in Sui stdlib so that developers building Move sources only see warnings pertaining to their own code.
Perhaps some of these suppressions should actually result in the rewrite of the library but this is beyond the scope of this PR.
N/A
---
Developers trying recently introduced linters might have seen linter warnings coming from Sui standard library which are from now on going to be suppressed
=> [move-compiler] Suppressed linter warnings in Sui stdlib

apps/wallet/src/ui/app/pages/approval-request/transaction-request/index.tsx
Ethos 8192 requires a lot of transactions to play, and it's starting to eat into our Amplitude event quota (5 mil events a day at this rate). Since we don't have the governance add-on, we can just manually exclude these transactions with a simple blocklist for the time being. 
- CI
---
=> [wallet-ext] exclude transactions from Ethos 8192 from analytics tracking 

crates/sui-indexer/src/apis/write_api.rs, crates/sui-indexer/src/models/objects.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/tests/integration_tests.rs
1. remove fast path commit method. We came to the consensus that indexer will not rely on fast path.
2. for object changes, instead of grouping and returning a nested vector, using a HashMap and return the latest objects.
3. for mutated objects, apply chunks.
4. clean up experimental code
---
1. remove fast path commit method. We came to the consensus that indexer will not rely on fast path. 2. for object changes, instead of grouping and returning a nested vector, using a HashMap and return the latest objects. 3. clean up …
=> sort objects with HashMap

crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/error.rs, crates/sui-json-rpc/src/metrics.rs
`QuorumDriverError::NonRecoverableTransactionError` indicates an error in the user transaction, so should be a client error.
CI
---
Change `QuorumDriverError::NonRecoverableTransactionError`'s error code from -32000 to -32602
=> make non recoverable error client error

dapps/multisig-toolkit/src/components/connect.tsx, dapps/multisig-toolkit/src/routes/offline-signer.tsx
- Uses `dryRun` instead of `devInspect` to properly preview effects.
- Nit: `Logout` becomes `disconnect`
---
=> [multisig dapp] Switch to dryRun from devInspect

.changeset/kind-insects-shake.md, apps/wallet/src/dapp-interface/WalletStandardInterface.ts, sdk/typescript/src/builder/TransactionBlock.ts, sdk/typescript/src/builder/export.ts, sdk/typescript/src/client/client.ts, sdk/typescript/src/providers/json-rpc-provider.ts, sdk/typescript/src/signers/signer-with-provider.ts
Change `TransactionBlock.is()` to be `isTransactionBlock`. When we have module-level tree shaking, this will let the entire builder get treeshaked (shooked? treeshaken?) out of the bundle leaving just a small utility method.
---
=> Rework the transaction block is method

doc/src/build/fullnode.md
When setting up your own archival fallback, to prevent local transaction pruning from going over latest archived checkpoint - one needs to add the right `archive-read-config`
=> Fix setting up own archival fallback documentation

crates/sui-protocol-config/src/lib.rs
As in title. Before this change, we were committing on all chains but mainnet.
Existing tests
---
=> [StateAccumulator] Commit root state hash on all chains

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-json-rpc-tests/tests/transaction_tests.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-node/src/lib.rs, crates/sui-storage/src/key_value_store.rs
This still fetches the data from the AuthorityStore, we just do it through the trait now so that we can swap out the impl later.
=> ReadApi now uses the KV store trait for loading transactions, effects, and events

sdk/docs/pages/typescript-sdk/_meta.json, sdk/docs/pages/typescript-sdk/connect.mdx, sdk/docs/pages/typescript-sdk/hello-sui.mdx, sdk/docs/pages/typescript-sdk/index.mdx, sdk/docs/pages/typescript-sdk/install.mdx
Prelim doc content for Hayes.
NA
---
=> WIP content

dapps/multisig-toolkit/src/components/header.tsx, dapps/multisig-toolkit/src/routes/index.tsx, dapps/multisig-toolkit/src/routes/multisig-address.tsx
Add a tab to the multisig-toolkit for creating Sui MultiSig Addresses 'on-the-fly' ✈️  
Ref #12932
* Get PubKeys!
```
AB3VXSdvFq6ym0ulqnVNuEI9xxI5b8RY21azMU6ybWp1
ADue3nTTYz9pE75pMKEnnLIrcTSS/c0uwr6WEU5nz4RM
AIPVXOb2rbm8dX0LBL4PEgN4HPQDpwUIHpIy2THr/it1
```
* run locally `pnpm run dev`
* goto [localhost:5173/multisig-address](http://localhost:5173/multisig-address)
* add pubkeys and weights
* create!
---
=> Create View for creating musig addresses in multisig-toolkit

dapps/multisig-toolkit/src/routes/signature-analyzer.tsx, sdk/typescript/src/index.ts, sdk/typescript/src/multisig/index.ts, sdk/typescript/src/multisig/publickey.ts, sdk/typescript/src/verify/index.ts
publicKeyFromBytes hasn't been released, I wanted to rename it to publicKeyFromRawBytes to keep things more clear, and add a `publicKeyFromSuiBytes` to the multisig package, since it will be fairly useful there.  
---
=> [ts-sdk] add publicKeyFromSuiBytes to multisig package

crates/sui-indexer/src/apis/indexer_api.rs
indexer ws does not work after splitting of readers and writers, but on testnet, some unknown subscribers are constantly hitting the endpoint and slow down Explorer.
Steps forward:
- disable ws on indexer as it does not work and to avoid unknown clients slowing down explorer;
- we might want to split the RPC reader and WS reader in the long run, and open to discuss that.
local run
---
=> indexer: temp disable ws due to split of reader & writer

crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql
Found this while testing mainnet Explorer based on Auora, which was behind on data.
---
=> indexer: minor fix for popular package query

crates/sui-core/src/consensus_validator.rs, narwhal/executor/src/subscriber.rs, narwhal/network/src/client.rs, narwhal/network/src/traits.rs, narwhal/node/src/generate_format.rs, narwhal/node/tests/staged/narwhal.yaml, narwhal/primary/src/primary.rs, narwhal/test-utils/src/lib.rs, narwhal/types/build.rs, narwhal/types/src/primary.rs, narwhal/worker/src/batch_fetcher.rs, narwhal/worker/src/batch_maker.rs, narwhal/worker/src/handlers.rs, narwhal/worker/src/tests/handlers_tests.rs
We have moved past protocol version 11 so we can remove some of the unused code. However because Batch store expects the original Batch enum format we cannot remove BatchV1 completely without causing issues to the schema. To fully remove BatchV1 we will have to create a new Batch store that only uses BatchV2 instead of the Batch versioned enum.
[Tested version upgrade in labnet](https://metrics.sui.io/d/HH91BjB4z/throughput?orgId=1&from=1690435970447&to=1690437139251&var-Environment=mysten-metrics-internal&var-network=labnet&var-validator=All)
=> Remove unused NW code now that we moved past V11

crates/sui-protocol-config-macros/src/lib.rs, crates/sui-protocol-config/src/lib.rs
Reverts MystenLabs/sui#13178 to unbreak `CI`
=> Revert "Set prot cfg fields in test"

crates/sui/tests/cli_tests.rs
When this test was added it needed to be ignored because package upgrades were not allowed at the current protocol version. However they are now supported so this test should be run.
CI
---
=> [simple] Unignore package upgrade test in CLI tests

crates/sui-types/src/execution.rs, crates/sui-types/src/storage.rs, crates/sui-types/src/temporary_store.rs, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs, sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs, sui-execution/v0/sui-move-natives/src/object_runtime/object_store.rs
When collecting storage rebate from mutated objects, for child object we read from the DB. This is a waste because we already loaded all of them in memory at runtime. This PR populates that information back to the temporary store.
CI
---
=> Do not read from DB to collect storage rebate

sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs, sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
1. In the circular ownership check, input objects cannot have object owner, so they don't need to be involved at all. Remove them. @tnowacki please double check if this is correct.
2. Rename ObjectStore to ChildObjectStore to improve accuracy
3. Fix a few indentations
CI
---
=> A few simplifications in the sui-executor

Cargo.lock, Cargo.toml, crates/sui/Cargo.toml, crates/sui/src/keytool.rs, crates/sui/src/sui_commands.rs, crates/workspace-hack/Cargo.toml
Revamp the keytool CLI command to pretty print output as formatted tables and add support for json output. This is the first experimental step to gain feedback before moving to other CLI commands.
The PR also removes seven commands that should not be part of the CLI and were OK'ed by @siomari and @ammn to be removed:
* Base64PubKeyToAddress
* BytesToBase64
* Base64ToBytes
* Base64ToHex
* BytesToHex
* HexToBase64
* HexToBytes
Executed the existing tests. 
---
This PR modifies the `CLI keytool` as follows:
* Adds support for `json` output. Use the `--json` flag when …
=> [keytool] use a table format output and add json output support

apps/core/src/hooks/useGetKioskContents.ts, apps/core/src/hooks/useMultiGetObjects.ts, apps/wallet/src/ui/app/components/navigation/index.tsx, apps/wallet/src/ui/app/components/nft-display/Kiosk.tsx, apps/wallet/src/ui/app/components/nft-display/index.tsx, apps/wallet/src/ui/app/hooks/useGetNFTs.ts, apps/wallet/src/ui/app/pages/enoki-onboarding/ForgotPassword.tsx, apps/wallet/src/ui/app/pages/home/assets/index.tsx, apps/wallet/src/ui/app/pages/home/hidden-assets/HiddenAssetsProvider.tsx, apps/wallet/src/ui/app/pages/home/hidden-assets/index.tsx, apps/wallet/src/ui/app/pages/home/nft-details/index.tsx, apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx, apps/wallet/src/ui/app/pages/home/nfts/AssetsOptionsMenu.tsx, apps/wallet/src/ui/app/pages/home/nfts/NonVisualAssets.tsx, apps/wallet/src/ui/app/pages/home/nfts/VisualAssets.tsx, apps/wallet/src/ui/app/pages/home/nfts/index.tsx, apps/wallet/src/ui/app/shared/toaster/index.tsx
Includes various changes to the Assets / NFTs page, mainly: 
- Adds ability to filter by Visual / Non-Visual assets. (note: I split this out into two pages for now but could probably be rolled back into one since it's really just a grid / list view) 
- Moved the show / hide asset logic into a provider which cleans things up a bit. We could also potentially expand this in the future if we add more types of filtering / functionality
- Addressed some remaining feedback / UI polish for kiosks
https://github.com/MystenLabs/sui/assets/122397493/caebcb96-27d2-4a96-a280-98838ae878fc
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release …
=> [wallet-ext] - asset filtering / more kiosk polish

crates/sui-indexer/benches/indexer_benchmark.rs, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/lib.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/store/indexer_store.rs
This PR improves indexer ingestion latency, including the following notable changes:
1. avoid downloading object data for txes/checkpoints indexing. To keep epoch indexing working, we will special handle system state objects when the checkpoint is either Genesis or ChangeEpoch. Also move package indexing to object indexing pipeline.
2. use `metered_channels` so we can easily identify the bottlenecks.
3. make some of queue sizes configuration. As in experiments, they turned out to be too small.
4. get rid of unnecessary `Arc<Mutex>>` around sender/receivers.
5. use a dedicated tokio task to poll fullnode checkpoint number, to avoid adding this latency in every download attempt.
Note: I also tried to use `lru` (crate) to cache the preliminary transaction data for object indexing, so they …
=> do not download objects data for tx data, and others

crates/sui-core/src/authority/authority_store.rs, crates/sui-indexer/src/utils.rs, crates/sui-json-rpc/src/object_changes.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/mod.rs
There are a few API functions in TransactionEffects that can be derived from other functions. They don't need to be defined per-effect type, but can be defined at top level. This will reduce code duplication when we introduce new effects variants.
Also change the semantics of all_deleted to exclude unwrapped_then_deleted objects and rename it, because unwrapped_then_deleted are never needed with this API call.
CI
---
=> [EffectsV2] Lift up a few effects APIs

crates/sui-indexer/src/lib.rs, crates/sui-indexer/src/main.rs, crates/sui-indexer/src/metrics.rs
- add configurable DB pool size
- monitor DB pool, the total size and idle conn
local run and saw metrics on localhost
```
indexer_idle_db_conn{indexer_fullnode="ord-mnt-rpcbig-06.mainnet.sui"} 100
indexer_db_conn_pool_size{indexer_fullnode="ord-mnt-rpcbig-06.mainnet.sui"} 100
```
and logs
```
2023-07-29T20:50:37.370315Z  INFO sui_indexer: DB connection pool size: 100, with idle conn: 100.
```
---
=> indexer: DB pool config & metrics

apps/explorer/src/ui/PageHeader.tsx
- Move Copy icon inlined with large address name
Current
---
=> [Explorer]: move copy icon inline with address name

crates/sui-core/src/authority/authority_store.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-node/src/lib.rs, crates/sui-storage/src/http_key_value_store.rs, crates/sui-storage/src/key_value_store.rs, crates/sui-storage/src/key_value_store_metrics.rs, crates/sui-storage/src/lib.rs, crates/sui-storage/tests/key_value_tests.rs
This required a pretty extensive refactoring to avoid adding duplicated metrics code to different impls, but the end result is much nicer anyway.
=> Add metrics to key value store, refactor

crates/sui-indexer/src/store/pg_indexer_store.rs
Turn off cache sync write of TPS metric
Tested and deployed to testnet.
---
=> indexer: turn off sync write on cache

crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
this is a bug but did not manifest when we committed each checkpoint one by one.
after recent change of writing multiple checkpoints together, an error of ON CONFLICT DO UPDATE would happen.
specifically, if in an object commit batch, an object is mutated first and then deleted later, this error will show up.
thanks to @bschwab for detecting and reporting this.
test locally and with bryan on the snowflake pipeline.
---
=> indexer fix: split commits of obj mutation and deletion

.github/workflows/rust.yml
Add `test-extra-notrust` step - necessary so that PRs that do not run the test-extra step (i.e. non-rust PRs) can still pass all required checks.
=> Fix required text-extra step

.changeset/tender-cows-flash.md, sdk/kiosk/README.md, sdk/kiosk/src/index.ts, sdk/kiosk/src/tx/rules.ts, sdk/kiosk/src/utils.ts
This PR adds support to attaching rules (royalty + kiosk lock) on a Transfer Policy. 
It also extends the README to add some more examples on how to use these.
---
=> [Kiosk SDK] Adds support for attaching rules to Transfer Policy

crates/sui-types/src/error.rs, crates/sui/src/client_commands.rs
...when publishing or upgrading packages via the CLI.  Improvements are as follows:
- Preserve formatting in the error (newlines, etc) by removing debug formatting.
- Add context explaining what the warning means, and that it can be ignored using a command-line flag.
- Create two packages: `test` depending on `dep`.
- Publish `dep`, and update its manifest with its published location.
- Modify `dep`'s source to be different from the version that was published.
- Try to publish `test`, expect a source verification error, which now looks like this:
```
Failed to publish the Move module(s), reason: [warning] Local dependency did not match its on-chain 
version at b33d80d795a038ce44d1f67b84047493f8775ab29d7f856271f705c6e1fd329f::Dep::dep
This may indicate that the on-chain version(s) of your …
```
=> [CLI] Improve warning message for source verification failure

apps/explorer/src/components/Object/ObjectFieldsCard.tsx
- Currently the `ObjectFieldsCard` always renders invalid values for `package` due to `enabled` being false and the spinner runs endlessly (Slack ref https://mysten-labs.slack.com/archives/C032676BWGN/p1690883106846709)
Parsing by data.type will give correct value for `sui_getNormalizedMoveStruct` query
---
=> [Explorer]: fix object view page

external-crates/move/move-compiler/src/diagnostics/codes.rs, external-crates/move/move-compiler/src/diagnostics/mod.rs, external-crates/move/move-compiler/src/expansion/translate.rs, external-crates/move/move-compiler/src/naming/translate.rs, external-crates/move/move-compiler/src/shared/mod.rs, external-crates/move/move-compiler/tests/move_check/naming/unused_fun_tparam.move, external-crates/move/move-compiler/tests/move_check/naming/unused_fun_tparam.unused.exp, external-crates/move/move-compiler/tests/move_check/naming/used_fun_tparam.move, external-crates/move/move-prover/move-abigen/tests/sources/some_script.move, external-crates/move/move-prover/move-docgen/tests/sources/root_template_script1.notest_move, external-crates/move/move-prover/move-docgen/tests/sources/root_template_script2.notest_move, external-crates/move/move-prover/move-docgen/tests/sources/root_template_script3.notest_move, external-crates/move/move-prover/move-docgen/tests/sources/some_script.move, external-crates/move/tools/move-cli/tests/sandbox_tests/print_stack_trace/sources/N.move
Added a warning for unused function type params. Kept the same suppression annotation as for struct type params which required a small change to how known warning filters are stored.
Added new tests
---
When building Move code new compiler warnings may appear pointing towards unused function type parameters
=> [move-compiler] Added a warning for unused function type params

Cargo.lock, Cargo.toml, crates/sui-indexer/src/schema.rs, crates/workspace-hack/Cargo.toml
diesel added support for column max sizes in 2.1.0
example is as follows:
```
active_addresses (account_address) {
#[max_length = 66]
account_address -> Varchar,
```
Need to update cargo to pull in this newer version
Tested on my pipeline dev server
---
=> Updating diesel to support max_length

crates/sui-indexer/src/apis/write_api.rs, crates/sui-indexer/src/types.rs
There will be no fast path in indexer.
The code is not in used anyway.
---
remove fast path from indexer
=> [cleanup] remove fast path from indexer

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/checkpoints/mod.rs
Using `multi_gets` / `multi_contains`  to reduce the time spent completing & creating checkpoints. Also removed the accumulation of checkpoints step in non end-of-epoch scenarios and leave that for the checkpoint executor. 
Tested in private-testnet
before 
after
=> Reduce time spent completing & creating checkpoints

Cargo.lock, crates/sui-core/src/authority.rs, crates/sui-e2e-tests/Cargo.toml, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-node/src/lib.rs, crates/sui-storage/src/key_value_store.rs
As in title 
Existing tests
---
=> Use kv store fallback in coin_api rpc

.config/nextest.toml, narwhal/consensus/src/tests/randomized_tests.rs
Making the consensus randomized tests run for both the new and current schedule algorithm to ensure that until we enable it on production things work as expected.
---
=> [narwhal] enable randomized tests for new consensus schedule algorithm

.eslintrc.js, pnpm-lock.yaml, sdk/build-scripts/src/build-package.ts, sdk/dapp-kit/.prettierignore, sdk/dapp-kit/LICENSE, sdk/dapp-kit/package.json, sdk/dapp-kit/src/components/SuiClientProvider.tsx, sdk/dapp-kit/src/components/index.ts, sdk/dapp-kit/src/hooks/index.ts, sdk/dapp-kit/src/hooks/useSuiClient.ts, sdk/dapp-kit/src/index.ts, sdk/dapp-kit/test/hooks/useSuiClient.test.ts, sdk/dapp-kit/test/test-utils.tsx, sdk/dapp-kit/test/tsconfig.json, sdk/dapp-kit/tsconfig.esm.json, sdk/dapp-kit/tsconfig.json, sdk/dapp-kit/vitest.config.ts, sdk/typescript/package.json
This adds build/test/lint setup for a new dapp-kit package that will eventually contain a set of hooks to make building dapps using data available in our RPCs nodes easier.
This PR is primarily just setting up all the boilerplate for a new package with steps for building, testing, linting, etc and creating a few placeholder directories for things to come.
---
=> Add scaffolding for dapp-kit package

Cargo.lock, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-e2e-tests/Cargo.toml, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-node/src/lib.rs, crates/sui-storage/src/bin/http_kv_tool.rs, crates/sui-storage/src/http_key_value_store.rs, crates/sui-storage/src/key_value_store.rs, crates/sui-storage/tests/key_value_tests.rs, crates/sui-transactional-test-runner/src/test_adapter.rs, crates/sui-types/src/messages_checkpoint.rs
- Load checkpoint contents from KV store (#13262)
- Complete checkpoint fetching code (#13279)
- Use kv store for checkpoint loading (#13282)
- Use kv store fallback in coin_api rpc (#13280)
=> mlogan cherry pick ckpt kv

crates/sui-core/src/scoring_decision.rs, narwhal/consensus/src/consensus.rs, narwhal/consensus/src/tests/bullshark_tests.rs
The changes on the new leader schedule algorithm will always exclude the X% by stake of validators with the worst scores. Practically we don't have good reason to continue submitting transactions to those validators to sequence in consensus as they'll never be leaders hence they have slimmer chances of sequencing transactions.
It makes sense to align the low scoring detection on the submission side with the logic of the leader election schedule. Thus we'll make sure that only the validators who participate on the latest (updated) schedule will receive transactions to sequence them. For that reason we are removing the `MED` approach and we go with a flat exclusion always of the validators with the lowest scores and up to the designated `consensus_bad_nodes_stake_threshold` . For instance, …
=> [narwhal] align low scoring detection on submission with leader schedule

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_20.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_20.snap, narwhal/consensus/src/tests/bullshark_tests.rs, narwhal/consensus/src/tests/consensus_tests.rs, narwhal/consensus/src/tests/randomized_tests.rs
The PR is:
* enabling the new narwhal leader election schedule algorithm for version 20 for all the environments except `Mainnet`
---
=> [protocol version] increase protocol version to 20 & enable nw new leader schedule

apps/explorer/src/components/Activity/index.tsx, apps/explorer/src/ui/FilterList.tsx, apps/explorer/src/ui/Tabs.tsx
- Fit full name for tab lists
- Dynamically switching tab spacing for smaller mobile views
---
=> [Explorer]: add dynamic spacing for tabs

crates/sui-node/src/lib.rs
Settings only take effect if not explicitly set in startup configs. New defaults match existing hard-coded narwhal settings.
=> Add high-perf quic defaults for sui/state sync anemo network.

crates/sui-core/src/authority/authority_test_utils.rs, crates/sui-core/src/unit_tests/move_package_tests.rs, crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs, crates/sui-move-build/src/lib.rs, crates/sui-move/src/build.rs, crates/sui-move/src/unit_test.rs, crates/sui-source-validation/src/tests.rs, crates/sui/src/client_commands.rs, crates/sui/tests/cli_tests.rs, crates/transaction-fuzzer/src/executor.rs
A long overdue clean-up PR to get rid of the `--legacy-digest` flag on `sui client upgrade` and `sui move build`.  This flag was responsible for changing the way package digests were calculated, as the algorithm changed around protocol version 7.
```
```
---
Removes the `--legacy-digest` flag from the `sui client upgrade` and `sui move build` CLI commands, as no Sui networks require package digests to be calculated using the legacy algorithm anymore.
=> [CLI] Remove reference to --legacy-digest

kiosk/examples/collectible.move, kiosk/sources/rules/floor_price_rule.move, kiosk/sources/rules/royalty_rule.move, kiosk/sources/rules/witness_rule.move
Removes the `key + store` constraint on existing rules as it is very limiting.
Code builds
- Kiosk rules now don't constrain the type to `key + store`
=> [kiosk] Remove the key+store constraint on rules

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/types/base64.rs, crates/sui-graphql-rpc/src/types/big_int.rs, crates/sui-graphql-rpc/src/types/date_time.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/sui_address.rs
Adds skeletons for SuiAddress, BigInt, Base64, DateTime scalars which are needed for other types.
N/A
---
=> add basic scalar skeletoon

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/commands.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/tests/snapshot_tests.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
* Adds snapshot tests to ensure schema stability
* Adds command to dump the schema
```
$  ./target/debug/sui-graphql-rpc generate-schema
type Query {
chainIdentifier: String!
}
schema {
query: Query
}
```
Manual
---
=> [graphql/rpc] schema export and snapshot tests

Cargo.lock, crates/sui-json-rpc/Cargo.toml, crates/sui-json-rpc/src/authority_state.rs, crates/sui-json-rpc/src/balance_changes.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/error.rs, crates/sui-json-rpc/src/governance_api.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-json-rpc/src/lib.rs, crates/sui-json-rpc/src/metrics.rs, crates/sui-json-rpc/src/move_utils.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-json-rpc/src/transaction_builder_api.rs, crates/sui-json-rpc/src/transaction_execution_api.rs
Part of the first set of PRs is to group the errors that are possible on the RPC today into a few categories transparently, setting us up to eventually standardize error strings and resolution. This PR specifically introduces a `State` trait which `AuthorityState` implements to centralize `AuthorityState`-originating `SuiError`s so that we can disambiguate these errors from other sources of `SuiError`. This has the added benefit of helping w/ unit test writing, as demonstrated by `coin_api` and `move_utils`.
No change has been made to error strings, but StateReadError::Internal will now code to `-32603` instead of `-32000`. But this can be negotiable too.
Existing tests
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please …
=> [rpc][structured-error-handling][2/n] State trait for AuthorityState, group AuthorityState-originating SuiErrors

crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/name_service.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Adds the `Owner` interface and the required stubs to get it to work
Snapshot
---
=> [graphql/rpc] owner interface and stubs

.github/workflows/nightly-narwhal.yml, crates/sui-core/src/authority/authority_store_pruner.rs
1. For some reason, `info!("Max eligible checkpoint {}", max_eligible_checkpoint);` is pretty noisy in simtests. Downgrading it to `debug`.
2. Remove test that no longer exists from Narwhal nightly CI config
CI
Locally run
```
cargo nextest run -E 'kind(test) and (package(narwhal-primary) + package(narwhal-consensus))' --profile narwhalnightly --run-ignored ignored-only
``` 
---
=> [Cleanup] fix logging and CI config

external-crates/move/move-vm/profiler/src/lib.rs
Fixes a bug causing unused data in gas profiler output.
Reduced size of profile considerably (15MB to 5MB in test).
Manual
---
=> [vm] reduce duplicate frame names

.github/CODEOWNERS, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/name_service.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Sets up all the stubs for `Address` and cleans up some nits.
Adds reviewers to codeowners
Snapshot
---
=> [graphql/rpc] Graphql impl part5 address stubs

external-crates/move/move-compiler/src/cfgir/absint.rs, external-crates/move/move-compiler/tests/move_check/liveness/implicit_copy_with_continue.move
- Fixed abs int bug that was fixed in the bytecode verifier, but not the compiler
- Addressing https://github.com/move-language/move/issues/1068
- Added a test
---
Fixed an edge-case bug with the Move compiler that could result in control-flow sensitive errors not being caught before reaching the bytecode verifier.
=> [move-compiler] Fixed abstract interpreter bug

narwhal/config/src/committee.rs, narwhal/network/src/client.rs, narwhal/network/src/p2p.rs, narwhal/network/src/traits.rs, narwhal/primary/src/lib.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/synchronizer.rs, narwhal/primary/src/tests/certificate_fetcher_tests.rs, narwhal/primary/src/tests/certifier_tests.rs, narwhal/primary/src/tests/primary_tests.rs, narwhal/primary/src/tests/rpc_tests.rs, narwhal/primary/src/tests/synchronizer_tests.rs, narwhal/test-utils/src/cluster.rs, narwhal/types/src/worker.rs, narwhal/worker/src/batch_fetcher.rs, narwhal/worker/src/worker.rs
Use `NetworkClient` to plumb `anemo::Network` to components and tests.
Add a test for primary and worker RPC authorizations.
CI
---
=> [Narwhal] add test for primary and worker RPC authorizations

.changeset/four-meals-clean.md, sdk/typescript/scripts/generate.ts, sdk/typescript/src/client/types/generated.ts
I think this type got overlooked because it wasn't used anywhere in the Sui repo, but having 2 things called `TransactionBlock` may cause some confusion.  This aligns this types name more closely with other generated types
---
=> [ts-sdk] rename generated TransactionBlock type to avoid naming conflicts

crates/sui-e2e-tests/tests/unwrapped_then_deleted_tests.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
simplified_unwrap_then_delete is enabled in v16, sui-execution latest is enabled in v18.
So we could always assume simplified_unwrap_then_delete in sui-execution latest without having to check it.
CI
---
=> Assume simplified_unwrap_then_delete in sui-execution latest

crates/sui-graphql-rpc/schema/draft_schema.graphql
- `Owner` becomes `ObjectOwner`
- `AmbiguousOwner` becomes `Owner` and gets downcasts to `Address` and `Object`.
- New `enum`: `ObjectKind` to indicate whether the object is owned, shared or immutable.
```
schema$ graphql-inspector diff draft_schema.graphql draft_schema.graphql
```
=> [GraphQL/RFC] Changes to Owner

crates/sui-graphql-rpc/src/server/data_provider.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Adds
* Chain identifier with rpc 1.0 data source
* Basic `Object` pagination/connection impl with rpc 1.0 data source
Sample output below
Manual
---
=> [graphql/rpc] object connection pagination support with rpc 1.0 backing

crates/sui-graphql-rpc/schema/draft_schema.graphql, crates/sui-graphql-rpc/src/server/data_provider.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
As spotted during the review of #13379 -- we need a different kind for objects that are owned by other objects via a dynamic field (as opposed to being transfered to another object).
```
```
=> [GraphQL/RFC] Add a "CHILD" ObjectKind

apps/wallet/src/background/accounts/zk/ZkAccount.ts
* currently only aud of type string is supported
* throw an error if for some reason aud is an array
👀 
---
=> wallet-ext: don't allow aud to be array

crates/sui-json-rpc/src/error.rs, crates/sui-json-rpc/src/logger.rs, crates/sui-json-rpc/src/metrics.rs
Overall simplify execution-side errors on `execute_transaction_block` RPC method by informing the caller how to resolve in the error message and reducing the data we put into the `data` field.
1. (modify) QuorumDriverError::InvalidUserSignature, ::ObjectsDoubleUsed, NonRecoverableTransactionError are now considered client errors
2. (new) ::TimeoutBeforeFinality, as a transient error -32000
4. (modify) For NonRecoverableTransactionError, populate 'data' field with vector of error strings. Previously, we dump Vec<(SuiError, StakeUnit, Vec<ConciseAuthorityPublicKeyBytes>)> which just becomes a huge object. Transient errors are filtered out, unless they are the only error in the data field, in which case we return a generic error string and ask the caller to just try again.
6. (new) For …
=> [rpc] Simplify error response from execute_transaction_block of transaction_execution_api

narwhal/primary/src/tests/rpc_tests.rs, narwhal/primary/tests/nodes_bootstrapping_tests.rs, narwhal/test-utils/src/cluster.rs
It seems after the merge of this PR https://github.com/MystenLabs/sui/pull/13328/files the narwhal nightly tests started failing https://github.com/MystenLabs/sui/actions/runs/5828472064/job/15806247384
This PR is refactoring the cluster struct so we always create a new network client and inject it to the primary/worker nodes to ensure that we don't deal with any internal state mutations after shutdown (which were preventing properly reusing the client on a new start).
---
=> [fix] small refactoring to fix the usage of Network client in cluster tests

crates/sui-graphql-rpc/schema/draft_schema.graphql, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Replace the `objectId` and `version` fields in `ObjectFilter` with `objectIds: [SuiAddress!]` and `objectKeys: [ObjectKey]`, so that `objectConnection` can be used to multi-get objects.
Schema generation:
```
sui-graphql-rpc$ cargo insta test
```
=> [GraphQL] Interface for Object multi-get

crates/sui-graphql-rpc/schema/draft_schema.graphql, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
This reduces the size of the index needed to serve this kind of query while still satisfying the requirements on Explorer.
```
```
=> [GraphQL] Limit TransactionBlockKind to system vs programmable

crates/sui-move-build/src/linters/custom_state_change.rs, crates/sui-move-build/src/linters/self_transfer.rs, crates/sui-move-build/src/linters/share_owned.rs, external-crates/move/move-compiler/src/cfgir/visitor.rs, external-crates/move/move-compiler/src/sui_mode/id_leak.rs
- Added defaults for custom functions in absint visitor
- cargo check
---
=> [move-compiler] Use default implementations for custom visitors in SimpleAbsInt

crates/sui-graphql-rpc/src/commands.rs
`main` fails because `help` short form of `h` conflicts with `host` short form.
Manual
---
=> [graphql/rpc] fix cmd clobber with help short cmd

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/server/mod.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/server/version.rs
Adds two pieces of middleware:
- One that checks the version of the service against the version of in the request header.
- One that adds the version to the response header.
```
```
=> [GraphQL] Versioning Middleware

apps/explorer/src/components/validator/StakeButton.tsx
The validator pages are broken on Sui Explorer because we're checking `wallet.wallet.features` and doing some type assertions to see what wallets supported the staking feature. With https://github.com/MystenLabs/sui/pull/13359, now we should just be checking `wallet.features` instead of `wallet.wallet.features`
Broken:
https://suiexplorer.com/validator/0x9062fc51d91056246dc31f2b818a4ddb113a044ec22c8dd0674616bbe56f7192
Fixt:
https://explorer-git-wrobertson-fixvalipage-mysten-labs.vercel.app/validator/0x4430b86069d8850d9bee199739e5fc90bb0f323a5a7735f431ec7a5fb5409e6b
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes …
=> [explorer] fix the validator page crashing because we're checking the wrong field for wallet features

crates/sui/src/client_commands.rs, doc/src/build/dev_cheat_sheet.md, doc/src/learn/cryptography/sui-offline-signing.md
It seems the flag name has been updated.
CI
Ran command with the new flag name.
---
=> [Doc] Update `--serialize-output` to `--serialize-unsigned-transaction`

apps/wallet/src/ui/app/pages/layout/index.tsx, apps/wallet/src/ui/styles/global.scss
I have no clue why this issue started happening out of the blue, but changing the flex-direction to `row` makes div respect its child's width/height properly. Some folks mentioned that it happened after they updated their browser, but I'm using the latest version of Chrome and couldn't get a repro 🤷🏼‍♂️ 
Before:
After:
Chrome fullscreen:
Chrome popup:
- Played around with the wallet in Chrome/Brave in popup mode and fullscreen mode and it seems to work fine
---
=> [wallet-ext] fix the browser extension having a width of 25px when used on Brave and sometimes Chrome

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/server/data_provider.rs, crates/sui-graphql-rpc/src/types/base64.rs, crates/sui-graphql-rpc/src/types/big_int.rs, crates/sui-graphql-rpc/src/types/sui_address.rs
1. Consolidate error strings to sui_graphql_rpc::Error enum.
2. Extend enum variants with machine-readable code using ErrorExtensions. Map code to default graphql codes as best as possible.
3. Use graphql::InputValueError::expected_type for parsing logic. 
Follow-up:
1. Error middleware to extend all errors with a machine-readable code. As an example, if we run into a validation issue of graphql::InputValueError, it would be missing errors[n].extensions.code
2. embedded error typing for queries like fetch_owned_objs
---
=> CustomError enum

crates/sui-swarm-config/src/genesis_config.rs
We keep hitting problems due to the fact that we rely on executing `sui keytool generate` within our network redeploy scripts and parsing the cli stdout.
This PR allows us to remove that dependency by ~adding an optional, `--override-validator-keypairs` flag to `sui genesis`~ setting default values for the validator keypairs, in the event that they are left unset (thanks @longbowlu for the suggestion).
Tested locally, I'll also test as a part of our deploy pipeline
=> add serde defaults to ValidatorGenesisConfig

crates/sui-source-validation-service/Cargo.toml, crates/sui-source-validation-service/config.toml, crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/tests/tests.rs
Adds ability to specify `watch = <Object ID>` to track on-chain upgrades. This PR is scaffolding and only adds the option to the config and the Rust types, no actual tracking of the `Object ID`. That happens in follow up PR: https://github.com/MystenLabs/sui/pull/13396.
Updated tests for config schema.
---
=> move: field to watch upgraded objects in source service

crates/sui-indexer/src/lib.rs
the epoch commit sometimes takes longer than that b/c it has triggers which are relatively slow.
test in tnt production
---
=> indexer: read statement timeouts from env variables

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/server/data_provider.rs, crates/sui-graphql-rpc/src/server/json_rpc_data_provider.rs, crates/sui-graphql-rpc/src/server/mod.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs, crates/sui-graphql-rpc/src/types/query.rs
DataProvider trait + pass Box<dyn DataProvider> to graphql objects
---
=> [graphql] data provider trait to support swapping out providers for snapshot testing

crates/sui-graphql-rpc/src/server/context_ext.rs, crates/sui-graphql-rpc/src/server/mod.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/server/sui_sdk_data_provider.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs, crates/sui-graphql-rpc/src/types/query.rs
1. Implement DataProvider trait directly on sui_sdk
2. Extend Context struct so we can avoid having to write ctx.data_unchecked everywhere
3. Caught a potential bug where we were erroneously still expecting sui_sdk
Verified that the following query returns an expected result:
```
query:
{
address(
address: "0xefa434f1441f5d61bfb5f3d9a26e494e8fcaef87a69cd9ce639d6b648cc8a512"
) {
balance {
totalBalance
}
objectConnection(first:10) {
edges {
node {
version, digest, kind
}
}
}
}
object(address:"0x0000b4e82142db2a8b933ea453f37c26ba6144d6d4a670f22153e9a4a9ef0142") {
version, previousTransactionBlock {
bcs
}, objectConnection(first: 10) {
edges {
node {
version
}
}
}
}
protocolConfig {
protocolVersion
}
chainIdentifier
}
```
---
If your changes are not user-facing and not a breaking change, you …
=> [graphql] Data provider trait followup

crates/sui-move-build/src/linters/freeze_wrapped.rs, crates/sui-move-build/tests/linter/freeze_wrapped.exp, crates/sui-move-build/tests/linter/freeze_wrapped.move
The original implementation of the freeze wrapped linter (https://github.com/MystenLabs/sui/pull/13194) had a bug - arguments to the transfer function were not processed to look for other cases where the linter warning should kick in. The case would have to look similarly to the example below, which makes it pretty unlikely, but still...
```
public fun freeze_arg(w1: Wrapper, w2: Wrapper) {
transfer::public_freeze_object({ transfer::public_freeze_object(w1) ; w2});
}
```
Added a test capturing the missing bit (same as example above)
---
=> [move-compiler] A fix to the freeze wrapped linter

apps/explorer/src/pages/transaction-result/programmable-transaction-view/TransactionsCard.tsx
- @mystie711 requested to auto-expand the txn card on txn block page when opening
---
=> [explorer]: auto expand transaction cards

crates/sui-graphql-rpc/src/server/sui_sdk_data_provider.rs, crates/sui-graphql-rpc/src/types/big_int.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Add data provider for the GasInput graphql type. 
Manually checked the output for now. 
---
=> [graphql] Add data provider for the GasInput type

apps/explorer/src/hooks/useSearch.ts
All SuiNS domain names are lowercase, so we should lowercase the query when doing the domain look-up from Sui Explorer.
- Manual testing (Scam.sui returns results now)
---
=> [explorer] lowercase SuiNS domain names when performing searches

doc/src/build/fullnode.md
Adding gcs bucket to fullnode archive fallback documentation.
Existing tests
=> Adding gcs archive bucket to fullnode doc

sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/v0/sui-adapter/src/execution_engine.rs
conserve_unmetered_storage_rebate call is not part of the conservation check. Move the code around to avoid confusion.
CI
---
=> Nit cleanup in run_conservation_checks

crates/sui-framework-tests/src/unit_tests.rs, examples/sui-move/entry_functions/Move.toml, examples/sui-move/entry_functions/sources/example.move
Some examples of functions that are and are not entry functions, to be used as part of Sui docs.
This PR also introduces a new home for sui-move examples (i.e. to port examples from `sui_programmability`).
```
sui$ cargo build --bin sui
sui$ ~/sui/target/debug/sui move build -p ~/sui/examples/sui-move/entry_function
sui-framework-test$ cargo nextest run
```
=> [docs/entry] Runnable examples for entry function docs

crates/sui-core/src/authority.rs, crates/sui-genesis-builder/src/lib.rs, crates/sui-move/src/unit_test.rs, crates/sui-replay/src/replay.rs, crates/sui-swarm-config/src/network_config_builder.rs, sui-execution/src/executor.rs, sui-execution/src/latest.rs, sui-execution/src/v0.rs
This PR makes it such that we always construct TempStore and GasCharger inside execution layer, and there is no more access to either of these two types outside of execution. This sets up the code in the right shape for step 2 of actually moving them.
Non functional change, CI.
---
=> [1/2] Move TempStore and GasCharger to execution layer

crates/sui-indexer/src/models/transaction_index.rs, crates/sui-indexer/src/processors/address_processor.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
see thread in https://mysten-labs.slack.com/archives/C0578KFD9D2/p1693095224772239?thread_ts=1692994121.678369&cid=C0578KFD9D2
tested on devnet and made sure that addr stats can be populated accordingly based on recipients table;
could not test on mainnet b/c old txns have been pruned
---
=> indexer: update address & active address info based on recipients instead

crates/sui-types/src/execution.rs, crates/sui-types/src/storage.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs, sui-execution/latest/sui-move-natives/src/test_scenario.rs, sui-execution/suivm/sui-adapter/src/programmable_transactions/context.rs, sui-execution/suivm/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/suivm/sui-adapter/src/temporary_store.rs, sui-execution/suivm/sui-move-natives/src/object_runtime/mod.rs, sui-execution/suivm/sui-move-natives/src/object_runtime/object_store.rs, sui-execution/suivm/sui-move-natives/src/test_scenario.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs
Refactor sui-execution latest to make it generate primitive execution results, which is compatible with both transaction effects v1 and v2.
The purpose of this change is to gradually introduce changes necessary for effects v2.
In this change, instead of figuring out write kinds and delete kinds in the runtime, we only generate primitive results in the runtime, and then in the end we derive all the write kinds and delete kinds from the primitive results to generate effects v1.
This is a non-functional change, and allows us to test the sui-execution refactoring using existing production data.
In the next PR I will refactor the rest of execution engine to also generate effects v2 compatible results.
CI.
Also ran fullnode locally and sync on mainnet.
---
If your changes are not user-facing …
=> sui-execution generate primitive results

crates/sui-faucet/src/faucet/simple_faucet.rs
Separating out queues so that batch and normal transfers don't try to use the same gas coin
Currently there is a race condition where the 2 API calls `batch_gas` and `gas` try to use the same coin. This is a PR to implement a different queue so that they don't contest each other
---
=> [Faucet] Adding 2 consumer queues for locking

crates/sui-indexer/migrations/2023-03-05-165748_transaction_index/up.sql, crates/sui-indexer/migrations/2023-03-20-041133_epoch/down.sql, crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql, crates/sui-indexer/src/store/pg_indexer_store.rs
context is https://mysten-labs.slack.com/archives/C05PUKKGNRF/p1693190511602099
make DB ops with _test and verify that it returns the same result as the original view
```
defaultdb=> SELECT
defaultdb->                 day,
defaultdb->                 move_package,
defaultdb->                 move_module,
defaultdb->                 move_function,
defaultdb->                 count
defaultdb->             FROM epoch_move_call_metrics_test WHERE epoch = (SELECT MAX(epoch) FROM epoch_move_call_metrics_test);
day |                            move_package                            |    move_module    |         move_function         |  count
-----+--------------------------------------------------------------------+-------------------+-------------------------------+----------
3 | …
```
=> indexer: epoch move call view -> table

.changeset/lovely-adults-heal.md, sdk/wallet-standard/README.md
Just a quick fix for a broken doc site link that I encountered while working on dapp-kit stuff. https://sui-wallet-kit.vercel.app/wallet-kit/advanced/wallet-standard is the correct URL for the wallet-standard documentation (the other URL gives a 404).
- 👁️ 
---
=> [wallet-standard] fix broken documentation link for the wallet-standard SDK

scripts/generate-release-notes.sh
Adding protocol change highlight to release notes script
```
eugene@mac-studio ~/code/sui (eugene/add_protocol_highlight_to_release_notes) $ ./scripts/generate-release-notes.sh releases/sui-v1.7.0-release releases/sui-v1.8.0-release
Sui Protocol Version in this release: XX
https://github.com/MystenLabs/sui/pull/13124:
Add protocol config feature flags for zkLogin to enable testing in Devnet, use updated proof verification logics for zkLogin signature verification.
https://github.com/MystenLabs/sui/pull/13417:
When building Move code, there are now additional linter warnings related to comparing collections from Sui framework code (`Bag`, `Table`, and `TableVec`). Note that this comparison is not a structural one based on the collection content, which is what one might expect, so Sui now …
```
=> Adding protocol change highlight to release notes script

crates/sui-adapter-transactional-tests/tests/dynamic_fields/remove_add_back_and_remove.exp, crates/sui-adapter-transactional-tests/tests/dynamic_fields/remove_add_back_and_remove.move
There seems to be an implementation inconsistency in the object runtime.
If we remove a dynamic object field and transfer it, such removal will show up in child object effects which is expected: https://github.com/MystenLabs/sui/blob/ebf24400925047e868971ddac2a3b24bbec0c467/sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs#L442, and hence processing child object effects is sufficient to figure out all child object changes.
However, if we remove a field, add it back, remove it again, and then transfer it, such change won't show up in child object effects, hence we have to consult the transfers to figure it out (similar for deletes).
Add a test to expose such case and makes sure we always get it right.
CI
---
If your changes are not user-facing and not a breaking change, you …
=> Add adapter tests for repeat dynamic field add/removal

crates/sui-rest-api/src/checkpoints.rs
Fix a bug when getting events when requesting a full checkpoint due to the fact that events are not unique. It is possible that two transactions both have identical events emitted, leading them to have the same emitted events digests.
---
=> rest: fix bug when getting events when requesting a full checkpoint

examples/sui-move/dynamic_fields/Move.toml, examples/sui-move/dynamic_fields/sources/example.move
So that they are built and run as part of CI.  As a side effect, I found that the examples in the docs can be simplified.
```
sui-framework-tests$ cargo nextest run -- run_docs_examples_move_unit_tests
```
=> [docs/dynamic-fields] Put dynamic fields docs examples in repo

narwhal/network/src/p2p.rs, narwhal/worker/src/batch_maker.rs, narwhal/worker/src/quorum_waiter.rs
- When broadcasting a batch, set a request timeout which will be retried.
- When batch quorum broadcast fails (which can only happen on Narwhal worker shutdown, or when the node is byzantine itself), do not forward the batch to be included in headers.
Currently when broadcasting a Narwhal batch, requests to each peer will be retried indefinitely. This partially addresses the issue where a batch can fail verification then succeed later at the receiver. Two related issues are fixed as described above.
When a node is itself unintentionally byzantine, it is possible that its quorum broadcast will be stuck indefinitely until quorum waiter is filled up. We can fail a request if there are > f failure responses and retry from the consensus adapter or client if needed. But current behavior should …
=> [Narwhal] harden batch quorum broadcast

crates/sui-indexer/migrations/2023-03-06-182806_checkpoint_metrics/up.sql, crates/sui-indexer/src/store/pg_indexer_store.rs
Saw this error on indexer 0
```
`Failed persisting checkpoint metrics to PostgresDB`: `Indexer failed to commit changes to PostgresDB with error: `duplicate key value violates unique constraint "checkpoint_metrics_pkey"``
```
CI
---
=> indexer: on conflict do nothing for cp metrics processor

crates/sui-core/src/authority.rs, crates/sui-core/src/authority_client.rs, crates/sui-core/src/test_authority_clients.rs, crates/sui-core/src/transaction_orchestrator.rs
- Reenable local execution for transactions with shared input objects.
- Remove unused code for input object fast path.
CI.
---
=> [Fullnode] more cleanups on local execution

crates/sui-graphql-rpc/src/server/sui_sdk_data_provider.rs, crates/sui-graphql-rpc/src/types/date_time.rs, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Add epoch's timestamp fields.
Manually. 
---
=> [graphql] add epoch's timestamp fields

apps/wallet/src/ui/app/components/IconButton.tsx, apps/wallet/src/ui/app/components/accounts/AccountItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountListItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountMultiSelectItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountsList.tsx, apps/wallet/src/ui/app/hooks/useExplorerLink.ts, apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx
Updates the accounts list UI to match the latest designs for copying to clipboard and links out to Explorer.
https://github.com/MystenLabs/sui/assets/122397493/cc61ca84-0338-480c-abdc-1bd8b529804e
---
=> [wallet-ext] - update copy / explorer link UI for accounts

crates/sui-types/src/dynamic_field.rs, crates/sui/src/client_commands.rs, crates/sui/src/console.rs
This PR implements the structured output (table with header and rows) for two Sui CLI commands, `sui client addresses` and `sui client dynamic-field`. 
Manual tests by running the commands.
---
This PR implements the structured output (table with header and rows) for two Sui CLI commands, `sui client addresses` and `sui client dynamic-field`.
=> [cli] change display output for addresses and dynamic field in the Sui CLI client command

crates/sui-core/src/test_utils.rs, crates/sui-core/src/unit_tests/authority_aggregator_tests.rs, crates/sui-core/src/unit_tests/execution_driver_tests.rs, crates/sui-core/src/unit_tests/gas_tests.rs, crates/sui-core/src/unit_tests/move_integration_tests.rs, crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_23.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_23.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_23.snap, crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui-test-transaction-builder/src/lib.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/messages_tests.rs, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/latest/sui-adapter/src/gas_charger.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/suivm/sui-adapter/src/execution_engine.rs, sui-execution/suivm/sui-adapter/src/gas_charger.rs, sui-execution/suivm/sui-adapter/src/temporary_store.rs
This is a PR that supersedes #13387 . It is applied only to `latest` and `suivm` given the latest changes that brought `TemporaryStore` and `GasCharger` into the execution layer.
Re-enabled some gas tests and changed some gas constants to be more in line with a proper usage.
We still have one big value that seems inevitable (though maybe code could be organized better).
Removed some redundant code and some cleanup as highlighted by @lxfind, thanks!
@lxfind @sblackshear please read below...
We made changes to the conservation checks. Specifically we broke them into 2 parts and re-enabled some tests that were commented because of OOG logic. We now have 2 conservation check functions: a simple one and the expensive one. The expensive one is the same, the simple one has been lifted into its …
=> Update on gas tests and conservation rules

crates/sui-core/src/unit_tests/move_integration_tests.rs, crates/sui-core/src/unit_tests/move_package_publish_tests.rs, crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_23.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_23.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_23.snap, crates/sui-types/src/error.rs, crates/sui-types/src/transaction.rs
There is no point in having a significant number of publish/upgrade in a single transaction block.
Cost will be higher after a relatively low number because of memory compound effects and tracking upgrade caps/packages will be harder.
So we are adding a protocol config controllable cap to the number of publish/upgrades per PTB
New tests added for publish, upgrade and mixed
---
=> Limit number of pacakges/upgrades in a single transaction block

examples/sui-move/color_object/Move.toml, examples/sui-move/color_object/sources/example.move
Original: ./sui_programmability/examples/objects_tutorial/sources/color_object.move
Port and modernise:
- Remove use of `entry` keyword.
- Remove custom transfer/freeze etc functions, in favour of adding `store` to the type.
- Standardise example against other examples (similar comments, test structure etc.)
Existing unit tests:
```
examples/sui-move$ sui move test -p color_object
```
=> [example/color_object] Port color_object.move

narwhal/primary/src/synchronizer.rs, narwhal/primary/src/tests/synchronizer_tests.rs
GC logic in Synchronizer is a bit more complicated than necessary. Refactor it to just accept all certificates at and below gc round + 1.
CI
---
=> [Narwhal] simplify GC logic in Synchronizer

crates/sui/src/keytool.rs
Improves how the `keytool convert` command is displayed by explicitly showing the output's encoding: base64 or hex
---
=> [cli] improve how the keytool convert command is displayed

crates/sui-types/src/move_package.rs, crates/sui-types/src/object.rs, external-crates/move-execution/suivm/move-vm/runtime/src/lib.rs, external-crates/move-execution/suivm/move-vm/runtime/src/move_vm.rs, external-crates/move-execution/suivm/move-vm/runtime/src/runtime.rs, sui-execution/suivm/sui-adapter/src/programmable_transactions/context.rs, sui-execution/suivm/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/suivm/sui-adapter/src/programmable_transactions/linkage_view.rs, sui-execution/suivm/sui-adapter/src/type_layout_resolver.rs
This is the first step in removing Session from the execution layer/adapter.
It's a replacement for #13000 as it creates a new version of the execution layer.
It also adds a couple of protocol config features around publishing, a change in charging and in the number of packages published per PTB.
Here we get rid of Session entirely. However there is a lot more we are doing in the VM (loader and more) and in the adapter traits. More coming.
I have the change for protocol config here, however I could remove it if we want to go in without the protocol change yet. Looking for feedback around how we want to push this.
We can enable this only for devnet (maybe testnet) if we wanted, or go to mainnet, or nowhere for now.
@tnowacki @amnn sorry for the churn but this should be what you reviewed …
=> Remove session

examples/sui-move/trusted_swap/Move.toml, examples/sui-move/trusted_swap/sources/example.move
Original: ./sui_programmability/examples/objects_tutorial/sources/trusted_swap.move
Porting and modernising example used in "object wrapping" documentation, with the following changes:
- Moved into an isolated move package.
- Remove use of `public entry`
- Avoid transfer-to-sender pattern where possible (e.g. creating a new object and returning the fee to the service).
- Use named error codes.
- Add unit tests that will get run during CI.
- Rename `ObjectWrapper` to `SwapRequest`.
```
sui move test trusted_swaps
```
=> [example/swap] Port trusted_swap.move

examples/sui-move/escrow/Move.toml, examples/sui-move/escrow/sources/example.move
Original: ./sui_programmability/examples/defi/sources/escrow.move
Porting and modernising example used in "object wrapping" documentation, with the following changes:
- Moved into an isolated move package.
- Remove use of `public entry`
- Add unit tests that will get run during CI.
The modernised example also addresses the TODO in the original where one party can commit to a trade believing they are getting one object, only to have that object modified (and therefore made less valuable).
This is done by adding a new phase to the swap where parties lock the object they are going to transfer.  See comments in the example for how this is done while preserving safety and liveness at all stages.
```
sui-move$ sui move test -p escrow
```
=> [example/escrow] Port escrow.move

examples/sui-move/hero/Move.toml, examples/sui-move/hero/sources/example.move
Original: ./sui_programmability/examples/games/sources/hero.move
Modernise and port the hero game example.  Involves many changes:
Made `GameInfo` (now `Game`) a shared object that collects funds from player's actions, instead of it being an immutable object that pointed to an address to send funds to (this improves UX because players make payments by interacting with a stable object identity while admins have the flexibility of storing the `Admin` cap wherever they like and using that to recover those funds).
`Boar` gets `store`, because I'm not sure why it didn't have `store` in the first place. `Admin` has `store` because it's now fine to freely transfer it around.
Changed style for error codes, to use `EUpperPascalCase`.
Got rid of module initializer -- also no longer required for …
=> [example/hero] Port hero.move

crates/sui-core/src/authority.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-kvstore/src/client.rs, crates/sui-kvstore/src/writer.rs, crates/sui-storage/src/http_key_value_store.rs, crates/sui-storage/src/key_value_store.rs, crates/sui-storage/tests/key_value_tests.rs
Adds support for reading/writing transaction to checkpoint metadata to kvstore. Please check that i've properly covered all the necessary pieces since this is my first time modifying this system.
---
=> kvstore: add support for reading/writing transaction to checkpoint metadata

apps/wallet/src/ui/app/hooks/useCreateAccountMutation.ts, apps/wallet/src/ui/app/pages/accounts/ImportPrivateKeyPage.tsx
* enable onboarding by importing a private key account
https://github.com/MystenLabs/sui/assets/10210143/3952ed19-b3b2-49bb-941d-073cf1984396
part of APPS-1501
closes APPS-1587
👀 
---
=> wallet-ext: onboarding import private key account

apps/wallet/src/background/connections/UiConnection.ts, apps/wallet/src/background/qredo/index.ts, apps/wallet/src/background/qredo/utils.ts, apps/wallet/src/shared/messaging/messages/payloads/QredoConnect.ts, apps/wallet/src/ui/app/background-client/index.ts, apps/wallet/src/ui/app/components/DAppInfoCard.tsx, apps/wallet/src/ui/app/components/accounts/AccountsFormContext.tsx, apps/wallet/src/ui/app/hooks/useCreateAccountMutation.ts, apps/wallet/src/ui/app/index.tsx, apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx, apps/wallet/src/ui/app/pages/qredo-connect/SelectQredoAccountsPage.tsx
* allow onboarding with qredo
https://github.com/MystenLabs/sui/assets/10210143/dc4f3fb4-de6e-4d30-90bf-1ddbd8fb2b6b
* includes a small fix for DAppInfoAppCard to hid permission if not provided (not required)
| -- | -- |
| <img width="367" alt="Screenshot 2023-09-04 at 18 45 42" src="https://github.com/MystenLabs/sui/assets/10210143/81720f06-6342-412b-b963-ce36244cfd28"> | <img width="367" alt="Screenshot 2023-09-04 at 18 45 56" src="https://github.com/MystenLabs/sui/assets/10210143/9720439d-4cfb-4d36-8104-906ac05b1c8a"> |
part of APPS-1501
👀 
---
=> wallet-ext: onboarding qredo accounts

apps/wallet/src/ui/app/hooks/useInitializedGuard.ts, apps/wallet/src/ui/app/pages/accounts/WelcomePage.tsx
* wait to finish before navigating to tokens page
* this fixes an issue where the account is locked and the unlocked (now it wait for it to unlock)
* this adds an enabled flag to init guard since this was that was doing the redirect
* creating zklogin account time will be improved with APPS-1621
before
https://github.com/MystenLabs/sui/assets/10210143/fda96339-db92-4148-a8d5-b44f13d731b0
after
https://github.com/MystenLabs/sui/assets/10210143/6822b16b-d7fe-4a77-84f2-5b7e341e9ac6
closes APPS-1501
👀 
---
=> wallet-ext: welcome page wait for creating zklogin to finish

apps/wallet/src/ui/app/components/accounts/AccountsFormContext.tsx, apps/wallet/src/ui/app/components/accounts/ZkLoginButtons.tsx, apps/wallet/src/ui/app/hooks/useCountAccountByType.ts, apps/wallet/src/ui/app/hooks/useCreateAccountMutation.ts, apps/wallet/src/ui/app/pages/accounts/AddAccountPage.tsx, apps/wallet/src/ui/app/pages/accounts/ProtectAccountPage.tsx, apps/wallet/src/ui/app/pages/accounts/WelcomePage.tsx, apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx, apps/wallet/src/ui/app/shared/tooltip/index.tsx, apps/wallet/src/ui/app/shared/utils/ButtonOrLink.tsx
* add accounts page support for zk login accounts
* allow only one zklogin account for each provider
* show a tooltip why a zklogin button is disabled
* force doing the zklogin creation flow in a tab to avoid having the popup closed during the process
* changes the accounts form values to context to avoid having issues with outdated values
* tittle prop for ButtonOrLink now renders a tooltip
https://github.com/MystenLabs/sui/assets/10210143/40a95458-d42b-4e98-9df5-5da9e19be7de
https://github.com/MystenLabs/sui/assets/10210143/2386b3b7-5cf6-4d9d-8a87-f3a45b77eec1
* adding accounts shows password verification when password accounts exist
https://github.com/MystenLabs/sui/assets/10210143/fdf3f55b-7707-47b3-9140-38c6eb80eca5
closes APPS-1496
👀 
---
If your changes are not user-facing and not …
=> wallet-ext: add accounts functionality

crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/extensions/timeout.rs, crates/sui-graphql-rpc/src/server/simple_server.rs
Allows setting a timeout for the overall request. This helps limit long running queries.
Manual
---
=> [graphql/rpc] query complexity limiting: add request time limiter

crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, narwhal/Docker/validators/parameters.json, narwhal/benchmark/README.md, narwhal/benchmark/fabfile.py, narwhal/config/src/lib.rs, narwhal/config/tests/snapshots/config_tests__parameters.snap, narwhal/config/tests/snapshots/config_tests__parameters_import.snap, narwhal/test-utils/src/cluster.rs, nre/config/validator.yaml
This change should be less relevant after leader schedule change rolls out. And dynamic config will be strictly better. Still, when a validator is down, 2s timeout is too disruptive. Reducing it to 1s.
Watching private testnet metrics.
---
=> [Narwhal] reduce max header timeout from 2s to 1s

crates/sui-kvstore/src/client.rs, crates/sui-kvstore/src/writer.rs
temporary PR used for initial backfill
=> kvstore: add suport for writting tx to checkpoint to dynamodb

.changeset/fuzzy-pumpkins-provide.md, apps/wallet/src/background/accounts/zk/ZkAccount.ts, apps/wallet/src/shared/cryptography/keystore.ts, sdk/zklogin/src/bcs.ts
* generate proofs only when required for signing
* keep ephemeral keys/logins in cache for each network to avoid always creating new one every time user switches
* this makes login-in pretty fast but adds about 3-5 seconds before executing a transaction (but only if proofs are not cached already)
* zklogin make email in claims optional
* zklogin-sdk: update AddressParams struct to not require aud since it was removed [here](https://github.com/MystenLabs/sui/pull/13617/files#diff-6b13a8f8558936c1cc76658631764d455f401ff65b40498c63e53908bcf0e4baR56)
closes APPS-1621
👀 
--- …
=> wallet-ext: zklogin generate proofs only when required

.changeset/stale-wolves-relate.md, sdk/bcs/src/hex.ts, sdk/bcs/tests/encodings.test.ts
=> [bcs] Fix parsing of hex strings where leading 0s have been trimmed

crates/sui-core/src/authority.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-kvstore/src/client.rs, crates/sui-kvstore/src/writer.rs, crates/sui-storage/src/http_key_value_store.rs, crates/sui-storage/src/key_value_store.rs, crates/sui-storage/tests/key_value_tests.rs
Adds the ability to fetch transaction -> checkpoint number mappings from the kvstore.
---
=> cherrypick kvstore tx to checkpoint changes to 1.9

apps/wallet/src/background/account-sources/AccountSource.ts, apps/wallet/src/background/account-sources/MnemonicAccountSource.ts, apps/wallet/src/background/account-sources/QredoAccountSource.ts, apps/wallet/src/background/account-sources/index.ts, apps/wallet/src/background/accounts/Account.ts, apps/wallet/src/background/accounts/ImportedAccount.ts, apps/wallet/src/background/accounts/LedgerAccount.ts, apps/wallet/src/background/accounts/MnemonicAccount.ts, apps/wallet/src/background/accounts/index.ts, apps/wallet/src/background/accounts/zk/ZkAccount.ts, apps/wallet/src/background/qredo/index.ts, apps/wallet/src/background/storage-migration.ts, apps/wallet/src/ui/app/components/accounts/AccountListItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountsList.tsx, apps/wallet/src/ui/app/components/accounts/FooterLink.tsx, apps/wallet/src/ui/app/helpers/sortAccounts.ts, apps/wallet/src/ui/app/hooks/useAccountGroups.ts, apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx, apps/wallet/src/ui/app/pages/accounts/manage/ManageAccountsPage.tsx
- adds some helper functions to group the accounts list by `type` and `sourceID` / `provider` / other for display on the Manage Accounts page. 
- sort accounts within a group
- add default sort for account groups: `zk -> mnemonic-derived -> imported -> ledger -> qredo`
notes:
-  might want to rename `useAccountGroups` to something else
- we should eventually update the UI to distinguish groups of the same type (Passphrase Derived in the video) cc: @mystie711 
https://github.com/MystenLabs/sui/assets/122397493/63dede7a-a0ef-4ec5-80ec-ee2a2d07a131
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted …
=> [wallet-ext] - group / sort accounts list 

.github/workflows/release-notes-monitor.yml
Currently, we are not accounting for sorting by number/version without 0 padding. Adding `-V` to account for it
Before
```
eugene@mac-studio ~/code/sui (eugene/fix_release_notes_tag_lookup) $ git tag | grep -E 'sui_v1(.*)_rel_notes' | sort -r | head -1
sui_v1.9.0_1693613519_rel_notes
```
After
```
eugene@mac-studio ~/code/sui (eugene/fix_release_notes_tag_lookup) $ git tag | grep -E 'sui_v1(.*)_rel_notes' | sort -rV | head -1
sui_v1.10.0_1694185668_rel_notes
```
[Run via the branch](https://github.com/MystenLabs/sui/actions/runs/6123742749)
=> Using version-sort when sorting

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/state_accumulator.rs, crates/sui-genesis-builder/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-types/src/in_memory_storage.rs, crates/sui-types/src/storage.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/suivm/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs
The ParentSync trait has an explicit dependency to tombstones as it also returns the tombstone as the result if it's the latest entry. Depending on this trait will make it impossible to prune tombstones.
Currently only sui-execution v0 still depends on it, and no other places should continue to depend on it.
This PR gets rid of such dependency except in sui-execution v0.
One thing I changed here which requires a close review is in the shared object lock assignment path, where I believe we shouldn't need to use parent sync.
CI
---
=> Stop depending on tombstones

crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-json/src/lib.rs, crates/sui-types/src/execution_status.rs, crates/sui/src/client_commands.rs, doc/src/build/cli-client.md
This PR adds a comment regarding the necessity of providing type arguments to Move calls.
I ran into this issue while testing the examples provided in the example [Defi](https://github.com/MystenLabs/sui/blob/main/sui_programmability/examples/defi/sources/escrow.move) package:
* calling the `create` entry function, via `sui client call`, without instantiating both of its type arguments resulted in
```
Error calling module: Failure {
error: "VMVerificationOrDeserializationError in command 0",
}
```
Adding the required type arguments fixes the issue.
Since this very small PR consists of comments only, I believe no tests are needed.
---
=> [docs] Add comments regarding type argument instantiation

crates/sui/src/client_commands.rs, crates/sui/tests/cli_tests.rs
When requesting a new keypair via `sui client new-address`, display the newly created keypair in a well formatted table. 
---
When requesting a new keypair via `sui client new-address`, display the newly created keypair in a well formatted table. Use `--json` to get a standard JSON output.
=> [cli] improve display for sui client new-address command

apps/wallet/configs/webpack/webpack.config.common.ts
* every time wallet is built using NODE_ENV='development', manifest will use a specific public key to make the extension id be the same across devices/installs
* if we ever want to publish a dev build to chrome store we should make sure we remove this `key` field
* now id for dev should always be `iabmfhchcocfljednlcpgnijajedhecc`
NOTE: after this building the wallet in dev and installing it will create the above id, which is different than any existing one so it will be a fresh install
👀 
---
=> wallet-ext: consistent extension ids across dev builds

apps/wallet/src/background/accounts/zk/ZkAccount.ts, apps/wallet/src/background/accounts/zk/providers.ts, apps/wallet/src/background/accounts/zk/utils.ts, apps/wallet/src/ui/app/components/accounts/ZkLoginButtons.tsx, apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx
* adds twitch in enabled providers
https://github.com/MystenLabs/sui/assets/10210143/f145a0dd-8197-4be3-8a99-bd247f6817f0
https://github.com/MystenLabs/sui/assets/10210143/8a3f6f36-fd7a-4191-b039-79d27cfd004f
* includes a workaround to avoid calling `identity.launchWebAuthFlow` when a silent auth flow can work
* twitch is using html/js redirect instead of response headers and that makes the browser to open a window and then close it right after
* we need this workaround to avoid closing the popup window and also avoid a flickering effect from opening and closing the auth window
* this does a get request to the auth url and extracts the `redirect_url` from the response
without the workaround
https://github.com/MystenLabs/sui/assets/10210143/4d5da125-491f-45d1-a82f-7fb3bac12e3e
with the …
=> wallet-ext: enable zklogin with twitch

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_23.snap
Enabling the reputation based leader election for mainnet . So far it was enabled for any enviornment but mainnet.
---
=> [consensus] enable new reputation based leader election

.changeset/sixty-balloons-run.md, sdk/dapp-kit/src/components/WalletProvider.tsx, sdk/dapp-kit/src/reducers/walletReducer.ts, sdk/dapp-kit/src/utils/walletUtils.ts, sdk/wallet-standard/src/detect.ts, sdk/wallet-standard/src/features/index.ts
In `wallet-standard`, we only enforce that a wallet has `standard:connect` and `standard:events` to function. However, we make a type assertion in `isWalletWithSuiFeatures` that any wallet with these two features + any other features has all Sui features which isn't a safe assumption to make. This leads to type mismatches like the one below - you could register a wallet without `sui:signPersonalMessage` but TypeScript is going to think the wallet automatically has that feature within `wallet-kit`.
To fix this, we can introduce a new `WalletWithRequiredFeatures` type to more accurately reflect what features are available. I didn't change anything in `wallet-kit` since we're working on deprecating that library, but I did make the updates for `dapp-kit` regarding the `currentWallet` and …
=> [dapp-kit][wallet-standard] fix type mismatch in the wallet provider for wallets

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_23.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_24.snap
Enabling the reputation based leader election for mainnet . So far it was enabled for any enviornment but mainnet.
---
=> [consensus] enable reputation based leader election for mainnet

sdk/dapp-kit/src/constants/walletMutationKeys.ts, sdk/dapp-kit/src/errors/walletErrors.ts, sdk/dapp-kit/src/hooks/wallet/useDisconnectWallet.ts, sdk/dapp-kit/src/index.ts, sdk/dapp-kit/src/reducers/walletReducer.ts, sdk/dapp-kit/test/hooks/useDisconnectWallet.test.tsx
This PR adds a new `useDisconnectWallet` mutation hook with tests for disconnecting from an active wallet connection!
Equivalent PR for connecting: https://github.com/MystenLabs/sui/pull/13661
- Automated tests pass
- Manual testing in an example dApp
- CI
---
=> [dapp-kit] add new useDisconnectWallet mutation hook

crates/sui-core/src/authority.rs, crates/sui-genesis-builder/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-swarm-config/src/network_config_builder.rs, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/src/executor.rs, sui-execution/src/latest.rs, sui-execution/src/suivm.rs, sui-execution/src/v0.rs, sui-execution/suivm/sui-adapter/src/execution_engine.rs, sui-execution/suivm/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/execution_engine.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs
Simplify sui-execution API and avoid too much logic in the dispatch functions.
CI
---
=> Simplify sui-execution interface

crates/sui-json-rpc/src/error.rs, crates/sui-sdk/examples/json_rpc_errors.rs, crates/sui-sdk/examples/utils.rs, crates/sui-sdk/src/error.rs, crates/sui-sdk/src/json_rpc_error.rs, crates/sui-sdk/src/lib.rs
Users of our rust sdk should not need to import the jsonrpsee crate just to error match on jsonrpc errors, nor should clients be encouraged to do string matching on the error message.
1. Introduce json_rpc_error::Error, and a conversion from jsonrpsee::Error to json_rpc_error::Error, so we don't make any breaking changes
2. json_rpc_error::Error has some basic api to determine error type for further manual handling
3. It seems like the jsonrpsee crate makes liberal use of error codes in the -32000 to -32099 range, and unfortunately our -32001 transient error code conflicts with their unknown error code. Bumped our transient error code to -32050.
Further improvements:
From here, we can consider providing more detailed classification of errors, if useful. For example, if we receive …
=> [sui-sdk] jsonrpc error response classification and handling

crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/server/data_provider.rs, crates/sui-graphql-rpc/src/server/sui_sdk_data_provider.rs, crates/sui-graphql-rpc/src/types/gas.rs
This PR refactors convert_to_gas_input, convert_to_gas_cost_summary, and convert_to_gas_effects in favor of utilizing the `#[Object]` macro. These convert_to functions are intended to convert struct objects into GraphQL objects, but the issue is that they will always make computations and data fetches for each field, even if the caller did not specify those fields. For example, if I make a query for TransactionBlock for the gasInput field and only specify the gas_price, we nonetheless make the extra conversions for gas_sponsor, gas_budget, and the data fetch for gas_payment. 
Continuing with the example above, in this refactor, the struct definition of the GraphQL object GasInput now has the corresponding "native" fields, and implements From SuiGasData. The impl Object for GasInput block …
=> [graphql][1/n] Refactor gas-related convert_to fns to utilize async-graphql's Object macro

crates/sui-types/src/execution.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/suivm/sui-adapter/src/programmable_transactions/context.rs, sui-execution/suivm/sui-adapter/src/temporary_store.rs, sui-execution/suivm/sui-move-natives/src/object_runtime/mod.rs, sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
This will allow us to record the old owner in effects v2.
CI
---
=> Record owner in loaded runtime objects

crates/sui-graphql-rpc/src/commands.rs, crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs
Implements query depth limiting.
Manual
---
=> [graphql/rpc] limit query depth

crates/sui-config/src/p2p.rs, crates/sui-network/src/state_sync/mod.rs
This enables recovery from a split brain/stall scenario using this feature.
=> Skip verification of pinned checkpoints in state sync

crates/sui-graphql-rpc/schema/draft_schema.graphql
Updates to the schema based on what we now understand to be possible to serve from the data layer:
- Remove `eventField` filtering (generic filtering by the contents of events).
- Mark filtering by event timestamps as a post-MVP enhancement, as it is not useful without compound filtering.
- Add filter for events by checkpoint as another post-MVP enhancement (similar to time-range filtering: bound checkpoints from above and from below).
- Update transaction block checkpoint filtering to match.
- Add a timestamp range based filter to transaction blocks for consistency with event filters (again, as a post-MVP enhancement).
- Add generic compound filters to transaction block and event-based filtering, as a post-MVP enhancement.
:eyes:
=> [GraphQL/Schema] Refine schema to match data layer

crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/server/mod.rs
Mark modules as `pub(crate)` or private where possible, to limit the public interface of the crate.  This is to make it less likely for other crates to depend on it, which should simplify its versioning story (Only one target should depend on this crate, which is the binary for the GraphQL service).
Some modules may need to be re-opened later as more dependencies come, but that's okay -- it's easier to know when to open things up than to know when to close things up.
```
cargo nextest run
cargo run
```
=> [RPC/GraphQL] Lock down exported modules

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/commands.rs, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs
Introduce config for functional groups to enable and disable groups of features in the schema, so that different operators can choose to run the RPC service with different sets of features enabled (for example running public nodes without analytics).
The precise set of functional groups may shift -- the current list is derived from the list in the RFC (#13700).
This PR only introduces the config, and not the logic in the schema to listen to the functional group config.  The config is read from a TOML file whose path is passed as a command-line parameter.  It is stored as data in the schema's context so that it can later be accessed by whatever system limits access to endpoints by flags.
A stub "experiments" section has also been added as a place to keep ad-hoc experimental flags (to gate …
=> [GraphQL/Config] TOML-based config

crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-types/src/storage.rs
Changes the layout of the `object_per_marker_table` layout to not contain the `MarkerKind` in the key, and instead map to a `MarkerValue` which will contain specific data depending on if the object was received, owned-deleted, or shared-deleted.
This table has been and remains unused for now so changing the layout of it should be fine.
=> [storeage] Change `object_per_epoch_marker_table` layout

crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/narwhal_manager/mod.rs, crates/sui-core/src/scoring_decision.rs, crates/sui-core/src/unit_tests/narwhal_manager_tests.rs, crates/sui-node/src/lib.rs, narwhal/executor/src/lib.rs, narwhal/executor/src/subscriber.rs, narwhal/node/src/execution_state.rs, narwhal/node/src/main.rs, narwhal/node/src/primary_node.rs, narwhal/node/tests/node_test.rs, narwhal/test-utils/src/cluster.rs
Refactored consensus handler to pass as value to Narwhal since it's only managed by the subscriber anyways and the certificate processing is sequential. That also allow us to not use any Mutexes for internal state management but rather act on a `&mut self` reference. Also did some clean up so we do use the injected hostname map for metric reporting , but rather rely on the existing injected committee object to derive the same info.
---
=> [refactor] consensus handler

sdk/dapp-kit/src/constants/walletMutationKeys.ts, sdk/dapp-kit/src/errors/walletErrors.ts, sdk/dapp-kit/src/hooks/wallet/useSwitchAccount.ts, sdk/dapp-kit/src/reducers/walletReducer.ts, sdk/dapp-kit/test/hooks/useSwitchAccount.test.tsx
This PR adds a new `useSwitchAccount` mutation hook for switching between different wallet accounts. Not sure if we prefer `useSelectAccount` or `useSwitchAccount` for naming, but I thought saying "I'm using this hook to switch accounts" out loud made more sense than "I'm using this hook to select an account" 😛 .
- Automated tests
- CI
---
=> [dapp-kit] add new useSwitchAccount mutation hook

crates/sui-graphql-rpc/src/context_data/data_provider.rs, crates/sui-graphql-rpc/src/context_data/sui_sdk_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Continuing off https://github.com/MystenLabs/sui/pull/13714. 
It looks like the effects field of TransactionBlock have some heavy overlaps with other top-level fields of TransactionBlock. We already have the data needed to resolve every field on effects: TransactionBlockEffects. In fact, if a caller specifies both tx.effects.epoch and tx.expiration, we make redundant calls for sui_system_state and fetch_protocol_config. It's also a little strange to me that we pass tx_effects to TransactionBlockEffects for status and errors. Wondering if it's worth it right now to modify schema for TransactionBlock and TransactionBlockEffects? We could remove the redundant digest, lift status and errors to top-level, etc.
---
If your changes are not user-facing …
=> [graphql][2/n] Refactor convert_to_transaction_block

crates/sui-graphql-rpc/schema/draft_schema.graphql
A previous update to the schema (#13744) marked filters that could only be used compounded with others (like the checkpoint and time-based filters in `EventFilter`) or required querying/joining over multiple tables in the data layer as a post-MVP enhancement.
This PR identifies more filters that require this feature, and also standardises the offering of such compound filters:
- Adds compound filters for objects.
- Marks `filter` parameters for connection queries that are nested within some other object (like transactions within an epoch, or events within a transaction) as also an enhancement, because the fact that they are nested within another structure implies an initial filter, that the filters from, e.g. `EventFilter` would have to compound with.
:eyes:
=> [GraphQL/Schema] Treat all compound filters as enhancements

narwhal/primary/src/synchronizer.rs
Adding test for the gc logic of the synchronizer State. I've specifically tested the `State` as it is more straightforward to test this directly there instead of the Synchronizer it. self as it would be harder to understand/make it obvious the gc limit.
---
=> [narwhal] hardening synchronizer gc testing

crates/sui-core/src/authority.rs, crates/sui-genesis-builder/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-swarm-config/src/network_config_builder.rs, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/src/executor.rs, sui-execution/src/latest.rs, sui-execution/src/suivm.rs, sui-execution/src/v0.rs, sui-execution/suivm/sui-adapter/src/execution_engine.rs, sui-execution/suivm/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/execution_engine.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs
This simplifies the executor interface, removing the need for the backing store to be an Arc and removes the lifetime from the interface
---
=> executor: simplify interface

apps/wallet/src/ui/app/shared/faucet/useFaucetMutation.ts
before
https://github.com/MystenLabs/sui/assets/10210143/9f0273b7-eff7-4536-8af6-f85f4780bd00
after
https://github.com/MystenLabs/sui/assets/10210143/e2cef14c-3289-485f-a689-f3812b7a0d1c
closes APPS-1628
👀 
---
=> wallet-ext: only show the faucet button when account is unlocked

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-genesis-builder/src/lib.rs, crates/sui-storage/src/indexes.rs, crates/sui-types/src/base_types.rs, crates/sui-types/src/execution.rs, crates/sui-types/src/in_memory_storage.rs, crates/sui-types/src/inner_temporary_store.rs, crates/sui-types/src/transaction.rs, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/suivm/sui-adapter/src/execution_engine.rs, sui-execution/suivm/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/execution_engine.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs
This PR simplifies the fields of InnerTemporaryStore such that it's no longer dependent on the implementation details of effects.
Specifically, it gets rid of all the use of WriteKind and DeleteKind stuff. Instead it only has a map of all written objects.
To access to deleted objects, we could always refer to effects because we always have effects when we have the inner.
CI
---
=> [EffectsV2 1/n] Simplify inner temp store

crates/sui-move-build/src/lib.rs, external-crates/move/move-compiler/src/diagnostics/mod.rs
We would like to present to the developer a place where they could provide feedback on the available linters, with the information about how to report feedback being immediately available whenever the linter warnings are generated
All existing tests must pass plus manually tested that the message gets printed.
---
When linter warnings get generated, information about a place where the feedback on linters can be provided will be printed alongside the warning messages.
=> [move-compiler] Print request for linter feedback if linter warnings present

crates/sui-framework/packages/sui-framework/sources/table_vec.move, crates/sui-framework/packages/sui-framework/tests/table_vec_tests.move, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_25.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_25.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_25.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Added `swap_remove` function to `table_vec.move` since we have a situation to remove an certain element in the `TableVec` and both `table` and `vector` have similar functionality implemented.
New unit tests for `sui::table_vec`.
---
Introduces protocol version 25 which adds `sui::table_vec::swap` and `sui::table_vec::swap_remove` to system packages.  Use these functions to swap two positions in a single `TableVec<T>` or swap an element to the end and remove it in `O(1)` time, analogous to `std::vector::swap` and `std::vector::swap_remove`.
=> [sui-framework] Added swap and swap_remove function to the table_vec.move

sdk/dapp-kit/src/constants/walletMutationKeys.ts, sdk/dapp-kit/src/hooks/wallet/useSignTransactionBlock.ts, sdk/dapp-kit/src/index.ts, sdk/dapp-kit/test/hooks/useSignTransactionBlock.test.tsx
Same as https://github.com/MystenLabs/sui/pull/13720 but for `signTransactionBlock`.
- Automated tests
- CI
---
=> [dapp-kit] add new useSignTransactionBlock mutation hook

crates/sui/src/client_commands.rs, crates/sui/tests/cli_tests.rs
This PR disables the use of the `--test` flag when executing `sui client publish`.
It closes #13679, following discussion in that thread.
I've added a test to `./crates/sui/tests/cli_tests.rs` that verifies the `--test` flag will no longer be accepted with `client publish`, along with an error message explaining why.
---
* Added an error message to Sui CLI when trying to publish a package via `sui client publish`, and the package requires compilation in test mode
=> Disable `--test` flag when publishing package using Sui client

crates/sui-types/src/execution.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/suivm/sui-adapter/src/programmable_transactions/context.rs, sui-execution/suivm/sui-adapter/src/temporary_store.rs, sui-execution/suivm/sui-move-natives/src/object_runtime/mod.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs
In the current implementation, we track the input object metadata at runtime, including object digest. Then in the end, we put that information in objects_modified_at, which we could use to get the old object information in effects v2.
There are two issues with this approach:
1. These information are somewhat redundant to what we already have and record in mutable inputs and loaded child objects. Having another copy is inefficient and leaves space for mistakes.
2. In fact, the object digest in the input object metadata is not guaranteed to be the same as the original input object digest, since we may be smashing gas prior to entering PT. So it's actually incorrect to use that information.
This PR simplifies the modified_at in execution results to just modified_objects as a list of IDs.
CI …
=> [EffectsV2 2/n] Record modified object ids only in execution results

sdk/dapp-kit/src/errors/walletErrors.ts, sdk/dapp-kit/src/hooks/wallet/useConnectWallet.ts, sdk/dapp-kit/test/hooks/useConnectWallet.test.tsx
@Jordan-Mysten brought up a good point during a discussion last week that we shouldn't impose the constraint for people to disconnect a wallet connection before connecting a new wallet since disconnecting is really a facade sort of concept. This PR removes the associated logic, so people can technically connect as many wallets as they please 🔌 
- CI
---
=> [dapp-kit] remove WalletAlreadyConnectedError from useConnectWallet

crates/sui-graphql-rpc/schema/draft_schema.graphql
As per discussion in #13574 -- we may not want to expose effects digest (favouring using transaction digest everywhere). This PR removes:
- `TransactionBlockEffects.digest`
- The ability to find a transaction block by its effects digest (now it can only be found by its transaction digest).
- The ability for execution to return an effects digest (now returns a transaction digest on success).
:eyes:
=> [GraphQL/Schema] Remove reference to effects digest

sdk/dapp-kit/src/constants/walletMutationKeys.ts, sdk/dapp-kit/src/hooks/wallet/useSignAndExecuteTransactionBlock.ts, sdk/dapp-kit/src/hooks/wallet/useSignPersonalMessage.ts, sdk/dapp-kit/src/hooks/wallet/useSignTransactionBlock.ts, sdk/dapp-kit/src/index.ts, sdk/dapp-kit/test/hooks/useSignAndExecuteTransactionBlock.test.tsx
This PR adds the final Sui feature mutation hook for signing and executing a transaction block. This is similar to https://github.com/MystenLabs/sui/pull/13741 and https://github.com/MystenLabs/sui/pull/13720.
- Automated tests
- CI
---
=> [dapp-kit] add new useSignAndExecuteTransactionBlock hook 

scripts/execution_layer.py
I wanted to create a feature branch vm-rework, but the script today will create Rust files and refer to the feature as "vm-rework", which breaks Rust convention. This PR extends the script so that we can still reference feature cuts w/ dashes, but will create Rust files and references with "vm_rework". Verified this works with ./scripts/execution_layer.py cut vm-rework, and then rebasing with ./scripts/execution_layer.py rebase latest
Verified this works with ./scripts/execution_layer.py cut vm-rework, and then rebasing with ./scripts/execution_layer.py rebase latest
--- …
=> Extend execution_layer.py to support dashes

apps/wallet/src/ui/app/hooks/useExplorerLink.ts
removes the following warning
👀 
---
=> wallet-ext: fix redux selector warning

apps/wallet/src/ui/app/components/DAppInfoCard.tsx, apps/wallet/src/ui/app/components/accounts/AccountItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountListItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountMultiSelectItem.tsx, apps/wallet/src/ui/app/components/user-approve-container/index.tsx, apps/wallet/src/ui/app/pages/approval-request/SignMessageRequest.tsx, apps/wallet/src/ui/app/pages/approval-request/transaction-request/index.tsx
* show unlock button instead of allowing approving when selected account is locked
* show new account UI for the selected account and allow unlocking it
* fix dapp info overflowing
* fix spacing in Sign Message screen
https://github.com/MystenLabs/sui/assets/10210143/c9c1449c-1cfa-4b6c-93d7-c8ebcd78e863
https://github.com/MystenLabs/sui/assets/10210143/cd4eae1e-f53b-4007-bab5-0e2798712da2
part of [APPS-1700](https://mysten.atlassian.net/browse/APPS-1700)
closes [APPS-1499](https://mysten.atlassian.net/browse/APPS-1499)
👀 
---
=> wallet-ext: update dapp approval pages for locked accounts

apps/wallet/src/background/accounts/index.ts, apps/wallet/src/shared/messaging/messages/payloads/MethodPayload.ts, apps/wallet/src/ui/app/background-client/index.ts, apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx, apps/wallet/src/ui/app/pages/accounts/manage/ManageAccountsPage.tsx
* allow removing accounts in manage page
* removing all accounts of an account source will remove the account source as well
* removed mnemonic accounts will be added back by creating a new account for the account source (deriving next account will fill any gaps)
https://github.com/MystenLabs/sui/assets/10210143/5ac1440f-e1be-4426-9c53-b48d8ce2d8d3
https://github.com/MystenLabs/sui/assets/10210143/eb065db8-94e2-42f6-8969-24532fbcf593
closes APPS-1615
👀 
---
=> wallet-ext: remove accounts

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_25.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
follow up on https://github.com/MystenLabs/sui/pull/13822
---
Upgrade protocol version to 25.
=> chore: update protocol version to 25

external-crates/move/move-vm/runtime/src/lib.rs, external-crates/move/move-vm/runtime/src/move_vm.rs, external-crates/move/move-vm/runtime/src/runtime.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/linkage_view.rs, sui-execution/latest/sui-adapter/src/type_layout_resolver.rs
Move suivm to latest. Suivm is getting in the way of a bunch of work happening in the execution layer.
This is also showing the issues related to branches that are live for long. It is at times inevitable but we need to be careful about what people review and how to go back to latest.
Hopefully the work to make latest the working branch will make this less of a problem. We'll see
Existing tests
---
=> Move suivm to latest

Cargo.lock, crates/sui-indexer/Cargo.toml, crates/sui-indexer/src/handlers/mod.rs, crates/sui-indexer/src/handlers/tx_processor.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/store/module_resolver_v2.rs
This PR adds a few things:
(Note that because of the way I'm splitting PRs, some structures/functions are not immediately in use, but i hope they more or less make sense).
1. `InMemPackageCache`: an in-mem cache for packages. Because we batch process checkpoints, it's possible that when we need a module it's not yet persisted in db. And here's where we can find it.
2. `InMemObjectCache`: an in-mem cache for objects for processing like object changes or balance changes. Its lifetime is per checkpoint.
3. `TxChangesProcessor`: a helper that leverages `InMemObjectCache` and implements `ObjectProvider` for dynamic fields processing and others.
4. `InterimModuleResolver` consists of a backup ModuleResolver (e.g. IndexerStoreModuleResolver) and an in-mem package cache.
Stack:
1. …
=> [Indexer-v2 4/n] add caches for indexing

crates/sui-indexer/src/handlers/mod.rs, crates/sui-indexer/src/store/indexer_store_v2.rs, crates/sui-indexer/src/store/mod.rs
This PR adds `IndexerStoreV2` trait and a few helper structs. `IndexerStoreV2` only contains the necessary functions for now, and will be immediately used in next PR in the stack.
Stack:
---
=> [Indexer-v2 5/n] add indexer_store_v2 trait and DataToCommit structs

crates/sui/src/client_commands.rs
This PR updates the way the `sui client envs` command is displayed as a well formatted table.
---
This PR updates the way the `sui client envs` command is displayed as a well formatted table. Use `--json` to get a standard JSON output.
=> [cli] display sui client envs as a table

apps/wallet/src/ui/app/components/DAppInfoCard.tsx, apps/wallet/src/ui/app/components/accounts/AccountItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountListItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountMultiSelectItem.tsx, apps/wallet/src/ui/app/pages/site-connect/index.tsx
* stop auto selecting active account when locked
* remove copy and explorer icons from approve connection and dapp status
* show message when all accounts are locked
before
https://github.com/MystenLabs/sui/assets/10210143/6c4c32a0-02b9-4af5-a64b-b8918b0c59ef
https://github.com/MystenLabs/sui/assets/10210143/ecfa39ae-3cd6-4582-956a-d8e12084c460
https://github.com/MystenLabs/sui/assets/10210143/32fcd73c-60f7-49d2-9cd4-39801c24f303
after
https://github.com/MystenLabs/sui/assets/10210143/48e213b2-2cbb-4c89-82cc-f051bd86f59d
https://github.com/MystenLabs/sui/assets/10210143/f23a2d45-2a7e-4508-bc35-7f1c79b5d966
closes [APPS-1700](https://mysten.atlassian.net/browse/APPS-1700)
closes [APPS-1698](https://mysten.atlassian.net/browse/APPS-1698)
---
If …
=> wallet-ext: connect to dapp ui polish and fixes

apps/wallet/src/ui/app/components/accounts/AccountItem.tsx
* do not select the account when user clicks on the explorer link
before
https://github.com/MystenLabs/sui/assets/10210143/aafb9a35-7ffd-4336-b8d0-837eddb0188c
after
https://github.com/MystenLabs/sui/assets/10210143/8e31814a-93a5-4b92-b5fe-c10a8892210d
closes [APPS-1690](https://mysten.atlassian.net/browse/APPS-1690)
---
=> wallet-ext: fix explorer link of accounts

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs
Limit the number of nodes in graphql query
Unit
---
=> [graphql/rpc] limit number of query nodes

external-crates/move/move-compiler/src/expansion/ast.rs, external-crates/move/move-compiler/src/expansion/mod.rs, external-crates/move/move-compiler/src/expansion/translate.rs, external-crates/move/move-compiler/src/hlir/translate.rs, external-crates/move/move-compiler/src/naming/ast.rs, external-crates/move/move-compiler/src/naming/translate.rs, external-crates/move/move-compiler/src/typing/ast.rs, external-crates/move/move-compiler/src/typing/dependency_ordering.rs, external-crates/move/move-compiler/src/typing/mod.rs, external-crates/move/move-compiler/src/typing/translate.rs, external-crates/move/move-compiler/tests/move_check/dependencies/use_cycle_2.exp, external-crates/move/move-compiler/tests/move_check/dependencies/use_friend_direct.exp, external-crates/move/move-compiler/tests/move_check/dependencies/use_friend_transitive_by_friend.exp, external-crates/move/move-compiler/tests/move_check/dependencies/use_friend_transitive_by_use.exp, external-crates/move/move-model/src/lib.rs
- With receiver syntax, we will not be able to determine immediate dependencies until after typing
- As such, module ordering must be done after typing. The logic remains the same
Internal compiler change (updated some location information for tests)
---
=> [move][receiver syntax][1/n] Move module dependency ordering to after typing

apps/wallet/src/background/accounts/Account.ts, apps/wallet/src/background/accounts/ImportedAccount.ts, apps/wallet/src/background/accounts/LedgerAccount.ts, apps/wallet/src/background/accounts/MnemonicAccount.ts, apps/wallet/src/background/accounts/QredoAccount.ts, apps/wallet/src/background/accounts/index.ts, apps/wallet/src/ui/app/hooks/useCreateAccountMutation.ts, apps/wallet/src/ui/app/pages/accounts/manage/AccountGroup.tsx, apps/wallet/src/ui/app/pages/accounts/manage/ManageAccountsPage.tsx
https://github.com/MystenLabs/sui/assets/10210143/a5f00e51-3912-46d2-8b49-37503fbae4b8
closes [APPS-1701](https://mysten.atlassian.net/browse/APPS-1701)
👀 
---
=> wallet-ext: mnemonic accounts skip pass when account source is unlocked

crates/sui-graphql-rpc/schema/draft_schema.graphql
The underlying data schema supports multiple senders, which a transaction can have today if it is sponsored.  This feature may also be generalised in future, to allow for multiple accounts to sign for access to their objects in a given transaction.
:eyes:
=> [GraphQL][EASY] Update schema to account for multiple senders.

crates/sui-graphql-rpc/schema/draft_schema.graphql
- Rename it to `transactionBlockConnection` from just `transactionConnection`.
- Add a `TransactionBlockFilter` parameter as a post-MVP enhancement.
:eyes:
Also double check that no other transaction block related connections slipped through the net previously.
=> [GraphQL/Schema] Standardise Checkpoint transaction block connection

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/extensions/limits_info.rs, crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/server/simple_server.rs
Extension which shows the query limits and usages
Coming soon
---
=> [graphql/rpc] show query limits and usage

Cargo.lock, crates/sui-framework-snapshot/src/lib.rs, crates/sui-genesis-builder/Cargo.toml, crates/sui-genesis-builder/src/lib.rs
Previously we would always start genesis with the current set of framework modules. This causes issues in the compatibility tests if the current version of the framework is not backwards compatible with the old version (e.g., by adding a new type in the new version of the framework). 
This updates the genesis creation to now use the correct framework snapshot for all protocol 
versions, defaulting to the current framework if a snapshot for the given protocol version is not found. 
This also updates framework snapshots to be ordered based on the order in which they need to be published.
Added a type to the framework locally, and made sure the `test_upgrade_compatibility` test passes with these changes.
=> [sui-genesis-builder] Start genesis with correct framework for protocol version

sdk/bcs/src/bcs-type.ts, sdk/bcs/src/bcs.ts, sdk/bcs/src/index.ts, sdk/bcs/src/legacy-registry.ts, sdk/bcs/src/types.ts, sdk/bcs/tests/builder.test.ts
This PR adds all the new bcs builder methods, it is not tageting `main`, and changes for the typescript SDK and other packages will come in a separate PR. 
---
=> [bcs] Add new bcs builder methods

crates/sui-graphql-rpc/schema/draft_schema.graphql
Rather than just return a digest on success, execution should return the full effects.  This is so that people who want to avoid including indexing in their transaction critical path can maintain object versions locally and use that to form subsequent transactions.
This change requires making `ID` a nullable field on `TransactionBlock` because a transaction block that is part of a `TransactionBlockEffect` that was returned from execution will not have an `ID` until it has been put in a checkpoint which has subsequently been indexed.
:eyes:
=> [GraphQL/Schema] ExecutionResults expose full effects

Cargo.lock, Cargo.toml
Detected from cargo-deny
2023-09-21T16:26:16.0342685Z     [0m[34m=[0m Announcement: https://github.com/quinn-rs/quinn/pull/1667
2023-09-21T16:26:16.0343117Z     [0m[34m=[0m Solution: Upgrade to ^0.9.5 OR >=0.10.5
pointing to https://github.com/quinn-rs/quinn/pull/1667 with solution to update to 10.5 or above
---
=> fix cargo-deny for quinn-proto

Cargo.lock, Cargo.toml, crates/simulacrum/Cargo.toml, crates/simulacrum/src/checkpoint_builder.rs, crates/simulacrum/src/epoch_state.rs, crates/simulacrum/src/lib.rs, crates/simulacrum/src/store.rs, crates/sui-genesis-builder/src/lib.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-3.snap, crates/sui-types/src/base_types.rs, crates/sui-types/src/clock.rs, crates/sui-types/src/gas.rs, crates/sui-types/src/in_memory_storage.rs, crates/sui-types/src/messages_checkpoint.rs, crates/sui-types/src/object.rs
This patch adds a new crate `simulacrum` which contains tooling for
creating an instance of a Sui Blockchain that is fully simulated. In
other words it is a chain that only advances state when explicitly
cranked. The intent of this is to enable producing fully deterministic
chain states for testing of downstream applications or for smart
contract developers that want a cheap, local development environment
without needing to spin up full consensus.
---
=> simulacrum: introduce a tool for simulating Sui chain state

crates/sui-protocol-config/src/lib.rs, crates/sui-types/src/gas_model/gas_predicates.rs, sui-execution/latest/sui-adapter/src/gas_charger.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
as titled we were too aggressive in pushing the change not under protocol version
Existing tests
---
Package upgrade is now charging for the bytes being published. That is more in line with our charging model.
=> Protect changes in gas charging

crates/sui-indexer/migrations_v2/2023-08-19-044052_epochs/up.sql, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/handlers/mod.rs, crates/sui-indexer/src/handlers/tx_processor.rs, crates/sui-indexer/src/models_v2/epoch.rs, crates/sui-indexer/src/schema_v2.rs, crates/sui-indexer/src/store/indexer_store_v2.rs, crates/sui-indexer/src/store/mod.rs, crates/sui-indexer/src/types_v2.rs, crates/sui-rest-api/src/checkpoints.rs, crates/sui-types/src/event.rs
This PR has the following major things:
1. implement `CheckpointHandlerV2`, a `Hanlder` that indices data passed by fetcher.
2. implement `committer`. `Committer` consumes indexed data from handler then commits to the db store.
It also changes `epoch_total_transactions` column in Epoch table to nullable since it's only accessible at the end of an epoch.
Stack:
10. …
=> [Indexer-v2 6/n] add Checkpoint Handler v2 and committer

crates/sui-move-build/src/lib.rs, crates/sui/tests/cli_tests.rs, crates/sui/tests/data/linter/Move.toml, crates/sui/tests/data/linter/sources/suppression_stats.move, external-crates/move/move-compiler/src/diagnostics/mod.rs, external-crates/move/move-compiler/src/expansion/translate.rs, external-crates/move/move-compiler/src/shared/mod.rs, external-crates/move/tools/move-package/src/resolution/resolution_graph.rs
This PR adds basic stats about suppressed linters in user code.
All existing tests must pass plus manually tested that the correct stats get printed.
---
When linter warnings in user code are suppressed, basic statistics about suppressed warnings (number of suppresed warnings and number of suppressed warning categories) will be printed.
=> [move-compiler] Added basic stats about suppressed linters

crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/models_v2/epoch.rs, crates/sui-indexer/src/store/indexer_store_v2.rs, crates/sui-indexer/src/store/mod.rs, crates/sui-indexer/src/store/pg_indexer_store_v2.rs
This PR adds `PGIndexerStoreV2`, an implementor of `IndexerStoreV2`. 
Stack:
10. https://github.com/MystenLabs/sui/pull/13892
--- …
=> [Indexer-v2 7/n] add PGIndexerStoreV2

crates/sui-indexer/src/framework/mod.rs, crates/sui-indexer/src/indexer_v2.rs, crates/sui-indexer/src/lib.rs
This PR adds `IndexerV2`, the new indexer server (writer/reader)
Stack:
10. https://github.com/MystenLabs/sui/pull/13892
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted …
=> [Indexer-v2 8/n] add the indexer server `IndexerV2`

crates/sui-indexer/benches/indexer_benchmark.rs, crates/sui-indexer/src/lib.rs, crates/sui-indexer/src/main.rs, crates/sui-indexer/src/test_utils.rs, crates/sui-indexer/src/utils.rs
This is the final PR that completes the basic indexer writer skeleton. It adds the option to use v2 when the binary starts.
Stack:
10. https://github.com/MystenLabs/sui/pull/13892
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what …
=> [indexer-v2 9/n] wire things up - allow to use indexer v2 in startup

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/extensions/feature_gate.rs, crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/server/version.rs
Adds an extension to intercept field resolution to check whether the field being queried belongs to a disabled functional group.  If so, an error is produced instead of allowing the query through.
Changes the functional group enum itself:
- Removing "Packages" (there are no package-specific queries).
- Renaing "NameServer" to "NameService" for consistency.
Currently, disabled fields are not removed from the schema during introspection. This has been left as a follow-up (TODO in the codebase).
Also, the error from the extension does not supply a source location in the query because this is not supplied to the extension by `async-graphql`.  Fixing this requires an upstream change, so this has also been left as a follow-up.
New tests for extension:
```
``` …
=> [GraphQL/FunctionalGroups] Configuration disables queries

crates/sui-core/src/authority.rs, crates/sui-e2e-tests/tests/move_test_code/sources/tto1.move, crates/sui-e2e-tests/tests/transfer_to_object_tests.rs, crates/sui-protocol-config/src/lib.rs
All elements of the `object_per_epoch_marker` table can be pruned at epoch boundaries, so this adds this in to the reconfiguration step that transitions between each epoch. I believe the way I have it here is the correct way, but I'm less familiar with this so please let me know if there's a better way to do this.
Added e2e tests with reconfiguration enabled, and manually checked to make sure any entries were cleared out at epoch boundaries.
=> [2/n][transfer-to-object] Add pruning of object marker table at epoch boundaries

crates/sui-core/src/authority.rs, crates/sui-e2e-tests/tests/move_test_code/sources/tto1.move, crates/sui-e2e-tests/tests/transfer_to_object_tests.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs
This adds support for receiving transaction argument types to json-rpc
Tested by PRs above this.
---
Release notes included in base PR.
=> [1/n][tto-json-rpc] Plumb receiving object support out into json-rpc

crates/sui-analytics-indexer/src/csv_writer.rs
Some of the fields contain `,` which makes snowflake snowpipe fail parsing file parsing(rightly so). So switching to a different delimiter will likely fix the issue here. One such field is:
`"0x2::dynamic_field::Field<u64, 0x3::sui_system_state_inner::SuiSystemStateInnerV2>"`
=> Switch to using pipe as delimiter in csv writer for analytics

crates/sui/src/client_commands.rs
This PR displays the output of `sui client gas [address]` as a well formatted table. If there are more than 10 coins, it will add an extra header and footer with the number of coins. 
*Found an address with lots of coins on devnet*
---
This PR changes the output of `sui client gas [address]` to a well-formatted table. This breaks the previous JSON format, when using `--json` flag, due to changing the `GasCoin` output type to a simpler one. For example, you might have previously accessed the gas coin ID using `id.id` and the value using `balance.value` from the …
=> [cli] format output of `sui client gas` to a well formatted table

crates/sui/src/client_commands.rs
This PR improves the way we show the output of the `sui client objects` command by using a well formatted table. For the `objectType` field, it mimics the `type` field from the `sui explorer`.  Use `--json` for a more verbose & standard JSON output. 
Used the command, see screenshot (overlayed a black square on the addresses, version, digest).
---
This PR improves the way we show the output of the `sui client objects` command by using a well formatted table. Use `--json` for a more verbose & standard JSON output.
=> [cli] change the output format of `sui client objects` to a well formatted table

crates/sui-analytics-indexer/src/analytics_handler.rs, crates/sui-analytics-indexer/src/csv_writer.rs, crates/sui-analytics-indexer/src/lib.rs
When writing to a bucket which is used for snowpipe ingestion, we need to randomize the file names. This is because if for some reason we want to re-run the data pipeline, we will be generating the same file names in the following runs and writing to the bucket and replacing existing files. But snowpipe today would not pick up modified files. 
Existing tests, running locally
=> Add file name random suffix

Cargo.lock, external-crates/move/Cargo.lock, external-crates/move/tools/move-disassembler/Cargo.toml, external-crates/move/tools/move-disassembler/src/disassembler.rs
Tries to determine if a constant in the constant pool can be interpreted as a utf8 string. If it can it displays it as such, and adds a comment saying it's interpreted the data that way.
Tested locally: 
```rust
module 0x1::M {
const X: vector<u8> = b"hello world";
public fun use_X(): vector<u8> { X }
}
```
```rust
$ move disassemble --name M
// Move bytecode v6
module 1.M {
public use_X(): vector<u8> {
B0:
0: LdConst[0](Vector(U8): 0b68656c..)
1: Ret
}
Constants [
0 => vector<u8>: "hello world" // interpreted as UTF8 string
]
}
```
---
Updated display of constants in …
=> [move-diassembler][small] Display strings in disassembler

apps/wallet/src/ui/app/components/accounts/ProtectAccountForm.tsx, apps/wallet/src/ui/app/shared/page-main-layout/PageMainLayout.tsx
* accept ToS checkbox only link clickable
https://github.com/MystenLabs/sui/assets/10210143/6b703b9a-a4b5-44d3-8282-71c5ef9bc7ca
* add shadow for the main content container
| -- | -- |
| ![image (1)](https://github.com/MystenLabs/sui/assets/10210143/5491aeed-452c-4882-9857-363c621d32b1) | <img width="384" alt="Screenshot 2023-09-25 at 19 27 33" src="https://github.com/MystenLabs/sui/assets/10210143/e317959e-e1c3-47f8-9cec-662d28152b00"> |
closes [APPS-1749](https://mysten.atlassian.net/browse/APPS-1749)
--- …
=> wallet-ext: small ui fixes

apps/wallet/src/ui/app/ApiProvider.ts, apps/wallet/src/ui/app/hooks/useSigner.ts, apps/wallet/src/ui/app/redux/slices/app/index.ts, apps/wallet/src/ui/app/redux/store/thunk-extras.ts, apps/wallet/src/ui/index.tsx, pnpm-lock.yaml
* seems that the change in order of imports broke the wallet
* removing ApiProvider from thunks fixes it
---
=> wallet-ext: fix wallet ApiProvider error

crates/sui-faucet/src/main.rs
Added params to GET call to follow API schema/ patterns
Local Testing: 
---
=> [faucet] adding get to faucet with params

apps/core/tailwind.config.ts, apps/wallet/src/background/accounts/index.ts, apps/wallet/src/background/accounts/zk/ZkAccount.ts, apps/wallet/src/background/accounts/zk/providers.ts, apps/wallet/src/shared/messaging/messages/payloads/MethodPayload.ts, apps/wallet/src/ui/app/background-client/index.ts, apps/wallet/src/ui/app/components/accounts/ZkLoginAccountWaringModal.tsx, apps/wallet/src/ui/app/shared/Dialog.tsx, apps/wallet/src/ui/index.tsx
for every zkLogin account show a modal to the user to enable 2fa
https://github.com/MystenLabs/sui/assets/10210143/d1b0f165-c9b6-4b30-9d6b-26d43d924906
closes [APPS-1746](https://mysten.atlassian.net/browse/APPS-1746)
---
=> wallet-ext: add zkLogin 2fa modal

crates/sui-replay/src/data_fetcher.rs, crates/sui-replay/src/replay.rs
End of epoch logic changed in testnet due to this PR https://github.com/MystenLabs/sui/pull/13576
Replay logic has been changed to account for this.
Will add more unit tests to prevent such in future
Manual
---
=> [replay] fix end of epoch change tx

Cargo.lock, crates/sui-benchmark/Cargo.toml, crates/sui-benchmark/tests/simtest.rs, crates/sui-config/src/node.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/signature_verifier.rs, crates/sui-e2e-tests/Cargo.toml, crates/sui-e2e-tests/tests/zklogin_tests.rs, crates/sui-framework/packages/sui-framework/sources/authenticator_state.move, crates/sui-framework/packages/sui-framework/tests/authenticator_state_tests.move, crates/sui-node/src/lib.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui-swarm/src/memory/swarm.rs, crates/test-cluster/Cargo.toml, crates/test-cluster/src/lib.rs
Tests for handling duplicated / conflicting JWKs.
These cases are unlikely to happen in practice, as oauth providers will almost certainly remain well-behaved. Nevertheless, we want to continue behaving correctly even with pathological inputs.
=> Tests for pathologcial jwk cases

apps/explorer/package.json, pnpm-lock.yaml
I don't know how this passed CI, but I forgot to add `@vanilla-extract/vite-plugin` as a dev dependency to Sui Explorer which is used for bundling the CSS from `dapp-kit`. This was the original PR: https://github.com/MystenLabs/sui/pull/13845
- No more local type error in `vite.config.ts`
---
=> [explorer] add missing dependency from previous PR that I accidentally forgot about

crates/sui-graphql-rpc/schema/draft_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Expose the limits and enabled features that the service was configured with under its own GraphQL API.
Now that the limits are exposed over GraphQL as numbers, their types have been changed from `usize` to `u32` to guarantee they won't lose precision when shared in the API (this should still be more than big enough to hold any reasonable limit).
Tested with GraphiQL
=> [GraphQL] API for exposing ServiceConfig

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/schema/draft_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/extensions/feature_gate.rs, crates/sui-graphql-rpc/src/extensions/limits_info.rs, crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/server/version.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Add a header -- `X-Sui-RPC-Show-Usage` -- to control whether to display a query's usage of limits.  Also only show the usage, and not the limits themselves, now that the limits are exposed via an explicit GraphQL API.
Tested on GraphiQL
=> [GraphQL/Limits] Gate showing limits behind header

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/types/sui_address.rs
Implement `FromStr` and `From<AccountAddress>` for `SuiAddress`, for use in implementing the `MoveValue` type.
This also simplifies many of the tests, which can now be written in terms of `FromStr` rather than via the `InputType`/`ScalarType` interface.
Also fixes a small bug in the error response when failing to parse an address because of an invalid hex code -- previously the implementation forwarded the error directly from the `hex` crate, but this results in an index that is off-by-two, because we stripped the leading "0x" from the string before we passed it to `hex::decode`.
```
sui-graphql-rpc$ cargo nextest run -- sui_address
```
=> [GraphQL] Factor out SuiAddress parsing

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/schema/draft_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/extensions/feature_gate.rs, crates/sui-graphql-rpc/src/extensions/limits_info.rs, crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/server/version.rs, crates/sui-graphql-rpc/src/types/big_int.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Generate `From<uint>` implementations for `BigInt` for each of the unsigned integer types.  This is necessary to support the representing Move Values which are stored in a primitive form, and need to be converted to a `BigInt`.
Also makes `BigInt` serializable, with a transparent representation, for use within the `MoveValue` type.
Tests have been simplified to be written in terms of `BigInt`'s `FromStr` implementation, which allows us to avoid having to test both the `InputType` and `ScalarType` paths.
Additional tests have been added for conversion from primitive types.
```
sui-graphql-rpc$ cargo nextest run -- big_int
```
=> [GraphQL] BigInt from primitive integer types

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/schema/draft_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/extensions/feature_gate.rs, crates/sui-graphql-rpc/src/extensions/limits_info.rs, crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/server/version.rs, crates/sui-graphql-rpc/src/types/base64.rs, crates/sui-graphql-rpc/src/types/big_int.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Adds a new GraphQL object type: `MoveValue` and a new scalar type to represent structured move value contents: `MoveData`.
This PR proposes that `MoveData` should be a scalar rather than a GraphQL (output) type because of its recursive nature:  It would be difficult/impossible to selectively query into its nested structure.
This type and scalar are not currently hooked into the schema, because to do so requires implementing a module resolver that can be used to generate a type layout for any given type, but unit tests have been added for the value representation:
```
sui-graphql-rpc$ cargo nextest run -- move_value
```
=> [GraphQL] Support for MoveValue

sdk/docs/pages/kiosk/_meta.json, sdk/docs/pages/kiosk/from-v1.mdx
Remove `V1` and `V2` references and use npm versioning instead.
---
=> Change version naming on docs

doc/src/build/zk_login.md
Changed 2 lines in the zkLogin docs example.
- Show the construction of sui client
- epoch is returned as a string and maxEpoch is used as number so the epoch is converted to a number
I tested that code is working
---
=> Fix minor discrepancy in the zkLogin docs

crates/sui-core/benches/verified_cert_cache_bench.rs, crates/sui-core/src/signature_verifier.rs, crates/sui-types/src/digests.rs, crates/sui-types/src/message_envelope.rs, crates/sui-types/src/multisig.rs, crates/sui-types/src/multisig_legacy.rs, crates/sui-types/src/signature.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/zk_login_authenticator.rs
add `verify_uncached_checks` to AuthenticatedMessage. this iterates through all GenericSignatures in SenderSignedData and perform `verify_uncached_checks` for (this returns empty ok for all signature schemes except zklogin signature, which calls `verify_zklogin_inputs` that contains the expensive zkproof verification)
---
=> zklogin: add LRU for zklogin inputs verify

crates/sui-graphql-rpc/schema/draft_target_schema.graphql
Cleanup types which fail validation
`TransactionBlockID` was not defined
`ProtocolConfig` should be `ProtocolConfigs`
Manual
---
=> [graphql/rpc] easy/chore: fix types

external-crates/move/move-compiler/src/editions/mod.rs, external-crates/move/move-compiler/src/parser/syntax.rs, external-crates/move/move-compiler/src/shared/mod.rs, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_infix_and_postfix.exp, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_infix_and_postfix.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_infix_and_postfix_native_struct.exp, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_infix_and_postfix_native_struct.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_infix_postfix_no_fields.exp, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_infix_postfix_no_fields.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_infix_postfix_no_fields_with_comma_sep.exp, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_infix_postfix_no_fields_with_comma_sep.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_missing_commas.exp, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_missing_commas.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_missing_semi_multiple_structs.exp, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_missing_semi_multiple_structs.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_no_abilities_no_semi.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_no_abilities_with_semi.exp, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_no_abilities_with_semi.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_no_fields.exp, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_no_fields.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_no_semi.move, external-crates/move/move-compiler/tests/move_2024/parser/ability_modifier_postfix_with_semi.move, external-crates/move/move-compiler/tests/move_2024/parser/struct_public.exp, external-crates/move/move-compiler/tests/move_2024/parser/struct_public.move, external-crates/move/move-compiler/tests/move_2024/struct_invalid_visibility_progress_inside.exp, external-crates/move/move-compiler/tests/move_2024/struct_invalid_visibility_progress_inside.move, external-crates/move/move-compiler/tests/move_check/parser/struct_public.exp, external-crates/move/move-compiler/tests/move_check_testsuite.rs, external-crates/move/move-compiler/transactional-tests/tests/dependencies/public_package.move, external-crates/move/move-compiler/transactional-tests/tests/dependencies/public_package_different_packages.move
Add support for `public struct` declarations in the Move 2024 edition.
To my knowledge this is the first backwards incompatible change, so we need to split off a separate version of the move-stdlib that tracks the new 2024 edition as well. 
The bottom commit of this PR does this, and also refactors the test runner so we aren't passing so many fields all the time in the test runner. 
Added additional tests.
---
Adds initial `public struct` type visibility support to Move 2024.alpha. When using the Move 2024.alpha edition you will be required to write `public` in front …
=> [move-compiler] Add public struct type support to the parser

Cargo.lock, Cargo.toml, crates/sui/Cargo.toml, crates/sui/src/keytool.rs, crates/sui/src/zklogin_commands_util.rs, crates/workspace-hack/Cargo.toml
Add a way to verify zkLogin signature based on the provider and its latest JWK. 
---
=> cli: add a cli to verify a zkLogin signature

doc/src/build/connect-sui-network.md
Both links should point to anchor text "Connect to a custom RPC endpoint" rather than "Connect to custom RPC endpoint".
---
=> Correct anchor link in connect-sui-network.md

crates/sui-core/src/authority_aggregator.rs
In the case where a tx is already finalized with a different user sig, we only need f+1 errors to confirm. 
---
use validity threshold to capture determine TxAlreadyFinalizedWithDifferentUserSignatures
=> use validity threshold to determine TxAlreadyFinalizedWithDifferentUserSignatures

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs, crates/sui-graphql-rpc/src/server/simple_server.rs
Current limit checking logic in async-graphql library does not terminate early if limits are reached. This is wasteful as it allows other validations and checks to go through.
Created an upstream [issue](https://github.com/async-graphql/async-graphql/issues/1383) to support this but in meantime we can run an extension early which approximates the desired behavior.
In future we can add limits for other query components in this extension
Todo: reconcile this logic with the remaining query logic and extensions
Manual
Unit TBD
---
=> [graphql/rpc] Impl custom query limiter for early termination

crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/test_authority_builder.rs
There is no cfg release. So the current macro guard doesn't actually work, removing it.
Reuse the existing function instead of iterating all objects.
Rename them for better clarity
CI
---
=> Nit cleanup in bulk object insert

crates/sui-analytics-indexer/src/analytics_handler.rs, crates/sui-indexer/src/framework/interface.rs, crates/sui-indexer/src/framework/runner.rs, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-indexer/src/handlers/tx_processor.rs, crates/sui-indexer/src/store/module_resolver_v2.rs, crates/sui-indexer/src/types_v2.rs
Experiment results show that sometimes indexing could be the bottleneck. This PR changes the Handler's interface, to process `Vec<CheckpointData>` so they can be handled in parallel. Also break down `fn index_checkpoint_epoch` as it's too lengthy.
---
This PR changes the Handler's interface, to process Vec<CheckpointData> so they can be handled in parallel. Also break down fn index_checkpoint_epoch as it's too lengthy.
=> [indexer-writer] send multiple checkpoints to handler to process in parallel

pnpm-lock.yaml, sdk/dapp-kit/package.json, sdk/dapp-kit/src/components/AccountDropdownMenu.tsx, sdk/dapp-kit/src/components/connect-modal/ConnectModal.css.ts, sdk/dapp-kit/src/components/connect-modal/ConnectModal.tsx, sdk/dapp-kit/src/components/styling/StyleMarker.css.ts, sdk/dapp-kit/src/components/styling/StyleMarker.tsx, sdk/dapp-kit/src/constants/styleDataAttribute.ts
This PR adds locally scoped CSS resets to our `dapp-kit` library which aims to be as minimal / unobtrusive as possible. 
There really isn't a great industry solution to this as a web application can always override library styling. To explain the options I considered here:
1.  ❌ Not shipping any CSS reset and leaving it purely to the consumer (not everyone uses CSS resets)
2. ❌  Using a globally scoped CSS reset (this is bad as library styling should never affect broader application styling)
3. [✅] Using locally scoped CSS resets to only reset the styling in our library with sensible defaults
-  [❌] Creating a `reset.css.ts` file with reset styles that have to be manually applied to every element
- [❌] Doing the above but creating a generic `Box` type component to apply resets (I really …
=> [dapp-kit] provide locally scoped CSS resets for our UI components

.changeset/nice-dragons-warn.md, sdk/dapp-kit/src/components/WalletProvider.tsx, sdk/dapp-kit/test/components/WalletProvider.test.tsx
As the title says ^
Before:
After:
---
=> [dapp-kit] require sui:signTransactionBlock by default so only Sui-specific wallets show

crates/sui-types/src/effects/mod.rs, crates/sui-types/src/effects/object_change.rs, crates/sui-types/src/execution.rs, crates/sui-types/src/sui_system_state/mod.rs, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/latest/sui-adapter/src/gas_charger.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/vm-rework/sui-adapter/src/execution_engine.rs, sui-execution/vm-rework/sui-adapter/src/gas_charger.rs, sui-execution/vm-rework/sui-adapter/src/temporary_store.rs
This PR refactors TemporaryStore so that it could emit both effects v1 and v2.
Previously, TemporaryStore contains a `written` field and a `deleted` field that contains all the writes and deletions, tailored for effects v1.
This PR changes the output field of TemporaryStore to use ExecutionResultsV2 directly. ExecutionResultsV2 contains all the primitive data of the execution output.
In order to maintain all the primitive results properly, this PR replaced the `write_object` and `delete_object` function with a list of more specific APIs such as `mutate_input_object`, `mutate_child_object`, `delete_input_object`, `create_object`, `update_system_package` and etc.
At the end, when we emit effects, we generate the object changes based on the primitive results, and convert back to what effects …
=> [EffectsV2 3/n] Refactor TemporaryStore to be ready for effects V2

crates/sui-core/src/authority.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-core/src/unit_tests/execution_driver_tests.rs
A function that operates on the first parameter as the primary entity is best defined inside that type.
This PR makes the following refactorings:
1. Move "handle_certificate" into AuthorityState, because it really belongs there.
2. Move the execution overload check into TransactionManager as it depends on its internal state.
3. Move the consensus overload check into ConsensusHandler.
Also cleaned up some strange Arc clones.
---
=> Clean up some AuthorityServer functions

apps/wallet/src/ui/app/pages/swap/BaseAssets.tsx, apps/wallet/src/ui/app/pages/swap/QuoteAssets.tsx, apps/wallet/src/ui/app/pages/swap/utils.ts, apps/wallet/src/ui/app/pages/swap/validation.ts
- Portions of DEFI swap page
---
=> [Wallet]: Add asset pages for DEFI swap

apps/explorer/src/components/Layout/PageLayout.tsx
https://mysten.atlassian.net/browse/APPS-1752
---
=> [Explorer]: add network outage banner for testnet

.changeset/three-masks-fry.md, sdk/dapp-kit/src/hooks/wallet/useConnectWallet.ts, sdk/dapp-kit/src/walletStore.ts, sdk/dapp-kit/test/hooks/useConnectWallet.test.tsx
This PR resolves https://github.com/MystenLabs/sui/issues/11457 in dapp-kit. To summarize, when you connect a multi-chain wallet we were updating our `accounts` state to include non-Sui accounts. This PR adds some basic filtering so that our UI state excludes non-Sui wallets ⛓️ 
- Added a test
- CI
---
=> [dapp-kit] only take Sui accounts when connecting to wallets that are multi-chain

crates/sui-config/data/fullnode-template.yaml, docker/fullnode/README.md, docker/fullnode/docker-compose.yaml, docker/sui-node/Dockerfile
Make some fixes to make fullnode docker compose work on the latest `main` branch.
```
sui/docker/sui-node $ sudo ./build.sh -t sui-node-local
~/fullnode/docker $ wget https://github.com/MystenLabs/sui-genesis/raw/main/devnet/genesis.blob
~/fullnode/docker $ cp ~/sui/crates/sui-config/data/fullnode-template.yaml ./
~/fullnode/docker $ cp ~/sui/docker/fullnode/docker-compose.yaml ./
~/fullnode/docker $ sudo docker compose up
```
---
=> [Docker] fix fullnode docker compose

crates/sui-core/src/generate_format.rs, crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs, crates/sui-core/src/unit_tests/transfer_to_object_tests.rs, crates/sui-core/tests/staged/sui.yaml, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_27.snap, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/effects_v2.rs, crates/sui-types/src/effects/mod.rs, crates/sui-types/src/effects/object_change.rs, crates/sui-types/src/execution.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/vm-rework/sui-adapter/src/temporary_store.rs
This reverts commit 91991daa4d3b0f58449c6ffce3cbb2d4d00007b1.
The change was not gated properly. Reverting and redo it.
---
=> Revert "Enable effects v2 in protocol config (#13969)"

.changeset/nice-onions-listen.md, sdk/kiosk/src/tx/rules/resolve.ts
Fixes `resolveRoyaltyRule` from breaking after 0.43 update.
---
=> Fix `resolveRoyaltyRule` breaking

Cargo.lock, crates/sui-indexer/src/apis/indexer_api_v2.rs, crates/sui-indexer/src/apis/mod.rs, crates/sui-indexer/src/apis/move_utils_v2.rs, crates/sui-indexer/src/apis/read_api_v2.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/indexer_v2.rs, crates/sui-indexer/src/lib.rs, crates/sui-indexer/src/main.rs, crates/sui-indexer/src/models_v2/objects.rs, crates/sui-indexer/src/models_v2/tx_indices.rs, crates/sui-json-rpc-types/src/lib.rs
(note: will merge this thing with `IndexerReader`)
1. separate the indexer writer & reader such that reader takes `PgIndexerStoreV2` instead of a trait
2. implement a few indexer api, including `query_transaction_blocks`, `get_dynamic_fields`, `get_owned_object` (does not support filter yet).
Tested locally
---
implement a few indexer api and separate the indexer writer & reader
=> [indexer] indexer api Part I

crates/sui-protocol-config/src/lib.rs
Add more comments to clarify obj size limits
N/A
---
=> chore/easy: add more comments to clarify obj size limits

apps/wallet/src/ui/app/shared/InputWithAction.tsx
- Decouple Formik from `InputWithActionButton`
---
=> [Wallet]: Input with action btn decoupled from formik

crates/sui-analytics-indexer/src/handlers/package_handler.rs, crates/sui-analytics-indexer/src/handlers/transaction_handler.rs, crates/sui-analytics-indexer/src/tables.rs
Knowing the commands in a programmable transaction, or more precisely certain commands can help in grouping and analyzing transactions. 
This change is a very simple way to do it.
Simply tested the pipeline on my machine and looked at the generated files
---
=> changes to the schema to allow a better view over transctions

crates/sui-framework/packages/sui-framework/sources/crypto/zklogin_verified_id.move, crates/sui-framework/packages/sui-framework/sources/crypto/zklogin_verified_issuer.move, crates/sui-framework/packages/sui-framework/tests/crypto/zklogin_verified_id_tests.move, crates/sui-framework/packages/sui-framework/tests/crypto/zklogin_verified_issuer_tests.move, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Fix `verify_zklogin_id` and `verify_zklogin_issuer` functions such that they transfer the verified id or issuer objects to the sender.
Unit tests
Fix bug in `verify_zklogin_id` and `verify_zklogin_issuer` functions.
=> Fix verify_zklogin_id and issuer functions

crates/sui-graphql-rpc/src/client/simple_client.rs, crates/sui-graphql-rpc/src/server/builder.rs
Previous logic was always yielding the headers even when not present. This seems like recent behavior.
Will dig in to see what changed but this new logic works well and is clearer
Manual
---
=> [graphql/rpc] change usage header checks

crates/sui-sdk/src/lib.rs
expose ws ping duration config to SuiClientBuilder.
User can use this setting to prevent inactive WS subscription got disconnected due to proxy timeout
Manual test
---
Expose WS ping duration config to SuiClientBuilder,  user can use this setting to prevent inactive WS subscription got disconnected due to proxy timeout.
=> [Rust SDK] - expose ws ping duration config to SuiClientBuilder

crates/sui-single-node-benchmark/src/benchmark_context.rs, crates/sui-single-node-benchmark/src/command.rs, crates/sui-single-node-benchmark/src/execution.rs, crates/sui-single-node-benchmark/src/main.rs, crates/sui-single-node-benchmark/src/single_node.rs, crates/sui-single-node-benchmark/tests/smoke_tests.rs
This PR extends the single-node-benchmark to be able to benchmark the TransactionManager.
Specifically it now supports 3 different components:
1. Execution and storage layer only
2. (1) + TxManager
3. ValidatorService, which is basically (2) + Cert verification
CI
---
=> [benchmark] Support benchmarking tx manager

crates/sui-graphql-rpc/examples/checkpoint/checkpoint.graphql, crates/sui-graphql-rpc/examples/checkpoint_connection/checkpoint_connection.graphql, crates/sui-graphql-rpc/examples/epoch/epoch.graphql, crates/sui-graphql-rpc/examples/object/object.graphql, crates/sui-graphql-rpc/examples/object_connection/object_connection.graphql, crates/sui-graphql-rpc/examples/owner/owner.graphql, crates/sui-graphql-rpc/examples/transaction_block_connection/transaction_block_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Implements postgres resolvers for Query type, except for the following:
1. availableRange - pending impl. on IndexerV2
2. dryRunTransactionBlock
3. coinMetadata -> need to be added to DB
4. resolveNameServiceAddress
5. event_connection -> TODO: need to define typings
transactionBlockConnection
* can support all transactionBlockFilter except the post-MVP ones
objectConnection
* Does not support filtering by package::module::type as the column is missing on object table
* Does not support querying by objectKeys = (objectId, version) either, as we do not have an object history table
1. Manual queries, which were then added to the examples dir
2. snapshot tests
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate …
=> [graphql] resolvers for Query type

apps/wallet/src/ui/app/shared/InputWithAction.tsx
- Adding suffix for Input box that's decoupled from Formik
---
=> [Wallet]: Add suffix for Input

crates/sui-graphql-rpc/src/server/builder.rs
Disables tests which depend on DB while we develop data source for CI
N/A
---
=> [graphql/rpc] disable builder tests pending alt data source

crates/sui-graphql-rpc/src/context_data/sui_sdk_data_provider.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs
Make it more explicit via comments that we're moving away from depending on RPC 1.0 SDK so we can migrate and cleanup as needed.
N/A
---
=> [graphql/rpc] chore/easy: add TODO comments to callout we're moving away from sdk usage

Cargo.lock, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/config.rs
Adds ServerConfig type which will be used to drive all server configs from a yaml file
TBD
---
=> [graphql/rpc] easy: add initial server config struct and file loader

crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs
The source service has two long running threads:
- the server thread that serves source when requests come in
- a thread that monitors on-chain transactions for upgrades (`fn watch_for_upgrades`)
The second thread needs access to the server thread state, in order to invalidate (and later update) source code when it observes an on-chain upgrade. This PR simply does the plumbing to share the server state as a mutable reference in `watch_for_upgrades`. The state is not used yet, see follow up PRs for more.
N/A no functional changes
---
=> move: create Arc app state for source service

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_handler.rs
Collect two stats for each epoch:
- Narwhal certificates created per validator.
- Sui transactions submitted to consensus per validator
Create write mod for updating consensus indices per consensus commit, instead of per transaction.
Another change is to always set the `consensus_message_processed` bit regardless of transaction type. I think there was no dependency on some message types not setting `consensus_message_processed`, but let me know otherwise.
CI
---
=> [ConsensusHandler] accumulate consensus stats for each epoch

crates/workspace-hack/Cargo.toml, external-crates/move/move-model/Cargo.toml, external-crates/move/move-model/src/ast.rs, external-crates/move/move-prover/move-docgen/tests/sources/code_block_test.spec_inline.md, external-crates/move/move-prover/move-docgen/tests/sources/code_block_test.spec_inline_no_fold.md, external-crates/move/move-prover/move-docgen/tests/sources/code_block_test.spec_separate.md, external-crates/move/move-prover/move-docgen/tests/sources/root_template.spec_inline.md, external-crates/move/move-prover/move-docgen/tests/sources/root_template.spec_inline_no_fold.md, external-crates/move/move-prover/move-docgen/tests/sources/root_template.spec_separate.md, external-crates/move/move-prover/move-docgen/tests/sources/some_script.spec_inline.md, external-crates/move/move-prover/move-docgen/tests/sources/some_script.spec_inline_no_fold.md, external-crates/move/move-prover/move-docgen/tests/sources/some_script.spec_separate.md
Fixes an issue from #14112 where docgen was improperly formatting scripts since these are identified with an address of `MAX_ADDR` but to get this in `BigUint` which is what the Move model uses it passes the address value string.
Ran tests locally and updated.
=> Fix determination of scripts in Move model to work for 32-byte addresses

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs
Use the available data for the expiration field instead of using the get last system state.
---
=> [graphql/rpc] change expiration field in tx block

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_handler.rs
Current logic does not initialize ConsensusStats for upgraded validators.
CI
---
=> Fix initialization of ConsensusStats after upgrades

crates/sui-graphql-rpc/examples/transaction_block/transaction_block_kind.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Add `TransactionBlockKind` resolvers in Graphql. Not fully completed due to missing other types (Move stuff). 
Not clear how to handle the `GenesisObject` yet. 
---
=> [graphql/rpc] transaction block kind

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
The scalar `MoveData` wasn't properly defined
Unit
---
=> [graphql/rpc] easy/chore: fix type def & schema

crates/sui-analytics-indexer/src/analytics_processor.rs, crates/sui-analytics-indexer/src/lib.rs, crates/sui-analytics-indexer/src/writers/csv_writer.rs
This PR allows for us to run analytics pipeline from any given checkpoint passed in through the config. This is useful for testing purposes and for backfill we need to be able to run from an arbitrary checkpoint.
Ran locally, pipeline works as expected
=> [Analytics] Make analytics pipelines run from any checkpoint to support backfill

crates/sui-rest-api/src/checkpoints.rs, crates/sui-rest-api/src/lib.rs, crates/sui-rest-api/src/node_state_getter.rs, crates/sui-rest-api/src/objects.rs
First part in a series of PRs to allow for simulated chain state which feeds into indexer etc and can be used for testing and experimentation 
NFC
---
=> sim data source 1/x: parametize rest api data source

apps/wallet/src/ui/app/pages/home/nfts/index.tsx, apps/wallet/src/ui/app/shared/page-main-layout/PageMainLayout.tsx
* hide hidden assets menu button when no hidden assets exist
* center empty message
before
https://github.com/MystenLabs/sui/assets/10210143/fbf47c0f-ae6e-4cdd-a45e-b3ff6c1ec03a
after 
https://github.com/MystenLabs/sui/assets/10210143/b7b5d9f9-ba29-41d9-ad6d-d347f686b19e
closes [APPS-1807](https://mysten.atlassian.net/browse/APPS-1807) 
---
=> wallet-ext: hidden assets ui improvements

apps/wallet/src/ui/app/components/accounts/AccountMultiSelect.tsx
| -- | -- |
| <img width="363" alt="Screenshot 2023-10-06 at 12 34 39" src="https://github.com/MystenLabs/sui/assets/10210143/ffe17b26-3d4f-4b8d-a921-18bad28d102f"> | <img width="363" alt="Screenshot 2023-10-06 at 12 29 17" src="https://github.com/MystenLabs/sui/assets/10210143/4a050a75-dc2e-4835-84c8-bed2d91155ee"> |
| <img width="363" alt="Screenshot 2023-10-06 at 12 33 55" src="https://github.com/MystenLabs/sui/assets/10210143/5a99505a-5a86-41a3-aafa-9a669905f701"> | <img width="363" alt="Screenshot 2023-10-06 at 12 33 10" src="https://github.com/MystenLabs/sui/assets/10210143/17809a4e-7dc6-4ab1-8a10-f192156a3d62"> |
closes [APPS-1808](https://mysten.atlassian.net/browse/APPS-1808)
---
If your changes are not user-facing …
=> wallet-ext: approve dapp connection hide (de)select all when one account

Cargo.lock, apps/wallet/src/background/auto-lock-accounts.ts, apps/wallet/src/ui/app/components/accounts/AutoLockSelector.tsx, apps/wallet/src/ui/app/components/accounts/LockUnlockButton.tsx, apps/wallet/src/ui/app/index.tsx, apps/wallet/tests/balanceChanges.spec.ts, apps/wallet/tests/demo-app/src/index.tsx, apps/wallet/tests/lock.spec.ts, apps/wallet/tests/onboarding.spec.ts, apps/wallet/tests/sites-to-cs-messaging.spec.ts, apps/wallet/tests/staking.spec.ts, apps/wallet/tests/tabs.spec.ts, apps/wallet/tests/utils/auth.ts, crates/sui-cluster-test/src/faucet.rs, crates/sui-test-validator/Cargo.toml, crates/sui-test-validator/src/main.rs
* adds support for v1 requests for test faucet
closes [APPS-1751](https://mysten.atlassian.net/browse/APPS-1751)
---
=> wallet-ext: enable e2e tests

crates/sui-benchmark/src/bank.rs, crates/sui-benchmark/src/drivers/bench_driver.rs, crates/sui-benchmark/src/drivers/driver.rs, crates/sui-benchmark/src/drivers/mod.rs, crates/sui-benchmark/src/options.rs, crates/sui-benchmark/src/workloads/adversarial.rs, crates/sui-benchmark/src/workloads/batch_payment.rs, crates/sui-benchmark/src/workloads/delegation.rs, crates/sui-benchmark/src/workloads/mod.rs, crates/sui-benchmark/src/workloads/shared_counter.rs, crates/sui-benchmark/src/workloads/transfer_object.rs, crates/sui-benchmark/src/workloads/workload_configuration.rs, crates/sui-benchmark/tests/simtest.rs
Modifying the sui-benchmark suite in order to allow us to run benchmarks with multiple traffic profiles instead of only one constant rate as we currently do. That will allow us to simulate load of variable traffic (and type of txes etc) instead of constant one. To achieve this the `Bench` cli subcommand was extended to provide all the arguments as vectors allowing us to set multiple "benchmark groups" , where the properties of each benchmark group are all the values of the specified vector position. More information about this on the `options.rs` file.
To achieve the above we build workloads for each "benchmark group" and then we initialise all those once. Then a bench workers schedule task has been introduced to coordinate running each benchmark group. Each group is defined to run for a …
=> [sui-benchmark] run multiple traffic profiles on same benchmark

.changeset/lovely-ties-stare.md, sdk/bcs/package.json, sdk/kiosk/package.json, sdk/typescript/package.json, sdk/wallet-standard/package.json, sdk/zklogin/package.json
This marks some packages as side-effect free now that we shouldn't have any imports that create side-effects without exporting the references, which makes it work fine in testing.
I only marked packages that we are actively developing (which is why I didn't include wallet-kit and suins-toolkit packages) and that I was somewhat familiar with (which is why I didn't include ledger, deepbook, move-binary-format) as being side-effect free.
---
=> Mark packages as side-effect free

.changeset/small-turtles-tie.md, sdk/dapp-kit/src/hooks/wallet/useDisconnectWallet.ts, sdk/dapp-kit/src/hooks/wallet/useSignAndExecuteTransactionBlock.ts, sdk/dapp-kit/src/hooks/wallet/useSignTransactionBlock.ts, sdk/dapp-kit/src/hooks/wallet/useSwitchAccount.ts
This PR does a little polish on the signing hooks for a few things I noticed were off. The most notable change here is that we're making the `chain` arg optional as we should just infer the active chain from the account. This keeps parity with the wallet-kit implementation
- CI
---
=> [dapp-kit] do a little polishing on the hooks for inferring the active chain / exposing errors / etc.

crates/sui-core/src/authority.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-storage/src/http_key_value_store.rs, crates/sui-storage/src/key_value_store.rs, crates/sui-storage/tests/key_value_tests.rs
Fixes an issue where data could be missing when using query_transaction
when the transaction data itself isn't present on the node, due to
pruning, requiring us to fallback to the kvstore.
---
=> jsonrpc: fix missing data when using query_transaction

crates/sui-core/Cargo.toml, crates/sui-core/src/consensus_handler.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, narwhal/consensus/benches/process_certificates.rs, narwhal/consensus/src/tests/bullshark_tests.rs, narwhal/consensus/src/tests/consensus_tests.rs, narwhal/consensus/src/tests/randomized_tests.rs, narwhal/executor/tests/consensus_integration_tests.rs, narwhal/node/src/generate_format.rs, narwhal/primary/src/aggregators.rs, narwhal/primary/src/certificate_fetcher.rs, narwhal/primary/src/certifier.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/proposer.rs, narwhal/primary/src/synchronizer.rs, narwhal/primary/src/tests/certificate_fetcher_tests.rs, narwhal/primary/src/tests/certificate_tests.rs, narwhal/primary/src/tests/certifier_tests.rs, narwhal/primary/src/tests/primary_tests.rs, narwhal/primary/src/tests/proposer_tests.rs, narwhal/primary/src/tests/synchronizer_tests.rs, narwhal/storage/src/certificate_store.rs, narwhal/storage/src/consensus_store.rs, narwhal/test-utils/src/lib.rs, narwhal/types/benches/verify_certificate.rs, narwhal/types/src/consensus.rs, narwhal/types/src/primary.rs, narwhal/types/tests/primary_tests.rs
Added new version for NW `Certificate` which Includes new `AggregateSignatureState`. This holds `AggregateSignatureBytes` but with the added layer to specify if the signature was verified via a leader, verified directly, unverified or unsigned. This will be used to take advantage of the certificate chain that is formed via the DAG by only verifying the leaders of the certificate chain when they are fetched from validators during catchup. 
This is gated by a protocol feature flag so this PR should have no effect yet. Still testing the [followup PR](https://github.com/MystenLabs/sui/commit/ef48f56d972e46ada7b58bd2ecd7eebd23d8010b) which will include the usage of `CertificateV2`, but sharing here to provide more context for these changes.
=> [narwhal] Add CertificateV2

crates/sui-benchmark/src/lib.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority_aggregator.rs, crates/sui-core/src/authority_client.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/quorum_driver/mod.rs, crates/sui-core/src/safe_client.rs, crates/sui-core/src/test_authority_clients.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-core/src/transaction_orchestrator.rs, crates/sui-e2e-tests/tests/dynamic_committee_tests.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-e2e-tests/tests/shared_objects_version_tests.rs, crates/sui-e2e-tests/tests/transfer_to_object_tests.rs, crates/sui-types/src/quorum_driver_types.rs, crates/test-cluster/src/lib.rs
It seems this optimization is unlikely to come back, so removing the remaining scaffolding.
CI
---
=> [Cleanup] remove remaining logic for input object fastpath

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_test_utils.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/lib.rs, crates/sui-core/src/post_consensus_tx_reorder.rs, crates/sui-core/src/unit_tests/consensus_tests.rs
This PR does a few cleanups for ConsensusHandler:
1. Move all the code that are consensus-independent into the function inside epoch_store. This allows us to get rid of this strange CommitBatch thing, as well as opens up an interface for other code to call (e.g. if we want to benchmark the system with a dummy consensus)
2. Move the tx oredering code into its own file for clarity
3. Insert roots at the end to reduce dup entries.
CI
---
=> Clean up ConsensusHandler
