MystenLabs/sui

Cargo.lock, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-single-node-benchmark/Cargo.toml, crates/sui-single-node-benchmark/src/benchmark_context.rs, crates/sui-single-node-benchmark/src/command.rs, crates/sui-single-node-benchmark/src/lib.rs, crates/sui-single-node-benchmark/src/mock_consensus.rs, crates/sui-single-node-benchmark/src/single_node.rs, crates/sui-single-node-benchmark/tests/smoke_tests.rs
Try to exercise the consensus path in the single node benchmark.
There are two modes: noop and direct.
CI
---
=> [benchmark] Support two modes of consensus

crates/sui-core/src/authority_server.rs, crates/sui-single-node-benchmark/src/benchmark_context.rs, crates/sui-single-node-benchmark/src/command.rs, crates/sui-single-node-benchmark/src/execution.rs, crates/sui-single-node-benchmark/src/single_node.rs
Adding a benchmark to measure validator signing transaction performace in the single node benchmark suite.
Sample output:
```
cargo run --release --bin sui-single-node-benchmark -- move --component txn-signing
2023-10-10T16:08:05.023632Z  INFO sui_single_node_benchmark::benchmark_context: Creating 500001 accounts and 1000002 gas objects
2023-10-10T16:08:06.430838Z  INFO sui_single_node_benchmark::benchmark_context: Initializing validator
2023-10-10T16:08:10.306098Z  INFO sui_single_node_benchmark::benchmark_context: Programmable Move Transaction Generator: Creating 500001 transactions
2023-10-10T16:08:11.236391Z  INFO sui_single_node_benchmark::execution: Sample transaction: SenderSignedData([SenderSignedTransaction { intent_message: IntentMessage { intent: Intent { scope: …
```
=> Adding a benchmark for transaction signing

pnpm-lock.yaml, sdk/dapp-kit/README.md, sdk/dapp-kit/package.json, sdk/dapp-kit/src/components/WalletProvider.tsx, sdk/dapp-kit/src/types.ts, sdk/docs/examples/wallet-components.tsx, sdk/docs/examples/wallet-hooks.tsx, sdk/docs/package.json, sdk/docs/pages/_meta.json, sdk/docs/pages/dapp-kit/_meta.json, sdk/docs/pages/dapp-kit/index.mdx, sdk/docs/pages/dapp-kit/themes.mdx, sdk/docs/pages/dapp-kit/wallet-components/ConnectButton.mdx, sdk/docs/pages/dapp-kit/wallet-components/ConnectModal.mdx, sdk/docs/pages/dapp-kit/wallet-components/_meta.json, sdk/docs/pages/dapp-kit/wallet-hooks/_meta.json, sdk/docs/pages/dapp-kit/wallet-hooks/useAccounts.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useConnectWallet.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useCurrentAccount.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useCurrentWallet.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useDisconnectWallet.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useSignAndExecuteTransactionBlock.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useSignPersonalMessage.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useSignTransactionBlock.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useSwitchAccount.mdx, sdk/docs/pages/dapp-kit/wallet-hooks/useWallets.mdx, sdk/docs/pages/dapp-kit/wallet-provider.mdx, sdk/docs/pages/typescript/sui-client.mdx
https://sui-typescript-docs-git-mh-dapp-kit-wallet-docs-mysten-labs.vercel.app/dapp-kit
---
=> [docs] Add docs for wallet hooks and components in dapp-kit

Cargo.lock, Cargo.toml, crates/sui-rest-api/Cargo.toml, crates/sui-rest-api/src/node_state_getter.rs
Continuation of https://github.com/MystenLabs/sui/pull/14164
This will allow the simulator feed data into indexer etc
N/A
---
=> sim data source 2/x: impl node state getter for simulacrum

crates/sui-protocol-config-macros/src/lib.rs
Replace the use of CS randomly ordered HashSet with Vec to ensure consistent code generation.
=> Ensure sui-protocol-config-macros is deterministic

sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/vm-rework/sui-adapter/src/temporary_store.rs
I tried to update the existing PR but was unable to, so this is meant to replace https://github.com/MystenLabs/sui/pull/13361 which show cased a major performance improvement by removing a clone in temporary store.
---
=> remove expensive clone on hot execution path

.changeset/pretty-poets-confess.md, sdk/dapp-kit/src/index.ts
I was taking a stab at migrating SuiFrens to use dapp-kit, and I noticed none of the theme types were exposed.
[before] dAppTheme.ts
```
const theme = {}; // bleh
const theme: ComponentProps<typeof WalletProvider>['theme'] = {}; // bleh
```
[after] dAppTheme.ts
```
const theme: Theme = {...};
```
- CI
---
=> [dapp-kit] expose theme types so people can declare external themes more easily

crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/lib.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
This makes the executor in adapter test runner parametric.
Subseq PR, will enable choosing the executor in the test file.
Executors include: validator (current approach) and an upcoming simulator
Existing tests
---
=> data sim 3/x: make test adapter executor parametric

external-crates/move-execution/vm-rework/move-vm/runtime/src/interpreter.rs, external-crates/move/testing-infra/transactional-test-runner/src/framework.rs
Split the test parsing logic from the expectation checking and capture the state of adapter after the the execution.
This state will be used to feed the simulator post processing engine
Existing tests
---
=> capture adapter state after transactional test

crates/simulacrum/src/lib.rs, crates/simulacrum/src/store.rs, crates/sui-types/src/lib.rs, crates/sui-types/src/mock_checkpoint_builder.rs
Move checkpoint_builder to sui-types so that we could reuse it for other things, such as benchmarking.
Also added a validator key provider trait to hide how the underline key management works.
cargo build
---
=> Move checkpoint_builder to sui-types

.changeset/funny-flies-kiss.md, .eslintrc.js, apps/wallet/src/background/accounts/zklogin/utils.ts, sdk/typescript/src/zklogin/utils.ts, sdk/typescript/test/unit/zklogin/address.test.ts, sdk/zklogin/src/address.ts, sdk/zklogin/src/index.ts, sdk/zklogin/src/nonce.ts, sdk/zklogin/src/utils.ts
This makes a couple changes to simplify usage of the zklogin SDK.
- Randomness now returns a base64-encoded string
- Expose new `getExtendedEphemeralPublicKey` helper that returns a base64-encoded string of the public key (this helper is really just a one-liner but it makes it obvious what you should do, so I think there's value in keeping it).
- Remove `toBigIntBE` as an export.
---
=> Simplify zklogin SDK

crates/sui-graphql-rpc/src/commands.rs, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-json-rpc/src/name_service.rs
Allows one build a server from a config file
N/A
---
=> [graphql/rpc] chore/easy: build server from config

crates/sui-graphql-rpc/src/context_data/data_provider.rs, crates/sui-graphql-rpc/src/context_data/sui_sdk_data_provider.rs, crates/sui-graphql-rpc/src/error.rs
Removes unused rpc 1.0 logic which we used for experimentation
This is a non-functional change
Existing
---
=> [graphql/rpc] chore/easy: remove dead rpc 1.0 code

crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs
Stacked on https://github.com/MystenLabs/sui/pull/14106.
When we see a successful upgrade transaction on the network for monitored packages (e.g., sui-framework), the source service should not serve its existing knowledge of sources. I.e., the existing sources have changed in part or in whole, and we don't want to falsely report the sources for bytecode. 
This PR ensures that as soon as we observe an upgrade transaction, the `sources` reported are cleared and invalidated. It is basically the ultra conservative approach to ensure we don't report outdated sources. See inline comment on how we have to approach re-verifying sources when we know they have changed.
Added test to validate (a) successful upgrade transaction triggers in `watch_for_upgrades` and (b) such a transaction causes the …
=> move: source service invalidates data on upgrade txn

crates/sui-graphql-rpc/examples/transaction_block_connection/transaction_block_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
tx_indices does not exist in db anymore, so we should also stop referring to the table
---
=> [graphql] remove tx_indices usage

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
While the types are being fleshed out, render the some transactions kinds as strings
Manual
---
=> [graphql/rpc] render transaction kinds as strings temporarily

crates/sui-indexer/src/test_utils.rs
`start_test_indexer` does not honor the schema choice, causing DB to get reset to v1 everytime.
Manual
---
=> use the right schema on reset

apps/explorer/src/components/module/ModuleCodeTabs.tsx, apps/explorer/src/components/module/ModuleView.module.css, apps/explorer/src/components/module/PkgModulesWrapper.tsx, apps/explorer/src/hooks/useVerifiedSourceCode.ts, apps/explorer/src/ui/Tabs.tsx
This PR implements phase 1 of our source code verification functionality according to https://www.notion.so/mystenlabs/Source-Code-Verification-1aaebb21554e466eaf70e19db2f66825.  To summarize, we're going to show a "Source [Verified]" tab for verified modules as determined by our new `source.mystenlabs.com/api` endpoint. I'll get sign off from @rvantonder and Sean before landing :)
Verified source tab:
https://explorer-git-wrobertson-sourcever-mysten-labs.vercel.app/object/0x0000000000000000000000000000000000000000000000000000000000000002
No source tab:
https://explorer-git-wrobertson-sourcever-mysten-labs.vercel.app/object/0x04e20ddf36af412a4096f9014f4a565af9e812db9a05cc40254846cf6ed0ad91
- Manual testing on devnet/testnet/mainnet against verified and non-verified modules
- Manual …
=> [explorer] show source code for verified modules

crates/sui-indexer/src/apis/governance_api_v2.rs
This fixes a bug that leads to a panic when an `activation_epoch` is 0.
Manual queries
---
=> [governance_api_v2] fix subtle bug that leads to a panic when an activation_epoch is 0

crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs
See inline comment.
Updated tests, semantics-preserving change.
---
=> move (easy): source service uses smaller data dependency for watching upgrades

crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/tests/tests.rs
See inline comment.
Updated types and semantics-preserving change.
---
=> move (easy): source service rename SourcePackages -> SourcePackage

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_28.snap, narwhal/node/tests/staged/narwhal.yaml, narwhal/primary/src/certificate_fetcher.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/tests/certificate_fetcher_tests.rs, narwhal/primary/src/tests/certificate_tests.rs, narwhal/primary/src/tests/certifier_tests.rs, narwhal/primary/src/tests/primary_tests.rs, narwhal/primary/src/tests/synchronizer_tests.rs, narwhal/types/src/error.rs, narwhal/types/src/primary.rs
- Disabled CertificateV2 temporarily for additional testing
- Removed unused Cert methods
- Fixed an issue where old certificate versions were not being gated properly and were being accepted by the network and causing panics. This was happening via the RequestVote missing parents codepath.
```
thread '{"timestamp":"2023-10-13T18:14:52.906206Z","level":"ERROR","fields":{"message":"panicked at narwhal/types/src/primary.rs:1024:9:\nnot implemented: CertificateV2 field! Use aggregated_signature.","panic.file":"narwhal/types/src/primary.rs","panic.line":1024,"panic.column":9},"target":"telemetry_subscribers","filename":"crates/telemetry-subscribers/src/lib.rs","line_number":201}
```
=> [narwhal] Temporarily disable NW Certificate V2

crates/sui-indexer/src/lib.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/processors/processor_orchestrator.rs
As title. Instead of letting it fail after hitting a certain retry times, keep it run forever. Also add metrics for monitoring
Patching to prod indexer.
---
=> let indexer processors run forever

crates/sui-core/benches/batch_verification_bench.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/signature_verifier.rs, crates/sui-core/src/unit_tests/batch_verification_tests.rs, crates/sui-core/src/unit_tests/transaction_deny_tests.rs, crates/sui-e2e-tests/tests/zklogin_tests.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_29.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_29.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_29.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui-types/src/base_types.rs, crates/sui-types/src/signature.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/messages_tests.rs, crates/sui-types/src/unit_tests/utils.rs, crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs, crates/sui-types/src/zk_login_authenticator.rs, crates/sui/src/keytool.rs
Make Sui derive zkLogin address with padded address_seed so the address derived in the legacy way can still send funds. 
unit test
---
Make Sui to verify zkLogin legacy address (derived with padded address_seed). Upgrade protocol version to 29 to enable verify with legacy address.
=> fix: intepret zklogin address with padded address_seed field

crates/sui-core/benches/batch_verification_bench.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/signature_verifier.rs, crates/sui-core/src/unit_tests/batch_verification_tests.rs, crates/sui-core/src/unit_tests/transaction_deny_tests.rs, crates/sui-e2e-tests/tests/zklogin_tests.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_29.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_29.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_29.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui-types/src/base_types.rs, crates/sui-types/src/signature.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/messages_tests.rs, crates/sui-types/src/unit_tests/utils.rs, crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs, crates/sui-types/src/zk_login_authenticator.rs, crates/sui/src/keytool.rs
mirror: https://github.com/MystenLabs/sui/pull/14290
---
Make Sui to verify zkLogin legacy address (derived with padded address_seed). Upgrade protocol version to 29 to enable verify with legacy address.
=> fix: derive zklogin address with padded seed

crates/simulacrum/src/lib.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-single-node-benchmark/README.md, crates/sui-single-node-benchmark/src/benchmark_context.rs, crates/sui-single-node-benchmark/src/command.rs, crates/sui-single-node-benchmark/src/execution.rs, crates/sui-single-node-benchmark/src/lib.rs, crates/sui-single-node-benchmark/src/main.rs, crates/sui-single-node-benchmark/src/mock_account.rs, crates/sui-single-node-benchmark/src/mock_consensus.rs, crates/sui-single-node-benchmark/src/single_node.rs, crates/sui-single-node-benchmark/src/tx_generator.rs, crates/sui-single-node-benchmark/src/tx_generator/move_tx_generator.rs, crates/sui-single-node-benchmark/src/tx_generator/non_move_tx_generator.rs, crates/sui-single-node-benchmark/src/tx_generator/root_object_create_tx_generator.rs, crates/sui-single-node-benchmark/src/workload.rs, crates/sui-single-node-benchmark/tests/smoke_tests.rs, crates/sui-types/src/mock_checkpoint_builder.rs
This PR adds the ability to benchmark checkpoint executor.
The benchmark will first try to execute all transactions on the node, then revert them as if they were not yet executed, use the results to construct checkpoints, and then trigger the checkpoint executor.
CI
---
=> [benchmark] Benchmark checkpoint executor

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_29.snap, narwhal/node/tests/staged/narwhal.yaml, narwhal/primary/src/tests/certificate_fetcher_tests.rs, narwhal/primary/src/tests/certificate_tests.rs, narwhal/primary/src/tests/certifier_tests.rs, narwhal/primary/src/tests/primary_tests.rs, narwhal/primary/src/tests/synchronizer_tests.rs
150 Validators @ 200 TPS w/ 2 Hour downtime : https://metrics.sui.io/goto/TQ6QueGSR?orgId=1
120 Validators @ 200 TPS w/ 2 Hour downtime:  https://metrics.sui.io/goto/nJ6PJgnSR?orgId=1
---
Enable CertV2 for faster NW Catchup in Devnet
=> Re-enable CertV2 for faster NW Catchup in Devnet

crates/sui-graphql-rpc/schema/draft_target_schema.graphql
Continuing #13946 which converts the Move value representation into a scalar.  This PR is an RFC to do the same for the various type representations, for similar reasons (they are deeply nested structures which are difficult to query with GraphQL).
The downside is that we lose the ability to query, e.g. module information, struct declaration, etc for a type in the same query as the type (it needs to be issued as a separate query). This seems reasonable, however, because it is difficult to do this in practice because such a query would be all or nothing (e.g. the modules of all fields, or all type parameters, etc).
If the number of scalars is piling too high, we can also return a generic `JSON` scalar for all of these types (`MoveData`, `MoveTypeSignature`, `MoveTypeLayout`, …
=> [GraphQL/Schema][RFC] Scalars for Move Types

.github/workflows/rust.yml, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
I will obfuscate this further, but wanted to address the glaring error of using checkpoint_sequence_number as a cursor for objects
---
=> [graphql][fix] object use object_id as cursor

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_type.rs, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Implement `MoveType` and `MoveTypeSignature` from the RFC in #13955 and add `type` as a field to `MoveValue`.
`MoveType` is missing its layout field, because this requires support for converting a type tag into a type layout which will land in an upcoming PR.
```
sui-graphql-rpc$ cargo nextest run  -- move_type
```
=> [GraphQL] MoveType and MoveTypeSignature

crates/sui-types/src/lib.rs
So that it can be used in the GraphQL implementation which uses `AccountAddress` (and does not really distinguish between object IDs and addresses).
CI
=> [sui-types][EASY] `is_system_package` for AccountAddress

crates/sui/src/keytool.rs
The `keytool list` does not show the mnemonic for obvious reasons, but the field appears empty for every keypair. Therefore, this field should not be serialized and shown. 
*Before*
*After*
---
The `keytool list` does not show the mnemonic for obvious reasons, but the field appears empty for every keypair. Therefore, this field should not be serialized and shown.
=> [cli/keytool - easy] don't serialize mnemonic if it's empty

Cargo.lock, crates/simulacrum/Cargo.toml, crates/simulacrum/src/lib.rs, crates/simulacrum/src/store.rs
Just puts the sim store behind a trait so we can use persisted store (in upcoming PR) and other stores.
Manual, existing.
---
=> [data-sim/graphql testing] easy: add trait for sim store

crates/sui-graphql-rpc/examples/stake_connection/stake_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
This PR adds an ID field for the Stake object.
Manually through queries.
---
=> [graphql/rpc] add id to stake

sdk/dapp-kit/README.md, sdk/docs/pages/dapp-kit/index.mdx, sdk/docs/pages/dapp-kit/sui-client-provider.mdx
I noticed a tiny typo while reading the dapp-kit docs, the actual function is called `createNetworkConfig` and not `createNetworkConfigs` 😄 
- Eyes
---
=> [docs] fix typo in dapp-kit docs (createNetworkConfig vs. createNetworkConfigs)

crates/sui-graphql-rpc/src/types/query.rs
Fix Query.owner resolution to ObjectOwner::Owner variant to lazy render
existing tests
---
=> [graphql][easy][fix] remove some comments and fix owner enum variant

crates/sui-core/src/authority/test_authority_builder.rs
By exposing account cfg in test auth builder, we dont have to sideload initial gas objects.
Dependent test will be migrated
Existing
---
=> easy: expose account cfg in test

.github/CODEOWNERS
Since the basic integration & design has been decided, no need to add noise for non-core graphql devs
N/A
---
=> [graphql/impl] remove non core gql folks from from codeowners

.cargo/config, external-crates/move/move-model/src/spec_translator.rs, external-crates/move/move-prover/boogie-backend/src/boogie_helpers.rs, external-crates/move/move-prover/bytecode/src/graph.rs, external-crates/move/move-prover/bytecode/src/mono_analysis.rs, external-crates/move/tools/move-cli/src/sandbox/utils/mod.rs
Fixes some clippy lints ignored when [this](https://github.com/MystenLabs/sui/pull/14167) PR was inteoduced.
Others coming shortly.
Existing
---
=> chore/easy: fix some clippy lints in move

.cargo/config, external-crates/move/move-analyzer/src/symbols.rs, external-crates/move/move-binary-format/src/normalized.rs, external-crates/move/move-borrow-graph/src/graph.rs, external-crates/move/move-bytecode-verifier/src/struct_defs.rs, external-crates/move/move-compiler/src/cfgir/cfg.rs, external-crates/move/move-compiler/src/expansion/translate.rs, external-crates/move/move-compiler/src/hlir/translate.rs, external-crates/move/move-compiler/src/naming/translate.rs, external-crates/move/move-compiler/src/shared/mod.rs, external-crates/move/move-compiler/src/typing/dependency_ordering.rs, external-crates/move/move-compiler/src/typing/infinite_instantiations.rs, external-crates/move/move-compiler/src/typing/recursive_structs.rs, external-crates/move/move-compiler/src/typing/translate.rs, external-crates/move/move-ir-compiler/move-bytecode-source-map/src/marking.rs, external-crates/move/move-model/src/builder/model_builder.rs, external-crates/move/move-model/src/builder/module_builder.rs, external-crates/move/move-model/src/model.rs, external-crates/move/move-prover/boogie-backend/src/boogie_wrapper.rs, external-crates/move/move-prover/bytecode/src/access_path_trie.rs, external-crates/move/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs, external-crates/move/move-prover/bytecode/src/verification_analysis_v2.rs, external-crates/move/move-prover/interpreter/src/concrete/value.rs, external-crates/move/move-vm/runtime/src/loader.rs, external-crates/move/tools/move-cli/src/base/prove.rs, external-crates/move/tools/move-coverage/src/coverage_map.rs, external-crates/move/tools/move-coverage/src/summary.rs, external-crates/move/tools/move-unit-test/src/test_reporter.rs
Fixes clippy lints for unwrap or defaults
Existing
---
=> easy/chore: unwrap or default lints

.cargo/config, external-crates/move/move-analyzer/src/symbols.rs, external-crates/move/move-borrow-graph/src/references.rs, external-crates/move/move-compiler/src/shared/unique_set.rs, external-crates/move/move-core/types/src/gas_algebra.rs
This is the last cleanup for the outstanding lints from https://github.com/MystenLabs/sui/pull/14167
In order to preserve existing behavior, it was easier to selectively ignore the lints on specific files.
Existing
---
=> chore/easy: ord clippy lint

crates/sui-json/src/lib.rs, crates/sui-transaction-builder/src/lib.rs, crates/sui/tests/cli_tests.rs, crates/sui/tests/data/tto/Move.toml, crates/sui/tests/data/tto/sources/tto1.move, sdk/typescript/src/bcs/index.ts, sdk/typescript/src/builder/Inputs.ts, sdk/typescript/src/builder/TransactionBlock.ts, sdk/typescript/src/builder/__tests__/Transaction.test.ts, sdk/typescript/src/client/types/generated.ts, sdk/typescript/test/e2e/data/tto/Move.toml, sdk/typescript/test/e2e/data/tto/sources/tto1.move, sdk/typescript/test/e2e/receive-object.test.ts
Adds support for constructing and sending transactions using the new `Receiving` transaction argument in the typescript and Rust SDKs.
The bottom commit adds typescript support and the top commit adds Rust SDK support (and has already been reviewed and approved). 
Added a number of additional tests to the typescript SDK to make sure `receiving` arguments are handled correctly.
---
Support has been added to both Typescript and Rust SDKs to construct transactions to receive previously-sent objects using the new transfer-to-object functionality and `Receiving` …
=> [3/n][transfer-to-object] Add SDK support for receiving objects

external-crates/move/move-compiler/src/expansion/translate.rs, external-crates/move/move-compiler/tests/move_check/parser/function_visibility_friend_script.exp, external-crates/move/move-compiler/tests/move_check/parser/function_visibility_friend_script.move
Discovered an interesting panic while playing with function visibility modifiers:
```Move
module 0x0::test {
public(friend) public(script) fun hey() {}
}
```
Compiler panics:
```
thread 'main2023-10-22T19:25:23.907561Z ERROR telemetry_subscribers: panicked at external-crates/move/move-compiler/src/expansion/translate.rs:1657:13:
assertion failed: !context.env.has_errors() panic.file="external-crates/move/move-compiler/src/expansion/translate.rs" panic.line=1657 panic.column=13
' panicked at external-crates/move/move-compiler/src/expansion/translate.rs:1657:13:
```
Adds a test for the scenario.
--- …
=> [compiler] Fix panic on public(script) after public(friend)

.changeset/ten-maps-exercise.md
Bumps the version for transfer to object.
-
---
=> [sui.js] Version bump for Transfer to Object

crates/sui-indexer/migrations_v2/2023-10-04-161107_move_call_metrics/up.sql, crates/sui-indexer/src/apis/extended_api_v2.rs, crates/sui-indexer/src/apis/mod.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/indexer_v2.rs, crates/sui-indexer/src/models_v2/address_metrics.rs, crates/sui-indexer/src/models_v2/move_call_metrics.rs, crates/sui-indexer/src/models_v2/network_metrics.rs
Implement the read path of analytical endpoints of indexer v2, the read path.
the related write path PR is https://github.com/MystenLabs/sui/pull/14140
- locally populate the analytical tables from the write PR
cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --rpc-client-url http://ewr-suifn-y71v1.devnet.sui.io:9000 --fullnode-sync-worker --reset-db --use-v2
cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --rpc-client-url http://ewr-suifn-y71v1.devnet.sui.io:9000 --fullnode-sync-worker --reset-db --use-v2
- locally run json rpc server with this PR and test cmd like
curl --location http://127.0.0.1:9000 \
--data '{
"id": 1,
"method": …
=> indexer v2: analytical endpoints, read path

crates/sui-archival/src/lib.rs, crates/sui-storage/src/object_store/mod.rs, crates/sui-tool/src/lib.rs
Allow passing in a custom endpoint for object store to start using accelerated s3 endpoint which is proven to be more reliable during archival verification
Ran an archive verification workflow with the cherry pick
=> Allow passing in an aws endpoint for accelerated s3 downloads

Cargo.lock, crates/sui-replay/src/lib.rs, crates/sui/Cargo.toml, crates/sui/src/client_commands.rs, doc/src/build/cli-client.md
Adds 3 new CLI commands for replay which call into the existing replay commands. We've removed most of the optional parameters in leu of the defaults so that we provide a simple and straightforward user experience. Based on feedback if there is an ask to expose these we can add them in as needed. 
A follow-up PR will be added to reformat the output using the tabular structure instead of the existing println! statements.
---
=> add replay command to the CLI which point to existing replay commands

crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs
Some GraphQL endpoint implementations were cloning existing fields to return, this is unnecessary -- we can just return a reference.
Manually tested with GraphiQL
=> [GraphQL/EASY] Clean-up -- avoid clones

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs
The BCS output for Object should represent its raw bytes (what you would see if you looked at it in a node's DB), which differs from its current format which outputs the BCS representation of an object if it's a `MoveObject`, or the BCS representation of a package if it's a `MovePackage`.
This also has the unfortunate side effect of discarding the information about whether the Object is a Package or a MoveObject after it has been initialised.
This PR adapts the BCS representation for Object to be the serialization of its on-chain representation (this can be done more efficiently when we introduce data loaders and sunset the existing interface because this is exactly the contents of one of the DB fields).
In future PRs, I will introduce the `bcs` representation of a `MovePackage` …
=> [GraphQL/Object] Tweak BCS implementation

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Now that the BCS representation of an `Object` does not lose information about whether it's a `MovePackage` or `MoveObject`, it becomes possible to implement `asMoveObject`, which this PR does.
Manually tested with GraphiQL:
- #14376 
- #14377
=> [GraphQL/Object] Implement asMoveObject

narwhal/consensus/src/tests/consensus_utils.rs, narwhal/storage/src/consensus_store.rs, narwhal/storage/src/node_store.rs
Removes access to `sub_dag` column family. It has been deprecated in favor of `submitted_sub_dag` several months ago. Notably we can't simply delete everything in the code because rocksdb wants us to be aware the CF exists.
1. all tests passed
2. sui genesis -f and then sui start from main. Ctrl+C, then sui start from this branch. Observe narwhal still runs without any issues.
---
remove the access to the deprecated cf sub_dag
=> [narwhal] remove the access to the deprecated cf sub_dag

crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/tests/tests.rs
Just factors out checking version headers to a middleware function. Previously we only had one route and checked the headers in line. Now I want to add a second `/list` route (see https://github.com/MystenLabs/sui/pull/14361) where the server can report which source paths are verified, so factoring out header checking to middleware.
Just factoring out a middleware layer, covered by existing test for header checks
---
=> move: factor out source service header middleware

Cargo.lock, Cargo.toml, crates/sui-analytics-indexer-derive/Cargo.toml, crates/sui-analytics-indexer-derive/src/lib.rs, crates/sui-analytics-indexer/Cargo.toml, crates/sui-analytics-indexer/src/analytics_processor.rs, crates/sui-analytics-indexer/src/lib.rs, crates/sui-analytics-indexer/src/tables.rs, crates/sui-analytics-indexer/src/writers/csv_writer.rs, crates/sui-analytics-indexer/src/writers/mod.rs, crates/sui-analytics-indexer/src/writers/parquet_writer.rs, crates/sui-metric-checker/src/lib.rs, crates/workspace-hack/Cargo.toml
Initial implementation of `Parquet` protocol support for a data analytics pipeline. 
_PR is not production-ready. It is being submitted for an early preview and discussion of the approach._
Notes:
* only the most popular field types are currently supported(u64, String). If this approach makes sense, will add support for other types
* the Rust Parquet library is relatively basic, so new macros have been introduced to help automatically describe the type's schema (i.e., the names of fields) and to retrieve column/field values by their index in the type declaration
=> [data analytics] parquet: initial implementation

docker/sui-tools/Dockerfile
I'm working on improving the archive validator workflows by converting them to k8s cron job and including sui-tool in the sui-tools docker image would make this much easier to accomplish.
tested against the Sui Build Image Workflow. 
https://github.com/MystenLabs/sui-operations/actions/runs/6632377485
for future ref - previous [PR]( https://github.com/MystenLabs/sui/pull/14383) attempt for this change
---
=> [docker] add sui-tool to sui-tools docker image

external-crates/move-execution/vm-rework/move-vm/runtime/src/interpreter.rs
add allow-unused-variable to silence warnings that occur due to different compilation flags. This is fine as the allows are added to a wip branch vm-rework
---
=> cherrypick fix

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/mod.rs, crates/sui-graphql-rpc/src/context_data/package_cache.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_type.rs, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Use PackageCache to calculate type layouts, and use this information to serve requests (derive type layouts from type tags, and returned structured representations of Move data).
This also eliminates some unused methods for fetching packages from the DB Data Provider.
Integration with GraphQL also requires introducing a new scalar type to represent `MoveTypeLayout`s, and a function to map from the native version of that type to the GraphQL version.
Tested with GraphiQL:
- #14376 
- #14377 
- #14378 
- #14319
=> [GraphQL] Integrate PackageCache

crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
Now we have serialized tests, we can enable cluster db dependent tests
e2e test
---
=> [rgaphql/rpc] easy: re-enable cluster

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_29.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_30.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_29.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_30.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_30.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
These were mistakenly released on top of existing cherrypicked v29 in devnet.
=> Move narwhal cert v2 and random beacon to a new protocol version.

crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_package.rs
Use `sui_graphql_rpc::error::Error` instead of `async_graphql::Error`.
```
```
=> [GraphQL/EASY] Use crate's error type

crates/sui-core/src/authority/authority_store.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-types/src/execution.rs, crates/sui-types/src/storage/mod.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/linkage_view.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/latest/sui-adapter/src/type_layout_resolver.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/linkage_view.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/type_layout_resolver.rs, sui-execution/vm-rework/sui-adapter/src/programmable_transactions/linkage_view.rs, sui-execution/vm-rework/sui-adapter/src/temporary_store.rs, sui-execution/vm-rework/sui-adapter/src/type_layout_resolver.rs
AuthorityStore should not care about Move modules. This can be done because we can retrieve modules as long as a type has BackingPackageStore trait which could fetch package objects.
Doing so forces us to not depend on the store directly as a module store.
This allowed me discover a place in RPC/indexerv0 where we forgot to use the module cache but went to the store directly. Fixed it.
CI
---
=> Remove module traits from AuthorityStore

crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs
This PR has the source service monitor all chains for upgrades; previously only the local network was monitored.
Note: I tested these changes for about ~1 week on a separate live instance to see stability / proneness to losing connections or erroring, and it has been stable.
Added tests.
---
=> move: source service watches multiple chains for upgrades

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_30.snap
Enable transaction effects v2 on testnet as well.
It has been working well on devnet.
---
- [x ] protocol change
- [x ] breaking change for FNs (FN binary must upgrade)
- [x ] breaking change for validators or node operators (must upgrade binaries)
=> Enable transaction effects v2 on testnet

crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/cluster.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
Refactors some things so we uss DB over RPC 1.0 in tests
Existing
---
=> [graphql/rpc] use db over rpc 1.0 in tests

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/metrics.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs
Adds DB query cost limit to the configs which will be enforced in subseq PRs
Existing 
---
=> [graphql/rpc] easy: introduce db query cost limit to config

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-indexer/src/apis/governance_api_v2.rs, crates/sui-indexer/src/apis/mod.rs
This PR implements the estimated reward for Stake by leveraging indexer's governance api. 
Manually. See figure.
---
=> [graphql/rpc] add estimated reward for Stake

crates/sui-single-node-benchmark/move_package/sources/benchmark.move, crates/sui-single-node-benchmark/src/command.rs, crates/sui-single-node-benchmark/src/main.rs, crates/sui-single-node-benchmark/src/tx_generator/move_tx_generator.rs, crates/sui-single-node-benchmark/src/tx_generator/non_move_tx_generator.rs, crates/sui-single-node-benchmark/src/workload.rs, crates/sui-single-node-benchmark/tests/smoke_tests.rs
This PR updates the sui-single-node-benchmark's workload such that there is a fair comparison between non-Move and Move workload. Specifically it makes the num_input_objects a common parameter that can be specified in both non-Move and Move mode.
CI
---
=> [benchmark] Update Move workload

crates/sui-core/src/authority.rs, crates/sui-core/src/execution_driver.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-core/src/unit_tests/transaction_manager_tests.rs
https://github.com/MystenLabs/sui/pull/11269 by @andll was rolled back because of drop in throughput. At that time anemo was using very small udp buffer, where any operation increasing transaction latency causes throughput drop (e.g. batching writes in consensus handler). Now the anemo issue has been fixed, so rolling the change forward.
`cargo run --release --bin sui-single-node-benchmark -- --component with-tx-manager no-move`
shows increase from 20k -> 26k TPS.
---
=> [Sui] Roll forward parallelizing spawning tasks to execute transactions

crates/sui-graphql-rpc/src/cluster.rs, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs
Both server builder and example server have similar logic.
This PR condenses them
Existing
---
=> [graphql/rpc] cleanup duplicate logic in server creation

crates/sui-graphql-rpc/examples/transaction_block_connection/before_after_checkpoint.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/epoch.rs
Modify querying mechanism for epoch.transactionBlockConnection per feedback. Query now completes under 2 seconds (previously would run >10 or forever). Previously, to fetch transactions for an epoch, we made a query for transactions whose checkpoint_sequence_number were between the first and last checkpoint ids of the epoch. Even though this filtering is done on an index, the filer causes some slowness if the distance between the two checkpoints are significant enough since we order the results by tx_sequence_number. This change fetches the first tx_sequence_number from the first checkpoint and the last tx_sequence_number from the last checkpoint, so now the filtering and ordering are both done on tx_sequence_number
manually run same queries
---
If your changes are not user-facing and not …
=> [graphql] address epoch.transactionBlockConnection slow querying

Cargo.lock, crates/sui-snapshot/src/reader.rs, crates/sui-storage/src/lib.rs, crates/sui-tool/Cargo.toml, crates/sui-tool/src/commands.rs, crates/sui-tool/src/lib.rs, crates/sui-tool/src/main.rs
- Optimize checkpoint summary sync + verification
- Rather than blocking on verification during summary sync, which can be slow as it requires that we sync in order, instead sync all checkpoint summaries, and then locally verify.
- This optimization moves checkpoint summary sync and verification from 3.5 hours to ~20 minutes, as measured against testnet `epoch_125` snapshot
- Optimize state accumulation
- Parallel divide and conquer partial accumulators (per file partition), then union 
- This speeds up accumulation from 3.2 hours to 20 minutes (for same benchmark as above)
-  Introduce early termination on snapshot verification failure
- Introduce `verbose` flag, which, when not set, sets log level to `off` for cleaner status output  
- Factor out snapshot accumulation and object …
=> [formal snapshots] Optimize and polish

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
Simple refactor that splits querying into two parts, building the query and actually executing it. This is done to support making an explain call on the query fragment before every query is actually executed
Manually ran all of our examples
---
=> [graphql] split queries into build and execution

apps/explorer/src/pages/object-result/views/ObjectView.tsx
- Add SUINS name resolver for object page
- https://mysten.atlassian.net/browse/APPS-1715
---
=> [Explorer]: Add suins address resolver on object page

crates/sui-verifier-transactional-tests/tests/one_time_witness/wrong_field_type.exp, crates/sui-verifier-transactional-tests/tests/one_time_witness/wrong_field_type.mvir, external-crates/move/move-compiler/src/sui_mode/typing.rs, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/init_many_wrong_parameters.exp, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/init_many_wrong_parameters.move, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/init_unbound_type.exp, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/init_unbound_type.move, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/many_fields_invalid.exp, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/wrong_field_type.move, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/wrong_field_type_and_extra_field.move, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/wrong_field_type_and_extra_field_with_init.exp, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/wrong_field_type_and_extra_field_with_init.move, external-crates/move/move-compiler/tests/sui_mode/one_time_witness/wrong_field_type_with_init.exp
- Fixed bug with OTW checks
- Improved init error messages
- Added tests
---
This release fixes a bug in the Sui mode of the Move compiler that categorized certain structs erroneously as one-time witnesses.
=> [sui-mode][move-compiler] Fixed init bug. Improved other cases

external-crates/move/move-compiler/src/cfgir/optimize/constant_fold.rs, external-crates/move/move-compiler/src/typing/core.rs
Follow up on small nits on PR that accidentally didn't get landed.
Same as before.
---
=> [move] cgswords/const in const nits

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
Bound the number of fragment definitions
Manual, coming up
---
=> [graphql/rpc] limit num fragment defs

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/db_query_cost.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
Now that we've split out query building from execution, we can run a cost analysis through db explain, and stop early if it exceeds query cost limits set in config
Manual testing, making sure existing tests pass
---
=> [graphql] query costing

crates/sui-graphql-rpc/src/server/builder.rs
GET request on `{url}/schema` will now return the pretty schema,
Manual
---
=> [graphql/rpc] get schema from url

Cargo.lock, crates/sui-config/src/node.rs, crates/sui-core/Cargo.toml, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/test_utils.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-core/src/unit_tests/execution_driver_tests.rs, crates/sui-node/src/lib.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui-types/src/error.rs
This PR enhances our current system overload detection to also include the scenario where the transactions depending on an object are not great in the count, but lengthy in execution. More precisely, we keep track of how long each transaction has been in the execution queue and use this age as a proxy for the hotness of the object when determining whether to reject a transaction or not. 
I also added a field in the node config to make this threshold configurable and easier to test. We can also move other similar numbers here as well.
Added a test.
---
Enhance our …
=> Check system overload using txn age in queue

.github/actions/diffs/action.yml, .github/workflows/rust.yml, examples/move/first_package/sources/example.move
Move tests are run as part of the Rust tests for the Sui Framework, but they should also be run when there are only Move changes.
Surfaced because a recent PR (#14429) Moved some Move tests causing CI to fail on `main`, and this wasn't picked up because diff tests hadn't been run.
CI
=> [CI] Ensure Move Tests are run when Move files change

crates/sui-transactional-test-runner/src/args.rs, external-crates/move/move-command-line-common/src/parser.rs, external-crates/move/move-command-line-common/src/values.rs
- Struct value parsing was broken and incorrect, since it sorted the fields
- Replaced with a simple runtime struct representation parser
- Tested in an upcoming PR
---
=> [transactional-tests] Fix struct parser

crates/sui-move/src/prove.rs
People keep trying to use Move Prover with Sui and there is currently no easily accessible place where the current level of support is mentioned. Adding a warning at the time when Prover is ran seems like a reasonable thing to do here.
Verified that the warning is printed.
---
A warning about current level of Move Prover support for Sui is now printed when the Prover is ran.
=> [move-prover] Print warning about the level of Prover support for Sui

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Field to get the BCS representation of a package's modules.  The decision to only output the modules, rather than the whole package struct was done to match the format that modules take when they are passed in to the network, during publish and upgrade transactions.
Tested in GraphiQL:
And using cURL:
```
curl -LX POST "http://127.0.0.1:9001" \
--data-raw '{
"query": "{ object(address: \"0x2\") { asMovePackage { bcs } } }"
}' \
| jq  -r .data.object.asMovePackage.bcs
| base64 -d
| hexdump -C
```
- #14422
=> [GraphQL/MovePackage] BCS field

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Lists the packages transitive dependencies.  Exposing this as its own field because the BCS representation of a package doesn't contain this information (it contains only the modules).
This maps how this field is represented in RPC 1.0
Tested with GraphiQL:
- #14422 
- #14423
=> [GraphQL/MovePackage] Linkage Field

crates/sui-analytics-indexer/src/handlers/package_handler.rs, crates/sui-analytics-indexer/src/tables.rs
As title says, currently this field is missing which makes it hard to join packages with transactions table
=> Add txn digest to package table

doc/src/learn/cryptography/sui-move-signatures.md
I added the public keys as inputs to the examples for BLS verification, since they were missing.
---
=> fix: include `pk` in `bls12381_*_verify` examples

crates/sui-e2e-tests/tests/protocol_version_tests.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_30.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_30.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_30.snap, crates/sui-types/src/object.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- has_public_transfer is conceptually static, but is not for core types due to in-place upgrades
- The flag originally existed to avoid having to load the VM in the very early days of Sui. This is no longer the case and the type is loaded anyway. So we should just recompute the flag.
---
=> [execution] Recompute has_public_transfer on load

crates/sui-graphql-rpc/src/server/builder.rs
Adds basic health checks to `/health`
Sample output
```
{"status": UP,"uptime": 47.347985292,"checks": {"DB": UP,}}
```
Manual
---
=> [graphql/rpc] add health checks

external-crates/move/move-compiler/src/diagnostics/codes.rs, external-crates/move/move-compiler/src/parser/lexer.rs, external-crates/move/move-compiler/src/parser/syntax.rs, external-crates/move/move-compiler/tests/move_check/parser/constant_type_annotation_invalid.exp, external-crates/move/move-compiler/tests/move_check/parser/constant_type_annotation_invalid.move
This adds a slightly more-informative error message to constant parsing failures based on feedback from @tedks 
Added a new test
---
=> [move] improve better error message for const bindings

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_30.snap, narwhal/primary/src/certificate_fetcher.rs, narwhal/primary/src/tests/certificate_fetcher_tests.rs
This enables faster catchup, which seems to work fine in private testnet.
---
=> [Narwhal] enable cert v2 on testnet

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Completing the set of "raw" fields for MovePackage with a field exposing type origins.
Tested using GraphiQL:
- #14422 
- #14423 
- #14424
=> [GraphQL/MovePackage] Type Origins Field

docs/content/guides.mdx
- Missing "out" in first paragraph.
- Rewording intro sentence for "Guides by role", which was hard to scan (for me).
- Remove references to the "monorepo" in the section about Environment set-up (environment set-up no longer requires forking the Sui repo).
- Clean-up whitespace (editor did this automatically).
:eyes:
=> [Docs] Guides Overview Tweaks

docs/content/concepts/object-ownership/immutable.mdx, docs/content/concepts/sui-move-concepts/patterns/id-pointer.mdx, docs/content/guides/developer/first-app/publish.mdx, docs/content/guides/developer/getting-started/sui-environment.mdx, docs/content/references/cli/client.mdx, docs/content/references/cli/move.mdx
Examples in `sui_programmability` are out-of-date, and we should prefer referencing examples in `examples/move` instead.  This PR gets updates most references to `sui_programmability` in the docs, leaving only two to be picked up in follow-ups:
- Flash Lender
- Shared vs Owned Objects
Where in both these cases more examples need to be modernised and ported to `examples/move` to remove the existing reference.
:eyes:
=> [Docs/Examples] Purge References to `sui_programmability`

docs/content/guides/developer/getting-started/sui-install.mdx
- Make the order of "Next Steps" match the order in the sidebar/IA.
- Reduce repetition of references to "start"-ing.
- Re-word bullet about the "Sui CLI" reference -- that page is not a guide, so it needs a different call-to-action from the other next steps (to make it clear what the action is -- i.e. just read this page).
:eyes:
=> [Docs/Install Sui] Tweak "Next Steps"

docs/content/guides/developer/first-app/publish.mdx
Lists were indented too far and were being formatted as codeblocks.
:eyes:
=> [Docs/Publish] Fix list formatting

docs/content/concepts/sui-move-concepts/init.mdx
- Rename from "Init" to "Module Initializers" for clarity
- Fix formatting issue with lists looking like code blocks
- Fix inconsistency in documentation about `init`'s signature -- it can have more than one parameter.
- Clarify interaction between `init` and upgrades.
:eyes:
=> [Docs/Init] Tweaks for Module Initializers

docs/content/concepts/sui-move-concepts/entry-functions.mdx
The content here was stale -- from a time before PTBs and other semantic changes.  Rewrite this page to:
- Explain how `entry`, `public` and PTBs interact.
- Update the example in the docs to match the modernised example in the repo.
:eyes:
=> [Docs/Entry] Rewrite page

docs/content/concepts/sui-move-concepts/one-time-witness.mdx
Clarify OTW conditions (it's allowed to have one field, it is required to have the `drop` ability).  Other changes are just wording clarifications.
👀
=> [Docs/OTW] Tweak

docs/content/concepts/sui-move-concepts/patterns/witness.mdx
Witnesses are not about proving ownership -- they are proof that a thing happened, usually a privileged operation (that not anyone could witness).
Also fix the list formatting (was being interpreted as a code block).
:eyes:
=> [Docs/Witness] Reword

crates/sui-source-validation-service/src/lib.rs
Was debugging why the metrics weren't showing up and it turns out I hardcoded [`9814` instead of `9184`](https://github.com/MystenLabs/sui/pull/14448#discussion_r1373622863) 🤦 🤦‍♀️ 
non-functional change, existing test
---
=> move: fix metrics port for source service (easy)

docs/content/concepts/sui-move-concepts/patterns/hot-potato.mdx, examples/move/flash_lender/Move.toml, examples/move/flash_lender/sources/example.move
- Move code to `examples/move`.
- Remove use of `public entry`.
- Wrap comments at 80 characters.
- Move tests inline (like other examples in `examples/move`).
- Add headers for sections
- Update docs to refer to new location.
```
examples/move/flash_lender$ sui move build
examples/move/flash_lender$ sui move test
```
=> [Example/Flash Lender] Modernise example

docs/content/concepts/dynamic-fields/tables-bags.mdx
This section was a hold-over -- this limitation no longer exists (and has not existed for a long time).
Also updated the relevant section on containment checks.
:eyes:
=> [Docs/Bags] Remove "Current Limitations" section

examples/move/color_object/sources/example.move, examples/move/dynamic_fields/sources/example.move, examples/move/escrow/sources/example.move, examples/move/first_package/sources/example.move, examples/move/hero/sources/example.move, examples/move/simple_warrior/sources/example.move, examples/move/trusted_swap/sources/example.move
Two new recent changes to the Move toolchain have introduced some warnings when building/testing the examples:
- The lint that picks up unnecessary `&mut`.
- Some change that means that imports are now being analysed even if they don't get used, which caused non-test builds to fail on imports of `test_scenario`.
This PR updates the examples to build and test cleanly.
```
sui-framework-tests$ cargo nextest run
```
=> [Examples] Clean-up Move Warnings/Lints

doc/src/build/sui-object-display.md
fix display docs error ，change  transfer to public_transfer
N/A
---
=> [docs]Update sui-object-display.md  transfer to public_transfer

crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Simplify how we build genesis in transactional-test-runner.
The genesis building process in the test authority builder already loads the corresponding packages and objects. We don't need to do them in the transactional test runner init. They are redundant. Remove all of them.
Also fix a bug in test authority builder where we didn't pass along the protocol version.
CI
---
=> Simplify transactional-test-runner genesis build

docs/content/references/cli/keytool.mdx
Fixes the example in the CLI keytool docs page.
---
=> [docs] fix mismatch in keytool CLI example

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_30.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_30.snap
Disabling the throughput aware consensus submission for all environments
---
=> [chore] disable the throughput aware consensus submission

apps/explorer/src/pages/object-result/views/ObjectView.tsx, apps/explorer/src/ui/Description.tsx
Add hover tooltip for object type
---
=> [Explorer]: Add hover tooltip

crates/sui-source-validation-service/src/lib.rs
Metrics not getting picked up, this is probably the issue.
N/A
---
=> move: source service exposes metrics on 0.0.0.0

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/extensions/timeout.rs, crates/sui-graphql-rpc/src/server/builder.rs
Exposes request timeout setting in config.
Existing
---
=> [graphql/rpc] expose timeout in limits config

crates/sui-source-validation-service/src/lib.rs
Display the network when a websocket connection fails
N/A for debugging
---
=> move: better websocket error message for source service (easy)

crates/sui-framework-tests/src/unit_tests.rs
A recent change to the toolchain caused the examples to fail to build, because they `use`-d `test_scenario` without guarding the import with `#[test_only]` (fixed in #14512).
Previously this seemed to work because imports were largely ignored unless the imported value was referenced, and at that point, there may be an unbound reference issue.
Now, the imports seem to be eagerly resolved by the compiler, which causes a problem because `test_scenario` is itself a `#[test_only]` module.
This PR introduces an extra step to the CI support for Move tests to also try building example packages in non-test mode, to make sure that continues to work.
This extra step has only been introduced for example packages, because the system package builds are already covered by CI (they already need to build …
=> [Move/Tests] Ensure examples build outside of test mode

crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
This counts fragments in the query complexity
Fragments can be defined but not used, causing them to still be parsed. We will limit these early on too in subseq PR.
Manual, coming next
---
=> [graphql/rpc] add fragment limits inline

crates/sui-analytics-indexer/src/handlers/object_handler.rs, crates/sui-analytics-indexer/src/tables.rs
As title says, these fields are currently missing on the objects table
=> Add coin type and coin balance in pipeline v2 object table

crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-types/src/object.rs
`as...` fields are special in that they are fallible conversion operators: It's a valid query to request stake-specific information on an object that isn't a `StakedSui`.
This PR changes the behaviour of the `asStake` to match this pattern. It also tweaks `asCoin` to follow a similar coding pattern.
Tested with GraphiQL:
- #14422 
- #14423 
- #14424 
- #14425
=> [GraphQL/Object] asStake is allowed to fail

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/types/json.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap, crates/sui-types/src/object.rs
Implementing a feature request from @hayes-mysten to have a Move value representation that is more directly "JSON-like" (where Move concepts map to directly to their JSON counterpart without any extra boilerplate).
```
sui-graphql-rpc$ cargo nextest run -- types::move_value::tests
```
Tested on GraphiQL:
- #14422 
- #14423 
- #14424 
- #14425
- #14485
=> [GraphQL/MoveObject] JSON field

crates/sui-indexer/src/store/pg_indexer_analytical_store.rs
turns out that although DB analyze samples, it is very slow and cause timeout.
see this in logs
```
2023-10-31T03:14:08.324921Z ERROR sui_indexer::processors_v2::processor_orchestrator_v2: Indexer move call metrics processor failed with error ErrorWithContext("Failed reading transactions from PostgresDB", PostgresReadError("canceling statement due to statement timeout")), retrying in 5s..
```
local verifies without DB analyze, the estimated count takes less than 100ms to finish
```
SELECT reltuples::bigint AS estimated_count FROM pg_class WHERE relname='objects';
estimated_count
-----------------
22882962
(1 row)
Time: 85.789 ms
```
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add …
=> indexer v2 analytical: skip analyze on estimated count query

docs/content/concepts/sui-move-concepts.mdx
This one's a large rewrite:
- Refer to "Core Move" and "Diem Move" as "Move on Diem", everywhere.
- Reword section explaining scaling issues with global storages and contracts that store large mappings, and the explanation of how global storage works -- the original explanations didn't really seem to hold whatever for me.
- Added a link to the `entry` function docs.
:eyes:
=> [Docs/Move] Reword

crates/sui-source-validation-service/src/lib.rs
`Info` log showing up every minute when the the service is scraped, noisy and not needed right now.
N/A
---
=> move: remove noisy trace logs in source service (easy)

crates/sui-open-rpc/spec/openrpc.json, crates/sui-open-rpc/src/examples.rs
`suix_getCoinMetadata` was using the internal Rust `CoinMetadata` type in the example, rather than the type actually used by JSON RPC (`SuiCoinMetadata`).
`suix_getStakes` returns a list, rather than a single delegated stake structure.
Make calls to the relevant APIs in fullnode, and make sure the output matches the example:
```shell
$ curl -LX POST  "https:/fullnode.mainnet.sui.io:443" \
--header 'Content-Type: application/json'     \
--data-raw '{
"method": "suix_getCoinMetadata",
"id": 1,
"params": ["0x2::sui::SUI"]
}' | jq  -C .
$ curl -LX POST  "https:/fullnode.mainnet.sui.io:443" \
--data-raw '{
"method": "suix_getStakes",
"id": 1,
"params": ["'$ADDRESS'"]
}' | jq  -C .
```
=> [Docs/JSON-RPC] Fix suix_getCoinMetadata, suix_getStakes examples

.changeset/orange-insects-wave.md, sdk/dapp-kit/src/components/ConnectButton.tsx, sdk/dapp-kit/src/components/connect-modal/ConnectModal.tsx
I noticed a hack in one of our dApps that works around a CSS ordering issue with dApp-kit styles + application styles. I don't think we should apply style resets to custom trigger buttons; we should only apply the style marker to the button provided by `ConnectButton`.
Hacky workaround pattern:
```
<Button
className="flex-1"
variant="outline"
onClick={() => {
setOpen(true);
}}
>
<div className="flex gap-4 items-center">
<div>Connect Wallet</div>
</div>
</Button>
<ConnectModal
trigger={<></>}
open={open}
onOpenChange={(open) => setOpen(open)}
/>
```
Ideal pattern:
```
<ConnectModal
trigger={
<Button
className="flex-1"
variant="outline"
>
<div className="flex gap-4 items-center">
<div>Connect Wallet</div>
</div>
</Button>
}
/>
```
- Made a custom button and tested that no resets were being …
=> [dapp-kit] don't apply CSS resets to custom triggers in the connect modal

crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/consensus_types/committee_api.rs, crates/sui-core/src/consensus_types/consensus_output_api.rs, crates/sui-core/src/consensus_types/mod.rs, crates/sui-core/src/lib.rs, crates/sui-core/src/scoring_decision.rs
Starting a little bit on the consensus handler refactoring, and send out a small PR first just to make sure everyone is ok with the direction. As you can see in the PR, we are adding a bunch of types inside consensus-types as abstract trait types, including the Committee and ConsensusOutput, and then start implement functions on them for Narwhal.
The consensus handler code then calls these functions.
This PR focuses on abstracting the types needed by the reputation score updates.
CI
---
=> Make reputation score abstract

crates/sui-core/src/generate_format.rs, crates/sui-types/src/effects/mod.rs
An attempt to keep effects v2 type private through `pub use`.
CI
---
=> Make effects v2 type private

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs, crates/sui-types/src/transaction.rs
This API should no longer be used given that we have a new version.
Leaving it there would only give space for making mistakes. In fact we already have callers to it that's already out of dated.
Remove it.
CI
---
=> Deprecate is_change_epoch_tx

crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs, crates/sui-macros/src/lib.rs
This issue was found while working on pruning tombstone (#14373). Based on observation, the highest executed checkpoint's effects and objects are still used in the state accumulator, so we can't prune it.
It wasn't causing test issue before probably because we are using `ignore_range_deletions` option when issuing range deletes, so some of the objects are still available after pruning.
Send this PR out separately while I'm still making that PR work, and it seems unrelated to tombstones.
After adding a test path (basically doing a pruning and then compaction before state accumulation), here is the result:
Without the 1 line fix, 59 tests failed with missing object during state accumulation:
With the 1 line fix, all passed:
How did you …
=> Making sure that we don't prune the checkpoint corresponding to the highest executed watermark

crates/simulacrum/src/store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs, crates/sui-replay/src/replay.rs, crates/sui-single-node-benchmark/src/mock_storage.rs, crates/sui-storage/src/package_object_cache.rs, crates/sui-transaction-checks/src/deny.rs, crates/sui-types/src/in_memory_storage.rs, crates/sui-types/src/storage/mod.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/linkage_view.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/latest/sui-adapter/src/type_layout_resolver.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/linkage_view.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/type_layout_resolver.rs
This PR makes the BackingPackageStore trait ready to support object/package cache.
BackingPackageStore used to have two APIs, get_package and get_package_object. Both returns value (MovePackage and Object). This will make it very inefficient to support a package cache because we would have to clone all the time.
This PR makes it such that BackingPackageStore trait now only has one API, which is get_package_object. It returns an Arc of package object that can be passed around cheaply.
The primary change is in storage/src/mod.rs. All other changes are due to the API change.
CI
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the …
=> BackingPackageStore trait returns Arc

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/consensus_types/consensus_output_api.rs, narwhal/types/src/primary.rs
This PR completes the `ConsensusOutputAPI` trait, and makes ConsensusHandler consensus-type agnostic.
There are a few changes that made this possible:
1. The biggest change is the `into_transactions()` function, which hides the details of the ConsensusOutput data structure and returns all transactions from it.
2. Introduced the `intro_transactions()` function to `Batch` so that we can get rid of unnecessary clones. In fact, all previous clones were removed.
3. Removed the `certificate` field from `SequencedConsensusTransaction` type, because we don't need it. Instead we only need the authority index of the origin of the certificate.
4. Added `handle_consensus_output_internal` which operates on common types only, and hence can be called from both Narwhal and Mysticeti.
5. The only semantic …
=> Make ConsensusHandler abstract

crates/sui-core/src/consensus_validator.rs, narwhal/node/src/primary_node.rs, narwhal/primary/src/certificate_fetcher.rs, narwhal/primary/src/primary.rs, narwhal/primary/src/proposer.rs, narwhal/primary/src/synchronizer.rs, narwhal/primary/src/tests/certificate_fetcher_tests.rs, narwhal/primary/src/tests/proposer_tests.rs, narwhal/primary/src/tests/synchronizer_tests.rs, narwhal/worker/src/handlers.rs
Currently, certificates fetched during catchup are processed and accepted one-by-one, same as normal certificate handling. This turns out to be a throughput bottleneck for catching up. This PR includes one major and a few minor changes to improve the catchup throughput.
Main change: take the lock on `state` once per batch of certificates in `process_certificate_with_lock()`, instead of once per certificate. `tokio::sync::Mutex` seems to be really slow as the lock on `state`, taking 5 ~ 10s for 2000 lock operations.
Other changes:
- Increase channel size in Narwhal across the board from 1k to 10k, to avoid filling the channels too often. I did not see very noticeable memory usage increase.
- Avoid using blocking thread for verifying user signatures in transactions, which should be …
=> [Narwhal] speed up batch processing of fetched certificates

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Adds doc comments for the `epoch` and `validatorSet` types.
---
=> [graphql/rpc]add epoch doc comments

crates/sui-core/src/authority/authority_store.rs, crates/sui-storage/src/package_object_cache.rs, crates/sui-transaction-checks/src/lib.rs, crates/sui-types/src/storage/mod.rs
This PR puts the package cache into the AuthorityStore and uses it in the production path.
It improves single node benchmark baseline throughput by about 30-40%.
The only thing that's tricky is that we must force evict the system packages after the execution of epoch change transaction.
CI
---
=> Use package cache in prod

docs/content/standards/kiosk.mdx
- Removes all Kiosk SDK examples as:
1. They are outdated (using the first version of the SDK)
2. We already have in-depth documentation for the SDK in the TS doc site. 
- Adds a link to the SDK website. 
@ronny-mysten Please feel free to place it somewhere else if it fits better.
---
=> Removes outdated SDK examples, link to SDK docs

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap
Make sure all the limits in the `Limits` type are exposed via the `ServiceConfig` GraphQL type.
Also spotted that none of the `ServiceConfig` APIs need to return `Result`s because they never fail.
Tested on GraphiQL:
=> [GraphQL/Config] Expose more limits

crates/sui-indexer/src/models_v2/address_metrics.rs, crates/sui-indexer/src/models_v2/transactions.rs, crates/sui-indexer/src/processors_v2/address_metrics_processor.rs, crates/sui-indexer/src/processors_v2/move_call_metrics_processor.rs, crates/sui-indexer/src/processors_v2/processor_orchestrator_v2.rs, crates/sui-indexer/src/store/indexer_analytical_store.rs, crates/sui-indexer/src/store/pg_indexer_analytical_store.rs
various perf and fixes
- turns out fetching txns of 1k checkpoints was very slow and caused timeouts, thus we want to read only necessary columns
- a couple of fixes: retrial on each processor; no conflict do nothing when binary resumes.
local run analytical worker
---
=> indexer v2 analytical: partial tx fetching and fixes

docs/content/concepts/transactions.mdx, docs/content/sidebars/concepts.js
Made these changes from your feedback on 14530, committed them, but failed to push.
Local
---
=> Changes not pushed to earlier PR

Cargo.lock, Cargo.toml, crates/sui-core/Cargo.toml, crates/sui-core/src/consensus_validator.rs, crates/sui-core/src/generate_format.rs, crates/workspace-hack/Cargo.toml, deny.toml, narwhal/worker/src/client.rs
This PR imports mysticeti and implements `BlockValidator` for `SuiBlockValidator`. The former is the counterpart of `TransactionValidator` in narwhal, used to verify the block contents. The major verification logic is extracted into a shared function `validate_transactions`.
Also updated `futures` and `zeroize`'s config to align with mysticeti's. 
---
=> [mysticeti] add SuiBlockValidator

external-crates/move/move-compiler/src/cfgir/cfg.rs, external-crates/move/move-compiler/src/hlir/translate.rs, external-crates/move/move-compiler/tests/move_check/typing/loop_result_type.exp
This simplifies the HLIR lowering to make things a bit cleaner, and reflows a little how the compiler handles dead code warnings to accommodate that.
Revised and run tests
---
=> [move 2024] simplify hlir lowering rewrite

crates/sui-graphql-rpc/schema/draft_target_schema.graphql
These fields are only relevant once we have a generic `Query.node` query, so let's add these back when we have those.  This field was initially mistakenly added because it was thought to be relevant for cursor APIs.
:eyes:
=> [GraphQL/RFC][EASY] Remove `ID` fields (for now)

crates/sui-indexer/migrations_v2/2023-08-19-044026_transactions/up.sql, crates/sui-indexer/migrations_v2/2023-10-06-204335_tx_recipients/down.sql, crates/sui-indexer/migrations_v2/2023-10-06-204335_tx_recipients/up.sql, crates/sui-indexer/migrations_v2/2023-10-06-204340_tx_senders/down.sql, crates/sui-indexer/migrations_v2/2023-10-06-204340_tx_senders/up.sql, crates/sui-indexer/src/models_v2/transactions.rs, crates/sui-indexer/src/models_v2/tx_count_metrics.rs, crates/sui-indexer/src/processors_v2/network_metrics_processor.rs, crates/sui-indexer/src/schema_v2.rs, crates/sui-indexer/src/store/indexer_analytical_store.rs, crates/sui-indexer/src/store/pg_indexer_analytical_store.rs
without storing this, the analytical pipeline has to fetch the whole row of transactions, parse them back to `SenderSignedData` and `TransactionEffects` to count the success cmd, which oftentimes is very slow on DB reading 
for example this query takes 262272.070 ms, or > 4 min to finish, it will be worse on larger checkpoints:
```
select * from transactions where checkpoint_sequence_number > 6370000 and checkpoint_sequence_number <= 6380000;
```
while fetching 2 columns from same set of txns takes only 578.369 ms
```
select tx_sequence_number, checkpoint_sequence_number from transactions where checkpoint_sequence_number > 6370000 and checkpoint_sequence_number <= 6380000;
```
local run fullnode sync worker and analytical worker, verify that
- the transaction table is properly populated …
=> indexer v2 analytical: store command per tx for TPS calculation

crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/up.sql, crates/sui-indexer/src/apis/governance_api_v2.rs, crates/sui-indexer/src/apis/indexer_api_v2.rs, crates/sui-indexer/src/apis/transaction_builder_api_v2.rs, crates/sui-indexer/src/indexer_reader.rs
This PR enables struct type and `MatchAny` struct type filters for get_owned_objects method.
---
=> [indexer] add ability to use struct type filter for get_owned_objects

crates/sui-graphql-rpc/schema/draft_target_schema.graphql
Based on feedback that having to explicitly upcast (e.g. from `Coin`, to `MoveObject`, to `Object`) was annoying, this PR changes the schema so that accessing parent type fields is done via interfaces (each parent type comes with an accompanying interface).
`asX` fields are still used for downcasting, however, e.g. `MoveObject` has `asCoin`, `asStake`, etc.
This change required adopting a naming scheme for these accompanying interfaces, e.g. `Foo` is accompanied by `IFoo` (and this was retroactively applied to `ObjectOwner` which became `IOwner`).
Also cleans up some inconsistencies in the draft schema relative to the current planned schema:
- Dynamic Field related APIs have moved to the `IOwner` interface, to make it possible to query dynamic fields on wrapped objects (which can't …
=> [GraphQL/RFC] Changes to `asX` fields in Object type hierarchy

examples/move/object_bound/Move.toml, examples/move/object_bound/sources/object_bound.move
Implements an OBO - object-bound object for "transfer to object", similar to soulbound for accounts.
One funny detail (and the main reason for this PR) is what we called a Matryoshka-pattern where T is taken from ObjectBound, and then ObjectBound is wrapped into a Borrow. 
---
=> [Examples] Adds obo - object bound object

crates/sui-json-rpc-types/src/balance_changes.rs, crates/sui/src/client_commands.rs
Implements the Display trait for the `BalanceChange` type. This is part of a larger effort (and multiple PRs) in implementing a nice format output for `SuiTransactionBlockResponse` in the CLI, following @laura-makdah's excellent formatting in `SuiTransactionBlockEffects`.
---
Implements the `Display` trait for the `BalanceChange` type as part of a larger effort in implementing a good-looking format output for `SuiTransactionBlockResponse` in the CLI.
=> [cli] Implement Display for BalanceChange type

crates/sui-move/src/build.rs, crates/sui-move/src/unit_test.rs, crates/sui-source-validation-service/tests/tests.rs, crates/sui/src/client_commands.rs, crates/sui/tests/cli_tests.rs
Linter support was initially introduced as opt-in but it's time to make it opt-out - it's been over two weeks after this has been announced (blog post, Discord, Sui forum). Switching to opt-out has been vetted by @dariorussi, @sblackshear, and @tedks.
Verified that opt-out flag works in the CLI.
---
Recently introduced Sui linters are now enabled by default. Developers may see additional warnings without changing any of their code or compiler build/test/publish/upgrade options.
=> [move-compiler] Making the use of Sui linters opt-out

.changeset/weak-penguins-hunt.md, docs/content/guides/developer/app-examples/coin-flip.mdx, docs/content/standards/kiosk.mdx, sdk/kiosk/src/tx/kiosk.ts, sdk/typescript/src/builder/pure.ts
Introduces `txb.pure.id()` for more intuitive ID argument in PTB calls.
Applied it on Kiosk SDK & tests run successfully.
---
=> SDK - Adds `pure.id(..)`

Cargo.lock, crates/sui-analytics-indexer/src/handlers/transaction_handler.rs, crates/sui-graphql-rpc/src/types/move_type.rs, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/models_v2/display.rs, crates/sui-indexer/src/models_v2/events.rs, crates/sui-indexer/src/models_v2/objects.rs, crates/sui-indexer/src/types_v2.rs, crates/sui-types/Cargo.toml, crates/sui-types/src/base_types.rs, crates/sui-types/src/lib.rs, crates/sui-types/src/sui_serde.rs, external-crates/move/crates/move-core-types/src/account_address.rs, external-crates/move/crates/move-core-types/src/language_storage.rs, external-crates/move/crates/move-package/src/resolution/dependency_graph.rs, external-crates/move/crates/move-stdlib/src/natives/debug.rs, external-crates/move/crates/move-stdlib/src/natives/type_name.rs, external-crates/move/move-execution/v0/move-stdlib/src/natives/debug.rs, external-crates/move/move-execution/v0/move-stdlib/src/natives/type_name.rs
1. introduces to_canonical_display -> impl Display for AccountAddress, TypeTag, and StructTag on the move crate
2. implements to_canonical_string for sui_types::MoveObjectType
3. test cases that verify Object -> IndexedObject -> StoredObject -> Object conversion does not lose or result in the incorrect type string/ display
4. test cases to verify that parse_sui_struct_tag still works correctly
unit tests on conversion from sui_types::Object to IndexedObject to StoredObject. The dynamic fields path is a bit challenging to write a unit test for
---
=> [indexerv2] use canonical string with 0x prefix for types

docs/site/src/components/API/api-ref/method.js
There was a bug Stefan found where immediately after using the reference navigation, anywhere you clicked on screen caused the page to jump to the top. The click event is only meant for headings, so return from handler if the activated node name does not begin with H. 
Vercel
---
=> Fix API ref bug that caused screen to jump when clicked

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_handler.rs, crates/typed-store/src/rocks/mod.rs
Transactions may be deferred in each consensus round by providing either the future consensus commit or future random round to which the commit should be deferred.
When the given round arrives, all transactions that were deferred to that point in time are loaded from the DB and added to the set of transactions that arrived in the most recent commit.
=> Transaction deferral system

narwhal/config/src/lib.rs
Add default rate limits to RPC handlers, in case they are not set.
Private testnet.
---
=> [Narwhal] set default rate limits on RPC handlers

Cargo.lock, crates/sui-core/Cargo.toml, crates/sui-core/src/lib.rs, crates/sui-core/src/mysticeti_adapter.rs, crates/sui-types/src/error.rs, crates/test-cluster/src/lib.rs, crates/workspace-hack/Cargo.toml
Add a simple BlockHandler and `SubmitToConsensus` impl
not trivial to test without being wired up by Consensus Manager 
---
=> implement BlockHandler and SubmitToConsensus for mysticeti

crates/sui-config/data/fullnode-template-with-path.yaml, crates/sui-config/data/fullnode-template.yaml, crates/sui-config/src/node.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-node/src/lib.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/effects_v2.rs, crates/sui-types/src/effects/mod.rs
This PR implements the main logic of pruning sui object tombstones.
Given the fact that we are using range deletes and `ignore_range_deletions` read option to improve read performance, it makes tombstone deletion tricky because once a tombstone is deleted, we need to make sure that all prior versions of the object must also be deleted. Otherwise, it'll leak object. To not hurt performance much (pending performance evaluation), we decided to use scan-and-point-delete when encounter an object tombstone. In this case, we guarantee that all prior versions are not visible to readers after the deletion.
The tombstone pruning logic currently is only tested in unit test. I wanted to enable it in integration test, but the PR becomes messy. It will come up in a follow up PR.
Unit test: this PR …
=> Pruning object tombstones

Cargo.lock, crates/sui-core/Cargo.toml, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/consensus_types/consensus_output_api.rs, crates/sui-types/src/messages_consensus.rs, crates/workspace-hack/Cargo.toml, narwhal/types/src/consensus.rs
Implement ConsensusOutputAPI for CommittedSubDag in Mysticeti.
Instead of displaying the digest of consensus output, we now rely on the Display impl of the consensus output.
Also changed into_transactions() to transactions(), instead, which returns reference to the serialized bytes to avoid clones.
Left a few TODOs in the impl
CI
---
=> Implement ConsensusOutputAPI for mysticeti

crates/sui-config/data/fullnode-template-with-path.yaml, crates/sui-config/data/fullnode-template.yaml, crates/sui-config/src/node.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-node/src/lib.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/effects_v2.rs, crates/sui-types/src/effects/mod.rs
This reverts commit e9735471f528ce27562bc7e85c687284a21da7ae because of validator crash
```
ubuntu@lax-suival-2f0e8:~$ sudo bash -c "RUST_BACKTRACE=1 /opt/sui/bin/sui-node --config-path /opt/sui/config/sui-node.yaml"
thread 'main' panicked at crates/sui-node/src/main.rs:53:58:
called `Result::unwrap()` on an `Err` value: authority-store-pruning-config: missing field `enable-pruning-tombstones` at line 52 column 33
Stack backtrace:
0: sui_config::Config::load
1: sui_node::main
2: std::sys_common::backtrace::__rust_begin_short_backtrace
3: std::rt::lang_start::{{closure}}
4: std::rt::lang_start_internal
5: main
6: <unknown>
7: __libc_start_main
8: _start
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::result::unwrap_failed
3: sui_node::main
note: Some details …
```
=> Revert "Pruning object tombstones (#14373)"

external-crates/move/crates/move-compiler/src/editions/mod.rs, external-crates/move/crates/move-compiler/src/expansion/translate.rs, external-crates/move/crates/move-compiler/src/parser/ast.rs, external-crates/move/crates/move-compiler/src/parser/syntax.rs, external-crates/move/crates/move-compiler/tests/move_check/parser/nested_module_use.move, external-crates/move/crates/move-compiler/tests/move_check/parser/nested_module_use_invalid.exp, external-crates/move/crates/move-compiler/tests/move_check/parser/nested_module_use_invalid.move
This allows users to import modules all in one line, as:
```
use 0x42::{a::{A, Self as g, foo as f}, b::{Self as q, B, baz as bar}};
```
New test files
---
=> [move-compiler] implement nested module imports

crates/sui-json-rpc-types/src/sui_transaction.rs
Improves the formatting output of the `SuiGasData` type when a transaction response is displayed in the CLI.
---
Improved the formatting output of the gas data information shown in a transaction in the CLI.
=> [cli] nicer formatting of `SuiGasData` object

docs/content/references/sui-api/beta-graph-ql.mdx
Adds a brief paragraph in the GraphQL page in our docs website showing how to query the GraphQL instance through `curl`.  
Made sure the `curl` command works. 
---
Improved the GraphQL docs by adding a short paragraph on how to use `curl` to query the GraphQL service.
=> [docs/graphql] add information about using curl with GraphQL

doc/src/build/zk_login.md, docs/content/concepts/cryptography/zklogin.mdx
See above.
```
> wget -O - https://raw.githubusercontent.com/sui-foundation/zklogin-ceremony-contributions/main/download-test-zkey.sh | bash 
--2023-11-06 12:32:39--  https://raw.githubusercontent.com/sui-foundation/zklogin-ceremony-contributions/main/download-test-zkey.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 180 [text/plain]
Saving to: ‘STDOUT’
-                                               100%[=====================================================================================================>]     180  --.-KB/s    in 0s …
```
=> Update zk_login.md to include instructions for downloading devnet proving key 

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/server/builder.rs
Allows setting the the title of the IDE, which makes it easier to distinguish different envs esp for demo servers.
Manual
---
=> [graphql/rpc] add IDE title setting

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs
**Problem**: when issuing a query to fetch a transaction block, and its effects and checkpoint, the latest checkpoint in the system is always returned and not the checkpoint for that specific transaction block.
**Solution**: Pass the checkpoint sequence number from the indexer's transaction data to the GraphQL type. 
**Extra**: Remove old code related to the other data provider that we do not use anymore. 
---
=> [graphql/easy] fix fetching the right checkpoint for a tx block

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-indexer/src/apis/coin_api_v2.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/store/pg_indexer_analytical_store.rs
Went through the code and there seems to be a few more places where we should switch to using `to_canonical_string`.
---
=> [indexer][graphql] use to_canonical_string consistently for ObjectID and StructTag

Cargo.lock, crates/sui-core/Cargo.toml, crates/sui-core/src/consensus_manager/mod.rs, crates/sui-core/src/consensus_manager/mysticeti_manager.rs, crates/sui-core/src/consensus_manager/narwhal_manager.rs, crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs, crates/sui-core/src/unit_tests/narwhal_manager_tests.rs, crates/workspace-hack/Cargo.toml
This PR is:
* abstracting via a guard the acquisition of locking, metric reporting & logging when start/shutdown the consensus engines to be used by the managers
* implementing the start/shutdown methods for the MysticetiManager to start/shutdown the mysticeti validator. Necessary type conversations take place. Some assumptions have been made for now for the integration reasons (some TODOs have been left)
* a simple test has been added for the MysticetiManager - will add more cases on follow up PRs
**Note:** a few types on Mysticeti had to be opened up to allow initialising and pass them to the mysticeti validator. PR here https://github.com/MystenLabs/mysticeti/pull/36
Next steps
CI
---
If your changes are not user-facing and not a breaking change, you can skip the following section. …
=> [refactor] wire Mysticeti in MysticetiManager

crates/sui-analytics-indexer/src/handlers/mod.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-types/src/effects/mod.rs
Added a new API to effects to return all tombstones.
Revert all tombstones during transaction revert.
---
=> Revert unwrapped and deleted tombstones during tx revert

crates/sui-benchmark/src/drivers/bench_driver.rs, crates/sui-benchmark/src/lib.rs
This was causing simtest failures due to the following sequence of events:
- Client submits a tx, fails to gather an effects cert, but the tx is included in the final checkpoint
- after reconfiguration, the client retries. validators re-sign the effects, but client fails to accept the new effects cert because it does not yet know about the new committee
- validators prune tx
- client retries again
- client now gets ObjectVersionUnavailableForConsumption
The transaction can never succeed (from the client's POV) after this point, so it retries forever, generating enough errors to cause the test to fail.
=> Don't retry non-recoverable errors in benchmark

narwhal/primary/src/primary.rs, narwhal/primary/src/state_handler.rs, narwhal/primary/src/tests/state_handler_tests.rs, narwhal/types/src/primary.rs
This avoids the cost of deserializing the messages in places where the contents are not needed.
=> Change `fastcrypto` types in `SystemMessage` to opaque bytes

.changeset/silent-trains-whisper.md, sdk/dapp-kit/src/components/styling/StyleMarker.tsx, sdk/dapp-kit/test/components/ConnectButton.test.tsx
It looks like I introduced a pretty bad bug in the last version of dapp-kit where clicking the connect button does nothing since I'm not passing props through the `Slot` component in `StyleMarker`. I don't know how I didn't catch this in https://github.com/MystenLabs/sui/pull/14566... but automated tests are our friend 😅 
- https://sui-typescript-docs-git-wrobertson-bleh-mysten-labs.vercel.app/dapp-kit/wallet-components/ConnectButton
- Automated tests (the test fails on `main` and passes with this fix) 🌈 
---
=> [dapp-kit] fix bug introduced in the last version where the ConnectButton doesn't open the modal

crates/sui-storage/src/object_store/mod.rs
In testing R2 writes, I've discovered that connections to R2 fail when `builder.with_virtual_hosted_style_request(true)` is set.
This PR allows that to be configurable, along with respecting the `aws_allow_http` setting.
---
=> Add aws builder params to config

crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui/src/client_commands.rs
Implements the `Display` trait for `SuiTransactionBlock` type - this is only at the top level. A follow-up PR will address the `SuiTransactionBlockData` stuff. 
---
Improves the formatting output in the CLI for the `Transaction Data` part when a transaction's response is displayed.
=> [cli] implement display for SuiTransactionBlock

dapps/regulated-token/Move.toml, dapps/regulated-token/README.md, dapps/regulated-token/publish.sh, dapps/regulated-token/sources/denylist.move, dapps/regulated-token/sources/reg.move, dapps/regulated-token/sources/token.move
Adds a dapp-example for a CLI application. 
---
=> [dapps, closed loop] Adds regulated token cli

Cargo.lock, crates/sui-config/src/node.rs, crates/sui-core/Cargo.toml, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/consensus_manager/mod.rs, crates/sui-core/src/consensus_manager/mysticeti_manager.rs, crates/sui-node/src/lib.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/workspace-hack/Cargo.toml
Follow up of https://github.com/MystenLabs/sui/pull/14698
This PR:
* introduces a config property to switch between consensus protocols . We default to `Narwhal`
* initialises the consensus protocol when bootstrapping the node according to the property
* starts the mysticeti consensus handler on every mysticeti validator start
CI
---
=> [mysticeti] wire mysticeti consensus handler & boot consensus protocol based on property

Cargo.lock, crates/sui-config/src/node.rs, crates/sui-core/Cargo.toml, crates/sui-core/src/authority_server.rs, crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/consensus_manager/mod.rs, crates/sui-core/src/consensus_manager/mysticeti_manager.rs, crates/sui-core/src/mysticeti_adapter.rs, crates/sui-core/src/unit_tests/consensus_tests.rs, crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs, crates/sui-node/src/lib.rs, crates/sui-single-node-benchmark/src/single_node.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/workspace-hack/Cargo.toml
This PR:
* introducing the `LazyMysticetiClient` to be used on the `consensus_adapter`
* Sharing the `LazyMysticetiClient` between the consensus adapter and the mysticeti manager to directly update the underneath client `MysticetiClient` on every epoch change. That was preferred to the global variable approach as it's more straightforward when needing to spin up programmatically multiple sui nodes.
* `SimpleBlockHandler` moved to `Mysticeti` as it was finally proved to be more convenient that way
* is updating the mysticeti ref
Next:
CI
---
=> [mysticeti] wire in mysticeti client

crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/owner/dynamic_field_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/package_cache.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-types/src/base_types.rs, crates/sui-types/src/dynamic_field.rs
Implements Dynamic Field, rendering just the K of DynamicField<K, V> when DynamicField.name is queried, or the V of DynamicField for dynamic fields, or the actual object if the dynamic field is an object
Dynamic field object:
dynamic field
---
Manual tests and existing tests ...
=> [graphql] implement dynamicFieldsConnection

crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/transaction_block_effects/transaction_block_effects.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Add coinType to BalanceChange, so we know the coin type of the balance that was changed (rhymes)
manual verification, updated examples
---
=> [graphql][fix][easy] add coinType to BalanceChange

crates/sui-graphql-rpc/src/client/mod.rs, crates/sui-graphql-rpc/src/client/response.rs, crates/sui-graphql-rpc/src/client/simple_client.rs, crates/sui-graphql-rpc/src/extensions/mod.rs, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/server/mod.rs, crates/sui-graphql-rpc/src/server/version.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
Creates a custom `GraphqlResponse` type which is created from http response and supports fetching commonly used data.
This will be useful for tests.
e2e test
---
=> [graphql/rpc] add rich graphql casting from response

crates/sui-types/src/digests.rs
This allows tests to force ProtocolConfig to act as a specific chain. It will not allow overrides where the actual ChainIdentifier is for mainnet or testnet.
=> Add support for Chain override in ProtocolConfig

crates/sui-graphql-rpc/src/extensions/logger.rs
Force the `__schema` response that is generated everytime the server is reloaded to be logged using `debug` as it is too noisy.
---
=> [graphql/logging] change logging level for schema to debug

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Improves the docs by explaining that the `type` field of the `coin_connection` expects the coin's inner type as a string. 
---
=> [graphql/docs] add docs for coin type in coin_connection

crates/sui-json-rpc-types/src/object_changes.rs, crates/sui/src/client_commands.rs
Removes the extra empty line that exists between two items and fixes the version to be a u64. 
---
Improves the consistency across the way object changes are shown in transaction effects and outside of transaction effects, and fixes a bug that was not displaying an object's change version correctly as a u64.
=> [cli] remove the extra empty line between two consecutive items and fix the object's version

crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/transaction_block/transaction_block.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
This PR adds the `timestamp` field for the `TransactionBlock` type. It also adds a corresponding example for querying a transaction block by its digest.
---
=> [graphql] add timestamp for TransactionBlock

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Limits the size of graphql query payloads
Manual
---
=> [graphql/rpc] limit query payload size

crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-types/src/transaction.rs
the tx count was designed to count system tx as well, after c667fdb975ea515cb3b59aeaf9530c0f30073bae it stopped counting the system tx, this PR is to fix that.
CI
---
=> indexer v2: fix transaction count

crates/sui-core/src/authority/authority_store_pruner.rs
When pruning_run_delay_seconds is set in config, it is used as milliseconds in tick_duration.
---
=> Fix pruner tick_duration getting value from config

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-core/src/unit_tests/transaction_manager_tests.rs, crates/sui-types/src/inner_temporary_store.rs, crates/sui-types/src/storage/mod.rs
- remove dead code
- Move output key computation into InnerTemporaryStore method
- Combine commit_cert_and_notify with commit_certificate
=> Some simple refactorings to clean up the commit cert path

crates/sui-core/src/authority.rs, crates/sui-core/src/db_checkpoint_handler.rs, crates/sui-node/src/lib.rs
Today in order for formal snapshots to work, we also need to enable full db checkpoint config, including providing an object store and awaiting upload. Some node operators may want to only upload formal snapshots without incurring the cost of also uploading and maintaining a db checkpoint snapshot. Moreover, we will eventually move to only supporting formal snapshots. This PR introduces the capability to configure a node to generate and upload formal snapshots (state snapshots) without the need to also upload db checkpoints. We do this by generating a minimal db checkpoint config for use by `DBCheckpointHandler` and introducing a separate loop path in the handler, which simply marks new db checkpoints with `UPLOAD_COMPLETED` marker so that they can be used for formal snapshots and …
=> [formal snapshots] Support without DB Checkpoint upload

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
Add some tracing to examine checkpoint execution.
I'm playing with tracing to see the effectiveness of #14667 . As a result, a typical transaction execution (`handle_execution_effects`) may take 100s of milliseconds, whereas the `finalize checkpoint` takes ~1.5ms before #14667 and ~700µs.
The DB is setup in a way that is moderately busy (compaction takes 20% of CPU).
Before #14667:
After #14667:
---
=> Add some tracing annotation for checkpoint execution

crates/sui-core/src/authority.rs, crates/sui-single-node-benchmark/src/mock_storage.rs, crates/sui-types/src/inner_temporary_store.rs, crates/sui-types/src/storage/mod.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/v1/sui-adapter/src/temporary_store.rs
I noticed that we still spend a non-trivial amount of time loading packages in execution. After digging in, I realized that this is mostly due to us trying to save all runtime loaded packages.
This PR minimizes that overhead by:
1. Do not write unless it's not already in the runtime loaded package map.
2. Avoid clone.
This fix is sufficient to make the package load disappear in a local benchmark, and we are seeing about 10% improvements in throughout in the baseline mode. So this is good enough for now.
However as a long term fix, I think a proper solution is that we should introduce a verbose flag to execution. Normally the verbose flag is off. When we detect a fork, we rerun the execution with the verbose flag on so that we could collect more information for the debug state dump.
Also …
=> More optimizations to package load

crates/sui-move/src/unit_test.rs, external-crates/move/crates/move-cli/src/base/test.rs
This PR adds warning message and returns early if it the binary is not a debug build when running `sui move test` with the `--coverage` flag. 
---
Improves the error message when running `sui move test --coverage` with a non debug build binary.
=> [cli] add a check and warning message when trying to run sui move test --coverage in non debug builds

Cargo.lock, Cargo.toml, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/generate_format.rs, crates/sui-core/src/state_accumulator.rs, crates/sui-core/src/storage.rs, crates/sui-faucet/src/faucet/write_ahead_log.rs, crates/sui-rosetta/src/errors.rs, crates/sui-types/Cargo.toml, crates/sui-types/src/error.rs, crates/typed-store-error/Cargo.toml, crates/typed-store-error/src/errors.rs, crates/typed-store-error/src/lib.rs, crates/typed-store/Cargo.toml, crates/typed-store/src/rocks/errors.rs, crates/typed-store/src/rocks/iter.rs, crates/typed-store/src/rocks/mod.rs, crates/typed-store/src/rocks/safe_iter.rs, crates/typed-store/src/sally/mod.rs, crates/typed-store/src/test_db.rs, narwhal/storage/src/certificate_store.rs
This PR separates out TypedStore error into its own crate so crates which only depend on the error don't need to import and build RocksDB. hopefully this speeds up build times for specific crates.
`sui-types` is one of those crates which benefits from this. It's also used in many places so perf is important.
Ideally I don't want to use the explicit convert functions but Rust traits rules prevent implementing From trait outside.
Thanks to @stefan-mysten for pointing out this issue.
Existing
---
=> remove rocksdb deps for sui types

crates/sui-graphql-rpc/src/test_infra/cluster.rs, crates/sui-graphql-rpc/src/test_infra/data/example.exp
Fixes a test due to checkpoint digest change, and uses better logic for getting sequence number as flagged in [PR](https://github.com/MystenLabs/sui/pull/14710#discussion_r1385656414)
Existiing
---
=> [graphql/rpc] fix test and comment

Cargo.lock, crates/sui-indexer/Cargo.toml, crates/sui-indexer/migrations_v2/2023-10-04-161107_move_call_metrics/up.sql, crates/sui-indexer/migrations_v2/2023-10-06-204335_tx_recipients/down.sql, crates/sui-indexer/migrations_v2/2023-10-06-204340_tx_senders/down.sql, crates/sui-indexer/migrations_v2/2023-10-06-204400_tx_calls/up.sql, crates/sui-indexer/src/processors_v2/address_metrics_processor.rs, crates/sui-indexer/src/processors_v2/move_call_metrics_processor.rs, crates/sui-indexer/src/processors_v2/processor_orchestrator_v2.rs, crates/sui-indexer/src/store/indexer_analytical_store.rs, crates/sui-indexer/src/store/pg_indexer_analytical_store.rs
various optimizations on the address metrics and move call metrics processor, after all the optimizations per estimation, the analytical processor should be able to backfill in ~3 days as well.
local run to verify the correctness, run on explorer testing DB to see the improvement of speed
---
=> indexer v2 analytical: optimize addr and move call processors

crates/sui-indexer/migrations_v2/2023-10-04-161058_tx_count_metrics/up.sql, crates/sui-indexer/migrations_v2/2023-10-04-161244_network_metrics/up.sql, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/models_v2/network_metrics.rs, crates/sui-indexer/src/models_v2/transactions.rs, crates/sui-indexer/src/models_v2/tx_count_metrics.rs, crates/sui-indexer/src/processors_v2/network_metrics_processor.rs, crates/sui-indexer/src/schema_v2.rs, crates/sui-indexer/src/store/indexer_analytical_store.rs, crates/sui-indexer/src/store/pg_indexer_analytical_store.rs
- simplify the network metrics such that only peak TPS is calculated per epoch
- other data like realtime TPS can be done on the reading side, as the view query takes < 100 ms to finish on a fully populated DB
this will
- shorten network metrics backfill from days to a couple of hours
- also on Explorer, metrics of current checkpoint and current TPS is more realtime.
local run and verify
---
=> indexer v2 analytical: simplify and fix network metrics

crates/sui-graphql-rpc/src/client/mod.rs, crates/sui-graphql-rpc/src/client/simple_client.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
Allow passing variables in the graphql client.
This will make testing suite much more flexible as we can swap out value easier. 
e2e test
---
=> [graphql/rpc] support variables in client

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Query payload limit makes fragment and variable limits unnecessary.
N/A
---
=> [graphql/rpc] remove fragment and variable count limits

sui_programmability/examples/defi/sources/pool.move
Fix missing 0 in comment describing fee_percent values
---
Fix missing 0 in comment describing `fee_percent` values in the defi example.
=> [examples/defi] Fix missing 0 in comment describing fee_percent values

crates/sui-analytics-indexer/src/package_store.rs, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/package_cache.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/object_change.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-indexer/src/types_v2.rs, crates/sui-package-resolver/src/lib.rs, crates/sui-types/src/governance.rs
A number of changes to bring all the type representations within the `Object` hierarchy inline with each other, and make it easier to adopt a `DataLoader` style interface for all of them (which will be the next step).
Every type in this hierarchy (`Object`, `MoveObject`, `MovePackage`, `Coin, `Stake`) stores the following:
- Their `super_` type, by value (e.g. `Coin` stores `MoveObject` which stores `Object`).
- The "native" representation (the `sui-type` type).
Additionally, `Object`, as the top of the hierarchy also contains its `stored` representation, and its `address` (to avoid having to convert it from a byte array every time).
All upcast operations have been made infallible, and work by returning a reference to `super_`.  This is temporary because after #14649, these will …
=> [GraphQL] Change Object hierarchy representation

Cargo.lock, crates/sui-json-rpc/Cargo.toml, crates/sui-json-rpc/src/api/mod.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-replay/Cargo.toml
In cleaning up build times, this removes more unneeded deps on RocksDB 
Existing
---
=> chore: remove more rocksdb deps

crates/sui/src/main.rs, external-crates/move/crates/move-package/src/lib.rs
- Propagate version for all commands in the CLI
- Removed standalone Move Package version
- `cargo run --bin sui --locked -- <COMMAND> -V`
---
The Sui CLI tools will now display the correct version across all subcommands.
=> [sui-cli] Propagate version

crates/sui-analytics-indexer/src/analytics_processor.rs, crates/sui-archival/src/lib.rs, crates/sui-archival/src/reader.rs, crates/sui-archival/src/writer.rs, crates/sui-core/src/db_checkpoint_handler.rs, crates/sui-snapshot/src/reader.rs, crates/sui-snapshot/src/uploader.rs, crates/sui-snapshot/src/writer.rs, crates/sui-storage/src/object_store/http/gcs.rs, crates/sui-storage/src/object_store/http/local.rs, crates/sui-storage/src/object_store/http/mod.rs, crates/sui-storage/src/object_store/http/s3.rs, crates/sui-storage/src/object_store/mod.rs, crates/sui-storage/src/object_store/util.rs, crates/sui-tool/src/commands.rs, crates/sui-tool/src/lib.rs
Allow using no sign requests for sui tool, archival and snapshot use cases in sui. User just passes in so sign request as a parameter in their object store config and right downloader tool is used. 
Also cleaned up the abstractions and created new ones so in the future we can support unauthenticated list requests if need be.
=> Integrate http based downloader with archival, snapshot and sui tool

crates/typed-store/src/metrics.rs, crates/typed-store/src/rocks/mod.rs
With the way we create new db's every epoch, it sometimes isn't clear whether we are leaking db handles (and may be causing memory leak). Having a metric which tracks the number of active db's would be useful to have.
Existing tests
=> Track number of active db handles

crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/stake_connection/stake_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Change type representing Staked SUI to `StakedSui` (from `Stake`). This matches the naming used in the draft schema, which was in turn chosen to match the names used in Move code (as opposed to the names in JSON-RPC where this concept is also called `Stake`).
Also tweaks the draft schema to make the connection types and names also use this naming scheme.
GraphiQL:
=> [GraphQL][EASY] Stake -> StakedSui

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_handler.rs
- Use `hostname` as the `authority` label value, similar to the `consensus_handler_scores` metric. This should make associating the authority with actual validator easier.
- Rename the metric to be meaningful after future Mysticeti rollout.
CI
---
=> [Narwhal] improve usability of consensus message per authority metric

sdk/move-binary-format-wasm/Cargo.toml
Broke with the recent flattening of the move repo, spotted in the CI runs for #14816 (not sure why it only started showing up now as the flattening happened 2 weeks ago: #14637).
```
sui$ pnpm install
sui$ pnpm turbo build
```
Failed on `main` before this change, now succeeds.
=> [move-binary-format-wasm] Fix-up move dependencies

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/db_query_cost.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/simple_server.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/src/types/move_type.rs, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/sui_system_state_summary.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind.rs
Follow these rules when emitting errors in GraphQL:
- All implementations of GraphQL fields (that can fail), use `async_graphql::Result<T>` (meaning their error type is always `async_graphql::Error`).
- All other internal APIs that produce errors should produce `crate::error::Error`, for better composability, and to encourage use of the `extend()` API to convert to `async_graphql::Error` (this process is what adds the custom error code).
- Import the `Error` type rather than mention it in a fully-qualified way.
GraphiQL:
=> [GraphQL/Errors] Standardise use of Error types

crates/sui-adapter-transactional-tests/tests/dynamic_fields/exhaustive.exp, crates/sui-adapter-transactional-tests/tests/mvcc/child_of_child.exp, crates/sui-adapter-transactional-tests/tests/mvcc/child_of_child.move, crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids.exp, crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids_dof.exp, crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids_on_child.exp, crates/sui-adapter-transactional-tests/tests/mvcc/receive_object_dof.exp, crates/sui-adapter-transactional-tests/tests/mvcc/receive_object_dof.move, crates/sui-adapter-transactional-tests/tests/mvcc/v0/child_of_child.exp, crates/sui-adapter-transactional-tests/tests/mvcc/v0/child_of_child.move, crates/sui-adapter-transactional-tests/tests/mvcc/v0/find_all_uids.exp, crates/sui-adapter-transactional-tests/tests/mvcc/v0/find_all_uids_dof.exp, crates/sui-adapter-transactional-tests/tests/mvcc/v0/find_all_uids_on_child.exp, crates/sui-adapter-transactional-tests/tests/size_limits/event_limits_tests.exp, crates/sui-adapter-transactional-tests/tests/size_limits/event_limits_tests_out_of_gas.exp, crates/sui-adapter-transactional-tests/tests/size_limits/move_object_size_limit.exp, external-crates/move/crates/move-compiler/src/cfgir/optimize/mod.rs, external-crates/move/crates/move-compiler/src/cfgir/translate.rs, external-crates/move/crates/move-compiler/src/editions/mod.rs, external-crates/move/crates/move-compiler/src/hlir/translate.rs
This is an experiment to disable the optimizations I introduced during the CFG and HLIR  rewrites (#13497, https://github.com/MystenLabs/sui/pull/14641) until we have a better solution for handling on-chain divergence, in hopes of landing those rewrites sooner.
Revised tests match main, and all work.
---
=> [move-compiler] disable rewrite optimizations

crates/sui-graphql-rpc/tests/e2e_tests.rs
Disable disable genesis-sensitive e2e test [this](https://github.com/MystenLabs/sui/pull/14822) pr goes in, which has a cleaner way of updating tests.
N/A
---
=> [graphql/rpc] disable genesis-sensitive test

crates/sui-json-rpc-types/src/sui_event.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui/src/client_commands.rs
Implements the `Display` trait for `SuiEvent` and `SuiTransactionBlockEvents` to enable better output formatting of transaction responses in the CLI.
Run `sui client tx-block GQLaqTNk2XRxYkDRauj7MkLkkG6ZatdPp5dxR17FBt9Q` on `mainnet`
Run `sui client tx-block CGjPmjpxuYGYuDrGQMTrBvyujFjkzakRvBnwr3bERBen` on `mainnet`
Run `sui client tx-block DjwYzwnDENdZfeLec2b2grKthuLudgN1dCGr4Ltn9YAu` on `mainnet`
---
Improves the formatting output of `SuiEvent` objects in the CLI.
=> [cli] Impl Display for SuiEvent and SuiTransactionBlockEvents

sui-execution/latest/sui-move-natives/src/test_scenario.rs
Adds support for shared object deletion in the test scenario -- mainly making sure that we don't raise an error if a shared object was deleted, whereas before it would complain.
PR this is stacked on tests this.
---
=> Add support for shared-object deletion in test scenario

.changeset/cyan-rabbits-joke.md, pnpm-lock.yaml, sdk/dapp-kit/src/hooks/wallet/useSignPersonalMessage.ts, sdk/dapp-kit/test/hooks/useSignPersonalMessage.test.tsx, sdk/dapp-kit/test/mocks/mockFeatures.ts
Some builders were having issues migrating over to dApp Kit since some wallets haven't migrated over to `signPersonalMessage` yet. Instead of creating a `useSignMessage` hook and making folks do feature detection on their own, I think it's a slightly more ergonomic fix to just fallback to `signMessage` within the `useSignPersonalMessage` hook and then we can just kill the functionality once we discontinue support for `signMessage`.
The alternative solution would look something like this:
```
const { mutate: signPersonalMessage } = useSignPersonalMessage();
const { mutate: signMessage } = useSignMessage();
signPersonalMessage({ variables }, {
onError(error) {
if (error instance of WalletFeatureNotSupported) {
signMessage({ variables });
}
}
});
```
as opposed to just:
```
const { mutate: …
```
=> [dapp-kit] fall back to signMessage if signPersonalMessage isn't supported

crates/sui-core/src/authority/authority_per_epoch_store.rs
In #14087, we thought it is ok to set the processed bit for every transaction in the consensus output. But it turns out setting ignored transaction to `processed` may prevent reverting transactions, if a validator restarts during epoch change.
This change only avoid setting the `processed` bit for ignored transactions. It does not completely restore the behavior before #14087.
Ran on `simtest-01` CI machine:
```
SIM_STRESS_TEST_DURATION_SECS=300  USE_MOCK_CRYPTO=1 MSIM_TEST_NUM=60 cargo simtest test_simulated_load_reconfig_with_crashes_and_delays
```
---
=> [Sui] do not record ignored consensus transaction as processed

crates/sui-json-rpc-types/src/object_changes.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui/src/client_commands.rs
Move the formatting of `SuiTransactionBlockResponse` to its own display, instead of doing it in the `client_commands.rs` file.
`sui client tx-block DCJkLyhMCExPULwUAGkD67EnfKwjZYo8e4bYnyMVP5Yh`
(https://gist.github.com/stefan-mysten/ea8c205fc626801acd3022b6d89bd1af)
---
=> [cli/easy] move the formatting of transaction block response to its own display

crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-core/src/unit_tests/transaction_manager_tests.rs
This PR reverts the logic introduced in #10557 where transaction manager first executes all the transactions that only read a shared object and then executes the transaction that mutate it (if there is any). This was due to that child object reading was not properly handled. Now, since we have MVCC in child objects, we can remove this restriction, and send all transactions to execute as soon as all input objects become available.
Unit test
---
=> Remove shared object locking in transaction manager before sending to execute

crates/sui-indexer/src/apis/extended_api.rs, crates/sui-indexer/src/apis/extended_api_v2.rs, crates/sui-json-rpc-types/src/sui_extended.rs, crates/sui-json-rpc/src/api/extended.rs
A lightweight RPC endpoint for faster epoch metrics loading on Explorer.
The related thread is https://mysten-labs.slack.com/archives/C032676BWGN/p1699941535995239
local run RPC server and test via curl, the latest epoch is not complete, so still missing some end of epoch info
```
curl --location http://127.0.0.1:9000 \
--data '{
"id": "5",
"method": "suix_getEpochMetrics",
"params": [
null,
2,
true
]
}' | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   920  100   804  100   116   2288    330 --:--:-- --:--:-- --:--:--  2643
{
"result": {
"data": [
{
"epoch": "216",
"epochTotalTransactions": "0",
"firstCheckpointId": …
```
=> indexer v2: light-weight epoch endpoints

crates/sui-core/src/db_checkpoint_handler.rs, crates/sui-storage/src/object_store/util.rs
For http-based snapshot downloads we need to have an easily accessible list of the files available in a snapshot. This PR creates a MANIFEST file which is written to the epoch dir root, and contains the list of all files available.
Just a unit test
---
=> Add a simple MANIFEST file to db snapshots

docs/content/guides/developer/getting-started/local-network.mdx
consensus-off doesn't turn off consensus. It just turns off logging for consensus.
---
=> Fix local network command doc

crates/sui-cluster-test/src/cluster.rs, crates/sui-test-validator/src/main.rs
Cleans-up some unwraps and logic from sui-test-validator
Adds printing of config before cluster start. Makes it easy to see what GraphQL server exactly one should connect to.
Existing
---
=> [sui-test-validator] chore: cleanup unwraps

crates/sui-core/src/unit_tests/data/tto/sources/tto4.move, crates/sui-core/src/unit_tests/transfer_to_object_tests.rs, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_32.snap, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs, sui-execution/v1/sui-move-natives/src/object_runtime/mod.rs, sui-execution/v1/sui-move-natives/src/object_runtime/object_store.rs
Minor updates and cleanups to execution code related to transfer-to-object. Nothing about the semantics should be changed with this. 
This also turns transfer-to-object on for testnet and devnet (only).
Added an additional test, and made sure existing tests continue to all pass. 
---
Transfer-to-object is now turned on and supported in testnet and devnet.
=> [transfer-to-object] Turn on in testnet, minor updates

.github/workflows/rust.yml
Use nextest over cargo test
Serialize e2e tests due to PG instance limitations
Existing
---
=> [graphql/rpc] serialize data tests and use nextest

external-crates/move/crates/move-cli/src/base/new.rs, external-crates/move/crates/move-cli/tests/build_tests/simple_build_with_docs/args.exp, external-crates/move/crates/move-cli/tests/build_tests/simple_new/args.exp
- We are making changes that make our compiler fail against move-language/move's version of stdlib 
- This does not affect the Sui CLI 
- At least temporarily, we will remove the stdlib link from the core Move CLI. We can add it back once we have our repo situation figured out
- ran CLI tests
---
=> [move] Temporarily remove stdlib link

crates/sui-graphql-rpc/src/test_infra/cluster.rs
Set to 20 to reduce hitting limits
Manual
---
=> [graphql/rpc] set DB pool size to 20 in indexer start test

crates/sui-analytics-indexer/src/analytics_processor.rs, crates/sui-analytics-indexer/src/lib.rs
Add an optional path prefix which could be used to write data to remote buckets (s3/gcs, etc). This is primarily needed for backfills where we would re-run the pipelines for older checkpoints and write data to a different prefix so regular workflow isn't interrupted.
Ran locally on local directory with prefix
=> [analytics]Add optional path prefix while writing data in remote bucket

crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/call/simple.move
Remove tests which can change when framework changes.
Existing
---
=> [graphqlrpc] remove tests which depend on framework

.github/workflows/rust.yml, crates/sui-graphql-e2e-tests/Cargo.toml, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/README.md, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/mod.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs
This PR is localized to just the graphql side.
Each backend implements GenericQueryBuilder, and then exports a type alias QueryBuilder to be used in db_data_provider (pending rename?)
Because the function for executing a query has its type defs tied to the db backend, we also move this out into the corresponding backend.rs file. So for pg_backend.rs, we define a new trait PgQueryExecutor and implement it for PgManager (also pending rename.)
Custom sql functions like 'explain' play nicely enough with this approach - each backend just needs to implement the QueryFragment and RunQueryDsl portion.
In subsequent PRs:
1. Rename PgManager, instantiate a reader based on config (which will just fail if not postgres, until the next one is supported)
2. Modify IndexerReader on indexer crate to …
=> [graphql][1/n] conditional db for testing and local dev

crates/sui-analytics-indexer/src/analytics_processor.rs, crates/sui-analytics-indexer/src/writers/csv_writer.rs, crates/sui-analytics-indexer/src/writers/mod.rs, crates/sui-analytics-indexer/src/writers/parquet_writer.rs
Parquet writer does not write a file when called with `flush()` if there are no records to write:
```
fn flush(&mut self, end_checkpoint_seq_num: u64) -> Result<bool> {
if self.data.is_empty() {
return Ok(false);
}
```
This is not handled in analytics processor today (with its integration with csv writer) because it expects the file to be written but later an empty file is just discarded when uploading to remote store. This PR fixes analytics processor to handle this scenario properly i.e handle the scenario when file is not written to disk (as parquet writer does it).
We basically change the function `flush()` to return a boolean true if it did write a file or false otherwise so analytics processor can handle it properly.
Ran locally for move-call pipeline (which generates empty files) …
=> Fix analytics processor and parquet writer integration for empty files

external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/interpreter.rs
`next-vm` execution layer cut (#14874) raced with removal of scripts (#14870), introduced a build issue.
Fixed by replicating the fix applied to v0 from the scrip removal PR.
```
external-crates/move/move-execution/next-vm$ cargo nextest run
```
=> [move/next-vm] Fix main

crates/sui-config/src/node.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-e2e-tests/tests/object_deletion_tests.rs, crates/sui-surfer/tests/move_building_blocks/sources/objects.move, sui-execution/v0/sui-verifier/src/id_leak_verifier.rs
Modified unwrapped_then_deleted_tests.rs to add the pruning test there, since both are testing object deletion.
Will turn on tombstone pruning by default the next PR.
This PR
---
=> Create an integration test to test object pruning

sdk/dapp-kit/README.md, sdk/docs/pages/dapp-kit/index.mdx
A builder in Discord was confused about why the provided UI components weren't displaying correctly in their app, and it was because they didn't realize they needed to import the CSS file for dApp Kit into their application. I noticed we don't have anything in our documentation about this, so I'm adding a section in the docs with this PR 😄 
https://mysten-labs.slack.com/archives/C0393DWJD7X/p1700380725599999
- 👁️ 
---
=> [dapp-kit] update docs to include a snippet about importing the CSS stylesheet

crates/sui-core/src/unit_tests/shared_object_deletion_tests.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/next-vm/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs
Updates requirements for when a shared object can be deleted
Added additional tests
---
=> [shared-object-deletion] Update some requirements

crates/sui-transactional-test-runner/src/simulator_persisted_store.rs, crates/typed-store-derive/src/lib.rs
Expands DBMapUtil macros to allow read replicas to sync all tables at once. 
This is useful in transactional test logic (for graphql) which needs to catchup to primary periodically.
Existiing
---
=> [typed-store/graphql] add util to sync all read only tables

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_32.snap
Protocol upgrade happened successfully in testnet and a [catchup test in testnet was also successfully](https://metrics.sui.io/goto/T9Wm8C4Ig?orgId=1) completed
=> Enable CertV2 in mainnet

crates/sui-graphql-e2e-tests/README.md, crates/sui-graphql-e2e-tests/tests/call/owned_objects.exp, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-indexer/README.md
Instructions for how to set-up `postgresql` for the GraphQL E2E tests. Also updating the instructions for `sui-indexer` (Postgres is called `postgresql` on homebrew).
Follow instructions.  Note that when I did this, the digests and IDs changed (not sure whether that's supposed to happen or not, but CI will tell us!).
=> [GraphQL/Tests] README for running transactional-tests locally

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_handler.rs
So we can release them earlier.
CI
---
=> Cherrypick consensus metric fixes #14811 and #14875 to 1.13

crates/sui-core/tests/staged/sui.yaml, crates/sui-types/src/transaction.rs
This may fix backwards compat issues with FullCheckpointContents serialization.
Add into failing replay workflows.
=> move new TransactionKind::RandomnessStateUpdate to end of list

crates/sui-types/src/storage/shared_in_memory_store.rs
I recently introduced this bug while moving `self.epoch_to_committee.push(committee);` outside the if condition. This PR fixes the check
=> Fix check for comparing committee length with epoch

crates/mysten-metrics/src/lib.rs, crates/sui-node/src/main.rs, crates/sui-proxy/src/main.rs
This helps to differentiate between validators and fullnodes. When validators have stuck consensus, it is harder to differentiate via other metrics.
---
=> [Sui] add a `process` label to `uptime` metric

crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/call/simple.move, crates/sui-graphql-rpc/src/test_infra/cluster.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Followup of [this](https://github.com/MystenLabs/sui/pull/14957) PR which now allows the objects manipulated to be accessible as variables.
Object of name `FakeID(x,y)` will now have mapping `obj_x_y` and `obj_x_y_opt` variables.
Integration test
---
=> [graphql/rpc] testing infra: add object id mapping to varoables

crates/sui-graphql-rpc/src/commands.rs, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/main.rs
Makes it easy to set the title of the IDE. Helps when distinguishing different IDEs and to find the Sui mainnet vs testnet IDE.
Example:
`sui-graphql-rpc start-server --db-url postgres://0.0.0.0:5432/postgres  --ide-title mygql`
---
=> [graphql/rpc] easy: command to set ide title

.changeset/calm-ligers-rush.md, crates/sui-transaction-builder/src/lib.rs, crates/sui/tests/cli_tests.rs, crates/sui/tests/data/sod/Move.toml, crates/sui/tests/data/sod/sources/sod.move, sdk/typescript/src/builder/TransactionBlock.ts, sdk/typescript/test/e2e/data/serializer/sources/serializer.move, sdk/typescript/test/e2e/data/serializer_upgrade/sources/serializer.move, sdk/typescript/test/e2e/txn-builder.test.ts
Updates SDKs to properly determine mutability of shared objects when passed by value.
Added new tests in both the Typescript and Rust SDKs
---
=> [sdk/shared-object-deletion] Update SDKs

crates/sui-indexer/src/apis/indexer_api_v2.rs, crates/sui-indexer/src/apis/read_api_v2.rs, crates/sui-indexer/src/indexer_reader.rs
Same as ##14750 except rebased on main and using `to_canonical_string`.
---
=> [indexer] add MatchNone struct filter

crates/sui-graphql-e2e-tests/tests/call/dynamic_fields.exp, crates/sui-graphql-e2e-tests/tests/call/dynamic_fields.move, crates/sui-graphql-e2e-tests/tests/call/owned_objects.exp, crates/sui-graphql-e2e-tests/tests/call/owned_objects.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/owner/dynamic_field.graphql, crates/sui-graphql-rpc/examples/owner/dynamic_field_connection.graphql, crates/sui-graphql-rpc/examples/owner/dynamic_object_field.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Implements fetching dynamicField by dynamicFieldName. Clients are expected to know whether they're looking up a dynamic field or dynamic object field.
Manual + existing + new test suite
Fetching dynamic field
Fetching dynamic object
---
=> [graphql] implement dynamicField

crates/sui-indexer/migrations_v2/2023-10-04-161107_move_call_metrics/up.sql, crates/sui-indexer/migrations_v2/2023-10-04-161115_address_metrics/up.sql, crates/sui-indexer/migrations_v2/2023-10-04-161244_network_metrics/down.sql, crates/sui-indexer/src/indexer_v2.rs, crates/sui-indexer/src/main.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/models_v2/move_call_metrics.rs, crates/sui-indexer/src/models_v2/network_metrics.rs, crates/sui-indexer/src/models_v2/transactions.rs, crates/sui-indexer/src/models_v2/tx_count_metrics.rs, crates/sui-indexer/src/processors_v2/address_metrics_processor.rs, crates/sui-indexer/src/processors_v2/move_call_metrics_processor.rs, crates/sui-indexer/src/processors_v2/network_metrics_processor.rs, crates/sui-indexer/src/processors_v2/processor_orchestrator_v2.rs, crates/sui-indexer/src/schema_v2.rs, crates/sui-indexer/src/store/indexer_analytical_store.rs, crates/sui-indexer/src/store/pg_indexer_analytical_store.rs
The overall idea is that, much of time in the past were spent on passing data from DB and then write them back, even with parallelism on many steps, instead this PR does that directly in DB, on testing this will reduce backfill time of move call metrics and DAU related metrics from days to hours.
local run and test speed on a separate testing DB
---
=> indexer v2 analytical: faster move call and address processors

crates/sui-cluster-test/src/cluster.rs, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/server/builder.rs
Removes use of magic number 3 for db pool size and puts it under config attr.
Existing
---
=> [graphql/rpc] chore: config cleanups

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/error.rs
Allow for shorthand representation of the coin type.
On Error:
---
=> [graphql] Allow for shorthand representation of the coin type

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Once #14965 lands, this PR fixes the doc comments in the `coinConnection` for the `Query` type. 
---
=> [graphql/easy] Fix coin connection doc comments

crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm/src/memory/swarm.rs, crates/test-cluster/src/lib.rs
Originally I was going to just make the overload threshold high for tests by default to fix the `shared_object_sync` simtest failure, but I thought it would be useful to be able to customize it as we add more parameters to the config and may want to test these out in tests.
Test itself.
---
=> add ability to customize overload threshold in TestCluster

.github/workflows/rust.yml, crates/sui-graphql-e2e-tests/tests/packages/friends.exp, crates/sui-graphql-e2e-tests/tests/packages/modules.exp
Locally, these tests do not run unless pg_backend is removed. Checked and our previous PRs also skipped the e2e tests. Removing pg_backend should allow the tests to run.
CI tests do not skip e2e tests
---
=> [graphql][fix] e2e tests do not run if pg_backend flag is provided

crates/sui-indexer/README.md
Fixes typo in the command. It should be `brew services` instead of `brew service`. 
---
=> [docs] Fix typo in brew command 

.changeset/happy-ducks-yell.md, pnpm-lock.yaml, sdk/enoki/demo/App.tsx, sdk/enoki/demo/index.html, sdk/enoki/demo/main.tsx, sdk/enoki/demo/tsconfig.json, sdk/enoki/demo/vite.config.ts, sdk/enoki/package.json, sdk/enoki/src/EnokiClient/index.ts, sdk/enoki/src/EnokiClient/type.ts, sdk/enoki/src/EnokiFlow.ts, sdk/enoki/src/react.tsx
This adds the ability to sponsor and execute a transaction in the enoki SDK, and makes a couple tweaks to improve the SDK. I also added a demo app to test the Enoki SDK.
---
=> Add basic sponsorship functionality and demo

sui_programmability/examples/games/README.md, sui_programmability/examples/games/sources/drand_based_lottery.move, sui_programmability/examples/games/sources/drand_based_scratch_card.move, sui_programmability/examples/games/sources/drand_lib.move, sui_programmability/examples/games/tests/drand_based_lottery_tests.move, sui_programmability/examples/games/tests/drand_based_scratch_card_tests.move
Use DRAND's quicknet in example games. Quicknet has a period of 3 seconds instead of the default chains 30 seconds.
Unit tests.
Update DRAND lib to use the new quicknet network which has a 3 second period.
=> Use drand quicknet in examples

docs/content/guides/operator/formal-snapshot.mdx
We have removed the requirement to specify a `db-checkpoint-config` in order to write formal snapshots. Fix the docs to reflect this.
👀 
---
=> Update formal snapshot docs

crates/sui-config/src/node.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-node/src/lib.rs
Leaving the config option there for now in case we need to turn it off for emergency.
---
=> Turn on tombstone pruning by default

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
Default and max page size should be separate parameters, so providers don't incur the max cost every time a multiget is made. 
New e2e test checking that default page size set to 1 returns exactly 1.
---
=> [graphql] set default page size separately from max page size

README.md
I noticed the link to the developer grants program was broken with the new Sui Foundation website. This PR corrects the link in the README so that it points to the correct page on the sui.io website.
N/A, README only.
=> [fix] Update link to developer grants program in README.

crates/sui-graphql-rpc/src/test_infra/cluster.rs
Since it's possible to create more than one checkpoint before running a graphql command, the hardcoded 10 second catch up may not be enough. Naively set max timeout = diff(indexer, simulator) * base time out secs
ci 
---
=> [graphql] more lenient timeout for checkpoint catch up

docs/content/guides/developer/first-app/client-tssdk.mdx
The useSuiClientQuery 'owner' parameter was incorrectly set to 'account?.address', causing a bug. This has been fixed by correctly setting it to the 'address' prop passed to the OwnedObjects component.
=> Update client-tssdk.mdx for Fixing bug in OwnedObjects component

crates/sui-json-rpc-types/src/sui_transaction.rs
Explicitly add that the gas values are in MIST
---
The gas price and budget are shown in MIST, but this is not explicitly stated when a transaction is retrieved or performed through the CLI. This change adds the word MIST after the gas's price and budget's respective value.
=> Explicitly add that the gas values are in MIST

crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/service_config/service_config.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
include defaultPageSize as a field in ServiceConfig
update snapshots
---
=> [graphql][feature] include defaultPageSize in ServiceConfig

examples/move/locked_stake/Move.toml, examples/move/locked_stake/sources/epoch_time_lock.move, examples/move/locked_stake/sources/locked_stake.move, examples/move/locked_stake/tests/locked_stake_tests.move
Added a package that allows locking sui tokens and stake objects up, and performing stake/unstake operations while the assets are locked.
Added tests.
---
=> add locked_stake module

external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/debug.rs, external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/interpreter.rs, external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/loader.rs, external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/runtime.rs, external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/session.rs, external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/unit_tests/vm_arguments_tests.rs, sui-execution/next-vm/sui-move-natives/src/object_runtime/mod.rs, sui-execution/next-vm/sui-move-natives/src/object_runtime/object_store.rs, sui-execution/next-vm/sui-verifier/src/id_leak_verifier.rs
Moving the latest changes in `latest` (and particularly the removal of `Script`) into `next-vm`.
Run the script to do it and things looks decent. @tnowacki take a look but I assume most of the removal was not in the execution layer.
Existing tests
---
=> Merge `latest` to `next-vm`

crates/sui-config/src/node.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
* makes repeatable parameters optional (num_latest_epoch_dbs_to_retain, epoch_db_pruning_period_secs, max_checkpoints_in_batch, max_transactions_in_batch)
* adds metrics to represent following config parameters: num_epochs_to_retain, num_epochs_to_retain_for_checkpoints
=> [pruner config] make repeated parameters optional/default + add metric

crates/simulacrum/src/epoch_state.rs, crates/simulacrum/src/lib.rs, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-transactional-test-runner/src/lib.rs, crates/sui-transactional-test-runner/src/test_adapter.rs, crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs, external-crates/move/crates/move-command-line-common/src/address.rs
Followup to [changes](https://github.com/MystenLabs/sui/pull/14959) which expose variables in testing infra.
Graphql variables are now available as `validator_x` and `validator_x_opt`, where x is an unsigned 0-based integer marking the position of the  validator in the list of validators.
The variables are also accessible as named addresses in the commands with `@validator_x`
---
=> [graphql/rpc] testing: expose validator addresses in test infra

crates/sui/src/client_commands.rs
Fixes the description of the `sui client merge-coin` command, by removing the reference to the 20 bytes address. This should close #10152. 
Just a CLI help description update, no tests are needed.
---
Fixed the description of the `sui client merge-coin` command, by removing the reference to the 20 bytes address.
=> [cli] remove the 20 bytes address description

.changeset/new-humans-join.md, sdk/enoki/src/EnokiFlow.ts, sdk/enoki/src/react.tsx
Some minor updates to the Enoki SDK that are needed after attempting to integrate into the zkSend codebase:
- The session is currently not observable, which means there's no way to get the users' JWT consistently in React. `getSession` _mostly_ works but there is a timing issue if you call it before the `authCallback` has processed. I updated this state to be observable (the API here is not really ideal, but we kind of know that _all_ of theses APIs are weird and will need to be rethought once we have more usage).
- `useAuthCallback` didn't expose the returned state parameter, which is often used to track auth redirects. The hook now returns the state parameter so that this functionality can be implemented.
---
If your changes are not …
=> Enoki SDK improvements

crates/sui-framework/src/lib.rs
Frameworks are special because of their in-place update mechanism and interactions with roll-back and re-configuration.  Documenting why, because ...I forgot.
:eyes:
=> [Framework] Explain why we prevent breaking entry compatibility

.changeset/itchy-emus-nail.md, pnpm-lock.yaml, sdk/dapp-kit/package.json, sdk/dapp-kit/src/hooks/wallet/useAutoConnectWallet.ts, sdk/dapp-kit/src/walletStore.ts, sdk/dapp-kit/test/components/WalletProvider.test.tsx, sdk/dapp-kit/test/hooks/useAutoConnectWallet.test.tsx, sdk/dapp-kit/test/mocks/mockWallet.ts, sdk/dapp-kit/test/test-utils.tsx, sdk/dapp-kit/vitest.config.ts
While integrating the `useAutoConnectWallet` hook, I encountered two issues, which this PR fixes:
- When using SSR, the initial state can disagree between with the client render. This is easy to work around by forcing the initial state to be `idle`.
- The `isDisconnected` condition in auto connect led to an issue, where after _attempting_ to connect the first time, this would become false (since we go from disconnected -> connecting). The query would then run with a different query key but immediately return `attempted` since `isDisconnected` is false. This would lead to the hook resolving to `attempted` before the connection attempt was done (this could cause UIs to churn if you depended on this hook result). ~~I opted to just remove this entirely, although we could also update this to …
=> Fixes for auto connect state

Cargo.lock, crates/sui-benchmark/Cargo.toml, crates/sui-benchmark/tests/simtest.rs, crates/sui-config/src/node.rs, crates/sui-core/src/checkpoints/checkpoint_executor/data_ingestion_handler.rs, crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs, crates/sui-rest-api/src/checkpoints.rs, crates/sui-rest-api/src/client.rs, crates/sui-rest-api/src/lib.rs, crates/sui-storage/src/blob.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm/src/memory/swarm.rs, crates/sui-types/src/full_checkpoint_content.rs, crates/sui-types/src/lib.rs, crates/test-cluster/src/lib.rs
first step in implementing a new data ingestion pipeline.
Adds a new optional setting to FN. When enabled, FN will dump the full checkpoint content into the specified local directory. This directory will be used by an external daemon for post-processing
added simtest
=> [data ingestion pipeline] optionally dump full checkpoint content to local directory

Cargo.lock, crates/sui-tool/Cargo.toml, crates/sui-tool/src/commands.rs
This PR adds the git commit hash to the `sui-tool --version` output, matching [sui-node](https://github.com/MystenLabs/sui/blob/main/crates/sui-node/src/main.rs#L18-L38) behavior. This is will help us easily identify the running commit in some internal workflows.
Local run output:
```
cargo run --bin sui-tool -- --version
Finished dev [unoptimized + debuginfo] target(s) in 0.59s
Running `/Users/chrisgorham/github.com/sui/target/debug/sui-tool --version`
sui-tool 1.15.0-59d4a595c5fa-dirty
```
---
=> [sui-tool] Include git commit hash in sui-tool version output

.changeset/heavy-mayflies-think.md, sdk/enoki/src/EnokiFlow.ts
The enoki flow session isn't always hydrated, which means the user needs to start the hydration with `flow.getSession()`, which isn't really ideal. This updates to start hydrating the session once the store is mounted.
---
=> Hydrate enoki flow session on mount

deny.toml
According to @kchalkias  we don't do RSA signings on Sui. So it's ok to suppress this error.
---
suppress RUSTSEC-2023-0071
=> suppress RUSTSEC-2023-0071

.changeset/five-cobras-boil.md, sdk/dapp-kit/src/hooks/wallet/useAutoConnectWallet.ts
When integrating the new SDK into zkSend I noticed that switching the selected account would actually cause the UI to flicker. This happened because the `useAutoConnectWallet` would flip back to `idle` while the query was being resolved, which isn't the expected behavior. Now, we just early return in the hook if the wallet has been connected.
---
=> Early return status on auto connect

crates/sui-graphql-e2e-tests/tests/packages/structs.exp, crates/sui-graphql-e2e-tests/tests/packages/structs.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/src/types/move_struct.rs, crates/sui-graphql-rpc/src/types/open_move_type.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-package-resolver/src/error.rs, crates/sui-package-resolver/src/lib.rs
Add `MoveStruct` + supporting GraphQL types, and `MoveModule.struct` for querying structs from modules.
New E2E tests:
```
-j 1 --features pg_integration \
-- structs.move
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961
=> [GraphQL/Move] MoveStruct

crates/sui-package-resolver/src/lib.rs, crates/sui-package-resolver/tests/packages/c0/sources/m.move
Calculate an index from function name to function definition index when reading a `Module`, in preparation for supporting function definition based look-ups in the GraphQL RPC.
```
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
=> [Package Resolver] Add function definition indexing

crates/sui-graphql-e2e-tests/tests/packages/friends.exp, crates/sui-graphql-e2e-tests/tests/packages/friends.move, crates/sui-graphql-e2e-tests/tests/packages/structs.exp, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/move_package.rs
Modules need to track which package they came from, separately from their self ID in bytecode.  This is required to support:
- fetching friends from an upgrade package.
- fetching modules from functions and structs that were first defined in upgraded packages.
New E2E test:
```
-- friends.move
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
=> [GraphQL/MoveModule] Keep track of storage_id

docs/content/sidebars/standards.js, docs/content/standards.mdx, docs/content/standards/wallet-adapter.mdx, docs/content/standards/wallet-standard.mdx
Migrating this doc to the sui docs site and updating the name from "Wallet Kit" (not the standard thing) to "Wallet Standard".
---
=> Migrate wallet standard docs to sui docs site

apps/wallet/turbo.json
* we are using turbo now to build the wallet and the current command that we run in order to build it and release it is `pnpm wallet build:prod` but this fails because turbo doesn't know about the `build:prod` script
* this should fix the issue
---
=> wallet-ext: fix release workflow

docker/sui-tools/Dockerfile
The latest docker imager for sui-tools crashes when running sui-tool commands.
Example Ouput or see [Grafana Logs](https://metrics.sui.io/goto/UUPheANSg?orgId=1):
```
gorpig@gorpig ~/github/sui/docker/sui-tools
main $ docker run -it sha256:1221d5917607885bc70cc986e04326b3edc129e2da5059a0f58c5ed4bda9ceef sui-tool --version                                                                                                                           [18:12:50]
sui-tool: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
```
This issue only materialized in the last 24 hours. It appears that some postgres dependencies were added into sui-tool within that time frame and is likely the cause of the libpq requirement now.
I'm not sure if we …
=> [sui-tool] include libpq dynamic linked files in runtime docker layer

crates/sui-move-build/src/linters/coin_field.rs, crates/sui-move-build/tests/linter/coin_field.exp, crates/sui-move-build/tests/linter/coin_field.move
This fixes a coin-field linter bug - Coin was identified by module name only rather than by module name AND struct name...
Added a test checking that the spurious linter warning message is not generated.
---
Coin-field linter will no longer generate a spurious warning message when a field of a given object is from the `coin` module but is not a `Coin` itself.
=> [move-compiler] Coin field linter fix

crates/sui-graphql-e2e-tests/tests/packages/friends.exp, crates/sui-graphql-e2e-tests/tests/packages/friends.move, crates/sui-graphql-e2e-tests/tests/packages/functions.exp, crates/sui-graphql-e2e-tests/tests/packages/functions.move, crates/sui-graphql-e2e-tests/tests/packages/modules.exp, crates/sui-graphql-e2e-tests/tests/packages/modules.move, crates/sui-graphql-e2e-tests/tests/packages/structs.exp, crates/sui-graphql-e2e-tests/tests/packages/structs.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/event_connection/event_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Merge `MoveModuleId` with `MoveModule` by introducing fields to the latter containing the module's package and name, and replace the reference to `MoveModuleId` in `Event` with `MoveModule`.
Fixed up E2E tests:
```
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
- #15015
- #15016
- #15018
=> [GraphQL/MoveModule] Remove MoveModuleId

crates/sui-core/src/authority.rs
The metric guard was already started inside authority server: https://github.com/MystenLabs/sui/blob/main/crates/sui-core/src/authority_server.rs#L338
CI
---
=> handle_transaction_latency metric

Cargo.lock, crates/sui-aws-orchestrator/Cargo.toml, crates/sui-aws-orchestrator/README.md, crates/sui-aws-orchestrator/assets/grafana-dashboard-narwhal-only.json, crates/sui-aws-orchestrator/src/main.rs, crates/sui-aws-orchestrator/src/measurement.rs, crates/sui-aws-orchestrator/src/orchestrator.rs, crates/sui-aws-orchestrator/src/protocol/mod.rs, crates/sui-aws-orchestrator/src/protocol/narwhal.rs, crates/sui-benchmark/src/drivers/bench_driver.rs, narwhal/config/src/committee.rs, narwhal/config/src/lib.rs, narwhal/node/src/benchmark_client.rs, narwhal/node/src/main.rs, narwhal/node/src/metrics.rs, narwhal/worker/src/transactions_server.rs
Added narwhal only benchmark using aws-orchestrator. Once stable we can remove the old narwhal benchmark suite (which is currently broken) 
Some changes were made to narwhal genesis and usage can be found here
- benchmark config generator
`RUST_LOG=info cargo run --release --bin narwhal-node benchmark-genesis  --working-directory ~/benchmark --ips 127.0.0.1,127.0.0.1,127.0.0.1,127.0.0.1 --num-workers 1 --base-port 5000`
- running benchmark setup (worker + primary in process)
`RUST_LOG=debug cargo run --release --bin narwhal-node run --primary-keys ~/benchmark/primary-3-key.json --primary-network-keys ~/benchmark/primary-3-network-key.json --worker-keys ~/benchmark/worker-3-key.json --committee ~/benchmark/committee.json --workers ~/benchmark/workers.json --store ~/benchmark/db-3 …
=> Narwhal only benchmark using aws orchestrator

external-crates/move/crates/move-analyzer/editors/code/.vscodeignore, external-crates/move/crates/move-analyzer/editors/code/LICENSE, external-crates/move/crates/move-analyzer/editors/code/README.md, external-crates/move/crates/move-analyzer/editors/code/package-lock.json, external-crates/move/crates/move-analyzer/editors/code/package.json, external-crates/move/crates/move-analyzer/editors/code/scripts/create.sh, external-crates/move/crates/move-analyzer/editors/code/src/configuration.ts, external-crates/move/crates/move-analyzer/editors/code/src/main.ts
This PR adds bundling of platform-specific move-analyzer binary with the VSCode extension distribution itself. This seems like the current solution of choice (e.g., adopted by newer versions of rust-analyzer).
The PR includes required changes to TS code as well as a script responsible for packaging bundled extensions locally (for testing) as well as publishing them.
Added licensing information copied from the root of the Sui repository to have it included in VSCode Marketplace once the extension is published.
This PR is marked as not having user-visible impact as it's not a change to the existing extension but rather one of the initial steps to creating a new one.
I tested this pretty extensively manually on a Mac (not sure if it's even possible to automate this). I also tested bundled …
=> [move-ide] Bundling of move-analyzer binary with the plugin

Cargo.lock, crates/simulacrum/src/lib.rs, crates/sui-core/Cargo.toml, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/consensus_types/consensus_output_api.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/tests/staged/sui.yaml, crates/sui-e2e-tests/tests/multisig_tests.rs, crates/sui-e2e-tests/tests/zklogin_tests.rs, crates/sui-graphql-e2e-tests/tests/transactions/system.exp, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_32.snap, crates/sui-rosetta/src/types.rs, crates/sui-transactional-test-runner/src/test_adapter.rs, crates/sui-types/src/digests.rs, crates/sui-types/src/messages_checkpoint.rs, crates/sui-types/src/messages_consensus.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/messages_tests.rs, narwhal/types/src/consensus.rs, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/next-vm/sui-adapter/src/execution_engine.rs, sui-execution/v0/sui-adapter/src/execution_engine.rs, sui-execution/v1/sui-adapter/src/execution_engine.rs
This PR implements consensus folk detection by adding consensus output digest into consensus commit prologue transaction. The digest implementation uses the existing ConsensusOutputCommit.
Unit test to test to test basic ConsensusCommitPrologueV2
Unit test to test CheckpointSummary creates different digest if the included ConsensusCommitPrologueV2 transactions have different consensus output digest.
---
=> Consensus folk detection

crates/sui-analytics-indexer/src/handlers/event_handler.rs, crates/sui-analytics-indexer/src/handlers/object_handler.rs, crates/sui-analytics-indexer/src/package_store.rs
Without this, package resolution is slow in parsing object as package. This keeps the parsed object in local cache which seems to be 10-20x faster
Running locally produces much faster results. And graphql uses the same setup, so this is just following the existing practice
=> Add local cache for package resolver in analytics

crates/sui-analytics-indexer/src/store/snowflake/schemas/checkpoint.sql, crates/sui-analytics-indexer/src/store/snowflake/schemas/event.sql, crates/sui-analytics-indexer/src/store/snowflake/schemas/move_call.sql, crates/sui-analytics-indexer/src/store/snowflake/schemas/object.sql, crates/sui-analytics-indexer/src/store/snowflake/schemas/package.sql, crates/sui-analytics-indexer/src/store/snowflake/schemas/setup.sql, crates/sui-analytics-indexer/src/store/snowflake/schemas/transaction.sql, crates/sui-analytics-indexer/src/store/snowflake/schemas/transaction_objects.sql
Add schemas for setting up analytics suite in snowflake. This is a snapshot of the existing schemas which can be reused to bootstrap analytics framework
Followed schemas in this PR to set up parquet based data ingestion
=> Add snowflake anlytics schemas

docker/grafana-local/dashboards/dashboard.yaml, docker/grafana-local/dashboards/validator-dashboard.json, docker/grafana-local/docker-compose.yaml, docker/grafana-local/prometheus.yaml
Local cluster means a testing cluster running in one machine.
The validator ports need to be fixed, and such cluster config can be generated using `sui genesis --benchmark-ips <ips>`. If the ports are dynamic, `prometheus.yaml` needs to be updated to use the corresponding metrics port from the validators.
Also added an example dashboard to show some metrics example. And future testing can build the dashboard from there (or import it from somewhere).
---
=> Allow `grafana-local` to track and show metrics in local cluster

crates/sui-graphql-e2e-tests/tests/limits/directives.exp, crates/sui-graphql-e2e-tests/tests/limits/directives.move, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
Until we formally support them, enforce ban on [directives](https://www.apollographql.com/docs/apollo-server/schema/directives/) which could be confusing if expected to work.
e2e test included and manual.
---
=> [graphql/rpc] enforce ban on directives

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
Add back parallel checkpoint execution since we have MVCC now. (Undo the effect of #10546).
Benchmark result:
command: `cargo run --release --bin sui-single-node-benchmark -- --tx-count 500000 --component checkpoint-executor --checkpoint-size 5 --num-input-objects 2 no-move`
before `TPS=16310.020876826722`
after `TPS=17611.214821598394`
---
=> Parallel checkpoint execution

crates/sui-framework/packages/move-stdlib/sources/unit_test.move, external-crates/move/crates/move-stdlib/sources/unit_test.move, external-crates/move/crates/move-stdlib/src/natives/mod.rs, external-crates/move/crates/move-stdlib/src/natives/unit_test.rs, external-crates/move/crates/move-unit-test/tests/test_sources/use_unit_test_module.exp, external-crates/move/crates/move-unit-test/tests/test_sources/use_unit_test_module.move, external-crates/move/move-execution/next-vm/crates/move-stdlib/sources/unit_test.move, external-crates/move/move-execution/next-vm/crates/move-stdlib/src/natives/unit_test.rs
- This will replace create_signers_for_testing
- #14994 is blocked (and probably rightfully so) as we have some projects in examples that download the stdlib from testnet. Those examples were failing in the signer removal PR since the new `unit_test::poison` function did not exist in that stdlib.
- We can land this smaller change and wait for it to get pulled into testnet before landing the breaking change
- Added a new test to call the poison function
---
=> [move-stdlib] Add new unit_test::poison function

crates/sui-graphql-e2e-tests/tests/transactions/errors.exp, crates/sui-graphql-e2e-tests/tests/transactions/errors.move, crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
Use the `error`'s `Display` impl rather than its `Debug` impl, so that the error message becomes a human-readable sentence, and represent the command as a 1-indexed ordinal number with a suffix so it's more obvious whether it's 1- or 0-indexed.
E2E tests (including new ones)
```
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
- #15015
- #15016
- #15018
- #15020
- #15021
- #15036 
- #15037 
- #15038
=> [GraphQL/TransactionBlock] Improve error representation

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Fill out doc comments for the various effect-related types that don't have them.
Snapshot tests:
```
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
- #15015
- #15016
- #15018
- #15020
- #15021
- #15036 
- #15037 
- #15038 
- #15039 
- #15040
=> [GraphQL/TransactionBlock][EASY] Doc comments for effect types

crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/models_v2/objects.rs
We switched to use long canonical format for object types and caused confusion for clients. 
This PR makes sure that for coin read API, the short format is still being output.
tested locally
---
=> [indexer] output response using short format for coin type

crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/transaction_input_loader.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-test-transaction-builder/src/lib.rs
When an object is missing from the store, instead of always return ObjectNotFound, we try to be more smart about the error. This is important because different validators could have different view of an old object due to pruning. So when queried using an old object, we want validators to return a more consistent error result.
TODO: I will add some tests.
---
=> Return more accurate error for missing input object

crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/down.sql, crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/up.sql, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/handlers/mod.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/models_v2/objects.rs, crates/sui-indexer/src/schema_v2.rs, crates/sui-indexer/src/store/indexer_store_v2.rs, crates/sui-indexer/src/store/pg_indexer_store_v2.rs, crates/sui-indexer/src/types_v2.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Add objects_history table with partitions, where
- each new object version will be appended to the table with a new row
- deleted, wrapped, unwrapped_then_deleted will be marked as WrappedOrDeleted in the object_status column
This is to unblock checkpoint consistent read (CSR) on RPC 2.0 graphQL server
local run and make sure that objects_history can be populated with partitions
---
=> indexer: object history with partition

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/balance_change.rs, crates/sui-graphql-rpc/src/types/big_int.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Represent a `BalanceChange` using the underlying indexer representation (like `Object` and `TransactionBlockEffects`) and document it.
```
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
- #15015
- #15016
- #15018
- #15020
- #15021
- #15036 
- #15037 
- #15038 
- #15039 
- #15040
- #15041
- #15042
=> [GraphQL/TransactionBlock] BalanceChange Representation

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/balance_change.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_type.rs, crates/sui-graphql-rpc/src/types/move_value.rs
Previously `MoveType` was represented using its string representation. This meant that everywhere we needed to create a `MoveType`, we had to be careful to ensure we canonicalised the string representation first. This PR flips things around so that the native representation relies on `TypeTag` and we derive the canonical form of it when requested (by the accessing the `repr` field).
This makes it harder (or impossible) to accidentally return a non-canonical type in a query response.
```
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
- #15015
- #15016
- #15018
- #15020
- #15021
- #15036 
- #15037 
- #15038 
- #15039 
- #15040
- #15041
- #15042 
- …
=> [GraphQL/MoveType] Represent using TypeTag

crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/down.sql, crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/up.sql, crates/sui-indexer/src/schema_v2.rs, crates/sui-indexer/src/store/pg_indexer_store_v2.rs, crates/sui-indexer/src/store/pg_partition_manager.rs
impl objects_snapshot table, instead of taking literal snapshots from objects, this snapshot is generated by folding the objects_history and only keeping data with max object version to avoid requirements of DB snapshot features and the related migration costs.
- local run to make sure snapshot table is populated
- verify that after generating snapshot from a epoch, total number of objects in snapshot is equal to distinct object id in the past partitions of objects_history
```
checking after epoch 9, where the next cp is 699410
SELECT COUNT(DISTINCT object_id) from objects_history WHERE checkpoint_sequence_number < 699410;
2079
SELECT COUNT(*) FROM objects_snapshot;
2079
```
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, …
=> indexer: object snapshot for cp consistent read

crates/sui-cluster-test/src/cluster.rs, crates/sui-config/src/lib.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-keys/src/keystore.rs, crates/sui-keys/src/lib.rs, crates/sui-keys/src/random_names.rs, crates/sui-keys/tests/tests.rs, crates/sui-rosetta/src/main.rs, crates/sui-sdk/examples/utils.rs, crates/sui-sdk/tests/tests.rs, crates/sui/src/client_commands.rs, crates/sui/src/keytool.rs, crates/sui/src/sui_commands.rs, crates/sui/src/unit_tests/keytool_tests.rs, crates/sui/src/zklogin_commands_util.rs, crates/sui/tests/cli_tests.rs, crates/test-cluster/src/lib.rs
This PR adds support for basic alias naming of Sui addresses in the keystore. If an alias is not provided, it will automatically generate a random name as `first-second` based on a list of predefined strings (adjectives and precious stone gems). 
Added tests to ensure new functionality works as expected. 
Manual tests:
`sui client new-address ed25519 my_alias_test / sui client new-address ed25519`
---
Added initial support for basic alias naming of Sui addresses in the keystore.
=> [cli] add alias support for sui addresses in the CLI

crates/sui-keys/src/keystore.rs, crates/sui/src/client_commands.rs, crates/sui/src/console.rs
Add support for showing aliases when calling `sui client addresses`.
---
Added support for showing the aliases when calling the `sui client addresses` command. If you used to call this command passing the `--json` flag, the update will break the format. For each address, it will also give return the alias, so each item in the address array will be an array itself, containing two elements: alias and address.
=> [cli] Display aliases when calling `sui client addresses`

crates/sui-keys/src/keystore.rs, crates/sui-keys/tests/tests.rs, crates/sui/src/keytool.rs
Display alias for each key when calling `sui keytool list`. 
Extra tests added for new keystore APIs that were introduced.
---
Added functionality to show the aliases of each address when calling the `sui keytool list` CLI command.
=> [cli/alias] Add alias to keytool list

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Represent a `TransactionBlock` by its stored form and its native form, similar to `TransactionBlockEffects`, `Object`, etc.  This simplifies the process of translating between transactions and their effects.
This PR also cleans up the doc comments for the fields of `TransactionBlock` and orders its fields as in the draft schema.
```
```
- #15095
- #15145
=> [GraphQL/TransactionBlock] TransactionBlock representation

crates/sui-graphql-e2e-tests/tests/transactions/system.exp, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
System transactions have a sentinel `0x0` sender -- recognise that and represent that as the transaction having no sender, rather than providing access to the `0x0` address.
```
-- transactions/system.move
```
- #15095 
- #15145 
- #15146
=> [GraphQL/TransactionBlock] No sender for system transactions

crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp, crates/sui-graphql-e2e-tests/tests/transactions/programmable.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Make sure all the transaction kind types end in `Transaction`, except `ProgrammableTransactionBlock` which is a compound transaction, so ends in `Block`.  Make sure the types match what is in the drafts.
```
sui-graphql-e2e-tests$ cargo nextest run -j 1 --feaures pg_integration
```
- #15095 
- #15145 
- #15146 
- #15147
=> [GraphQL/TransactionBlock] Consistent naming for kind types

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind.rs
Move `impl From<NativeTransactionKind> for TransactionBlockKind` into the `transaction_block_kind` module, from `db_data_provider`, in preparation for updating its representation.
This PR also changes the conversion to be from value.  This will become more relevant when the conversion operator works by wrapping the native type with the GraphQL type (in follow-up PRs).
This change doesn't affect behaviour at all:
```
```
- #15095 
- #15145 
- #15146 
- #15147
- #15179
- #15180
=> [GraphQL/TransactionBlockKind][EASY] Move `From` impl into module

crates/sui-graphql-e2e-tests/tests/transactions/system.exp, crates/sui-graphql-e2e-tests/tests/transactions/system.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/transaction_block/transaction_block_kind.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/change_epoch.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Complete support for the ChangeEpoch transaction kind, leveraging the support for representing `Object`s that have not been indexed to represent the contents of system package upgrades.
This PR adds the following fields:
- `ChangeEpochTransaction.protocolVersion`.
- `ChangeEpochTransaction.systemPackageConnection`.
And renames `ChangeEpochTransaction.timestamp` to `ChangeEpochTransaction.startTimestamp` to match its representation in `sui-types`.
It also uses the native representation of `ChangeEpochTransaction` as the underlying representation of the GraphQL type, moving it into its own module.
It's not easy to simulate a system package upgrade using transactional tests, so instead, tested manually, by viewing the following transaction: `F8GGcAVhtPumDoXzc6z9N8Hf9zoTNFx1BPiCy7FJNZsQ` …
=> [GraphQL/TransactionBlock] ChangeEpochTransaction

crates/sui-graphql-e2e-tests/tests/transactions/system.exp, crates/sui-graphql-e2e-tests/tests/transactions/system.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/transaction_block/transaction_block_kind.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-types/src/object.rs, sui-execution/next-vm/sui-adapter/src/execution_engine.rs
Revamp `GenesisTransaction`:
- Use native representation.
- Return object contents, as serialized in the transaction rather than the Object ID of the created object.
- Return objects in a connection, because they can now contain nested queries.
Updated E2E Test:
```
-- system.move
```
- #15095 
- #15145 
- #15146 
- #15147
- #15179
- #15180 
- #15181 
- #15182
=> [GraphQL/TransactionBlock] GenesisTransaction

crates/sui-graphql-e2e-tests/tests/transactions/system.exp, crates/sui-graphql-e2e-tests/tests/transactions/system.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/transaction_block/transaction_block_kind.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/date_time.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/consensus_commit_prologue.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
- Move implementation to its own module.
- Align with pattern used for other kind types (relying on the native representation), but with a twist.
- Adds `consensusCommitDigest` from the V2 version.
- Rename `timestamp` to `commitTimestamp` to match core protocol type.
```
-- system.move
```
- #15095 
- #15145 
- #15146 
- #15147
- #15179
- #15180 
- #15181 
- #15182 
- #15183
=> [GraphQL/TransactionBlock] ConsensusCommitPrologueTransaction

crates/simulacrum/src/lib.rs, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/transactions/random.exp, crates/sui-graphql-e2e-tests/tests/transactions/random.move, crates/sui-graphql-e2e-tests/tests/transactions/system.exp, crates/sui-graphql-e2e-tests/tests/transactions/system.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/randomness_state_update.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-rest-api/src/node_state_getter.rs, crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/lib.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Add structured support for the `RandomnessStateUpdate` transaction.
Added a new E2E test that sets up the randomness object, and updates it:
```
-- random.move
```
This required making some changes and additions to the transactional test runner:
- Epoch changes using `EndOfEpochTransaction` (the newer form) instead of `ChangeEpoch`.
- A `--create-random-state` option for `advance-epoch`.
- A `set-random-state` command for running the associated system transaction.
- An API for extracting the latest Epoch ID.
This has knock-on effects to other tests:
- Digests change because the epoch change transaction kind has changed.
- The test for `ChangeEpochTransaction` no longer works (but this will be fixed once …
=> [GraphQL/TransactionBlock] RandomnessStateUpdate

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Structured representation of `AuthenticatorStateUpdate` system transaction.
Manual test (reading transaction `AwTZ7qm3BSPfDLJdut8WfF7xrqLLg6oamxCAy6UGyBbB`):
- #15095 
- #15145 
- #15146 
- #15147
- #15179
- #15180 
- #15181 
- #15182 
- #15183 
- #15184 
- #15185
=> [GraphQL/TransactionBlock] AuthenticatorStateUpdate

crates/sui-bridge/src/eth_syncer.rs, crates/sui-bridge/src/lib.rs, crates/sui-bridge/src/sui_client.rs, crates/sui-bridge/src/sui_mock_client.rs, crates/sui-bridge/src/sui_syncer.rs, crates/sui-indexer/src/apis/indexer_api_v2.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-types/src/event.rs
Implements `SuiSyncer` that periodically pulls from Sui to fetch Bridge related events. 
---
Implements `SuiSyncer` that periodically pulls from Sui to fetch Bridge related events.
=> [bridge 4/n] SuiSyncer

crates/sui-graphql-rpc/schema/draft_target_schema.graphql
All the information that was contained in this structure is derivable from other sources.  Originally we thought that we would need to surface the end of epoch commitments specially but this too is already exposed as:
```graphql
query {
epoch(epochId: E) {
checkpointConnection(last: 1) {
previousCheckpointDigest
liveObjectSetDigest
}
}
}
```
:eyes:
=> [GraphQL/Schema]  Remove reference to EndOfEpochData

crates/sui-graphql-e2e-tests/tests/available_range/available_range.exp, crates/sui-graphql-e2e-tests/tests/available_range/available_range.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/types/available_range.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
According to data platform, the min and max checkpoints in checkpoint table correspond to the avail range, and the table is ordered.
e2e test
---
=> [graphql/rpc] available range support

crates/sui-graphql-e2e-tests/tests/call/checkpoint_connection_pagination.exp, crates/sui-graphql-e2e-tests/tests/call/checkpoint_connection_pagination.move, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs
Simplify cursor logic for checkpoints to just the first+after and last+before cases, and return an error for all other combinations.
New test checkpoint_connection_pagination.move
---
=> [graphql][fix][breaking] cursor logic for checkpoint connection

crates/sui-graphql-e2e-tests/tests/objects/filter_by_type.exp, crates/sui-graphql-e2e-tests/tests/objects/filter_by_type.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/object_connection/filter_on_generic_type.graphql, crates/sui-graphql-rpc/examples/object_connection/filter_on_type.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Today we have a cascading filter of package, module, and ty on the ObjectFilter. This PR combines the three fields into 1, and adds logic to handle looking up generic types. 
Now, callers can provide
1. primitive like u64
2. just the package, 0x2
3. package and module: 0x2::coin
4. package, module, type: 0x2::coin::Coin
5. fully instantiated type: 0x2::coin::Coin<0x2::sui::SUI>
New filter_by_type.move
---
=> [graphql][feature][breaking] compound type filter on ObjectFilter

crates/sui-graphql-e2e-tests/tests/epoch/epoch.exp, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-indexer/migrations_v2/2023-08-19-044052_epochs/up.sql, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/models_v2/epoch.rs, crates/sui-indexer/src/schema_v2.rs, crates/sui-indexer/src/store/pg_indexer_store_v2.rs, crates/sui-indexer/src/types_v2.rs
GraphQL server also needs system state object for each epoch.
Instead of adding it to the existing epochs table, this PR adds a new table b/c epoch rows have been sorta heavy and cause extra latency on Explorer, so we will want to keep it lean.
local run to make sure system states table is populated for each epoch
---
=> indexer: system states for graphQL

crates/typed-store/src/rocks/mod.rs, crates/typed-store/src/rocks/safe_iter.rs
Similar change to #10756 , to SafeIterator
Existing unit tests have good coverage for SafeIterator (not for the old iterator though). I'll send out a test specific PR for the old iterator next.
---
=> Do not always seek to first when creating SafeIterator

crates/sui-framework/packages/sui-framework/sources/clock.move, docs/content/guides/developer/sui-101/access-time.mdx
The Clock test in the docs had diverged from the test in the framework, (`sui-framework/tests/clock_tests.move`) and so no longer worked.
This PR brings them back in line with each other.
Closes #15226
:eyes: +
```
sui-framework-tests$ cargo nextest run -- run_sui_framework_tests
```
=> [Docs/Clock] Fix Clock Test

crates/sui-graphql-e2e-tests/tests/event_connection/pagination.exp, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
Need to reverse the result set if the 'last' value is provided.
Update existing event_connection/pagination.exp test to correct snapshot
---
=> [gql][fix] reverse event connection result if last provided

crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp, crates/sui-graphql-e2e-tests/tests/transactions/programmable.move, crates/sui-graphql-e2e-tests/tests/transactions/system.exp, crates/sui-graphql-e2e-tests/tests/transactions/system.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/test_infra/cluster.rs, crates/sui-graphql-rpc/src/types/base64.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/object_change.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Structured representation of ProgrammableTransactionBlock.  The implementation diverges from the originally written schema in some important ways:
- `TransactionInput` has changed drastically. Previously it was a union between `MoveObject`, `MovePackage` and `SharedInput`. Now it is a union between `ImmutableOrOwned` (object), `SharedInput`, `Receiving`, and `Pure`. This is because it's not possible to know from the transaction kind alone whether a given input is a package or an object, so they have been combined into `ImmutableOrOwned`, the absence of `Pure` arguments was a previous oversight, and `Receiving` is a new feature.
- Types that were empty in the schema now need a dummy field.
- The `inputs` and `transactions` fields are now connections, because they can contain complex …
=> [GraphQL/TransactionBlock] ProgrammableTransactionBlock

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/types/big_int.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/date_time.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/open_move_type.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
The draft schema and real schema diverged quite a bit while we added new features and responded to feedback.  It was becoming unclear which differences were because we responded to feedback directly in the implementation, and which ones were features we need to implement from the draft.
This PR brings it back in line so that the draft schema can once again act as a source of truth:
- Ported over doc comments from the draft schema
- Made some fields non-nullable to match schema (`OpenMoveType`, mainly).
- Made `ServiceConfig` limit fields all `Int` rather than `BigInt` (these limits won't be over 2^53).
- Changes to execution APIs to reflect recent discussions with @oxade (dry-run API doesn't accept an epoch parameter, accepts gas objects by ObjectRef rather than just by ID, and also …
=> [GraphQL/Schema][chore] Sync draft schema with current

crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Add the ability to specify a transction input that is a read-only shared object (So I can test what transaction effects look like when a transaction includes one of these).
Tested in a follow-up PR that uses this in one of its tests.
=> [transactional-test-runner] read-only shared inputs

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_32.snap
Delay this to Jan.
This is already on Testnet so there is no other effect removing this feature override for v32 on mainnet.
CI
---
=> Delay shipping effects v2 to mainnet

crates/simulacrum/src/epoch_state.rs, crates/sui-config/src/node.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-genesis-builder/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, external-crates/move/crates/move-vm-config/src/runtime.rs, external-crates/move/move-execution/v0/move-vm/runtime/src/interpreter.rs, external-crates/move/move-execution/v0/move-vm/runtime/src/loader.rs, external-crates/move/move-execution/v1/crates/move-vm-runtime/src/interpreter.rs, external-crates/move/move-execution/v1/crates/move-vm-runtime/src/loader.rs, scripts/execution_layer.py, sui-execution/latest/sui-adapter/src/adapter.rs, sui-execution/next-vm/sui-adapter/src/adapter.rs, sui-execution/src/latest.rs, sui-execution/src/lib.rs, sui-execution/src/lib.template.rs, sui-execution/src/next_vm.rs, sui-execution/src/v0.rs, sui-execution/src/v1.rs, sui-execution/v0/sui-adapter/src/adapter.rs, sui-execution/v1/sui-adapter/src/adapter.rs
Didn't make sense to keep this for old execution versions but it was causing additional work to keep around, so removing it there as well. 
=> [move-vm] Remove paranoid mode from previous execution versions

Cargo.lock, Cargo.toml, crates/sui-core/src/unit_tests/move_package_publish_tests.rs, crates/sui-move-build/Cargo.toml, crates/sui-move-build/src/lib.rs, external-crates/move/crates/move-package/src/lib.rs, external-crates/move/crates/move-package/src/lock_file/schema.rs, external-crates/move/crates/move-package/tests/test_lock_file.rs
As in title, see inline for more.
Updated tests.
---
=> move: build writes toolchain version to Move.lock

external-crates/move/crates/move-analyzer/src/symbols.rs, external-crates/move/crates/move-analyzer/tests/symbols/sources/M6.move
This PR fixes a problem with doc comments being incorrectly extracted for display in "type-on-hover" IDE feature. We were trying to add doc comments for identifiers that should never have them. It's more in sync with how rust-analyzer is extracting and displaying them.
Tests have been modified to reflect this and new tests have been added.
=> [move-ide] Fixed doc comment treatment in symbolicator

crates/sui-core/src/db_checkpoint_handler.rs, crates/sui-snapshot/src/uploader.rs
Formal snapshots are much smaller than db snapshots, hence they take much less time to upload. Additionally, validators are the greatest beneficiaries of formal snapshots, and are more sensitive to the effects of lagging the network, therefore there is a strong need for formal snapshots of the current epoch to be available as quickly as possible after epoch change (6 hour lag out of a 24 hour epoch is too long).
To address this, for a node that is configured to upload both snapshot types, formal snapshots will be the first to start, and db snapshot upload will block on its completion (note that we cannot do them concurrently as they both need to open the db checkpoint as a perpetual DB - formal snapshots in order to scan the live object set, and db checkpoint uploader to prune and …
=> [snapshots] Upload formal snapshots before db snapshots

crates/sui-core/src/unit_tests/transaction_tests.rs, crates/sui-types/src/multisig.rs, crates/sui-types/src/multisig_legacy.rs, crates/sui-types/src/signature.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/multisig_tests.rs, crates/sui-types/src/zk_login_authenticator.rs
check zklogin authenticator derives the same address as the public key identifier from multisig public key. 
unit test
---
=> zklogin: check multisig public key derive consistency

crates/sui-core/src/unit_tests/transaction_tests.rs, crates/sui-types/src/multisig.rs, crates/sui-types/src/multisig_legacy.rs, crates/sui-types/src/signature.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/multisig_tests.rs, crates/sui-types/src/zk_login_authenticator.rs
check zklogin authenticator derives the same address as the public key identifier from multisig public key.
unit test
---
---------
---
=> zklogin: check multisig public key derive consistency (#15208)

Cargo.lock, crates/simulacrum/src/lib.rs, crates/sui-cluster-test/src/lib.rs, crates/sui-core/src/test_utils.rs, crates/sui-faucet/src/bin/merge_coins.rs, crates/sui-faucet/src/faucet/simple_faucet.rs, crates/sui-graphql-rpc/src/mutation.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-replay/Cargo.toml, crates/sui-replay/src/replay.rs, crates/sui-rosetta/src/construction.rs, crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs, crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs, crates/sui-sdk/examples/programmable_transactions_api.rs, crates/sui-sdk/examples/sign_tx_guide.rs, crates/sui-sdk/examples/tic_tac_toe.rs, crates/sui-sdk/examples/utils.rs, crates/sui-sdk/src/wallet_context.rs, crates/sui-test-transaction-builder/src/lib.rs, crates/sui-types/src/messages_checkpoint.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/intent_tests.rs, crates/sui-types/src/unit_tests/messages_tests.rs, crates/sui-types/src/unit_tests/utils.rs, crates/sui/src/client_commands.rs, crates/sui/src/fire_drill.rs, crates/sui/src/unit_tests/validator_tests.rs, crates/sui/src/validator_commands.rs, crates/sui/src/zklogin_commands_util.rs
All transaction messages should have the same intent, which can be hard coded instead of always passing in, which adds possibility for introducing errors and bugs.
CI. All changes are trivial and straightforward.
---
=> Hardcode intent for transaction messages

crates/sui-graphql-e2e-tests/tests/objects/pagination.exp, crates/sui-graphql-e2e-tests/tests/objects/pagination.move, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs
Last of the multi get queries backing connections. Fix results returned for last + before queries to return results in ascending order.
objects/pagination.move
---
=> [gql] update cursor logic for coins and objects

Cargo.lock, crates/sui-keys/Cargo.toml, crates/sui-keys/src/keystore.rs, crates/sui-keys/tests/tests.rs, crates/sui/src/keytool.rs
Provide a new command for updating the alias of an address. The new command `keytool alias` has one flag `--update`, followed by an old alias that needs to be updated, and optionally, a new alias name. If there is no new alias given, a new random alias will be generated.
An example for using this command is: 
`sui keytool update-alias test high_yield_address`, which outputs the following text:
`Old alias test was updated to high_yield_address`
Two new tests for FileBasedKeystore and InMemKeystore.
---
Added support for updating an alias of an address in the Sui CLI. …
=> [cli/alias] Keytool update alias

crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/test_infra/cluster.rs, crates/sui-graphql-rpc/tests/examples_validation_tests.rs
This PR makes the prod limits smaller
The values were chosen based on the limits in our examples which are:
Max nodes: 39, Max depth: 11, Max payload: 976
Existing
---
=> [graphql/rpc] reduce limits

crates/sui-macros/src/lib.rs, crates/sui-node/src/lib.rs
Introduces a macro for logging only in replay tests, which will print debug logs when `REPLAY_LOG` envvar is present
It compiles
---
=> Introduce replay logging macro

crates/sui-keys/src/keystore.rs, crates/sui-keys/tests/tests.rs, crates/sui/src/client_commands.rs, crates/sui/src/keytool.rs
Introduce a validation step when creating or updating an alias. The alias must start with a letter and can contain only letters, digits, hyphens (-), or underscores (_). 
Updated existing tests.
---
Added a validation step when creating or updating an alias of an address in the Sui CLI. The alias must start with a letter and can contain only letters, digits, hyphens (-), or underscores (_).
=> [cli] Validate alias

crates/sui-source-validation-service/src/lib.rs
Suppress warnings in logs for source service so this doesn't clutter Grafana logs.
Checked locally that warnings are suppressed.
---
=> move: suppress log spew in source service

external-crates/move/crates/move-analyzer/src/symbols.rs
This PR extends on-hover functionality for struct types - when hovering over the type, instead of just seeing the type name, what is now displayed is the whole structure of the type (including fields). In addition to being more informative, this is also more in line with what rust-analyzer provides.
Test have been adjusted to reflect this change.
=> [move-ide] Extended on-hover for struct types

crates/sui-macros/src/lib.rs
Because chain replay logs are exceedingly verbose, we will need to run them with `info` level. This means that this logging macro will need to run in `info` level lest they be ignored.
👀 
---
=> [replay tooling] Move replay log macro to info level

crates/sui-graphql-rpc/src/server/builder.rs
Since we have custom `query_limits_checker` which has been shown to work, we don't need the limit [logic](https://async-graphql.github.io/async-graphql/en/depth_and_complexity.html) provided by the library.
Removing it allows us make other changes such as making exceptions for schema queries in limits checker.
Existing
---
=> [graphql/rpc] easy: remove old limits logic

crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/stake_connection/stake_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Renames the `active_epoch` and `request_epoch` of `StakedSui` to past tense.
Updated the example.
---
=> [graphql][EASY] Renamed active_epoch and request_epoch to past tense

crates/sui-graphql-e2e-tests/tests/packages/types.exp, crates/sui-graphql-e2e-tests/tests/packages/types.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Makes it possible to get layout information for a type without it being associated to an existing object, as requested by @hayes-mysten.
Note that currently this implementation will report an internal error if you try and fetch the layout of a type that doesn't exist. This should really be a user error (bad user input), for supplying a type that doesn't exist.
This will be fixed in a follow-up when we overhaul the error story for GraphQL (Similar fixes are also required for the database and execution layers as well).
New E2E tests:
```
-- types.move
```
=> [GraphQL/Query] Standalone type query

Cargo.lock, crates/sui-graphql-e2e-tests/tests/call/coin_metadata.exp, crates/sui-graphql-e2e-tests/tests/call/coin_metadata.move, crates/sui-transactional-test-runner/Cargo.toml, crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Interpolates variables in RunGraphqlCommand by replacing instances of "@{var}" to the value of the var named by "var". This follows the obj_x_y syntax for now. Add test for coin metadata to test new feature and test coin metadata implementation on graphql.
cargo nextest run --test-threads 1 --package sui-graphql-e2e-tests --features pg_integration -- coin_metadata.move
---
=> [gql][txn-test-runner] interpolate variables in RunGraphqlCommand

crates/sui-core/src/authority_server.rs
It used to be there because execution was done in the handle_certificate task. Right now we do execution in a separate task, handle_certificate should not be cancellation safe.
List of `await`s in the `handle_certificate` path:
* `signature_verifier.verify_cert` - safe to drop (`verify_cert_inner` seem to have comments about cancellation safety)
* `execute_certificate` - only `await` inside this call is `notify_read_effects` which is cancellation safe
=> [authority] Remove spawn from handle_certificate_v2

crates/sui-core/src/authority_server.rs
As in title
Existing tests in `crates/sui-core/src/unit_tests/authority_tests.rs`. Specifically, `test_refusal_to_sign_consensus_commit_prologue_v2` verifies we reject system transactions.
---
=> [cert handling] Perform fullnode/system tx checks earlier

crates/sui-bridge/src/abi.rs, crates/sui-bridge/src/error.rs, crates/sui-bridge/src/eth_client.rs, crates/sui-bridge/src/eth_syncer.rs, crates/sui-bridge/src/events.rs, crates/sui-bridge/src/lib.rs, crates/sui-bridge/src/orchestrator.rs, crates/sui-bridge/src/storage.rs, crates/sui-bridge/src/sui_syncer.rs, crates/sui-bridge/src/types.rs
Add storage stuff. The meat is in `storage.rs` and `orchestrator.rs`. Note we haven't wired it up in `fn run_eth_watcher`, because some modification are needed in the receiving channel, which will come in the next PR.
High level it works in this way:
```
#[derive(DBMapUtils)]
pub struct BridgeOrchestratorTables {
/// pending BridgeActions that orchestrator received but not yet executed
pub(crate) pending_actions: DBMap<BridgeActionDigest, BridgeAction>,
/// module identifier to starting transaction digest
pub(crate) sui_syncer_cursors: DBMap<Identifier, TransactionDigest>,
/// contract address to starting block
pub(crate) eth_syncer_cursors: DBMap<ethers::types::Address, u64>,
}
```
1. Orchestrator receives events from syncers. If an event is an action (e.g. token transfer), then it …
=> [bridge 10/n] storage

Cargo.lock, crates/sui-graphql-e2e-tests/tests/available_range/available_range.move, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Makes it easier to create effects struct when indexer view is not available
Needed for dry run impl as mentioned here https://github.com/MystenLabs/sui/pull/15167/files
Existing
---
=> [graphql/rpc] Make store effects optional in effects struct

crates/sui-core/src/unit_tests/transaction_tests.rs
- Convert transaction_tests to sim_test so they don't swallow panics
- Check exact errors in all failure cases
=> mlogan transaction test fixes

crates/sui-graphql-rpc/src/server/builder.rs
Removes the `/schema` endpoint e.g https://graphql-beta.mainnet.sui.io/schema which is not really needed anymore
Manual
---
=> [graphql/rpc] easy: remove `/schema` endpoint

crates/sui-core/src/authority.rs, crates/sui-core/src/authority_server.rs, crates/sui-transaction-checks/src/lib.rs, crates/sui-types/src/transaction.rs
Run cheap transaction validity checks when starting to process transactions and certificates.
The checks include the input size count check, that needs to run before system overload and input object checks. This check is moved into `validity_check()` for `ProgrammableTransaction`.
The assumption is that calling `check_version_supported()` and `validity_check()` contain no cryptography or rocksdb ops, so should be cheap enough to run multiple times during the processing of a transaction.
CI
---
=> [Sui] run cheap transaction validity checks early

Cargo.lock, crates/sui-move/Cargo.toml, crates/sui-open-rpc/Cargo.toml
sui_core is not used in these crates, removing dep.
CI
---
=> Remove unused dep to sui_core

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/typed-store/src/rocks/mod.rs, crates/typed-store/src/rocks/tests.rs, crates/typed-store/src/test_db.rs, crates/typed-store/src/traits.rs
Create a `safe_range_iter` and replace existing `range_iter` with it. With `safe_range_iter`, it returns RocksDB erros encountered while iterating through specified key ranges.
Added more unit test to test range iterator.
---
=> Create safe_range_iter and replace range_iter

crates/sui-core/src/authority.rs, crates/sui-core/src/transaction_input_loader.rs, crates/sui-transaction-checks/src/lib.rs
Currently there are both duplications and differences between transaction and certificate input checks. Extracting them into a separate function so it will be easier to update all check logic in future.
Also, remove unnecessary input length checks that should not run during epoch change.
CI
---
=> [Sui] extract common checks for transaction into a separate function

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_test_utils.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/test_utils.rs, crates/sui-core/src/transaction_orchestrator.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/src/unit_tests/consensus_tests.rs, crates/sui-core/src/unit_tests/gas_tests.rs, crates/sui-core/src/unit_tests/transaction_deny_tests.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/reconfiguration_tests.rs
=> Move verify_transaction to AuthorityPerEpochStore to discourage calling it with an out-of-date epoch store

Cargo.lock, crates/sui-core/Cargo.toml, crates/sui-core/src/authority_server.rs, crates/sui-core/src/unit_tests/transaction_tests.rs, crates/sui-types/src/transaction.rs
We should check the size of the txn bytes at the beginning of handle_transaction and handle_certificate.
Added two tests.
---
=> check txn size upfront and add tests for it

crates/sui-types/src/execution_mode.rs, crates/sui-types/src/storage/mod.rs, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs, sui-execution/next-vm/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/v1/sui-adapter/src/temporary_store.rs
- Rewrote the ownership invariant check to hopefully make it a bit easier to follow 
- Threaded in wrapped object data and the mutable input information for more precise ownership checks. Previously we would have missed mutations on readonly/deleted shared objects. Additionally, we assumed any writes to wrapped object children were properly authenticated. 
- Do we have tests for this?
---
=> Make the ownership invariant checks easier to understand. Improved precision.  

crates/sui-storage/src/object_store/util.rs, crates/sui-tool/src/commands.rs, crates/sui-tool/src/lib.rs
It's happened a few times where users try to restore a snapshot that hasn't been uploaded yet or does not exist, this will cleanly exit in the case that the success marker hasn't been uploaded.
tested locally:
```
$ target/debug/sui-tool download-db-snapshot --epoch "439" --genesis "/opt/sui/config/genesis.blob" --formal --network mainnet --path /opt/sui/db/authorities_db --num-parallel-downloads 50 --snapshot-bucket-type=gcs
thread 'main' panicked at /Users/johnmartin/src/github.com/johnjmartin/sui/crates/sui-tool/src/commands.rs:714:21:
Aborting snapshot restore: missing success marker at mysten-mainnet-formal/epoch_439/_SUCCESS
```
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add …
=> check for success before snapshot restore

external-crates/move/crates/move-analyzer/src/symbols.rs, external-crates/move/crates/move-analyzer/tests/symbols/sources/M8.move
This PR extends on-hover functionality for constants. Previously, we were only displaying constant typo on hover, for example:
With this PR, we display constant name, type, and value, which closely resembles what rust-analyzer does:
We need custom to-string conversions as those provided by the compiler for the AST do not look quite right.
Existing tests have been adjusted and tests have been added.
=> [move-ide] Enhancement to on hover for constants

crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/up.sql, crates/sui-indexer/migrations_v2/2023-10-07-160139_display/up.sql, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/handlers/mod.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/store/indexer_store_v2.rs, crates/sui-indexer/src/store/pg_indexer_store_v2.rs, crates/sui-indexer/src/store/pg_partition_manager.rs
main changes are:
- instead of updating object snapshot at epoch boundary, now we update object snapshot following a sliding window of checkpoints, so that each update will not take too long
- fix object history, prev it skipped intermediate object versions, which is correct for `objects` which only tracks latest versions, but not the case for `objects_history`, which is supposed to track all versions
- move advance epoch before checkpoint persisting, so that checkpoint can always be the watermark, in case of pod crashing and resuming, the advance epoch process will be resumed properly too
local run and verify that
- objects_history table has all intermediate versions & checkpoints
- object snapshot can be update properly per the objects_history
---
If your changes are not user-facing and …
=> indexer: quick object snapshot and fix object history

crates/sui-types/src/effects/effects_v2.rs, crates/sui-types/src/execution.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs
Add a few more assertions in effects v2, some comment updates and etc.
CI
---
=> Add more invariants for effects v2

crates/sui-framework-tests/src/unit_tests.rs, crates/sui-move/src/lib.rs, crates/sui-move/src/unit_test.rs, external-crates/move/crates/move-cli/src/base/test.rs
- Refactored the execution of sui-move-test execution to ensure flags aren't ignored 
- Added a `FILTER=<filter>` env for `sui-framework-test` that threads down to sui move test/unit test execution
- 👀 
---
=> Cleaned up sui move test args. Added sui-framework-test filter

Cargo.lock, crates/sui-bridge/Cargo.toml, crates/sui-bridge/src/abi.rs, crates/sui-bridge/src/error.rs, crates/sui-bridge/src/eth_client.rs, crates/sui-bridge/src/eth_syncer.rs, crates/sui-bridge/src/events.rs, crates/sui-bridge/src/orchestrator.rs, crates/sui-bridge/src/types.rs
1. For Orchestrator's eth watcher channel, change eth logs from `Log` to `EthLog`. The latter contains essential attribute of the log, which are Optional in the former. See `fn get_log_tx_details` for the conversion from `Log` to `EthLog`
2. add handling for eth actions (handling for sui actions is done in previous PR)
3. add storage focused tests for orchestrator
---
=> [bridge 11/n] handle eth actions in orchestrator

.github/CODEOWNERS
Noticed CodeOwners is not populated for e2e crates
N/A
---
=> [graphql/rpc] add all members to e2e crate

crates/sui-graphql-e2e-tests/tests/objects/public_transfer.exp, crates/sui-graphql-e2e-tests/tests/objects/public_transfer.move, crates/sui-graphql-e2e-tests/tests/packages/types.exp, crates/sui-graphql-e2e-tests/tests/packages/types.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_type.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Adds a GraphQL field to `MoveType` to expose its `abilities` and use the same source of information to compute `hasPublicTransfer`.
New E2E tests:
```
-- types.move public_transfer.move
```
- #15393
=> [GraphQL/MoveType] Expose type abilities

crates/sui-indexer/src/lib.rs, crates/sui-indexer/src/main.rs
To automate DB reset on CI, staging and devnet more easily
```
cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --reset-db
```
```
2023-12-21T19:23:13.733316Z  INFO sui_indexer::utils: Resetting database ...
2023-12-21T19:23:13.733365Z  INFO sui_indexer::utils: Dropping all tables in the database
2023-12-21T19:23:13.756210Z  INFO sui_indexer::utils: Dropped all tables in the database
2023-12-21T19:23:13.798343Z  INFO sui_indexer::utils: Reset database complete.
2023-12-21T19:23:13.799022Z  WARN sui_indexer: Failed to convert full node url http://0.0.0.0:9000 to a shorter version
2023-12-21T19:23:13.799138Z  INFO sui_indexer: Starting prometheus server with labels: {"indexer_fullnode": "unknown_url"}
2023-12-21T19:23:13.802157Z  INFO sui_indexer: DB …
```
=> indexer: separate cmd for DB reset

Cargo.lock, consensus/config/Cargo.toml, consensus/config/src/committee.rs, consensus/config/src/crypto.rs, consensus/config/src/lib.rs, consensus/config/tests/committee_test.rs, consensus/config/tests/snapshots/committee_test__committee.snap
`Committee` config and crypto key types are added to the `consensus-config` crate.
CI
---
=> [Consensus] add `Committee` type

docker/grafana-local/prometheus.yaml
Added benchmark client metrics collection for analyzing client side metrics. 8081 is the default port and also adds a few custom port.
---
=> local grafana adds metrics collection for benchmark clients

crates/sui-graphql-e2e-tests/tests/call/checkpoint_connection_pagination.exp, crates/sui-graphql-e2e-tests/tests/call/checkpoint_connection_pagination.move, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.exp, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.move, crates/sui-graphql-e2e-tests/tests/objects/pagination.exp, crates/sui-graphql-e2e-tests/tests/objects/pagination.move, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs
The bug is that when only last is provided, because the current implementation depends on using before or after to determine how to order the db, the code ends up returning the behavior as if we provided first. To address this, rather than pass first and last directly to pg_backend, I created a PageLimit enum with variants First, Last. db_data_provider is responsible for determining whether to set the variant as First or Last, and defaults to First(default_page_size) if a value is not provided. Then, pg_backend maps First -> asc and Last -> desc, optionally adding a filter for First -> after and Last -> before
Existing tests should work. Add new tests for connections with just (last: n) to snapshot expected results.
---
If your changes are not user-facing and not a breaking change, you …
=> [gql][fix] connections return correct values for last queries

crates/sui-graphql-e2e-tests/tests/objects/display.exp, crates/sui-graphql-e2e-tests/tests/objects/display.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/types/display.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/move_value.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Implements rendering Display<T> on the graphql::Object through the 'display' field. This will attempt to resolve each template string defined on Display<T>, and returns a corresponding DisplayEntry { key: String, value: Option<String>, error: Option<String> } where a successful render populates DisplayEntry { key, value, error: None }, and any errors encountered populates DisplayEntry { key, None, error }.
objects/display.move
---
=> [gql][feature] display field on object

crates/sui-graphql-e2e-tests/tests/event_connection/pagination.exp, crates/sui-graphql-e2e-tests/tests/objects/pagination.exp, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/available_range.rs, crates/sui-graphql-rpc/src/types/query.rs
Use new available range logic provided in [this](https://github.com/MystenLabs/sui/pull/15339/files#r1425718144) PR as specified by `get_consistent_read_range`.
Existing test
---
=> [graphql/rpc] use new available range logic

crates/sui-faucet/src/faucet/simple_faucet.rs, crates/sui-keys/src/keystore.rs, crates/sui/src/client_commands.rs, crates/sui/src/key_identity.rs, crates/sui/src/keytool.rs, crates/sui/src/lib.rs, crates/sui/src/unit_tests/keytool_tests.rs, crates/sui/tests/cli_tests.rs
Several commands that accept an address for a recipient can also take as input the address' alias if it is in the keystore. This PR allows those commands to accept the alias of an address, or the address as a string.
Added a test.
---
Added support for accepting an address by its alias in several `sui client` commands: `gas, objects, pay-sui, pay-all-sui, transfer, transfer-sui, switch`, and in `sui keytool sign`
=> [cli/alias] accept an address by its alias in `sui client` commands

crates/sui-node/src/metrics.rs
In certain cases where we experience degraded metric submit rates or an inability to submit any, we can experience recovery issues when that degredataion subsides. It is an edge case but it seems to present every so often. The intent of this pr is to recreate a reqwest client anytime we hit an error submitting metrics. This will allow for automatic recovery of the node without restarting. Since our tick interval for submit is every 60 secs, it should be fine to recreate.
local instruments
```
2023-12-19T20:31:02.903599Z  WARN sui_node::metrics: unable to push metrics: error sending request for url (https://metrics-proxy.testnet.sui.io:8443/publish/metrics): error trying to connect: tcp connect error: Connection refused (os error 61); new client will be created
```
and it recovers:
``` …
```
=> [sui-node/metrics] recreate client

crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/call/simple.move, crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Gas price setting wasn't properly exposed per command at at default level
e2e
---
=> [graphql/rpc] make gas price settable everywhere

crates/sui-graphql-e2e-tests/tests/validator/validator.exp, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/epoch/latest_epoch.graphql, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/models_v2/epoch.rs, crates/sui-indexer/src/store/pg_indexer_store_v2.rs, crates/sui-indexer/src/types_v2.rs
quick followups of https://github.com/MystenLabs/sui/pull/15434
also updated system state at the end of epoch
local run and check that last_epoch's system state is always the same as the current epoch via query
```
SELECT a.epoch, a.system_state, b.epoch, b.system_state
FROM epochs a, epochs b
WHERE a.system_state = b.system_state AND a.epoch < b.epoch
```
---
=> indexer: epoch split nits

crates/sui-package-resolver/src/error.rs, crates/sui-package-resolver/src/lib.rs
Implement enforcement for limit on number of type parameters in a single generic type instantiation.
New unit test:
```
```
- #15393 
- #15407 
- #15408
- #15409 
- #15410
- #15442
=> [GraphQL/Package Resolver] Type Parameter width limit

crates/sui-package-resolver/src/error.rs, crates/sui-package-resolver/src/lib.rs
Hook up `max_type_nodes` to limit the number of struct defs that need to be loaded to resolve a single type request (a layout request or an abilities request).
New unit test:
```
sui-package-resolve$ cargo nextest run
```
- #15393 
- #15407 
- #15408
- #15409 
- #15410
- #15442 
- #15443
=> [GraphQL/Package Resolver] Limits for struct defs loaded

crates/sui-package-resolver/src/error.rs, crates/sui-package-resolver/src/lib.rs
Limit how deeply type parameters can be nested in a type tag that needs to be resolved.  This limit only applies to the "outermost" type parameter application, and not to type parameters that exist in signatures in Move bytecode (which already had to go through chain-enforced limits to be published).
```
```
- #15393 
- #15407 
- #15408
- #15409 
- #15410
- #15442 
- #15443 
- #15444
=> [GraphQL/Package Resolver] Limits on type parameter nesting

crates/sui-graphql-e2e-tests/tests/packages/structs.exp, crates/sui-graphql-e2e-tests/tests/packages/structs.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-package-resolver/src/lib.rs
Use the cursor framework for `MoveModule.structConnection` and rename it to `structs`.
Updated E2E tests:
```
-- structs.move
```
- #15467
=> [GraphQL/Cursor] MoveModule.structs

crates/sui-graphql-e2e-tests/tests/packages/functions.exp, crates/sui-graphql-e2e-tests/tests/packages/functions.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-package-resolver/src/lib.rs
Use cursor framework for functions.  This makes the cursor value itself opaque, and standardises the behaviour around default and max page sizes.
Updated E2E tests to expose cursors:
```
-- functions.move
```
- #15467 
- #15470
=> [GraphQL/Cursor] MoveModule.functions

crates/sui-graphql-e2e-tests/tests/packages/friends.exp, crates/sui-graphql-e2e-tests/tests/packages/friends.move, crates/sui-graphql-e2e-tests/tests/packages/functions.exp, crates/sui-graphql-e2e-tests/tests/packages/functions.move, crates/sui-graphql-e2e-tests/tests/packages/modules.exp, crates/sui-graphql-e2e-tests/tests/packages/modules.move, crates/sui-graphql-e2e-tests/tests/packages/structs.exp, crates/sui-graphql-e2e-tests/tests/packages/structs.move, crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp, crates/sui-graphql-e2e-tests/tests/transactions/programmable.move, crates/sui-graphql-e2e-tests/tests/transactions/shared.exp, crates/sui-graphql-e2e-tests/tests/transactions/shared.move, crates/sui-graphql-e2e-tests/tests/transactions/system.exp, crates/sui-graphql-e2e-tests/tests/transactions/system.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/transaction_block/transaction_block_kind.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-package-resolver/src/lib.rs, crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Add a generic framework for opaque cursors.  There is already a type in `async_graphql` that serializes cursors as JSON and then Base64 -- `OpaqueCursor<T>` -- but it doesn't implement `ScalarType`, so this PR introduces a `Cursor<C>` that wraps `OpaqueCursor` to implement both `ScalarType` and `CursorType` so the same type can be used as a parameter for connections and for a field on `Connection`s.
`MoveModule.friendConnection` has been updated to
`MoveModule.friends`, and to use the new cursor framework.
New unit test:
```
sui-graphql-rpc$ cargo nextest run -- types::cursor
```
Updated E2E test:
```
-- friends.move
```
E2E tests have been updated to support injecting cursor variables into the …
=> [GraphQL/Cursor] Cursor Framework

crates/sui-graphql-e2e-tests/tests/validator/validator.exp, crates/sui-graphql-e2e-tests/tests/validator/validator.move, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-indexer/src/models_v2/epoch.rs
Once #15434 lands, we need to switch to QueryableEpochInfo instead of StoredEpochInfo.
---
=> [graphql] switch to QueryableEpochInfo instead of StoredEpochInfo

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/date_time.rs, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/consensus_commit_prologue.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Make datetime to return a result instead of option and fix all associated code that uses DateTime::from_ms
Ran existing unit tests, updated schema.
---
=> [graphql] Make datetime::from_ms return result instead of option

crates/sui-core/src/db_checkpoint_handler.rs, crates/sui-storage/src/object_store/util.rs
Write manifest based on output directory file list so we can be guaranteed of the contents being present
=> Write manifest based on output store

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Small change to add max_output_nodes to ServiceConfig for output node estimation
Existing tests. Functionality will be tested in follow-up PR
---
=> [gql][1/n][easy] add max_output_nodes to ServiceConfig for output node estimation

crates/sui-bridge/src/main.rs, crates/sui-bridge/src/server/handler.rs, crates/sui-bridge/src/server/mod.rs, crates/sui-bridge/src/sui_client.rs
implements simple logic for BridgeRequestHandler::handle_sui_tx_digest. Similar to https://github.com/MystenLabs/sui/pull/15405, optimization will be added together.
unit tests
---
implements simple logic for BridgeRequestHandler::handle_sui_tx_digest.
=> [bridge 15/n] handle sui tx digest

external-crates/move/crates/move-analyzer/src/symbols.rs, external-crates/move/crates/move-analyzer/tests/symbols/sources/M9.move
This PR extends on-hover support to include module accesses. When hovering over a module name, we now see a description of the module and can jump into its definition:
This also works for aliases:
This PR also includes a refactoring to reduce the number of parameters that were being threaded thorough all calls of both symbolicators.
At a high level, the implementation of this new feature is quite simple - a module access that needs to be connected with module definition can only happen when accessing a struct or a const, or when calling a function, and we need to add an additional `UseDef` in these places. What complicates things is aliasing - at the level of typed AST we no longer have access to alias names in module accesses (see explanation around this …
=> [move-ide] Extended on-hover and go-to-def for module accesses

crates/sui-swarm-config/src/genesis_config.rs, crates/sui-swarm-config/src/network_config_builder.rs
Follow up of https://github.com/MystenLabs/sui-operations/pull/2943
Currently validators in our dev environments expose hostnames as "Validator-1,2,3...". We need better insight in our environments when debugging and that labelling doesn't help . Instead exposing the actual hostname (dns url) will help here. Not aware if there is a specific reason of not allowing this.
---
=> [refactor] allow setting validator name during genesis

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/epoch/reconfiguration.rs
Adds a new config state for end-of-epoch in which we reject all certs, but continue to accept system tx (including randomness updates) until all deferred tx have been sequenced.
Also cleans up and fixes issues with final checkpoint generation.
=> Don't end epoch until all deferred tx have been sequenced

crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
Adds a helper function to `Page<usize>` to treat `usize` cursors as indices into an array of some kind, and convert the page into an iterator over elements in that page, identified by their Cursor.
```
sui-graphql-e2e-test$ cargo nextest run \
-j 1 --features pg_integration
```
- #15467 
- #15470 
- #15471 
- #15472 
- #15473
- #15474 
- #15475 
- #15484
=> [GraphQL/Cursor] Abstraction for index-based cursors

crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
We interrupt the scheduled cursor framework PRs to do some clean-ups.
We no longer need this function with the introduction of the new implementation for `availableRange`.
```
```
- #15467 
- #15470 
- #15471 
- #15472 
- #15473
- #15474 
- #15475 
- #15484 
- #15485
=> [GraphQL/Checkpoint][EASY] Remove get_earliest_complete_checkpoint

crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs, crates/sui-indexer/src/apis/indexer_api_v2.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-json-rpc/src/name_service.rs
If we need conversion operators to/from `SuiAddress` and `Address`, move them into `sui_address.rs` or `address.rs` as appropriate, but in most cases, we don't need those operations.
```
```
- #15467 
- #15470 
- #15471 
- #15472 
- #15473
- #15474 
- #15475 
- #15484 
- #15485
- #15519
=> [GraphQL/DB][EASY] (Re)move conversion to/from SuiAddress

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/digest.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/string_input.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs
Create a `impl_string_input` macro that opts a type that implements `FromStr` into being treated as a `ScalarType`, while still appearing as a `String`.
This allows `async-graphql` to handle input validation as part of its own query resolution, which avoids us repeating validation work through-out the codebase.
The `Digest` type is the first type to use the macro (although the pattern is already used by the `Cursor` type), in this PR.
```
```
- #15467 
- #15470 
- #15471 
- #15472 
- #15473
- #15474 
- #15475 
- #15484 
- #15485
- #15519
- #15520
- #15521
- #15522
- #15523
- #15524
- #15525
- #15526
=> [GraphQL/Digest] Refactor Digest type for use as Scalar.

crates/sui-config/src/genesis.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/epoch_start_configuration.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs, crates/sui-node/src/lib.rs, crates/sui-replay/src/replay.rs, crates/sui-snapshot/src/lib.rs
1. Remove unused old constructors.
2. Dedup all the code that reads the init shared versions of epoch start objects.
---
=> Minor cleanups in EpochStartConfig

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_33.snap
Turns on transfer-to-object in mainnet.
Tested and has been running in devnet and testnet for the past couple months.
---
Enables transfer-to-object functionality on mainnet.
=> [transfer-to-object] Turn on for mainnet

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_33.snap
Enables shared object deletion in testnet.
Existing tests + baking in devnet for the past couple months.
---
Shared object deletion is now enabled in testnet.
=> [shared object deletion] Enable in testnet

Cargo.lock, Cargo.toml, crates/mysten-service/Cargo.toml, crates/mysten-service/src/health.rs, crates/mysten-service/src/lib.rs, crates/mysten-service/src/service.rs, crates/mysten-service/tests/integration_test.rs
Doing some work to bring this to the sui repo – basic service utilities for new services.
Full list of items to eventually include in [this notion doc](https://www.notion.so/mystenlabs/code-bootstrapping-de278ec675c6473ba6004f22baf610eb?pvs=4)
cargo test
```
running 3 tests
test health::tests::health_response_new_works ... ok
test tests::package_name_works ... ok
test tests::package_version_works ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running tests/integration_test.rs (/Users/jkjensen/mysten/sui/target/debug/deps/integration_test-85ebcfb09adf53fc)
running 1 test
test test_add ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Doc-tests mysten-service
running 0 tests
test result: …
```
=> [mysten-service] 1/n initialize crate for service dependencies

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_33.snap
Enable effects v2.
Added more tests. Run node catchup with all debug asserts enabled. Baked in testnet for months.
---
- [x ] protocol change
- [x ] breaking change for FNs (FN binary must upgrade)
- [x ] breaking change for validators or node operators (must upgrade binaries)
- [x ] breaking change for on-chain data layout
This is a rework of the core effects data structure that make it simpler, more efficient and extensible.
More details in https://github.com/MystenLabs/sui/issues/12813
=> Enable effects v2 in mainnet

crates/sui-graphql-e2e-tests/tests/transactions/events.exp, crates/sui-graphql-e2e-tests/tests/transactions/events.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
StoredTransaction has a vector of serialized sui_types::Event. We can use this to resolve the events field on tx. StoredEvent and StoredTransaction share many data fields, and the remaining ones can be determined from the serialized sui_types::Event. Cursor framework handles pagination.
transactions/events.move
---
=> [gql] events (eventConnection) on tx

crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/graphiql_server.rs, crates/sui-json-rpc/src/lib.rs
Adding `/json-rpc` route to the `sui-indexer` service and `/graphql` route to the `sui-graphql` service. These mirror the behaviors of their respective `/` routes.
Test new routes:
```
curl -s -i http://localhost:8001/graphql | egrep '(200 OK|GraphiQL)'
HTTP/1.1 200 OK
React.createElement(GraphiQL, {
fetcher: GraphiQL.createFetcher({
```
```
curl -s -X POST -H "Content-Type: application/json" --data '{ "query": "query { chainIdentifier }", "variables": { "userId": "123" } }' http://localhost:8001/graphql | jq
{
"data": {
"chainIdentifier": "4c78adac"
}
}
```
```
% curl -w "%{http_code}" http://localhost:9000/json-rpc -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0", "method":"sui_getObject", "params":["0x2"], "id":1}'
{"jsonrpc":"2.0","result":{"data":{"objectId":"0x000000000000000 …
```
=> add graphql and json-rpc routes

crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, narwhal/primary/src/state_handler.rs
Without this fix, narwhal nodes will not be able to sign any headers containing randomness after they restart.
Also adds additional detail to some relevant log messages.
Fixes simtest failure in `test_upgrade_compatibility`.
=> random beacon: Write restored VSS public key to output after crash recovery

crates/sui-graphql-e2e-tests/tests/packages/types.exp, crates/sui-graphql-e2e-tests/tests/packages/types.move, crates/sui-package-resolver/src/lib.rs
Add tests that the limits implemented in the package resolver help to protect the GraphQL service against malicious type queries.
Note that tests were not added for the `max_type_nodes` and `max_type_argument_width` limits because the RPC limits are the same as the chain limits in these cases, so it's not possible to generate a type that could hit these limits in RPC, because they are already stopped by the chain's protocol config.  These limits have been separately tested in the package resolver crate.
```
-- types.move
```
- #15393 
- #15407 
- #15408
- #15409 
- #15410
- #15442 
- #15443 
- #15444 
- #15445 
- #15446 
- #15447
=> [GraphQL/Package Resolver] E2E tests for type resolution limits

Cargo.lock, crates/mysten-service/Cargo.toml, crates/mysten-service/src/lib.rs, crates/mysten-service/src/metrics.rs, crates/mysten-service/src/service.rs, crates/mysten-service/tests/integration_test.rs
Add metrics initialization
cargo test
```
running 3 tests
test health::tests::health_response_new_works ... ok
test tests::package_name_works ... ok
test tests::package_version_works ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running tests/integration_test.rs (/Users/jkjensen/mysten/sui/target/debug/deps/integration_test-5c35a104ffffed4f)
running 1 test
test test_mysten_service ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
Doc-tests mysten-service
running 1 test
test crates/mysten-service/src/metrics.rs - metrics::start_basic_prometheus_server (line 16) ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.68s
```
---
If your changes …
=> [mysten-service] 2/n add basic metrics functionality

crates/sui-graphql-e2e-tests/tests/limits/directives.exp, crates/sui-graphql-e2e-tests/tests/limits/directives.move, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
As discussed internally, we should allow the default/built-in directives.
e2e
---
=> [graphql/rpc] allow @skip and @include directives

Cargo.lock, crates/mysten-service/Cargo.toml, crates/mysten-service/src/lib.rs, crates/mysten-service/src/logging.rs, crates/mysten-service/src/service.rs, crates/mysten-service/tests/integration_test.rs
unify logging initialization to a utility fn
cargo test
```
running 3 tests
test health::tests::health_response_new_works ... ok
test tests::package_name_works ... ok
test tests::package_version_works ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running tests/integration_test.rs (/Users/jkjensen/mysten/sui/target/debug/deps/integration_test-2597f82918f87a66)
running 1 test
test test_mysten_service ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Doc-tests mysten-service
running 1 test
test crates/mysten-service/src/metrics.rs - metrics::start_basic_prometheus_server (line 19) ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.80s
```
--- …
=> [mysten-service] 3/n add logging utility

crates/sui-json-rpc/src/read_api.rs, crates/sui-storage/src/key_value_store.rs, crates/sui-storage/src/key_value_store_metrics.rs
Because the metrics have labels, switch to prometheus histogram.
Label the fetch latency metrics with the data fetched (tx vs checkpoint).
Add trace logs to `multi_get_transaction_blocks_internal()`.
CI
---
=> [kvstore] improve metrics

crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/packages/structs.exp, crates/sui-graphql-e2e-tests/tests/packages/types.exp, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs, crates/sui-graphql-rpc/src/types/move_type.rs, crates/sui-graphql-rpc/src/types/open_move_type.rs, crates/sui-graphql-rpc/tests/examples_validation_tests.rs
Make sure all fields are correctly serialized in camelcase.  This was not the case for `typeParameters` or for `queryPayload`.
E2E tests
```
```
Also, do an audit of all GraphQL responses in E2E tests to make sure they are appropriately formatted:
```
sui-graphql-e2e-tests/tests$ sed -n '/^Response: {$/,/^}$/p' **/*.exp \
| sed 's/Response: //'                                              \
| jq -r 'paths | map(tostring) | join(".")'                         \
| awk -F'.' '$NF ~ /[a-zA-Z]+_/ && $0 !~ /\.json\./ { print $NF }'
```
(all remaining names that include underscores come from field aliases).
=> [GraphQL][EASY] Ensure fields are generally output in camelCase

.changeset/smooth-carrots-jam.md, sdk/dapp-kit/src/components/WalletProvider.tsx, sdk/dapp-kit/src/constants/walletDefaults.ts, sdk/dapp-kit/src/utils/stateStorage.ts, sdk/docs/pages/dapp-kit/wallet-provider.mdx
dapp-kit breaks when used in a framework like Next since we default to using local storage for persisting connection data which doesn't exist in an SSR context. While we're working on better support for these frameworks, this PR fixes the immediate breakage issue by defaulting to memory storage when local storage isn't available. I also added the option to entirely disable data persistence by setting `storage: null` in the `WalletProvider`.
Most of this was copy-pasta'd from @Jordan-Mysten's Next PR, I did hoist the storage determination logic up to the `WalletProvider` since I think it might be more clear to consumers what storage ends up being used. I don't have a super strong opinion on where this lives (`WalletProvider.tsx` or `walletStore.ts`), so I'm glad to change this back if …
=> [dapp-kit] default storage to memory storage when local storage isn't available in an SSR context

crates/sui-bridge/src/types.rs
Remove source chain tx and event idx in encoding.
---
=> [bridge 19/n] fix sui to eth encoding and add a encoding regression test

Cargo.lock, consensus/core/Cargo.toml, consensus/core/src/block.rs, consensus/core/src/context.rs, consensus/core/src/lib.rs, consensus/core/src/metrics.rs, consensus/core/src/validator.rs
There are a number of values used by most components and they do not change within an epoch. Pull these values into an `Arc<Context>`, so initializations and task spawming are cleaner and easier.
CI
---
=> [Consensus] add `Context` for epoch configuration

external-crates/move/crates/move-compiler/src/hlir/translate.rs, external-crates/move/crates/move-compiler/tests/move_2024/hlir/tail_block_freeze.move
There was a small oversight in freezing bound expressions in tail positions introduced during the HLIR rewrite. The VM validator caught the issue, but but would be nice to allow this code since it should ostensibly work.
Added a new test file to cover the behavior.
---
=> [move] Add freezing for tail expressions

.github/workflows/split-cluster.yml, crates/sui-genesis-builder/src/lib.rs
Introduces a workflow to be run on new pull requests. Workflow calls into a script which spins up a local cluster of 4 nodes on the host, with 2 nodes running mainnet release branch and 2 nodes running a release candidate (in this case, the PR branch head). The new cluster is regenesis'ed and overridden to identify as mainnet, therefore it can provide merge-blocking for changes that could introduce backwards incompatibility or other issues.
If run on merges to main, will also bisect if this fails
https://github.com/MystenLabs/sui/actions/runs/7428260893
---
=> [CI] Run split cluster check on pull requests

docs/content/guides/operator/sui-full-node.mdx
Docs change:
- page: https://docs.sui.io/guides/operator/sui-full-node#set-up-from-source
- update incorrect/legacy SSFN's
- started syncing a fullnode using these peers
=> update testnet ssfn seed-peer config

crates/sui/src/client_commands.rs, crates/sui/src/keytool.rs, crates/sui/src/unit_tests/keytool_tests.rs, crates/sui/tests/cli_tests.rs
Add sort by alias in client addresses and keytool list
Existing tests
---
Added a `--sort-by-alias | -s` flag for the `sui client addresses` and `sui keytool list` to allow to sort by alias the list of addresses or keys. By default, the output is sorted by address.
=> [cli][alias][easy] Add sort by alias in client addresses and keytool list

crates/sui-graphql-e2e-tests/tests/call/owned_objects.exp, crates/sui-graphql-e2e-tests/tests/call/owned_objects.move, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/call/simple.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/epoch/specific_epoch.graphql, crates/sui-graphql-rpc/examples/object/object.graphql, crates/sui-graphql-rpc/examples/object_connection/filter_object_ids.graphql, crates/sui-graphql-rpc/examples/object_connection/filter_owner.graphql, crates/sui-graphql-rpc/examples/transaction_block_effects/transaction_block_effects.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Refactors ObjectOwner to be a union of four different owner types, as per our draft schema.
Running existing tests.
---
=> [graphql] Refactor ObjectOwner

Cargo.lock, Cargo.toml, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.exp, crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.move, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs, crates/sui-graphql-rpc/src/metrics.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs, crates/sui-graphql-rpc/tests/examples_validation_tests.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Implements output nodes estimation. A node adds a cost of 1, unless it is a connection field, where it would then have a cost of default_page_size, or min(first, last) if so provided. This is multiplicative - at the next child connection, that child's estimated output will be multiplied with its parent's to yield the cumulative result.
1. check that we get this back in the headers when showUsage is provided
4. output_node_estimation.move
---
=> [gql][2/n] output nodes estimation

crates/sui-core/src/authority.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/models_v2/transactions.rs, crates/sui-json-rpc-types/src/sui_event.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-types/src/event.rs, crates/sui-types/src/inner_temporary_store.rs, crates/sui-types/src/object.rs, crates/sui-types/src/type_resolver.rs, sui-execution/latest/sui-adapter/src/type_layout_resolver.rs, sui-execution/next-vm/sui-adapter/src/type_layout_resolver.rs, sui-execution/v0/sui-adapter/src/type_layout_resolver.rs, sui-execution/v1/sui-adapter/src/type_layout_resolver.rs
This PR mostly involves changing usages of module cache to layout resolver, so that deserialization of structs can be package upgrade aware in fullnode txn post processing.
Tested against @amnn's repro script.
---
=> make fullnode txn post processing and event handling upgrade aware

Cargo.lock, crates/sui-oracle/Cargo.toml, crates/sui-oracle/move/oracle/Move.toml, crates/sui-oracle/move/oracle/sources/data.move, crates/sui-oracle/move/oracle/sources/decimal_value.move, crates/sui-oracle/move/oracle/sources/meta_oracle.move, crates/sui-oracle/move/oracle/sources/simple_oracle.move, crates/sui-oracle/tests/data/Test/Move.toml, crates/sui-oracle/tests/data/Test/sources/test_module.move, crates/sui-oracle/tests/integration_tests.rs
Sui Oracle is a general purpose oracle that can be used to fetch data from external sources and feed it to the Sui Chain.
It is designed to be modular and extensible, so that it can be easily extended to support new data sources and new data types.
Move test + manual integration tests
We need to add more documentation to explain the design of this package and turn it into an example.
---
=> move sui-oracle move package to public repo

crates/sui-indexer/src/main.rs
to run reset DB command only without panic
local run 
```
cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --reset-db --use-v2
```
---
=> do not panic on DB reset cmd

crates/sui-indexer/src/main.rs
to run reset DB command only without panic
local run 
```
cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --reset-db --use-v2
```
---
---
=> do not panic on DB reset cmd (#15626)

narwhal/primary/src/consensus/bullshark.rs, narwhal/primary/src/consensus/mod.rs, narwhal/primary/src/consensus/tests/consensus_utils.rs, narwhal/primary/tests/nodes_bootstrapping_tests.rs, narwhal/primary/tests/randomized_tests.rs
Randomized tests are not currently running on the narwhal as part of the [narwhal-nightly](https://github.com/MystenLabs/sui/actions/workflows/nightly-narwhal.yml) since the consensus crate was moved. Also giving more slack on the commit threshold for the `test_loss_of_liveness_with_recovery`.
---
=> [narwhal ]re-enable randomized tests

crates/sui-graphql-e2e-tests/tests/event_connection/event_connection.exp, crates/sui-graphql-e2e-tests/tests/event_connection/event_connection.move, crates/sui-graphql-e2e-tests/tests/event_connection/nested_emit_event.exp, crates/sui-graphql-e2e-tests/tests/event_connection/nested_emit_event.move, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.exp, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/event_connection/event_connection.graphql, crates/sui-graphql-rpc/examples/event_connection/filter_by_emitting_package_module_and_event_type.graphql, crates/sui-graphql-rpc/examples/event_connection/filter_by_sender.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
As title, to keep event.sender aligned with transaction_block.sender
existing tests should pass after modifying senders -> sender
---
=> [gql][easy] change event.senders to single sender

crates/sui-framework/packages/bridge/sources/bridge.move, crates/sui-framework/packages/bridge/sources/committee.move, crates/sui-framework/packages/bridge/sources/message.move
add http_rest_url for committee and harden encoding logic
unit tests
---
add http_rest_url for committee and harden encoding logic
=> [Bridge/Move]  add http_rest_url for committee and harden encoding logic

crates/sui-framework/packages/bridge/sources/bridge.move, crates/sui-framework/packages/bridge/sources/committee.move, crates/sui-framework/packages/bridge/sources/message.move
This PR changes the a few things:
1. when message is already processed/claimed, return Ok instead of panic. This is to make bridge client's life easier such that whenever they see a successful execution status, they consider the action is done
2. emit events for approval/claiming
3. fix message::key function
---
=> More updates to bridge move code 

crates/sui-genesis-builder/src/lib.rs, crates/sui-types/src/digests.rs
As in title
Will check against CI test
---
=> Respect chain override in genesis system object generation

.changeset/twenty-squids-double.md, sdk/deepbook/src/client.ts, sdk/deepbook/test/e2e/client.test.ts
This PR modifies the getLevel2BookStatus method of deepbook sdk so that both ask and bid side can be retrieved in a single PTB.   
Added a test function.
=> [deepBookClient] GetLevel2BookStatus method returns both ask and bid, if side is left undefined

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/move_function.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/src/types/move_struct.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/object_change.rs, crates/sui-graphql-rpc/src/types/object_read.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs, crates/sui-graphql-rpc/src/types/validator.rs
Move Object and associated types to leverage new Type::query framework. This PR only touches the singleton gets. Remove its equivalent methods from db_data_provider as they are no longer used.
Existing tests should pass
---
=> [gql] refactor object and related types to leverage new Type::query framework

crates/sui/src/main.rs
Change log level to error for all the CLI commands to avoid the output like this
---
=> [cli][easy] Change log level to error for all commands

crates/sui-data-ingestion/src/executor.rs, crates/sui-data-ingestion/src/reader.rs, crates/sui-data-ingestion/src/worker_pool.rs
the PR prevents various deadlock issues related to mpsc channels in the data ingestion daemon by limiting the number of concurrent tasks on the reader side. This restriction ensures that actor channels won't get congested, as the number of tasks produced by the reader is now capped
=> [data ingestion] enforce limit on reader side

docs/content/guides/developer/sui-101/building-ptb.mdx
A piece of exposition was sandwiched between two code blocks.
:eyes:
=> [Docs] Fix text trapped in code block

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_35.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_35.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_35.snap, sui-execution/latest/sui-move-natives/src/crypto/poseidon.rs
Only enable Poseidon for devnet for now.
Unit tests
---
=> Only enable Poseidon for devnet

crates/sui-analytics-indexer/src/store/bq/schemas/transaction.sql
Fix clustering of transaction table as most of the queries don't query by epoch and checkpoint which leads to inefficient scans.
Changing clustering reduced bytes scanned and billing
=> Fix clustering of transaction table

crates/sui-tool/src/commands.rs, crates/sui-tool/src/lib.rs, docs/content/guides/operator/snapshots.mdx
~Removes `--skip-checkpoints`, `--formal`, `--verify`, and `--genesis`, from the `download-db-snapshot` command~
```
ToolCommand::DownloadDBSnapshot {
epoch,
path,
skip_indexes,
num_parallel_downloads,
network,
snapshot_bucket,
snapshot_bucket_type,
snapshot_path,
no_sign_request, # support TODO
verbose,
}
```
**Adds**: `download-formal-snapshot` as a future replacement for the `--formal` flag.
Tested with both formal snapshot and db snapshot changes via: https://github.com/MystenLabs/sui/pull/15509
---
Breaking change for the `sui-tool` command. This breaks the `sui-tool download-db-snapshot` into `sui-tool …
=> [snapshots] split db download and formal download snapshot commands

crates/sui-graphql-e2e-tests/tests/event_connection/event_connection.exp, crates/sui-graphql-e2e-tests/tests/event_connection/event_connection.move, crates/sui-graphql-e2e-tests/tests/event_connection/nested_emit_event.exp, crates/sui-graphql-e2e-tests/tests/event_connection/nested_emit_event.move, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.exp, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.move, crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.exp, crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.move, crates/sui-graphql-e2e-tests/tests/transactions/events.exp, crates/sui-graphql-e2e-tests/tests/transactions/events.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/event_connection/event_connection.graphql, crates/sui-graphql-rpc/examples/event_connection/filter_by_emitting_package_module_and_event_type.graphql, crates/sui-graphql-rpc/examples/event_connection/filter_by_sender.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/type_filter.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
This PR applies the various preceding abstractions (cursor and pagination frameworks) to `Query.eventConnection`, and renames it to `Query.events`.
Events also support more expressive filters than previous types that we applied these frameworks to, in particular, they support filtering by modules and types, so we introduce `TypeFilter` and `ModuleFilter` (string) scalars as a new abstraction responsible for:
- Parsing cascading filters of this kind.
- Applying them as filters onto existing queries.
The parsing implementation has also been made to uniformly rely on Move's parser for types and identifiers (previously it used Move's parser for types, but string manipulation for package and module based filters), which required exposing some more endpoints to Move's parser.
Existing E2E tests …
=> [GraphQL/Cursor] Refactor Events Pagination

crates/sui-graphql-e2e-tests/tests/call/dynamic_fields.move, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/call/simple.move, crates/sui-graphql-e2e-tests/tests/event_connection/event_connection.exp, crates/sui-graphql-e2e-tests/tests/event_connection/event_connection.move, crates/sui-graphql-e2e-tests/tests/event_connection/nested_emit_event.exp, crates/sui-graphql-e2e-tests/tests/event_connection/nested_emit_event.move, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.exp, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.move, crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.exp, crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.move, crates/sui-graphql-e2e-tests/tests/transactions/events.exp, crates/sui-graphql-e2e-tests/tests/transactions/events.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/event_connection/event_connection.graphql, crates/sui-graphql-rpc/examples/event_connection/filter_by_emitting_package_module_and_event_type.graphql, crates/sui-graphql-rpc/examples/event_connection/filter_by_sender.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/error.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/mod.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/type_filter.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Replace all remaining instances of GraphQL variable-based binding to interpolation-based binding (which is more general), so that we can clean-up the code in the E2E test runner that deals with GraphQL variable substitution and printing.
```
```
- #15467 
- #15470 
- #15471 
- #15472 
- #15473
- #15474 
- #15475 
- #15484 
- #15485
- #15519
- #15520
- #15521
- #15522
- #15523
- #15524
- #15525
- #15526
- #15527
- #15625 
- #15528
=> [GraphQL/E2E][EASY] Finish porting variables to interpolation

Cargo.lock, crates/sui-data-ingestion/Cargo.toml, crates/sui-data-ingestion/src/executor.rs, crates/sui-data-ingestion/src/main.rs, crates/sui-data-ingestion/src/reader.rs, crates/sui-data-ingestion/src/tests.rs
Adds the functionality of falling back to the remote store/bucket if data is not present in the local directory for the data ingestion daemon.
Example of a possible configuration:
```
path: checkpoints
remote_store_url: https://s3.us-west-2.amazonaws.com/mysten-mainnet-checkpoints
remote_store_options:
- ["aws_access_key_id", "..."]
- ["aws_secret_access_key", "..."]
....
```
=> [data ingestion] remote reader

.changeset/fresh-dots-swim.md, sdk/zksend/src/links.ts
=> [zksend] Add method for sending non-sui balances

crates/simulacrum/src/epoch_state.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-e2e-tests/tests/coin_deny_list_tests.rs, crates/sui-e2e-tests/tests/move_test_code/sources/regulated_coin.move, crates/sui-sdk/src/wallet_context.rs, crates/sui-transaction-checks/src/lib.rs, crates/sui-types/src/base_types.rs, crates/sui-types/src/deny_list.rs, crates/sui-types/src/dynamic_field.rs, crates/sui-types/src/error.rs, crates/sui-types/src/lib.rs, crates/sui-types/src/transaction.rs, crates/test-cluster/src/lib.rs
This PR checks the deny list during signing to see if the sender address is denied in any of the Coin<T> types of the input objects (including receiving objects).
1. Test that denylist works for transfer objects
2. Test that denylist works for receiving objects
3. Test that denylist works for Move call input objects
4. Test that undeny works
5. Test that one coin denied an address doesn't affect use of other coins
---
This PR introduces the ability to deny specific addresses for newly created regulated coins.
Coin issuer who owns the deny cap can send transactions to …
=> Use deny list during signing

crates/sui/src/keytool.rs
Update description of keytool update-alias to include allowing dot as a character
Just docs, no tests needed.
---
The `keytool update-alias` command's description was updated to match the latest changes that allow aliases to contain the dot character in their names.
=> [cli] Update description of keytool update-alias to include allowing dot as a character

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Follow up on PR #15569 to fix the wrong description on shared mutable objects - they can never become immutable (this can be done only when they're created).
---
=> [graphql] Add more context about a parent's object

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/open_move_type.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Try to add doc comments to most Enums to improve the docs for the reference page that will be autogenerated from the schema.
---
=> [graphql] Improve doc comments for references doc

crates/sui-graphql-rpc/src/data.rs, crates/sui-graphql-rpc/src/data/pg.rs, crates/sui-graphql-rpc/src/types/chain_identifier.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/type_filter.rs, crates/sui-indexer/src/indexer_reader.rs
Adapt the `QueryExecutor` interface, to allow multiple queries to be issued within one transaction that sees a consistent snapshot of the database.
The previous API required that a query executor offer a way to run a query that produced a single result, multiple results, and an optional result (and provided a helper that produced one result), asynchronously.
The new API splits this functionality into two parts:
- `QueryExecutor` which offers an asynchronous API for executing transactions.
- `DbConnection` which offers a way to run a query that produces one or more results.
When `QueryExecutor` executes a transaction, it passes it an instance of `DbConnection`, which can then be used to run queries.
This change also gets rid of the `optional` helper, because it's no longer required -- we …
=> [GraphQL/Data] Consistent Reads API

crates/sui-graphql-rpc/src/data.rs, crates/sui-graphql-rpc/src/data/pg.rs, crates/sui-graphql-rpc/src/types/chain_identifier.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs
Now the `DbConnection` (previously `QueryExecutor`) no longer needs to be given a boxed query.  This unblocks use of union queries, which we will likely need to support consistent object reads.
Behaviour preserving refactor, passing all unit and E2E tests:
```
```
- #15661 
- #15695
=> [GraphQL/Data] Loosen restriction on Boxed Queries

crates/sui-graphql-rpc/src/data.rs, crates/sui-graphql-rpc/src/data/pg.rs, crates/sui-graphql-rpc/src/types/chain_identifier.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs
Implement filtering transaction blocks above and below by checkpoints by first translating the checkpoint sequence number bound into a transaction sequence number bound.
This was an optimisation that existed prior to #15661, but was implemented by issuing three separate queries (three separate DB round-trips).  #15661, switched the query to a single DB round-trip, but experimentally, we found that querying for a max page size of transaction blocks was too slow -- and often it timed out at the DB.
This PR is hopefully the best of both worlds: One DB roundtrip and good use of indices.
Tried the following query (querying the first 50 transactions in the last full epoch stored in the data-set for the GraphQL beta), in SQL:
```sql
SELECT
*
FROM
transactions
WHERE
tx_sequence_number > (
-- Last …
```
=> [GraphQL/TransactionBlock] Checkpoint bound to Tx Seq Num bound

crates/sui-graphql-rpc/src/data.rs, crates/sui-graphql-rpc/src/data/pg.rs, crates/sui-graphql-rpc/src/types/chain_identifier.rs, crates/sui-graphql-rpc/src/types/protocol_config.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/type_filter.rs
Adds a way to intersect two module or fully-qualified name filters, to correct the behaviour of transaction block filtering (which previously implemented intersection of its function filter by simple equality test).
```
sui-graphql-rpc$ cargo nextest run -- type_filter
```
- #15661 
- #15695 
- #15698 
- #15699
=> [GraphQL/Type Filter] Intersection algorithm

crates/sui/src/main.rs
Part of adding sui to homebrew core. For the native install we run `cargo install --path crates/sui` on a tar'd release. The problem is that github's tar'd source bundles (ie. https://github.com/MystenLabs/sui/archive/refs/tags/mainnet-v1.15.1.tar.gz) don't have any git history:
```
Compiling sui v1.15.1 (/Users/johnmartin/Downloads/sui-mainnet-v1.15.1/crates/sui)
error[E0080]: evaluation of constant value failed
--> crates/sui/src/main.rs:20:13
|
20 |             panic!("unable to query git revision");
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'unable to query git revision', crates/sui/src/main.rs:20:13
```
```
$ rm -fr .git/
$ cargo install --path crates/sui  
$ target/release/sui -V …
```
=> [sui cli] remove panic when git revision cannot be found

crates/sui-framework-tests/src/unit_tests.rs, examples/move/transfer-to-object/README.md, examples/move/transfer-to-object/common/Move.toml, examples/move/transfer-to-object/common/sources/identified_payment.move, examples/move/transfer-to-object/owned-no-tto/Move.toml, examples/move/transfer-to-object/owned-no-tto/sources/cash_register.move, examples/move/transfer-to-object/shared-no-tto/Move.toml, examples/move/transfer-to-object/shared-no-tto/sources/shared_cash_register.move, examples/move/transfer-to-object/shared-with-tto/Move.toml, examples/move/transfer-to-object/shared-with-tto/sources/shared_cash_register.move
Adds a long-form example where transfer to object can be useful. It's a long running example on how to create a "cash register" on chain. It does this in a number of ways and compares them:
* Using an address and having all payments sent to that address;
* Using a shared object without transfer-to-object;
* Using a shared object along with transfer-to-object.
* Adds a bonus on how to use custom receiving rules to add tips.
=> [transfer-to-object] Transfer to object examples and long-form doc

crates/sui-core/src/authority.rs
A quick optimization before we implement something more complex.
The sui coin will never have deny list.
CI
---
=> Do not check deny list for sui coins

external-crates/move/crates/move-compiler/src/naming/ast.rs, external-crates/move/crates/move-compiler/src/naming/resolve_use_funs.rs, external-crates/move/crates/move-compiler/src/naming/translate.rs, external-crates/move/crates/move-compiler/src/typing/core.rs
- Refactor use fun scopes to reduce O(n) clones in favor of O(n) lookups
- non functional change, ran tests
---
=> [move] Refactor use fun scopes

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-storage/src/indexes.rs, crates/sui-tool/src/db_tool/index_search.rs, crates/sui-tool/src/db_tool/mod.rs, crates/typed-store/src/rocks/mod.rs, crates/typed-store/src/rocks/tests.rs, crates/typed-store/src/test_db.rs, crates/typed-store/src/traits.rs
Replacing iter_with_bounds with safe_iter_with_bounds. Appreciate if the reviewers can spot check each call site and see if returning error makes sense.
More test cases added in unit test.
---
=> Convert iter_with_bounds to safe_iter_with_bounds

crates/sui-core/src/authority.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/src/unit_tests/gas_tests.rs, crates/sui-e2e-tests/tests/protocol_version_tests.rs, crates/sui-indexer/src/apis/write_api.rs, crates/sui-indexer/src/apis/write_api_v2.rs, crates/sui-json-rpc-api/src/write.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-json-rpc/src/authority_state.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-open-rpc/src/examples.rs, crates/sui-rosetta/src/construction.rs, crates/sui-sdk/src/apis.rs, crates/sui-transaction-checks/src/lib.rs, crates/sui-transactional-test-runner/src/lib.rs, crates/sui-types/src/execution_mode.rs, sui-execution/src/executor.rs, sui-execution/src/latest.rs, sui-execution/src/next_vm.rs, sui-execution/src/v0.rs, sui-execution/src/v1.rs
For graphql we would like to combine dry run and dev inspect functionality, and any behavior difference between the two should be made toggleable via user provided options, which will look a lot like the newly added struct `DevInspectArgs` in this PR. This PR modifies the dev inspect code to make implementing new dev inspect easier. It also adds optional additional args to dev inspect APIs.
existing tests
---
Add optional additional parameters to `dev_inspect_transaction_block` including gas_budget, gas_objects, gas_sponsor and skip_checks.
=> add more optional args to dev inspect on fullnode

crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs
`Page<C>` was originally designed to work with `Cursor<C>`. This change allows it to be used with any type that implements `CursorType`.
The motivation for this is the upcoming port of `Object` to the cursor and pagination framework: We need to be able to use `Page` to paginate Objects, but the representation of an object cursor in this form is very large, because it converts the hex-encoded string into a JSON array of numbers (bytes), stringifies that and Base64 encodes the result.
By decoupling `Page` and `Cursor`, we can define a new Cursor type for Object cursors (which will BCS-encode the underlying type before Base64 encoding it) with a more compact representation, and still take advantage of the pagination framework.
Behaviour preserving refactor:
```
sui-graphql-rpc$ cargo nextest …
```
=> [GraphQL/Cursor] Generalise cursor type used by Page

crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Implement `GasInput.gasPayments` using the new `Object::paginate`. While here, also perform some clean-ups:
- Store the object *keys* instead of IDs for payment objects, so that we can see the version of the payment object that was input.
- Run the query using object keys, instead of object IDs, in preparation for object history support.
- Tweak the types used in the representation of gas types to favor the GraphQL equivalent types (e.g. `SuiAddress` instead of `ObjectID`).
- Remove an unused `From` impl that introduces a dependency on JSON-RPC.
```
```
Note that the `programmable.move` test shows the gas payment connection returning an empty result now -- this should be fixed once …
=> [GraphQL/Cursor] Object::paginate for gas_payment

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority_aggregator.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/test_authority_clients.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-json-rpc/src/authority_state.rs, crates/sui-node/src/lib.rs
Suffix it with unsafe to avoid accidental calls.
CI
---
=> Rename get_sui_system_state_object to make it less error prone

docker/grafana-local/dashboards/cluster-status-dashboard.json
Adding a dashboard for observing local cluster status and critical information.
This is currently only used by myself, but I find it very helpful to give an overview of the current system status.
Don't have a strong opinion if we have to merge it.
---
=> Add cluster status dashboard to local grafana

crates/sui-core/src/test_authority_clients.rs, crates/sui-core/src/unit_tests/authority_aggregator_tests.rs, crates/sui-core/src/unit_tests/transaction_tests.rs
This PR is for item 67/68 in the fixit doc. There are multiple protections in place for incorrect epoch across safe client, stake aggregator & signature verifier, added some tests to ensure they are not moved. Added some tests as well for bad user input into handle certificate. This is already tested for handle transaction.
=> Add tests for handle_certificate

.github/workflows/simulator-nightly.yml
to fix simtest-nightly workflow.
https://github.com/MystenLabs/sui/actions/runs/7560084330
---
=> Revert "build(deps): bump teleport-actions/auth from 1.1.2 to 2.0.0"

Cargo.lock
```
cargo deny check advisories
error[vulnerability]: Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)
┌─ /Users/luzhang/Workplaces/sui/Cargo.lock:415:1
│
415 │ h2 0.3.18 registry+https://github.com/rust-lang/crates.io-index
│ --------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2024-0003
= Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0003
= An attacker with an HTTP/2 connection to an affected endpoint can send a steady stream of invalid frames to force the
generation of reset frames on the victim endpoint.
By closing their recv window, the attacker could then force these resets to be queued in an unbounded fashion,
resulting in Out Of Memory (OOM) and high CPU usage.
This fix is corrected in …
```
=> update h2 to 0.3.24

crates/sui-indexer/src/models_v2/transactions.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/src/types.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-open-rpc/src/examples.rs, crates/sui-sdk/examples/read_api.rs, crates/sui/src/client_commands.rs
Add an option to return raw transaction effects via transaction execution api on fullnode so that graphql can use it. See discussion on the gql PR #15717.
Existing tests
---
Add an option to SuiTransactionBlockResponseOptions to return the raw transaction effects.
=> add option to return raw txn effects on fullnode

crates/sui-bridge/src/config.rs, crates/sui-bridge/src/error.rs, crates/sui-bridge/src/eth_client.rs, crates/sui-bridge/src/eth_syncer.rs, crates/sui-bridge/src/events.rs, crates/sui-bridge/src/server/handler.rs, crates/sui-bridge/src/sui_client.rs, crates/sui-bridge/src/sui_syncer.rs, crates/sui-bridge/src/sui_transaction_builder.rs
The meat of this PR is in `eth_client.rs` and `sui_client.rs`. Basically, they only care about events that are defined in corresponding packages/contracts. This is critical to make sure no other random events will be considered as legit bridge actions.
unit tests
---
=> [Bridge 24/n] only use events that are emitted/declared from specific contracts/packages

crates/sui-adapter-transactional-tests/tests/children/child_of_shared_object.exp, crates/sui-adapter-transactional-tests/tests/deny_list/coin_deny_and_undeny.exp, crates/sui-adapter-transactional-tests/tests/deny_list/coin_deny_and_undeny.move, crates/sui-adapter-transactional-tests/tests/deny_list/coin_deny_multiple_per_module.exp, crates/sui-adapter-transactional-tests/tests/deny_list/coin_deny_multiple_per_module.move, crates/sui-adapter-transactional-tests/tests/deny_list/coin_deny_tto.exp, crates/sui-adapter-transactional-tests/tests/deny_list/coin_deny_tto.move, crates/sui-adapter-transactional-tests/tests/entry_points/obj_vector.exp, crates/sui-adapter-transactional-tests/tests/entry_points/obj_vector_generic.exp, crates/sui-adapter-transactional-tests/tests/entry_points/obj_vector_generic_v20.exp, crates/sui-adapter-transactional-tests/tests/entry_points/obj_vector_v20.exp, crates/sui-adapter-transactional-tests/tests/receive_object/duplicate_receive_argument.exp, crates/sui-adapter-transactional-tests/tests/receive_object/receive_invalid_param_ty.exp, crates/sui-adapter-transactional-tests/tests/receive_object/receive_object_owner.exp, crates/sui-adapter-transactional-tests/tests/sui/coin_transfer.exp, crates/sui-adapter-transactional-tests/tests/transfer_object/package.exp, crates/sui-adapter-transactional-tests/tests/transfer_object/quasi_shared.exp, crates/sui-adapter-transactional-tests/tests/upgrade/upgrade_ratchet.exp, crates/sui-e2e-tests/tests/coin_deny_list_tests.rs, crates/sui-e2e-tests/tests/move_test_code/sources/regulated_coin.move, crates/sui-transactional-test-runner/src/test_adapter.rs, external-crates/move/crates/move-transactional-test-runner/src/framework.rs, external-crates/move/crates/move-transactional-test-runner/src/vm_test_harness.rs
This PR replaces the deny list simtest with transactional tests, which are much easier to inspect and validate.
To make errors easier to visualize and update, this PR also introduces a new function in the test adapter that can replace known addresses and IDs with names/fake ids in the error string.
CI
---
=> Add deny list transactional tests

consensus/core/src/block.rs, consensus/core/src/block_manager.rs, consensus/core/src/core.rs, consensus/core/src/core_thread.rs, consensus/core/src/lib.rs, consensus/core/src/metrics.rs, consensus/core/src/threshold_clock.rs, consensus/core/src/validator.rs
Adding part of the application logic for the block processing. More specifically:
* accept the blocks via the `block_manager` (mock is used for now for the `block_manager`)
* advance the `threshold_clock` for the processed (accepted) blocks
* pull transactions via the `TransactionsConsumer` and add them to local queue
* send signals for `new round` advancement and `new block proposal` 
* switched to using the `VerifiedBlock` and `SignedBlock` structs
Next steps:
CI
---
=> [consensus 2.0] adding application logic for block processing

apps/wallet/src/background/accounts/ImportedAccount.ts, apps/wallet/src/background/legacy-accounts/LegacyVault.ts, apps/wallet/src/shared/utils/from-exported-keypair.ts
* this allows supporting keys that are stored in base64 format already in the wallet storage
---
=> support base64 exported keypairs

docs/content/concepts/sui-move-concepts.mdx
This PR corrects a broken link in the sui-move-concepts.mdx file, resolving a 404 error. The issue was a typographical error in the file extension of the hyperlink to the "Key abilities" section in the Move language documentation. The corrected link now properly redirects to the intended destination on GitHub.
Verified the updated link manually in sui-move-concepts.mdx. The link now successfully accesses the "Key abilities" page, confirming the resolution of the 404 error.
---
N/A - Minor documentation fix with no significant impact on users, system components, or protocol.
=> Fix Broken Documentation Link in Sui Move Concepts

external-crates/move/crates/move-package/src/lock_file/schema.rs
Adds a helper we need to check Move.lock versions.
Context: https://github.com/MystenLabs/sui/pull/15731#discussion_r1456080903
Unused currently. When used will be part of tests.
---
=> move [EASY]: add function to read lock header with file handle

Cargo.lock, Cargo.toml, crates/mysten-service-boilerplate/Cargo-sui.toml, crates/suiop-cli/Cargo.toml, crates/suiop-cli/boilerplate, crates/suiop-cli/src/cli/mod.rs, crates/suiop-cli/src/cli/service/init.rs, crates/suiop-cli/src/cli/service/mod.rs, crates/suiop-cli/src/main.rs
Duplicate of the work originally in https://github.com/MystenLabs/sui-operations/pull/3072/files
```
» cargo r -- s i --path ../my-service
Finished dev [unoptimized + debuginfo] target(s) in 0.99s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop s i --path ../my-service`
```
```
» tree ../my-service 
../my-service
├── Cargo.toml
└── src
└── main.rs
```
Added to the main cargo.toml then
```
» cargo r 
Updating crates.io index
Compiling prometheus-closure-metric v0.1.0 (/Users/jkjensen/mysten/sui/crates/prometheus-closure-metric)
Compiling telemetry-subscribers v0.2.0 (/Users/jkjensen/mysten/sui/crates/telemetry-subscribers)
Compiling mysten-metrics v0.7.0 (/Users/jkjensen/mysten/sui/crates/mysten-metrics)
Compiling mysten-service v0.0.1 …
```
=> [mysten-service] 5/n add boilerplate instantiation from suiop

consensus/config/src/committee.rs, consensus/core/src/authority.rs, consensus/core/src/authority_node.rs, consensus/core/src/block.rs, consensus/core/src/lib.rs
Use `Authority` consistently across type names.
CI
---
=> [Consensus] rename Validator to AuthorityNode

crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/name_service/name_service.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/sui_address.rs, crates/sui-graphql-rpc/src/types/suins_registration.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Implement `Query.resolveSuinsAddress` using the new data framework, and add a downcast operation to `MoveObject` to convert an arbitrary object into a `SuinsRegistration`.
This comes associated with the following changes:
- Rename the query from `resolveNameServiceAddress` to `resolveSuinsAddress` as per feedback from the dogfooding session.
- Make `Domain` a string scalar type.
Manually tested with:
```
{
resolveSuinsAddress(domain: "example.sui") {
address
}
object(address: "0x55936857d1ca4d8a107b35e4d513bd0932da329389c976e8db6d52c58f16aefb") {
asMoveObject {
contents {
json
}
asSuinsRegistration {
domain
}
}
}
}
```
- #15749
=> [GraphQL/Data] Query.resolveSuinsAddress

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/suins_registration.rs, crates/sui-graphql-rpc/src/types/type_filter.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Port `IOwner.suinsRegistrations` to the new cursor and data framework and clarify some of the related doc comments.
Manually tested with:
```
{
address(address: "0x0b86be5d779fac217b41d484b8040ad5145dc9ba0cba099d083c6cbda50d983e") {
suinsRegistrations {
nodes {
domain
}
}
}
}
```
- #15749 
- #15760 
- #15761
=> [GraphQL/Cursor] SuinsRegistration pagination

crates/sui-graphql-e2e-tests/tests/objects/staked_sui.exp, crates/sui-graphql-e2e-tests/tests/objects/staked_sui.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/stake_connection/stake_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/src/types/suins_registration.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Port StakedSui to the cursor/data/pagination framework.
Also extracts the logic for paginating a sub-type of Object into a reusable helper function: `Object::paginate_subtype`.
New E2E test:
```
-- objects/staked_sui.move
```
- #15749 
- #15760 
- #15761 
- #15764
=> [GraphQL/Cursor] StakedSui pagination

crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/src/types/suins_registration.rs
While implementing pagination for dynamic fields, I realised it would be easier for it to implement its own query, rather than go through `Object::paginate` which means we no longer need to be aware of `OwnerType::Object` in the Object querying paths.
Behaviour preserving refactor -- run all tests:
```
```
- #15749 
- #15760 
- #15761 
- #15764
- #15777
- #15778
=> [GraphQL/Data] Specialise Object::paginate to OwnerType::Address

crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs
Ported to new data framework -- this introduces a slight behaviour change that a failure to parse a coin type in the data layer is now treated as an internal error, not a user error, because the user error is handled by `ExactTypeFilter`.
```
```
- #15749 
- #15760 
- #15761 
- #15764
- #15777
- #15778
- #15779
- #15780
=> [GraphQL/Data] Balance point query

crates/sui-graphql-e2e-tests/tests/objects/coin.exp, crates/sui-graphql-e2e-tests/tests/objects/coin.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/balance_connection/balance_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/functional_group.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/move_type.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Port paginated Balance queries to the new cursor/data/pagination framework. The earlier implementation asked whether it was even worth paginating balances, because we needed to compute all the balances up-front before we limit them. This is in fact not true, because we have an index on `coin_type`, so the database can avoid work by knowing that we only need to produce `N < COUNT(coin_type)` balances.
New E2E tests:
```
-- objects/coin.move
```
- #15749 
- #15760 
- #15761 
- #15764
- #15777
- #15778
- #15779
- #15780
- #15781
=> [GraphQL/Cursor] Balance pagination

crates/sui-storage/src/object_store/util.rs, crates/sui-tool/src/commands.rs, crates/sui-tool/src/lib.rs
Add support for permissionless downloads to download-db-snapshot
* clean up download-db-snapshot code path
* support ObjectStoreGetExt in download_db_snapshot codepath
* add utils for manifest file read/write
I'll follow this up with a PR to remove the deprecated `--formal` flag, after the next release. 
Tested on a mainnet fullnode
---
introduces support for permissionless downloads of legacy db snapshots: eg: `sui-tool download-db-snapshot --epoch 269 --network mainnet --no-sign-request`
=> [snapshot] download-db-snapshot support r2 permissionless downloads

crates/sui-core/src/authority.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-json-rpc/src/authority_state.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-open-rpc/src/examples.rs
This PR makes two changes:
- Added an option to dev inspect arguments to return the raw transaction data. This is needed to implement dry run from graphql side.
- In a previous PR #15679 , I started using the unused `epoch` parameter as transaction expiration epoch for dev inspect, which is apparently wrong. This `epoch` was supposed to be for running a txn in a previous epoch, which was never implemented. So this PR reverted that change and kept ignoring `epoch`.
---
Added an option to return raw transaction data for dev inspect.
=> change fullnode dev inspect interface to return raw txn data

docs/content/guides/operator/sui-full-node.mdx
Compiling sui-node requires `libpq-dev` installed.
N/A
=> Update sui-full-node.mdx to add libpq-dev

crates/simulacrum/src/lib.rs, crates/simulacrum/src/store/in_mem_store.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-core/src/authority/authority_store_types.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/epoch/committee_store.rs, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/handlers/tx_processor.rs, crates/sui-indexer/src/indexer_reader.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-json-rpc/src/coin_api.rs, crates/sui-replay/src/replay.rs, crates/sui-rest-api/src/node_state_getter.rs, crates/sui-single-node-benchmark/src/mock_storage.rs, crates/sui-storage/src/http_key_value_store.rs, crates/sui-storage/src/indexes.rs, crates/sui-transactional-test-runner/src/lib.rs, crates/sui-transactional-test-runner/src/simulator_persisted_store.rs, crates/sui-transactional-test-runner/src/test_adapter.rs, crates/sui-types/src/error.rs, crates/sui-types/src/in_memory_storage.rs, crates/sui-types/src/storage/error.rs, crates/sui-types/src/storage/mod.rs, crates/sui-types/src/storage/object_store_trait.rs
This PR does some work to create a general purpose storage error, and then converting ObjectStore to use it, in an effort to reduce the reliance on the SuiError type (which is sort of a kitchen sink of errors across our repo).
---
=> introduce a general purpose storage error and convert ObjectStore to use it

crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/up.sql, crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/indexer_v2.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/processors_v2/mod.rs, crates/sui-indexer/src/processors_v2/objects_snapshot_processor.rs, crates/sui-indexer/src/schema_v2.rs, crates/sui-indexer/src/store/indexer_store_v2.rs, crates/sui-indexer/src/store/pg_indexer_store_v2.rs
- separate objects snapshot from batch cp commit, b/c on some heavy checkpoints, one cp would take >30s, which slowed down other data ingestion a lot
```
Persisted snapshot for checkpoints from 7798404 to 7798405 elapsed=57.556287846000004
```
Also snapshot is meant to be behind, so no need to stay in sync either.
- also some logging misc.
local run to make sure that both ingestion and snapshot can proceed independently
---
=> indexer: separate objects snapshot processing

crates/sui-graphql-e2e-tests/tests/transaction_block_effects/events.exp, crates/sui-graphql-e2e-tests/tests/transaction_block_effects/events.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/schema/draft_target_schema.graphql, crates/sui-graphql-rpc/src/mutation.rs, crates/sui-graphql-rpc/src/types/balance_change.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/execution_result.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
This PR does a few things to implement transaction execution in graphql:
- Extend in a number of graphql places to take in either the stored or native version of some information, now that a transaction can be either indexed or just executed
- Actually finish implementing executeTransactionBlock
Existing tests
---
=> [graphql] implement executeTransactionBlock

crates/sui-storage/src/object_store/util.rs, crates/sui-tool/src/commands.rs, crates/sui-tool/src/lib.rs
This PR adds the support for user to pass in `--latest` while downloading snapshots. This is going to be super useful for first time users trying to run a testnet or mainnet sui fullnode locally (where they don't want to fist find out the latest epoch somehow first) and make running a fullnode for the first time a more convenient process
```
(base) sadhansood@Sadhans-Laptop sui % cargo run -p sui-tool download-db-snapshot --genesis ~/Downloads/genesis.blob --formal --network mainnet  --path /opt/sui/db/authorities_db --num-parallel-downloads 50 --no-sign-request --snapshot-bucket-type=s3 --verbose --latest
Finished dev [unoptimized + debuginfo] target(s) in 0.81s
Running `target/debug/sui-tool download-db-snapshot --genesis /Users/sadhansood/Downloads/genesis.blob --formal --network …
```
=> Add support for downloading latest epoch snapshot in sui-tool

crates/sui-core/src/authority.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-json-rpc/src/authority_state.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-open-rpc/src/examples.rs
Similar to #15790, raw txn effects is also needed to implement dry run for graphql.
existing tests.
---
=> return raw effects for dev inspect

crates/sui-graphql-e2e-tests/tests/objects/historical.exp, crates/sui-graphql-e2e-tests/tests/objects/historical.move, crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp, crates/sui-graphql-e2e-tests/tests/transactions/shared.exp, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/move_module.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/object_change.rs, crates/sui-graphql-rpc/src/types/object_read.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/suins_registration.rs, crates/sui-graphql-rpc/src/types/validator.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-indexer/src/types_v2.rs
Refactor Object’s internal representation to contain a status: ObjectKind enum with variants Live, Historical, NotIndexed, WrappedOrDeleted, and OutsideAvailableRange. This minimizes changes to the current Object schema on graphql, and allows users to look up graphql fields of wrapped objects even if the objects themselves cannot be accessed.
The PR also implements available-range-aware single-object lookups by constructing a union query on objects_snapshot and objects_history. We need to look up both tables when fetching an object at version. To illustrate, if an object was created or mutated at checkpoint 1, and the current available range is now 100-200, a query for the object at version 1 will not show up if we look strictly in the objects_history table, since it only tracks object …
=> [gql] get object at version

crates/sui-cluster-test/src/cluster.rs, crates/sui-graphql-e2e-tests/tests/objects/snapshot.exp, crates/sui-graphql-e2e-tests/tests/objects/snapshot.move, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/test_infra/cluster.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs, crates/sui-graphql-rpc/tests/examples_validation_tests.rs, crates/sui-indexer/src/indexer_v2.rs, crates/sui-indexer/src/processors_v2/objects_snapshot_processor.rs, crates/sui-indexer/src/test_utils.rs, crates/sui-indexer/tests/ingestion_tests.rs, crates/sui-transactional-test-runner/src/args.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Expose a way to provide config values to ObjectsSnapshotProcessor to enable e2e tests around objects_snapshot. 
1. Adds a SnapshotLagConfig to ObjectsSnapshotProcessor struct
2. ReaderWriterConfig for start_test_indexer_v2, reorganizes some logic on instantiating a reader or writer indexer_v2
3. RunGraphqlCommand now waits for objects_snapshot catch up in addition to the existing checkpoint catch up.
snapshot.move to test querying against objects_snapshot and objects_history tables
snapshot.move
---
=> [gql] objects_snapshot test for availableRange-aware object history lookup

crates/sui-graphql-e2e-tests/tests/objects/received.exp, crates/sui-graphql-e2e-tests/tests/objects/received.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
This function seems to have gone missing (it's in the draft schema, but doesn't show up in the current schema).  It is a specialisation of `Address.transactionBlocks` for `Object`s which can't send transactions, but can receive them.
New E2E tests:
```
-- objects/received.move
```
- #15804
=> [GraphQL/Objects] receivedTransactionBlocks

crates/sui-graphql-e2e-tests/tests/objects/received.exp, crates/sui-graphql-e2e-tests/tests/objects/received.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/tests/snapshot_tests.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Consolidates the locations where we build a schema in the codebase to one place (inside `ServerBuilder`) to fix a bug where querying the schema from the server would not reveal an interface while it shows up in our snapshot tests.
```
-- objects/received.move
```
- #15804 
- #15823
=> [GraphQL/Upcast] Consolidate schema building

Cargo.lock
https://rustsec.org/advisories/RUSTSEC-2024-0006
Update shlex to 1.3.0 in response to security advisory, using:
```
cargo update shlex
```
```
crago deny check advisories
```
=> [RUSTSEC-2024-0006] Update shlex

crates/sui-data-ingestion/src/executor.rs, crates/sui-data-ingestion/src/reader.rs, crates/sui-data-ingestion/src/worker_pool.rs, crates/sui-data-ingestion/src/workers/blob.rs
the PR includes the following changes:
* updated the task distribution method in the worker pool. Before, worker `i` used to process checkpoints with the `sequence number % number_of_workers = i`. We now track idle workers separately and assign new tasks to the first available one
* constructs the AWS ObjectStore with 0 retries (retries will be managed externally by the ingestion framework) and set an explicit timeout. The default timeout in the object store library is several minutes, and a single worker hanging during upload can sometimes paralyze overall progress
=> [data ingestion] perf tweaks

external-crates/move/crates/move-compiler/src/cfgir/locals/mod.rs, external-crates/move/crates/move-compiler/tests/move_check/liveness/vector_loop.exp, external-crates/move/crates/move-compiler/tests/move_check/liveness/vector_loop.move
This fixes a situation where locals analysis bails when it finds weird temp usages.
New test (thanks to @tedks)
---
=> [move-compiler] Report tmp lvalue errors in locals analysis

crates/sui-graphql-e2e-tests/tests/call/owned_objects.exp, crates/sui-graphql-e2e-tests/tests/call/owned_objects.move, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/call/simple.move, crates/sui-graphql-e2e-tests/tests/objects/display.exp, crates/sui-graphql-e2e-tests/tests/objects/display.move, crates/sui-graphql-e2e-tests/tests/objects/received.exp, crates/sui-graphql-e2e-tests/tests/objects/received.move, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/main.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/types/address.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/tests/snapshot_tests.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Part of the feedback to address from 1.5 -- return a `MoveObject` from te `objects` connection on owners, because it's impossible for an object that is owned by another object or an address to be a package.
At the moment, this makes certain queries more annoying (if you want to access fields on `Object` from this endpoint), but this inconvenience will disappear soon, when the explicit upcasts are replaced by interfaces (in a PR to come).
Existing E2E and unit tests:
```
-j 1 --features pg_integration
```
=> [GraphQL/Upcast] IOwner.objects returns MoveObjects

crates/sui-bridge/src/crypto.rs, crates/sui-bridge/src/types.rs, examples/move/bridge/sources/message.move
Change little endian to big endian, to make solidity easier. 
move changes are mirrored from https://github.com/MystenLabs/sui/pull/15722
unit tests
---
=> [bridge 27/n] use big endian

crates/sui-graphql-e2e-tests/tests/owner/downcasts.exp, crates/sui-graphql-e2e-tests/tests/owner/downcasts.move, crates/sui-graphql-rpc/src/types/owner.rs
Implemented by querying for the object with that address. Note that this needs to be revised once we have consistent reads, to read the latest object for the checkpoint that the owner was queried at.
New E2E test:
```
-- owner/downcasts.move
```
- #15804 
- #15823 
- #15824 
- #15825
=> [GraphQL/Owner] Implement asObject

crates/sui-graphql-e2e-tests/tests/owner/downcasts.exp, crates/sui-graphql-e2e-tests/tests/owner/downcasts.move, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/types/coin_metadata.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/query.rs
Use the new data framework to read singleton objects from the DB, and use it to implement fetching `CoinMetadata`.  The query only accepts a type and returns its `CoinMetadata`.  In the absence of cross-query consistency, I don't believe this needs to be made consistent.
Existing E2E tests
```
-- call/coin_metadata.move
```
- #15826
=> [GraphQL/Data] CoinMetadata

external-crates/move/crates/move-package/src/resolution/dependency_graph.rs
Moved `collect_overrides` functionality to a more natural place. This is used for resolve_version hook implementation later so that the manifest doesn't have to be parsed again.
This is part of the work to enable compiling against on-chain
dependencies https://github.com/MystenLabs/sui/pull/14178.
cc @rvantonder @amnn
It's a pure refactor. Ran unit tests.
---
=> move-package: collect overrides from collect_graphs (refactor)

crates/sui-graphql-rpc/src/context_data/db_backend.rs, crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/context_data/pg_backend.rs, crates/sui-graphql-rpc/src/types/coin_metadata.rs
Query for total supply via a `Coin`'s `TreasuryCap` to implement `CoinMetadat::supply`, using the new data framework.
Existing E2E tests:
```
sui-graphql-rpc$ cargo nextest run \
-j 1 --features pg_integration   \
-- call/coin_metadata.move
```
=> [GraphQL/Data] CoinMetadata::supply

apps/wallet/src/ui/app/pages/home/tokens/coin-balance/index.tsx
Fixes a bug were we were showing different amounts in USD for Sui
- Updates the recently-added hook `useTokenPrice` to use price info from CoinGecko for Sui, and updates the portfolio balance to use that hook
=> [wallet-ext] update Sui balance in coins list

.changeset/three-bats-warn.md, sdk/zksend/src/channel/events.ts, sdk/zksend/src/wallet.ts
It looks like the `build` before the window open causes the transaction to fail. Moving to use serialize instead.
---
=> [zksend] Use serialize instead of build in SDK

consensus/config/src/committee.rs, consensus/core/src/base_committer.rs, consensus/core/src/block.rs, consensus/core/src/core.rs, consensus/core/src/dag_state.rs, consensus/core/src/storage/mod.rs
Implement `DagState` methods used by commit rule.
There are some overlaps with #15806, but there shouldn't be a lot of conflicts hopefully.
Unit test.
---
=> [Consensus] implement `DagState` methods

.changeset/young-toys-relax.md, sdk/kiosk/src/client/kiosk-transaction.ts, sdk/kiosk/test/e2e/helper.ts
Fixes the `lock` function parameter to be `item` and its type to be `ObjectArgument`.
@hayes-mysten I kept the `itemId` for backwards compatibility, do you think I should make this a minor instead of a patch and break compatibility or keep it like this?
Updated the test & run the e2e tests.
---
=> [Kiosk SDK] Fixes lock function parameter type

crates/sui-framework/packages/bridge/sources/message.move
This is to make encoding easier (and cheaper) in solidity
---
=> [native bridge 3/n] - use big endian encoding in Sui

crates/test-cluster/src/lib.rs
This should fix the simtest failure in test_validator_resign_effects.
CI
---
=> Make test cluster wait for epoch more robust

crates/suiop-cli/src/cli/service/init.rs
The sui-services docker image exists to support non-node-operator services. Put new services generated in the sui repo into it to bundle them with other services.
```
» RUST_LOG=debug cargo r -- s i --path ../my-dumb-service
Blocking waiting for file lock on build directory
Compiling suiop-cli v0.1.5 (/Users/jkjensen/mysten/sui/crates/suiop-cli)
Finished dev [unoptimized + debuginfo] target(s) in 14.76s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop s i --path ../my-dumb-service`
2024-01-23T18:42:03.699278Z  INFO suioplib::cli::service::init: creating rust service in ../my-dumb-service
2024-01-23T18:42:03.699616Z DEBUG suioplib::cli::service::init: sui service: true
```
```
diff --git a/docker/sui-services/Dockerfile b/docker/sui-services/Dockerfile
index e7962453ac..ff0100e7a3 …
```
=> [mysten-service] 6/n update the sui-services dockerfile with new service

crates/sui-source-validation-service/src/lib.rs, crates/sui-source-validation-service/src/main.rs, crates/sui-source-validation-service/tests/tests.rs
Stacked on https://github.com/MystenLabs/sui/pull/14359
Implements `api/list` route that reports all verified sources served. This info is currently opaque (a client has to know or guess what's available based on the repos we index), but `api/list` exposes this info explicitly.
Currently we just report the filename path--in follow up I will update this to point to the original source URL (like `github.com/...`) but that requires a bit more lifting.
```json
{
"mainnet": {
"0000000000000000000000000000000000000000000000000000000000000001": {
"address": {
"path": "address.move"
},
"ascii": {
"path": "ascii.move"
},
"bcs": {
"path": "bcs.move"
},
...
```
added test
---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate …
=> move: source service lists verified sources

crates/sui-graphql-rpc/src/extensions/logger.rs, crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
Improves code readability for the query id and session id when passing them to trace macros. The `%` is used to call Display on a type in the trace macros.
---
=> [graphql] Improve code readability for the query id and session id with logging

crates/sui-core/src/authority/authority_store_pruner.rs
PR introduces state tracking for the last manually processed SST files in memory. This prevents the recurrence of situations where the same file is repeatedly selected for manual compaction because its initial compaction run was a noop
=> [pruner] keep state of last manually processed SST files

crates/sui-graphql-rpc/src/extensions/logger.rs, crates/sui-graphql-rpc/src/server/builder.rs
Due to the way things are set up, the health endpoint is filling up the logs, so we want to not log it. Unfortunately, all the `cost` logs will still push an `info` with 
`INFO sui_graphql_rpc::data::pg::query_cost: Estimated cost cost=0.54 max_db_query_cost=20000 exceeds=false`. Adding a Uuid to the log function in the `cost` module is not trivial. Need to assess if this is the right way.
Should be merged after #15871
---
=> [graphql] Exclude health endpoint from logging

crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/suins_registration.rs
Based on feedback from Manos that it is confusing to have the resolution functions hanging off `SuinsRegistration`.
This slightly goes against an earlier recommendation I made to not introduce functions on types that don't need `self` unless they are constructors of some kind, but it is done to match the pattern we have for queries.
```
```
=> [GraphQL/SuiNS] Introduce NameService

crates/sui-graphql-rpc-client/src/simple_client.rs, crates/sui-graphql-rpc/src/test_infra/cluster.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Add a step to the E2E set-up to poll for a response from the GraphQL server before proceeding with the test to prevent it from failing due to the server not coming up fast enough.
```
sui-graphlql-rpc$ cargo nextest run \
-j 1 --features pg_integration    \
--test e2e_tests
```
=> [GraphQL] Fix flaky E2E test

crates/sui-graphql-e2e-tests/tests/call/checkpoint_connection_pagination.exp, crates/sui-graphql-e2e-tests/tests/call/checkpoint_connection_pagination.move, crates/sui-graphql-rpc/src/types/cursor.rs
Fix handling the case where we are drawing from one side of the page (e.g. the front), without a cursor on that side but with a cursor on the other side which ends up included in the fetched results.
In this case, we should be trimming the cursor on the off-side and indicating that there is a further page in that direction, but instead we include it in the results and assume that because we couldn't satisfy the limit requested, there are no further results.
This PR generalises the special case that was introduced for the situation where both the before and after cursors were supplied and both were found in the results, regardless of the limit -- now we correctly detect a trailing `before` cursor when drawing from the front and a leading `after` cursor when drawing from the back and strip …
=> [Pick #15894][GraphQL/Cursor][BUGFIX] Pagination Edge Case

consensus/core/src/authority_node.rs, consensus/core/src/block.rs, consensus/core/src/block_manager.rs, consensus/core/src/core.rs, consensus/core/src/core_thread.rs, consensus/core/src/dag_state.rs
Adding the block propose logic in Core. The implementation is not finished as there are things missing (ex using the DagState to query for blocks, write state, recover state, signing blocks etc) but it should still capture the core logic. 
More tests will be added on follow up PR.
CI
---
=> [consensus 2.0] adding propose logic in Core

docs/content/guides/developer/sui-101/shared-owned.mdx
Changes "reads and written" to "reads and writes" + rephrases run-on sentence
=> Fix typo in shared-owned.mdx and rewrite for clarity

crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs, crates/sui-graphql-rpc/src/metrics.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
Switched back to prometheus metrics as it is easier to work with the percentiles in Grafana due to prometheus not establishing exact percentiles like the mysten metrics, where the histogram is set to 50, 90, 99 percentiles.
It also adds back the previous test on query complexity.
---
=> [graphql] Switch to prometheus metrics

Cargo.lock, consensus/config/src/committee.rs, consensus/core/Cargo.toml, consensus/core/src/base_committer.rs, consensus/core/src/block.rs, consensus/core/src/context.rs, consensus/core/src/core.rs, consensus/core/src/core_thread.rs, consensus/core/src/dag_state.rs, consensus/core/src/lib.rs, consensus/core/src/storage/mod.rs, consensus/core/src/test_dag.rs, consensus/core/src/test_utils.rs, consensus/core/src/tests/base_committer_tests.rs, consensus/core/src/threshold_clock.rs, consensus/core/src/transactions_client.rs
Additionally added prevention for writing multiple blocks per slot to own index in dag state. We should also consider preventing adding multiple blocks to slot from ancestor if received from the same index as the ancestor.
=> [consensus] Add base committer tests

crates/sui-core/src/metrics.rs
Only adding the struct in this PR. It will be used to track transaction ready rate and execution driver execution rate.
I didn't find any existing rust library to do this so I just created one.
Usage (to track 10 seconds rollowing window event rate):
```
let mut tracker = RateTracker::new(Duration::from_secs(10));
...
tracker.record();
...
tracker.record();
...
tracker.rate() //returns the event rate.
```
Unit tests.
---
=> Create rate tracker that can track event rate for a rolling window

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs, crates/sui-core/src/checkpoints/mod.rs
In case we, for whatever reason, do not receive a notification about newly synced checkpoints after some amount of time, this change will cause us to exit the `tokio::select!` statement and re-loop, which will in turn re-invoke `schedule_synced_checkpoints`. Note that `schedule_synced_checkpoints` always checks the db directly and attempts to schedule everything it can, so this is a failsafe. 
Existing simtests
---
=> [CheckpointExecutor] Make scheduling more robust

crates/sui/src/client_commands.rs
Added a new command `sui client faucet` to make it easier to get gas from `devnet`, `testnet`, or `local` network. If a different network than the usual ones (`fullnode.network.sui.io`) is used, it will complain and ask to pass the url to its faucet. 
There are two options for the command:
`--url`, which is the URL to the gas faucet server
`--address`, which can be either an address or the alias name corresponding to an address in the wallet.
```
sui client faucet => will use the active network and active address
sui client faucet --address alias_name => will use the address corresponding to this alias, and the active network
sui client faucet --url => will use the active address and the faucet server at that endpoint
sui client faucet --address alias_name --url …
```
=> [cli] Add client faucet command to get gas

crates/sui-core/src/authority.rs, crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/execution_driver.rs, crates/sui-core/src/metrics.rs
Trying to reuse the existing `LatencyObserver` to track the queueing delay. It computes the average queueing latency of the last 64 samples. To not add too much overhead (since the observer also takes a lock when updating the metrics), I added sampling to track queueing delay (currently set to 5%, which means 1 sample per 2 second if we have 10 qps, or 250 samples per second if we have 5000 qps).
Also added metrics for exposing the queueing delay.
Cluster testing to test metrics reporting correct value.
---
=> Tracking transaction queueing latency after becoming ready for execution

crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-e2e-tests/tests/call/simple.move, crates/sui-graphql-e2e-tests/tests/epoch/epoch.exp, crates/sui-graphql-e2e-tests/tests/epoch/epoch.move, crates/sui-graphql-e2e-tests/tests/validator/validator.exp, crates/sui-graphql-e2e-tests/tests/validator/validator.move, crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/epoch/specific_epoch.graphql, crates/sui-graphql-rpc/examples/stake_connection/stake_connection.graphql, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/validator.rs, crates/sui-graphql-rpc/src/types/validator_set.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
`activeValidators` and `reportRecords` may result in long arrays of results so we need to paginate them.
Added to existing tests.
---
=> [GraphQL] paginate activeValidators and reportRecords

docs/content/concepts/sui-move-concepts/conventions.mdx, docs/content/sidebars/concepts.js
We added conventions for Sui Move 2024 to the documentations.
---
=> docs: add sui move 2024 conventions

.github/workflows/rust.yml, crates/sui-graphql-e2e-tests/README.md, crates/sui-graphql-rpc/src/config.rs, crates/sui-graphql-rpc/src/test_infra/cluster.rs, crates/sui-indexer/src/test_utils.rs, crates/sui-transactional-test-runner/src/test_adapter.rs, external-crates/move/crates/move-transactional-test-runner/src/framework.rs, external-crates/move/crates/move-transactional-test-runner/src/vm_test_harness.rs
Reworks tests and DB logic so e2e tests can run in parallel, hence reducing test time from 21 mins to 13 mins. It shouldn't increase much in future.
* Graphql tests were the slowest of all CI tests @ 21 mins.
* The time to beat was the second slowest test test-extra (ubuntu-ghcloud) test which takes ~15mins
* With new changes, we’re down to 13 mins now and should stay roughly constant regardless of new e2e tests.
* Actual test time is now down from 9 mins to 1.5 mins.
* Most of the remaining total test time is building and installing containers
**How to use it:**
* When running the sui-graphql-e2e-tests , you no longer need to force serialization of e2e test using --test-threads 1 or -j 1 
* Note: this is only for the tests in sui/crates/sui-graphql-e2e-tests
* I have not applied this …
=> [graphq/rpc] e2e tests run in parallel

.github/workflows/release.yml
> Wondering if there is a quick win here (and will tag 
@Ştefan also) should we make homebrew build from the devnet or testnet branch by default? The average dev getting started via the brew install route is almost certainly going to be hitting devnet or testnet first, so the onboarding flow in the docs will always work
> My 2c would be testnet as a good balance between being leading edge and being stable.
@ebmifa I see there's already a `testnet` release for 1.17 - can we re-run this workflow for 1.17 or should I just manually update the homebrew tap for 1.17?
---
=> push homebrew updates on testnet releases

Cargo.toml, crates/sui-data-ingestion/src/reader.rs
add support for http based remote reader. 
Workload can be enabled by just specifying following setting in config:
```remote_store_url: https://checkpoints.testnet.sui.io```
=> [data ingestion] http based remote reader

.changeset/angry-rocks-brush.md, apps/wallet/src/background/accounts/Account.ts, apps/wallet/src/background/accounts/ImportedAccount.ts, apps/wallet/src/background/accounts/MnemonicAccount.ts, apps/wallet/src/background/accounts/zklogin/ZkLoginAccount.ts, apps/wallet/src/background/legacy-accounts/LegacyVault.ts, apps/wallet/src/background/legacy-accounts/storage-migration.ts, apps/wallet/src/shared/messaging/messages/payloads/MethodPayload.ts, apps/wallet/src/shared/utils/from-exported-keypair.ts, apps/wallet/src/ui/app/components/accounts/AccountsFormContext.tsx, apps/wallet/src/ui/app/components/accounts/ImportPrivateKeyForm.tsx, apps/wallet/src/ui/app/helpers/validation/privateKeyValidation.ts, apps/wallet/src/ui/app/pages/accounts/ExportAccountPage.tsx, apps/wallet/src/ui/app/pages/accounts/ImportPrivateKeyPage.tsx, sdk/typescript/src/cryptography/keypair.ts
* deprecate `ExportedKeyPair` and `Keypair.export`
* stop using `ExportedKeyPair` in wallet
* support importing hex private keys
---
=> deprecate ExportedKeyPair and Keypair.export

crates/sui-json-rpc-types/src/displays/mod.rs, crates/sui-json-rpc-types/src/displays/transaction_displays.rs, crates/sui-json-rpc-types/src/lib.rs, crates/sui-json-rpc-types/src/sui_transaction.rs, crates/sui-types/src/transaction.rs
Improves the way we display PTB info in table output. Previously, the inputs would output all the data in a long String, which breaks the table.
*Before*
*After*
Visual inspection.
---
Improved the way a transaction kind of type programmable is shown in the CLI's output.
=> [cli] Improve the way we display PTB info in table output

Cargo.lock, Cargo.toml, crates/sui/Cargo.toml, crates/sui/src/ptb/ptb.rs, crates/sui/src/ptb/ptb_parser/argument.rs, crates/sui/src/ptb/ptb_parser/build_ptb.rs, crates/sui/src/ptb/ptb_parser/command_token.rs, crates/sui/src/ptb/ptb_parser/context.rs, crates/sui/src/ptb/ptb_parser/errors.rs, crates/sui/src/ptb/ptb_parser/mod.rs, crates/sui/src/ptb/ptb_parser/parser.rs, crates/sui/src/ptb/ptb_parser/utils.rs
Updates parsing and building of the PTB so that we can generate nice errors.
This adds:
* A way for us to track source locations during parsing. This information is then used for error reporting throughout both parsing and PTB building.
* Updated errors so that we can generate accurate error reports. 
Ran a bunch of commands locally and verified they worked/errors appeared as expected.
---
=> [CLI] Better error messages and source tracking for commands

crates/sui/src/client_commands.rs
This missing clap annotation leads to a panic if there is no subcommand requested, e.g., when `sui client` is called.
```
thread 'main' panicked at /Users/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.1/src/builder/debug_asserts.rs:747:9:
Argument 'serialize_unsigned_transaction` is positional, it must take a value
```
---
=> [cli] fix missing clap macro which breaks the cli

crates/sui/src/client_commands.rs, external-crates/move/Cargo.lock, external-crates/move/crates/move-cli/src/sandbox/commands/run.rs, external-crates/move/crates/move-unit-test/src/test_runner.rs, external-crates/move/crates/move-vm-integration-tests/src/tests/instantiation_tests.rs, external-crates/move/crates/move-vm-profiler/src/lib.rs, external-crates/move/crates/move-vm-runtime/src/interpreter.rs, external-crates/move/crates/move-vm-runtime/src/runtime.rs, external-crates/move/crates/move-vm-runtime/src/session.rs, external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/interpreter.rs, external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/runtime.rs, external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/session.rs, external-crates/move/move-execution/v0/move-vm/runtime/src/interpreter.rs, external-crates/move/move-execution/v1/crates/move-vm-runtime/src/interpreter.rs, external-crates/move/move-execution/v1/crates/move-vm-runtime/src/runtime.rs, external-crates/move/move-execution/v1/crates/move-vm-runtime/src/session.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/next-vm/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs
- Don't `clone` the function in the interpreter.
- Use the `enable` and `disable` macros consistently, rather than `#[cfg(feature = "gas-profiler")]`.
- Added a guard around the body of these macros so that the compiler wouldn't complain about unreachable statements following an invocation of this macro.
- Use `OsStr` and `OsString` to avoid throwing away reasonable paths that don't convert through strings.
```
external-crates/move$ cargo nextest run --features gas-profiler
external-crates/move$ cargo nextest run
sui$ cargo nextest run --features gas-profiler
sui$ cargo nextest run
```
Try a replay with the feature enabled (should succeed):
```
sui$ cargo run --bin sui --features gas-profiler \
-- client profile-transaction                  \
-t …
```
=> [Move] Clean-ups spotted from #14592

crates/sui/src/client_commands.rs
I was overzealous about removing an import (not sure why local builds did not catch this!).
```
sui$ cargo build --bin sui
```
=> [CLI] Fix main

docs/content/guides/developer/getting-started/graphql-rpc.mdx
Noticed some small things that I thought would be helpful to change while preparing the docs for cursors and pagination:
- Name the "Getting Started" guide as "Querying Sui GraphQL RPC" instead of just "Sui GraphQL RPC" so that its name includes a verb, to match other guides.
- Remove the reference to Github's GraphQL docs here, because that is already present in the conceptual docs (which we link to from here).
- Flatten out the "Examples" section, as that is mostly what this page is about.
- Standardise how we present variables across examples.
- Standardise indent level in examples (2 spaces).
- Use the present participle (progressive tense) for all the example titles ("Finding" vs "Find"). We were using both tenses before -- I don't feel strongly about one or the other but it's good …
=> [GraphQL/Docs] Tweaking "Getting Started"

consensus/core/src/lib.rs, consensus/core/src/network/mod.rs
Add the minimum network traits. In the beginning, implementations of the traits will just wrap anemo unicast RPCs. Later, streaming and connection management logic can be added inside `NetworkClient` and `NetworkServer` implementations.
n/a
---
=> [Consensus] add network interface

crates/sui-graphql-e2e-tests/tests/consistency/balances.exp, crates/sui-graphql-e2e-tests/tests/consistency/balances.move, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/raw_query.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs
Implements consistent reads for the Balance type.
1. RawQuery struct builds a BoxedSqlQuery to support consistent reads. The query demands more than what diesel's dsl can provide today, so unfortunately we will have it in raw sql for the time being. 
2. Split the pagination methods of the Target trait into a separate, Paginated trait. Implement target to build a cursor for a database entity.
3. Break the validation step out from paginate_query, so that the new paginate_raw_query method, which accepts a thunk that builds a RawQuery, can also have its results validated.
consistency/balances.move
---
=> [gql][consistent-reads][2/n] Implement consistent reads for Balance

crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination.exp, crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination.move, crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination_single.exp, crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination_single.move, crates/sui-graphql-e2e-tests/tests/consistency/tx_address_objects.exp, crates/sui-graphql-e2e-tests/tests/consistency/tx_address_objects.move, crates/sui-graphql-e2e-tests/tests/objects/coin.exp, crates/sui-graphql-e2e-tests/tests/objects/pagination.exp, crates/sui-graphql-e2e-tests/tests/objects/pagination.move, crates/sui-graphql-e2e-tests/tests/objects/staked_sui.exp, crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/type_filter.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
1.  Implement raw-query version of the existing TypeFilter and ObjectFilter logic
2. Note that when object_keys - object_id and object_version - are provided, the WHERE condition gets dropped. This is so that we can actually return data like the gas payment of a transaction. In other words, return the historical rather than the consistent view.
3. Extend `test_adapter` to handle complex `Object` cursors.
4. extend paginate_raw_query again to accept a cursor_fn that transforms each element's cursor. This is predominantly for Object, as the checkpoint_sequence_number to be set on an object as context should come from the method parameters, not the object itself.
tx_address_objects.move
objects_pagination.move
---
If your changes are not user-facing and do not break anything, you can skip …
=> [gql][consistent-reads][3/n] Implement consistent reads for Object and MoveObject

crates/sui-graphql-e2e-tests/tests/consistency/staked_sui.exp, crates/sui-graphql-e2e-tests/tests/consistency/staked_sui.move, crates/sui-graphql-e2e-tests/tests/objects/staked_sui.exp, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/object.rs
Add consistent read support for Object subtypes, which end up being just suinsRegistration and stakedSui.
staked_sui.move
---
=> [gql][consistent-reads][4/n] Implement consistent reads for suinsRegistration and stakedSui

crates/sui-move/src/build.rs, crates/sui-source-validation/src/lib.rs
Tidying up some lock file logic and spotted this
Covered by existing tests
---
=> move: use source package layout to resolve Move.lock path

crates/sui-graphql-rpc/src/extensions/logger.rs, crates/sui-graphql-rpc/src/server/builder.rs
Improve the health check by removing the query to the DB and replacing it with a status code 200 if all is OK, or 500 on error. It also cleans up the previous health check checks in the logging logic.
It also moves metrics and connection under a `AppState` struct as `axum` does not allow states with different types on the router, so we need to bundle them under one state and then have `FromRef` implementations for the substates.
Existing tests, manually analyzing the logs.
---
=> [graphql] Improve the health check

crates/sui-graphql-rpc/src/consistency.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/raw_query.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/object.rs
Moves the various historical object queries into the `consistency` module to reduce copypasta. Unfortunately does not play well with Balance's query, since it has different select conditions. It is possible to rely on `build_objects_query` to construct the historical query, and then compose a new query starting from the customized select, but any pagination will throw the bindings order off.
Also centralizes the valid consistent range check into a top-level `consistent_range` function in the module. While it would be nice to return `Result<(u64, u64), Error>` here, because it is intended to be used in an `execute_repeatable`, the custom error gets converted into an `IndexerError`, and then into `sui-graphql-rpc::Error` - the many error conversions back and forth are not worth it.
Refactor …
=> [gql][consistent-reads][8/n] Consolidate queries that require historical object state into one module.

crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/deleted_df.exp, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/deleted_df.move, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/deleted_dof.exp, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/deleted_dof.move, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.exp, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.move, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/mutated_df.exp, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/mutated_df.move, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/mutated_dof.exp, crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/mutated_dof.move, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/coin_metadata.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/move_object.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/owner.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/src/types/suins_registration.rs
Implement a historical read query for `DynamicField`'s `query` and `paginate` against the `objects_snapshot` and `objects_history` tables, and bound this historical read by a `checkpoint_viewed_at` for consistency. 
Substitute `DynamicField`'s internal representation with the `MoveObject` graphql type instead of the `Object` type.
This led to an observation where `MoveObject::query` returns an error on encountering a `WrappedOrDeleted` object. The underlying conversion has been modified to return `MoveObjectDowncastError::WrappedOrDeleted`, which `MoveObject::query` will convert into an `Ok(None)`.
Additionally, in order to look up the correct dynamic object fields for a parent object, we need to bound them by its parent's version. The entrypoints to fetch a dynamic object and dynamic …
=> [gql][consistent-reads][6/n] Implement consistent reads for dynamic fields

crates/sui-graphql-e2e-tests/tests/consistency/balances.exp, crates/sui-graphql-e2e-tests/tests/consistency/staked_sui.exp, crates/sui-graphql-e2e-tests/tests/objects/coin.exp, crates/sui-graphql-rpc/src/consistency.rs, crates/sui-graphql-rpc/src/lib.rs, crates/sui-graphql-rpc/src/raw_query.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/object.rs
Even though `Balance` does not resolve to other non-Scalar nodes, because there is a `Balance` connection, we will still need to track `checkpoint_viewed_at`. This is so that the caller stays on the same checkpoint while paginating through a balance connection.
---
=> [gql][consistent-reads][7/n] Extend Balance cursor to include checkpoint_viewed_at

crates/sui-graphql-e2e-tests/tests/consistency/tx_address_objects.exp, crates/sui-graphql-e2e-tests/tests/event_connection/event_connection.exp, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.exp, crates/sui-graphql-e2e-tests/tests/event_connection/pagination.move, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
Add `checkpoint_viewed_at` to internal representation for `Event` and `Event`'s cursor to support consistent queries through pagination and nested fields. `Event.paginate` is updated to be bound by `checkpoint_viewed_at`. 
---
=> [gql][consistent-reads][10/n] Add context to Events for consistent reads

crates/sui-graphql-e2e-tests/tests/call/checkpoint_connection_pagination.exp, crates/sui-graphql-e2e-tests/tests/call/checkpoint_connection_pagination.move, crates/sui-graphql-e2e-tests/tests/consistency/coins.exp, crates/sui-graphql-e2e-tests/tests/consistency/tx_address_objects.exp, crates/sui-graphql-rpc/src/types/available_range.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
Add `checkpoint_viewed_at` to `Checkpoint` and its cursor for consistent pagination and querying. This is needed because `Checkpoint` has a resolve field for `TransactionBlock`s, which further resolve out to fields like `Address` which would need checkpoint sequence number context for consistency.
---
=> [gql][consistent-reads][11/n] Set consistent context for checkpoints

crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/query.rs, crates/sui-graphql-rpc/src/types/stake.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/consensus_commit_prologue.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/randomness_state_update.rs
Add context to `Epoch`. Note that some `TransactionBlockKind`s do resolve `Epoch`, so that will be coming in a follow-up.
There's a lot of duplicate `validate_cursor_consistency` functions - introduce new `Checkpointed` trait for retrieving `checkpoint_viewed_at`, and add an implementation on `Page` to do this check instead of in each type module.
---
=> [gql][consistent-reads][12/n] Consistent reads for epochs

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_36.snap
Turn on shared object deletion in mainnet. This is a flag-only PR (+ updates) that adds a new protocol version (version 36).
Existing tests + has been running in devnet/testnet for the past couple months.
---
Enable shared object deletion in mainnet.
=> [shared-object-deletion] Turn on shared object deletion in mainnet

crates/sui-graphql-rpc/docs/examples.md, crates/sui-graphql-rpc/examples/checkpoint_connection/first_ten_after_checkpoint.graphql, crates/sui-graphql-rpc/examples/checkpoint_connection/last_ten_after_checkpoint.graphql, crates/sui-graphql-rpc/examples/epoch/with_tx_block_connection.graphql, crates/sui-graphql-rpc/examples/epoch/with_tx_block_connection_latest_epoch.graphql, crates/sui-graphql-rpc/examples/event_connection/filter_by_emitting_package_module_and_event_type.graphql, crates/sui-graphql-rpc/src/consistency.rs, crates/sui-graphql-rpc/src/mutation.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/balance_change.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/dry_run_result.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/event.rs, crates/sui-graphql-rpc/src/types/gas.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/object_change.rs, crates/sui-graphql-rpc/src/types/object_read.rs, crates/sui-graphql-rpc/src/types/transaction_block.rs, crates/sui-graphql-rpc/src/types/transaction_block_effects.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/consensus_commit_prologue.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/mod.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs, crates/sui-graphql-rpc/src/types/transaction_block_kind/randomness_state_update.rs, crates/sui-graphql-rpc/src/types/unchanged_shared_object.rs
Adds a `ConsistentIndexCursor` to the `consistency` module - we have a good number of cursors that are just indices into a type's `Vec` field, so this is a quick way to handle consistency for all of them in one go.
Sets `checkpoint_viewed_at` field on cursors to non-null. `DryRun` and `Mutation` results now fetch the latest checkpoint sequence number so that we can set `TransactionBlock` and `TransactionBlockEffects` to a checkpoint value. This is so that pagination fields on types that do not make a db roundtrip will have the correct checkpoint context on hand already - thus we can set `checkpoint_viewed_at: u64` on fields like the transaction calls of a `PTB`. Actually, it's likely the case that all graphql types can have a non-null `checkpoint_viewed_at`, but this can be revisited …
=> [gql][consistent-reads][x/n] Make cursor's checkpoint non-null, add context from the input and transaction connections down to ObjectRead.

.changeset/metal-dryers-clean.md, sdk/typescript/src/cryptography/index.ts, sdk/typescript/src/cryptography/keypair.ts
I noticed that new keypair functions were not being exported, and that the wallet was actually getting them through path aliasing into the source directory.
---
=> [ts-sdk] Export all keypair helpers

external-crates/move/crates/move-package/tests/test_sources/nested_deps_git_local/Move.locked, external-crates/move/crates/move-package/tests/test_sources/nested_deps_git_local/Move.resolved, external-crates/move/crates/move-package/tests/test_sources/nested_deps_git_local/Move.toml
Forgot this yesterday with the nits. It's related to this https://github.com/MystenLabs/sui/pull/15867/files/3ee2e7f1df0cfea267a0b25896b46a5d6c61629b#r1466324788
@rvantonder @amnn 
---
=> move-package: make `nested_deps_git_local` use sui repo for dep

external-crates/move/crates/move-package/src/lock_file/schema.rs, external-crates/move/crates/move-package/src/resolution/dependency_graph.rs
Just a cleanup of how we do lock file header reads. See separate commits for a breakdown of the change, and inline comments for more.
Follow up of https://github.com/MystenLabs/sui/pull/15751#pullrequestreview-1829957061. 
Should not be changing anything functionally, covered by existing tests.
---
=> move: tidy lock file header read interface

consensus/core/src/base_committer.rs, consensus/core/src/block.rs, consensus/core/src/commit.rs, consensus/core/src/context.rs, consensus/core/src/dag_state.rs, consensus/core/src/lib.rs, consensus/core/src/metrics.rs, consensus/core/src/tests/base_committer_tests.rs, consensus/core/src/tests/universal_committer_tests.rs, consensus/core/src/universal_committer.rs
The `UniversalCommitter` uses a collection of `BaseCommitter`'s to commit a sequence of leaders. It will be configured to enable multi-leader & pipelining in Mysticeti.
Note: Feel free to ignore test util changes as most of that will be reviewed and checked in with [PR#15806](https://github.com/MystenLabs/sui/pull/15806)
Added a few basic tests to ensure things are working, but will add more tests in a follow up PR so this PR can remain small.
=> [consensus] Add universal committer

crates/sui-source-validation-service/config.toml
The source for this package is moving on the `master` branch https://github.com/kunalabs-io/sui-smart-contracts/commit/e6fcbd69ed330de2824abb45c876f4b360923de2 which shouldn't happen when we're tracking it for bytecode verification. When it moves, but the published address stays the same, the bytecode no longer matches upstream and the service pauses.
I'll get in touch with package maintainers to figure out how we can pin the source to a branch that doesn't move or is being actively developed against, and will then re-enable. 
N/A, maintaining source service.
---
=> move: pause tracking a package in config.toml

consensus/core/src/authority_node.rs, consensus/core/src/context.rs, consensus/core/src/core.rs, consensus/core/src/core_thread.rs, consensus/core/src/network/mod.rs, consensus/core/src/transactions_client.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_36.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_36.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_36.snap
This PR is:
* Moving the block transactions size checks to the TransactionsConsumer/Client.
* Introducing the `consensus_max_transaction_size_bytes` and `consensus_max_block_transactions_size_bytes` properties to the ProtocolConfig.
* Bumping the protocol config version to 36.
CI
---
=> [Consensus 2.0] move transactions size check to consumer/client

consensus/core/src/authority_node.rs, consensus/core/src/core.rs, consensus/core/src/core_thread.rs, consensus/core/src/leader_timeout.rs, consensus/core/src/lib.rs
Introduces a dedicated component to timeout the leader based on the new produced round signal from Core. An interface has been added for the core thread dispatcher so we can more easily unit test the component without having to spin up the actual core - we can do this separately as an integration test.
CI
---
=> [Consensus 2.0] introduce the leader timeout task component

docs/content/concepts/graphql-rpc.mdx, docs/content/concepts/graphql-rpc/fragments.mdx, docs/content/concepts/graphql-rpc/headers.mdx, docs/content/concepts/graphql-rpc/limits.mdx, docs/content/concepts/graphql-rpc/pagination.mdx, docs/content/concepts/graphql-rpc/variables.mdx, docs/content/guides/developer/advanced/graphql-migration.mdx, docs/content/guides/developer/getting-started/graphql-rpc.mdx, docs/content/snippets/info-graphql-release.mdx
Removes the top info banner explaining that the launch is near.
---
=> [docs] Remove the graphql MVP launch date info

crates/sui-config/src/node.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/consensus_throughput_calculator.rs, crates/sui-core/src/execution_driver.rs, crates/sui-core/src/lib.rs, crates/sui-core/src/overload_monitor.rs, crates/sui-core/src/scoring_decision.rs, crates/sui-core/src/transaction_manager.rs, crates/sui-core/src/unit_tests/execution_driver_tests.rs, crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
This PR implements overload monitor in AuthorityState.
Overload monitor periodically monitors 3 signals:
- the execution queueing latency
- txn enqueue rate
- txn execution rate
to make a decision whether it should enter load shedding mode, and what percentage of traffic to shed.
Currently, we store the load shedding information in AuthorityState::overload_info struct, and expose it using
metrics. This PR doesn't implement any actions when an authority is in load shedding mode.
1. Added unit tests to test overload_monitor module
2. Single node benchmark `cargo run --release --bin sui-single-node-benchmark -- --component with-tx-manager no-move`
with this PR: `Execution finished in 24.127s, TPS=20723.670576532517`
before this PR: `Execution finished in 24.007s, TPS=20827.258716207773`
3. …
=> Authority overload monitor

external-crates/move/crates/move-compiler/src/sui_mode/typing.rs, external-crates/move/crates/move-compiler/tests/sui_mode/private_generics/no_public_transfer.exp
Allows calling this function in the compiler.
Ran existing tests + ran on local network.
=> [move-compiler] Add receiving_object_id function to compiler

.github/workflows/simulator-nightly.yml, Cargo.lock, Cargo.toml, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-e2e-tests/tests/reconfiguration_tests.rs, crates/workspace-hack/Cargo.toml, scripts/simtest/simtest-run.sh
This should get us back to a world where we can copy/paste the `MSIM_TEST_SEED=xxx` out of nightly failures and get a repro.
Commit summary:
- Remove static HashSet (breaks simtest determinism)
- Upgrade anemo
- Expand determinism testing to reconfig
- Test determinism in nightly run
=> Fix sources of non-determinism / non-repeatability and add better test coverage

crates/sui/src/client_commands.rs
This cleans up commands that have no output to use the NoOutput type. In particular, the replay commands' output is shown through trace info, and thus no output is passed here and thus we don't need to have their own special command result types. 
Existing tests
---
=> [cli][easy] Replace Replay related command result type with NoOutput type

crates/sui-bridge/src/action_executor.rs, crates/sui-bridge/src/lib.rs, crates/sui-bridge/src/main.rs, crates/sui-bridge/src/sui_client.rs, crates/sui-bridge/src/sui_mock_client.rs, crates/sui-bridge/src/types.rs
=> [bridge 30/n] skip action if it's already processed on chain

crates/sui-analytics-indexer/src/handlers/package_handler.rs, crates/sui-analytics-indexer/src/tables.rs
This PR starts tracking the root package id for every package and records it under a newly added column called "root_package_id" in the package table. In future, once we have canonical package names, we could use other methods to track and record package lineage under the same column
Running locally and verifying
=> Start tracking package lineage in analytics pipelines

Cargo.lock, crates/sui-analytics-indexer/Cargo.toml, crates/sui-analytics-indexer/src/handlers/df_handler.rs, crates/sui-analytics-indexer/src/handlers/mod.rs, crates/sui-analytics-indexer/src/lib.rs, crates/sui-analytics-indexer/src/tables.rs
This PR adds a new indexing pipeline for indexing dynamic fields. The primary clustering is to be done by `parent_id` to lookup dynamic fields and objects
Running locally and verifying
=> Start indexing dynamic fields in analytics

external-crates/move/crates/move-compiler-transactional-tests/tests/control_flow/named_block_nesting.exp, external-crates/move/crates/move-compiler-transactional-tests/tests/control_flow/named_block_nesting.move, external-crates/move/crates/move-compiler/src/cfgir/translate.rs, external-crates/move/crates/move-compiler/src/hlir/translate.rs
Due to a wildcard match, recompuing `loop` breaks did not proceed under them in HLIR lowering. This fixes that and revises HLIR lowering to always exhaustively match the forms when looking for breaks.
Also, the testing found cases where we had `annot((x: _|_): T)`, causing freeze operations to fail. This modified freeze checking to pass when we find `x: _|_` because that expression is unreachable and will be removed, plus typing was fine with it.
A very long test for all these forms.
---
=> [move-2024] Correctly recompute breaks under named blocks

Cargo.lock, crates/sui-bridge/Cargo.toml, crates/sui-bridge/src/crypto.rs, crates/sui-bridge/src/error.rs, crates/sui-bridge/src/server/handler.rs, crates/sui-bridge/src/sui_mock_client.rs
This PR hardens the bridge authority signing server:
1. introduce `ActionVerifier` trait to verify if an action is legit. Two impls are `SuiActionVerifier` that checks sui initialized transfers, and `EthActionVerifier` that checks eth initialized transfer. We will soon have a governance verifier.
2. add a LRU cache in signing server such that duplicated requests will not lead to wasted work. Non-transient errors will be cached too.
unit tests
---
=> [bridge 31/n] harden bridge authority signing server

crates/sui/src/ptb/mod.rs, crates/sui/src/ptb/ptb.rs
Fixes the `preview` and `warn-shadows` being shown in the preview command -- only when they're passed they will appear. 
---
=> [cli] cli ptb fix warn shadows preview preview

dapps/multisig-toolkit/package.json, dapps/multisig-toolkit/src/components/preview-effects/EffectsPreview.tsx, dapps/multisig-toolkit/src/components/preview-effects/ObjectLink.tsx, dapps/multisig-toolkit/src/components/preview-effects/PreviewCard.tsx, dapps/multisig-toolkit/src/components/preview-effects/context.ts, dapps/multisig-toolkit/src/components/preview-effects/partials/BalanceChanges.tsx, dapps/multisig-toolkit/src/components/preview-effects/partials/Events.tsx, dapps/multisig-toolkit/src/components/preview-effects/partials/ObjectChanges.tsx, dapps/multisig-toolkit/src/components/preview-effects/partials/Overview.tsx, dapps/multisig-toolkit/src/components/preview-effects/partials/Transactions.tsx, dapps/multisig-toolkit/src/components/preview-effects/utils.ts, dapps/multisig-toolkit/src/routes/offline-signer.tsx, dapps/multisig-toolkit/src/routes/root.tsx, pnpm-lock.yaml
Introduces effects preview in an easy to read way in the offline signer.
Before:
After:
---
=> [Multi-sig Toolkit] Introduce user-friendly effects preview

Cargo.lock, crates/sui/Cargo.toml, crates/sui/src/ptb/ptb_parser/argument.rs, crates/sui/src/ptb/ptb_parser/build_ptb.rs, crates/sui/src/ptb/ptb_parser/context.rs, crates/sui/src/ptb/ptb_parser/errors.rs, crates/sui/src/ptb/ptb_parser/parser.rs
Also fixes an issue in error reporting and spans due to the delayed resolution of arguments.
=> Update to allow address aliases that use `.`s in them

crates/sui-bridge/src/client/bridge_client.rs, crates/sui-bridge/src/server/mod.rs, crates/sui-bridge/src/sui_transaction_builder.rs, crates/sui-bridge/src/types.rs
=> [Bridge 33/n] add emergency action and encoding

external-crates/move/crates/move-compiler/src/cfgir/translate.rs, external-crates/move/crates/move-compiler/src/expansion/ast.rs, external-crates/move/crates/move-compiler/src/expansion/translate.rs, external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs, external-crates/move/crates/move-compiler/src/naming/ast.rs, external-crates/move/crates/move-compiler/src/naming/translate.rs, external-crates/move/crates/move-compiler/src/parser/ast.rs, external-crates/move/crates/move-compiler/src/parser/syntax.rs, external-crates/move/crates/move-compiler/tests/move_2024/expansion/pattern_ellipsis.move, external-crates/move/crates/move-compiler/tests/move_2024/expansion/pattern_ellipsis_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/expansion/pattern_ellipsis_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/naming/pattern_ellipsis.move, external-crates/move/crates/move-compiler/tests/move_2024/naming/pattern_ellipsis_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/naming/pattern_ellipsis_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/naming/struct_ellipsis.move, external-crates/move/crates/move-compiler/tests/move_2024/naming/struct_ellipsis_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/naming/struct_ellipsis_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/parser/enum_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/parser/pattern_ellipsis.move, external-crates/move/crates/move-compiler/tests/move_2024/parser/pattern_ellipsis_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/parser/pattern_ellipsis_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/parser/struct_ellipsis.move, external-crates/move/crates/move-compiler/tests/move_2024/parser/struct_ellipsis_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/parser/struct_ellipsis_invalid.move
Add support for ellipsis patterns in both enum and struct patterns. 
Ellipsis patterns are supported in both named and positional patterns.
1. Only one ellipsis pattern may be present (both in positional and named patterns).
2. An ellipsis pattern corresponds to zero or more arguments.
3. Ellipsis patterns are only valid as field patterns, and cannot occur as a top-level pattern.
Some examples of valid patterns (for both struct and enum variant patterns): 
```
C(..)
C(x, ..)
C(x, .., y)
C(.., x)
N { x, .. }
N { x, y, .. }
N { .., x }
N { .. }
```
Some invalid patterns:
```
C(.., ..)
C(x, .., y, ..)
C(..) // if C is a named variant or does not have any parameters
N { .., .. }
N { .. } // If N is a positional/empty variant
```
Added additional positive and negative tests.
---
If your …
=> [move-enums] Ellipsis patterns

external-crates/move/crates/move-cli/src/base/test.rs, external-crates/move/crates/move-compiler/src/unit_test/mod.rs, external-crates/move/crates/move-unit-test/src/lib.rs
When I was digging around in `TestPlan` code I noticed `TestPlan::new` takes `AnnotatedCompiledUnit` when it only needs a subvalue `NamedCompiledModule`. So I'm making the interface change that simplifies this (Y/n)?
Just a refactor.
---
=> move: simplify TestPlan::new interface (refactor)

docs/content/guides/developer/getting-started/sui-install.mdx
sui is available as a homebrew-core library now: https://github.com/Homebrew/homebrew-core/pull/161424
I have another PR to mark the older mysten-tap sui formula as deprecated to encourage people to migrate to the core library
---
=> update homebrew sui install

crates/sui-config/src/node.rs, crates/sui-core/src/overload_monitor.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Create a simulation test to test overload monitor. Particularly, it tests 5 scenarios
- No overload
- Slightly overload
- Heavy overload
- Single spike
- Consistent spikes
The tests use a simple load generator and executor. Both use a AuthorityState.overload_info to keep track of requests. The overload monitor inside the same AuthorityState can be used as an overload monitor for the load generator.
This test discovered several improvements from the previous load generator. Some notable ones are:
- When we are already in shedding mode, say 50%, and decide to shed 10%, previously the new shedding percentage will be 10% but it really should be 50% + 50% * 10% = 55%.
- When txn ready rate < execution rate, it doesn't mean that the overload is over. We need to protect against future spikes by …
=> Overload monitor simulation tests

crates/sui-bridge/Cargo.toml, crates/sui-bridge/src/tools/validator_cli.rs
usage:
```
./sui-bridge-validator-cli create-bridge-validator-key {file path}
```
tested locally
---
=> generate and write bridge authority key to a file

crates/sui-graphql-rpc/src/error.rs, crates/sui-indexer/src/apis/indexer_api_v2.rs, crates/sui-indexer/src/errors.rs, crates/sui-json-rpc-tests/tests/name_service_tests.rs, crates/sui-json-rpc/src/error.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-json-rpc/src/name_service.rs
IndexerV2 & GraphQL logic will be carried over on the next PRs.
- Adds checks for expiration on SLD names
- Adds subdomain lookup & expiration checks (for both node/leaf subdomains)
- Changes error structure for easier support between the 3 crates that use it
Added some unit tests and did some localnet testing for the resolution aspect. 
---
=> [NameService] Subdomain support

crates/sui-bridge/src/action_executor.rs, crates/sui-bridge/src/error.rs, crates/sui-bridge/src/sui_client.rs, crates/sui-bridge/src/sui_mock_client.rs, crates/sui-bridge/src/types.rs
`source_chain_id` is a bit confusing concept. This PR de-ambiguates it and updates some functions to only handle token bridge actions.
CI
---
=> [bridge 35/n] update function family get_action_onchain_status

external-crates/move/crates/move-compiler/src/diagnostics/mod.rs, external-crates/move/crates/move-compiler/src/expansion/translate.rs, external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs, external-crates/move/crates/move-compiler/src/hlir/translate.rs, external-crates/move/crates/move-compiler/src/naming/resolve_use_funs.rs, external-crates/move/crates/move-compiler/src/naming/translate.rs, external-crates/move/crates/move-compiler/src/typing/ast.rs, external-crates/move/crates/move-compiler/src/typing/core.rs, external-crates/move/crates/move-compiler/src/typing/expand.rs, external-crates/move/crates/move-compiler/src/typing/translate.rs
The compiler has a number of panics when things have gone wrong. This tries to remediate a large number of them to return some sort of error to allow compilation to continue, plus report it as a bug.
It's unclear if this will make development easier, but I think it is overall a situation we should move toward to helps when users stumble into these. If there are any specific panics we'd like to reinstate, please call them out.
The test suite behavior should not change. 
---
=> [move] Make most ICEs diagnostics

crates/sui/src/ptb/ptb.rs
Adds support for quoted values in PTB values. Note that non-quoted values are also still supported.
Manually tested, but will add tests once we have the testing framework :) 
---
=> Add support for quoted values in ptb files

external-crates/move/crates/move-analyzer/src/bin/move-analyzer.rs, external-crates/move/crates/move-analyzer/src/diagnostics.rs, external-crates/move/crates/move-analyzer/src/symbols.rs
This is mainly a refactoring with a small change to how constants are displayed (to include their defining module).
The refactoring started while attempting to implement a new feature but it was deemed a better idea to create a separate PR for it. In addition to enabling a new feature, it also reduces memory consumption by storing additional information for definitions on the side instead of inlining them in the `UseDef` structure - we moved `IdentOnHover` (now called `DefInfo` as it will be used for other things as well) to a separate map.
All existing tests (after new constant display adjustment) pass.
=> [move-ide] Refactoring to reduce memory footprint and prepare for new features

crates/sui-graphql-rpc/src/types/balance.rs
Filtering on owner_id is only efficient if we specify the `owner_type`. Balances consist of coin objects, which will be owned by an `AddressOwner`.
Existing tests
---
=> [gql] add owner_type to balance query

.changeset/young-mayflies-sit.md, sdk/typescript/src/client/http-transport.ts
Reason: 
When using WebSocket in the browser, the value in option is still used by default.
This will result in an error: 
```
Uncaught Error: Missing WebSocket constructor
```
But in the documentation, it is not mentioned that the constructor needs to be set to window.WebSocket
So this should be fixed
=> [TS SDK] Fix  WebSocket constructor miss in Browser

consensus/core/src/tests/universal_committer_tests.rs
Most test scenarios are identical to the test in base_committer_tests.rs but just going through the `UniversalCommitter` logic to handle checking between direct & indirect rules. Feel free to review all tests but the new tests that were not relevant in base_committer_tests.rs are
- `direct_commit_late_call`
- `no_genesis_commit`
- `no_leader`
Will follow up in another PR with the tests for multi leader and pipelining.
=> [consensus] Add universal committer tests

external-crates/move/crates/move-compiler/src/cfgir/optimize/forwarding_jumps.rs, external-crates/move/crates/move-compiler/src/cfgir/optimize/mod.rs, external-crates/move/crates/move-compiler/src/cfgir/translate.rs, external-crates/move/crates/move-compiler/src/editions/mod.rs, external-crates/move/crates/move-compiler/tests/move_2024/borrows/freeze_combo.move, external-crates/move/crates/move-compiler/tests/move_2024/borrows/freeze_combo_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/borrows/freeze_combo_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/borrows/freeze_field.move, external-crates/move/crates/move-compiler/tests/move_2024/borrows/freeze_field_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/borrows/freeze_field_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/borrows/freeze_full.move, external-crates/move/crates/move-compiler/tests/move_2024/borrows/freeze_full_invalid.move
The Move 2024 optimizations got disabled from alpha at some point. This re-enables them.
The test suite still works, plus more tests to ensure the new freeze mechanisms work.
---
=> [move-2024] Enable Move 2024 optimizations

Cargo.lock, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/test_infra/cluster.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs, crates/sui-indexer/Cargo.toml, crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs, crates/sui-indexer/src/handlers/tx_processor.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/store/indexer_store_v2.rs, crates/sui-indexer/src/store/module_resolver_v2.rs, crates/sui-indexer/src/store/pg_indexer_store_v2.rs
make indexer package upgrading aware 
via repro script and make sure that before the change, DF indexing will error but no longer the case after.
- on one terminal
```
sui_release genesis -f && sui_release start
```
- on second terminal
```
SUI=/Users/gegao/Documents/sui/target/release/sui ./repro.sh --object
SUI=/Users/gegao/Documents/sui/target/release/sui ./repro.sh --event
SUI=/Users/gegao/Documents/sui/target/release/sui ./repro.sh --dynamic-field
```
- on 3rd terminal
```
RUST_LOG=error DB_POOL_SIZE=10 cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --rpc-client-url http://0.0.0.0:9000 --fullnode-sync-worker --use-v2 --reset-db
```
before the change on main
```
2024-01-23T17:50:41.829029Z ERROR sui_indexer::handlers::checkpoint_handler_v2: …
```
=> indexer: package upgrade awareness

crates/sui-framework/packages/sui-framework/tests/test_scenario_tests.move, sui-execution/latest/sui-move-natives/src/test_scenario.rs
Adds support for shared object deletion in the test scenario -- mainly making sure that we don't raise an error if a shared object was deleted, whereas before it would complain.
This change was previously landed into https://github.com/MystenLabs/sui/pull/14598 but there's a desire/need for this in main sooner so putting this change up separately. 
This adds a test case to make sure the test scenario handles shared object deletion properly.
---
Add support for shared object deletion in test scenario.
=> Support shared object deletion in test scenario

Cargo.lock, crates/mysten-network/Cargo.toml, crates/mysten-network/src/callback/future.rs, crates/mysten-network/src/callback/layer.rs, crates/mysten-network/src/callback/mod.rs, crates/mysten-network/src/callback/service.rs, crates/mysten-network/src/lib.rs, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/metrics.rs, crates/sui-graphql-rpc/src/server/builder.rs
Implement a Callback tower layer, which is then used in the Graphql Axum server to be able to properly handle metrics. This way we are properly tracking in-flight requests, since we're using an RAII guard which will decrement when dropped.
---
=> graphql: utilize a tower layer for more accurate tracking of graphql metrics

.github/workflows/release.yml
changes commit message to remove the testnet-v prefix (https://github.com/Homebrew/homebrew-core/pull/161984#issuecomment-1934857715)
```
$ echo "refs/tags/testnet-v1.18.0" | sed s/'refs\/tags\/'// | sed s/'testnet\-v'//                               
1.18.0
```
---
=> fixup commit message

crates/sui/src/ptb/display/gas_cost_summary.rs, crates/sui/src/ptb/display/mod.rs, crates/sui/src/ptb/display/status.rs, crates/sui/src/ptb/display/summary.rs, crates/sui/src/ptb/mod.rs, crates/sui/src/ptb/ptb.rs
Add the `--summary` flag and refactored our way to display different types.
---
=> [cli] add summary and move displays

external-crates/move/crates/move-compiler/src/expansion/translate.rs, external-crates/move/crates/move-compiler/tests/move_check/verification/specs_are_not_errors.exp, external-crates/move/crates/move-compiler/tests/move_check/verification/specs_are_not_errors.move
- `spec` modules were erroneously marked as errors, and could also trigger duplicate module errors
- new test
---
Fixed an issue where the Move compiler would error when hitting module spec blocks. The error is now a warning, as specs are no longer supported.
=> [move] Fix spec modules being an error

external-crates/move/crates/move-package/src/compilation/build_plan.rs
Updates `clean` in the Move package system to handle extranious top-level files. If someone accidentally created a file there a `clean` would fail, and package builds would not be able to be run.
Tested case locally.
=> [move-package] Update `clean` to handle extranious files in `build` dir

crates/sui-source-validation/src/lib.rs
On windows we have a step to rename the compiler binary like `sui-windows-x86_64` to `sui`. Except that, the windows release tarball names the source binary `sui-windows-x86_64.exe`, so we need to append the `.exe` for the rename to succeed.
Part of end-to-end testing on windows and ran into this.
Tested the fix with local source build--we don't have windows CI env for testing (yet?) so this will have to do for now!
---
=> toolchain versioning: fix windows binary rename

consensus/core/src/base_committer.rs, consensus/core/src/tests/pipelined_committer_tests.rs, consensus/core/src/universal_committer.rs
To help with the review, the test scenarios are the same as in universal_committer_tests.rs & base_committer_tests.rs. Just a different result with number of leaders being committed due to pipelining.
=> [consensus] Add universal committer pipelined tests

crates/sui-json-rpc-types/src/displays/transaction_displays.rs, crates/sui-replay/src/displays/transaction_displays.rs
This fixes the panic that tabled throws when trying to show the output for a transaction that has no inputs or commands. (e.g., calling `client call --package 0x2 --module kiosk --function default`). 
Existing tests, manual test.
Before:
```
thread 'main' panicked at /Users/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tabled-0.15.0/src/grid/records/records_mut.rs:25:18:
index out of bounds: the len is 0 but the index is 0
2024-02-11T03:33:37.781716Z ERROR telemetry_subscribers: panicked at /Users/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tabled-0.15.0/src/grid/records/records_mut.rs:25:18:
index out of bounds: the len is 0 but the index is 0 …
```
=> [cli] Fix issues with showing the output for a transaction 

crates/sui-json-rpc-types/src/displays/transaction_displays.rs, crates/sui-replay/src/displays/transaction_displays.rs
This fixes the panic that tabled throws when trying to show the output for a transaction that has no inputs or commands. (e.g., calling `client call --package 0x2 --module kiosk --function default`).
Existing tests, manual test.
Before:
```
thread 'main' panicked at /Users/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tabled-0.15.0/src/grid/records/records_mut.rs:25:18:
index out of bounds: the len is 0 but the index is 0
2024-02-11T03:33:37.781716Z ERROR telemetry_subscribers: panicked at /Users/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tabled-0.15.0/src/grid/records/records_mut.rs:25:18:
index out of bounds: the len is 0 but the index is 0 …
```
=> [cli] Fix issues with showing the output for a transaction  (#16190)

crates/sui-graphql-rpc/src/types/balance.rs
Filtering on owner_id is only efficient if we specify the owner_type. Balances consist of coin objects, which will be owned by an AddressOwner.
---
=> [gql][cherry-pick] balance query optimization

Cargo.lock, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-rpc/Cargo.toml, crates/sui-graphql-rpc/src/server/builder.rs
This PR cherry-picks the RPC2.0 CORS implementation for the new release.
Existing tests & CI.
---
Added support for CORS in RPC 2.0 server.
=> [cherry-pick-graphql] Add CORS support (#16100)

docs/content/guides/developer/getting-started/local-network.mdx
This PR updates the docs to show how to to use `sui client faucet` for getting tokens from faucet.
Docs, no tests needed.
---
This PR updates the docs to show how to to use `sui client faucet` for getting tokens from faucet.
=> [docs] Show how to use `sui client faucet` for getting tokens from faucet

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/server/builder.rs
The connection timeout parameter is used to control how long we wait for a connection from the pool, rather than how long the connection is allowed to last for -- use the request timeout for the statement timeout instead (how long each request to the DB can take).
```
sui-graphql-e2e-tests$ cargo nextest run --features pg_integration
```
=> [GraphQL] Connection Timeout -> Statement Timeout

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
Causing log spam due to timeout being too small for some simtests. 
Existing simtests
---
=> [CheckpointExecutor] Reduce checkpoint scheduling timeout log spam

Cargo.lock, Cargo.toml, crates/sui-config/src/node.rs, crates/sui-core/Cargo.toml, crates/sui-core/src/authority.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/overload_monitor.rs, crates/sui-core/src/unit_tests/execution_driver_tests.rs, crates/sui-single-node-benchmark/src/single_node.rs, crates/sui-types/src/error.rs, crates/workspace-hack/Cargo.toml
This PR implements the server-side logic of authority overload pushback.
- When txn rejected during signing, objects are still locked to prevent equivocation.
- Create a new error type, ValidatorPushbackAndRetry, to indicate that the client should keep retrying the same request.
Unit tests added for txn selection logic
Integration tests added for testing server side logic.
---
=> Server side authority overload pushback

crates/sui-bridge/src/abi.rs, crates/sui-bridge/src/client/bridge_client.rs, crates/sui-bridge/src/config.rs, crates/sui-bridge/src/error.rs, crates/sui-bridge/src/events.rs, crates/sui-bridge/src/main.rs, crates/sui-bridge/src/server/governance_verifier.rs, crates/sui-bridge/src/server/handler.rs, crates/sui-bridge/src/server/mock_handler.rs, crates/sui-bridge/src/server/mod.rs, crates/sui-bridge/src/sui_client.rs, crates/sui-bridge/src/types.rs
This PR adds the logic for server to handle governance action requests:
1. adds `approved_governance_actions` in `BridgeNodeConfig`. Validators add approved actions there to show support. It is then passed to `GovernanceVerifier`
2. add `GovernanceVerifier` which checks if the requested action is in `approved_governance_actions`, and only signs the action if it is.
More unit tests will come in next PR, to keep this one small. 
unit tests
---
=> [bridge 37/n] add governance action verifier and logic for handling governance actions

consensus/core/src/authority_node.rs, consensus/core/src/block_manager.rs, consensus/core/src/core.rs, consensus/core/src/core_thread.rs, consensus/core/src/dag_state.rs, consensus/core/src/metrics.rs
This PR introduces the first implementation of the block manager. It doesn't handle the Byzantine cases where blocks with invalid causal history can be successfully (proven) cleaned up from memory, but it should be ok for the common case. Some optimisations could be done when we query the DagState (ex could do in bulk) but left those for future iterations.
CI
---
=> [Consensus 2.0] add first implementation of block manager

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs, crates/sui-graphql-rpc/src/server/builder.rs
Cherry-pick of #16206 
The connection timeout parameter is used to control how long we wait for a connection from the pool, rather than how long the connection is allowed to last for -- use the request timeout for the statement timeout instead (how long each request to the DB can take).
```
sui-graphql-e2e-tests$ cargo nextest run --features pg_integration
```
=> [pick/GraphQL] Connection Timeout -> Statement Timeout (#16206)

.github/workflows/release.yml
fix grabbing commit version for homebrew formula.
follow up to https://github.com/MystenLabs/sui/pull/16168
https://github.com/Homebrew/homebrew-core/pull/162591 was created with the version missing from the commit message due to this change, this will fix that moving forward
do it live
---
=> [homebrew] fix grabbing commit version

consensus/core/src/commit_observer.rs, consensus/core/src/dag_state.rs, consensus/core/src/lib.rs, consensus/core/src/linearizer.rs, consensus/core/src/metrics.rs, consensus/core/src/test_dag.rs
Copying comment from PR
```
/// Role of CommitObserver
/// - Called by core when block is created via try_new_block or force_new_block
/// and try_commit returns newly comitted leaders
/// - The newly committed leaders are sent to commit observer and then commit observer
/// gets subdags for each leader via the commit interpreter (linearizer)
/// - The committed subdags are sent as consensus output via an unbounded tokio channel.
/// No back pressure mechanism is needed as backpressure is handled as input into
/// consenus.
/// - Last commit index is persisted in store as soon as the subdag is sent to
/// output channel.
/// - When CommitObserver is initialized a last received commit index can be used
/// to ensure any missing commits are re-sent.
```
=> [consensus] Add Commit Observer

external-crates/move/crates/move-analyzer/src/bin/move-analyzer.rs, external-crates/move/crates/move-analyzer/src/symbols.rs, external-crates/move/crates/move-analyzer/tests/mod-ident-uniform/Move.toml, external-crates/move/crates/move-analyzer/tests/mod-ident-uniform/sources/M1.move
This PR fixes a problem related to module ID strings between parsed AST and typing AST not being the same. In the typing AST name, if the module has both the package address and the package name, the ID string will be `(pkg_name=pkg_addres)::mod_name` whereas the parsing AST it only has the name (as address is not resolved). When using module ID as a map key this causes discrepancy - module info inserted with one ID is unavailable when queried with the other ID. This PR unifies both IDs.
This PR also adds back parallelism accidentally removed in https://github.com/MystenLabs/sui/pull/16178 (move-analyzer does not work without this as the requests are served in separate threads).
Tried to create a unit test for the module ID string fix but was not successful. Nevertheless, without this …
=> [move-ide] Fixed module id name construction

crates/suins-indexer/.env.sample, crates/suins-indexer/src/indexer.rs, crates/suins-indexer/src/main.rs, crates/suins-indexer/tests/checkpoint_process_tests.rs
This PR:
1. Allows dynamic config for registry + subdomain wrapper ID from env file (so we can deploy in diff networks)
2. Gets rid of any S3 related envs, we can just use the public endpoint.
3. Rewrites the logic to use a single loop over all transactions in a sequenced way (so we make sure that in the end of each checkpoint, we only have the LAST state for updates/deletions per name record).
Re-run the existing tests 
```
crates/suins-indexer$ cargo test
```
---
=> [SuiNS Indexer] Dynamic config & edge case fix

crates/sui-framework/packages/sui-framework/Move.toml, external-crates/move/crates/move-cli/src/base/new.rs, external-crates/move/crates/move-cli/tests/build_tests/simple_new/args.exp
Here's what it looks like!
```toml
[package]
name = "love"
[dependencies]
[addresses]
[dev-dependencies]
[dev-addresses]
```
---
=> [CLI] Better manifest, more comments, more love

crates/sui-source-validation/src/lib.rs
Toolchain versioned builds on windows will use `sui.exe` and invoke `sui.exe` rather than just `sui` so that windows users don't need to strip the `.exe` extension in order for things to work.
(from https://github.com/MystenLabs/sui/pull/16182#issuecomment-1938482795)
👀 
---
=> move toolchain: preserve .exe extension for windows

crates/sui-move/src/lib.rs, crates/sui-move/src/manage_package.rs, external-crates/move/crates/move-cli/src/base/disassemble.rs
Adds `sui move manage-package` to scaffold a command that will record `Move.lock` variables for automated address management. Relevant portion of CLI output when running `sui move manage-package --help`:
```
Record addresses (Object IDs) for where this package is published on chain (this command sets variables in Move.lock)
Usage: sui move manage-package [OPTIONS] --network <NETWORK> --original-id <ORIGINAL_ID> --latest-id <LATEST_ID> --version-number <VERSION_NUMBER>
Options:
--network <NETWORK>                       The network chain identifer. Use '35834a8a' for mainnet
--original-id <ORIGINAL_ID>               The original address (Object ID) where this package is published
--latest-id <LATEST_ID>                   The most recent address (Object ID) where this package is published. …
```
=> move: scaffold manage-package command

crates/sui-config/src/node.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/overload_monitor.rs, crates/sui-core/src/test_utils.rs, crates/sui-core/src/unit_tests/execution_driver_tests.rs, crates/sui-e2e-tests/tests/shared_objects_tests.rs, crates/sui-node/src/lib.rs, crates/sui-swarm-config/src/network_config_builder.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui-swarm/src/memory/swarm.rs, crates/test-cluster/src/lib.rs
The config is no longer just threshold. Should be a safe change since it is not being explicitly set in prod.
---
=> Rename OverloadThresholdConfig to AuthorityOverloadConfig

crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination.exp, crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination.move, crates/sui-graphql-e2e-tests/tests/consistency/performance/many_objects.exp, crates/sui-graphql-e2e-tests/tests/consistency/performance/many_objects.move, crates/sui-graphql-rpc/src/consistency.rs, crates/sui-graphql-rpc/src/types/balance.rs, crates/sui-graphql-rpc/src/types/coin.rs, crates/sui-graphql-rpc/src/types/cursor.rs, crates/sui-graphql-rpc/src/types/dynamic_field.rs, crates/sui-graphql-rpc/src/types/object.rs, crates/sui-graphql-rpc/src/types/type_filter.rs, crates/sui-transactional-test-runner/src/test_adapter.rs
Today the consistent objects query is the union of filters applied to the `objects_snapshot` and `objects_history` table. This set of candidates is then `LEFT JOIN`ed against the `objects_history` table again to filter out yet more recent versions of objects that match the criteria. The left hand side grows ever-larger as `objects_snapshot` gets updated, so to limit the number of rows read, we push the `LEFT JOIN` down into the inner queries, essentially treating it as a filter. 
performance/many_objects.move
---
=> [gql] modify consistent objects query to be more performant

crates/sui-graphql-rpc/src/types/dry_run_result.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
Currently we assume that the dev inspect result coming from fullnode is always `Some` but it can actually be `None` if the transaction failed to execute. This PR fixes that and adds a few more e2e test cases for this scenario as well as a scenario where a `TransactionKind` is provided.
Added tests
---
=> [GraphQL] fix issue with failed dry run and add more e2e test

crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/mutation.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
Based on questions/feedback about what fields can return values under the `Mutation.executeTransactionBlock.effects`.
:eyes:
=> [GraphQL/Docs] Clarify docs on transaction finality
