Cargo.toml
crates/sui-graphql-rpc/Cargo.toml

Fixes comment from here https://github.com/MystenLabs/sui/pull/14420#discussion_r1374472597
Existing 
---

[graphql/rpc] easy/chore: fix workspace import

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.13.0 version bump

---

sdk/deepbook/src/client.ts

https://github.com/MystenLabs/sui/issues/14421
Integrations with MM have found some issues with the type check.
Testnet.
---

[deepbook ts-sdk] Bug fixing coin type check + arg for pool query

---

docs/site/docusaurus.config.js
docs/site/vercel.json

Config updates for doc site. Hiding from search and updating edit link.
Local
---

Config update for docs

---

docs/content/concepts/sui-move-concepts/patterns/capabilities.mdx

- `upgradeCap` -> `UpgradeCap`
- Remove unnecessary trailing paren.
:eyes:

[Docs/Capability] Tweaks

---

docs/content/concepts/cryptography/transaction-auth/keys-addresses.mdx

[Docs/Keys and Addresses][EASY] Fix typo in title

---

docs/content/concepts/sui-move-concepts/patterns/id-pointer.mdx

List was being rendered as a code block
:eyes:

[Docs/ID Pointer] Fix list formatting

---

docs/site/package.json

Forgot to upload package.json previously
---

Added doco module

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_30.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_30.snap

Same as https://github.com/MystenLabs/sui/pull/14536 but for main branch
---

[chore] disable the throughput aware consensus submission for all environments

---

crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/main.rs

Allows generating the config file for editing & loading later
Manual
---

[graphql/rpc] easy: cmd to generate config yaml

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/address.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap

Adds comments for the Stake fields and stake connection.
---

[graphql/rpc] stake comments for docs

---

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/transaction_block.rs

[graphql] accurate costing

---

crates/sui-graphql-rpc/docs/examples.md
crates/sui-graphql-rpc/examples/address/address.graphql

Add a simple address example.
---

[graphql/example] add address example

---

crates/sui-graphql-rpc/docs/examples.md
crates/sui-graphql-rpc/examples/service_config/service_config.graphql

Add service config example.
No tests needed. 
---

[graphql/examples] add service config example

---

docs/site/src/pages/index.js
docs/site/src/theme/Footer/Layout/index.js

Fixes some responsive issues on some phones
Local
---

Responsive fixes

---

crates/sui-graphql-rpc/src/config.rs

Allows schema get queries to run
Manual
---

[graphql/rpc] increase default query limits

---

apps/wallet/src/ui/app/hooks/useSortedCoinsByCategories.ts
apps/wallet/src/ui/app/shared/tooltip/index.tsx
apps/wallet/src/ui/app/staking/stake/ValidatorFormDetail.tsx

- Add sorting coins by SUI first, and rest alphabetical ordering
- Fix width issue with icon tooltip
---

add wallet small fixes

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/protocol_config.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap

Document ProtocolConfig related queries
:eyes:

[GraphQL/Docs] Protocol Config

---

docs/content/references/cli/client.mdx

Updated cli client doc with added commands

---

crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs

Prod DBs are slower so we need to compensate
Estimated based on prod DB
---

[graphql/rpc] increase db cost limit

---

crates/sui-graphql-rpc/src/config.rs

[graphql/rpc] raise limits

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/safe_mode.rs
crates/sui-graphql-rpc/src/types/stake_subsidy.rs
crates/sui-graphql-rpc/src/types/storage_fund.rs
crates/sui-graphql-rpc/src/types/sui_system_state_summary.rs
crates/sui-graphql-rpc/src/types/system_parameters.rs
crates/sui-graphql-rpc/src/types/validator_set.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap

Also:
- `SystemParameters`
- `StakeSubsidy`
- `ValidatorSet` (although this is missing some fields)
- `SafeMode`
- `StorageFund`
:eyes:

[GraphQL/Docs] Comments for SuiSystemStateSummary et al.

---

docs/content/references/sui-api/beta-graph-ql.mdx

Augment the documentation on the current limits, future plans for limits, currently unsupported features and where to send feedback.
:eyes:

[Docs/GraphQL] Document Limits, Unsupported Features

---

docs/content/sidebars/guides.js

Nav entry was missing for "write package"
Local
---

Adding missing write package nav entry

---

.changeset/six-ways-destroy.md
sdk/typescript/src/bcs/index.ts
sdk/typescript/src/builder/__tests__/bcs.test.ts
sdk/typescript/test/e2e/read-transactions.test.ts

[ts sdk] Fix formatting when parsing addresses with bcs.Address

---

docs/content/references/sui-api/beta-graph-ql.mdx

remove references to testnet instance until we get it working properly and are able to launch it.
---

[docs/graphql] remove references to testnet instance

---

docs/site/docusaurus.config.js

Adding config for search
Local
---

Docs search

---

docs/site/src/pages/index.js

Updating link and adding alt text to decorative image
Vercel
---

Update api link on index and add alt text

---

docs/content/guides/developer/app-examples.mdx
docs/content/guides/developer/app-examples/coin-flip.mdx

Updated the Coin Flip app example
Locally

Update Coin Flip app example

---

.changeset/blue-bulldogs-provide.md
sdk/dapp-kit/src/components/AccountDropdownMenu.tsx
sdk/dapp-kit/src/hooks/useResolveSuiNSNames.ts
sdk/dapp-kit/src/hooks/useSuiClientInfiniteQuery.ts
sdk/dapp-kit/src/hooks/useSuiClientMutation.ts
sdk/dapp-kit/src/hooks/useSuiClientQuery.ts
sdk/dapp-kit/src/hooks/wallet/useAccounts.ts
sdk/dapp-kit/src/hooks/wallet/useConnectWallet.ts
sdk/dapp-kit/src/hooks/wallet/useCurrentAccount.ts
sdk/dapp-kit/src/hooks/wallet/useDisconnectWallet.ts
sdk/dapp-kit/src/hooks/wallet/useSignAndExecuteTransactionBlock.ts
sdk/dapp-kit/src/hooks/wallet/useSignPersonalMessage.ts
sdk/dapp-kit/src/hooks/wallet/useSignTransactionBlock.ts
sdk/dapp-kit/src/hooks/wallet/useSwitchAccount.ts
sdk/dapp-kit/tsconfig.esm.json

[dapp-kit] fix esm typescript types

---

docs/content/sidebars/guides.js

Moving app examples into the developer guides.
Vercel
---

Moving examples into dev guides

---

crates/sui-move-build/tests/linter/coin_field.exp
crates/sui-move-build/tests/linter/share_owned.exp
external-crates/move/move-compiler/src/cfgir/borrows/mod.rs
external-crates/move/move-compiler/src/cfgir/borrows/state.rs
external-crates/move/move-compiler/src/cfgir/cfg.rs
external-crates/move/move-compiler/src/cfgir/liveness/mod.rs
external-crates/move/move-compiler/src/cfgir/locals/mod.rs
external-crates/move/move-compiler/src/cfgir/optimize/constant_fold.rs
external-crates/move/move-compiler/src/cfgir/optimize/eliminate_locals.rs
external-crates/move/move-compiler/src/cfgir/visitor.rs
external-crates/move/move-compiler/src/hlir/ast.rs
external-crates/move/move-compiler/src/hlir/translate.rs
external-crates/move/move-compiler/src/to_bytecode/translate.rs
external-crates/move/move-compiler/src/typing/translate.rs
external-crates/move/move-compiler/tests/move_check/borrows/unused_mut_ref_unpack.move
external-crates/move/move-compiler/tests/move_check/borrows/unused_mut_ref_unpack.unused.exp
external-crates/move/move-compiler/tests/move_check/borrows/used_mut_ref_unpack.move
external-crates/move/move-compiler/tests/move_check/typing/unused_id_field.move
external-crates/move/move-compiler/tests/move_check/typing/unused_id_field.unused.exp
external-crates/move/move-compiler/tests/sui_mode/struct_with_key/unused_id_field.move

- Unused mutable borrow warning did not play well with unpack field. The fields from an unpack now track the original reference, since you cannot switch individual fields to be immutable 
- Suppressed unused field warning for id in Sui mode
- New tests
---
This release fixes two issues with compiler warnings. 
- Fixed an issue where mutable borrow warnings did not work as intended with unpack patterns. The warning was given when it should not have been if some fields in the pattern were not used mutably.
- The unused field warning is now suppressed for objects in Sui …

[move-compiler] Fix issue with mut borrow warnings. Suppress unused id field

---

sdk/dapp-kit/src/components/AccountDropdownMenu.tsx
sdk/dapp-kit/src/hooks/useResolveSuiNSNames.ts
sdk/dapp-kit/src/hooks/useSuiClientQuery.ts

[dapp-kit] Fix typing when using select with useSuiClientQuery

---

docs/site/docusaurus.config.js

Updating to correct data

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/address.rs
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap

[graphql]comments for movepackage, suins, object

---

crates/sui-archival/src/lib.rs

This sui-tool command may fail silently due to returning `Ok(())` after `num_retries` unsuccessful attempts. Let's log errors and bubble up a failure code on repeated unsuccessful attempts.
TODO
---

[archival checker] Log errors and fail after num_retries

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/gas.rs
crates/sui-graphql-rpc/src/types/transaction_block.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__test__schema_sdl_export.snap

[graphql] doc comments for checkpoint and tx block

---

docs/content/concepts/sui-move-concepts/patterns/hot-potato.mdx

Temporarily addresses poor display of code in dark mode. 
Local
---

Revert language to original until style gets fixed

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/transaction_manager.rs

Add some metrics for 
- How long transactions wait in execution queue,
- Rejections at signing and executing stage due to system overload,
---

add metrics for system overload

---

crates/sui-core/src/state_accumulator.rs
crates/sui-e2e-tests/tests/unwrapped_then_deleted_tests.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-types/src/effects/effects_v2.rs

Make accumulate_state work with TransactionEffectsV2

---

docs/site/docusaurus.config.js

Search config change

---

apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
apps/wallet/src/ui/app/pages/swap/ToAssetSection.tsx

- Add info to input section
---

[Wallet]: add info to input section

---

sui-execution/latest/sui-adapter/src/temporary_store.rs

As explained in the comment
CI
---

Update a bogus comment in TemporaryStore

---

crates/sui-archival/src/lib.rs

[archive checker] Fix start checkpoint for retries

---

.github/workflows/release.yml

Add move-analyzer binary to releases
[Testing via my branch](https://github.com/MystenLabs/sui/actions/runs/6735987128)

Add move-analyzer binary to releases

---

docs/content/standards/deepbook/orders.mdx
docs/content/standards/deepbook/query-the-pool.mdx
docs/content/standards/deepbook/routing-a-swap.mdx
docs/content/standards/deepbook/trade-and-swap.mdx

[Deepbook Documentation] Adding websocket example for deepbook

---

docs/content/guides/developer/getting-started/sui-install.mdx

Install topic was missing some content. Added it back in and fixed the links that began install from source section.
Vercel
---

Updated install with missing content and fixed internal linking

---

crates/sui-e2e-tests/tests/unwrapped_then_deleted_tests.rs
crates/sui-protocol-config/src/lib.rs

Set enable effect V2 inside setting simplified_unwrap_then_delete option

---

docs/content/guides/operator/sui-full-node.mdx
docs/content/references/exchange-integration-guide.mdx

Updated content to match most recent recommendations.
Local
---

Updated content to most up-to-date recs

---

crates/sui-core/src/consensus_handler.rs

Described in the comment
CI
---

Add MysticetiConsensusHandler

---

crates/shared-crypto/src/intent.rs
crates/sui-types/src/unit_tests/utils.rs
crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs
crates/sui/src/keytool.rs
crates/sui/src/zklogin_commands_util.rs
docs/content/concepts/cryptography/zklogin.mdx

Add a keytool to verify a zklogin signature offchain. 
unit test and local cli test
```
target/debug/sui keytool zk-login-sign-personal-message --data hello                                     ✔  10086  11:54:56
────────────────────────────────────────────────╮
│ sig   │  BQNNMTczMTgwODkxMjU5NTI0MjE3MzYzNDIyNjM3MTc5MzI3MTk0Mzc3MTc4NDQyODI0MTAxODc5NTc5ODQ3NTE5Mzk5NDI4OTgyNTEyNTBNMTEzNzM5NjY2NDU0NjkxMjI1ODIwNzQwODIyOTU5ODUzODgyNTg4NDA2ODE2MTgyNjg1OTM5NzY2OTczMjU4OTIyODA5MTU2ODEyMDcBMQMCTDU5Mzk4NzExNDczNDg4MzQ5OTczNjE3MjAxMjIyMzg5ODAxNzcxNTIzMDMyNzQzMTEwNDcyNDk5MDU5NDIzODQ5MTU3Njg2OTA4OTVMNDUzMzU2ODI3MTEzNDc4NTI3ODczMTIzNDU3MDM2MTQ4MjY1MTk5Njc0MDc5MTg4ODI4NTg2NDk2Njg4NDAzMjcxNzA0OTgxMTcwOAJNMTA1NjQzODcyODUwNzE1NTU0Njk3NTM5OTA2NjE0MTA4NDAxMTg2MzU5MjU0NjY1OTcwMzcwMTgwNTg3NzAwNDEzNDc1MTg0NjEz …
```

keytool: add sign personal message cli and verify with zklogin

---

apps/explorer/src/components/footer/footerLinks.tsx
apps/wallet/src/shared/constants.ts

Update explorer and wallet TOS links

---

docs/content/concepts/cryptography/zklogin.mdx

These changes were made to the zklogin doc during update to new site and were missed. This PR puts them back in.
Local
---

[Docs] Transferring changes from PR14472

---

Cargo.lock
crates/sui-core/Cargo.toml
crates/sui-core/src/consensus_types/consensus_output_api.rs
crates/workspace-hack/Cargo.toml

[mysticeti] Use committed subdag index

---

crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/types/address.rs
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_object.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/object_change.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/sui_address.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind.rs

Cleanup clippy overrides
Existing
---

[graphql/rpc] chore: cleanup clippy

---

crates/sui-kvstore/src/client.rs
crates/sui-kvstore/src/writer.rs

most common failure is timeout on DynamoDB side

[kv store] add retries for checkpoint uploads

---

crates/sui-analytics-indexer/src/handlers/transaction_handler.rs
crates/sui-analytics-indexer/src/tables.rs

Adds two fields which let us query and filter for transactions which have used zklogin or upgraded multisig signature schemes in analytics
Will run a backfill for last few weeks

Add fields to capture zklogin or upgraded multisig in txn

---

apps/wallet/src/shared/analytics/ampli/index.ts
apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
apps/wallet/src/ui/app/pages/swap/index.tsx

https://mysten.atlassian.net/browse/APPS-1912
---

[Wallet]: Add Amplitude tracking for DEFI swap

---

Cargo.lock
crates/sui-core/Cargo.toml
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-core/src/consensus_validator.rs
crates/workspace-hack/Cargo.toml

[mysticeti] Pass block verifier to mysticeti

---

Cargo.lock
crates/sui-core/Cargo.toml
crates/workspace-hack/Cargo.toml

This fixes some network issues and add debug logs
---

[mysticeti] Update mysticeti reference

---

crates/sui-core/src/consensus_types/consensus_output_api.rs

[mysticeti] Fix transaction deserialization

---

crates/sui-storage/src/object_store/mod.rs

Follow up to https://github.com/MystenLabs/sui/pull/14707, missed a spot
I'll test on a testnet fullnode

remove hardcoded virtual hosted

---

.changeset/cyan-ladybugs-matter.md
sdk/typescript/src/zklogin/address.ts
sdk/zklogin/test/address.test.ts

[zkLogin] Use the same issuer string in address derivation for the two google's iss values 

---

docs/content/references/cli/console.mdx

Adds the console page for the CLI docs.
---
Added the console page documentation for the CLI docs.

[docs/cli] add console page

---

crates/sui-replay/src/data_fetcher.rs
crates/sui-replay/src/lib.rs
crates/sui-replay/src/replay.rs
crates/sui-replay/src/types.rs

Use the proper chain when fetching protocol configs
Existing
---

[replay] use proper chain

---

sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs

Ported from https://github.com/qkniep/sui/commit/910f127305d0b8ec95b631c1b10259bfe8e39487

basic type caching with static HashMap

---

docs/content/references/cli.mdx
docs/content/references/cli/client.mdx
docs/content/references/cli/console.mdx
docs/content/references/cli/keytool.mdx
docs/content/references/cli/move.mdx
docs/content/snippets/cli-check-install.mdx

Adds version check content and install link to all CLI docs using single source.
Local
---

[Docs] Added version check to all cli docs

---

.changeset/heavy-frogs-own.md
sdk/typescript/src/client/client.ts
sdk/typescript/test/e2e/dev-inspect.test.ts

[ts-sdk] fix setting gasPrice in devInspectTransactionBlock call

---

docs/site/src/components/API/api-ref/examples.js
docs/site/src/components/API/api-ref/method.js
docs/site/src/pages/index.js

Fixes API ref bad info on method param in examples.
Local
---

API ref fix

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.15.0 version bump

---

docs/content/references/cli/client.mdx

Fix typo in references/cli/client docs.
---
Fix typo in docs.

[docs] Fix typo

---

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs

If no coin type is provided, we should default to `0x2::sui::SUI`. Previously we added no filter on the coin type, which meant that we were returning arbitrary objects from the coin connection field.
GraphiQL:
<TODO: Screenshot>

[GraphQL] Fix default coin type

---

docs/content/concepts/sui-architecture/epochs.mdx

Add epoch and reconfig doc

---

crates/sui-core/src/authority/authority_store_pruner.rs

Add a metric to track pruned tombstones

---

docs/content/guides/operator/exchange-integration.mdx
docs/content/sidebars/guides.js
docs/site/vercel.json

Importing the exchange integration doc and updating links.
Local
---

Import exchange integration doc and add redirects (DOCS-110, too)

---

crates/sui-graphql-rpc/src/test_infra/data/example.exp
crates/sui-transactional-test-runner/src/test_adapter.rs

Cleansup logic based on [comments](https://github.com/MystenLabs/sui/pull/14710/files#r1389817735) from PR
Existing
---

[transactional test runner] chore: refactor account creation

---

crates/sui-analytics-indexer/src/analytics_processor.rs
crates/sui-archival/src/lib.rs
crates/sui-archival/src/reader.rs
crates/sui-archival/src/writer.rs
crates/sui-core/src/db_checkpoint_handler.rs
crates/sui-snapshot/src/reader.rs
crates/sui-snapshot/src/uploader.rs
crates/sui-snapshot/src/writer.rs
crates/sui-storage/src/object_store/http/gcs.rs
crates/sui-storage/src/object_store/http/local.rs
crates/sui-storage/src/object_store/http/mod.rs
crates/sui-storage/src/object_store/http/s3.rs
crates/sui-storage/src/object_store/mod.rs
crates/sui-storage/src/object_store/util.rs
crates/sui-tool/src/commands.rs
crates/sui-tool/src/lib.rs

Cherry pick https://github.com/MystenLabs/sui/pull/14761 into release branch
---

Cherry pick 14761

---

apps/core/src/utils/kiosk.ts
apps/wallet/src/ui/app/components/nft-display/index.tsx
apps/wallet/src/ui/app/hooks/useGetNFTs.ts
apps/wallet/src/ui/app/pages/home/hidden-assets/index.tsx
apps/wallet/src/ui/app/pages/home/nfts/VisualAssets.tsx

* support displaying personal kiosks in wallet
closes APPS-1917
👀 
---

wallet-ext: support personal kiosks

---

crates/sui-indexer/src/apis/coin_api_v2.rs
crates/sui-json-rpc/src/coin_api.rs

return a hardcoded Sui total supply on FN RPC
CI
---

Fn sui supply

---

crates/sui-tool/src/commands.rs

[formal snapshots] Fix default bucket type

---

external-crates/move/crates/move-analyzer/editors/code/.eslintrc.json
external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package-lock.json
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/editors/code/src/configuration.ts
external-crates/move/crates/move-analyzer/editors/code/src/context.ts
external-crates/move/crates/move-analyzer/editors/code/src/extension.ts
external-crates/move/crates/move-analyzer/editors/code/src/log.ts
external-crates/move/crates/move-analyzer/editors/code/src/main.ts
external-crates/move/crates/move-analyzer/editors/code/tsconfig.json

Changed the name of the Sui-focused plugin to previously agreed name. Also updated dependencies (TS compiler version etc.). No functionality added or removed.
Verified that it works the same as before
---

[move-ide] Changed the plugin name and updated dependencies

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

Cherrypick #14850

---

dapps/kiosk/package.json
dapps/kiosk/vite.config.ts
dapps/multisig-toolkit/package.json
dapps/multisig-toolkit/vite.config.ts
dapps/sponsored-transactions/package.json
dapps/sponsored-transactions/vite.config.ts

Remove source conditions from dapps

---

sdk/dapp-kit/package.json
sdk/dapp-kit/vitest.config.ts
sdk/wallet-kit/example/package.json
sdk/wallet-kit/example/src/index.tsx
sdk/wallet-kit/example/vite.config.ts
sdk/zklogin/vitest.config.ts
turbo.json

Remove source conditions from sdks

---

crates/sui-graphql-rpc/src/test_infra/cluster.rs

Indexer reader should not reset the DB
Manual
---

fix indexer reader start

---

apps/core/package.json
apps/core/vitest.config.ts
apps/explorer/src/index.tsx
apps/wallet/tests/demo-app/vite.config.ts
apps/wallet/vitest.config.ts
sdk/bcs/package.json
sdk/dapp-kit/package.json
sdk/deepbook/package.json
sdk/kiosk/package.json
sdk/suins-toolkit/package.json
sdk/typescript/package.json
sdk/wallet-kit/core/package.json
sdk/wallet-kit/react/package.json
sdk/wallet-standard/package.json
sdk/zklogin/package.json

Remove the rest of the source conditions

---

Cargo.lock
crates/sui-archival/src/lib.rs
crates/sui-archival/src/reader.rs
crates/sui-archival/src/tests.rs
crates/sui-network/src/state_sync/mod.rs
crates/sui-tool/Cargo.toml
crates/sui-tool/src/commands.rs
crates/sui-tool/src/lib.rs

Adding a sui tool command to dump checkpoint summaries in range in an archive
`cargo run --release -p sui-tool dump-archive s3 --bucket mysten-mainnet-archives --aws-region us-west-2 --no-sign-request 18345081 18345657`
```2023-11-17T02:25:12.580356Z  INFO sui_tool: 18345103:9cHBvnYg5bWDKPexhmTRsj2VuZVqNBfgJahyGguSQspc:"{\"transactions\":[{\"transaction\":{\"data\":[{\"intent_message\":{\"intent\":{\"scope\":0,"
2023-11-17T02:25:12.581868Z  INFO sui_tool: 18345104:8pWBwBZJN7wmZ7gemiA8fT99ujA3K9keUmiWNrEhMLXP:"{\"transactions\":[{\"transaction\":{\"data\":[{\"intent_message\":{\"intent\":{\"scope\":0,"
2023-11-17T02:25:12.582815Z  INFO sui_tool: 18345105:7KoPwertPFjsgCkrizbMHkdDKJ2eNbj3Ap1obGszQNDN:"{\"transactions\":[{\"transaction\":{\"data\":[{\"intent_message\":{\"intent\":{\"scope\":0, …
```

Dump checkpoint summaries in range

---

apps/wallet/src/ui/app/pages/home/tokens/coin-balance/index.tsx

https://mysten-labs.slack.com/archives/C0393DWJD7X/p1700181684869979
Disable USDC values when !== mainnet
---

[wallet]: disable coin values when not mainnet

---

docs/content/guides/developer/cryptography/ecvrf.mdx

docs fix typo

---

crates/sui-core/src/consensus_handler.rs

When an authority is down, no update will be generated for its consensus metric values.
But in this case we still want to update prometheus about the new metric values.
CI
---

[Fix] set consensus metric values for all authorities

---

crates/sui-test-validator/src/main.rs

Change cmd behavior for start test validaror:
* no default graphql port, which forces one to specify it to enable graphql
* indexer is gated by --with_indexer, and --use-indexer-v2 for newer indexer, which is what you want
* graphql does not depend on indexer flags but on db availability
Manual
---

[graphql/rpc] simplify cmd

---

crates/sui-core/src/consensus_handler.rs

The feature is a bit time sensitive and the commit should be low risk.
---

Cherrypick #14875

---

external-crates/move/crates/move-vm-runtime/src/debug.rs
external-crates/move/crates/move-vm-runtime/src/loader.rs

This adds some ad-hoc quality of life improvements to the Move debugger, without going into a larger engineering effort. By no means the end-all-be-all, but just fixes some pain points and adds a couple small new requested features.
Existing tests
---

[move] Add some quality of life improvements to the debugger

---

docs/content/concepts/sui-architecture/staking-rewards.mdx
docs/content/guides/operator/staking-rewards.mdx
docs/content/sidebars/concepts.js
docs/content/sidebars/guides.js
docs/content/snippets/staking-pool-reqs.mdx

Add docs for staking and rewards in node operator guides.
---

[docs] add staking and rewards for operator doc

---

.github/workflows/release.yml

push sui binaries archives to s3
https://github.com/MystenLabs/sui/actions/runs/6934597507
Upload to s3: https://s3.console.aws.amazon.com/s3/object/sui-releases?region=us-east-1&prefix=releases/sui-devnet-v1.14.0-ubuntu-x86_64.tgz

[sui-releases]: push sui binaries archives to s3

---

README.md

Update link to documentation.
N/A

Update link to documentation in README.md

---

crates/sui-sdk/README.md
docs/content/references.mdx
docs/content/references/rust-sdk.mdx
docs/content/sidebars/references.js

Import readme for Rust SDK crate in docs.sui.io page.
Local
---

[Docs] Update Rust SDK doc

---

crates/sui-graphql-e2e-tests/tests/call/owned_objects.exp
crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-e2e-tests/tests/call/simple.move
crates/sui-transactional-test-runner/src/args.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

As discussed, allow stepping by multiple checkpoints and epochs
included
---

[graphql/rpc] add multi checkpoint and epoch advance commands

---

docs/site/pnpm-workspace.yaml
pnpm-lock.yaml

pnpm installs are broken on vercel because of a change to empty projects.
---

Fix docs site for new pnpm

---

.changeset/beige-tigers-knock.md
pnpm-lock.yaml
sdk/enoki/package.json
sdk/enoki/src/encryption.ts

Enoki SDK fixes

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/schema/draft_target_schema.graphql
crates/sui-graphql-rpc/src/context_data/db_backend.rs
crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-graphql-rpc/src/context_data/pg_backend.rs
crates/sui-graphql-rpc/src/types/address.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Adds `coinConnection` to top-level `Query`
Need to figure out how to write tests for this. Until then, here's a screenshot.
---

[graphql] Add coinConnection to Query

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

This has been cherrypicked into 1.14 (https://github.com/MystenLabs/sui/commit/e705692ba50b2ffbb79e10ab00fdcff955b4a6c8), but it seems we will rollout a newer 1.13 build to mainnet.
---
---

Cherrypick #14850 to 1.13

---

apps/explorer/src/components/Layout/PageLayout.tsx

https://mysten-labs.slack.com/archives/C032676BWGN/p1700593329399899?thread_ts=1699902455.126649&cid=C032676BWGN
---

[Explorer]: remove custom banner on testnet

---

crates/sui-graphql-rpc/src/error.rs

Removes duplicate Error type.
---

[graphql] remove duplicate Error type

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs

Reduce  the time spent initializing cluster in tests.
This speeds up tests.
Existing
---

Graphql impl quicker tests

---

crates/sui-graphql-e2e-tests/tests/packages/friends.exp
crates/sui-graphql-e2e-tests/tests/packages/friends.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Connection to go over a module's friends.
New E2E test:
```
-- friends.move
```
- #14929 
- #14930 
- #14934

[GraphQL/MoveModule] friendConnection

---

dapps/sponsored-transactions/src/App.tsx
dapps/sponsored-transactions/src/utils/rpc.ts
dapps/sponsored-transactions/src/utils/sponsorTransaction.ts

Fix sponsored-transaction example

---

pnpm-lock.yaml
sdk/zksend/.prettierignore
sdk/zksend/README.md
sdk/zksend/package.json
sdk/zksend/src/index.test.ts
sdk/zksend/src/index.ts
sdk/zksend/tsconfig.esm.json
sdk/zksend/tsconfig.json
sdk/zksend/vitest.config.ts

Scaffold zkSend SDK

---

.github/workflows/simulator-nightly.yml

Tagging `@sui-core` for simtest failures
See https://mysten-labs.slack.com/archives/C03QJ1B6BC0/p1700678375773249

Tagging `@sui-core` for simtest failures

---

crates/sui-graphql-e2e-tests/tests/call/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-e2e-tests/tests/packages/modules.exp
crates/sui-graphql-e2e-tests/tests/packages/modules.move
crates/sui-graphql-rpc/src/types/move_package.rs

Some improvements to `MovePackage.moduleConnection` and associated tests.
New E2E tests:
```
-- modules.move
```

[GraphQL/MovePackage] Hardening moduleConnection

---

Cargo.lock
Cargo.toml
crates/sui-core/benches/verified_cert_cache_bench.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/signature_verifier.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-e2e-tests/tests/zklogin_tests.rs
crates/sui-types/src/base_types.rs
crates/sui-types/src/effects/mod.rs
crates/sui-types/src/error.rs
crates/sui-types/src/message_envelope.rs
crates/sui-types/src/messages_checkpoint.rs
crates/sui-types/src/transaction.rs
crates/sui-types/src/unit_tests/messages_tests.rs
crates/sui-types/src/unit_tests/utils.rs
crates/sui-types/src/zk_login_authenticator.rs
crates/workspace-hack/Cargo.toml

- Test improvements and fixes
- update fastcrypto pointer

Test fixes and fastcrypto update

---

docs/content/guides/developer/first-app/build-test.mdx

Fixes typo in the command in [docs](https://docs.sui.io/guides/developer/first-app/build-test#testing-a-package)
---

[docs] Fixes typo in the command

---

nre/sui_for_node_operators.md

`sui_system` is in package `0x3` not `0x2`
---

Fix wrong package id

---

crates/sui-graphql-rpc/src/test_infra/cluster.rs

handle potential panic if checkpoint is 0
existing tests
---

[graphql] update checkpoint catch up logic for test suite

---

.github/workflows/simulator-nightly.yml

simtest notification: remove brackets
👀

simtest notification: remove brackets

---

crates/sui/src/keytool.rs

add feature to import private key for all schemes. 
local test
---

keytool: add import private key for schemes

---

crates/sui-framework/docs/groth16.md
crates/sui-framework/docs/validator_set.md
crates/sui-framework/packages/sui-framework/sources/crypto/groth16.move
crates/sui-framework/packages/sui-system/sources/validator_set.move

Fixes several types identified by @liziopizio in #9641. That PR is very outdated, so it was easier to just fix it in a new PR.  
---
Fixes several doc typos indicated by @liziopizio in #9641.

[docs] Fix typos in docs and source code, flagged by @liziopizio

---

examples/move/flash_lender/sources/example.move

Update source code comment to reflect the function's purpose. Closes #15024
---

[examples] Fix source code comment in FlashLender example

---

docs/README.md

Added more detail to the docs deployment README
Local

Update docs deployment instructions

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Standardise the docs for `coinConnection` to explain which type is expected and what it defaults to.
:eyes:

[GraphQL/Coin][EASY] Be explicit about default coin type

---

.github/workflows/simulator-nightly.yml

Simtest: make sui_commit more explicit
Testing via my branch

Simtest: make sui_commit more explicit

---

.github/actions/ts-e2e/action.yml

TS SDK e2e fixes

---

crates/sui-storage/src/object_store/mod.rs

Requester pays buckets are failing to be written with because of the following error: `Bucket is a requester pays bucket but no user project provided`. 
I believe I need to set both headers, based off of: https://github.com/googleapis/google-cloud-go/commit/558b56dfa3c56acc26fef35cb07f97df0bb18b39
Running on testnet
---

set user project headers for requester pays bucket

---

docs/content/guides/developer/getting-started/get-coins.mdx

[Docs][EASY] Updating port for faucet on local network

---

.changeset/unlucky-donkeys-ring.md
sdk/zklogin/src/address.ts
sdk/zklogin/test/address.test.ts

Revert easy-to-implement + important checks from #14298. Rest requires a custom json parser (which requires finding an alternative to https://github.com/microsoft/node-jsonc-parser/) + the remaining are not as crucial.
Added tests!
---

[zkLogin] Add length checks

---

crates/sui-core/src/db_checkpoint_handler.rs

Do not swallow errors in db checkpoint handler

---

docs/content/guides/developer/app-examples/coin-flip.mdx
docs/content/guides/developer/app-examples/e2e-counter.mdx
docs/content/guides/developer/first-app/client-tssdk.mdx
sdk/create-dapp/README.md
sdk/docs/pages/dapp-kit/create-dapp.mdx

We previously documented the command as `pnpm create @mysten/create-dapp` but should be using `pnpm create @mysten/dapp` which will work when converted to yarn or npm (the `create-` prefix for the package name is automatically applied by the `create` command)
---

[docs] update docs for create-dapp command

---

Cargo.lock
Cargo.toml
crates/sui-bridge/Cargo.toml
crates/sui-bridge/abi/example.json
crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/error.rs
crates/sui-bridge/src/eth_client.rs
crates/sui-bridge/src/handler.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/main.rs
crates/sui-bridge/src/server.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-sdk/src/apis.rs
crates/workspace-hack/Cargo.toml
deny.toml

As title, mostly server side of things.
Started the server locally with more functionality. This is a cleaned up version for review.
---
add skeleton for bridge node

[bridge] 1/n add skeleton for bridge node

---

Cargo.lock
Cargo.toml
crates/workspace-hack/Cargo.toml

chore: update fastcrypto pointer

---

docs/content/guides/developer/app-examples/weather-oracle.mdx

Fixes typo in Weather Oracle that makes a lint to fail.
---

[docs] Fix typo in Weather Oracle

---

crates/sui-graphql-e2e-tests/tests/packages/functions.exp
crates/sui-graphql-e2e-tests/tests/packages/functions.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/mod.rs
crates/sui-graphql-rpc/src/types/move_function.rs
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_struct.rs
crates/sui-graphql-rpc/src/types/open_move_type.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-package-resolver/src/lib.rs

Query for a function from a module by name.
New E2E tests:
```
sui-graphql-e2e-test$ cargo nextest run \
-j 1 --features pg_integration        \
-- functions.move
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
- #15015

[GraphQL/MoveModule] function field

---

crates/sui-macros/src/lib.rs

These log messages seem to be a bit noisy in simtests.
simtest
---

Reduce severity of failpoint log

---

crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp
crates/sui-graphql-e2e-tests/tests/transactions/programmable.move
crates/sui-graphql-e2e-tests/tests/transactions/system.exp
crates/sui-graphql-e2e-tests/tests/transactions/system.move

Create some transactional tests demonstrating the various transaction block and effects queries, to make it easy to spot changes to output due to changes to come in future refactorings.
```
-- transactions
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
- #15015
- #15016
- #15018
- #15020

[GraphQL/TransactionBlock] E2E tests

---

crates/sui-graphql-rpc/src/types/gas.rs

Code motion only change, similar to previous change to TransactionBlock:
- Put the types first
- Put the non-trait impl blocks after
- Then the trait impls
- Then the free functions
In each section, public functions first.  This is
- to surface the parts of the file that people need to see if they are visiting that file from somewhere else.
- to make it more obvious when a file is growing too large (contains a lot of disparate things).
- for consistency, which helps with readability.
```
```
- #14929 
- #14930 
- #14934
- #14935 
- #14961 
- #14974
- #15013
- #15014
- #15015
- #15016
- #15018
- #15020
- #15021
- #15036

[GraphQL/Gas][EASY] Re-order file

---

docs/content/references/cli/client.mdx
docs/content/references/cli/console.mdx
docs/content/references/cli/keytool.mdx
docs/content/references/cli/move.mdx
docs/content/references/cli/validator.mdx

Adds the CLI validator page and minor updates to other clis
---

[docs] CLI updates

---

.changeset/tame-wasps-sit.md
sdk/enoki/demo/main.tsx
sdk/enoki/src/EnokiClient/index.ts
sdk/enoki/src/EnokiClient/type.ts
sdk/enoki/src/EnokiFlow.ts

Two step sponsor API

---

crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-open-rpc/spec/openrpc.json

---
add clarifying comments for EventFilter

add clarifying comments for EventFilter

---

.github/workflows/bench.yml
.github/workflows/release-notes-monitor.yml
.github/workflows/tag.yml

Remove self-hosted runners usage
See https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security
👀

Remove self-hosted runners usage

---

docs/content/concepts/transactions/transaction-lifecycle.mdx
docs/content/guides/developer/app-examples.mdx
docs/content/guides/developer/app-examples/recaptcha.mdx
docs/content/standards/wallet-standard.mdx

I didn't read the description the first time through, but it was outdated.
---

copy tweak

---

.github/workflows/docs-ci.yml

Noticed that docs didn't have any CI and we broke it a couple times as a result, so adding a job that tests it.
---

[docs] Add CI

---

nre/sui_for_node_operators.md

Updated links to scripts for binaries verification
👀

Updated links to scripts for binaries verification

---

.github/workflows/codecov.yml

[codecov]: Add setting swap space
Going to test this once it lands

[codecov]: Add setting swap space

---

docs/content/guides/developer/sui-101/building-ptb.mdx

Move the code statement inside the code block.
---

[docs] move the code statement inside the code block

---

docs/content/guides/operator/formal-snapshot.mdx

This is available on all networks.
👀 
---

[docs] Remove rollout banner for formal snapshots

---

crates/sui-graphql-rpc/src/client/simple_client.rs

Condense duplication between mutation and query client logic
Existing
---

[graphql/rpc] chore: cleanup client

---

docs/content/guides/developer/app-examples/tic-tac-toe.mdx

[Docs] Added Tic Tac Toe docs

---

.github/workflows/external.yml

This test is blocking PRs and we don't have plans to fix the issues yet.
---

remove move prover run in external crate tests

---

.github/workflows/release.yml

Do not use GH token to attache binaries
👀

Do not use GH token to attache binaries

---

.changeset/tidy-cows-approve.md
sdk/bcs/README.md
sdk/bcs/src/bcs.ts
sdk/docs/pages/bcs/index.mdx

[bcs] Depricate the bcs.generic helper

---

Cargo.lock
crates/sui-sdk/Cargo.toml
crates/sui-sdk/examples/sign_tx_guide.rs
docs/content/guides/developer/sui-101/send-txn.mdx
docs/content/guides/developer/sui-101/sign-and-send-txn.mdx
docs/content/guides/developer/sui-101/sign-txn.mdx
docs/content/sidebars/guides.js

wip/placeholder for links, please review for content.
---

doc: add sign-txn page

---

docs/content/concepts/dynamic-fields/transfers/transfer-to-object.mdx
sdk/docs/pages/typescript/transaction-building/basics.mdx

Updates docs to include `Receiving` transaction and function arguments. 
docs only

[docs] Update docs to include building transactions with Receiving arguments in SDKs

---

docs/content/guides/developer/sui-101/sign-and-send-txn.mdx

[docs] Update sign-and-send-txn.mdx

---

docs/content/guides/developer/sui-101/create-nft.mdx
docs/content/guides/developer/sui-101/sponsor-txn.mdx

Add Sponsored Transaction 101 doc.
---
[doc]Add Sponsored Transaction 101 doc

[doc] Add Sponsored Transaction 101 doc

---

crates/sui-sdk/README.md
crates/sui-sdk/examples/sign_tx_guide.rs

New example added #15103 needs some comments processing to comply with a line width of 100 characters. 
---

[sui-sdk] Fix line width in example

---

crates/sui-bridge/Cargo.toml
crates/sui-json-rpc-types/Cargo.toml
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-types/src/base_types.rs

add more compilation conditions for SuiEvent::random_for_testing

---

crates/sui-graphql-rpc/src/types/object.rs

Make it possible to create an `Object` type without a `StoredObject`. This allows us to create objects that have not been indexed.  This will be used when representing a `GenesisTransaction` which stores object contents inline.
This pattern is also applicable for representing `TransactionBlockEffects` that have not been indexed yet.
Existing tests (this PR does not use the code path where an object is created without its indexed counterpart, it only introduces the possibility of that, to be used in a later PR).
```
```
- #15095 
- #15145 
- #15146 
- #15147
- #15179

[GraphQL/Object] Make `StoredObject` optional

---

sdk/typescript/test/e2e/read-transactions.test.ts

[ts-sdk] Fix a flaky test

---

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs

To remove redundant `checkpoint_seq=?checkpoint.sequence_number()` in all the nested debugging logging.
---

Cleanup: use instrument to log checkpoint sequence number in checkpoint execution

---

docs/content/guides/developer/dev-cheat-sheet.mdx

Update dev cheat sheet with zkLogin tips

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_handler.rs

Fixes simtest failures on epoch change.

Continue deduping system tx on end-of-epoch

---

docs/content/guides/operator/node-tools.mdx
docs/content/guides/operator/validator-tasks.mdx
docs/content/references/cli/validator.mdx

Validator topics pulled from readmes.
local
---

[docs] Validator topics

---

docs/content/guides/developer/first-app/client-tssdk.mdx

Fix incorrect fields
Successfully ran code test locally
---

Fix client-tssdk field.mdx

---

crates/sui-analytics-indexer/src/package_store.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_store_pruner.rs
crates/sui-core/src/authority/authority_store_tables.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/db_checkpoint_handler.rs
crates/sui-core/src/epoch/committee_store.rs
crates/sui-faucet/src/faucet/write_ahead_log.rs
crates/sui-storage/src/indexes.rs
crates/sui-storage/src/lib.rs
crates/sui-storage/src/write_path_pending_tx_log.rs
crates/sui-transactional-test-runner/src/simulator_persisted_store.rs
crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks/mod.rs
narwhal/storage/src/node_store.rs

Also make sure every production DB has a name.
CI, private testnet
---

[Sui] label db handle metric with db names

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-json-rpc/src/authority_state.rs

Remove deprecated code

---

docs/content/guides/developer/sui-101/shared-owned.mdx

Fix typo in sentence, remove duplicate "the".

Fix typo in shared-owned.mdx

---

.github/workflows/release.yml

Add `sui-data-ingestion` binary to release process
Testing via my branch

Add `sui-data-ingestion` binary to release process

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/consensus_commit_prologue.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Add a brief description of each transaction block kind based on its description in `sui-types/src/transaction.rs`.
:eyes:
- #15188 
- #15211

[GraphQL/TransactionBlock][EASY] Document TransactionBlockKinds

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/schema/draft_target_schema.graphql
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

I realised I jumped the gun landing #15252 -- I had comments addressed on it, sitting locally.
:eyes:

[GraphQL/Schema] Address Comments from #15252

---

docs/content/concepts/dynamic-fields/tables-bags.mdx
docs/content/concepts/sui-move-concepts/collections.mdx

Collections topic

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Refactor `Epoch` to store the representation object.
Existing tests should suffice, things only got moved around.
---

[GraphQL] Refactor epoch

---

crates/sui-source-validation-service/README.md

Just a minor update to make the README more general (since it can be) and remove outdated info.
N/A
---

move: sui source service doc update [EASY]

---

crates/sui-aws-orchestrator/.gitignore
crates/sui-aws-orchestrator/README.md
crates/sui-aws-orchestrator/assets/settings-template.json
crates/sui-aws-orchestrator/src/main.rs

Improve readme and error messages a bit.
Manually ran the tool.
---

[AWSOrchestrator] a few small cleanups

---

docs/content/guides/developer/getting-started/sui-install.mdx

Including brew tap instructions

---

crates/typed-store/src/rocks/tests.rs

Making the iterator test parameterized so that tests can test both `Rocks::Iter` and `Rocks::SafeIter`.
---

Making iterator tests parameterized so that they can test various Iterator that scans the entire DB

---

docs/content/guides/developer/app-examples.mdx

[docs][easy] Update app examples page

---

crates/sui-core/src/unit_tests/transaction_tests.rs

fix: use intent at default

---

apps/wallet/src/ui/app/components/active-coins-card/CoinItem.tsx
apps/wallet/tailwind.config.ts

- Fix truncate for long texts
https://mysten.atlassian.net/browse/UXR-54
Current 
Fix
---

[Wallet]: update wallet truncate for unrecognized coins

---

docs/site/.gitignore
docs/site/package.json
docs/site/pnpm-lock.yaml
docs/site/src/theme/Footer/Layout/index.js

Adds Amplitude to the site for data tracking.
Local
---

[docs] Amplitude

---

crates/sui-data-ingestion/src/reader.rs
crates/sui-data-ingestion/src/tests.rs
crates/sui-data-ingestion/src/worker_pool.rs

few minor tweaks to data ingestion binary based on a backfill job run + added debug logging

[data ingestion] minor tweaks + logging

---

sdk/wallet-standard/README.md

Noticed this was linking to a dead URL.
---

Fix wallet standard docs URL

---

dapps/kiosk/README.md

fix: update readme

---

crates/sui-tool/src/commands.rs

Use correct endpoints for snapshot downloads

Add right chain endpoints

---

crates/sui-tool/src/commands.rs

CP https://github.com/MystenLabs/sui/commit/78379be28c7a21550561008bf3ee7c4858ac0204
---

Cherry pick add right chain endpoints (#15325)

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_32.snap

cherrypick [PR#15281](https://github.com/MystenLabs/sui/pull/15281) from 1.15 release branch to main

[cherrypick] Delay shipping effects v2 to mainnet

---

docs/content/references/sui-api/beta-graph-ql.mdx

Update the link to examples by pointing to the commit used for release instead of main.
Not needed
---

[graphql][easy] Update link to graphql examples in the docs

---

crates/sui-core/src/authority.rs

Same check is performed 10 lines above.
---

Remove redundant check in handle_transaction

---

Cargo.lock
Cargo.toml
crates/sui-types/Cargo.toml
crates/sui-types/src/transaction.rs
crates/workspace-hack/Cargo.toml

Use NonEmpty in TransactionDataAPI::signers()

---

crates/sui-benchmark/src/lib.rs
crates/sui-core/src/authority_client.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/safe_client.rs
crates/sui-core/src/test_authority_clients.rs
crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-network/build.rs
crates/sui-types/src/messages_grpc.rs

Remove HandleCertificateV1

---

.github/workflows/release.yml

1. Adding logic to skip building if archives already exist.
2. Testing file existence before copying to avoid errors
3. Clean up variables
https://github.com/MystenLabs/sui/actions/runs/7199617823/job/19611841832

Adding logic to skip building if archives already exist

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_adapter.rs

This is a clean up after going through whether it is possible that the lock on ReconfigState can starve/deadlock. Based on what I read, as long as the DB access to update per epoch tables has bounded return time, the locks shouldn't be starve.
The only other lock that may interact with ReconfigState lock is the lock on pending_consensus_certificates. We always acquire ReconfigState lock before acquire pending_consensus_certificates lock.
---

Some clean up around ReconfigState guard

---

crates/sui-core/src/consensus_adapter.rs

Update comment about sending EndOfPublish

---

crates/typed-store/src/rocks/mod.rs

To remove redundant setup in multiple iterator implementations.
---

Create a common function to setup DBMap iterators

---

crates/sui-graphql-rpc/docs/examples.md
crates/sui-graphql-rpc/examples/checkpoint/multiple_selections.graphql
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/transaction_block.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Fixes several typos which prevent the PR docs to pass the CI (#15366).
---

[graphql] Fix typos in docs

---

crates/sui-types/src/transaction.rs

- Combined upgrade/publish checks for clarity
- Reordered max publish checks before checking validity 
- 👀 
---

Reorganized upgrade/publish transaction checks. Reordered max publish checks

---

crates/sui-core/src/unit_tests/transaction_tests.rs

Add test for rejecting system transactions

---

crates/sui-package-resolver/src/lib.rs

Batching together some churn-y clean-ups before adding some more features to the package resolver:
- Ensure types are at the top, then traits, then impls.
- Clean-up some commented out code and unnecessary clones.
- Add a doc comment for the `Resolver` type.o
- Remove an `allow(dead_code)` annotation that is no longer required.
```
```

[Package Resolver][EASY/Chore] Standardise file structure

---

crates/sui-types/src/transaction.rs

- Rewrite type_tag_validity_check to reduce the duplication of the maximum number of type tag check
- For sanity, removed the recursion (should be safe since we are currently checking the depth, but no point playing with fire here) 
- @oxade do we have tests for these? 
---

Rewrite type_tag_validity_check to reduce duplication

---

crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/data/object_basics/sources/object_basics.move
crates/sui-types/src/lib.rs
crates/sui-types/src/transaction.rs

Add tests for object checks 
cargo test
---

fix war-room: tests for object checks

---

external-crates/move/crates/move-analyzer/src/symbols.rs

This PR does three related things:
1. Fixes and extends on-hover functionality for struct fields
Not only on-hover information for fields was very simple (just the type), it was also incorrect in field access chains as the type displayed on-hover was incorrectly obtained from the access chain expression (prefix part). For example, old on-hover looked as follows (not that the type `SomeStruct` rather than `OuterStruct`):
The new on-hover looks as follows, and closely resembles what rust-analyzer is displaying (field name and type but also type of the enclosing struct):
2. Fixes and extends on-hover functionality for local variables (including params)
With locals, only type was being displayed on hover, and this type was not always correct as it was obtained from the use rather than from …

[move-ide] Fixed and extended on-hover for struct fields and locals

---

.github/workflows/release-notes-monitor.yml

Tag the PR author in Slack channel

[Release Notes]: Tag PR author in slack channel

---

crates/sui-source-validation-service/src/lib.rs
crates/sui-source-validation-service/tests/tests.rs

Two small quality-of-life improvements.
Update tests / local testing.
---

move: source service with better logging, restart logic [EASY]

---

crates/sui-core/src/unit_tests/gas_tests.rs
crates/sui-transaction-checks/src/lib.rs

Remove and test a condition that is quadratic in behavior.
The test tests for worst case allowed by current limit.
It turns out there is no difference in time between the old and the new behavior and the removal is more for future piece of mind. 
I am fine even letting this go and leave things as they are
Added tests and measured time of execution
---

Make owner checks simpler

---

Cargo.lock
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/context_data/pg_backend.rs

As discussed, we should not act on exceeding explain-based costs for now, but there would be value in recording data points for now and refining this at a later point in time.
---

[gql] dont error when we exceed costs

---

crates/sui-core/src/db_checkpoint_handler.rs

Otherwise manifest may contain files that seem missing in the snapshot
Existing tests
---

[snapshots] Write manifest file after pruning and compaction

---

examples/move/locked_stake/Move.toml
examples/move/object_bound/Move.toml

- Removed direct link to testnet 
- ran tests 
---

[move][examples] Remove hard testnet dependency

---

.github/CODEOWNERS

Adds new supporting members to codeowners
N/A
---

[graphql/rpc] add Joe, Emma to codeowners

---

.github/actions/diffs/action.yml
Cargo.lock
Cargo.toml
consensus/README.md
consensus/config/Cargo.toml
consensus/config/README.md
consensus/config/src/lib.rs
consensus/config/src/parameters.rs
consensus/config/tests/parameters_test.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/Cargo.toml
consensus/core/src/lib.rs
crates/simulacrum/Cargo.toml
docker/sui-graphql-rpc/Dockerfile
docker/sui-indexer/Dockerfile
docker/sui-services/Dockerfile
docker/sui-source-service/Dockerfile
docker/sui-tools/Dockerfile

Create the `consensus/` directory as discussed.
Also add the initial `Parameters` type.
CI
---

[Consensus] add initial directory structure

---

apps/wallet/src/ui/app/hooks/deepbook/useRecognizedCoins.ts
apps/wallet/src/ui/app/pages/swap/FromAssets.tsx
apps/wallet/src/ui/app/shared/InputWithAction.tsx

https://mysten-labs.slack.com/archives/C0393DWJD7X/p1702938804399499
https://mysten.atlassian.net/browse/APPS-2028
---

[Wallet]: enforce allowed coins list and z index

---

crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-types/src/base_types.rs
crates/sui-types/src/crypto.rs
crates/sui-types/src/multisig.rs
crates/sui-types/src/signature.rs
crates/sui-types/src/transaction.rs
crates/sui-types/src/unit_tests/multisig_tests.rs
crates/sui-types/src/unit_tests/utils.rs
crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs
crates/sui-types/src/zk_login_authenticator.rs
crates/sui/src/keytool.rs
crates/sui/src/zklogin_commands_util.rs

zklogin: always use PublicKey to derive SuiAddress

---

crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models_v2/epoch.rs

title, splitting epoch for more efficient loading.
---

indexer: split epoch into system state and others

---

crates/sui-rosetta/docker/sui-rosetta-local/Dockerfile
docker/sui-node/Dockerfile
narwhal/Docker/Dockerfile

A few `Dockerfile` were not fixed for #15440. 
Test building the images locally, and [running the image build workflow](https://github.com/MystenLabs/sui-operations/actions/runs/7281744148).
---

[Consensus] fix docker builds

---

crates/sui-graphql-rpc/src/client/mod.rs
crates/sui-graphql-rpc/src/client/simple_client.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs

Checks early that variable names are valid
Unit
---

[graphql/rpc] easy: check variables validity in client

---

Cargo.lock
crates/sui-data-ingestion/Cargo.toml
crates/sui-data-ingestion/src/executor.rs
crates/sui-data-ingestion/src/lib.rs
crates/sui-data-ingestion/src/main.rs
crates/sui-data-ingestion/src/metrics.rs
crates/sui-data-ingestion/src/reader.rs
crates/sui-data-ingestion/src/worker_pool.rs
crates/sui-data-ingestion/src/workers/kv_store.rs
crates/sui-data-ingestion/src/workers/mod.rs

migrate key value store uploader to new data ingestion framework

[data ingestion] kv store worker

---

apps/wallet/src/ui/app/hooks/deepbook/useGetEstimate.ts

- add 1 retry for getEstimate
---

[Wallet]: add retry for estimate

---

crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-e2e-tests/tests/call/simple.move
crates/sui-transactional-test-runner/src/args.rs
crates/sui-transactional-test-runner/src/simulator_persisted_store.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Exposes setting reference gas price in init of simulator mode
e2e test
---

[graphql/rpc] expose rgp in testing

---

crates/sui-source-validation-service/config.toml

Added Kai Finance repo for source validation.
Tested locally with curl and it works.
---

source-validation-service: add kai finance to config.toml

---

.changeset/clever-kiwis-tickle.md
pnpm-lock.yaml
sdk/deepbook/README.md
sdk/deepbook/src/client.ts
sdk/deepbook/test/e2e/client.test.ts

This PR fixes a critical parsing issue in the #getCoinType function. It now correctly handles complex coin types, including those with nested type parameters. This issue was affecting the accuracy of certain token types and functionality reliant on this parsing logic
With a testing function

[deepBookClient] Fix complex coin type parsing in #getCoinType function

---

crates/sui-graphql-e2e-tests/tests/packages/functions.exp
crates/sui-graphql-e2e-tests/tests/packages/functions.move
crates/sui-graphql-e2e-tests/tests/packages/modules.exp
crates/sui-graphql-e2e-tests/tests/packages/modules.move
crates/sui-graphql-e2e-tests/tests/transactions/system.exp
crates/sui-graphql-e2e-tests/tests/transactions/system.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-package-resolver/src/lib.rs

Use cursor framework for `MovePackage.modules`.
```
-- modules.move system.move
```
- #15467 
- #15470 
- #15471

[GraphQL/Cursor] MovePackage.modules

---

crates/sui-graphql-e2e-tests/tests/packages/functions.exp
crates/sui-graphql-e2e-tests/tests/packages/functions.move
crates/sui-graphql-e2e-tests/tests/packages/modules.exp
crates/sui-graphql-e2e-tests/tests/packages/modules.move
crates/sui-graphql-e2e-tests/tests/transactions/system.exp
crates/sui-graphql-e2e-tests/tests/transactions/system.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-package-resolver/src/lib.rs

Cursor framework for another field.
This one has less test coverage -- but the schema itself is covered by the unit tests:
```
```
- #15467 
- #15470 
- #15471 
- #15472

[GraphQl/Cursor] AuthenticatorStateUpdate.newActiveJwks

---

crates/sui-graphql-e2e-tests/tests/packages/functions.exp
crates/sui-graphql-e2e-tests/tests/packages/functions.move
crates/sui-graphql-e2e-tests/tests/packages/modules.exp
crates/sui-graphql-e2e-tests/tests/packages/modules.move
crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp
crates/sui-graphql-e2e-tests/tests/transactions/programmable.move
crates/sui-graphql-e2e-tests/tests/transactions/shared.exp
crates/sui-graphql-e2e-tests/tests/transactions/shared.move
crates/sui-graphql-e2e-tests/tests/transactions/system.exp
crates/sui-graphql-e2e-tests/tests/transactions/system.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-package-resolver/src/lib.rs

Using the cursor framework for the `inputs` and `transactions` connections on `ProgrammableTransactionBlock`.
```
-- programmable.move shared.move
```
- #15467 
- #15470 
- #15471 
- #15472 
- #15473

[GraphQL/Cursor] ProgrammableTransactionBlock

---

crates/sui-graphql-e2e-tests/tests/transactions/system.exp
crates/sui-graphql-e2e-tests/tests/transactions/system.move
crates/sui-graphql-rpc/docs/examples.md
crates/sui-graphql-rpc/examples/transaction_block/transaction_block_kind.graphql
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Yet more Cursor framework applications -- obfuscates cursors, standardises handling of max and default page sizes.
```
-- system.move
```
- #15467 
- #15470 
- #15471 
- #15472 
- #15473
- #15474

[GraphQL/Cursor] GenesisTransaction.objects

---

crates/sui-bridge/src/orchestrator.rs

Orchestrator submits action to ActionExecutor.
Unit tests
---
wire up orchestrator and action executor

[bridge 13/n] wire up orchestrator and action executor

---

crates/sui-indexer/src/handlers/checkpoint_handler_v2.rs

temp handle dynamic field creation failure

---

crates/sui-core/src/authority.rs

Temporary patch for testnet inc 1654
---

[patch] - inc 1654

---

crates/sui-sdk/src/wallet_context.rs

[cli] remove redundant with_events in wallet context

---

crates/sui-indexer/src/models_v2/epoch.rs

after https://github.com/MystenLabs/sui/pull/15453, system state on of the latest / current epoch is empty and thus caused deserialization error, this PR fixed that.
local run and curl with getEpochMetrics
```
curl 'http://127.0.0.1:9000' \
-H 'content-type: application/json' \
--data-raw '{"jsonrpc":"2.0","id":6,"method":"suix_getEpochMetrics","params":[null,2,true]}' | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   779  100   700  100    79  64587   7289 --:--:-- --:--:-- --:--:-- 77900
{
"result": {
"data": [
{
"epoch": "1",
"epochTotalTransactions": "0",
"firstCheckpointId": "372",
"epochStartTimestamp": "1704140374063",
"endOfEpochInfo": null
},
{
"epoch": "0", …
```

indexer: epoch metrics fix after split

---

crates/sui-replay/src/replay.rs

This fixes a bug in the replay where if we were to not find a digest in the provided client env, we previously didn't return, and then hit a different error. 
---

display correct error message

---

docs/content/references/cli/client.mdx

Adds example to CLI documentation for transaction replay. I will add a link to this example in the newsletter once this is merged
---

add example for transaction replay to CLI docs

---

sdk/dapp-kit/README.md

Example doesn't work without getFullNodeUrl imported.
---

Add getFullNodeUrl to imports.

---

crates/sui-graphql-e2e-tests/tests/datetime/datetime.exp
crates/sui-graphql-e2e-tests/tests/datetime/datetime.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/date_time.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Add tests to check if `DateTime` returns the right milliseconds granularity.
Added new test for `DateTime`.
---

[graphql] Add DateTime tests 

---

Cargo.lock
consensus/config/Cargo.toml
consensus/config/src/crypto.rs
consensus/core/Cargo.toml
consensus/core/src/block.rs
consensus/core/src/lib.rs

Add skeleton of `Block` type. Additional fields will be added later, e.g. for transactions and byzantine behavior proofs.
CI
---

[Consensus] add Block and related types

---

crates/sui-graphql-e2e-tests/tests/epoch/system_state.exp
crates/sui-graphql-e2e-tests/tests/epoch/system_state.move

Forgot to fix the whitespaces in graphql tests before merging the previous PR.
---

[graphql][easy] Fix whitespaces in test file

---

crates/sui-core/src/transaction_manager.rs

So next time we can know which hot shared obj is triggering overload.
existing tests
---

add logging for obj ids during system overload

---

crates/sui-graphql-rpc/src/context_data/db_data_provider.rs

Refactoring `convert_to_validators` to:
- Avoid using chains and nests of `and_then`s or `map`s (these are hard to follow).
- Avoid cloning the system state multiple times to extract out parts of it.
```
```
- #15467 
- #15470 
- #15471 
- #15472 
- #15473
- #15474 
- #15475 
- #15484 
- #15485
- #15519
- #15520

[GraphQL/Validators][EASY] Clean-up convert_to_validators

---

crates/sui-sdk/README.md
docs/content/references/rust-sdk.mdx
docs/content/references/sui-sdks.mdx

Linking to crate docs and instruction on building locally
Local
---

[docs] Linking to crate docs and instruction on building locally

---

.github/workflows/release-notes-monitor.yml

1. Remove carriage returns from the release notes string
2. Only tagging commit if all jobs were successful
https://github.com/MystenLabs/sui/actions/runs/7415729622

Remove carriage returns from release notes string

---

crates/sui-package-resolver/src/lib.rs

Move the test for type parameter arity mismatch into the first phase of layout calculation (while fetching packages). This helps avoid wasting work if we know the resolution will not succeed, and it also makes the likelihood of exceeding the type parameter width limit exceedingly low in practice, because all parameter widths are checked against the arity of a type that is actually loaded (so it would require the RPC's limit to be set lower than the limit on-chain).
This is a refactor of existing functionality so relies on existing tests:
```
```
- #15393 
- #15407 
- #15408
- #15409 
- #15410
- #15442 
- #15443 
- #15444 
- #15445 
- #15446

[GraphQL/Package Resolver] Early check for type param arity mismatch

---

crates/sui-graphql-rpc/src/types/event.rs

Move the `impl` block after the GraphQL interface, as per-convention, replace
```rust
let Some(serialized_event) = stored_tx
.events
.get(idx)
.ok_or_else(|| {
Error::Internal(format!(
"Could not find event with event_sequence_number {} at transaction {}",
idx, stored_tx.tx_sequence_number
))
})?
.as_ref()
else {
return Err(Error::Internal(format!(
"Unexpected None value for event with event_sequence_number {} at transaction {}",
idx, stored_tx.tx_sequence_number
)));
};
```
with
```rust
let Some(Some(serialized_event)) = stored_tx.events.get(idx) else {
return Err(Error::Internal(format!(
"Could not find event with event_sequence_number {} at transaction {}",
idx, stored_tx.tx_sequence_number
)));
};
```
for readability, and avoid an unnecessary clone (of `native_event.contents`).
``` …
```

[GraphQL/Events][EASY] Event::try_from_stored_transaction clean-ups

---

crates/sui-json-rpc-types/src/balance_changes.rs
crates/sui-json-rpc-types/src/object_changes.rs

Optimize sui CLI response format
---

Optimize sui CLI response format

---

crates/sui-bridge/abi/bridge_vault.json
crates/sui-bridge/abi/sui_bridge.json
examples/move/bridge/Move.toml
examples/move/bridge/sources/bridge.move
examples/move/bridge/sources/btc.move
examples/move/bridge/sources/chain_ids.move
examples/move/bridge/sources/committee.move
examples/move/bridge/sources/eth.move
examples/move/bridge/sources/message.move
examples/move/bridge/sources/message_types.move
examples/move/bridge/sources/treasury.move
examples/move/bridge/sources/usdc.move
examples/move/bridge/sources/usdt.move

This is basically a copy of https://github.com/MystenLabs/sui/pull/15411 which is very hard to integrate with until it's merged into main. At the moment we want more eyes to review it. This PR enables programatic e2e testing.
Code added in this PR will be cleaned up eventually once the aforementioned PR is merged.
---

[Bridge 18/n] add bridge move package as an example

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.17.0 version bump

---

apps/wallet/src/ui/app/hooks/deepbook/useGetEstimate.ts
apps/wallet/src/ui/app/pages/swap/ToAssetSection.tsx
apps/wallet/src/ui/app/pages/swap/index.tsx
apps/wallet/src/ui/app/shared/InputWithAction.tsx

https://mysten.atlassian.net/browse/APPS-2049
---

[Wallet]: Add error message and retry for swap errors

---

crates/sui-analytics-indexer/src/tables.rs
crates/sui-aws-orchestrator/src/protocol/narwhal.rs
crates/sui-sdk/README.md
crates/sui-swarm-config/src/network_config_builder.rs
crates/sui-test-validator/README.md

chore: fix typos

---

crates/sui-keys/src/keystore.rs

Allow the dot character in aliases' names so that someone can associate an address like this: `my.address.sui`
Added test for validating aliases.
---
Relaxed the rule around Sui CLI aliases names. The character `.` is now allowed to be in an alias for the keys in the Sui CLI.

[cli][alias][easy] Allow the dot character in aliases' names

---

crates/sui-core/src/authority.rs
crates/sui-e2e-tests/tests/full_node_tests.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models_v2/transactions.rs
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-json-rpc/src/transaction_execution_api.rs
crates/sui-types/src/event.rs
crates/sui-types/src/inner_temporary_store.rs
crates/sui-types/src/object.rs
crates/sui-types/src/type_resolver.rs
sui-execution/latest/sui-adapter/src/type_layout_resolver.rs
sui-execution/next-vm/sui-adapter/src/type_layout_resolver.rs
sui-execution/v0/sui-adapter/src/type_layout_resolver.rs
sui-execution/v1/sui-adapter/src/type_layout_resolver.rs

cherry picking #15601 
---
---

cherry pick 15601

---

docs/content/concepts/sui-move-concepts.mdx

Fixing a small typo in document sui-move-concepts.mdx.

[docs] fix a small typo in sui-move-concepts.mdx

---

docs/content/guides/developer/advanced.mdx
docs/content/sidebars/guides.js

Removing Advanced Topics placeholder text and changing navigation until more topics available.
---

Advanced Topics fix

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/transaction_manager.rs

These are potential throughput bottleneck spots.
---

Add more tracing sub components for txn execution

---

crates/sui-genesis-builder/src/lib.rs
crates/sui-types/src/digests.rs

CP https://github.com/MystenLabs/sui/commit/0c0a906396d9d4a7c7613045f3f71fdd1ecca895
Existing 
---
---

CP Respect chain override in genesis system object generation (#15632)

---

.changeset/config.json
.changeset/fluffy-turtles-argue.md
pnpm-lock.yaml
sdk/zksend/package.json
sdk/zksend/src/channel/events.ts
sdk/zksend/src/channel/index.ts
sdk/zksend/src/index.ts
sdk/zksend/src/links.ts
sdk/zksend/src/utils/withResolvers.ts
sdk/zksend/src/wallet.ts

Add ZKSend wallet implementation and SDK for creating ZKSend links

---

.changeset/strong-kings-clap.md
dapps/sponsored-transactions/src/utils/sponsorTransaction.ts
sdk/zksend/src/links.ts
sdk/zksend/src/wallet.ts

[zksend] fix import paths

---

.changeset/silly-rabbits-leave.md
sdk/zksend/src/channel/index.ts
sdk/zksend/src/wallet.ts

Allow setting of origin when registering zksend wallet

---

.changeset/ninety-fishes-notice.md
.changeset/popular-pillows-bathe.md
sdk/zksend/src/channel/events.ts
sdk/zksend/src/channel/index.ts
sdk/zksend/src/links.ts

Fix cursor pagination when loading a links owned objects

---

.changeset/fair-parents-glow.md
sdk/zksend/src/channel/index.ts
sdk/zksend/src/links.ts

Add method for claiming assets from zksend link

---

crates/sui-bridge/src/error.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/types.rs

This PR implements get_commmittee
---

[bridge 20/n] implement get committee

---

crates/sui-rest-api/src/client.rs

Properly check and report the status codes when a rest request fails. This will help us better identify the actual root cause of failed calls to the rest api. 
---

rest: properly check and report unsuccessful response status codes

---

.changeset/nasty-turtles-laugh.md
.changeset/serious-rabbits-relax.md
sdk/typescript/src/builder/TransactionBlock.ts
sdk/typescript/src/client/client.ts
sdk/zksend/src/links.ts

Add gas estimation for creating zksend links

---

.changeset/red-terms-talk.md
sdk/zksend/src/channel/events.ts
sdk/zksend/src/channel/index.ts
sdk/zksend/src/wallet.ts
sdk/zksend/tsconfig.json

Tweak zksend bridge types

---

.changeset/serious-lizards-report.md
sdk/zksend/src/links.ts

Handle cases where list of objects to transfer is empty

---

.changeset/orange-geckos-play.md
sdk/zksend/src/links.ts

Detect gasCoin when claiming

---

.changeset/young-ducks-end.md
sdk/zksend/src/links.ts

[sksend] Fix ownedAfterClaim check

---

.changeset/empty-taxis-bathe.md
sdk/zksend/src/channel/index.ts
sdk/zksend/src/links.ts

[zksend] handle spaces in hash

---

.changeset/brown-buttons-accept.md
sdk/zksend/src/links.ts

[zksend] fix how coin balances are merged

---

.changeset/real-penguins-cover.md
pnpm-lock.yaml
pnpm-workspace.yaml
sdk/zksend/src/links.ts

[zksend sdk] Add link redirection to builder

---

.changeset/flat-zebras-agree.md
sdk/zksend/src/links.ts

Fix required link issue

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/error.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/types.rs

implement correct tx construction and replace the dummy one
local e2e testing
---

[bridge 22/n] tx construction

---

Cargo.lock
crates/sui-analytics-indexer/Cargo.toml
crates/sui-analytics-indexer/src/handlers/transaction_handler.rs
crates/sui-archival/Cargo.toml
crates/sui-rest-api/src/node_state_getter.rs

Add a new endpoint which returns full checkpoint in simulacrum. Add one test to test important fields in transaction handler. More tests to follow soon.

Add analytics test for transaction handler using simulacrum

---

.changeset/nice-colts-whisper.md
sdk/docs/pages/_meta.json
sdk/docs/pages/zksend/_meta.json
sdk/docs/pages/zksend/dapp.mdx
sdk/docs/pages/zksend/index.mdx
sdk/docs/pages/zksend/link-builder.mdx
sdk/zksend/src/wallet.ts

Add zkSend SDK Docs

---

docs/content/guides/developer/getting-started/sui-install.mdx

Make the branch from which to install consistent
---

[docs] Make the branch from which to install consistent

---

crates/sui-proxy/src/main.rs

truncate the git string we report
local build
---

[sui-proxy] add abbrev=12 to GIT_REVISION

---

.changeset/perfect-rings-cover.md
.changeset/three-mayflies-melt.md
pnpm-lock.yaml
sdk/dapp-kit/package.json
sdk/dapp-kit/src/components/WalletProvider.tsx
sdk/dapp-kit/src/constants/walletDefaults.ts
sdk/dapp-kit/src/hooks/wallet/useZkSendWallet.ts
sdk/dapp-kit/tsconfig.json
sdk/docs/pages/dapp-kit/_meta.json
sdk/docs/pages/dapp-kit/wallet-provider.mdx
sdk/docs/pages/dapp-kit/zksend.mdx
sdk/docs/pages/zksend/dapp.mdx
sdk/zksend/src/channel/index.ts
sdk/zksend/src/wallet.ts

[zksend] Add zkSend wallet support to dapp kit

---

crates/sui-framework/packages/bridge/sources/bridge.move

[bridge/move] emit nicer event for token transfer

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Fix a lint on docs due to typo.
---

[graphql][easy] Fix lint on docs

---

crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/client/bridge_authority_aggregator.rs
crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/eth_client.rs
crates/sui-bridge/src/main.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/storage.rs
crates/sui-bridge/src/sui_client.rs

This PR wires things up.
Ran manual e2e test locally 
---

[bridge 23/n] wire things up

---

crates/mysten-metrics/src/histogram.rs

HistogramCollector format cleanup

---

crates/sui-bridge/src/eth_client.rs
crates/sui-bridge/src/eth_syncer.rs

[bridge 25/n] paginate eth log queries if range is too big

---

crates/sui-core/src/checkpoints/mod.rs
crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs

I couldn't see any reason to not use the version from EpochStartConfig here

Don't read system object directly

---

crates/sui/src/main.rs

add back info logs to replay

---

Cargo.lock
Cargo.toml
crates/mysten-service-boilerplate/Cargo.toml
crates/mysten-service-boilerplate/src/main.rs

Boilerplate code for new services based on the `mysten-service` crate standards
`cargo run` works as is
---

[mysten-service] 4/n add service boilerplate

---

external-crates/move/crates/move-compiler-transactional-tests/tests/control_flow/unused_named_blocks.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/control_flow/unused_named_blocks.move
external-crates/move/crates/move-compiler/src/cfgir/translate.rs
external-crates/move/crates/move-compiler/src/hlir/ast.rs
external-crates/move/crates/move-compiler/tests/move_2024/cfgir/loops.move
external-crates/move/crates/move-compiler/tests/move_2024/cfgir/named_blocks.move

This fixes a bug for named blocks.
New tests that work 
---

[move-2024] Fix issue with namd block cfg lowering

---

crates/sui-graphql-rpc/src/context_data/db_backend.rs
crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-graphql-rpc/src/context_data/pg_backend.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/sui_address.rs

Ported to new data framework.
Behaviour preserving refactor:
```
```
- #15749 
- #15760 
- #15761 
- #15764
- #15777

[GraphQL/Data] DynamicField point query

---

docs/content/concepts/cryptography/zklogin.mdx

[docs][easy] Update zklogin.mdx

---

crates/sui-bridge/src/events.rs
crates/sui-bridge/src/main.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_syncer.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/types.rs
examples/move/bridge/sources/bridge.move

[Bridge 26/n] emit TokenBridgeEvent event and stitch things e2e for sui -> eth

---

docs/content/concepts/tokenomics/gas-in-sui.mdx

[docs][easy] Update gas-in-sui.mdx

---

docs/content/concepts/cryptography/zklogin.mdx

fix: update providers list

---

docs/content/concepts/sui-move-concepts/collections.mdx

Fix broken links to the framework definitions
---

Fix broken links in collections.mdx

---

docs/content/concepts/transactions/transaction-lifecycle.mdx

I have fixed some typo errors.Please review and merge it. Thanks

fix:typo errors

---

apps/wallet/src/ui/app/pages/swap/GasFeeSection.tsx

[wallet]: Update fees name

---

Cargo.lock
Cargo.toml
crates/sui-analytics-indexer/Cargo.toml
crates/sui-analytics-indexer/src/lib.rs
crates/workspace-hack/Cargo.toml

This is so we can start alerting if certain tables start falling behind
Ran locally and verified it works

Add support to monitor max checkpoint in snowflake tables for monitoring

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.18.0 version bump

---

crates/sui-core/src/authority.rs
crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-json-rpc/src/authority_state.rs
crates/sui-json-rpc/src/transaction_execution_api.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-open-rpc/src/examples.rs

cherrypick #15815 
existing tests.
---
---

cherrypick 15815

---

crates/sui-types/src/effects/effects_v2.rs
external-crates/move/crates/move-vm-runtime/src/loader.rs
external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/loader.rs

Fix a few release build warnings

---

docs/content/references/cli/client.mdx

 added line to replay docs for replay flags

---

.github/workflows/release.yml
.github/workflows/trigger-builds.yml

Trigger tagging sui dockerhub images
I will test this once https://github.com/MystenLabs/sui-operations/pull/3122 lands

Trigger tagging sui dockerhub images

---

apps/wallet/README.md

Updated "Load an unpacked extension" link
N/A code not affected

Update Wallet README.md

---

.github/labeler.yml
.github/workflows/trigger-builds.yml

Fixing client payload params
Need to land this first

Fixing client payload params

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-rpc/Cargo.toml

Changing sui-graphql-rpc version
👀

Changing sui-graphql-rpc version

---

.changeset/chilled-spoons-tan.md
.changeset/polite-buses-relate.md
sdk/typescript/src/builder/TransactionBlock.ts
sdk/zksend/src/channel/index.ts

Fixes #15821. Also attempts to resolve a zkSend SDK issue with windows refusing to open.
---

Tweak SDKs

---

apps/wallet/src/ui/app/hooks/deepbook/useGetEstimate.ts
apps/wallet/src/ui/app/pages/swap/index.tsx

Add sentry tracking for swap coins
https://mysten.atlassian.net/browse/APPS-2077

[wallet]: add sentry tracking for swap coins

---

.github/workflows/trigger-builds.yml

Do not pass the branch name

---

crates/sui-graphql-rpc/src/server/builder.rs

The logger extension needs the `uuid` for the query as well as the `ip address`, otherwise it will crash.
---

[graphql] Fix health check error with telemetry missing uuid and socker addr

---

crates/sui-graphql-rpc/src/server/builder.rs

The logger extension needs the `uuid` for the query as well as the `ip address`, otherwise it will crash. This happens for the `health` endpoint that does not call the `graphql_handler`.
---
Fixed health check error due to the health endpoint not setting the uuid and socket addr.

[graphql] Fix health check error

---

external-crates/move/crates/move-vm-runtime/src/debug.rs

Updates the most used commands to be a single character, and prints the stack when a breakpoint is hit
---

Debugger tool tweaks

---

crates/sui-json-rpc-types/src/sui_object.rs

as title. remove unnecessary clone and duplicated code
CI
---
consolidate impl for SuiObjectResponse object and into_object

consolidate impl for SuiObjectResponse object and into_object

---

crates/sui/src/client_commands.rs
docs/content/concepts/cryptography/transaction-auth/offline-signing.mdx
docs/content/references/cli/client.mdx

Add command to execute the output of --serialized-signed-transaction and improve docs. 
---

fix: add execute command using a combined signed tx

---

docs/content/standards/deepbook/trade-and-swap.mdx

[Deepbook Docs] adding scaling doc

---

crates/sui-indexer/src/processors_v2/objects_snapshot_processor.rs

indexer: use sleep config for obj snapshot

---

examples/move/bridge/sources/chain_ids.move

Add SuiLocalTest and EthLocalTest chain ids
---

add SuiLocalTest and EthLocalTest chain ids

---

docs/content/guides/developer/getting-started/sui-install.mdx

title
title
eyes on preview
---

Update sui-install.mdx to add libpq to dependency

---

chocolatey/sui.nuspec

Adding nuspec file for sui

---

docs/content/guides/developer/getting-started/graphql-rpc.mdx

To reflect recent changes in the schema.
Confirmed that all these queries are accepted by the GraphQL service.

[GraphQL/Docs] Update Getting Started Examples

---

docs/content/guides/developer/getting-started/graphql-rpc.mdx

[docs] add an example for transaction execution to graphql docs

---

docs/content/references/cli/client.mdx

CLI documentation for the gas profiler https://github.com/MystenLabs/sui/pull/15775
---

profiler documentation

---

crates/sui-framework/packages/sui-framework/sources/balance.move
crates/sui-framework/packages/sui-framework/sources/bcs.move
crates/sui-framework/packages/sui-framework/sources/kiosk/transfer_policy.move

Adds some test-only methods for overall convenience in testing.
I am test.

[framework, tests] Adds convenience method for testing

---

docs/content/references/sui-api/rpc-best-practices.mdx

Fix link to jump to correct section. Does not process attributes anymore.
---

[docs][easy] Update rpc-best-practices.mdx

---

docs/content/sidebars/standards.js
docs/content/standards.mdx
docs/content/standards/kiosk-apps.mdx
docs/content/standards/kiosk.mdx

Added kiosk apps page.
sui-core
---

[docs][kiosk apps] Added to nav

---

crates/sui-framework/packages/bridge/sources/bridge.move

[bridge move refactoring] - use borrow mut

---

chocolatey/sui.nuspec

fix chocolatey file paths

---

chocolatey/sui.nuspec

chocolatey: fix verification file path

---

Cargo.lock
crates/sui/Cargo.toml
crates/sui/ptb_tests/1.ptb
crates/sui/src/client_commands.rs
crates/sui/src/ptb/ptb.rs
crates/sui/src/ptb/ptb_parser/argument.rs
crates/sui/src/ptb/ptb_parser/argument_token.rs
crates/sui/src/ptb/ptb_parser/build_ptb.rs
crates/sui/src/ptb/ptb_parser/command_token.rs
crates/sui/src/ptb/ptb_parser/context.rs
crates/sui/src/ptb/ptb_parser/errors.rs
crates/sui/src/ptb/ptb_parser/mod.rs
crates/sui/src/ptb/ptb_parser/parser.rs

Updates to parsing to:
* Have better error messages
* Track command location for where each error is raised so we can better report the command location.
* Not stop at first error we encounter
* Support dotted accesses, `gas`, and spaces between vector and array elements
Added additional tests

Enhance CLI parsing

---

crates/suiop-cli/src/cli/service/init.rs

```
» RUST_LOG=debug cargo r -- s i --path ../my-dumb-service                                         
Compiling suiop-cli v0.1.5 (/Users/jkjensen/mysten/sui/crates/suiop-cli)                                                                    
Finished dev [unoptimized + debuginfo] target(s) in 2.62s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop s i --path ../my-dumb-service`                                                     
2024-01-23T20:39:35.910330Z  INFO suioplib::cli::service::init: creating rust service in ../my-dumb-service                                    
2024-01-23T20:39:35.910729Z DEBUG suioplib::cli::service::init: sui service: true  
```
```
diff --git a/Cargo.toml b/Cargo.toml
index afa17929a1..b194896523 …
```

[mysten-service] 7/n add new service as member of sui workspace

---

docs/content/concepts/cryptography/zklogin.mdx

Simplify process to setup own zkLogin proving service

---

.github/workflows/release.yml

Adding sui binary to chocolatey store
https://github.com/MystenLabs/sui/actions/runs/7644881657/job/20830190190

Adding sui binary to chocolatey store

---

crates/sui-e2e-tests/tests/coin_deny_list_tests.rs

Change test to not fail on new protocol versions

---

docs/content/references/cli.mdx

[docs][easy] Update cli.mdx

---

docs/content/concepts/sui-architecture/sui-security.mdx
docs/content/sidebars/concepts.js

Security doc was ready but waiting for more architecture topics.
👀 
---

[docs] Security architecture

---

crates/sui-proxy/src/consumer.rs

* needless and noisy to have this error log here. it was committed in error.
builds
---

[sui-proxy] remove error log

---

.github/workflows/cargo-llvm-cov.yml
.github/workflows/codecov.yml

Using `cargo-llvm-cov` for code coverage
Going to be testing once this lands

Using `cargo-llvm-cov` for code coverage

---

.changeset/blue-otters-trade.md
sdk/dapp-kit/src/hooks/useSuiClientInfiniteQuery.ts

Fixes infinite queries never flipping back to `hasNextPage: false`, because the next cursor is present even if `hasNextPage` in the response is false.
---

Fix infinite queries

---

apps/explorer/src/utils/api/DefaultRpcClient.ts

Change explorer testnet url

---

crates/sui-cluster-test/src/cluster.rs

Start graphql server with fullnode url in sui-cluster-test

---

crates/sui-source-validation/src/lib.rs

As in title. Follow up of https://github.com/MystenLabs/sui/pull/15731#discussion_r1465458038
Testnet manually locally by changing the required version. It's a bit tricky to add a test that simulates this. Though, maybe we can pass in the url to download through a callback and test that way, the change might just be a little invasive.
---

move toolchain: add testnet binary download fallback

---

crates/sui-replay/src/types.rs

increase replay timeout

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_store.rs
crates/sui-e2e-tests/tests/shared_objects_tests.rs

Unlike the previous attempt to do this (#14635), this time I'm not removing anything from the read side, only removing unused code

Remove deprecated & dead code

---

examples/trading/api/README.md
examples/trading/api/config.ts
examples/trading/api/indexer/escrow-handler.ts
examples/trading/api/indexer/event-indexer.ts
examples/trading/api/indexer/locked-handler.ts
examples/trading/api/package.json
examples/trading/api/server.ts
examples/trading/api/sui-utils.ts
examples/trading/api/tsconfig.json
examples/trading/api/utils/api-queries.ts

Add API to read the data saved from the event indexer.
---

[e2e demo 3/3] API to read data

---

docs/content/guides/developer/sui-101/using-events.mdx

[docs] Add `MoveEventModule` to the event filter docs

---

Cargo.lock
Cargo.toml
crates/sui-core/Cargo.toml
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_validator.rs
crates/sui-core/src/epoch/epoch_metrics.rs
crates/sui-core/src/epoch/mod.rs
crates/sui-core/src/epoch/randomness.rs
crates/sui-e2e-tests/tests/simulator_tests.rs
crates/sui-node/src/lib.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-types/Cargo.toml
crates/sui-types/src/messages_consensus.rs
crates/workspace-hack/Cargo.toml

Adds a `RandomnessManager` to contain state machine for randomness DKG and generation.
Manual testing, added unit tests.

Implement random beacon DKG in sui-core

---

crates/sui-types/src/multisig.rs

fix: log base64 pubkey in error

---

.github/workflows/release.yml

Publish to chocolatey for testnet
👀

Publish to chocolatey for testnet

---

.github/workflows/release.yml

Fix chocolatey workflow

---

.github/workflows/release.yml

Update clauses for testnet builds
👀

Update clauses for testnet builds

---

.changeset/two-olives-enjoy.md

followup to https://github.com/MystenLabs/sui/pull/15415
---

fix: update sui wallet changeset

---

docs/content/concepts/sui-move-concepts/conventions.mdx

It fixes a typo on the import statement of move code example.
---

docs: import typo on the conventions example

---

crates/sui-graphql-e2e-tests/tests/epoch/epoch.exp
crates/sui-graphql-e2e-tests/tests/epoch/epoch.move
crates/sui-graphql-e2e-tests/tests/objects/staked_sui.exp
crates/sui-graphql-e2e-tests/tests/objects/staked_sui.move
crates/sui-graphql-rpc/docs/examples.md
crates/sui-graphql-rpc/examples/checkpoint/multiple_selections.graphql
crates/sui-graphql-rpc/examples/checkpoint/with_timestamp_tx_block_live_objects.graphql
crates/sui-graphql-rpc/examples/checkpoint/with_tx_sent_addr_filter.graphql
crates/sui-graphql-rpc/examples/epoch/specific_epoch.graphql
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/src/types/validator_set.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Implement missing fields from the schema including:
- StakedSui's pool id
- epoch total transactions
- a number of fields in ValidatorSet
- liveObjectDigest to Epoch
Added to existing tests.
---

[GraphQL] implement some missing fields

---

crates/sui-graphql-e2e-tests/tests/consistency/coins.exp
crates/sui-graphql-e2e-tests/tests/consistency/coins.move
crates/sui-graphql-e2e-tests/tests/objects/coin.exp
crates/sui-graphql-rpc/src/types/coin.rs

Implement consistent reads for coins.
consistency/coins.move
---

[gql][consistent-reads][5/n] Implement consistent reads for coins

---

crates/sui-core/src/metrics.rs

Not sure if this is necessary.
---

Remove unused scoped_counter

---

crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-e2e-tests/tests/call/simple.move
crates/sui-graphql-e2e-tests/tests/epoch/epoch.exp
crates/sui-graphql-e2e-tests/tests/epoch/epoch.move
crates/sui-graphql-e2e-tests/tests/objects/staked_sui.exp
crates/sui-graphql-e2e-tests/tests/objects/staked_sui.move
crates/sui-graphql-e2e-tests/tests/validator/validator.exp
crates/sui-graphql-e2e-tests/tests/validator/validator.move
crates/sui-graphql-rpc/docs/examples.md
crates/sui-graphql-rpc/examples/checkpoint/multiple_selections.graphql
crates/sui-graphql-rpc/examples/checkpoint/with_timestamp_tx_block_live_objects.graphql
crates/sui-graphql-rpc/examples/checkpoint/with_tx_sent_addr_filter.graphql
crates/sui-graphql-rpc/examples/epoch/specific_epoch.graphql
crates/sui-graphql-rpc/examples/stake_connection/stake_connection.graphql
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/src/types/validator.rs
crates/sui-graphql-rpc/src/types/validator_set.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

cherrypick 15933 and 15993

---

crates/sui-graphql-rpc/src/extensions/logger.rs
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
crates/sui-graphql-rpc/src/metrics.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs

Cherry pick the missing changes:
- switch back to prometheus metrics
- make query_id and session_id use the display formatter
- updated health check to use 200 OK instead of a DB query
Existing features + manual check of the logs
---

[graphql] Gql cherry pick

---

docs/content/guides/developer/getting-started/graphql-rpc.mdx

There are some queries that will hit our initial performance limits. This PR adapts the ones that can be scaled back and removes the ones that can't so people don't get tripped up on these.
We will add these examples back once we have done the performance work to handle them easily.
Tried the new queries on our production services.
```
sui/docs/site$ pnpm build && pnpm start
```
+ :eyes:

[GraphQL/Docs] Update docs to match capabilities of MVP

---

crates/sui-indexer/src/test_utils.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Spotted some things post land.
```
sui-graphql-e2e-tests$ cargo nextest run --features pg_integration
```

[GraphQL/E2E][EASY] Clean-ups form #15942

---

.changeset/poor-scissors-repeat.md
sdk/enoki/src/EnokiClient/index.ts
sdk/enoki/src/EnokiClient/type.ts

Updates to mirror latest API changes.
---

Enoki SDK updates for API

---

docs/content/references/cli/client.mdx

This should be referring to the active address and not current environment.
---

[docs] Fix wrong heading in Sui CLI reference page

---

external-crates/move/crates/move-analyzer/prettier-plugin/README.md

[move-ide] Prettier Move plugin install instruction fix

---

docs/content/guides/developer/getting-started/get-coins.mdx

Added information on how to get tokens using the Sui CLI.
Just docs, no need, though I did test the commands.
---
Added information on how to get tokens using the Sui CLI.

[docs] Add information on how to get tokens using the Sui CLI

---

crates/sui-distributed-execution/src/exec_worker.rs
crates/sui-distributed-execution/src/seqn_worker.rs
crates/sui-distributed-execution/src/server.rs
crates/sui-distributed-execution/src/types.rs

Making Sure we do not do unnecessary serializations when broadcasting messages

reduce serializations

---

.github/workflows/simulator-nightly.yml

Lookup oncalls from Pager Duty
https://github.com/MystenLabs/sui/actions/runs/7749321350/job/21133642866

Lookup oncalls from Pager Duty

---

.github/workflows/cargo-llvm-cov.yml
scripts/simtest/cargo-simtest

Creating code coverage workflow
https://github.com/MystenLabs/sui/actions/runs/7746320697

Creating code coverage workflow

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.19.0 version bump

---

crates/sui/src/client_commands.rs

add protocol and executor version to replay

---

crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/crypto.rs
crates/sui-bridge/src/server/mod.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/types.rs

[bridge 32/n] add BlocklistCommitteeAction and its encoding

---

sdk/docs/pages/typescript/index.mdx
sdk/docs/theme.config.jsx

[docs][typescript] Include admonition about prod apps and nodes

---

docs/content/guides/developer/app-examples.mdx
docs/content/references/sui-api/rpc-best-practices.mdx
docs/content/snippets/warn-ml-rpcs.mdx

Adds an admonition box that warns about using ML servers for production apps. Includes link to DevPortal curated list.
---

[docs] Adds a more identifiable caution about using ML servers

---

crates/sui/src/ptb/ptb.rs

[cli] Fix relative path file inclusion

---

Cargo.lock
consensus/config/Cargo.toml
consensus/config/src/committee.rs
consensus/config/src/lib.rs
consensus/config/src/test_committee.rs
consensus/config/tests/committee_test.rs
consensus/core/Cargo.toml
consensus/core/build.rs
consensus/core/src/authority_node.rs
consensus/core/src/block.rs
consensus/core/src/context.rs
consensus/core/src/core.rs
consensus/core/src/error.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/stake_aggregator.rs

Set up basic anemo client and server, using unary RPCs.
Unit test
---

[Consensus] add basic RPC client and server

---

sdk/docs/pages/typescript/index.mdx

Updated broken links found in the TS SDK migration page.
---

[docs] Update broken links

---

crates/sui-framework/docs/sui-framework/object.md
crates/sui-framework/packages/sui-framework/sources/object.move

Fixed sui_deny_list_object_id comment

---

docs/content/guides/developer/sui-101/working-with-ptbs.mdx
docs/content/sidebars/guides.js

Landing page for PTB subtopics
👀 
---

[docs] Working with ptb topic

---

.changeset/breezy-ties-juggle.md
sdk/enoki/src/EnokiFlow.ts

[enoki] fix decoding of ephemeral keypair secret

---

.github/workflows/release.yml

see title
@ebmifa lets do it live when releasing testnet next week
---

run brew bump-formula-pr on new testnet releases

---

crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/authority/authority_store_tables.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/passthrough_cache.rs
crates/sui-json-rpc/src/authority_state.rs

The only possible source of error here is a serialization failure of the key, so this almost certainly could not have caused a problem. Still, good to fix.

Thou shalt not convert Err => None

---

sdk/docs/pages/dapp-kit/create-dapp.mdx
sdk/docs/pages/dapp-kit/index.mdx
sdk/docs/pages/dapp-kit/rpc-hooks.mdx
sdk/docs/pages/dapp-kit/sui-client-provider.mdx
sdk/docs/pages/dapp-kit/themes.mdx
sdk/docs/pages/dapp-kit/wallet-components/ConnectModal.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useAccounts.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useAutoConnectWallet.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useConnectWallet.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useCurrentAccount.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useCurrentWallet.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useDisconnectWallet.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useSignAndExecuteTransactionBlock.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useSignPersonalMessage.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useSignTransactionBlock.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useSwitchAccount.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useWallets.mdx
sdk/docs/pages/dapp-kit/wallet-provider.mdx
sdk/docs/pages/dapp-kit/zksend.mdx

[docs] dapp kit updates

---

dapps/multisig-toolkit/src/components/preview-effects/EffectsPreview.tsx
dapps/multisig-toolkit/src/components/preview-effects/PreviewCard.tsx
dapps/multisig-toolkit/src/components/preview-effects/partials/BalanceChanges.tsx
dapps/multisig-toolkit/src/components/preview-effects/partials/Events.tsx
dapps/multisig-toolkit/src/components/preview-effects/partials/ObjectChanges.tsx
dapps/multisig-toolkit/src/components/preview-effects/partials/Overview.tsx
dapps/multisig-toolkit/src/components/preview-effects/partials/Transactions.tsx
dapps/multisig-toolkit/src/components/preview-effects/utils.ts

Address some PR comments from previous merge.
---

[Multi-sig] Code improvements

---

.github/workflows/release.yml

`$ pin-github-action .github/workflows/release.yml`
---

run pin-github-action on release workflow

---

external-crates/move/move-execution/next-vm/crates/move-vm-runtime/src/debug.rs
external-crates/move/move-execution/v0/move-vm/runtime/src/debug.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/debug.rs

Reflects recent changes to the Move debugger into other execution versions. 
Tested it locally

[move-debugger] Reflect updates into older execution versions

---

consensus/core/src/base_committer.rs
consensus/core/src/dag_state.rs
consensus/core/src/lib.rs
consensus/core/src/linearizer.rs
consensus/core/src/universal_committer.rs

The module used to convert a list of committed leaders into the output of consensus which is an ordered list of CommittedSubDags

[consensus] Add linearizer

---

crates/sui-data-ingestion/src/workers/archival.rs

with the current setup once `save_progress` returns true progress watermark will be saved, but because we don't include currently processed checkpoint in the result when we cut, it will result in watermark being off by 1. This fixes it, but resulting files might be slightly over the limit

[data ingestion] fix archival watermark

---

crates/sui/src/ptb/ptb.rs

[cli] Fix missing gas logic

---

crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/types.rs

[bridge 34/n] add AssetPriceUpdate and LimitUpdate action

---

crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/types.rs

[bridge 36/n] add EvmContractUpgradeAction

---

.changeset/proud-spoons-move.md
sdk/zksend/src/links.ts

[zksend] Fix detection of claimable balances for single coin links

---

.changeset/tough-suns-think.md
sdk/zksend/src/links.ts

[zksend] fix listing assets for empty links

---

crates/sui/src/keytool.rs
docs/content/references/cli/keytool.mdx

Rename `sui keytool decode-tx-bytes` to `sui keytool decode-or-verify-tx`. This command now can take an optional signature arg, if provided, decode the tx_data and outputs the verification result for the signature against the tx data. 
test cli output
```
╭────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ tx     │ ╭────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮        │
│        │ │ V1 │ ╭────────────┬────────────────────────────────────────────────────────────── …
```

feat: decode or verify tx command

---

.github/ISSUE_TEMPLATE/doc-bug.md

Update assignee for doc-bug.md

---

docs/content/concepts/sui-architecture/indexer-functions.mdx

[doc] fix typo in concepts/sui-architecture/indexer-functions

---

crates/sui-core/src/quorum_driver/metrics.rs
crates/sui-core/src/quorum_driver/mod.rs

This PR adds a new metric to track transaction settlement finality. This is more accurate because it only tracks the case where a transaction is driven from raw transaction to effects with one try, successfully.
Also use custom buckets and built-in histogram as it's more accurate.
CI.
---

Add settlement finality latency metric

---

crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-framework/packages/bridge/sources/crypto.move
crates/sui-framework/packages/bridge/sources/message.move
crates/sui-framework/packages/bridge/sources/message_types.move

Added BlockList, UpdateBridgeLimit and UpdateAssetPrice messages
---

[native bridge smart contract 5/n] - new message types

---

.changeset/old-owls-hammer.md
sdk/docs/pages/zksend/dapp.mdx
sdk/docs/pages/zksend/index.mdx
sdk/zksend/src/links.ts

[zksend] remove references to preview.zksend.com

---

crates/sui-core/src/quorum_driver/metrics.rs
crates/sui-core/src/quorum_driver/mod.rs

This PR adds a new metric to track transaction settlement finality. This is more accurate because it only tracks the case where a transaction is driven from raw transaction to effects with one try, successfully.
Also use custom buckets and built-in histogram as it's more accurate.
CI
---

[CherryPick 1.18] Add settlement finality latency metric

---

crates/sui/src/ptb/ptb.rs
crates/sui/src/ptb/ptb_builder/argument.rs
crates/sui/src/ptb/ptb_builder/build_ptb.rs
crates/sui/src/ptb/ptb_builder/command_token.rs
crates/sui/src/ptb/ptb_builder/errors.rs
crates/sui/src/ptb/ptb_builder/parse_ptb.rs
crates/sui/src/ptb/ptb_builder/utils.rs
crates/sui/tests/ptb_files/publish/test_pkg/sources/a.move

[cli] fix clippy

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/server/builder.rs

[graphql] Add CORS support

---

crates/sui/src/ptb/display/mod.rs
crates/sui/src/ptb/ptb.rs
crates/sui/src/ptb/ptb_builder/build_ptb.rs
crates/sui/src/ptb/ptb_builder/utils.rs

Remove min, fix disable a clippy lint

---

crates/sui-indexer/migrations_v2/2023-08-19-044023_objects/up.sql

for RPC query perf, see https://mysten-labs.slack.com/archives/C05KSEPP27M/p1707754962186039?thread_ts=1707266303.637119&cid=C05KSEPP27M
- tested on DB in slack msg ^
- CI
---

indexer: add object_id index column

---

docs/content/concepts/cryptography/zklogin.mdx
docs/content/concepts/sui-architecture/epochs.mdx
docs/content/standards/deepbook/design.mdx
docs/content/standards/deepbook/pools.mdx
sui_programmability/examples/crypto/sources/ec_ops.move
sui_programmability/examples/games/sources/drand_based_lottery.move

Found few errors while reading the docs, as well as typos in sui_programmability. Fixed them.
Shouldn't require changelog entry or testing. Have a nice evening!

Proofreading docs &  sui_programmability

---

crates/sui-types/src/error.rs

SuiError::is_retryable cleanup

---

Cargo.lock
crates/mysten-network/Cargo.toml
crates/mysten-network/src/callback/future.rs
crates/mysten-network/src/callback/layer.rs
crates/mysten-network/src/callback/mod.rs
crates/mysten-network/src/callback/service.rs
crates/mysten-network/src/lib.rs
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/metrics.rs
crates/sui-graphql-rpc/src/server/builder.rs

Cherry pick the changes @bmwill did regarding the metrics issue we had when inflight requests were not correctly decremented in some cases.
---

[cherry-pick/graphql] Cherry pick improvements for GraphQL metrics

---

crates/sui-config/src/p2p.rs
crates/sui-e2e-tests/tests/protocol_version_tests.rs
crates/sui-network/src/state_sync/mod.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
crates/sui-swarm/src/memory/swarm.rs
crates/test-cluster/src/lib.rs

Also adds improved debug logging in a few places.

Fix simtest failure due to pruned checkpoints after long sync timeout

---

consensus/config/Cargo.toml
consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/authority_node.rs
consensus/core/src/block.rs
consensus/core/src/context.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs
consensus/core/src/test_dag.rs

Recover Core from storage to make sure that we can make progress from the latest possible quorum.
CI
---

[Consensus 2.0] Core recovery from storage

---

docs/content/guides/developer/sui-101/create-coin.mdx

[docs][easy] Removed devnet only notice

---

crates/sui-analytics-indexer/src/store/bq/schemas/package.sql

Add package version and original package id columns

Update package table schema

---

crates/sui-proxy/src/metrics.rs

* pr14121 removed a handler and replaced it with the mysten_metrics metric handler, but these funcs do not do the same work
* add back our original code and place a comment
tested on a testnet metrics host
---

[sui-proxy/metrics regression] re-add code removed in pr14121

---

crates/sui-source-validation/src/lib.rs

Tabs snuck in D: (I have fixed my editor)
N/A
---

chore [EASY]: untabify source validation code

---

crates/sui-bridge/src/server/handler.rs

[bridge 38/n] add more tests for governance verifier

---

sdk/graphql-transport/src/mappers/util.ts
sdk/graphql-transport/src/methods.ts

Fix flaky test caused by address normalization

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-rpc/Cargo.toml

Sui Graphql RPC version bump `v2024.2.0`
👀

Sui Graphql RPC version bump `v2024.2.0`

---

apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx

- Show stake when no SUI in account.
---

[wallet]: show stake when no coins avail

---

crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/main.rs
crates/sui-bridge/src/node.rs

as title. So that we can start node in memory for testing.
---

[bridge 39/n] move code in main to node.rs

---

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs

[CheckpointExecutor] Make eager scheduling a warning

---

Cargo.lock
consensus/core/Cargo.toml
consensus/core/src/authority_node.rs
consensus/core/src/broadcaster.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/lib.rs
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs

Add `Broadcaster` of created blocks.
Unit test.
---

[Consensus] add `Broadcaster`

---

crates/sui-indexer/src/framework/fetcher.rs
crates/sui-indexer/src/indexer_v2.rs
crates/sui-indexer/src/metrics.rs

- add config for checkpoint download queue size
- add metrics for downloaded checkpoint size in bytes
CI
---

indexer easy: metrics and config for oom experiment

---

crates/sui-data-ingestion/src/workers/kv_store.rs

introduce timeouts for kv workflow

[data ingestion] kv workflow timeout

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/authority_node.rs
consensus/core/src/base_committer.rs
consensus/core/src/block.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/context.rs
consensus/core/src/core_thread.rs
consensus/core/src/error.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/linearizer.rs
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/stake_aggregator.rs
consensus/core/src/storage/mod.rs
consensus/core/src/threshold_clock.rs
consensus/core/src/universal_committer.rs

- Add basic timedrift handling.
- Add a basic unit test with `AuthorityService`.
- Update types visibility.
Unit test.
---

[Consensus] handle blocks with clock drift

---

crates/sui-analytics-indexer/src/handlers/mod.rs
crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
crates/sui-analytics-indexer/src/lib.rs
crates/sui-analytics-indexer/src/tables.rs

This pr introduces a new pipeline to start indexing wrapped structures in sui move. NOTE: This does not deal with dynamic object's account ownership yet. That will be in a different PR
Added some unit tests to validate parsing of sui move values.

[analytics] Add wrapped object and struct pipeline

---

docs/content/guides/developer/getting-started/graphql-rpc.mdx

Based on an explorer feature request to be able to iterate over the elements of a Table or Bag.
:eyes:

[GraphQL/Docs] Add example for iterating overall dynamic fields

---

consensus/config/src/parameters.rs
consensus/core/src/authority_node.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/linearizer.rs
consensus/core/src/metrics.rs
consensus/core/src/universal_committer.rs

- Current committer defaults defined in Parameters is with pipelining enabled and 1 leader per round. Can update as we experiment

[consensus] Integrate commit logic into core

---

docs/content/concepts/transactions.mdx

[docs] Updating link pointing to wrong location

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

93e6b4845a481300ed4a56ab4ac61c5ccb6aa008
👀

Sui `v1.20.0` Version Bump

---

crates/sui-graphql-rpc/src/server/builder.rs

Make some changes to the E2E tests to make them more robust:
- Every test waits for the created checkpoints to be indexed (logic for this is moved into `prep_cluster` so we can't forget it).
- Tests for whether a query succeeded uses `expect` instead of `assert!(... .is_ok())`, so we get some context on why the assertion failed, when it fails.
```
sui-graphql-rpc$ cargo nextest run \
-j 1 --features pg_integration   \
--test e2e-tests
```

[GraphQL/E2E] Make tests more robust

---

crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-e2e-tests/tests/zklogin_tests.rs

fix: increase test timeout

---

.github/workflows/changesets-ci-comment.yml
.github/workflows/labeler.yml

Reverting upgrade of `potiuk/get-workflow-origin` gh action
👀

Reverting upgrade of `potiuk/get-workflow-origin` gh action

---

crates/sui-config/src/genesis.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/tests/staged/sui.yaml
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/sui-e2e-tests/tests/protocol_version_tests.rs
crates/sui-genesis-builder/src/lib.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs
crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
crates/sui-types/src/transaction.rs
sui-execution/latest/sui-adapter/src/execution_engine.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v1/sui-adapter/src/execution_engine.rs

This PR add bridge creation logic to end of epoch transaction
---

[native bridge smart contract 2/n] - Add Bridge object to Sui framework

---

docs/content/standards/kiosk.mdx

Added callout for info on functions available for listing locked assets.
---

[docs] Added info callout

---

crates/sui-graphql-e2e-tests/tests/consistency/balances.move
crates/sui-graphql-e2e-tests/tests/consistency/checkpoints/transaction_blocks.exp
crates/sui-graphql-e2e-tests/tests/consistency/epochs/transaction_blocks.exp
crates/sui-graphql-e2e-tests/tests/consistency/epochs/transaction_blocks.move
crates/sui-graphql-e2e-tests/tests/transactions/programmable.exp
crates/sui-graphql-rpc/docs/examples.md
crates/sui-graphql-rpc/examples/epoch/with_tx_block_connection.graphql
crates/sui-graphql-rpc/examples/epoch/with_tx_block_connection_latest_epoch.graphql
crates/sui-graphql-rpc/src/types/transaction_block.rs

Cherry pick https://github.com/MystenLabs/sui/pull/16332 into release branch.
---

[gql][cherry-pick] tx block query timeouts

---

crates/sui-protocol-config/Cargo.toml
scripts/simtest/config-patch

meta: fix a few breakages from sunsetting workspace-hack

---

crates/sui-analytics-indexer/src/handlers/mod.rs

Cherry pick for PR https://github.com/MystenLabs/sui/pull/16322

Cherry pick the change to fix object status

---

docs/content/references/cli/client.mdx

The report from speedscope does not include MIST. Making assumption that higher percentage equals responsible for more gas?
---

[docs] speedscope reporting fix

---

consensus/config/src/committee.rs
consensus/core/src/authority_node.rs
consensus/core/src/broadcaster.rs
consensus/core/src/core.rs
consensus/core/src/synchronizer.rs

Add an integration test with a committee of authorities, including transaction submission and verification.
Unit test.
---

[Consensus] add a small integration test with a committee of authorities

---

docs/content/guides/developer/app-examples/trading/frontend.mdx
docs/content/guides/developer/app-examples/trading/indexer-api.mdx

[docs] Fix links in the trading example

---

consensus/core/build.rs

consensus: stop constant rebuilding

---

crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/docs/bridge/btc.md
crates/sui-framework/docs/bridge/chain_ids.md
crates/sui-framework/docs/bridge/eth.md
crates/sui-framework/docs/bridge/limiter.md
crates/sui-framework/docs/bridge/treasury.md
crates/sui-framework/docs/bridge/usdc.md
crates/sui-framework/docs/bridge/usdt.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-framework/packages/bridge/sources/btc.move
crates/sui-framework/packages/bridge/sources/chain_ids.move
crates/sui-framework/packages/bridge/sources/eth.move
crates/sui-framework/packages/bridge/sources/limiter.move
crates/sui-framework/packages/bridge/sources/treasury.move
crates/sui-framework/packages/bridge/sources/usdc.move
crates/sui-framework/packages/bridge/sources/usdt.move

[native bridge move] bridge limiter

---

crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/passthrough_cache.rs
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/sui-json-rpc-api/src/bridge.rs
crates/sui-json-rpc-api/src/lib.rs
crates/sui-json-rpc/src/authority_state.rs
crates/sui-json-rpc/src/bridge_api.rs
crates/sui-json-rpc/src/lib.rs
crates/sui-node/src/lib.rs

[bridge 44/n] skeleton for bridge-api

---

docs/content/guides/developer/sui-101/shared-owned.mdx

Added some diagrams that explains the escrow concepts better and fixed broken code sample link
Visual inspection
---

[docs] add diagrams and fix broken links

---

sdk/docs/pages/typescript/cryptography/keypairs.mdx

chore: add keypair doc on bech32

---

crates/sui-node/src/lib.rs

Log reconfiguration error

---

crates/sui-core/src/authority_server.rs

1.  verify_user_input in `submit_certificate`.
2. Remove unnecessary clone.
3. Remove unnecessary spawn in `submit_certificate`.
CI
---

Minor cleanup in authority_server

---

crates/sui-core/src/authority.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/execution_cache/passthrough_cache.rs

As title.
Not quite sure how to test yet.
---

Commit cache post checkpoint execution

---

crates/sui-data-ingestion-core/src/reader.rs

improve usability of hybrid reader (i.e. if local files are present but watermark is lower fallback to remote bucket)

[data ingestion] hybrid reader

---

crates/sui/src/client_ptb/ptb.rs

This PR fixes the help description.
---

[cli] Fix help description

---

docs/content/concepts.mdx

[docs][easy] Fixing link to updated path

---

apps/wallet/src/ui/app/pages/swap/GasFeeSection.tsx
apps/wallet/src/ui/app/pages/swap/index.tsx
apps/wallet/src/ui/app/pages/swap/utils.ts

[wallet]: fix round float err

---

docs/content/sidebars/guides.js
docs/content/sidebars/references.js
docs/site/docusaurus.config.js
docs/site/vercel.json

Don't automatically close sibling categories if you open another category, and default to having some categories opened by default:
- Concepts
- Developer Guides - Getting Started
- References
- Sui RPC
- Sui CLI
- Sui SDKs
- Move
:eyes:

[Docs] Change sidebar defaults

---

docs/content/guides/operator/sui-full-node.mdx

[docs] Added mainnet config

---

Cargo.lock

Updates cargo lock file to work with the new cargo updates.
CI

[cargo] Update lock file

---

external-crates/move/crates/move-core-types/src/annotated_value.rs
external-crates/move/crates/move-core-types/src/unit_tests/value_test.rs

Fixes `MoveValue` display for annotated Move values so that alternate formatting is properly handled.
Printed some move values with alternate formatting and verified the output was prettier.

[move] Fix display implementation for Move values

---

crates/sui-graphql-rpc/src/types/dry_run_result.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs

cherry pick 16248

---

crates/sui-core/src/quorum_driver/metrics.rs
crates/sui-core/src/quorum_driver/mod.rs

Track current number of txns in retry loop in quorum driver

---

docs/content/guides/operator/sui-full-node.mdx

Fix doc format in sui-full-node.mdx .
Change `set to1` to `set to 1`
None of above

[Docs] fix doc format

---

docs/content/guides/operator/sui-full-node.mdx

[docs][easy] Formatting fix

---

external-crates/move/crates/move-cli/tests/build_tests/migration/args.exp
external-crates/move/crates/move-cli/tests/build_tests/migration/args.txt
external-crates/move/crates/move-cli/tests/build_tests/migration/expected_migration.patch
external-crates/move/crates/move-cli/tests/build_tests/migration/migration_tests/test0.move
external-crates/move/crates/move-cli/tests/build_tests/migration/tests/test0.move
external-crates/move/crates/move-package/src/lib.rs

Migration mode now also considers test files by setting test mode
New test, plus testing locally against the sui standard library.
---

[move-2024] Add migration for tests

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_37.snap

Running in devnet for 3 months now, and no issue so far.
---

Turn on consensus fork detection in testnet

---

docs/content/guides/operator/snapshots.mdx

document --skip-indexes flag

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.21.0 version bump

---

crates/sui-core/src/authority/authority_store.rs
crates/sui-node/src/lib.rs
crates/sui-tool/src/lib.rs

[formal snapshots] Do not load genesis objects on restore

---

docs/content/standards/kiosk-apps.mdx

Fixed `Basic app ideas` sample contract to be executable
---
Fix kiosk-apps docs code-example

[docs/kiosk-apps] Fix build error

---

docs/content/references.mdx
docs/content/references/cli/ptb.mdx

Improve the docs by explicitly stating which are the reserved words.
---

[docs/cli-ptb] Explicit mention of reserved words + add CLI PTB to references page

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

Minor nits including renaming variables, cleanup types and remove link overrides.
CI
---

Minor cleanup in acquire_shared_locks_from_effects

---

Cargo.lock
Cargo.toml
crates/sui-bridge/Cargo.toml
crates/sui-bridge/build.rs
crates/sui-json-rpc-tests/tests/rpc_server_tests.rs
deny.toml

as title. We want to use forge to install solidity dependencies without gitmodules. It will also be helpful for bridge e2e tests.
---

introduce forge for bridge solidity code merging and bridge e2e test

---

external-crates/move/crates/move-compiler/tests/move_2024/naming/index_fun_invalid_redefinition.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_fun_invalid_redefinition.move
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_fun_invalid_visibility.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_fun_invalid_visibility.move
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_syntax_methods_invalid_return.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_syntax_methods_invalid_return.move
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_syntax_methods_invalid_subject.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_syntax_methods_invalid_subject.move
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_syntax_methods_mismatched_args.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_syntax_methods_mismatched_args.move
external-crates/move/crates/move-compiler/tests/move_2024/naming/syntax_annotation_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/syntax_annotation_invalid.move

Code coverage tools identified a few cases that were not tested, and now they are.
New tests plus consulting code coverage tool
---

[move-2024][move] more syntax index tests

---

crates/sui-core/src/authority.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-replay/src/data_fetcher.rs
crates/sui-replay/src/replay.rs
crates/sui-snapshot/src/reader.rs
crates/sui-types/src/dynamic_field.rs

Provide more object context in NodeStateDump

---

docs/content/guides/developer/getting-started/connect.mdx
docs/content/snippets/data-wipe.mdx

I noticed that my objects are getting wiped in devnet but couldn't find any information from the doc site. I linked network release page that explains the data wipes
visual inspection
---

[docs] add information about data wipes in devnet

---

crates/suins-indexer/Cargo.toml

Adds a missing dependency feature.
---

[SuiNS indexer] Fix missing dependency feature

---

bridge/evm/deploy_configs/11155111.json

add more supported chains to sepolia

---

apps/explorer/src/components/Layout/PageLayout.tsx

[Explorer]: Updating sunsetting UI

---

Cargo.lock
Cargo.toml
crates/sui-bridge/Cargo.toml
crates/sui-bridge/build.rs
crates/sui-json-rpc-tests/tests/rpc_server_tests.rs
deny.toml

Reverts MystenLabs/sui#16405
This breaks simtest build

Revert "introduce forge for bridge solidity code merging and bridge e2e test"

---

Cargo.lock
crates/sui-core/Cargo.toml
crates/sui-core/src/consensus_validator.rs
crates/sui-node/src/lib.rs
crates/sui-node/src/main.rs
crates/sui-rosetta/src/main.rs
crates/sui-swarm/src/memory/container-sim.rs
crates/sui-swarm/src/memory/container.rs

- Also remove the mysticeti prototype deps
- Additional mode to swap consensus protocols between epochs

[consensus] Add CONSENSUS env var that can be used to set the consensus protocol

---

crates/sui-core/src/authority.rs

Perticularly, we are interested in gas consumption / VM execution latency, and gas consumption / commit certificate latency including writing to DB.
The bucket selection is based on local cluster testing result
---

Add metrics to measure the relationship between computation gas and transaction execution latency

---

apps/wallet/package.json
pnpm-lock.yaml
sdk/enoki/package.json
sdk/zklogin/package.json

To silence the audit warning
---

Upgrade jose version

---

sdk/move-bytecode-template/src/lib.rs
sdk/move-bytecode-template/tests/universal.test.ts

Explicit error on incorrect Identifier passed.
---

[move-bytecode-template] Emit better error on identifier failure

---

docker/grafana-local/dashboards/cluster-status-dashboard.json

Save some changes made during offsite, before it's forgotten in the laptop forever.
This does not affect the rest of the codebase.
---

Local grafana dashboard update

---

docs/content/guides/developer/advanced/custom-indexer.mdx

update existing docs:
* add more examples
* fix diagrams
* add documentation for a helper function to setup a single pipeline workflow

[data ingestion] update docs

---

.github/workflows/mysticeti.yml

Reduce logging noise.
https://github.com/MystenLabs/sui/actions/runs/8242605824/job/22541828303
---

[CI] only show error logs for Mysticeti tests

---

.github/workflows/cargo-llvm-cov.yml
.github/workflows/simulator-nightly.yml

Use PD api to get current oncall
👀

Use PD api to get current oncall

---

sdk/enoki/src/EnokiClient/index.ts
sdk/enoki/src/EnokiClient/type.ts
sdk/zksend/package.json
sdk/zksend/src/index.test.ts
sdk/zksend/src/index.ts
sdk/zksend/src/links.ts
sdk/zksend/src/links/builder.ts
sdk/zksend/src/links/claim.ts
sdk/zksend/src/links/utils.ts
sdk/zksend/src/links/zk-bag.ts
sdk/zksend/src/zk-bag.ts

Implement contract based links for zksend

---

.changeset/great-toes-notice.md
.changeset/rich-rabbits-thank.md

Add changesets for supporting contract based zksend links

---

.changeset/moody-hounds-pretend.md
sdk/zksend/src/index.ts
sdk/zksend/src/links/claim.ts
sdk/zksend/src/links/utils.ts

[zksend] Add isClaimTransaction helper

---

sdk/typescript/test/e2e/multisig.test.ts

This reverts commit e608e9b59151efd3a6c5101db330ecb4280298ed.
---

Revert "fix: add some sleep before zklogin test (#16642)"

---

crates/sui-config/data/fullnode-template-with-path.yaml
crates/sui-config/data/fullnode-template.yaml
docker/fullnode/docker-compose.yaml
docs/content/guides/operator/sui-full-node.mdx

Some information seems a bit outdated.
n/a
---

[Config] update example fullnode template and docker compose config

---

crates/sui-data-ingestion-core/src/lib.rs
crates/sui-data-ingestion-core/src/reader.rs
crates/sui-data-ingestion-core/src/util.rs
crates/sui-data-ingestion/src/workers/archival.rs
crates/sui-data-ingestion/src/workers/blob.rs

* added support for gcp
* abstracted away creation of client from different workloads to common util.rs

[data ingestion] blob worker: support gcp

---

Cargo.lock
Cargo.toml
crates/sui-storage/src/http_key_value_store.rs

hyper-rustls: don't use native-certs

---

docs/content/guides/developer/app-examples/plinko.mdx

Adding repo/deployment link callout and related links.
---

[docs] Added links to source and deployment

---

crates/sui-graphql-rpc/src/types/event.rs
crates/sui-indexer/migrations_v2/2023-08-19-044044_checkpoints/up.sql

1. modify `checkpoints_epoch` to index on (epoch, sequence_number)
2. use `single_value()` for events filtered on tx digest
---

[gql][cherry-pick] performance tuning cherry-picks 1 and 2

---

.github/workflows/simulator-nightly.yml

Fix workflow conclusion msg

---

Cargo.lock
crates/sui-core/Cargo.toml
crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-types/Cargo.toml
crates/sui-types/src/base_types.rs
crates/sui-types/src/crypto.rs
crates/sui-types/src/zk_login_authenticator.rs

zklogin: ensure address-seed is at most 32 bytes long

---

docs/content/concepts/tokenomics/gas-in-sui.mdx
docs/content/guides/developer/advanced/asset-tokenization.mdx
docs/content/guides/developer/app-examples/plinko.mdx
docs/content/guides/developer/first-app/client-tssdk.mdx
docs/content/guides/developer/getting-started/connect.mdx
docs/content/guides/developer/getting-started/get-address.mdx
docs/content/guides/developer/getting-started/local-network.mdx
docs/content/guides/developer/getting-started/sui-environment.mdx
docs/content/guides/developer/sui-101/using-events.mdx
docs/content/guides/operator/sui-full-node.mdx
docs/content/guides/operator/validator-tasks.mdx
docs/content/references/contribute/style-guide.mdx

[docs] Removing Sui Explorer refs

---

apps/explorer/src/components/Layout/PageLayout.tsx
apps/explorer/src/components/footer/footerLinks.tsx

[explorer]: Update footer

---

crates/sui-json-rpc-types/src/sui_transaction.rs

Optimize sui CLI response format
---

[cli] Optimize sui CLI response format

---

crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-e2e-tests/tests/zklogin_tests.rs

Temporarily disable two tests that are timing out

---

.github/workflows/simulator-nightly.yml

simtest: cargo clean before each run
👀

simtest: cargo clean before each run

---

Cargo.lock
Cargo.toml
crates/sui-bridge/Cargo.toml
crates/sui-bridge/build.rs
deny.toml
scripts/simtest/cargo-simtest

This reverts commit 6c085fce5efe5c634b62ab2966a18249a128710a.
---

Revert "Re introduce forge (#16640)"

---

scripts/update_all_snapshots.sh

Add a script that allows you to update all snapshots. This should make life slightly easier.
Run it locally.
---

Add script to update all snapshots

---

consensus/core/src/network/anemo_network.rs
crates/mysten-network/src/multiaddr.rs
crates/sui-aws-orchestrator/src/protocol/sui.rs
crates/sui-swarm-config/src/genesis_config.rs
narwhal/primary/src/primary.rs

The previous implementations of address with zero ip or localhost do not support dns. Adding support for that which seem ok from callsites.
CI
---

[Consensus] support dns addresses

---

crates/sui/src/client_commands.rs

This PR replaces the code in the `format_balance` function, with @amnn's nicer code.
Existing test, manual balance inspection.
---

[cli][easy] Improve code used in format balance function

---

apps/explorer/src/components/footer/footerLinks.tsx

update blog url

---

crates/sui-core/src/overload_monitor.rs

By widening the error margin. Also added debug logging.
Ran 2000 times and all passed.
---

De-flake test_txn_rejection_rate test

---

docs/content/guides/developer/getting-started/sui-install.mdx

[docs] Add Choco Windows installation instruction.

---

docs/content/concepts/cryptography/zklogin.mdx

Update zklogin.mdx with recommended machine specs

---

.changeset/big-colts-help.md
.changeset/orange-rabbits-complain.md
.changeset/short-deers-ring.md
.changeset/strong-worms-teach.md
sdk/docs/pages/zksend/link-builder.mdx
sdk/zksend/src/index.test.ts
sdk/zksend/src/index.ts
sdk/zksend/src/links/builder.ts
sdk/zksend/src/links/claim.ts
sdk/zksend/src/links/list-created-links.ts
sdk/zksend/src/links/utils.ts

[zksend] add support for bulk link creation, and simplified claim APIs

---

.changeset/big-colts-help.md
.changeset/many-ghosts-confess.md
.changeset/orange-rabbits-complain.md
.changeset/short-deers-ring.md
.changeset/strong-worms-teach.md
sdk/docs/pages/zksend/link-builder.mdx
sdk/zksend/src/index.test.ts
sdk/zksend/src/index.ts
sdk/zksend/src/links/builder.ts
sdk/zksend/src/links/claim.ts
sdk/zksend/src/links/list-created-links.ts
sdk/zksend/src/links/utils.ts
sdk/zksend/src/links/zk-bag.ts

[zksend] Use mainnet contract by default for new links

---

apps/wallet/src/ui/app/components/navigation/index.tsx
apps/wallet/tests/balanceChanges.spec.ts
apps/wallet/tests/onboarding.spec.ts

[wallet-ext] - update home tab name

---

crates/sui-framework/docs/bridge/dependencies/sui-system/sui_system.md
crates/sui-framework/docs/bridge/dependencies/sui-system/sui_system_state_inner.md
crates/sui-framework/docs/sui-system/sui_system.md
crates/sui-framework/docs/sui-system/sui_system_state_inner.md
crates/sui-framework/packages/sui-system/sources/sui_system.move
crates/sui-framework/packages/sui-system/sources/sui_system_state_inner.move

[native bridge move] - revert unused sui sys changes

---

external-crates/move/documentation/book/src/structs.md

Update Move book docs with positional structs and post-fix ability decls.

[move-2024] Add positional struct fields and different ability decls

---

bridge/evm/script/deploy_bridge.s.sol
bridge/evm/test/BridgeBaseTest.t.sol
bridge/evm/test/BridgeCommitteeTest.t.sol
bridge/evm/test/BridgeLimiterTest.t.sol
bridge/evm/test/BridgeMessageTest.t.sol
bridge/evm/test/CommitteeUpgradeableTest.t.sol
bridge/evm/test/SuiBridgeTest.t.sol
bridge/evm/test/mocks/MockTokens.sol

Add signature regression tests for governance actions.
---

[bridge][solidity] add sig regression tests for governance actionss

---

.github/workflows/simulator-nightly-mysticeti.yml

This will run after simtest nightly and will not notify so it will need to be checked manually for now

[consensus] Add simtest nightly workflow for mysticeti

---

external-crates/move/crates/move-compiler/tests/move_2024/naming/use_fun_shadows.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/by_value_method.move
external-crates/move/documentation/book/src/SUMMARY.md
external-crates/move/documentation/book/src/functions.md
external-crates/move/documentation/book/src/method-syntax.md
external-crates/move/documentation/book/src/uses.md

Book chapter for methods
- 👓 
---

[move 2024] Method syntax docs

---

apps/wallet/src/shared/constants.ts
sdk/docs/vercel.json

[apps] Updating link

---

external-crates/move/crates/move-compiler/src/sui_mode/linters/public_random.rs
external-crates/move/crates/move-compiler/tests/sui_mode/linter/public_random_invalid.exp
external-crates/move/crates/move-compiler/tests/sui_mode/linter/public_random_invalid.move
external-crates/move/crates/move-compiler/tests/sui_mode/linter/public_random_valid.move

Process all problematic arguments instead of aborting after the first one.
Existing tests + new ones
---

public_random linter: process all problematic arguments

---

consensus/core/src/block_manager.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/metrics.rs

[Consensus 2.0] adding additional metrics

---

consensus/core/src/core.rs
consensus/core/src/metrics.rs
consensus/core/src/universal_committer.rs

[Consensus] small cleanup in metrics

---

docs/content/guides/operator/validator-config.mdx

[docs][easy] Typo fix

---

crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-e2e-tests/tests/zklogin_tests.rs

fix: wait for auth state before protocol version

---

docs/content/guides/developer/advanced/move-2024-migration.mdx
docs/content/sidebars/guides.js

- One pager migration guide 
- 👀 
---

[docs] Move 2024 migration guide

---

docs/content/references/sui-sdks.mdx
docs/content/sidebars/references.js

adding links to go and python sdks
visual inspection + manual test
---

[docs] add go and python sdk links

---

Cargo.lock
Cargo.toml
crates/mysten-network/src/server.rs

Upgrade tonic and prost

---

crates/sui-protocol-config/src/lib.rs

[nit] Better protocol config panic error

---

external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/typing/num_infer.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/num_infer.move

Fixes a small bug in subtyping
Added a new test, plus everythong else still works
---

[move] Fix subtyping bug in typing

---

apps/wallet/src/background/accounts/zklogin/ZkLoginAccount.ts
apps/wallet/src/background/accounts/zklogin/utils.ts

use prod prover api only in mainnet & testnet

---

crates/sui-indexer/src/apis/extended_api.rs
crates/sui-json-rpc-api/src/extended.rs
crates/sui-json-rpc-types/src/sui_extended.rs

title, these endpoints were added solely for explorer, thus can be removed too.
CI
---

explorer cleanup: JSON RPC methods and types

---

narwhal/worker/src/transactions_server.rs

Currently when Narwhal shuts down, the narwhal clients in the static `LOCAL_NARWHAL_CLIENTS` map are not cleared. Also, Narwhal clients are set asynchronously after Narwhal starts. In a new epoch if Sui consensus adapter tries to send transactions before new Narwhal clients are set, errors will be returned because the left over Narwhal clients are no longer connected to Narwhal.
This change moves setting Narwhal client to be earlier, at the time when Narwhal starts. Clearing Narwhal client on shutdown is not added because it should be unnecessary.
In Consensus 2.0, there will no longer be any static variable involved in Sui->Consensus submissions so this code path will become cleaner.
Using 10s epoch duration:
`MSIM_TEST_NUM=20 RUST_LOG=error cargo simtest --test protocol_version_tests …

Create LocalNarwhalClient synchronously when Narwhal starts

---

Cargo.lock
crates/sui-archival/Cargo.toml
crates/sui-archival/src/lib.rs
crates/sui-tool/src/commands.rs

```cargo run --bin sui-tool -- print-archive-manifest file --directory /tmp/local```

Add tools to print and update archive manifest

---

crates/sui-config/src/node.rs
crates/sui-node/src/lib.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

json-rpc: add option to only allow websocket traffic

---

apps/wallet/src/shared/deepBook/context.tsx

https://mysten-labs.slack.com/archives/C0578KFD9D2/p1711405396467869
Changed filter since MatchAll is no longer supported

change to matchAny for wallet

---

crates/sui-data-ingestion-core/src/reader.rs

current implementation(without this change) works, but leads to very noisy logs and overfetching(because fetching actor gets recreacted on any error) when tailing the most recent state of the blockchain

[data ingestion] retry 404s by default for remote fetcher

---

sdk/docs/pages/dapp-kit/wallet-hooks/useCurrentWallet.mdx

:speech_balloon: fix: typo on connectionStatus state

---

external-crates/move/documentation/book/src/unit-testing.md

Updates docs for unit testing in Move for Move 2024.

[move-2024] Update unit testing doc

---

crates/sui-e2e-tests/tests/bridge_tests.rs
crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/base/sources/sui_system.move
crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/deep_upgrade/sources/sui_system.move
crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/safe_mode/sources/sui_system.move
crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/shallow_upgrade/sources/sui_system.move
crates/sui-e2e-tests/tests/protocol_version_tests.rs
crates/sui-genesis-builder/src/lib.rs
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_43.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_43.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_43.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
crates/sui-types/src/bridge.rs
crates/sui-types/src/transaction.rs

[native bridge] - bridge feature branch snapshot test fix

---

crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/docs/bridge/btc.md
crates/sui-framework/docs/bridge/chain_ids.md
crates/sui-framework/docs/bridge/committee.md
crates/sui-framework/docs/bridge/crypto.md
crates/sui-framework/docs/bridge/eth.md
crates/sui-framework/docs/bridge/limiter.md
crates/sui-framework/docs/bridge/message.md
crates/sui-framework/docs/bridge/message_types.md
crates/sui-framework/docs/bridge/treasury.md
crates/sui-framework/docs/bridge/usdc.md
crates/sui-framework/docs/bridge/usdt.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-framework/packages/bridge/sources/btc.move
crates/sui-framework/packages/bridge/sources/chain_ids.move
crates/sui-framework/packages/bridge/sources/committee.move
crates/sui-framework/packages/bridge/sources/crypto.move
crates/sui-framework/packages/bridge/sources/eth.move
crates/sui-framework/packages/bridge/sources/limiter.move
crates/sui-framework/packages/bridge/sources/message.move
crates/sui-framework/packages/bridge/sources/message_types.move
crates/sui-framework/packages/bridge/sources/treasury.move
crates/sui-framework/packages/bridge/sources/usdc.move
crates/sui-framework/packages/bridge/sources/usdt.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

[bridge] Bridge 2024

---

docs/content/guides/developer/cryptography/groth16.mdx

Update groth16.mdx 

---

Cargo.lock
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-bridge/src/types.rs
crates/sui-e2e-tests/Cargo.toml
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/sui-types/src/bridge.rs

[bridge 50/n] use right threshold for different action types

---

crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/test_utils.rs

[bridge 51/n] support build sui transaction for emergency op action

---

Cargo.lock
Cargo.toml
crates/sui-core/src/generate_format.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-types/src/base_types.rs
crates/sui-types/src/crypto.rs
crates/sui-types/src/unit_tests/multisig_tests.rs
crates/sui-types/src/unit_tests/utils.rs
crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs

updates to include: https://github.com/MystenLabs/fastcrypto/pull/751
---

fix: update strong type

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

This adds Apple as a provider in node config - once its pulling for 
---

feat: enable apple as zklogin provider

---

crates/sui-bridge/src/sui_transaction_builder.rs

[bridge 54/n] support build sui transaction for price update action

---

docs/content/guides/developer/advanced/move-2024-migration.mdx

- Added a section about alpha/beta guidance 
- :eyes: 
---

Added alpha/beta guidance

---

crates/sui-bridge/src/client/bridge_authority_aggregator.rs
crates/sui-bridge/src/crypto.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/tools/cli.rs
crates/sui-bridge/src/tools/mod.rs
crates/sui-bridge/src/types.rs
crates/sui-types/src/crypto.rs

as title. Governance Command collects signatures and execute on chain transactions.
---

[bridge 59/n] add bridge governance command to faciliate governance actions

---

crates/sui-bridge/src/config.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/tools/cli.rs
crates/sui-bridge/src/tools/mod.rs
crates/sui-types/src/bridge.rs
crates/sui/src/sui_commands.rs

[bridge 61/n] polish governance client commands 

---

docs/content/references.mdx

Update link from landing to sui framework
👀 
---

[docs][easy] Updated link on landing page

---

crates/sui-bridge/src/config.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/sui_syncer.rs
crates/sui-bridge/src/utils.rs

[bridge/63] remove unnecessary fields in bridge config

---

Cargo.lock

revert a package version bump

---

bridge/evm/deploy_configs/31337.json
bridge/evm/foundry.toml
bridge/evm/script/deploy_bridge.s.sol
crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/mod.rs
crates/sui-bridge/src/eth_client.rs
crates/sui-bridge/src/eth_transaction_builder.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/sui_syncer.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/tools/cli.rs
crates/sui-bridge/src/tools/mod.rs
crates/sui-bridge/src/utils.rs
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/test-cluster/src/lib.rs

[bridge 64/n] the first integration test

---

.changeset/loud-mangos-wonder.md
pnpm-lock.yaml
sdk/typescript/package.json
sdk/typescript/src/graphql/schemas/2024-01/index.ts

[ts-sdk] Update gql.tada and add type definitions for custom scalars

---

.github/actions/diffs/action.yml
.github/workflows/rust.yml

[bridge] enable some tests for sol changes

---

crates/sui-core/src/authority/shared_object_version_manager.rs

Add tests for assign_versions_from_effects

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.23.0 version bump

---

crates/sui-snapshot/src/uploader.rs

There has been multiple ocasions of snapshot uploads failing for various reasons. Without metrics this takes us a while to notice and then fix. This PR will add a metric for errors on uploading where we can alert on error rate increases.
`cargo test .` to ensure it builds. Please make further suggestions on testing metrics.
---

[sui-snapshot] Add metric for snapshot upload errors

---

bridge/evm/contracts/BridgeConfig.sol
bridge/evm/contracts/interfaces/IBridgeConfig.sol
bridge/evm/script/deploy_bridge.s.sol
bridge/evm/test/BridgeBaseTest.t.sol
bridge/evm/test/BridgeLimiterTest.t.sol
bridge/evm/test/SuiBridgeTest.t.sol

Change the token price type stored in the BridgeConfig contract from uint256 to uint64 as discussed with @longbowlu

token price uint256 => uint64

---

crates/sui-core/src/quorum_driver/mod.rs

Update transaction_retry_count only when a transaction is retried

---

crates/sui-types/src/digests.rs
crates/sui-types/tests/digests_tests.rs

See title
Added new tests. Will wait for CI
---

Add new tests for digests

---

crates/sui-tool/src/commands.rs

Cherry pick https://github.com/MystenLabs/sui/pull/16979

unblock sui-tool download-db-snapshot

---

crates/sui-indexer/src/framework/fetcher.rs

cherry pick #16983 into 1.22 as it's a fix of production incident
CI
---

indexer fetcher: configurable fetch interval

---

crates/sui-surfer/src/surfer_task.rs

Minor improvements to sui-surfer

---

.github/workflows/rust.yml

[CI] add back required no-op jobs

---

.changeset/lazy-files-bathe.md
sdk/typescript/src/client/http-transport.ts
sdk/typescript/src/graphql/client.ts

[ts sdk] Fix fetch being incorrectly bound to GraphQL client

---

crates/sui-types/src/object/bounded_visitor.rs

Bumps bound to handle genesis objects. 
Manually verified the change worked.
---

[simple] bump bound 

---

.changeset/giant-eyes-juggle.md
sdk/zksend/src/links/builder.ts

[zksend] Make contract optional in ZkSendLinkBuilder.createLinks

---

crates/sui-types/src/object/bounded_visitor.rs

Bumps the bounds up a bit higher
Manually tested

[simple] Bump bounds

---

docs/content/guides/developer/getting-started/local-network.mdx

Removing instructions for local wallet install. A subsequent PR might put them back in a different location.
---

[docs] Removing wallet local install instructions

---

docs/content/guides/developer/getting-started/sui-environment.mdx

This PR updates move-analyzer installation instructions.
Made sure that the updated command does what it's supposed to

[move-ide] Updated move-analyzer installation instructions

---

crates/sui-indexer/src/framework/fetcher.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

add lag metrics from checkpoint to 
- checkpoint download
- checkpoint indexing
- checkpoint DB commit
CI
---

indexer: add lag metrics for each step

---

sdk/graphql-transport/src/generated/queries.ts
sdk/graphql-transport/src/mappers/transaction-block.ts
sdk/graphql-transport/src/methods.ts
sdk/graphql-transport/src/queries/devInspectTransactionBlock.graphql
sdk/graphql-transport/src/queries/dryRunTransactionBlock.graphql
sdk/graphql-transport/src/queries/executeTransactionBlock.graphql
sdk/graphql-transport/src/queries/getCurrentEpoch.graphql
sdk/graphql-transport/src/queries/getLatestSuiSystemState.graphql
sdk/graphql-transport/src/queries/stakes.graphql
sdk/graphql-transport/src/queries/transactions.graphql
sdk/graphql-transport/test/compatability.test.ts
sdk/typescript/src/bcs/bcs.ts
sdk/typescript/src/bcs/effects.ts
sdk/typescript/src/bcs/index.ts
sdk/typescript/src/bcs/types.ts
sdk/typescript/src/client/types/generated.ts
sdk/typescript/src/client/types/params.ts

[TS SDK] Add BCS types for effects

---

docs/content/guides/developer/advanced/randomness-onchain.mdx
docs/content/sidebars/guides.js

Adds an on-chain randomness doc.
---

[docs] Randomness content

---

docs/content/concepts/cryptography/zklogin.mdx

[zkLogin] Replace prover endpoint with a link to Enoki

---

Cargo.lock
crates/data-transform/src/main.rs
crates/sui-analytics-indexer/src/handlers/mod.rs
crates/sui-core/src/unit_tests/subscription_handler_tests.rs
crates/sui-graphql-rpc/src/types/move_value.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-indexer/src/models/events.rs
crates/sui-json/src/lib.rs
crates/sui-replay/src/displays/transaction_displays.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
crates/sui-types/src/event.rs
crates/sui-types/src/object.rs
crates/sui-types/src/object/balance_traversal.rs
crates/sui-types/src/object/bounded_visitor.rs
external-crates/move/Cargo.lock
external-crates/move/Cargo.toml
external-crates/move/crates/move-core-types/Cargo.toml
external-crates/move/crates/move-core-types/src/annotated_value.rs
external-crates/move/crates/move-core-types/src/annotated_visitor.rs
external-crates/move/crates/move-core-types/src/lib.rs
external-crates/move/crates/move-core-types/src/unit_tests/mod.rs
external-crates/move/crates/move-core-types/src/unit_tests/visitor_test.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v0/sui-move-natives/src/test_scenario.rs
sui-execution/v1/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v1/sui-move-natives/src/test_scenario.rs
sui-execution/v2/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v2/sui-move-natives/src/test_scenario.rs

Cherry pick of the value visitor change
CI + manually tested

Value visitor

---

external-crates/move/crates/move-analyzer/editors/code/src/main.ts

[move-ide] TypeScript compilation problem fix

---

docs/content/guides/developer/advanced/move-2024-migration.mdx

- Added a section to the migration guide for IDE support 
- 👁️ 
---

[move 2024 migration guide] Mention rebuilding IDE

---

external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package.json

Updated README to add information about building/testing projects and an additional troubleshooting tip.

[move-ide] Updated README

---

crates/sui-tool/src/commands.rs

Also removes the default `/tmp` write path as I think it's confusing for a user who runs the command and isn't sure where files are being written to. 
```
$ target/debug/sui-tool download-db-snapshot --epoch 356 --network mainnet --path=/tmp                                                                                                                                           
thread 'main' panicked at /Users/johnmartin/src/github.com/johnjmartin/sui/crates/sui-tool/src/commands.rs:833:26:
You must set either --snapshot-bucket-type or --no-sign-request
$ target/debug/sui-tool download-db-snapshot --epoch 341 --network mainnet --path=/tmp --no-sign-request --snapshot-bucket-type=gcs                                                                                              
error: the …
```

use clap arg groups to reduce confusion about sui-tool usage

---

external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package.json

Updated README with Sui installation instructions, added the "Mysten" keyword, and updated extension keyword search instructions.

[move-ide] Updated README with Sui installation instructions

---

.changeset/slimy-suits-prove.md
sdk/enoki/src/EnokiFlow.ts

Missed this in a few more places
---

Add missing network param

---

docs/content/guides/developer/advanced/move-2024-migration.mdx

Updated Move 2024 migration guide to include the new IDE info

[docs] Updated Move 2024 migration guide to include the new IDE info

---

Cargo.lock

fix cargo deny

---

crates/sui-framework/packages/bridge/sources/chain_ids.move
crates/sui-framework/packages/bridge/sources/committee.move
crates/sui-framework/packages/bridge/sources/limiter.move

Added the easy tests to have 100% test coverage on most modules.
The difficult modules are coming next ;)
This is tests only and the code coverage tool shows 100% on the changes modules
---

Unit tests and test coverage

---

docs/content/guides/developer/cryptography/groth16.mdx

Fix public inputs encoding in groth16.mdx

---

crates/sui-source-validation-service/README.md

Doc update. Context: https://mysten-labs.slack.com/archives/C06S3CR1DPS/p1711534695421979
N/A
---

source service: hosted service usage README

---

external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/editors/code/src/configuration.ts
external-crates/move/crates/move-analyzer/editors/code/src/context.ts
external-crates/move/crates/move-analyzer/src/bin/move-analyzer.rs

This PR updates linting level option to reflect recently introduced three different linting levels.
Manually checked that the option is recognized correctly.

[move-ide] Update to the linting level option

---

docs/content/guides/developer/advanced/randomness-onchain.mdx

Publish the documentation of the beacon

---

.github/workflows/release.yml

* Fix tar ball structure
* Simplify the code
https://github.com/MystenLabs/sui/actions/runs/8637810185

Fix tar ball structure

---

crates/sui-bridge/Cargo.toml

Fix toml file to build both from root and from `crates/sui-bridge`
Built in both directory
---

Fix `crates/sui-bridge` build

---

Cargo.lock
crates/sui-security-watchdog/Cargo.toml
crates/sui-security-watchdog/src/main.rs
crates/sui-security-watchdog/src/metrics.rs
crates/sui-security-watchdog/src/query_runner.rs
crates/sui-security-watchdog/src/scheduler.rs

Add ability to parse i128 type arrays from snowflake returned as arrow arrays. Also fix a small issue with metric handling
Running locally works

Small fixes to handle large numbers in watchdog service

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.24.0 version bump

---

Cargo.lock
Cargo.toml
crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

chore: add test issuer to devnet

---

docker/sui-indexer/Dockerfile

* add jemalloc to docker build image
tsia
---

[docker/indexer] add jemalloc

---

sdk/graphql-transport/test/compatability.test.ts
sdk/typescript/test/e2e/data/dynamic_fields/Move.lock

cherry pick  #17014 to relax graphql test 

---

docker/sui-indexer/Dockerfile

[dockerfile/sui-indexer] remove profile arg

---

docker/sui-indexer/Dockerfile

* adjust the arg so it can be passed in
p up
---

[indexer/dockerfile] adjust arg

---

docker/stress/entrypoint.sh

poll fullnode for availability before starting stress

---

crates/sui-single-node-benchmark/move_package/sources/benchmark.move
crates/sui-single-node-benchmark/src/command.rs
crates/sui-single-node-benchmark/src/tx_generator/move_tx_generator.rs
crates/sui-single-node-benchmark/src/workload.rs
crates/sui-single-node-benchmark/tests/smoke_tests.rs
crates/sui-types/src/programmable_transaction_builder.rs

New workload for minting NFT's with a given object size and batch size.
Adding minting to smoke test + variety of manual tests

[bench] single node benchmark for NFT minting

---

.eslintrc.js
crates/sui-framework/docs/deepbook/critbit.md
crates/sui-framework/packages/deepbook/sources/critbit.move
crates/sui-json-rpc/src/indexer_api.rs
sdk/bcs/README.md
sdk/docs/.prettierignore
sdk/docs/pages/bcs/index.mdx

remove repetitive words
No need
---

chore: remove repetitive words

---

docker/sui-indexer/Dockerfile

Revert "[indexer/dockerfile] adjust arg"

---

crates/sui-indexer/src/indexer_reader.rs

event and txn query should be done in blocking tasks instead.
tnt release tests
---

cherry-pick: indexer reader: event and txn query in blocking tasks

---

dapps/multisig-toolkit/src/routes/combine-sigs.tsx

UX gets better & we also have re-usable links, so we don't have to redo the setup every time from scratch. Ordering is preserved.
👀 
---

[Multisig toolkit] Better combine signatures UX

---

dapps/multisig-toolkit/src/components/header.tsx
dapps/multisig-toolkit/src/components/menu.tsx
dapps/multisig-toolkit/src/routes/execute-transaction.tsx
dapps/multisig-toolkit/src/routes/multisig-address.tsx
dapps/multisig-toolkit/src/routes/offline-signer.tsx

Adds a Mobile menu for tablet-down sizes to avoid the ugly header problem.
(Not an overly though implementation, simple one).
Also makes the "create multisig address" UX a bit better (errors & spacing).
👀 
---

[Multisig Toolkit] Add mobile menu, improve create address UX.

---

crates/sui-e2e-tests/tests/coin_deny_list_tests.rs
crates/test-cluster/src/lib.rs

Since we have passed protocol version 35 everywhere now, and the deny list should have been initiated.
---

Remove test_coin_deny_list_creation test

---

scripts/simtest/config-patch

- No idea what I'm doing, but the patch applies cleanly now
- The patch applies 
---

[cleanup] fix config-patch

---

crates/sui-indexer/src/indexer_reader.rs

the bug was introduced in the pkg upgrade pr and this pr is to fix that. 
we will want to add a test for this in CI too.
test run in 
https://github.com/MystenLabs/sui-operations/actions/runs/8698757835
---

indexer reader: event and txn query in blocking tasks

---

crates/sui-framework/packages/sui-framework/sources/display.move

fix display unit test move 2024 style

[Unit Test] fix display unit test move 2024 style

---

sdk/typescript/src/transactions/ObjectCache.ts
sdk/typescript/src/transactions/TransactionBlockDataResolver.ts
sdk/typescript/src/transactions/index.ts
sdk/typescript/test/e2e/object-cache.test.ts
sdk/zksend/src/links/claim.ts

Add object cache and caching executor

---

docs/content/guides/developer/sui-101/create-coin/regulated.mdx

Update Doc 2024 Move Style 
[https://docs.sui.io/guides/developer/sui-101/create-coin/regulated](https://docs.sui.io/guides/developer/sui-101/create-coin/regulated)

[Update Doc] Update <create-coin> Doc 2024 Move Style 

---

crates/sui-security-watchdog/src/lib.rs
crates/sui-security-watchdog/src/main.rs
crates/sui-security-watchdog/src/query_runner.rs
crates/sui-security-watchdog/src/scheduler.rs

read secrets from env instead of cli args

---

examples/trading/contracts/escrow/sources/lock.move
examples/trading/contracts/escrow/sources/owned.move
examples/trading/contracts/escrow/sources/shared.move

[Move 2024] Convert trading demo to move 2024

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

Remedy for highly congested shared object before the new congestion control is out.
---

Reduce per shared object max queue length to 100

---

docs/content/guides/developer/app-examples/trustless-token-swap/backend.mdx

Changes the code to use latest code (move2024 friendly)
---

[Docs] Minor change on trading demo docs
