crates/sui-tool/src/commands.rs

Follow up to #15690, cleans up the deprecated `--formal` snapshot flag and associated docs
I'll hold off on merging this until after the next release.
Tested locally
---

[snapshot] remove deprecated --formal flag from download-db-snapshots

---

crates/sui-core/src/overload_monitor.rs
crates/sui-types/src/error.rs

With some other nit changes:
- add `s` in `retry_after_secs`
- create a const for calculate the seed used in should_reject_tx, and change interval to 30s (60s may be too long).
Existing tests. No logic change in this PR.
---

Add a simple suggestion in ValidatorOverloadedRetryAfter

---

crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/quorum_driver/metrics.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/quorum_driver/tests.rs
crates/sui-core/src/test_authority_clients.rs
crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
crates/sui-json-rpc/src/error.rs
crates/sui-types/src/error.rs
crates/sui-types/src/quorum_driver_types.rs

This PR implements the client side change for handling ValidatorOverloadedRetryAfter error. Upon receiving more than 2f+1 such error, the client performs exponential backoff and retry. Different from other retryable errors, the retry in this case ignores the max_retry_times constraints to make sure that locked objects can be eventually unlocked.
Caveat in this PR:
- ValidatorOverloadedRetryAfter error contains a suggestion about the minimum duration to wait until the next retry. This is currently ignored on the client side to make the PR managable.
Unit test + integration tests added.
---

Client side change for handling ValidatorOverloadedRetryAfter error

---

docs/content/concepts/graphql-rpc.mdx
docs/content/references/sui-graphql.mdx
docs/site/package.json

Addressing some specific feedback about lack of cross-linking between different parts of the GraphQL docs (we will need to do a broader audit for other examples of the same).
This change:
- Adds links from GraphQL concepts to references and vice versa.
- Removes a generated but otherwise redundant page from the docs generation process.
- Adds more structure and more inner links to the references landing page, where possible.
:eyes:

[GraphQL/Docs] Increased Concepts/References cross-linking

---

crates/sui/src/client_commands.rs
docs/content/references/cli/client.mdx

Add a `sui client balance` command to show the balance of an address. Pass the `--with-coins` flag for a detailed list of each coin and its balance.
Existing tests
---
Added a new command in the CLI: `sui client balance`, which displays the balance of an address. Pass the `--with-coins` flag for a detailed list of each coin and its balance.

[cli] Add client balance command

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/pulumi/init.rs
crates/suiop-cli/src/cli/pulumi/mod.rs

tsia
```
» suiop p i --help                   
initialize a new pulumi project
Usage: suiop pulumi init [OPTIONS]
Options:
-a, --app                          initialize app project
-b, --basic                        initialize barebones project (default)
-c, --cronjob                      initialize cronjob project
-k, --kms                          use GCP KMS as encryption provider
--project-name <PROJECT_NAME>  the name of the project to be created
-h, --help                         Print help
```
---

[suiop] make project name configurable without user input

---

crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination.exp
crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination.move
crates/sui-graphql-e2e-tests/tests/consistency/performance/many_objects.exp
crates/sui-graphql-e2e-tests/tests/consistency/performance/many_objects.move
crates/sui-graphql-rpc/src/consistency.rs
crates/sui-graphql-rpc/src/types/balance.rs
crates/sui-graphql-rpc/src/types/coin.rs
crates/sui-graphql-rpc/src/types/cursor.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/type_filter.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Cherry-pick consistent objects query change into sui-graphql-rpc release branch.
Same tests as original PR
---

[gql] modify consistent objects query to be more performant (#16244)

---

crates/sui-json-rpc-types/src/sui_transaction.rs

This PR adds the postfix `MIST` to gas cost summary display implementation to make it consistent with how gas cost is showed in transaction data.
---

[cli] Improve display for gas cost summary

---

crates/sui-core/src/quorum_driver/mod.rs
crates/sui-types/src/quorum_driver_types.rs

Given the recent retry behavior update, u8 may be too small.
FailedWithTransientErrorAfterMaximumAttempts is only used inside QuorumDriver, so updating it's field type won't break compatibility.
---

Update retry_times in QuorumDriverTask to u32

---

docs/content/guides/developer/getting-started/sui-install.mdx

Suggested brew install "all deps" command did not include all deps.
---

Fix brew install all deps by including libpq

---

scripts/execution_layer.py
sui-execution/Cargo.toml

Removal of workspace hack caused some issues with the existing logic for cutting a new execution layer. So this gets things back to a working state. 
Did a cut locally and ensured it worked. CI

[execution-layer] Update logic for execution-layer cuts to work with no workspace hack

---

consensus/core/src/authority_node.rs
consensus/core/src/block_manager.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/error.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/lib.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

This PR is doing the following:
* Refactoring the `block_manager` to return the missing ancestors that encountered for first time
* Introduce the `Synchronizer` component to fetch the missing blocks from the designated peer (the "live synchronization" mechanism)
* Refactor the `handle_send_block` rpc handler in order to submit the missing ancestors during block proposal to the synchronizer.
Please keep in mind that this implementation can/will be improved but for now keeping it to a functional level for the immediate milestone purposes.
CI
---

[Consensus 2.0] block_manager to return missing blocks & introduce synchronizer

---

consensus/core/src/authority_node.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

Introducing the periodic missing block fetching on the synchronizer. We can do more sophisticated things, but this is probably good enough for the immediate milestones. 
CI
---

[Consensus] add the task scheduler to periodically fetch missing blocks

---

crates/sui-data-ingestion-core/src/executor.rs
crates/sui-data-ingestion-core/src/reader.rs
crates/sui-data-ingestion-core/src/worker_pool.rs
crates/sui-data-ingestion/src/progress_store.rs
crates/sui-data-ingestion/src/workers/kv_store.rs

dynamodb connection timeout is the reason why single task can stop whole daemon from making any progress

[data ingestion] add timeouts to all dynamodb operations

---

crates/sui-analytics-indexer/src/handlers/mod.rs

This PR fixes how we are tagging object status in object and transaction object table. Currently, all output object statuses are incorrect i.e. created objects are marked as deleted, deleted as mutated and mutated as created. This would require some careful fixing. These are the proposed steps to fix:
1. Stop the ingestion pipelines for object and transaction_object tables (ensure currently running pipelines are done processing) and run the following commands:
2. `UPDATE dataset.OBJECT SET object_status = 'Mutated_tmp' WHERE object_status = 'Created';`
3. `UPDATE dataset.OBJECT SET object_status = 'Created' WHERE object_status = 'Deleted';`
4. `UPDATE dataset.OBJECT SET object_status = 'Deleted' WHERE object_status = 'Mutated';`
5. `UPDATE dataset.OBJECT SET object_status = 'Mutated' …

Fix how we track object status in analytics

---

docs/content/guides/developer/sui-101/using-events.mdx

fix a code block in this page.
https://docs.sui.io/guides/developer/sui-101/using-events
before
```
/// Take coin from `DonutShop` and transfer it to tx sender.
/// Requires authorization with `ShopOwnerCap`.
public fun collect_profits( _: &ShopOwnerCap, shop: &mut DonutShop, ctx: &mut TxContext ) {
let amount = balance::value(&shop.balance);
let profits = coin::take(&mut shop.balance, amount, ctx);
// simply create new type instance and emit it event::emit(ProfitsCollected { amount }); transfer::public_transfer(profits, tx_context::sender(ctx)) }
```
after
```
/// Take coin from `DonutShop` and transfer it to tx sender.
/// Requires authorization with `ShopOwnerCap`.
public fun collect_profits( _: &ShopOwnerCap, shop: &mut DonutShop, ctx: &mut TxContext ) {
let amount = …
```

【docs】Fix broken code block in event usage documentation

---

external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/expansion/always_module_member_without_chain.move
external-crates/move/crates/move-compiler/tests/move_2024/expansion/implicit_std_aliases.move
external-crates/move/crates/move-compiler/tests/move_2024/expansion/leading_builtin_name.move
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/expansion/implicit_sui_aliases.move

- Fixed an edge case with builtin names, where `<builtin>` would resolve to a module after a `use a::<builtin>` 
- Added implicit aliases for `std` and `sui` 
New tests
---
Move 2024 now has the following implicit aliases 
```
use std::vector;
use std::option::{Self, Option};
use sui::object::{Self, ID, UID};
use sui::transfer;
use sui::tx_context::{Self, TxContext};
```

[move 2024] Added implicit/default aliases. Fixed edgecase with builtin names

---

external-crates/move/crates/move-compiler/src/lib.rs

- Replicating https://github.com/MystenLabs/sui/pull/16360 for `main`
- Hopefully reduce the chance of this stacker approach from causing issues when building. Longterm, we will need to be more granular when growing the stack.
- @nikos-kitmeridis verified the fix addressed his issue
---
Fixed the likelihood of `sui` failing to build due to stack sizing issues.

[main] Lower Move compiler stack size

---

crates/sui-core/src/authority.rs
crates/sui-core/src/lib.rs
crates/sui-core/src/overload_monitor.rs
crates/sui-core/src/unit_tests/overload_monitor_tests.rs
crates/sui-node/src/lib.rs

It also doesn't handle validator -> fullnode -> validator flow.
Unit test added. Also did a round of cluster testing to make sure that overload monitor can start on validators.
---

Only start overload monitor when sui node is a validator

---

crates/sui-analytics-indexer/src/handlers/mod.rs
crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs

The current approach to wrapped object indexing uses `SuiMoveStruct` which hides some underlying types like `Balance` which causes it to miss indexing such types. Instead, we will start using `MoveStruct` i.e. the actual underlying type and retain the same functionality (i.e we will continue to skip indexing string and url types which we were doing before with `SuiMoveStruct` as well)
Added balance type in the test to check if things work as expected

Use MoveStruct instead of SuiMoveStruct for wrapped indexing

---

crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/docs/bridge/chain_ids.md
crates/sui-framework/docs/bridge/committee.md
crates/sui-framework/docs/bridge/limiter.md
crates/sui-framework/docs/bridge/message.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-framework/packages/bridge/sources/chain_ids.move
crates/sui-framework/packages/bridge/sources/committee.move
crates/sui-framework/packages/bridge/sources/limiter.move
crates/sui-framework/packages/bridge/sources/message.move

[bridge move] governance actions

---

Cargo.lock
crates/typed-store-derive/Cargo.toml
crates/typed-store-derive/src/lib.rs
crates/typed-store/tests/macro_tests.rs

This allows us to change the rust identifier of a table without changing the underlying pathname
Here is a diff of the generated code for the RenameTables1 and RenameTables2, to show exactly which pieces of the output this changes: https://gist.github.com/mystenmark/34e8416b2b7770766fc00fe5036744bb

Add `#[rename = name]` attribute.

---

docs/content/guides/developer/sui-101/using-events.mdx

Fixed the Rust sample code for subscribing to events as it was no longer working.
https://docs.sui.io/guides/developer/sui-101/using-events#rust-sdk
- `SuiEventFilter` -> `EventFilter`
- The `SuiEventFilter` type no longer exists.
- Set WebSocket URL
- Subscription only supported by WebSocket client.
---

【docs】Fix Rust sample code for subscribing to events

---

docs/content/guides/developer/sui-101/shared-owned.mdx

Update code sample with perma link and add diagrams to improve readability of Shared/owned objects concept
Visual Inspection
---

[docs] Fix broken link for shared/owned objects and add diagrams part 2

---

external-crates/move/crates/move-compiler/src/lib.rs

- Hopefully reduce the chance of this stacker approach from causing issues when building. Longterm, we will need to be more granular when growing the stack.
- @nikos-kitmeridis verified the fix addressed his issue
---
Fixed the likelihood of `sui` failing to build due to stack sizing issues.

[1.19] Lower Move compiler stack size

---

crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs

`MSIM_TEST_NUM=40 RUST_LOG=off cargo simtest test_concurrent_readers` passed after this PR.
---

Always create new registry in test_concurrent_readers

---

.github/workflows/ci-docs.yml

Use stable Rust for doc CI, instead of nightly. Nightly is inherently unstable and pinning to a specific nightly version can break too. For generating index page, maybe they can be done as a one-off command / workflow instead.
https://github.com/MystenLabs/sui/actions/runs/8055670229/job/22003035280
---

[CI] use stable rust for doc CI

---

docs/content/references/cli.mdx

Fixes missing CLI PTB item in the CLI commands reference list.
---

[docs] Add CLI PTB item in the CLI reference page.

---

crates/sui-sdk/README.md

When building doc for only one crate, it is unnecessary to enable building workspace index page.
Tried out the instructions locally.
---

[Doc] simplify instructions to build sui-sdk doc

---

sdk/docs/pages/dapp-kit/index.mdx

From `{ type SuiClientOptions}` to `{ getFullnodeUrl }`
Documentation change
---
Fix dapp-kit docs code-example

docs dapp-kit code example fix wrong import

---

crates/sui-package-resolver/src/error.rs
crates/sui-package-resolver/src/lib.rs
crates/sui-package-resolver/src/snapshots/sui_package_resolver__tests__function_parameters.snap
crates/sui-package-resolver/src/snapshots/sui_package_resolver__tests__signature_instantiation.snap

Add an API to get function parameter signatures, with package IDs relocated, and a separate API for instantiating an open parameter signature to get a (closed) signature.
```
```

[Package Resolver] Function parameters and signature instantiation

---

consensus/core/src/broadcaster.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs

Propagates the errors from Core to upstream components (namely CoreThread) to handle. When the error is a `Shutdown` one then we close the core loop and exit, otherwise we panic as it is deemed a fatal one. Since we are doing this I've also propagated an error from the commit observer to follow a uniform approach.
CI
---

[Consensus 2.0] propagate errors from Core to upstream

---

crates/sui-json/src/lib.rs
crates/sui-package-resolver/src/error.rs
crates/sui-package-resolver/src/lib.rs
crates/sui-package-resolver/src/snapshots/sui_package_resolver__tests__pure_input_layouts.snap
crates/sui-package-resolver/tests/packages/e0/Move.toml
crates/sui-package-resolver/tests/packages/e0/sources/m.move
crates/sui-package-resolver/tests/packages/std/Move.toml
crates/sui-package-resolver/tests/packages/std/sources/std.move
crates/sui-types/src/base_types.rs
crates/sui/src/client_ptb/builder.rs

Add a function to the package resolver to infer types and layouts for pure transaction inputs, for use by the indexer to generate output for transaction blocks in JSON-RPC (and maybe eventually also GraphQL).
```
```
- #16340

[Package Resolver] Resolver::pure_input_layouts

---

docs/content/references/cli/ptb.mdx

Fix typo in ptb.mdx doc file.
---

[docs] Fix typo in CLI PTB page

---

crates/sui-graphql-rpc/README.md
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs

Some queries in the ts sdk shim layer exceed the defaults set by sui-graphql-rpc today, so we raise them here. Also remove the special init fn for simulator testing, so we don't run into these discrepancies in the future. 
existing tests pass
---

[gql][1/n][adjust-limits] Adjust limits to support json-rpc-compatible ts sdk shim layer

---

crates/sui-graphql-rpc/README.md
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs

Cherry-pick of #16407
Some queries in the ts sdk shim layer exceed the defaults set by sui-graphql-rpc today, so we raise them here. Also remove the special init fn for simulator testing, so we don't run into these discrepancies in the future.
existing tests pass
---
---

[gql][cherry-pick] Adjust limits to support json-rpc-compatible ts sdk shim layer

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/pulumi/init.rs
crates/suiop-cli/src/cli/pulumi/mod.rs

Make it so we can create pulumi projects in the services dir
```
» suiop p i --service --project-name source-service                                                   
2024-02-27T16:37:38.736654Z  INFO suioplib::cli::pulumi::init: creating k8s containerized application/service                
2024-02-27T16:37:38.736699Z  INFO suioplib::cli::pulumi::init: creating project directory at /Users/jkjensen/mysten/sui-operations/pulumi/services/source-service                                                                                         
2024-02-27T16:37:38.736831Z  INFO suioplib::cli::pulumi::init: creating new pulumi project in /Users/jkjensen/mysten/sui-operations/pulumi/services/source-service
2024-02-27T16:37:38.736834Z  INFO suioplib::cli::pulumi::init: extra pulumi options added: …
```

[suiop] add type for services

---

crates/sui-analytics-indexer/src/analytics_processor.rs
crates/sui-analytics-indexer/src/lib.rs

The dir prefix path is today not acknowledged during the setup phase where pipeline starts from a particular checkpoint. This will cause the pipeline to re-run from the same checkpoint when doing backfills. This PR fixes the particular issue.
Ran locally, verified the path used during re-run is the backfill path (not the main path)

Fix dir prefix that is used for backfills

---

Cargo.lock
crates/sui-analytics-indexer/src/handlers/object_handler.rs
crates/sui-analytics-indexer/src/lib.rs
crates/sui-analytics-indexer/src/tables.rs

We do not track deleted objects in object history table which makes it hard to know final object states. This PR fixes this by starting to track tombstone object state.
Running locally

Start tracking deleted objects in object history table

---

crates/sui/src/client_commands.rs
crates/sui/src/client_ptb/lexer.rs
crates/sui/src/client_ptb/ptb.rs
crates/sui/src/client_ptb/snapshots/sui__client_ptb__lexer__tests__tokenize_commands.snap
crates/sui/src/client_ptb/snapshots/sui__client_ptb__lexer__tests__tokenize_flags.snap
crates/sui/src/client_ptb/snapshots/sui__client_ptb__lexer__tests__unexpected_dash_dash.snap
crates/sui/src/client_ptb/token.rs

Make help flag detection more robust by doing it after tokenisation, so that the help flag is treated consistently like other `--commands` or `-f`lags.
This PR also introduces a new notion of a `-f`lag to the lexer (which is only used for `-h` at the moment).
```
crates/sui$ cargo nextest run -- lexer
```
Trying the command:
```
sui$ cargo run --bin sui -- --help
sui$ cargo run --bin sui -- -h
```

[CLI/PTB] Check for help flags after lexing

---

crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dof_add_reclaim_transfer.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dof_add_reclaim_transfer.move
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dof_add_reclaim_transfer_reclaim_add.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dof_add_reclaim_transfer_reclaim_add.move
crates/sui-graphql-rpc/src/consistency.rs
crates/sui-graphql-rpc/src/types/coin.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/object.rs

The dynamic fields of a parent object are further constrained in that their `object_version` cannot exceed the parent object's `object_version`. This currently manifests as additional filter conditions on the `newer` subquery, `WHERE object_version <= parent_version AND object_status=ObjectStatus::WrappedOrDeleted as i16`. On a revisit, this latter check on `object_status` is unnecessary and actually incorrect. If there are more recent versions of the object where its version is less than the parent version, we should always filter it out, because the `candidates` subquery will always select the latest object version that satisfies the filtering criteria. But the additional `object_status` check means that we'll erroneously return the historical child object even if later versions are not …

[gql][fix] Refactor dynamic fields query to use `build_objects_query`

---

consensus/core/src/authority_node.rs
consensus/core/src/base_committer.rs
consensus/core/src/block_manager.rs
consensus/core/src/broadcaster.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/linearizer.rs
consensus/core/src/metrics.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs
consensus/core/src/synchronizer.rs
consensus/core/src/test_dag.rs
consensus/core/src/tests/base_committer_tests.rs

`DagState::flush()` persists blocks, commits and last committed rounds known to `DagState`. It is efficient in only writing out the delta from the last `flush()` to storage. It must be called before proposing a block to peers, and sending committed blocks to execution.
Additionally,
- When getting blocks by refs, check storage if they are not found in memory.
- Crash on storage errors in DagState, because callers to DagState can only panic on these errors as well.
- Clean up old blocks after each flush.
- Try to propose and commit immediately after Core recovery.
Unit tests.
---

[Consensus] `DagState` persistence

---

crates/sui-data-ingestion-core/Cargo.toml
crates/sui-data-ingestion-core/src/executor.rs
crates/sui-data-ingestion-core/src/lib.rs
crates/sui-data-ingestion-core/src/progress_store/mod.rs

The PR introduces a helper function to execute a simple workflow (a single type of job) from a remote bucket, starting from a specified checkpoint (progress store is mocked).
It aims to minimize unnecessary complexity when setting up a new data ingestion pipeline for external developers

[data ingestion] simple workflow helper

---

crates/sui-indexer/src/apis/indexer_api.rs
crates/sui-indexer/src/indexer_reader.rs

Fix an issue where a blocking indexer call was being made from an async context, causing a runtime panic.
---

indexer: fix sync-from-async call logic error

---

external-crates/move/crates/move-compiler/src/typing/syntax_methods.rs
external-crates/move/crates/move-compiler/tests/move_2024/naming/index_syntax_methods_return_mismatch.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/primitive_index_invalid_2.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/syntax_methods_args_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/syntax_methods_args_polymorphic_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/syntax_methods_args_polymorphic_invalid_positional.exp

This does a bit more work in syntax index function checking to produce nicer errors when types disagree.
Updated expectation files
---

[move-2024] Slighlty improve type mismatch errors in syntax index errors

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/test_authority_clients.rs
crates/sui-core/src/transaction_manager.rs
crates/sui-core/src/unit_tests/execution_driver_tests.rs
crates/sui-core/src/unit_tests/transaction_manager_tests.rs
crates/sui-simulator/src/lib.rs

To be consistent with all the other calls inside the function, where we always use expect.
It's also a bad practice to ignore the return value of some calls. Changing all of them to expect.
The core of this PR is in TransactionManager. All changes in other functions are due to the function signature change.
---

TxManager::enqueue does not need to return Result

---

crates/sui-graphql-rpc/src/error.rs
crates/sui-graphql-rpc/src/extensions/timeout.rs
crates/sui-graphql-rpc/src/server/builder.rs

This PR enables logging of queries that time out. The logging uses the `error` macro together with a new error code, `REQUEST_TIMEOUT`.
Note, that the timeout extension function was switched to `parse_query` + `execute`. Execute one takes care of the time, parse query takes care of stringifying up the query (including resolving any passed, fragments, etc).
Existing tests, manually checking for errors when setting a small (500ms) timeout.
```bash
2024-02-28T23:25:23.373001Z ERROR sui_graphql_rpc::extensions::timeout: Query: {
transactionBlocks(first: 50) {
nodes {
digest
}
}
} query_id=97a7adca-52dc-4e4e-9cdc-bfdaaf1d65ae session_id=127.0.0.1:52232 error_code="REQUEST_TIMEOUT"
```
```
2024-02-29T02:35:24.740291Z ERROR sui_graphql_rpc::extensions::timeout: …
```

[GraphQL] Add query logging when timing out

---

crates/sui-graphql-rpc/src/error.rs
crates/sui-graphql-rpc/src/extensions/timeout.rs
crates/sui-graphql-rpc/src/server/builder.rs

This PR enables logging of queries that time out. The logging uses the `error` macro together with a new error code, `REQUEST_TIMEOUT`.
Note, that the timeout extension logic was switched to use `parse_query`
and `execute` instead of `request`. Execute one takes care of the timeout, parse query takes care of stringifying up the query (including resolving any passed variables, fragments, etc).
Existing tests, manually checking for errors when setting a small (500ms) timeout.
---
Enabled logging of queries that time out.

[Cherry-pick] Add query logging when timing out (#16455) - cherry pick into graphql release

---

crates/sui-config/src/node.rs
crates/sui-core/src/overload_monitor.rs
crates/sui-core/src/unit_tests/execution_driver_tests.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

Also update parameters to be less aggressive. Works better at higher throughput based on experiments.
Testnet experiments show no regression
---

Turn on overload protection at signing by default

---

external-crates/move/crates/move-package/src/lib.rs
external-crates/move/crates/move-package/src/lock_file/mod.rs

Setup for test in follow up PR: https://github.com/MystenLabs/sui/pull/16445. When getting a lock file handle it's useful for it to be set to the beginning for reads rather than the caller needing to rewind it (or forgetting to and not seeing content when reading from the handle).
Covered by existing test that exercises these functions together.
---

move lock: rewind when creating new lock file from copy

---

crates/sui/src/client_ptb/ptb.rs

This PR fixes the edge case of not providing any arguments when calling `sui client ptb`, which currently panics.
`sui client ptb` | `sui client ptb --` 
**Before**
```
~ % sui client ptb
2024-03-01T04:48:11.873626Z ERROR telemetry_subscribers: panicked at crates/sui/src/client_ptb/error.rs:180:34:
attempt to subtract with overflow panic.file="crates/sui/src/client_ptb/error.rs" panic.line=180 panic.column=34
thread 'main' panicked at crates/sui/src/client_ptb/error.rs:180:34:
attempt to subtract with overflow
```
**After**
```
~ % sui client ptb
Build, preview, and execute programmable transaction blocks. Depending on your shell, you might have to use quotes around arrays or other passed values. Use --help to …
```

[cli] Fix panic when no arg is given in client ptb

---

crates/sui/tests/data/ptb_complex_args_test_functions/Move.toml

Fix the package path in the package to refer to the local sui-framework and not a network.
Existing tests/CI

[easy] fix package path in test to be local

---

consensus/core/src/authority_node.rs
consensus/core/src/block.rs
consensus/core/src/block_manager.rs
consensus/core/src/block_verifier.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/error.rs
consensus/core/src/synchronizer.rs
consensus/core/src/test_dag.rs

Verify that max ancestors timestamp <= block timestamp.
Since this check requires all ancestors block to be available, it needs to be done after a block has complete causal history but before the block is accepted.
Also,
- Verify genesis ancestors are valid.
- Refactor genesis block creation.
Unit test.
---

[Consensus] verify block timestamp invariant and genesis ancestors

---

consensus/core/src/block.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/lib.rs
consensus/core/src/linearizer.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-core/src/consensus_types/consensus_output_api.rs
narwhal/executor/src/lib.rs
narwhal/node/src/execution_state.rs

Add a `TrustedCommit` type that contains refcounted and versioned internal data.
In future, uncertified commit received from peers will be stored in another type.
`TrustedCommit` internal layout will evolve in future PRs. Digest, serialized bytes and certifier fields will be added. How commits are stored will also evolve.
CI.
---

[Consensus] add `TrustedCommit` type

---

consensus/core/src/base_committer.rs
consensus/core/src/block.rs
consensus/core/src/block_manager.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/context.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/error.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/linearizer.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/stake_aggregator.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/synchronizer.rs
consensus/core/src/threshold_clock.rs
consensus/core/src/transaction.rs
consensus/core/src/universal_committer.rs

Non-test code should all get used now.
CI
---

[Consensus] remove `allow(unused)` and `allow(dead_code)`

---

.changeset/plenty-cobras-matter.md
sdk/enoki/src/EnokiClient/index.ts

Add EnokiClientError to expose enoki service error details

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/src/vfs.rs

This fixes a bug related to a misunderstanding on how VFS's overlay file system works. (a read-only layer has to be created explicitly, rather than being automatically provided by the overlay file system).

[move-ide] IDE VFS fix to guarantee in-execution immutability

---

crates/sui-core/src/authority/authority_store.rs
crates/sui-tool/src/lib.rs

CP https://github.com/MystenLabs/sui/pull/16496
---
---

[formal snapshots] Do not load genesis objects on restore (#16496)

---

Cargo.lock
crates/sui-bridge/Cargo.toml
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/sui_syncer.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/sui-framework/docs/bridge/committee.md
crates/sui-json-rpc-api/src/bridge.rs
crates/sui-json-rpc/src/bridge_api.rs

1. replace `BRIDGE_PACKAGE_ID` env var to 0xb
2. replace `ROOT_BRIDGE_OBJECT_ID` env var to 0x9
3. replace `ROOT_BRIDGE_OBJECT_INITIAL_SHARED_VERSION` env var with bridge_api RPC call
---

[bridge 45/n] replace env ids in Bridge Node

---

crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-types/src/bridge.rs

replace both `BRIDGE_OBJECT_ID` and `BRIDGE_RECORD_ID` with `get_bridge_summary` RPC API
---

[bridge 46/n] replace remaining env ids in Bridge Node

---

docker/grafana-local/dashboards/cluster-status-dashboard.json

Add overload status dashboard in local grafana

---

crates/sui-json/src/lib.rs
crates/sui-replay/src/displays/mod.rs
crates/sui-replay/src/displays/transaction_displays.rs
crates/sui-replay/src/replay.rs
crates/sui-types/src/transaction.rs

This makes a call to `dev_inspect_transaction` and forwards the PTB intermediate results to the transaction display where it can be formatted and output, if and only if the `--ptb-info` flag was supplied. This approach doesn't change any code in the main path of execution. 
The tabled library does not support displaying such large values so we omit the table for this new section.
example output 1:
example output 2:
---

Get PTB results available in transaction displays

---

sdk/docs/pages/dapp-kit/sui-client-provider.mdx

From { type SuiClientOptions } to { getFullnodeUrl }
Documentation change
---
Fix typo in examples in dapp-kit docs

dapp-kit-docs: Documentation typo

---

Cargo.lock
external-crates/move/Cargo.toml

upgrade some dependencies for the new advisory: 
```
error[vulnerability]: Tokens for named pipes may be delivered after deregistration
┌─ /Users/luzhang/Workplaces/sui/Cargo.lock:564:1
│
564 │ mio 0.7.14 registry+https://github.com/rust-lang/crates.io-index
│ ---------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2024-0019
= Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0019
= ## Impact
When using named pipes on Windows, mio will under some circumstances return invalid tokens that correspond to named pipes that have already been deregistered from the mio registry. The impact of this vulnerability depends on how mio is used. For some applications, invalid tokens may be ignored or cause a warning or a crash. On the other …
```

upgrade mio for advisories

---

crates/sui/src/client_ptb/ast.rs
crates/sui/src/client_ptb/builder.rs
crates/sui/src/client_ptb/parser.rs
crates/sui/tests/ptb_files/parsing/invalid_commands.ptb
crates/sui/tests/snapshots/ptb_files_tests__invalid_commands.ptb.snap

Adds help messages for misspelled PTB commands:
Added a test to make sure we properly report suggested names
---
Suggest the closes valid command if an invalid command name is encountered in CLI PTBs.

[cli-ptb] Add "did you mean" for misspelled commands

---

Cargo.lock

```
1380 │ whoami 1.3.0 registry+https://github.com/rust-lang/crates.io-index
│ ------------------------------------------------------------------ security vulnerability detected
│
= ID: RUSTSEC-2024-0020
= Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0020
= With older versions of the whoami crate, calling the `username` function leads to an immediate stack
buffer overflow on illumos and Solaris. Denial of service and data corruption have both been
observed in the wild, and the issue is possibly exploitable as well.
This also affects any other Unix platforms that aren't any of: `linux`, `macos`, `freebsd`,
`dragonfly`, `bitrig`, `openbsd`, `netbsd`.
This issue has been addressed in whoami 1.5.0.
For more information, see [this GitHub …
```

update whoami for advisory

---

crates/sui-sdk/src/lib.rs

This fixes the link not generating automatically during the GH action. Risk is small that the link location changes.
---

[docs] Temporary fix for link not automatically generated

---

.changeset/six-garlics-dress.md
sdk/typescript/src/zklogin/index.ts

an useful function to export for deriving multisig address from zklogin account. 
---

sdk: export toZkLoginPublicIdentifier

---

.dockerignore
docker/sui-node/Dockerfile
docker/sui-node/build.sh

This uses the stagex toolchain (see: https://codeberg.org/stagex/stagex) to build the`sui-node` container.
[stagex](https://codeberg.org/stagex/stagex) starts with 256 bytes of x86 assembly and deterministically reproduces every dependency necessary to build modern software. Every release of stagex is coordinated such that only if two maintainers with a separate hardware stack are able to reproduce the _entire_ toolchain, will the containers be published. As such, stagex can be built locally to get the _exact_ same images that exist in Docker Hub (when using Docker 25.x with containerd snapshotter).
This pull request uses the stagex toolchain and the stagex Containerfile workflow to build a deterministic OCI image. The image may be loaded to Docker using:
```sh
env -C build/oci/sui-node …
```

Deterministic Build using StageX

---

docs/content/concepts/sui-move-concepts/packages/upgrade.mdx

Abilities for existing structs cannot be changed in non-system package upgrades.
:eyes:

[Docs] Clarify upgrade requirements on abilities

---

docker/sui-node/Dockerfile

Update `sui-node` path in Dockerfile to original path previously used.
* Run  [Build Sui Images Job
](https://github.com/MystenLabs/sui-operations/actions/workflows/dockerize-to-ecr.yml)
* Run commands to verify `sui-node` binary is accessible at expected path
---

add sui-node binary paths used in the past

---

scripts/simtest/cargo-simtest

simtests are no longer immediately after [#16537](https://github.com/MystenLabs/sui/pull/16537) :
https://github.com/MystenLabs/sui/actions/runs/8160893924/job/22308495694

Revert PR#16537

---

crates/sui-indexer/migrations/2023-08-19-044044_checkpoints/up.sql

We have an index on `checkpoints` on the `epoch` field, but this is not used by the query planner to support queries from graphql, since we always have an additional filter on `sequence_number`, either from the high watermark, or from the cursor when paginating through checkpoints. This results in a query that essentially iteratively scans through the pkey index. Even though the estimated cost is low, the actual runtime is significant since we do a great deal of filtering.
```
defaultdb=> explain analyze select * from checkpoints where epoch = 321 order by sequence_number limit 3;
QUERY PLAN         
------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=0.44..108.48 rows=3 …
```

[gql][performance-tuning][1/n] add `checkpoints_epoch_sequence_number` index to support graphql checkpoint queries

---

.github/workflows/mysticeti.yml
.github/workflows/rust.yml

This allows running all unit and sim tests manually. Everyday the workflow runs periodically too. In future, this can be triggered on PR.
CI
---

[CI] add manual and periodic Mysticeti workflow

---

crates/sui-single-node-benchmark/src/benchmark_context.rs
crates/sui-single-node-benchmark/src/mock_storage.rs
crates/sui-single-node-benchmark/src/single_node.rs

Now that we support RunWithRange in checkpoint execution, there is no longer a need to construct end of epoch tx in the benchmark. Removing it.
CI
---

[bench] Simplify checkpoint execution benchmark

---

docs/site/src/theme/prism-move.js

Adds 2024 syntax support to docs.
Docs preview.

[docs] Adds move 2024 support to docs

---

external-crates/move/crates/move-compiler-transactional-tests/tests/operators/eq_refs.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/operators/eq_refs.move
external-crates/move/crates/move-compiler/src/editions/mod.rs
external-crates/move/crates/move-compiler/src/typing/core.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/typing/eq_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/eq_invalid.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/eq_ref_tvars.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/eq_ref_tvars.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/eq_refs_struct.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/eq_refs_struct_invalid_no_drop.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/eq_refs_struct_invalid_no_drop.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/eq_refs_struct_no_drop.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/neq_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/neq_invalid.move

This considers refs during typechecking Eq/Neq binops, and does automatic referencing when possible to allow equality to work a bit easier.
Note this is now Move 2024 feature gated.
New tests, plus updated expected output for old ones.
---

[move-2024] Automatic Referencing in Equality

---

Cargo.lock
external-crates/move/Cargo.lock
external-crates/move/crates/move-compiler/Cargo.toml
external-crates/move/crates/move-compiler/src/cfgir/borrows/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/liveness/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/locals/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/optimize/constant_fold.rs
external-crates/move/crates/move-compiler/src/cfgir/optimize/eliminate_locals.rs
external-crates/move/crates/move-compiler/src/cfgir/optimize/forwarding_jumps.rs
external-crates/move/crates/move-compiler/src/cfgir/optimize/inline_blocks.rs
external-crates/move/crates/move-compiler/src/cfgir/optimize/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/optimize/simplify_jumps.rs
external-crates/move/crates/move-compiler/src/cfgir/translate.rs
external-crates/move/crates/move-compiler/src/cfgir/visitor.rs
external-crates/move/crates/move-compiler/src/command_line/compiler.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/lib.rs
external-crates/move/crates/move-compiler/src/naming/resolve_use_funs.rs
external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/src/to_bytecode/translate.rs
external-crates/move/crates/move-compiler/src/typing/dependency_ordering.rs
external-crates/move/crates/move-compiler/src/typing/expand.rs
external-crates/move/crates/move-compiler/src/typing/infinite_instantiations.rs
external-crates/move/crates/move-compiler/src/typing/macro_expand.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/src/typing/visitor.rs
external-crates/move/crates/move-proc-macros/src/lib.rs

This replaces the previous stacker fix with an annotation proc macro that bumps the stack any time it's at risk of running out of room.
Everything still works as expected, plus windows tests (TBD).
---

[move] Add fine-grained calls to stacker across the compiler

---

docs/content/guides/developer/first-app/write-package.mdx

Should use public_transfer
```
transfer::transfer(admin, tx_context::sender(ctx));
```
```
transfer::public_transfer(admin, tx_context::sender(ctx));
```

[Docs] Fix : Transfer Object need use public_transfer

---

crates/sui-graphql-rpc/src/types/event.rs

Since the event filter takes in a single `tx_digest`, we know that there will only be one corresponding transaction. We can use `single_value()` to tell the query planner that we expect only one instead of a range of values, which will subsequently speed up query execution time.
existing tests (will be picked up by benchmarking suite when I get to that)
---

[gql][performance-tuning][2/n] Leverage `single_value()` for event look up by tx digest

---

external-crates/move/crates/move-compiler-transactional-tests/tests/macros/loop.move
external-crates/move/crates/move-compiler-transactional-tests/tests/macros/loop_nested.move
external-crates/move/crates/move-compiler/src/parser/lexer.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/tests/move_2024/parser/for_keyword.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/for_keyword.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/macros_have_unique_scopes_nested.move

- `for` is now a keyword in Move 2024 
- new tests
---
Move 2024 now reserves `for` as a keyword

Made 'for' a Move 2024 keyword

---

crates/sui-framework/packages/move-stdlib/Move.toml
external-crates/move/crates/move-cli/tests/build_tests/migration_names/Move.toml
external-crates/move/crates/move-cli/tests/build_tests/migration_names/Move.toml.expected
external-crates/move/crates/move-cli/tests/build_tests/migration_names/args.exp
external-crates/move/crates/move-cli/tests/build_tests/migration_names/args.txt
external-crates/move/crates/move-cli/tests/build_tests/migration_names/migration_sources/mod0.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names/migration_sources/mod_intermodule_errors.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names/migration_sources/mod_let.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names/migration_sources/mod_let_errors.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names/sources/mod0.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names/sources/mod_intermodule_errors.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names/sources/mod_let.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names/sources/mod_let_errors.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names_mut_allowed/Move.toml
external-crates/move/crates/move-cli/tests/build_tests/migration_names_mut_allowed/Move.toml.expected
external-crates/move/crates/move-cli/tests/build_tests/migration_names_mut_allowed/args.exp
external-crates/move/crates/move-cli/tests/build_tests/migration_names_mut_allowed/args.txt
external-crates/move/crates/move-cli/tests/build_tests/migration_names_mut_allowed/migration_sources/mut_name.move
external-crates/move/crates/move-cli/tests/build_tests/migration_names_mut_allowed/sources/mut_name.move
external-crates/move/crates/move-compiler/src/diagnostics/codes.rs
external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/editions/mod.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/parser/ast.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/tests/move_check/expansion/invalid_local_name.exp

This sets up a (mildly hacky) solution to migrate newly-reserved keywords when they appear in existing code by maing them restricted identifiers (e.g., "type" -> "`type`").
New test case for migration, plus attempting to run it against the sui framework locally which does similar things.
---

[move-2024] Add support for migrating keywords

---

.changeset/giant-tomatoes-worry.md
sdk/wallet-standard/src/chains.ts

This PR adds a new type-guard util called `isSuiChain` which is useful for implementing dApp interfaces in wallets (see example below). The Solana wallet-standard has an equivalent utility for this as well, and it seems to be used commonly in open source wallet implementations.
---

[wallet-standard] add isSuiChain utility

---

crates/suiop-cli/src/cli/service/init.rs

Make a single invocation of `suiop service init` produce a working crate within the sui repo.
- include `crates/` in the top-level reference so the workspace still works
- rename boilerplate cargo toml project to the new directory name
```
» cargo run -- s i --path ../test-svc
Compiling suiop-cli v0.1.9 (/Users/jkjensen/mysten/sui/crates/suiop-cli)
Finished dev [unoptimized + debuginfo] target(s) in 7.14s                                                                                                                                                                     
Running `/Users/jkjensen/mysten/sui/target/debug/suiop s i --path ../test-svc`
2024-03-11T17:19:52.224787Z  INFO suioplib::cli::service::init: creating rust service in ../test-svc
» cd ../test-svc 
» cargo run
Compiling …
```

[suiop][service-platform] fix top-level cargo file and add name to project cargo file

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

Previously we notified checkpoint service of new pending checkpoints before the batch containing it was written.

Fix race in pending checkpoint notification

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/checkpoints/mod.rs

Argument was only used for logging, but its existence makes it seem like it would be used for the notification.

Simplify notify_checkpoint interface not to take a PendingCheckpoint

---

crates/suiop-cli/src/cli/incidents/pd.rs

Add priority to listing recent incidents
---

[suiop][pagerduty] add priority to recent incidents listing

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/core.rs
crates/sui-node/src/lib.rs
crates/sui-rosetta/tests/end_to_end_tests.rs
crates/telemetry-subscribers/Cargo.toml
crates/telemetry-subscribers/tests/reload.rs

- Fix the test timeout by adding a minimum delay between rounds, and reduce workload in some tests. Otherwise with small p2p latencies in tests, consensus has high round rate, uses significant CPU and slows down tests.
- Fix `test_coin_deny_list_creation` by only allow overriding consensus protocol when protocol config is >= 36. But in future Mysticeti will need to be able to run at earlier protocol versions, because Narwhal may get removed completely. An alternative is to remove these tests for specific earlier protocol versions.
This recreates #16614 because somehow the PR is no longer updated with new commits in the branch.
CI
Local tests with `CONSENSUS=mysticeti`
---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please …

[Consensus] fix additional test failures for Sui with Mysticeti

---

docs/content/guides/developer/app-examples/e2e-counter.mdx
docs/content/guides/developer/first-app.mdx
docs/content/guides/developer/first-app/build-test.mdx
docs/content/guides/developer/first-app/client-tssdk.mdx
docs/content/guides/developer/first-app/debug.mdx
docs/content/guides/developer/first-app/publish.mdx
docs/content/guides/developer/first-app/write-package.mdx
docs/content/references/cli/address-prefix.mdx
docs/content/references/cli/ptb.mdx
docs/content/sidebars/concepts.js
docs/content/snippets/address-prefix.mdx
docs/content/snippets/info-pnpm-required.mdx

- Completed the publish package guide and added another execution step that interacts with the package using PTB.
- Added a small example of calling a move package in the PTB CLI reference section
- Refactored the tip section for address prefix `@` in CLI so the fragment can be reused across doc site
Visual inspection
---

[docs] PTB CLI guide and reference update

---

sdk/typescript/test/e2e/multisig.test.ts

ocassionally this test fails in localnet before JWK object is created, this adds a wait time to make sure epoch reaches 1 to run the zklogin tx. 
---

fix: add some sleep before zklogin test

---

crates/sui-cluster-test/src/cluster.rs
crates/sui-cluster-test/src/faucet.rs
crates/sui-cluster-test/src/wallet_client.rs
crates/sui-faucet/src/bin/merge_coins.rs
crates/sui-faucet/src/main.rs
crates/sui-oracle/src/main.rs
crates/sui-sdk/examples/utils.rs
crates/sui-sdk/src/wallet_context.rs
crates/sui/src/sui_commands.rs
crates/test-cluster/src/lib.rs

Fix #16458 
---
The `WalletContext::new` method does not have any asynchronous dependencies, and thus it does not need to be defined as an asynchronous function. This PR is a breaking change that modifies the signature of `WalletContext::new` into a synchronous function. Users that depend on `WalletContext::new` will need to update callsites accordingly by dropping the `.await`.

Delete async when new wallet context in sui sdk

---

Cargo.lock
crates/sui-data-ingestion-core/Cargo.toml
crates/sui-data-ingestion-core/src/reader.rs

PR makes remote fetch implementation more similar to the indexer implementation

[data ingestion] change remote reader implementation

---

external-crates/move/crates/move-cli/tests/build_tests/migration/args.exp
external-crates/move/crates/move-cli/tests/build_tests/migration_names/args.exp
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/Move.toml
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/Move.toml.expected
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/args.exp
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/args.txt
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/migration_sources/migration.move
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/migration_sources/other.move
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/migration_sources/validate.move
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/migration_tests/test0.move
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/sources/migration.move
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/sources/other.move
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/sources/validate.move
external-crates/move/crates/move-cli/tests/build_tests/migration_paths/tests/test0.move
external-crates/move/crates/move-cli/tests/build_tests/migration_with_blocking_errors/Move.toml.expected
external-crates/move/crates/move-cli/tests/build_tests/migration_with_blocking_errors/args.exp
external-crates/move/crates/move-cli/tests/build_tests/migration_with_blocking_errors/args.txt
external-crates/move/crates/move-cli/tests/build_tests/migration_with_blocking_errors/sources/mod1.move
external-crates/move/crates/move-compiler/src/diagnostics/codes.rs
external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-package/src/migration/mod.rs

In legacy move, we allowed three-place names to use an address in the first position, even if there was also a module in scope with that name. Move 2024's resolution rules now require `::` proceeding that name to do this. This updates migration to support.
Also, this moves writing the edition flag to the `Move.toml` file  _after_ successful migration, so that we aren't updating the it in the error case.
New tests plus more local testing against the sui framework code.
---

[move-2024] Add migration support for globally qualifying names

---

crates/sui-node/src/lib.rs

So far this is the only thing I've identified that needs to be shutdown manually (due to being an async shutdown) rather than being handled by `Drop`. If there are others, please point them out
Existing `RunWithRange` simtests
---

[RunWithRange] Work toward graceful shutdown

---

consensus/core/src/authority_node.rs
consensus/core/src/block.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/error.rs
consensus/core/src/lib.rs
consensus/core/src/linearizer.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
narwhal/executor/src/lib.rs
narwhal/node/src/execution_state.rs

This is the write path for commit certification. It is kept simple: each block can contain one or more `CommitRef` that includes commit leader round, index and digest. For each commit, all votes on it are recorded in storage when blocks containing commit votes are persisted.
Unit tests.
---

[Consensus] vote on commits and persist votes in store

---

.github/workflows/mysticeti.yml
consensus/core/src/authority_node.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/storage/store_tests.rs
crates/mysten-network/src/multiaddr.rs
crates/sui-network/src/state_sync/mod.rs
crates/telemetry-subscribers/tests/reload.rs
crates/test-cluster/src/lib.rs

Receive the network service IP from the host, instead of specifying it when starting the service. Among other reasons, this helps with binding to the same IP and port after stopping the service in sim tests.
Also,
- Allow the Mysticeti workflow to run from a branch or commit.
- Use `warn` for not finding archive reader.
- Avoid spurious lint issues when running simtest.
CI
https://github.com/MystenLabs/sui/actions/runs/8276357969/job/22644782845
---

[Consensus] start service with unspecified IP

---

Cargo.lock
Cargo.toml
crates/sui-framework/packages/sui-framework/tests/crypto/bls12381_tests.move
sui-execution/latest/sui-move-natives/src/crypto/group_ops.rs

Move EC ops - skip validation of already validated group elements. This is purely an internal performance optimization.
Also adding a few more small tests.
Existing unit tests pass
---

Move EC ops - skip validation of already validated group elements

---

crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/error.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/src/types/transaction_block.rs
crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/consensus_commit_prologue.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/randomness_state_update.rs
crates/sui-indexer/src/models/epoch.rs

Initial plumbing to use `Db` as the source for a `DataLoader` and an implementation of `DataLoader` for `Epoch` to exercise it.
This is a behaviour preserving refactor, so we use the existing tests:
```
```
@wlmyng also manually tested a query that would previously have done multiple sequential Epoch reads, and found a 10x speed-up (3s to 300ms) in local testing.

[GraphQL/DataLoader] Epochs

---

crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/error.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/src/types/transaction_block.rs
crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/authenticator_state_update.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/consensus_commit_prologue.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/randomness_state_update.rs
crates/sui-indexer/src/models_v2/epoch.rs

Initial plumbing to use `Db` as the source for a `DataLoader` and an implementation of `DataLoader` for `Epoch` to exercise it.
This is a behaviour preserving refactor, so we use the existing tests:
```
```
@wlmyng also manually tested a query that would previously have done multiple sequential Epoch reads, and found a 10x speed-up (3s to 300ms) in local testing.

[pick #16650][GraphQL/DataLoader] Epochs

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/authority_node.rs
consensus/core/src/block.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/stake_aggregator.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs
consensus/core/src/synchronizer.rs

Using the DagState to figure out the ancestors to include in next block proposal instead of caching them in Core. Similarly use DagState to figure out whether the leader of previous round exist. Also the Store is no longer used in `Core` and the `DagState` is solely used instead.
CI
---

[Consensus 2.0] use DagState for block proposal in Core

---

crates/sui/src/client_commands.rs

This PR improves the formatting of the coin objects for `client gas` and `client balance`.
Visual tests + existing tests.
```
🚀 sui % sui client gas 0x28409ff3622bbe6f08ac6199ac676864097378ca61cb084c8ccd60e2b187c2bd
[warn] Client/Server api version mismatch, client api version : 1.20.0, server api version : 1.19.1
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Showing 11 gas coins and their balances.                                                                   │
├────────────────────────────────────────────────────────────────────┬────────────────────┬──────────────────┤
│ gasCoinId                                                          │ mistBalance (MIST) │ suiBalance (SUI) │ …
```

[cli] Add balance formatting for balance and gas commands

---

crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/graphiql_server.rs
crates/sui-json-rpc/src/name_service.rs

Today we have two entrypoints, `start-server` and `from-config`. The former is the standard way we launch the graphql service, by providing a `--config` path to a `.toml` file. The latter is a yaml-based entrypoint. Because we do not use this yaml config, this PR removes yaml-related code to simplify. Also refactors `config.rs` to this order:
1. consts and struct defs
2. impl async-graphql's Object macro
3. impl
4. impl Trait
Note that `NameServiceConfig` has a `domain_type_tag` field that is computed, so it probably won't play nicely with reading from a `.toml` file. I'll address this in a follow-up PR. 
Existing
---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release …

[gql] clean up config.rs

---

Cargo.lock
Cargo.toml
crates/sui-bridge/Cargo.toml
crates/sui-bridge/build.rs
deny.toml
scripts/simtest/cargo-simtest

This PR re-introduces forge after the revert. It's too much work to make simtest compatible with all the new dependencies so we choose to exclude sui-bridge when building with simulation profile.
---

Re introduce forge

---

crates/sui-json-rpc-tests/tests/name_service_tests.rs
crates/sui-json-rpc/src/name_service.rs

**Updated the description (16-01-2024) due to a change in our support (we won't omit TLDs and `@` is a special format after all, not another wildcard)**
With this PR, we add support for wildcard `.` or `*` as the separator for a valid domain, and also support the new SuiNS display format, based on `@`.
Some examples:
`@test` -> `test.sui`
`sub@test` -> `sub.test.sui`
`inner.sub@test` -> `inner.sub.test.sui`
`more.inner.sub@test` -> `more.inner.sub.test.sui`
All of the above would work with `*` instead of `.` too.
Added a new test file (We didn't have one for the name service). Not sure if this is the right way to test stuff on our crates, so please advise me here if it's not right.
---
If your changes are not user-facing and not a breaking change, you can skip the following section. …

[NameService] Adds support to more input formats

---

crates/sui-core/src/authority.rs

Since average DB reads are around 100us. The LATENCY_SEC_BUCKETS does not give meaningful results since it starts from 500us.
---

Create a LOW_LATENCY_SEC_BUCKETS for DB read histogram

---

external-crates/move/documentation/book/src/SUMMARY.md
external-crates/move/documentation/book/src/index-syntax.md

Add a write-up for index syntax methods for Move 2024 book
👁️ 🔴 👁️  
---

[move-2024] index syntax write-up

---

docker/deterministic-canary/Dockerfile
docker/deterministic-canary/build.sh
docker/sui-node-deterministic/Dockerfile
docker/sui-node-deterministic/build.sh
docker/sui-node/Dockerfile
docker/sui-node/build.sh

output from the canary build
```
=> exporting manifest sha256:2ec436df682191538225be5c30465d3aae75c31f392ac7f84ade5908095c5e7f                                                                                                                                                        
=> => exporting config sha256:02e10b7996825007a153055ac8e441c471a0a73b860c729a32e5229ea9e530e6   
{"schemaVersion":2,"manifests":[{"mediaType":"application/vnd.oci.image.manifest.v1+json","digest":"sha256:2ec436df682191538225be5c30465d3aae75c31f392ac7f84ade5908095c5e7f","size":481,"annotations":{"org.opencontainers.image.created":"1970-01-01T00:00:01Z","org.opencontainers.image.ref.name":"docker.io/library/canary:latest"},"platform":{"architecture":"amd64","os":"linux"}}]}
```
How did you test the new or updated …

docker: add back old sui-node image and add a deterministic canary

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/authority/authority_store_tables.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/passthrough_cache.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-macros/src/lib.rs
crates/sui-node/src/lib.rs
crates/sui-replay/src/replay.rs
crates/sui-snapshot/src/lib.rs
crates/test-cluster/src/lib.rs
crates/typed-store-derive/src/lib.rs

The original table now stores only the "object is live" marker. Actual locks are stored in the new table.

Split object lock table into two tables 

---

crates/sui-benchmark/tests/simtest.rs

The protocol config upgrade compatibility test doesn't allow skipping versions on main.
This makes it difficult to move forward when we want to plan ahead.
This PR fixes that by simply not injecting framework if a snapshot for a version is not found.
---

Allow skip protocol upgrade

---

.github/workflows/simulator-nightly.yml
scripts/simtest/simtest-run.sh

Otherwise people need to make new branches to test changes.
Another changes:
- Allow specifying `MSIM_TEST_NUM` per run.
- Increase time limit to 4hr.
- Do not notify if the run is not a scheduled run.
https://github.com/MystenLabs/sui/actions/runs/8311073333/job/22744289663
---

[CI] support running simtest nightly on a particular commit

---

crates/sui-cluster-test/src/test_case/coin_index_test.rs
crates/sui-json-rpc/src/transaction_builder_api.rs
crates/sui-sdk/examples/tic_tac_toe.rs
crates/sui-transaction-builder/src/lib.rs
crates/sui/src/client_commands.rs
crates/sui/tests/cli_tests.rs

This PR only adds the `gas_price` option in the `sui client call` command.
I can add this option to other `sui client` command if there is a need for it.
---

Allow `sui client call` command to set gas price

---

crates/sui-move/src/new.rs

Following the discussion on scaffolding the app:
- adds `sources/{name}.move`
- adds `tests/{name}_tests.move`
```sh
sources/
donuts.move
tests/
donuts_tests.move
Move.toml
```
File: sources/name.move; Commented out contents:
```move
/// Module: donuts
module donuts::donuts {
}
```
File: tests/name_tests.move; Commented out contents:
```move
#[test_only]
module donuts::donuts_tests {
// uncomment this line to import the module
// use donuts::donuts;
const ENotImplemented: u64 = 0;
#[test]
fun test_donuts() {
// pass
}
#[test, expected_failure(abort_code = donuts::donuts_tests::ENotImplemented)]
fun test_donuts_fail() {
abort ENotImplemented
}
}
```
Tests pass!

[CLI] Adds initial package layout on `sui move new`

---

.github/workflows/simulator-nightly.yml
scripts/simtest/simtest-run.sh

A small followup to #16707, emit more info from the script and only run the determinism test (last step) once.
https://github.com/MystenLabs/sui/actions/runs/8311292117
---

[CI] do not run multiple iterations for the determinism test

---

consensus/config/src/committee.rs
consensus/config/tests/snapshots/committee_test__committee.snap
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs

Committee members should be ordered in the same order as the SUI committee (protocol public key order ascending).
CI
---

[Consensus 2.0] fix mysticeti committee member ordering

---

consensus/core/src/core.rs
consensus/core/src/transaction.rs

The PR is modifying the transaction submission of the transaction client to return only when the transaction has been successfully included to the next block proposal. The `TransactionGuard` struct has been added which is implicitly acknowledging the transaction inclusion once dropped.
CI
---

[Consensus 2.0] acknowledge transaction on submission

---

crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/graphiql_server.rs
crates/sui-json-rpc/src/name_service.rs

Today we have two entrypoints, `start-server` and `from-config`. The former is the standard way we launch the graphql service, by providing a `--config` path to a `.toml` file. The latter is a yaml-based entrypoint. Because we do not use this yaml config, this PR removes yaml-related code to simplify. Also refactors `config.rs` to this order:
1. consts and struct defs
2. impl async-graphql's Object macro
3. impl
4. impl Trait
Note that `NameServiceConfig` has a `domain_type_tag` field that is computed, so it probably won't play nicely with reading from a `.toml` file. I'll address this in a follow-up PR.
Existing
---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes …

[gql][cherry pick]config changes

---

crates/sui-graphql-rpc/src/extensions/timeout.rs
crates/sui-graphql-rpc/src/server/builder.rs

There is only one extension factory per server instance, but a new instance of the extension is created once per query. Using the same type for both of these is confusing.
```
sui$ cargo build -p sui-graphql-rpc
```

[GraphQL/Timeout] Disambiguate extension factory and extension

---

crates/sui-graphql-e2e-tests/README.md
crates/sui-indexer/README.md

v14 doesn't actually work. So it's better to explicitly require 15.
There is also a mistake in the sql command.
The service name isn't correct either.
Run each command locally.
---

A few fixes in the indexer/graphql README

---

crates/sui-single-node-benchmark/src/benchmark_context.rs
crates/sui-single-node-benchmark/src/command.rs
crates/sui-single-node-benchmark/src/lib.rs
crates/sui-single-node-benchmark/src/main.rs
crates/sui-single-node-benchmark/tests/smoke_tests.rs

When forming a cert, properly sign the transaction on the validator.
This will make it possible to measure performance changes with transaction lock cache.
CI
---

[bench] Properly sign transactions in single node benchmark

---

consensus/core/src/core.rs

This PR is fixing the issue of not emitting a new round signal when a new quorum is reached after proposing for a round. This could potentially create a liveness issue under network faults and marginal quorum availability as the leader timeout component would never get signalled about the new round to trigger a new round advancement.
The PR is re-using the `add_accepted_blocks` method to handle this
CI
---

[Consensus 2.0] fix potential liveness issue

---

crates/sui-graphql-rpc/src/extensions/timeout.rs
crates/sui-graphql-rpc/src/server/builder.rs

There is only one extension factory per server instance, but a new instance of the extension is created once per query. Using the same type for both of these is confusing.
```
sui$ cargo build -p sui-graphql-rpc
```

[pick #16720][GraphQL/Timeout] Disambiguate extension factory and extension

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

Remove unused function `multi_get_next_shared_object_versions()`

---

crates/sui-move/src/lib.rs
crates/sui-move/src/migrate.rs
external-crates/move/crates/move-cli/src/base/migrate.rs

What it says on the tin.
Also a small bit of cleanup for `fetch_deps_only` on migration mode, which shouldn't even be an option there,
Local testing, plus 👀 
---
Move migration will be available

[move-2024] Add Move 2024 migration to  `sui move` cli

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_40.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_40.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_40.snap
crates/sui-types/src/transaction.rs

`enable_randomness_ptb_restrictions` is not needed since Random does not yet exist on testnet/mainnet.
(`git cherry-pick 1c60177dcbf876850575c9581f477af7111a6e9d` that removed the unneeded flag in main)
---

Remove unneeded flag enable_randomness_ptb_restrictions (#16715)

---

external-crates/move/crates/move-cli/src/base/test.rs
external-crates/move/crates/move-cli/src/sandbox/utils/mod.rs
external-crates/move/crates/move-compiler/src/command_line/compiler.rs
external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/parser/mod.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-unit-test/src/test_reporter.rs

Arc the strings for file sources inside of `FilesSourcesText` and add a `MappedFiles` struct to manage the file mappings (to be extended and added to over time -- there's places for simplification with this, but that can be done in separate PRs/gradually).
Made sure existing tests all pass + #16659 uses this (this was split off from that).

[move-compiler] Update `FilesSourcesText` to Arc the source

---

bridge/evm/script/deploy_bridge.s.sol
bridge/evm/test/mocks/MockTokens.sol

as title.
(I don't quite like how we handle `supportedTokens` in config, it's quite error-prone)
The reason to print addresses is like in post deployment processing it's easier to grab the addresses from output than anything else.
---

[bridge][solidity] add mockUSDT, fix supportedTokens in deploy script and print addresses

---

external-crates/move/crates/move-cli/src/base/new.rs
external-crates/move/crates/move-cli/tests/build_tests/simple_new/args.exp

Change  default TOML to be 2024 beta
Local testing, plus other tests still work.
---
Changes the default `Move.toml` for `sui move new` and `move new` to use the Move 2024 beta release.

[move-2024] Change  default TOML to be 2024 beta

---

consensus/core/src/authority_node.rs
consensus/core/src/broadcaster.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs

To ensure liveness we should attempt to re-broadcast the last proposed block after recovery if no new one created. This is a fix for the case but a more proper solution should be provided as discussed in the past to ensure re-broadcast of last proposed block under no new round advancement
CI
---

[Consensus 2.0] re-broadcast last proposed block after recover

---

crates/sui-core/src/consensus_manager/mysticeti_manager.rs

This is more consistent with the code structure, and avoids the double "_".
CI
---

[Consensus] use consensus_ as metric prefix

---

Cargo.lock
Cargo.toml
consensus/core/src/broadcaster.rs
scripts/simtest/cargo-simtest
scripts/simtest/config-patch

Blocks get acknowledged before persistence, so it is useful to resend the latest block in case the peer restarted.
CI
---

[Consensus] resend last block to peer when there is no new proposal

---

crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
crates/sui-graphql-rpc/src/metrics.rs
crates/sui-graphql-rpc/src/server/builder.rs

Fix metrics issue with elapsed time not being correctly converted to seconds. It is now standardized everywhere that any elapsed argument should be of type `Duration`, and on that variable we call `as_secs_f64()` to pass it to the prometheus metric.
This should fix the problem with the latency metric in our dashboards.
👀 
---

[graphql] Fix metrics issue with elapsed time not being correct

---

sdk/docs/pages/typescript/cryptography/keypairs.mdx
sdk/docs/pages/typescript/cryptography/multisig.mdx
sdk/docs/pages/typescript/hello-sui.mdx
sdk/docs/pages/typescript/install.mdx
sdk/docs/pages/typescript/sui-client.mdx
sdk/docs/pages/typescript/transaction-building/gas.mdx

Slack message pointed out requestSuiFromFaucetV0 s/b requestSuiFromFaucetV1 and there was a link without a redirect. Updated other links to docs.sui while here.
👀 
---

[docs][sdk] Update links and lib ref

---

crates/sui-graphql-rpc/src/error.rs
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/suins_registration.rs
crates/sui-indexer/src/apis/indexer_api_v2.rs
crates/sui-indexer/src/errors.rs
crates/sui-json-rpc-tests/tests/name_service_tests.rs
crates/sui-json-rpc/src/error.rs
crates/sui-json-rpc/src/indexer_api.rs
crates/sui-json-rpc/src/name_service.rs

Cherry-picks 
1. #15576 
2. #16319 
3. #15466 
in that order to support expiration checks, subdomains, and alternative formats to the existing dot format.
---
---------
---

[gql][cherry pick] suins subdomains

---

crates/sui-indexer/src/apis/write_api.rs

the fast-path opts were needed when we wanted read-after-write consistency, but it's no longer needed and could cause error as described in https://mysten-labs.slack.com/archives/C0578KFD9D2/p1710944999356049
local indexer server and run
---

indexer fix: user input instead of fast-path opts

---

crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
crates/sui-graphql-rpc/src/metrics.rs
crates/sui-graphql-rpc/src/server/builder.rs

Fix metrics issue with elapsed time not being correctly converted to seconds. It is now standardized everywhere that any elapsed argument should be of type `Duration`, and on that variable we call `as_secs_f64()` to pass it to the prometheus metric. This should fix the problem with the latency metric in our dashboards.
👀 
---
---

[graphql][cherry-pick] Fix metrics issue with elapsed time not being correct (#16782)

---

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs

Otherwise we can hit an assert failure if we crash after bumping the checkpoint, but before reconfiguring

Check highest executed checkpoint before beginning epoch

---

crates/sui-graphql-rpc/src/types/available_range.rs
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/digest.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/transaction_block_effects.rs

Implement two separate data loaders -- one for checkpoints by sequence number, and one for checkpoints by digest.
```
```
And test that the following queries runs much faster now:
```graphql
query {
transactionBlocks(last: 50) {
nodes {
effects {
checkpoint {
digest
sequenceNumber
}
}
}
}
}
```
```graphql
query {
c00: checkpoint(id: { digest: "..." }) {
sequenceNumber
}
c01: checkpoint(id: { digest: "..." }) {
sequenceNumber
}
c30: checkpoint(id: { digest: "..." }) {
sequenceNumber
}
}
```

[GraphQL/DataLoader] Checkpoint DataLoader

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

There is no reason to add them one-by-one in-place, from both consensus transaction and owned object transaction path.
In fact, in the end we will have all transactions to be scheduled. We can add them all in one function in the end.
This makes this piece of code slightly simpler.
CI
---

Simplify finish_consensus_certificate_process_with_batch

---

crates/sui-graphql-rpc/src/types/available_range.rs
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/digest.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/transaction_block_effects.rs

Implement two separate data loaders -- one for checkpoints by sequence number, and one for checkpoints by digest.
```
```
And test that the following queries runs much faster now:
```graphql
query {
transactionBlocks(last: 50) {
nodes {
effects {
checkpoint {
digest
sequenceNumber
}
}
}
}
}
```
```graphql
query {
c00: checkpoint(id: { digest: "..." }) {
sequenceNumber
}
c01: checkpoint(id: { digest: "..." }) {
sequenceNumber
}
c30: checkpoint(id: { digest: "..." }) {
sequenceNumber
}
}
```

[pick #16783][GraphQL/DataLoader] Checkpoint DataLoader

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs

I found that it would cause quick OOM when indexer has many objects to resolve, although many object types are the same, so this PR improves that by only resolving unique struct tags.
on rpc-benchmark, run with this PR and the OOM gets much better
although on some huge checkpoints of size 50MB+, oom still happens a couple of times (with a solution in a coming PR).
---

indexer: optimize memory usage of move struct layout resolution

---

docs/content/guides/developer/first-app/publish.mdx

Example code swapped the ordering of `to_address` and the parameters as a result of https://github.com/MystenLabs/sui/pull/16566 
Visual inspection
---

[docs] ptb transfer object ordering were swapped

---

crates/sui-data-ingestion-core/src/worker_pool.rs

In the data ingestion workers, when send channels return `Err` it is a sign the processing pipeline is being closed, but right now this can lead to panics due to the use of `expects`. This PR replaces these with break or return statements, and ensures that all workers are finished before returning.
Unit tests are run.

fix: Graceful shutdown of pool workers in data ingestion framework

---

external-crates/move/crates/move-compiler/src/editions/mod.rs
external-crates/move/crates/move-compiler/tests/move_check_testsuite.rs
external-crates/move/crates/move-symbol-pool/src/lib.rs

Adds a development edition for the Move source language. Will be useful for future source language developments so we can land and test them before exposing them to developers.
Ensure existing tests pass.

[move][easy] Add a development edition for Move source language

---

.github/workflows/mysticeti.yml
.github/workflows/rust.yml
.github/workflows/trigger-builds.yml

This gives us early signals on test failures with Mysticeti.
Also, run Rust and Mysticeti tests on release branches.
CI
---

[CI] run mysticeti workflow on PR

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/shared_object_version_manager.rs

This PR moves all the shared object version calculation logic out to a separate file.
Previously we would accumulate shared object version assignment one by one as we process each transaction.
This PR changes it such that we simply process all of them in the end when we have the list of verified transactions.
This has a few benefits:
1. It simplifies the consensus transaction processing
2. Makes it easier to reason about the version assignment logic
3. Allows better code sharing (this will be needed in the benchmark)
4. A side benefit is that we could also batch assign version for a vector of effects from checkpoint_executor
CI
---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under …

Add shared object version manager

---

docs/content/guides/operator/sui-full-node.mdx

Update our docs with the list of new 3rd party ssfns
Going to test each ssfn independently
---

update fullnode spec to use mysten + external ssfns instead of mysten-only

---

consensus/core/src/dag_state.rs
consensus/core/src/metrics.rs

Add metrics for
- highest accepted round
- commit round advancement interval
The commit round advancement interval is the same as commit interval right now with one leader per round. But in future with multiple leaders per round, the round advancement interval will match up with Sui checkpoint interval more closely.
CI
---

[Consensus] add metrics

---

.github/workflows/turborepo.yml

Raise audit level to high which seems like a much more sensible default based on this: https://docs.npmjs.com/about-audit-reports
---

Raise audit level

---

crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/graphiql_server.rs
crates/sui-graphql-rpc/src/server/version.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
sdk/graphql-transport/test/compatability.test.ts

Add the build sha into the existing version header.
👀 
```bash
🚀 sui-graphql-rpc % curl -i -X POST http://127.0.0.1:8000 --data '{"query": "query {chainIdentifier}"}'
HTTP/1.1 200 OK
content-type: application/json
content-length: 39
x-sui-rpc-version: 2024.2.0-17a173450a86f16b06b5818f21397b808adb2d8c
access-control-allow-origin: *
vary: origin
vary: access-control-request-method
vary: access-control-request-headers
date: Thu, 21 Mar 2024 01:43:28 GMT
```
---

[graphql] Add build sha as a header

---

crates/sui-framework/docs/sui-system/genesis.md
crates/sui-framework/docs/sui-system/stake_subsidy.md
crates/sui-framework/docs/sui-system/staking_pool.md
crates/sui-framework/docs/sui-system/storage_fund.md
crates/sui-framework/docs/sui-system/sui_system.md
crates/sui-framework/docs/sui-system/sui_system_state_inner.md
crates/sui-framework/docs/sui-system/validator.md
crates/sui-framework/docs/sui-system/validator_cap.md
crates/sui-framework/docs/sui-system/validator_set.md
crates/sui-framework/docs/sui-system/voting_power.md
crates/sui-framework/packages/sui-system/sources/genesis.move
crates/sui-framework/packages/sui-system/sources/stake_subsidy.move
crates/sui-framework/packages/sui-system/sources/staking_pool.move
crates/sui-framework/packages/sui-system/sources/storage_fund.move
crates/sui-framework/packages/sui-system/sources/sui_system.move
crates/sui-framework/packages/sui-system/sources/sui_system_state_inner.move
crates/sui-framework/packages/sui-system/sources/validator.move
crates/sui-framework/packages/sui-system/sources/validator_cap.move
crates/sui-framework/packages/sui-system/sources/validator_set.move
crates/sui-framework/packages/sui-system/sources/validator_wrapper.move
crates/sui-framework/packages/sui-system/sources/voting_power.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

This updates the `sui-system` library to use method syntax.
No new use funs.
Tests still work, plus manual bytecode diffing between old and new versions.
---

[move-2024] Add method syntax to `sui-system`

---

crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/graphiql_server.rs
crates/sui-graphql-rpc/src/server/version.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs

Add the build sha into the existing version header.
👀
```bash
🚀 sui-graphql-rpc % curl -i -X POST http://127.0.0.1:8000 --data '{"query": "query {chainIdentifier}"}'
HTTP/1.1 200 OK
content-type: application/json
content-length: 39
x-sui-rpc-version: 2024.2.0-17a173450a86f16b06b5818f21397b808adb2d8c
access-control-allow-origin: *
vary: origin
vary: access-control-request-method
vary: access-control-request-headers
date: Thu, 21 Mar 2024 01:43:28 GMT
```
---

[graphql][cherry-pick] Cherry pick build sha PR

---

crates/sui-framework/packages/move-stdlib/tests/ascii_tests.move
crates/sui-framework/packages/move-stdlib/tests/bit_vector_tests.move
crates/sui-framework/packages/move-stdlib/tests/fixedpoint32_tests.move
crates/sui-framework/packages/move-stdlib/tests/option_tests.move
crates/sui-framework/packages/move-stdlib/tests/string_tests.move
crates/sui-framework/packages/move-stdlib/tests/vector_tests.move

Title
Note that the vector tests changed around quite a bit in the generated bytecode. I hand-checked that it appears to perform the same, but the usage of `vector[]` changes things quite a bit.
`sui move test` plus local disassembly diff
---

[move-2024] Add method syntax to Move stdlib tests

---

crates/sui-data-ingestion/src/workers/archival.rs

if the data ingestion daemon restarts on an epoch boundary, and the first checkpoint/task afterward is the beginning of a new epoch, the daemon uses incorrect epoch value from the archival MANIFEST(i.e. previous epoch)

[data ingestion] archival workflow: ensure correct epoch on restart

---

external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/typing/all_index_paths.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/all_index_paths.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/const_method_subject.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/const_method_subject_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/const_method_subject_invalid.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/implicit_const_copy_method.exp

This allows constants to be used in some positions that were previously errors.
New and updated tests
---

Allow constants as standalone value paths

---

crates/sui-indexer/src/db.rs
crates/sui-indexer/src/framework/builder.rs
crates/sui-indexer/src/framework/fetcher.rs
crates/sui-indexer/src/framework/runner.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

the checkpoint size varies a lot and as a result, it's challenging to find a static batch size for indexing;
from the experiment, batch size of 10 would still sometimes go OOM, thus this PR introduces a dynamic way of adjusting the batch size based on the downloaded checkpoint data size.
experiment on rpc-benchmark.
---

indexer: dynamically adjust index batch size to avoid oom

---

crates/sui-framework/packages/sui-system/sources/staking_pool.move
crates/sui-framework/packages/sui-system/tests/delegation_tests.move
crates/sui-framework/packages/sui-system/tests/governance_test_utils.move
crates/sui-framework/packages/sui-system/tests/rewards_distribution_tests.move
crates/sui-framework/packages/sui-system/tests/sui_system_tests.move
crates/sui-framework/packages/sui-system/tests/validator_set_tests.move
crates/sui-framework/packages/sui-system/tests/validator_tests.move
crates/sui-framework/packages/sui-system/tests/voting_power_tests.move

Plus some use funs
Tests still pass. Binary diffing is the same, except for `sui_system_tests.move` which differs only in its ascii call usage.
---

[move-2024] Update sui system tests to Move 2024 / Method Syntax

---

Cargo.lock
crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/crypto.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/server/governance_verifier.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/server/mod.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-bridge/src/types.rs
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/sui-genesis-builder/src/lib.rs
crates/sui-types/Cargo.toml
crates/sui-types/src/bridge.rs
sui-execution/latest/sui-adapter/src/execution_engine.rs

1, introduce a few more constants and move things to sui-types/bridge.rs
2, relax the total voting power = 10k requirement, in case of not all validators opt in.
---

[bridge 48/n] types: introduce a few more constants and move things to sui-types/bridge.rs

---

Cargo.lock
Cargo.toml
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/client/bridge_authority_aggregator.rs
crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/crypto.rs
crates/sui-bridge/src/server/governance_verifier.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/storage.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-bridge/src/types.rs
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/sui-types/src/bridge.rs
crates/test-cluster/Cargo.toml
crates/test-cluster/src/lib.rs

reimplement `get_token_transfer_action_onchain_status` with dev_inspect
---

[bridge 49/n] use devInpsect to get on chain status

---

crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
crates/sui-storage/tests/key_value_tests.rs
crates/sui-types/src/effects/effects_v2.rs
crates/sui-types/src/effects/mod.rs
crates/sui-types/src/effects/test_effects_builder.rs
crates/sui-types/src/messages_checkpoint.rs
crates/sui-types/src/unit_tests/messages_tests.rs

Add a builder to create test effects from transactions. This will make it easier to test some components.
CI
---

Add TestEffectsBuilder

---

crates/sui-json-rpc/src/lib.rs

Support indexer listening on `/public` (json-rpc) and sui-node listening on `/subscribe` (websockets).
- testing existing and new json-rpc routes (with indexer and sui-node):
```
curl -w "%{http_code}" http://localhost:9000/ -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0", "method":"sui_getObject", "params":["0x2"], "id":1}'
{"jsonrpc":"2.0","result":{"data":{"objectId":"0x0000000000000000000000000000000000000000000000000000000000000002","version":"1","digest":"7WbYdh6bcvniPfyZjUnjoLziM1KYuqEreRv5CFBYxXBS"}},"id":1}200%
```
```
% curl -w "%{http_code}" http://localhost:9000/json-rpc -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0", "method":"sui_getObject", "params":["0x2"], "id":1}'
{"jsonrpc":"2.0","result":{"data":{"objectId":"0x00000000000000000000000000000000000000000 …
```

add new rpc routes

---

crates/sui-bridge/src/sui_transaction_builder.rs

[bridge 52/n] support build sui transaction for committee blocklist update

---

crates/sui-bridge/abi/bridge_committee.json
crates/sui-bridge/abi/bridge_config.json
crates/sui-bridge/abi/bridge_limiter.json
crates/sui-bridge/abi/bridge_vault.json
crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/crypto.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-bridge/src/types.rs

Use the latest abi from solidity and update the structs
---

[bridge 56/n] update abi and eth event structs

---

Cargo.lock
crates/sui-bridge/Cargo.toml
crates/sui-bridge/src/encoding.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/types.rs

For reviewers: not much to read in this PR, mostly moving things around.
---

[bridge 57/n] enum-dispatch BridgeActions and move encoding logic to its own file

---

Cargo.lock
crates/sui-bridge/Cargo.toml
crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/encoding.rs
crates/sui-bridge/src/eth_transaction_builder.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/types.rs

This PR adds ethereum transaction building and message conversion.
---

[bridge 58/n] handle eth message conversion and transaction builder

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/address.rs
crates/sui-graphql-rpc/src/types/coin.rs
crates/sui-graphql-rpc/src/types/coin_metadata.rs
crates/sui-graphql-rpc/src/types/move_object.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/src/types/suins_registration.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-json-rpc-tests/tests/name_service_tests.rs
crates/sui-json-rpc/src/name_service.rs

Adds optional support for "@"(at) format naming in GraphQL.
Using this, you can get the default name in two formats:
1. Dot style: `manos.sui`
2. At style: `@manos`
Defaults to `dot` style for now. We wanna make the At style the default, but this would be a breaking change.
Tested the output conversions through unit tests.
Tested it live locally using mainnet.
---

[NameService][GraphQL] Adds support to @ (at) format output.

---

crates/sui/src/client_commands.rs

Adding a couple of features to the `verify-bytecode-meter` command:
- Specify a `--module` (as bytecode) to verify.
- Specify a protocol version to verify at.
Also switches the `--package` path from a positional parameter to a flag, for symmetry with the new `--module` flag.
```
sui-framework/deepbook$ cargo run --bin sui -- \
client verify-bytecode-meter
sui-framework/deepbook$ cargo run --bin sui -- \
client verify-bytecode-meter --package .
sui-framework/deepbook$ cargo run --bin sui -- \
move build
sui-framework/deepbook$ cargo run --bin sui -- \
client verify-bytecode-meter --module build/DeepBook/bytecode_modules/clob.mv
sui-framework/deepbook$ cargo run --bin sui -- \ # Errors
client verify-bytecode-meter --package '.'   \
--module build/DeepBook/bytecode_modules/clob.mv
```
---
If …

[CLI] Add ability to run verifier on an individual module

---

crates/sui/src/client_commands.rs
sui-execution/src/latest.rs
sui-execution/src/v0.rs
sui-execution/src/v1.rs
sui-execution/src/v2.rs

We were returning the ticks used for the last function as the verifier ticks, which is not correct.  Returning the ticks used for the last function is also not particularly useful, but I will fix that in a follow-up PR.
```
sui-framework/deepbook$ cargo run --bin sui -- \
client verify-bytecode-meter
Total number of linter warnings suppressed: 3 (filtered categories: 2)
Running bytecode verifier for 7 modules
╭──────────────────────────────────╮
│ Module will pass metering check! │
├────────┬────────────┬────────────┤
│        │ Module     │ Function   │
│ Max    │ 16000000   │ 16000000   │
│ Used   │ 5869980    │ 7040       │
╰────────┴────────────┴────────────╯
```
- #16899 
---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, …

[BUGFIX][CLI] verify-bytecode-meter returns module ticks

---

crates/sui/src/client_commands.rs
crates/sui/src/client_ptb/ast.rs
crates/sui/src/client_ptb/parser.rs
crates/sui/src/client_ptb/ptb.rs
crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_commands.snap
crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_publish.snap
crates/sui/src/lib.rs

Add support for the `serialize-signed-transaction` and `serialize-unsigned-transaction` flags that output transaction bytes instead of executing the transaction for the `sui client ptb` command.
Existing tests as this uses the `serialize-or-execute` macro.
---
Added support for the `serialize-signed-transaction` and `serialize-unsigned-transaction` flags that output transaction bytes instead of executing the transaction for the `sui client ptb` command.

[cli][easy] Add serialize-signed-transaction and serialize-unsigned transaction flags for sui client ptb command

---

.github/workflows/mysticeti.yml
.github/workflows/rust.yml
crates/sui-bridge/build.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/tools/cli.rs
crates/sui-bridge/src/utils.rs
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/test-cluster/src/lib.rs

This PR does two things:
1. make `bridge_client_gas_object` in BridgeConfig optional. If no gas object is provided, then we look for any gas object owned by the client address.
2. add tests for starting bridge node.
3. move key generation helper functions to `crates/sui-bridge/src/utils.rs`
---

[bridge 62/n] make `bridge_client_gas_object` optional, add tests for starting bridge node

---

crates/sui-indexer/src/indexer_reader.rs

indexer cursor should always be exclusive so that when the iteration reaches the end, it can keep retrying with the same cursor until new items arrive and no duplicate items will be returned.
Pavlos found this on the DF fields method and I searched the indexer_reader file and made sure that we do not have `.ge(` or `.le(` any more.
CI
---

indexer fix: cursor should be exclusive

---

crates/sui-framework/docs/deepbook/clob_v2.md
crates/sui-framework/packages/deepbook/sources/clob_v2.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Validation for get_level2_book_status_bid(ask)_side for price_low, price_high inputs.
Testnet deepbook pool testing
---
Bug fix for rounding error in Deepbook accessor function (read only), which returns level 2 book data within price range

fix: level2 book status validation

---

crates/sui-indexer/src/indexer_reader.rs

indexer cursor should always be exclusive so that when the iteration reaches the end, it can keep retrying with the same cursor until new items arrive and no duplicate items will be returned.
Pavlos found this on the DF fields method and I searched the indexer_reader file and made sure that we do not have `.ge(` or `.le(` any more.
CI
---
---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release …

indexer fix: cursor should be exclusive (#16925)

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/move-2024/Move.toml
external-crates/move/crates/move-analyzer/tests/move-2024/sources/implicit_uses.move

This is a small fix that ensures symbolicator works correctly with implicit uses.
Added a new test

[move-ide] A fix to support implicit uses

---

crates/sui-framework/docs/bridge/committee.md
crates/sui-framework/packages/bridge/sources/committee.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

As reported by audit if a validator registers with an already used pubkey for the bridge (whether maliciously or not) the creation of the committee will fail and as such an end of epoch would fail attempting to create the committee.
Moreover there is no way at the moment to flush the proposed committee (in that respect, should we have an API for it?) and it would require an emergency release to take care of the problem.
This should prevent the problem from happeing.
Added unit test
---

Fix audit feedback on committee creation

---

crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/crypto.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/encoding.rs
crates/sui-bridge/src/error.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/server/mod.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-bridge/src/tools/mod.rs
crates/sui-bridge/src/types.rs
crates/sui-types/src/bridge.rs

To unblock token flow, in this PR we change the usage of TokenID enum to u8.
---

[bridge 65/n] change tokenId from enum to u8, to prepare for the add token flow

---

crates/sui-core/src/authority.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/state_accumulator.rs
crates/sui-node/src/lib.rs
crates/sui-snapshot/src/tests.rs
crates/sui-snapshot/src/uploader.rs
crates/sui-snapshot/src/writer.rs

During snapshot write, we iterate through the live object set. Later, a reader downloads and verifies. If there is an inconsistency in the write path, we will learn about it too late, so let's verify during the write stage.
Running https://github.com/MystenLabs/sui/pull/16914/commits against R2 mainnet snapshot writer. [This workflow run](https://github.com/MystenLabs/sui-operations/actions/runs/8474730636) shows that the snapshot exists and we were able to restore from it
---

[formal-snasphots] Verify on write

---

bridge/evm/contracts/BridgeCommittee.sol
bridge/evm/contracts/BridgeConfig.sol
bridge/evm/foundry.toml
bridge/evm/script/deploy_bridge.s.sol
bridge/evm/test/BridgeBaseTest.t.sol
bridge/evm/test/BridgeCommitteeTest.t.sol
bridge/evm/test/BridgeConfigTest.t.sol
bridge/evm/test/mocks/MockSuiBridgeV2.sol
bridge/evm/test/mocks/MockTokens.sol

1. update signature verification to revert with duplicate, and invalid signatures instead of skipping.
2. include verification of provided "Sui Decimals" in Add EVM Token message function.

Signature verification and add token message verification

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/storage.rs

When the node restarts, we read pending actions from DB and send to executor to resume them.
meat is in `crates/sui-bridge/src/orchestrator.rs`
---

[bridge 66/n] resume pending actions when node restarts

---

Cargo.lock
crates/mysten-service-boilerplate/Cargo-sui.toml
crates/mysten-service-boilerplate/Cargo.toml
crates/suiop-cli/src/cli/service/init.rs

cargo-sui is for the sui repo, the base cargo.toml is for external use
functions as expected
---

[suiop] fix cargo configuration to work for sui repo and externally

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/move-2024/sources/structs.move

This PR adds IDE support for Move 2024 structs:
- positional fields
- public visibility modifier
A new test has been added

[move-ide] Updates to support Move 2024 structs

---

crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Audit found that `send_token` was not checking for valid routes. 
Added the missing check
Added unit tests.
Positive tests (no abort) for `send_token` are a bit trickier and will be added when unit test review is done. They were not there so this is not a regression in tests.
---

Check bridge routes on send token

---

crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

More on audit feedback. Renaming as in the TODOs and invariants pulled at the entry of the function.
`approve_bridge_message` has been renamed to `approve_token_transfer` and invariants have been pulled all the way up to the entry. You'll notice that because of that, the logic of the function changed a bit, both in terms of errors and in terms of what gets executed unconditionally.
I think it's fine, but please review 
Unit tests
---

More audit, rename and invariants

---

crates/sui-framework/docs/bridge/committee.md
crates/sui-framework/packages/bridge/sources/committee.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Found from audit, we need to reset the start of the loop when looking for members
Added unit test
---

Reset index in loop to restart member search

---

crates/sui-tool/src/commands.rs

@tharbert noticed `sui-tool download-db-snapshot` doesn't currently work against our requester pays bucket. this fixes the problem.
I'll cherry-pick this fix so it's included in the next release and doesn't break @tharbert's statefulset

unblock sui-tool download-db-snapshot

---

Cargo.lock
crates/sui-core/benches/batch_verification_bench.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/signature_verifier.rs
crates/sui-core/src/unit_tests/batch_verification_tests.rs
crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-e2e-tests/tests/zklogin_tests.rs
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_42.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_42.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_42.snap
crates/sui-types/src/multisig.rs
crates/sui-types/src/multisig_legacy.rs
crates/sui-types/src/signature.rs
crates/sui-types/src/transaction.rs
crates/sui-types/src/unit_tests/multisig_tests.rs
crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs
crates/sui-types/src/zk_login_authenticator.rs
crates/sui/src/keytool.rs
sdk/typescript/package.json
sdk/typescript/test/e2e/multisig.test.ts

currently a zklogin sig is valid as long as max_epoch is larger than current epoch. this adds a protocol config that the max_epoch cannot be too large, the config sets the upper bound to 30 + current epoch. 
based on new testing framework in simtest only. 
simtest
---
Protocol version upgrades to 42. This adds a feature flag to set the upper bound of the max epoch for a zklogin signature.

feat: add upper bound for max epoch in zklogin sig

---

crates/sui-faucet/src/faucet/simple_faucet.rs

IIUC there is no internal queue in faucet for available gas coins, so there should not be more requests to faucet in parallel than the # of gas coins.
CI
---

[Faucet][test] issue one request per gas coin in parallel

---

crates/sui-indexer/src/framework/fetcher.rs

this was found in incident inc_mainnet_wallet_latencies_2058 and patching this PR reduced the FN -> indexer lagging from ~10s to near realtime, more details can be found in the incident channel.
CI and incident deployment
---

indexer fetcher: configurable interval and set default to 0.5s

---

Cargo.lock
crates/data-transform/src/main.rs
crates/sui-analytics-indexer/src/handlers/mod.rs
crates/sui-core/src/unit_tests/subscription_handler_tests.rs
crates/sui-graphql-rpc/src/types/move_value.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-indexer/src/models/events.rs
crates/sui-json/src/lib.rs
crates/sui-replay/src/displays/transaction_displays.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
crates/sui-types/src/event.rs
crates/sui-types/src/object.rs
crates/sui-types/src/object/balance_traversal.rs
crates/sui-types/src/object/bounded_visitor.rs
external-crates/move/Cargo.lock
external-crates/move/Cargo.toml
external-crates/move/crates/move-core-types/Cargo.toml
external-crates/move/crates/move-core-types/src/annotated_value.rs
external-crates/move/crates/move-core-types/src/annotated_visitor.rs
external-crates/move/crates/move-core-types/src/lib.rs
external-crates/move/crates/move-core-types/src/unit_tests/mod.rs
external-crates/move/crates/move-core-types/src/unit_tests/visitor_test.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v0/sui-move-natives/src/test_scenario.rs
sui-execution/v1/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v1/sui-move-natives/src/test_scenario.rs
sui-execution/v2/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v2/sui-move-natives/src/test_scenario.rs

Adds a visitor for annotated Move values (finally!) 🙂 
Added additional tests + make sure CI passes. 
---

[move] Visitor trait for annotated Move values

---

Cargo.lock
crates/data-transform/src/main.rs
crates/sui-analytics-indexer/src/handlers/mod.rs
crates/sui-core/src/unit_tests/subscription_handler_tests.rs
crates/sui-graphql-rpc/src/types/move_value.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-indexer/src/models/events.rs
crates/sui-json/src/lib.rs
crates/sui-replay/src/displays/transaction_displays.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
crates/sui-types/src/event.rs
crates/sui-types/src/object.rs
crates/sui-types/src/object/balance_traversal.rs
crates/sui-types/src/object/bounded_visitor.rs
external-crates/move/Cargo.lock
external-crates/move/Cargo.toml
external-crates/move/crates/move-core-types/Cargo.toml
external-crates/move/crates/move-core-types/src/annotated_value.rs
external-crates/move/crates/move-core-types/src/annotated_visitor.rs
external-crates/move/crates/move-core-types/src/lib.rs
external-crates/move/crates/move-core-types/src/unit_tests/mod.rs
external-crates/move/crates/move-core-types/src/unit_tests/visitor_test.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v0/sui-move-natives/src/test_scenario.rs
sui-execution/v1/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v1/sui-move-natives/src/test_scenario.rs
sui-execution/v2/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v2/sui-move-natives/src/test_scenario.rs

Adds a visitor for annotated Move values (finally!) 🙂 
Added additional tests + make sure CI passes. 
---
---

[move] Visitor trait for annotated Move values (#16994) 

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/move-2024/sources/let_mut.move

This PR adds support for displaying mutability annotations for parameters and local variables added in Move 2024.
A new test has been added.

[move-ide] Added support for mutability annotations

---

.github/workflows/mysticeti.yml
.github/workflows/rust.yml

When a simtest is flaky, unrelated PRs can encounter failures which cannot be easily reproduced locally or in simtest nightly. It doesn't seem productive to block the PR submission in this case.
CI
---

[CI] use seed specific to commit for Mysticeti simtest

---

crates/sui-move-build/src/lib.rs
crates/sui-move/src/build.rs
crates/sui/src/client_commands.rs
external-crates/move/crates/move-package/src/lib.rs
external-crates/move/crates/move-package/tests/test_lock_file.rs

Ensures toolchain versioning records `edition`/`flavor` derived from `Move.toml` when available. This was not the case before, because I was under the impression that `BuildConfig` reflects the current edition ([source and comment](https://sourcegraph.com/github.com/MystenLabs/sui@ed652f36766c4dec90de307278d64528b1697624/-/blob/external-crates/move/crates/move-package/src/compilation/compiled_package.rs?L71-72)) but this is not the case: [`compiler_config`](https://sourcegraph.com/github.com/MystenLabs/sui@ed652f36766c4dec90de307278d64528b1697624/-/blob/external-crates/move/crates/move-package/src/resolution/resolution_graph.rs?L522) is really the function that merges both `BuildConfig` flags (specified on the command line) and `Move.toml` with edition. The result of that computation …

move lock: derive toolchain edition and flavor from manifest

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-types/src/effects/test_effects_builder.rs

Adds caching for the rest of the non-object transaction outputs

Implement caching for transactions, effects, and events

---

crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-e2e-tests/tests/full_node_tests.rs
crates/sui-single-node-benchmark/src/benchmark_context.rs

- revert_state_update may be called for transactions that have not been
executed
- force_reload_system_packages was not only unnecessary, but harmful, as
it reloaded stale state from the db

WritebackCache bugfixes

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_42.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_43.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_43.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_42.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_43.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

```
eugene@eugene-dev ~/code/sui (bump-protocol-config) $ ./scripts/compatibility/check-protocol-compatibility.sh testnet
Found following versions on testnet:
40 1.22.0-036299745992
25 1.21.1-5f2bfb15ea0a
20 1.22.0-0362997459
8 1.21.1-5f2bfb15ea
1 1.21.1-cf708afc5fe9
Using most frequent version 1.22.0-036299745992 for compatibility check
Checking protocol compatibility with testnet (036299745992)
Checking out testnet snapshot files
Checking for changes to snapshot files matching *__Testnet_version_*
HEAD is now at b8435cf3b8 chore: update protocol config
Running snapshot tests...
Compiling syn v2.0.48
Compiling syn v1.0.107
Compiling darling_core v0.14.2
Compiling serde_derive_internals v0.26.0
Compiling sui-protocol-config-macros …
```

chore: update protocol config

---

external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/typing/dot_call_private_field.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/borrow_field_internal.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/implicit_deref_borrow_field_internal.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/mutate_field_internal.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/native_structs_pack_unpack.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/unused_struct_field.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/unused_struct_field.unused.exp

Attempts to make the error message for an invalid field access (outside of the declaring module) a bit nicer and easier to understand.
Updated existing tests.
---
Made error messages for accessing struct fields outside of the declaring module nicer.

[move] Make error message for invalid field access nicer

---

Cargo.lock
consensus/core/Cargo.toml
consensus/core/build.rs
consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/broadcaster.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/lib.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/network/tonic_network.rs
consensus/core/src/synchronizer.rs

This is the first PR of the streaming implementation. Tonic streaming, and streaming support in `AuthorityService` are implemented.
But block propagation with tonic is still using unary RPC. It will switch to use streaming after adding client side logic for block subscription in future.
CI
---

[Consensus] add streaming support to tonic network

---

Cargo.lock

Fix to:
```
error[vulnerability] Degradation of service in h2 servers with CONTINUATION Flood
```
`cargo deny check advisories` must pass

Update h2 to 0.3.26

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_store_pruner.rs
crates/sui-core/src/db_checkpoint_handler.rs
crates/sui-core/src/execution_cache/passthrough_cache.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-tool/src/db_tool/db_dump.rs

The PR adds a smoothing option to the objects pruner. 
The implementation is very basic: the pruner aims to clear the backlog over the course of one epoch. 
On every tick (which is around 1 minute by default), it calculates the appropriate delta to prune. 
The delta is calculated as 
`(last_executed_checkpoint - last_pruned_checkpoint) / number_of_tick_intervals_per_epoch`

[pruner] add smoothing option

---

crates/sui-core/src/quorum_driver/mod.rs

Log every settlement finality. This is a small overhead given that it's just one extra log line per finalized transaction. Log whether it's a single_writer transaction as well. This will help eye ball transactions for regressions.
CI
---

Better settlement finality logging

---

scripts/compatibility/check-protocol-compatibility.sh

* Making protocol compatibility script more verbose when a failure occurs since it does not output the source commit on main and or release branches
* Remove hacky code
```
eugene@eugene-dev ~/code/sui/ (ebmifa/make_protocol_compotibility_script_more_verbose) $ ./scripts/compatibility/check-protocol-compatibility.sh mainnet
Found following versions on mainnet:
80 1.21.1-a67a73bcfab3
34 1.21.1-a67a73bcfa
1 1.21.1-3b488a9df005
Using most frequent version 1.21.1-a67a73bcfab3 for compatibility check
Source commit: c2c22e7e9f0b56a16cc54dde46d537f0658e72ea
Source branch: ebmifa/make_protocol_compotibility_script_more_verbose
Checking protocol compatibility with mainnet (a67a73bcfab3)
Checking out mainnet snapshot files
Checking for changes to snapshot files matching *__Mainnet_version_*
HEAD is …
```

Making protocol compatibility script more verbose

---

scripts/release_notes.py

Script extracts release notes in the new format where a single PR can contain different breaking changes for each functional area
Tested manually against a set of local commits.
Example output from `generate` command:
```
Sui Protocol Version in this release: 43
https://github.com/MystenLabs/sui/pull/42:
Bumped protocol version to 42
https://github.com/MystenLabs/sui/pull/9001:
You get a release note
https://github.com/MystenLabs/sui/pull/44:
https://github.com/MystenLabs/sui/pull/9001:
You get a release note
https://github.com/MystenLabs/sui/pull/42:
Made some sweeping changes, to:
- Foo
- Bar
https://github.com/MystenLabs/sui/pull/9001:
Everybody gets release notes
```
Example output from `check` command (if there are issues):
```
Found issues with release notes in …
```

[Release Notes] Script to extract release notes in the new format

---

external-crates/move/crates/move-compiler/src/naming/translate.rs

- Switched unscoped_types and locals to doing O(n) lookups instead of O(n) clones
- ran tests
---

[move-compiler] Reduce clones in favor of linked-list scopes

---

crates/sui-framework-tests/src/metered_verifier.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_43.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_43.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_43.snap
crates/sui-types/src/metrics.rs
crates/sui/src/client_commands.rs
external-crates/move/crates/move-bytecode-verifier-meter/src/bound.rs
external-crates/move/crates/move-vm-config/src/verifier.rs
sui-execution/latest/sui-adapter/src/adapter.rs
sui-execution/latest/sui-verifier/src/meter.rs

The motivation for this change is to properly track the modules being visited in the `Meter`, so that in our command line tool, we can provide an output that correctly tracks how many meter ticks were used to verify each function and module.
Prior to this change, the metered verifier pretended like there was only "one module" that all the functions being verified were in. This change introduces the level of packages that ticks from modules are transferred to.
We also add an explicit protocol config parameter to set a max tick limit per package (whose value is the same as the function and module level limits currently). This was not strictly necessary but was done to avoid confusion (caused by treating the module level limit as the package level limit).
This should be a behaviour …

[Verifier/Meter] Transfer module meter to package meter

---

crates/sui-snapshot/src/uploader.rs

In state snapshot uploader, we want to drop success marker in db checkpoints which already have state snapshot. This will unblock db checkpoint to not wait indefinitely if state snapshots already exist

Drop marker in db checkpoint which has state snapshot

---

.changeset/sweet-gorillas-remember.md
sdk/enoki/src/EnokiFlow.ts

This was missing from the `EnokiFlow` APIs, adding in a couple places to fix this.
---

Add missing network param to EnokiFlow

---

external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/tests/move_2024/parser/complex_as.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/complex_as.move
external-crates/move/crates/move-compiler/tests/move_2024/parser/positional_struct_explicit_type_args.exp

This undoes some of the opinionated parsing introduced in #16922 
Test updates, plus a new one.
---

[move-2024] Allow spacing in some type argument positions

---

docs/content/guides/developer/getting-started/sui-environment.mdx

Updated IDE installation instructions by linking the recommended VSCode extension and removing move-analyzer installation instructions which are no longer necessary as the extension bundles it automatically. I think leaving them there, while potentially useful, would be confusing - instructions on how to install move-analyzer by-hand are included in the extension's troubleshooting guide in the VS Marketplace.

[docs] Updated IDE installation instructions

---

crates/sui/src/client_commands.rs
crates/sui/src/lib.rs
crates/sui/src/verifier_meter.rs

Use a custom meter to track every function and module that is verified, and display all of them.
```
deepbook$ cargo run --bin sui -p sui \
-- client verify-bytecode-meter    \
--module build/DeepBook/bytecode_modules/math.mv
╭──────────────────────────────────────╮
│ Package will pass metering check!    │
├──────────────────────────────────────┤
│ Limits                               │
├─────────────────────────┬────────────┤
│ packages                │ 16,000,000 │
│   modules               │ 16,000,000 │
│     functions           │ 16,000,000 │
├─────────────────────────┴────────────┤
│ Ticks Used                           │
├─────────────────────────┬────────────┤
│ <unknown>               │     41,915 │
│   math                  │     41,915 │
│     unsafe_mul          │      1,225 │ …
```

[Verifier] verify-bytecode-meter prints module/function breakdown

---

crates/sui/src/main.rs

Previously the replay-batch command output was not getting printed to the console because the wrong log level was set. This fixes the level.
---

allow output for command output for batch replay

---

Cargo.lock
Cargo.toml
crates/sui-analytics-indexer/Cargo.toml
crates/sui-security-watchdog/Cargo.toml
crates/sui-security-watchdog/README.md
crates/sui-security-watchdog/src/lib.rs
crates/sui-security-watchdog/src/main.rs
crates/sui-security-watchdog/src/metrics.rs
crates/sui-security-watchdog/src/pagerduty.rs
crates/sui-security-watchdog/src/query_runner.rs
crates/sui-security-watchdog/src/scheduler.rs

This PR adds a crate whic downloads a github repo to read a config file with queries (repo will have limited access and enables peer review before any modification), parses the config file for queries and their schedules, and reports data back to prometheus by running those queries.
Not tested yet.

Add a security watchdog service to periodically run queries and report data

---

crates/sui-json/Cargo.toml

`sui-framework` should only be a dev dep for `sui-json`. It's causing circular dependencies in additions of my one of my working branches.
CI
---

chore: move sui-framework to dev-dep in sui-json

---

crates/sui-security-watchdog/Cargo.toml
crates/sui-security-watchdog/src/scheduler.rs

Remove signal as it is breaking windows build, we don't really need it

Remove signal feature in tokio cron scheduler

---

crates/sui-framework/docs/deepbook/clob_v2.md
crates/sui-framework/packages/deepbook/sources/clob_v2.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Reverting change to L2 accessor in Deepbook causing error for market makers.
Reverting changes, no testing needed.

fix: revert deepbook l2 update

---

crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/objects_snapshot_processor.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/tests/ingestion_tests.rs

during the backfill, all tables except objects snspshot are committed all together and day can finish from genesis to latest in 4-5 days after recent optimization, however the objects_snapshot table took longer. 
This PR is to backfill objects snapshot in 2 modes
- during backfill, just populate it with new object changes and stay updated
- when close to backfill finish, we switch to the original intentionally lagging update mode
local run and benchmark to monitor the new perf and correctness
--- …

indexer: backfill snapshot table via 2 modes

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/unit_tests/consensus_tests.rs
crates/sui-single-node-benchmark/src/mock_consensus.rs

The metric is added to AuthorityMetrics instead of EpochMetrics. So this PR also does some pluming to make `process_consensus_transactions` to take AuthorityMetrics.
---

Add metric to track the number of deferred transactions in consensus handler

---

crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-core/src/state_accumulator.rs
crates/sui-e2e-tests/tests/object_deletion_tests.rs
crates/sui-node/src/lib.rs
crates/sui-single-node-benchmark/src/single_node.rs

Add accumulate_cached_live_object_set_for_testing, because there are many tests that rely on the ability to iterate the live objects mid-epoch

Implement accumulate_cached_live_object_set_for_testing

---

external-crates/move/crates/move-analyzer/src/bin/move-analyzer.rs
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/partial-function/Move.toml
external-crates/move/crates/move-analyzer/tests/partial-function/sources/M1.move

Beyond the main objective (completion snippets support for `init` function and objects), this PR also enhances on-hover for struct definitions to also show abilities.
When the developer starts typing `fun i` (and continue typing to get to `fun init`) the IDE will recognize that we are trying to write a function definition whose name starts with `i` and will offer a code snippet expanding this to a full init function definition:
````
module 0x0::some_module {
fun init(ctx: &mut TxContext) {   
}
}
````
Furthermore, if the module contains a struct definition being a one-time-witness candidate, the IDE will be smart enough to recognize this and offer an expanded snippet:
```
module 0x0::some_module {
struct SOME_MODULE has drop {}
fun init(witness: SOME_MODULE, ctx: &mut TxContext) {   
}
} …
```

[move-ide] Added support for completion snippets

---

crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Combining it with `DevInspectResults` we can get signatures for a recorded transfer action.
Before this i have to do multiple calls to retrieves sigs. See the red lines replaced with `get_token_transfer_action_onchain_signatures_until_success`  call  in `basic.rs`. This will also make front end's life easier when getting sigs.
---

[bridge 69/n] add pub function `get_token_transfer_action_signatures` to get signatures in one call

---

crates/sui-core/src/authority/authority_store_pruner.rs

Currently, if the smoother and effects pruner are enabled, but the objects pruner is disabled, the smoother only activates if the archival store is configured with use_for_pruning_watermark set to true. So it works but may cause confusion for users. To address this, the PR initiates max_eligible_checkpoint as the last executed checkpoint

[effects pruner] adjust max eligible checkpoint

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/transaction_manager.rs
crates/sui-core/src/unit_tests/execution_driver_tests.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

Move `MAX_TM_QUEUE_LENGTH` and `MAX_PER_OBJECT_QUEUE_LENGTH` to AuthorityOverloadConfig, so that changing them doesn't require a new release.
This PR just move the config, and should be a no-op
---

Update shared object overload config

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/move-2024/Move.toml
external-crates/move/crates/move-analyzer/tests/move-2024/sources/implicit_uses.move

This PR removed a dependency of move-analyzer's tests on Sui framework code.
Testing for implicit imports has been made dependent on Move stdlib instead.

[move-ide] Removed test dependency on Sui framework

---

.github/workflows/mysticeti.yml
.github/workflows/simulator-nightly-mysticeti.yml
Cargo.lock
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_manager/mod.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-core/src/consensus_manager/narwhal_manager.rs
crates/sui-core/src/epoch/randomness.rs
crates/sui-core/src/execution_driver.rs
crates/sui-core/src/transaction_manager.rs
crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs
crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
crates/sui-node/src/lib.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-types/src/error.rs
narwhal/executor/src/lib.rs
narwhal/executor/src/subscriber.rs
narwhal/node/src/main.rs
narwhal/storage/Cargo.toml
narwhal/storage/src/certificate_store.rs
narwhal/storage/src/node_store.rs

This helps to ensure that coverage for Narwhal in testnet is maintained while rolling out Mysticeti. Support for this policy has been added to both `ProtocolConfig` and environmental variables (in an earlier PR). And this policy (`swap_each_epoch`) is enabled in Mysticeti CI.
The implementation involves wrapping `NarwhalManager` and `MysticetiManager` within a `ConsensusManager` struct, which selects the appropriate consensus protocol to use.
MysticetiManager was updated to wait for consensus handler task to exist during shutdown.
CI
private testnet: no crash after >90 epoch changes with 5min epoch duration.
--- …

[Consensus] support swapping protocols between epochs

---

Cargo.lock
crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/metrics.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-e2e-tests/tests/zklogin_tests.rs
crates/sui-json-rpc-tests/tests/routing_tests.rs
crates/sui-json-rpc/Cargo.toml
crates/sui-json-rpc/src/axum_router.rs
crates/sui-json-rpc/src/transaction_execution_api.rs
crates/sui-types/src/traffic_control.rs

As in title. The dead man's switch file is expected to have the side effect of disabling relevant firewalls (e.g. BPF)
Added test
---

[traffic-controller][4/n] Introduce firewall dead man's switch

---

.cargo/config
external-crates/move/crates/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
external-crates/move/crates/invalid-mutations/src/bounds.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-binary-format/src/binary_config.rs
external-crates/move/crates/move-binary-format/src/proptest_types/functions.rs
external-crates/move/crates/move-binary-format/src/proptest_types/signature.rs
external-crates/move/crates/move-binary-format/src/unit_tests/binary_limits_tests.rs
external-crates/move/crates/move-binary-format/src/unit_tests/mod.rs
external-crates/move/crates/move-core-types/src/unit_tests/visitor_test.rs
external-crates/move/crates/move-package/tests/test_lock_file.rs
external-crates/move/crates/move-stackless-bytecode/src/borrow_analysis.rs
external-crates/move/crates/move-stackless-bytecode/src/stackless_bytecode_generator.rs
external-crates/move/crates/move-vm-types/src/loaded_data/runtime_types.rs
external-crates/move/crates/test-generation/src/bytecode_generator.rs
external-crates/move/crates/test-generation/src/transitions.rs

- cargo move-clippy did not include tests 
- CI
---

[move][clippy] Apply clippy CI check to all targets 

---

Cargo.lock
consensus/config/src/parameters.rs
consensus/config/tests/parameters_test.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/Cargo.toml
consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/broadcaster.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/lib.rs
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/network/test_network.rs
consensus/core/src/network/tonic_network.rs
consensus/core/src/subscriber.rs
consensus/core/src/synchronizer.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs

Implements block subscription with stream block responses via tonic.
From experiments, this is shown to reduce latency jitters, especially between hosts in different continents.
Also, enable keepalive and message size limits in tonic.
CI
---

[Consensus] block stream subscription

---

crates/sui-move/src/build.rs

Fix a bug which reproduces with:
```
sui move new test_rel_path
sui move build --path ./test_rel_path
```
`base::reroot_path()` modifies cwd which results in a second call during `resolve_lock_file_path()` to abort.
Run above commands with the committed changes.
---

Fix sui move build with --path argument when using relative path.

---

crates/sui-e2e-tests/tests/object_deletion_tests.rs
crates/sui-protocol-config/src/lib.rs
sui-execution/latest/sui-adapter/src/temporary_store.rs

No longer needed in the latest temp store since v2 is always enabled.
CI
---

Remove effects v1 logic from latest temp store

---

crates/sui-types/src/lib.rs

Main motivation for this change is to have a single source of truth to drive the `is_system_package` predicate and a list of system packages. This will be used by the GraphQL service to enumerate packages to evict from its package resolution cache on epoch boundaries.
In the process, I ended up creating a macro to avoid some of the duplication in this module (abstracts away defining all built-in IDs as `AccountAddress` and `ObjectID`, and provides a unified way to create the associated vanity IDs from a single `u16`).
Existing simtests
--- …

[Types] Abstraction for defining built-in IDs and Packages

---

crates/sui-graphql-rpc/src/data/package_resolver.rs
crates/sui-graphql-rpc/src/server/builder.rs

Change GraphQL's package store implementation to depend on GraphQL's `Db` type, instead of `IndexerReader`. This means package loads are subject to our limits and metrics, and makes it easier to switch them to using data loaders in future.
Existing tests
- #17177 
- #17178 
---

[GraphQL/Package] Query using Db, not IndexerReader

---

Cargo.lock
sdk/build-scripts/src/build-dapp-kit.ts
sdk/build-scripts/src/build-package.ts
sdk/build-scripts/src/utils/buildPackage.ts

Fix to:
```
error[vulnerability] Degradation of service in h2 servers with CONTINUATION Flood
```
`cargo deny check advisories` must pass
---

[gql][cherry-pick] Update h2 to 0.3.26 (#17032)

---

crates/sui-benchmark/tests/simtest.rs

Short epochs (<10 seconds) can result in failure to submit capabilities, which prevents upgrade from going through. Also the 7 validators are totally unnecessary for this test, using 4 will speed it up.

Adjust test to be more reliable

---

.changeset/bright-ravens-provide.md
sdk/kiosk/src/client/kiosk-client.ts
sdk/kiosk/test/e2e/e2e.test.ts

Adds pagination to the `getOwnedKiosks` method of the `kioskClient`.
The method `getOwnedKiosks` of the `src/query/kiosk.ts` that is being used by the `kioskClient` under the hood, is already accepting the optional pagination arguments, but the method of the `kioskClient`, does not.
This PR adds the optional pagination arguments to the method of the `kioskClient`, and then passes them to the underlying method.
This PR adds two tests to the e2e tests of the Kiosk SDK, to test the pagination added on the `getOwnedKiosks` method.
Run `pnpm prepare:e2e` to run the localnet, and then `pnpm test:e2e` to run the tests.
--- …

Add pagination to getOwnedKiosks method of kioskClient

---

nre/bpf/nodefw/nodefw/src/drainer.rs
nre/bpf/nodefw/nodefw/src/lib.rs
nre/bpf/nodefw/nodefw/src/main.rs

Add a drain file to control the firewall if needed.
`RUST_LOG=info cargo bpf run -- --drain-file /tmp/drain`
then rm or touch the file at /tmp/drain.  the firewall will unload or be prevented from loading if present.
https://github.com/MystenLabs/sui/assets/123987499/0a21b9f0-b9ca-47c4-a5b2-6217c350a75d
---

[nodefw/drainer] add a drain flag and file

---

scripts/release_notes.py

I forgot to make one of the regex strings a raw string, and now Python is complaining about invalid escapes.
```
sui$ ./scripts/release_notes.py --help
```
No longer produces a syntax warning.
---

[EASY][Release Notes] Fix regex raw string

---

Cargo.lock
crates/sui-framework/packages/sui-framework/sources/test/test_scenario.move
crates/sui-framework/packages/sui-framework/sources/transfer.move
crates/sui-framework/packages/sui-framework/tests/test_scenario_tests.move
crates/sui-move/Cargo.toml
crates/sui-move/src/unit_test.rs
crates/sui-types/Cargo.toml
crates/sui-types/src/in_memory_storage.rs
external-crates/move/crates/move-vm-runtime/src/native_extensions.rs
sui-execution/latest/sui-move-natives/src/lib.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs

This adds support for transfer-to-object/Receiving tickets in the test scenario.
In order to do this a "proper" object store needed to be added to the test scenario since we cannot count on caching to keep the object for us like we can with dynamic fields in test scenario tests.
This adds such a test by creating a shared `InMemoryStorage` (wrapped in a mutex since tests can be multi-threaded and we need internal mutability). Two handles are then created for this -- one for the storage read operations, and another is added to the context extension so that we can place "objects-to-be-received" into this store when we create the `Receiving` ticket.
This might generally be useful for other tests as well/refactoring the test scenario to be more realistic but I will leave any such …

[transfer-to-object] TTO support in test scenario

---

Cargo.lock
crates/sui-framework/packages/sui-framework/sources/random.move
crates/sui-framework/packages/sui-framework/tests/crypto/bls12381_tests.move
sui-execution/latest/sui-move-natives/Cargo.toml
sui-execution/latest/sui-move-natives/src/lib.rs
sui-execution/latest/sui-move-natives/src/random.rs

Provide randomness in Move UTs: instantiate `RandomGenerator` from a given seed or a random one.
---

Provide randomness in Move UTs

---

crates/sui-indexer/migrations/2023-10-06-204335_tx_indices/up.sql
crates/sui-indexer/src/schema.rs

the original intention was to partition tx_ tables such that they can be easily pruned by dropping old partitions, however that indicates that for each query with a "lookup key" like sender, we will have to scan all partitions, which can be costly.
also after pulling the numbers from DB, the sizes of these tables are relatively small and thus we can take the extra storage for now in favor of reading side perf.
benchmark and experiment 
---

indexer breaking change: merge back tx_ tables

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/tools/cli.rs
crates/sui/src/sui_commands.rs

instead of querying the bridge arg on chain every time, we do this in the beginning of the program and cache it. If the fetch (with retry) fails, it panics.
existing tests 
---

[bridge/70] cache the result of get_mutable_bridge_object_arg

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_syncer.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/tools/cli.rs
crates/sui/src/sui_commands.rs

Removed inaccurate comments. They were correct until we changed the type of watermark.
---

[bridge 71] remove stale comments

---

external-crates/move/crates/move-analyzer/src/bin/move-analyzer.rs
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/symbols.rs

This PR adds clearing of pre-compiled dependencies for a given package if the manifest file of this package changes.
Tested manually to verify that pre-compiled dependencies are re-computed on manifest file change

[move-ide] Reset pre-compiled libs on manifest change

---

crates/sui-framework/packages/sui-framework/sources/package.move

`sui::package` has definitions of multiple types where we have had to disambiguate function names. Adding some receiver function aliases so that we don't need to use the disambiguated names when they are called as receiver functions.
CI
---

[Framework] Receiver function aliases for package.move

---

crates/sui-bridge/src/config.rs
crates/sui-bridge/src/e2e_test_utils.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-bridge/src/types.rs
crates/sui-bridge/src/utils.rs
crates/test-cluster/src/lib.rs

(the meat is in `config.rs`)
This PR reworks `BridgeNodeConfig` to make it easier to reason about. The main changes:
1. add `sui_bridge_chain_id` and `eth_bridge_chain_id`
2. sui related fields are moved to `SuiConfig`
3. eth related fields are moved to `EthConfig`
4. `eth_addresses` is now `eth_bridge_proxy_address`, and when the node starts, it fetches all contracts's addresses starting from `EthSuiBridge` 
Other than that, i also moved some common test utils around from `basic.rs` to `test_utils.rs`.
unit tests
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions …

[bridge 72/n] rework node config a little bit

---

crates/sui-indexer/src/store/mod.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

We had a couple of reports that although certain checkpoints have been committed, tx_senders and objects of the same checkpoint missed some data.
after investigation, the bug was on joinAll of 
```
Vec<JoinHandle<Result<(), IndexerError>>>
```
where it has a nested result, the outer one is Result<_, JoinError>, and the inner one is Result<(), IndexerError>, before this fix, when the DB commit retries run out, indexer will skip and move on b/c the outer Result is okay, this PR is to fix that.
Also increased the retry timeout to 3600 seconds, b/c when retry fails indexer will panic and restart the whole binary, which is relatively expansive and so we want to try more here.
CI
will want to test and make sure that indexer does panic and restart, will look into it separately.
---
Check each …

indexer: fix partial commit failure bug

---

crates/sui-replay/src/config.rs
crates/sui-replay/src/lib.rs
crates/sui-replay/src/replay.rs
crates/sui-replay/tests/regression_replay.rs
crates/sui-tool/src/commands.rs
crates/sui/src/client_commands.rs
crates/sui/src/unit_tests/profiler_tests.rs

When rpc_url is not specified, previously the sui-tool would iterate through the network config and try each config one by one. This is rather unnecessary and inefficient.
This PR adds an explicit --chain option so that when rpc_url is not specified, it will use the config named `chain` in the config file. This simplifies some of the implementation and makes it faster to replay a transaction when the desired config is not the first one in the config file.
CI
Run locally
---

Add --chain option to sui-tool replay commands

---

Cargo.lock
consensus/config/src/committee.rs
consensus/core/Cargo.toml
consensus/core/src/block.rs
consensus/core/src/commit_observer.rs
consensus/core/src/dag_state.rs
consensus/core/src/lib.rs
consensus/core/src/linearizer.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/test_dag.rs
consensus/core/src/test_dag_builder.rs
consensus/core/src/test_dag_parser.rs
consensus/core/src/tests/universal_committer_tests.rs

Add `DagBuilder` API and Dag DSL that can be parsed via `DagParser` module.
```
let dag_builder = DagBuilder::new(num_authorities); 
dag_builder.layer(1).build(); // Round 1 is fully connected with parents by default.
dag_builder.layers(2..10).build(); // Rounds 2 ~ 10 are fully connected with parents by default.
dag_builder.layers(11).min_parent_links().build(); // Round 11 is minimally and randomly connected with parents, without weak links.
dag_builder.layers(12).no_leader_block(0).build(); // Round 12 misses leader block. Other blocks are fully connected with parents.
dag_builder.layers(13).no_leader_link(12, 0).build(); // Round 13 misses votes for leader block. Other blocks are fully connected with parents.
dag_builder.layers(14).authorities(vec![3,5]).skip_block().build(); // Round …
```

[consensus] Add DagBuilder & DagParser V1

---

crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-framework/packages/bridge/sources/committee.move
crates/sui-framework/packages/bridge/sources/treasury.move
crates/sui-framework/packages/bridge/tests/bridge_tests.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

More Move2024 cleanup and formatting.
Moved tests out of `bridge.move` in its own test directory.
We will transition all tests to that model as we work towards 100% test coverage.
This is mostly tests
---

Cleanup and test rework

---

crates/sui-graphql-rpc/src/consistency.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/mod.rs
crates/sui-graphql-rpc/src/server/watermark_task.rs
crates/sui-graphql-rpc/src/types/query.rs

Cherrypick change to extend the existing checkpoint watermark task to also report the current epoch. Additionally set up a watch channel to notify listeners on epoch change.
---
---

[gql][cherry-pick] epoch boundary task notifier and listener example (#16806)

---

Cargo.lock
crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-analytics-indexer/src/handlers/event_handler.rs
crates/sui-analytics-indexer/src/handlers/object_handler.rs
crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
crates/sui-analytics-indexer/src/package_store.rs
crates/sui-graphql-rpc/src/data/package_resolver.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/mod.rs
crates/sui-graphql-rpc/src/server/system_package_task.rs
crates/sui-graphql-rpc/src/server/watermark_task.rs
crates/sui-indexer/Cargo.toml
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/lib.rs
crates/sui-indexer/src/store/package_resolver.rs
crates/sui-indexer/src/system_package_task.rs
crates/sui-json-rpc-tests/tests/routing_tests.rs
crates/sui-json-rpc/Cargo.toml
crates/sui-json-rpc/src/lib.rs
crates/sui-light-client/src/main.rs
crates/sui-package-resolver/src/lib.rs

Replace `version` based API with one where the LruCache-based store includes an API for evicting packages, and this gets called by a background task that detects epoch changes.
This change was tested manually, by running a local cluster and simulating a protocol upgrade:
Start by creating a genesis config with a fast epoch duration, and run the network for some time:
```
sui$ cargo run --bin sui -- genesis -f --with-faucet --epoch-duration-ms 10000
sui$ RUST_LOG='off,sui_graphql_rpc=INFO' cargo run --bin sui-test-validator -- \
--graphql-port 9001 \
--with-indexer      \
--c ~/.sui/sui_config
```
After some time, apply a pretend system package upgrade, and restart the `sui-test-validator` invocation:
```diff
diff --git a/crates/sui-framework/packages/sui-framework/sources/sui.move …
```

[GraphQL/Package] Evict system packages on epoch boundaries

---

Cargo.lock
crates/sui-replay/Cargo.toml
crates/sui-replay/src/batch_replay.rs
crates/sui-replay/src/data_fetcher.rs
crates/sui-replay/src/lib.rs
crates/sui/src/client_commands.rs

This PR fixes an issue where the batch replay would get stuck.
The core fix is to remove the `tokio::spawn` from the task creation, and instead it pushes an async function directly.
This allows the runtime to schedule tasks together during `join_all`.
It also does some optimizations: instead of scheduling batches one by one, this PR creates N tasks, each pulling transaction digests from a dequeue. This speeds up execution.
This PR also makes each task to reuse the executor, which allows for package cache reuse, another speedup.
Run locally.
--- …

Fix batch replay

---

consensus/config/src/committee.rs
consensus/core/src/authority_node.rs
consensus/core/src/base_committer.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/lib.rs
consensus/core/src/linearizer.rs
consensus/core/src/metrics.rs
consensus/core/src/test_dag_builder.rs
consensus/core/src/tests/pipelined_committer_tests.rs
consensus/core/src/tests/universal_committer_tests.rs
consensus/core/src/universal_committer.rs

This is one of many PRs to implement Leader Scoring & Leader Schedule feature for Mysticeti.
- [Design Doc](https://www.notion.so/mystenlabs/Leader-Schedule-Scoring-538c65cb370b4644944a94485efc4979?pvs=4)
- [Prototype PR](https://github.com/MystenLabs/sui/pull/16975)
Notes:
- `LeaderSwapTable` & `ReputationScores` are mostly the same from the NW implementation
- Kept the `Authority` & `ReputationScores` info in `LeaderSwapTable` mostly for debugging purposes. It is not required functionally
unit tests

[consensus] Add LeaderSwapTable & ReputationScores

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/partial-dot/Move.toml
external-crates/move/crates/move-analyzer/tests/partial-dot/sources/M1.move
external-crates/move/crates/move-compiler/src/expansion/ast.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/naming/ast.rs
external-crates/move/crates/move-compiler/src/naming/resolve_use_funs.rs
external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/src/parser/ast.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/src/typing/ast.rs
external-crates/move/crates/move-compiler/src/typing/dependency_ordering.rs
external-crates/move/crates/move-compiler/src/typing/expand.rs
external-crates/move/crates/move-compiler/src/typing/infinite_instantiations.rs
external-crates/move/crates/move-compiler/src/typing/macro_expand.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/src/typing/visitor.rs
external-crates/move/crates/move-compiler/tests/move_2024/parser/dot_incomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/dot_incomplete.move
external-crates/move/crates/move-compiler/tests/move_check/parser/let_binding_missing_semicolon.move

This PR adds parsing resilience to dot chains (e.g., `some_struct.some_field`). It's a pre-requisite to adding auto-completion for struct fields and struct functions (aka methods) to the IDE.
Implementation-wise, I was also trying making `parse_identifier` parser-resilient (have it always return a value instead of `Result`). This does not quite work, though, since in `parse_dot_or_index_chain` we need to know that if an identifier fails to parse, we should stop parsing the chain itself. If the `parse_identifier` never returns an error, we would simply continue parsing the chain and generate weird errors.
An additional compiler test has been added. Also a symbolicator test has been added to verify that prefixes of partially parsed dot chains are parsed correctly.
---
Check each box that …

[move-compiler] Added dot chain parsing resilience

---

consensus/config/src/parameters.rs
consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/block.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

During catchup, a large number of suspended and "missing" blocks can be accumulated inside `BlockManager`. The memory usage can be significant. A mitigation is added here to stop accepting incoming blocks once local commit is lagging quorum commit progress significantly.
Also, fix commit and block syncer to verify the timestamps of blocks fetched. The local time can be behind the fetched block timestamps. For commit syncer fetching, potentially the fetch task needs to wait to enforce the invariant that local time > accepted block timestamp. For block syncer, since processing is done in a single thread, it has to drop the blocks with advanced timestamp for now.
CI
private testnet
--- …

[Consensus] improve resilience for commit and block sync

---

.github/actions/diffs/action.yml
Cargo.lock
Cargo.toml
deny.toml

Upgrade rustls used in the workspace to a version that fixes RUSTSEC-2024-0336.
But there are still Sui dependencies using the unpatched version, which I'm not sure when will be upgraded.
Also, make sure Rust CI runs when Rust workspace config changes.
CI
---

Upgrade rustls

---

crates/sui-core/src/unit_tests/transaction_manager_tests.rs
crates/sui-types/src/object.rs

Trying to pull some independent changes from #17200 .
Noticed that `shared_for_testing` always return the same shared object if called from the same thread. Added a new `with_id_shared_for_testing` instead of changing `shared_for_testing`'s behavior since I guess it was purposely created in that way.
Unit test
---

Create with_id_shared_for_testing helper

---

bridge/evm/contracts/BridgeVault.sol
bridge/evm/contracts/SuiBridge.sol
bridge/evm/script/deploy_bridge.s.sol
bridge/evm/test/BridgeBaseTest.t.sol
bridge/evm/test/BridgeConfigTest.t.sol
bridge/evm/test/BridgeLimiterTest.t.sol
bridge/evm/test/CommitteeUpgradeableTest.t.sol
bridge/evm/test/SuiBridgeTest.t.sol

Thanks to @dariorussi for pointing out this very obvious design flaw. The SuiBridge contract no longer needs reference the WETH contract at all, and the vault takes care of all wrapping and unwrapping of ETH. 
Updated necessary tests

Move all ETH wrapping and unwrapping to vault

---

Cargo.lock
consensus/core/Cargo.toml
consensus/core/src/authority_service.rs
consensus/core/src/block.rs
consensus/core/src/block_manager.rs
consensus/core/src/commit.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/synchronizer.rs
consensus/core/src/transaction.rs

Improve panic message when local timestamp < accepted block timestamp.
Add more details to logs for block creation and processing.
Remove logic no longer necessary after using DagState for proposing and keeping track of last proposed ancestors.
Ensure timestamp_utc_ms() returns monotonic values. Ensure after Core recover, local time > max ancestor timestamp.
CI
Simulation
---

[Consensus] improve logs and panic messages

---

consensus/core/src/dag_state.rs

There are multiple sources of blocks when accepting them into Core & DagState, so adding another invariant check inside DagState.
CI
Simulation
---

[Consensus] check timestamp invariant when accepting blocks

---

docs/content/references/cli/ptb.mdx

Explain how string literals work in the CLI PTB command-line, especially how they need to be single- *and* double-quoted when input on the command-line.
:eyes:
---

[Docs/CLI] Add explanation for string literals

---

consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/block_manager.rs
consensus/core/src/broadcaster.rs
consensus/core/src/commit_observer.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/network/test_network.rs
consensus/core/src/network/tonic_network.rs
consensus/core/src/subscriber.rs
consensus/core/src/synchronizer.rs

This PR is introducing the following changes to the synchronizer & block_manager
1. `BlockManager` will not return any more the missing blocks only once during block acceptance , but every time
2. `Synchronizer` during live synchronization will allow a block to be fetched from up to two different peers. Those peers are basically block authors who used the missing peers as ancestors (the info we basically get from the block manager) thus allowing is to make more informed decisions and make the synchronization more intensive
3. `Synchronizer` will attempt to kick off the scheduler immediately if after fetching missing blocks and try to accept them, we still have more missing ancestors 
4. The highest accepted rounds are provided as part of the `FetchBlocksRequest` to allow the other peer …

[Consensus 2.0] Refactor synchronizer 

---

crates/sui/src/sui_commands.rs

If the CLI is ran for the first time and there is no client configuration (e.g., client.yaml file), the user will be prompted a menu to either enter a network or accept the defaults. This PR changes the default network from devnet to testnet.
No tests needed.
---

[cli] Switch to testnet as a default network environment 

---

Cargo.lock
crates/sui-data-ingestion-core/Cargo.toml
crates/sui-data-ingestion-core/src/reader.rs

temporary functionality. 
Intended for use in environments like devnet/staging when remote bucket is not available.
In future should be covered by colocation functionality.
It has a side benefit that even for testnet/mainnet we will have an option to fallback to querying FN

[data ingestion] reader: support FN based REST API

---

crates/sui-replay/src/replay.rs

For receiving object transactions, the dependency assert is no longer valid.
This PR removes the assert.
Replay on a receiving object transaction.
---

[replay] Fix for receiving object transactions

---

apps/wallet/src/ui/app/components/accounts/ImportPrivateKeyForm.tsx
apps/wallet/src/ui/app/helpers/validation/privateKeyValidation.ts

as notified in https://github.com/sui-foundation/sips/blob/main/sips/sip-15.md we are deprecating hex private key importing. 
---

wallet: disable hex import for private key

---

crates/sui-graphql-rpc/src/server/builder.rs

Adding wildcard route to support additional graphql routes.
`/health`
```
% curl http://127.0.0.1:8001/health -w "%{http_code}"
200%
```
`/`
```
% curl -X POST -H "Content-Type: application/json" --data '{ "query": "query { chainIdentifier }", "variables": { "userId": "123" } }' http://127.0.0.1:8001/ -w "%{http_code}"
{"data":{"chainIdentifier":"4c78adac"}}200%
```
`/graphql`
```
% curl -X POST -H "Content-Type: application/json" --data '{ "query": "query { chainIdentifier }", "variables": { "userId": "123" } }' http://127.0.0.1:8001/graphql -w "%{http_code}"
{"data":{"chainIdentifier":"4c78adac"}}200%
```
`graphql/hola`
```
% curl -X POST -H "Content-Type: application/json" --data '{ "query": "query { chainIdentifier }", "variables": { "userId": "123" } }' …
```

add route for version wildcards

---

bridge/evm/.gitignore
crates/sui-bridge/src/e2e_tests/test_utils.rs

When we run multiple bridge tests in the same time, forge may complain about the conflicts. This PR fixes this problem by using a different FOUNDRY_OUT folder for each test run.
CI tests
---

[bridge] use different foundry-out for each test run

---

docs/content/references/rust-sdk.mdx
docs/content/references/sui-sdks.mdx
docs/content/sidebars/references.js

Adding more community SDKs to the SDK reference page
Visual inspection
---

[docs] add more sdks to reference page

---

crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/types.rs
crates/sui-core/src/authority_server.rs
crates/sui-types/src/effects/mod.rs
crates/sui-types/src/message_envelope.rs
crates/sui-types/src/messages_checkpoint.rs
crates/sui-types/src/transaction.rs

`verify_user_input` is only applicable to SenderSignedData. There is no need to make it a trait function of Message.
It also contains a bunch of checks that are already done in either validity_check, or verify_message_signature. Remove those redundant checks.
CI
---

[crypto] Remove verify_user_input from message envelope trait

---

crates/sui-bridge/src/config.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/utils.rs

This PR adds `eth_contracts_start_block_fallback` in `BridgeNodeConfig`. The comment describes it enough:
```
/// The starting block for EthSyncer to monitor eth contracts.
/// It is required when `run_client` is true. Usually this is
/// the block number when the bridge contracts are deployed.
/// When BridgeNode starts, it reads the contract watermark from storage.
/// If the watermark is not found, it will start from this fallback block number.
/// If the watermark is found, it will start from the watermark.
/// this v.s.`eth_contracts_start_block_override`:
pub eth_contracts_start_block_fallback: Option<u64>,
/// The starting block for EthSyncer to monitor eth contracts. It overrides
/// the watermark in storage. This is useful when we want to reprocess the events
/// from a specific …
```

[bridge 73] add `eth_contracts_start_block_fallback`

---

consensus/core/src/authority_node.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

This PR is amending the leader timeout component to trigger a block creation both when:
* the min round delay has pass - without though trying to `force` the block creation. This ensures that even though all the blocks have been received on a round before the min round, an block creation attempt will be made without having to reach the max leader timeout
* when the leader timeout has passed, as before, it will attempt to create a new block
The approach for now has been kept simple and both timers will trigger unless a new round has advanced. More smart decisions could be made as follow ups.
CI
--- …

[Consensus 2.0] trigger leader timeout on min round delay as well

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/passthrough_cache.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-core/src/transaction_manager.rs
crates/sui-node/src/lib.rs

This will be necessary for the WritebackCache, and unnecessary but harmless otherwise.
Until built checkpoints are re-executed, the validator is an in inconsistent state, since
every locally checkpointed transaction should have effects locally available. Without this change, we hit this case https://github.com/MystenLabs/sui/blob/59168f73ffd71023de6427186e5dac206cf4698e/crates/sui-core/src/storage.rs#L172 when we shouldn't.
This is a temporary measure. Once we cache and quarantine consensus output, we will simply re-process any consensus commits which have not yet resulted in a certified checkpoint, so we won't have this edge case anymore.

Re-execute locally built checkpoints at startup

---

crates/sui-core/src/transaction_manager.rs

In enqueue_impl, we acquire inner.write() twice - in between these two critical sections we need to ensure that the cache is in unbounded mode so that we do not miss object writes that happen in between.
However, since we do not hold the lock the entire time, reconfiguration could previously happen. This would reset the inner state, and then we could crash at https://github.com/MystenLabs/sui/blob/d181e3f6ec8c3e185c239543f2613103db806eee/crates/sui-core/src/transaction_manager.rs#L201 when attempting to disable unbounded mode.
This PR ensures that reconfig cannot happen at any point during `enqueue_impl` or any other method that holds the lock. (Note that other methods were not affected since `enqueue_impl` is the only one that has two separate critsecs)

Ensure that reconfiguration cannot happen while we are in enqueue_impl (or other methods)

---

Cargo.lock
crates/sui-indexer/Cargo.toml
crates/sui-indexer/src/lib.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/test_utils.rs

There are instances where we some sensitive information is logged. This PR should resolve this issue.
Ran unit-tests and ran against a local DB on my laptop. The log output is below. I tried with db_url args and individual db args.
```
cargo run --bin sui-indexer -- --db-url "postgresql://postgres:postgres@localhost:5432/sui_indexer" --rpc-client-url "https://fullnode.devnet.sui.io:443" --fullnode-sync-worker
2024-04-23T00:50:44.350678Z  INFO sui_indexer: Parsed indexer config: IndexerConfig {
db_url: Some(
Secret([REDACTED alloc::string::String]),
),
db_user_name: None,
db_password: None,
db_host: None,
db_port: None,
db_name: None,
rpc_client_url: "https://fullnode.devnet.sui.io:443",
remote_store_url: Some(
"https://checkpoints.mainnet.sui.io",
),
client_metric_host: "0.0.0.0", …
```

[indexer] modify IndexerConfig logging

---

crates/suiop-cli/src/cli/mod.rs
crates/suiop-cli/src/cli/service/init.rs
crates/suiop-cli/src/cli/service/mod.rs
crates/suiop-cli/tests/integration_tests.rs

Add a couple of simple integration tests to verify that we can initialize a new service based on the boilerplate code in the sui repo and externally.
```
» cargo test
Compiling suiop-cli v0.1.9 (/Users/jkjensen/mysten/sui/crates/suiop-cli)
Finished test [unoptimized + debuginfo] target(s) in 2.04s
Running unittests src/lib.rs (/Users/jkjensen/mysten/sui/target/debug/deps/suioplib-b060133edb7a006f)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running unittests src/main.rs (/Users/jkjensen/mysten/sui/target/debug/deps/suiop-3e180845c83f7297)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running tests/integration_tests.rs …
```

[suiop] integration test for `suiop service init`

---

crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-indexer/src/framework/builder.rs
crates/sui-indexer/src/framework/fetcher.rs
crates/sui-indexer/src/framework/runner.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/objects_snapshot_processor.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/test_utils.rs

In the codebase today, when each e2e test is completed, we send a cancellation token to the graphql service and then delete the database created for the test. The issue is that the indexer and its supporting tasks continue to run, and now that they're trying to establish a connection to a db that does not exist, every connection will wait for `CONNECTION_TIMEOUT` duration. This means every test hangs for much longer than needed. To resolve, we thread a cancellation token through the indexer's test instantiation, so that on cleanup we can send a cancellation signal to both services, and finally spin down the db.
Manually check that test duration is shorter.
---
For each box …

[gql] thread cancellation token through indexer to address flaky graphql e2e tests

---

Cargo.lock
Cargo.toml
crates/data-transform/src/main.rs
crates/sui-cluster-test/Cargo.toml
crates/sui-cluster-test/src/cluster.rs
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-indexer/Cargo.toml
crates/sui-indexer/src/apis/coin_api.rs
crates/sui-indexer/src/apis/extended_api.rs
crates/sui-indexer/src/apis/governance_api.rs
crates/sui-indexer/src/apis/indexer_api.rs
crates/sui-indexer/src/apis/move_utils.rs
crates/sui-indexer/src/apis/read_api.rs
crates/sui-indexer/src/apis/transaction_builder_api.rs
crates/sui-indexer/src/db.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/lib.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/store/mod.rs
crates/sui-indexer/src/store/package_resolver.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/store/pg_partition_manager.rs
crates/sui-indexer/src/system_package_task.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-indexer/tests/ingestion_tests.rs

This PR generalizes the code in `sui-indexer` crate such that different diesel backends can be enabled through feature flags when compiling. The default backend is still postgres which means nothing changes in terms of how we build our binaries today. 
1. The most important thing is that we do all kinds of db operation through macros which are feature gated such that we only pull in relevant db specific dependencies. 
2.  In Cargo.toml by default we do not add any db specific dependencies but only pull them through features:
3. In `sui-indexer`, all instances of `diesel::PgConnection` are pulled with `postgres-feature` and similary all instances of `diesel::MySqlConnection` are pulled with `mysql-feature`
4. `run_query` and `run_query_async` are replaced with their corresponding macro …

[1/n][dialect_support]Generalize indexer code to support different sql dialects

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-types/src/traffic_control.rs

Dry run mode runs the policy without enforcing its output (does not block requests, but will still accumulate and log, so we can see the would-be effects on both the node and the request).
Note that this does nothing for BPF enforcement - with dry run enabled, we may still run BPF and populate the BPF blocklist. BPF userspace will itself need to introduce a dry-run mode in order to ignore the blocklist and instead log/bump metrics. Until then, we will need to explicitly not configure traffic controller to delegate to BPF (which will be a less complete dry run).
Added tests
---
For each box you select, include information after the relevant heading that describes the impact …

[TrafficControl] Dry run mode

---

consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/dag_state.rs
consensus/core/src/linearizer.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs
consensus/core/src/test_dag.rs

This makes consuming commit timestamp easier.
CI
---

[Consensus] ensure commit timestamps are monotonic

---

crates/sui-analytics-indexer/src/package_store.rs
crates/sui-graphql-rpc/src/data.rs
crates/sui-graphql-rpc/src/data/package_resolver.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-indexer/src/store/package_resolver.rs
crates/sui-light-client/src/main.rs
crates/sui-package-resolver/src/error.rs
crates/sui-package-resolver/src/lib.rs

Use a DataLoader to serve fetches from the package store, so that when concurrent threads request the same package be fetched, we can batch them and avoid multiple round trips to the DB.
Try the following query before and after the change:
```graphql
query {
owner(
address: "0x029170bfa0a1677054263424fe4f9960c7cf05d359f6241333994c8830772bdb"
) {
dynamicFields(first: 50) {
pageInfo {
hasNextPage
endCursor
}
nodes {
name {
type {
repr
}
json
}
value {
... on MoveValue {
type {
repr
}
json
}
... on MoveObject {
contents {
json
type {
repr
}
}
}
}
}
}
}
}
```
Before this change, the above request made about 90 DB roundtrips, and after the change, it takes about 5, not including checkpoint watermark fetches.
--- …

[GraphQL/DataLoader] Data Loader for Package Resolver

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/epoch/randomness.rs
crates/sui-network/src/randomness/builder.rs
crates/sui-network/src/randomness/mod.rs
crates/sui-network/src/randomness/tests.rs

Adds code to keep track of the highest completed RandomnessRound during an epoch. On restart, we report this to the randomness network loop so it can recover state used to decide for which rounds to accept partial sigs.
Added unit test.

Use highest completed randomness round to recover state after restart

---

crates/sui-replay/src/batch_replay.rs
crates/sui-replay/src/lib.rs
crates/sui/src/client_commands.rs

Add the ability to persist the state into files during batch replay.
It skips transactions that are already persisted.
Run it on a list of transactions.
---

[replay] Support state persist in batch replay

---

crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.exp
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

With the removal of direct accesses to the `objects` table, the nomenclature we use around object kinds ("not indexed", "live", "historical", "deleted or wrapped") is less relevant. In particular, we never use "live" and the name "historical" is confusing because even the latest version of the object may be considered "historical".
This PR removes the "live" kind, and renames "historical" to "indexed" to better reflect how the users of GraphQL perceive the kinds of objects, rather than how the data is stored in the indexer's tables.
```
```
---
For each box …

[GraphQL] Remove "Live" ObjectKind, rename "Historical" to "Indexed"

---

docs/content/guides/developer/sui-101/using-events.mdx

Make it clearer that there is a difference between the subscriptions API and the query API for events right now.
:eyes:
---

[Docs] Clarify EventFilter subscription/query differences

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-e2e-tests/tests/checkpoint_tests.rs
crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs

In simtests, and also if the `PANIC_ON_NEW_CHECKPOINT_TIMEOUT` env var is set, we panic if we do not receive a certified checkpoint for too long. This condition should encompass more or less everything we mean when we say "loss of liveness".
In order to get tests to pass under this stricter condition, several fixes were required:
- changes to the crash failpoints to prevent crashes from happening too close together in time
- disable pruning in crash tests
Additionally, some tests cannot pass in this condition, so we suppress the panic on a per-test basis.

detect loss of liveness in tests

---

consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/block.rs
consensus/core/src/commit_observer.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/context.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/synchronizer.rs

This PR refactors the method to retrieve the current system timestamp and instead creates a dedicated Clock obj to facilitate the functionality. The refactor will fix the failing sim tests [here](https://github.com/MystenLabs/sui/actions/runs/8813919886)
The static initialisation of the unix epoch instant is creating issues with simulation testing framework which is not allowing the re-initalisation from one iteration to another, and effectively making simtests with multiple iterations fail. Different iterations are initialised with different dates, thus making a test run with multiple iterations going back and forth in time effectively making Mysticeti producing timestamps from the first run (which intialised the static context). Failures here: …

[Consensus 2.0] extract timestamp method to a Clock component.

---

Cargo.lock
Cargo.toml
crates/sui-core/Cargo.toml
crates/sui-core/src/traffic_controller/policies.rs
crates/sui-types/src/traffic_control.rs

Introduce Count Min Sketch based traffic control policy. Count min sketch, also known as counting bloom filter, allows for estimating frequency counts on an unbounded stream via repeated hashing, within some threshold with some probability (configurable). Memory is bounded, and current settings attempt to limit to around 20MB per sketch.
In order to introduce a time based frequency, rather than a count (as is required for "rate" limiting), we introduce a sliding window of count min sketches, implemented as a circular buffer. A window of `n` time slots, each of `t` seconds, will consider all estimated tallies in the last `n * t` seconds, and get the rate by dividing by window length. This allows for the frequency to decay with granularity `t`. 
Added unit tests
---
Check each box that your …

[TrafficControl] Efficient traffic policy via Count Min Sketch

---

docs/content/guides/developer/app-examples/e2e-counter.mdx

This updates the `counter` doc example to be use Move 2024 syntax.
👀  plus local project creation / test to ensure it works
---

[move-2024][docs] Update e2e-counter.mdx to move 2024 syntax

---

crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/main.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/server/mod.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-e2e-tests/tests/bridge_tests.rs
crates/test-cluster/src/lib.rs

This PR:
1. refactors e2e test utils by introducing `BridgeTestClusterBuilder` and `BridgeTestCluster`
2. enables the ability to drop spawned BridgeNodes, and restart them (not in this PR, but this PR makes it easy to do)
3. speeds up the setup by doing things in parallel. This probably cuts at least 20 seconds for each test.
existing tests
---

[bridge] refactor test utils

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-types/src/bridge.rs

This PR adds more events in Rust to match those emitted in bridge.move. This is one extra step towards the monitoring system on bridge node.
Also adds two two handy functions `new_bridge_transactions` and `new_bridge_events` to help observe bridge transactions/events.
unit tests + integration tests
---

[bridge] add more sui events emitted in bridge.move

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-core/src/traffic_controller/policies.rs
crates/sui-json-rpc/src/axum_router.rs
crates/sui-types/src/traffic_control.rs

The list of servers that need to run traffic controller is 2 and will be 3 with graphql, perhaps more later.
Instead of requiring that traffic controller understand different error types for each server, allow the server to define the importance of an error type by replacing `ServiceResponse` in `TrafficTally` with a `Weight`, which is a float between 0 and 1, generated by each server. For errors that the server does not care about, weight is set to 0, and ignored by traffic controller during error tallying. For spam tallying, we disregard weight and consider all tallies.
This logic currently only serves to simplify some error case statements. In later PR's, we will test this logic against error-aware policies (there are currently none). So for now, just ensure all existing tests pass
--- …

[TrafficController] Delegate error weighting to the server

---

consensus/core/src/authority_service.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs

PR#17040 has all of the changes required to store/recover leader schedule/scoring related items. Making the storage changes separately early before we go to testnet. 
Also started swapping over to using CommitRange but all of the changes will be done in PR#17040 to keep this PR small.

[consensus] Storage changes in preparation for LeaderSchedule/Scoring

---

crates/sui-e2e-tests/tests/protocol_version_tests.rs

Let's see if giving the shutdown validator more time to catchup can reduce flakiness. 
CI
---

[Simtest] increase wait for shutdown validator to catch up

---

scripts/simtest/seed-search.py

Usage and output:
```
; ./scripts/simtest/seed-search.py simtest --test test_simulated_load_restarts
Found binary: /Users/marklogan/dev/sui/target/simulator/deps/simtest-a3d94d04483ce652
running seed: 3145
running seed: 3146
running seed: 3147
running seed: 3149
running seed: 3148
running seed: 3150
running seed: 3151
running seed: 3152
running seed: 3153
running seed: 3154
running seed: 3155
running seed: 3156
running seed: 3157
running seed: 3158
running seed: 3159
running seed: 3160
running seed: 3161
running seed: 3162
running seed: 3163
running seed: 3164
Command '/Users/marklogan/dev/sui/target/simulator/deps/simtest-a3d94d04483ce652 test_simulated_load_restarts' failed with exit code 101 for seed: 3146
stdout:
==========================
running 1 test
test …
```

Add script to search for failing seeds

---

docs/content/guides/developer/app-examples/coin-flip.mdx

Updates coin flip to use Move 2024 syntax. 
Should not land until this does: https://github.com/MystenLabs/satoshi-coin-flip/pull/2
:eyes:
---

[move-2024][docs] Update coin-flip.mdx to use Move 2024 Syntax

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-core/src/traffic_controller/policies.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-json-rpc/src/axum_router.rs

As in title. This is not an end to end traffic simulator, but instead a simulator to allow for testing, benchmarking, and parameter tuning of traffic controller policies. 
This PR also contains a deadlock fix in traffic controller's use of `DashMap`
Run it and see the results. Currently there are 2 tests introduced that leverage it, but will add more benchmarking later. 
* 100K TPS
* 10K TPS per client
* 10 clients
* 20 second run
* 1 second blocklist TTL
```
> cargo simtest --nocapture -- test_traffic_sketch_no_blocks
...
Running naive traffic simulation for 20 seconds
Policy: PolicyConfig {
connection_blocklist_ttl_sec: 1,
proxy_blocklist_ttl_sec: 1,
spam_policy_type: FreqThreshold(
FreqThresholdConfig {
threshold: 10100,
window_size_secs: 4,
update_interval_secs: 1,
sketch_capacity: …
```

[TrafficControl] Introduce naive traffic simulator; Fix deadlock

---

crates/sui-core/src/consensus_handler.rs

`update_index_and_hash` was originally created to both checking whether a transaction is processed and updating consensus handler's `last_consensus_stats`. Overtime, consensus handler semantic has changed and the call site of update_index_and_hash is no longer able to receive already processed transactions (see checks [here](https://github.com/MystenLabs/sui/blob/bcbd84900e0da8aae9c41bf326def383ad9102ec/crates/sui-core/src/consensus_handler.rs#L239)). This PR clean up the usage of update_index_and_hash to only update the index and hash.
--- …

Update the usage of update_index_and_hash

---

crates/sui/src/client_ptb/builder.rs

...and make its corresponding module in `sui_programmability/examples/basics` line up.
```
sui$ cargo nextest run -p sui-framework-tests
```
+ :eyes: for docs

[CLI/PTB] Avoid fetching the protocol config when building a PTB

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-config/src/p2p.rs
crates/sui-network/src/state_sync/builder.rs

Making the `wait_interval_when_no_peer_to_sync_content`  property configurable so we can run in simtests with lower wait as with the current setting `10s` some tests seem to fail due to early timeout without giving the opportunity to nodes to retry.
CI/simtests
---

[fix] make wait_interval_when_no_peer_to_sync_content configurable for simtests

---

docs/content/guides/developer/sui-101/access-time.mdx
sui_programmability/examples/basics/sources/clock.move

...and make its corresponding module in `sui_programmability/examples/basics` line up.
```
sui$ cargo nextest run -p sui-framework-tests
```
+ :eyes: for docs

[Docs] Update Clock docs to use Move 2024 syntax

---

sdk/move-bytecode-template/Cargo.lock
sdk/move-bytecode-template/README.md
sdk/move-bytecode-template/src/lib.rs
sdk/move-bytecode-template/tests/universal.test.ts

- Adds 2 unit tests for `update_constants` method
- Asserts that the bytecode is not updated if there is an expected type miss match 
- Asserts that the bytecode is not updated if there is an expected value miss match 
- Updates deserialize doc comments
- Updates readme's template `DECIMALS` const to align with the bytecode that is found in the test files.
Tested by running `pnpm run test` in the `move-bytecode-template` sub folder
---

[sdks/move-bytecode-template] Adds unit tests + fixes

---

crates/sui-replay/src/batch_replay.rs
crates/sui-replay/src/replay.rs
crates/sui-replay/src/types.rs

There are two types of transactions that are currently not supported today:
- System transactions (we should fix this)
- Transactions with protocol version < 16. This is due to the dependency to wrapped tombstones, which we have no way of fetching.
When we see unsupported transactions, we should return error instead of Ok. And in that case we skip persisting them.
CI
---

[replay] Skip persisting unsupported transactions

---

crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/version.rs

This PR updates the version middleware to check for path based versions instead of header based versions.
Existing tests (updated + removed some). 
```
cd crates/sui-graphql-rpc && cargo test -- version
```
---
--- …

[GraphQL][cherry-pick] Switch to path based versioning (#17349)

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-network/src/state_sync/mod.rs
crates/sui-swarm-config/src/network_config_builder.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm/src/memory/swarm.rs
crates/test-cluster/src/lib.rs

- Do not stack timeouts in state sync
- Disable overload protection and make consensus submission very aggressive in tests
- Increase no-checkpoint timeout to 30s in simtests
After these changes, `test_simulated_load_reconfig_with_crashes_and_delays` can run for 400 seeds without failures.

Fixes to stabilize tests

---

crates/simulacrum/src/store/mod.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/transaction_input_loader.rs
crates/sui-single-node-benchmark/src/mock_storage.rs
crates/sui-single-node-benchmark/src/single_node.rs
crates/sui-transactional-test-runner/src/lib.rs

Previously we share the same code path between dryrun/devinspect and `read_objects_for_synchronous_execution`  when loading input objects. This is error prone. For instance, we check receiving objects in that path. But we should not check receiving objects when loading input for execution. This makes the end of epoch transaction vulnerable to any potential issue that code might lead to. In general, the mix of these two entirely separate concepts (one for builders, one for end-of-epoch transaction) is very dangerous.
This PR changes it such that the dryrun/devinpect uses the signing path, which is much less prone to mistakes, and probably is more aligned with the intention of dryrun/devinspect.
CI
---
Check each box that your changes affect. If none of the boxes relate to your changes, …

[core] Use read_objects_for_signing for dry run and devinspect

---

crates/sui-bridge/src/events.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

for better naming and fewer bytes
---

[bridge] rename  `TokenBridgeEvent` to `TokenDepositedEvent` and remove the message_type field

---

crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.exp
crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.move
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/event.rs
crates/sui-graphql-rpc/src/types/gas.rs
crates/sui-graphql-rpc/src/types/move_function.rs
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_object.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/move_struct.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/object_change.rs
crates/sui-graphql-rpc/src/types/object_read.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/suins_registration.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
crates/sui-graphql-rpc/src/types/validator.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs

Implement data loaders for fetching historical object versions, objects bounded by their parent versions, and the latest versions of an object at a given checkpoint.
By implementing an Object DataLoader, we also implicitly get support for data-loading all derived types (`MoveObject`, `MovePackage`, `MoveModule`, `DynamicField`, `Coin`, etc).
These implementations (particularly historical queries and queries where the version can be bounded by a parent version) can be made even more efficient with the existence of an index/side table that maps an object's ID and version to the checkpoint it is part of. This change has not been included in this PR, but we will follow up on this as part of Object query benchmarking.
As part of this change, I enabled queries for historical objects outside the …

[GraphQL] Object DataLoader

---

crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.exp
crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.move
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/event.rs
crates/sui-graphql-rpc/src/types/gas.rs
crates/sui-graphql-rpc/src/types/move_function.rs
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_object.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/move_struct.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/object_change.rs
crates/sui-graphql-rpc/src/types/object_read.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/suins_registration.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
crates/sui-graphql-rpc/src/types/validator.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs

Implement data loaders for fetching historical object versions, objects bounded by their parent versions, and the latest versions of an object at a given checkpoint.
By implementing an Object DataLoader, we also implicitly get support for data-loading all derived types (`MoveObject`, `MovePackage`, `MoveModule`, `DynamicField`, `Coin`, etc).
These implementations (particularly historical queries and queries where the version can be bounded by a parent version) can be made even more efficient with the existence of an index/side table that maps an object's ID and version to the checkpoint it is part of. This change has not been included in this PR, but we will follow up on this as part of Object query benchmarking.
As part of this change, I enabled queries for historical objects outside the …

[pick 2024.4][GraphQL] Object DataLoader (#17332)

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/version.rs

Cherry pick the version path into the GraphQL legacy release version (v2024.1.4).
---

[cherry-pick][graphql] Cherry pick version path

---

crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.exp
crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.move
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/event.rs
crates/sui-graphql-rpc/src/types/gas.rs
crates/sui-graphql-rpc/src/types/move_function.rs
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_object.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/move_struct.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/object_change.rs
crates/sui-graphql-rpc/src/types/object_read.rs
crates/sui-graphql-rpc/src/types/owner.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/suins_registration.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
crates/sui-graphql-rpc/src/types/validator.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs

Implement data loaders for fetching historical object versions, objects bounded by their parent versions, and the latest versions of an object at a given checkpoint.
By implementing an Object DataLoader, we also implicitly get support for data-loading all derived types (`MoveObject`, `MovePackage`, `MoveModule`, `DynamicField`, `Coin`, etc).
These implementations (particularly historical queries and queries where the version can be bounded by a parent version) can be made even more efficient with the existence of an index/side table that maps an object's ID and version to the checkpoint it is part of. This change has not been included in this PR, but we will follow up on this as part of Object query benchmarking.
As part of this change, I enabled queries for historical objects outside the …

[pick][GraphQL] Object DataLoader (#17332)

---

crates/sui-protocol-config/src/lib.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
external-crates/move/crates/move-compiler-transactional-tests/tests/evaluation_order/binop_aborts.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/evaluation_order/binop_aborts.move
external-crates/move/crates/move-compiler-transactional-tests/tests/evaluation_order/binop_call_struct.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/evaluation_order/binop_call_struct.move
external-crates/move/crates/move-compiler-transactional-tests/tests/evaluation_order/binop_calls.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/evaluation_order/binop_calls.move
external-crates/move/crates/move-compiler-transactional-tests/tests/evaluation_order/macro_calls.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/evaluation_order/macro_calls.move
external-crates/move/crates/move-compiler-transactional-tests/tests/macros/break_from_macro_arg.exp
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/shared/string_utils.rs

Fixes an issue in how binops evaluated their arguments, ensuring the LHS value is stored if the RHS has effect operations.
Tests thanks to Aptos: https://github.com/aptos-labs/aptos-core/pull/12936 
---

[move][bug] Fix binop ordering

---

sui_programmability/examples/crypto/sources/groth16.move

Add an example of how to verify a Groth16 zk-proof using Move and group_ops.
Unit tests.

Add Groth16 example

---

consensus/core/src/authority_node.rs
consensus/core/src/block.rs
consensus/core/src/block_manager.rs
consensus/core/src/block_verifier.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/context.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/linearizer.rs
consensus/core/src/test_dag_parser.rs
consensus/core/src/tests/base_committer_tests.rs
consensus/core/src/tests/pipelined_committer_tests.rs
consensus/core/src/tests/universal_committer_tests.rs

Swapping the `std::time::Instant` with the `tokio::time::Instant` for consistency across the Consensus crate. 
The caveat here is that the simtest framework will by default try to run the `#[test]` tests where a tokio reactor is not running. Since the `Context` now uses tokio components (Instant) the simtest framework starts complaining with errors:
```
there is no reactor running, must be called from the context of a Madsim runtime
```
after talking to @mystenmark it looks like there aren't too many ways to bypass this. On this PR I've just converted all the `#[test]` to `#[tokio::test]` as in this case simtests framework won't attempt to run them at all . An alternative would be to tag them as `#[cfg_attr(msim, ignore)]`. Let's evaluate at this point how important is for us to use …

[Consensus 2.0] update Clock to use the tokio Instant

---

crates/sui-config/src/p2p.rs
crates/sui-node/src/lib.rs

Bring max concurrency limits down to more reasonable numbers, also increases Quinn max streams to accommodate the new limits.

Tweak p2p network concurrency settings

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/errors/clever_errors.exp
crates/sui-graphql-e2e-tests/tests/errors/clever_errors.move
crates/sui-graphql-e2e-tests/tests/transactions/errors.exp
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-package-resolver/Cargo.toml
crates/sui-package-resolver/src/lib.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Adds support for clever errors to GraphQL. So now, if you have code like the following:
```move
module p::m {
#[error]
const ENotFound: vector<u8> = b"Element was unable to be found in the vector"
public fun abort() {
assert!(false, ENotFound); // Can also be an `abort ENotFound` 
}
}
```
This will result in a humand-readable output from graphql:
```
Error in 1st command
'ENotFound' from module '0x8fd7251015bfd1dc4283bb3d38dc95a2769f75d621c871a81bb9c191a2860aaf::m' in function 'abort' at source line 6
The element was unable to be found in the vector
```
Added tests for all supported constant types, along with tests to make sure that we properly handle package upgrades and resolving to the correct version of a package when resolving clever errors.
---
Check each box that your changes …

[graphql] Add support for clever error resolution in graphql

---

crates/sui-benchmark/src/lib.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/authority_client.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/quorum_driver/tests.rs
crates/sui-core/src/safe_client.rs
crates/sui-core/src/test_authority_clients.rs
crates/sui-core/src/transaction_orchestrator.rs
crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
crates/sui-e2e-tests/tests/full_node_tests.rs
crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
crates/sui-network/build.rs
crates/sui-types/src/committee.rs
crates/sui-types/src/messages_grpc.rs
crates/sui-types/src/quorum_driver_types.rs

This is a part of the "execution 2.0" effort where we allow for a client to request that a validator provides input/output objects for a certificate that it executes.
This PR does the following:
- Adds a new handle_certificate_v3 api to the Validator interface
- adds support to transaction_orchestrator, quorum_driver, and authority_aggregator to be able to conditionally call handle_certificate_v2/v3 depending on the provided request parameters
- Adds e2e test for ensuring that we can properly call the new api from transaciton_orchestrator -> quorum_driver -> authority_aggregator -> validator and back
The ability for end users to submit transactions and leverage this new mechanism to request input/output objects is not yet exposed (the existing v2 path is still used for all calls into …

validator-api: support validators returning input/output objects when executing a certificate

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-core/src/traffic_controller/policies.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-json-rpc/src/axum_router.rs
crates/sui-types/src/traffic_control.rs

* For error tallies, sample by `error_weight`, as defined by the originating server based on the error type. 
* For spam tallies, sample based on sampling weight, a new config parameter (by default, we will only tally 20% of "all traffic" for spam policy) 
---

[TrafficControl] Add sampling

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/graphiql_server.rs

Fix GraphiQL not loading on the new routes: `/:version` & `graphql/:version`
Existing tests & manual tests in the browser:
```bash
http://127.0.0.1:8000/graphql/beta
http://127.0.0.1:8000/graphql/stable
http://127.0.0.1:8000/graphql/legacy
http://127.0.0.1:8000/graphql/2024.7
http://127.0.0.1:8000/beta
http://127.0.0.1:8000/stable
http://127.0.0.1:8000/legacy
http://127.0.0.1:8000/2024.7
```
---

[GraphQL] Fix GraphiQL not loading on the new routes

---

consensus/core/src/block.rs
consensus/core/src/block_manager.rs
consensus/core/src/block_verifier.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/context.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/linearizer.rs
consensus/core/src/test_dag_parser.rs
consensus/core/src/tests/base_committer_tests.rs
consensus/core/src/tests/pipelined_committer_tests.rs
consensus/core/src/tests/universal_committer_tests.rs

This reverts commit f192bc2b0288b826f32f6ec391cd6e4a3717e980.
This was causing CI failures: https://github.com/MystenLabs/sui/actions/runs/8917965108/job/24491850786?pr=17465
---

Revert "[Consensus 2.0] update Clock to use the tokio Instant (#17357)"

---

crates/sui-json-rpc/src/axum_router.rs
crates/sui-json-rpc/src/transaction_execution_api.rs

Before, map based params to `executeTransactionBlock` worked fine, in addition to array based. Now we fail due to the introduced panic. So:
* Support map based params
* Allow for deserialization errors on user input to fallback to injecting no client addr (in this case, we route to `execute_transaction_block` rather than `monitored_execute_transaction_block`)
Ran from local build, and ran the curl request, and it looks to be getting past this point and instead failing due to the transaction missing a dependency that I don't have since I'm running from genesis
```
λ curl '127.0.0.1:9000' -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "id": 1, "method": "sui_executeTransactionBlock", "params": {"tx_bytes": "AAADAQA2D2S7yQT7LGUkRTntLEVU+d2nLEun34wEbhYGcszPqwEAAAAAAAAAILhTnZTKxFvh/ …
```

[TrafficControl] Support param injection on map params; add fallback

---

sui_programmability/examples/games/sources/drand_based_lottery.move
sui_programmability/examples/games/sources/drand_based_scratch_card.move
sui_programmability/examples/games/sources/drand_lib.move
sui_programmability/examples/games/sources/hero.move
sui_programmability/examples/games/sources/raffles.move
sui_programmability/examples/games/sources/rock_paper_scissors.move
sui_programmability/examples/games/sources/sea_hero.move
sui_programmability/examples/games/sources/sea_hero_helper.move
sui_programmability/examples/games/sources/shared_tic_tac_toe.move
sui_programmability/examples/games/sources/slot_machine.move
sui_programmability/examples/games/sources/tic_tac_toe.move
sui_programmability/examples/games/tests/drand_based_lottery_tests.move
sui_programmability/examples/games/tests/drand_based_scratch_card_tests.move
sui_programmability/examples/games/tests/raffles_tests.move
sui_programmability/examples/games/tests/rock_paper_scissors_tests.move
sui_programmability/examples/games/tests/shared_tic_tac_toe_tests.move
sui_programmability/examples/games/tests/slot_machine_tests.move
sui_programmability/examples/games/tests/tic_tac_toe_tests.move

Updates the `games` examples directory to use Move 2024 syntax
Local disassembly testing, plus all the tests still work. Would appreciate a careful review, though!
---

[move-2024][migration] Update `games` to use Move 2024 Syntax

---

consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/linearizer.rs
consensus/core/src/test_dag.rs
consensus/core/src/test_dag_builder.rs

This PR swaps the use of the `build_dag` method with the `DagBuilder`  in the `linearizer, commit_observer and dag_state`
CI
---

[Consensus 2.0] use DagBuilder

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

1. `get_token_transfer_action_signatures` and `get_token_transfer_action_status` does not need mutable Bridge ref
2. switch the order of Bridge and clock in `claim_token_internal` so we can use the receiver syntax
existing tests
---

[bridge] remove unnecessary &mut

---

external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/src/bin/move-analyzer.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/pkg-naming-error/Move.toml
external-crates/move/crates/move-analyzer/tests/pkg-naming-error/sources/M1.move
external-crates/move/crates/move-analyzer/tests/pkg-naming-error/sources/M2.move
external-crates/move/crates/move-analyzer/tests/pre-type-error/Move.toml

This PR fixes a problem with move-analyzer crashing if a dependency defined one package name in the source but the main package overrode this name with a new one. The gist of the problem was that we used package name to represent its identity which is not reliable due to above-mentioned renamings. What we need to do instead is to rely on package addresses whenever they are available.
Added a new test that was crashing the analyzer before this PR's fix.

[move-ide] Fixed a problem related to handling package identity

---

crates/sui-graphql-rpc/src/server/builder.rs

Move the middleware to the `build` function to avoid adding it multiple times due to multiple `route` calls in the `start_graphiql_server`, which was introduced in #17456.
http://127.0.0.1:8000/graphql/beta
http://127.0.0.1:8000/graphql/stable
http://127.0.0.1:8000/graphql/legacy
http://127.0.0.1:8000/graphql/2024.7
http://127.0.0.1:8000/beta
http://127.0.0.1:8000/stable
http://127.0.0.1:8000/legacy
http://127.0.0.1:8000/2024.7
---

[GraphQL] Move the version middleware route layer to build function

---

crates/sui-graphql-rpc/src/server/graphiql_server.rs

Fixes the endpoint for the GraphiQL service to always be `/graphql` + version if it is specified, regardless if the request is to `[...]/` or to `[...]/graphql`.  
Visually in the browser. Checked: 
* bad version `/graphql/test` is caught: ✅ 
* good version works `/graphql` or `/` or `/stable` or `/legacy`: ✅ 
* if the routing actually goes where it needs
---

[GraphQL] Fix endpoint for GraphiQL IDE

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/graphiql_server.rs

Fix GraphiQL not loading on the new routes: `/:version` & `graphql/:version`
Existing tests & manual tests in the browser:
```bash
http://127.0.0.1:8000/graphql/beta
http://127.0.0.1:8000/graphql/stable
http://127.0.0.1:8000/graphql/legacy
http://127.0.0.1:8000/graphql/2024.7
http://127.0.0.1:8000/beta
http://127.0.0.1:8000/stable
http://127.0.0.1:8000/legacy
http://127.0.0.1:8000/2024.7
```
---

[cherry-pick][GraphQL] Cherry pick fix graphiql into v2024.1.4

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/graphiql_server.rs

Fix GraphiQL not loading on the new routes: `/:version` & `graphql/:version`
Existing tests & manual tests in the browser:
```bash
http://127.0.0.1:8000/graphql/beta
http://127.0.0.1:8000/graphql/stable
http://127.0.0.1:8000/graphql/legacy
http://127.0.0.1:8000/graphql/2024.7
http://127.0.0.1:8000/beta
http://127.0.0.1:8000/stable
http://127.0.0.1:8000/legacy
http://127.0.0.1:8000/2024.7
```
---

[cherry-pick][GraphQL] Cherry pick fix graphiql into v2024.4

---

external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/macros/Move.toml
external-crates/move/crates/move-analyzer/tests/macros/sources/fun_type.move
external-crates/move/crates/move-analyzer/tests/move-2024/Move.toml

This PR adds support for on-hover displaying function types (`entry` and `macro`)
A test has been added.

[move-ide] Added support for displaying function types

---

.github/workflows/github-issues-monitor.yml

When a PR is created, this workflow will pick it up and find if it is from someone in the MystenLabs organization or not. If it is not, then it will push a Slack message to notify us of this PR coming from an external contributor.
---

[CI] Add external PRs to the github-issues workflow

---

external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs
external-crates/move/crates/move-compiler/tests/sui_mode/id_leak/private_pack.exp
external-crates/move/crates/move-compiler/tests/sui_mode/id_leak/private_pack.move

- Fixes #17426
- The id-leak assumed pack visibility was a blocking error 
- Added a test 
---

[bug fix][move] Removed compiler unwrap

---

crates/sui-replay/src/batch_replay.rs
crates/sui-replay/src/lib.rs
crates/sui-replay/src/replay.rs
crates/sui-replay/src/types.rs
crates/sui/src/client_commands.rs

This PR adds sandbox file format option (json or bcs) to batch replay.
Only batch replay needs this because otherwise we prefer json as we don't care about the size of the files.
This cuts the size of a sandbox file by 70%.
Also fixing a bug in the dev inspect tracing execution: it's not always guaranteed that the transaction execution would succeed.
Run locally
---

[replay] Add bcs format support for sandbox file during replay

---

external-crates/move/crates/move-compiler/src/editions/mod.rs
external-crates/move/crates/move-compiler/src/shared/string_utils.rs
external-crates/move/crates/move-compiler/tests/move_check/feature_gate/macro_call.exp
external-crates/move/crates/move-compiler/tests/move_check/feature_gate/macro_definition.exp
external-crates/move/crates/move-compiler/tests/move_check/feature_gate/macro_lambda.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/type_hole_gated_invalid_usage.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/type_hole_gated_valid_usage.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/spec_parsing_lambda_fail.exp

- Change edition gating for macros and type holes to beta
- ran tests
---

[move] macros and type holes to 2024.beta

---

sui_programmability/examples/README.md

Add a message to indicate that these examples are out-of-date and that people should go to the `examples` directory instead.
:eyes:
---

[Docs] Deprecate sui_programmability examples

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-types/src/error.rs
crates/sui-types/src/transaction.rs

1. We only call validity_check once on a transaction.
2. Make the validity_check path identical for all cases.
3. Remove some out-of-dated comments
4. Also check transaction expiration during validity check.
CI
---

[core] More cleanup on transaction validity check

---

crates/sui-graphql-e2e-tests/tests/errors/clever_errors_in_macros.exp
crates/sui-graphql-e2e-tests/tests/errors/clever_errors_in_macros.move
external-crates/move/crates/move-compiler-transactional-tests/tests/constants/macro_call_line_number_assertion.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/constants/macro_call_line_number_assertion.move
external-crates/move/crates/move-compiler/src/cfgir/borrows/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/liveness/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/locals/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/optimize/constant_fold.rs
external-crates/move/crates/move-compiler/src/cfgir/optimize/eliminate_locals.rs
external-crates/move/crates/move-compiler/src/cfgir/visitor.rs
external-crates/move/crates/move-compiler/src/hlir/ast.rs
external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/naming/ast.rs
external-crates/move/crates/move-compiler/src/naming/resolve_use_funs.rs
external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/src/to_bytecode/translate.rs
external-crates/move/crates/move-compiler/src/typing/ast.rs
external-crates/move/crates/move-compiler/src/typing/dependency_ordering.rs
external-crates/move/crates/move-compiler/src/typing/expand.rs
external-crates/move/crates/move-compiler/src/typing/infinite_instantiations.rs
external-crates/move/crates/move-compiler/src/typing/macro_expand.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/src/typing/visitor.rs

- Added support for `assert!(cond)` line numbers inside of macros. The line number will point to the invocation of the macro, instead of the line where the assert was written. This should be helpful for cross-module macro invocations with `assert` and error codes
- Thanks @alnoki for the discussion leading to this improvement! 
- Added new tests
- The line numbers are a bit off in transactional tests, so I temporarily and localy added compiler warnings to verify the line numbers correspond to the correct loc. 
--- …

[move] Added special support for clever errors in macros

---

crates/suiop-cli/src/cli/docker/mod.rs
crates/suiop-cli/src/cli/mod.rs
crates/suiop-cli/src/main.rs

First bit of making service platform tooling work for ts services – generate dockerfiles for existing projects.
```bash
cr -- docker g
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Compiling suiop-cli v0.1.9 (/Users/jkjensen/mysten/sui/crates/suiop-cli)
Finished dev [unoptimized + debuginfo] target(s) in 5.02s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop docker g`
2024-04-25T20:13:11.901549Z  INFO suioplib::cli::docker: Generating Dockerfile
```
--- …

[suiop] stub out docker command for dockerfile generation

---

crates/sui-tool/src/commands.rs
crates/sui-tool/src/lib.rs

1. add `LockedObject` command to check if a object is locked and rescue it if possible (by `--rescue` flag). It can also check all gas objects owned by one accounts in case there are potentially many gas objects get locked.
2. rework the grouping logic for `FetchObject`, now it displays more clear aggregated lock info .
3. remove `genesis` param from a few commands, and replace with `fullnode-url` to fetch committee info.
```
sui-tool locked-object --address 0x02a212de6a9dfa3a69e22387acfbafbb1a9e591bd9d636e7895dcfc8de05f331 --fullnode-rpc-url https://rpc.mainnet.sui.io:443
sui-tool locked-object --id 0xd4c3ecf5eaa211da58c36495613899e70349f6048baaeca99596f1682e89c837 --fullnode-rpc-url https://rpc.mainnet.sui.io:443
```
---
Check each box that your changes affect. If none of the boxes …

[sui-tool] check locked objects and rescue flow

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/shared_object_congestion_tracker.rs
crates/sui-core/src/epoch/randomness.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_32.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_33.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_34.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_35.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_36.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_37.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_38.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_39.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_40.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_41.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_42.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_43.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_44.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_45.snap

Most substantive:
- Longer delay until DKG failure.
- Preserve original deferral round when randomness-deferred tx becomes congestion-deferred tx and vice versa.

Tweaks for random beacon from code walkthrough

---

crates/sui-graphql-rpc/src/server/builder.rs

A previous [PR](https://github.com/MystenLabs/sui/pull/17420) only introduced one route, but both routes are needed. 
---

[GraphQL][v2024.1] Fix missing route inside init_router function

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/ci/key.rs
crates/suiop-cli/src/cli/ci/mod.rs
crates/suiop-cli/src/cli/iam/mod.rs
crates/suiop-cli/src/cli/iam/whoami.rs
crates/suiop-cli/src/cli/lib/mod.rs
crates/suiop-cli/src/cli/mod.rs
crates/suiop-cli/src/main.rs

With this change, we can now create/recreate/delete deploy keys for our users and the private keys will be stored securely instead of on users' laptop.
suiop here is just a client, all it does is authn the user and use the returned Okta token to the infra-metadata-service endpoint for ssh key generation.
Manually tested, for example, to create a deploy key:
`suiop ci key create --repo-name suiop-test`
```
Public Key:
-------------------------
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPn4Rj84+AGRPJNx2QVV7R8gURJHxicC0YW1UKWLOlz0 pulumi_automation_deploy_key
-------------------------
Please add the public key above to your repository suiop-test via the link below:
https://github.com/MystenLabs/suiop-test/settings/keys/new
```
A new key will be created automatically and user will be prompted to …

[suiop] add support for deploy key automation

---

.cargo/config
.github/workflows/rust.yml
crates/sui-indexer/src/models/events.rs
crates/sui-indexer/src/schema/mod.rs

Without this PR, with xclippy we run `cargo clippy --all-features` but that does not get run on mysql protected code since we enable only one code path i.e. either postgres or mysql and postgres is set as default everywhere. We want to however run clippy on mysql code paths as well. With this, we should be able to do so.
This PR

Add a new clippy target to run on mysql feature protected code

---

crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/docs/bridge/committee.md
crates/sui-framework/docs/bridge/crypto.md
crates/sui-framework/docs/bridge/limiter.md
crates/sui-framework/docs/bridge/treasury.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-framework/packages/bridge/sources/chain_ids.move
crates/sui-framework/packages/bridge/sources/committee.move
crates/sui-framework/packages/bridge/sources/crypto.move
crates/sui-framework/packages/bridge/sources/limiter.move
crates/sui-framework/packages/bridge/sources/message.move
crates/sui-framework/packages/bridge/sources/treasury.move
crates/sui-framework/packages/bridge/tests/commitee_test.move
crates/sui-framework/packages/bridge/tests/limiter_tests.move
crates/sui-framework/packages/bridge/tests/message_tests.move
crates/sui-framework/published_api.txt
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Mostly moved tests in their own files. Particularly tests that have to be expanded.
Move 2024 cleanup.
Formatting and convention alignment.
This is almost no change except for few visibility changes we will talk about
Existing test, no feature added
---

tests and move 2024 cleanup

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/validator.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Deprecates the ` exchange_rates` and `staking_pool` resolvers on validator type, and adds a `staking_pool_id` and `exchange_rates_table` resolver to correctly return the staking pool id and the wrapped exchange rates object.
```
cd sui-graphql-e2e-tests && cargo nextest run --features pg_integration
```
---

[GraphQL] 

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/validator.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Deprecates the ` exchange_rates` and `staking_pool` resolvers on validator type, and adds a `staking_pool_id` and `exchange_rates_table` resolver to correctly return the staking pool id and the wrapped exchange rates object.
```
cd sui-graphql-e2e-tests && cargo nextest run --features pg_integration
```
---

[cherry-pick][graphql] Cherry pick exchange rates

---

crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/transaction_block.rs
crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
crates/sui-indexer/src/db.rs
crates/sui-indexer/src/models/transactions.rs

Implement Transaction DataLoader using the `tx_digests` lookaside table to translate digests into a checkpoint and transaction sequence number that can be used to query into the partitioned transactions table without having to query each partition.
```
sui$ cargo nextest run
sui-graphql-e2e-tests$  cargo nextest run --features pg_integration
```
And run the following query, which should perform better after this optimisation:
```graphql
query {
objects(first: 10) {
nodes {
previousTransactionBlock {
effects {
status
dependencies(first: 10) {
nodes {
digest
effects {
status
dependencies(first: 10) {
nodes {
effects {
status
}
}
}
}
}
}
}
}
}
}
}
```

[GraphQL/DataLoader] Transaction DataLoader

---

crates/sui-replay/src/batch_replay.rs
crates/sui-replay/src/lib.rs
crates/sui-replay/src/types.rs
crates/sui/src/client_commands.rs

Unfortunately the json-rpc types cannot be stably serde-ed.
CI
---

[replay] Remove bcs serde support for sandbox data

---

crates/sui-move-build/src/lib.rs
crates/sui/tests/cli_tests.rs
external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/linters/mod.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/coin_field.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/collection_equality.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/custom_state_change.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/freeze_wrapped.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/mod.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/public_random.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/self_transfer.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/share_owned.rs
external-crates/move/crates/move-compiler/tests/sui_mode/linter/coin_field.exp
external-crates/move/crates/move-compiler/tests/sui_mode/linter/collection_equality.exp
external-crates/move/crates/move-compiler/tests/sui_mode/linter/custom_state_change.exp
external-crates/move/crates/move-compiler/tests/sui_mode/linter/freeze_wrapped.exp
external-crates/move/crates/move-compiler/tests/sui_mode/linter/public_random_invalid.exp
external-crates/move/crates/move-compiler/tests/sui_mode/linter/self_transfer.exp
external-crates/move/crates/move-compiler/tests/sui_mode/linter/share_owned.exp
external-crates/move/move-execution/v0/crates/move-bytecode-verifier/src/instantiation_loops.rs
external-crates/move/move-execution/v2/crates/move-bytecode-verifier/src/check_duplication.rs

- Fixing an issue exposed in #16819. Since Sui lints use the `lint` prefix for suppression, we need to make sure all category/code combos are distinct.
- Added new lint categories, with a specific one for Sui lints
- Updated tests 
---

[move] Fix linter categories

---

consensus/core/src/commit.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/leader_scoring_strategy.rs
consensus/core/src/lib.rs
consensus/core/src/stake_aggregator.rs
consensus/core/src/universal_committer.rs

This is one of many PRs to implement Leader Scoring & Leader Schedule feature for Mysticeti.
- [Design Doc](https://www.notion.so/mystenlabs/Leader-Schedule-Scoring-538c65cb370b4644944a94485efc4979?pvs=4)
- [Prototype PR](https://github.com/MystenLabs/sui/pull/16975)
Notes:
- Unscored subdags will eventually be cached in `DagState` and when there are enough commits to trigger a leader schedule change the `ReputationScoreCalculator` will be used to calculate the `ReputationScores`. As can be seen in the flow diagram below.
- Added multiple scoring strategies so that we can experiment with them quickly until we decided on the strategy that is best to use. By default we will use the `VoteScoringStrategy` when everything is hooked up as it had the best early …

[consensus] Add ReputationScoreCalculator & ScoringStrategy

---

external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/mod.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/shared/string_utils.rs
external-crates/move/crates/move-compiler/src/typing/ast.rs
external-crates/move/crates/move-compiler/src/typing/core.rs
external-crates/move/crates/move-compiler/src/typing/dependency_ordering.rs
external-crates/move/crates/move-compiler/src/typing/expand.rs
external-crates/move/crates/move-compiler/src/typing/match_compilation.rs
external-crates/move/crates/move-compiler/src/typing/mod.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/development/enums/matching/invalid_binding_var.exp
external-crates/move/crates/move-compiler/tests/development/enums/matching/invalid_head_ctor.exp
external-crates/move/crates/move-compiler/tests/development/enums/matching/invalid_head_ctor_2.exp
external-crates/move/crates/move-compiler/tests/development/enums/matching/invalid_mut_2.exp
external-crates/move/crates/move-compiler/tests/development/enums/matching/invalid_mut_3.exp
external-crates/move/crates/move-compiler/tests/development/enums/matching/invalid_mut_4.exp
external-crates/move/crates/move-compiler/tests/development/enums/matching/multi_or_not_exhaustive.exp
external-crates/move/crates/move-compiler/tests/development/enums/naming/pattern_ellipsis_invalid.exp
external-crates/move/crates/move-compiler/tests/development/enums/parser/invalid_mut_usage_match.exp

This migrates match compilation to happen in typing, in order to better-support IDE integartion.
A few updated tests, but everything else is still the same.
---

[move-2024][enums][ide] Compile match in typing

---

.changeset/four-experts-boil.md
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_45.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_45.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_45.snap
crates/sui-types/src/execution_config_utils.rs
external-crates/move/crates/move-binary-format/src/binary_config.rs
external-crates/move/crates/move-binary-format/src/deserializer.rs
external-crates/move/crates/move-binary-format/src/unit_tests/deserializer_tests.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/loader.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/runtime.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/loader.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/runtime.rs
sdk/graphql-transport/src/methods.ts

Adds a minimum binary version to the deserializer, and plumbs this into the protocol config.
Make sure existing tests pass, and also added a deserializer test to make sure we raise the correct error for a too-low binary version module. 
---

[move] Add minimum binary version

---

crates/sui/src/client_commands.rs

Adds two small checks to give better error messages if a package with an unsupported binary version number is published to a specific network.
Tested locally against enum changes.
---

[CLI] Add module binary version check when publishing and upgrading modules

---

crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs

There isn't a way to configure `db_pool_size` on `ConnectionConfig` since it's not exposed on `start_server`. This is a simple PR that exposes it, and bumps the default pool size from 3 to 10. This is because we already have a few background tasks in addition to the main graphql service.
---
- [ x] GraphQL: Expose an additional parameter `db_pool_size` on `start-server` command so that users can configure how many db connections the graphql service will spin up for its …

[gql] expose db_pool_size on ConnectionConfig

---

crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs

There isn't a way to configure `db_pool_size` on `ConnectionConfig` since it's not exposed on `start_server`. This is a simple PR that exposes it, and bumps the default pool size from 3 to 10. This is because we already have a few background tasks in addition to the main graphql service.
---
--- …

[gql] expose db_pool_size on ConnectionConfig (#17595)

---

consensus/core/src/authority_node.rs
consensus/core/src/block.rs
consensus/core/src/block_manager.rs
consensus/core/src/block_verifier.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/context.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/leader_scoring_strategy.rs
consensus/core/src/linearizer.rs
consensus/core/src/test_dag_parser.rs
consensus/core/src/tests/base_committer_tests.rs
consensus/core/src/tests/pipelined_committer_tests.rs
consensus/core/src/tests/universal_committer_tests.rs

This is an attempt to re-merge the changes of an earlier PR that reverted here https://github.com/MystenLabs/sui/pull/17467.
CI/locally
---

[Consensus 2.0] convert use of std::time::Instant to tokio::time::Instant

---

crates/sui-cost/tests/data/dummy_modules_publish/sources/trusted_coin.move
crates/sui-framework/docs/move-stdlib/ascii.md
crates/sui-framework/docs/move-stdlib/option.md
crates/sui-framework/docs/move-stdlib/string.md
crates/sui-framework/docs/move-stdlib/type_name.md
crates/sui-framework/docs/move-stdlib/vector.md
crates/sui-framework/docs/sui-framework/vec_map.md
crates/sui-framework/packages/move-stdlib/sources/ascii.move
crates/sui-framework/packages/move-stdlib/sources/bit_vector.move
crates/sui-framework/packages/move-stdlib/sources/fixed_point32.move
crates/sui-framework/packages/move-stdlib/sources/option.move
crates/sui-framework/packages/move-stdlib/sources/string.move
crates/sui-framework/packages/move-stdlib/sources/type_name.move
crates/sui-framework/packages/move-stdlib/sources/vector.move
crates/sui-framework/packages/move-stdlib/tests/ascii_tests.move
crates/sui-framework/packages/move-stdlib/tests/bit_vector_tests.move
crates/sui-framework/packages/move-stdlib/tests/fixedpoint32_tests.move
crates/sui-framework/packages/move-stdlib/tests/option_tests.move
crates/sui-framework/packages/move-stdlib/tests/string_tests.move
crates/sui-framework/packages/move-stdlib/tests/vector_tests.move
crates/sui-framework/published_api.txt
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
crates/sui/tests/data/dummy_modules_publish/sources/trusted_coin.move

Adds new methods to `std::ascii`:
- `ascii::append(&mut String, String)`
- `ascii::is_empty(): bool`
- `ascii::substring(&String, i, j): String`
- `ascii::index_of(&String, &String): u64`
- `ascii::to_uppercase(&String): String`
- `ascii::to_lowercase(&String): String`
_So ASCII interface is similar to the one in UTF8_
Renames:
- `string::bytes() -> string::as_bytes()`
- `string::sub_string() -> string::substring()`
Additionally:
- updates `std::type_name` to use `std::substring`
- removes use statements for implicit imports
- renames constants from `E_INDEX` to conventional `EIndexOutOfBounds`
Features tests
For each box you select, include information after the relevant …

[std] Better ASCII methods + minor cleanup in std

---

Cargo.lock
crates/simulacrum/src/lib.rs
crates/sui-core/benches/batch_verification_bench.rs
crates/sui-core/benches/verified_cert_cache_bench.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/signature_verifier.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/batch_verification_tests.rs
crates/sui-core/src/unit_tests/execution_driver_tests.rs
crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs
crates/sui-rosetta/src/construction.rs
crates/sui-types/Cargo.toml
crates/sui-types/src/multisig.rs
crates/sui-types/src/multisig_legacy.rs
crates/sui-types/src/signature.rs
crates/sui-types/src/signature_verification.rs
crates/sui-types/src/transaction.rs
crates/sui-types/src/unit_tests/intent_tests.rs
crates/sui-types/src/unit_tests/messages_tests.rs
crates/sui-types/src/unit_tests/multisig_tests.rs
crates/sui-types/src/unit_tests/utils.rs
crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs
crates/sui-types/src/zk_login_authenticator.rs
crates/sui/src/keytool.rs

- moved the caching definition to sui-types
- pass down the zklogin cache to the authenticator trait themselves from verify_claims
- move the caching check logic inside zklogin authenticator: if hash_input is in cache, skip the verify_zklogin_inputs. otherwise, verify_zklogin_inputs, if its ok, cache it, else return error for txn and do not cache. 
- 
---

add caching for zklogin verify

---

crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/transaction_block.rs
crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
crates/sui-indexer/src/db.rs
crates/sui-indexer/src/models/transactions.rs

Implement Transaction DataLoader using the `tx_digests` lookaside table to translate digests into a checkpoint and transaction sequence number that can be used to query into the partitioned transactions table without having to query each partition.
```
sui$ cargo nextest run
sui-graphql-e2e-tests$  cargo nextest run --features pg_integration
```
And run the following query, which should perform better after this optimisation:
```graphql
query {
objects(first: 10) {
nodes {
previousTransactionBlock {
effects {
status
dependencies(first: 10) {
nodes {
digest
effects {
status
dependencies(first: 10) {
nodes {
effects {
status
}
}
}
}
}
}
}
}
}
}
}
```
--- …

[pick][GraphQL/DataLoader] Transaction DataLoader (#17042)

---

docs/content/references/sui-sdks.mdx
docs/content/sidebars/references.js

add dapp-kit (vue) link to docs reference

docs: add dapp-kit (vue) to reference docs on siderbar

---

docs/content/concepts/cryptography/zklogin.mdx
docs/content/guides/developer/cryptography/multisig.mdx

fix some links and make multisig page inter linked. 
---

fix: update links

---

docs/content/guides/developer/cryptography/ecvrf.mdx

The hexdecimal of `Hello, World!` is not `48656c6c6f2c20776f726c6421`, in which `W`'s hexdecimal should be 57, while 77 corresponds to `w`.
---

Update ecvrf.mdx for hexdecimal mismatch

---

.github/workflows/simulator-nightly-mysticeti.yml
.github/workflows/simulator-nightly-narwhal.yml
.github/workflows/simulator-nightly.yml
crates/sui-benchmark/tests/simtest.rs

Simtest has been timing out for awhile, because of increased transaction workload. Reducing the transactions sent from Sui surfer and increase simtest nightly timeout.
CI
https://github.com/MystenLabs/sui/actions/runs/9012876888: probably will be cancel by other runs, but worth checking if it is taking too long.
---

[Simtest] reduce surfer traffic and increase simtest nightly timeout

---

crates/sui-core/src/authority/shared_object_version_manager.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_validator.rs
crates/sui-core/src/unit_tests/consensus_tests.rs
crates/sui-core/src/unit_tests/transaction_manager_tests.rs
crates/sui-types/src/object.rs

We have two test utils that create a random shared object
- shared_for_testing, which returns a shared object always with the same ID when calling from the same thread
- with_id_shared_for_testing, which returns a random shared object each time called
Looking at the history of shared_for_testing, it was first created to be used in a specific test, where a random object ID
is hard coded. Later on, the function is gradually moved to be a global test util, but the move always tries to preserve the
function semantic that when called multiple times, same object ID is used. Particularly, test_certificates() expects using the same shared object as the tests calling this function.
Therefore, we probably don't want to have a shared_for_testing with a surprising semantics. This PR merges …

Update test util for creating shared objects

---

consensus/core/src/authority_node.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/error.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/leader_scoring_strategy.rs
consensus/core/src/metrics.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs

This is one of many PRs to implement Leader Scoring & Leader Schedule feature for Mysticeti.
- [Design Doc](https://www.notion.so/mystenlabs/Leader-Schedule-Scoring-538c65cb370b4644944a94485efc4979?pvs=4)
- [Prototype PR](https://github.com/MystenLabs/sui/pull/16975)
Leader Schedule Change Notes:
- We can choose the scoring strategy via an env var similar to how we are doing for networking. Will submit the workflow changes so this is easily configurable via gh deploy workflows
- In practice it looks like the LeaderSchedule change takes about [250](https://metrics.sui.io/goto/5pPPAExSR?orgId=1)-[500ms](https://metrics.sui.io/goto/qifU0ExIR?orgId=1) depending on the scoring strategy chosen. While this is not negatively impacting performance it does mean that there is additional room for …

[consensus] Hookup LeaderSchedule change & Recovery paths

---

crates/sui-proxy/src/admin.rs
crates/sui-proxy/src/lib.rs
crates/sui-tls/src/lib.rs
crates/sui-tls/src/verifier.rs

Reuse the self signed client cert verification logic for verifying self signed server cert.
Allow flexible server name.
Allow getting public key from cert to be used outside of sui-tls crate.
CI
---

[tls] add ServerCertVerifier

---

crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-e2e-tests/tests/call/simple.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/schema/draft_target_schema.graphql
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Adds available versions query to the service config. Uses the crate's version if no `versions` section exists in the `config.toml` file.
Existing tests. Manual query on local instance. 
```graphql
{
serviceConfig {
availableVersions
}
}
```
```json
{
"data": {
"serviceConfig": {
"availableVersions": [
"2024.7"
]
}
}
}
```
```toml
[limits]
max-query-depth = 15
max-query-nodes = 500
max-output-nodes = 100000
max-query-payload-size = 5000
max-db-query-cost = 20000
default-page-size = 5
max-page-size = 10
request-timeout-ms = 15000
max-type-argument-depth = 16
max-type-argument-width = 32
max-type-nodes = 256
max-move-value-depth = 128
[versions]
versions = ["2024.1", "2024.4", "2024.7"]
```
Same query
```json
{
"data": {
"serviceConfig": {
"availableVersions": [
"2024.1",
"2024.4",
"2024.7" …
```

[GraphQL] Add available versions query to service config

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/metrics.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs

Dry run previously only applied to validators. This change refactors such that it will apply to all callsites of `TrafficController::check`
---

[Traffic Control] Fix dry-run for fullnodes

---

.github/workflows/release.yml
binary-build-list.json

Add internal builds to the dictionary
```
eugene@eugene-dev ~/code/sui (ebmifa/add_internal_binary_list) $ cat ./binary-build-list.json | jq -r '.release_binaries[]'
sui
sui-node
sui-tool
sui-faucet
sui-test-validator
sui-data-ingestion
sui-bridge
sui-bridge-cli
sui-graphql-rpc
```

Add internal build names  to dictionary

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/consensus_tests.rs
crates/sui-single-node-benchmark/src/mock_consensus.rs

Move consensus commit prologue transaction creation after all the transitions in a consensus commit
is processed, and before shared object versions are assigned.
This is to prepare for adding cancelled transaction info into the consensus commit prologue message later.
Unit test added.
---

Create consensus commit prologue transaction after finishing processing other transactions in a consensus commit batch

---

crates/sui-indexer/src/indexer_reader.rs

Right now we are setting the key of the cache to be the raw string `"{ format!("{}{}", package_id, obj_type) }"`, which does not change with the input causing the cache to essentially store the first entry and always returning it. This PR fixes that. I've scanned the code base and changed the only two occurrences of `cache_get_or_set_with`
tested locally
---

[indexer] properly set key for cache in indexer reader

---

consensus/config/src/parameters.rs
consensus/core/src/base_committer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/leader_scoring_strategy.rs
consensus/core/src/universal_committer.rs
crates/sui-core/src/consensus_adapter.rs

Issue found via failining simtest
```
RUST_LOG=info,consensus=debug MSIM_TEST_SEED=161715360837 MSIM_TEST_NUM=1 MSIM_WATCHDOG_TIMEOUT_MS=60000 SIM_STRESS_TEST_DURATION_SECS=300   scripts/simtest/cargo-simtest simtest     --color always     --package sui-benchmark     --test-threads 1     --profile simtestnightly test_simulated_load_with_reconfig_and_correlated_crashes
```
Added logging to confirm
```
2022-03-02T00:44:12.689178Z  INFO node{id=5 name="k#99f25ef6.."}: consensus_core::leader_schedule: consensus/core/src/leader_schedule.rs:75: Recovering LeaderSchedule from store using LeaderSwapTable for CommitRange(21..31), good_nodes:[] with stake:0, bad_nodes:Map { iter: [] } with stake:0
2022-03-02T00:44:12.689178Z  INFO node{id=5 name="k#99f25ef6.."}: consensus_core::leader_schedule: …
```

[consensus] Fix for stuck leader schedule on recovery

---

crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/quorum_driver/tests.rs
crates/sui-core/src/test_authority_clients.rs
crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
crates/sui-types/src/error.rs

ValidatorOverloadedRetryAfter error contains a server suggested retry after duration. So when the quorum driver retries under SystemOverloadRetryAfter error, it should take the suggested retry duration into consideration.
Unit tests added.
---

Quorum driver take server requested retry interval into consideration

---

consensus/core/src/authority_node.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/leader_scoring_strategy.rs
consensus/core/src/tests/pipelined_committer_tests.rs
consensus/core/src/tests/universal_committer_tests.rs
consensus/core/src/universal_committer.rs
crates/sui-core/src/consensus_types/consensus_output_api.rs

Currently score ties are broken with authority index, which can bias leader selection to nodes with lower authority index. Instead, shuffle the scores based on commit index, then stable sort scores.
Use a separate type `DecidedLeader` to represent leader slots that are either committed or skipped.
CI
---

[Consensus] break score ties in randomized and deterministic order

---

crates/suiop-cli/dockerfile-templates/typescript.Dockerfile
crates/suiop-cli/src/cli/docker/mod.rs
crates/suiop-cli/src/main.rs

Working dockerfile generation for typescript express services
```
> cr --bin suiop -- d g --runtime ts --path /tmp/docker
Blocking waiting for file lock on build directory
Compiling suiop-cli v0.2.0 (/Users/jkjensen/mysten/sui/crates/suiop-cli)
Finished dev [unoptimized + debuginfo] target(s) in 30.63s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop d g --runtime ts --path /tmp/docker`
2024-05-07T15:51:11.767616Z  INFO suioplib::cli::docker: Generating Dockerfile for Typescript in "/tmp/docker"
```
```
> docker build -t jk-exp-0 -f /tmp/docker/Dockerfile . && docker run -p 8080:8080 jk-exp-0 
[+] Building 2.5s (20/20) FINISHED                                             docker:desktop-linux
=> [internal] load build definition from Dockerfile …
```

[suiop][docker-gen] e2e ts dockerfile template generation

---

crates/sui-network/src/randomness/mod.rs

Previously these would not be removed until end of epoch.

Randomness: remove partial sigs when full sig is received via checkpoint

---

crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-e2e-tests/tests/call/simple.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/schema/draft_target_schema.graphql
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Adds available versions query to the service config. Uses the crate's version if no `versions` section exists in the `config.toml` file.
Existing tests. Manual query on local instance. 
```graphql
{
serviceConfig {
availableVersions
}
}
```
```json
{
"data": {
"serviceConfig": {
"availableVersions": [
"2024.7"
]
}
}
}
```
```toml
[limits]
max-query-depth = 15
max-query-nodes = 500
max-output-nodes = 100000
max-query-payload-size = 5000
max-db-query-cost = 20000
default-page-size = 5
max-page-size = 10
request-timeout-ms = 15000
max-type-argument-depth = 16
max-type-argument-width = 32
max-type-nodes = 256
max-move-value-depth = 128
[versions]
versions = ["2024.1", "2024.4", "2024.7"]
```
Same query
```json
{
"data": {
"serviceConfig": {
"availableVersions": [
"2024.1",
"2024.4",
"2024.7" …
```

[cherry-pick][GraphQL]Gql cherry pick available versions

---

crates/sui-indexer/migrations/pg/2023-10-06-204335_tx_indices/up.sql
crates/sui-indexer/src/schema/pg.rs

One transaction can call multiple functions in a package so the primary key should include all parts of a function - package, module, func.
---

[indexer] primary key of tx_calls should include module and func

---

crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs

this endpoint assumes the transaction sender is a single zklogin but not a multisig. this should be agnostic to what the transaction sender is from single zklogin or multisig
---

fix: use derived author for zklogin verify signature

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/errors/clever_errors.exp
crates/sui-graphql-e2e-tests/tests/errors/clever_errors.move
crates/sui-graphql-e2e-tests/tests/transactions/errors.exp
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/transaction_block_effects.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-package-resolver/Cargo.toml
crates/sui-package-resolver/src/lib.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Adds support for clever errors to GraphQL. So now, if you have code like the following:
```move
module p::m {
#[error]
const ENotFound: vector<u8> = b"Element was unable to be found in the vector"
public fun abort() {
assert!(false, ENotFound); // Can also be an `abort ENotFound` 
}
}
```
This will result in a humand-readable output from graphql:
```
Error in 1st command
'ENotFound' from module '0x8fd7251015bfd1dc4283bb3d38dc95a2769f75d621c871a81bb9c191a2860aaf::m' in function 'abort' at source line 6
The element was unable to be found in the vector
```
Added tests for all supported constant types, along with tests to make sure that we properly handle package upgrades and resolving to the correct version of a package when resolving clever errors.
---
Check each box that your changes …

[cherry-pick][graphql] Add support for clever error resolution in graphql (#17338)

---

crates/sui-core/src/unit_tests/transaction_tests.rs
crates/sui-types/src/base_types.rs
crates/sui-types/src/transaction.rs

Removes the need for several asserts, since all failures will now be deserialization errors

Use NonEmpty for SenderSignedData

---

crates/sui-cluster-test/src/cluster.rs
crates/sui-sdk/src/sui_client_config.rs
crates/sui/src/client_commands.rs
crates/sui/src/sui_commands.rs
crates/test-cluster/src/lib.rs

Add option to provide basic auth in a client environment. This is then used to create the RPC client.
Tried locally
---

[sui-client] Add basic auth option to client rpc config

---

crates/sui-json-rpc/src/error.rs
crates/sui-types/src/error.rs
crates/sui/tests/snapshots/ptb_files_tests__move_call_fun_resolution.ptb.snap

Like the following example error messages contains a redundant trailing dot.
```
Transaction execution failed due to issues with transaction inputs, please review the errors and try again: Gas budget: 1000 is lower than min: 1000000..
```
Run `ExecuteTransactionBlock` with the update. Then the trailing dot will be removed

fix: Remove redundant dot in error message

---

crates/sui-indexer/README.md

Explain what needs to be installed to get the MySQL version of the Indexer working.
Try the steps and make sure they work.

[Indexer/TiDB][EASY] Add pre-requisites to README.

---

crates/sui-indexer/README.md
crates/sui-indexer/migrations/mysql/2024-03-22-052019_events/up.sql
crates/sui-indexer/migrations/mysql/2024-03-25-203621_objects/up.sql
crates/sui-indexer/migrations/mysql/2024-03-26-004025_transactions/up.sql
crates/sui-indexer/migrations/mysql/2024-04-24-180008_checkpoints/up.sql
crates/sui-indexer/migrations/mysql/2024-04-24-180207_epochs/up.sql
crates/sui-indexer/migrations/mysql/2024-04-24-180418_tx_indices/up.sql
crates/sui-indexer/migrations/mysql/2024-04-24-180727_display/up.sql

Fix up the formatting of MySQL schema files, to make them easier to port to from Postgres:
- Indent table column descriptors to 4 spaces.
- Make all types uppercase.
- Align column constraints.
```
sui-indexer$ diesel database reset --database-url="$DB" --migration-dir="migrations/mysql"
```
- #17686

[Indexer/TiDB][chore] Fix schema indentation and capitalization

---

crates/sui-indexer/migrations/mysql/2024-03-22-052019_events/up.sql
crates/sui-indexer/migrations/mysql/2024-03-25-203621_objects/up.sql
crates/sui-indexer/migrations/mysql/2024-03-26-004025_transactions/up.sql
crates/sui-indexer/migrations/mysql/2024-04-24-180008_checkpoints/up.sql
crates/sui-indexer/migrations/mysql/2024-04-24-180418_tx_indices/up.sql
crates/sui-indexer/migrations/mysql/2024-04-24-180727_display/up.sql

Pick standard prefix lengths for well-known types that make good use of details we know about their structure:
- Object IDs, addresses and digests are all 32 byte quantities.
- Move Identifiers cannot be larger than 128 bytes.
- Fully-qualified types are unlikely to be more than 256 bytes (this is the only case where we have to approximate).
```
sui-indexer$ diesel database reset --database-url=$DB --migration-dir='migrations/mysql'
sui-indexer$ cargo run                           \
--no-default-features --features mysql-feature \
-- --db-url $DB --reset-db                     \
--fullnode-sync-worker                         \
--rpc-client-url "$MAINNET"
```
Ensure data being filled from mainnet by the indexer is well-formed.
- #17686 
- #17687

[Indexer/TiDB] Standardize prefix lengths for blob indices

---

crates/sui-indexer/migrations/mysql/2024-05-05-155158_obj_indices/down.sql
crates/sui-indexer/migrations/mysql/2024-05-05-155158_obj_indices/up.sql
crates/sui-indexer/migrations/pg/2024-05-05-155158_obj_indices/down.sql
crates/sui-indexer/migrations/pg/2024-05-05-155158_obj_indices/up.sql
crates/sui-indexer/src/models/mod.rs
crates/sui-indexer/src/models/obj_indices.rs
crates/sui-indexer/src/schema/mod.rs
crates/sui-indexer/src/schema/mysql.rs
crates/sui-indexer/src/schema/pg.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

This table maps an object's ID and version to a checkpoint sequence number, in a table partitioned by the first byte of the object ID. This speeds up look ups into `objects_history` by offering a path for a first look-up to the correct partition in that table for a given object's ID and version.
This PR introduces the table, and the logic to populate it in the indexer.
```
sui$ cargo nextest run -p sui-indexer
```
A future PR will make use of this table from GraphQL, which will test it further.
- #17686 
- #17687 
- #17688 
- #17689 
- #17691
- #17694 
- #17695 
--- …

[Indexer] Create `objects_version` table.

---

crates/sui-indexer/migrations/mysql/2024-04-24-180249_packages/up.sql
crates/sui-indexer/migrations/mysql/2024-05-05-155158_obj_indices/down.sql
crates/sui-indexer/migrations/mysql/2024-05-05-155158_obj_indices/up.sql
crates/sui-indexer/migrations/pg/2023-08-19-060729_packages/up.sql
crates/sui-indexer/migrations/pg/2024-05-05-155158_obj_indices/down.sql
crates/sui-indexer/migrations/pg/2024-05-05-155158_obj_indices/up.sql
crates/sui-indexer/src/models/mod.rs
crates/sui-indexer/src/models/obj_indices.rs
crates/sui-indexer/src/models/packages.rs
crates/sui-indexer/src/schema/mod.rs
crates/sui-indexer/src/schema/mysql.rs
crates/sui-indexer/src/schema/pg.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

Recreating #17690 which was accidentally closed.
Adding data to the `packages` table, to support the following GraphQL queries:
```graphql
type Query {
packages(
afterCheckpoint: Int,
beforeCheckpoint: Int,
first: Int,
after: String,
last: Int,
before: String,
): MovePackageConnection
packageVersions(
address: SuiAddress!,
afterVersion: Int,
beforeVersion: Int,
first: Int,
after: String,
last: Int,
before: String,
): MovePackageConnection
package(address: SuiAddress!, version: Int): MovePackage
}
type MovePackage {
atVersion(version: Int): MovePackage
versions(
afterVersion: Int,
beforeVersion: Int,
first: Int,
after: String,
last: Int,
before: String,
): MovePackageConnection
}
```
These queries are important for writing tools that perform whole-chain package analyses, and also for the …

[Indexer] Index Package original ID, version, cp sequence number

---

external-crates/move/crates/move-analyzer/editors/code/package.json

A version of extension in`package.json` needs to be bumped in order to publish it (even if the only change is in the bundled binary).

[move-ide] Bump version number for publishing

---

crates/suins-indexer/.env.sample
crates/suins-indexer/src/indexer.rs
crates/suins-indexer/src/main.rs
crates/suins-indexer/tests/checkpoint_process_tests.rs

- Adds the mainnet values
- Makes the `is_name_record` check stricter, by also checking the type (to avoid the possibility of breaking with TTO to the registry's table).
Changed the type to the new expected, and re-run the tests.
---

[SuiNS Indexer] Mainnet values & stricter check

---

consensus/config/src/parameters.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs

bridge e2e tests can't use sim tests today because of several reasons. With `tokio::test` we stumble into a case where high commit rate (50ms) can cause reconfiguration to take long and eventually build up the checkpoint queue (interesting it is the checkpoint content downloading queue). This PR introduces an env var to keep the commit rate normal.
---

use env var to set consensus min delay in tests

---

crates/sui/src/client_commands.rs

Fixes the issue with providing a path to a Move project with `sui client publish <path>`, and failing to find the directory.
Existing tests. Manual checks
```bash
~/src/sui/examples > sui client publish move/first_package 
~/src/sui/examples/move > sui client publish first_package 
~/src/sui/examples/move/first_package > sui client publish . 
```
---

[cli] Fix cli client publish path

---

crates/bin-version/src/lib.rs

https://github.com/MystenLabs/sui/pull/17478 breaks our homebrew releases (https://github.com/Homebrew/homebrew-core/pull/171726#issuecomment-2111545964), as it reversed the changes made in https://github.com/MystenLabs/sui/pull/15727. 
```
$ mv .git .notgit
$ cargo install --path crates/sui
$ /Users/johnmartin/.cargo/bin/sui -V                                                                                                                                                           sui 1.26.0
```

[fix][homebrew] don't panic if git commit unavailable

---

crates/sui-transactional-test-runner/src/test_adapter.rs
external-crates/move/Cargo.lock
external-crates/move/crates/move-analyzer/Cargo.toml
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-compiler/src/command_line/compiler.rs
external-crates/move/crates/move-transactional-test-runner/src/vm_test_harness.rs

This PR fixes a problem related to construction of pre-compiled libraries in the IDE. In particular:
- we need to use virtual file system while constructing pre-compiled libraries to make sure that file hashes remain consistent throughout the symbolication process
- we need to invalidate pre-compiled library for a package if dependency source files changed since last symbolication
Verified that a crash previously happening when trying the following test procedure can no longer happen:
- Add a method in module M, save the file
- Use the method in module X, save the file
- Remove the method in module M DO NOT save the file
- Reload vscode using "Developer: Reload Window"

[move-ide] Fix pre-compiled libs construction problems

---

external-crates/move/crates/module-generation/src/generator.rs
external-crates/move/crates/move-cli/src/sandbox/commands/publish.rs
external-crates/move/crates/move-cli/src/sandbox/utils/package_context.rs
external-crates/move/crates/move-compiler/src/bin/move-build.rs
external-crates/move/crates/move-compiler/src/command_line/compiler.rs
external-crates/move/crates/move-compiler/src/compiled_unit.rs
external-crates/move/crates/move-compiler/src/to_bytecode/translate.rs
external-crates/move/crates/move-ir-to-bytecode-syntax/src/syntax.rs
external-crates/move/crates/move-ir-to-bytecode/src/compiler.rs
external-crates/move/crates/move-ir-types/src/ast.rs
external-crates/move/crates/move-package/src/compilation/compiled_package.rs

The logic around overriding the binary version output by the compiler was spread out over a number of places, and in general was a bit nasty. This simplifies the logic so the version setting happens in only one place in the code base. 

[move] Simplify binary version override logic

---

crates/sui-core/src/traffic_controller/policies.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-types/src/traffic_control.rs

We curently only handle connection IP traffic for traffic sketch based policy. This is fine for rpc nodes, which should never receive proxy IP in tally (as it is only connecting to client directly).
This PR adds support for proxy IP in this policy. To achieve this, we need to distinguish the IP types in the count min sketch key whose frequency is estimated. We also need a separate threshold config, as generally it makes little sense to use the same threshold given that RPC nodes route traffic from many clients, thus they will naturally have a much higher tally frequency compared to client IP frequency.
Updated tests
--- …

[Traffic Control] Distinguish IP source in traffic sketch

---

consensus/core/src/authority_node.rs
consensus/core/src/core.rs
consensus/core/src/transaction.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/checkpoints/checkpoint_output.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/consensus_manager/mod.rs
crates/sui-core/src/epoch/randomness.rs
crates/sui-core/src/mysticeti_adapter.rs
crates/sui-core/src/unit_tests/consensus_tests.rs
crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
crates/sui-single-node-benchmark/src/mock_consensus.rs
crates/sui-types/src/error.rs
narwhal/executor/tests/consensus_integration_tests.rs
narwhal/node/src/benchmark_client.rs
narwhal/primary/tests/causal_completion_tests.rs
narwhal/primary/tests/nodes_bootstrapping_tests.rs
narwhal/types/proto/narwhal.proto
narwhal/types/src/proto.rs
narwhal/worker/src/batch_maker.rs
narwhal/worker/src/client.rs
narwhal/worker/src/tests/batch_maker_tests.rs
narwhal/worker/src/tests/worker_tests.rs
narwhal/worker/src/transactions_server.rs

Please refer to this SIP draft: 
https://github.com/sui-foundation/sips/pull/19
The PR focuses only on consensus related changes, covering both Narwhal and Mysticeti.
We will proceed to work on the remaining parts once this gets merged.
The PR includes a commit from @mwtian that changes `TransactionConsumer` for ack handling in a bundle context.
Special thanks to @mwtian for taking time to discussions and authoring the change above!
The feature is not exactly user-facing and do not break anything.

Consensus changes for SIP-19

---

crates/bin-version/src/lib.rs

Reverts MystenLabs/sui#17760 using https://github.com/Homebrew/homebrew-core/pull/171838 instead

Revert "[fix][homebrew] don't panic if git commit unavailable"

---

crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/objects_snapshot_processor.rs

objects snapshot backfill mode was introduced to speed backfill speed, following the idea that populating `objects` and `objects_snapshot` while backfilling is faster than running the periodical updating query.
however one assumption of doing this is that, `objects` and `objects_snapshot` should always be in sync. this is is not true when `objects_snapshot` was behind already.
the consequence is that, the objects_snspshot backfill mode ingestion will skip data in the middle and only populate the latest object info.
this pr is to fix that by limit backfill mode to be triggered only when `objects_snapshot` table is in sync.
1. local run DB to backfill
2. delete some recent rows from `objects_snapshot` to make it behind
3. restart the indexer writer to make sure that it will not trigger the …

indexer fix: only start objects snapshot backfill mode when synced

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-compiler/src/unit_test/filter_test_members.rs
external-crates/move/crates/move-symbol-pool/src/lib.rs

This PR prevents on-hover info from being displayed by the IDE for a dummy function that does not exist in source as it's auto-inserted by the compiler. This is what was happening before:
Verified that on-hover info is no longer displayed

[move-ide] Dummy function no longer shows on-display info

---

crates/sui-config/src/node.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-indexer/src/lib.rs
crates/sui-json-rpc-tests/tests/routing_tests.rs
crates/sui-json-rpc/src/axum_router.rs
crates/sui-json-rpc/src/lib.rs
crates/sui-node/src/lib.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm/src/memory/swarm.rs
crates/test-cluster/src/lib.rs

This will disable the client IP injection path altogether. Adds builder params in order to keep enabled in tests. 
Existing tests

[Traffic Control] Disable ip injection by default

---

crates/sui/src/client_commands.rs
crates/sui/src/client_ptb/ptb.rs
crates/sui/tests/cli_tests.rs

PR #17431 introduced the `dry_run_or_execute_or_serialize` function and messed up the output for the `sui client ptb` when the `serialize-` flags were used. This fixes it and adds a test.
Added a new test.
---

[cli] Fix error when `--serialize` flags are used with PTBs

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/extensions/timeout.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Increases the timeout for mutation requests.
Updated existing tests to also include this `mutation` timeout case.
```
cargo nextest run --features pg_integration -- tests::test_timeout                 
```
---

[GraphQL] Add a separate timeout field in ServiceConfig for mutations

---

crates/sui-tool/src/commands.rs

@tharbert and @chris-gorham pointed out that the use of the archival bucket is pretty confusing in formal snapshots. This PR attempts to make usage easier by defaulting to the web/zero auth endpoint unless explicitly setting `CUSTOM_ARCHIVE_BUCKET=true`
Testing on a testnet host with the formal snapshot restore ansible task

default archive bucket to use no-sign-request

---

crates/sui-indexer/src/framework/fetcher.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs

I found that the download lag metric was always 0 https://metrics.sui.io/goto/KFEC2VPIg?orgId=1
it turns out that after data ingestion framework migration, the download is no longer in the fetcher.rs, thus we will need to update this metric
local run and verify in logs
```
sui_indexer::handlers::checkpoint_handler: checkpoint download lag: 242224874
```
---

indexer: update cp download lag metric for data ingestion framework

---

Cargo.lock
crates/sui-bridge/Cargo.toml
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/tools/mod.rs
crates/sui-bridge/src/utils.rs
crates/sui-keys/src/keypair_file.rs
crates/sui/src/sui_commands.rs
crates/sui/src/validator_commands.rs

We have been using `read_bridge_client_key` and `read_bridge_authority_key` to read keys for different purposes which is confusing to say the least. This PR consolidates them to `read_key`
exiting unit tests
---

[Bridge] consolidate key reading functions to `read_key`

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/extensions/timeout.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Increases the timeout for mutation requests.
Updated existing tests to also include this `mutation` timeout case.
```
cargo nextest run --features pg_integration -- tests::test_timeout                 
```
---

[cherry-pick][graphql] Cherry pick mutation timeout to 2024.1

---

crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui/src/sui_commands.rs
crates/sui/src/validator_commands.rs
crates/test-cluster/src/lib.rs

When validators register their info, most likely they don't have BridgeNodeConfig yet. In this PR we provide the authority key path directly to avoid depending on the config.
---

[bridge] provide raw metadata for BridgeCommitteeRegistration commands

---

crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-e2e-tests/tests/call/simple.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/schema/draft_target_schema.graphql
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Adds available versions query to the service config. Uses the crate's version if no `versions` section exists in the `config.toml` file.
Existing tests. Manual query on local instance. 
```graphql
{
serviceConfig {
availableVersions
}
}
```
```json
{
"data": {
"serviceConfig": {
"availableVersions": [
"2024.7"
]
}
}
}
```
```toml
[limits]
max-query-depth = 15
max-query-nodes = 500
max-output-nodes = 100000
max-query-payload-size = 5000
max-db-query-cost = 20000
default-page-size = 5
max-page-size = 10
request-timeout-ms = 15000
max-type-argument-depth = 16
max-type-argument-width = 32
max-type-nodes = 256
max-move-value-depth = 128
[versions]
versions = ["2024.1", "2024.4", "2024.7"]
```
Same query
```json
{
"data": {
"serviceConfig": {
"availableVersions": [
"2024.1",
"2024.4",
"2024.7" …
```

[cherry-pick][graphql] Cherry pick available versions PR to 2024.1

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/extensions/timeout.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Increases the timeout for mutation requests.
Updated existing tests to also include this `mutation` timeout case.
```
cargo nextest run --features pg_integration -- tests::test_timeout                 
```
---

[cherry-pick][graphql] Cherry pick mutation timeout to 2024.4

---

.changeset/green-penguins-attack.md
sdk/dapp-kit/src/components/styling/InjectedThemeStyles.tsx
sdk/deepbook/package.json

If you render a `style` tag outside of the `body` element in canary versions of React, you get a breaking error informing you to specify a precedence/href prop. This PR adds those props which should fix https://github.com/MystenLabs/sui/issues/17794
- Tested manually with a Next 14.2.3 app
- https://sui-typescript-docs-git-wrobertson-dappkitstylefix-mysten-labs.vercel.app/dapp-kit/wallet-components/ConnectButton still works
---

[dapp-kit] fix edge case where the theme style element breaks when used in Next apps

---

Cargo.lock
crates/suins-indexer/Cargo.toml
crates/suins-indexer/src/main.rs

Attempt to fix metrics for suins-indexer by initializing a real registry.
builds successfully:
```
> c b
...
warning: `sui-core` (lib) generated 2 warnings
Compiling suins-indexer v0.1.0 (/Users/jkjensen/mysten/sui/crates/suins-indexer)
Finished dev [unoptimized + debuginfo] target(s) in 2.80s
```
I will deploy testnet after landing this change to validate e2e correctness.
```
> c t
running 5 tests
test process_22279944_checkpoint ... ok
test process_22279365_checkpoint ... ok
test process_22279496_checkpoint ... ok
test process_22280030_checkpoint ... ok
test process_22279187_checkpoint ... ok
test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
Doc-tests suins-indexer
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 …
```

[suins-indexer] fix metrics

---

Cargo.lock
Cargo.toml
crates/sui-bridge-cli/Cargo.toml
crates/sui-bridge-cli/src/lib.rs
crates/sui-bridge-cli/src/main.rs
crates/sui-bridge/Cargo.toml
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/lib.rs

Previously this binary is located in `sui-bridge`, which makes it impossible to install using `cargo install --git`. This PR moves it to its own crate.
tested locally
---

[bridge] extract sui-bridge-cli into its own crate

---

crates/sui/src/validator_commands.rs

This PR allows committee registration command to print unsigned transaction bytes for offline signing. This is important to validators who keep their account keys in cold storage. 
Also rename `BridgeCommitteeRegistration` to `RegisterBridgeCommittee` to keep command names consistent
tested locally.
---

[bridge] allow offline signing for committee registration

---

package.json

Vercel added something to their builds that detects pnpm 9 lockfiles, and then forces pnpm 9.0.4 to be used.  This detection takes priority over the corepack/the packageManager field
---

Downgrade engine requirement to fix vercel issue

---

crates/sui-data-ingestion/src/bin/archival_ingestion.rs
crates/sui-data-ingestion/src/workers/archival.rs

PR creates an extra binary for the archival workflow. It can be used by partners that want to maintain a Sui archive. The new binary doesn't have a DynamoDB dependency for managing the progress state and uses MANIFEST directly instead

[archival] separate binary

---

Cargo.lock
external-crates/move/Cargo.lock
external-crates/move/crates/move-cli/src/sandbox/commands/test.rs
external-crates/move/crates/move-cli/src/sandbox/utils/on_disk_state_view.rs
external-crates/move/crates/move-model/Cargo.toml
external-crates/move/crates/move-stackless-bytecode-interpreter/src/lib.rs
external-crates/move/crates/move-stackless-bytecode/Cargo.toml
external-crates/move/crates/move-stdlib/Cargo.toml
external-crates/move/crates/move-vm-runtime/Cargo.toml
external-crates/move/move-execution/v0/crates/move-stdlib-natives/Cargo.toml
external-crates/move/move-execution/v0/crates/move-vm-runtime/Cargo.toml
external-crates/move/move-execution/v1/crates/move-stdlib-natives/Cargo.toml
external-crates/move/move-execution/v1/crates/move-vm-runtime/Cargo.toml
external-crates/move/move-execution/v2/crates/move-abstract-interpreter/Cargo.toml
external-crates/move/move-execution/v2/crates/move-stdlib-natives/Cargo.toml
external-crates/move/move-execution/v2/crates/move-vm-runtime/Cargo.toml

Ran `cargo udeps` to find unused Cargo dependencies and removed them, and then also found some unused private types, and removed those as well. 
CI

[cleanup][move] Remove unused cargo deps + minor removal of some more unused things

---

crates/sui-bridge/src/events.rs

This PR
1. adds the remaining events emitted on Sui in Rust
2. extracts common logic with macro `new_move_event`
some events are tested in `test_bridge_events_conversion`. There is a TODO to add tests for other events. It's easier to test them in e2e tests where more actions happen.
---

[bridge] add remaining sui events in bridge node

---

crates/sui-bridge/Cargo.toml
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/utils.rs
crates/test-cluster/src/lib.rs

Some refactoring to make tests slightly faster:
1. consolidate `fn publish_coins_return_add_coins_on_sui_action` and `fn wait_for_server_to_be_up` in `crates/sui-bridge/src/e2e_tests/test_utils.rs` and `crates/sui-bridge/src/utils.rs`
2. refactor `publish_coins_return_add_coins_on_sui_action` to `publish_and_register_coins_return_add_coins_on_sui_action` which does token publish and token register.
---

[bridge] some refactoring for e2e tests

---

crates/sui-core/src/authority/authority_store_pruner.rs

ensures that pruner periodically yields back to the tokio runtime and doesn't cause a potential halt of other tasks

[pruner] yield on pruning iteration in prune_for_eligible_epochs

---

crates/sui-indexer/src/store/pg_indexer_store.rs

This is to fix slow `objects_snapshot` update via query.
in the past, we used to have fewer object mutations and with recent increase on object mutations, the objects_snapshot table starts to fall behind on mainnet.
perf comparison with and without a larger mem on a separate cloned DB
```
Insert on objects_snapshot  (cost=1787923.79..1810332.86 rows=0 width=0) (actual time=1007038.109..1007038.110 rows=0 loops=1)
Conflict Resolution: UPDATE
Conflict Arbiter Indexes: objects_snapshot_pkey
Tuples Inserted: 0
Conflicting Tuples: 341814
->  Subquery Scan on subquery  (cost=1787923.79..1810332.86 rows=3448 width=797) (actual time=15796.923..20093.768 rows=341814 loops=1)
Filter: (subquery.rn = 1)
->  WindowAgg  (cost=1787923.79..1801713.99 rows=689510 width=805) (actual …
```

indexer: configure PG work mem for perf

---

crates/sui-core/src/authority/authority_store_pruner.rs

Improves smoothing effect by at least 2X.
Currently, the smoother roughly processes `(last_executed_checkpoint - last_pruned_checkpoint) / number_of_tick_intervals_in_epoch` per interval tick. 
This method is not ideal because `last_executed_checkpoint != max_eligible_checkpoint_for_pruning`.
For instance, for effects and transactions num_epochs_to_retain is >= 2. 
Thus we can achieve even smoother traffic.
This PR addresses the issue by utilizing the `epoch_last_checkpoint_map` table

[pruner] improve smoothing over the epoch

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/lib/autocomplete/mod.rs
crates/suiop-cli/src/cli/lib/mod.rs
crates/suiop-cli/src/cli/pulumi/init.rs

Make it easier to identify paths by adding autocomplete.
```
> suiop p i
2024-05-21T22:23:18.536725Z  INFO suioplib::cli::pulumi::init: raw path: git@github.com:MystenLabs/sui-operations.git
2024-05-21T22:23:18.622178Z  INFO suioplib::cli::pulumi::init: suipop path: /Users/jkjensen/mysten/sui-operations
> project name: yeet
? project subdir (under sui-operations/pulumi/): /Users/jkjensen/mysten/sui-operations/pulumi/ 
/Users/jkjensen/mysten/sui-operations/pulumi/meta/
/Users/jkjensen/mysten/sui-operations/pulumi/gcp/
/Users/jkjensen/mysten/sui-operations/pulumi/components/
/Users/jkjensen/mysten/sui-operations/pulumi/common/
/Users/jkjensen/mysten/sui-operations/pulumi/.dockerignore
/Users/jkjensen/mysten/sui-operations/pulumi/examples/
v …
```

[suiop] add autocomplete for basic pulumi projects

---

crates/sui-network/src/randomness/metrics.rs
crates/sui-network/src/randomness/mod.rs

To aid in debugging, and enable tests that match on log messages.

Add randomness generation backlog warning message

---

crates/sui-core/src/authority/authority_store_pruner.rs

Monitored the outer functions to help us understand the utilization of pruning loops.
CI
---

[Pruner] add more monitored scopes

---

crates/sui-framework/docs/sui-framework/vec_map.md
crates/sui-framework/docs/sui-framework/vec_set.md
crates/sui-framework/packages/sui-framework/sources/vec_map.move
crates/sui-framework/packages/sui-framework/sources/vec_set.move
crates/sui-framework/packages/sui-framework/tests/vec_map_tests.move
crates/sui-framework/packages/sui-framework/tests/vec_set_tests.move
crates/sui-framework/published_api.txt
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

- There was no easy way to make a VecMap or VecSet from a PTB 
- New functions and tests
---

[move][stdlib] Add vec_map::from_key_values and vec_set::from_keys

---

Cargo.lock
crates/x/Cargo.toml
crates/x/src/lint.rs

convert the existing compound if block into a func that does the same thing and allow for more funcs that also do similar work.  If the ignore_funcs return true, any of them, they will not count as a lint error
cargo build
---

[x/extend ignore] extend the path ignore functionality

---

consensus/core/src/network/mod.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_47.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_47.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_47.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Enable tonic networking for Mysticeti.
CI
Private testnet: tonic has been the default for awhile.
---

[Consensus] enable tonic

---

crates/sui-sdk/README.md

fix rust sdk docs error
fix rust sdk docs error
Fix the code and run build
---

fix rust sdk docs error

---

crates/sui-adapter-transactional-tests/tests/upgrade/abort_code_resolution.exp
crates/sui-adapter-transactional-tests/tests/upgrade/abort_code_resolution.move
crates/sui-adapter-transactional-tests/tests/upgrade/abort_code_resolution_v46.exp
crates/sui-adapter-transactional-tests/tests/upgrade/abort_code_resolution_v46.move
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_47.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_47.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_47.snap
sui-execution/latest/sui-adapter/src/error.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs

Updates Move aborts so that the address in the abort location uses the package ID as opposed to the runtime module ID. 
Basically, before if you had a package `P` with a module `M` 
```move
module P::M {
public fun aborter() { abort 0 }
}
```
published at `0xA` for version 1, `0xB` for version 2, and `0xC` for version 3, then before this change
```
0xA::aborter().location.address == 0xA
0xB::aborter().location.address == 0xA
0xC::aborter().location.address = 0xA
```
After this change
```
0xA::aborter().location.address == 0xA
0xB::aborter().location.address == 0xB
0xC::aborter().location.address == 0xC
```
The only meaningful changes are in `sui-execution/latest/sui-adapter/src/error.rs` the other changes are just plumbing/protocol config updates and tests.
Added tests to make sure …

[sui-adapter] Resolve Move abort locations to package ID instead of runtime ID

---

crates/sui-bridge-cli/src/lib.rs
crates/sui-bridge-cli/src/main.rs
crates/sui-bridge/src/utils.rs

Add examine-key command to read key file and print related info (pubkey, addresses etc).
tried locally:
```
sui-bridge-cli create-bridge-client-key bar
sui-bridge-cli examine-key bar
```
---

[bridge] add examine-key command for sui-bridge-cli

---

crates/sui-indexer/src/metrics.rs

see title, prev some slow queries were not captured well by the existing buckets b/c the numbers are out of scale.
I found this from `objects_snapshot` and then found out that the epoch advance is the other one.
eyeballs and CI in case of unexpected failures
---

indexer: fix buckets of long latency metrics

---

external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/symbols.rs

Doc strings are now extracted only once when processing definitions rather than each time they were needed
All existing tests must pass

[move-ide] Optimized doc string extraction

---

consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/leader_scoring_strategy.rs
consensus/core/src/lib.rs
consensus/core/src/linearizer.rs
consensus/core/src/test_dag_builder.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_types/consensus_output_api.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs

Currently the default digest is being used on the mysticeti committed subdag making the fork detection in checkpoints weaker as included in the `ConsensusCommitInfo`. This PR is calculating the committed sub dag digest and enabling it behind a feature flag. It has to be noted that the reputation scores are not included in the sub dag digest as during crash recovery we don't restore the actual scores for every committed sub dag, but only restoring the last ones and sent as part of the last committed sub dag. 
CI
--- …

[Consensus 2.0] Calculate committed sub dag digest

---

external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/src/inlay_hints.rs
external-crates/move/crates/move-analyzer/src/symbols.rs

Added on-hover when hovering over struct type hints:
Verified that on-hover works for struct type hints

[move-ide] Added on-hover for inlay type hints

---

crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/complex.rs
crates/sui-bridge/src/e2e_tests/mod.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs

... and some refactoring to e2e test utils
e2e tests
---

[native-bridge] - add e2e test to test Sui bridge pause.

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_store_pruner.rs
crates/sui-core/src/db_checkpoint_handler.rs
crates/sui-node/src/lib.rs

Fix no-op pruner setting

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs

Adding a metric to track cancelled txn count.
---

Track cancelled transaction count

---

.github/workflows/build-suiop-cli.yml

Create a workflow dispatch that will cause a github action to trigger on `Mystenlabs/sui-operations` which will generates binary builds for `suiop-cli` on different architectures.
Relative PR to sui operations: https://github.com/MystenLabs/sui-operations/pull/3769
- Create a dummy PR to `Mystenlabs/sui`, that contains a change in the `crates/suiop-cli/` directory or its subdirectories.
- Check if the gh action is triggered in https://github.com/MystenLabs/sui-operations.
---

[suiop] Build suiop-cli binaries workflow dispatch

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-transaction-checks/src/lib.rs
crates/sui-types/src/effects/mod.rs
crates/sui-types/src/message_envelope.rs
crates/sui-types/src/transaction.rs

This PR consolidates protocol version support checks on transactions during validity check.
Specifically, it breaks down the protocol config version checks from authority_server into two pieces:
1. User signature related version checks. These are moved to a single function and called from validity_chec().
2. Transaction data related version checks. This is the randomness check, and is moved to check_version_supported() of TransactionData.
One notable change is that the randomness check now only checks the protocol config feature, without checking whether the randomness object exists. I believe this is fine because if the randomness object does not exist, it will fail latter when loading input objects anyway. But worth double check @aschran 
CI
---
Check each box that your changes affect. …

[core] Cleanup protocol version cheecks in transaction validity check

---

docs/content/standards/wallet-standard.mdx
pnpm-lock.yaml
sdk/dapp-kit/src/constants/walletMutationKeys.ts
sdk/dapp-kit/src/hooks/wallet/useReportTransactionEffects.ts
sdk/dapp-kit/src/hooks/wallet/useSignAndExecuteTransaction.ts
sdk/dapp-kit/src/hooks/wallet/useSignTransaction.ts
sdk/dapp-kit/src/index.ts
sdk/dapp-kit/test/hooks/useSignAndExecuteTransaction.test.tsx
sdk/dapp-kit/test/hooks/useSignTransaction.test.tsx
sdk/docs/package.json
sdk/docs/pages/dapp-kit/wallet-hooks/_meta.json
sdk/docs/pages/dapp-kit/wallet-hooks/useReportTransactionEffects.mdx
sdk/docs/pages/dapp-kit/wallet-hooks/useSignTransaction.mdx
sdk/docs/typedoc.json
sdk/typescript/src/transactions/data/v2.ts
sdk/typescript/src/transactions/executor/parallel.ts
sdk/typescript/src/transactions/executor/serial.ts
sdk/wallet-standard/src/features/suiReportTransactionEffects.ts
sdk/wallet-standard/src/index.ts
sdk/wallet-standard/src/types.ts
sdk/wallet-standard/typedoc.json

Update docs for the wallet-standard

---

Cargo.lock
consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/Cargo.toml
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/metrics.rs
consensus/core/src/network/metrics_layer.rs
consensus/core/src/network/mod.rs
consensus/core/src/network/tonic_network.rs

Reuse the "callback layer" implementations for anemo and tonic.
Add trace layer to tonic.
Request and response size monitoring will be added as a followup.
CI
Private testnet.
---

[Consensus] add tracing and basic metrics to tonic

---

external-crates/move/crates/move-analyzer/src/compiler_info.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/shared/ide.rs
external-crates/move/crates/move-compiler/src/typing/ast.rs
external-crates/move/crates/move-compiler/src/typing/core.rs
external-crates/move/crates/move-compiler/src/typing/dependency_ordering.rs
external-crates/move/crates/move-compiler/src/typing/expand.rs
external-crates/move/crates/move-compiler/src/typing/infinite_instantiations.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/src/typing/visitor.rs
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/dot_incomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/index_autocomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/named_struct_autocomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/positional_struct_autocomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/struct_method_autocomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/struct_scoped_autocomplete.exp
external-crates/move/crates/move-compiler/tests/move_check/ide_mode/dot_incomplete.exp
external-crates/move/crates/move-compiler/tests/move_check/ide_mode/struct_method_autocomplete.exp

This adds autocomplete information collection to the `IDEInfo` form.
Testing is difficult without the analyzer calling it with a location, but I anticipate working with Adam on that over the next few days.
---

[move][move-id] Move IDE autocomplete information to IDEInfo form

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-compiler/src/cfgir/ast.rs
external-crates/move/crates/move-compiler/src/cfgir/locals/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/mod.rs
external-crates/move/crates/move-compiler/src/cfgir/translate.rs
external-crates/move/crates/move-compiler/src/cfgir/visitor.rs
external-crates/move/crates/move-compiler/src/command_line/compiler.rs
external-crates/move/crates/move-compiler/src/hlir/ast.rs
external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/linters/constant_naming.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-compiler/src/shared/program_info.rs
external-crates/move/crates/move-compiler/src/shared/string_utils.rs
external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/coin_field.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/collection_equality.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/custom_state_change.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/freeze_wrapped.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/public_random.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/self_transfer.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/share_owned.rs
external-crates/move/crates/move-compiler/src/sui_mode/typing.rs
external-crates/move/crates/move-compiler/src/to_bytecode/translate.rs
external-crates/move/crates/move-compiler/src/typing/ast.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/src/typing/visitor.rs
external-crates/move/crates/move-model/src/lib.rs

- Some lints probably want to use the CFGIR, since they are easier to do post optimizations 
- Cleaned up the linter APIs
- internal change 
---

[move] Add CFGIR Ast Visitor. Clean up rough edges of T::Program.

---

crates/sui-bridge-cli/src/lib.rs
crates/sui-bridge-cli/src/main.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/utils.rs

A subcommand to print eth contract addresses in sui-bridge-cli. We may end up expanding this subcommand to display onchain config but let's start with this for now.
```
sui-bridge-cli print-eth-bridge-addresses --bridge-proxy 0x80a22938b7b19a9c6da7c7dd3ba674b912198018 --eth-rpc-url https://ethereum-sepolia-rpc.publicnode.com
```
---

Add print eth address in cli

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-rpc/Cargo.toml

After the `v2024.1.5` release, this PR bumps up the version for the legacy service. 
---

[GraphQL] Bump graphql legacy version to 2024.1.6

---

external-crates/move/crates/move-compiler/src/expansion/alias_map_builder.rs
external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-compiler/tests/move_2024/expansion/constants_dont_shadow_leading_access_struct.exp
external-crates/move/crates/move-compiler/tests/move_2024/expansion/use_nested_self_as_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/matching/invalid_head_ctor_3.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/clever_errors_line_assert.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/positional_struct_non_positional_unpack.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/positional_unpack_of_non_positional_struct.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/struct_ellipsis_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/invalid_positional_struct_unpack_deeply_nested.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/long_path.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/positional_struct_explicit_type_arg_assign.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/positional_struct_explicit_type_args.exp
external-crates/move/crates/move-compiler/tests/move_check/deprecated/assert_function.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/invalid_unpack_assign_lhs_other_value.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/invalid_unpack_assign_mdot_no_struct.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/pack_no_fields_single_block_other_expr.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/unpack_assign_other_expr.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/weird_apply_assign.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/unbound_constant.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/unbound_module_name.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/unbound_struct_in_current.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/unbound_struct_in_module.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/invalid_unpack_assign_rhs_not_fields.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/positional_struct_unpack.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/module_call_missing_function.exp

This cleans up and combines a lot of the code in naming into a more-uniform interface. This work is in service of hopefully one day combining path expansion and name resolution into a single operation.
A few of the tests were updated with expected output. Bikeshedding is quite welcome on those, but overall things are more-uniform with more normalized structure now.
---

[move][naming][0/k] Clean up naming infrastructure

---

crates/sui-bridge-cli/src/lib.rs
crates/sui-bridge-cli/src/main.rs

Add a subcommand to display current registration info.
```
sui-bridge-cli print-sui-bridge-info --sui-rpc-url https://rpc.testnet.sui.io:443
```
---

[bridge] Add print registration info in cli

---

crates/sui-bridge-cli/src/lib.rs
crates/sui-bridge-cli/src/main.rs

1. adds subcommand `PrintBridgeCommitteeInfo` 
2. adds subcommands `AddTokensOnSui` and `AddTokensOnEvm` for governance
tested all three locally.
---

[bridge] add PrintBridgeCommitteeInfo subcommand and more governance command

---

external-crates/move/crates/move-compiler/src/parser/lexer.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/tests/move_check/parser/doc_comments_annotations.move
external-crates/move/crates/move-compiler/tests/move_check/parser/doc_comments_annotations_invalid.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/doc_comments_annotations_invalid.move
external-crates/move/crates/move-compiler/tests/move_check/parser/doc_comments_placement.move
external-crates/move/crates/move-docgen/tests/sources/annotation_test.move
external-crates/move/crates/move-docgen/tests/sources/annotation_test.spec_inline.md
external-crates/move/crates/move-docgen/tests/sources/annotation_test.spec_inline_no_fold.md
external-crates/move/crates/move-docgen/tests/sources/annotation_test.spec_separate.md

Adds support for parsing doc comments with attributes either before, after, or in the middle of the doc comments.
Before, the following were all errors
```move
/// Doc comment
#[annotation]
fun foo() { }
/// Doc comment
#[annotation]
/// Other doc comment
fun foo() { }
/// Doc comment
#[annotation]
/// Other doc comment
#[annotation]
fun foo() { }
```
These are now all supported, and the previous behavior of 
```move
#[annotation]
/// Doc comments
fun foo() { }
```
is also maintained.
Added additional tests for both the parser, and docgen to make sure we attach doc comments correctly.

[move] Support parsing doc comments before/after/in-between attributes

---

crates/sui-move/src/build.rs
crates/sui-move/src/manage_package.rs
crates/sui-source-validation-service/src/lib.rs
crates/sui/src/client_commands.rs

Rust doesn't like importing from modules called `build` (I think due to `build.rs`). This moves the offending function to `manage_package`.
CI + ran repro locally.

[sui-move] Unbreak build

---

crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/metrics.rs
crates/sui-core/src/overload_monitor.rs

1. Do not report latency from sampler until enough samples are taken. This avoids issues with wildly off latency estimates at the start of an epoch.
2. Reduce max submission delay step to 10s, which is still significantly larger than consensus latency.
3. Do not report latency from system transactions that do no require quorum to have formed. These transactions can distort the latency estimate, their submission attempts start before a consensus quorum has formed.
4. Increase expected latency samples to 128.
CI
--- …

Improve sampling of consensus submission latency

---

.github/workflows/narwhal.yml
.github/workflows/rust.yml

Sometimes failed integration tests can produce too much logs and overwhelm the browser even when reading raw logs.
CI
---

[CI] reduce log verbosity in tests

---

crates/sui-move/src/disassemble.rs
external-crates/move/crates/move-bytecode-viewer/src/bytecode_viewer.rs

Fixes the interactive disassembler, and adds the flag for it to `sui move disassemble` (with the `-i` flag). See screencast for what this looks like.
https://github.com/MystenLabs/sui/assets/2895723/50a75eb1-3d84-4c00-a30b-ab051c2ca169
👀 
---

[move] Fix and add interactive disassembler

---

Cargo.lock
crates/sui/Cargo.toml
crates/sui/src/sui_commands.rs

The `move-analyzer` binary was recently moved to `crates` to support its versioning according to the same scheme as the `sui` binary. The goal is to distribute `move-analyzer` in two ways:
- embed it with VSCode extension for those that just want to use the IDE and don't want or (yet) need Sui CLI
- via Sui CLI (so that each time CLI is updated, `move-analyzer` binary is updated as well)
Out of these two options, the newer one (according to the version number) will be chosen to be used by the VSCode extension.
This PR embeds `move-analyzer` within Sui CLI so that it can be distributed via brew and chocolatey. The difference in binary size is rather small 110MB vs 108MB on a Mac

[move-ide] Embed move-analyzer within Sui CLI

---

crates/sui-core/src/generate_format.rs
crates/sui-types/src/move_package.rs

Adds an alias for the old name of the field in the type origin table to preserve backwards compatibility with a rename for enums.
Verified transaction replay worked (was previously failing off of `main`).

[sui-types] Add Serde alias in type origin table to preserve backwards compatibility

---

crates/sui-core/src/transaction_manager.rs

I think this bug would almost certainly never happen (transactions shouldn't be reinserted after being executed), but better safe than sorry.

Fix possible bug with re-insertion

---

crates/sui-graphql-e2e-tests/tests/validator/validator.exp
crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-indexer/src/apis/governance_api.rs
sdk/graphql-transport/test/compatability.test.ts

Move exchange_rates to be a free function, and remove unneeded APIs. GraphQL APY code is reworked in #17701. 
This PR needs to be merged first, before #17701. Note that the diff messes things up. The code was not changed, except for `self -> state`.
---

[indexer] Move `exchange_rates` to be a free function

---

external-crates/move/crates/move-compiler/src/editions/mod.rs
external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/expansion/macro_identifier_missing.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/macro_parameter_assignment.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/macro_var_as_fun_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/macro_var_as_fun_invalid.move
external-crates/move/crates/move-compiler/tests/move_2024/naming/var_as_fun_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/var_as_fun_invalid.move
external-crates/move/crates/move-compiler/tests/move_2024/naming/var_as_fun_macro.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/var_as_fun_macro.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/use_lambda_outside_call_invalid.exp
external-crates/move/crates/move-compiler/tests/move_check/feature_gate/macro_definition_with_usage.exp
external-crates/move/crates/move-compiler/tests/move_check/feature_gate/macro_definition_with_usage.move
external-crates/move/crates/move-compiler/tests/move_check/feature_gate/macro_lambda.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/var_as_fun_invalid.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/var_as_fun_invalid.move
external-crates/move/crates/move-compiler/tests/move_check/parser/spec_parsing_lambda_fail.exp

This fixes a bug in how var calls were being resolved across naming into typing, when the variable was not a valid macro call target. 
This also adds a `lambda` feature gate to make error reporting a bit nicer in these cases.
New tests cover the crash/bug and ensure it doesn't occur now.
---

[move] Fix issue where varcalls could persist into typing without an error.

---

.github/workflows/release.yml

Since GitHub now has its own `macos-arm64` runners, no need to maintain our own.
See https://mysten-labs.slack.com/archives/C03MDPR2012/p1716561199210589 for context.
https://github.com/MystenLabs/sui/actions/runs/9308556385/job/25622204644

Move to GH hosted macOS arm64 runner

---

crates/sui-sdk/examples/function_move_call.rs

I have added an example in the Rust SDK for a Move call function with parameters to call hello wolrd module from a package on testnet on the Sui Blockchain.
Completed
---

[rust-sdk] add function_move_call example

---

consensus/core/src/authority_node.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs
consensus/core/src/transaction.rs
crates/mysten-metrics/src/lib.rs
crates/mysten-metrics/src/metered_channel.rs
crates/mysten-metrics/src/monitored_mpsc.rs
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/eth_syncer.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/sui_syncer.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-core/src/streamer.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs

Majority of the implementation is adapted from the existing metered bounded channel. The main advantage of the new implementation is that it eliminates the need to create separate metrics for each channel.
Channels in `consensus-core` are migrated to the new monitored channel wrappers. This adds monitoring for unbounded channels.
CI
---

[Metrics] add bounded and unbounded mpsc channel wrappers

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-rpc/Cargo.toml

After the `v2024.4.1` release, this PR bumps up the version for the prod service.
---

[GraphQL] Bump graphql prod version to 2024.4.2

---

crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/docs/bridge/treasury.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-framework/packages/bridge/sources/treasury.move
crates/sui-framework/packages/bridge/tests/bridge_setup.move
crates/sui-framework/packages/bridge/tests/bridge_tests.move

Increase test coverage and create a test environment for the bridge that should make it easier to test.
At this point once we have API to sign messages we can reach 100% coverage. All missing tests are related to signature generation, function depending on that, or versioning. API to sign messages and create pub/priv keys are coming that would allow us to create a great testing environment and experience.
Current coverage is as follows
```
+-------------------------+
| Move Coverage Summary   |
+-------------------------+
Module 000000000000000000000000000000000000000000000000000000000000000b::treasury
>>> % Module coverage: 100.00
Module 000000000000000000000000000000000000000000000000000000000000000b::message_types
>>> % Module coverage: 100.00
Module …
```

Bridge test env

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/epoch/randomness.rs

The underlying race issue causing these not to be removed properly will be fixed in a future change.

Prune erroneously lingering pending randomness rounds from `AuthorityPerEpochStore` tables on startup

---

sdk/docs/pages/typescript/executors.mdx

txb is nowhere defined so the correct statements should include tx1 and tx2.
Fixed typos.

Update executors.mdx - replace txb with tx1 & tx2

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_49.snap

Start running Mysticeti with mainnet configuration, only in testnet.
CI
---

Enable Mysticeti in testnet only

---

external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs
external-crates/move/crates/move-analyzer/src/symbols.rs

Very short PR to fix IDE getting stuck due to a forgotten `println` call. Additional assertion removal is temporary until proper enum support lands (soon) but at the moment I am chasing a perf problem which takes priority.

[move-ide] Fix IDE getting stuck

---

crates/sui-framework/packages/sui-framework/sources/crypto/ecdsa_k1.move
crates/sui-framework/packages/sui-framework/tests/crypto/ecdsa_k1_tests.move
sui-execution/latest/sui-move-natives/src/crypto/ecdsa_k1.rs
sui-execution/latest/sui-move-natives/src/lib.rs

Adds test functions to generate keypairs and create ECDSA signatures over Secp256k1
Unit tests
---

Add k1 test functions

---

consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/broadcaster.rs
consensus/core/src/commit.rs
consensus/core/src/commit_observer.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/leader_scoring_strategy.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/network/test_network.rs
consensus/core/src/network/tonic_network.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs
consensus/core/src/subscriber.rs
consensus/core/src/synchronizer.rs

[consensus] Make CommitRange inclusive and use in commit syncer

---

bridge/evm/contracts/SuiBridge.sol
bridge/evm/contracts/utils/BridgeUtils.sol
bridge/evm/test/SuiBridgeTest.t.sol

Currently only the depositERC20 checks that the conversion is greater than 0. Moving the requirement to the conversion function itself to capture both ERC20 and ETH deposits
Added unit test coverage to account for both depositEth and depositERC20

Move deposit amount restriction to utils

---

external-crates/move/crates/move-analyzer/src/symbols.rs

We should not check for if the (remote) dependencies are up-to-date on each compilation as this is quite costly (seconds) and can massively slowdown some features (e.g., auto-completion). For IDE use case it should be sufficient to check dependency freshness on the first compilation only.
Verified that time to finish auto-completion request when remote deps are used went down from ~2s to miliseconds

[move-ide] Optimized dependency graph construction

---

external-crates/move/crates/move-analyzer/editors/code/.eslintrc.json
external-crates/move/crates/move-analyzer/editors/code/package-lock.json
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/editors/code/src/configuration.ts
external-crates/move/crates/move-analyzer/editors/code/src/context.ts
external-crates/move/crates/move-analyzer/editors/code/src/main.ts

This goal of this PR is to allow friction-less updates of the Move analyzer binary, particularly for developers that utilize Sui CLI, which should be the majority. We still want friction-less Move analyzer binary installation for developers that want to only use the IDE and do not have a local CLI installation.
Move analyzer can now be installed in three different way:
1. it's bundled with the VSCode extension and if no local Move analyzer installation exists (or local installations have a lower version than the bundled one), it gets installed as part of VSCode Move extension activation process
2. it's bundled with Sui's CLI binary (if this binary has the highest version of all those installed, it will be used)
3. it can be built locally (or downloaded from GitHub) and placed in the …

[move-ide] Modified move-analyzer installation procedure to utilize versioning

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_49.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_49.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_49.snap
sui-execution/latest/sui-adapter/src/execution_engine.rs

Gated by a protocol version we run upgrades of framework in its own VM.
That is to avoid loader cache issues when verification of a VM can use packages that are loaded already and as such incompatible with the new upgrade.
This solution should solve the vast majority of problems related to changes in framework code.
Next steps:
- forbid new `init` in framework modules (verifier check)
- make a easy to use framework to push `init` style code on the epoch after the framework upgrade. That is in line with what has been done for all new systems we exposed in the framework (e.g. random beacon and bridge)
Existing tests and about to run multi-epochs replay
--- …

Run framework verification on its own VM

---

crates/sui-graphql-rpc/src/types/coin.rs
crates/sui-indexer/migrations/mysql/2024-03-25-203621_objects/up.sql
crates/sui-indexer/migrations/pg/2023-08-19-044023_objects/up.sql

We need a dedicated index for `coin_type`. This can be a partial index `WHERE coin_type IS NOT NULL`
Manually ran benchmark suite and verified that all benchmarked queries did not timeout and completed within a sensible amount of time.
---

improve coin and balance query performance

---

crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/main.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/server/mock_handler.rs
crates/sui-bridge/src/server/mod.rs

This PR added an "/ping" endpoint that returns `BridgeNodePublicMetadata`. `BridgeNodePublicMetadata` is a collection of public info about a node. Now it contains the node version.
tested the new endpoint locally.
---

[bridge] return public metadata upon ping

---

consensus/core/src/authority_service.rs
consensus/core/src/block_manager.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/metrics.rs
consensus/core/src/subscriber.rs
consensus/core/src/synchronizer.rs

More metrics and logs related to block receive/acceptance/commit , subscription etc
CI
---

[Consensus 2.0] Additional metrics & logs

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-config/src/node.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/state_accumulator.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
crates/sui-e2e-tests/tests/checkpoint_tests.rs
crates/sui-node/src/lib.rs
crates/sui-single-node-benchmark/src/single_node.rs
crates/sui-swarm-config/src/network_config_builder.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
crates/sui-swarm/src/memory/swarm.rs
crates/test-cluster/src/lib.rs

With Mysticeti moving our checkpoint rate to 12 checkpoints per second, we now have to handle state accumulation for ~1 million new checkpoints per epoch. This requires that we rethink a few design decisions in state accumulator. 
This PR introduces V2 (enabled by default), which aims to make state accumulation more efficient across a couple of levels:
1. Make end of epoch accumulation faster by amortizing the cost of unioning all checkpoint accumulators in the epoch. i.e. rather than unioning ~1M accumulators (one per checkpoint) at end of epoch, sequentially accumulate each checkpoint into the running root state hash, and finalize the running root as the root state hash at end of epoch.
2. Avoid needing to read all 1 million accumulators from disk at end of epoch by enforcing that the …

[StateAccumulator] Introduce StateAccumulatorV2

---

external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_autocomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_autocomplete.move
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_no_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_no_autocomplete.move

This fixes a severity check in a `debug_assert` that was the result of adding `Severity::Info` to the compiler.
New tests that previously triggered the bug now do not.
---

[move][move-ide] Fix severity bug

---

.github/workflows/rust.yml

This changes simtest seed on rebase, but keeps the seed constant if there is no code change.
Also, do not fail fast, so all failures get found.
CI
---

[CI] use current commit hash as simtest seed, and do not fail fast

---

consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/synchronizer.rs

Mostly based on https://github.com/MystenLabs/sui/pull/18009.
Info contained in blocks can get outdated quickly, but processing old blocks still take significant resources. Disable proposing new blocks if there is no active peer consumer.
CI
---

[Consensus] stop proposing when there is no consumer for blocks

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/state_accumulator.rs

If a validator is behind on execution for the entire epoch, then checkpoint builder may craft the final checkpoint of the epoch and attempt to accumulate the root state hash, with the end result being that we skip accumulating all checkpoints of the epoch into the root state hash but the final. This is because to bootstrap running root accumulation at beginning of a new epoch, we use the previous root state hash, and we assume that if there are no running roots for the current epoch, we are handling accumulation for the beginning of the new epoch. 
To fix, let's check that the previous root state digest is current up to the previous checkpoint, otherwise await
The following passes against 100 seeds
```
./scripts/simtest/seed-search.py simtest --test …
```

[StateAccumulatorV2] Fix edge case; Disable for mainnet

---

consensus/core/src/authority_node.rs
consensus/core/src/commit_observer.rs
consensus/core/src/storage/rocksdb_store.rs
crates/sui-types/src/programmable_transaction_builder.rs

Initialize vector with capacity when the upcoming `push()` with known times.
---

refactor: Preallocate capacity for known size vectors

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-node/src/lib.rs
crates/sui-storage/src/indexes.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/typed-store-derive/src/lib.rs
crates/typed-store/tests/macro_tests.rs

The PR adds a new attribute `[deprecated]` that is used to drop the corresponding column family and eventually reclaim the space. 
During restart, the marked cf will be dropped. Space will be gradually reclaimed during the compaction process. Eventually, references to deprecated column families could be removed from the codebase.
The feature is hidden behind the temporary `remove_deprecated_tables` configuration flag.
Making it optional extends transition period and allows certain node operators to serve deprecated JSON RPC APIs for a bit longer

[rocksdb] add a deprecate attribute

---

crates/sui-indexer/src/apis/read_api.rs
crates/sui-json-rpc-api/src/read.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-open-rpc-macros/src/lib.rs

PR introduces new temporary JSON RPC endpoint that returns an object with version <= target. 
The endpoint will only be used by sui replay tool, so the latter can stop using expensive `loaded_child_object_versions` index on FNs

[json rpc] add tryGetObjectBeforeVersion endpoint

---

CONTRIBUTING.md
sdk/docs/pages/zksend/dapp.mdx

This pull request includes two changes:
1. Fixes a typo in the `StashedOnly` function. The variable `curentWallet` has been corrected to `currentWallet`.
2. Updates the documentation link in the `CONTRIBUTING.md` file to reflect the correct URL from `sui.docs.io` to `docs.sui.io`.
**For `StashedOnly` Function:**
- Verified that the function `StashedOnly` works correctly with the updated variable name.
- Ensured that there are no errors or warnings after the change.
- Manually tested the functionality to confirm that it behaves as expected with the correct variable name.
**For Documentation Link:**
- Verified that the new link directs to the correct site.
- Checked that the "Edit this page" link works correctly with the updated URL.
---
Check each box that your changes affect. If none of …

Fix typo in StashedOnly function and update documentation link in CONTRIBUTING.md

---

crates/sui-benchmark/src/workloads/shared_counter.rs
crates/sui-benchmark/src/workloads/shared_object_deletion.rs
crates/sui-benchmark/src/workloads/workload_configuration.rs

In shared counter workload, when `shared_counter_hotness_factor == 100`, currently no shared counter is created due to the calculation, even though the option doc specifies that when hotness factor is 100, we need to create 1 shared counter and all requests is targeting that counter.
```
// total_shared_counters = max(1, qps * (1.0 - hotness/100.0))
shared_counter_hotness_factor: Vec<u32>,
```
This PR also adds shared deletion workload weight in the total weight calculation in create_workload_builders.
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user …

Fix shared counter workload config creation

---

crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs

Due to recent performance degradations, the existing `DynamicField::query` method is now consistently timing out. As a workaround, we are using the `query_latest_dynamic_field` method, which fetches object data from the live `objects` table. This can be reverted once the `objects_snapshot` lag issue is fixed and we've backfilled the `objects_version` table.
Existing tests, manually verified additional examples
---

patch for fetching latest dynamic field state for zkloginverifysignature

---

crates/sui-types/src/object/bounded_visitor.rs

This adds the ability to start the Sui process (/indexers/fullnodes etc) with different `MAX_BOUNDs` for annotated values -- this is particularly useful for fullnodes and indexers.
To use a different bound from the default, you simply set `MAX_ANNOTATED_VALUE_SIZE=N` in your environment before starting the process. Where `N` is the number of bytes "in addition" that you're willing to tolerate when creating the annotated value from the un-annotated value (i.e., on types, variant names, and field names).
Added new test to make sure:
1. We respect this variable if set; and
2. Do not update the value if changed during runtime;
---
For each box you select, include information …

[sui-types] Update bounded visitor to take an environment variable override at startup

---

crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs

Due to recent performance degradations, the existing `DynamicField::query` method is now consistently timing out. As a workaround, we are using the `query_latest_dynamic_field` method, which fetches object data from the live `objects` table. This can be reverted once the `objects_snapshot` lag issue is fixed and we've backfilled the `objects_version` table.
---

Zklogin Verify Signature uses workaround to fetch 0x7 dynamic field

---

crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/raw_query.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/compatibility_check.rs
crates/sui-graphql-rpc/src/server/mod.rs
crates/sui-indexer/src/models/checkpoints.rs
crates/sui-indexer/src/models/display.rs
crates/sui-indexer/src/models/events.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-indexer/src/models/packages.rs
crates/sui-indexer/src/models/tx_indices.rs

Add a compatibility check on server start `server.run` that goes through each table in the schema and makes a simple `select * from table limit 1`
I've added `Selectable` as a macro to the Rust structs that correspond to the data we'd select from each table, so we can use it in the macro
---

[gql] Compatibility check on graphql service startup

---

crates/sui-graphql-rpc/src/raw_query.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/compatibility_check.rs
crates/sui-graphql-rpc/src/server/mod.rs
crates/sui-indexer/src/models/checkpoints.rs
crates/sui-indexer/src/models/display.rs
crates/sui-indexer/src/models/events.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-indexer/src/models/packages.rs
crates/sui-indexer/src/models/tx_indices.rs

Add a compatibility check on server start `server.run` that goes through each table in the schema and makes a simple `select * from table limit 1`
I've added `Selectable` as a macro to the Rust structs that correspond to the data we'd select from each table, so we can use it in the macro
---
---
Check each box that your changes affect. If none …

[gql] Compatibility check on graphql service startup (#18118)

---

crates/sui-core/src/consensus_adapter.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/test-cluster/src/lib.rs
scripts/simtest/seed-search.py

Previously, the test could fail because newly created validators might not be in the current epoch when asked to terminate the epoch early. This could result in not having a quorum for end-of-epoch.
The fix is to wait for newly spawned validators to sync to the current epoch.

Fix flakiness in test_reconfig_with_committee_change_stress

---

crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/e2e_tests/complex.rs
crates/sui-bridge/src/error.rs
crates/sui-bridge/src/eth_client.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/orchestrator.rs

The latest solidity code already disallows 0 transfer. After move's update, this should not be reachable in bridge node.
new unit tests
---

[bridge] bridge node check zero transfer value and err

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-core/src/traffic_controller/policies.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-json-rpc/src/axum_router.rs
crates/sui-types/src/traffic_control.rs

We received reports from a community validator of error logs from failure to parse `x-forwarded-for` header value to a `SocketAddr`. Investigation revealed that this is because the validator is running HAProxy, which attempts to insert the header itself (and in this case the value inserted was `-`). 
We are not using this value anyway, and even if we were, we would not want to be reading the value inserted by HAProxy as this would correspond to the fullnode rather than the client. 
Note that this also should obviate the fact that running TrafficController or related on a validator that is running HAProxy can have bad unintended side effects - namely that a spammy fullnode may cause a validator running HAProxy to block its HAProxy instance rather than the fullnode itself. 
To fix all of …

[Traffic Control] Make it play nicely with proxy infra

---

crates/sui-core/src/state_accumulator.rs
crates/sui-snapshot/src/lib.rs
crates/sui-snapshot/src/reader.rs
crates/sui-tool/src/commands.rs
crates/sui-tool/src/lib.rs

`--verify strict` adds an additional level of verification by verifying the live object set of the db after restore, rather than simply the contents of the snapshot itself. These two are not equivalent in cases where the restore process inadvertently adds objects to the live object set from a source other than the downloaded snapshot itself. One such example could be inserting genesis objects.
```
target/release/sui-tool download-formal-snapshot --network mainnet --latest --path /opt/sui/db/authorities_db --genesis /opt/sui/mainnet/config/genesis.blob --no-sign-request --verify strict
Beginning formal snapshot restore to end of epoch 419, network: Mainnet with verification mode Strict
[00:25:02] ███████████████████████████████████████████████████████████████████████████████████████████████ …
```

[formal-snapshots] Introduce strict verification

---

crates/sui-json-rpc-types/src/sui_move.rs

Got removed in the enums PR for some reason, so adding it back in.
CI

[sui-json-rpc-types] Add back `read_dynamic_field_value` to SuiMoveStruct

---

external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/naming/unknown_contructor_name.exp
external-crates/move/crates/move-compiler/tests/move_2024/naming/unknown_contructor_name.move

This improves the error for a specific naming miss.
New test
---

[move][move-2024] Improve errors when a call might be referring to a missing datatype.

---

docker/sui-tools/Dockerfile

The `sui-bridge` binary is unable to make upstream TLS requests without the root CA bundle
Add the ca-certificates package in the sui-tools Dockerfile package list.
---

Add ca-certificates to sui-tools Dockerfile

---

.github/workflows/release.yml
chocolatey/sui.nuspec

Fix `sui.exe` path for chocolatey upload
https://github.com/MystenLabs/sui/actions/runs/9490454584/job/26153963440

Fix `sui.exe` path for chocolatey upload

---

external-crates/move/crates/move-cli/src/base/test.rs
external-crates/move/crates/move-cli/tests/sandbox_tests/clever_errors/args.exp
external-crates/move/crates/move-cli/tests/sandbox_tests/clever_errors/sources/AModule.move
external-crates/move/crates/move-cli/tests/sandbox_tests/clever_errors/tests/AModuleTestsShouldAllFail.move
external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/unit_test/mod.rs
external-crates/move/crates/move-unit-test/src/lib.rs
external-crates/move/crates/move-unit-test/src/test_reporter.rs

This changes the way we report source locations for clever errors coming from an `assert!(<bool>)` within a macro. In particular, since the line number is rewritten during macro-expansion, we use this as the location of the error in unit tests when reporting the error if there is no overlap between the line number from the clever assertion error and the "actual" error.
Note that it was easiest to do this by plumbing in the `MappedFiles` instead of using the `FilesSourcesText` in unit tests anymore. This simplified a number of other places as well (e.g., for getting the line number from a location).
Made sure existing tests continued to pass, and added tests for the new behavior.
--- …

[move] Use clever error locations for macro-rewritten lines in Move unit test errors

---

external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs
external-crates/move/crates/move-compiler/src/hlir/mod.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/shared/matching.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-compiler/src/shared/program_info.rs
external-crates/move/crates/move-compiler/src/typing/core.rs
external-crates/move/crates/move-compiler/src/typing/dependency_ordering.rs
external-crates/move/crates/move-compiler/src/typing/match_analysis.rs
external-crates/move/crates/move-compiler/src/typing/mod.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs

This make the following changes:
1. It moves some custom query information that was being maintained as part of the typing context (and before that, as part of the HLIR context) onto `ProgramInfo` to allow matching operations to query information about the structure of datatypes for any program information.
2. It splits the main `PatternMatrix` definitions (data + code) into `shared/matching.rs`, along with a `MatchContext` trait that the matrix specialization operations are now generic over.
3. It removes the actual match compilation code from typing, partially reverting #17559 -- counterexample generation and IDE suggestion analysis happens in typing as a visitor over function bodies, but matches remain intact through all of typing now.
4. It reinstates the previous code for compiling …

[move][move-2024][ide] Split up match in the compiler

---

crates/sui-replay/src/data_fetcher.rs
crates/sui-replay/src/lib.rs
crates/sui-replay/src/replay.rs
crates/sui-replay/src/types.rs
crates/sui-sdk/src/apis.rs
crates/sui/src/client_commands.rs

The PR removes usage of the sui_getLoadedChildObjects API for the remote mode of the replay tool. 
It's required to drop the corresponding index from index_db.
The change is verified by deploying the dynamic field smart contract to devnet, modifying the underlying child object several times, and replaying the corresponding transactions:
```sui-tool replay --rpc https://fullnode.devnet.sui.io:443 tx -t F5xtZeoHH8Dk6cSMbN1CEz7GiYmC4HGjYuBN2La5wr3R```

[sui replay] migrate off using sui_getLoadedChildObjects json rpc api

---

consensus/core/src/core.rs
consensus/core/src/transaction.rs
consensus/core/src/universal_committer.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/mysticeti_adapter.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_50.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_50.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_50.snap
scripts/simtest/seed-search.py

On the boundaries of Leader Schedule change it is possible to elect a new leader for the same round resulting in multiple commits for the same round. This was unintended output from consensus as we have set the parameters to only commit 1 leader per round. Sui also only expects one commit per round, because of this the second commit of the same round is ignored by consensus handler. This led to an error in simtests where the `EndOfPublish` transaction was part of this ignored commit and we could not form a quorum to close the epoch without this node. 
Changes
-  Explicitly set number of leaders per round to 1 for Mysticeti commits. I wanted to try and maintain this but it would be a much more intrusive change and we will probably have to do a larger refactor to fully support it anyways, …

[consensus] Disable multi leader per round in universal committer

---

crates/sui-core/src/authority.rs
crates/sui-indexer/src/apis/read_api.rs
crates/sui-json-rpc-api/src/read.rs
crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-json-rpc/src/authority_state.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-open-rpc/src/examples.rs
crates/sui-sdk/src/apis.rs
crates/sui-storage/src/indexes.rs

PR marks as deprecated following indexes:
* transactions_by_input_object_id
* transactions_by_mutated_object_id
* loaded_child_object_versions

[json rpc] deprecate indexes

---

crates/sui-graphql-rpc/src/extensions/timeout.rs

A previous PR messed up the logging of queries that time out. This fixes it.
Locally.
---

[GraphQL][cherry-pick] Fix missing setting the query string (#18238)

---

crates/sui-graphql-rpc/src/extensions/timeout.rs

A previous PR messed up the logging of queries that time out. This fixes it.
Locally.
---

[Cherry-pick][GraphQL] Fix for timeout query logs

---

crates/sui-archival/src/reader.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-snapshot/src/lib.rs
crates/sui-snapshot/src/reader.rs
crates/sui-tool/src/commands.rs
crates/sui-tool/src/lib.rs

Checkpoint summary sync and verification now dominates the critical path for formal snapshot restore. Mysticeti is magnifying this due to the increased checkpointing rate. 
This PR aims to fix this by removing the requirement that we download and verify all checkpoints. 
If `--all-checkpoints` flag is provided, behavior is as it was before. If not, we simply download all end of epoch checkpoints, check signatures, and omit the step where we verify checkpoint chain continuity. The security argument for why this is ok is that the validators in the committee had to verify chain continuity, and a quorum of them signed against the given checkpoint digest. Signature verification confirms that the contents have not been altered, and the digest matching confirms that the chain was checked for …

[formal-snapshots] skiplist checkpoint sync and verification

---

crates/sui-core/src/consensus_handler.rs

When Narwhal is running it is still possible on restarts to resend a commit from the same round. Mysticeti should not return more than one commit per round unless something is broken so it is okay to keep this check for now.

[consensus] Revert consensus handler change where commits from the same round are ignored

---

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-e2e-tests/tests/checkpoint_tests.rs
crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs

This will allow us to disable fault injection on antithesis after reaching the warn timeout.

Support for a separate panic timeout and warn timeout.

---

.github/workflows/bridge.yml

there is no need to run evm tests for Rust changes: if Rust change becomes incompatible with solidity code, the Rust e2e tests will fail.
---

do not run evm tests except for sol changes

---

external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs
external-crates/move/crates/move-analyzer/src/compiler_info.rs
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/inlay_hints.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/src/utils.rs
external-crates/move/crates/move-analyzer/tests/completion/Move.toml
external-crates/move/crates/move-analyzer/tests/completion/sources/dot.move
external-crates/move/crates/move-compiler/src/shared/ide.rs
external-crates/move/crates/move-compiler/src/typing/core.rs
external-crates/move/crates/move-compiler/src/typing/expand.rs
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/use_fun_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/use_fun_autocomplete.move

This PR stands on the shoulders of previously done compiler-side work and simply adds the IDE-side of things to support intelligent auto-completion.
Works for dot completion without valid identifier following the dot:
It also works for dot completion when the following identifier is already (partially) typed:
Note that additional information (in addition to just name to be completed is available): target function (for methods) as well as the target function signature/type (for methods/fields)
Field completions are inserted "as is" (just the field name) but method completions are inserted as snippets listing parameter names for a given method. The following screenshot shows the effect of accepting the auto-completion suggestion from the screenshot directly above (`param` has been inserted …

[move-ide] Added support for intelligent dot auto-completion

---

crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/objects_snapshot_processor.rs
crates/sui-indexer/src/indexer.rs

This PR separates indexing and committing of objects snapshot table into its own pipeline, that can run independently from the rest of the indexer easily. 
Tested locally against devnet fullnode.
---

[indexer] move objects snapshot processing into its own pipeline

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/compatibility_check.rs
crates/sui-indexer/src/schema/mod.rs
crates/sui-indexer/src/schema/mysql.rs
crates/sui-indexer/src/schema/pg.rs

Increase the likelihood that when a schema change is made on the indexer side, the compatibility check on the GraphQL side is also updated, by removing the duplication of table names from both places:
Now, the compatibility check relies on a macro --
`sui_indexer::for_all_tables` to enumerate tables. This is more likely to be updated when a new table is added because it's also used by the indexer to ensure all the tables can appear in queries next to each other.
This PR also changes the nature of the query used for the compatibility check: It no longer relies on knowing about a model type to select fields for, because such a type may have columns missing. Instead it fetches all the columns for the table, but then discards them.
Run the service against a compatible DB -- it should spin up. …

[GraphQL] Ensure single source of truth for compatibility check

---

crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/state_accumulator.rs

Manual CP of https://github.com/MystenLabs/sui/pull/18278
---

Disable accum v2 testnet cp

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/compatibility_check.rs
crates/sui-indexer/src/schema.rs

Increase the likelihood that when a schema change is made on the indexer side, the compatibility check on the GraphQL side is also updated, by removing the duplication of table names from both places:
Now, the compatibility check relies on a macro --
`sui_indexer::for_all_tables` to enumerate tables. This is more likely to be updated when a new table is added because it's also used by the indexer to ensure all the tables can appear in queries next to each other.
This PR also changes the nature of the query used for the compatibility check: It no longer relies on knowing about a model type to select fields for, because such a type may have columns missing. Instead it fetches all the columns for the table, but then discards them.
Run the service against a compatible DB -- it should spin up. …

[pick #18261][GraphQL] Ensure single source of truth for compatibility check

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_50.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_50.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_50.snap

Deferred txn due to congestion will be cancelled after 10 consensus commit rounds.
Note that this setting has no effect if congestion control is not on.
---

Set max_deferral_rounds_for_congestion_control to 10

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs

Add an API to AuthorityState to allow for epoch change during a single validator test.
This will unblock the per-epoch-immutable config Move transactional tests.
Added a smoke test.
---

[test] Allow AuthorityState to reconfigure in single validator tests

---

Cargo.lock
crates/sui-config/src/node.rs
crates/sui-core/Cargo.toml
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/signature_verifier.rs
crates/sui-network/build.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
crates/sui-types/src/error.rs
crates/sui-types/src/messages_grpc.rs

This is a follow up change after PR #17508 , for [SIP-19](https://github.com/sui-foundation/sips/blob/main/sips/sip-19.md).
The changeset focuses on sui-core, particularly authority server, to add a new API `SoftBundleCertifiedTransactionsV3` that allows submission of a Soft Bundle through gRPC.
The API accepts a list of `CertifiedTransaction` for input, then returns either nothing (should `wait_for_effects` be `false`) or a list of `HandleCertificateResponseV3` containing the execution result.
The API is named `_v3` because it reuses `HandleCertificateResponseV3`. 
Besides introducing a new feature flag and a protocol config field, a local node config field `enable_soft_bundle` is also added, to allow a validator node to turn off soft bundle support without having to upgrade the entire …

Soft Bundle authority API implementation

---

crates/sui-move-build/src/lib.rs
external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/diagnostics.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/src/utils.rs
external-crates/move/crates/move-cli/src/base/test.rs
external-crates/move/crates/move-cli/src/sandbox/utils/mod.rs
external-crates/move/crates/move-compiler/src/command_line/compiler.rs
external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/parser/mod.rs
external-crates/move/crates/move-compiler/src/shared/files.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-compiler/src/to_bytecode/translate.rs
external-crates/move/crates/move-compiler/src/unit_test/mod.rs
external-crates/move/crates/move-ir-types/src/location.rs
external-crates/move/crates/move-model/src/lib.rs
external-crates/move/crates/move-package/src/compilation/build_plan.rs
external-crates/move/crates/move-package/src/compilation/compiled_package.rs
external-crates/move/crates/move-transactional-test-runner/src/framework.rs
external-crates/move/crates/move-unit-test/src/lib.rs
external-crates/move/crates/move-unit-test/src/test_reporter.rs

This swaps out `FilesSourceText` for `MappedFiles` whenever possible, along with the following changes: 
- The internal implementation of `MappedFiles` is a little more complicated to support some `move-analyzer` behaviors.
- `MappedFiles` now lives in `move-compiler/shared/files.rs` to reflect it being standalone from the diagnostics.
- This also updates the `move-analyzer` to start using the `MappedFiles` instead of maintaining a separate file state.
- The `Position` form had its fields reverted to non-`pub` with getters to better-clarify the value being returned.
All tests still run.
--- …

[move][move-ide][move-compiler] Swap `FilesSourceText` to `MappedFiles` in most places

---

crates/sui-core/src/authority.rs
crates/sui-core/src/unit_tests/coin_deny_list_tests.rs
crates/sui-core/src/unit_tests/data/coin_deny_list_v1/Move.toml
crates/sui-core/src/unit_tests/data/coin_deny_list_v1/sources/regulated_coin.move

The coin deny list v1 tests can be run in a single authority, without a cluster.
CI
---

[test] Move coin deny list tests to authority tests

---

Cargo.lock
crates/sui-core/Cargo.toml
crates/sui-core/src/authority/authority_store_tables.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/rest_index.rs
crates/sui-node/src/lib.rs

From a few local tests using epoch 429's formal snapshot, this patch reduced indexing time from ~45 minutes to ~5 minutes.
---

rest-index: parallelize initializing index

---

crates/sui-graphql-rpc/src/server/compatibility_check.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/models/tx_indices.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/types.rs

update the TxIndex.senders to a single .sender, since we only index a single sender today. Update the Rust structs that correspond to tx lookup tables, and then update how we index data to these tables. Namely, we drop `cp_sequence_number` and denormalize `sender` as a column on all the lookup tables.
---

[2/n][gql-performance] update committer and store-writer for new tx indices

---

crates/sui-core/src/execution_cache/writeback_cache.rs

We already invalidated the `object_by_id` cache for written objects, but we must also invalidate it for deleted and wrapped objects.

Fix cache bug caused by insufficient validation

---

scripts/simtest/seed-search.py

Previously, the options were more or less reversed from what you'd expect

Make command line usage of seed-search mirror that of nextest

---

consensus/core/src/core.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/transaction.rs
crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/congestion_control_tests.rs
crates/sui-core/src/unit_tests/shared_object_deletion_tests.rs
crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-e2e-tests/tests/zklogin_tests.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
narwhal/primary/src/consensus/tests/bullshark_tests.rs
narwhal/primary/src/consensus/tests/consensus_tests.rs
narwhal/primary/src/consensus/tests/leader_schedule_tests.rs
narwhal/primary/src/tests/certificate_fetcher_tests.rs
narwhal/primary/tests/randomized_tests.rs

1. For the feature flags, all setters should be named with _for_testing suffix.
2. For non feature flags, there are already testing setters defined through macro, and there is no need to define them separately.
Also found that there are quite a few non-boolean flags in the feature flags, which we should clean up at some point too.
CI
---

Clean up protocol config testing setters

---

crates/sui/src/client_commands.rs
crates/sui/src/displays/dry_run_tx_block.rs

Prints the estimated gas cost after a dry run's execution status.
```
Dry run completed, execution status: success
Estimated gas cost (includes a small buffer): 72216400 MIST
```
Existing features
---

[CLI][Easy] Display the estimated gas budget after a dry run info

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs

All of these flags have been released for months, so the old code should not be needed anywhere at this point.

Deprecate old epoch flags and delete dead code

---

docker/sui-network/Dockerfile
docker/sui-network/docker-compose-antithesis.yaml

follow up to https://github.com/MystenLabs/sui/pull/18311
specific changes are:
calling `/usr/local/bin/sui-node-inst` instead of `/usr/local/bin/sui-node` and changing the image name to `sui-node:mainnet`

use dedicated antithesis compose file

---

Cargo.lock
crates/sui-package-resolver/src/lib.rs
crates/sui/src/clever_error_rendering.rs
crates/sui/src/client_commands.rs
crates/sui/src/lib.rs
crates/sui/src/snapshots/sui__clever_error_rendering__tests__parse_abort_status_string.snap
crates/sui/tests/cli_tests.rs
crates/sui/tests/data/clever_errors/Move.toml
crates/sui/tests/data/clever_errors/sources/clever_errors.move
crates/sui/tests/snapshots/cli_tests__body_fn.snap
external-crates/move/Cargo.lock
external-crates/move/crates/move-cli/tests/build_tests/disassemble_module/args.exp
external-crates/move/crates/move-cli/tests/build_tests/disassemble_module/sources/m.move
external-crates/move/crates/move-cli/tests/sandbox_tests/package_basics/args.exp
external-crates/move/crates/move-command-line-common/Cargo.toml
external-crates/move/crates/move-command-line-common/src/display.rs
external-crates/move/crates/move-command-line-common/src/lib.rs
external-crates/move/crates/move-disassembler/src/disassembler.rs

Enables clever error rendering in the Sui CLI.
It also abstracts out some of the rendering logic for constants into their own file so it can be reused across the graphql and Sui CLI renderer. 
This also updates the Move disassembler to use this new (nicer!) renderer to that we support rendered values for constants in the Move disassembler instead of just strings in constants.
Added new tests for this to the Sui CLI, and updated/added additional tests for the disassembler.
---

[CLI] Add clever error support to Sui CLI

---

crates/sui-core/src/unit_tests/coin_deny_list_tests.rs
crates/sui-core/src/unit_tests/data/coin_deny_list_v2/Move.toml
crates/sui-core/src/unit_tests/data/coin_deny_list_v2/sources/regulated_coin.move
crates/sui-types/src/base_types.rs
crates/sui-types/src/deny_list_v2.rs
crates/sui-types/src/lib.rs

This is based on the upcoming implementation in https://github.com/tnowacki/sui/tree/config/crates/sui-framework/packages/sui-framework/sources
This PR doesn't introduce any functional changes yet.
It only adds the basic types for denylist v2, as well as the functions to load the config setting data.
Added a test that passes with the new Move code.
We can merge this early.
Test can be enabled once we have the Move code in.
Added a basic test.
---

Add Rust types for denylist v2

---

crates/sui-framework/packages/sui-framework/sources/event.move
crates/sui-framework/packages/sui-framework/tests/event_tests.move
crates/sui-framework/packages/sui-framework/tests/test_scenario_tests.move

Follow up on https://github.com/MystenLabs/sui/commit/9c9ffd088cc00d5775100971be96198ced0dfb26 now that the native functions are live

[move] enable event introspection in tests

---

external-crates/move/crates/move-cli/src/sandbox/utils/mod.rs
external-crates/move/crates/move-core-types/src/effects.rs
external-crates/move/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/crates/move-vm-runtime/src/runtime.rs
external-crates/move/crates/move-vm-runtime/src/session.rs
external-crates/move/crates/move-vm-test-utils/src/storage.rs
external-crates/move/crates/move-vm-types/src/data_store.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/runtime.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/session.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/runtime.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/session.rs
external-crates/move/move-execution/v2/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/move-execution/v2/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/move-execution/v2/crates/move-vm-runtime/src/runtime.rs
external-crates/move/move-execution/v2/crates/move-vm-runtime/src/session.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs
sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs
sui-execution/v2/sui-adapter/src/programmable_transactions/context.rs

Remove code related to resources from the transaction data cache to simplify code on our way to session removal and trait simplification in the Move VM.
One step at the time to avoid making a massive and too confusing PR.
This way we get more clarity on what is needed.
It slightly cleans up things in the adapter as well
Existing tests
---

remove resource handling from transaction data cache

---

external-crates/move/crates/move-compiler/src/parser/syntax.rs

This fixes a minor compiler implementation issue reported in https://github.com/MystenLabs/sui/issues/18285 (the `parse_file` function no longer needs to return `Result` as diagnostics previously returned as part of it are instead added to the compilation context).
All existing tests must pass

[move-compiler] No need to ever return diags when parsing a file

---

consensus/core/src/block_manager.rs
consensus/core/src/context.rs
consensus/core/src/core.rs
consensus/core/src/lib.rs
consensus/core/src/test_dag.rs
consensus/core/src/test_dag_builder.rs
consensus/core/src/tests/randomized_tests.rs
consensus/core/src/universal_committer.rs

The random tests will print out a seed that can be passed in as an env var (`DAG_TEST_SEED`) to repro any failures. Also for now going through block manager so we can randomize how the blocks are received but ideally we can test this flow directly through core once "turning off proposal" is possible in core. Additionally we can follow up this PR with even more randomized dags to simulate crashes, byzantine validators, etc.

[consensus] Add Randomized Commit Tests

---

crates/sui-adapter-transactional-tests/tests/epoch/advance.exp
crates/sui-adapter-transactional-tests/tests/epoch/advance.move
crates/sui-transactional-test-runner/src/lib.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

- Added advance epoch support to normal sui-adapter-transactional-tests
- added a test 
---

[move][transactional tests] Add advance-epoch support

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/ci/image.rs
crates/suiop-cli/src/cli/ci/mod.rs

Support building image from suiop CLI
With this, you can build and push images to our repo. The CLI tool supports building from branch, commit or tag.
you can build from branch or commit from suiop CLI
you can also query the image build history:
---

[suiop] Add ci image build command

---

external-crates/move/crates/move-analyzer/src/symbols.rs

The main fix here is to add back merge of `file_use_defs` in the `Symbols` struct accidentally removed in https://github.com/MystenLabs/sui/pull/18270
It also finesses merging of `MappedFiles` struct a bit:
- re-implements a variant of `extend` function that allows duplicate hashes (as this is a normal situation when merging symbolic information (as most files will not change between symbol computations)
- adds `MappedFiles` extension on pre-compiled libs retrieval (as opposed to having it only on pre-compiled lib computation)
All tests must pass plus verified that IDE support now again works correctly

[move-ide] Symbolic information merge fixes

---

crates/sui-core/src/epoch/randomness.rs
scripts/compatibility/split-cluster-check.sh

Verify that DKG completes after the reconf in split-cluster-check.
Also add a more concrete log for 'DKG start' event, to be used in the future in the above verification.
manually tested
---

split-cluster-check - Verify that DKG completes if enabled

---

Cargo.lock
crates/sui-bridge-indexer/Cargo.toml
crates/sui-bridge-indexer/src/eth_worker.rs
crates/sui-bridge-indexer/src/latest_eth_syncer.rs
crates/sui-bridge-indexer/src/lib.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-indexer/src/metrics.rs
crates/sui-bridge-indexer/src/postgres_manager.rs
crates/sui-bridge-indexer/src/sui_worker.rs

Added the following:
- DepositedUnfinalized TokenTransferStatus. This status indicates that this event was captured in an unfinalized block.  
- LatestEthSyncer component that enables the indexer to listen to unfinalized blocks. 
- Eth idempotency. This is so that we can start indexing from the block that was last processed when starting / restarting the indexer.

Bridge Indexer Latest Eth Syncer

---

Cargo.lock
external-crates/move/Cargo.lock
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/parsing/named_addresses.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/parsing/named_addresses.mvir
external-crates/move/crates/move-ir-compiler/Cargo.toml
external-crates/move/crates/move-ir-compiler/src/lib.rs
external-crates/move/crates/move-ir-to-bytecode-syntax/src/lexer.rs
external-crates/move/crates/move-ir-to-bytecode-syntax/src/syntax.rs
external-crates/move/crates/move-ir-to-bytecode/src/parser.rs
external-crates/move/crates/move-transactional-test-runner/src/framework.rs

Little PR that adds support for using named addresses in Move IR source syntax.
Added a test to make sure that we handle them correctly, and existing tests.

[move] Add named addresses to Move IR syntax

---

external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs
external-crates/move/crates/move-compiler/tests/move_2024/matching/mut_in_guard.move

Fix a bug where mutability was preserved for variables when creating match bindings (not the final arm binders, but the imm. ref binders themselves).
Test added that demonstrated the issue, and now it works instead.
---

[move][move-2024][match] Fix mut match bug

---

.changeset/rude-cooks-know.md
.github/actions/turbo-diffs/action.yml
.github/workflows/e2e.yml
sdk/docs/pages/typescript/executors.mdx
sdk/docs/pages/typescript/transaction-building/intents.mdx
sdk/typescript/src/transactions/ObjectCache.ts
sdk/typescript/src/transactions/executor/caching.ts
sdk/typescript/src/transactions/executor/parallel.ts
sdk/typescript/src/transactions/executor/serial.ts
sdk/typescript/src/transactions/json-rpc-resolver.ts
sdk/typescript/test/e2e/entry-point-string.test.ts
sdk/typescript/test/e2e/object-cache.test.ts
sdk/typescript/test/e2e/object-vector.test.ts
sdk/typescript/test/e2e/parallel-executor.test.ts
sdk/typescript/test/e2e/serial-executor.test.ts
sdk/typescript/test/e2e/utils/setup.ts

e2e test improvements, and fixes for executor classes

---

bridge/evm/contracts/utils/BridgeUtils.sol
bridge/evm/test/SuiBridgeTest.t.sol

We want to disable bridging of zero amounts provided. 
Added two unit tests for both ERC20 and Native ETH bridging 
---

Enforce non-zero bridge amount

---

Cargo.lock
external-crates/move/Cargo.lock
external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/inlay_hints.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-compiler/Cargo.toml
external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/shared/files.rs

This swaps the move analyzer `DefLoc` to be a shared IR `Loc` form (used everywhere else). 
The move analyzer tests pass, plus local testing in VS Code still works.
---

[move][move-ide] Swap move-analyzer to use `loc`

---

crates/sui-bridge-cli/src/lib.rs
crates/sui-bridge-cli/src/main.rs
crates/sui-bridge-indexer/src/eth_worker.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/encoding.rs
crates/sui-bridge/src/eth_client.rs
crates/sui-bridge/src/eth_syncer.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/metrics.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/server/mod.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_syncer.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/types.rs

[bridge] some fixes to bridge node

---

Cargo.lock
Cargo.toml
crates/sui-graphql-config/Cargo.toml
crates/sui-graphql-config/src/lib.rs
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/version.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/examples_validation_tests.rs

When a field is labeled with `#[serde(default)]` it means that if that field is not present, it is populated using the `Default` impl for the field's type:
```rust
#[derive(Serialize, Deserialize, Clone, Debug)]
struct Foo {
#[serde(default)]
bar: Bar,
}
Foo { bar: Bar::default() }
```
This is not the behaviour we want, however. We want fields that have not been supplied to be populated with their value from the `Default` impl of the type they are part of:
```rust
Foo { bar: Foo::default().bar }
```
Implementing this manually requires a lot of boilerplate -- each field needs to have an associated function that returns its default value:
```rust
#[derive(Serialize, Deserialize, Clone, Debug)]
struct Foo {
#[serde(default = "Foo::__default_bar")]
bar: Bar,
}
```
So this PR introduces an …

[GraphQL] Fix bug where config types "zero out" fields not in TOML

---

crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/immutable_dof.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/immutable_dof.move
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/nested_dof.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/nested_dof.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/coin.rs
crates/sui-graphql-rpc/src/types/coin_metadata.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/move_object.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/src/types/suins_registration.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Cherry-pick #17934 which fixes dof implementation of nested dof
---

[pick][gql-2024.4] fix nested dof implementation

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/ci/image.rs

Adding two endpoints for improving image building process visibility:
1. list: show all the images in the AR
2. status: check whether the image is built and stored in AR, if not in AR, show real-time status of the building process
list
status
```
suiop ci image status --repo-name infra-metadata-service --image-name go-executor
Requested status for repo: infra-metadata-service, image: go-executor, ref: branch:main
Image Status: Found
Image SHA: 1d01c74ca5cfb3c7103
```
```
suiop ci image status --repo-name infra-metadata-service --image-name go-executor --ref-type=commit --ref-val=123
Requested status for repo: infra-metadata-service, image: go-executor, ref: commit:123
Image Status: Not built and image not found
Image SHA: 123
```
---
Check each …

[suiop][image] add list and get current status endpoint

---

crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs

Unblock https://github.com/MystenLabs/sui/pull/18277 by explicitly setting up the correct test scenario for the `test_query_default_page_limit` test.
I think we can follow this up with 
1. instead of using the same db url, follow sui-graphql-e2e-tests pattern and generate unique db urls for each test
2. this is so that we can run tests in parallel instead of sequentially (which is the case today due to the serial)
3. we can leverage ExecutorCluster.cleanup_resources to cleanup each test
--- …

explicitly setup test scenario for test_query_default_page_limit

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/watermark_task.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs

Adds a `checkpoint_timestamp_ms` to the watermark task and uses it in a new health check endpoint function. The health endpoint checks for two things
- if there is a DB connection, otherwise it returns code 500
- if the last known checkpoint timestamp is within an acceptable buffer. It subtracts the current timestamp from the checkpoint timestamp, and checks if the value is larger than the provided query param `max_checkpoint_lag_ms` or a default value, and it returns code 504, GATEWAY TIMEOUT in that case.
How to query this endpoint:
`curl -X GET "http://127.0.0.1:8000/health" -i `
Set the check for max checkpoint time lag to 10s. If it returns 503, then the checkpoint is behind.
`curl -X GET "http://127.0.0.1:8000/health?max_checkpoint_lag_ms=10000" -i`       
Added a new test.
`cargo …

[GraphQL] Add health endpoint 

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/watermark_task.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs

Adds a `checkpoint_timestamp_ms` to the watermark task and uses it in a new health check endpoint function. The health endpoint checks for two things
- if there is a DB connection, otherwise it returns code 500
- if the last known checkpoint timestamp is within an acceptable buffer. It subtracts the current timestamp from the checkpoint timestamp, and checks if the value is larger than the provided query param `max_checkpoint_lag_ms` or a default value, and it returns code 504, GATEWAY TIMEOUT in that case.
How to query this endpoint:
`curl -X GET "http://127.0.0.1:8000/health" -i `
Set the check for max checkpoint time lag to 10s. If it returns 503, then the checkpoint is behind.
`curl -X GET "http://127.0.0.1:8000/health?max_checkpoint_lag_ms=10000" -i`
Added a new test.
`cargo nextest …

[GraphQL][cherry-pick #18277] Gql cherry pick health endpoint into 2024.4 release

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/checkpoints/checkpoint_executor/metrics.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/state_accumulator.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-node/src/lib.rs
crates/sui-single-node-benchmark/src/single_node.rs

Make state accumulator a per epoch component. This also requires that we make checkpoint executor a proper per epoch component (previously it was only instantiated once, but `run_epoch` called once per epoch) since it needs to have a reference to the fresh accumulator after reconfig. Now we actually drop it after the call to `run_epoch` returns.
Passed against 120+ seeds:
```
./scripts/simtest/seed-search.py simtest --test test_simulated_load_reconfig_with_crashes_and_delays
```
---

[core] Make proper per epoch execution components

---

crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/immutable_dof.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/immutable_dof.move
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/nested_dof.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/nested_dof.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/coin.rs
crates/sui-graphql-rpc/src/types/coin_metadata.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/move_object.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/src/types/suins_registration.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/end_of_epoch.rs
crates/sui-graphql-rpc/src/types/transaction_block_kind/genesis.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Cherry-pick #17934 to the legacy branch
---

[pick][gql-2024.1.0] fix dof queries

---

crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/store/pg_partition_manager.rs

If a table is partitioned by not by epochs, we shouldn't do anything to it when advancing epochs.
---

[indexer] ignore tables not partitioned by epoch at epoch change

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/checkpoints/mod.rs

This is the first step of a change to remove effects signing from the execution path and adding effects equivocation prevention (necessary for WB cache on validators).

Use dedicated table for determining if transaction was executed in current epoch

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/test_utils.rs
crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-e2e-tests/tests/transfer_to_object_tests.rs
crates/sui-e2e-tests/tests/zklogin_tests.rs
crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-transaction-checks/src/lib.rs
crates/sui-types/src/error.rs
crates/sui-types/src/transaction.rs

1. Consolidate check_version_and_features_supported with validity_check for all transaction related types.
2. Remove a few redundant checks.
3. Make the error type consistent.
CI
---

Get rid of versioned message impl for transaction related types

---

external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs
external-crates/move/crates/move-compiler/src/shared/matching.rs
external-crates/move/crates/move-compiler/src/typing/match_analysis.rs
external-crates/move/crates/move-compiler/tests/move_2024/matching/counterexample_malformed_match.exp
external-crates/move/crates/move-compiler/tests/move_2024/matching/counterexample_malformed_match.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/counterexample_malformed_match_2.exp
external-crates/move/crates/move-compiler/tests/move_2024/matching/counterexample_malformed_match_2.move

This fixes a bug that was previously a compiler crash when a match was malformed and counterexample generation occurred. This was due to some changes for parser resilience combined with moving match analysis to typing.
Added the repro test, and it now produces the error as expected.
---

[move][move-2024][enums] Fix a small issue when match is malformed

---

Cargo.lock
Cargo.toml
crates/sui-graphql-config/Cargo.toml
crates/sui-graphql-config/src/lib.rs
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/context_data/db_data_provider.rs
crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/version.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/examples_validation_tests.rs

When a field is labeled with `#[serde(default)]` it means that if that field is not present, it is populated using the `Default` impl for the field's type:
```rust
#[derive(Serialize, Deserialize, Clone, Debug)]
struct Foo {
#[serde(default)]
bar: Bar,
}
Foo { bar: Bar::default() }
```
This is not the behaviour we want, however. We want fields that have not been supplied to be populated with their value from the `Default` impl of the type they are part of:
```rust
Foo { bar: Foo::default().bar }
```
Implementing this manually requires a lot of boilerplate -- each field needs to have an associated function that returns its default value:
```rust
#[derive(Serialize, Deserialize, Clone, Debug)]
struct Foo {
#[serde(default = "Foo::__default_bar")]
bar: Bar,
}
```
So this PR introduces an …

[pick #18347][GraphQL] Fix bug where config types "zero out" fields not in TOML

---

crates/sui-core/src/traffic_controller/metrics.rs
crates/sui-core/src/traffic_controller/mod.rs

As in title (and code comments)
Existing tests
---

[TrafficControl] Make blocklist clearing periodic; Metrics improvements

---

crates/sui-types/src/effects/mod.rs
crates/sui-types/src/message_envelope.rs
crates/sui-types/src/transaction.rs

The trait is never used for effects either.
CI
---

Fully remove VersionedProtocolMessage

---

external-crates/move/crates/move-model/src/builder/module_builder.rs

Fix an issue in the Move Model module builder where it was trying to handle macro funs before they were translated.
External test.

[move] Fix move model module builder for macros

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/transfer_to_object_tests.rs
crates/sui-single-node-benchmark/src/single_node.rs

This provides a small optimization for sequential execution and/or catchup, and will simplify the job of preventing equivocation on effects when WB cache is enabled.

Remove effects signing from execution path

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/checkpoints/mod.rs

The main behavior change caused here is that we will no longer store signatures of certificates that arrive via consensus. However, once a certificate has been committed in consensus, there is little need for quorum driver to be able to obtain a certificate via the `transaction` API

Only store cert signatures for certs handled by AuthorityServer

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-core/src/traffic_controller/policies.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-json-rpc/src/axum_router.rs
crates/sui-types/src/traffic_control.rs
crates/test-cluster/src/lib.rs

This PR redefines spam in the context of traffic controller as any request type that does not consume gas. There are two such categories that have bee considered so far - read api requests and transaction execution requests that do not invoke the vm (which, to my knowledge, should only happen on submitting a certificate for an already executed transaction, at which point all validators simply read and return the effects). Both cases are hadled here.
Fixed existing tests to exercise the new logic
--- …

[TrafficController] correctly categorize spam

---

Cargo.lock
crates/sui-core/src/unit_tests/move_package_publish_tests.rs
crates/sui-e2e-tests/tests/snapshot_tests.rs
crates/sui-framework/build.rs
crates/sui-move-build/Cargo.toml
crates/sui-move-build/src/lib.rs
crates/sui-move/src/build.rs
crates/sui-package-management/Cargo.toml
crates/sui-package-management/src/lib.rs
crates/sui-source-validation-service/src/lib.rs
crates/sui/src/client_commands.rs
crates/sui/src/client_ptb/builder.rs
crates/sui/tests/cli_tests.rs
sdk/typescript/test/e2e/multisig.test.ts
sdk/typescript/test/e2e/utils/setup.ts

This PR adds automated address management support for `sui client publish` and `sui client upgrade`. The `chain_id` is resolved early in sui commands and propagated down where published ID resolution is needed.
High-level:
- If a package contains a `Move.lock` that contains info to support a package upgrade, then that is used, and a user does not have to (nor should they) maintain a `published-at` address in their `Move.toml`.
- If a package does _not_ have any `Move.lock` information to support a package upgrade, we will still fallback to `Move.toml` as we do today. Nothing changes.
- If a package has both a `Move.lock` and `Move.toml`, then the `Move.lock` will be used (the user is free to delete `published-at` in their `Move.toml`). Caveat: If a published address is in both of these …

move: support automated address management

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/metrics.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-core/src/traffic_controller/policies.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-json-rpc/src/axum_router.rs
crates/sui-types/src/traffic_control.rs
crates/test-cluster/src/lib.rs

CP https://github.com/MystenLabs/sui/pull/18396 and https://github.com/MystenLabs/sui/pull/18324
---

Cp traffic control changes

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/checkpoints/checkpoint_executor/metrics.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/state_accumulator.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-node/src/lib.rs
crates/sui-single-node-benchmark/src/single_node.rs

CP https://github.com/MystenLabs/sui/pull/18281
---

Cp accum per epoch component

---

crates/sui-bridge-indexer/src/latest_eth_syncer.rs
crates/sui-bridge/src/lib.rs
docker/sui-tools/Dockerfile

This change makes the exponential backoff to duration longer hence reduce the amount of queries we send to eth providers.
---

[bridge indexer] increase the max elapsed time for the eth query retry loops

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/state_accumulator.rs

Create new epoch flags for state accum v2, since the old one was already written in some places. Also fix chain-specific logic

Fix epoch flag logic for state accum v2

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/state_accumulator.rs

Create new epoch flags for state accum v2, since the old one was already
written in some places. Also fix chain-specific logic
Cherry pick of #18448

[Cherry-pick] Fix epoch flag logic for state accum v2 (#18448)

---

crates/sui-framework/packages/move-stdlib/sources/option.move
crates/sui-framework/packages/move-stdlib/tests/option_tests.move

Adds macros for option, currently, contains `do` and `destroy` (identical).
Features tests.
---

[stdlib] Adds macros for option

---

scripts/release_notes.py

When merging a PR, we can either use `squashed` or `rebase`.
Before, our release note script supports `squashed` commit only, this change will add support to `rebase` PR as well.
The downside of this is it might take a bit longer to run given that we'll need to send a HTTP request to Github API if it's not a squashed commit. But given this script won't be run more than once a week, it's a good tradeoff.
`GITHUB_TOKEN=<my_PAT> python ./scripts/release_notes.py generate 9e2be6ad4185563ecd98bf35abfe92b86a0b280f 1428c71346045112c7adb1a316365c5cba325d9b`
(all the release notes from `releases/sui-v1.27.0-release` to `releases/sui-v1.28.0-release` branch) now shows @bmwill 's https://github.com/MystenLabs/sui/pull/18099
---
Check each box that your changes affect. If none of the boxes relate to …

support generating notes of merged PRs with rebase

---

examples/move/transfer-to-object/common/Move.toml
examples/move/transfer-to-object/owned-no-tto/Move.toml
examples/move/transfer-to-object/shared-no-tto/Move.toml
examples/move/transfer-to-object/shared-with-tto/Move.toml

These started failing after some new macros landed, and we should be depending on the local framework and not devnet for them.
CI

[move examples] Depend only on local framework not devnet for examples

---

crates/sui-bridge-indexer/src/eth_worker.rs
crates/sui-bridge-indexer/src/latest_eth_syncer.rs
crates/sui-bridge/src/eth_client.rs
crates/sui-bridge/src/types.rs

in `get_events_in_range` it issues extra queries to get `log_index_in_tx`. Indexer does not need this info. This PR adds `get_raw_events_in_range` and `RawEthLog` to replace that for indexer.
---

[bridge indexer] add get_raw_events_in_range for indexer to reduce # of eth queries

---

external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs
external-crates/move/crates/move-analyzer/src/analyzer.rs
external-crates/move/crates/move-analyzer/src/compiler_info.rs
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/context.rs
external-crates/move/crates/move-analyzer/src/inlay_hints.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/enums.exp
external-crates/move/crates/move-analyzer/tests/enums.ide
external-crates/move/crates/move-analyzer/tests/enums/Move.toml
external-crates/move/crates/move-analyzer/tests/enums/sources/int_match.move
external-crates/move/crates/move-analyzer/tests/enums/sources/long_enum.move
external-crates/move/crates/move-analyzer/tests/enums/sources/mut_match.move
external-crates/move/crates/move-analyzer/tests/enums/sources/nested_guard.move
external-crates/move/crates/move-analyzer/tests/enums/sources/nested_match.move
external-crates/move/crates/move-analyzer/tests/enums/sources/struct_match.move
external-crates/move/crates/move-analyzer/tests/enums/sources/variant_match.move
external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs
external-crates/move/crates/move-compiler/src/shared/files.rs

This PR adds enums support to the Move analyzer. 
In this PR, I also sneaked a fix for symbols merging, which was not very robust when multiple packages are built within the same IDE instance. It's much more robust to keep symbols on the per-package basis, even if it's more memory-intensive.
All existing and newly added tests must pass.

[move-ide] Added support for enums

---

external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs

This is a workaround for an issue with IDE caching pre-compiled binaries which do not include source code needed for macro expansion. It's only a workaround to avoid `move-analyzer` crashing rather than a proper fix.

[move-ide] Macro expansion crash workaround

---

external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/editors/code/src/context.ts
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/inlay_hints.rs

This PR fixes a problem with inlay type hints introduced in a previous PR (https://github.com/MystenLabs/sui/pull/18124)
Not only inlay type hints could no longer be disabled, they were also displayed in the wrong position.
This PR also changes the `move-analyzer` binary installation process to enable the bundled version overwriting the locally installed one if they both have the same version but different commit sha. This allows a `move-analyzer` fix to be pushed with the new version of the extension without bumping `move-analyzer`'s version number (which is difficult as it's really the Sui release version number)
Tested that the installation procedure works as expected, that the inlay type hints are displayed correctly, and that they can be enabled/disabled

[move-ide] Fixed inlay type hints

---

consensus/core/src/subscriber.rs
crates/sui-core/src/checkpoints/checkpoint_output.rs
crates/sui-core/src/checkpoints/metrics.rs
crates/sui-core/src/checkpoints/mod.rs

During catchup in mysticeti if the validator was down for long periods of time we will see a large number of checkpoint signatures start to get [backlogged](https://metrics.sui.io/goto/HgmncvwSR?orgId=1) and then submitted to consensus quickly after the node has caught up. This will cause the block size to increase in consensus and then a variance in the distribution of those blocks across the network leading to a round rate dip. This PR will skip submitting checkpoint signatures when checkpoint is already certified to mitigate the issue and we will look into properly handling block size variance in a separate PR
Recreated the issue and tested the fix in private-testnet

Skip submitting checkpoint signatures when checkpoint is already certified

---

.github/workflows/github-issues-monitor.yml
.github/workflows/labeler.yml

The external PR notifier does not get triggered properly, so moved it to the labeler workflow which seems to get triggered every single time an external PR is opened.
---

[CI] Fix github external prs workflow

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/test_utils.rs

These changes ensure that brew can compile our code to release `sui` binary, and similarly, that `cargo install [..] sui --branch testnet` does not break. We need this to go with the testnet release today.
---

[indexer] Fix indexer to compile for Rust 1.75

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/mod.rs

With the writeback cache enabled, a validator can lose execution outputs when restarting, if they have not yet been committed to disk. But the validator may have returned signed effects for those transactions to users. If they have done so, we must be sure we do not produce differing outputs when re-executing any such transaction. (The most likely way this would happen would be due to switching to an upgraded binary that changes execution in some way).

Prevent effects equivocation

---

crates/sui-indexer/README.md
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/test_utils.rs

These changes ensure that brew can compile our code to release `sui` binary, and similarly, that `cargo install [..] sui --branch testnet` does not break. We need this to go with the testnet release today.
---

[cherry-pick][indexer] Cherry-pick to `v1.28.0-release` branch: Fix indexer to compile for Rust 1.75 (#18490)

---

external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
external-crates/move/crates/move-compiler/src/naming/ast.rs
external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/src/typing/macro_expand.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_check/naming/partially_invalid_binding_with_usage.exp
external-crates/move/crates/move-compiler/tests/move_check/naming/partially_invalid_binding_with_usage.move

Fix a crash (now ICE) in the compiler that occurred due to how naming erased invalid `lvalue` forms.
Also modifies `diagnostics` to be better-behaved when errors without locations are reported (e.g., due to `sui_mode` implicits).
Added a new test with updated output.
---

[move] Fix crash

---

docs/content/concepts/sui-move-concepts/packages.mdx
docs/content/concepts/sui-move-concepts/packages/automated-address-management.mdx
docs/content/concepts/sui-move-concepts/packages/upgrade.mdx
docs/content/guides/developer/nft/asset-tokenization.mdx
docs/content/sidebars/concepts.js
docs/site/vercel.json

Adds docs that reflect the functionality in https://github.com/MystenLabs/sui/pull/17995.
I just wanted to get the bulk of documentation for automated address management out, which is this PR. The main addition is a page on `Automated Address Management`.
Some nitty gritty:
Coming up in a PR soon™️, the need for manipulating `[addresses]` will go away with automated address management and that will be reflected in the docs as well. In the interest of reflecting the current functionality (post https://github.com/MystenLabs/sui/pull/17995 merge), this PR preserves the instructions that go along with upgrading and setting `0x0` in `[addresses]`. I've carved out tabs in the `Upgrading Packages` doc section to separate steps with `Automated Addresses` versus (legacy) `Manual Addresses`:
N/A …

docs: automated address management

---

crates/sui-bridge-indexer/config.yaml
crates/sui-bridge-indexer/src/config.rs
crates/sui-bridge-indexer/src/lib.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-indexer/src/migrations/2024-06-25-112132_smart_progress_store/down.sql
crates/sui-bridge-indexer/src/migrations/2024-06-25-112132_smart_progress_store/up.sql
crates/sui-bridge-indexer/src/models.rs
crates/sui-bridge-indexer/src/postgres_manager.rs
crates/sui-bridge-indexer/src/schema.rs
crates/sui-bridge-indexer/src/sui_checkpoint_ingestion.rs
crates/sui-bridge-indexer/src/sui_worker.rs
crates/sui-data-ingestion-core/src/executor.rs

This PR adds ability to the indexer to ingest checkpoint data in a smarter way, we added a task to ingest "live" data and a separate task to backfill historical data, the historical data are ingested using a range based method and the lot size of each task can be configured, this allow us to Ingest the "latest" historical data first.  
---

[bridge-indexer] - smarter checkpoint backfill 

---

crates/sui-benchmark/tests/simtest.rs

By probabilistically setting the mode to txn count based congestion control mode.
---

Add count based congestino control mode in stress test

---

.github/workflows/labeler.yml

This gets triggered when changes happen on a PR, so just force it to only dispatch the workflow when a PR is opened. That's what we want anyway for someone to label it and tag it to the right person.
Sorry for the churn @after-ephemera 
---

[CI] Only trigger this on pull request being opened

---

crates/sui-core/src/authority/authority_store_pruner.rs
scripts/simtest/simtest-run.sh

- Print TIMEOUT errors when test fails
- Shorten minimum pruning tick interval to speed up tests

Speed up object_pruning_test, print TIMEOUT errors in simtest nightly

---

external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/inlay_hints.rs
external-crates/move/crates/move-analyzer/tests/inlay-hints/Move.toml
external-crates/move/crates/move-analyzer/tests/inlay-hints/sources/type_hints.move

What the title says. I decided to go for by-hand tests rather than add a framework similar to what we use for symbols as we really only need a rather limited number of tests and they will be different for different types of inlay hints (e.g. for upcoming parameter hints) so by-hand tests seem to be more cost-efficient.
All new and existing tests must pass

[move-ide] Added tests for inlay type hints

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/ci/image.rs

after adding the support for specifying hardware request in infra-metadata-servcie, we could now allow this from suiop CLI as well.
`suiop ci image build --repo-name=sui --dockerfile=docker/sui-node/Dockerfile --ref-type=branch --ref-val=testnet --build-mode=beast --build-args="PROFILE=release" --repo-region=us-west1 --image-name=sui-node`
```
Requested built image for repo: sui, ref: branch:testnet, dockerfile: docker/sui-node/Dockerfile, image: sui-node
Build Job Status: Pending
Build Job Name: sui-ywgdt
Build Job Start Time: 2024-07-03 14:58:48
```
then in k8s, hardware request is actually beast mode 
```
Args:
--dockerfile=docker/sui-node/Dockerfile
--context=git://github.com/MystenLabs/sui.git#refs/heads/testnet
--build-arg=PROFILE=release
State:          Running
Started:      Wed, …
```

[suiop] allow specifying CPU/RAM/DISK requests and build args

---

docker/sui-network/Dockerfile
docker/sui-network/docker-compose-antithesis.yaml

Allows the antithesis docker-compose network to be run with two different sui-node images, with half of the validators running one image and half running the other.

Changes to support multi-version tests in antithesis

---

consensus/core/src/authority_service.rs

Init the metric with 0 on boot otherwise it won't get reported at all making metrics harder to calculate
CI
---

[fix] report subscribed_peers as 0 on boot

---

Cargo.lock
crates/sui-core/src/unit_tests/move_package_publish_tests.rs
crates/sui-move-build/src/lib.rs
crates/sui-package-management/Cargo.toml
crates/sui-package-management/src/lib.rs
crates/sui/src/client_commands.rs
crates/sui/tests/cli_tests.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-cli/src/base/info.rs
external-crates/move/crates/move-cli/src/base/test.rs
external-crates/move/crates/move-cli/src/sandbox/commands/test.rs
external-crates/move/crates/move-package/src/lib.rs
external-crates/move/crates/move-package/src/lock_file/schema.rs
external-crates/move/crates/move-package/src/resolution/resolution_graph.rs
external-crates/move/crates/move-package/tests/package_hash_skips_non_move_files.rs
external-crates/move/crates/move-package/tests/test_additional_addresses.rs
external-crates/move/crates/move-package/tests/test_runner.rs

This PR enables automation of package addresses so that users don't need to fiddle with the `[addresses]` section when publishing/upgrading a package. However, if they are accustomed to the previous habits of changing `[addresses]`, they can still do so: the PR is backwards compatible with the "old way" described in the docs, which we'll keep during transition. In that case, though, they can't benefit from publishing to multiple chains.
There are two key implementation changes:
- **Part 1** (see inline comment): For named addresses in `[addresses]` we resolve the original published ID from the `Move.lock` if it exists there under some `chain-id`. 
- Crucially, we assume that a key/value such as `foo = 0x0` with the special value of `0x0` implies that `foo` is the current package for which …

move: manage [addresses] automatically on publish / upgrade

---

crates/sui/src/client_commands.rs

In https://github.com/MystenLabs/sui/pull/18470 I made a change that uses the `package_path` before canonicalizing, causing relative paths to the package to not work on `publish`.
This PR reorders the statements to canonicalize the path before any uses.
Tested locally, will follow up immediately with a CLI test for relative paths in a separate PR--want to plug this first.
---

move: canonicalize path before all uses of package path

---

crates/sui/src/client_commands.rs

Strengthen the error handling of `sui client faucet` command.
---

[CLI] Fix faucet errors when server returns a 503

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json
crates/sui-rest-api/Cargo.toml
crates/sui-rest-api/openapi/elements.html
crates/sui-rest-api/openapi/openapi.json
crates/sui-rest-api/openapi/swagger.html
crates/sui-rest-api/src/accounts.rs
crates/sui-rest-api/src/checkpoints.rs
crates/sui-rest-api/src/coins.rs
crates/sui-rest-api/src/committee.rs
crates/sui-rest-api/src/health.rs
crates/sui-rest-api/src/info.rs
crates/sui-rest-api/src/lib.rs
crates/sui-rest-api/src/objects.rs
crates/sui-rest-api/src/openapi.rs
crates/sui-rest-api/src/system.rs
crates/sui-rest-api/src/transactions/execution.rs
crates/sui-rest-api/src/transactions/mod.rs
crates/sui-types/src/sui_sdk2_conversions.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/v2/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v2/sui-move-natives/src/test_scenario.rs

This PR introduces an OpenAPI spec for the REST api and hosts the spec and an explorer off of the main rest service. While the spec as introduced in this PR enumerates all of the available endpoints, the documentation, inputs, request and response types for all of the endpoints has not been completed and will be done in a follow up PR. The spec can be explored locally (without the actual backend service) by running:
```
OPENAPI_EXPLORER=1 cargo test -p sui-rest-api openapi_explorer
```
and navigating to `http://127.0.0.1:8000/openapi` in a browser.
The openapi spec is checked-in to the repo and a test exists to ensure that the checked-in version matches what is derived by the service. This allows for subsequent changes to the spec to be reviewed at code review time.
The api spec is still …

rest: create and host openapi spec and explorer

---

external-crates/move/crates/bytecode-verifier-transactional-tests/tests/locals_safety/enum_non_drop_assignment.exp
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/locals_safety/enum_non_drop_assignment.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/double_enum_unpack.exp
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/double_enum_unpack.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/enum_variant_factor.exp
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/enum_variant_factor.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/invalid_enum_ref_unpack.exp
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/invalid_enum_ref_unpack.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/invalid_enum_ref_unpack_loop.exp
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/invalid_enum_ref_unpack_loop.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/valid_enum_ref_unpack.exp
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/valid_enum_ref_unpack.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/valid_enum_unpack_loop.exp
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/valid_enum_unpack_loop.mvir
external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_jump_same_label.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_jump_same_label.mvir
external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_tag_unpack_invalid.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_tag_unpack_invalid.mvir
external-crates/move/crates/move-vm-transactional-tests/tests/enums/unpack_mut_ref_alias.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/unpack_mut_ref_alias.mvir

Adds a number of additional tests for enums. 
These tests test a couple things:
* All variations of "unpack wrong variant at runtime" (by value, mut ref, and immut ref).
* Various incarnations of this (e.g., all switch arms branching to the same branch).
* Various reference tests around unpacking enum variants. 
It's all tests!

[move] Add additional enums tests

---

crates/sui-core/src/state_accumulator.rs

Testing infra surfaced a rare edge case where, if a validator on a newly genesis'ed chain is slow in execution such that the epoch 0 end of epoch checkpoint is proposed before we have executed and accumulated genesis checkpoint, we will panic due to attempting to bootstrap the running root from the previous epoch root state hash, which does not exist in that case.
Note that this is not a critical fix as it only would affect a newly genesis'ed chain.
Existing tests for now
---

[StateAccumulator] Fix genesis edge case

---

crates/sui-graphql-rpc/src/server/builder.rs

Add health endpoint to version routes as well.
---

[GraphQL] Add health endpoint to version routes as well

---

external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package-lock.json
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/editors/code/src/configuration.ts
external-crates/move/crates/move-analyzer/editors/code/src/context.ts
external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs
external-crates/move/crates/move-analyzer/src/analyzer.rs
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/context.rs
external-crates/move/crates/move-analyzer/src/inlay_hints.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/dot_completion.ide
external-crates/move/crates/move-analyzer/tests/enums.ide
external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs
external-crates/move/crates/move-analyzer/tests/inlay-hints/sources/param_hints.move
external-crates/move/crates/move-analyzer/tests/inlay_hints.exp
external-crates/move/crates/move-analyzer/tests/inlay_hints.ide

What the title says. Here is an example:
We also support on-hover for param inlay hints:
The algorithm works in two stages:
- collect information about expressions representing arguments when visiting parsing AST (as that'w when they are still represented as a vector of expressions rather than a single expression as in typed AST)
- find the call's function target when visiting typed AST to be able to combine its signature with argument locations collected in the previous step to generate param hints when they are requested
Also this PR drops by-hand testing for inlay hints and replaces it with an extension of the IDE testing harness
All old and new tests must pass

[move-ide] Added support for param inlay hints

---

crates/sui-cluster-test/src/lib.rs
crates/sui-cluster-test/src/test_case.rs
crates/sui-cluster-test/src/test_case/random_beacon_test.rs
crates/sui-test-transaction-builder/src/lib.rs
sui_programmability/examples/basics/sources/random.move

Was reverted in https://github.com/MystenLabs/sui/pull/18585 since the wrong check was committed 
(`if Self::is_beacon_enabled(wallet_context).await` instead of `if !Self::is_beacon_enabled(wallet_context).await`).
[Confirmed](https://github.com/MystenLabs/sui-operations/actions/runs/9870085557/job/27255754698) that the problem was fixed.

Add back the simple test of Random to cluster-test
