crates/sui-core/src/traffic_controller/mod.rs, crates/sui-e2e-tests/tests/traffic_control_tests.rs, crates/sui-types/src/traffic_control.rs
Simplify killswitching to simply touch the file, as this does not consume disk space.
Integration and unit tests
---
=> [TrafficController] Simplify killswitch mechanism

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_44.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_44.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_44.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Running on testnet for 6 weeks now. Turning it on mainnet.
---
=> Turn on consensus fork detection on mainnet

crates/sui-framework/packages/sui-framework/sources/random.move, sui-execution/latest/sui-move-natives/src/lib.rs, sui-execution/latest/sui-move-natives/src/random.rs
=> Rename 2 testing only functions in random.move

scripts/execution_layer.py
- Fix bug introduced in #17164
- Made a new cut and built 
---
=> [fix] Fix execution_layer.py

Cargo.lock, crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/epoch/randomness.rs, crates/sui-network/Cargo.toml, crates/sui-network/src/randomness/mod.rs
- Failure to send partial sigs
- Failure to participate in DKG
=> Add simtests for random beacon failures

crates/sui-network/src/randomness/builder.rs, crates/sui-network/src/randomness/mod.rs
- Verify that we receive the right share ids
- warn instead of debug level logging
---
=> Beacon: more verifications

docs/content/snippets/openid-providers.mdx
Apple as an openid provider is now supported in both testnet and mainnet for zklogin. Updating the openid provider table to show affirmative for those two columns. Did not see any other mention of apple only being available in devnet.
---
=> [docs] Updated apple support

.github/workflows/narwhal.yml, .github/workflows/simulator-nightly-mysticeti.yml, .github/workflows/simulator-nightly-narwhal.yml, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_44.snap
This configuration has been running in CI and private testnet for awhile.
CI
Private testnet.
---
=> [Consensus] enable switching consensus between epochs in tests and devnet

apps/wallet/src/shared/analytics/ampli/index.ts, apps/wallet/src/ui/app/hooks/useFileExtensionType.ts, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs, sui-execution/v2/sui-adapter/src/programmable_transactions/context.rs
=> chore: Fix the typos

docs/content/concepts/sui-move-concepts/conventions.mdx
I updated the Add section titles for the Move 2024 conventions to be up to date with the latest changes.
It does not require any tests.
---
=> [DOCS] :memo: fix: move 2024 conventions

deny.toml
=> Remove out of dated RUSTSEC

deny.toml
I don't think there is value in blocking CI while upgrading the underlying library, which could take more time.
CI
---
=> [CI] unblock RUSTSEC-2024-0336

crates/sui-core/src/authority_aggregator.rs, crates/sui-core/src/quorum_driver/mod.rs, crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
If some validator already have the certificate for a transaction, this was likely already submitted before, and in this case we should not record it as settlement finality.
To do this we add a new field to process transaction results with certs.
Added a test.
---
=> [AuthAgg] Do not record settlement finality for old certs

crates/sui-move/src/new.rs
Patches const in "expected_failure" to be prefixed with `::`
Manually. 
=> [Move CLI] Fixes initial setup

deny.toml
=> [bridge] Cherry pick 17252

consensus/core/src/core.rs, consensus/core/src/metrics.rs
=> [Consensus] rename metric

docs/content/guides/operator/validator-tasks.mdx
Increasing network buffer sizes are pretty important for supporting high throughput with low latency.
n/a
---
=> [Doc] add instructions for setting network buffer

crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-node/src/lib.rs, crates/sui-types/src/message_envelope.rs
These seem no longer used/needed.
Let me know if we want to keep them somewhere, I could move them to a separate file.
CI
---
=> Delete unused jwk bytes

crates/sui-framework/build.rs, crates/sui-framework/published_api.txt
Generate a human-readable file containing all structs and functions that will be published with the framework. This makes it easier to track when functions/structs are added or removed. The output file is not meant to capture the full signature, but simply be an easy way to determine if/when a new function or struct is added. 
Built and checked the output file.
=> [sui-framework][tooling] Add human-readable published-api file

crates/sui/src/sui_commands.rs
Fixes a typo in the config prompt (Tevnet -> Testnet)
No tests needed.
---
=> [cli] fix typo in config prompt

docs/content/guides/developer/getting-started/sui-install.mdx
Differentiating the titles for various methods of installation further.
:eyes:
---
=> [Docs] Clarify headings in Installation Guide

consensus/core/src/block.rs, consensus/core/src/core.rs
Logic to generate and process misbehavior reports will be added later.
CI
---
=> [Consensus] types for misbehavior reporting

crates/sui-core/src/authority_server.rs
The errors shown here should be skipped and logged if encountered, not returned to the requestor
---
=> [TrafficControl] Safer error handling

crates/sui-config/src/p2p.rs
=> Multiply all p2p network concurrency limits by 20

consensus/core/src/authority_node.rs, consensus/core/src/lib.rs, consensus/core/src/synchronizer.rs, crates/sui-core/src/consensus_manager/mysticeti_manager.rs, crates/sui-protocol-config/src/lib.rs
From experiments in private testnet, using tonic streaming seems to improve throughput and reduce latency on nodes with bad network conditions. The plan is to enable Tonic in unit tests and devnet, after 1.24 is cut.
CI
---
=> [Consensus] add protocol config for network type

consensus/config/src/parameters.rs, consensus/config/tests/snapshots/parameters_test__parameters.snap
This limits round rate to ~10/s.
CI
---
=> [Consensus] increase min round delay to 100ms

docs/content/standards/display.mdx
Fixed the display example to move 2024 grammar
---
=> [docs] Fixed the display example to move 2024 grammar

crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-faucet/src/faucet/simple_faucet.rs, crates/sui-source-validation-service/tests/tests.rs, crates/sui/src/client_commands.rs, crates/sui/tests/cli_tests.rs
This PR groups several flags and options for several commands, to reduce code duplication. 
Existing tests
---
=> [cli][easy] Refactor global options for several commands

sui_programmability/examples/crypto/sources/ec_ops.move
=> Update an example in ec_ops.move

consensus/core/src/core.rs, consensus/core/src/metrics.rs, consensus/core/src/threshold_clock.rs
This can help identify the authorities causing propose delays and the magnitudes of the delays.
CI
---
=> [Consensus] measure delays caused by leaders when proposing

crates/sui-analytics-indexer/src/package_store.rs, crates/sui-graphql-rpc/src/data.rs, crates/sui-graphql-rpc/src/data/package_resolver.rs, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/types/checkpoint.rs, crates/sui-graphql-rpc/src/types/epoch.rs, crates/sui-graphql-rpc/src/types/move_package.rs, crates/sui-light-client/src/main.rs, crates/sui-package-resolver/src/error.rs, crates/sui-package-resolver/src/lib.rs
Use a DataLoader to serve fetches from the package store, so that when concurrent threads request the same package be fetched, we can batch them and avoid multiple round trips to the DB.
Try the following query before and after the change:
```graphql
query {
owner(
address: "0x029170bfa0a1677054263424fe4f9960c7cf05d359f6241333994c8830772bdb"
) {
dynamicFields(first: 50) {
pageInfo {
hasNextPage
endCursor
}
nodes {
name {
type {
repr
}
json
}
value {
... on MoveValue {
type {
repr
}
json
}
... on MoveObject {
contents {
json
type {
repr
}
}
}
}
}
}
}
}
```
Before this change, the above request made about 90 DB roundtrips, and after the change, it takes about 5, not including checkpoint watermark fetches.
--- …
=> [pick][GraphQL/DataLoader] Data Loader for Package Resolver (#17298)

crates/sui-core/src/checkpoints/mod.rs
=> Fix bug in filtering for end-of-epoch txns

crates/sui-sdk/README.md
Update README.md to include the autogenerated crate doc
No test needed
---
=> [sui-sdk] Update README.md to include the autogenerated crate doc

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_44.snap
Rolling out Mysticeti to testnet.
CI
---
=> [Consensus] switch between Narwhal and Mysticeti in testnet

.changeset/three-windows-heal.md, sdk/docs/pages/typescript/utils.mdx, sdk/typescript/src/client/client.ts, sdk/typescript/src/utils/index.ts, sdk/typescript/src/utils/suins.ts, sdk/typescript/test/unit/utils/suins.test.ts
=> Add new utils and options for handling new SuiNS name format

crates/sui-framework/docs/sui-framework/kiosk.md, crates/sui-framework/docs/sui-framework/transfer_policy.md, crates/sui-framework/docs/sui-framework/zklogin_verified_id.md, crates/sui-framework/docs/sui-framework/zklogin_verified_issuer.md, crates/sui-framework/packages/sui-framework/sources/crypto/group_ops.move, crates/sui-framework/packages/sui-framework/sources/crypto/zklogin_verified_id.move, crates/sui-framework/packages/sui-framework/sources/crypto/zklogin_verified_issuer.move, crates/sui-framework/packages/sui-framework/sources/kiosk/kiosk.move, crates/sui-framework/packages/sui-framework/sources/kiosk/transfer_policy.move, crates/sui-framework/packages/sui-framework/sources/test/test_scenario.move, crates/sui-framework/packages/sui-framework/tests/linked_table_tests.move, crates/sui-framework/packages/sui-framework/tests/token/token_config_tests.move
Fix typos in `crates/sui-framework/packages/sui-framework`
---
=> fix typos of comments and const name  in sui-framework packages

docs/content/guides/developer/app-examples/weather-oracle.mdx
Update docs for weather oracle example to use Move 2024 syntax
:eyes:
---
=> [move-2024][docs] Update weather-oracle.mdx to use move 2024 syntax

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.25.0 Version bump

docs/content/references/contribute/mdx-components.mdx, docs/site/vercel.json
There was a forward that shouldn't have been there.
---
=> [docs][easy] Removing forward

docs/content/references/sui-sdks.mdx
Use similar terminology in their respective title cards to make it clear that these are different pieces/kinds of documentation for the same thing.
:eyes:
---
=> [Docs/SDK] Link Rust SDK and its auto-generated docs

consensus/core/src/block_manager.rs, consensus/core/src/test_dag_builder.rs, consensus/core/src/tests/universal_committer_tests.rs
A small refactoring in block manager tests to use the `DagBuilder` 
CI
---
=> [Consensus 2.0] small refactoring block manager tests

docs/site/vercel.json
It seems to be circular.
Vercel
---
=> [Docs] Remove concepts/graphql redirect

Cargo.lock, crates/sui-json-rpc-tests/Cargo.toml, crates/sui-json-rpc-tests/tests/transaction_tests.rs, crates/sui-json-rpc/src/indexer_api.rs, crates/sui-transaction-builder/src/lib.rs
title
CI with added sim test
---
=> json rpc: de-dup intermediate digests in query_transaction_blocks

crates/sui-core/src/authority/shared_object_version_manager.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/unit_tests/transaction_tests.rs, crates/sui-types/src/signature_verification.rs, crates/sui-types/src/transaction.rs, crates/sui-types/src/unit_tests/messages_tests.rs, crates/sui-types/src/unit_tests/utils.rs, crates/sui/src/client_commands.rs
=> transaction: enforce the correct Intent for TransactionData

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-node/src/lib.rs
This is something I've wanted to do for a while, and I decided it will make it simpler to handle the comments on #17191
=> Store the entire NodeConfig in AuthorityState

crates/sui-benchmark/src/workloads/shared_object_deletion.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs, narwhal/executor/src/subscriber.rs
- Reduce the severity of some error logs, which seem a bit noisy in simtests.
- Log receiving checkpoint from state sync at info level, to make debugging simtest panic easier.
CI
---
=> [Simtest] adjust log levels for a few messages

consensus/core/src/authority_service.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_45.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_45.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_45.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, narwhal/primary/src/certifier.rs
Start testing tonic network more, before we decide if it should become the default.
CI
---
=> [Consensus] use tonic in tests and devnet

crates/sui-core/src/authority_server.rs, crates/sui-core/src/traffic_controller/mod.rs, crates/sui-core/src/traffic_controller/policies.rs, crates/sui-e2e-tests/tests/traffic_control_tests.rs, crates/sui-json-rpc/src/axum_router.rs
CP https://github.com/MystenLabs/sui/pull/17377
---
=> Cherry-pick 17377 (Naive traffic sim and deadlock fix)

.github/workflows/rust.yml, Cargo.lock, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-rpc/Cargo.toml
Bump Sui GraphQl version: `v2024.7.0`
=> Bump Sui GraphQl version: `v2024.7.0`

narwhal/executor/src/state.rs
=> Remove end_for_commit

.github/actions/ts-e2e/action.yml, .github/workflows/e2e.yml, crates/sui-indexer/src/lib.rs, sdk/typescript/package.json
=> [cherry-pick][graphql] Cherry pick hotfix to release

.github/workflows/release.yml
Add sui debug builds
https://github.com/MystenLabs/sui/actions/runs/8902476941/job/24448446006
=> Add sui debug builds

.github/workflows/release.yml
Fix upload path for tar ball
https://github.com/MystenLabs/sui/actions/runs/8903048046
=> Fix upload path for tar ball

README.md
As in title
Fixes #17436 
:eyes:
---
=> [Docs] Update link to reseach in README.md

.github/workflows/trigger-builds.yml
Only trigger graphql artifact builds for graphql branches
👀
=> Only trigger graphql artifact builds for graphql branches

.github/workflows/github-issues-monitor.yml
Fix broken link in the workflow.
---
=> [ci] Fix workflow

docs/content/guides/developer/getting-started.mdx
Updating ide and plugin list. 
👀 
---
=> [docs][easy] Updating IDE list

crates/sui-bridge/src/e2e_tests/test_utils.rs, crates/sui-bridge/src/events.rs, crates/sui-bridge/src/node.rs, crates/sui-bridge/src/types.rs, crates/sui-types/src/bridge.rs
This PR adds events for committee.move in bridge node.
tests
---
=> [bridge 76/n] add events for committee.move

.github/workflows/trigger-builds.yml
=> Fix conditionals

docs/content/guides/developer/app-examples/tic-tac-toe.mdx
Updates the code in the docs to reflect #17327 and #17091 
:eyes:
---
=> [move-2024][docs] Update tic-tac-toe.mdx with Move 2024 methods

external-crates/move/crates/move-compiler/tests/development/enums/matching/const_visibility.exp, external-crates/move/crates/move-compiler/tests/development/enums/matching/const_visibility.move, external-crates/move/crates/move-compiler/tests/development/enums/matching/enum_visibility.exp, external-crates/move/crates/move-compiler/tests/development/enums/matching/enum_visibility.move, external-crates/move/crates/move-compiler/tests/development/enums/matching/struct_visibility.exp, external-crates/move/crates/move-compiler/tests/development/enums/matching/struct_visibility.move
This adds tests to ensure visibility is correctly enforced for matching
New tests
---
=> Add match visibility tests

crates/sui-framework/packages/sui-framework/tests/crypto/bls12381_tests.move
=> More tests of MSM

crates/sui-bridge/src/tools/cli.rs, crates/sui-bridge/src/tools/mod.rs, crates/sui/src/validator_commands.rs
added a new command to bridge tool cli to register as a committee member
manually tested on bridgenet
---
=> [native-bridge] - committee registration cli tool

crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/authority_server.rs, crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/consensus_validator.rs, crates/sui-core/src/scoring_decision.rs, crates/sui-core/src/transaction_manager.rs
Otherwise validator operators can get confused on if Narwhal is running.
👀
---
=> Rename Narwhal -> consensus for non-Narwhal specific logs

crates/sui/src/client_ptb/ptb.rs
The sender should be the gas object owner when gas is passed, for mutisig txs
Existing tests. Though I should add a test, not sure the best way to add one.
---
=> [cli] Fix sender in CLI PTB

crates/sui/src/client_ptb/ptb.rs
The sender should be the gas object owner when gas is passed.
---
=> [cherry-pick][cli] Cherry pick cli ptb fix

docs/content/concepts/sui-architecture.mdx, docs/content/concepts/sui-architecture/consensus.mdx
I decided to remove most the previous consensus page, because they seem to be confusing.
Only a short overview section is added to replace the previous page. We can include more images later on. Not sure if we want very detailed docs here though, which can be hard to keep updated.
n/a
---
=> [Doc] rewrite consensus section

.github/workflows/cargo-llvm-cov.yml
Instruct oncall to look over the code coverage report.
👀
---
=> Update code coverage notification message

docs/content/guides/developer/sui-101/access-time.mdx
Add info for Mysticeti consensus.
👀
---
=> [Doc] update when time gets updated

docs/content/references/cli/ptb.mdx
Add explanation for passing the types in the CLI PTB.
---
=> [docs] Update ptb.mdx

.github/workflows/github-issues-monitor.yml
This fixes the workflow to produce the correct PR number and user for notifying about external PRs.
---
=> [CI] Fix GitHub issues workflow

docs/content/guides/operator/data-management.mdx
Some validators see to have issues with pruning after epoch change as well.
👀
---
=> [Doc] indicate the pruning config suitable for validators

.github/workflows/github-issues-monitor.yml
Removes typo in the script + fixes an if condition.
---
=> [CI] Fix github issues monitor workflow

sdk/zksend/src/links/utils.ts
* load only assets owned by bag
* fix object type
---
=> [zksend] fix getting assets from transaction

crates/sui-e2e-tests/tests/zklogin_tests.rs
=> fix: reduce epoch duration for test

.github/workflows/rust.yml, crates/sui-tool/src/lib.rs
Fix `mysqlclient-sys` windows cargo build error
https://github.com/MystenLabs/sui/actions/runs/8978802872/job/24659827747?pr=17538
=> Fix `mysqlclient-sys` windows cargo build error

consensus/core/src/authority_node.rs, crates/sui-json-rpc-tests/tests/transaction_tests.rs, crates/sui/tests/cli_tests.rs
simple cleanup to address simtest warnings.
---
=> Suppress simtest warnings

consensus/core/src/commit_syncer.rs, consensus/core/src/dag_state.rs, consensus/core/src/metrics.rs
Improve metrics for tracking the progress of a validator during catching up.
CI
---
=> [Consensus] improve metrics

crates/sui-core/src/authority.rs, crates/sui-core/src/consensus_handler.rs
This helps us understand the size of transactions sent through consensus.
CI
---
=> [Metric] export transaction sizes by transaction kinds

sdk/bcs/README.md, sdk/docs/pages/bcs/index.mdx
=> [docs] fix UID definition in bcs docs

.changeset/light-tables-yawn.md, sdk/docs/pages/typescript/cryptography/multisig.mdx, sdk/typescript/src/multisig/index.ts, sdk/typescript/src/multisig/publickey.ts, sdk/typescript/src/multisig/signer.ts, sdk/typescript/test/unit/cryptography/multisig.test.ts
=> [TS SDK] Add MultiSigSigner class to simplify multisig signing

sdk/move-bytecode-template/src/lib.rs
=> Fix serialize calls in move-bytecode-template

crates/sui-bridge/src/server/mod.rs, crates/sui-framework/docs/bridge/treasury.md, crates/sui-framework/packages/bridge/sources/treasury.move, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Audit feedback around `notional_value`, minor cleanup
Existing tests
---
=> audit feedback

Cargo.lock, crates/suiop-cli/Cargo.toml, crates/suiop-cli/src/cli/pulumi/init.rs
1. trim the spaces from user input when creating new projects
2. set init pulumi envs
tested locally, things are working as expected
---
=> [suiop-cli] minor improvements

.changeset/fluffy-schools-agree.md, sdk/zksend/src/index.test.ts, sdk/zksend/src/links/claim.ts, sdk/zksend/src/links/get-sent-transaction-blocks.ts, sdk/zksend/src/links/list-created-links.ts
=> [zksend] Add support for sponsoring link reclamation

crates/sui-core/src/authority/authority_per_epoch_store.rs
=> DKG: Limit messages size

.changeset/friendly-shrimps-decide.md, pnpm-lock.yaml, sdk/typescript/package.json
=> [sdk] fix gql.tada dependency

crates/sui-framework-tests/src/unit_tests.rs, examples/move/transfer-to-object/common/sources/identified_payment.move, examples/move/transfer-to-object/shared-with-tto/sources/shared_cash_register.move
- Run recursively move tests under examples/
- Update tests
---
=> Run recursively move tests under examples/

docs/content/guides/developer/advanced/randomness-onchain.mdx
=> Beacon: Update links in documentation

.github/workflows/release.yml, Cargo.lock
Remove extra dot from sui.exe path
👀
=> Remove extra dot from sui.exe path

.github/workflows/github-issues-monitor.yml
Moved the logic into another workflow that this one triggers.
---
=> [CI] GitHub issue external prs monitor

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_45.snap
=> feat: enable zklogin inside multisig

.github/workflows/github-issues-monitor.yml
If conditions only work at job level, and not at step level.
---
=> [CI] Github issues & external PRs fix

pnpm-lock.yaml, sdk/docs/package.json
=> Fix npm audit warning for next <13.5.1

consensus/config/src/parameters.rs, consensus/config/tests/snapshots/parameters_test__parameters.snap, consensus/core/src/authority_node.rs, consensus/core/src/commit.rs, consensus/core/src/commit_observer.rs, consensus/core/src/core.rs, consensus/core/src/core_thread.rs, consensus/core/src/dag_state.rs, consensus/core/src/leader_schedule.rs, consensus/core/src/leader_scoring.rs, consensus/core/src/leader_scoring_strategy.rs, crates/sui-core/src/consensus_handler.rs, crates/sui-core/src/consensus_types/consensus_output_api.rs, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_45.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_45.snap
This is the final PR for Leader Scoring & Leader Schedule feature for Mysticeti
https://metrics.sui.io/goto/lkph80LSR?orgId=1
=> [consensus]  Gate scoring feature via protocol config and pass scores to sui for submission

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.26.0 Version bump

crates/sui-indexer/README.md
=> Update readme to run indexer writer with a local tidb

.github/workflows/release.yml
Remove carriage returns on windows platform
👀
=> Remove carriage returns on windows platform

consensus/config/src/parameters.rs, consensus/core/src/base_committer.rs, consensus/core/src/core.rs, consensus/core/src/dag_state.rs, consensus/core/src/leader_schedule.rs, consensus/core/src/leader_scoring.rs, consensus/core/src/leader_scoring_strategy.rs, consensus/core/src/universal_committer.rs, crates/sui-core/src/consensus_adapter.rs
=> [cherrypick] Fix for stuck leader schedule on recovery (#17654)

consensus/core/src/commit.rs, consensus/core/src/core.rs, consensus/core/src/leader_schedule.rs, consensus/core/src/leader_scoring.rs, consensus/core/src/leader_scoring_strategy.rs, consensus/core/src/linearizer.rs, consensus/core/src/test_dag_builder.rs, consensus/core/src/universal_committer.rs
Scoring leader slots that may be skipped can potentially lead to opportunity for malicious behavior. Scoring the leaders that were committed should prevent this.
=> [consensus] Only score committed leaders

consensus/core/src/commit.rs, consensus/core/src/core.rs, consensus/core/src/leader_schedule.rs, consensus/core/src/leader_scoring.rs, consensus/core/src/leader_scoring_strategy.rs, consensus/core/src/linearizer.rs, consensus/core/src/test_dag_builder.rs, consensus/core/src/universal_committer.rs
See https://github.com/MystenLabs/sui/pull/17668 for details
=> [cherrypick] Only score committed leaders (#17668)

consensus/core/src/authority_node.rs, consensus/core/src/commit.rs, consensus/core/src/commit_observer.rs, consensus/core/src/core.rs, consensus/core/src/dag_state.rs, consensus/core/src/leader_schedule.rs, consensus/core/src/leader_scoring.rs, consensus/core/src/leader_scoring_strategy.rs, consensus/core/src/tests/pipelined_committer_tests.rs, consensus/core/src/tests/universal_committer_tests.rs, consensus/core/src/universal_committer.rs, crates/sui-core/src/consensus_types/consensus_output_api.rs, package.json
=> Cherry pick 17673 & 17667

sdk/bcs/README.md, sdk/docs/pages/bcs/index.mdx
fix ts sdk doc error, for serializing a map type to bcs format.
---
=> [docs] fix ts sdk doc error

.github/workflows/release.yml
Check for binary list file before reading it
https://github.com/MystenLabs/sui/actions/runs/9066746062/job/24910342419
=> Check for binary list file before reading it

crates/sui-e2e-tests/tests/protocol_version_tests.rs
=> Remove unused import in simtest

docs/content/references/cli/client.mdx
Adds a few more examples to sui client.
---
=> [docs] Add more examples to sui client

crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs
cherrypick from https://github.com/MystenLabs/sui/pull/17685
---
=> fix: cherrypick use derived author for zklogin verify endpoint

crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs
=> fix: cherrypick derived author check for zklogin signature verify

docs/content/concepts/transactions/sponsored-transactions.mdx
Fixes https://github.com/MystenLabs/sui/issues/17640
---
=> [docs] Update sponsored-transactions.mdx

crates/sui-indexer/README.md
minor fix of TiDB indexer README
---
=> TiDB indexer: minor README change

docs/content/guides/developer/app-examples/plinko.mdx
This diretly replaces the plinko code with its Move 2024 equivalent.
This is copy/pasted from this PR and should not be landed until that PR is: https://github.com/MystenLabs/plinko-poc/pull/74 
:eyes:
---
=> [move-2024][docs] Update plinko.mdx

crates/sui-indexer/src/db.rs, crates/sui-indexer/src/indexer.rs
on a prev investigation on staging, we were unsure if the issue was on remote store url or DB connection.
improve the loggings a bit here.
---
=> indexer logging: DB connection & reset info

external-crates/move/crates/move-model-2/src/compiled_model.rs, external-crates/move/crates/move-model-2/src/lib.rs, external-crates/move/crates/move-model-2/src/source_model.rs
first commit: build failed I assume running docgen. It still fails ;) but now on the `todo` for the docs.
second commit: introduces a compiled model. Things are not hooked up yet but they will as soon as I sync with people
hope and faith
---
=> couple of fixes and compile model

examples/move/crypto/bls_signature/Move.toml, examples/move/crypto/bls_signature/sources/example.move, examples/move/crypto/elgamal/Move.toml, examples/move/crypto/elgamal/sources/example.move, examples/move/crypto/elgamal/tests/example_tests.move, examples/move/crypto/ibe/Move.toml, examples/move/crypto/ibe/sources/example.move, examples/move/crypto/ibe/tests/example_tests.move
Updated the examples from `sui_programmability/examples/crypto/sources/ec_ops.move`.
---
=> Update Move examples of EC operations

consensus/config/src/parameters.rs, consensus/config/tests/snapshots/parameters_test__parameters.snap, consensus/core/src/network/tonic_network.rs
Remove usage of unix only socket API. It should not matter much anyway.
Also, move http2 buffer size into a Parameter field.
CI
---
=> Fix Windows build

apps/wallet/src/ui/app/components/AccountListItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountItem.tsx, apps/wallet/src/ui/app/components/accounts/AccountItemApproveConnection.tsx, apps/wallet/src/ui/app/components/ledger/LedgerAccountRow.tsx, apps/wallet/src/ui/app/components/receipt-card/TxnAddress.tsx, apps/wallet/src/ui/app/hooks/useAppResolveSuinsName.ts, apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
Growthbook flag: https://app.growthbook.io/features/wallet-enable-new-suins-name-format
=> update extension to use new SUINS format

bridge/evm/contracts/SuiBridge.sol, bridge/evm/test/SuiBridgeTest.t.sol
https://hackenproof.com/manager/sui/sui-protocol/reports/SUIPR-94
=> Ensure Non Zero Bridge Amount

crates/sui-tool/src/commands.rs, docs/content/guides/operator/snapshots.mdx
Received some feedback from a node operator about the sui-tool command's arg groups not working properly. Also clarified the docs
tested locally
=> [bugfix] Sui tool snapshot download cli arg fixes

.github/workflows/release.yml
Fixing
```
/Users/officestudio/_work/_temp/8e0cc728-97e6-432b-bd99-a0ab022f8b99.sh: line 6: jq: command not found
cat: stdout: Broken pipe
```
https://github.com/MystenLabs/sui/actions/runs/9118733143/job/25072508475
=> Install `jq` on macos arm64 self-hosted runner

external-crates/move/crates/move-compiler/src/unit_test/filter_test_members.rs
Forgot to push this change before merging https://github.com/MystenLabs/sui/pull/17775
=> [move-ide] Forgotten constant addition

apps/wallet/src/ui/app/pages/approval-request/transaction-request/TransactionDetails/Command.tsx, crates/sui-core/src/unit_tests/data/entry_point_types/Move.lock, crates/sui-core/src/unit_tests/data/entry_point_vector/Move.lock, docs/content/guides/developer/sui-101/building-ptb.mdx, examples/mev_bot/src/index.ts, sdk/docs/pages/typescript/transaction-building/basics.mdx, sdk/docs/pages/typescript/v1-migration.mdx, sdk/graphql-transport/src/mappers/transaction-block.ts, sdk/typescript/src/bcs/bcs.ts, sdk/typescript/src/transactions/ObjectCache.ts, sdk/typescript/src/transactions/TransactionBlock.ts, sdk/typescript/src/transactions/TransactionBlockData.ts, sdk/typescript/src/transactions/Transactions.ts, sdk/typescript/src/transactions/blockData/internal.ts, sdk/typescript/src/transactions/blockData/v1.ts, sdk/typescript/src/transactions/blockData/v2.ts, sdk/typescript/src/transactions/intents/CoinWithBalance.ts, sdk/typescript/src/transactions/json-rpc-resolver.ts, sdk/typescript/src/verify/index.ts, sdk/typescript/test/e2e/coin-with-balance.test.ts, sdk/typescript/test/e2e/data/coin_metadata/Move.lock, sdk/typescript/test/e2e/data/id_entry_args/Move.lock, sdk/typescript/test/e2e/data/serializer/Move.lock, sdk/typescript/test/e2e/object-vector.test.ts, sdk/typescript/test/e2e/txn-serializer.test.ts, sdk/typescript/test/unit/cryptography/multisig.test.ts
=> Update JSON representation to match feedback

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_46.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_45.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_46.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_46.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
=> [native-bridge] - enable bridge in testnet

crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/handlers/objects_snapshot_processor.rs
title
test on the other PR
---
=> indexer fix cherry-pick of #17771

bridge/evm/contracts/SuiBridge.sol
https://hackenproof.com/manager/sui/sui-protocol/reports/SUIPR-93
=> Enable Fee on Transfers Tokens

crates/sui-indexer/src/store/pg_indexer_store.rs
=> [indexer] fix backfilling of objects snapshot to include all columns

Cargo.lock, Cargo.toml, crates/typed-store/src/rocks/mod.rs
The upgrades the underlying rocksdb library as well.
CI
Private testnet: no visible performance change
---
=> Upgrade rocksdb crate

.github/workflows/rust.yml
Fix `mysqlclient-sys` windows cargo build error
https://github.com/MystenLabs/sui/actions/runs/8978802872/job/24659827747?pr=17538
=> [cherry-pick][graphql] Cherry pick windows build fix

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_46.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_46.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_46.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Enable bridge in testnet
---
---
=> [cherry pick] [native-bridge] - enable bridge in testnet (#17756)

crates/sui-indexer/src/framework/fetcher.rs, crates/sui-indexer/src/handlers/checkpoint_handler.rs
title, to early collect indexer lag metrics due to remote store etc.
---
=> testnet indexer: cherry pick of #17796

crates/sui-core/src/traffic_controller/metrics.rs, crates/sui-core/src/traffic_controller/mod.rs
=> [Traffic Control] Add more metrics

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
As in title
Ran against 100 seeds via the following:
```
CONSENSUS=narwhal ./scripts/simtest/seed-search.py simtest --test test_simulated_load_reconfig_with_crashes_and_delays
```
---
=> Increase checkpoint timeout

crates/sui-package-management/src/lib.rs
Convert tabs to spaces. 
(I set up my editor from scratch and caught some cases. Unfortunately rust clippy doesn't catch these?)
N/A
---
=> [Easy] fixup: spaces for tabs in sui-pkg-mgmt lib

crates/sui-core/src/checkpoints/mod.rs
Right now, it is always logs `0` certificates.
---
=> Update wait_for_transactions_sequenced logging field

.changeset/lovely-clouds-sin.md, sdk/enoki/src/EnokiKeypair.ts
=> Add support for personal message signing in Enoki

sdk/docs/pages/typescript/v1-migration.mdx, sdk/typescript/src/cryptography/keypair.ts, sdk/typescript/test/unit/cryptography/keypair.test.ts, sdk/zksend/src/wallet/index.ts
=> Fix bytes in signPersonalMessage

external-crates/move/crates/move-compiler/src/typing/translate.rs, external-crates/move/crates/move-compiler/tests/development/enums/typing/invalid_capabilities.exp, external-crates/move/crates/move-compiler/tests/development/enums/typing/invalid_capabilities.move
Add a test for enum capabilities. Behavior was as expected, but now there is a test for them.
New test
---
=> Add invalid capabilities test for enums

crates/sui-bridge-cli/src/main.rs, crates/sui-bridge/Cargo.toml, crates/sui-bridge/src/action_executor.rs, crates/sui-bridge/src/client/bridge_authority_aggregator.rs, crates/sui-bridge/src/e2e_tests/basic.rs, crates/sui-bridge/src/e2e_tests/test_utils.rs, crates/sui-bridge/src/lib.rs, crates/sui-bridge/src/node.rs, crates/sui-bridge/src/orchestrator.rs, crates/sui-bridge/src/storage.rs, crates/sui-bridge/src/sui_client.rs, crates/sui-bridge/src/sui_mock_client.rs, crates/sui-bridge/src/sui_transaction_builder.rs, crates/sui-bridge/src/test_utils.rs, crates/sui-bridge/src/utils.rs, crates/test-cluster/src/lib.rs
as title. should be straightforward to spot what they are in the changes.
existing test cases
---
=> [bridge] fix a few simple todos

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/epoch/epoch_metrics.rs
Make metric field name to be consistent with metric name
CI
---
=> [nit] Rename metric field

crates/sui-core/src/overload_monitor.rs
=> Overload monitor add monitored_scope

Cargo.lock, Cargo.toml, scripts/simtest/cargo-simtest, scripts/simtest/config-patch
Hopefully this fixes the simtest failures where a port cannot be reused for udp after serving tcp connection on the port without graceful shutdown.
CI
---
=> Upgrade msim pointer

docs/content/references/cli/client.mdx
Add explicit faucet example in the Sui CLI client doc page.
---
=> [docs] Add explicit faucet example

.github/workflows/ci-docs.yml
Install Rust toolchain specified in the repo, as done in other workflows.
CI
https://github.com/MystenLabs/sui/actions/runs/9200509240
---
=> [CI] fix doc CI

sdk/dapp-kit/README.md, sdk/docs/pages/dapp-kit/index.mdx
fix a url work unexcepted
before : `https://sdk.mystenlabs.com/radix-ui.com/primitives`
now: `https://www.radix-ui.com/primitives`
---
=> [docs] fix a url work unexcepted

sdk/docs/pages/dapp-kit/wallet-hooks/useSignAndExecuteTransactionBlock.mdx
Update `SuiClient.signAndExecuteTransactionBlock` link in useSignAndExecuteTransactionBlock page
No test
---
=> [docs] Update link in useSignAndExecuteTransactionBlock page

.github/workflows/release-notes-monitor.yml
=> Fix Release Notes monitor

docs/content/references/cli/keytool.mdx
[DOCS] fix keytool cli doc format issues
---
=> [DOCS] fix keytool cli doc format issues

crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
title, for more granular analysis and tracking
eyeball and CI
---
=> indexer: add lag logs & metrics with abs timestamp and cp seq

Cargo.lock, sui-execution/latest/sui-adapter/Cargo.toml, sui-execution/latest/sui-adapter/src/temporary_store.rs
=> Add monitored scope for read_child_object

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_47.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_47.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_47.snap
Enable feature flag for all environments
CI
---
=> [Consensus 2.0] enable the mysticeti digest inclusion in the committed sub dag

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.27.0 Version Bump

docker/sui-node-deterministic/Dockerfile, docker/sui-node-deterministic/build.sh
=> docker: pin stagex for deterministic builds

crates/sui/src/client_ptb/ptb.rs, docs/content/references/cli/ptb.mdx
- Improve the accuracy of the help for Move call 
- 👀 
---
=> [cli] Fix PTB CLI help

.changeset/bright-wombats-try.md, sdk/typescript/src/client/errors.ts
=> [ts sdk] Add more JSON rpc error codes

Cargo.lock, Cargo.toml, crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap, crates/sui/src/keytool.rs, crates/sui/src/zklogin_commands_util.rs
this added 4 new providers to devnet (aws test tenant, this will not move beyond devnet, main purpose is to serve as a AWS Cognito an example, Microsoft, Credenza3, KarrierOne) 
also fixes couple keytool ergo to simplify testing for zklogin vs multisig/zklogin
depends on: https://github.com/MystenLabs/fastcrypto/pull/737 
tested end to end with prover-dev (currently missing karrier one till they exposes a testing redirect url)
```
==== aws "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_LPSLCkC3A ====
target/debug/sui keytool zk-login-enter-token --parsed-token eyJraWQiOiJrRjRGZU40emQ2Vk5ZREFkeERGYTRcL3FqcWpNS29vbnJ5WVp1S1RONzZkRT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoibE9ta012RXQzZ0RTcEx2Q0FOUlJzdyIsInN1YiI6ImI0NzgxNDM4LWIwNjEtNzA5ZS1iNzRkLWQ4NDU5Yzg0M2NhNCIsImVtYWlsX3ZlcmlmaWVkIjp0 …
```
=> feat: add more providers to devnet

crates/sui-bridge/src/e2e_tests/basic.rs, crates/sui-bridge/src/e2e_tests/complex.rs, crates/sui-bridge/src/e2e_tests/mod.rs, crates/sui-bridge/src/e2e_tests/test_utils.rs
Reverts MystenLabs/sui#17926
Turns out not to be an issue at all, sorry for all the reverts!
=> Revert "Revert "[native-bridge] - add e2e test to test Sui bridge pause.""

crates/sui-config/src/node.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/db_checkpoint_handler.rs, crates/sui-node/src/lib.rs
=> Cherrypick: Fix no-op pruner setting

crates/sui-framework/docs/bridge/message.md, crates/sui-framework/packages/bridge/sources/message.move, crates/sui-framework/packages/bridge/tests/message_tests.move
Some cleanup and 100% test coverage for `message.move`
This is all about testing...
---
=> towards 100% test coverage

sdk/move-bytecode-template/src/lib.rs
=> Fix struct_handles to datatype_handles rename in move-bytecode-template

.changeset/bright-wombats-try.md, .changeset/witty-llamas-smile.md
=> Add changeset for 1.0 release

crates/sui-core/src/transaction_manager.rs
=> Cherrypick #17952 into 1.26

.changeset/little-dolls-rush.md, sdk/typescript/src/bcs/bcs.ts
=> Fix parsing struct tags

.changeset/hot-experts-whisper.md, sdk/typescript/src/transactions/data/v1.ts
=> fix serialization of v1 objects

consensus/core/src/subscriber.rs
Logging raw block bytes is too verbose for validators lagging in timestamp or accepted blocks.
CI
---
=> [Consensus] remove verbose logging of raw blocks

crates/sui-bridge/src/action_executor.rs, crates/sui-bridge/src/e2e_tests/test_utils.rs, crates/sui-bridge/src/lib.rs, crates/sui-bridge/src/main.rs, crates/sui-bridge/src/metrics.rs, crates/sui-bridge/src/node.rs, crates/sui-bridge/src/server/handler.rs, crates/sui-bridge/src/server/mock_handler.rs, crates/sui-bridge/src/server/mod.rs
as title. More to come
tested by running bridge nodes locally
---
=> [bridge] add the first batch of metrics

pnpm-lock.yaml, sdk/wallet-standard/package.json, sdk/wallet-standard/serialized-transaction-data-v2.schema.json, sdk/wallet-standard/src/types.ts
=> Add json schema for new JSON format

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_49.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_49.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_49.snap
Run Mysticeti for consensus in all environments.
Updating relevant parameters and cleaning up CI will be in separate PRs.
CI
---
=> Enable Mysticeti by default

external-crates/move/crates/move-command-line-common/Cargo.toml, external-crates/move/crates/move-command-line-common/src/parser.rs, external-crates/move/crates/move-command-line-common/src/types.rs
Update the move-command-line type parser to be a bit more general.
Added additional tests + proptests.
---
=> [move] Update command line type parsing

external-crates/move/crates/move-command-line-common/Cargo.toml, external-crates/move/crates/move-command-line-common/src/parser.rs, external-crates/move/crates/move-command-line-common/src/types.rs
Update the move-command-line type parser to be a bit more general.
Added additional tests + proptests.
---
--- …
=> [cherry-pick-1.25][move] Update command line type parsing (#18011)

external-crates/move/crates/move-command-line-common/Cargo.toml, external-crates/move/crates/move-command-line-common/src/parser.rs, external-crates/move/crates/move-command-line-common/src/types.rs
Update the move-command-line type parser to be a bit more general.
Added additional tests + proptests.
---
--- …
=> [cherry-pick-1.26][move] Update command line type parsing (#18011)

.changeset/chatty-singers-begin.md, .changeset/thirty-forks-heal.md, sdk/bcs/src/bcs.ts, sdk/typescript/src/transactions/index.ts
=> Export types needed for transaction plugins and improve bcs.option types

.changeset/healthy-dolphins-pretend.md, sdk/zksend/src/wallet/channel/index.ts
=> [zksend-sdk] fix connect issue

consensus/core/src/synchronizer.rs
Cherry pick of https://github.com/MystenLabs/sui/pull/18033
---
=> Cherry pick: [Consensus 2.0] Fix retries and wait time during fetch block request timeout

docs/site/docusaurus.config.js
Replaced the url on the doc site with the right one since it goes 404. 
manually check if the link works.
---
=> docs: fix license url

sdk/wallet-standard/serialized-transaction-data-v2.schema.json, sdk/wallet-standard/src/types.ts
=> Add extensions for implementation specific data

sdk/docs/pages/typescript/migrations/sui-1.0.mdx
=> Fix type in migration guide

apps/core/src/hooks/nameService.ts, apps/wallet/src/ui/app/components/address-input/validation.ts, apps/wallet/src/ui/app/components/receipt-card/TxnAddressLink.tsx, apps/wallet/src/ui/app/pages/home/nft-transfer/TransferNFTForm.tsx, apps/wallet/src/ui/app/pages/home/transfer-coin/SendTokenForm.tsx
=> Support validate address input base on new SuiNS name format

sdk/docs/pages/dapp-kit/wallet-hooks/useSignAndExecuteTransaction.mdx, sdk/docs/pages/typescript/migrations/sui-1.0.mdx
=> [docs] Fix execute in migration guide

docker/sui-bridge-indexer/Dockerfile, docker/sui-bridge-indexer/build.sh
=> [bridge indexer] - bridge indexer docker image

crates/sui-bridge-indexer/src/lib.rs, crates/sui-bridge-indexer/src/main.rs, crates/sui-bridge-indexer/src/postgres_writer.rs, crates/sui-bridge-indexer/src/worker.rs
Make db write transactional to make sure data are not partially written.
for Sui data are written per checkpoint, for eth, data are written per transaction
Tested manually on local database
---
=> [bridge indexer error handling 1/n] - make db write transactional

bridge/evm/deploy_configs/31338.json, crates/sui-bridge-cli/src/lib.rs, crates/sui-bridge/src/abi.rs, crates/sui-bridge/src/action_executor.rs, crates/sui-bridge/src/e2e_tests/basic.rs, crates/sui-bridge/src/metrics.rs, crates/sui-bridge/src/node.rs, crates/sui-bridge/src/orchestrator.rs, crates/sui-bridge/src/server/mod.rs, crates/sui-bridge/src/types.rs
This PR includes a few things:
1. adds more metrics, logs and instruments to bridge software
2. to do instruments we spin out `fn handle_execution_task` and `fn handle_signing_task` from the while loops.
3. revise some existing metrics such that all errors starts with name `bridge_err`
4. fix a bug where we exit the on chain execution task if the task is already handled. Since it's now in `fn handle_execution_task` this becomes a non-issue
5. added client command `DepositNativeEtherOnEth` which is self-descriptive. I needed this when testing the change locally. The change is small and straightforward so i didn't bother to separate it to its own PR
6. update solidity deploy configs. for 31337.json, change the source chain id to 12. Also add 31338 and make it match the local deploy script's …
=> [bridge] more metrics, logs and instruments 

.github/workflows/bridge.yml, .github/workflows/narwhal.yml, .github/workflows/rust.yml, crates/sui-bridge/src/e2e_tests/basic.rs
=> move bridge test to its own GH workflow

external-crates/move/crates/move-analyzer/src/symbols.rs
Positionality of the struct fields is now preserved until typing so it no longer has to be computed by the IDE itself
All existing tests must pass
=> [move-ide] Trimmed no longer necessary explicit computation of positional fields

sdk/docs/pages/typescript/transaction-building/basics.mdx
During latest TransactionBlock->Transaction change, a code sample was updated slightly improperly: 
> client.signAndExecuteTransaction**B**()  
This PR fixes the code sample.
Compare the updated function name with the latest official API docs.
---
=> (docs) Fixed a typo in a code sample

Cargo.lock, Cargo.toml, crates/typed-store/src/rocks/mod.rs
This reverts commit 1a51faa476b8d9e7e00f5b04d492654581bc0b02.
=> Revert "Upgrade rocksdb crate (#17813)"

external-crates/move/crates/move-compiler/src/editions/mod.rs, external-crates/move/crates/move-compiler/src/expansion/translate.rs, external-crates/move/crates/move-compiler/src/parser/ast.rs, external-crates/move/crates/move-compiler/src/parser/filter.rs, external-crates/move/crates/move-compiler/src/parser/syntax.rs, external-crates/move/crates/move-compiler/src/typing/visitor.rs, external-crates/move/crates/move-compiler/tests/move_2024/parser/top_level_module.move, external-crates/move/crates/move-compiler/tests/move_2024/parser/top_level_module_address_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/parser/top_level_module_address_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/parser/top_level_module_double_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/parser/top_level_module_double_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/parser/top_level_module_mixed_invalid.move, external-crates/move/crates/move-compiler/tests/move_2024/parser/top_level_module_mixed_invalid_2.exp, external-crates/move/crates/move-compiler/tests/move_2024/parser/top_level_module_mixed_invalid_2.move, external-crates/move/crates/move-compiler/tests/move_check/parser/module_missing_lbrace.exp, external-crates/move/crates/move-compiler/tests/move_check/parser/top_level_module.exp, external-crates/move/crates/move-compiler/tests/move_check/parser/top_level_module.move, external-crates/move/crates/move-compiler/tests/move_check/parser/top_level_module_address_invalid.exp, external-crates/move/crates/move-compiler/tests/move_check/parser/top_level_module_address_invalid.move
Exactly what it says on the tin.
New tests
---
=> [move][move-2024] Add support for inline module definitions

crates/sui-indexer/migrations/mysql/2024-03-25-203621_objects/up.sql, crates/sui-indexer/migrations/pg/2023-08-19-044023_objects/up.sql
very small pr to rename the existing _coin index to _coin_owner to better differentiate between the coin_only index
---
=> rename _coin to _coin_owner

crates/sui-core/src/execution_cache/writeback_cache.rs, crates/sui-node/src/lib.rs
This causes rare test failures, fix is pretty self-explanatory
=> Handle rare edge case in cache coherency check

crates/sui-bridge-cli/src/lib.rs
title 
tested locally on bridgent
---
=> [Bridge[cli]] make function-selection optional and allow depositing fraction of eth 

consensus/config/src/parameters.rs, consensus/config/tests/snapshots/parameters_test__parameters.snap, consensus/core/src/network/tonic_network.rs, crates/sui-core/src/consensus_adapter.rs
Reduce consensus adapter max submission delay to be more suitable for Mysticeti.
Increase message size limit.
---
=> [Consensus] update parameters

docker/sui-tools/Dockerfile
adjust the tools in the `sui-tools` image
will test a build of sui-tools for our prod images
=> [docker] More tools in sui-tools

crates/sui-config/src/object_storage_config.rs
Enable aws secrets read from env rather than configs
will test on snapshot hosts
=> [snapshot] allow for setting archival/snapshot aws keys via env vars

external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs, external-crates/move/crates/move-compiler/src/typing/visitor.rs
- @tzakian ran into the problem of needing to point to where the type is from, not just where it was declared. 
- There is likely some longer term work here (like remembering which types were annotated by the user vs inferred) but this is a good/decent bandaid 
- 👀 
---
=> [move-compiler] Update typing visitor to include optional expression loc in visit_type

consensus/core/src/authority_service.rs, consensus/core/src/block_manager.rs
=> [Consensus 2.0] reduce log level

docs/content/guides/developer/app-examples/trustless-swap/frontend.mdx, docs/content/guides/developer/cryptography/zklogin-integration.mdx, docs/content/guides/developer/sui-101/sign-and-send-txn.mdx
=> Fix some incorrectly updated docs

crates/sui-protocol-config/src/lib.rs
=> Update doc for consensus commit prologue V3 in protocol config

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.28.0 Version Bump

consensus/core/src/commit.rs
Maintain backward compatibility with the initial implementation of CommitRange.
CI
---
=> [Consensus] use Range internally for CommitRange

crates/sui-bridge-indexer/config.yaml, crates/sui-bridge-indexer/src/config.rs, crates/sui-bridge-indexer/src/lib.rs, crates/sui-bridge-indexer/src/main.rs, crates/sui-bridge-indexer/src/metrics.rs, crates/sui-bridge-indexer/src/worker.rs
Initial work for monitoring values. 
This is a good start for values to track and please advise on what else you'd like to see.
Not much now and need to come up with something to check that things are good
---
=> Initial metrics work for the indexer

consensus/core/src/commit.rs, consensus/core/src/metrics.rs, consensus/core/src/network/tonic_network.rs, consensus/core/src/subscriber.rs
=> Cherrypicks to 1.27

crates/sui-rest-api/src/committee.rs, crates/sui-rest-api/src/lib.rs, crates/sui-rest-api/src/reader.rs, crates/sui-types/src/sui_sdk2_conversions.rs
=> rest: add endpoint for querying the ValidatorCommittee

crates/sui-protocol-config/src/lib.rs, crates/sui-rest-api/src/info.rs, crates/sui-rest-api/src/response.rs, crates/sui-rest-api/src/types.rs
=> rest: add human readable chain name to responses

sdk/typescript/test/e2e/coin-with-balance.test.ts, sdk/typescript/test/unit/client/http-transport.test.ts
=> [tests] fix some flakey tests

crates/sui-e2e-tests/tests/traffic_control_tests.rs
There are two classes of errors from what I've seen: 
1. `Expected blocklist to be non-empty` -- this was simply due to race conditions between when the test server garbage collects IPs from the blocklist after TTL and when the test checks for existence in the blocklist. If there's some sort of network delay then we may check for existence too soon. To fix, we could either increase the TTL timeout or have signaling between the server and the test (note that we can't run as a simtest today because simtests don't correctly simulate socket connections). I chose to increase the TTL and remove the later garbage collection check as it's not really necessary (it's really only checking that we correctly pass the TTL config to the "remote server"). However if this continues to be an issue, can add …
=> [TrafficController] Fix fw delegation tests

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
=> [CheckpointExecutor] Remove unneccesary asyncs

crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/state_accumulator.rs
CP https://github.com/MystenLabs/sui/pull/18131
---
=> [StateAccumulatorV2] CP Fix and disable in mainnet

consensus/core/src/metrics.rs, consensus/core/src/network/anemo_network.rs, consensus/core/src/network/connection_monitor.rs, consensus/core/src/network/metrics.rs, consensus/core/src/network/tonic_network.rs
This provides visibility into the tcp socket buffer sizes and limits on validators.
CI
---
=> [Consensus] add tcp socket buffer size metrics

consensus/core/src/metrics.rs, consensus/core/src/network/anemo_network.rs, consensus/core/src/network/connection_monitor.rs, consensus/core/src/network/metrics.rs, consensus/core/src/network/tonic_network.rs, sdk/typescript/test/e2e/coin-with-balance.test.ts, sdk/typescript/test/unit/client/http-transport.test.ts
=> CP CI fix and additional metrics into 1.27

docs/content/guides/developer/advanced/randomness-onchain.mdx
=> Randomness doc - stress that the example is insecure

crates/sui-graphql-rpc/src/types/object.rs
=> [GraphQL] cherry pick 18069

Cargo.lock, Cargo.toml
=> sui-sdk: bump to rev 'bb224b9e6b6edf5eeedcdf71c750a30b68073057'

sdk/docs/pages/typescript/executors.mdx
=> [docs] Fix type in docs

docs/README.md
Fix the link syntax to make it work.
No.
---
=> docs: fix link syntax

bridge/incentivize_testnet_faq.md
=> add incentive program faq

external-crates/move/crates/move-analyzer/src/compiler_info.rs, external-crates/move/crates/move-compiler/src/diagnostics/codes.rs, external-crates/move/crates/move-compiler/src/naming/translate.rs, external-crates/move/crates/move-compiler/src/shared/ide.rs, external-crates/move/crates/move-compiler/src/typing/expand.rs, external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/ellipsis_expansion.ide.exp, external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/ellipsis_expansion.move
This modifies ellipsis handling to record them for the IDE.
New test added
---
=> [move][move-ide] Add ellipsis IDE info

sdk/docs/pages/bcs/index.mdx
=> [docs] improve inference of bcs generic functions

pnpm-lock.yaml
=> Fix npm audit

bridge/incentivize_testnet_faq.md
=> add some format for bridge incentive program faq

docs/content/guides/developer/sui-101/access-time.mdx, examples/move/basics/Move.toml, examples/move/basics/sources/clock.move
=> [docs] Update time topic

dapps/multisig-toolkit/src/components/preview-effects/DryRunContext.tsx, dapps/multisig-toolkit/src/components/preview-effects/EffectsPreview.tsx, dapps/multisig-toolkit/src/components/preview-effects/partials/BalanceChanges.tsx, dapps/multisig-toolkit/src/components/preview-effects/partials/Overview.tsx, dapps/multisig-toolkit/src/routes/offline-signer.tsx
Adds support for any input (`TransactionBlock.from` parsing) on dry runs.
Adds custom network selector for dry runs, so we do not require a wallet connection to dry run. It still keeps in sync with the wallet selected network! 
---
=> [Multisig Toolkit] Improve dry run options

crates/sui-single-node-benchmark/src/mock_account.rs
=> [bench] Use random object IDs

crates/sui-benchmark/tests/simtest.rs, crates/sui-core/src/authority.rs, crates/sui-core/src/authority/authority_store.rs, crates/sui-core/src/authority/authority_store_pruner.rs, crates/sui-core/src/authority/authority_store_tables.rs, crates/sui-core/src/authority/test_authority_builder.rs, crates/sui-core/src/checkpoints/checkpoint_executor/data_ingestion_handler.rs, crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/db_checkpoint_handler.rs, crates/sui-core/src/lib.rs, crates/sui-core/src/rest_index.rs, crates/sui-core/src/state_accumulator.rs, crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/object_deletion_tests.rs, crates/sui-node/src/lib.rs, crates/sui-tool/src/db_tool/db_dump.rs, crates/sui-types/src/base_types.rs, crates/sui-types/src/coin.rs, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/effects_v2.rs, crates/sui-types/src/full_checkpoint_content.rs, crates/sui-types/src/inner_temporary_store.rs, crates/sui-types/src/object.rs, crates/sui-types/src/storage/mod.rs, crates/sui-types/src/storage/read_store.rs, crates/typed-store/src/rocks/mod.rs
=> rest: introduce RestIndexStore

docs/content/guides/developer/getting-started/connect.mdx
=> [docs] Update connect.mdx

.changeset/neat-adults-double.md, sdk/typescript/src/transactions/intents/CoinWithBalance.ts
=> [sdk] Fix coinWithBalance when using number for balance

docs/content/guides/developer/sui-101/shared-owned.mdx
=> [docs] Using code references

apps/wallet/src/ui/app/components/LabelValueItem.tsx, apps/wallet/src/ui/app/pages/home/nft-details/index.tsx
=> [wallet-ext] - remove hyperlinks from nft details

apps/wallet/src/ui/app/hooks/useBlockedObjectList.ts, apps/wallet/src/ui/app/pages/home/hidden-assets/index.tsx, apps/wallet/src/ui/app/pages/home/nfts/index.tsx
=> add blocked list

.github/workflows/bridge.yml
Updating the test environment used. 
Testing it in CI
---
=> Update Bridge Github Workflow Environment

crates/sui-bridge/src/sui_transaction_builder.rs, crates/sui/src/sui_commands.rs, crates/sui/src/validator_commands.rs, crates/test-cluster/src/lib.rs
=> [sui native bridge] - add update committee node url to validator CLI

crates/simulacrum/src/lib.rs, crates/sui-core/src/execution_cache.rs, crates/sui-core/src/execution_cache/passthrough_cache.rs, crates/sui-core/src/execution_cache/proxy_cache.rs, crates/sui-core/src/execution_cache/writeback_cache.rs, crates/sui-core/src/storage.rs, crates/sui-rest-api/src/info.rs, crates/sui-rest-api/src/response.rs, crates/sui-rest-api/src/types.rs, crates/sui-transactional-test-runner/src/simulator_persisted_store.rs, crates/sui-types/src/storage/read_store.rs
=> rest: properly expose the lowest available checkpoit watermark

crates/sui-rest-api/src/lib.rs, crates/sui-rest-api/src/reader.rs, crates/sui-rest-api/src/system.rs
=> rest: add endpoint for fetching a SystemStateSummary

crates/sui-graphql-rpc/src/extensions/timeout.rs
A previous PR messed up the logging of queries that time out. This fixes it.
Locally.
---
=> [GraphQL][easy] Fix missing setting the query string

.github/workflows/e2e.yml, sdk/deepbook/package.json, sdk/kiosk/package.json, sdk/typescript/package.json, sdk/typescript/test/e2e/object-cache.test.ts, sdk/typescript/test/e2e/utils/setup.ts
=> [tests] make e2e test output less verbose

crates/sui-adapter-transactional-tests/tests/enums/enum_with_key_only.exp, crates/sui-adapter-transactional-tests/tests/enums/enum_with_key_only.mvir, crates/sui-adapter-transactional-tests/tests/enums/enum_with_key_only_uid_field.exp, crates/sui-adapter-transactional-tests/tests/enums/enum_with_key_only_uid_field.mvir, crates/sui-adapter-transactional-tests/tests/enums/enum_with_key_store.exp, crates/sui-adapter-transactional-tests/tests/enums/enum_with_key_store.mvir, crates/sui-adapter-transactional-tests/tests/enums/enum_with_key_store_uid_field.exp, crates/sui-adapter-transactional-tests/tests/enums/enum_with_key_store_uid_field.mvir, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_only.exp, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_only.mvir, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_only_uid_field.exp, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_only_uid_field.mvir, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_only_uid_field_version_48.exp, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_only_uid_field_version_48.mvir, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_only_version_48.exp, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_only_version_48.mvir, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_store.exp, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_store.mvir, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_store_uid_field.exp, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_store_uid_field.mvir, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_store_uid_field_version_48.exp, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_store_uid_field_version_48.mvir, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_store_version_48.exp, crates/sui-verifier-transactional-tests/tests/enums/enum_with_key_store_version_48.mvir, sui-execution/latest/sui-verifier/src/struct_with_key_verifier.rs
Adds some more tests for enums in Move
Added a bunch new tests.
=> [move] Add more enums tests

.changeset/stale-cycles-clean.md, sdk/typescript/src/transactions/Transaction.ts
=> Fix bug that prevents coinWithBalance intent from being resolved

external-crates/move/crates/move-cli/src/sandbox/commands/publish.rs, external-crates/move/crates/move-cli/src/sandbox/commands/run.rs, external-crates/move/crates/move-core-types/src/effects.rs, external-crates/move/crates/move-transactional-test-runner/src/vm_test_harness.rs, external-crates/move/crates/move-unit-test/src/test_runner.rs, external-crates/move/crates/move-vm-integration-tests/src/tests/exec_func_effects_tests.rs, external-crates/move/crates/move-vm-integration-tests/src/tests/loader_tests.rs, external-crates/move/crates/move-vm-runtime/src/data_cache.rs, external-crates/move/crates/move-vm-runtime/src/session.rs, external-crates/move/move-execution/v0/crates/move-vm-runtime/src/data_cache.rs, external-crates/move/move-execution/v0/crates/move-vm-runtime/src/session.rs, external-crates/move/move-execution/v1/crates/move-vm-runtime/src/data_cache.rs, external-crates/move/move-execution/v1/crates/move-vm-runtime/src/session.rs, external-crates/move/move-execution/v2/crates/move-vm-runtime/src/data_cache.rs, external-crates/move/move-execution/v2/crates/move-vm-runtime/src/session.rs, sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs
Remove code related to events
existing tests
---
=> Remove events from the Move VM

Cargo.lock, crates/sui-rest-api/Cargo.toml, crates/sui-rest-api/src/lib.rs, crates/sui-rest-api/src/system.rs
=> rest: add protocol-config and gas endpoints

crates/sui-core/src/epoch/randomness.rs
Before this change, a crash after DKG completed and before any round completed would cause nodes to resume at round 1 and miss round 0.
simtest seed-search to verify
=> Fix off-by-one error in RB crash recovery

crates/sui-core/src/rest_index.rs
=> rest-index: fix bug which stops restoring from snapshot

apps/wallet/src/ui/app/components/known-scam-overlay/index.tsx, apps/wallet/src/ui/app/components/known-scam-overlay/useShowScamWarning.tsx, apps/wallet/src/ui/app/components/user-approve-container/index.tsx
=> [wallet-ext] - remove ability to bypass malicious domain check

crates/sui-core/src/authority/epoch_start_configuration.rs, crates/sui-core/src/state_accumulator.rs
=> [StateAccumulator] Do not set epoch flag by default

Cargo.lock, Cargo.toml, scripts/simtest/cargo-simtest, scripts/simtest/config-patch
=> Update msim pointer to latest commit

crates/simulacrum/src/lib.rs, crates/sui-core/src/storage.rs, crates/sui-rest-api/src/accounts.rs, crates/sui-rest-api/src/checkpoints.rs, crates/sui-rest-api/src/client.rs, crates/sui-rest-api/src/health.rs, crates/sui-rest-api/src/lib.rs, crates/sui-rest-api/src/objects.rs, crates/sui-rest-api/src/reader.rs, crates/sui-rest-api/src/transactions/mod.rs, crates/sui-transactional-test-runner/src/simulator_persisted_store.rs, crates/sui-types/src/messages_checkpoint.rs, crates/sui-types/src/storage/mod.rs, crates/sui-types/src/storage/read_store.rs, crates/sui-types/src/sui_sdk2_conversions.rs
Introduce:
- list checkpoints
- list transactions
- list account owned objects
---
=> rest: introduce a number of list endoints

crates/sui-security-watchdog/src/main.rs
adds an uptime metric 
i'll test in prod
=> add uptime metric to sui security watchdog

Cargo.lock, Cargo.toml, scripts/simtest/cargo-simtest, scripts/simtest/config-patch
This reverts commit 285d4030315caeeeb7af4e6ce8729d56c6775e5f.
Seems causing test failure, and currently investigating.
---
=> Revert "Update msim pointer to latest commit (#18282)"

crates/sui-core/src/state_accumulator.rs
Bug is explained in the comments
=> Fix bug with single-checkpoint epochs

crates/sui-core/src/authority.rs
Explained in comments.
This unblocks the transactional tests using advance epoch, which would panic today as it would lose the randomness beacon override.
CI
---
=> [test] Keep protocol config the same when single authority reconfigure

Cargo.lock
I think we need this cherry pick to unblock CI on these GraphQL release branches. 
---
=> [GraphQL] Cherry pick cargo deny fix

Cargo.lock
Cherry pick cargo deny fix to legacy branch.
---
=> [GraphQL] Cherry pick cargo deny fix to legacy

Cargo.lock, crates/sui-bridge/Cargo.toml, crates/sui-bridge/src/action_executor.rs, crates/sui-bridge/src/node.rs, crates/sui-bridge/src/orchestrator.rs
as title
unit test. Will add an e2e test in a separate PR (needs some new test infra that will inflate this PR)
---
=> [bridge] let bridge node automatically accept new tokens after they are approved.

Cargo.lock, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-rpc/Cargo.toml
Bump prod version (forgot to do it last release).
---
=> [GraphQL] Bump prod version

Cargo.lock, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-rpc/Cargo.toml
Bump legacy service version. (forgot to do it after the release last week).
---
=> [GraphQL] Bump legacy service version

crates/sui-config/src/object_storage_config.rs
@chris-gorham pointed out a copy-paste error on my end
=> fix call to set with_access_key_id

crates/sui-bridge-indexer/src/config.rs, crates/sui-bridge-indexer/src/eth_worker.rs, crates/sui-bridge-indexer/src/main.rs, crates/sui-bridge-indexer/src/metrics.rs, crates/sui-bridge-indexer/src/schema.rs
Refactor eth_worker to clean up main. 
---
=> Refactor eth_worker 

crates/sui-core/src/unit_tests/coin_deny_list_tests.rs, crates/sui-types/src/config.rs, crates/sui-types/src/deny_list_v2.rs, crates/sui-types/src/lib.rs
- Added additional functionality for config types
- Moved them to their own module 
- 👀 
---
=> [config] sui types for config

bridge/evm/contracts/BridgeLimiter.sol, bridge/evm/contracts/interfaces/IBridgeLimiter.sol
We don't find this event super useful yet.
---
=> [bridge] not emit HourlyTransferAmountUpdated

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.29.0 version bump

crates/sui-network/src/discovery/mod.rs, crates/sui-network/src/state_sync/mod.rs
=> [Sync state] add debug/trace messages

Cargo.lock, Cargo.toml, scripts/simtest/cargo-simtest, scripts/simtest/config-patch
=> Update MSIM to latest commit

crates/sui-core/src/authority.rs, crates/sui-core/src/unit_tests/coin_deny_list_tests.rs, crates/sui-core/src/unit_tests/data/coin_deny_list_v2/sources/regulated_coin.move, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_50.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_51.snap, crates/sui-types/src/config.rs, crates/sui-types/src/deny_list_v1.rs, crates/sui-types/src/deny_list_v2.rs, crates/sui-types/src/dynamic_field.rs, crates/sui-types/src/error.rs
Add a new feature flag. Check the Denylist v2 during signing.
We will add transactional tests.
---
=> Denylist v2 sign checks

.changeset/flat-ligers-brush.md, pnpm-lock.yaml, sdk/typescript/src/zklogin/index.ts, sdk/zklogin/src/nonce.ts
Fixes nonce generation sometimes being off by one byte.
---
=> Fix nonce length generation

docs/content/guides/developer/cryptography/zklogin-integration.mdx, docs/content/snippets/openid-providers.mdx
=> fix: update providers and link

crates/sui-bridge-cli/src/lib.rs, crates/sui-bridge-cli/src/main.rs, crates/sui-bridge/src/client/bridge_authority_aggregator.rs
=> [bridge cli] add dry run option in governance cmd

Cargo.lock, crates/sui-framework/docs/bridge/committee.md, crates/sui-framework/docs/bridge/message.md, crates/sui-framework/packages/bridge/sources/committee.move, crates/sui-framework/packages/bridge/sources/message.move, crates/sui-framework/published_api.txt, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_52.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_52.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_52.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui/Cargo.toml, crates/sui/src/validator_commands.rs
1. emit CommitteeMemberUrlUpdateEvent when a validator updates url
2. add url checks when validator add or update bridge url
3. update a comment: the Blocklist payload contains 20 bytes evm addresses instead of 33 bytes pub keys
---
=> [bridge] emit CommitteeMemberUrlUpdateEvent event 

Cargo.lock, crates/sui-framework/docs/bridge/committee.md, crates/sui-framework/docs/bridge/message.md, crates/sui-framework/packages/bridge/sources/committee.move, crates/sui-framework/packages/bridge/sources/message.move, crates/sui-framework/published_api.txt, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_52.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_52.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_52.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, crates/sui/Cargo.toml, crates/sui/src/validator_commands.rs
=> Cherry pick 18359 to 1.28.0

crates/sui-keys/src/keystore.rs
=> [keystore] No need to print this everytime a key is added

crates/sui-core/src/unit_tests/coin_deny_list_tests.rs, crates/sui-types/src/deny_list_v2.rs
=> Fix global pause setting

docs/site/docusaurus.config.js, docs/site/package.json, docs/site/pnpm-lock.yaml
=> [docs] add posthog config to doc site

crates/sui-core/tests/staged/sui.yaml, crates/sui-types/src/deny_list_v2.rs, crates/sui-types/src/execution_status.rs, crates/sui-types/src/storage/mod.rs, crates/sui-types/tests/staged/exec_failure_status.yaml, sui-execution/latest/sui-adapter/src/execution_engine.rs, sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs, sui-execution/latest/sui-adapter/src/temporary_store.rs, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/v1/sui-adapter/src/temporary_store.rs, sui-execution/v2/sui-adapter/src/temporary_store.rs
This PR checks denylist v2 during execution.
At the end of execution, it collects all the coin objects that are written with an address owner, and check whether the address is denied for the coin.
I am working on tests separately using the Move branch, since the Move code hasn't been merged yet.
---
=> Check denylist v2 during execution

docs/site/vercel.json
=> [docs][uber-easy] Adding redirect to move book

docker/sui-tools/Dockerfile
make it possible to run bridge-indexer via sui-tools bin
=> add bridge-indexer to sui-tools

sui-execution/v2/sui-adapter/src/programmable_transactions/execution.rs
Fix a typo issue in an old execution version 
Historical replays
=> [adapter] Fix overlapping match in old execution version

sui-execution/v2/sui-adapter/src/programmable_transactions/execution.rs
Fix a typo issue in an old execution version 
Historical replays
=> [cherry-pick][adapter] Fix overlapping match in old execution version (#18415)

crates/sui-framework/docs/move-stdlib/option.md, crates/sui-framework/docs/sui-framework/coin.md, crates/sui-framework/docs/sui-framework/config.md, crates/sui-framework/docs/sui-framework/deny_list.md, crates/sui-framework/docs/sui-framework/dynamic_object_field.md, crates/sui-framework/docs/sui-framework/token.md, crates/sui-framework/packages/move-stdlib/sources/option.move, crates/sui-framework/packages/sui-framework/sources/coin.move, crates/sui-framework/packages/sui-framework/sources/config.move, crates/sui-framework/packages/sui-framework/sources/deny_list.move, crates/sui-framework/packages/sui-framework/sources/dynamic_object_field.move, crates/sui-framework/packages/sui-framework/tests/coin_tests.move, crates/sui-framework/packages/sui-framework/tests/config_tests.move, crates/sui-framework/packages/sui-framework/tests/deny_list_tests.move, crates/sui-framework/published_api.txt, crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_52.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_52.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_52.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, external-crates/move/crates/move-vm-types/src/values/values_impl.rs, sui-execution/latest/sui-move-natives/src/config.rs, sui-execution/latest/sui-move-natives/src/lib.rs, sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs, sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs, sui-execution/latest/sui-move-natives/src/test_scenario.rs
- Deny list v2 using config 
- All APIs are behind public(protected) currently
- Types are public but will change before likely before hitting devnet
- Added test scenario support and tests
---
=> Coin denylist v2 + config 

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_52.snap
Action following release schedule.
---
=> Turn on shared object congestion control in tests and devnet

.changeset/loud-keys-sort.md, .changeset/slow-kangaroos-breathe.md, sdk/typescript/src/transactions/Transaction.ts, sdk/zksend/src/links/builder.ts, sdk/zksend/src/links/claim.ts, sdk/zksend/src/links/zk-bag.ts
=> [zksend] update zkbag class to improve compatibility with plugin API

crates/sui-sdk/src/lib.rs
=> sdk: silently fail if ws connection can't be made

apps/wallet/src/ui/app/components/known-scam-overlay/types.ts, apps/wallet/src/ui/app/components/known-scam-overlay/useDappPreflight.ts, apps/wallet/src/ui/app/components/known-scam-overlay/useShowScamWarning.tsx
Adds current network to preflight request
---
=> [wallet-ext] - add network to preflight request

crates/sui-core/src/authority/epoch_start_configuration.rs, crates/sui-core/src/state_accumulator.rs
=> [StateAccumulatorV2] Re-enable on testnet as per epoch component

docs/content/concepts/transactions/prog-txn-blocks.mdx
fix description about `MergeCoins` comand 
=> [PTB Concepts]Update prog-txn-blocks.mdx

crates/sui-core/src/authority/epoch_start_configuration.rs, crates/sui-core/src/state_accumulator.rs
Same as https://github.com/MystenLabs/sui/pull/18444 but against the release branch
---
=> [StateAccumulatorV2] Re-enable on testnet

.github/workflows/release.yml
Fixes a bug I introduced with #18204 in the bash script building `sui-pg` binary.
---
=> [CI] Fix release workflow

.github/workflows/release.yml
Fixes a bug I introduced with #18204 in the bash script building `sui-pg` binary.
---
=> [cherry-pick][CI] Cherry pick workflow fix

.github/workflows/rust.yml
need this env var after the release notes change.
eyes
---
=> fix release note check in workflow

crates/sui-framework/packages/move-stdlib/sources/vector.move, crates/sui-framework/packages/move-stdlib/tests/vector_tests.move
Adds the first batch of macros for `vector`. These are the least controversial.
Features tests.
Adds macros for common vector operations. 
=> [stdlib] Adds vector macros 1/n

crates/sui-bridge-indexer/Cargo.toml, crates/sui-bridge-indexer/src/config.rs, crates/sui-bridge-indexer/src/eth_worker.rs, crates/sui-bridge-indexer/src/latest_eth_syncer.rs, crates/sui-bridge-indexer/src/main.rs, crates/sui-bridge-indexer/src/sui_transaction_handler.rs, crates/sui-bridge-indexer/src/sui_worker.rs
=> [bridge-indexer] - Bridge indexer cleanup refactoring 1/n

crates/simulacrum/src/lib.rs, crates/sui-core/src/rest_index.rs, crates/sui-core/src/storage.rs, crates/sui-rest-api/src/coins.rs, crates/sui-rest-api/src/lib.rs, crates/sui-rest-api/src/objects.rs, crates/sui-transactional-test-runner/src/simulator_persisted_store.rs, crates/sui-types/src/storage/mod.rs, crates/sui-types/src/storage/read_store.rs
=> rest: add get_coin_info and list_dynamic_fields endpoints

Cargo.lock, consensus/core/Cargo.toml, consensus/core/src/commit_syncer.rs, consensus/core/src/error.rs, consensus/core/src/metrics.rs
* add a couple of metrics on commit syncer which found probably useful during investigations
* report the error enum name for the fetch once error metric
CI
---
=> [chore] add more metrics on commit syncer

crates/sui/src/sui_commands.rs
Cherry pick #18469 into release branch v1.28
Prior to #18204, `sui start` accepted a network config file when using `--network.config`, and `sui-test-validator` accepted a config directory when using the `--config-dir`, so we need to support both. That PR introduces a bug as in it accepts only directories.
---
=> [cherry-pick][cli] Cherry pick cli fix (#18469)

external-crates/move/crates/move-compiler/src/parser/syntax.rs, external-crates/move/crates/move-compiler/tests/move_2024/matching/raw_address.move, external-crates/move/crates/move-compiler/tests/move_2024/matching/raw_address_invalid.exp, external-crates/move/crates/move-compiler/tests/move_2024/matching/raw_address_invalid.move
This allows raw addresses to be used as pattern prefixes
New tests
---
=> [move][move-2024] Add raw address support for patterns

crates/sui-core/src/unit_tests/coin_deny_list_tests.rs, crates/sui-e2e-tests/tests/move_test_code/sources/regulated_coin.move, crates/sui-e2e-tests/tests/per_epoch_config_stress_tests.rs
Add a test that starts two threads, one that keeps mutating the denylist, one keeps executing transactions.
Make sure there is no fork.
CI
---
=> Add per epoch config stress tests

consensus/core/src/authority_node.rs, consensus/core/src/commit_observer.rs, consensus/core/src/core.rs, consensus/core/src/metrics.rs, consensus/core/src/network/anemo_network.rs, consensus/core/src/network/tonic_network.rs, consensus/core/src/synchronizer.rs
=> [Consensus] Additional logging and monitoring

crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_deny_and_undeny_sender.exp, crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_global_pause.exp, crates/sui-adapter-transactional-tests/tests/random/happy_flows.exp, crates/sui-graphql-e2e-tests/tests/transactions/shared.exp, crates/sui-transactional-test-runner/src/test_adapter.rs, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/effects_v2.rs, crates/sui-types/src/effects/mod.rs
Also include unchanged shared objects in the tx summary so we could see them in the test result.
This will allow us to see the check on deny list objects.
---
=> Add unchanged shared object in transactional tests summary

.changeset/config.json, examples/trading/frontend/package.json
=> Ignore examples from changsets

.github/workflows/e2e.yml
=> Disable wallet tests

crates/sui-core/src/traffic_controller/metrics.rs, crates/sui-core/src/traffic_controller/mod.rs, crates/sui-core/src/traffic_controller/policies.rs
As in title and comments
Updated unit tests
---
=> [TrafficController] Periodic highest traffic rate metrics and logging

apps/wallet/src/shared/constants.ts, apps/wallet/src/ui/app/components/menu/content/WalletSettingsMenuList.tsx
=> [wallet-ext] - add support link

.github/workflows/github-issues-monitor.yml
This somehow got broken, just remove unneeded stuff.
---
=> [CI] Update github-issues-monitor.yml

crates/sui-indexer/README.md
=> [docs][easy] Small edit

external-crates/move/crates/move-cli/tests/build_tests/dependency_deprecations/args.exp, external-crates/move/crates/move-compiler/src/expansion/translate.rs, external-crates/move/crates/move-compiler/src/shared/mod.rs, external-crates/move/crates/move-compiler/tests/move_2024/typing/allow_deprecated.move, external-crates/move/crates/move-compiler/tests/move_2024/typing/deprecated_macros.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/deprecated_ty_params.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/deprecation_inter_module_calls.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/deprecation_intra_module_calls.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/deprecation_use_in_constants.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/internal_module_deprecations.exp
- Added annotation for allowing deprecated usage 
- New test 
---
=> [move] #[allow(deprecated_usage)]

crates/sui-core/src/authority_server.rs, crates/sui-core/src/unit_tests/authority_tests.rs, crates/sui-core/src/unit_tests/server_tests.rs, crates/sui-core/src/unit_tests/transaction_tests.rs
Generate local tcp ip in the constructor instead of passing in the same thing every time.
CI
---
=> [test] Simplify authority server creation

crates/mysten-network/src/multiaddr.rs, crates/sui-core/src/authority_client.rs
=> authority_client: rewrite udp address to tcp

crates/mysten-network/src/multiaddr.rs, crates/mysten-network/src/server.rs
=> mysten-network: default to http if not present

crates/sui-storage/src/indexes.rs
fixes the JSON RPC bug mentioned in [this issue](https://github.com/MystenLabs/sui/issues/18253), related to the incorrect indexing of coin objects when transferred from objects.
Previous assumption that coin object has to be present in input objects is no longer valid
=> [json rpc indexes] fix coin_index edge case with receiving objects

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_53.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_53.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_53.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
The goal is to make them into 1.29. Is it too late?
---
=> Turn on consensus commit prologue v3 in testnet

docs/content/guides/developer/advanced/randomness-onchain.mdx
=> [Fix Doc] Update randomness-onchain.mdx

docs/content/concepts/sui-move-concepts/packages/automated-address-management.mdx, docs/content/concepts/sui-move-concepts/packages/upgrade.mdx
Updates docs to reflect https://github.com/MystenLabs/sui/pull/18470 changes.
N/A docs
---
=> docs: automated address management updates

crates/sui-core/src/unit_tests/move_package_publish_tests.rs, crates/sui-move-build/src/lib.rs, crates/sui-package-management/src/lib.rs, crates/sui/tests/cli_tests.rs
Small things I spotted to update that I didn't want to bloat previous PRs with
Simplification / covered by tests.
---
=> move: better errors, simplify logic for addr mgmt

crates/sui-core/src/authority/epoch_start_configuration.rs
=> [StateAccumulatorV2] Enable on mainnet for next release

crates/sui-core/src/authority_server.rs, crates/sui-types/src/transaction.rs
Consolidate the last piece of validity checks.
CI
---
=> Check randomness in tx validity checks

crates/sui-data-ingestion-core/src/reader.rs
Chris set up a colocated FN <> indexer, adding some logs to differentiate the read source.
---
=> indexer ingestion: logs for local files

scripts/update_all_snapshots.sh
=> scripts: add sui-framework and openapi to snapshot update script

crates/sui/src/sui_commands.rs
On Windows, binding the localnet IP address to 0.0.0.0 leads to issues and failing with a networking error for any CLI command when the localnet network is the default one. By default, when starting a Sui local network using `sui start` and when there is no default configuration, the command will generate a genesis including a `client.yaml` file that contains the localnet IP address set to `0.0.0.0`. This PR fixes that for the `client.yaml` file and should close #10371.
On a Windows box, run the binary and tested that it can connect to the network.
--- …
=> [CLI] Fix genesis client yaml file on Windows

crates/sui-graphql-rpc/src/server/builder.rs
Add health endpoint to version routes as well.
---
=> [cherry-pick][GraphQL] Cherry pick health endpoint on versioned routes to 2024.4.0

crates/sui-e2e-tests/tests/per_epoch_config_stress_tests.rs
=> Make per_epoch_config_stress_test more reliable

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_53.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_53.snap
=> Enable deny list v2 on testnet and mainnet

.github/workflows/changesets-ci.yml, .github/workflows/docs-ci.yml, .github/workflows/e2e.yml, .github/workflows/turborepo.yml, crates/sui-graphql-rpc/src/server/builder.rs, crates/sui-graphql-rpc/src/server/watermark_task.rs, crates/sui-graphql-rpc/tests/e2e_tests.rs
=> [cherry-pick][GraphQL] Gql cherry pick health endpoint to 2024.1.0

crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_50.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_52.snap
```
eugene@eugene-dev ~/code/sui (remove-whitespace) $ ./scripts/compatibility/check-protocol-compatibility.sh testnet
Found following versions on testnet:
86 1.28.3-3781a7e6b56c
9 1.28.2-08b50387a184
2 1.28.3-3781a7e6b5
1 1.28.3-3781a7e6b56c-dirty
Using most frequent version 1.28.3-3781a7e6b56c for compatibility check
Source commit: 68e59b5bee1196ee9eca2dc158c6fab9c58d8dee
Source branch: remove-whitespace
Checking protocol compatibility with testnet (3781a7e6b56c)
Checking out testnet snapshot files
Checking for changes to snapshot files matching *__Testnet_version_*
HEAD is now at 68e59b5bee remove whitespace
Running snapshot tests...
Updating crates.io index
Compiling serde_json v1.0.120
Compiling serde_derive_internals v0.29.1 …
```
=> remove whitespace

crates/sui-core/src/authority_server.rs, crates/sui-json-rpc/src/axum_router.rs
Nodes taking proxied connections can provide configuration that allows traffic controller to read the `x-forwarded-for` header so that we tally against the client rather than the proxy. Unfortunately we only supported this in code for authority server. This PR fixes that
Existing tests. Will later test against an rpc node behind a proxy.
---
=> [TrafficController] Add forwarded header parsing to axum server

crates/sui/src/client_commands.rs
Fix faucet for when requesting local coins as it returns created status code
---
=> [cli] Fix handling faucet request

.github/workflows/cargo-llvm-cov.yml
=> Fix code-coverage llvm-tools install

crates/sui-benchmark/src/fullnode_reconfig_observer.rs, crates/sui-benchmark/src/lib.rs, crates/sui-core/src/authority_aggregator.rs, crates/sui-core/src/authority_client.rs, crates/sui-core/src/checkpoints/mod.rs, crates/sui-core/src/quorum_driver/reconfig_observer.rs, crates/sui-core/src/transaction_orchestrator.rs, crates/sui-e2e-tests/tests/traffic_control_tests.rs, crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs, crates/sui-node/src/lib.rs
=> Make sure AuthAgg construction cannot fail

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.30.0 Version Bump

crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
There is already a orchestrator, no need to create new one in the test.
---
=> [test] Simplify transaction orchestrator tests

.github/workflows/cargo-llvm-cov.yml, Cargo.toml
Disable debug symbols when running `cargo llvm-cov` as it seems the CI run is OOM-ing when building `sui-e2e-tests`.
---
=> [codecov-ci] Disable debug symbols

docs/content/guides/developer/app-examples/tic-tac-toe.mdx, docs/site/src/css/custom.css, examples/tic-tac-toe/README.md
A README for the tic-tac-toe app example, derived from:
https://github.com/MystenLabs/multisig_tic-tac-toe/blob/main/README.md
And updates to the docs for the tic-tac-toe app example to reflect changes to
modernise the guide and bring all its source code into the `sui`
mono-repo.
This is the last major example that lived in the `sui_programmability` directory.
:eyes:
- #18525 
- #18526 
- #18557 
---
=> [Examples/Docs] Tic-tac-toe

Cargo.lock, Cargo.toml
=> chore: update fastcrypto and serde_with

external-crates/move/crates/move-analyzer/prettier-move/src/cst/function/BlockItem.ts, external-crates/move/crates/move-analyzer/prettier-move/src/cst/function/Expression.ts, external-crates/move/crates/move-analyzer/prettier-move/src/cst/use/UseDeclaration.ts, external-crates/move/crates/move-analyzer/prettier-move/src/tree.ts, external-crates/move/crates/move-analyzer/prettier-move/src/utilities.ts, external-crates/move/crates/move-analyzer/prettier-move/tests/control-flow/if_expression.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/control-flow/if_expression.move, external-crates/move/crates/move-analyzer/prettier-move/tests/functions/expression.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/functions/let_statement.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/mega-test/other.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/mega-test/other.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/authenticator_state.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/coin.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/dynamic_field.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/dynamic_object_field.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/kiosk.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/priority_queue.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/random.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/sui.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/test_scenario.exp.move, external-crates/move/crates/move-analyzer/prettier-move/tests/sui-framework/tx_context.exp.move
=> better let

crates/sui-core/src/unit_tests/data/entry_point_types/Move.lock, crates/sui-core/src/unit_tests/data/entry_point_vector/Move.lock, sdk/typescript/package.json, sdk/typescript/test/e2e/data/coin_metadata/Move.lock, sdk/typescript/test/e2e/data/dynamic_fields/Move.lock, sdk/typescript/test/e2e/data/id_entry_args/Move.lock, sdk/typescript/test/e2e/data/serializer/Move.lock, sdk/typescript/test/e2e/utils/setup.ts
=> avoid rebuilding sui cli during tests

crates/mysten-network/src/multiaddr.rs, crates/sui/src/validator_commands.rs
as title and self-descriptive.
tested locally.
---
=> Add more addresses checks for validator tool

crates/sui-core/src/authority/epoch_start_configuration.rs
=> [Cherry Pick] Re-order flags to match order in v1.28 (#18682)

.changeset/late-peas-greet.md, sdk/bcs/src/bcs-type.ts, sdk/typescript/src/client/client.ts, sdk/typescript/src/transactions/Transaction.ts
=> [ts sdk] Make symbol types not unique between versions

crates/sui-core/src/validator_tx_finalizer.rs
=> Fix flaky validator_tx_finalizer tests

sdk/deepbook-v3/src/client.ts, sdk/deepbook-v3/src/transactions/deepbook.ts, sdk/deepbook-v3/src/transactions/deepbookAdmin.ts, sdk/deepbook-v3/src/transactions/flashLoans.ts, sdk/deepbook-v3/src/transactions/governance.ts, sdk/deepbook-v3/src/types/index.ts, sdk/deepbook-v3/src/utils/config.ts, sdk/deepbook-v3/src/utils/constants.ts
=> SDK improvements

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_53.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_53.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_53.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, sdk/graphql-transport/src/methods.ts
the next version should be 53 instead of 54. Also update MAX_VERSION
---
=> change protocol version 54 to 53

sdk/deepbook-v3/package.json, sdk/deepbook-v3/src/client.ts, sdk/deepbook-v3/src/utils/config.ts, sdk/deepbook-v3/test/client.test.ts, sdk/deepbook-v3/test/env.d.ts, sdk/deepbook-v3/test/helper/constants.ts, sdk/deepbook-v3/test/helper/toml.ts, sdk/deepbook-v3/test/helper/utils.ts, sdk/deepbook-v3/test/setup.ts, sdk/deepbook-v3/test/tsconfig.json
=> test suite

sdk/deepbook-v3/src/client.ts, sdk/deepbook-v3/src/transactions/balanceManager.ts, sdk/deepbook-v3/src/transactions/deepbook.ts, sdk/deepbook-v3/src/transactions/deepbookAdmin.ts, sdk/deepbook-v3/src/transactions/flashLoans.ts, sdk/deepbook-v3/src/transactions/governance.ts
Add function definitions for Deepbook typescript sdk
No testing needed, comments only
---
=> Comments for SDK

crates/sui-bridge-indexer/src/eth_worker.rs, crates/sui-bridge-indexer/src/lib.rs, crates/sui-bridge-indexer/src/migrations/2024-07-02-101842_error_transaction/down.sql, crates/sui-bridge-indexer/src/migrations/2024-07-02-101842_error_transaction/up.sql, crates/sui-bridge-indexer/src/models.rs, crates/sui-bridge-indexer/src/postgres_manager.rs, crates/sui-bridge-indexer/src/schema.rs, crates/sui-bridge-indexer/src/sui_transaction_handler.rs, crates/sui-bridge-indexer/src/sui_worker.rs, crates/sui-bridge-indexer/src/types.rs
=> [bridge indexer] - record bridge txn errors

docs/content/standards/wallet-standard.mdx
=> Grammar fix on the Wallet Standard page

.changeset/pink-wombats-appear.md, sdk/typescript/src/transactions/executor/caching.ts, sdk/typescript/src/transactions/executor/parallel.ts, sdk/typescript/src/transactions/executor/serial.ts, sdk/typescript/test/e2e/object-cache.test.ts, sdk/typescript/test/e2e/parallel-executor.test.ts, sdk/typescript/test/e2e/serial-executor.test.ts
=> Add waitForLastTransaction to all executor classes

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_53.snap
=> Enable consensus commit prologue V3 on mainnet

.changeset/silver-tomatoes-refuse.md, sdk/docs/pages/typescript/transaction-building/basics.mdx, sdk/typescript/src/transactions/pure.ts, sdk/typescript/test/e2e/utils/setup.ts, sdk/typescript/test/unit/pure-serialization.test.ts
=> add tx.pure.vector and tx.pure.option

.github/PULL_REQUEST_TEMPLATE.md, scripts/release_notes.py
Add REST API section to release notes
👀
=> Add REST API section to release notes

external-crates/move/crates/move-disassembler/src/disassembler.rs
Always pick whole UTF8 characters.
Tested against a package containing a UTF8 constant.
---
=> [Disassembler] Fix string contraction logic

crates/sui-metric-checker/src/lib.rs, crates/sui-metric-checker/src/query.rs
This should tolerate temporary spikes better. If we want to check to ensure there is no spikes, we can create a new query type in future.
CI
---
=> Compute median instead of average for range queries in metrics checker

crates/sui-framework-tests/src/unit_tests.rs, examples/move/transfer-to-object/common/Move.toml, examples/move/transfer-to-object/owned-no-tto/Move.toml, examples/move/transfer-to-object/shared-no-tto/Move.toml, examples/move/transfer-to-object/shared-with-tto/Move.toml, examples/trading/contracts/demo/Move.toml, examples/trading/contracts/demo/sources/demo_bear.move, examples/trading/contracts/escrow/Move.toml, examples/trading/contracts/escrow/sources/owned.move, examples/trading/contracts/escrow/sources/shared.move
All Move examples should depend on the Sui framework in the repo, so that this framework is compatible with the compiler that is being used to compile them -- especially when running CI on non-main branches.
```
sui-framework-tests$ cargo nextest run
```
---
=> [pick #18463, #18573][Examples/Move] Fix Move Example test set-up

crates/sui-core/src/consensus_adapter.rs, crates/sui-core/src/validator_tx_finalizer.rs, crates/sui-node/src/lib.rs, crates/sui-types/src/committee.rs
Add incremental delays for validators so that they wake up at different times for efficiency.
Added a test
---
=> [tx-finalizer] Add validator leader delay

docs/content/references/cli/move.mdx
Update the Sui Move CLI docs to have the latest CLI options
manual
---
=> [docs] update sui move cli options

docker/sui-network/docker-compose-antithesis.yaml
- Reduce # of commands in each batch payment txn and its TPS to 1.
- Reduce TPS of shared and owned obj txns to 1 as well, since sui surfer is already running.
- Update logging config for consensus.
https://github.com/MystenLabs/sui-operations/actions/runs/9997864674
---
=> Tweak antithesis configs

crates/sui-core/src/authority/authority_per_epoch_store.rs, crates/sui-core/src/epoch/randomness.rs, crates/sui-protocol-config/src/lib.rs, crates/sui-types/src/messages_consensus.rs
=> [beacon] Remove dkg v0

.github/workflows/build-suiop-cli.yml
Update dispatch event-type to be more specific. See https://github.com/MystenLabs/sui-operations/pull/3967
👀
=> Update suiop-cli-binaries workflow

external-crates/move/crates/move-compiler/src/typing/core.rs, external-crates/move/crates/move-compiler/src/typing/translate.rs, external-crates/move/crates/move-compiler/tests/move_2024/matching/enum_visibility.exp, external-crates/move/crates/move-compiler/tests/move_2024/parser/invalid_macro_locs.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/macro_visibility_higher_order_error.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/macro_visibility_higher_order_error.move, external-crates/move/crates/move-compiler/tests/move_2024/typing/macros_visibility_not_checked_called.exp, external-crates/move/crates/move-compiler/tests/move_check/typing/native_structs_pack_unpack.exp, external-crates/move/crates/move-compiler/tests/move_check/typing/pack_private_with_field.exp, external-crates/move/crates/move-compiler/tests/move_check/typing/pack_unpack_private.exp, external-crates/move/crates/move-compiler/tests/sui_mode/id_leak/private_pack.exp
This adds information about macro expansion to visibility errors, when appropriate.
It also slightly reforms how visibility errors for data structures are reported to unify reporting them and function visibility errors.
Updated tests, plus some new ones.
---
=> [move][move-2024] Revise some visibility errors, add macro information

crates/sui-e2e-tests/tests/validator_tx_finalizer_e2e_tests.rs
=> Increase timeout

sdk/deepbook-v3/.npmignore, sdk/deepbook-v3/examples/deepbookMarketMaker.ts, sdk/deepbook-v3/examples/tsconfig.json, sdk/deepbook-v3/examples/useDeepbookClient.ts, sdk/deepbook-v3/src/client.ts, sdk/deepbook-v3/src/transactions/balanceManager.ts, sdk/deepbook-v3/src/transactions/deepbook.ts, sdk/deepbook-v3/src/transactions/deepbookAdmin.ts, sdk/deepbook-v3/src/transactions/flashLoans.ts, sdk/deepbook-v3/src/transactions/governance.ts, sdk/deepbook-v3/src/types/index.ts, sdk/deepbook-v3/src/utils/config.ts, sdk/deepbook-v3/src/utils/constants.ts, sdk/deepbook-v3/test/helper/utils.ts
Examples usage for Deepbook SDK
Tested on local, will get feedback from integrators for improvements
---
=> Examples for Deepbook SDK

apps/wallet/src/shared/experimentation/features.ts, apps/wallet/src/ui/app/components/coin-icon/index.tsx, apps/wallet/src/ui/app/hooks/useCoinMetadataOverride.ts, apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
=> [wallet]: add token metadata overrides

crates/sui-bridge/src/events.rs
=> [bridge] add url update event in rust

crates/sui-core/src/validator_tx_finalizer.rs
This PR adds a cap to how long a validator can wait before waking up. It makes it slightly easier to reason about the max amount of time these kinds of threads will stay alive.
---
=> [tx-finalizer] Cap validator wait time

crates/sui-types/src/messages_consensus.rs
=> [beacon] Print a fixed error message instead of a panic

crates/typed-store/src/rocks/mod.rs
If a DB has a large number of column families, and each of them receives a large amount of writes, there will be a large number of memtable flushes and compactions that need to be processed. Only allowing 4 concurrent processing per DB seems not enough, as observed on some column families stopping writes because of too many memtables pending to flush. The default is increased to 8.
Allow the value to be overridden by env var, so operators can increase / decrease the value on their own.
Remove the `set_max_background_jobs()` call since it effect is overwritten by the subsequent `increase_parallelism()` call.
Private testnet.
---
For each box you select, include information …
=> [DB] increase parallelism per db from 4 to 8, and allow env var override

docs/content/guides/developer/nft/nft-rental.mdx
Updates a broken link in the [related links](https://docs.sui.io/guides/developer/nft/nft-rental#related-links) section
Run locally the doc site and tested that the link has been successfully updated.
---
=> [Docs - NFT Rental] Updates broken link

Cargo.lock, Cargo.toml, crates/sui-rest-api/openapi/openapi.json, crates/sui-rest-api/src/accept.rs, crates/sui-rest-api/src/accounts.rs, crates/sui-rest-api/src/checkpoints.rs, crates/sui-rest-api/src/coins.rs, crates/sui-rest-api/src/committee.rs, crates/sui-rest-api/src/health.rs, crates/sui-rest-api/src/info.rs, crates/sui-rest-api/src/lib.rs, crates/sui-rest-api/src/objects.rs, crates/sui-rest-api/src/openapi.rs, crates/sui-rest-api/src/reader.rs, crates/sui-rest-api/src/system.rs, crates/sui-rest-api/src/transactions/execution.rs, crates/sui-rest-api/src/transactions/mod.rs
=> rest: update openapi spec for existing endpoints

external-crates/move/crates/move-compiler/tests/move_2024/typing/macro_visibility_enum_error.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/macro_visibility_enum_error.move, external-crates/move/crates/move-compiler/tests/move_2024/typing/macro_visibility_function_error.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/macro_visibility_function_error.move, external-crates/move/crates/move-compiler/tests/move_2024/typing/macro_visibility_struct_error.exp, external-crates/move/crates/move-compiler/tests/move_2024/typing/macro_visibility_struct_error.move
Add tests I wrote but forgot to include on #18735 😭 
New tests
---
=> [move][move-2024] Add macro visibility error tests 

deny.toml
This specific vulnerability does not seem to impact Sui. Upgrading the affect package involves upgrading dependencies which will take more time.
CI
---
=> Ignore RUSTSEC-2024-0358

docs/content/standards/wallet-standard.mdx
=> [docs] Updates to wallet standard

docs/content/guides/developer/advanced/custom-indexer.mdx, docs/content/snippets/custom-indexer-source.mdx, docs/site/src/plugins/inject-code/injectLoader.js
=> [docs] Retrieving edits

external-crates/move/crates/move-compiler/src/linters/constant_naming.rs, external-crates/move/crates/move-compiler/src/linters/mod.rs, external-crates/move/crates/move-compiler/tests/linter/incorrect_constant_naming.exp
Function Updates:
Updated the known_filters function to use the LinterDiagnosticCategory::Style enum variant.
Simplified the linter_visitors function by combining the None and Default cases into a single match arm, reducing redundancy.
Naming Consistency:
Ensured consistent naming conventions throughout the code.
Removed Unused Code:
Eliminated any unused code or imports to improve code cleanliness.
Existing linter unit tests
---
=> [Linter] Refactor: Optimize Linter Configuration and Visitor Generation

crates/sui-bridge/src/action_executor.rs, crates/sui-bridge/src/node.rs
As title. In follow up PRs, we will introduce monitoring component to swap the aggregator when there are changes to committee members (e.g. url change)
existing tests.
---
=> [bridge] store bridge authority aggregator in ArcSwap

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_53.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_53.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_53.snap
=> Revert "Enable random beacon on mainnet"

consensus/core/src/commit_syncer.rs
Validators with limited network need larger timeout for the requests to succeed. In future, we will add support for partial results.
n/a
---
=> [Consensus] increase commit syncer fetch timeouts

docs/content/concepts/sui-architecture/epochs.mdx, docs/content/concepts/sui-architecture/sui-security.mdx, docs/content/concepts/sui-move-concepts/packages/automated-address-management.mdx
Hello
I found several typos in your docs.
Hope it helps.
=> docs: fix spelling issues

scripts/simtest/simtest-run.sh
Until timeout issues can be debugged.
=> Skip validator_tx_finalizer_e2e_tests in simtest-run.sh

Cargo.lock, Cargo.toml, consensus/core/src/network/connection_monitor.rs, crates/sui-network/src/state_sync/server.rs, narwhal/network/src/connectivity.rs, scripts/simtest/cargo-simtest, scripts/simtest/config-patch
=> chore: update anemo and quinn

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui Version Bump v1.31

apps/wallet/src/background/accounts/zklogin/utils.ts, crates/sui-package-resolver/src/lib.rs, examples/move/crypto/bls_signature/sources/example.move, examples/tic-tac-toe/README.md, external-crates/move/crates/move-vm-runtime/src/loader.rs, sdk/docs/pages/typescript/executors.mdx, sdk/docs/pages/typescript/migrations/sui-1.0.mdx, sui-execution/README.md
=> chore: fix some comments

Cargo.lock, deny.toml
=> cargo-deny: update deny.toml to clear out warnings

crates/sui-bridge/src/monitor.rs
as title 
added unit tests
---
=> [bridge] let monitor handle blocklist event

crates/sui-snapshot/src/reader.rs
=> log the file that we fail to fetch

docker/sui-indexer-tidb/Dockerfile
add dockerfile for tidb indexer
tsia
---
=> [docker/tidb-indexer]

crates/sui-core/src/execution_cache/writeback_cache.rs
See comments in code for explanation.
I haven't been able to repro this in a test, but I'm pretty confident about the source of the bug.
=> Fix edge-case in assert which can be triggered from jsonrpc

crates/sui-core/src/consensus_manager/mysticeti_manager.rs, crates/sui-core/src/mysticeti_adapter.rs
Getting a consensus client only fails when the validator has not finished initializing consensus. This issue can and should be detected inside consensus instead of through client.
Also, clear consensus client at the end of epochs.
CI
---
=> Remove wait timeout from LazyMysticetiClient

scripts/simtest/config-patch
=> simtest: fix config-patch

apps/wallet/src/ui/app/components/sui-apps/Banner.tsx, apps/wallet/src/ui/app/pages/home/interstitial/index.tsx
- Rounded corners in apps list
- Bake in centering and padding for interstitial 
---
=> update promo setup

crates/sui-core/src/authority.rs, crates/sui-core/src/checkpoints/causal_order.rs, crates/sui-core/tests/staged/sui.yaml, crates/sui-graphql-rpc/schema/current_progress_schema.graphql, crates/sui-graphql-rpc/src/types/unchanged_shared_object.rs, crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap, crates/sui-types/src/digests.rs, crates/sui-types/src/effects/effects_v1.rs, crates/sui-types/src/effects/effects_v2.rs, crates/sui-types/src/effects/mod.rs, crates/sui-types/src/execution.rs, crates/sui-types/src/execution_status.rs, crates/sui-types/tests/staged/exec_failure_status.yaml, sui-execution/v0/sui-adapter/src/temporary_store.rs, sui-execution/v1/sui-adapter/src/temporary_store.rs, sui-execution/v2/sui-adapter/src/temporary_store.rs
Picking parts of two changes that alter the unchanged shared object type, which can impact GraphQL's ability to deserialize transaction effects
---
=> [pick #17200, #18501][GraphQL] Unchanged Shared Objects

crates/sui-core/src/authority_server.rs
The PR adds several metrics and logging to Soft Bundle.
A node operator will have the ability to understand what bundles are submitted, as well as the content.
This can be particularly useful when tracing down a transaction.
---
=> Soft bundle basic observability

docs/content/guides/operator/snapshots.mdx
Got some feedback from a validator operator that the docs were a bit confusing, attempting to improve them.
=> [docs] update snapshot docs based off operator feedback

Cargo.toml, crates/sui-rest-api/src/client/mod.rs, crates/sui-rest-api/src/client/sdk.rs, crates/sui-rest-api/src/system.rs, crates/sui-rest-api/src/transactions/mod.rs
=> rest: implement client with support for all existing endpoints

Cargo.lock, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-rpc/Cargo.toml
Bump prod version, just in case we need this branch again.
---
=> [GraphQL] Gql bump version prod to 2024.4.4

.changeset/beige-windows-build.md, sdk/typescript/scripts/generate.ts, sdk/typescript/src/client/types/generated.ts, sdk/typescript/src/client/types/params.ts, sdk/wallet-standard/src/features/suiSignAndExecuteTransactionBlock.ts
=> [sdk] deprecate requestType option in SDK

crates/sui-sdk/src/wallet_context.rs
Handle unwrap in wallet context
---
=> [Rust SDK] Handle unwrap in wallet context

docs/content/sidebars/standards.js, docs/content/standards/deepbookv3-sdk.mdx, docs/content/standards/deepbookv3-sdk/flash-loans.mdx, docs/content/standards/deepbookv3-sdk/orders.mdx, docs/content/standards/deepbookv3-sdk/pools.mdx, docs/content/standards/deepbookv3-sdk/staking-governance.mdx, docs/content/standards/deepbookv3-sdk/swaps.mdx
=> [docs] DeepBook SDK

.changeset/warm-elephants-marry.md, sdk/deepbook-v3/src/utils/constants.ts
Update Deepbook SDK for redeployment
Tested on testnet, all pool order placing is accurate
---
=> SDK Updates

crates/sui-benchmark/tests/simtest.rs
This reproduces prior bugs with random beacon.
Manual repro testing on old commits.
=> Add long-epoch, rolling restart simtest

crates/suiop-cli/src/cli/ci/image.rs
make it a bit easier to use
works
```bash
» suiop ci image list --repo sui-operations --image test
Requested list for repo: sui-operations
╭──────┬──────╮
│ name │ tags │
├──────┼──────┤
```
---
=> [suiop] add aliases for image building

Cargo.lock
Update `time` crate to a newer version to avoid compilation errors (#18904)
---
=> [chore][cherry-pick] #18904 - update `time` crate version - cherry pick into `devnet` branch

binary-build-list.json
[suiop] add to internal binaries release list
=> [suiop] add to internal binaries release list

.changeset/breezy-dragons-sing.md, .changeset/two-toes-watch.md, sdk/bcs/src/bcs.ts, sdk/typescript/src/bcs/effects.ts, sdk/typescript/test/e2e/object-cache.test.ts
=> [ts sdk] Add PerEpochConfig and Cancelled to UnchangedSharedKind

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_54.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_54.snap
Says by the title. Going out in 1.3.1
---
=> Turn on shared object congestion control in mainnet

crates/sui-node/src/lib.rs
=> Enable tx finalizer on mainnet

binary-build-list.json
Revert #18910
Unbreaking https://github.com/MystenLabs/sui-operations/actions/runs/10278960227/job/28445039800
Will fix later
👀
=> Revert #18910

Cargo.toml
=> serde_json: don't use the arbitrary_precision feature

crates/sui-e2e-tests/tests/traffic_control_tests.rs
Temporary disabling until further tuned by @williampsmith 
CI
---
=> [chore] disable flaky test

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> sui v1.32.0 version bump

external-crates/move/crates/move-docgen/tests/sources/enums_test.move, external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_inline.md, external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_inline_no_fold.md, external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_separate.md, external-crates/move/crates/move-model/src/model.rs, external-crates/move/crates/move-model/src/ty.rs
Fixes an issue around globalizing type signatures in the Move model for enums.
Added tests to make sure we handle enums types in these cases.
=> [move] Bugfix in Move model for enums

crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
=> feat: enable karrier one for testnet/mainnet

crates/sui-types/src/deny_list_v2.rs
=> [cherry-pick][denylist] Fix sign check early return

.changeset/weak-ears-nail.md, sdk/deepbook-v3/src/transactions/balanceManager.ts, sdk/deepbook-v3/src/utils/constants.ts
Update balance manager and constants in SDK
Test in testnet and feedback from integrators
=> Deepbook SDK Update

crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-types/src/storage/mod.rs
Picks https://github.com/MystenLabs/sui/pull/18958
---
=> [cherrypick] Fix fullnode event resolution

apps/wallet/src/ui/app/components/address-input/index.tsx
Prevent showing errors during isValidator.
---
=> Fix isValidating state from showing invalid address 

docs/site/src/pages/index.js
Changing order of landing page links. Testing effects on page views. Reexamining specific links used is beyond scope.
Previous
Current
---
=> [docs][site] Landing page links

dapps/multisig-toolkit/src/components/connect.tsx
=> Fix cmdk not rendering account list

dapps/multisig-toolkit/src/components/ui/command.tsx
=> [multisig toolkit] fix mouse events in account selector

crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_deny_multiple_coin_types.exp, crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_deny_multiple_coin_types.move, crates/sui-types/src/deny_list_v2.rs
Will add test in a separate PR.
---
=> [denylist] Fix sign check early return

crates/sui-bridge-indexer/src/eth_bridge_indexer.rs, crates/sui-bridge-indexer/src/indexer_builder.rs
=> [bridge-indexer] - simplify bridge generic

crates/sui-e2e-tests/tests/full_node_tests.rs, crates/sui-e2e-tests/tests/move_test_code/sources/init_with_events.move, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-types/src/storage/mod.rs
Introduce a new struct that contains both local package store and newly published packages. This allows us to resolve new events using both.
I will add some tests later.
---
=> Fix fullnode event resolution

docs/content/guides/developer/advanced/custom-indexer.mdx, docs/content/guides/developer/sui-101/using-events.mdx
Code inject link was broken. Renaming to fix it. Also added deprecation warning for event subscription
by inspection
---
=> [docs] change custom indexer example Cargo.toml capitalization

crates/sui-core/src/authority_server.rs, crates/sui-e2e-tests/tests/traffic_control_tests.rs, crates/sui-json-rpc/src/axum_router.rs
=> [TrafficControl] Handle invalid client sig on rpc node

crates/sui-indexer/src/models/objects.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/src/types.rs
All the other fields can be derived from Object. Remove them.
CI
---
=> [indexer] Simplify IndexedObject

chocolatey/sui.nuspec
=> Fix chocolatey binary path

sdk/docs/pages/typescript/index.mdx
import path is @mysten/sui/transaction**s**
=> Update import path for @mysten/sui/transactions

Cargo.lock, Cargo.toml, scripts/simtest/config-patch
=> chore: update quinn-proto

crates/sui-core/src/authority_aggregator.rs
=> authority_aggregator: sample 5 validators for objects contents

.github/workflows/cargo-llvm-cov.yml
Exclude sui-bridge tests for code coverage
https://github.com/MystenLabs/sui/actions/runs/10407677341/job/28823468147
=> Exclude sui-bridge tests for code coverage

crates/sui-indexer/src/store/pg_indexer_store.rs
title, per a related slack thread 
CI
---
=> indexer minor: more efficient total tx query

.github/workflows/release.yml
Fail if publish to chocolatey fails
👀
=> Fail if publish to chocolatey fails

.github/workflows/release.yml, chocolatey/sui.nuspec
Update chocolatey sui content
👀
=> Update chocolatey sui content

.changeset/unlucky-lamps-design.md, sdk/deepbook-v3/src/utils/constants.ts
Deepbook SDK Constants Update
Testnet
---
=> Deepbook SDK Constants Update

crates/sui-indexer/src/db.rs
=> indexer: DB reset to handle incomplete migration history #19019

crates/sui-light-client/src/proof.rs
Fixed documentation spelling and grammar
Proof read.
=> [light client] Fix light client doc spelling

.changeset/small-months-shop.md, sdk/deepbook-v3/src/utils/constants.ts
Upgrade Deepbook SDK Constant
Testnet
=> Upgrade Deepbook SDK Constant

sdk/typescript/test/e2e/id-entry-args.test.ts, sdk/typescript/test/e2e/multisig.test.ts, sdk/typescript/test/e2e/objects.test.ts, sdk/typescript/test/e2e/txn-builder.test.ts
=> [sdk e2e] fix some more flaky e2e tests

.changeset/perfect-peaches-retire.md, sdk/docs/pages/typescript/cryptography/keypairs.mdx, sdk/docs/pages/typescript/transaction-building/basics.mdx, sdk/typescript/src/verify/verify.ts, sdk/typescript/src/zklogin/publickey.ts
=> Add docs on zklogin signature verification and using waitForTransaction

.changeset/silly-berries-rush.md, .changeset/ten-panthers-shave.md, sdk/docs/pages/typescript/executors.mdx, sdk/typescript/src/transactions/executor/parallel.ts, sdk/typescript/src/transactions/executor/serial.ts
=> [sdk] Add default budget to serial transaction executor

.changeset/five-ads-dream.md, apps/wallet/vitest.config.ts, sdk/deepbook/vitest.config.ts, sdk/graphql-transport/vitest.config.ts, sdk/kiosk/vitest.config.ts, sdk/suins-toolkit/vitest.config.ts, sdk/typescript/src/transactions/Arguments.ts, sdk/typescript/src/transactions/Transaction.ts, sdk/typescript/src/transactions/object.ts, sdk/typescript/test/e2e/object-cache.test.ts, sdk/typescript/test/e2e/parallel-executor.test.ts, sdk/typescript/test/e2e/serial-executor.test.ts, sdk/typescript/test/unit/object-inputs.test.ts, sdk/typescript/vitest.config.ts
=> [ts sdk] Add new tx.object methods

Cargo.lock, Cargo.toml, crates/sui-rest-api/openapi/openapi.json
=> chore: update rust-sdk

.changeset/twelve-games-shake.md, sdk/enoki/src/EnokiClient/index.ts, sdk/enoki/src/EnokiClient/type.ts, sdk/enoki/src/index.ts
=> [enoki-sdk] Add sdk methods for managing enoki subnames

apps/wallet/src/ui/app/pages/home/nfts/VisualAssets.tsx
https://linear.app/mysten-labs/issue/APPS-246/remove-nft-name-andor-object-id-from-thumbnail-image
---
=> remove hover label

crates/sui-rest-api/src/checkpoints.rs
=> rest: cleanup

crates/sui-indexer/README.md, crates/sui-indexer/src/main.rs
=> indexer:add experimental warning

crates/sui-indexer/src/handlers/pruner.rs
This PR changes the pruning epoch for the objects_history table to 2, instead of the epochs_to_keep from the config.
To do this more efficiently I made some change to the pruning loop, where instead of checking whether the current max_epoch is within the range, I kept a local var to track the most recent max_epoch. We proceed to pruning whenever that number changes.
We first process all partitions, which will cover the objects_history; and then we cover everything else.
I hope we have tests?
--- …
=> [indexer] Use different pruning policy for objects_history

Cargo.lock, crates/sui-graphql-e2e-tests/tests/call/simple.exp, crates/sui-graphql-rpc/Cargo.toml
=> [GraphQL] Gql 2024.4.0 bump version

crates/suiop-cli/src/cli/ci/mod.rs
=> [suiop] fix dup alias issue

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.33.0 version bump

crates/sui/src/sui_commands.rs
Fixed variable error in printing logs
Fixed variable error in printing logs
---
=> Update sui_commands.rs. Fixed variable error in printing logs

docs/content/standards/deepbookv3-sdk.mdx
Demo code in Deepbook doc is not working properly. Fix some syntax bugs.
No test included. Doc fix on code syntax issue.
---
- [√] REST API:
=> Fix syntax issues in deepbook-v3 doc.

.changeset/dirty-masks-taste.md, sdk/deepbook-v3/src/client.ts, sdk/deepbook-v3/src/transactions/deepbook.ts, sdk/deepbook-v3/src/utils/constants.ts
Pool Book Param function and package upgrade
Testnet
=> Pool Book Param and package upgrade

.github/workflows/release-notes-generator.yml
Add run name for generate release notes workflow
👀
=> Add run name for generate release notes workflow

.github/workflows/release.yml
=> Trigger on pre-released

crates/sui-benchmark/src/workloads/shared_counter.rs, crates/sui-benchmark/src/workloads/shared_object_deletion.rs
Otherwise we don't see the error from quorum driver.
CI
---
=> [Bench] emit error from shared counter creation failure

Cargo.lock, Cargo.toml
Update anemo to a version where dns resolution can no longer block the async runtime.
---
=> chore: update anemo to e609f7697e

.changeset/lucky-cobras-dance.md, sdk/deepbook-v3/src/client.ts
=> Try Catch in SDK

scripts/release_notes.py
=> [Release Notes] Revert support for rebased commits for now

.changeset/chatty-bears-switch.md, sdk/zksend/src/index.ts, sdk/zksend/src/links/builder.ts, sdk/zksend/src/links/claim.ts, sdk/zksend/src/links/get-sent-transactions.ts, sdk/zksend/src/links/list-created-links.ts, sdk/zksend/src/links/zk-bag.ts, sdk/zksend/src/wallet/channel/index.ts, sdk/zksend/src/wallet/index.ts, sdk/zksend/src/wallet/types.ts
=> Add testnet support to stashed

crates/sui-storage/src/bin/http_kv_tool.rs, crates/sui-storage/src/http_key_value_store.rs, crates/sui-storage/tests/key_value_tests.rs, crates/sui-types/src/digests.rs
e.g.
`http_kv_tool decode-key -u https://transactions.sui.io/mainnet/cP1pPYHRXroEHhXrsD_uy-kbAcH5lZguUEPfocX0zXsIsR0GAAAAAA/ob`
=> Add decode-key command to http_kv_tool

.changeset/sour-ducks-drive.md, sdk/dapp-kit/src/hooks/wallet/useStashedWallet.ts
=> Stashed wallet dapp-kit

Cargo.lock, crates/sui-bridge-indexer/src/main.rs, crates/sui-indexer-builder/Cargo.toml, crates/sui-indexer-builder/src/indexer_builder.rs
=> [bridge-indexer] some logs and todos

crates/typed-store/src/metrics.rs, crates/typed-store/src/rocks/mod.rs
#19112: this emits more metrics from rocksdb, to help with investigations into external fullnode write stalls.
CI
---
--- …
=> Cherrypick additional rocksdb metrics

.github/workflows/bridge.yml, bridge/evm/.gitignore, bridge/evm/README.md, bridge/evm/foundry.toml, bridge/evm/remappings.txt, bridge/evm/soldeer.lock
=> Reintroduce soldeer dependency management and pin foundry version 

bridge/incentivize_testnet_faq.md, docs/content/concepts/transactions.mdx, nre/docker/README.md, nre/validator_tool.md, sdk/docs/pages/kiosk/from-v1.mdx
=> [docs] Fix typos

.changeset/yellow-wolves-tell.md, sdk/deepbook-v3/src/utils/constants.ts
Package updates with latest changes
Testnet
=> Testnet update after campaign

.changeset/clever-suits-eat.md, sdk/docs/pages/dapp-kit/stashed.mdx, sdk/docs/pages/dapp-kit/wallet-provider.mdx, sdk/docs/pages/zksend/dapp.mdx, sdk/docs/pages/zksend/link-builder.mdx, sdk/zksend/src/links/builder.ts, sdk/zksend/src/links/claim.ts
=> Update zkSend docs

Cargo.lock, crates/suiop-cli/Cargo.toml, crates/suiop-cli/src/cli/incidents/mod.rs, crates/suiop-cli/src/cli/incidents/pd.rs, crates/suiop-cli/src/cli/incidents/slack.rs, crates/suiop-cli/src/cli/lib/utils.rs, crates/suiop-cli/src/lib.rs, crates/suiop-cli/src/main.rs
Allow interactive incident review selection with suiop
Successful e2e test in #test-notifications
---
=> [suiop] add interactive incident selection

crates/sui-data-ingestion-core/src/worker_pool.rs
Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.
For each box you select, include information after the relevant heading
that describes the impact of your changes that a user might notice and
any actions they must take to implement updates.
=> [data ingestion] handle termination in worker pool

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.34.0 Version Bump

crates/sui-core/src/authority_aggregator.rs
Change AuthorityAggregator to always pass through request_events flag, even to the validators we aren't sampling for objects.
In addition, up the sample size of validators to 10 and log when we get unlucky and reach quorum without having recieved input or output objects.
---
=> authority_aggregator: always request for events when asked

.github/workflows/release.yml
Add debug builds back for all platforms
https://github.com/MystenLabs/sui/actions/runs/10741384417/job/29791637040
=> Add debug builds back for all platforms

.github/workflows/validate-release-notes-pre-land.yml
Check for PR number before running release notes check
👀
=> Check for PR number before running release notes check

crates/sui-indexer/migrations/pg/2024-09-05-164455_full_objects_history/down.sql, crates/sui-indexer/migrations/pg/2024-09-05-164455_full_objects_history/up.sql, crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/models/objects.rs, crates/sui-indexer/src/schema/mod.rs, crates/sui-indexer/src/schema/pg.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
This is a redo of https://github.com/MystenLabs/sui/pull/18994, but instead of merging to parking branch, merge it to main.
CI
---
=> [Indexer] Add full_objects_history table

bridge/runbook/validator_runbook.md
Add instructions for validators to register bridge metadata.
---
=> [doc] add validator runbook for bridge

crates/sui-benchmark/src/drivers/bench_driver.rs
Follow up to this [comment](https://github.com/MystenLabs/sui/pull/19235#discussion_r1746372963)
=> [benchmark] Add error types

external-crates/move/Cargo.lock, external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs, external-crates/move/crates/move-compiler/src/cfgir/translate.rs, external-crates/move/crates/move-compiler/src/cfgir/visitor.rs, external-crates/move/crates/move-compiler/src/command_line/compiler.rs, external-crates/move/crates/move-compiler/src/hlir/ast.rs, external-crates/move/crates/move-compiler/src/linters/abort_constant.rs, external-crates/move/crates/move-compiler/src/linters/constant_naming.rs, external-crates/move/crates/move-compiler/src/linters/meaningless_math_operation.rs, external-crates/move/crates/move-compiler/src/linters/unnecessary_while_loop.rs, external-crates/move/crates/move-compiler/src/linters/unneeded_return.rs, external-crates/move/crates/move-compiler/src/shared/mod.rs, external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/coin_field.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/collection_equality.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/custom_state_change.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/freeze_wrapped.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/freezing_capability.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/missing_key.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/public_mut_tx_context.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/public_random.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/self_transfer.rs, external-crates/move/crates/move-compiler/src/sui_mode/linters/share_owned.rs, external-crates/move/crates/move-compiler/src/sui_mode/typing.rs, external-crates/move/crates/move-compiler/src/typing/ast.rs, external-crates/move/crates/move-compiler/src/typing/match_analysis.rs, external-crates/move/crates/move-compiler/src/typing/translate.rs, external-crates/move/crates/move-compiler/src/typing/visitor.rs, external-crates/move/crates/move-compiler/tests/move_check_testsuite.rs
- Made all visitors immutable
- Added mutable variant for typing, but the lints cant use it
- Gave the CFG to the construction of cfgir/absint visitors 
- helpful for filtering 
- non-functional 
---
=> [move-compiler] Small changes to visitors for upcoming improvements

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_58.snap
=> finalize bridge committee on mainnet in protocol version 58

crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_58.snap
https://github.com/MystenLabs/sui/pull/19246
---
=> Cherry pick 19246 (finalize bridge committee on mainnet in protocol version 58)

crates/sui-rest-api/src/response.rs
=> rest: avoid panicking when constructing response headers

crates/sui-indexer/migrations/pg/2023-08-19-044023_objects/up.sql
I noticed I forgot to merge the creation of these indices into `main` branch so adding it now. These are results of the object query performance investigation from awhile ago.
existing tests
---
=> [indexer] create obj snapshot type indexes for performance

.github/workflows/release.yml
Add additional release trigger types
👀
=> Add additional release trigger types

crates/suiop-cli/src/cli/incidents/mod.rs, crates/suiop-cli/src/cli/incidents/pd.rs
channels
Limit the noisy incidents/alerts
ran locally successfully 
---
=> [suiop] filter incident selection by incidents with status or slack

docs/content/snippets/openid-providers.mdx
=> chore: update doc for new providers

bridge/runbook/validator_runbook.md
=> [brideg] add hardware requirements for bridge node

Cargo.lock
=> chore: update quinn-proto to address RUSTSEC-2024-0373

.github/workflows/release.yml
=> Fix env variable name

crates/sui-node/src/metrics.rs
move warn to error when sui-node cannot send metrics
it builds
---
=> [sui-node/logging]

consensus/core/src/block.rs, consensus/core/src/block_verifier.rs, consensus/core/src/lib.rs, consensus/core/src/transaction.rs, crates/sui-core/src/consensus_validator.rs
Add block variant that supports voting.
Add method to TransactionVerifier trait, for calling into the voting logic.
CI
---
=> [Consensus] add type and interface for transaction voting

examples/trading/api/package.json, pnpm-lock.yaml, sdk/graphql-transport/src/methods.ts
=> [chore] upgrade express to fix npm audit warning

Cargo.lock, crates/sui-rosetta/Cargo.toml, crates/sui-rosetta/src/account.rs, crates/sui-rosetta/src/block.rs, crates/sui-rosetta/src/construction.rs, crates/sui-rosetta/src/lib.rs, crates/sui-rosetta/src/operations.rs, crates/sui-rosetta/src/state.rs, crates/sui-rosetta/src/types.rs, crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs, crates/sui-rosetta/src/unit_tests/operations_tests.rs, crates/sui-rosetta/src/unit_tests/types_tests.rs, crates/sui-rosetta/tests/custom_coins/test_coin/Move.toml, crates/sui-rosetta/tests/custom_coins/test_coin/sources/test_coin.move, crates/sui-rosetta/tests/custom_coins/test_coin_utils.rs, crates/sui-rosetta/tests/custom_coins_tests.rs, crates/sui-rosetta/tests/end_to_end_tests.rs, crates/sui-rosetta/tests/gas_budget_tests.rs, crates/sui-rosetta/tests/rosetta_client.rs
Rosetta support for all coins.
Unit and integration tests, CB also did a thorough manual integration test on their end.
---
---------
Co-authored-by: nikos-terzo <nikos.terzo@mystenlabs.com>
Co-authored-by: patrick <patrickkuo@me.com>
(cherry picked from commit 915deb4bbfaee4e2e0a7dc712cda2042507bbd35)
--- …
=> [Rosetta] Support coin standard (#19018)

crates/sui-indexer/migrations/pg/2024-09-05-164455_full_objects_history/down.sql, crates/sui-indexer/migrations/pg/2024-09-05-164455_full_objects_history/up.sql, crates/sui-indexer/src/handlers/committer.rs, crates/sui-indexer/src/metrics.rs, crates/sui-indexer/src/models/objects.rs, crates/sui-indexer/src/schema/mod.rs, crates/sui-indexer/src/schema/pg.rs, crates/sui-indexer/src/store/indexer_store.rs, crates/sui-indexer/src/store/pg_indexer_store.rs
Add full_objects_history schema.
CI
---
---
=> [Indexer][CherryPick] Add full_objects_history table (#19227)

.changeset/mean-swans-look.md, .changeset/ninety-horses-cover.md, sdk/deepbook-v3/src/transactions/deepbookAdmin.ts, sdk/deepbook-v3/src/utils/config.ts, sdk/deepbook-v3/src/utils/constants.ts
setTreasuryAddress function in SDK
Admin createPoolFunction updates
Constant Updates
Testnet
=> Deepbook SDK Updates

docker/sui-tools/Dockerfile
=> add deepbook indexer to sui tool image

crates/sui-move/src/disassemble.rs, external-crates/move/crates/move-cli/src/base/test.rs
=> Revert "[move][tracing] Document flag for generating traces from `sui move test`"

external-crates/move/crates/move-compiler/tests/sui_mode/linter/false_positive_share_owned.move, external-crates/move/crates/move-compiler/tests/sui_mode/linter/true_negative_share_owned.move, external-crates/move/crates/move-compiler/tests/sui_mode/linter/true_positive_share_owned.move
Fix some move compiler tests that landed in a broken state somehow.
CI/ran them locally.
---
=> [move] Fix move compiler tests

Cargo.lock, Cargo.toml, crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Adds configuration for One
---
=> Adds configuration for One

crates/sui-bridge-cli/src/main.rs, crates/sui-bridge/src/config.rs, crates/sui-bridge/src/e2e_tests/test_utils.rs, crates/sui-bridge/src/metrics.rs, crates/sui-bridge/src/monitor.rs, crates/sui-bridge/src/node.rs, crates/sui-bridge/src/sui_client.rs, crates/sui-bridge/src/sui_transaction_builder.rs, crates/sui/src/sui_commands.rs, crates/sui/src/validator_commands.rs
as title, boring PR
existing tests
---
=> [bridge] add metrics to SuiClient and Monitor

.changeset/gentle-beds-melt.md, sdk/zksend/src/links/builder.ts, sdk/zksend/src/links/claim.ts
=> [zksend] check transaction status when creating and claiming links

.github/workflows/release.yml
Start building binaries for ubuntu-arm64
https://github.com/MystenLabs/sui/actions/runs/10853752222/job/30122694354
=> Start building binaries for ubuntu-arm64

crates/sui-analytics-indexer/src/analytics_processor.rs, crates/sui-analytics-indexer/src/handlers/checkpoint_handler.rs, crates/sui-analytics-indexer/src/handlers/df_handler.rs, crates/sui-analytics-indexer/src/handlers/event_handler.rs, crates/sui-analytics-indexer/src/handlers/move_call_handler.rs, crates/sui-analytics-indexer/src/handlers/object_handler.rs, crates/sui-analytics-indexer/src/handlers/package_handler.rs, crates/sui-analytics-indexer/src/handlers/transaction_handler.rs, crates/sui-analytics-indexer/src/handlers/transaction_objects_handler.rs, crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs, crates/sui-analytics-indexer/src/lib.rs, crates/sui-bridge-indexer/src/sui_datasource.rs, crates/sui-data-ingestion-core/src/executor.rs, crates/sui-data-ingestion-core/src/lib.rs, crates/sui-data-ingestion-core/src/reader.rs, crates/sui-data-ingestion-core/src/tests.rs, crates/sui-data-ingestion-core/src/worker_pool.rs, crates/sui-data-ingestion/src/workers/archival.rs, crates/sui-data-ingestion/src/workers/blob.rs, crates/sui-data-ingestion/src/workers/kv_store.rs, crates/sui-deepbook-indexer/src/sui_datasource.rs, crates/sui-indexer/src/handlers/checkpoint_handler.rs, crates/sui-indexer/src/handlers/objects_snapshot_processor.rs, crates/suins-indexer/src/main.rs, deny.toml
---
Ingestion framework api has been updated to take CheckpointData by reference instead of by value.
=> ingestion: reduce memory footprint by passing references to workers and using Arcs internally

crates/sui-indexer/src/apis/read_api.rs
the original impl. fires a DB query for each object, which is wasteful
ci
---
=> indexer json rpc: batch object db reades

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_59.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_59.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_59.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap, deny.toml
=> Bump MAX_PROTOCOL_VERSION to 59

crates/sui-core/src/authority.rs, crates/sui-core/src/verify_indexes.rs, crates/sui-storage/src/indexes.rs
This reverts commit bb778828e36d53a7d91a27e55109f2f45621badc
It was a temporary fix for one release only
---
=> Revert "repair coin index"

crates/sui-proxy/src/peers.rs
=> change extract_bridge errors to warn

.mypkg, crates/sui-proxy/MYPKG, crates/sui-proxy/sui_proxy_dockerfile
=> [sui-proxy/mypkg] add mypkg

crates/sui-node/src/lib.rs
disable kv store for testnet
---
=> [kv store] explicitly disable for testnet

crates/sui-rest-api/src/accounts.rs, crates/sui-rest-api/src/checkpoints.rs, crates/sui-rest-api/src/client/mod.rs, crates/sui-rest-api/src/client/sdk.rs, crates/sui-rest-api/src/coins.rs, crates/sui-rest-api/src/error.rs, crates/sui-rest-api/src/objects.rs, crates/sui-rest-api/src/reader.rs, crates/sui-rest-api/src/transactions/execution.rs, crates/sui-types/src/sui_sdk2_conversions.rs
=> types: failable conversions to/from sdk and core types

bridge/evm/contracts/BridgeConfig.sol, bridge/evm/contracts/utils/CommitteeUpgradeable.sol, bridge/evm/script/deploy_bridge.s.sol, bridge/evm/test/BridgeBaseTest.t.sol, bridge/evm/test/BridgeCommitteeTest.t.sol, bridge/evm/test/BridgeConfigTest.t.sol, bridge/evm/test/BridgeLimiterTest.t.sol, bridge/evm/test/CommitteeUpgradeableTest.t.sol, bridge/evm/test/SuiBridgeTest.t.sol
Addressing: https://dashboard.hackenproof.com/manager/sui/sui-protocol/reports/SUIPR-150 
Update the CommitteeUpgradeable contract to disable all upgradeable bridge contracts' implementations from initialising.
Added a unit test.
=> Bridge evm implementation initialization

crates/sui-rest-api/src/accounts.rs, crates/sui-rest-api/src/objects.rs, crates/sui-types/src/sui_sdk2_conversions.rs
=> rest: avoid panic when converting from TypeTag

crates/mysten-metrics/src/lib.rs, crates/sui-bridge/src/eth_client.rs, crates/sui-bridge/src/main.rs, crates/sui-bridge/src/node.rs, crates/sui-bridge/src/server/mod.rs
As title.
tested by running a bridge network locally.
---
=> [bridge] add uptime metrics for bridge node

bridge/runbook/validator_runbook.md
=> [bridge] add bridge node info to validator run book

crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Adds testnet and mainnet support for playtron provider
Devnet tests, according to the predefined procedure
---
=> Adds testnet and mainnet support for playtron provider

docs/content/guides/developer/getting-started/sui-install.mdx, docs/content/snippets/libpq-req.mdx
Updated the requirement for libpq. Also, highlighting the quick install method.
---
=> [docs] libpq updates

crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Adds testnet and mainnet support for one provider
Devnet tests, according to the predefined procedure
---
=> Adds testnet and mainnet support for one provider

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.35.0 Version Bump

docs/content/guides/operator/archives.mdx
=> Include the aws region in example config

crates/sui-node/src/lib.rs
cherry pick of https://github.com/MystenLabs/sui/pull/19433
=> cherry-pick #19433 to 1.34

crates/sui-config/src/object_storage_config.rs, crates/sui-snapshot/src/reader.rs, crates/sui-storage/src/object_store/http/gcs.rs, crates/sui-storage/src/object_store/mod.rs
=> [formal snapshots] Fix retry logic in GCS and improve logging

bridge/evm/contracts/BridgeCommittee.sol, bridge/evm/contracts/BridgeConfig.sol, bridge/evm/contracts/BridgeLimiter.sol, bridge/evm/contracts/SuiBridge.sol, bridge/evm/contracts/interfaces/IBridgeCommittee.sol, bridge/evm/contracts/interfaces/IBridgeConfig.sol, bridge/evm/contracts/interfaces/IBridgeLimiter.sol, bridge/evm/contracts/interfaces/ISuiBridge.sol, bridge/evm/contracts/utils/CommitteeUpgradeable.sol
Updated the governance action events to include the message nonce for indexing purposes. 
Unit tests
=> Update Events to include message nonce 

examples/turnip-town/move/Move.toml, examples/turnip-town/move/sources/field.move, examples/turnip-town/move/sources/game.move, examples/turnip-town/move/sources/royalty_policy.move, examples/turnip-town/move/sources/turnip.move, examples/turnip-town/move/sources/water.move, examples/turnip-town/move/tests/field_tests.move, examples/turnip-town/move/tests/game_tests.move, examples/turnip-town/move/tests/turnip_tests.move, examples/turnip-town/move/tests/water_tests.move
New and shiny Turnip Town.
---
=> [examples] Turnip Town V2

crates/sui-network/src/discovery/mod.rs, crates/sui-network/src/discovery/server.rs
=> discovery: limit the number of peers shared during discovery

.github/workflows/release-notes-generator.yml
Use PAT token for release creation
Will be testing this next week
=> Use PAT token for release creation

crates/sui-core/src/authority_aggregator.rs
Change AuthorityAggregator to always pass through request_events flag, even to the validators we aren't sampling for objects.
In addition, up the sample size of validators to 10 and log when we get unlucky and reach quorum without having recieved input or output objects.
---
=> authority_aggregator: always request for events when asked (#19251)

bridge/runbook/validator_runbook.md, crates/sui-bridge/src/eth_syncer.rs
=> [bridge] log last synced eth blocks and default to end block

bridge/evm/contracts/BridgeConfig.sol
=> [bridge] fix token price index

crates/suins-indexer/README.md
Adds a README file to explain some of the env variables that were kinda unclear.
---
=> [NS Indexer] adds README

.changeset/three-carpets-allow.md, sdk/deepbook-v3/src/utils/constants.ts
Deepbook SDK package constants update, coin IDs update
Tested on testnet
---
=> Deepbook SDK package constants

docs/content/guides/developer/sui-101/using-events.mdx
Updates a broken SDK example. Need to eventually recreate in the sui repo for ease of maintenance; ticket created.
---
=> [docs] Updated example and linked to source

bridge/runbook/validator_runbook.md
=> [bridge] add metrics push section to runbook

crates/sui-proxy/src/peers.rs
some bridge endpoints take very long to return and eventually fail, this slows down the key fetching process
=> [sui-proxy] set 10s timeout for bridge metrics key query

apps/wallet/src/ui/app/pages/home/interstitial/index.tsx
=> add paddings to interstitial

crates/sui-framework/docs/sui-framework/authenticator_state.md, crates/sui-framework/docs/sui-framework/balance.md, crates/sui-framework/docs/sui-framework/coin.md, crates/sui-framework/docs/sui-framework/config.md, crates/sui-framework/docs/sui-framework/deny_list.md, crates/sui-framework/docs/sui-framework/sui.md, crates/sui-framework/docs/sui-framework/token.md, crates/sui-framework/docs/sui-framework/transfer.md, crates/sui-framework/packages/sui-framework/sources/authenticator_state.move, crates/sui-framework/packages/sui-framework/sources/balance.move, crates/sui-framework/packages/sui-framework/sources/coin.move, crates/sui-framework/packages/sui-framework/sources/config.move, crates/sui-framework/packages/sui-framework/sources/deny_list.move, crates/sui-framework/packages/sui-framework/sources/sui.move, crates/sui-framework/packages/sui-framework/sources/token.move, crates/sui-framework/packages/sui-framework/sources/transfer.move, crates/sui-framework/packages/sui-framework/tests/balance_tests.move
Final framework PR (excluding tests) in the formatting series.
All tests must pass, framework must produce the same bytecode.
---
=> [framework] Formatting: coin, token, balance, config, transfer 6/N

docs/content/guides/developer/getting-started/get-coins.mdx
=> Set the right path to get a coin from faucet

crates/sui-rosetta/src/operations.rs
=> rosetta: don't panic when accessing inputs

crates/sui-graphql-e2e-tests/tests/stable/objects/full_objects_history.exp, crates/sui-graphql-e2e-tests/tests/stable/objects/full_objects_history.move
Hope this addresses ci test issues
---
=> [gql] affix protocol version to e2e test

crates/sui-graphql-e2e-tests/tests/stable/objects/wrap_unwrap.exp, crates/sui-graphql-e2e-tests/tests/stable/objects/wrap_unwrap.move, crates/sui-indexer/src/store/pg_indexer_store.rs
title
```
cargo nextest run objects/wrap_unwrap
PASS [   7.594s] sui-graphql-e2e-tests::tests run_test::stable/objects/wrap_unwrap.move
```
---
=> indexer: fix unwrap after wrap bug in a checkpoint batch

crates/sui-open-rpc/spec/openrpc.json, crates/sui-types/src/event.rs, sdk/typescript/src/client/types/generated.ts
=> Update outdated event id doc

crates/sui-open-rpc/spec/openrpc.json, crates/sui-protocol-config/src/lib.rs, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_61.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_61.snap, crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_61.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap, crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
This is a fix for CI. Bumping protocol version and pushing new feature change to that version
---
=> Enable distributed vote scoring in testnet v61

.github/actions/ts-e2e/action.yml
The TS E2E tests were trying to build the Sui CLI with the `indexer` feature enabled, but that feature no longer exists (and the functionality it guarded is now available by default).
CI
---
=> fix(ci): clean-up final use of --features indexer

README.md, pnpm-lock.yaml, sdk/docs/package.json, sdk/docs/typedoc.json
Was unable to build site locally to test. Trying to get mermaid graph to render here: https://sdk.mystenlabs.com/typedoc/index.html  
https://sui-typescript-docs-7fcypvvd6-mysten-labs.vercel.app/typedoc/index.html
---
=> [sdk docs] Added mermaid ref

crates/sui-indexer/src/store/pg_indexer_store.rs
We will need a copy of the full epochs history somewhere.
We either create a separate KV table or just simply don't prune the existing table.
Given that this table is quite small, it's probably ok just to not prune it.
CI
---
=> [Indexer] Do not prune epochs table

crates/sui-bridge-indexer/src/eth_bridge_indexer.rs, crates/sui-bridge-indexer/src/metrics.rs, crates/sui-bridge-indexer/src/sui_datasource.rs, crates/sui-deepbook-indexer/src/metrics.rs, crates/sui-deepbook-indexer/src/sui_datasource.rs, crates/sui-indexer-builder/src/indexer_builder.rs, crates/sui-indexer-builder/tests/indexer_test_utils.rs, crates/sui-indexer-builder/tests/indexer_tests.rs
1. add more logs in indexer especially in error cases
3. add inflight live tasks metrics
tested running locally.
---
=> [bridge] add logs and metrics for bridge indexer

crates/sui-bridge/src/action_executor.rs, crates/sui-bridge/src/config.rs, crates/sui-bridge/src/metrics.rs
1. report gas coin balance on node start
2. set the minimal gas balance to 10 SUI on start
3. some other metrics updates
---
=> [bridge] report gas coin balance on node start

crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Enable 3DOS oauth provider for Prod
---
=> [cherry-pick] Enable 3DOS oauth provider for Prod

crates/sui-rosetta/src/operations.rs
Cherry-pic of rosetta fix from main branch
---
(cherry picked from commit 23fa67bdc4afe68518e8f3536151e221ed33a53b)
--- …
=> rosetta: don't panic when accessing inputs (#19544)

docs/content/guides/developer/advanced/custom-indexer.mdx
Applies doc change to data ingestion's Worker trait
=> [docs] fix interface reference for data ingestion

.github/workflows/nightly.yml
Fixing nightly workflow: Remove profile release option
👀
=> Fixing nightly workflow: Remove profile release option

crates/sui-core/src/authority.rs, crates/sui-core/src/transaction_orchestrator.rs, crates/sui-e2e-tests/tests/traffic_control_tests.rs, crates/sui-swarm-config/src/network_config_builder.rs
This PR replaces active local execution with waiting for checkpoint execution.
There are some cleanup needed later to remove all the local execution code, but we can do that separately.
CI
---
=> Replace local execution with wait for checkpoint execution

.changeset/silent-kangaroos-laugh.md, sdk/deepbook-v3/src/utils/constants.ts
Upgrade Deepbook SDK package
Testnet
---
=> Deepbook Testnet Upgrade

docs/content/concepts/research-papers.mdx
Adds additional research papers. Alphabetizes the list, as well.
Adds
- Sui Lutris
- Mysticeti
- zkLogin
- HammerHead
---
=> [docs][easy] Adding research papers

Cargo.lock, Cargo.toml, crates/sui-config/src/node.rs, crates/sui-swarm-config/src/node_config_builder.rs, crates/sui-swarm/src/memory/swarm.rs, crates/test-cluster/src/lib.rs
This is a cherry pick of https://github.com/MystenLabs/sui/pull/19490/files
=> cherry-pick: Add an option to disable fullnode pruning in test cluster (#19490)

.github/workflows/nightly.yml, .github/workflows/rust.yml
=> chore: separate cargo-deny advisory checks into its own job

.github/actions/diffs/action.yml, .github/workflows/rust.yml
=> chore: fix github actions warnings

Cargo.lock, Cargo.toml, deny.toml
Revert tonic update in release branch
=> Revert tonic update in release branch

crates/sui-framework/docs/sui-framework/random.md, crates/sui-framework/packages/sui-framework/sources/random.move, docs/content/guides/developer/advanced/randomness-onchain.mdx
=> Update documentation of Random

crates/sui-indexer/Cargo.toml, crates/sui-indexer/src/apis/mod.rs, crates/sui-indexer/src/apis/read_api.rs, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/src/test_utils.rs, crates/sui-indexer/tests/ingestion_tests.rs, crates/sui-indexer/tests/read_api_tests.rs
title
cargo test --package sui-indexer --test read_api_tests
---
=> indexer json rpc tests: checkpoint apis

apps/wallet/src/shared/analytics/ampli/index.ts, apps/wallet/src/ui/app/components/coin-icon/index.tsx, apps/wallet/src/ui/app/index.tsx, apps/wallet/src/ui/app/pages/home/usdc-promo/UsdcPromo.tsx, apps/wallet/src/ui/app/pages/home/usdc-promo/UsdcPromoBanner.tsx, apps/wallet/src/ui/app/pages/home/usdc-promo/useUsdcPromo.ts
Add amplitude and minor fixes
---
=> Add amplitude and minor fixes

sui-execution/latest/sui-move-natives/src/validator.rs
=> ValidateMetadata Move struct doesn't match typo

crates/sui-faucet/src/server.rs
=> [faucet] request status should return bad request for invalid UUIDs

crates/sui-indexer/src/backfill/backfill_instances/system_state_summary_json.rs
The backfill for system state json was missing data for epoch 0.
Run against testnet
---
=> [Index] Fix a bug in epochs system state json backfill

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.36.0 Version Bump

docker/sui-proxy/Dockerfile
add a sui-proxy dockerfile
tsia
---
=> [sui-proxy/dockerfile]

consensus/core/src/commit_syncer.rs
This addresses consensus sync issues on some validators.
CI
---
---
=> CP #19705 to 1.35

crates/sui-bridge/src/crypto.rs, crates/sui-bridge/src/metrics.rs, crates/sui-bridge/src/node.rs, crates/sui-bridge/src/sui_client.rs, crates/sui-bridge/src/test_utils.rs, crates/sui-bridge/src/types.rs, crates/sui-bridge/src/utils.rs
so we can use this in the dashboard
---
=> [bridge] report bridge voting power when node starts

crates/sui-proxy/src/peers.rs
=> [proxy] use validator name when logging metrics for bridge

consensus/core/src/synchronizer.rs
Reduce the blocks per request from synchronizer, since synchronizer generally uses smaller timeouts.
CI
PT
---
=> [Consensus] adjust sync params

crates/telemetry-subscribers/src/bin/import-trace.rs
Tested with:
$ cd docker/jaeger-local
$ docker compose up
$ cargo run --bin import-trace -- --trace-file  /tmp/suitrace.out
Compiling telemetry-subscribers v0.2.0 (/Users/marklogan/dev/sui/crates/telemetry-subscribers)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.60s
Running `target/debug/import-trace --trace-file /tmp/suitrace.out`
importing trace with service name "sui-node-1728342184"
sending 271 spans to otlp collector
sending 512 spans to otlp collector
.... <omitted>
sending 512 spans to otlp collector
all spans imported
Imported traces are then visible in the jaeger UI with the correct service.name
=> Add service.name when it is not found

crates/sui-core/src/authority.rs, crates/sui-indexer/src/handlers/tx_processor.rs, crates/sui-json-rpc/src/balance_changes.rs, crates/sui-json-rpc/src/object_changes.rs, crates/sui-json-rpc/src/read_api.rs, crates/sui-json-rpc/src/transaction_execution_api.rs, crates/sui-storage/src/http_key_value_store.rs, crates/sui-storage/src/indexes.rs, crates/sui-storage/tests/key_value_tests.rs
=> jsonrpc: add instrumentation to read apis

crates/sui-core/src/authority/authority_per_epoch_store.rs
Confirmed fix via:
./scripts/simtest/seed-search.py --test simtest test_simulated_load_rolling_restarts_all_validators
=> Delete user sigs in process_pending_checkpoint

Cargo.lock, docs/content/guides/operator/bridge-node-configuration.mdx
=> [bridge-doc] add how to update url after finalization

.github/workflows/release.yml
=> Fix release type trigger

docs/content/guides.mdx, docs/content/guides/operator.mdx, docs/site/src/pages/index.js
=> [bridge-doc] make bridge runbook more visible

.changeset/itchy-ants-notice.md, sdk/deepbook-v3/src/utils/constants.ts
Test Mainnet Package
Mainnet
---
=> Mainnet Packages

.github/actions/ts-e2e/action.yml
=> Fix ts-e2e test

docs/content/standards/deepbookv3-sdk.mdx, docs/content/standards/deepbookv3-sdk/pools.mdx, docs/content/standards/deepbookv3/query-the-pool.mdx
=> [docs] DBv3 updates

.github/actions/ts-e2e/action.yml
=> [CI] Fix action workflow

crates/suiop-cli/src/cli/pulumi/init.rs, crates/suiop-cli/src/cli/pulumi/mod.rs, crates/suiop-cli/src/cli/pulumi/setup.rs, crates/suiop-cli/src/main.rs
Preparing for the addition of the typescript 
non-functional change
---
=> [suiop] simplify pulumi init subcommand

crates/sui-authority-aggregation/src/lib.rs, crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
as title. This state is not used today.
---
=> remove `ContinueWithTimeout` in authority aggregation

crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Enable Trace OAuth provider on Prod
=> Trace OAuth provider on Prod

Cargo.lock, consensus/core/src/network/tonic_tls.rs, crates/sui-tls/Cargo.toml, crates/sui-tls/src/lib.rs, crates/sui-tls/src/verifier.rs
=> Consolidate `HashSetAllow` and `AllowedPublicKeys` types

crates/sui-bridge-indexer/config.yaml, crates/sui-deepbook-indexer/config.yaml, crates/sui-deepbook-indexer/src/config.rs
=> remove unused fields for bridge indexer

apps/wallet/src/ui/app/pages/swap/index.tsx, apps/wallet/src/ui/app/pages/swap/useSwapTransaction.ts
Add source for swap wallet address: https://github.com/MystenLabs/apps-backend/blob/main/src/routes/legacy/swap.ts#L85
---
=> add source to swap

external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts, external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts, external-crates/move/crates/move-analyzer/trace-adapter/src/source_map_utils.ts, external-crates/move/crates/move-analyzer/trace-adapter/src/trace_utils.ts
This PR adds support for tracking variable values for structs and enums. It also does some code cleanup (mostly via renamings)
Tested manually
=> [trace-view] Added support for tracking struct/enum values

Cargo.lock, crates/sui-indexer/Cargo.toml, crates/sui-indexer/src/store/pg_indexer_store.rs, crates/sui-indexer/src/types.rs
=> indexer fix: chunk to avoid PG parameter limit (#19754)

crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
=> Adds arden to prod providers

.github/actions/diffs/action.yml, .github/workflows/docs-ci.yml
Use existing action to filter change location.
yolo
---
=> [docs][ci] Updated examples check

crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Cherry-picked commits for adding Arden and Trace to the upcoming release
---
=> Releases/sui v1.35.0 arden trace cherrypicks

.changeset/afraid-stingrays-collect.md, sdk/deepbook-v3/src/utils/constants.ts
=> DEEP Pool Redeploy

crates/sui-config/src/node.rs, crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
=> Add Trace to prod providers

.changeset/cuddly-beds-shop.md, sdk/deepbook-v3/src/utils/constants.ts
=> Mainnet Pools

sdk/typescript/README.md
Update Typescript SDK examples in README to work
Copy-pasted changed code to a new project depending on '@mysten/sui' and checked for no relevant typescript errors.
---
=> Update typescript sdk examples

docker/sui-services/Dockerfile
kaniko doesn't like `*` wildcard, so have to be a little bit smarter.
had a successfully built from kaniko. I pulled it down and inspected manually, binaries are ther
---
=> [docker] fix dockerfile for kaniko

sdk/graphql-transport/src/mappers/transaction-block.ts, sdk/graphql-transport/test/compatability.test.ts
=> [gql-transport] fix rawInput for transaction queries

docs/content/snippets/deepbook.mdx
DBv3 is now on Mainnet. Makes the sentence removed somewhat pointless.
👀 
---
=> [docs] Update dbv3 content

docs/content/guides/operator/updates.mdx
Fix node operator doc quote
Before:
After:
=> Fix node operator doc quote

Cargo.lock, Cargo.toml, crates/sui-e2e-tests/tests/rest.rs, crates/sui-rest-api/Cargo.toml, crates/sui-rest-api/openapi/openapi.json, crates/sui-rest-api/src/error.rs, crates/sui-rest-api/src/transactions/resolve/literal.rs, crates/sui-rest-api/src/transactions/resolve/mod.rs
Improve the format of `UnresolvedTransaction` as well as introduce the ability to resolve un-serialized pure argument literals.
Example of JSON payload of an `UnresolvedTransaction`:
```
{
"inputs": [
{
"object_id": "0x2d7f57570815c43eb485be9018caabd11ac863e9d49b1d9e33b3f4ac40cadc72"
},
{
"value": 1
},
{
"value": "0xc6fc0e38458632b1dd1d60b3a833865268a0faebe36864c71fb9805bd5a116cf"
}
],
"commands": [
{
"command": "split_coins",
"coin": {
"input": 0
},
"amounts": [
{
"input": 1
},
{
"input": 1
}
]
},
{
"command": "transfer_objects",
"objects": [
{
"result": [
0,
1
]
},
{
"result": [
0,
0
]
}
],
"address": {
"input": 2
}
}
],
"sender": "0xff69fdb72bfc6ff5a337ff01c650fb0ce72447105ff050c2039c6b5b267b04a7"
}
```
which is resolved into the following `Transaction`:
```
{
"version": "1",
"kind": { …
```
=> rest: enable resolving of literals

crates/sui-node/src/lib.rs
This will enable quinn stats for p2p network
---
=> Add known peers for p2p network connection monitor

Cargo.lock, crates/suiop-cli/Cargo.toml, crates/suiop-cli/src/cli/ci/image.rs
Make it so the user can hit 'q' or 'esc' to exit the image watch interface
https://github.com/user-attachments/assets/578ab67e-763e-4cd8-a4a7-1ac6006a4004
---
=> [suiop][image] enable q or esc to quit watching

Cargo.lock, crates/sui-rosetta/Cargo.toml, crates/sui-rosetta/src/construction.rs, crates/sui-rosetta/src/types.rs, crates/sui-rosetta/src/unit_tests/types_tests.rs
=> [Rosetta] - serialize total_coin_value to string instead of number to prevent precision lost

.changeset/happy-penguins-kick.md, sdk/deepbook-v3/src/utils/constants.ts
New Deepbook Pool Params
Mainnet
=> New Deepbook Pool Params

.github/workflows/rust.yml
=> ci: set log level to error

.changeset/small-icons-smash.md, sdk/typescript/src/bcs/effects.ts
=> [ts sdk] Add new errors to ExecutionFailureStatus

crates/sui-bridge-cli/src/main.rs
Handle the case where a bridge committee member is no longer a validator. 
=> Fix ViewSuiBridge Bridge CLI command

Cargo.lock, Cargo.toml, crates/sui-open-rpc/spec/openrpc.json
=> Sui v1.37.0 Version Bump

Cargo.lock, crates/sui-rosetta/Cargo.toml, crates/sui-rosetta/src/construction.rs, crates/sui-rosetta/src/operations.rs, crates/sui-rosetta/src/types.rs, crates/sui-rosetta/src/unit_tests/types_tests.rs, crates/sui-rosetta/tests/custom_coins/test_coin_no_symbol/Move.toml, crates/sui-rosetta/tests/custom_coins/test_coin_no_symbol/sources/test_coin.move, crates/sui-rosetta/tests/custom_coins/test_coin_utils.rs, crates/sui-rosetta/tests/custom_coins_tests.rs
Cherry pick of 2 rosetta fixes
---
=> Releases/sui v1.35.0 release rosetta fixes

crates/sui-indexer/src/handlers/mod.rs
without this change, the unprocessed buffer will grow unboundedly until OOM
it did not manifest on previous processor b/c it has sleep codes of 
```
_ = tokio::time::sleep(std::time::Duration::from_secs(config.sleep_duration))
```
and `sleep_duration` is 5 seconds.
- correctness via the added objects_snapshot test
- oom via experiment result on benchmark env with mem usage [link](https://app.datadoghq.com/metric/explorer?fromUser=false&start=1729280070529&end=1729283670529&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMiZUggYojoAdOqqblhNeBoY8MAA1ngARnBOkb7yGNnI2vKZALTDIpmMHtp9AAQU67Ui9Y3ao1FwyBp4EHOiAsQ6POuDWOvADlCH6jwgPAC6VK7ue …
=> indexer handler: limit unprocessed buffer size

crates/sui-indexer/src/handlers/mod.rs
without this change, the unprocessed buffer will grow unboundedly until OOM
it did not manifest on previous processor b/c it has sleep codes of 
```
_ = tokio::time::sleep(std::time::Duration::from_secs(config.sleep_duration))
```
and `sleep_duration` is 5 seconds.
- correctness via the added objects_snapshot test
- oom via experiment result on benchmark env with mem usage [link](https://app.datadoghq.com/metric/explorer?fromUser=false&start=1729280070529&end=1729283670529&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGABuMMiZUggYojoAdOqqblhNeBoY8MAA1ngARnBOkb7yGNnI2vKZALTDIpmMHtp9AAQU67Ui9Y3ao1FwyBp4EHOiAsQ6POuDWOvADlCH6jwgPAC6VK7ue …
=> Pick: indexer handler: limit unprocessed buffer size #19913
