MystenLabs/sui

crates/sui/src/client_ptb/builder.rs
crates/sui/tests/cli_tests.rs

Fixes the case where the `Move.lock` state isn't prepared for publish/upgrade via PTBs.
Issue reported in https://mysten-labs.slack.com/archives/C04HS54LHUM/p1720554945603299
More details--
In https://github.com/MystenLabs/sui/pull/18470 `sui client publish` / `sui client upgrade` supports setting/resetting published addresses to `0x0` in the `Move.lock` to prepare publish actions. I was under the impression PTBs used the same internal `::Publish` and `::Upgrade` commands, but it has its own, meaning that it doesn't prepare the `Move.lock` state for PTB publish/upgrades.
The implementation does _exactly_ what we do in `client_commands.rs`, but for PTBs, so that this PR introduces the same mechanical change with predictable behavior. There is an opportunity to squash this logic (so that …

move: ptb flow publishes packages with automated addy mgmt

---

crates/sui-core/src/authority_client.rs
crates/sui-types/src/error.rs

Cherry pick 18536

---

crates/sui-adapter-transactional-tests/tests/deny_list_v1/coin_deny_and_undeny.exp
crates/sui-adapter-transactional-tests/tests/deny_list_v1/coin_deny_multiple_per_module.exp
crates/sui-adapter-transactional-tests/tests/deny_list_v1/coin_deny_tto.exp
crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_deny_and_undeny_receiver.exp
crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_deny_and_undeny_sender.exp
crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_global_pause.exp
crates/sui-adapter-transactional-tests/tests/programmable/coin_negative.exp
crates/sui-adapter-transactional-tests/tests/programmable/coin_operations_custom_coin.exp
crates/sui-adapter-transactional-tests/tests/programmable/coin_overflow.exp
crates/sui-adapter-transactional-tests/tests/programmable/merge_coin_mismatched_coin.exp
crates/sui-core/tests/staged/sui.yaml
crates/sui-types/src/deny_list_v2.rs
crates/sui-types/src/effects/effects_v2.rs
crates/sui-types/src/effects/mod.rs
crates/sui-types/src/effects/test_effects_builder.rs
crates/sui-types/src/storage/mod.rs
scripts/update_all_snapshots.sh
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
sui-execution/latest/sui-adapter/src/temporary_store.rs
sui-execution/v0/sui-adapter/src/temporary_store.rs
sui-execution/v1/sui-adapter/src/temporary_store.rs
sui-execution/v2/sui-adapter/src/temporary_store.rs

Commit per epoch config object load to effects.
This is done by introducing another variant to UnchangedSharedObject.
This does not need to be in input shared objects since it's not a sequenced input object.
This however does mean that this will not be added to the UnchangedSharedObject graphql rpc types since that relies on the input shared objects.
CI
---

Commit per epoch config load to effects v2

---

crates/sui-framework-tests/src/unit_tests.rs
examples/trading/contracts/demo/Move.toml
examples/trading/contracts/escrow/Move.toml
examples/trading/contracts/escrow/sources/owned.move
examples/trading/contracts/escrow/sources/shared.move

Prepare Move code in E2E examples to be run under CI tests:
- Depend on a local version of the Sui framework, to avoid CI refetching the Sui repo.
- Broaden the scope that the test checks for Move packages in, to include Move code in `./examples` but not in `./examples/move`.
- Fixing some things that the CI brought up (`use` statements that were only relevant in test mode.)
```
sui-framework-tests$ cargo nextest run
```
---

[Examples] Run Move tests for E2E examples in CI

---

external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/tests/completion/sources/init.move
external-crates/move/crates/move-analyzer/tests/completion/sources/init_otw.move
external-crates/move/crates/move-analyzer/tests/completion/sources/object.move
external-crates/move/crates/move-analyzer/tests/completion/sources/uid.move
external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs
external-crates/move/crates/move-analyzer/tests/inlay_hints.ide
external-crates/move/crates/move-analyzer/tests/snippet_completion.exp
external-crates/move/crates/move-analyzer/tests/snippet_completion.ide
external-crates/move/crates/move-compiler/src/shared/files.rs

This fixes a problem with dot-completion introduced in https://github.com/MystenLabs/sui/pull/18371
Due to how `Loc` from `Position` computation was changed, dot completion in the IDE stopped working even though unit tests were passing (after a modification that accommodated for `Loc` computation change).
All unit tests must pass. Also tested that dot completion actually works in the IDE

[move-ide] A dot-completion fix

---

crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids_dof_enum.exp
crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids_dof_enum.move
crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids_enums.exp
crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids_enums.move
crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids_on_child_enum.exp
crates/sui-adapter-transactional-tests/tests/mvcc/find_all_uids_on_child_enum.move
crates/sui-adapter-transactional-tests/tests/mvcc/middle_version_less_than_child_enum.exp
crates/sui-adapter-transactional-tests/tests/mvcc/middle_version_less_than_child_enum.move
crates/sui-verifier-transactional-tests/tests/private_generics/no_public_transfer_explicit.exp
crates/sui-verifier-transactional-tests/tests/private_generics/no_public_transfer_explicit.mvir
crates/sui-verifier-transactional-tests/tests/private_generics/private_event_emit.exp
crates/sui-verifier-transactional-tests/tests/private_generics/private_event_emit.mvir

Adds additional tests for enums in Sui.
It's all tests!

[Sui-move] More enums tests for sui-specific aspects

---

examples/tic-tac-toe/move/Move.toml
examples/tic-tac-toe/move/sources/owned.move
examples/tic-tac-toe/move/sources/shared.move
examples/tic-tac-toe/move/tests/owned_tests.move
examples/tic-tac-toe/move/tests/shared_tests.move

Port Move code for the tic tac toe example into the `sui/examples` directory, modernising it in the process:
- Standardise the implementation between the owned, shared and multi-sig variants, so that the only differences are relevant to what they need to do differently. In doing this, the owned and multi-sig variants become identical (at least at the level of Move code).
- Use transfer-to-object in the "owned" example, to send potential moves to the `Game` object, instead of the admin that owns the game.
- Use more Move 2024 features (`syntax(index)`, receiver function aliases, etc).
- Improve test coverage
```
tic_tac_toe/move$ sui move test
```
---
For …

[Examples/Move] Tic-tac-toe

---

crates/sui-storage/src/object_store/util.rs

During rocksdb snapshotting of the db (for creating rocksdb checkpoints), we temporarily suffix the toplevel dir with `.tmp`, and remove it after the snapshotting is complete. There is cleanup code to ensure that these temp files get deleted if we were to crash mid-operation, however there may be some rare edge cases where this is not the case, for example if we crash mid-operation, then start the node up again without db checkpointing enabled, causing the node to progress to the next epoch never having executed the cleanup code. 
In such cases, we will panic on all subsequent snapshot upload attempts due to inability to parse the db checkpoint name due to the unexpected `.tmp` suffix. This handles that edge case by ignoring such files.
👀 
---
Check each box that your changes affect. If …

[snapshots] Ignore .tmp files during db checkpoint scan

---

.github/workflows/cargo-llvm-cov.yml

Enable verbose mode for cargo llvm-cov
---

[codecov-ci] Enable verbose mode for cargo llvm-cov

---

crates/sui-test-validator/src/main.rs
sdk/graphql-transport/package.json
sdk/typescript/package.json

[pnpm] Fix running sui binary with --features indexer

---

crates/sui-benchmark/src/embedded_reconfig_observer.rs
crates/sui-benchmark/src/fullnode_reconfig_observer.rs
crates/sui-benchmark/src/lib.rs
crates/sui-config/src/genesis.rs
crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/authority_client.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/quorum_driver/reconfig_observer.rs
crates/sui-core/src/transaction_orchestrator.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
crates/sui-genesis-builder/src/lib.rs
crates/sui-node/src/lib.rs
crates/sui-swarm-config/src/network_config.rs
crates/sui-types/src/committee.rs
crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs
crates/sui-types/src/sui_system_state/simtest_sui_system_state_inner.rs
crates/sui-types/src/sui_system_state/sui_system_state_inner_v1.rs
crates/sui-types/src/sui_system_state/sui_system_state_inner_v2.rs
crates/sui-types/src/sui_system_state/sui_system_state_summary.rs

This PR restructures the inner fields of CommitteeWithNetworkMetadata such that it guarantees each authority name must corresponding to a pair of stake and network metadata. Potential mismatch was the last reason that AuthAggregator construction could fail. This PR addresses that from type system. After this we could make AuthAggregator constructor a non-fallable function.
CI
---

Refactor CommitteeWithNetworkMetadata

---

docker/sui-node-deterministic/Dockerfile

Update Deterministic Sui Build to compile a statically-linked binary.
StageX uses `musl` for compiling `sui-node`. 
In order for this to run the `sui-node` binary directly on glibc-based linux macines, it must be statically linked.
Cherry-pick commit to `testnet` branch and test on a private testnet.
* build docker image
* extract `sui-node` binary
* confirm statically linked (run `file` on mac, `ldd` on linux)
* upload to baremetal test server + run
* check build is still deterministic from github action build, linux machine, macOS machine
--- …

build statically-linked sui-node for testing on glibc-based hosts

---

crates/sui-bridge/src/client/bridge_authority_aggregator.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/types.rs
crates/sui-core/src/authority.rs
crates/sui-json-rpc-types/src/sui_protocol.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-rest-api/src/system.rs
crates/sui-types/src/transaction.rs
sui-execution/latest/sui-adapter/src/execution_engine.rs

In this PR we introduce a way to order validators to request signatures according to their voting power. This is useful for signatures to be verified on ethereum because the # of signatures do impact the gas cost there significantly.
deploying on a testnet bridge node to test.
---

[bridge]  support rank validators by voting power when requesting signatures

---

sdk/typescript/test/e2e/utils/setup.ts

Some test setups call [`[setup(), setup()]`](https://github.com/MystenLabs/sui/blob/9c588e14f284a8feb10f29791f32ad6bb3f36ae4/sdk/typescript/test/e2e/coin-with-balance.test.ts#L22) which can cause a race on accessing the tmp `config.yaml` (which happens in the same tmp directory). This change ensures `setup()` is creates `config.yaml` in unique directories. 
This issue is probably what caused the flakiness in [CI](https://github.com/MystenLabs/sui/actions/runs/9897466376/job/27342099106#step:10:2279), note the:
```
Cannot open wallet config file at "/tmp/client.yaml
```
Tested locally that running the test creates separate directories and passes.
---
For each box you select, …

sdk test setup: fix racy access on tmp config file

---

crates/sui-bridge/src/sui_client.rs
crates/sui-core/src/authority.rs
crates/sui-json-rpc-types/src/sui_protocol.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-rest-api/src/system.rs
crates/sui-types/src/transaction.rs
sui-execution/latest/sui-adapter/src/execution_engine.rs

Updated: we decided to introduce a protocol parameter to determine when bridge committee happens. This gives us more flexibility to include validators. As a result, we don't need the original change of threshold any more. Together with the new parameter, the old default value 7500 still acts as the minimal voting power threshold
------------------
Old description:
Previously the 75% minimal stake is too low to include most validators. This PR changes it to 90%.
I have two commits in this PR:
* the first commit sets the value by distinguish chain id - if it's testnet, then use 7500, otherwise 9000. This is safe because on mainnet we haven't enabled registration yet.
* the second commit uses a different approach with protocol config. Basically it adds a …

[bridge] use protocol parameter to determine when to finalize bridge committee `bridge_should_try_to_finalize_committee` 

---

crates/sui/src/sui_commands.rs
crates/sui/tests/cli_tests.rs

Make indexer, GraphQL, faucet hosts configurable. When using Docker, due to the way it sets up a network interface for the container, the services need to bind to 0.0.0.0 to be able to be accessed from outside the container. This PR enables configurable hosts for these three services via optional flags:
- `--indexer-host 0.0.0.0`
- `--faucet-host 0.0.0.0`
- `--graphql-host 0.0.0.0`
If no host flag is provided, it will use the default `0.0.0.0` one.
In addition, I found a bug where if the `default_value` is not provided, calling `unwrap_or_default` will return value 0 (if that field is an int). For example, if we call `--with-graphql`, the indexer port would have been set to 0 because the `default_missing_value` is only set when the flag is passed, but not when it is not passed, which is …

[CLI] Make service hosts configurable in `sui start` 

---

crates/mysten-metrics/src/lib.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_validator.rs
crates/sui-core/src/lib.rs
crates/sui-core/src/unit_tests/transaction_deny_tests.rs
crates/sui-core/src/validator_tx_finalizer.rs

The ValidatorTxFinalizer gets called whenever a transaction is signed on a validator. It would then sleep for a min, wake up and check if the tx has already been executed, if not, use authority aggregator to finalize it.
Added unit tests to cover various cases:
1. Basic flow
2. Epoch change
3. Tx already executed
---

[RFC][core] Add validator tx finalizer

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-e2e-tests/tests/protocol_version_tests.rs
crates/sui-node/src/lib.rs
crates/sui-node/src/main.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-swarm-config/src/network_config_builder.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm/src/memory/swarm.rs
crates/sui-types/src/lib.rs
crates/sui-types/src/messages_consensus.rs
crates/sui-types/src/supported_protocol_versions.rs
crates/test-cluster/src/lib.rs

Quick refactoring to prepare for adding AuthorityCapabilitiesV2, which will include the digest of ProtocolConfig for each supported version.

Move SupportedProtocolVersions to sui-types, rename AuthorityCapabilities -> AuthorityCapabilitiesV1

---

crates/sui-adapter-transactional-tests/tests/programmable/split_coins.exp
crates/sui-adapter-transactional-tests/tests/programmable/split_coins.move
external-crates/move/crates/move-compiler/src/typing/translate.rs

This extracts macros from the precompiled program so that macro expansion works for them, too.
Updated a test to use `vector`'s `do!`. It failed before the fix, and works now.
---

[move][move-2024] Extract macros from precompiled programs for expansion.

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
crates/sui/src/keytool.rs

This enables a new aws tenant for devnet for zklogin
```
cargo build --bin sui 
RUST_LOG=info target/debug/sui start --force-regenesis --with-faucet
target/debug/sui keytool zk-login-sign-and-execute-tx --max-epoch 10 --network localnet --fixed
Visit URL (AWS - Ambrus): https://ambrus.auth.us-east-1.amazoncognito.com/login?response_type=token&client_id=t1eouauaitlirg57nove8kvj8&redirect_uri=https://api.ambrus.studio/callback&nonce=hTPpgF7XAKbW37rEUS6pEVZqmoI
target/debug/sui keytool zk-login-enter-token --parsed-token eyJraWQiOiJWSEFcL3ZZMWQyaDdYMzNEcFo2WkJEUmZuQ1NcL09JZ2lWN3RvQ2R4eUVVRFk9IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiZktkZ21iXzNOMW1KTGlWNFByRG9IUSIsInN1YiI6Ijc0YjhmNGI4LTYwNTEtNzAwNC0wOGUxLTNkNTQxOTE1MzExOCIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvd …
```

chore: add a new cognito tenant

---

crates/sui-benchmark/src/lib.rs
crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/quorum_driver/reconfig_observer.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/transaction_orchestrator.rs
crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
crates/sui-core/src/validator_tx_finalizer.rs
crates/sui-node/src/lib.rs
crates/sui-tool/src/commands.rs

This PR makes two changes:
1. The primary change is to be able to construct AuthorityAggregator from epoch start state, instead of reading system state from the store. This is much safer and sync way to do it in prod.
2. The secondary change is to extend AuthorityAggregatorBuilder to be able to build more aggregators, to simplify some of the code.
CI
---

[AuthAgg] Use epoch start state to construct AuthorityAggregator

---

scripts/release_notes.py

Remove the Auth header because `sui` is a public repo..no need for GTIHUB_TOKEN
---

[script] no need for GITHUB_TOKEN because sui is a public repo

---

crates/mysten-common/src/sync/mod.rs
crates/sui-config/src/node.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/typed-store/src/rocks/mod.rs
crates/x/src/lint.rs

Cleanup a few references to Narwhal.
Remove consensus protocol choice from `ConsensusConfig`. This field is unused now.
CI
---

Cleanup a few Narwhal references

---

crates/sui-core/src/transaction_orchestrator.rs
crates/sui-node/src/lib.rs

This PR moves the construction of AuthorityAggregator to sui-node and stores a reference there.
This will make sure that all the metrics are ever only instantiated once (to avoid double register problem).
It will also allow us to use AuthorityAggregator later in ValidatorTxFinalizer.
CI
---

Store AuthorityAggregator in sui-node

---

crates/suiop-cli/src/cli/incidents/mod.rs
crates/suiop-cli/src/cli/incidents/pd.rs

enable limiting incident results to those with a priority set via the `--with-priority`/`-p` flag.
```
» cargo run --bin suiop -- i r -p     
Finished dev [unoptimized + debuginfo] target(s) in 0.43s
Running `/Users/jordankylejensen/mysten/sui/target/debug/suiop i r -p`
2433: (2d) P0 dummy incident
3135: (2d) P2 [FIRING:2] incident for something
3134: (2d) P2 [FIRING:2] redacted
```
---

[suiop][incidents] add --with-priority flag

---

external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/src/inlay_hints.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/inlay-hints/sources/type_hints.move
external-crates/move/crates/move-analyzer/tests/inlay_hints.exp
external-crates/move/crates/move-analyzer/tests/inlay_hints.ide

With this PR inlay type hints work for variant unpacks (they already worked for struct unpacks):
This includes nested patterns:
This PR also changes the way that types are displayed for type hints - the fully qualified name seemed too long (particularly for functions with multiple parameters on the same line) and not really necessary (or redundant even) since you can hover over the hint to see the full type.
All new and existing tests must pass

[move-ide] Added inlay type hints for unpacks

---

crates/sui-data-ingestion-core/src/reader.rs

adding support for hybrid setup, where indexer fetches checkpoint from a remote FN and falls back to a remote bucket if the FN's already pruned

[data ingestion] hybrid remote setup 

---

crates/sui-core/src/authority.rs
crates/sui-core/src/consensus_validator.rs

Add a metric for time consumed during transaction verifications in Mysticeti.
Add a metric for the specific overloaded component when transactions are rejected for signing / submission.
CI
---

Add metrics for batch verify and overload

---

crates/sui-core/src/authority/epoch_start_configuration.rs

This is intended to prevent mistakes such as the one being fixed by #18682

Make EpochFlag values explicit to avoid mistakes when cherry picking

---

sdk/docs/pages/typescript/owned-object-pool/index.mdx

`Sui_Owned_Objects_Pools` has been deprecated and replaced by `ParallelTransactionExecutor`. 
Adding these changes will redirect the users to the correct solution. 
Bonus: Fixed the hyperlink to `ParallelTransactionExecutor` which was broken.

Deprecate Sui_Owned_Object_Pools

---

crates/sui-graphql-e2e-tests/tests/limits/directives.exp
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs

Passing an unsupported directive should be a user input error, not an internal error.
```
sui-graphql-e2e-tests$ cargo nextest run --features pg_integration -- limits/directives
```
- #18660
---

[GraphQL/Limits] BUGFIX: directives test error type

---

crates/sui-graphql-e2e-tests/tests/limits/directives.exp
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
crates/sui-graphql-rpc/src/server/builder.rs

Two header related clean-ups:
- The version header should no longer be part of the CORS configuration, because we don't expect versions to be configured by (request) header.
- The `ShowUsage` type doesn't need to implement `Header` because we only care about comparing its name.
CI
- #18660
- #18661 
---

[chore][GraphQL/Limits] Clean up headers

---

consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

The PR disables the scheduled synchronizer when we detect local commit to lag compared to the quorum index, same as we do during block processing. It has to be noted that we do not disable the live synchronizer as this will normally be taken care of from the `authority_service` block processing path.
With this change we'll avoid issues that have been observed during crash recovery (or even lagging nodes) where some blocks are received (until the commit voter finally gathers a quorum and cut off the block processing path) and trigger the block synchronization attempting to complete the causal history for the received blocks leading to a big queue of suspended & missing blocks.
CI/PT
Testing on PT environment, on the first screenshot we can see the number of pending suspended blocks in …

[Consensus] disable scheduled synchronizer when commit lag

---

crates/sui-graphql-e2e-tests/tests/limits/directives.exp
crates/sui-graphql-e2e-tests/tests/limits/directives.move
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/extensions/directive_checker.rs
crates/sui-graphql-rpc/src/extensions/mod.rs
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
crates/sui-graphql-rpc/src/server/builder.rs

Trying to do the directive checks at the same time as the query checks complicates both implementations. Split out the directive check into its own extension.
Also fix the directive checks not looking at directives on variable definitions.
```
--features pg_integration              \
-- limits/directives.move
```
- #18660
- #18661 
- #18662 
- #18663 
---

[GraphQL/Limits] Separate out directive checks

---

crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.exp
crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.move
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
crates/sui-graphql-rpc/src/server/builder.rs

Rewriting query limits checker to land a number of improvements and fixes:
- Avoid issues with overflows by counting down from a predefined budget, rather than counting up to the limit and protecting multiplications using `checked_mul`.
- Improve detection of paginated fields: 
- Previously we treated all connections-related fields as appearing as many times as the page size (including the field that introduced the connection, and the `pageInfo` field). This was over-approximated the output size by a large margin. The new approach counts exactly the number of nodes in the output: The connection's root field, and any non-`edges` or `nodes` field will not get multiplied by the page size.
- The checker now also detects connections-related fields even if they are obscured by fragment or …

[GraphQL/Limits] Reimplement QueryLimitsChecker

---

crates/sui-graphql-e2e-tests/tests/limits/directives.exp
crates/sui-graphql-e2e-tests/tests/limits/directives.move
crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.exp
crates/sui-graphql-e2e-tests/tests/limits/output_node_estimation.move
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/extensions/directive_checker.rs
crates/sui-graphql-rpc/src/extensions/mod.rs
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
crates/sui-graphql-rpc/src/server/builder.rs

Split up the extension factory from the extension itself, similar to what we did for `Timeout` before. This avoids the confusion of the single type being created with defaulted fields to act as the factory and then creating new versions of itself to act as the extension.
CI
---

[chore][GraphQL/Limits] Separate QueryLimitChecker extension/factory

---

crates/sui-benchmark/src/workloads/batch_payment.rs
crates/sui-benchmark/src/workloads/delegation.rs
crates/sui-benchmark/src/workloads/shared_counter.rs
crates/sui-benchmark/src/workloads/shared_object_deletion.rs
crates/sui-benchmark/src/workloads/transfer_object.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/shared_object_congestion_tracker.rs

Also some chore to add txn execution status in workloads.
Unit test
---

Add a metric to track per object cost in consensus commit for congestion control

---

crates/sui-storage/src/indexes.rs
crates/typed-store/src/rocks/mod.rs

Index db cfs can become large and require compactions. Write throttling based on compaction bytes can happen after initial ingestion of data, and is hard to investigate. Disable write throttling for index cfs.
Deploy to private testnet.
---

[DB] disable write stalling and stopping due to pending compaction bytes for index cfs

---

crates/mysten-metrics/src/lib.rs
crates/sui-authority-aggregation/src/lib.rs
crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/safe_client.rs
crates/sui-core/src/transaction_orchestrator.rs

tracing for an execute transaction attempt now looks like:

Improve tracing for TransactionOrchestrator, QD, and AuthAgg

---

crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks/mod.rs

We have seen situations where rocksdb throttling briefly causes all threads to block while attempting to write to a throttled table.
However, it is not clear that very rare events such as these will show up in histograms. By tracking them in counters we can see definitively how often and when these events occur.

Record batch writes and inserts that are slower than 1s

---

external-crates/move/crates/move-disassembler/src/disassembler.rs

Always pick whole UTF8 characters.
Tested against a package containing a UTF8 constant.
---

[pick #18710][Disassembler] Fix string contraction logic

---

crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_21.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_44.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_50.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_44.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_50.snap
scripts/compatibility/check-protocol-compatibility.sh

- Remove bad changes from cargo insta
- Remove deleted protocol fields from older snapshots to avoid spurious failures

Remove deleted protocol fields from older snapshots to avoid spurious failures

---

crates/sui-package-resolver/src/lib.rs
crates/sui-package-resolver/src/snapshots/sui_package_resolver__tests__pure_input_layouts_overlapping.snap

From the perspective of input layout calculation, it's fine for a pure input to be referred to multiple times in a PTB, as long as those usages are consistent (all refer to those pure bytes as being the same type).
New unit test:
```
```
---

[Resolver/Inputs] Support layout inference for overlapping inputs

---

docs/content/concepts/tokenomics/sui-bridging.mdx

In line 7:
Sui supports bridging through .... and [Wormhole Portal Bridge](#wormhole-portal-bridge).
Updating line 27 to make the anchor link match with line 7, or else the section jump from lin 7 would fail.
N/A
---

Update sui-bridging.mdx for the correct anchor link

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/unit_tests/execution_driver_tests.rs
crates/sui-core/src/validator_tx_finalizer.rs
crates/sui-e2e-tests/tests/validator_tx_finalizer_e2e_tests.rs
crates/sui-node/src/lib.rs
crates/sui-single-node-benchmark/src/single_node.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
crates/sui-types/src/sui_system_state/simtest_sui_system_state_inner.rs

This PR integrates the validator tx finalizer with the validator service, which is then invoked after handling a transaction.
A node config is used to control whether an instance of the service is created when the service starts.
It is enabled on devnet and testnet. We will enable for mainnet later when we feel confident.
Added e2e simtests.
---

Integrate validator tx finalizer

---

crates/sui-bridge/src/metrics.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/server/governance_verifier.rs
crates/sui-bridge/src/server/handler.rs

as title. `SignerWithCache` today already guarantees single processing of one request (if they are received in a short period of time and not evicted in cache). In this PR we add hit and miss metrics for us to understand how well it works.
https://github.com/MystenLabs/sui/blob/main/crates/sui-bridge/src/server/handler.rs#L152
---

[bridge] add metrics for SignerWithCache

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/shared_object_congestion_tracker.rs
crates/sui-core/src/consensus_manager/mod.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/congestion_control_tests.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_53.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_52.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_53.snap
sdk/graphql-transport/src/methods.ts

Since mysticeti has different commit rate than Narwhal, we want to use different transaction count limit for shared
object congestion control in consensus commit. Therefore, I created a different config for mysticeti, and
the consensus handler will choose to use different limit based on the current consensus algorithm.
We also turn on shared object congestion control on testnet.
simtest updated
cluster testing
---

Create a separate congestion control consensus commit limit for Mysticeti

---

crates/mysten-metrics/Cargo.toml
crates/mysten-metrics/src/lib.rs
crates/mysten-metrics/src/thread_stall_monitor.rs
crates/sui-core/src/validator_tx_finalizer.rs
crates/sui-node/src/lib.rs

Assuming when tokio scheduling stalls temporarily, tasks are not woken up after sleeps. A dedicated task can be used to monitor this issue.
This mechanism will stop reporting when the system is completely frozen, which has been observed once before. This issue will require a separate std::thread to monitor, which can be added if needed in future.
TODO
---

Monitor thread stalls in sui node

---

external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/typing/index_call_invalid_args.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/index_invalid_crash.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/index_invalid_crash.move
external-crates/move/crates/move-compiler/tests/move_2024/typing/index_syntax_methods_miscalled.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/index_underspecified.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/index_underspecified.move

This fixes an issue reported around crashing when there are errors in index calls that then chain to method calls.
Repros added to the compiler suite
---

[move][move-2024] Revised index syntax typing to avoid crash

---

crates/sui-metric-checker/src/lib.rs
crates/sui-metric-checker/src/main.rs
crates/sui-metric-checker/src/query.rs

This allows the following:
1. Check p95 or even p99 in the time range for p50 latency and TPS.
2. Check p50 in the time range for p95 latency.
Config will be modified separately.
Nightly run
---

[Metric Checker] Take specific percentiles for range queries

---

external-crates/move/crates/move-compiler/src/expansion/aliases.rs
external-crates/move/crates/move-compiler/src/expansion/path_expander.rs
external-crates/move/crates/move-compiler/src/shared/ide.rs
external-crates/move/crates/move-compiler/src/shared/string_utils.rs
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/index_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_no_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_check/ide_mode/named_struct_autocomplete.ide.exp

This revises IDE path information to include _all_ available information, not just information based on the position of the name.
A new test, plus updated other tests.
---

[move][ide] Revise IDE path information to always include all possible names.

---

.github/workflows/external.yml
external-crates/move/crates/move-compiler-transactional-tests/tests/tests.rs
external-crates/move/crates/move-core-types/src/effects.rs
external-crates/move/crates/move-stackless-bytecode/src/function_target.rs
external-crates/move/crates/move-stackless-bytecode/src/number_operation.rs
external-crates/move/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/crates/move-vm-runtime/src/session.rs
external-crates/move/crates/move-vm-types/src/data_store.rs
external-crates/move/move-execution/v0/crates/move-bytecode-verifier/src/check_duplication.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/src/session.rs
external-crates/move/move-execution/v1/crates/move-bytecode-verifier/src/check_duplication.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/runtime.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/session.rs
external-crates/move/move-execution/v2/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/move-execution/v2/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/move-execution/v2/crates/move-vm-runtime/src/session.rs

This updates the external workflow to check all crates. It appears that, without this, `cargo` will not check crates with `publish = false` by default.
This updates tests to ensure formatting is applied uniformly in the external crates, plus a few commits explicitly tested behavior.
---

[move] Update external workflow to check formatting for _all_ packages

---

crates/sui-indexer/migrations/mysql/2024-04-24-180008_checkpoints/down.sql
crates/sui-indexer/migrations/mysql/2024-04-24-180008_checkpoints/up.sql
crates/sui-indexer/migrations/pg/2023-08-19-044044_checkpoints/down.sql
crates/sui-indexer/migrations/pg/2023-08-19-044044_checkpoints/up.sql
crates/sui-indexer/migrations/pg/2023-10-06-204335_tx_indices/up.sql
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/models/checkpoints.rs
crates/sui-indexer/src/schema/mod.rs
crates/sui-indexer/src/schema/mysql.rs
crates/sui-indexer/src/schema/pg.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/types.rs

a separate pruner that use `epochs` table and `cp_tx` table to track progress of pruning and handle disaster recovery;
and `checkpoints` table as available range data source.
local run and verify via local client
- progress tracking via epoch, cp, and tx
- verify on checkpoints & tx_ tables
- make sure that the checkpoints table is indeed latest cp_tx cp + 1
- make sure that all cp < min_tx in cp_tx have been pruned
---

indexer pruner: add pruner and prune unpartitioned tables

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/validator_tx_finalizer.rs
crates/sui-e2e-tests/tests/validator_tx_finalizer_e2e_tests.rs
crates/sui-node/src/lib.rs

This PR moves the validator tx finalizer into AuthorityState, since there we have the most accurate information on whether a transaction is newly signed.
Only spawn a thread if it's newly signed.
CI
---

Only spawn validator tx finalizer for newly signed tx

---

external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/cursor_tests/cursor_dot_call_tests.exp
external-crates/move/crates/move-compiler/src/diagnostics/codes.rs
external-crates/move/crates/move-compiler/src/expansion/path_expander.rs
external-crates/move/crates/move-compiler/src/parser/ast.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/src/unit_test/filter_test_members.rs
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/colon_colon_incomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/colon_colon_incomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/colon_colon_incomplete.move

This adds parsing resilience for name access chains needed for IDE-level auto-completion
All old and new tests must pass
---

[move-compiler] Added parsing resilience for name access chains

---

crates/sui-core/src/authority_server.rs
crates/sui-json-rpc/src/axum_router.rs
crates/sui-types/src/traffic_control.rs

Sometimes there can be more than one proxy between the client and the server. In such cases, the `x-forwarded-for` header is appended with the full path of IPs, ostensibly with the client IP being the first. For this reason, we need to fix the parsing to accommodate a list of IPs. However, we additionally have the problem of knowing which IP in the list is the client IP. We cannot assume the first IP in the list is the client IP, as a malicious client could attempt to spoof by writing a junk value in `x-forwarded-for` in the request, to which the internal LBs would append. There are two possible solutions to this:
a) define a custom header and configure our gcs LBS to write to this and overwrite any existing value for that header.
b) add configuration such that the node operator defines …

[TrafficControl] Support multi-hop forwarding

---

consensus/core/src/network/tonic_network.rs
crates/sui-core/src/epoch/epoch_metrics.rs

Currently in testnet we seem to frequently hit the `5 second` connection shutdown timeout which seems to stall even more the epoch change. We can lower the grace period (similar to what used in Anemo - 1 second) .
CI
---

[Consensus] reduce connection shutdown grace period

---

consensus/core/src/authority_node.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

The second part of the recovering from amnesia feature. This PR is implementing the logic to fetch the last own block from the peer network in the synchronizer. It is also adding several tests to confirm the behaviour correctness.
CI
---

[Consensus 2.0] Recover from amnesia - part 2

---

external-crates/move/crates/move-vm-runtime/src/data_cache.rs
external-crates/move/crates/move-vm-runtime/src/interpreter.rs
external-crates/move/crates/move-vm-runtime/src/move_vm.rs
external-crates/move/crates/move-vm-runtime/src/runtime.rs
external-crates/move/crates/move-vm-runtime/src/session.rs
external-crates/move/crates/move-vm-types/src/data_store.rs
external-crates/move/crates/move-vm-types/src/values/value_tests.rs
external-crates/move/crates/move-vm-types/src/values/values_impl.rs

Simplify how `Locals` forms are created in the VM's runtime by directly taking any parameters. This removes a rather large number of checks and logic, making the code much more straightforward. It is _ostensibly_ faster (though dominated by other things).
All the tests still work.
---

[move][move-vm] Simplify locals creation

---

crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/store/mod.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/store/pg_partition_manager.rs

split epoch advance and partition dropping, and move partition dropping to pruner so that all pruning tasks are in sync and tracked by pruner watermark table.
local run and verify that
- partition dropping still works
- pruning are indeed in sync and accurately tracked by `pruner_watermark_cp` table
---

indexer: move partition dropping to pruner

---

docs/content/references/contribute/style-guide.mdx
docs/content/standards/deepbookv3/design.mdx
docs/content/standards/deepbookv3/swaps.mdx

Addresses requests made by aslan. Adds a style guide entry for using code in headings. Previous opinions were 50/50 and he tipped the scale.
Original request was to remove the bullets in `swap_exact_quote_for_base` to make it the same as the previous description. But the suggestion is to keep the bullets to break up the content and make the object list easier to read.
Also breaks up the last paragraph on Design because it looked weird. 
---

[docs] Content updates and style changes

---

Cargo.lock
crates/sui-config/Cargo.toml
crates/sui-config/src/node.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-swarm-config/src/genesis_config.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm-config/tests/snapshot_tests.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

This allows setting consensus Parameters via NodeConfig.
Also, do some minor cleanups. But the bulk of the cleanup will happen when we stop supporting Narwhal.
---

Integrate consensus Parameters into NodeConfig

---

crates/sui-proc-macros/src/lib.rs
scripts/simtest/cargo-simtest

So that other projects can choose their own move package for this static initialization.
---

Customize statis initialize move dir in simtest

---

crates/sui-core/src/execution_cache/writeback_cache.rs

This fixes a very unlikely race where:
- notify_read_executed_effects is called
- the effects are available and are returned immediately
- transaction itself has not yet been written to pending_transaction_writes
- reader thread tries to read the tx and asserts that it exists

Transaction must be written before executed_effects_digests

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/authority_node.rs
consensus/core/src/context.rs
crates/sui-config/src/node.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

1. Make consensus parameters optional in node config, since it has not been populated before.
2. Make consensus_config::Parameters::db_path non optional. It is always set from the node config after integration with Sui. If empty path causes problem, it needs to be detected from Sui or within consensus.
CI
---

[Consensus] make config optional

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

Before removing v1, we need to ensure that no one has v2 force disabled, as it would otherwise lead to a fork during upgrade due to forcing v2 to be enabled mid-epoch.
---

[StateAccumulator] Remove v2 disable functionality from node config

---

.config/nextest.toml
Cargo.lock
Cargo.toml
crates/mysten-network/src/client.rs
crates/mysten-network/src/multiaddr.rs
crates/mysten-network/src/server.rs
crates/sui-analytics-indexer/Cargo.toml
crates/sui-data-ingestion/src/workers/archival.rs
crates/sui-data-ingestion/src/workers/blob.rs
crates/sui-graphql-rpc-client/src/lib.rs
crates/sui-graphql-rpc-client/src/response.rs
crates/sui-graphql-rpc-client/src/simple_client.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-metric-checker/src/lib.rs
crates/sui-node/src/metrics.rs
crates/sui-oracle/Cargo.toml
crates/sui-proxy/src/lib.rs
crates/sui-rest-api/src/response.rs
crates/sui-sdk/src/lib.rs
crates/sui-security-watchdog/Cargo.toml
crates/sui-source-validation-service/Cargo.toml
crates/sui-storage/src/http_key_value_store.rs
crates/sui-storage/src/object_store/http/mod.rs
crates/sui-storage/src/object_store/mod.rs
crates/sui-storage/src/object_store/util.rs
crates/sui/src/client_commands.rs
crates/suiop-cli/src/cli/lib/oauth/mod.rs
scripts/simtest/cargo-simtest
scripts/simtest/config-patch

Update a number of http related libraries, including but not limited to:
- reqwest
- object-store
A future PR will continue by upgrading anemo, rustls, hyper
---

chore: update reqwest, object-store

---

sdk/docs/pages/typescript/utils.mdx

According to the function definition, the Docs description is backwards
function `fromB64` receive `base64 string` return `Uint8Array`
But in the description of the Docs it is the opposite :
>`fromB64`: Serializes a Uint8Array to a base64 string
---

[Docs] Update utils.mdx

---

consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/network/tonic_network.rs
crates/sui-core/src/consensus_manager/mod.rs
crates/sui-core/src/mysticeti_adapter.rs

* Increase timeout when waiting for consensus to start from `30s -> 60s`. Came across cases where commit recovery was taking a bit longer and might make sense to have a bit more tolerance.
* Add more logs in consensus components and switch them to `info` - it's ok since those should be printed once per epoch
* Make the consensus protocol choice log a `debug` . The method `get_consensus_protocol_in_epoch` is now being used from `get_max_accumulated_txn_cost_per_object_in_commit` which is called on every sequenced transaction leading to a very spammy log output:
---
For each box you select, include information after the relevant …

[Consensus] refine logging & small timeout changes

---

crates/sui-bridge-cli/src/lib.rs
crates/sui-bridge-cli/src/main.rs
crates/sui-bridge/src/types.rs
crates/sui-bridge/src/utils.rs

1. now you can use `--network testnet` to avoid having to provide proxy address
2. add more stuff to print functions, including nonces
3. print everything in json, for easier piped processing
See offline nodes:
```
sui-bridge-cli view-sui-bridge  --sui-rpc-url https://rpc.testnet.sui.io:443 --ping --hex | jq '.result.committee[] | select(.status == "offline")'
```
See eth nonce:
```
sui-bridge-cli view-eth-bridge --network testnet --eth-rpc-url https://ethereum-sepolia-rpc.publicnode.com
```
See sui nonce:
```
sui-bridge-cli view-sui-bridge  --sui-rpc-url https://rpc.testnet.sui.io:443 --ping --hex | jq '.result.nonces'
```
--- …

[bridge cli] print data in json and print more data

---

external-crates/move/crates/move-compiler/src/expansion/path_expander.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/missing_type_suggestions.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/missing_type_suggestions.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/missing_type_suggestions.move
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/partial_type_suggestions.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/partial_type_suggestions.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/partial_type_suggestions.move

This modifies the parser to build `UnresolvedError` for types that don't parse, and then uses those during expansion to provide IDE alias information at those locations.
New IDE tests, plus everything else still works as expected.
---

[move][ide] Change parsing / expansion to report IDE suggestions for missing types

---

crates/sui-bridge/src/client/bridge_authority_aggregator.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/monitor.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/test_utils.rs

This PR adds `BridgeMonitor` which receives all `SuiBridgeEvent` (and probably `EthBridgeEvent` as well soon) and handles them accordingly. In this PR we add the handling for `CommitteeMemberUrlUpdateEvent` by retrieving the latest committee onchain and swap it in.
added unit tests
---

[bridge] add BridgeMonitor and handle url change event

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/monitor.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/types.rs

as title. Note the actual usage of the watch channel hasn't been wired up in ActionExecutor. It will be in the next PR.
unit tests
---

[bridge] let monitor handle emergecny op

---

consensus/core/src/network/anemo_network.rs
consensus/core/src/network/tonic_network.rs
crates/mysten-network/src/multiaddr.rs

This avoids external network on local cluster tests.
`cargo nextest run -p sui-swarm`
---

[Consensus] bind to localhost if requested

---

crates/sui-move/src/build.rs
crates/sui/src/sui_commands.rs
crates/sui/tests/cli_tests.rs
crates/sui/tests/data/depends_on_simple/Move.toml
crates/sui/tests/data/depends_on_simple/sources/depends_on_simple.move
crates/sui/tests/data/simple/Move.toml
crates/sui/tests/data/simple/sources/simple.move
sdk/deepbook/test/e2e/setup.ts
sdk/kiosk/test/e2e/setup.ts
sdk/typescript/test/e2e/utils/setup.ts

`sui move build` does not ordinarily require a network connection because it doesn't need to know about a chain's ID. The exception is when `--dump-bytecode-as-base64` is specified: In this case, we should resolve the correct addresses for the respective chain (e.g., testnet, mainnet) from the `Move.lock` under automated address management.
Two options to fix `sui move build --dump-bytecode-as-base64` to work with automated addresses / by resolving from the `Move.lock`: 
1. Require an extra `--chain-id` flag on `sui move build`, which a user must specify along with `--dump-bytecode-as-base64`. E.g.,
```
sui move build --dump-bytecode-as-base64 --chain-id "$(sui client chain-identifier)"
``` 
OR
2. Require a network connection _only when_ `--dump-bytecode-as-base64` is set and and resolve …

move: dump-bytecode-as-base64 uses Move.lock addresses

---

crates/sui-e2e-tests/tests/passkey_e2e_tests.rs

my guess is the modified signature byte is already 0 and does not need modification. fix here is to deterministically flip the byte. 
---

fix: handle nondeterminism in test

---

docs/content/guides/developer/first-app/write-package.mdx

Outdated doc mention as of address management:
> The publish process replaces the `0x0` address with an actual on-chain address.
N/A
---

docs: update outdated mention on Move.toml

---

crates/sui-graphql-e2e-tests/tests/epoch/chain_identifier.exp
crates/sui-graphql-e2e-tests/tests/epoch/chain_identifier.move
crates/sui-graphql-rpc/src/types/chain_identifier.rs
crates/sui-indexer/migrations/pg/2024-07-13-003534_chain_identifier/down.sql
crates/sui-indexer/migrations/pg/2024-07-13-003534_chain_identifier/up.sql
crates/sui-indexer/src/models/checkpoints.rs
crates/sui-indexer/src/schema/mod.rs
crates/sui-indexer/src/schema/mysql.rs
crates/sui-indexer/src/schema/pg.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

This PR puts chain identifier into its own table so that queries of chain identifier does not depend on the existence of checkpoint 0 in the db, which may be pruned away.
Tested against devnet locally and added a gql e2e test.
---

[gql][indexer] index chain identifier into its own table

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/metrics.rs

in `ActionExecutor`, use `bridge_pause_rx` to decide whether to submit tx to Sui.
new unit test
---

[bridge] do not submit tx to sui if paused

---

crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/complex.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/eth_syncer.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/node.rs

As title, this will make some e2e tests easier to write.
It's worth noting that surprisingly this does not help with fullnode sync up speed in the test, which is the main source of slowness in bridge e2e tests.
existing tests
---

allow custom validator num in bridge tests

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/monitor.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-bridge/src/types.rs

Today, when receiving an `AddNewToken` event, orchestrator updates the sui type tags map and send to the watch channel that action execution watches. In this PR, we consolidate the handling of this event with the newly added monitor module. In the new approach, orchestrator sends the event to monitor, instead of handling it in place. Also the type tag maps is stored in a `ArcSwap` to allow monitor to change it. Hence we get rid of the watch channel.
Added unit tests.
---

[bridge] move add new coin's handling to monitor

---

crates/sui-bridge-indexer/src/eth_worker.rs
crates/sui-bridge-indexer/src/latest_eth_syncer.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/eth_client.rs
crates/sui-bridge/src/lib.rs
crates/sui-bridge/src/metered_eth_provider.rs
crates/sui-bridge/src/metrics.rs
crates/sui-bridge/src/monitor.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/test_utils.rs
crates/sui-bridge/src/types.rs

`MeteredEthHttpProvider` counts every eth rpc query and its latency. This will be useful to track the eth rpc usage.
unit tests
---

introduce MeteredEthHttpProvider that meters rpc usage

---

crates/sui-core/src/transaction_orchestrator.rs
crates/sui-e2e-tests/tests/full_node_tests.rs
crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
crates/sui-json-rpc/src/balance_changes.rs
crates/sui-json-rpc/src/transaction_execution_api.rs
sdk/graphql-transport/test/compatability.test.ts

This patch deprecates the `WaitForLocalExecution` request type that was
previously relied upon to calculate object and balance changes. Instead
the new `ExecuteTransactionRequestV3` functionality is used to request
output object data directly from the validators so that we no longer
need to rely on waiting for local execution.
The `WaitForLocalExecution` feature still exists and will still properly
wait to return a response to a client until after the transaction is
executed locally in order to retain the Read-after-Write semantics that
some clients may presently rely on.
--- …

jsonrpc: use ExecuteTransactionRequestV3 when executing a transaction

---

crates/typed-store/src/rocks/mod.rs

Currently for column families with high write rate, write stalling and stopping can happen after there are 24 pending L0 files, for example in consensus DB during consensus catchup. This hurts the throughput significantly and reduces the stability of the system. The # of L0 files to compact is reduced back to the default (4), to speed up L0 compactions. Also, for DB that optimizes for write throughput, the thresholds to stall and stop writes are further increased.
Logs observed from one validator:
```
2024/07/31-03:59:57.695047 2702658 [WARN] [db/column_family.cc:991] [blocks] Stalling writes because we have 24 level-0 files rate 16777216
2024/07/31-04:00:13.393421 2702607 [WARN] [db/column_family.cc:991] [blocks] Stalling writes because we have 24 level-0 files rate 13421772 …
```

[rocksdb] increase write stopping threshold for L0 files

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

This adds Ambrus aws cognito as a provider in node config - once 2f+1 validators has this in default config for JWKs, its considered active on testnet/mainnet.
Relevant ZK-circuit PR which is merged : https://github.com/MystenLabs/zklogin-circuits/pull/169/files
---

feat: enable ambrus aws cognito as zklogin provider

---

crates/sui-data-ingestion-core/src/progress_store/mod.rs

always update internal state of progress store wrapper. It should speed up cleaning up local files in case if the host is slow secondary

[data ingestion] update internal state of progress store wrapper

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_54.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_54.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_54.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Enables the native randomness (random beacon) feature on sui mainnet.
Extensive manual and automated testing.
---

Enable random beacon on mainnet

---

consensus/core/src/core.rs
consensus/core/src/metrics.rs
consensus/core/src/transaction.rs
crates/sui-config/src/node.rs

- With consensus latency consistently < 1s under max TPS, the consensus adapter limit can be significantly reduced even to support high TPS.
- Reduce # of transactions that can be included in a block.
Private Testnet
---

[Consensus] update a few parameters

---

external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/tests/move_2024/matching/match_break_parse.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/match_return_parse.move

This adds `Tok::Match` to the `at_start_of_exp` check in the parser
Added tests that failed before the fix.
---

[move][move-2024] Fix a small bug in how match was handled in parsing

---

crates/sui-rosetta/src/block.rs
crates/sui-rosetta/src/state.rs

Transaction response now include raw input to be parsed during the transformation to the Oparations object, so in case of a pay coin operation we can get the currency type.
Covered by the tests.
---

[rosetta] Adds raw input option for the transformation to operations object in block endpoints

---

crates/sui-core/src/validator_tx_finalizer.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-e2e-tests/tests/validator_tx_finalizer_e2e_tests.rs
scripts/simtest/simtest-run.sh

Introduce a timing config, and set the values differently for prod vs tests.
This allows tests to run much more quickly.
Re-enable the simtests in nightly.
CI
---

Improve tx finalizer simtests

---

external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-docgen/src/docgen.rs
external-crates/move/crates/move-docgen/tests/sources/enums_test.move
external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_inline.md
external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_inline_no_fold.md
external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_separate.md
external-crates/move/crates/move-model/src/builder/exp_translator.rs
external-crates/move/crates/move-model/src/builder/model_builder.rs
external-crates/move/crates/move-model/src/builder/module_builder.rs
external-crates/move/crates/move-model/src/lib.rs
external-crates/move/crates/move-model/src/model.rs

Fixes some issues with enums in Move model creation, and adds support for enums in docgen, and adding doc comments to enum variants. 
Added a test for docgen with enums -- this tests both the bugfixes and also the generation of doc comments for enums. 
---

[move] Fixes for enums in Move model + add support in docgen

---

crates/sui-data-ingestion-core/src/reader.rs

should decrease pressure on remote store. The parameter can be bumped manually for backfill jobs

[data ingestion] decrease default queue length for remote reader

---

external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/parser/ast.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/use_incomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/use_incomplete.move
external-crates/move/crates/move-compiler/tests/move_check/parser/use_module_member_invalid_missing_close_brace.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/use_module_member_invalid_missing_close_brace.move
external-crates/move/crates/move-compiler/tests/move_check/parser/use_module_member_invalid_missing_semicolon.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/use_module_member_invalid_missing_semicolon.move

This PR adds parsing resilience when parsing use declarations. The idea is to recognize partially parsed statements (examples below and also in the new test) to enable auto-completion in the IDE.
```
use a::m2::
use a::m2::{foo
use a::m2::{foo, bar
use a::{m2::{foo, bar
use a::{m2::{foo, bar}, m3
```
New and all tests must pass
---

[move-compler] Added parser resilience for use declarations

---

crates/sui-indexer/migrations/2023-08-19-044044_checkpoints/down.sql
crates/sui-indexer/migrations/2023-08-19-044044_checkpoints/up.sql
crates/sui-indexer/migrations/2023-10-06-204335_tx_indices/up.sql
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/models/checkpoints.rs
crates/sui-indexer/src/schema.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/types.rs

a separate pruner that use `epochs` table and `cp_tx` table to track progress of pruning and handle disaster recovery;
and `checkpoints` table as available range data source.
local run and verify via local client
- progress tracking via epoch, cp, and tx
- verify on checkpoints & tx_ tables
- make sure that the checkpoints table is indeed latest cp_tx cp + 1
- make sure that all cp < min_tx in cp_tx have been pruned
---
How did you …

[pick] indexer pruner: add pruner and prune unpartitioned tables (#18495)

---

crates/sui-core/src/db_checkpoint_handler.rs

Because we run snapshot upload and garbage collection as a background task but we perform rocksdb checkpointing at end of epoch unconditionally for configured nodes, any failure in either the upload or garbage collection path will lead to an accumulation of old db checkpoints, which will inevitably lead to disk filling and make things more difficult to debug.
This PR adds a metric to periodically count the number of rocksdb checkpoints that exist on local disk. Except in rare cases (backfills), this number should generally be lower than 3, so we can add alerting on this for early intervention.
👀 
---
For each box you select, include information after the relevant heading …

[snapshots] Add metric for number of local db checkpoints

---

.github/workflows/bridge.yml
bridge/evm/.gitignore
bridge/evm/README.md
bridge/evm/foundry.toml
bridge/evm/remappings.txt
bridge/evm/soldeer.lock

Replacing the dependency management from manual forge install to use the recommended Soldeer dependancy management tool. 
CI checks will test this update
---

Replace forge install with soldeer

---

external-crates/move/crates/move-analyzer/editors/code/package-lock.json
external-crates/move/crates/move-analyzer/editors/code/package.json

I was a bit overeager in bumping up extension version number and this PR brings it back (to `1.0.10`) to be consistent with what should be the next version in the marketplace:

[move-ide] Version number consistent with marketplace

---

.changeset/cuddly-days-wash.md
sdk/zklogin/src/poseidon.ts
sdk/zklogin/test/poseidon.test.ts

Turns out we don't check anywhere that the inputs fit into the field and neither does the poseidon-lite library (it just truncates elements and fits them into the field). 
Instrumenting poseidon seems like the simplest way to do this. The other option (which I have not taken) is to instrument as soon as we receive some inputs..
---

[zkLogin] Check that bigints fit into the field for extra safety

---

crates/sui-data-ingestion-core/src/progress_store/mod.rs
crates/sui-data-ingestion/src/progress_store.rs

In a setup where multiple processes are executing the same workflow with a shared progress store, there's a potential race condition when updating a watermark. 
This PR introduces a fix on the DynamoDB side, ensuring that the new version is stored only if it is higher than the current one

[data ingestion daemon] dynamodb progress store: make updates conditional

---

sui_programmability/examples/README.md

Clean-up the `sui_programmability` directory for good. It has been a month since everything was ported to the `examples` directory.

chore: [Examples] Remove sui_programmability

---

crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

The PR introducing the `rootVersion` parameter to `Query.owner` raced with the PR that introduced `UInt53`. This PR fixes the race by using `UInt53` as the type for `rootVersion`.
```
```
---

fix: [GraphQL/Owner] rootVersion: UInt53

---

consensus/core/src/context.rs

On Windows, `Instant::now()` can be close to 0 and we cannot subtract from that.
CI. Verifying on a Windows machine.
---

[Consensus] avoid subtracting from current Instant

---

.changeset/seven-pets-count.md
sdk/typescript/src/client/client.ts

[ts sdk] replace WaitForLocalExecution with waitForTransaction

---

external-crates/move/crates/move-docgen/tests/sources/enums_test.move
external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_inline.md
external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_inline_no_fold.md
external-crates/move/crates/move-docgen/tests/sources/enums_test.spec_separate.md
external-crates/move/crates/move-model/src/builder/exp_translator.rs
external-crates/move/crates/move-model/src/exp_generator.rs
external-crates/move/crates/move-model/src/model.rs
external-crates/move/crates/move-model/src/ty.rs

Fixes a bug in the Move model around enums, and does a small bit of cleanup in that area. 
Added a new test for the scenario.
---

[move] Add further support for enums in Move model

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/commit.rs
consensus/core/src/commit_consumer.rs
consensus/core/src/commit_observer.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/commit_vote_monitor.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/lib.rs
consensus/core/src/synchronizer.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs

`CommitSyncer` can download more transactions than what consensus handler and execution can process in the same amount of time. This PR adds backpressure to commit syncer based on # of commits not processed by consensus handler.
Also, record commit votes from blocks fetched through Synchronizer for completeness.
CI
---

[Consensus] stop commit sync when consensus handler cannot keep up

---

external-crates/move/crates/move-compiler-transactional-tests/tests/matching/field_ordering.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/matching/field_ordering.move
external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs
external-crates/move/crates/move-compiler/src/shared/matching.rs
external-crates/move/crates/move-compiler/src/typing/match_analysis.rs
external-crates/move/crates/move-compiler/tests/move_2024/matching/field_order_counterexample.exp
external-crates/move/crates/move-compiler/tests/move_2024/matching/field_order_counterexample.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/stloc_error.move

Revise match compilation that ensures misordered fields are sorted when bindings are created.
Two new tests to ensure things work correctly. I will add more tests ASAP as well.
---

[move][move-2024] Fix match compilation field ordering

---

crates/sui-cluster-test/src/test_case/coin_index_test.rs
crates/sui-cluster-test/src/test_case/fullnode_build_publish_transaction_test.rs
crates/sui-core/src/unit_tests/move_integration_tests.rs
crates/sui-json-rpc-tests/tests/balance_changes_tests.rs
crates/sui-json-rpc-tests/tests/rpc_server_tests.rs
crates/sui-move-build/src/lib.rs
crates/sui-move/src/build.rs
crates/sui-oracle/tests/integration_tests.rs
crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs

Fix a bug in tests that publish packages where the publish transaction was always constructed referring to dependencies at their original IDs, and not their storage IDs.
This has not caused a problem to date, meaning these tests may not publish a package that depends on an upgrade package, but to avoid confusion `get_dependency_original_package_ids` has been replaced with `get_dependency_storage_package_ids`.
Similarly, `get_package_dependencies_hex` has been replaced with an invocation of `get_dependency_storage_package_ids`.
CI +:
```
sui$ cargo build --bin sui
sui$ cd tmp
sui$ ~/sui/target/debug/sui move new test
sui$ # make it possible to compile
sui$ ~/sui/target/debug/ui move build --dump-bytecode-as-base64
```
- #18956 
- #18959
- #18978
- #18960 
---
Check each box that your …

fix(test): publish depending on upgrade

---

Cargo.lock
crates/sui-cluster-test/src/test_case/coin_index_test.rs
crates/sui-cluster-test/src/test_case/fullnode_build_publish_transaction_test.rs
crates/sui-core/src/unit_tests/move_integration_tests.rs
crates/sui-json-rpc-tests/tests/balance_changes_tests.rs
crates/sui-json-rpc-tests/tests/rpc_server_tests.rs
crates/sui-move-build/src/lib.rs
crates/sui-move/src/build.rs
crates/sui-oracle/tests/integration_tests.rs
crates/sui-package-management/Cargo.toml
crates/sui-package-management/src/lib.rs
crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs
crates/sui-source-validation-service/src/lib.rs
crates/sui-source-validation/Cargo.toml
crates/sui-source-validation/src/error.rs
crates/sui-source-validation/src/lib.rs
crates/sui-source-validation/src/tests.rs
crates/sui/src/client_commands.rs

Source validation additionally checks that dependencies in the linkage table of the on-chain package match the published dependencies from the source package.
Previously it was possible to construct a scenario where source verification would succeed even though a package's representation on-chain did not exactly match, because one of the dependencies mismatched on version but between two versions that were themselves identical.
New tests exercising the scenario mentioned above:
```
sui-source-validation$ cargo nextest run -- linkage_differs
```
- #18956 
- #18959
- #18978
- #18960 
- #18962
--- …

feat: [Source Validation] Check linkage

---

sdk/enoki/src/EnokiClient/index.ts
sdk/enoki/src/EnokiClient/type.ts

* use query instead of body params
* add status to subnames response
---

getSubnames api updates

---

.github/workflows/cargo-llvm-cov.yml
scripts/simtest/codecov.sh

Set `SIMTEST_STATIC_INIT_MOVE` variable for Code Coverage due to https://github.com/MystenLabs/sui/pull/18752
https://github.com/MystenLabs/sui/actions/runs/10406180594/job/28818615076

Set `SIMTEST_STATIC_INIT_MOVE` variable for Code Coverage 

---

external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-package/src/resolution/dependency_cache.rs

This PR fixes a problem recently reported in https://github.com/MystenLabs/sui/issues/18749 and https://github.com/MystenLabs/sui/issues/18983. When creating `git` commands using `Command::new(...).status()` standard input inherited from VSCode was somehow causing the child process to hang, even though the commands created did not in fact require any input. This only happened on Windows and while admittedly I do not understand the root cause (perhaps one of the reviewers can help), it does fix the problem.
All existing tests must pass. Additionally, manually verified that the build no longer hangs on Windows.

[move-ide] Fixed a bug preventing pkg build from VSCode

---

crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-indexer/migrations/pg/2023-11-29-193859_advance_partition/down.sql
crates/sui-indexer/src/db.rs
crates/sui-indexer/src/test_utils.rs

the issue was that, prev indexer db reset was done via dropping all tables, which is problematic when we change a PG PROCEDURE parameter, see this slack message. https://mysten-labs.slack.com/archives/C03TCGDF45N/p1723507055114959
this caused issues on CI after merging https://github.com/MystenLabs/sui/pull/18899 and it got reverted, this pr changes it to reverting all migrations and cleans up the table dropping codes
locally
- reset DB before #18899 
- cherry-pick this pr
- cherry-pick #18899
run cmd below, which was the cmd on CI that ran into issue 
```
DB_POOL_SIZE=10 cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --reset-db
```
--- …

indexer fix: reset db via reverting migrations

---

crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-indexer/migrations/pg/2023-11-29-193859_advance_partition/down.sql
crates/sui-indexer/src/db.rs
crates/sui-indexer/src/test_utils.rs

the issue was that, prev indexer db reset was done via dropping all tables, which is problematic when we change a PG PROCEDURE parameter, see this slack message.
https://mysten-labs.slack.com/archives/C03TCGDF45N/p1723507055114959
this caused issues on CI after merging
https://github.com/MystenLabs/sui/pull/18899 and it got reverted, this pr changes it to reverting all migrations and cleans up the table dropping codes
locally
- reset DB before #18899 
- cherry-pick this pr
- cherry-pick #18899
run cmd below, which was the cmd on CI that ran into issue 
```
DB_POOL_SIZE=10 cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgres@localhost/gegao" --reset-db
```
--- …

indexer fix: reset db via reverting migrations (#18993)

---

crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-sdk/src/apis.rs

If transaction execution requires waiting for local execution, then simulate it by polling, to account for the fact that fullnodes will soon start to ignore this parameter.
Run the programmable transaction SDK example:
```
sui-sdk$ cargo run --example programmable_transactions_api
```
Run the tic-tac-toe E2E example:
```
examples/tic-tac-toe/cli$ env $(cat testnet.env) \
cargo run -- new $(sui client active-address)
|   |
---+---+---
|   |
---+---+---
|   |
-> X: <ADDRESS>
O: <ADDRESS>
GAME: <GAME>
examples/tic-tac-toe/cli$ env $(cat testnet.env) \
cargo run -- move -r 0 -c 0 $GAME
...
```
--- …

feat(rust-sdk): Simulate WaitForLocalExecution

---

crates/sui-indexer/src/db.rs

previous fix did not work well when migration run history in __diesel_schema_migrations table is not complete.
I also considered dropping the database as we usually do locally, but a connection cannot drop the database in its own connection and ended up having errors of 
```
cannot drop the currently open database
```
thus this pr drops all tables, functions and procedures explicitly for PG and tables for MySQL as we now only have tables in MySQL.
1. diesel reset on latest main
2. cherry-pick this pr to 1.31 and 1.30, run cmd below and make sure that DB are indeed reset
```
DB_POOL_SIZE=10 cargo run --bin sui-indexer -- --db-url =DB_URL --reset-db
```
--- …

indexer: DB reset to handle incomplete migration history

---

crates/sui-graphql-e2e-tests/tests/packages/versioning.exp
crates/sui-graphql-e2e-tests/tests/packages/versioning.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/move_module.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/sui_address.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Implement `Query.package` and `MovePackage.atVersion` to query a package at a specific version, using the new fields added to the `packages` table, exposed via some new data loaders.
New transactional tests:
```
--features pg_integration                     \
-- packages/versioning
```
- #17686 
- #17687 
- #17688 
- #17689 
- #17691
- #17694 
- #17695 
- #17542 
- #17726
- #17543
- #17692
---

[GraphQL/MovePackage] Query by ID and version

---

crates/sui-graphql-e2e-tests/tests/packages/versioning.exp
crates/sui-graphql-e2e-tests/tests/packages/versioning.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Add a new kind of package point look-up to get the latest version of the package at a given ID (or from another `MovePackage`). For system packages, this is analogous to getting the latest version of the object at that ID, but the versions of other packages all exist at different IDs.
New transactional tests:
```
--features pg_integration                     \
-- packages/versioning
```
- #17686 
- #17687 
- #17688 
- #17689 
- #17691
- #17694 
- #17695 
- #17542 
- #17726
- #17543
- #17692
--- …

[GraphQL/MovePackage] Query for latest version

---

crates/sui-graphql-e2e-tests/tests/packages/versioning.exp
crates/sui-graphql-e2e-tests/tests/packages/versioning.move
crates/sui-graphql-rpc/schema/current_progress_schema.graphql
crates/sui-graphql-rpc/src/types/event.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Adds a query, `Query.packages` for fetching all packages that were introduced within a given checkpoint range. Useful for fetching package contents in bulk, to do local analyses.
New E2E tests:
```
--features pg_integration                     \
-- packages/versioning
```
Also tested for performance against a large read replica (the query planner quotes a high estimate for the query but the actual results do not take very long to run because queries on many sub-partitions are eliminated).
- #17686 
- #17687 
- #17688 
- #17689 
- #17691
- #17694 
- #17695 
- #17542 
- #17726
- #17543
- #17692 
- #17693 
--- …

[GraphQL/MovePackage] Paginate by checkpoint

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_55.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_55.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_55.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Turns on enums in mainnet.
CI
---

[move] Enable enums in mainnet

---

crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs

This reverts commit de8ae3c38c01011ade7e8bc0de70ef7076514ed4.
This change was introduced in the absence of optimisations that are going out as part of the next GraphQL release, so reverting so that we get the fully correct behaviour again (consistent lookup).
Existing zkLoginVerifySignature E2E tests.
---

revert(18170): patch for fetching latest dynamic field state for zkloginverifysignature

---

crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks/mod.rs

We measure number of bytes by cf for `put`, and measure total written in the batch by DB, but do not have breakdown for batch written bytes by cf. This metrics adds the breakdown by cf for batch writes

Measure RocksDB batch put bytes by cf

---

crates/sui-replay/src/replay.rs

This fixes a bug in the replay tool where if the transaction checked for the existence of the dynamic field before creating it, we would fail to be able to replay the transaction locally since the replay tool was not properly handling the underlying error.
Tested manually on a failing transaction.

[replay] Fix issue when replaying transactions taht query existence of dynamic fields before creating it

---

.github/workflows/release-notes-generator.yml
scripts/release_notes.py

Instead of running`./scripts/release_notes.py generate` locally, we should be doing this via a workflow and also be able to create a new release within the same workflow. 
https://github.com/MystenLabs/sui/actions/runs/10462421870/job/28972625617

Release Notes Generator

---

crates/sui-core/src/transaction_orchestrator.rs

We are about to deprecate local execution. This PR gets rid of the loop that subscribes effects from quorum driver and execute them locally. This was an optimization and it should be safe to remove at this point. Removing this also allows us to see clear metrics on the number of local execution requests received from the network.
---

[LocalExecution] Remove local execution loop from FN

---

apps/wallet/src/ui/app/components/address-input/validation.ts

Add expiry time to cached SuiNS name validation

---

crates/sui-json-rpc-tests/tests/transaction_tests.rs

`transaction_tests::test_get_fullnode_transaction` included a flaky assertion that if you fetch 5 transactions, then the rest of the transactions, and then fetched the latest 10 transactions, the latter would match up with the suffix of the former two queries concatenated together.
This does not work in general (at least not with this test set-up), because of consensus commit transactions.
I have updated the test to check a similar property: That if you fetch 5 transactions, then the rest, and then fetch the first 10 transactions, then the prefixes match (this tests that transaction order is stable).
There are other existing tests for what happens when you query transactions in descending order.
This seed previously exhibited the failure, and now it succeeds.
```
sui-json-rpc-tests$ …
```

fix(jsonrpc): Flaky fullnode JSON-RPC test

---

consensus/core/src/authority_node.rs
consensus/core/src/block_verifier.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/error.rs
consensus/core/src/transaction.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_55.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_55.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_55.snap

1. move transaction count per block limit to protocol config.
2. reduce the transaction bytes per block limit to 512KB, based on the transaction count limit.
3. verify the limits in `BlockVerifier`
Unit test
---

[Consensus] move transaction count limit to protocol config

---

crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/data/package_resolver.rs
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/event.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/transaction_block.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap
crates/sui-json-rpc-tests/tests/transaction_tests.rs
crates/sui-package-dump/src/lib.rs
crates/sui-tool/src/commands.rs

Gathering all the suggested docs fixes across the stack in #17543 into one PR.
:eyes:
- #19047 
---

fix(graphql): Docs fixes from #17543

---

crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/checkpoints/checkpoint_executor/metrics.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/checkpoint_output.rs
crates/sui-core/src/checkpoints/metrics.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/quorum_driver/metrics.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/safe_client.rs
crates/sui-core/src/transaction_orchestrator.rs
crates/sui-json-rpc-api/src/lib.rs
crates/sui-json-rpc/src/coin_api.rs
crates/sui-json-rpc/src/governance_api.rs
crates/sui-json-rpc/src/indexer_api.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-network/src/state_sync/metrics.rs
crates/sui-network/src/state_sync/mod.rs
crates/sui-oracle/src/lib.rs
crates/sui-oracle/src/metrics.rs
crates/sui-types/src/messages_checkpoint.rs
narwhal/primary/src/consensus/bullshark.rs
narwhal/primary/src/consensus/metrics.rs

mysten_metrics variant is difficult to use in Grafana because its precomputation of percentiles makes it impossible to aggregate streams from multiple hosts in a statistically valid way.

Migrate users of mysten_metrics Histogram to prometheus Histogram

---

crates/telemetry-subscribers/src/lib.rs

This changes allows specifying the open-telemetry service name to the `telemetry-subscribers` crate, by setting the `OTEL_SERVICE_NAME` environment variable. This defaults to sui-node, so there is no change in behaviour when unset.
As `OTEL_SERVICE_NAME` is not automatically consulted by the otel rust implementation, this uses the environment variable to perform the update in `telemetry-subscribers`.
The change is minor, the code compiles, and the environment variable is spelled correctly.
--- …

feat: allow specifying OTEL service name with OTEL_SERVICE_NAME

---

crates/sui-security-watchdog/src/query_runner.rs

Handle empty result set. Ran locally, works

Fix empty result set in wallet monitoring service

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_55.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_55.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_55.snap
external-crates/move/crates/move-vm-config/src/runtime.rs
external-crates/move/crates/move-vm-runtime/src/runtime.rs
sui-execution/latest/sui-adapter/src/adapter.rs
sui-execution/v0/sui-adapter/src/adapter.rs
sui-execution/v1/sui-adapter/src/adapter.rs
sui-execution/v2/sui-adapter/src/adapter.rs

Update the semantics around serialization errors when computing type layouts to follow the underlying layout errors more closely. 
Manually tested.

[move] Update error behavior on serialization boundaries

---

crates/sui-core/src/storage.rs

If the fullnodes is unpruned, then we should return 0 directly for lowest available cp.
---

return 0 for lowest available cp on unpruned fn

---

consensus/core/src/lib.rs
crates/sui-core/src/mysticeti_adapter.rs

This makes the submission failure more obvious when it is due to exceeding size limit.
CI
---

[Consensus] panic in tests when transaction exceeds consensus size limit

---

crates/sui-core/src/rest_index.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/tx_processor.rs
crates/sui-types/src/full_checkpoint_content.rs

per Xun's report 
https://linear.app/mysten-labs/issue/DP-43/bug-epochendindexingobjectstore-might-contain-multiple-versions-of
CI
ideally in the long run we want to have an embedded DB and test it on CI with a test, but we lack that today.
---

indexer fix: multiple object mutations in one checkpoint

---

crates/sui-adapter-transactional-tests/tests/entry_points/large_enum.exp
crates/sui-adapter-transactional-tests/tests/entry_points/large_enum.move
external-crates/move/crates/move-compiler-transactional-tests/tests/functions/large_enum.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/functions/large_enum.move
external-crates/move/crates/move-compiler/src/shared/program_info.rs
external-crates/move/crates/move-compiler/src/sui_mode/typing.rs
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/typing/enum_in_struct_position.exp
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/typing/enum_in_struct_position.move

- Fix compiler's sui-mode entry rules for enums
- Add large enum tests for entry functions 
---

[move] Add large enum test

---

bridge/evm/script/deploy_bridge.s.sol
bridge/evm/test/mocks/MockTokens.sol
crates/sui-bridge/abi/erc20.json
crates/sui-bridge/src/abi.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/complex.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/node.rs
crates/sui-types/src/bridge.rs

In this PR we extend e2e test `test_add_new_coins_on_sui` to `test_add_new_coins_on_sui_and_eth`, also testing
1. add new coin on Eth
2. bridge node capture the new token event without restarting
Also fixed a bug where bridge node did not listen to move events from treasury.move and limiter.move (caught by the updated e2e tests, apparently)
e2e tests
---

[bridge] extend add coin e2e test to cover evm side, and a bug fix

---

crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/checkpoints/checkpoint_executor/metrics.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/checkpoint_output.rs
crates/sui-core/src/checkpoints/metrics.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/quorum_driver/metrics.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/safe_client.rs
crates/sui-core/src/transaction_orchestrator.rs
crates/sui-json-rpc-api/src/lib.rs
crates/sui-json-rpc/src/coin_api.rs
crates/sui-json-rpc/src/governance_api.rs
crates/sui-json-rpc/src/indexer_api.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-network/src/state_sync/metrics.rs
crates/sui-network/src/state_sync/mod.rs
crates/sui-oracle/src/lib.rs
crates/sui-oracle/src/metrics.rs
crates/sui-types/src/messages_checkpoint.rs
narwhal/primary/src/consensus/bullshark.rs
narwhal/primary/src/consensus/metrics.rs

This reverts commit ed69f7cce7ac200a849647c5d8efa7113969d44a.
Need to revert this as it breaks health checks for services behind LB

Revert "Migrate users of mysten_metrics Histogram to prometheus Histogram (#19043)"

---

crates/sui-indexer/migrations/mysql/2024-08-14-000000_full_objects_history/down.sql
crates/sui-indexer/migrations/mysql/2024-08-14-000000_full_objects_history/up.sql
crates/sui-indexer/migrations/pg/2024-08-14-000000_full_objects_history/down.sql
crates/sui-indexer/migrations/pg/2024-08-14-000000_full_objects_history/up.sql
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-indexer/src/schema/mod.rs
crates/sui-indexer/src/schema/mysql.rs
crates/sui-indexer/src/schema/pg.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

We add a separate table that stores full object history that we do not plan to prune.
---

[indexer] Add full_objects_history

---

.github/workflows/cargo-llvm-cov.yml

This allows rerunning the workflow with a past commit.
https://github.com/MystenLabs/sui/actions/runs/10530504701/job/29180577939#step:3:3
---

[CI] allow specifying branch / commit in coverage workflow

---

external-crates/move/crates/move-compiler/src/linters/constant_naming.rs
external-crates/move/crates/move-compiler/src/linters/meaningless_math_operation.rs
external-crates/move/crates/move-compiler/src/linters/mod.rs
external-crates/move/crates/move-compiler/src/linters/unnecessary_while_loop.rs
external-crates/move/crates/move-compiler/src/linters/unneeded_return.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-compiler/tests/linter/move_2024/allowed_unneeded_return.move
external-crates/move/crates/move-compiler/tests/linter/move_2024/unneeded_return.exp
external-crates/move/crates/move-compiler/tests/linter/move_2024/unneeded_return.move
external-crates/move/crates/move-compiler/tests/linter/move_2024/unneeded_return_branch.exp
external-crates/move/crates/move-compiler/tests/linter/move_2024/unneeded_return_branch.move
external-crates/move/crates/move-compiler/tests/linter/move_2024/unneeded_return_okay.exp
external-crates/move/crates/move-compiler/tests/linter/move_2024/unneeded_return_okay.move
external-crates/move/crates/move-compiler/tests/linter/true_positive_meaningless_math_operation.exp
external-crates/move/crates/move-compiler/tests/linter/true_positive_unnecessary_while_loop.exp

Check for and report unnecessary returns.
New test case added
---

[move][lints] warn on uneeded return

---

Cargo.lock
Cargo.toml
crates/sui-bridge-indexer/Cargo.toml
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-indexer/src/postgres_manager.rs
crates/sui-bridge-indexer/src/sui_bridge_indexer.rs
crates/sui-bridge-indexer/src/sui_transaction_handler.rs
crates/sui-graphql-rpc/Cargo.toml
crates/sui-indexer/Cargo.toml
crates/suins-indexer/Cargo.toml
crates/suins-indexer/src/lib.rs
crates/suins-indexer/src/main.rs

This PR begins the journey of migrating our DB connections from sync to async by using `diesel-async`. Some of the motivation for such a change: 
- pure rust impl (no C FFI dep that needs to be present at compile and runtime)
- using a proper async connection won't block the async runtime, which can lead to poor tail latencies (since the thread can't be reused while waiting on blocking io)
---

{suins, sui-bridge}-indexer: convert to using diesel-async

---

crates/sui-bridge/src/config.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/main.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/server/mod.rs
crates/sui-bridge/src/utils.rs

adds a ed25519 network key to the `BridgeNodePublicMetadata`.
I'm also adding a new api endpoint, `/metrics/network_key` which returns only the network key, this isn't necessary, as `/ping` already returns this info, I'm open to removing it.
tested locally: 
```
$ curl localhost:9191/ping      
{"version":"1.31.0-e244466d3d18","network_key_pair":"nxuXbFTndKX4sbtmbyTBtvb0vFRL+ImjDoZifaWok+8="}%                                               
$ curl localhost:9191/metrics/network_key              
"nxuXbFTndKX4sbtmbyTBtvb0vFRL+ImjDoZifaWok+8="%                                                 
```

[bridge] add network key + /metrics/network_key rest endpoint

---

crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/test_utils.rs
crates/sui-bridge/src/sui_transaction_builder.rs
crates/sui-bridge/src/types.rs
crates/test-cluster/src/lib.rs

This PR does a few things to make e2e tests run faster:
1. instead of having every node running the client, only having one of them do so.
2. allow custom number of bridge nodes, and reduce the amount of nodes for some tests
3. reduce the epoch length to 1 slot from 3 slots
These jointly reduce the duration of the basic e2e transfer test from 100+s to 70s.
existing tests
---

[bridge] e2e tests optimizations

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/watermark_task.rs
crates/sui-graphql-rpc/src/types/chain_identifier.rs
crates/sui-graphql-rpc/src/types/query.rs

We cache the chain identifier & use ticks instead of sleep() on the loop (to keep our queries consistently on `self.sleep` duration, instead of `self.sleep + query time`, as suggested by @amnn !
---

[GraphQL] Cache chain identifier & use ticks

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/unit_tests/authority_per_epoch_store_tests.rs
crates/sui-core/src/unit_tests/consensus_tests.rs
crates/sui-core/src/unit_tests/transaction_tests.rs

This PR introduces logic to consider a transaction as processed when one of the following conditions is met:
1. It has been sequenced through consensus.
2. It has been executed via a checkpoint (state sync).
Under typical circumstances, transactions are expected to be marked as processed primarily through the consensus path. However, the checkpoint execution path proves beneficial when a node faces difficulties syncing with the consensus DAG but can still follow the state sync. This approach prevents transactions from remaining as inflight and, more importantly, avoids redundant submission through the consensus path, as these transactions are likely to be obsolete.
CI/Private Testnet
---
Check each box that your changes affect. If none of the boxes relate to your changes, release notes …

[Consensus] consider tx processed either via consensus or checkpoint when submit

---

external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/tests/colon_colon_completion.exp

This PR fixes autocompletion for empty enum variants. Previously the autocompletion would result in:
```
SomeEnum::EmptyVariant{}
```
After the change, autocompletion will result in:
```
SomeEnum::EmptyVariant
```
All tests must pass (the change in the PR is reflected in modified expected test output)

[move-ide] A fix to empty variant autocompletion

---

crates/sui-graphql-rpc/tests/e2e_tests.rs

Waiting a bit longer (until we've indexed checkpoint 1), to give time to the watermark task to pick up the proper timestamp in tests, otherwise the timestamp has the value of 0 causing a 504. 
https://github.com/MystenLabs/sui/blob/f6dd9a8ef91612f541405d0e2f704b1895abbc37/crates/sui-graphql-rpc/src/server/builder.rs#L658 
(`checkpoint_timestamp` being 0 would always cause this to fail as `now` is a system utc timestamp).
---

[GraphQL] fix health check acting up on tests

---

docs/content/guides/developer/first-app/build-test.mdx

While going through the tutorial I noticed that the filename `my_module.move` is not in the sources referenced in the documentation. Probably meant `example.move`.
Not relevant, I guess.
---

my_module.move -> example.move

---

crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks/mod.rs

Also, increase the interval where the metric is sampled. In comments, it says reading some metrics may impact live serving traffic.
CI
---

[rocksdb] add metric for pending compaction bytes and memtable flushes

---

crates/sui-graphql-rpc/tests/e2e_tests.rs

Tweaked some more tests that would randomly fail because of trying to retrieve data too early.
---

[GraphQL] Fix more tests failing due to not waiting long enough

---

crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/functional_group.rs
crates/sui-graphql-rpc/src/types/dot_move/mod.rs
crates/sui-graphql-rpc/src/types/dot_move/named_type.rs
crates/sui-graphql-rpc/src/types/dot_move/on_chain.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/tests/dot_move_e2e.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Introduces `typeByName` that resolves a given type using the equivalent dot move name.
You can run `cargo test` for unit tests (parsing of types).
For e2e tests:
```
cargo nextest run --package sui-graphql-rpc --test dot_move_e2e --features pg_integration
```
- #18774 
- #18770 
---

[GraphQL][DotMove][2/n] Introduce `typeByName`

---

crates/sui-graphql-rpc-client/src/simple_client.rs
crates/sui-graphql-rpc/src/data.rs
crates/sui-graphql-rpc/src/data/move_registry_data_loader.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/types/dot_move/named_move_package.rs
crates/sui-graphql-rpc/src/types/dot_move/on_chain.rs
crates/sui-graphql-rpc/tests/dot_move/dot_move/sources/dotmove.move
crates/sui-graphql-rpc/tests/dot_move_e2e.rs
crates/sui-types/src/collection_types.rs

Introduces the external resolution, which requests "names" from a different graphql node. 
In reality, that'll be a mainnet RPC endpoint being used. 
e2e tests updated to start a secondary service that utilizes external resolution, and depend on that:
```
cargo nextest run --package sui-graphql-rpc --test dot_move_e2e --features pg_integration
```
- #18797 
- #18774 
- #18770 
---

[GraphQL][DotMove][3/n] Adds `External` resolver

---

external-crates/move/crates/move-analyzer/trace-adapter/.eslintrc.json
external-crates/move/crates/move-analyzer/trace-adapter/.vscodeignore
external-crates/move/crates/move-analyzer/trace-adapter/LICENSE
external-crates/move/crates/move-analyzer/trace-adapter/README.md
external-crates/move/crates/move-analyzer/trace-adapter/package-lock.json
external-crates/move/crates/move-analyzer/trace-adapter/package.json
external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/server.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/source_map_utils.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/trace_utils.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/utils.ts
external-crates/move/crates/move-analyzer/trace-adapter/tsconfig.json
external-crates/move/crates/move-analyzer/trace-debug/.eslintrc.json
external-crates/move/crates/move-analyzer/trace-debug/.vscode/launch.json
external-crates/move/crates/move-analyzer/trace-debug/.vscodeignore
external-crates/move/crates/move-analyzer/trace-debug/LICENSE
external-crates/move/crates/move-analyzer/trace-debug/README.md
external-crates/move/crates/move-analyzer/trace-debug/package-lock.json
external-crates/move/crates/move-analyzer/trace-debug/package.json
external-crates/move/crates/move-analyzer/trace-debug/src/extension.ts
external-crates/move/crates/move-analyzer/trace-debug/tsconfig.json

Move VM tracing is currently in development (https://github.com/MystenLabs/sui/pull/18730) and this PR contains the first version of both the Move VM trace viewing VSCode extension and the IDE-independent [Debug Adapter Protocol ](https://microsoft.github.io/debug-adapter-protocol/)(DAP) implementation that is is responsible for actual trace analysis and visualization.
Reviewing advice - I would suggest focusing on TypeScript files as the rest is largely configuration and boilerplate to get a TypeScript project (and, by extension, a VSCode project) going.
Tested manually by both packaging/installing extension and making sure that the extension itself can be debugged correctly.

[trace-view] Initial version of debug adapter and trace view extension

---

crates/mysten-metrics/src/thread_stall_monitor.rs

Use a watchdog thread for monitoring thread stalls.
This allows us to detect a thread stall while it is still occurring, rather than only after the fact.

Improvements to thread stall monitor

---

external-crates/move/crates/move-compiler-transactional-tests/tests/matching/lit_abort.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/matching/lit_abort.move
external-crates/move/crates/move-compiler-transactional-tests/tests/matching/struct_abort.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/matching/struct_abort.move
external-crates/move/crates/move-compiler-transactional-tests/tests/matching/true_false_abort.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/matching/true_false_abort.move
external-crates/move/crates/move-compiler-transactional-tests/tests/matching/true_false_nested_abort.exp
external-crates/move/crates/move-compiler-transactional-tests/tests/matching/true_false_nested_abort.move
external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs
external-crates/move/crates/move-compiler/tests/linter/move_2024/unneeded_return_branch.exp
external-crates/move/crates/move-compiler/tests/move_2024/hlir/abort_pair.exp
external-crates/move/crates/move-compiler/tests/move_2024/hlir/abort_pair.move
external-crates/move/crates/move-compiler/tests/move_2024/hlir/determine_error.move
external-crates/move/crates/move-compiler/tests/move_2024/hlir/nested_if_abort.move
external-crates/move/crates/move-compiler/tests/move_2024/hlir/nested_if_abort_statement.exp
external-crates/move/crates/move-compiler/tests/move_2024/hlir/nested_if_abort_statement.move
external-crates/move/crates/move-compiler/tests/move_2024/hlir/true_false_nested_abort.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/lit_abort.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/struct_abort.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/true_false_abort.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/true_false_nested_abort.move

This addresses a bug where `abort` was causing mistyped literal arm binders in match compilation. It also addresses some false-positive dead code complaints that I discovered while fixing the bug up.
Longer-term, it would be nice to eliminate temp binders of the form `#%1: _|_ = unreachable` from HLIR generation so that CFGIR can invariantly ensure none exist, catching these sorts of issues, but due to multiple-binding forms `(x, y, z) = (abort 0, abort 1, abort 2)` and the current structure of the pass, that is work left for another day.
Several more tests to cover these cases, though still never enough.
---
For each box you select, include information after the relevant …

[move][move-2024] Add match fix for typing around literal switches, plus tests

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/models/obj_indices.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

objects_history has been a bottleneck of indexer ingestion / backfill, splitting objects_version and let it run in parallel.
this might have been a factor of recent backfill perf regression.
---

indexer: split object version ingestion for perf

---

crates/sui-cluster-test/src/cluster.rs
crates/sui-graphql-e2e-tests/tests/prune.exp
crates/sui-graphql-e2e-tests/tests/prune.move
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/examples_validation_tests.rs
crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-indexer/tests/ingestion_tests.rs
crates/sui-transactional-test-runner/src/args.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
crates/sui/src/sui_commands.rs

Currently, the pruner assumes that all partitioned tables are partitioned on epoch, which is an issue since `objects_version` is not partitioned by epoch. Modify the pruner so that it will filter out non-epoch-partitioned tables, and otherwise do the same thing.
Change `EPOCHS_TO_KEEP` from an env variable to a config, so we can pass in test values through the transactional test runner, and a prune.move test to validate that we prune epoch data without any trouble.
prune.move
---

[indexer][graphql] Pruner prunes only epoch-partitioned tables

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority/authority_store_tables.rs
crates/sui-node/src/lib.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/typed-store-derive/src/lib.rs

For fullnodes that do not prune the `perpetual` DB, especially `transactions` and `effects` cfs, they can run into write stalls occasionally that makes the fullnode non operational. Since fullnodes have to accept all writes from checkpoints, throttling writes do not seem to make much sense.
Write stalling on validators is left enabled.
CI
Deploy to a few fullnodes.
---

[Store] disable write stall on fullnodes perpetual db

---

Cargo.lock
crates/sui-bridge-indexer/src/sui_bridge_indexer.rs
crates/sui-indexer-builder/Cargo.toml
crates/sui-indexer-builder/src/indexer_builder.rs
crates/sui-indexer-builder/tests/indexer_test_utils.rs
crates/sui-indexer-builder/tests/indexer_tests.rs

In function `tasks()` we return only incomplete tasks. As a result, when the latest backfill tasks are done and ignored, we mistakenly use an intermediate value as the `latest target checkpoint` and use it to fill gaps. This causes duplicated tasks. This PR fixes it:
1. rename `tasks` to `get_ongoing_tasks` for semantics
2. add `get_largest_backfill_task_target_checkpoint` and use that to determine whether there is a gap
3. simplify `update_tasks` for backfill task creation
4. add some utils functions for testing.
---
For each box you select, include information after the relevant heading that describes the impact of your changes …

[bridge-indexer] fix duplicated task creation

---

Cargo.lock
crates/sui-bridge-indexer/src/config.rs
crates/sui-bridge-indexer/src/eth_bridge_indexer.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-indexer-builder/Cargo.toml
crates/sui-indexer-builder/src/indexer_builder.rs
crates/sui-indexer-builder/src/sui_datasource.rs
crates/sui-indexer-builder/tests/indexer_test_utils.rs
crates/sui-indexer-builder/tests/indexer_tests.rs

1. now the live task's starting height is always `get_live_task_starting_checkpoint`. See the comment for more consideration. Previously we used a value in config to determine.
2. add `fn get_live_task_starting_checkpoint` and `fn get_genesis_height` to `DataSource` trait. Therefore each datasource implements their own method to pick these values to determine task ranges, as opposed to we do it on `main.rs` today.
3. clean up `fn build` for `IndexerBuilder` by moving existing parameters to elsewhere.
4. remove unused parameters in indexer config
tests and more tests
--- …

[bridge-indexer] change live task start point

---

crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
crates/sui-graphql-rpc/src/functional_group.rs
crates/sui-graphql-rpc/src/metrics.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

The mutation payload can be a lot higher than a query payload, due to the possibility of passing a large transaction data (e.g., publishing a package). This PR adds a different check for when a mutation is requested, and adds a `max_tx_payload_size` variable that holds the max bytes that can be sent through a GraphQL mutation request. 
The total sum of `txBytes + signatures` of all GraphQL mutation or `txBytes` in a `dryRunTransactionBlock` query have to be below the `max_tx_payload_size`.  
The `max_tx_payload_size` is computed based on the `protocol_version -> max_tx_bytes` and a Base64 overhead as follows:
`max_tx_bytes * 4 / 3`
Added several tests.
`cd crates/sui-graphql-rpc`
`cargo nextest run --features pg_integration -- test_query test_mutation test_dry_run_transaction …

[GraphQL] Add a mutation payload size

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/call/simple.exp
crates/sui-graphql-e2e-tests/tests/call/simple.move
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/error.rs
crates/sui-graphql-rpc/src/main.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/version.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Removes support for multiple versions from GraphQL, including:
- Version parsing
- Routing by version
- Associated tests
- `ServiceConfig.availableVersions` in schema
- `[versions].versions` in TOML ServiceConfig
This change also removes the only use of some error APIs which have also been cleaned up.
The Service now quotes the same version as `sui-node`, etc, so to prevent churn during tests, it has been mocked to a fixed value.
```
sui-graphql-e2e-tests$ cargo nextest run --features pg_integration
```
--- …

feat(graphql): Remove versioning support

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_validator.rs
crates/sui-core/src/mock_consensus.rs
crates/sui-core/src/post_consensus_tx_reorder.rs
crates/sui-types/src/messages_consensus.rs

A few small refactors:
- Remove the deprecated RandomnessStateUpdate variant
- Rename UserTransaction to CertifiedTransaction. UserTransaction will be used for the non-certified variant later.
- Tag variants so serialization is unaffected when variants are reordered. Using `repr(u8)` should be compatible with the varint serialization of default tag type.
CI. Upgrade tests in simulation and PT.
---

Refactor ConsensusTransactionKind

---

external-crates/move/crates/move-analyzer/src/analysis/parsing_analysis.rs
external-crates/move/crates/move-analyzer/src/completion.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/colon_colon_completion.exp
external-crates/move/crates/move-analyzer/tests/colon_colon_completion.ide
external-crates/move/crates/move-analyzer/tests/completion/sources/colon_colon.move
external-crates/move/crates/move-analyzer/tests/enums.exp

This PR fixes field auto-completion in two ways:
- adds support for struct fields (previously only variant fields were being auto-completed)
- named fields are now listed in their definition order (which should typically be what a developer wants)
- finesses auto-completion formatting (previously all fields where inserted on a single line, and now named fields are inserted on separate lines if there are more than two fields)
- adds a no-field auto-completion option (for when a struct or variant is used as a type and not in pack/unpack context)

[move-ide] Fixes auto-completion for fields

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_56.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_56.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_56.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

enable bridge creation on mainnet by setting `bridge` to true. Before this change, the value is already true for testnet and devnet, but not mainnet. So this only applies to mainnet.
it creates a new version 56 and enables bridge feature flag on mainnet. This change creates
* [sui_protocol_config__test__Mainnet_version_56.snap](https://github.com/MystenLabs/sui/blob/4b2e1ab739cee34e4075717b52766eb3a07946df/crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_56.snap) and
* [sui_protocol_config__test__Testnet_version_56.snap](https://github.com/MystenLabs/sui/blob/4b2e1ab739cee34e4075717b52766eb3a07946df/crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_56.snap)
and it does NOT change
* …

[bridge] [cheerypick to 1.32] enable bridge on mainnet

---

docs/content/concepts/cryptography/transaction-auth/signatures.mdx
docs/content/concepts/sui-architecture.mdx
docs/content/guides/developer/sui-101/access-time.mdx
docs/content/guides/operator/exchange-integration.mdx
docs/content/guides/operator/validator-committee.mdx
docs/content/guides/operator/validator-tasks.mdx
docs/content/references/contribute/sui-environment.mdx
docs/content/references/exchange-integration-guide.mdx
docs/content/references/sui-compared.mdx
docs/content/references/sui-glossary.mdx
docs/content/standards/deepbookv2/design.mdx
docs/content/standards/deepbookv2/pools.mdx

Checkpoint rate is now ~4/s post Mysticeti launch.
Narwhal and Bullshark are no longer running in Sui and references to them need to be migrated to Mysticeti.
CI
---

[Docs] update references and metrics post Mysticeti launch

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_56.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_58.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_56.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_58.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_56.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_58.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

enable bridge creation on mainnet by setting bridge is true. Before this change, the value true for testnet and devnet, but not mainnet. So this only applies to mainnet.
* expect 56, 57, 58 all have bridge = true
* [old 57](https://github.com/MystenLabs/sui/blob/main/crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_57.snap) v.s. [new 58](https://github.com/MystenLabs/sui/blob/bb25a072dac4848337c111d4fefeb0256fa36cd8/crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_58.snap): https://www.diffchecker.com/AbcQx7DQ/
* [old 56](https://github.com/MystenLabs/sui/blob/main/crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_56.snap) v.s. [new …

[bridge] enable bridge on mainnet

---

crates/sui-data-ingestion-core/src/reader.rs

prevents local tests from hanging

[data ingestion] disable inotify for macos

---

crates/typed-store/src/rocks/mod.rs
crates/typed-store/src/test_db.rs
crates/typed-store/src/traits.rs

This PR adds a rocksdb endpoint to delete .sst files in key range in rocksdb which is useful to prune data (in certain scenarios) without compaction.

Delete sst files in key range in rocksdb

---

crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks/mod.rs

We don't add more detailed level to control the cardinality of the metrics.
Manually tested in local cluster:
---

Add a metric to track the number of managed files per column family in RocksDb

---

crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-graphql-rpc/tests/dot_move_e2e.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs

These were originally added to try and deal with a deadlock issue, which was due to an issue with `inotify` on macOS, fixed by #19195.
These calls are safe to remove (also note that if the test failed, they would never be hit, because the assert would cause a panic before they ran).
Rebase on top of #19195, run the following on macOS:
```
sui$ cargo nextest run       \
-j 1 -p sui-graphql-rpc    \
--test e2e_tests           \
--features pg_integration
```
This used to intermittently hang, but now succeeds.
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must …

test(graphql): Remove explicit cleanup_resources

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_validator.rs
crates/sui-types/src/messages_consensus.rs

It turns out BCS serializes enum purely based on the variant order. The discriminant / tag does not matter. https://github.com/diem/bcs/blob/master/README.md#externally-tagged-enumerations
Also revert tagging of the enum since it is no longer useful.
SUI_PROTOCOL_CONFIG_CHAIN_OVERRIDE=testnet scripts/compatibility/split-cluster-check.sh origin/testnet a6336e6390b31379c7d41ef0d6fba4f966fad00c
---

Revert "Remove RandomnessStateUpdate" from ConsensusTransactionKind

---

crates/sui-core/src/authority.rs
crates/sui-core/src/verify_indexes.rs
crates/sui-storage/src/indexes.rs

temporary PR.
This PR introduces a background task to repair the `coin_index` and remove any dangling entries. The PR will be active for one release and will be reverted afterward.
The background task works by iterating over a snapshot of the `coin_index`, identifying coins that no longer belong to their respective owners, and populating a list of candidates for removal(some entries might be benign)
Once the candidate list is populated, the task makes a second pass over the candidates list. This time it locks the corresponding entries to prevent potential races with concurrent writes. The task then reverifies the eligibility criteria and removes the dangling entries

repair coin index

---

crates/sui-graphql-e2e-tests/tests/available_range/available_range.exp
crates/sui-graphql-e2e-tests/tests/available_range/available_range.move
crates/sui-graphql-e2e-tests/tests/consistency/balances.exp
crates/sui-graphql-e2e-tests/tests/consistency/balances.move
crates/sui-graphql-e2e-tests/tests/consistency/coins.exp
crates/sui-graphql-e2e-tests/tests/consistency/coins.move
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/consistency/dynamic_fields/dynamic_fields.move
crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.exp
crates/sui-graphql-e2e-tests/tests/consistency/object_at_version.move
crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination.exp
crates/sui-graphql-e2e-tests/tests/consistency/objects_pagination.move
crates/sui-graphql-e2e-tests/tests/consistency/tx_address_objects.exp
crates/sui-graphql-e2e-tests/tests/consistency/tx_address_objects.move
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-graphql-rpc/src/types/available_range.rs
crates/sui-indexer/src/config.rs
crates/sui-indexer/src/handlers/objects_snapshot_processor.rs
crates/sui-transactional-test-runner/src/args.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

A separate task is solely responsible for updating `objects_snapshot`, which means the graphql e2e tests, which depend on forcing `objects_snapshot` changes through an update query, also need to obey this. In lieu of the current behavior, we instead configure the snapshot lag per test scenario, and 
```
//# advance-clock --duration-ns 1
//# create-checkpoint
```
to get the desired `objects_snapshot` state
---

[graphql] Remove usage of legacy objects snapshot processing

---

.github/workflows/release.yml

Do not build sui in debug mode for `macos-arm64` and delete unused software.
```
Filesystem        Size    Used   Avail Capacity  Mounted on
/dev/disk3s1s1   295Gi   9.6Gi    17Gi    37%    /
Filesystem        Size    Used   Avail Capacity  Mounted on
/dev/disk3s1s1   295Gi   9.6Gi    89Gi    10%    /
```
https://github.com/MystenLabs/sui/actions/runs/10725603432/job/29743813335

Do not build sui in debug mode for macos-arm64 and delete unused software.

---

crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks/mod.rs
deny.toml

Too many level 0 files can be a trigger to write stall & stop as well
CI
---

[rocksdb] add metric for num level 0 files

---

crates/sui-indexer/src/handlers/objects_snapshot_processor.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

the legacy method of updating `objects_snapshot` is no longer needed, thus this pr cleans it up
ci
---

indexer: clean up legacy snapshot codes

---

crates/sui-indexer/src/handlers/objects_snapshot_processor.rs

In ci, we saw that the `objects_snapshot_processor` stalls if there are unprocessed checkpoint data that we cannot commit unless we have a continuous stream of checkpoints from `[start_cp, max_allowed_cp]`. To address this, the processor should continue to read from stream whether `unprocessed` is empty or not. 
Ran indexer manually to observe that `objects_snapshot_processor` doesn't stall
---

[indexer] Objects Snapshot Processor continuously reads from stream

---

external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts

This PR adds the ability to step back through the trace. The main limitation is that stepping back into or over (previously executed) function calls is not supported. We will add this support after support for viewing variables is added as it will requires snapshotting variable state (which we do not have at the moment).
Tested manually that:
- viewer correctly steps back within the function and from inside the callee to the caller
- viewer correctly stops stepping back at the beginning of the trace
- viewer correctly stops stepping back upon encountering previously executed function call

[trace-view] Added support for stepping back through the trace

---

Cargo.lock
crates/sui-bridge-indexer/src/eth_bridge_indexer.rs
crates/sui-bridge-indexer/src/lib.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-indexer/src/metrics.rs
crates/sui-bridge-indexer/src/sui_bridge_indexer.rs
crates/sui-bridge-indexer/src/sui_datasource.rs
crates/sui-indexer-builder/Cargo.toml
crates/sui-indexer-builder/src/indexer_builder.rs
crates/sui-indexer-builder/src/lib.rs
crates/sui-indexer-builder/tests/indexer_test_utils.rs
crates/sui-indexer-builder/tests/indexer_tests.rs

This PR does two things:
1. pull checkpoint batches to processed when there are multiple, rather than one-by-one. This improves the efficiency especially for write_process
2. add metrics to check indexing progress.
Deployed in production.
---

[bridge-indexer] batch processing checkpoints and indexing progress metrics

---

bridge/evm/contracts/utils/CommitteeUpgradeable.sol

In the case the `CommitteeUpgradeable` contract needs to include more storage variables, a storage gap variable is needed to reserve storage slots  so the child contract state is not overwritten. 
Contract upgrade unit tests

Add storage gap variable to the CommitteeUpgradeable contract

---

.github/workflows/split-cluster-bisect.yml
.github/workflows/split-cluster-pr.yml

Currently when the check runs in PR CI, the failure is ignored and bisect does not run. So the workflow succeeds when it shouldn't.
For example, https://github.com/MystenLabs/sui/actions/runs/10641580676/job/29502904956#step:3:2268
CI
---

[CI] do not ignore failures from Split Cluster Check in PRs

---

crates/sui-benchmark/src/drivers/bench_driver.rs

This is more of an issue now that we have congestion control mechanisms in place where transactions can get cancelled after consensus. We also have not run our benchmark suite routinely to push these more congested scenarios so we have not run into this issue before,

[benchmark] Count tx as success only if effects are ok

---

crates/sui-core/src/authority/epoch_start_configuration.rs

We have removed the ability to disable state accumulator v2 previously by ignoring the config parameter (https://github.com/MystenLabs/sui/pull/18786), however if a node that had v2 disabled has been running since before this change without shutting down, the old config would still be stored in memory. This PR forces enabling of v2. Once we have reached the epoch change after all nodes are running this code, we can safely merge https://github.com/MystenLabs/sui/pull/18764.
Existing tests
--- …

[core] Force enable state accumulator v2

---

crates/sui-data-ingestion-core/src/executor.rs
crates/sui-data-ingestion-core/src/reader.rs

Introduces a new parameter: an upper limit for data ingestion. Once the framework reaches this checkpoint, it will gracefully shut down
---

[data ingestion] introduce upper limit for ingestion job

---

crates/sui-indexer/src/config.rs
crates/sui-indexer/src/lib.rs
crates/sui-indexer/src/test_utils.rs

`Url` elides ports if they are the default port for the URL scheme, and `jsonrpsee` needs the port to be provided explicitly, and never the twain shall meet.
Run a local indexer talking to a mainnet DB and a public good mainnet fullnode.
---

fix(indexer): Store JSON-RPC URL in String

---

crates/sui-core/src/authority_aggregator.rs

Change AuthorityAggregator to always pass through request_events flag, even to the validators we aren't sampling for objects.
In addition, up the sample size of validators to 10 and log when we get unlucky and reach quorum without having recieved input or output objects.
---

authority_aggregator: always request for events when asked

---

crates/suiop-cli/src/cli/incidents/pd.rs
crates/suiop-cli/src/cli/incidents/slack.rs

Add date output to make it clear when an incident was closed.
Add the slack channel url to short output.
```
DEBUG=true cargo run -- i r -i --limit 1
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.54s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop i r -i --limit 1`
2024-09-05T20:52:01.898863Z  INFO suiop: Debug mode enabled
3511:0d   [FIRING:1] disk used % Infrastructure (/dev/md1 mainnet ext4 ord-mnt-rpcbig-03 localhost:9091 node-exporter /opt/sui mainnet pagerduty/nre rpc active) (https://mystenlabs.pagerduty.com/incidents/Q1OS8GCY2HHNEB)
> Keep this incident for review? Yes
Incidents marked for review: 3511
Here is the message to send in the channel: 
Hello everyone and happy Thursday!
We have selected the following incidents for review:
• 3511 09/05/24 …
```

[suiop] add date to message output

---

crates/sui-bridge-indexer/src/storage.rs

This PR introduces `ProgressSavingPolicy` to deal with two problems:
1. The current implementation has a bug on Sui side - checkpoints data arrive out-of-order (e.g. checkpoint 10 may be processed earlier than checkpoint 9), so existing `save_process` may cause us to miss blocks.
2. In current implementation we need to write progress to DB for every call to `save_process`. This can be optimized to cache progresses in memory and flush them periodically or conditionally. 
We add two types of `ProgressSavingPolicy`, `SaveAfterDuration` and `OutOfOrderSaveAfterDuration`:
* `SaveAfterDuration` only flushes the progress to DB after a period of time
* `OutOfOrderSaveAfterDuration` assumes the data is out of order, and will only write height N when it makes sure everything before N has been …

[bridge-indexer] Progress saving policy

---

crates/sui-bridge-indexer/src/eth_bridge_indexer.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-indexer/src/metrics.rs
crates/sui-bridge-indexer/src/storage.rs
crates/sui-bridge-indexer/src/sui_datasource.rs
crates/sui-indexer-builder/src/indexer_builder.rs
crates/sui-indexer-builder/tests/indexer_test_utils.rs

This PR integrates `ProgressSavingPolicy`. Basically, sui data sources use `OutOfOrderSaveAfterDuration` and eth data sources use `SaveAfterDuration`.
Also changed metric `live_task_current_checkpoint` to `tasks_current_checkpoints` to track all tasks in `save_progress`
production deployment
---

[bridge-indexer] Integrate progress saving policy

---

crates/sui-bridge-indexer/src/eth_bridge_indexer.rs
crates/sui-bridge-indexer/src/models.rs
crates/sui-bridge-indexer/src/storage.rs
crates/sui-bridge-indexer/src/sui_datasource.rs
crates/sui-indexer-builder/src/indexer_builder.rs
crates/sui-indexer-builder/src/lib.rs
crates/sui-indexer-builder/tests/indexer_test_utils.rs
crates/sui-indexer-builder/tests/indexer_tests.rs

This PR reworks `Tasks`:
1. get rid of trait `Tasks` and create struct `Tasks` instead.
2. add `is_live_task` field to `Task`
3. pass `Task` to several functions instead of its parameters.
4. for ingestion framework, use a custom batch read size for backfill tasks (this significantly improves the data download speed)
---

[bridge-indexer] revamp task

---

scripts/simtest/codecov.sh
scripts/simtest/config-patch

Fix Code Coverage script due to https://github.com/MystenLabs/sui/commit/89ef73d1409e1bfdba868026890f87f9cfa8f67c#diff-9a4f3e4537ebb7474452d131b0d969d89a51286f4269aac5ef268e712be17268
👀

Fix Code Coverage script

---

Cargo.lock
Cargo.toml
crates/sui-protocol-config-macros/src/lib.rs
crates/sui-protocol-config/Cargo.toml
crates/sui-protocol-config/src/lib.rs

For use in local networks, or possibly for emergency response.
Tested with:
`SUI_PROTOCOL_CONFIG_OVERRIDE_ENABLE=1 SUI_PROTOCOL_CONFIG_OVERRIDE_min_checkpoint_interval_ms=1000 RUST_LOG=warn cargo run --bin sui start --no-full-node --force-regenesis`

Add support for overriding ProtocolConfig fields by env variable

---

crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-types/src/dynamic_field.rs

Remove references to the `df_object_id` column from GraphQL codebase, so that we can eventually remove it altogether.
```
```
---

refactor(graphql): Remove references to df_object_id

---

docs/content/guides/developer/first-app/write-package.mdx

Add a link to the Sui Move book. A link also exists in the move references page, however it is beneficial to have the link in the write a move package page as well. This will help users find the right book for writing move packages for sui and can be a good follow up step to writing a basic move package.
Built the docs, checked the link.
---

 [docs] Include a reference to "The Move Book" in the Write a Move Package page

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/objects.rs

title, with this pr and the corresponding pr in GQL, we can remove df_* from objects table except df_kind.
---

indexer reader: derive dynamic field info

---

consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

This metric might provide us with a better idea on blocks from which authorities are having propagation problems. 
Also, decrement the synchronizer inflight metric properly.
CI
PT
---

[Consensus] add missing blocks per authority metric

---

consensus/core/src/block_manager.rs
consensus/core/src/metrics.rs

Count missing ancestors and new missing blocks per authority.
This may help identify bad performing validators faster.
CI
PT
---

[Consensus] count missing ancestors and blocks per authority

---

Cargo.lock
crates/mysten-common/Cargo.toml
crates/mysten-common/src/lib.rs
crates/mysten-common/src/metrics.rs
crates/sui-bridge/Cargo.toml
crates/sui-bridge/src/metrics.rs
crates/sui-node/Cargo.toml
crates/sui-node/src/metrics.rs

Follow up to #19077, this shares the `push_metrics` fn between `sui-bridge` & `sui-node`.
Tested on a testnet fullnode & bridge validator node
---

split out push_metrics into mysten-common

---

docs/site/docusaurus.config.js
docs/site/src/plugins/askcookbook/index.js
docs/site/src/theme/SearchBar/index.js

Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Sui resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building on Sui, acting as an enhanced and streamlined technical documentation search tool as well as Solidity and Move coding co-pilot.
Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Sui-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.
- Added the Ask Cookbook plugin to embed the Cookbook …

feat: Cookbook Onboard (AI Assistant) integration

---

external-crates/move/crates/move-analyzer/editors/code/package.json

Bump version to the next one in VScode Marketplace (currently 1.0.11) as plugin can be republished only at a higher version

[move-ide] Version bump

---

crates/sui/src/sui_commands.rs

Fix a bug where a relative keystore path was written out to the config upon creation when the config itself was specified at a relative path.
The fix is to canonicalize the keystore path before using it, but we need to handle multiple edge cases:
- A wallet config created in the current working directory as a relative path (and relative paths in general).
- A wallet config created at the very root of the filesystem (although this should never happen, the correct behaviour is not to default to the default config directory here).
```
sui$ cargo build --bin sui
sui$ export SUI=~/sui/target/debug/sui
sui$ mv ~/.sui/sui_config/client.yaml{,~}
sui$ cd ~
sui$ $SUI client --client.config .sui/sui_config/client.yaml gas
sui$ cd -
sui$ $SUI client gas
sui$ mkdir -p /tmp/a
sui$ cd /tmp/a
a$ $SUI …
```

fix(cli): canonicalize keystore path

---

Cargo.lock
crates/sui-json/src/lib.rs
crates/sui-light-client/.gitignore
crates/sui-light-client/Cargo.toml
crates/sui-light-client/example_config/light_client.yaml
crates/sui-light-client/src/main.rs
crates/sui-light-client/src/proof.rs

Modernise the RPC used in the light client:
- Use GraphQL to get the end-of-epoch checkpoint.
- Use the supported Rust SDK to get objects and other info.
- Use a generic object store, by default provided by Mysten, for the full checkpoint data.
- Add a cache to package loader since we observed the same package downloaded multiple times.
Existing unit tests, and manual CLI invocations.

[light-client] Fix light client rpc

---

Cargo.lock
Cargo.toml
sui-execution/latest/sui-move-natives/src/crypto/groth16.rs
sui-execution/v0/sui-move-natives/src/crypto/groth16.rs
sui-execution/v1/sui-move-natives/src/crypto/groth16.rs
sui-execution/v2/sui-move-natives/src/crypto/groth16.rs

Update the fastcrypto version. This includes adding Playtron and Threedos as OIDC providers.
The path to the BLS12381 scalar size has been updated in fastcrypto and will be updated in here also. The value [is](https://github.com/MystenLabs/fastcrypto/blob/5f2c63266a065996d53f98156f0412782b468597/fastcrypto-zkp/src/bls12381/conversions.rs#L21) [unchanged](https://github.com/MystenLabs/fastcrypto/blob/501225efbb9d069062c0ab47e7ce25a7cd5128c0/fastcrypto/src/groups/bls12381.rs#L57).
Unit tests.
--- …

Update fastcrypto pointer and bls12381 scalar length path

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

Adds playtron provides to Devnet. 
Afaik, since Playtron serves only the `authorization_code` flow it cannot work with the current version of the keytool, so no need to bump fastcrypto version here, unless I am missing anything.
(Related: https://github.com/MystenLabs/fastcrypto/blob/781398d38fbf342a50e66dc0ad11d6227839bd68/fastcrypto-zkp/src/bn254/utils.rs#L88)
If I do miss something though, it looks that bumping to a later fastcrypto revision it causes dependency related error during the test execution (`cargo test -p sui-swarm-config`). Like the following:
```
error[E0433]: failed to resolve: could not find `conversions` in `bls12381`
--> sui-execution/v1/sui-move-natives/src/crypto/groth16.rs:205:41
|
205 |             > fastcrypto_zkp::bls12381::conversions::SCALAR_SIZE * …
```

Adds configuration for playtron provider in Devnet

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/validator_tx_finalizer.rs

This PR adds an extra checks before a validator would attempt to finalize a transaction: if the transaction is already submitted to consensus (i.e. in pending consensus transactions).
CI
---

Optimising validator tx fianlizer

---

.github/workflows/rust.yml
crates/sui-cluster-test/Cargo.toml
crates/sui-cluster-test/tests/local_cluster_test.rs
crates/sui-graphql-e2e-tests/Cargo.toml
crates/sui-graphql-e2e-tests/README.md
crates/sui-graphql-e2e-tests/tests/tests.rs
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/data/pg.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-graphql-rpc/tests/dot_move_e2e.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-graphql-rpc/tests/examples_validation_tests.rs
crates/sui-indexer/Cargo.toml
crates/sui-indexer/src/db.rs
crates/sui-indexer/tests/ingestion_tests.rs
scripts/update_graphql_e2e_test_protocol_version.py

indexer, graphql: remove pg_integration feature flag usage

---

crates/sui-graphql-rpc/src/types/object.rs
crates/sui-indexer/src/models/objects.rs

The WrappedOrDeleted variant only needs the version, as all other information is already in the Object struct.
CI
---

[Indexer] Minor cleanup on ObjectStatus::WrappedOrDeleted

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/models/obj_indices.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

objects_history has been a bottleneck of indexer ingestion / backfill, splitting objects_version and let it run in parallel. this might have been a factor of recent backfill perf regression.
---
---
For each box you select, include information after the relevant heading …

cherrypick indexer: split object version ingestion for perf (#19104)

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/incidents/mod.rs
crates/suiop-cli/src/cli/incidents/pd.rs

Refactor the filtering code into the review selection module. 
Use strsim to detect title similarity (only using the first 20 chars of the title for now to keep it simple)
Group similar titles and allow treating them as one atomic operation
tested locally, grouped successfully. tests pass
---

[suiop] add title similarity detection to incident review selection

---

external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/source_map_utils.ts
external-crates/move/crates/move-analyzer/trace-debug/src/extension.ts

In Move, there isn't necessarily 1:1 correspondence between source code and bytecode due to compiler optimizations. In the following code example (admittedly somewhat artificial for presentation purposes), there will be no entry for `constant` variable in the bytecode as it will be optimized away via constant propagation:
```
fun hello(param: u64): vector<u64> {
let mut res = param;
let constant = 42; // optimized away
if (constant >= 42) { // optimized away and turned into straight line code
res = 42;
};
vector::singleton(res)
}
```
This PR implements a heuristic that will mark source code lines optimized away by the compiler as having grey background. We do this by analyzing source maps for a given file and marking lines that are present in the source map but not in the source file …

[trace-view] Added support for marking optimized away code lines

---

crates/sui-types/src/object.rs

Put tests in sui-types/object.rs in their own module
The tests are just floating around in the main module, which presumably means they are also compiled into our production builds? They should go into their own module, guarded by a #[cfg(test] annotation.
---

Add tests module sui-types/object.rs

---

crates/sui-move/src/disassemble.rs
external-crates/move/crates/move-cli/src/base/test.rs

Add documentation for the `trace-execution` flag for `sui move test`, and also made the `-Xdebug` flag for the disassembler hidden. 
recompiled and manually checked. 
---

[move][tracing] Document flag for generating traces from `sui move test`

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/incidents/mod.rs
crates/suiop-cli/src/cli/incidents/pd.rs
crates/suiop-cli/src/cli/incidents/slack.rs
crates/suiop-cli/src/cli/incidents/slack_api.rs

- Refactor api logic into new module
- get all users so we can select them to be points of contact
- add multiselect to allow selection of an arbitrary set of users
- generalize serde logic for caching api responses (once per day)
- improve tagging of channels to link to the actual channel
- tag associated poc users for an incident
e2e functional (see [example message](https://mysten-labs.slack.com/archives/C03QJ1B6BC0/p1726147679829409))
---

[suiop] add point of contact selection for incident review

---

external-crates/move/crates/move-compiler/tests/linter/true_positive_unnecessary_while_loop.exp

- Fix lint tests
- Updated tests
---

[more] Fix move tests

---

crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/quorum_driver/tests.rs
crates/sui-json-rpc/src/error.rs
crates/sui-rest-api/src/error.rs
crates/sui-types/src/error.rs
crates/sui-types/src/quorum_driver_types.rs

The CLI and SDK rely on the QuorumDriverError type to handle errors from the Quorum driver. This PR improves the clarity of errors for the QuorumDriverError type and its usage in RPCs.
- a published transaction which has a conflict now provides the conflicting transaction
- invalid user signature simplified 
- better formatting for object double used
- rely on display when possible
Augment the current RPC error tests surrounding `From<QuorumDriverError>` trait implementations to ensure that the error messages are clear and informative.

Improve clarity of errors for QuorumDriverError type and it's usage in RPCs

---

consensus/core/src/authority_service.rs

Looking on the connectivity metrics for the subscribed peers  I believe it's possible to have some race conditions when nodes quickly connect/disconnect. As the metric is a gauge the last who sets the value "wins", so it's possible that we might have nodes connecting again while the earlier connection has not been dropped yet - which consequently once dropped it will make the peer appear in metrics as disconnected. The PR is refactoring a bit that part and only sets the peer as disconnected  when there is no other pending connection.
CI
--- …

[Consensus] subscriber counter to atomically set node status

---

crates/sui-indexer/migrations/pg/2024-09-12-150939_tx_affected/down.sql
crates/sui-indexer/migrations/pg/2024-09-12-150939_tx_affected/up.sql
crates/sui-indexer/src/models/tx_indices.rs
crates/sui-indexer/src/schema.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

Introduce `tx_affected_addresses` table -- a combination of `tx_recipients` and `tx_senders`, to power the sender-or-recipient query in GraphQL.
```
cargo build -p sui-indexer
```
Tests based on reading this field will be included with the PR introducing changes to GraphQL.
---

indexer: index tx_affected_addresses

---

crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/event/filter.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/transaction_block/filter.rs
crates/sui-graphql-rpc/src/types/transaction_block/tx_lookups.rs
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema_sdl_export.snap

Introducing documentation in a couple of places:
- Fields in `TransactionBlockFilter` so that they are documented in the schema
- Explaining the pattern we use for transaction lookup tables.
- #19355
---

docs(graphql): Documenting transaction filters and underlying schema

---

Cargo.lock
Cargo.toml
crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
crates/sui/src/keytool.rs
crates/sui/src/zklogin_commands_util.rs
sui-execution/latest/sui-move-natives/src/crypto/vdf.rs

pulling jwk ok on localnet
```
cargo build --bin sui 
RUST_LOG=info target/debug/sui start --force-regenesis --with-faucet
```
logs: 
```
2024-09-13T19:13:15.967816Z  INFO node{name=k#99f25ef6..}: sui_core::authority::authority_per_epoch_store: received jwk vote from k#8dcff6d1.. for jwk (JwkId { iss: "https://accounts.fantv.world", kid: "O5ryxF-zMCLmS6hQhcTC3pAAhQ4YYPEHoiQt1qx_86o" }, JWK { kty: "RSA", e: "AQAB", n: "mBi1td_GT0MubU5Lfeg4P4XsMUzpzcxuI9Yb1xDOpWFekEZF0TwTLJ6v4a28hiAU_ateCxlFQSkHrhbpdFkEWuDQnPUAnlAr5I7-W8ccKkWuuPwZz0wHcgFSxH5fstFaGuOACewBSmP3BlScQqRYhrj1QB_7j1_G7g17Q-QIBGrvp8gtb2K-saumUlF67ySZrSM_FV1_XalI0Z31oXKMECUfnbje-fLiIvSuXKK-sfO-MSrEEkB8dbzP6ez-xYGYIFisyiqeGlCeO4-ZDkvDrBnDGLxpgLcsWbgcUUvnmyrSQjTxqub17GkuPPwXpof0b8O …
```

Add FanTV as Zklogin OIDC provider onboarding

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/build.rs
consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/broadcaster.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/lib.rs
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/network/test_network.rs
consensus/core/src/network/tonic_network.rs
consensus/core/src/round_prober.rs
consensus/core/src/subscriber.rs
consensus/core/src/synchronizer.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_59.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_59.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_59.snap

Introduce `RoundProber` to gather information from each authority, on their received rounds from others. The gathered data on block propagation delays across the network are exported to metrics. The propagation delay for own blocks is used to control whether proposing blocks can happen.
CI
PT
---

[Consensus] stop proposing when propagation delay is high

---

crates/sui-bridge-indexer/src/eth_bridge_indexer.rs
crates/sui-bridge-indexer/src/lib.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-indexer/src/metrics.rs
crates/sui-bridge-indexer/src/migrations/2024-09-11-010632_add_finalized_to_token_transfer/down.sql
crates/sui-bridge-indexer/src/migrations/2024-09-11-010632_add_finalized_to_token_transfer/up.sql
crates/sui-bridge-indexer/src/models.rs
crates/sui-bridge-indexer/src/postgres_manager.rs
crates/sui-bridge-indexer/src/schema.rs
crates/sui-bridge-indexer/src/storage.rs
crates/sui-bridge-indexer/src/sui_bridge_indexer.rs
crates/sui-bridge-indexer/src/sui_transaction_handler.rs
crates/sui-bridge/src/eth_client.rs

Description
Account for Eth block re-orgs in eth indexer #19158
Test plan
Spot check on my local machine. Indexer validity checker tool coming soon...

Account for Eth block re-orgs in eth indexer

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/build.rs
consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/block_manager.rs
consensus/core/src/broadcaster.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/lib.rs
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/network/test_network.rs
consensus/core/src/network/tonic_network.rs
consensus/core/src/round_prober.rs
consensus/core/src/subscriber.rs
consensus/core/src/synchronizer.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_59.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_59.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_59.snap

Pick improvements to detect and mitigate large block propagation delay.
CI
---

Pick a few improvements to 1.33

---

bridge/runbook/validator_runbook.md

WAF details in validator_runbook.md

---

consensus/core/src/authority_node.rs
consensus/core/src/commit_consumer.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs

This is necessary for proper crash recovery with data quarantining, as we will need to wait until all previously-built checkpoints have been rebuilt before starting CheckpointExecutor

At startup, wait until all previously-observed commits have been sent to the consensus handler.

---

bridge/runbook/validator_runbook.md
crates/sui-bridge/src/utils.rs

[doc] add configs and client description to bridge node runbook

---

external-crates/move/crates/move-package/src/resolution/dependency_cache.rs

Check if git is installed.
Ouput the git clone or git fetch message
1. git is not installed
```
sui move build
Git is not installed or not in the PATH.
Failed to build Move modules: Failed to resolve dependencies for package 'gitt'
Caused by:
0: Fetching 'Sui'
1: Git is not installed or not in the PATH..
```
2.network error
```
sui move build
FETCHING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
Cloning into '/home/sun/.move/https___github_com_MystenLabs_sui_git_framework__testnet'...
fatal: unable to access 'https://github.com/MystenLabs/sui.git/': Could not resolve host: github.com
Failed to build Move modules: Failed to resolve dependencies for package 'up'
Caused by:
0: Parsing manifest for 'Sui'
1: No such file or directory (os error 2).
```
3.Show the progress of git
```
sui …
```

[cli] improve git output

---

external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/source_map_utils.ts

This PR adds support for "continue" debugger action. It also makes implementation of "next" ("step over") and "step out" actions faithful to their intended semantics (i.e., executing all instruction in a function stepped over or stepped out of). These changes do not actually change the current behavior of the viewer - they are done in preparation for implementing variable value tracking and displaying.
This PR also includes a refinement of the "step out" action implementation. As also explained in the code comment, previously in the following line of code, after entering `foo` and stepping out of it, we would immediately step into `bar`, which could be quite confusing for the user:
```
assert(foo() == bar());
```
Finally, this PR also includes some formatting changes for lines that were a …

[trace-view] Added support for continue

---

crates/sui-core/src/rest_index.rs

Allow dynamic field indexing to fail when building up fullnode REST indices to bring it in line with behaviour in `sui-indexer`, `sui-analytics-indexer`, and the existing fullnode indices.
CI
---

rest: discard failed dynamic field indices

---

crates/sui-core/src/rest_index.rs

Allow dynamic field indexing to fail when building up fullnode REST indices to bring it in line with behaviour in `sui-indexer`, `sui-analytics-indexer`, and the existing fullnode indices.
CI
---

pick(rest): discard failed dynamic field indices

---

external-crates/move/crates/move-compiler/src/parser/lexer.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/src/parser/token_set.rs
external-crates/move/crates/move-compiler/tests/move_2024/matching/invalid_match_lhs.exp
external-crates/move/crates/move-compiler/tests/move_2024/matching/invalid_match_lhs.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/matching_everywhere.move
external-crates/move/crates/move-compiler/tests/move_2024/migration/match_okay.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/mut_field_pun_invalid_assign.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/mut_field_pun_invalid_pack.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/pattern_ellipsis_invalid.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/positional_struct_fields_keyword_field.exp
external-crates/move/crates/move-compiler/tests/move_2024/typing/invalid_deprecation_attributes.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/pack_no_fields_block_expr.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/pack_no_fields_single_block_expr.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/pack_no_fields_single_block_other_expr.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/unpack_assign_block_expr.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/unpack_assign_block_single_expr.exp
external-crates/move/crates/move-compiler/tests/move_check/expansion/unpack_assign_other_expr.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/function_type_extra_comma.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/invalid_unpack_assign_rhs_not_fields.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/positional_struct_fields_keyword_field.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/struct_type_extra_comma.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/use_module_member_invalid_comma.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/vector_literal_unclosed_args.exp

Match did not end up in the expression start set due to these features growing separately. Now match parses in more places.
This PR also slightly changes parsing error reporting to report what symbol was there in comma list parse failures, allowing for slightly better error reporting(?)
New tests added.
---

[move][move-2024] Fix match parsing by adding Match to expression start set

---

crates/sui-indexer/src/config.rs
crates/sui-indexer/src/lib.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/sql_backfill.rs

This PR adds a command to sui-indexer that allows us to backfill using SQL queries, split by checkpoint ranges.
---

[Indexer] SQL Backfill command

---

crates/mysten-common/src/metrics.rs
crates/sui-bridge/src/metrics.rs
crates/sui-node/src/metrics.rs

We have observed `mainnet` validators cannot push metrics until restart. And metrics data points are dropped from some validators occasionally. Adding request timeouts and retries hopefully should mitigate some of these issues.
Interval ticks are skipped if missed, so it is ok to retry until success there. 
CI
---

[Metrics] add timeout and retries to metrics push task

---

consensus/core/src/authority_service.rs
consensus/core/src/metrics.rs
consensus/core/src/round_prober.rs
consensus/core/src/subscriber.rs

- Add metric to measure the gap between local last proposed round and low quorum round of each peer.
- Rename subscriber connection count metrics to be more intuitive.
CI
---

[Consensus] small metrics improvements

---

docs/content/concepts/graphql-rpc.mdx
docs/content/guides/developer/advanced/graphql-migration.mdx
docs/content/references/sui-graphql.mdx
docs/content/sidebars/concepts.js
docs/content/sidebars/guides.js
docs/content/sidebars/references.js
docs/site/docusaurus.config.js
docs/site/pnpm-lock.yaml
docs/site/src/components/BetaTag/index.tsx
docs/site/src/plugins/betatag/index.js
docs/site/src/theme/MDXContent/index.js

Adds a beta tag to the frontmatter. Applied the tag to the graphql topics. If networks provided as value, theyre added to the admonition box. Format is
```
---
beta: <list of networks available in or `true`>
---
```
---

[docs] Beta tag for graphql

---

crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-json-rpc-tests/tests/transaction_tests.rs
crates/sui-rosetta/tests/end_to_end_tests.rs

This PR fixes a few flaky tests:
1. The multisig tests. If epoch duration is too small, some times it triggered epoch changes in the middle of test and the max epoch becomes insufficient.
2. The transaction e2e tesets. The query includes system transactions too, which there can be a lot more than 2 pages if enough checkpoints have passed by.
3. In rosetta with_draw_stake test, similar issue to (1), we need to manually control epoch change otherwise accidental epoch change could lead to wrong stake results.
--- …

Fix a few flaky tests

---

crates/sui-sdk/src/apis.rs

In the code below these lines we emulate local execution by polling the transaction.
This means that we no longer need to pass through the request type to the RPC server, otherwise if user specified WaitForLocalExecution it would still be passed through.
---

Do not request local execution from Rust SDK

---

crates/sui-graphql-rpc/src/server/builder.rs

Removes the version related routes.
Existing tests
---

[GraphQL] Remove version related routes

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_59.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_59.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_59.snap

Now protocol version 59 will be dominant on `testnet`, update protocol config on `main`.
```
eugene@eugene-dev ~/code/sui/scripts/compatibility (tmw/config-fix) $ ./check-protocol-compatibility.sh testnet
....
running 1 test
test test::snapshot_tests ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.48s
```
---

Fix protocol config after patching 1.33

---

crates/sui-bridge/src/monitor.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/orchestrator.rs

This PR lets `Monitor` subscribes to eth governance events as well. Next PR (https://github.com/MystenLabs/sui/pull/19389) implements the actual handling of these events.
---

[bridge] let monitor subscribe to eth governance events

---

crates/sui-transactional-test-runner/src/args.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Add a way to create programmable transactions with gas from a sponsor address, rather than a sender address
TBD -- will be used in a follow-up PR.
- #19371 
- #19402 
---

test: adds sponsor to transactional test runner

---

crates/sui-graphql-e2e-tests/tests/stable/objects/full_objects_history.exp
crates/sui-graphql-e2e-tests/tests/stable/objects/full_objects_history.move
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-indexer/src/models/obj_indices.rs
crates/sui-indexer/src/models/objects.rs

This PR queries the full_objects_history table for objects query.
It does so in a backward-compatible way. We always return data from the objects_history table if it's found, and otherwise we return from the full_objects_history table.
Added e2e test
---

[indexer] Use full_objects_history in reads

---

crates/sui-sdk/src/lib.rs
crates/sui-sdk/src/wallet_context.rs
crates/sui/src/client_commands.rs
crates/sui/tests/cli_tests.rs
crates/sui/tests/snapshots/cli_tests__clever_errors.snap

Added a new function `execute_tx` that is used only in the CLI that uses `WaitForEffectsCert` instead of `WaitForLocalExecution` to align with the deprecation of waiting for local execution. 
Also added the polling for transaction like in https://github.com/MystenLabs/sui/pull/18996/files
---

[cli] Switch to `WaitForEffectsCert` for CLI

---

crates/sui-bridge/src/events.rs
crates/sui-bridge/src/monitor.rs
crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/packages/bridge/sources/bridge.move

1. in `bridge.move` rename `ETokenAlreadyClaimed` to `ETokenAlreadyClaimedOrHitLimit` and update comments accordingly.
2. implements `handle_eth_events`, mostly bumping metrics for governance action events
3. use a macro to update sui side metrics as well
4. adds `UpdateRouteLimitEvent` from Sui.
---

[bridge] handle eth events in monitor

---

crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_address.exp
crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_address.move
crates/sui-graphql-rpc/src/types/address.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/transaction_block/filter.rs
crates/sui-graphql-rpc/src/types/transaction_block/tx_lookups.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap

Add `TransactionBlockFilter.affectedAddress` as a way to filter transactions by their relationship to an address without worrying about what kind of relationship that is.
New E2E tests: 
```
cargo nextest run -p sui-graphql-e2e-tests --features staging -- affected_address.move
```
- #19363
- #19371
- #19402 
- #19403
---

feat(graphql): Filter by affected address

---

.changeset/gentle-pugs-knock.md
sdk/typescript/src/transactions/plugins/NamedPackagesPlugin.ts
sdk/typescript/src/transactions/plugins/utils.ts
sdk/typescript/src/utils/move-registry.ts
sdk/typescript/test/e2e/named-packages-plugin.test.ts
sdk/typescript/test/unit/utils/move-registry.test.ts

1. After the recent decision to change our naming scheme to `{suins_name}/{app}/{optional_version}`, I am updating the plugin to also match the expected naming.
2. Also parse `MakeMoveVec` types.
Updated tests to match this, added extra test case for `MakeMoveVec`
---

[SDK][MVR] Move to new naming standard

---

external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/source_map_utils.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/trace_utils.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/utils.ts

This PR is the first in the series of PRs aiming to implement support for inspecting variables when viewing the trace (splitting this into multiple PRs to make the reviewing easier). The current focus is on primitive values (no structs/enums or references), but even with this limited focus it leaves the following work to subsequent PR:
- support for shadowed variables (a variable declared in an inner scope/block that has the same name as the one declared in the outer scope/block)
- support for moving backwards in trace
Tested manually to make sure that thing work correctly

[trace-view] Support for differently named variables moving forward

---

crates/sui-proxy/MYPKG
crates/sui-proxy/src/metrics.rs

* add a route for pod health in k8s
i am using the consumer_operations_submitted value but more values can be added later if we need to.  when this value is non-zero, it means the service is processing data correctly and can be used to consider it healthy enough to handle traffic.  it will be implemented as a liveness check.
local
---

[sui_proxy/pod health]

---

crates/sui-graphql-e2e-tests/tests/stable/transactions/filters/sent.exp
crates/sui-graphql-e2e-tests/tests/stable/transactions/filters/sent.move
crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_address.move
crates/sui-graphql-rpc/examples/address/transaction_block_connection.graphql
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/address.rs
crates/sui-graphql-rpc/src/types/transaction_block/filter.rs
crates/sui-graphql-rpc/src/types/transaction_block/tx_lookups.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap

`TransactionBlockFilter.signAddress` and `AddressTransactionBlockFilter.SIGN` both claim to support filtering by sender and sponsor, but this is not true, they only support sender, and they should not be adapted to also filter by sponsor because we rely on the there being only one sender per transaction to ensure filters that combine sender with something else remain both space and time efficient.
Existing tests and CI, plus some new tests to make sure the new filter options work, and interactions between the old and new filters work.
```
```
--- …

feat(graphql)!: deprecate tx signer filters

---

crates/sui-json-rpc/src/read_api.rs

Add the ability to get transaction effects in BCS form, from JSON-RPC's read path, by passing the `showRawEffects` option.
```
sui$ cargo build --bin sui --features indexer
sui$ $SUI start --force-regenesis --with-indexer --with-graphql --with-faucet
```
Then in another session:
```
sui$ $SUI client faucet
```
Find the transaction `$DIGEST` of the faucet transaction, and then fetch it with:
```
curl -LX POST  "http://localhost:9000" \
--data-raw '{
"method": "sui_getTransactionBlock",
"id": 1,
"params": ["'$DIGEST'", { "showRawEffects": true }]
}' | jq .
```
And corroborate it against the following GraphQL query:
```
query ($digest: String!) {
transactionBlock(digest: $digest) {
effects { bcs }
}
}
```
Which can be requested at …

feat(json-rpc): get transaction block raw effects

---

crates/sui-graphql-e2e-tests/tests/stable/prune.exp
crates/sui-graphql-e2e-tests/tests/stable/prune.move

Fix some flakiness in the `prune.move` by removing the initial checkpoints query which may witness different degrees of pruning.
Run the E2E tests in a loop -- previously this would trigger the failure after some time (usually fewer than 10 runs) and after this change, the same thing does not happen:
```
sui$ while true; do
cargo nextest run -p sui-graphql-e2e-tests
done
```
---

fix(graphql): flakiness in pruning test

---

.github/actions/ts-e2e/action.yml
.github/workflows/e2e.yml
.github/workflows/release.yml
crates/sui-graphql-rpc/README.md
crates/sui-indexer/README.md
crates/sui-rpc-loadgen/README.md
crates/sui-test-validator/src/main.rs
crates/sui/Cargo.toml
crates/sui/src/sui_commands.rs
crates/sui/tests/cli_tests.rs
docs/content/guides/developer/getting-started/local-network.mdx
sdk/graphql-transport/package.json
sdk/typescript/package.json

Recent improvements on GraphQL and Postgres code removed the dynamic linking to `libpq`. Due to this linking (GH actions was linking to postgres@14), we had to have a separate `sui-pg` binary that was built with the `indexer` feature such that one can have access to `sui start --with-indexer` and `--with-graphql` due to the required dependencies to Postgres. 
This PR removes the `indexer` feature, all the instances of building the binary with `--features indexer` in workflows, actions, etc, and updates the documentation (docs + sui-test-validator crate). This is possible because `libpq` is no longer a dependency that gets dynamically linked to the binary. Note that in order to use those flags, a running Postgres DB is still required just like before.
---
Check each box …

[cli] Remove indexer feature for `sui` and remove the `sui-pg` binary

---

crates/sui-indexer/migrations/pg/2024-09-19-121113_tx_affected_objects/down.sql
crates/sui-indexer/migrations/pg/2024-09-19-121113_tx_affected_objects/up.sql
crates/sui-indexer/src/models/tx_indices.rs
crates/sui-indexer/src/schema.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

Similar to #19355, introduce `tx_affected_objects` table -- a combination of `tx_input_objects` and `tx_changed_objects` which will both eventually be removed in favour of the new table.
```
sui$ cargo build -p sui-indexer
```
Tests based on reading this field will be included with the PR introducing changes to GraphQL.
---

feat(indexer): index tx_affected_objects

---

crates/sui-indexer/src/config.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/sql_backfill.rs

This PR adds 3 improvements to the sql backfill tool:
1. It allows ON CONFLICT DO NOTHING, so that we can safely backfill gaps without been too precise.
2. It tunes down the default concurrency and chunk size, and allows for override through command line args.
3. It prints out the minimum in-progress checkpoint so that if it ever stops for some reason, you can restart using that number.
Run again locally
---

[Indexer] A few improvements to backfill tool

---

crates/sui-protocol-config/src/lib.rs

Otherwise it is relatively easy to miss updating the max protocol version.
CI
---

Test MAX_PROTOCOL_VERSION is indeed the max supported version

---

crates/sui-indexer/migrations/pg/2023-10-07-160139_display/up.sql
crates/sui-indexer/src/models/display.rs
crates/sui-indexer/src/restorer/formal_snapshot.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

title
upload table to remote and restore from remote to make sure that tables match
```
(SELECT * FROM display EXCEPT SELECT * FROM display_backup)
UNION ALL
(SELECT * FROM display_backup EXCEPT SELECT * FROM display);
```
---

indexer restore 2/N: restore display table

---

crates/sui-indexer/migrations/pg/2024-09-18-003318_epochs_add_bcs_system_state/down.sql
crates/sui-indexer/migrations/pg/2024-09-18-003318_epochs_add_bcs_system_state/up.sql
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/epoch.rs
crates/sui-indexer/src/schema.rs
crates/sui-indexer/src/types.rs

The existing system_state column is a BCS serialization of a JSON-RPC type, which is not evolvable.
This PR adds a new column that is the JSON serialization of SuiSystemStateSummary without BCS.
It also fixes two bugs along the way:
1. We were storing the wrong version of the system state, offsetting by 1 epoch. This PR fixes it by storing the right version of the json column at the beginning of the epoch instead of at the end.
2. We were ignoring a deserialization error and swallow it in some place. Made that throw instead.
Added a debug assert to see that this column is populated with the correct epoch.
---
For each box you select, include information after the relevant …

[Indexer] Add json serialized SuiSystemStateSummary to epochs table

---

crates/sui-archival/src/reader.rs
crates/sui-indexer/src/errors.rs
crates/sui-indexer/src/restorer/archives.rs
crates/sui-indexer/src/restorer/formal_snapshot.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/types.rs

title
local run and verify checkpoints and chain_identifier table.
---

indexer restore 3/N: restore checkpoints and chain identifier

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/authority_node.rs

For validators with limited bandwidth, too much parallelism can increase fetch jitters and slow down the overall progress. Before we make the algorithm more adaptive, start with less parallelism by default.
PT
---

[Consensus] reduce commit sync fetch parallelism

---

consensus/core/src/dag_state.rs
consensus/core/src/linearizer.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs

This is the fist part that implements Garbage Collection for consensus.
Compared to Narwhal/Bullshark where the GC round was calculated and driven by the consensus component it self, here the single threaded nature of the system and the fact that we do have DagState - which is shared amongst all the components - allow us to base the gc round calculations purely on the latest committed round as derived from DagState.
On this PR:
* `Linearizer` has been refactored to respect the `gc_round`. When linearizer tries to commit leader `R` , it attempts to commit everything up to the `gc_round` that has been set from leader `R-1` (as already discussed this is the desired approach).
* `DagState` is calculating the current `gc_round` based on the latest commit.
* `gc_depth` has been added as a …

[Consensus] Garbage Collection - 1

---

Cargo.lock
crates/sui-rosetta/Cargo.toml
crates/sui-rosetta/src/lib.rs
crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs
crates/sui-rosetta/src/unit_tests/lib_tests.rs
crates/sui-rosetta/tests/custom_coins_tests.rs
crates/sui-rosetta/tests/end_to_end_tests.rs

Replaces coins hashmap cache with an lru cache
Unit tests
---

[rosetta] SEBP-97 Replace coins hashmap cache with an lru cache

---

docs/content/guides/operator/archives.mdx

small docs update so users don't need to supply aws creds
---

add no sign request to archives docs

---

crates/sui-framework/docs/move-stdlib/ascii.md
crates/sui-framework/docs/move-stdlib/bcs.md
crates/sui-framework/docs/move-stdlib/option.md
crates/sui-framework/docs/move-stdlib/string.md
crates/sui-framework/docs/move-stdlib/type_name.md
crates/sui-framework/docs/move-stdlib/vector.md
crates/sui-framework/packages/move-stdlib/sources/address.move
crates/sui-framework/packages/move-stdlib/sources/ascii.move
crates/sui-framework/packages/move-stdlib/sources/bcs.move
crates/sui-framework/packages/move-stdlib/sources/bit_vector.move
crates/sui-framework/packages/move-stdlib/sources/debug.move
crates/sui-framework/packages/move-stdlib/sources/fixed_point32.move
crates/sui-framework/packages/move-stdlib/sources/hash.move
crates/sui-framework/packages/move-stdlib/sources/macros.move
crates/sui-framework/packages/move-stdlib/sources/option.move
crates/sui-framework/packages/move-stdlib/sources/string.move
crates/sui-framework/packages/move-stdlib/sources/type_name.move
crates/sui-framework/packages/move-stdlib/sources/u128.move
crates/sui-framework/packages/move-stdlib/sources/u16.move
crates/sui-framework/packages/move-stdlib/sources/u256.move
crates/sui-framework/packages/move-stdlib/sources/u32.move
crates/sui-framework/packages/move-stdlib/sources/u64.move
crates/sui-framework/packages/move-stdlib/sources/u8.move
crates/sui-framework/packages/move-stdlib/sources/unit_test.move
crates/sui-framework/packages/move-stdlib/sources/vector.move

Uses module label in the MoveStdlib, runs the current build of the formatter on the code.
All tests must pass, no snapshot regen should be required.
---

[stdlib] Formats MoveStdlib package 1/N

---

crates/mysten-common/src/metrics.rs
crates/sui-bridge/src/metrics.rs
crates/sui-node/src/metrics.rs

A few improvements to metrics push logic.
CI
---

Improve metrics push

---

apps/wallet/src/ui/app/components/address-input/index.tsx

Adjusts the Send Form to show the "No prior transactions" warning onChange instead of onBlur. This helps ensure that the user sees it before moving onto the Review screen. 
https://github.com/user-attachments/assets/743c58f8-f9c5-4530-8677-6511530ee98a

fix: show prior transaction warning onChange

---

crates/sui-move/src/new.rs

Updated the sui move new command to use module labels.
---

:sparkles: feat: update sui-move new to use module labels

---

crates/sui-bridge/abi/bridge_config.json

This PR sorts bridge_config.json based on name field. This is to make future abi changes more readable.
jq -S 'sort_by(.name)' bridge_config.json > bridge_config.sorted
---

[bridge] sort bridge config abi

---

crates/sui-bridge/abi/bridge_config.json
crates/sui-bridge/abi/bridge_vault.json

This PR sorts bridge_vault.json based on name field. This is to make future abi changes more readable.
jq -S 'sort_by(.name)' bridge_vault.json > bridge_vault.sorted
---

[bridge] Sort bridge vault abi

---

crates/sui-bridge/abi/bridge_config.json
crates/sui-bridge/abi/bridge_limiter.json
crates/sui-bridge/abi/bridge_vault.json

This PR sorts bridge_limiter.json based on name field. This is to make future abi changes more readable.
jq -S 'sort_by(.name)' bridge_limiter.json > bridge_limiter.sorted
---

[bridge] sort bridge limiter abi

---

crates/sui-bridge/abi/bridge_committee_upgradeable.json
crates/sui-bridge/abi/bridge_config.json
crates/sui-bridge/abi/bridge_limiter.json
crates/sui-bridge/abi/bridge_vault.json

This PR sorts bridge_committee_upgradeable.json based on name field. This is to make future abi changes more readable.
jq -S 'sort_by(.name)' bridge_committee_upgradeable.json > bridge_committee_upgradeable.sorted
---

[bridge] sort bridge committee upgradeable abi

---

crates/sui-bridge/abi/bridge_committee.json
crates/sui-bridge/abi/bridge_committee_upgradeable.json
crates/sui-bridge/abi/bridge_config.json
crates/sui-bridge/abi/bridge_limiter.json
crates/sui-bridge/abi/bridge_vault.json

This PR sorts bridge_committee.json based on name field. This is to make future abi changes more readable.
jq -S 'sort_by(.name)' bridge_committee.json.json > bridge_committee.json.sorted
---

[bridge] sort bridge committee abi

---

crates/sui-bridge/abi/bridge_committee.json
crates/sui-bridge/abi/bridge_committee_upgradeable.json
crates/sui-bridge/abi/bridge_config.json
crates/sui-bridge/abi/bridge_limiter.json
crates/sui-bridge/abi/bridge_vault.json
crates/sui-bridge/abi/sui_bridge.json

This PR sorts sui_bridge.json based on name field. This is to make future abi changes more readable.
jq -S 'sort_by(.name)' sui_bridge.json > sui_bridge.sorted
---

[bridge] sort sui bridge abi

---

crates/sui-framework/packages/move-stdlib/tests/ascii_tests.move
crates/sui-framework/packages/move-stdlib/tests/bcs_tests.move
crates/sui-framework/packages/move-stdlib/tests/bit_vector_tests.move
crates/sui-framework/packages/move-stdlib/tests/fixedpoint32_tests.move
crates/sui-framework/packages/move-stdlib/tests/hash_tests.move
crates/sui-framework/packages/move-stdlib/tests/integer_tests.move
crates/sui-framework/packages/move-stdlib/tests/option_tests.move
crates/sui-framework/packages/move-stdlib/tests/string_tests.move
crates/sui-framework/packages/move-stdlib/tests/type_name_tests.move
crates/sui-framework/packages/move-stdlib/tests/u128_tests.move
crates/sui-framework/packages/move-stdlib/tests/u16_tests.move
crates/sui-framework/packages/move-stdlib/tests/u256_tests.move
crates/sui-framework/packages/move-stdlib/tests/u32_tests.move
crates/sui-framework/packages/move-stdlib/tests/u64_tests.move
crates/sui-framework/packages/move-stdlib/tests/u8_tests.move
crates/sui-framework/packages/move-stdlib/tests/vector_tests.move

Follow up on #19461.
Tests pass.
---

[stdlib] Formats tests in MoveStdlib 2/N

---

crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-indexer/src/sui_transaction_queries.rs
crates/sui-bridge/src/eth_syncer.rs
crates/sui-bridge/src/metrics.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-bridge/src/sui_mock_client.rs
crates/sui-bridge/src/sui_syncer.rs

This PR reworks `last_synced_sui_checkpoints` and `last_synced_eth_blocks`.
* `last_synced_sui_checkpoints`: when SuiSyncer gets events with false `has_next_page`, it means it has synced to the tip of the blockchain. Then it notifies the metrics update task to query the latest checkpoint from chain and update it. Apparently this is not accurate, but it is the best we can do today, because event query does not return checkpoint number. In the future when we switch to graphql, checkpoint num will be available and we can get rid of this. 
* Also note that when the bridge node is catching up, `has_next_page` will be true and the metrics is not going to be updated.
* `last_synced_eth_blocks`: make it a vector to track all contract progresses.
added a unit test for sui side.
---
Check each box …

[bridge] add height metrics

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm/src/memory/swarm.rs
crates/test-cluster/src/lib.rs

Currently we aggressive prine FNs by default which causes tests which depend on reading checkpoints from rest api fail
Existing tests

Add an option to disable fullnode pruning in test cluster

---

crates/sui/src/sui_commands.rs

Improves the error message when running `sui start` when a sui config folder exists without genesis metadata.
---

[cli] Better error message when a sui config folder exists without genesis metadata

---

crates/sui-core/src/authority.rs

This fixes a crash where we clear all pending locks at reconfig
(https://github.com/MystenLabs/sui/blob/dec33d0a303a7f83e778fcc5a136ab9776162e68/crates/sui-core/src/execution_cache/object_locks.rs#L121)
while trying to acquire locks for a transaction.
Without this fix, the node can reconfigure while we are trying to acquire locks for a transaction. If `clear_locks()` linked above is called while we are trying to call `clear_cached_locks` at https://github.com/MystenLabs/sui/blob/74d6d564970406e1b3191a07cf207af1ab6b3356/crates/sui-core/src/execution_cache/object_locks.rs#L245, we hit the panic at https://github.com/MystenLabs/sui/blob/74d6d564970406e1b3191a07cf207af1ab6b3356/crates/sui-core/src/execution_cache/object_locks.rs#L160

Hold reconfig lock while handling transaction

---

crates/sui-config/src/object_storage_config.rs
crates/sui-storage/src/object_store/http/s3.rs

Followup to https://github.com/MystenLabs/sui/pull/19470 which does the same for AWS and Azure object stores, as well as on the http downloader side. Note that most timeouts are disabled by default when using reqwest ClientBuilder directly, as we do on the http downloader side (`--no-sign-request`), so hopefully these changes are non-controversial. 
---

[object store] Disable more timeouts

---

crates/sui-json-rpc/src/error.rs

SUI JSON RPC returns errors which suggest a transaction was executed, however transactions which throw `NonRecoverableTransactionError`, do not execute the transaction but instead attempt to retrieve validator signatures. This change updates the wording to better describe which step this error is thrown.
Existing tests sufficiently cover this change.
---

fix(rpc): reword errors to transaction validator signing

---

crates/sui/src/client_commands.rs
crates/sui/src/sui_commands.rs
crates/sui/tests/cli_tests.rs

Fixes the issue that if the active env cannot be connected to, `active-env` and `envs` do not display the output but instead a low level network error appears.
---

[cli] Make prerender clever errors to use context instead of client

---

crates/sui-indexer/src/indexer_reader.rs

Some pg-backed jsonrpc methods got left in the dust as the indexer db schema became more specialized for graphql. This PR revisits read queries in `indexer_reader` and updates them to make use of the recent changes. This PR specifically addresses tx and events queries, which assumes that there is still an index to support queries by `transaction_digest`. Instead, we need to use the `tx_digests` lookup table for the `tx_sequence_number`, and use that to key into the transactions and events tables.
manual :eye:
--- …

[indexer] Adjust transactions queries to the latest db schema

---

crates/sui-framework/docs/sui-framework/dynamic_field.md
crates/sui-framework/docs/sui-framework/dynamic_object_field.md
crates/sui-framework/docs/sui-framework/priority_queue.md
crates/sui-framework/docs/sui-framework/table_vec.md
crates/sui-framework/docs/sui-framework/vec_map.md
crates/sui-framework/packages/sui-framework/sources/bag.move
crates/sui-framework/packages/sui-framework/sources/dynamic_field.move
crates/sui-framework/packages/sui-framework/sources/dynamic_object_field.move
crates/sui-framework/packages/sui-framework/sources/linked_table.move
crates/sui-framework/packages/sui-framework/sources/object_bag.move
crates/sui-framework/packages/sui-framework/sources/object_table.move
crates/sui-framework/packages/sui-framework/sources/priority_queue.move
crates/sui-framework/packages/sui-framework/sources/table.move
crates/sui-framework/packages/sui-framework/sources/table_vec.move
crates/sui-framework/packages/sui-framework/sources/vec_map.move
crates/sui-framework/packages/sui-framework/sources/vec_set.move

Another PR in the formatting series, covers collection modules and dynamic fields.
See also:
- #19496
- #19463  
- #19461 
Tests must pass, framework must produce the same bytecode.
---

[framework] Formatting: collections and dynamic fields 4/N

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_60.snap

[consensus] Enable distributed vote scoring in testnet

---

crates/sui-core/src/generate_format.rs
crates/sui-core/tests/staged/sui.yaml
crates/sui-types/src/message_envelope.rs
crates/sui-types/src/object.rs

Closes: https://github.com/MystenLabs/sui/pull/19516 
---

types: add CheckpointData to bcs sui.yaml description file

---

crates/sui-core/src/execution_cache/object_locks.rs
crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs

Fix crash when two threads concurrently lock the same transaction.
The new test case fails reliably if the fix is not present.

Support concurrent threads locking the same transaction

---

crates/sui-core/src/execution_cache/object_locks.rs
crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs

Fix crash when two threads concurrently lock the same transaction.
The new test case fails reliably if the fix is not present.

Support concurrent threads locking the same transaction (#19526)

---

crates/sui-graphql-e2e-tests/tests/stable/epoch/system_state.exp
crates/sui-indexer/migrations/pg/2024-09-24-213054_epochs_system_state_nullable/down.sql
crates/sui-indexer/migrations/pg/2024-09-24-213054_epochs_system_state_nullable/up.sql
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/epoch.rs
crates/sui-indexer/src/schema.rs

This PR makes the old system_state column nullable, and stop reading from it.
CI
---

[Indexer] Stop reading old system_state in epochs

---

crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/indexer.rs

This PR makes a few improvements to the pruner:
1. It stops depending on the epochs table data range as the watermark for global pruning decisions. Instead, it keeps track of the next prune epoch and last seen max epoch locally in the task. Once we have the actual watermark table we probably could further improve it.
2. It also fixes an issue where we ignore failed pruning error.
Unfortunately we don't have any tests for pruner.
---

[Indexer] Break dependency between pruner and epoch watermark

---

crates/sui-indexer/src/handlers/pruner.rs

Add support to override epoch retention for individual tables. This can be passed from the command line.
It only supports partitioned table today. For non-partitioned tables it will take some wiring to make it work and not urgent. We need this today mainly to prune the objects_history table more aggressively.
CI
---

[Indexer] Support 2-day retention for objects_history table

---

external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts
external-crates/move/crates/move-analyzer/trace-debug/src/extension.ts

This PR adds handling of shadowed variables to the trace viewer:
- shadowed variables appear in separate scopes
- shadowed scope appears when a variable with the same name as an already existing one is declared
- shadowed scope disappears when all variables it includes stop being live
Additionally, this PR (temporarily) suppresses on-hover information that VSCode shows during debug session. The reason for it is that the default VSCode behavior in this department breaks in presence of shadowed variables
Tested manually

[move-ide] Added support for variable shadowing

---

crates/sui-json-rpc/src/lib.rs

This PR adds origin header logging into the json-rpc middleware.
Ran sui-node locally and tested RPC calls using suiscan.xyz custom node option.
example log line output: 
`2024-09-25T01:55:05.077872Z  INFO json-rpc-request{origin=https://custom.suiscan.xyz}:get_validators_apy: sui_json_rpc::governance_api: get_validator_apy`
---

[sui-node][json-rpc] log origin headers for json-rpc

---

docs/content/concepts/events.mdx
docs/content/concepts/sui-move-concepts/conventions.mdx
docs/content/concepts/sui-move-concepts/packages/custom-policies.mdx
docs/content/concepts/transactions/prog-txn-blocks.mdx

- Use `move` instead of `rust` for some code blocks
- Fix alignment in `conventions.md` with standard 4 spaces
- Fix minor formatting issues elsewhere

[docs] Fixed typos and formatting

---

scripts/compatibility/check-protocol-compatibility.sh

- Revert workaround that is no longer necessary
- Support running without a metrics api key
- Show diffs if the script fails

Fixes for compatibility checker

---

Cargo.lock
crates/sui-json-rpc/Cargo.toml
crates/sui-json-rpc/src/read_api.rs

when query transaction with showEvents set, it's possible that the transaction effects is available while events are not, as events are outputs of fn local execution, thus instead of returning empty events and make whole transaction response in-complete, we should retry, in that sense as long as fn responds, the response is complete. 
ci
---

fn json rpc: retry on empty events

---

crates/sui-indexer/src/config.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/restorer/archives.rs
crates/sui-indexer/src/restorer/formal_snapshot.rs

- we made `archives` and `display` buckets public, thus restorer no longer needs gcs cred
- remove un-necessary required args / env vars so that to restore from mainnet, only start-epoch & local snapshot download dir needs to be specified.
local run of restorer
---

indexer restorer: simplify commands

---

crates/sui-core/src/checkpoints/mod.rs

Otherwise it is possible for this panic to be hit: https://github.com/MystenLabs/sui/blob/34c9e3ef6fff67df7f6ec89b4ccee462fb111df2/crates/sui-core/src/checkpoints/mod.rs#L957

Terminate checkpoint builder before end of epoch

---

crates/sui-indexer/src/db.rs

It's okay for the list of locally known migrations to be a subset of the applied migrations, rather than a prefix (The only clear issue is if there is a migration that has been embedded locally, but that hasn't been run on the DB).
New unit test:
```
sui-indexer$ cargo nextest run
```
And confirm against the production DB.
---

indexer: relax migration check

---

crates/sui-network/src/state_sync/mod.rs

It seems `connection_rtt()` can get updated concurrently. This breaks total ordering, which becomes required for sorting in rust 1.81.
Other callsites of `sort_by()` are reviewed and they don't seem to have the same issue.
PT
---

Fix sorting in peer discovery

---

consensus/core/src/authority_service.rs
consensus/core/src/block_manager.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

Use the hostname whenever possible. Add the error type as well.
CI
---

[Consensus] Small enhancement to the invalid blocks metric 

---

crates/sui-indexer/src/db.rs

It's okay for the list of locally known migrations to be a subset of the applied migrations, rather than a prefix (The only clear issue is if there is a migration that has been embedded locally, but that hasn't been run on the DB).
New unit test:
```
sui-indexer$ cargo nextest run
```
And confirm against the production DB.
---

pick(19558) indexer: relax migration check

---

crates/sui-move-build/src/lib.rs
external-crates/move/crates/move-package/src/package_hooks.rs
external-crates/move/crates/move-package/src/resolution/dependency_cache.rs
external-crates/move/crates/move-package/src/resolution/dependency_graph.rs
external-crates/move/crates/move-package/src/resolution/mod.rs
external-crates/move/crates/move-package/src/resolution/resolution_graph.rs
external-crates/move/crates/move-package/src/source_package/manifest_parser.rs
external-crates/move/crates/move-package/src/source_package/parsed_manifest.rs
external-crates/move/crates/move-package/tests/test_runner.rs
external-crates/move/crates/move-package/tests/test_sources/package_hooks/Move.resolved
external-crates/move/crates/move-package/tests/test_sources/package_hooks/Move.toml
external-crates/move/crates/move-package/tests/test_sources/package_hooks_subdir/Move.resolved
external-crates/move/crates/move-package/tests/test_sources/package_hooks_subdir/Move.toml
external-crates/move/crates/move-package/tests/test_sources/parsing_no_path_set_for_dependency/Move.resolved

Refactor `Custom` dependency to `OnChain` (in the manifest) and streamline it. It now requires only the `id` field which specifies dependency's on-chain id (e.g. `Foo = { id = "0x123" }`. `Custom` dependencies aren't supported on Sui so this should be a fairly safe change.
This is part of the work to enable compiling against on-chain dependencies https://github.com/MystenLabs/sui/pull/14178.
cc @rvantonder @amnn
Updated existing unit tests.
---

[on-chain-deps][manifest] change `Custom` dependency to `OnChain`

---

crates/mysten-common/src/lib.rs
crates/mysten-common/src/logging.rs
crates/sui-core/src/execution_cache/object_locks.rs

Add two macros as superior alternatives to panic!
- `fatal!` logs its message at error level, and then panics. Logged messages are often easier to find than panic messages, both in loki and in simtest logs.
- `debug_fatal!` is a variant of `fatal!` that only logs an error in release mode.

Add fatal! and debug_fatal! macros

---

sdk/docs/pages/dapp-kit/sui-client-provider.mdx

Remove import duplication `from '@mysten/dapp-kit'` for Sui Client Provider "Using network specific configuration" code example (dapp-kit doc)
Sui Client Provider "Using network specific configuration" code example, link (https://sdk.mystenlabs.com/dapp-kit/sui-client-provider#using-network-specific-configuration)
---

[sdk docs] Remove import duplication for dapp-kit sui client provider

---

crates/sui-json-rpc/src/balance_changes.rs
crates/sui-json-rpc/src/transaction_execution_api.rs

Also populate the object cache used for calculating balance changes with the input objects returned from the validators.
---

jsonrpc: populate object cache with input objects

---

external-crates/move/crates/move-package/src/resolution/dependency_graph.rs
external-crates/move/crates/move-package/tests/test_sources/external_package_batch_response/Move.locked
external-crates/move/crates/move-package/tests/test_sources/external_package_batch_response/Move.resolved
external-crates/move/crates/move-package/tests/test_sources/resolvers/successful_package_batch_response.sh

Small fix to correctly load dependency version when using external resolver. Changed `echo` in `successful_package_batch_response.sh` to `printf` for more consistent handling of `\0` across systems (it fails on my machine).
This is part of the work to enable compiling against on-chain dependencies https://github.com/MystenLabs/sui/pull/14178.
cc @rvantonder @amnn
Updated the unit test to have a dependency with `version` field.
---

move: load package version when using external resolver in dependency graph

---

consensus/core/src/synchronizer.rs

[Consensus] use authority_index to derive hostname

---

crates/sui-bridge-indexer/src/eth_bridge_indexer.rs
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-indexer/src/metrics.rs
crates/sui-bridge-indexer/src/storage.rs
crates/sui-bridge-indexer/src/sui_datasource.rs

Currently indexer reports `current_checkpoint` when saving progress to DB. This makes the metrics a bit out of state when we cache the metrics in memory. This PR:
1. moves the metrics to data retrieval stage,
2. rename it to `latest_retrieved_checkpoints`
3. in EthSubscription task, periodically fetch the latest block height and update this metric
---

[bridge-indexer] move current checkpoint metric to retrieval stage

---

external-crates/move/crates/move-analyzer/src/analysis/typing_analysis.rs
external-crates/move/crates/move-analyzer/tests/enums.exp
external-crates/move/crates/move-analyzer/tests/enums.ide
external-crates/move/crates/move-analyzer/tests/move-2024/sources/structs.move
external-crates/move/crates/move-analyzer/tests/structs.exp
external-crates/move/crates/move-analyzer/tests/structs.ide

This PR improves on certain aspects of on hover for structs and enums. Mainly, it shows more meaningful information for struct/variant field values when packing structs/variants. Before, it would show information about the field itself, which was not very useful when inspecting the pack operation:
In the case above, it makes a lot more sense to show information about constant `TMP` which is what is implemented in this PR:
This PR also includes a fix to displaying on-hover information for variants when inspecting the pack operation
Old and newly added tests must pass

[move-ide] Improvements to on hover for structs and enums

---

crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_object.exp
crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_object.move
crates/sui-graphql-rpc/src/types/transaction_block/filter.rs
crates/sui-graphql-rpc/src/types/transaction_block/tx_lookups.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap

Add support for filtering transactions by the objects they touch, which will supersede filtering by a transaction's input and output objects.
This feature will exist only in staging mode until the underlying data has been fully backfilled.
New staging-only tests:
```
sui$ cargo nextest run -p sui-graphql-e2e-tests --features staging -- affected_object
```
---

graphql: filter transactions by affected object 

---

crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_object.exp
crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_object.move
crates/sui-graphql-rpc/src/types/transaction_block/filter.rs
crates/sui-graphql-rpc/src/types/transaction_block/tx_lookups.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
crates/sui-indexer/src/indexer_reader.rs
crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-open-rpc/spec/openrpc.json

Add an `AffectedObject` filter on `TransactionFilter` and implement it in `IndexerReader` and in the subscription system.
This filter is not implemented on fullnode indices, and in a follow-up PR, support for `InputObject` and `ChangedObject` will be removed from the PG-backed implementation of JSON-RPC.
It was difficult to replace `InputObject`/`ChangedObject` support on fullnode with `AffectedObject` because we don't have (and don't want to add) the necessary indices, and the current filters are referred to in certain tests.
Manually tested with a local network:
```
sui$ cargo run --bin sui -- start --with-indexer --force-regenesis
```
```
sui$ curl -LX POST  "http://localhost:9124" \
--data '{
"id": 1,
"method": …
```

indexer: support TransactionFilter::AffectedObject

---

crates/sui-indexer/src/indexer_reader.rs

Remove support for filtering by `ToAddress` in PG-backed JSON-RPC. At the same time, change implementations for `FromAndToAddress` and `FromOrToAddress` to use the new `tx_affected_addresses` table, which should be more efficient.
Manually tested:
```
sui$ cargo run --bin sui -- --force-regenesis \
--with-faucet --with-indexer
```
```
sui$ $SUI client faucet
sui$ $SUI client ptb --transfer-objects [gas] @0x42
sui$ curl -LX POST  "http://localhost:9124" \
--data '{
"id": 1,
"method": "suix_queryTransactionBlocks",
"params": [
{
"filter": {
"FromOrToAddress": { "addr": "'($SUI client active-address)'" }
}
},
null,
50,
true
]
}' | jq .result.data.[].digest
"4NDjddQA8Q158EuskHm73AVoo4Gmr6SknuTv1nzghVd1" …
```

indexer: deprecate TransactionFilter::ToAddress

---

crates/sui-core/src/authority.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-sdk/examples/event_api.rs
crates/sui-sdk/src/apis.rs

This PR removes EventFilters from JSON-RPC that aren't supported already by fullnode-backed JSON-RPC:
- Combination filters (`All`, `Any`, `Not`, `And`, `Or`)
- `Package`
- `EventField`
These filters were, however, supported by the now-deprecated subscription system, so a question remains whether they are safe to remove.
Manually tested, in particular `All: []` support, which we do still need to keep as a way to get all filters (this was also added to the `IndexerReader` implementation):
```
sui$ cargo run --bin sui -- --force-regenesis \
--with-indexer --with-faucet
```
...run for some time, so that some system events accumulate, then test that we get them from both the fullnode-backed JSONRPC and indexer-backed:
Fullnode:
```
curl -LX POST  "http://localhost:9000" \
--header …
```

events: Remove unsupported filters

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/models/tx_indices.rs
crates/sui-indexer/src/types.rs

Broaden the definition of "affected object" to include objects that a transaction creates and then immediately wraps, or objects that it unwraps and then immediately deletes. This ensures that a transaction will show up in the response to an `affectedObject` query if and only if the Object's ID shows up in its `objectChanges` response.
Updated GraphQL E2E test:
```
--features staging -- affected_object
```
---

pick(19618), indexer: affected objects include created+wrapped/unwrapped+deleted

---

crates/sui-core/src/authority.rs
crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_object.exp
crates/sui-graphql-e2e-tests/tests/staging/transactions/filters/affected_object.move
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/tx_indices.rs
crates/sui-indexer/src/types.rs
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-sdk/examples/event_api.rs
crates/sui-sdk/src/apis.rs

Broaden the definition of "affected object" to include objects that a transaction creates and then immediately wraps, or objects that it unwraps and then immediately deletes. This ensures that a transaction will show up in the response to an `affectedObject` query if and only if the Object's ID shows up in its `objectChanges` response.
Updated GraphQL E2E test:
```
--features staging -- affected_object
```
- #19474 
- #19614 
- #19615 
- #19616 
- #19617
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take …

indexer: affected objects include created+wrapped/unwrapped+deleted

---

crates/sui-config/data/fullnode-template.yaml

Update fullnode-template.yaml to include archival fallback

---

crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs
crates/sui-types/src/object/bounded_visitor.rs
external-crates/move/crates/move-core-types/src/annotated_value.rs

Introduce `FieldVisitor` as a new `annotated_visitor::Visitor` for extracting details from a `sui::dynamic_field::Field` without fully deserializing its name and value. This is helpful in a couple of places where not all the information is needed at once.
- When indexing, we can extract just the information that aids indexing, and not anything else.
- In GraphQL, the name and value fields are accessed separately, and we currently unnecessarily move back-and-forth between the serialized and structured representations to support this use case.
This commit does not replace any instances of dynamic field serialization, but introduces the visitor and associated tests.
```
sui-types$ cargo nextest run -- dynamic_field::visitor
```
- #19517 
---
Check each box that your changes affect. If none …

visitor: FieldVisitor for partially deserializing dynamic fields

---

crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs
crates/sui-types/src/object/bounded_visitor.rs
external-crates/move/crates/move-core-types/src/annotated_value.rs

Use the annotated visitor pattern to avoid deserializing a whole DynamicField (include its name and value) to only fetch one part of it.
```
sui-graphql-rpc$ cargo nextest run -j 1
sui-graphql-e2e-tests$ cargo nextest run
```
- #19517 
- #19518 
---

graphql(visitor): avoid DynamicField to-and-fro

---

crates/sui-framework/packages/move-stdlib/sources/unit_test.move

This is what we have today when using `assert_eq!`
```
[debug] 0x417373657274696f6e206661696c65643a
[debug] 2000
[debug] 0x213d
[debug] 1000
```
This is what we really want:
```
[debug] Assertion failed:
[debug] 2000
[debug] !=
[debug] 1000
```
---

[framework] output human readable debug in `std::unit_test`

---

crates/sui-indexer/src/indexer_reader.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs

Use `FieldVisitor` to extract necessary information from a dynamic field object, rather than fully expanding it, which can fail if the overall size is too large.
Unfortunately, because `DynamicFieldInfo` includes a structured representation of the field name, this operation can still fail if the name alone is too large to deserialize using `BoundedVisitor`, but we can at least avoid deserializing the value.
Build and run the indexer reader against a mainnet DB, and check for `0x5`:
```
sui$ cargo run --bin sui-indexer -- --database-url "$DB" --pool-size 10 \
json-rpc-service --rpc-client-url "https://fullnode.mainnet.sui.io:443"
```
Make the request:
```
$ curl -LX POST  "https:/fullnode.mainnet.sui.io:443" \
--data-raw '{ …
```

indexer(visitor): avoid fully deserializing dynamic field

---

crates/sui-core/src/rest_index.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs

Make it so that deserializing dynamic field info does not inflate the whole field -- just the outer struct -- which in turn means that this operation cannot fail.
```
sui$ cargo simtest
sui-adapter-transactional-tests$ cargo simtest
```
- #19517 
- #19518 
- #19519 
- #19520 
---

rest(visitor): avoid fully deserializing dynamic field

---

crates/sui-core/src/authority.rs
crates/sui-core/src/rest_index.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs

Make it so that deserializing dynamic field info does not inflate the whole field -- just the outer struct -- which in turn means that this operation cannot fail.
```
sui-core$ cargo simtest
sui-adapter-transactional-tests$ cargo simtest
```
- #19517 
- #19518 
- #19519 
- #19520 
- #19521 
---

authority(visitor): avoid fully deserializing dynamic field

---

crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/rest_index.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs

Switches the analytics indexer to use the new dynamic field visitor so that we inflate the value as little as possible during the indexing process. 
CI
---

[visitor] use dynamic field visitor in analytics indexer

---

crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/rest_index.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-indexer/src/types.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs

Use `FieldVisitor` to extract the dynamic field kind from a serialized MoveObject without deserializing the whole thing. This makes it so that the indexing process cannot fail if presented with an overly large dynamic field.
This PR also simplifies dynamic field indexing, taking advantage of the fact that we now only store the `df_kind`, and not any other part of `df_info`.
```
sui-indexer$ cargo nextest run
sui-graphql-e2e-tests$ cargo nextest run
```
- #19517
- #19518 
- #19519 
- #19520 
- #19521 
- #19548 
- #19554
--- …

indexer(visitor): avoid fully deserializing dynamic field on write path

---

crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/rest_index.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-indexer/src/types.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v1/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v2/sui-move-natives/src/object_runtime/mod.rs

Replace the legacy implementations of `get_all_uids` with the one that has been used in `latest` for some time now. This version avoids inflating the whole struct just to read its UIDs.
The main motivation in making the switch is to reduce the number of call-sites that use `simple_deserialize`, so that we can eventually get rid of it entirely, and replace it with a visitor based ipmplementation that includes the appropriate caveats around inflating a whole struct in memory.
```
sui$ cargo simtest
```
- #19517
- #19518 
- #19519 
- #19520 
- #19521 
- #19548 
- #19554
- #19565
--- …

adapter(visitor): Use UIDTraversal across all execution layers

---

crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/rest_index.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-indexer/src/types.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v0/sui-move-natives/src/test_scenario.rs
sui-execution/v1/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v1/sui-move-natives/src/test_scenario.rs
sui-execution/v2/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v2/sui-move-natives/src/test_scenario.rs

Use a custom annotated visitor to implement detecting wrapped objects in test scenario. Unlike other instances where we have switched to a custom visitor, there isn't an OOM risk or risk of failure at this call site,
because it is only used in Move tests, which are only run locally, but the motivation for this change is to avoid a reliance on `simple_deserialize` in the codebase, as it is too easy to copy this pattern and introduce a vulnerability elsewhere.
Eventually `simple_deserialize` will go away and be replaced by something that is based on the new annotated visitor, but looks scary enough to use that people think twice before reaching for it.
```
sui$ cargo nextest run -p sui-framework-tests
```
- #19517
- #19518 
- #19519 
- #19520 
- #19521 
- #19548 
- #19554
- #19565 
- #19576 …

framework(visitor): test_scenario wrapped object traversal

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/objects_snapshot_processor.rs
crates/sui-indexer/src/handlers/tx_processor.rs
crates/sui-indexer/src/store/package_resolver.rs

Further simplification to dynamic field indexing, where we avoid deserializing dynamic fields altogether and extract the only piece of information we need (whether the DF is a dynamic field or a dynamic object field) from its type.
DF deserialization was also the only reason to perform package resolution during indexing, so this change also means we can remove the package resolver, package buffer and logic to keep those up-to-date (pushing in new packages before indexing a checkpoint, and "evicting" packages after a checkpoint had been processed).
```
```
- #19517
- #19518 
- #19519 
- #19520 
- #19521 
- #19548 
- #19554
- #19565 
- #19576 
- #19621 
---
Check each box that your changes affect. If none of the boxes relate to your changes, …

indexer: no need to deserialize dynamic fields

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_types/consensus_output_api.rs

- Each consensus commit includes its previous commit's digest. Commit digests are logged inside consensus. So I believe we have what is needed to debug forks without the rolling hash inside consensus handler now.
- Deprecate the `last_consensus_index` table. It's replacement `last_consensus_stats` has been populated for awhile.
- Remove Narwhal implementation of ConsensusOutputAPI.
CI
---

[Cleanup] remove rolling hash from consensus handler

---

crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/rest_index.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/objects_snapshot_processor.rs
crates/sui-indexer/src/handlers/tx_processor.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-indexer/src/store/package_resolver.rs
crates/sui-indexer/src/types.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/dynamic_field/visitor.rs
crates/sui-types/src/object/balance_traversal.rs
crates/sui-types/src/object/bounded_visitor.rs
external-crates/move/crates/move-core-types/src/annotated_value.rs
external-crates/move/crates/move-core-types/src/annotated_visitor.rs
external-crates/move/crates/move-core-types/src/unit_tests/visitor_test.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/v0/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v0/sui-move-natives/src/test_scenario.rs
sui-execution/v1/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v1/sui-move-natives/src/test_scenario.rs
sui-execution/v2/sui-move-natives/src/object_runtime/mod.rs
sui-execution/v2/sui-move-natives/src/test_scenario.rs

Various refactors to expose the underlying byte stream, and the driver's progress through it to the visitor. This is done by:
- Introducing a `Cursor` to track the progress of the visitor, instead of using a `&mut &[u8]` (which "forgets" the bytes it has already produced).
- Introducing a `ValueDriver` to act as a driver for all other types that don't currently have a driver.
- Parametrizing the trait and drivers with lifetimes, so that it's possible for implementations to return values that reference those lifetimes.
New unit test for byte offset tracking:
```
move-core-types$ cargo nextest run -- byte_offset_test
```
---
For each box you select, include information after …

move(visitor): expose underlying byte slice

---

crates/sui-json-rpc/src/balance_changes.rs
crates/sui-json-rpc/src/transaction_execution_api.rs

Cherry-pick: jsonrpc: populate object cache with input objects (#19589)

---

consensus/config/src/parameters.rs
consensus/core/src/core.rs

It seems the default delay can result in too many commits per sec.
Also turn another per-commit log into debug, since we have not seen related issues recently.
CI
---

[Consensus] increase min round delay in tests

---

crates/sui-proxy/src/admin.rs
crates/sui-proxy/src/lib.rs

add an on_error to the trace layer
add a timeout to all routes, configurable via env vars or using the default.
nodes sending metrics will have an enforced timeout of 20 seconds. If metrics cannot be sent in that time, the sui-proxy metrics server will disconnect the client. This will not affect the blockchain or any related activity. It only applies to metrics transmission.
---

[sui-proxy/timeouts+errors]

---

docs/content/guides/developer/sui-101/sign-and-send-txn.mdx

Noticed some strange formatting, I think the problem is these vars are un-escaped
---

[docs] Fix formatting issues

---

apps/core/src/hooks/useFormatCoin.ts
apps/wallet/src/ui/app/components/buynlarge/HomePanel.tsx
apps/wallet/src/ui/app/components/coin-icon/index.tsx
apps/wallet/src/ui/app/hooks/useGetAllBalances.ts
apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
apps/wallet/src/ui/app/pages/home/usdc-promo/UsdcPromo.tsx
apps/wallet/src/ui/app/pages/home/usdc-promo/UsdcPromoBanner.tsx
apps/wallet/src/ui/app/pages/home/usdc-promo/useUsdcPromo.ts
apps/wallet/src/ui/app/pages/swap/utils.ts
apps/wallet/src/ui/app/shared/text/index.tsx

add banners

---

docs/content/guides/developer/advanced/graphql-migration.mdx

Adding some examples of things that we can do with GraphQL that can't be done with JSON-RPC.
:eyes: (and trying out the queries)
---

docs: examples of things only GraphQL can do

---

Cargo.lock
crates/sui-indexer/Cargo.toml
crates/sui-indexer/src/backfill/backfill_instances/ingestion_backfills/ingestion_backfill_task.rs
crates/sui-indexer/src/backfill/backfill_instances/ingestion_backfills/mod.rs
crates/sui-indexer/src/backfill/backfill_instances/ingestion_backfills/raw_checkpoints.rs
crates/sui-indexer/src/backfill/backfill_instances/mod.rs
crates/sui-indexer/src/backfill/backfill_runner.rs
crates/sui-indexer/src/backfill/mod.rs

This PR adds a backfill pipeline based on ingestion.
It also implement backfilling the raw checkpoints table.
Run backfill locally.
---

[Indexer] Add ingestion based backfill

---

crates/sui-indexer/src/backfill/backfill_instances/mod.rs
crates/sui-indexer/src/backfill/backfill_instances/sql_backfills/event_sender.sh
crates/sui-indexer/src/backfill/backfill_instances/sql_backfills/full_objects_history.sh
crates/sui-indexer/src/backfill/backfill_instances/system_state_summary_json.rs
crates/sui-indexer/src/backfill/backfill_instances/tx_affected_objects.rs
crates/sui-indexer/src/backfill/mod.rs

Custom backfill script for populating `tx_affected_objects` by loading the raw effects from the database and pulling the `object_changes` from it.
Includes a small clean-up parameterising the script-based SQL backfills.
Ran an updated version of this script locally, just printing the values to be added and ran that locally.
---

indexer: backfill tx_affected_objects 

---

Cargo.lock
Cargo.toml
crates/sui-bridge-indexer/Cargo.toml
crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-watchdog/Cargo.toml
crates/sui-bridge-watchdog/src/eth_bridge_status.rs
crates/sui-bridge-watchdog/src/eth_vault_balance.rs
crates/sui-bridge-watchdog/src/lib.rs
crates/sui-bridge-watchdog/src/metrics.rs
crates/sui-bridge-watchdog/src/sui_bridge_status.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/utils.rs

This PR adds
1. `Observable` traits that each perform an observation task to monitor bridge status.
1. `SuiWatchDog` that facilitates running `Observable` tasks
2. `EthVaultBalance` `SuiBridgeStatus`, and `EthBridgeStatus` that monitors vault balances on eth vault, whether sui bridge is paused and whether eth bridge is paused respectively.
running locally.
---

[bridge] add sui watch dog and a few observables

---

crates/sui-bridge-indexer/src/eth_bridge_indexer.rs
crates/sui-bridge-watchdog/src/eth_vault_balance.rs
crates/sui-indexer-builder/src/indexer_builder.rs

[bridge indexer] retry getting block number and add more logs when it err

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/object_locks.rs
crates/sui-core/src/execution_cache/passthrough_cache.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/transaction_deny_tests.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
crates/sui-types/src/transaction.rs
docker/sui-network/docker-compose-antithesis.yaml

Writeback cache has been stable on all mysten fullnodes plus our testnet validator for several months. Time to enable it by default everywhere

Enable writeback cache by default

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-e2e-tests/tests/simulator_tests.rs

The new table can be used with or without the random beacon. The only requirement is that we don't deploy this commit to a validator that is currently using the old table. An assert is added which will stop us from doing this accidentally.

Remove use of assigned_shared_object_versions

---

crates/sui-indexer/src/backfill/backfill_instances/tx_affected_objects.rs

When a given range of transactions generated too many affected object IDs, the backfill script would stop, because of limits in postgres' protocol over the wire.
By chunking up the writes into batches of 1000, we avoid hitting this limit.
Running this backfill against the DBs now -- and it is not crashing.
---

fix(backfill): chunk up writes to DB

---

crates/sui-cluster-test/src/cluster.rs
crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui/src/sui_commands.rs

Avoid duplicating fields for configs that are accepted as flags from the command-line and can also be read from TOML file. Use the same struct for both purposes but deocrate it with both `clap` and `serde` (or `GraphQLConfig`) annotations so that it can serve both purposes.
This change should preserve the config/command-line interface -- checked by running the GraphQL service with the same invocation, referencing all flags, before and after the change.
---

chore(graphql): deduplicate configs and clap args

---

crates/sui-cluster-test/src/cluster.rs
crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui/src/sui_commands.rs

Add a flag to optionally skip database migration compatibility checks. This is helpful when trying to connect a local build up to a production database to test a specific change, even if you are aware that other queries may not be compatible.
To accommodate this change, the compatibility check was also moved into `ServerBuilder` where the config is readily available. This also slightly simplifies the `Server` itself, which no longer needs to hold onto its own instance of the `Db`.
Connected a local build of GraphQL to the production DB, which it is not compatible with.
- #19670
--- …

graphql: add flag to skip db compatibility

---

crates/sui-cluster-test/src/cluster.rs
crates/sui-graphql-e2e-tests/tests/stable/events/sending_module.exp
crates/sui-graphql-e2e-tests/tests/stable/events/sending_module.move
crates/sui-graphql-rpc/src/commands.rs
crates/sui-graphql-rpc/src/config.rs
crates/sui-graphql-rpc/src/main.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_62.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_62.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_62.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
crates/sui/src/sui_commands.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs

Make it so that the module that is associated as the "sending module" for an event is relocated by linkage. This fixes an issue (captured in a regression test) where if the function that is called by the PTB is from some upgraded version of the package, it cannot be found because the Event's package ID still points to the original version of the package.
Introduced a regression test -- before the change, the "sending module" in the response returned `null`.
```
sui$ cargo nextest run -p sui-graphql-e2e-tests -- sending_module
```
- #19670 
- #19671 
--- …

core: event sending module relocation

---

consensus/core/src/commit_syncer.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs

- With less fetch parallelism, randomized target authorities should be acceptable for load distribution. And it is easier to reason about.
- Add a metric for fetch failures per peer.
CI
PT
---

[Consensus] remove PeerState from CommitSyncer

---

crates/sui-graphql-rpc/src/config.rs

I accidentally turned it into a positional argument in a recent refactoring. This change changes it back.
```
sui$ cargo run --bin sui-graphql-rpc -- start-server --help
```
---

fix(graphql): restore --node-rpc-url flag

---

crates/sui-graphql-rpc/src/types/object.rs

This PR mitigates the issue where we select all unfiltered results when the `load` function uses `or_filter` and the provided keys are empty. 
Tested locally against testnet db. The symptom of this bug was a dry run timeout when the user attempts to fetch gas object info so I don't know how we can repro the issue in local unit test without a big db.
---

[fix] return empty results when provided object lookup keys are empty

---

consensus/core/src/authority_service.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/metrics.rs
consensus/core/src/round_prober.rs

To be used in smart ancestor selection [PR#19605](https://github.com/MystenLabs/sui/pull/19605)
---

[consensus] return quorum rounds from round prober

---

crates/sui-cluster-test/src/cluster.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/lib.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-indexer/tests/ingestion_tests.rs
crates/sui/src/sui_commands.rs

Currently, tests that require spinning up an indexer do so through `start_test_indexer_impl` or `start_test_indexer`. This is further complicated by a single `start` function that accepts a `ReaderWriterConfig`. We can simplify this by exposing two functions with optional parameters that can be configured by the caller.
Part of a stack of PRs for watermarks
1. simplify setting up test indexer: https://github.com/MystenLabs/sui/pull/19663
2. update pruner config: https://github.com/MystenLabs/sui/pull/19637
3. committer writes upper bounds https://github.com/MystenLabs/sui/pull/19649
4. pruner writes lower bounds: https://github.com/MystenLabs/sui/pull/19650
5. pruner prunes (wip)
---
Check each box that your changes affect. If none of the boxes …

[indexer] Simplify setting up a test indexer writer or reader

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-types/src/transaction.rs

This PR is in preparation for data quarantining. The DQ PR will move the tables affected by this PR entirely into memory, and crash recovery will be driven by re-processing consensus commits.
However, when we deploy DQ to a validator for the first time, we will restart in a state where uncertified consensus commits have already been marked as processed, so they will not be re-processed on startup.
This means that upon starting up for the first time, some data will be on disk instead of in memory. There are two possible solutions to this:
- All reads fall back to the database. This is a lot of ugly code, and is slow.
- All data in the database is read into memory at startup. This is fast and simple.
This PR bounds the amount of data we will have to read at startup in order to make the …

Delete consensus data from tables when it is no longer needed

---

crates/sui-data-ingestion/src/workers/kv_store.rs

skips items over the DDB limit
already applied to existing kv pipeline
---

[data ingestion] kv store: skip items over the DDB limit

---

consensus/core/src/commit_syncer.rs
consensus/core/src/network/tonic_network.rs

- Avoid busy looping in commit sync, when failing to fetch from every peer.
- Make the error to serve connections debug, because the issue is on the requestor's side.
CI
---

[Consensus] minor fixes

---

Cargo.lock
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-indexer/Cargo.toml
crates/sui-indexer/README.md
crates/sui-indexer/src/config.rs
crates/sui-indexer/src/db.rs
crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Modify `PruningOptions` to point to a toml file that must specify `epochs_to_keep` and an optional `[overrides]` portion of per-table overrides. 
pruner.rs file will define prunable tables. the toml file when parsed into Rust config will warn if it tries to name any variants not supported by indexer code. additionally, there's also a check to make sure that prunable tables actually exist in the db
Part of a stack of PRs for watermarks
1. simplify setting up test indexer: https://github.com/MystenLabs/sui/pull/19663
2. update pruner config: https://github.com/MystenLabs/sui/pull/19637
3. committer writes upper bounds https://github.com/MystenLabs/sui/pull/19649
4. pruner writes lower bounds: https://github.com/MystenLabs/sui/pull/19650
5. pruner prunes (wip)
How did you test the new or …

[indexer][watermarks][1/n] Modify PruningOptions to point to a toml file of epochs_to_keep and optional per-table overrides

---

Cargo.lock
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-indexer/Cargo.toml
crates/sui-indexer/README.md
crates/sui-indexer/migrations/pg/2024-09-12-213234_watermarks/down.sql
crates/sui-indexer/migrations/pg/2024-09-12-213234_watermarks/up.sql
crates/sui-indexer/src/config.rs
crates/sui-indexer/src/db.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/handlers/objects_snapshot_handler.rs
crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/models/mod.rs
crates/sui-indexer/src/models/watermarks.rs
crates/sui-indexer/src/schema.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Adds `watermarks` table, and has committer writing upper bounds to it.
The committer works on the checkpoints level, so to simplify what it needs to do, we can have the committer call `store.update_watermarks_upper_bound()` once when it completes its batch of work. The upper bound update function relies on `PrunableTable` to tell it which of epoch, cp, or tx should be used to update the upper bound.
Part of a stack of PRs for watermarks
1. simplify setting up test indexer: https://github.com/MystenLabs/sui/pull/19663
2. update pruner config: https://github.com/MystenLabs/sui/pull/19637
3. committer writes upper bounds https://github.com/MystenLabs/sui/pull/19649
4. pruner writes lower bounds: https://github.com/MystenLabs/sui/pull/19650
5. pruner prunes (wip)
How did you test the new or …

[indexer][watermarks][2/n] committer writes upper bounds to watermarks table

---

consensus/core/src/authority_node.rs
consensus/core/src/block_manager.rs
consensus/core/src/block_verifier.rs
consensus/core/src/core.rs
consensus/core/src/metrics.rs
consensus/core/src/subscriber.rs
crates/sui-protocol-config/src/lib.rs

This is the second part of Garbage Collection which implements the following ticked next steps as outlined on the previous PR
Next steps:
CI/PT
---

[Consensus] Garbage Collection - 2

---

crates/sui-faucet/src/faucet/simple_faucet.rs
crates/sui-faucet/src/metrics.rs

Added a balance metric for alerting when we need to top it up.
Manual checks vs dashboard and `sui client balance`
```
➜  ~ sui client balance
╭────────────────────────────────────────╮
│ Balance of coins owned by this address │
├────────────────────────────────────────┤
│ ╭──────────────────────────────────╮   │
│ │ coin  balance (raw)  balance     │   │
│ ├──────────────────────────────────┤   │
│ │ Sui   1959956440480  1.95K SUI   │   │
│ ╰──────────────────────────────────╯   │
╰────────────────────────────────────────╯
➜  ~ 
```
--- …

[Faucet] Add balance metric

---

crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/metrics.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

Add missing metrics and logs for latency on objects version and objects version chunks. Also standardized some of the function names (object versions -> objects version).
Ran local indexer against mainnet remote store.
---

indexer: latency metrics for objects version

---

docker/sui-graphql-rpc-staging/Dockerfile
docker/sui-graphql-rpc-staging/build.sh

Create GraphQl staging build for `ci` and `devnet` environments.
See https://linear.app/mysten-labs/issue/DVX-329/devnet-and-ci-graphql-built-with-staging-feature-enabled for details
Will be testing this after it lands

Create GraphQl staging build for `ci` and `devnet` environments

---

Cargo.lock
crates/sui-indexer/Cargo.toml
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/types.rs
crates/sui-indexer/tests/ingestion_tests.rs

- fixed a bug that caused mainnet indexer to stop, also got reported in https://github.com/MystenLabs/sui/issues/19542, specifically here when tx has many input objects / affected objects / recipients / affected addresses etc. the expanded query will exceed the PG parameter limit of 65535
- also added ingestion tests for big tx indices & event indices and better error tracing
added ingestion tests for tx and event indices
---

indexer fix: chunk to avoid PG parameter limit

---

consensus/core/src/authority_node.rs
consensus/core/src/commit.rs
consensus/core/src/commit_consumer.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/linearizer.rs
consensus/core/src/test_dag_builder.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/consensus_handler.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-core/src/consensus_types/consensus_output_api.rs
crates/sui-core/src/consensus_types/mod.rs
crates/sui-core/src/consensus_validator.rs
crates/sui-core/src/scoring_decision.rs
crates/sui-core/src/transaction_manager.rs
crates/sui-core/src/unit_tests/consensus_tests.rs
crates/sui-json-rpc/src/error.rs
crates/sui-transaction-checks/src/deny.rs
crates/sui-types/src/error.rs

- Add support to execute certified transactions from consensus output.
- Refactor how consensus commit handler processes blocks from consensus commits, so the logic can be reused for consensus transaction handler.
- Small refactors in CommitConsumer and DagState.
CI
---

[Fastpath] execute transactions certified via fastpath

---

.github/workflows/rust.yml

`test-extra` finishes much earlier than `test`, so moving graphql test to `test-extra`.
CI
---

[CI] rebalance tests

---

crates/sui-graphql-e2e-tests/tests/stable/epoch/pagination.exp
crates/sui-graphql-e2e-tests/tests/stable/epoch/pagination.move
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap

Implementation of paginated query for epochs in GraphQL
Added a pagination.move test under the sui-graphql-e2e-tests crate.
---
Added support for paginated queries for epochs. This allows users to fetch epochs data in a paginated format.

[graphql] add query epochs functionality

---

crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/tests/ingestion_tests.rs

commit more eagerly, prev we only commit either filling the whole batch, or drained the un-processed, or at end of epoch, this pr changes it to commit more eagerly.
I was looking at average indexer extra data lag: it's about 2s from download to commit 
https://metrics.sui.io/goto/mj7m62zHg?orgId=1
however commit latency itself is about 1.7s and index is all in mem and very fast
https://metrics.sui.io/goto/W2FGehkHg?orgId=1
indexer ingestion test, also added one for end of epoch ingestion.
--- …

indexer ingestion: more eager commit

---

crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/types.rs
crates/sui-indexer/tests/ingestion_tests.rs

- before this pr, deletion futures wait for mutation futures, this pr makes it parallel
- also added object ingestion tests
object ingestion tests
---

indexer: execute objects mutation & deletion in parallel

---

crates/sui-indexer/src/store/pg_indexer_store.rs

https://mysten-labs.slack.com/archives/C0578KFD9D2/p1726765436840499
this will cut storage further down
objects snapshot ingestion test
---

indexer: exclude deleted/wrapped objects from snapshot

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/unit_tests/consensus_tests.rs

As part of the PR https://github.com/MystenLabs/sui/pull/18398 we are skip submitting checkpoint signatures when we have received verified checkpoints. Although this prevents the node from sending unnecessarily signatures, it's still possible to unnecessarily attempt to submit a signature tx after this has reached to consensus adapter. This PR is addressing that part.
CI/PT
---

[Consensus] abort submitting checkpoint sigs to consensus

---

crates/typed-store/src/rocks/mod.rs

Lz4 should be cheap enough to enable on level 1.
PT: looks like disk usage growth at the start is lower, while validator CPU usage doesn't seem to change.
---

[DB] remove min level to compress

---

crates/sui-graphql-e2e-tests/tests/stable/call/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/stable/consistency/dynamic_fields/immutable_dof.exp
crates/sui-graphql-e2e-tests/tests/stable/consistency/object_at_version.exp
crates/sui-graphql-e2e-tests/tests/stable/objects/wrap_unwrap.exp
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/consistency.rs
crates/sui-graphql-rpc/src/types/dynamic_field.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
crates/sui-indexer/migrations/pg/2024-10-08-025030_partial_index_instead/down.sql
crates/sui-indexer/migrations/pg/2024-10-08-025030_partial_index_instead/up.sql

we plan to remove deleted / wrapped objects from objects_snapshot, this prep pr is to make the consistency query no longer return deleted / wrapped objects as a whole, after the removal.
---

graphql: return live objects from consistent object query

---

crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
crates/sui-types/src/error.rs

E2e localnet tests appear to fail sporadically due the the `EpochEnded` error. Although it should not be the common case it's possible to happen when a transaction has reached a node's RPC endpoint, but epoch changes in the middle. In this case an `EpochEnded` can be thrown when trying to access the AuthorityEpochStore. Making the error retryable will allow the quorum driver retry the transaction and hopefully succeed.
CI
---

[AuthorityAggregator] EpochEnded to be retryable

---

crates/sui-graphql-e2e-tests/tests/stable/transaction_block_effects/events.exp
crates/sui-graphql-e2e-tests/tests/stable/transaction_block_effects/events.move
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/event/mod.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/transaction_block/mod.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap

Add the ability to fetch the transaction block that emitted the event.
New E2E tests:
```
sui$ cargo nextest run -p sui-graphql-rpc -- test_schema_sdl_export
sui$ cargo nextest run -p sui-graphql-rpc --features staging -- test_schema_sdl_export
```
- #19670 
- #19671 
- #19672 
---

graphql: Event.transactionBlock

---

crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/execution_cache/writeback_cache.rs

Individual object writes should log at TRACE

Reduce log verbosity for object writes

---

crates/sui-graphql-rpc/src/types/move_registry/named_type.rs
crates/sui-graphql-rpc/tests/move_registry_e2e.rs

Make sure named type queries go through the package resolver so `repr` has the correct type (not using latest).
---

[gql][mvr] Named typed queries go through the package resolver

---

crates/sui-core/src/execution_driver.rs

Previously, we could hit the panic here due to continually retrying a transaction from the previous epoch.

Do not continue transaction execution attempts after epoch has ended

---

consensus/core/src/storage/rocksdb_store.rs
crates/typed-store/src/rocks/mod.rs

- Switch to sst storage for `blocks` with large block size, to reduce disk footprint.
- Switch to universal compaction to reduce write amplifications due compaction.
PT: the changes shows no visible effect on performance of the network, with significant (~60%) reduction in `blocks` column family foot print.
---

[Consensus] improve compression and reduce compaction on `blocks` column family 

---

.changeset/hot-stingrays-press.md
crates/sui-graphql-e2e-tests/tests/stable/call/dynamic_fields.exp
crates/sui-graphql-e2e-tests/tests/stable/call/dynamic_fields.move
crates/sui-graphql-e2e-tests/tests/stable/consistency/dynamic_fields/immutable_dof.exp
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/consistency.rs
crates/sui-graphql-rpc/src/types/coin.rs
crates/sui-graphql-rpc/src/types/coin_metadata.rs
crates/sui-graphql-rpc/src/types/move_object.rs
crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-graphql-rpc/src/types/object.rs
crates/sui-graphql-rpc/src/types/stake.rs
crates/sui-graphql-rpc/src/types/suins_registration.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
sdk/graphql-transport/src/generated/queries.ts
sdk/graphql-transport/src/methods.ts
sdk/graphql-transport/src/queries/getDynamicFieldObject.graphql

Now that we no longer expose wrapped objects, we need a way to expose the addresses of object parents when they are other objects that have been wrapped.
Updated tests:
```
```
---

graphql: ObjectOwner::Parent exposed as Owner

---

crates/sui-core/src/authority.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-open-rpc/spec/openrpc.json

Temporarily re-enable `EventFilter::Any` as it is still in use in some places. This is a partial revert of #19617.
CI
---

subscriptions: reinstate EventFilter::Any

---

crates/sui-core/src/authority.rs
crates/sui-indexer/src/indexer_reader.rs
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-open-rpc/spec/openrpc.json

Temporarily re-enable `EventFilter::Any` as it is still in use in some places. This is a partial revert of #19617.
CI
---

pick(19807): subscriptions: reinstate EventFilter::Any

---

crates/suiop-cli/src/cli/ci/image.rs
crates/suiop-cli/src/cli/ci/mod.rs

as title,
1. with `--force`, we don't need to manually delete the k8s pod if we need to rebuild an image
2. `--image-target` or just `-t` can allow us build image from a multi-stage dockerfile
tested locally, works as expected. backend code already updated & redeployed as well
---

[suiop] add --force & image target to suiop image build

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/commit_syncer.rs
consensus/core/src/synchronizer.rs

This is fixing/improving the behaviour of the periodic synchronizer to:
(1) allow the backfilling of missing blocks when commit is lagging but we do have missing blocks that are in an tolerable threshold range from the current highest accepted round
(2) stop the periodic synchronizer when commit is lagging and missing blocks are too far in the future
Point (1) will allow bypassing a recently observed issue where equivocating blocks make their way into the DAG but they are not committed (due to the current commit rule this is not allowed). Then nodes that are using the commit syncer to catch up might come across blocks that appear on the fetched committed sub dags but do have ancestor dependencies on equivocated blocks that never got committed. Currently as the synchronizer is disabled …

[Consensus] Disable periodic synchronizer when commit is lagging and far missing blocks

---

crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

Spotted that MovePackage queries were still using `objects_history`, which is not going to work after that table gets pruned to two epochs.
This PR replaces queries to `objects_history` with queries to `full_objects_history`, with support from `objects_version` and `packages` to fetch the checkpoint sequence number where necessary.
```
```
And ran the following queries on the mainnet DB:
```graphql
query AllPackages($after: String) {
packages(first: 5 after: $after) {
pageInfo {
hasNextPage
endCursor
startCursor
}
nodes {
address
version
}
}
}
query AllPackagesBack($before: String) {
packages(last: 5 before: $before) {
pageInfo {
hasNextPage
endCursor
startCursor
}
nodes {
address
version
}
}
}
query SystemPackages($after: …
```

graphql: port MovePackage queries to full_objects_history

---

external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts
external-crates/move/crates/move-analyzer/trace-adapter/src/trace_utils.ts

This PR implements a more principled way to handle skipping instructions located on the same source code line for a smoother user experience. 
The main issue is handling call instructions, particularly if more than one of them is located on the same source code line. If not handled properly, the following effects could take place
- if a call instruction was preceded by another instruction on the same source code line, when executing `step` action, the user would have to click `step` button twice on the same line to actually step into the call making an impression that the debugger is somehow stuck (or at least stuttering)
- if more than one call instruction was on the same line, two things could happen:
- executing the `next` action would not skip over all calls but only over a single one …

[trace-view] Fixed skipping same line instructions

---

crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/transaction_block/mod.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
sdk/graphql-transport/src/mappers/transaction-block.ts
sdk/graphql-transport/test/compatability.test.ts

This PR modifies which data is serialized to bcs for `TransactionBlock` type. Instead of serializing to bcs `SenderSignedData`, which includes signatures and intent message, it only serializes the transaction data.
Existing tests
---

[GraphQL] Serialize bcs bytes of `TransactionData` instead of `SenderSignedData`

---

crates/sui-authority-aggregation/src/lib.rs
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/client/bridge_authority_aggregator.rs
crates/sui-bridge/src/client/bridge_client.rs
crates/sui-bridge/src/server/mock_handler.rs

Adds path to provide min timeout for sig aggregation with preference such that, when specified, we will wait at least `min_timeout` to collect as many sigs as possible before ordering based on the provided preference.
Note that the const min timeout value provided here is for verifying functionality for now, and should ideally be replaced with something like P95 latency.
Added unit test. Also ran on testnet node and observed that the client running this generated a certificate with 11 signatures, while other client generated a certificate with 28 signatures.
---
For each box you select, include information after the relevant heading that describes the impact of your changes …

[Bridge Node] Better optimize sig aggregation

---

crates/sui-rosetta/src/operations.rs
crates/sui-rosetta/tests/custom_coins/test_coin_no_symbol/Move.toml
crates/sui-rosetta/tests/custom_coins/test_coin_no_symbol/sources/test_coin.move
crates/sui-rosetta/tests/custom_coins/test_coin_utils.rs
crates/sui-rosetta/tests/custom_coins_tests.rs

This is a fix to disregard coin balance change response for coins with empty symbol.
Unit test
---

[Rosetta] - skip balance change response in rosetta if symbol is empty

---

crates/sui-graphql-rpc/src/types/move_package.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

Spotted that MovePackage queries were still using `objects_history`, which is not going to work after that table gets pruned to two epochs.
This PR replaces queries to `objects_history` with queries to `full_objects_history`, with support from `objects_version` and `packages` to fetch the checkpoint sequence number where necessary.
```
```
And ran the following queries on the mainnet DB:
```graphql
query AllPackages($after: String) {
packages(first: 5 after: $after) {
pageInfo {
hasNextPage
endCursor
startCursor
}
nodes {
address
version
}
}
}
query AllPackagesBack($before: String) {
packages(last: 5 before: $before) {
pageInfo {
hasNextPage
endCursor
startCursor
}
nodes {
address
version
}
}
}
query SystemPackages($after: …
```

pick(19817): graphql: port MovePackage queries to full_objects_history

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

The original limits on the object queue are set with 1s checkpoint interval. Having the oldest transaction on an object queued for 1s is almost tolerable. In hindsight it should be lower than the checkpoint interval to ensure healthy system. Now checkpoint interval is targeting 0.2s - 0.25s, so lowering the limits further to 0.2s, to ensure smooth checkpoint constructions.
CI
PT
Reading `num_rejected_cert_during_overload` metric from validators.
---

Lower per object queue age and length thresholds

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_63.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_63.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_63.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Bump to protocol version 63 
Has been running nightly in private-testnet and also running successfully in testnet https://metrics.sui.io/goto/KDyf-3kHR?orgId=1
---

[consensus] Enable distributed vote scoring in mainnet v63

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

Cherrypick to 1.35

---

consensus/core/src/base_committer.rs
consensus/core/src/dag_state.rs
consensus/core/src/leader_schedule.rs
consensus/core/src/leader_scoring.rs
consensus/core/src/linearizer.rs
consensus/core/src/test_dag_builder.rs

Currently we evict the cached ref entries in DagState whenever we `flush`. At this point we evict the entries for each authority by dropping all the blocks which are `<= evict_round`, where `evict_round = authority_latest_commit_round - CACHED_ROUNDS` . The `CACHED_ROUNDS` here allow us to keep around for a little longer committed blocks. Of course all the blocks that are `> evict_round` are kept.
This can work fine so far where we don't use GC , as we expect eventually to include blocks from other peers as weak links - no matter how far back they are - and that will move the `authority_latest_commit_round` and trigger the eviction of their blocks from our memory. Now with GC we don't have those guarantees. It is possible to get to a scenario where even a group of slow nodes that are …

[Consensus] DagState to evict blocks based on GC round

---

crates/typed-store/src/rocks/mod.rs

A followup to #19770. For cfs larger than 250GB, they need to be able to shard the files.
Applied the new setting to other large cfs (transactions, effects) on fullnodes.
---

[db] allow putting larger layer in higher levels

---

external-crates/move/crates/move-docgen/src/docgen.rs
external-crates/move/crates/move-docgen/tests/sources/const_string_test.move
external-crates/move/crates/move-docgen/tests/sources/const_string_test.spec_inline.md
external-crates/move/crates/move-docgen/tests/sources/const_string_test.spec_inline_no_fold.md
external-crates/move/crates/move-docgen/tests/sources/const_string_test.spec_separate.md
external-crates/move/crates/move-model/src/builder/model_builder.rs
external-crates/move/crates/move-model/src/builder/module_builder.rs
external-crates/move/crates/move-model/src/model.rs

This updates how constants annotated with `#[error]` are rendered in docgen. This also adds the `#[error]` annotation on them in the generated documentation.
Note that we don't try to render all bytearrays as strings, but only constants with the `#[error]` annotation to avoid rendering normal bytearrays strings. 
Added a test to make sure we render error-annotated consts as we expect.

[move][docgen] Render string constants for error constants

---

crates/sui-benchmark/tests/simtest.rs

So that we can exercise cap factor is higher and lower than the gas budget.
Updating tests
---

Use more realistic cap factor in simtest

---

docs/content/guides/operator/updates.mdx

Add release info for sui-full-node doc
@ronny-mysten !

Add release info for sui-full-node doc

---

crates/sui-graphql-e2e-tests/tests/stable/epoch/epoch_start_to_end.exp
crates/sui-graphql-e2e-tests/tests/stable/epoch/epoch_start_to_end.move
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-graphql-rpc/tests/e2e_tests.rs
crates/sui-indexer/migrations/pg/2024-10-09-180628_add_network_total_transactions_to_epochs/down.sql
crates/sui-indexer/migrations/pg/2024-10-09-180628_add_network_total_transactions_to_epochs/up.sql
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/models/epoch.rs
crates/sui-indexer/src/schema.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/pg_indexer_store.rs
crates/sui-indexer/src/store/pg_partition_manager.rs
crates/sui-indexer/src/types.rs

The `epoch_total_transactions` field on `epochs` table is calculated today from `checkpoints.network_total_transactions`, which is not ideal since the latter is prunable and `epochs` will not be pruned for the foreseeable future. To remove this dependency, we add `first_tx_sequence_number` to the `epochs` table at epoch boundary. That is, the network total transaction count from the final checkpoint of the epoch becomes the first tx sequence number of the new epoch. This also means that at epoch boundary, the current-to-be-previous epoch's `epoch_total_transactions` is derived from the checkpoint's network total transactions - the epoch's `first_tx_sequence_number`. Consequently, this will also help in the pruner implementation, as given an epoch we'd like to know the corresponding cp and …

[indexer][writer] Add first_tx_sequence_number to epochs table to decouple from checkpoints table

---

external-crates/move/crates/module-generation/src/generator.rs
external-crates/move/crates/move-compiler/src/to_bytecode/translate.rs
external-crates/move/crates/move-ir-to-bytecode-syntax/src/syntax.rs
external-crates/move/crates/move-ir-to-bytecode/src/compiler.rs
external-crates/move/crates/move-ir-types/src/ast.rs

Plumbs in source locations for `Type`s in the Move IR. This will be useful for adding return types to the Move source maps. 
Make sure existing types pass. 
---

[move][ir-to-bytecode] Add source locations to `Type` in the Move IR

---

consensus/core/src/commit_consumer.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs

Currently if someone recovers their node within epoch `R` with a snapshot that's from epoch `< R-1` , consensus will not start in amnesia recovery mode in epoch R as the boot counter will have already been incremented as node is trying to catch up from earlier epochs. This is problematic as it defies the whole point of the automatic amnesia recovery.
Instead on this PR we track consensus participation activity from earlier epochs/run and only then we increment the boot counter. Otherwise we keep the boot counter to `0` so we effectively enforce amnesia recovery until we get to an epoch where the node is able to participate. In this case participate means "able to have performed at least one commit".
CI/PT
--- …

[Consensus] fix amnesia recovery boot run

---

crates/sui-types/Cargo.toml
external-crates/move/crates/move-vm-integration-tests/Cargo.toml
external-crates/move/crates/move-vm-profiler/src/lib.rs
external-crates/move/crates/move-vm-runtime/Cargo.toml
external-crates/move/crates/move-vm-runtime/src/interpreter.rs
external-crates/move/crates/move-vm-runtime/src/loader.rs
external-crates/move/crates/move-vm-runtime/src/tracing2/mod.rs
external-crates/move/crates/move-vm-runtime/src/tracing2/tracer.rs
external-crates/move/crates/move-vm-types/Cargo.toml
external-crates/move/crates/move-vm-types/src/values/values_impl.rs
external-crates/move/move-execution/v0/crates/move-vm-runtime/Cargo.toml
external-crates/move/move-execution/v1/crates/move-vm-runtime/Cargo.toml
external-crates/move/move-execution/v2/crates/move-vm-runtime/Cargo.toml
sui-execution/latest/sui-adapter/Cargo.toml
sui-execution/v0/sui-adapter/Cargo.toml
sui-execution/v1/sui-adapter/Cargo.toml
sui-execution/v2/sui-adapter/Cargo.toml

This cleans up the insertion points of the tracing in the VM. This does this by moving the calls out into macros, and gating them on a const that is redefined based on the feature flags enabled. 
Note that this still keeps the gas profiler profiler calls within these macros (but as far as the interpreter is concerned, they're gone), as the unification of the gas profiler with the trace format can be done later. 
NB: the `tracing.rs` file has not be touched aside from removing the feature flag and a couple clippy fixes. So even though it shows up as a big change to the file it is in fact very small..
This also removes the (now unused) `gas-profiler` feature flag from the `move-vm-types` crate. 
Make sure existing tests pass. 
---
Check each box that your changes affect. If none of the …

[move][tracing] Cleanup insertion points of tracer in the VM

---

external-crates/move/crates/move-bytecode-source-map/src/source_map.rs
external-crates/move/crates/move-ir-to-bytecode/src/compiler.rs

[move] add return locations to source map

---

crates/sui-config/src/p2p.rs

Followup to PR #19587.
As tested in first PR.
---

Enable signed Discovery messages by default

---

crates/sui-indexer/migrations/pg/2024-09-12-213234_watermarks/up.sql
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/models/watermarks.rs
crates/sui-indexer/src/schema.rs
crates/sui-indexer/src/store/indexer_store.rs
crates/sui-indexer/src/store/mod.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

With the committer writing upper bounds, the pruner can now read from watermarks and determine whether the lower bounds need to be updated. Pruner does this by spawning a separate task, without touching the extant pruning logic (so all things are as is.) It will ignore any entries from watermarks that do not correspond to a `PrunableTable` variant.
Part of a stack of PRs for watermarks
simplify setting up test indexer: https://github.com/MystenLabs/sui/pull/19663
update pruner config: https://github.com/MystenLabs/sui/pull/19637
committer writes upper bounds https://github.com/MystenLabs/sui/pull/19649
pruner writes lower bounds: https://github.com/MystenLabs/sui/pull/19650
pruner prunes (wip)
---
Check each box that your changes affect. If …

[indexer][watermarks][3/n] pruner updates watermarks lower bound

---

crates/sui-bridge-cli/src/main.rs
crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/client/bridge_authority_aggregator.rs
crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-bridge/src/e2e_tests/complex.rs
crates/sui-bridge/src/metrics.rs
crates/sui-bridge/src/monitor.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/utils.rs

so we can monitor this in a dashboard.
unit tests & test in production
---

[bridge] add responses metrics in bridge auth aggregator

---

crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs
crates/sui-node/src/lib.rs

Currently during reconfig, `CheckpointService` tasks, including `CheckpointBuilder` and `CheckpointAggregator`, are [notified to shut down](https://github.com/MystenLabs/sui/blob/b1540cdb2019f0501d2cd7f6dad208f65a66b6d2/crates/sui-node/src/lib.rs#L1551). But reconfig does not wait for them to finish shutting down. There can be a race between the reconfig loop proceeding to [drop the epoch db handle](https://github.com/MystenLabs/sui/blob/b1540cdb2019f0501d2cd7f6dad208f65a66b6d2/crates/sui-node/src/lib.rs#L1633), while `CheckpointBuilder` tries to [read from epoch db when creating a new checkpoint](https://github.com/MystenLabs/sui/blob/b1540cdb2019f0501d2cd7f6dad208f65a66b6d2/crates/sui-core/src/checkpoints/mod.rs#L1378). The race can result in panics.
CI
Simulation
---
Check each box …

[Checkpoint] wait for checkpoint service to stop during reconfig

---

external-crates/move/crates/move-core-types/src/annotated_extractor.rs
external-crates/move/crates/move-core-types/src/annotated_value.rs
external-crates/move/crates/move-core-types/src/annotated_visitor.rs
external-crates/move/crates/move-core-types/src/lib.rs
external-crates/move/crates/move-core-types/src/unit_tests/extractor_test.rs
external-crates/move/crates/move-core-types/src/unit_tests/mod.rs
external-crates/move/crates/move-core-types/src/unit_tests/visitor_test.rs

Introduce a visitor that can extract a value from some sub-structure, by using a path of `Element`s to find the sub-structure and then delegating to another visitor to deserialize it.
This can be used as a building block in other visitors. It will be used to replace existing logic to create GraphQL representations of Move Values, and also to expose functionality to extract sub-values in the GraphQL schema.
Paths work by either selecting some sub-structure (by field name, or offset), or filtering on that sub-structure's type (or variant name, if it is an enum variant). Offsets work for selecting elements of vectors, but also fields in structs and variants, this is to simplify the process of describing the location of a field in a positional struct/variant without leaking how its field …

move: extracting visitor

---

crates/sui-indexer/src/indexer_reader.rs

This PR fixes a bug where events queries in descending order without a cursor return no results 
---

[indexer] quick fix for events in descending order without cursor

---

Cargo.lock
Cargo.toml
crates/simulacrum/src/lib.rs
crates/sui-indexer/Cargo.toml
crates/sui-indexer/src/benchmark.rs
crates/sui-indexer/src/config.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/lib.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-synthetic-ingestion/Cargo.toml
crates/sui-synthetic-ingestion/src/benchmark.rs
crates/sui-synthetic-ingestion/src/lib.rs
crates/sui-synthetic-ingestion/src/synthetic_ingestion.rs
crates/sui-synthetic-ingestion/src/tps_tracker.rs
crates/sui-types/src/mock_checkpoint_builder.rs

This PR adds two things:
1. A synthetic workload generator for the indexer. It generates synthetic checkpoints and transactions which are written to the ingestion dir. Currently only transfer transactions are generated, but we could extend it later.
2. A benchmark framework that allows us to connect the synthetic ingestion with any indexer implementation. The indexer implementation will need to implement a wrapper for a trait type.
Added an e2e test.
---

[Indexer] Add synthetic ingestion and benchmark framework

---

crates/sui-bridge/src/client/bridge_authority_aggregator.rs
crates/sui-bridge/src/client/bridge_client.rs

In some cases, the client observes a finalized transaction before most bridge authorities. In such cases, today the code will return an error without retries, causing this validator to be skipped in terms of signature aggregation. If bridge validators are using slow ethereum fullnode providers, for example, this can be a large amount of the committee, resulting in failed signature aggregation attempts in some cases (due to not achieving quorum), or high gas costs in others (due to not getting fewer higher staked validator signatures).
The solution here is to add retry logic in the map function.
Will run on a testnet node and see what happens.
---
For each box you select, …

[Bridge] Retry on finalized transaction not observed

---

crates/sui-indexer/migrations/pg/2024-09-12-213234_watermarks/up.sql
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/handlers/objects_snapshot_handler.rs
crates/sui-indexer/src/models/watermarks.rs
crates/sui-indexer/src/schema.rs
crates/sui-indexer/src/store/pg_indexer_store.rs

Since watermarks table isn't being written to yet, modify the db schema to match alt-indexer. The changes are to rename entity -> pipeline, tx_hi_inclusive -> tx_hi, and pruner_hi_inclusive -> pruner_hi and make it a non-null column. This works out nicely for graphql, since the transactions query implementations expect a half-open interval. Also simplifies pruner logic, since it can write the `reader_lo` as `pruner_hi` after delay, and table pruners will delete between `[table_data, pruner_hi)`.
--- …

[indexer] align watermarks table schema in live indexer to alt indexer

---

crates/sui-bridge-indexer/src/config.rs
crates/sui-bridge-indexer/src/main.rs

[bridge] remove disable-eth

---

Cargo.lock
crates/sui-indexer-alt/Cargo.toml
crates/sui-indexer-alt/src/ingestion/client.rs
crates/sui-indexer-alt/src/ingestion/error.rs
crates/sui-indexer-alt/src/ingestion/local_client.rs
crates/sui-indexer-alt/src/ingestion/mod.rs
crates/sui-indexer-alt/src/ingestion/remote_client.rs
crates/sui-indexer-alt/src/ingestion/test_utils.rs

This PR adds an IngestionClientTrait that abstracts over checkpoint fetching.
The existing one is moved into RemoteIngestionClient.
Added a new one LocalIngestionClient to read from files.
The retry logic is kept in a top-level struct, which then calls into the traits. Each trait decides the type of error for various cases.
Added a test.
---

Add local ingestion client to indexer-alt

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

This is safe because the corresponding commit is now in a mainnet release. The assert prevents current full nodes from starting from epochs before random beacon was enabled.
---

Remove assert preventing disabling random beacon on mainnet/testnet

---

Cargo.lock
crates/sui-faucet/Cargo.toml
crates/sui-faucet/src/main.rs

This PR adds the faucet version metrics so that it can be displayed in Grafana.
---

[Faucet] Add faucet version metrics for Grafana

---

apps/wallet/src/background/connections/ContentScriptConnection.ts
apps/wallet/src/dapp-interface/WalletStandardInterface.ts

Currently, when disconnecting from any dapp, the internal connection of the wallet for the given origin is not reset, making the experience unpredictable and confusing (main UX confusion we've been facing on every single bug bash).
---

[wallet] Disconnect active origin on dapp-kit disconnect call

---

crates/sui-indexer/tests/json_rpc_tests.rs
crates/sui-indexer/tests/move_test_code/Move.toml
crates/sui-indexer/tests/move_test_code/sources/events.move

Add an e2e test that creates a package to emit events, and then execute a transaction to emit them. Then query indexer-backed rpc for expected behavior. 
---

[indexer] test events query forward and backward pagination using indexer backed rpc in cluster test

---

crates/sui-indexer/src/config.rs
crates/sui-indexer/src/db.rs
crates/sui-indexer/src/main.rs

This is useful when I need to manually run migrations. 
CI
---

[Indexer] Add --skip-migrations option to --reset-database

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/writeback_cache.rs

Found this crash after adding the delay failpoint seen in this PR. I don't quite understand why that exposed this crash.

Must not wait on notify_read_effects after epoch ends, on a transaction that might be reverted

---

crates/sui-core/src/jsonrpc_index.rs
crates/typed-store/src/rocks/mod.rs

Don't explicitly remove old jsonrpc index tables as well as remove a possible panic when reporting rocksdb metrics.
---

jsonrpc: don't explicitly remove old tables

---

crates/sui-data-ingestion-core/src/reader.rs
crates/sui-data-ingestion-core/src/tests.rs
crates/sui-indexer/src/benchmark.rs
crates/sui-indexer/src/config.rs
crates/sui-indexer/src/indexer.rs
crates/sui-synthetic-ingestion/src/benchmark.rs

Be able to save generated workload in a specified dir instead of temp dir.
This requires adding a flag to ask the reader to not gc files.
Run locally
---

[Indexer] Save workload in benchmark

---

examples/custom-indexer/rust/Cargo.toml
examples/custom-indexer/rust/local_reader.rs
examples/custom-indexer/rust/remote_reader.rs

The custom indexer example is broken:
```
error[E0195]: lifetime parameters or bounds on method `process_checkpoint` do not match the trait declaration
--> remote_reader.rs:14:14
|
14 |     async fn process_checkpoint(&self, checkpoint: CheckpointData) -> Result<()> {
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetimes do not match method in trait
```
This PR fixes it. 
```
cd examples/custom-indexer/rust
cargo run  --bin local_reader --release
cargo run  --bin remote_reader --release
```
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions …

examples: fix custom indexer

---

crates/sui-core/src/execution_cache/writeback_cache.rs

Fix crashes in execution_driver due to inability to execute transactions.
--------
We must hold the lock for the object entry while inserting to the
`object_by_id_cache`. Otherwise, a surprising bug can occur:
1. A thread executing TX1 can write object (O,1) to the dirty set and then pause.
2. TX2, which reads (O,1) can begin executing, because TransactionManager immediately
schedules transactions if their inputs are available. It does not matter that TX1
hasn't finished executing yet.
3. TX2 can write (O,2) to both the dirty set and the object_by_id_cache.
4. The thread executing TX1 can resume and write (O,1) to the object_by_id_cache.
Now, any subsequent attempt to get the latest version of O will return (O,1) instead of
(O,2).
This seems very unlikely, but it may be more likely under …

Fix possible (but probably rare) race condition

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/transaction_input_loader.rs
crates/sui-core/src/transaction_manager.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-single-node-benchmark/src/mock_storage.rs
crates/sui-transactional-test-runner/src/lib.rs
crates/sui-types/src/storage/mod.rs

Fix rare crash when a transaction executes after its shared object assignments have been deleted.
This is only possible if a second execution of the same tx starts concurrently, and the shared version assignments have been deleted as we are checking for object availability in TransactionManager

Fix rare crash when a transaction executes after its shared object assignments have been deleted.

---

external-crates/move/crates/move-analyzer/src/symbols.rs

What the title says (to make it easier to get timing feedback from the users).

[move-ide] Add debugging info about compilation/analysis times

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/shared_object_congestion_tracker.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/epoch/randomness.rs
crates/sui-core/src/unit_tests/congestion_control_tests.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs

"Allow overage" mode allows up to one tx per-object per-commit to exceed
congestion control limits, as long as the limit was not already exceeded.
Accumulated debts are applied to future commits.
Added tests
---

Add support for overages on congestion control limits, with accumulated debt tracking

---

crates/sui-move/src/build.rs

Depending on the platform, "write" function may fail if the full directory path does not exist. So we have to create it before.
According to this doc https://doc.rust-lang.org/std/fs/fn.write.html "write" function may fail if the full directory path does not exist. And it does on macOS with an error "No such file or directory (os error 2)". I added a create_dir_all call before, to create dir first.
build --generate-struct-layouts flag must work on all platforms. It did not work on macOS Sequoia
---

CLI generate-struct-layouts fix

---

crates/sui-core/src/execution_cache/writeback_cache.rs

Fix crashes in execution_driver due to inability to execute
transactions.
--------
We must hold the lock for the object entry while inserting to the
`object_by_id_cache`. Otherwise, a surprising bug can occur:
1. A thread executing TX1 can write object (O,1) to the dirty set and
then pause.
2. TX2, which reads (O,1) can begin executing, because
TransactionManager immediately
schedules transactions if their inputs are available. It does not matter
that TX1
hasn't finished executing yet.
3. TX2 can write (O,2) to both the dirty set and the object_by_id_cache.
4. The thread executing TX1 can resume and write (O,1) to the
object_by_id_cache.
Now, any subsequent attempt to get the latest version of O will return
(O,1) instead of
(O,2).
This seems very unlikely, but it may be more likely under …

[cherrypick] Fix possible (but probably rare) race condition (#19951)

---

crates/sui-core/src/execution_driver.rs

Don't even try to execute certs from prior epochs

Fix one more possible crash in execution_driver

---

crates/sui/src/client_commands.rs
crates/sui/src/client_ptb/ast.rs
crates/sui/src/client_ptb/parser.rs
crates/sui/src/client_ptb/ptb.rs
crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_commands.snap
crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_publish.snap
crates/sui/src/displays/dev_inspect.rs
crates/sui/src/displays/mod.rs
crates/sui/tests/cli_tests.rs

This PR adds a `dev-inspect` flag to all executing-related commands.
```
sui client split-coin --coin-id 0x167f03292b0689800a149b62d6ac2f5163e1dd4995964195c521e0f3ff46183a --count 2 --dev-inspect
Dev inspect completed, execution status: success
╭───────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Transaction Effects                                                                               │
├───────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Digest: EHA6riF3SUU7UCa6xi11yTs3pN8exdzhF8hoNfiTGFF6                                              │
│ Status: Success                                                                                   │
│ Executed Epoch: 1 …
```

[CLI] Add dev inspect to CLI

---

consensus/core/src/core.rs
consensus/core/src/metrics.rs
consensus/core/src/threshold_clock.rs

Add metric for the interval between propsals.
[private-testnet](https://metrics.sui.io/goto/UhZ-qDkNR?orgId=1)
---

[consensus] Update proposer metrics

---

external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/matching/inferred_int_complex.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/inferred_int_mut_ref_type.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/inferred_int_ref_type.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/inferred_int_subject.move

Preserve int subject annotation during match pattern typing
New tests pass
---

[move][move-2024][matching] Preserve int subject annotation during match pattern typing

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

If DKG has failed, we might accidentally construct two end of epoch checkpoints.

Fix logic for end-of-epoch checkpoint when dkg has failed

---

crates/sui-cluster-test/src/cluster.rs
crates/sui-graphql-rpc/src/test_infra/cluster.rs
crates/sui-indexer/src/config.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/handlers/objects_snapshot_handler.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-indexer/tests/ingestion_tests.rs
crates/sui/src/sui_commands.rs
crates/test-cluster/src/test_indexer_handle.rs

useful for benchmark so that we can replay the same traffic again and again wo DB ops
- ci to make sure it does not break other ingestion
- added an ingestion test for the new start and end functions
---

indexer: support force start and end checkpoints

---

crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/env/mod.rs
crates/suiop-cli/src/cli/incidents/notion.rs
crates/suiop-cli/src/cli/incidents/pd/mod.rs
crates/suiop-cli/src/cli/mod.rs
crates/suiop-cli/src/cli/slack/mod.rs
crates/suiop-cli/src/main.rs

Let users load pulumi ESC envs into their current shell by name. The user can supply an env name or select one from pulumi's listing.
```
suiop-cli [jkj/suiop-load-env●●] cargo run -- help  
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.49s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop help`
Usage: suiop <COMMAND>
Commands:
docker     
iam        
incidents  
pulumi     
service    
ci         
load-env   Load an environment from pulumi
help       Print this message or the help of the given subcommand(s)
Options:
-h, --help     Print help
-V, --version  Print version
```
```
suiop-cli [jkj/suiop-load-env●●] cargo run -- load-env --help
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.52s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop …
```

[suiop][env] add load-env subcommand

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_driver.rs
crates/sui-core/src/transaction_input_loader.rs
crates/sui-core/src/transaction_manager.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-single-node-benchmark/src/mock_storage.rs
crates/sui-transactional-test-runner/src/lib.rs
crates/sui-types/src/storage/mod.rs

- [cherrypick] Must not wait on notify_read_effects after epoch ends, on a transaction that might be reverted (#19934)
- [cherrypick] Fix rare crash when a transaction executes after its shared object assignments have been deleted. (#19949)
- [cherrypick] Fix one more possible crash in execution_driver (#19870)
- [cherrypick] Fix logic for end-of-epoch checkpoint when dkg has failed (#19976)

Cherry pick all recent crash fixes

---

external-crates/move/crates/move-compiler/src/expansion/ast.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/hlir/detect_dead_code.rs
external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/linters/unnecessary_conditional.rs
external-crates/move/crates/move-compiler/src/linters/unneeded_return.rs
external-crates/move/crates/move-compiler/src/naming/ast.rs
external-crates/move/crates/move-compiler/src/naming/resolve_use_funs.rs
external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/src/typing/ast.rs
external-crates/move/crates/move-compiler/src/typing/dependency_ordering.rs
external-crates/move/crates/move-compiler/src/typing/expand.rs
external-crates/move/crates/move-compiler/src/typing/infinite_instantiations.rs
external-crates/move/crates/move-compiler/src/typing/macro_expand.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/src/typing/visitor.rs
external-crates/move/crates/move-compiler/tests/move_2024/parser/labeled_control_exp_associativity_else_after_if_block.exp
external-crates/move/crates/move-compiler/tests/move_2024/parser/labeled_control_exp_associativity_typing_invalid.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/control_exp_associativity_else_after_if_block.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/control_exp_associativity_typing_invalid.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/if_no_else.exp
external-crates/move/crates/move-compiler/tests/move_check/typing/if_no_else.move

- Improve error message for if without an else
- Persisting through typing for lints
- New test
---

[move-compiler] Improve error message for if without else

---

Cargo.lock
crates/sui-transactional-test-runner/src/args.rs
crates/sui-transactional-test-runner/src/programmable_transaction_test_parser/parser.rs
crates/sui-transactional-test-runner/src/programmable_transaction_test_parser/token.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
crates/sui-types/src/lib.rs
crates/sui/src/client_ptb/ast.rs
crates/sui/src/client_ptb/builder.rs
crates/sui/src/client_ptb/parser.rs
external-crates/move/Cargo.lock
external-crates/move/crates/move-cli/src/sandbox/cli.rs
external-crates/move/crates/move-command-line-common/Cargo.toml
external-crates/move/crates/move-command-line-common/src/lib.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/shared/ide.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-model/src/model.rs
external-crates/move/crates/move-stdlib/src/lib.rs
external-crates/move/crates/move-transactional-test-runner/src/framework.rs
external-crates/move/crates/move-transactional-test-runner/src/tasks.rs
external-crates/move/crates/move-transactional-test-runner/src/vm_test_harness.rs

Removes parsing aliases from `move-command-line-common` and update to use the `move_core_types::parsing` directly. 
CI

[move] Remove parsing aliases from `move-command-line-common`

---

Cargo.lock
crates/sui-transactional-test-runner/src/args.rs
crates/sui-transactional-test-runner/src/programmable_transaction_test_parser/parser.rs
crates/sui-transactional-test-runner/src/programmable_transaction_test_parser/token.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
crates/sui-types/src/lib.rs
crates/sui/src/client_ptb/ast.rs
crates/sui/src/client_ptb/builder.rs
crates/sui/src/client_ptb/parser.rs
external-crates/move/Cargo.lock
external-crates/move/crates/move-cli/src/sandbox/cli.rs
external-crates/move/crates/move-command-line-common/Cargo.toml
external-crates/move/crates/move-command-line-common/src/lib.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/shared/ide.rs
external-crates/move/crates/move-compiler/src/shared/mod.rs
external-crates/move/crates/move-core-types/Cargo.toml
external-crates/move/crates/move-core-types/src/language_storage.rs
external-crates/move/crates/move-core-types/src/parsing/address.rs
external-crates/move/crates/move-core-types/src/parsing/parser.rs
external-crates/move/crates/move-core-types/src/unit_tests/parsing_test.rs
external-crates/move/crates/move-model/src/model.rs
external-crates/move/crates/move-stdlib/src/lib.rs
external-crates/move/crates/move-transactional-test-runner/src/framework.rs
external-crates/move/crates/move-transactional-test-runner/src/tasks.rs
external-crates/move/crates/move-transactional-test-runner/src/vm_test_harness.rs

Adds additional tests and fixes a couple small issues around type lists. Also removes the `num_bigint` usage and instead uses `num::bigint` (which are the same as far as I am aware). This will get moved to a u256 in a PR above this. 
New tests + CI

[move] Add additional tests for parsing

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs

Add separate congestion control budget limit for randomness tx

---

crates/sui-replay/src/replay.rs

This allows the Sui replay tool to replay transaction's using a local version of the framework. This can be done by passing the protocol override version to use as  `-1` -- so `replay -tx <tx_digest> -p -1` 
Local/manual testing

[replay] Allow local override of framework

---

crates/sui-deepbook-indexer/src/server.rs

Multi pool query for volume
Comma separated format: /get_24hr_volume/0xe05dafb5133bcffb8d59f4e12465dc0e9faeaa05e3e342a08fe135800e3e4407,0xb663828d6217467c8a1838a03793da896cbe745b150ebd57d82f814ca579fc22
Sample output:
{"0xe05dafb5133bcffb8d59f4e12465dc0e9faeaa05e3e342a08fe135800e3e4407":497804600000000,"0xb663828d6217467c8a1838a03793da896cbe745b150ebd57d82f814ca579fc22":8989430000000}
Tested locally

Multi pool query 24hr endpoint

---

crates/sui-indexer-alt/src/ingestion/broadcaster.rs
crates/sui-indexer-alt/src/ingestion/mod.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/metrics.rs
crates/sui-indexer-alt/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/pipeline/concurrent/watermark.rs
crates/sui-indexer-alt/src/pipeline/mod.rs
crates/sui-indexer-alt/src/pipeline/processor.rs

This PR primarily adds support for concurrent writes, but it also includes (in separate commits) some docs and comment fixes, and a bug fix for early termination of the watermark task which was detected while building out the concurrent write support.
The early termination issue was easiest to reproduce by running a single pipeline that ended with a large number of empty checkpoints, eg. `ev_struct_inst` up to checkpoint 5000. Without this change, it would drop the last 100 or so (empty) checkpoints, and with it, it will reliably update the watermark to 5000 before exiting:
```
--remote-store-url …
```

indexer-alt: concurrent writes

---

crates/sui-move/src/main.rs

Use `default_value_if` to instead of using the same alias, and avoid to have panic in debug build.
Fix #20003 
Reuse existing test cases
---

sui-move: drop duplicate `--path` options

---

external-crates/move/crates/move-analyzer/src/analyzer.rs
external-crates/move/crates/move-analyzer/src/completions/mod.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs

This PR implements an optimization to the symbolication algorithm that avoids analyzing dependencies if they have not changed. Previously we were avoiding re-compiling unchanged dependencies but we were still analyzing them which introduces unnecessary overhead.
The implementation involved separating analysis of the main program and the dependencies, and merging the results of the two together in the end (whether the dependencies are computed fresh or obtained from the cache). In particular, we now create two analysis visitors per analysis phase, one for the main program and one for the dependencies.
For a simple package with Sui framework as a dependency we observe a significant reduction in analysis time.
Before:
After:
All existing test must pass. I also tested manually to verify that …

[move-ide] Avoid analyzing unmodified dependencies

---

external-crates/move/crates/move-compiler/src/cfgir/visitor.rs
external-crates/move/crates/move-compiler/src/linters/abort_constant.rs
external-crates/move/crates/move-compiler/src/linters/constant_naming.rs
external-crates/move/crates/move-compiler/src/linters/loop_without_exit.rs
external-crates/move/crates/move-compiler/src/linters/meaningless_math_operation.rs
external-crates/move/crates/move-compiler/src/linters/redundant_ref_deref.rs
external-crates/move/crates/move-compiler/src/linters/self_assignment.rs
external-crates/move/crates/move-compiler/src/linters/unnecessary_conditional.rs
external-crates/move/crates/move-compiler/src/linters/unnecessary_unit.rs
external-crates/move/crates/move-compiler/src/linters/unnecessary_while_loop.rs
external-crates/move/crates/move-compiler/src/linters/unneeded_return.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/coin_field.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/collection_equality.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/freeze_wrapped.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/freezing_capability.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/missing_key.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/public_mut_tx_context.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/public_random.rs
external-crates/move/crates/move-compiler/src/typing/visitor.rs
external-crates/move/crates/move-compiler/tests/sui_mode/linter/coin_field.exp

- Add a macro for the simple visitor declarations 
- Updated one test 
---

[move-compiler] Add macro for "simple" visitors 

---

external-crates/move/move-execution/v0/crates/move-vm-runtime/src/interpreter.rs
external-crates/move/move-execution/v1/crates/move-vm-runtime/src/interpreter.rs
external-crates/move/move-execution/v2/crates/move-vm-runtime/src/interpreter.rs

`cargo xclippy` has `--all-features` enabled. Seeing these warnings:
```
warning: unused import: `move_vm_profiler::GasProfiler`
--> external-crates/move/move-execution/v2/crates/move-vm-runtime/src/interpreter.rs:23:5
|
23 | use move_vm_profiler::GasProfiler;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `move_vm_profiler::GasProfiler`
--> external-crates/move/move-execution/v1/crates/move-vm-runtime/src/interpreter.rs:23:5
|
23 | use move_vm_profiler::GasProfiler;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `move_vm_profiler::GasProfiler`
--> external-crates/move/move-execution/v0/crates/move-vm-runtime/src/interpreter.rs:24:5
|
24 | use …
```

Fix lint with `cargo xclippy`

---

crates/sui-deepbook-indexer/src/server.rs

Historical volume query given start and end time in UNIX ms
Format: /get_historical_volume/:pool_ids/:start_time/:end_time
Sample Call: /get_historical_volume/0xe05dafb5133bcffb8d59f4e12465dc0e9faeaa05e3e342a08fe135800e3e4407,0xb663828d6217467c8a1838a03793da896cbe745b150ebd57d82f814ca579fc22/1729948782000/1730148782000
Sample Response:
{"0xb663828d6217467c8a1838a03793da896cbe745b150ebd57d82f814ca579fc22":38570720000000,"0xe05dafb5133bcffb8d59f4e12465dc0e9faeaa05e3e342a08fe135800e3e4407":1664402700000000}
Tested by running indexer locally …

Historical Volume Query (Deepbook)

---

crates/sui-indexer-alt/migrations/2024-10-16-002409_tx_affected_objects/up.sql
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/pipeline/concurrent/watermark.rs

Pulling out a couple of doc comment changes that I noticed while working on larger changes.
:eyes:
- #20050
---

easy(indexer-alt): assorted docs changes

---

crates/sui-indexer-alt/migrations/2024-10-16-002409_tx_affected_objects/up.sql
crates/sui-indexer-alt/src/models/watermarks.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/pipeline/concurrent/watermark.rs
crates/sui-indexer-alt/src/pipeline/mod.rs

Fix a quirk of the watermark update logic in the concurrent pipeline, where we would never issue an update for just the genesis checkpoint.
This fix was identified while working on the sequential pipeline where watermark updates and row updates are coupled and we therefore cannot afford to ignore the first checkpoint (doing so would cause it to drop all the rows from the first checkpoint as well).
Run the indexer on just one checkpoint:
```
--remote-store-url https://checkpoints.mainnet.sui.io                          \
--last-checkpoint 1
```
It will write a watermark.
- #20050 
- #20051 
---
Check each box that your changes …

fix(indexer-alt): watermark update off-by-one

---

crates/sui-indexer-alt/migrations/2024-10-27-150938_sum_obj_types/down.sql
crates/sui-indexer-alt/migrations/2024-10-27-150938_sum_obj_types/up.sql
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/sum_obj_types.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/schema.rs

The `sum_obj_types` sequential pipeline is the `sui-indexer-alt` equivalent of `objects` and `objects_snapshot`. It is a `sum`-mary of the object owner and type information as of a particular checkpoint (its watermark).
It differs from `objects` and `objects_snapshot` in the following ways:
- It only contains owner and type information (no coin balance, content, digest, or dynamic field information), but has a more "complete" set of indices for this data.
- The type information has been standardised into the same style as used by event indices.
- It uses the painter's algorithm to avoid processing redundant object updates (process transactions in a checkpoint in reverse order).
- Updates to the underlying table are atomic (all writes are sent out within a single transaction, along with a …

indexer-alt: sum_obj_types pipeline

---

crates/sui-indexer-alt/migrations/2024-10-27-150938_sum_obj_types/down.sql
crates/sui-indexer-alt/migrations/2024-10-27-150938_sum_obj_types/up.sql
crates/sui-indexer-alt/src/handlers/ev_emit_mod.rs
crates/sui-indexer-alt/src/handlers/ev_struct_inst.rs
crates/sui-indexer-alt/src/handlers/kv_objects.rs
crates/sui-indexer-alt/src/handlers/kv_transactions.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/sum_obj_types.rs
crates/sui-indexer-alt/src/handlers/tx_affected_objects.rs
crates/sui-indexer-alt/src/handlers/tx_balance_changes.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/pipeline/sequential/committer.rs
crates/sui-indexer-alt/src/pipeline/sequential/mod.rs
crates/sui-indexer-alt/src/schema.rs

Trying to make the purposes of various tuning parameters clearer by renaming them.
:eyes:
- #20050 
- #20051 
- #20052 
- #20053 
- #20054 
---

easy(indexer-alt): clarify names of tuning parameters

---

crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_68.snap

- Changes congestion control mode to use gas budget with cap.
- Sets a separate (lower) limit for randomness-using tx.
- Allows up to one tx per-commit per-object to exceed the budget, with accumulated debt tracking.
- Adds absolute capped cost at a multiple of per-commit budget.
Unit tests & simtests in PRs adding these `ProtocolConfig` parameters.
---

Enable gas-budget-based congestion control with overage & absolute cap

---

crates/sui-indexer-alt/migrations/2024-10-28-144002_sum_coin_balances/down.sql
crates/sui-indexer-alt/migrations/2024-10-28-144002_sum_coin_balances/up.sql
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/sum_coin_balances.rs
crates/sui-indexer-alt/src/handlers/sum_obj_types.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/schema.rs

Similar to `sum_obj_types` in that it is tracking the live object set,
but this index only covers coin objects owned by addresses, and it
orders them by balance, which allows queries to return them in
decreasing balance order.
Manually run the indexer on the first 100,000 checkpoints:
```
--remote-store-url https://checkpoints.mainnet.sui.io/                         \
--last-checkpoint 100000
```
- #20069 
- #20054 
- #20055 
--- …

indexer-alt: sum_coin_balances pipeline

---

crates/sui-deepbook-indexer/src/server.rs

Deepbook Indexer Manager Balance
Given balance_manager_id, returns the net deposit into the balance manager for each asset type.
Example call:
`/get_manager_balance/0x47dcbbc8561fe3d52198336855f0983878152a12524749e054357ac2e3573d58`
Example output:
`{"0xdba34672e30cb065b1f93e3ab55318768fd6fef66c15942c9f7cb846e2f900e7::usdc::USDC":10998046154370,"0xdeeb7a4662eec9f2f3def03fb937a663dddaa2e215b8078a284d026b7946c270::deep::DEEP":47870100000000,"0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN":33792,"0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI":241269580872061}`
---
For …

Deepbook Indexer Manager Balance

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_68.snap

Reduce minimum number of random beacon shares

---

external-crates/move/crates/move-vm-runtime/Cargo.toml
external-crates/move/crates/move-vm-runtime/src/lib.rs
external-crates/move/crates/move-vm-runtime/src/loader.rs
external-crates/move/crates/move-vm-runtime/src/tracing.rs

This unifies the old tracing under the `tracing` flag, and removes the `debugging` feature flag from the VM (one less feature flag 🎉). Otherwise behavior is kept the exact same.
Tested manually + CI
---

[move] Unify `debugging` and `tracing` feature flags for tracing in the VM

---

.changeset/dull-lobsters-punch.md
sdk/typescript/src/client/http-transport.ts
sdk/typescript/test/unit/client/http-transport.test.ts

This will be used by the new edge proxy for routing execute transaction requests to fullnodes with lower consensus latency
unit tests
---

add Client-Request-Method header to all TS SDK requests

---

crates/sui-config/src/node.rs

enables periodic compaction of individual SST files by default
---

[pruner] enable periodic compaction of individual SST files by default

---

crates/sui-e2e-tests/tests/rest/committee.rs
crates/sui-e2e-tests/tests/rest/main.rs
crates/sui-e2e-tests/tests/rest/objects.rs
crates/sui-e2e-tests/tests/rest/transactions.rs
crates/sui-rest-api/openapi/openapi.json
crates/sui-rest-api/proto/rest.proto
crates/sui-rest-api/src/checkpoints.rs
crates/sui-rest-api/src/client/mod.rs
crates/sui-rest-api/src/client/sdk.rs
crates/sui-rest-api/src/committee.rs
crates/sui-rest-api/src/lib.rs
crates/sui-rest-api/src/objects.rs
crates/sui-rest-api/src/proto/generated/sui.rest.rs
crates/sui-rest-api/src/proto/mod.rs
crates/sui-rest-api/src/transactions/execution.rs
crates/sui-rest-api/src/transactions/mod.rs
crates/sui-rest-api/src/transactions/resolve/mod.rs

rest: add support for protobuf to remaining endpoints that support a binary content type

---

crates/mysten-common/src/logging.rs
crates/mysten-metrics/src/lib.rs
crates/sui-core/src/authority.rs

Introduce a system invariant violation macro.
We can then set up alerts whenever the counter value changes.
Used it in one place as an example.
---

Add system_invariant_violation macro

---

crates/sui-benchmark/src/drivers/bench_driver.rs
crates/sui-benchmark/src/drivers/mod.rs
crates/sui-benchmark/src/lib.rs
crates/sui-benchmark/src/options.rs
crates/sui-benchmark/src/workloads/adversarial.rs
crates/sui-benchmark/src/workloads/batch_payment.rs
crates/sui-benchmark/src/workloads/delegation.rs
crates/sui-benchmark/src/workloads/expected_failure.rs
crates/sui-benchmark/src/workloads/mod.rs
crates/sui-benchmark/src/workloads/payload.rs
crates/sui-benchmark/src/workloads/randomness.rs
crates/sui-benchmark/src/workloads/shared_counter.rs
crates/sui-benchmark/src/workloads/shared_object_deletion.rs
crates/sui-benchmark/src/workloads/workload.rs
crates/sui-benchmark/src/workloads/workload_configuration.rs
crates/sui-benchmark/tests/simtest.rs

Introduce a new payload type into the benchmark tool - `ExpectedFailurePayload`. 
This payload type is configured with some expected failure type (currently only one implemented - user signature failure - but others can be added with minimal scaffolding) such that `payload.make_transaction()` generates a transaction that will fail in this manner.  Note that the failures that this payload type is concerned with are failures to execute the transaction itself, rather than during execution by the MoveVM. In other words, it is expected that the failure mode will not consume gas or produce effects.
Note that for this reason, its failure mode is inverted. It will be tallied for metrics purposes as an `error` if it succeeds and tallied as an `expected_error` (which is a success) if it fails. …

[sui-benchmark] Add expected failure payloads

---

crates/sui/src/keytool.rs

fix `sui keytool import` --alias command and default alias does not work
Before Fix：
After Fix：
- **--alias**
- **default alias**
---

[CLI] fix `sui keytool import` --alias command and default alias does not work

---

crates/sui-indexer-alt/migrations/2024-10-30-214852_wal_obj_types/down.sql
crates/sui-indexer-alt/migrations/2024-10-30-214852_wal_obj_types/up.sql
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/sum_coin_balances.rs
crates/sui-indexer-alt/src/handlers/sum_obj_types.rs
crates/sui-indexer-alt/src/handlers/wal_obj_types.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/schema.rs

Adds the concurrent pipeline that writes the write-ahead log for `sum_obj_types`. It re-uses the `process` implementation from `sum_obj_types` and then writes it into an append-only table.
Note that today:
- The pipelines are completely independent, which means the WAL pipeline redoes the processing work of the summary pipeline (this is presumably not an issue because the repeated work is not particularly heavy).
- This change does not include the pruning necessary to keep this table's size in check (in practice it should only be a couple of gigs in size). This will come in a follow-up PR.
Run the indexer and cross check the live-object set calculated from the write-ahead log with the summary:
``` …
```

indexer-alt: wal_obj_types pipeline

---

crates/sui-indexer-alt/migrations/2024-10-30-232206_wal_coin_balances/down.sql
crates/sui-indexer-alt/migrations/2024-10-30-232206_wal_coin_balances/up.sql
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/wal_coin_balances.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/schema.rs

`wal_coin_balances` is to `sum_coin_balances` what `wal_obj_types` is to `sum_obj_types`.
Run the indexer, and correlate the live object set calculated from the write-ahead log against the one that's already in the summary table:
```
indexer --remote-store-url https://checkpoints.mainnet.sui.io/                 \
--last-checkpoint 5000
```
```
sui_indexer_alt=# SELECT COUNT(*) FROM sum_coin_balances;
count
-------
178
(1 row)
sui_indexer_alt=# SELECT
COUNT(*)
FROM (
SELECT DISTINCT ON (object_id)
*
FROM
wal_coin_balances
ORDER BY
object_id,
object_version DESC
) o
WHERE
o.owner_id IS NOT NULL;
count
-------
178
(1 row)
```
- …

indexer-alt: wal_coin_balances pipeline

---

crates/sui-indexer-alt/src/pipeline/sequential/committer.rs

If the sequential pipeline committer can guarantee that it could process more checkpoints by looking at its pending buffer, we now reset the polling interval immediately, so it does not wait to issue the next write. This mimics a similar behaviour in the concurrent pipeline.
I made this change after noticing how the pipeline behaves when ingestion is stuck retrying a checkpoint, on my local machine. Usually when running locally, performance is limited by checkpoint download rate, but in a sequential pipeline, if a checkpoint failed to download, it is possible for many checkpoints to end up processed and pending.
With the previous implementation, once ingestion had recovered (the checkpoint is fetched), the pending buffer kept growing because it was only able to land `MAX_BATCH_CHECKPOINTS …

indexer-alt: allow sequential pipeline immediate reset

---

Cargo.lock
crates/sui-indexer-alt/Cargo.toml
crates/sui-indexer-alt/migrations/2024-10-16-225607_watermarks/up.sql
crates/sui-indexer-alt/src/metrics.rs
crates/sui-indexer-alt/src/models/watermarks.rs
crates/sui-indexer-alt/src/pipeline/concurrent/watermark.rs
crates/sui-indexer-alt/src/pipeline/mod.rs
crates/sui-indexer-alt/src/pipeline/processor.rs
crates/sui-indexer-alt/src/pipeline/sequential/committer.rs
crates/sui-indexer-alt/src/schema.rs

Track the timestamp associated with a watermark, include it in tracing messages, and introduce gauges to track the timestamps of the latest checkpoint gathered and written to the DB.
This change also introduces a couple of other timestamp/watermark related tracing improvements:
- Measure watermarks gathered and in DB for the sequential pipeline (previously just tracked the watermark after they were written to the DB). These will usually be the exact same, but may differ if the pipeline needs to retry a write.
- Gets rid of the ordering and equality impls for `CommitterWatermark` -- these are no longer required.
- Standardise the ordering of watermark traces between the sequential and concurrent pipelines, so that they are easier to compare with each other (they now share a common prefix). …

indexer-alt: watermark timestamps and other logging improvements

---

Cargo.lock
crates/sui-indexer-alt/Cargo.toml
crates/sui-indexer-alt/migrations/2024-10-16-225607_watermarks/up.sql
crates/sui-indexer-alt/migrations/2024-10-30-142219_obj_versions/down.sql
crates/sui-indexer-alt/migrations/2024-10-30-142219_obj_versions/up.sql
crates/sui-indexer-alt/migrations/2024-10-30-214852_wal_obj_types/down.sql
crates/sui-indexer-alt/migrations/2024-10-30-214852_wal_obj_types/up.sql
crates/sui-indexer-alt/migrations/2024-10-30-232206_wal_coin_balances/down.sql
crates/sui-indexer-alt/migrations/2024-10-30-232206_wal_coin_balances/up.sql
crates/sui-indexer-alt/src/args.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/obj_versions.rs
crates/sui-indexer-alt/src/handlers/sum_coin_balances.rs
crates/sui-indexer-alt/src/handlers/sum_obj_types.rs
crates/sui-indexer-alt/src/handlers/wal_coin_balances.rs
crates/sui-indexer-alt/src/handlers/wal_obj_types.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/metrics.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/models/watermarks.rs
crates/sui-indexer-alt/src/pipeline/concurrent/watermark.rs
crates/sui-indexer-alt/src/pipeline/mod.rs
crates/sui-indexer-alt/src/pipeline/processor.rs
crates/sui-indexer-alt/src/pipeline/sequential/committer.rs
crates/sui-indexer-alt/src/pipeline/sequential/mod.rs
crates/sui-indexer-alt/src/schema.rs

Add the ability to include an optional delay to sequential pipelines. This can be used to implement behaviour similar to `objects_snapshot` in the new architecture.
Sequential pipelines honour this configuration in their committer tasks:
- They process checkpoints at the same rate as other pipelines
- But hold back data in the committer's "pending" map until the committer witnesses a checkpoint that is at least `checkpoint_lag` checkpoints ahead.
This also requires slightly complicating the set-up and tear-down logic:
- When setting up, we may need to wait until the pending buffer has been primed enough to set a valid commit upperbound.
- If the pipeline runs dry before that point, we need to add an extra check to close down the committer.
- When tearing down the committer after its …

indexer-alt: delays for sequential pipelines

---

consensus/core/src/linearizer.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_68.snap
sdk/graphql-transport/src/methods.ts
sdk/graphql-transport/test/compatability.test.ts

[fastpath] add voting rounds and support env var override

---

crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-json/src/lib.rs
crates/sui-types/src/base_types.rs
crates/sui/src/client_ptb/builder.rs
crates/sui/tests/ptb_files/resolution/type_param_resolution.ptb
crates/sui/tests/snapshots/ptb_files_tests__type_param_resolution.ptb.snap

Fixes an issue where type layouts were not always returned for all primitive types, and simplifies the APIs around this a bit.
Added a repro test and made sure it passed.
---

[cli][ptb] Fix type resolution for primitive type instantiations in PTB CLI

---

crates/sui-kvstore/src/bigtable/client.rs
crates/sui-kvstore/src/lib.rs

added two APIs as reference examples: `get_latest_checkpoint` and `get_latest_object`
---

[kv store] bigtable: add support for reversed scans

---

Cargo.lock
crates/sui-bridge/Cargo.toml
crates/sui-bridge/src/metrics.rs
crates/sui-bridge/src/orchestrator.rs
crates/sui-bridge/src/types.rs
crates/sui-types/src/bridge.rs

[bridge] report last_observed_actions_seq_num metrics

---

crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/pipeline/concurrent/watermark.rs
crates/sui-indexer-alt/src/pipeline/mod.rs
crates/sui-indexer-alt/src/pipeline/sequential/committer.rs

The "first_checkpoint" option is a bit broken.
If first_checkpoint is larger than watermark + 1, for sequential pipeline this will simply lead to loss of liveness because it always expects watermark + 1 as the next checkpoint; for concurrent pipeline it will never be able to update watermark for a similar reason.
This PR adds a check when registering the pipeline to simply not allow that to happen.
If first_checkpoint is smaller than watermark + 1, the intention must be that we want to be able to backfill.
However the sequential pipeline will ignore any data that is below the watermark.
This PR fixes that by still allowing us to commit data even when they are below watermark.
CI.
Probably need to add tests too.
---
Check each box that your changes affect. If none of the boxes relate to …

[indexer-alt] Fix first_checkpoint option

---

crates/sui-core/src/safe_client.rs

safe_client_latency is the highest cardinality metric across our observability system due to the `address` label + being a histogram:
```
root@sui-node-mysten-rpc-0:/sui# curl -s localhost:9184/metrics | grep safe_client_latency_bucket | wc -l
8512
```
---

fix: remove high cardinality address label from safe_client_latency

---

crates/sui-deepbook-indexer/src/server.rs

Remove balance endpoint for Deepbook Indexer
Local indexer

Remove balance endpoint

---

crates/sui-indexer-alt/migrations/2024-10-31-174742_sum_displays/down.sql
crates/sui-indexer-alt/migrations/2024-10-31-174742_sum_displays/up.sql
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/sum_displays.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/displays.rs
crates/sui-indexer-alt/src/models/mod.rs
crates/sui-indexer-alt/src/schema.rs

Pipeline for indexing Display `VersionUpdated` events, so readers can render Display for Objects.
Run the indexer on the first ~1.6M checkpoints (the first display events happen around checkpoint 1.5M), and then inspect the database:
```
indexer --remote-store-url https://checkpoints.mainnet.sui.io                  \
--consistent-range 3600
```
```
sui_indexer_alt=# SELECT object_type, display_id FROM sum_displays LIMIT 10;
object_type                                                                                                               |                             display_id …
```

indexer-alt: sum_displays pipeline

---

crates/sui-indexer-alt/migrations/2024-10-19-113135_ev_indices/up.sql
crates/sui-indexer-alt/migrations/2024-10-31-174742_sum_displays/down.sql
crates/sui-indexer-alt/migrations/2024-10-31-174742_sum_displays/up.sql
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/sum_displays.rs
crates/sui-indexer-alt/src/ingestion/broadcaster.rs
crates/sui-indexer-alt/src/ingestion/client.rs
crates/sui-indexer-alt/src/ingestion/mod.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/displays.rs
crates/sui-indexer-alt/src/models/mod.rs
crates/sui-indexer-alt/src/schema.rs
crates/sui-indexer-alt/src/task.rs

A batch of clean-ups and refactorings that will help when implementing further pipelines (see stacked PRs):
- Expose the indexer's ingestion client and move the logic to repeatedly refetch a not found checkpoint into the client (from the ingestion service).
- Expose the indexer's DB connection pool.
- Allow the `graceful_shutdown` helper to return values (don't always expect the tasks will return `()`).
These changes are all in preparation for adding a "bootstrap" process to the indexer, where it waits until it can fetch the very first checkpoint in order to write out the chain identifier and initial protocol version, which will then be used to configure other pipelines.
- Make the `NOT NULL` constraints on event index columns explicit (as per an earlier PR comment).
CI
- #20118 
- #20132 …

refactor(indexer-alt): a variety of refactors

---

Cargo.lock
crates/sui-indexer-alt/Cargo.toml
crates/sui-indexer-alt/migrations/2024-10-19-113135_ev_indices/up.sql
crates/sui-indexer-alt/migrations/2024-10-31-174742_sum_displays/down.sql
crates/sui-indexer-alt/migrations/2024-10-31-174742_sum_displays/up.sql
crates/sui-indexer-alt/migrations/2024-11-01-182359_kv_genesis/down.sql
crates/sui-indexer-alt/migrations/2024-11-01-182359_kv_genesis/up.sql
crates/sui-indexer-alt/src/bootstrap.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/sum_displays.rs
crates/sui-indexer-alt/src/ingestion/broadcaster.rs
crates/sui-indexer-alt/src/ingestion/client.rs
crates/sui-indexer-alt/src/ingestion/mod.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/checkpoints.rs
crates/sui-indexer-alt/src/models/displays.rs
crates/sui-indexer-alt/src/models/mod.rs
crates/sui-indexer-alt/src/schema.rs
crates/sui-indexer-alt/src/task.rs

Index the chain identifier and initial protocol version in a `kv_genesis` table. This takes the place of chain identifier indexing and will also be used by indexers for protocol configs and feature flags, which need to know the initial protocol version to index and the chain identifier.
Run the indexer twice, and note from the tracing messages that the first time, the indexer is bootstrapped, and the second time it reads from the bootstrapped table.
- #20118 
- #20132 
- #20147
---

indexer-alt: index chain identifier

---

.changeset/curvy-walls-pull.md
sdk/deepbook-v3/src/client.ts
sdk/deepbook-v3/src/transactions/deepbook.ts

Get pool DEEP conversion in SDK
SDK on mainnet
Sample output: { asset_is_base: false, deep_per_quote: 28.613793980999997 }
This corresponds to the current DEEP price

Get pool DEEP conversion in SDK

---

crates/sui-json-rpc-api/src/lib.rs
crates/sui-json-rpc/src/lib.rs

adds `client-request-method` to allowed cors methods
---
---

add client-request-method to CORS allowed headers (#20160)

---

Cargo.lock
crates/sui-indexer-alt/Cargo.toml
crates/sui-indexer-alt/migrations/2024-10-19-113135_ev_indices/up.sql
crates/sui-indexer-alt/migrations/2024-10-31-000319_sum_packages/down.sql
crates/sui-indexer-alt/migrations/2024-10-31-000319_sum_packages/up.sql
crates/sui-indexer-alt/migrations/2024-10-31-174742_sum_displays/down.sql
crates/sui-indexer-alt/migrations/2024-10-31-174742_sum_displays/up.sql
crates/sui-indexer-alt/migrations/2024-11-01-182359_kv_genesis/down.sql
crates/sui-indexer-alt/migrations/2024-11-01-182359_kv_genesis/up.sql
crates/sui-indexer-alt/src/bootstrap.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/sum_displays.rs
crates/sui-indexer-alt/src/handlers/sum_packages.rs
crates/sui-indexer-alt/src/ingestion/broadcaster.rs
crates/sui-indexer-alt/src/ingestion/client.rs
crates/sui-indexer-alt/src/ingestion/mod.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/checkpoints.rs
crates/sui-indexer-alt/src/models/displays.rs
crates/sui-indexer-alt/src/models/mod.rs
crates/sui-indexer-alt/src/models/packages.rs
crates/sui-indexer-alt/src/schema.rs
crates/sui-indexer-alt/src/task.rs

Pipeline for writing out the set of latest packages. This is used to do type resolution during reads, and also to answer queries about package versions.
Originally, this was called `kv_packages`, but I realised that because of system packages, it is not append-only, so I renamed it to match the other summary tables.
Ran the indexer with the new pipeline on the first 1.2M checkpoints. This includes multiple system package upgrades and the first user package publish.
Inspect the contents of the table at that point:
```
indexer --remote-store-url https://checkpoints.mainnet.sui.io                  \
--last-checkpoint 1200000 …
```

indexer-alt: sum_packages pipeline

---

crates/sui-graphql-rpc/src/types/balance.rs
crates/sui-graphql-rpc/src/types/coin.rs

objects_snapshot no longer indexes wrapped or deleted objects. we added `object_status` to objects history, and modified all indexes to partial indexes. Coins and balances weren't picked up since they don't go through the same raw objects query path, so it was causing elevated query latencies.
Manually reran same graphql queries that were timing out. Also, estimated cost went from 3.5k down to 200.
---

need to add object_status=0 to use partial indexes

---

crates/sui-core/src/authority/shared_object_congestion_tracker.rs

Move verbose `SharedObjectCongestionTracker` log to `trace` level

---

crates/sui-core/src/consensus_manager/mysticeti_manager.rs

Enable amnesia recovery for mainnet
Tested in PT and public testnet. Things look good to go.
CI
---

[Consensus] enable amnesia recovery for mainnet

---

external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/src/shared/string_utils.rs
external-crates/move/crates/move-compiler/src/typing/core.rs
external-crates/move/crates/move-compiler/src/typing/expand.rs
external-crates/move/crates/move-compiler/src/typing/match_analysis.rs

This updates the debug flags to quiet down warnings during builds.
Local testing no longer emits warnings
---

[move] Update debugging flags in compiler to stop warnings during builds

---

sdk/docs/pages/typescript/transaction-building/basics.mdx

correct minor errors on TS SDK page: Transaction Building/ Sui Programmable Transaction Basics/ Pure values 
fix " you you can ..." -> "you can ..."
There seems to be a small mistake on the description in TS SDK/ Transaction Building/ Sui Programmable Transaction Basics/ Pure values:
Thus I created this PR to fix this error.

Fix a small syntax error in Sui Documentation, on TS SDK

---

Cargo.lock
external-crates/move/Cargo.lock
external-crates/move/crates/move-coverage/Cargo.toml
external-crates/move/crates/move-coverage/src/source_coverage.rs

Hardens source coverage gathering to be resilient to duplicate source spans from the compiler. (e.g., from macros and the like). 
Fixes issue #20075
Manually tested on a failing test case.

[move] Update source coverage gathering so we don't include any duplicate source spans

---

crates/sui-json-rpc/src/governance_api.rs
crates/sui-types/src/sui_system_state/mod.rs

Currently if the exchange rate for an epoch is not found, we would assign it the default exchange rate while we should've used the exchange rate from the previous existing epoch instead. This PR fixes that.
Added some unit tests.
---

[jsonrpc] fix estimated rewards during safe mode

---

.changeset/old-dolphins-tie.md
sdk/typescript/src/transactions/intents/CoinWithBalance.ts
sdk/typescript/test/e2e/coin-with-balance.test.ts
sdk/typescript/test/e2e/data/coin_metadata/sources/coin_metadata_zero.move

Change the `coinWithBalance` intent so that it creates a zero coin instead of splitting when amount is 0. This fixes the edge case where the user doesn't have a coin of required type in the wallet but the amount is 0 anyways, thus avoids throwing the `Not enough coins of type ${coinType} to satisfy requested balance` error in this situation 
cc @hayes-mysten 
Added e2e tests
---

ts sdk: coin-with-balance intent create zero coin on zero amount

---

consensus/core/src/core.rs

Refactoring Core to read the last proposed block from DagState rather than local cached value. This change:
* will allow for nodes that recover from amnesia (potentially) link their new proposed block the actual last proposed block instead of linking back to genesis. 
* because of the above point, we are also avoiding edge case error when an amnesia recovered node is attempting to propose for a round with exact quorum, although their last proposed block still pointing to genesis, practically making us (thankfully) hit the assert [here](https://github.com/MystenLabs/sui/blob/6a571f189b49f99ed9294cd01c82d56e03ef8bfe/consensus/core/src/core.rs#L759)
* our last proposed block is cached in DagState anyways so no practical difference
CI
---
Check each box that your changes affect. If none of …

[Consensus] Core to read last proposed round from DagState

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/traffic_controller/metrics.rs
crates/sui-core/src/traffic_controller/mod.rs
crates/sui-core/src/traffic_controller/policies.rs
crates/sui-e2e-tests/tests/traffic_control_tests.rs
crates/sui-json-rpc/src/axum_router.rs

* Add error categorization to the error metrics
* Added trace logging 
* Set invariant on x-forwarded-for header length vs associated node config setting
Ran on private testnet many times
---

[Traffic Control] Improved error metrics and benchmarking

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_69.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_69.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_68.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_69.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Fix for testnet compatibility test 

Add version 69 and move consensus voting round flag to 69

---

Cargo.lock
crates/sui-indexer-alt/Cargo.toml
crates/sui-indexer-alt/src/db.rs

Using `stringify!(DEFAULT...)` doesn't work, because it stringifies the constant name, not its contents. This change uses `const_str::format` to achieve what was originally intended.
Run the indexer without supplying a connection timeout. Before this change it would fail with a parse int error, because it tried to interpret the string `DEFAULT_CONNECTION_TIMEOUT_SECS` as an integer.
---

fix(indexer-alt): connection timeout default

---

crates/sui-indexer-alt/src/ingestion/broadcaster.rs
crates/sui-indexer-alt/src/ingestion/client.rs
crates/sui-indexer-alt/src/ingestion/local_client.rs
crates/sui-indexer-alt/src/metrics.rs

This metric will allow us to observe latest ingested checkpoint seq number. We could track its progress relative to other parts of the indexer.
---

[indexer-alt] Add indexer_latest_ingested_checkpoint metric

---

crates/sui-data-ingestion/src/main.rs
crates/sui-data-ingestion/src/progress_store.rs

adds timeouts to the Bigtable ingestion pipeline and introduces a backfill mode that skips most progress updates to DynamoDB during backfilling
---

[kv store] add timeout to bigtable ingestion + backfill mode

---

crates/sui-indexer-alt/src/ingestion/client.rs
crates/sui-indexer-alt/src/metrics.rs

This PR adds two metrics, one that tracks the ingestion lag on the latest fetched checkpoint, one that tracks histogram. These two combined could give us the full picture on the lag.
CI.
---

[indexer-alt] Add checkpoint ingestion lag metrics

---

crates/sui-types/src/lib.rs
external-crates/move/crates/move-compiler/src/cfgir/visitor.rs
external-crates/move/crates/move-compiler/src/expansion/ast.rs
external-crates/move/crates/move-compiler/src/hlir/ast.rs
external-crates/move/crates/move-compiler/src/naming/ast.rs
external-crates/move/crates/move-compiler/src/sui_mode/id_leak.rs
external-crates/move/crates/move-compiler/src/sui_mode/info.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/coin_field.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/collection_equality.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/custom_state_change.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/freeze_wrapped.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/freezing_capability.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/missing_key.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/mod.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/public_mut_tx_context.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/public_random.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/self_transfer.rs
external-crates/move/crates/move-compiler/src/sui_mode/linters/share_owned.rs
external-crates/move/crates/move-compiler/src/sui_mode/mod.rs
external-crates/move/crates/move-compiler/src/sui_mode/typing.rs
external-crates/move/crates/move-compiler/src/typing/ast.rs
external-crates/move/crates/move-compiler/tests/sui_mode/struct_with_key/key_struct_id_field_incorrect_struct_address.exp
external-crates/move/crates/move-compiler/tests/sui_mode/struct_with_key/key_struct_id_field_incorrect_struct_address.move
external-crates/move/crates/move-core-types/src/account_address.rs
external-crates/move/crates/move-core-types/src/parsing/address.rs

- Sui mode used only named addresses for type comparison. This is not sufficient for interface files that might be using only the numerical address.
- Switched `is` to use only the numerical address. We might want to evaluate differently if we start using it more outside of Sui mode
- Ran tests 
---

[move-compiler] Improve interactions with Sui mode and interface files

---

crates/sui-core/src/execution_cache/cache_types.rs
crates/sui-core/src/execution_cache/writeback_cache.rs

The previous version of this code was based on a misunderstanding of the
Moka Cache API. It assumed that:
let entry = cache.entry(k).or_insert_with(|| v);
entry.is_fresh()
could be used to detect whether there was a race with
cache.insert(k, v)
In fact this is not the case! Both threads must use `or_insert_with` in
order to handle the race correctly.
The bug is instantly reproducible with the following code:
use moka::sync::Cache;
use std::sync::{Arc, Mutex};
fn monotonic_update(cache: Arc<Cache<u64, Arc<Mutex<u64>>>>, key: u64, value: u64) {
let entry = cache
.entry(key)
.or_insert_with(|| Arc::new(Mutex::new(value)));
if !entry.is_fresh() {
let mut entry = entry.value().lock().unwrap();
// only update if the new value is greater than the current value
if value > *entry {
*entry = value; …

Fix bug with object_by_id inserts.

---

crates/sui-config/src/node.rs
crates/sui-core/src/transaction_manager.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

- Only check overload queues for mutable shared inputs
- Increase max tx queue age to 500ms
---

Fixes for overload protection

---

crates/sui-indexer-alt/migrations/2024-11-02-160143_kv_epochs/down.sql
crates/sui-indexer-alt/migrations/2024-11-02-160143_kv_epochs/up.sql
crates/sui-indexer-alt/src/bootstrap.rs
crates/sui-indexer-alt/src/handlers/kv_epoch_ends.rs
crates/sui-indexer-alt/src/handlers/kv_epoch_starts.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/epochs.rs
crates/sui-indexer-alt/src/schema.rs

Adds two tables and pipelines: `kv_epoch_starts` and `kv_epoch_ends`, to index epoch information. This pipeline is different from epoch indexing in `sui-indexer` in a number of ways:
- It is an append-only pipeline. The columns that are written at the start and end of the epoch are split into two separate tables that can be written to concurrently (by separate pipelines).
- The first row of `kv_epoch_starts` is written by the bootstrap process which seeds the `kv_genesis` table as well, this avoids having to condition on whether the checkpoint being processed is the genesis checkpoint in the main pipeline.
- Instead of indexing the number of transactions in the epoch, it tracks the transaction high watermark -- readers will need to read the records to calculate the number of total …

indexer-alt: epochs pipelines

---

crates/sui-indexer-alt/migrations/2024-10-16-225607_watermarks/up.sql
crates/sui-indexer-alt/src/args.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/metrics.rs
crates/sui-indexer-alt/src/models/watermarks.rs
crates/sui-indexer-alt/src/pipeline/concurrent/commit_watermark.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/pipeline/concurrent/reader_watermark.rs
crates/sui-indexer-alt/src/pipeline/mod.rs
crates/sui-indexer-alt/src/pipeline/sequential/mod.rs
crates/sui-indexer-alt/src/schema.rs

The reader watermark task is one half of the pruning implementation. It applies only to concurrent pipelines, and tracks the lowest checkpoint sequence number the reader is guaranteed to get data for, and the timestamp (from the DB), that this threshold was set at.
This task does not do any actual pruning, but it sets the limit that the pruner can go to, and a time at which it can start pruning to that point. A later PR will introduce the actual pruning task.
Unlike the existing pruner implementation, this system does not support pruning by epoch, only by checkpoint. This was for two reasons:
- Pruning no longer works by dropping partitions, so we can keep the implementation simple by only supporting the form of pruning we need (by checkpoint sequence number).
- Pruning is part of the …

indexer-alt: reader watermark task

---

crates/sui-indexer-alt/src/args.rs
crates/sui-indexer-alt/src/handlers/wal_coin_balances.rs
crates/sui-indexer-alt/src/handlers/wal_obj_types.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/metrics.rs
crates/sui-indexer-alt/src/models/watermarks.rs
crates/sui-indexer-alt/src/pipeline/concurrent/commit_watermark.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/pipeline/concurrent/pruner.rs
crates/sui-indexer-alt/src/pipeline/sequential/committer.rs

Add the task that actually deletes data, based on the reader low watermark.
Also (in a separate commit) fixes an issue where the "loud watermark update" logic was too chatty when the indexer was running faster than the network rate (i.e. during backfill).
Run the indexer and note the following:
- Metrics related to deleted rows by the pruner (from `localhost:9184/metrics`)
- The contents of the `watermarks` table.
```
indexer --remote-store-url https://checkpoints.mainnet.sui.io/                 \
--last-checkpoint 10000                                                        \
--consistent-range 100 …
```

indexer-alt: pruner task

---

external-crates/move/crates/move-unit-test/src/test_runner.rs

Make sure that if the `--trace-execution` flag is passed that the binary was compiled with the `tracing` feature flag set. 
CI
---

[move/tracing] Panic unit tests if tracing without being compiled with tracing support

---

external-crates/move/crates/move-analyzer/src/analysis/parsing_analysis.rs
external-crates/move/crates/move-compiler/src/expansion/ast.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/src/naming/ast.rs
external-crates/move/crates/move-compiler/src/naming/resolve_use_funs.rs
external-crates/move/crates/move-compiler/src/naming/translate.rs
external-crates/move/crates/move-compiler/src/parser/ast.rs
external-crates/move/crates/move-compiler/src/parser/syntax.rs
external-crates/move/crates/move-compiler/src/typing/macro_expand.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/dot_incomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/method_and_field_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/method_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/named_struct_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/named_struct_middle_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/on_dot_autocomplete.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/on_dot_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/on_dot_autocomplete.move
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/positional_struct_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/struct_method_invalid_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/type_param_no_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/use_fun_autocomplete.ide.exp
external-crates/move/crates/move-compiler/tests/move_check/ide_mode/named_struct_autocomplete.ide.exp

This PR fixes a certain problem with auto-completion on the `.` character. Previously, once a part of the access chain after the `.` was parsed, auto-completion information for the `.` character location was no longer generated. This is particularly problematic if someone expects auto-completion in the middle of the function code, for example:
```move
public struct SomeStruct has drop {
some_field: u64,
}
public fun foo(_param: SomeStruct) {}
public fun bar(): SomeStruct {
let val = SomeStruct{some_field: 42};
val.
SomeStruct {some_field: 42}
}
```
It is expected that auto-completion would work correctly after `val.` but previously it did not because this expression was actually parsed as `val.SomeStruct`. This PR fixes this:
Previously, auto-completion for the `.` location would also not …

[move-ide] Fixed auto-completion on the dot character

---

crates/sui-sdk/src/wallet_context.rs

This PR removes the SDK tracing warning on mismatch local + RPC API versions.
---

[RustSDK] Less noise when rpc version and local CLI version mismatch

---

crates/sui-json-rpc-types/src/sui_move.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-open-rpc/src/examples.rs

Adds enums to the `NormalizedMoveModule` for json-rpc.
This fixes #20205 
Tested manually on the repro provided in the issue to make sure enums are included in the output. 
---

[json-rpc] Add enums in `getNormalizedMoveModule`

---

crates/sui/src/sui_commands.rs

#20259 removed the warning for the SDK, so this PR adds it back for the CLI.
---

[CLI] Add back the warning about version mismatch

---

crates/sui-analytics-indexer/src/handlers/mod.rs
crates/sui-analytics-indexer/src/handlers/object_handler.rs
crates/sui-analytics-indexer/src/lib.rs

This PR adds a package filter for object handler in analytics for being able to generate an object table specifically for walrus in testnet.
Invoking with `--package-id-filter 0x9f992cc2430a1f442ca7a5ca7638169f5d5c00e0ebc3977a65e9ac6e497fe5ef --starting-checkpoint-seq-num 120132840` to filter for walrus specific objects. Here is the walrus package object:
https://testnet.suivision.xyz/package/0x9f992cc2430a1f442ca7a5ca7638169f5d5c00e0ebc3977a65e9ac6e497fe5ef

feat(analytics): Add package filter to object handler

---

crates/sui-core/src/execution_cache/cache_types.rs
crates/sui-core/src/execution_cache/writeback_cache.rs

pick writeback cache fix into next mainnet release

[cherrypick] PR#20236

---

crates/sui-indexer/src/benchmark.rs
crates/sui-indexer/src/config.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-indexer/tests/ingestion_tests.rs

introduce mvr-mode flag. If true, enables pruning objects_history, and toggles committer to write only a subset of tables to db. Compatible with the production indexer schema.
---

[mvr] Introduce mvr-mode on production indexer

---

crates/sui-indexer/src/benchmark.rs
crates/sui-indexer/src/config.rs
crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/handlers/committer.rs
crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/handlers/pruner.rs
crates/sui-indexer/src/indexer.rs
crates/sui-indexer/src/main.rs
crates/sui-indexer/src/test_utils.rs
crates/sui-indexer/tests/ingestion_tests.rs

introduce mvr-mode flag. If true, enables pruning objects_history, and toggles committer to write only a subset of tables to db. Compatible with the production indexer schema.
---
---
For each box you select, include information …

[mvr] Introduce mvr-mode on production indexer (#20271)

---

consensus/core/src/transaction.rs
crates/sui-core/src/mysticeti_adapter.rs

Following the work of https://github.com/MystenLabs/sui/pull/19572 , this PR is ensuring that a soft bundle will atomically be included in a consensus block. That:
1. Strengthens the guarantees around the soft bundle sequencing to allow them processed in exact sequence and not break in multiple blocks.
2. allow us to simply retry transactions of GC'ed blocks as we just retry all the transactions of softbundle
Kept the solution simple for now and if a soft bundle doesn't fit to a block then it's cached and is added to the next block.
CI
--- …

[Consensus] soft bundle to be included in a block atomically

---

external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs
external-crates/move/crates/move-compiler/src/shared/matching.rs
external-crates/move/crates/move-compiler/tests/move_2024/matching/generated_0.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/guard_invalid_copy.exp
external-crates/move/crates/move-compiler/tests/move_2024/matching/guard_invalid_copy.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/guard_wild.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/guard_wild_inexhaustive.exp
external-crates/move/crates/move-compiler/tests/move_2024/matching/guard_wild_inexhaustive.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/guard_wild_initial.move

Fix a bug, plus a bit of yak shaving: this removes the work queue from match compilation in favor of `growing_stack`, for the purpose of sanity. This refactor was actually sufficient (along with one small change) to eliminate the bug.
All tests still pass, plus the new ones.
---

[move][move-2024] Fix match bug, rework work queue from match for sanity

---

crates/sui-deepbook-indexer/src/models.rs
crates/sui-deepbook-indexer/src/server.rs

Historical volume by balance manager
**Endpoint 1:** `/get_historical_volume_by_balance_manager_id/:pool_ids/:balance_manager_id/:start_time/:end_time`
pool_ids delimited by ",", start_time and end_time in unix ts seconds
Response format:
`{pool_id_1: [maker_volume, taker_volume], pool_id_2: ...}
`
Example: `/get_historical_volume_by_balance_manager_id/0xb663828d6217467c8a1838a03793da896cbe745b150ebd57d82f814ca579fc22,0xe05dafb5133bcffb8d59f4e12465dc0e9faeaa05e3e342a08fe135800e3e4407/0x344c2734b1d211bd15212bfb7847c66a3b18803f3f5ab00f5ff6f87b6fe6d27d/1731260703/1731692703`
Response example:
`{"0xe05dafb5133bcffb8d59f4e12465dc0e9faeaa05e3e342a08fe135800e3e4407":[2036945300000000,17349400000000],"0xb663828d6217467c8a1838a03793da896cbe745b150ebd57d82f814ca579fc22":[14206210000000,3690000000]}` …

Historical volume by balance manager

---

external-crates/move/crates/move-analyzer/editors/code/CONTRIBUTING.md
external-crates/move/crates/move-analyzer/editors/code/README.md
external-crates/move/crates/move-analyzer/editors/code/package.json
external-crates/move/crates/move-analyzer/editors/code/src/configuration.ts
external-crates/move/crates/move-analyzer/editors/code/src/main.ts

This PR adds the ability to generate Move VM traces for tests from inside IDE. It also fixes a bug that would prevent IDE from picking up a custom Sui CLI path when building, running tests, and generating traces.
This PR also adds the ability to filter tests to be executed by test/trace commands
Tested manually that the new functionality works correctly

[move-ide] Added tracing command

---

.changeset/shiny-cups-sniff.md
sdk/zksend/src/links/get-sent-transactions.ts

Context: https://mysten-labs.slack.com/archives/C0701K5UHCP/p1732048923401389
We aren't passing through the Sui client instance to `loadAssets`, so it's defaulting to the public fullnode URL in Stashed which has heavier rate limits as opposed to our internal RPC.
---

[zksend SDK] fix getSentTransactions not respecting the passed in SuiClient URL

---

Cargo.lock
crates/suiop-cli/Cargo.toml
crates/suiop-cli/src/cli/lib/cache.rs
crates/suiop-cli/src/cli/lib/mod.rs
crates/suiop-cli/src/cli/service/logs.rs
crates/suiop-cli/src/cli/service/mod.rs
crates/suiop-cli/src/cli/slack/mod.rs
crates/suiop-cli/src/lib.rs
crates/suiop-cli/src/main.rs

allow log fetching via the k8s api.
- use pulumi esc for the kubeconfig
- use the local pulumi cwd + stack to determine the ns to query
- present the user with a list of pods to choose from, and also offer a quick link to namespace logs
- besides that, a bunch of extra this and that to make it all work, including caching the kubeconfig, stack-namespace mapping, and pulumi workspace file (indicates current stack). All cache usage expires after 1 day and uses a slower method (usually shelling out to pulumi) to refresh the cache on a miss.
--- …

[suiop] add service logs command

---

crates/sui-indexer/src/models/objects.rs

When requesting a package object
```sh
curl --location 'localhost:9124' \
--header 'content-type: application/json' \
--data '{
"id": 3,
"method": "sui_getObject",
"params": [
"0x2",
{
"showType": true,
"showContent": true,
"showOwner": true,
"showPreviousTransaction": true,
"showStorageRebate": true,
"showDisplay": true
}
]
}'
```
this error is returned
```json
{
"error": {
"code": -32000,
"message": "Indexer failed to read PostgresDB with error: `Object (0x0000000000000000000000000000000000000000000000000000000000000002, SequenceNumber(1), o#8MAXVsbUti4fZvSmk8xvKLYsaKSWyv8nNomCkGpLaj1T) is not a Move object`"
},
"id": 3
}
```
Before this [commit](https://github.com/MystenLabs/sui/commit/6c07b18b3b6da79ffaad9936b583008aff6a0f25#diff-c8d8604b043d015485da …

fix(sui_indexer): get object packages

---

.changeset/dry-stingrays-chew.md
external-crates/move/tooling/prettier-move/.npmignore
external-crates/move/tooling/prettier-move/CONTRIBUTING.md
external-crates/move/tooling/prettier-move/README.md
external-crates/move/tooling/prettier-move/package.json
external-crates/move/tooling/prettier-move/tsconfig.json
pnpm-lock.yaml
pnpm-workspace.yaml
sdk/move-bytecode-template/Cargo.lock

- adds `@mysten/prettier-plugin-move` to pnpm workspace
- resets versioning for publishing
- changeset
- CIs must pass
---

[prettier] Links prettier-plugin-move to pnpm workspace

---

Cargo.lock
crates/sui-graphql-e2e-tests/tests/stable/owner/root_version.exp
crates/sui-graphql-e2e-tests/tests/stable/owner/root_version.move
crates/sui-graphql-rpc/src/types/dynamic_field.rs

Today, when we fetch child objects, we can supply a root version, which is the version of the object in storage that eventually owns this object. We can't use the object's direct parent version because if we modify a child but not its parent in a transaction, then the parent's version will not be updated if that parent is itself a child object.
When we know that we are fetching a dynamic field off an object, O, if O was initialised with a root version, that is inherited by the dynamic field query, but if one was not supplied, then we use the object's version as the root version.
In the case of dynamic object fields, the dynamic field value is itself a child object of the `Field` that contains its name (which is itself a child object of some other object).
In the case of reading a dynamic …

fix(graphql): loading Owner.dynamicObjectField.value

---

crates/sui-core/src/execution_cache.rs
crates/sui-types/src/unit_tests/base_types_tests.rs

Remove PassthroughCache as an option, but leave the code in place so that nodes currently using it do not break

Force WritebackCache on

---

external-crates/move/crates/move-analyzer/trace-debug/.vscodeignore
external-crates/move/crates/move-analyzer/trace-debug/package-lock.json

What the title says (so that the Move icon file can be included in the published extension)

[trace-view] Un-ignore Move icon file

---

consensus/core/src/block_manager.rs
consensus/core/src/block_verifier.rs
consensus/core/src/core.rs
consensus/core/src/transaction.rs
crates/sui-core/src/authority_server.rs
crates/sui-types/src/transaction.rs

Fixes a bug when checking the total number of transactions included in a block via the transactions consumer in consensus. It would be possible to go over the max limit and effectively produce invalid blocks when it would verify on the block verifier side.
Also took this as opportunity to have an integration test that checks both the construction of block sizes and the block verifier so makes sure we are always aligned.
Added a couple of more soft bundle related metrics
CI
---

[Consensus] fix transaction size checks & metrics

---

crates/sui-indexer-alt/src/metrics.rs
crates/sui-indexer-alt/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt/src/pipeline/sequential/committer.rs

Add a metric to track the distribution of affected rows per database transaction from the committer. This will help measure how many rows the `sum_obj_types` pipeline is touching per write.
Local run, and test on deployment.
---

indexer-alt: metric for affected row histogram

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap

This helps some edge cases exercised more in simtests.
Also reduce `propagation_delay_stop_proposal_threshold` to 10 by default, which is still more than enough.
CI
---

[consensus] reduce parameter values for simtests

---

crates/sui-indexer-alt/src/handlers/sum_coin_balances.rs
crates/sui-indexer-alt/src/handlers/sum_obj_types.rs

Change how updates and deletes are handled in the sequential pipelines that need to delete rows such that the inserts and deletes can run concurrently with each other -- every little helps. This is based on a comment from @gegaowp on an earlier PR.
Run the indexer locally on the first 100,000 checkpoints.
---

indexer-alt: sequential pipeline concurrent update/delete

---

crates/sui-indexer-alt/src/ingestion/broadcaster.rs
crates/sui-indexer-alt/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt/src/pipeline/processor.rs
crates/sui-indexer-alt/src/task.rs

Create a `try_for_each_spawned` which works similarly to `try_for_each_concurrent` but spawns a new tokio task for each unit of work that it schedules based on values being pulled from the stream (but no more than the `limit` set on the max concurrency.
This does introduce some slight overhead if we run it with a limit of `1` (i.e. no concurrency) but otherwise will give the tokio runtime an opportunity to schedule each unit of work on a different thread (assuming the runtime is multi-threaded).
The interface is almost a drop-in replacement for
`try_for_each_concurrent` but with the following slight changes:
- The input stream does not need to be a `Result` itself.
- The future and returned error type must have `'static` lifetimes because they are being passed to the tokio runtime and we …

indexer-alt: try_for_each_spawned

---

crates/sui-core/src/authority.rs
crates/sui-json-rpc/src/authority_state.rs
crates/sui-json-rpc/src/coin_api.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-storage/src/bin/http_kv_tool.rs
crates/sui-storage/src/http_key_value_store.rs
crates/sui-storage/src/key_value_store.rs
crates/sui-storage/tests/key_value_tests.rs

Allows not to maintain extra table in Bigtable (i.e. checkpoint contents digest => checkpoint_sequence_number)
---

[json rpc] remove kv queries for checkpoint content by checkpoint contents digest

---

crates/sui-graphql-e2e-tests/tests/stable/call/checkpoint_connection_pagination.exp
crates/sui-graphql-e2e-tests/tests/stable/call/checkpoint_connection_pagination.move
crates/sui-graphql-e2e-tests/tests/stable/consistency/epochs/checkpoints.exp
crates/sui-graphql-e2e-tests/tests/stable/consistency/epochs/checkpoints.move
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/checkpoint.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap

This PR adds the `bcs` for Checkpoint to enable GraphQL Client to correctly handle `CheckpointSummary` data.
Added the field to two existing tests and updated the snapshots. A bit uncertain why some things have changed, so would need some help to figure out if it's correct or not. @wlmyng 
---

Add `bcs` field to `Checkpoint`

---

crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-mvr-graphql-rpc/src/test_infra/cluster.rs
crates/sui-mvr-graphql-rpc/tests/e2e_tests.rs

Needed to adjust the `ConnectionAsObjectStore`, because `objects` will not be written to in `mvr-mode`. Querying `objects` and querying `objects_history` + `objects_snapshot` should both yield the live object set.
---

[mvr] use mvr-mode on sui-mvr-graphql-rpc for in-crate tests

---

docker/sui-node-deterministic/Dockerfile

Change sui-node-deterministic to use glibc, requiring the latest stagex release.
---

docker: update sui-node-deterministic to use glibc with stagex 2024.11.0

---

crates/sui-deepbook-indexer/src/models.rs
crates/sui-deepbook-indexer/src/schema.rs
crates/sui-deepbook-indexer/src/server.rs

1. Allow for querying for quote asset
2. Removed 24 hour endpoints, historical endpoints will return 24 hour volume using base asset by default if query params not given
3. Interval default is 1 hour for interval endpoint
**Endpoint call examples:**
Public endpoint: https://deepbook-indexer.mainnet.mystenlabs.com/
```
/get_historical_volume/:pool_ids?start_time=1731260703&end_time=1731692703&volume_in_base=true
/get_historical_volume_by_balance_manager_id/:pool_ids/:balance_manager_id?start_time=1731260703&end_time=1731692703&volume_in_base=true
/get_historical_volume_by_balance_manager_id_with_interval/:pool_ids/:balance_manager_id?start_time=1731260703&end_time=1731462703&interval=86400&volume_in_base=true
```
Tested locally, updated docs …

New Deepbook Indexer Endpoints

---

crates/sui-protocol-config/src/lib.rs

This makes it more likely to exercise full blocks in simtests.
CI
---

Reduce max transactions per block in simtests

---

.changeset/nervous-baboons-build.md
external-crates/move/tooling/prettier-move/CHANGELOG.md
external-crates/move/tooling/prettier-move/README.md
external-crates/move/tooling/prettier-move/bin/prettier-move.js
external-crates/move/tooling/prettier-move/package-lock.json
external-crates/move/tooling/prettier-move/package.json
external-crates/move/tooling/prettier-move/pnpm-lock.yaml
external-crates/move/tooling/prettier-move/src/cst/expression/if_expression.ts
external-crates/move/tooling/prettier-move/src/cst/struct_definition.ts
external-crates/move/tooling/prettier-move/src/index.ts
external-crates/move/tooling/prettier-move/src/printer.ts
external-crates/move/tooling/prettier-move/src/utilities.ts
external-crates/move/tooling/prettier-move/tests/control-flow/if_expression.exp.move
external-crates/move/tooling/prettier-move/tests/errors/tree-sitter-match_test.move
external-crates/move/tooling/prettier-move/tests/module-members/enum.exp.move
external-crates/move/tooling/prettier-move/tests/module-members/struct.exp.move
external-crates/move/tooling/prettier-move/tests/module-members/struct.move

Preparing features for v0.2.0 release:
- abilities are now sorted in `key`, `copy`, `drop`, `store` order
- if no longer creates a block if expression is not block and breaks
- empty structs now support comments
- empty blocks now support comments
- packages `prettier-move` binary which simplifies CLI setup
- renames prettier parser name from `move-parser` to `move`
Features tests
---

[formatter] Next batch of improvements 

---

external-crates/move/crates/move-compiler/src/parser/lexer.rs
external-crates/move/crates/move-compiler/tests/move_check/parser/block_comments_inline.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/block_comments_inline.move
external-crates/move/crates/move-compiler/tests/move_check/parser/comments_nested_unbalanced.exp
external-crates/move/crates/move-compiler/tests/move_check/parser/empty_doc_comment.move

Partially revise block comment parsing, plus fix issues around parsing `/**/`
New tests that work now
---

[move][move-compiler] Revise block comment parsing to be more-resilient

---

external-crates/move/crates/move-compiler/src/naming/ast.rs
external-crates/move/crates/move-compiler/src/typing/core.rs
external-crates/move/crates/move-compiler/src/typing/syntax_methods.rs
external-crates/move/crates/move-compiler/src/typing/translate.rs

- Type variable generation now uses a counter in the context, rather than a global one. 
- non functional change 
---

[move-compiler] Replace usage of global tvar counter

---

crates/sui/src/client_commands.rs
crates/sui/src/sui_commands.rs

This change adds a warning when the CLI falls behind more than 2 protocol versions against the current active network on which the command will be executing against.
Locally.
---

[CLI] Add a warning if the CLI falls behind more than 2 protocol versions

---

crates/sui-core/src/authority.rs
crates/sui-json-rpc/src/coin_api.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-storage/src/http_key_value_store.rs
crates/sui-storage/src/key_value_store.rs
crates/sui-storage/tests/key_value_tests.rs

changes events query access pattern in JSON RPC from queries by events digest to queries by transaction digest.
It's prerequisite to switch to BigTable based KV store  
---

[json rpc] query events based on transaction digest

---

external-crates/move/tooling/prettier-extension/package.json

the prettier-move in vscode setting, `tabWidth` label name is error, it show the `tabSize`. So when I set the `tabSize`, format not work
in the source, the extension only read the `tabWidth` value, so need change `tabWidth` to `tabWidth`
https://github.com/MystenLabs/sui/blob/main/external-crates/move/tooling/prettier-extension/src/extension.js#L110
yes
open the vscode settings, then find the menu that name is  `prettierMove`
you can see the `Tab Size`, set it to 2,
then format the move file, it not work
but direct set the tabWidth, it work
---
For each box you select, include information after the relevant heading that describes …

change prettier-extension vscode setting name, tabSize to  tabWidth

---

.changeset/soft-days-relate.md
external-crates/move/tooling/prettier-move/src/index.ts
external-crates/move/tooling/prettier-move/tests/run.test.ts

Fixes missing parser error when using the binary.
---

[formatter] Fix missing parser error when running the binary

---

Cargo.lock
Cargo.toml
crates/sui-default-config/Cargo.toml
crates/sui-default-config/src/lib.rs
crates/sui-graphql-rpc/Cargo.toml
crates/sui-graphql-rpc/src/config.rs
crates/sui-mvr-graphql-rpc/Cargo.toml
crates/sui-mvr-graphql-rpc/src/config.rs

Take the `GraphQLConfig` procedural macro used by GraphQL and generalize it for use in other crates, as `DefaultConfig`. This macro simplifies defining a configuration to be read from a file, using serde's Serialze/Deserialize, and automatically using the type's `Default` to supply the default values while deserializing as well.
As part of generalizing, we dropped support for some features that don't work well in the more general setting:
- We no longer derive a number of other traits (like `Clone`, `Eq`, etc) -- these can be added manually if needed.
- We no longer force field names to be `rename_all = "kebab-case"`, because for the Indexer's config, we will want some of them to be renamed as `"snake_case"`. A check was added to see whether a `rename_all` attribute has been supplied, and …

indexer-alt: generalize GraphQLConfig

---

crates/sui-config/data/fullnode-template-with-path.yaml
crates/sui-config/data/fullnode-template.yaml

Fixes the fullnode template: incorrect documentation on how to set ipv4 address.
See reference: [sui/creates/sui-config/src/node.rs:478](https://github.com/MystenLabs/sui/blob/8bd53998f88c4619f39dcf298f699199a0071e7c/crates/sui-config/src/node.rs#L478)
Set the configuration value on a locally running node. Setting to `/ipv4/...` crashes on boot. Setting to `/ip4/...` continues to boot.
---

Fix: fullnode template ipv4 docs

---

crates/sui-indexer-alt/src/args.rs
crates/sui-indexer-alt/src/config.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs

Add the ability to combine configs together using a `merge-configs` command on the indexer. This allows:
- Each pipeline to be configured in its own file, and then combined based on how we want to distribute pipelines between pods.
- Combining the configurations of multiple application-specific indexers into one configuration.
Generally, when multiple configs define the same field, the last write wins. An exception is made for pruning retention which we merge using the `max` operation to cater to the second use case above where two applications may want to index the same data, at different retentions. 
This change also lays a foundation to support parameterized indexing, where the indexer can be configured to filter out data based on predicates which will also need to be merged to handle …

indexer-alt: merging file-based configs

---

crates/sui-indexer-alt/src/config.rs
crates/sui-indexer-alt/src/lib.rs

Add an extra flattened generic, `toml::Table` to every file-based config struct to pick up any flags that were not recognised by the indexer.
Extra fields will be logged as a warning and then ignored when processing flags, so that we are aware of potential typos, but will not cause an error to preserve some form of backwards compatibility (e.g. imagine a new pipeline is added to the indexer, and we update its TOML and try and run an old version of the indexer with the config that mentions the new pipeline).
Try merging together some configs that contain typos in them:
STDERR:
```
2024-11-27T00:29:37.177152Z  WARN sui_indexer_alt::config: Found unrecognized committer field which will be ignored by this indexer. This could be because of a typo, or because it was introduced in a newer …
```

indexer-alt: detect and warn against unrecognised fields.

---

crates/sui-indexer-alt/src/config.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/main.rs

Using the default impl for `IndexerConfig` to generate the output for `generate-config` lead to sub-par results because most of its fields are optional, and so will not show up.
This change introduces an explicit `example` function that is responsible for generating a non-default output that does a better job of documenting what fields and pipelines are available to configure.
Generate a config:
```
sui$ cargo run -p sui-indexer-alt -- generate-config
[ingestion]
checkpoint-buffer-size = 5000
ingest-concurrency = 200
retry-interval-ms = 200
[consistency]
consistent-pruning-interval-ms = 300000
pruner-delay-ms = 120000
[committer]
write-concurrency = 5
collect-interval-ms = 500
watermark-interval-ms = 500
[pruner]
interval-ms = 300000
delay-ms = 120000
retention = 4000000
max-chunk-size = …
```

indexer-alt: generate example config

---

crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/tests/json_rpc_tests.rs

Currently, there is a bug in the `suix_queryEvents` implementation when processing `EventFilter::MoveEventType(struct_tag)`. Even if the user provides a `struct_tag` in its full canonical hex representation (including the necessary prefix), it is not converted correctly to the format expected by the database. Instead, the struct_tag is transformed into a simplified representation that does not align with the structure stored in the indexer database.
This mismatch causes the SQL query to fail in finding the relevant records, effectively preventing the retrieval of the desired event data, despite the user supplying the correct input.
While `suix_queryEvents` makes use of following string:
https://github.com/MystenLabs/sui/blob/8bd53998f88c4619f39dcf298f699199a0071e7c/crates/sui-indexer/src/i …

fix(sui-indexer): Fix StructTag conversion for suix_queryEvents Indexer-RPC method

---

crates/sui/src/sui_commands.rs

When a `--config` is supplied and it is a directory, we treat it as the sui config directory in some but not all cases. This changes makes it so that if `--config` does not look like a YAML file, then it is treated like it should be the config directory, and that location is used everywhere the config directory is expected.
Manually tested running `sui start`, `sui start --network.config ...`:
```sh
$ sui start
$ sui start --force-regenesis
$ sui start --network.config ~/.sui/sui_config
$ sui start --network.config ~/.sui/sui_config/network.yaml
$ sui start --network.config "$CUSTOM_CONFIG"
$ sui start --network.config "$CUSTOM_CONFIG/network.yaml"
```
A custom config directory can be generated by taking a copy of the current config directory and tweaking it:
```sh
$ cp -r …
```

fix(sui): be consistent about sui config directory

---

crates/sui-move/src/build.rs
crates/sui/src/sui_commands.rs

Allow `sui move build --dump-bytecode-as-base64` to not need to read the chain from `client.yaml` by adding a flag `--ignore-chain`. This allows building to proceed without a network connection or active environment, but it will not be able to automatically determine the addresses of its dependencies.
NB: `--ignore-chain` depends on `dump-bytecode-as-base64`, so it cannot be used on its own.
Should close #20458.
Local test.
```
➜  first_package git:(main) ✗ sui move build --dump-bytecode-as-base64 --ignore-chain
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING my_first_package
JSON_OUTPUT_HERE - replaced for brevity.
➜  first_package git:(main) ✗ sui move build --dump-bytecode-as-base64
Config file ["/Users/user/.sui/sui_config/client.yaml"] doesn't exist, do you want to …
```

Ignore chain id when using `--dump-bytecode-as-base64` in `sui move build`

---

crates/sui-types/src/effects/effects_v1.rs

Fix a bug introduced in 874da38e39 (CheckpointData: fix bug when loading input objects with deleted shared objects, 2024-06-10) whereby CheckpointData began to be constructed by only leveraging the `TransactionEffectsAPI::modified_at_versions` method instead of the hand-rolled version which explicitly filtered out
`unwrapped_then_deleted` objects from calling the set of `modified_at_versions` list of objects. The impact of this, was that when processing transactions which have V1 format effects, the process which constructs CheckpointData tries to load an unwrapped_then_deleted object, which does not exist, leading to a crash. This behavior was never observed because at the time 874da38e39 was committed, the network only produced V2 formatted effects who's `modified_at_versions` properly …

effects: fix modified_at_versions in V1 to have parity with V2 semantics

---

crates/sui-graphql-e2e-tests/tests/stable/prune/prune.exp
crates/sui-graphql-e2e-tests/tests/stable/prune/prune.move
crates/sui-indexer/src/store/pg_indexer_store.rs

- a fix for pruning wait-for, `checkpoints` should be pruned last so that wait-for in test_infra can use that as a watermark table
- add more tests for pruning enabling
cargo nextest run sui-graphql-e2e-tests::tests run_test::stable/prune  
---

indexer: fix and more tests for pruning enabling

---

crates/sui-field-count-derive/src/lib.rs
crates/sui-field-count/src/lib.rs
crates/sui-indexer-alt/src/handlers/ev_emit_mod.rs
crates/sui-indexer-alt/src/handlers/ev_struct_inst.rs
crates/sui-indexer-alt/src/handlers/kv_feature_flags.rs
crates/sui-indexer-alt/src/handlers/kv_objects.rs
crates/sui-indexer-alt/src/handlers/kv_protocol_configs.rs
crates/sui-indexer-alt/src/handlers/kv_transactions.rs
crates/sui-indexer-alt/src/handlers/obj_versions.rs
crates/sui-indexer-alt/src/handlers/sum_coin_balances.rs
crates/sui-indexer-alt/src/handlers/sum_displays.rs
crates/sui-indexer-alt/src/handlers/sum_obj_types.rs
crates/sui-indexer-alt/src/handlers/sum_packages.rs
crates/sui-indexer-alt/src/handlers/tx_affected_addresses.rs
crates/sui-indexer-alt/src/handlers/tx_affected_objects.rs
crates/sui-indexer-alt/src/handlers/tx_balance_changes.rs
crates/sui-indexer-alt/src/handlers/tx_calls.rs
crates/sui-indexer-alt/src/handlers/tx_digests.rs
crates/sui-indexer-alt/src/handlers/tx_kinds.rs
crates/sui-indexer-alt/src/handlers/wal_coin_balances.rs
crates/sui-indexer-alt/src/handlers/wal_obj_types.rs
crates/sui-indexer-alt/src/models/displays.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/models/packages.rs
crates/sui-indexer-alt/src/models/transactions.rs
crates/sui-indexer-alt/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/pipeline/processor.rs
crates/sui-indexer-alt/src/pipeline/sequential/mod.rs

- change field_count trait from fn to const as we want to use it as part of const def
- use it in sui-indexer-alt
1. existing tests for sui-field-count
2. for replacements, I added temp tests to ensure the values before and after were the same, removed them afterwards to avoid unnecessary changes later on when we change struct definition
---

sui-field-count: const instead of fn and use it in sui-indexer-alt

---

crates/sui-indexer-alt/migrations/2024-11-25-211949_obj_info/up.sql

We always query cp_sequence_number in DESC order.
I will manually update the DB.
---

[indexer-alt] Sort cp_sequence_number DESC in obj_info indexes

---

Cargo.lock
crates/sui-indexer-alt/Cargo.toml
crates/sui-indexer-alt/src/ingestion/broadcaster.rs
crates/sui-indexer-alt/src/ingestion/mod.rs
crates/sui-indexer-alt/src/ingestion/regulator.rs
crates/sui-indexer-alt/src/metrics.rs
crates/sui-indexer-alt/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt/src/pipeline/concurrent/commit_watermark.rs
crates/sui-indexer-alt/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt/src/pipeline/concurrent/pruner.rs
crates/sui-indexer-alt/src/pipeline/concurrent/reader_watermark.rs
crates/sui-indexer-alt/src/pipeline/processor.rs
crates/sui-indexer-alt/src/pipeline/sequential/committer.rs

Part of the preparation for factoring out the indexer framework and schema. Removing a dependency on `mysten-metrics` because this is probably not something we want people outside of Mysten to depend on, and it is used in code that would be factored into the indexer framework.
This means we lose some metrics related to thread stalls, and number of tracked tasks, but as far as I'm aware, we don't rely on these metrics anywhere.
CI
---

refactor(indexer-alt): remove dependency on mysten-metrics

---

Cargo.lock
crates/sui-deepbook-indexer/Cargo.toml
crates/sui-deepbook-indexer/src/server.rs

**Modified Endpoint 1:** 
/get_historical_volume/:pool_id -> /historical_volume/pool_name
Response will display pool as pool_name
Example call:
`/historical_volume/SUI_USDC,DEEP_USDC?start_time=1733152516&end_time=1733238917`
Example response:
`{"DEEP_USDC":24033500000000,"SUI_USDC":2647584300000000}`
**New Endpoint 1: /all_historical_volume**
Retrieves the pools stored in db and return volume for all pools within time range
Example Call:
`/all_historical_volume?start_time=1733152516&end_time=1733238917`
Example Response:
`{"DEEP_USDC":23658150000000,"DEEP_SUI":5311220000000,"TYPUS_SUI":662314300000000,"SUI_USDC":3365051200000000,"WUSDC_USDC":7960304900000,"NS_USDC":783869300000,"NS_SUI":379958200000}`
**New Endpoint 2: /orderbook/:pool_name**
More information: …

Coinmarketcap Deepbook Endpoints

---

crates/sui-json-rpc/src/name_service.rs
crates/sui-node/src/lib.rs

Instead of requiring the node operators manually configure suins lookups for testnet, provide this configration baked into sui-node and use it when the node is operating on testnet.
---

jsonrpc: support suins by default on testnet

---

Cargo.lock
consensus/config/src/committee.rs
consensus/core/build.rs
consensus/core/src/ancestor.rs
consensus/core/src/authority_service.rs
consensus/core/src/broadcaster.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/leader_timeout.rs
consensus/core/src/metrics.rs
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/mod.rs
consensus/core/src/network/test_network.rs
consensus/core/src/network/tonic_network.rs
consensus/core/src/round_prober.rs
consensus/core/src/subscriber.rs
consensus/core/src/synchronizer.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_70.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_70.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_70.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

For ancestor selection we want to ensure the highest quality ancestors are included in the proposal, therefore if an authority is excluded we should start including them once they have caught up to the network with their accepted blocks not just received as its possible for blocks to be received but suspended on many hosts which can cause performance degradation
Additionally switched to using high quorum round of the high quorum round of accepted rounds for inclusion metric.
Also bumped protocol version to 70 to include the new feature.
Injected Latency Test - https://metrics.sui.io/goto/Jowh4F7Hg?orgId=1
Hoarded Block Test - Pending
--- …

[consensus] Get highest accepted rounds from RoundProber and use in ancestor selection

---

crates/sui-faucet/src/metrics.rs
crates/sui-faucet/src/metrics_layer.rs
crates/sui/src/client_commands.rs

This PR adds the `user-agent` header for the faucet requests to keep track which requests come from where. 
The CLI gets updated to make usage of this header when requesting a token via `sui client faucet`.
Locally, fired up a grafana dashboard and also looked at the prometheus metrics.
`total_requests_received{path="/v1/gas",user_agent="sui/1.39.0"} 1`
---

[faucet] add `user-agent` header for incoming requests

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_70.snap

Additionally will enable probing for accepted rounds which is used only by ancestor selection.
---

[consensus] Enable smart ancestor selection in testnet

---

external-crates/move/crates/move-analyzer/src/symbols.rs

Currently move-analyzer does not fully track all files requiring analysis but rather only the last one sent to the symbolicator. It should not be a huge deal from the user's point of view as they spend significant amount of time (at least compared to analysis time) editing a single file before switching to the next, but precise tracking will be needed if we only want to re-analyze specific files (as part of an upcoming optimization). This PR implements tracking of all files requiring analysis.

[move-ide] Track all files requiring analysis

---

crates/sui-graphql-e2e-tests/tests/stable/prune/prune.exp
crates/sui-graphql-e2e-tests/tests/stable/prune/prune.move
crates/sui-graphql-e2e-tests/tests/stable/prune/transactions.exp
crates/sui-graphql-e2e-tests/tests/stable/prune/transactions.move
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-graphql-rpc/src/server/watermark_task.rs
crates/sui-graphql-rpc/src/types/epoch.rs
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/src/types/transaction_block/mod.rs
crates/sui-graphql-rpc/src/types/transaction_block/tx_lookups.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs

- main changes from https://github.com/MystenLabs/sui/pull/19237 and this is the only unknown blocker
- plus rebase, addressing comments and some testing changes.
cargo nextest run --no-capture sui-graphql-e2e-tests::tests run_test::stable/prune
---

GraphQL changes to enable pruning

---

consensus/core/src/authority_node.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/round_prober.rs
consensus/core/src/synchronizer.rs
crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs

Obviously there is no fault tolerance. But this should be useful for running local cluster cheaply. `min_round_delay` should be set to a higher value for local cluster so not too many consensus blocks are built.
Add unit and simtest.
---

[consensus] support committee with 1 node

---

crates/sui-indexer-alt-framework/src/metrics.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/config.rs
crates/sui-indexer-alt/src/lib.rs

Add support for a lagged concurrent pipeline.
To do so we add an extra parameter to ConcurrentConfig, which then gets passed into collector.
Collector would maintain a list of checkpoints received but not ready for sending to the committer.
A checkpoint is only moved off from the received list if it meets the lag contraint.
Added unit tests for the main utility function.
---

[indexer-alt] Add support for lagged concurrent pipeline

---

crates/sui/src/sui_commands.rs
crates/sui/tests/cli_tests.rs

This PR enables `sui genesis` and `sui start` to pass the `committee-size` argument specifying the number of validators that should be started in the local network.
Note that if `sui start --committee-size 3` is executed with no `.sui` or `genesis` data, on a subsequent run the `--committee-size` arg will be ignored. 
Locally. Checked the number of generated config files for validators + GraphQL query.
```
sui start --committee-size 3 --with-graphql
➜  sui_config ls -l
total 3104
-rw-r--r--  1 s    staff    5338 Dec  4 21:15 127.0.0.1-51144.yaml
-rw-r--r--  1 s    staff    5338 Dec  4 21:15 127.0.0.1-51158.yaml
-rw-r--r--  1 s    staff    5338 Dec  4 21:15 127.0.0.1-51172.yaml
drwxr-xr-x  5 s  staff     160 Dec  4 21:15 authorities_db/
---
```
```json
{
"data": {
"epoch": { …
```

[CLI] Make the number of validators configurable for `sui genesis` and `sui start`

---

crates/sui-indexer-alt/src/models/objects.rs

```
// Add one here for cp_sequence_number field, because StoredObjectUpdate is used for
// wal_* handlers, where the actual type has an additional field besides fields of T.
```
Ci, we will want to add a test for chunk size <> commit limit, and will do that in a separate pr.
---

indexer-alt: fix field count for wal_ types

---

crates/sui-move/src/new.rs
docs/content/concepts/sui-move-concepts/conventions.mdx

* Fix typo in 2024 Conventions
* ~Add Conventions as comments to a new package when `sui move new`~
* Add Conventions link to a new package when `sui move new`
* no extra tests needed

Add move 2024 Conventions as comments to the new package example

---

crates/sui-indexer-alt/migrations/2024-10-27-150938_sum_obj_types/up.sql
crates/sui-indexer-alt/migrations/2024-10-28-144002_sum_coin_balances/up.sql
crates/sui-indexer-alt/migrations/2024-11-25-211949_obj_info/up.sql
crates/sui-indexer-alt/migrations/2024-12-02-185822_add_coin_balance_owner_kind/down.sql
crates/sui-indexer-alt/migrations/2024-12-02-185822_add_coin_balance_owner_kind/metadata.toml
crates/sui-indexer-alt/migrations/2024-12-02-185822_add_coin_balance_owner_kind/up.sql
crates/sui-indexer-alt/migrations/2024-12-05-153042_add_coin_balance_owner_kind_indexes/down.sql
crates/sui-indexer-alt/migrations/2024-12-05-153042_add_coin_balance_owner_kind_indexes/metadata.toml
crates/sui-indexer-alt/migrations/2024-12-05-153042_add_coin_balance_owner_kind_indexes/up.sql
crates/sui-indexer-alt/migrations/2024-12-05-162242_add_coin_balance_owner_kind_indexes/down.sql
crates/sui-indexer-alt/migrations/2024-12-05-162242_add_coin_balance_owner_kind_indexes/metadata.toml
crates/sui-indexer-alt/migrations/2024-12-05-162242_add_coin_balance_owner_kind_indexes/up.sql
crates/sui-indexer-alt/migrations/2024-12-05-162243_add_coin_balance_owner_kind_indexes/down.sql
crates/sui-indexer-alt/migrations/2024-12-05-162243_add_coin_balance_owner_kind_indexes/metadata.toml
crates/sui-indexer-alt/migrations/2024-12-05-162243_add_coin_balance_owner_kind_indexes/up.sql
crates/sui-indexer-alt/migrations/2024-12-05-162244_add_coin_balance_owner_kind_indexes/down.sql
crates/sui-indexer-alt/migrations/2024-12-05-162244_add_coin_balance_owner_kind_indexes/metadata.toml
crates/sui-indexer-alt/migrations/2024-12-05-162244_add_coin_balance_owner_kind_indexes/up.sql
crates/sui-indexer-alt/src/handlers/sum_coin_balances.rs
crates/sui-indexer-alt/src/handlers/sum_obj_types.rs
crates/sui-indexer-alt/src/handlers/wal_coin_balances.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/schema.rs

Partial revert of #20486 (only the changes relevant to `sui-indexer-alt`), as the migrations associated with that change are taking too long to run on the production database.
We will have to revisit how to set-up those migrations so that they run in a reasonable time.
Local run of `sui-indexer-alt` + CI.
---

revert(#20486): Add ConsensusV2 object support to `sui-indexer-alt`

---

crates/sui-indexer-alt-framework/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs

Added tests for indexer alt collector and also corrected a potential debug assert.
Added tests.
---

[indexer alt] add collector tests

---

crates/sui-deepbook-indexer/src/server.rs

1. Deepbook Summary Endpoint: /summary
Sample response:
`[{"trading_pairs":"WUSDC_USDC","quote_currency":"USDC","base_volume":3675177.5,"last_price":1.0,"lowest_price_24h":0.9999,"base_currency":"WUSDC","highest_bid":1.0,"highest_price_24h":1.0002,"price_change_percent_24h":-0.009999000099991662,"quote_volume":3675165.11285,"lowest_ask":1.0001},{"highest_price_24h":4.4748,"base_volume":48790.4,"lowest_price_24h":0.0033,"highest_bid":4.2293,"lowest_ask":4.2361,"trading_pairs":"SUI_AUSD","quote_currency":"AUSD","price_change_percent_24h":0.6522306287503277,"quote_volume":207421.6792,"last_price":4.25,"base_currency":"SUI"}]`
2. Volume query defaults to using quote asset
Tested locally using production data
Check each box that your changes affect. …

Deepbook Summary Endpoint

---

external-crates/move/crates/move-analyzer/tests/cursor_tests/cursor_dot_call_tests.exp

The output for `move-analyzer` tests changed (and needed to be updated) due to recent compiler changes but due to some issue with the CI test runner the "old" output was not reported as incorrect. This PR updates test output to reflect the current state of affairs.

[move-ide] Regenerated test output

---

.github/workflows/turborepo.yml

allow secrets for turborepo workflow for gcp + aws KMS e2e testing
* once this is merged, create a pull-request from a forked repo to test turborepo action
---
if there is a security incident with these secrets, it should only compromise the following
these secrets have been created to only allow limited operations for the designed AWS / GCP KMS keys (these keys and access policies only allow for using the designated test keys / keycahins.

update tuborepo workflow to allow secrets for PRs from forked repos

---

crates/sui-core/src/execution_cache/object_locks.rs

Log the conflicted object as well as transactions digests

Improve logs for lock conflicts

---

.github/workflows/turborepo.yml

Reverts MystenLabs/sui#20552
`pull_request_target` checks out target branch (i.e. `main`) which means tests aren't run on new code 🤦 
Will also update to not run gcp / kms tests for all prs

Revert "update tuborepo workflow to allow secrets for PRs from forked repos"

---

external-crates/move/crates/move-disassembler/src/disassembler.rs
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/declarations/function.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/declarations/let.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/binary_add.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/borrow.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/borrow_mut.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/builtins/vector.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/combined.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/pack.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/unpack.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/assert.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/enums.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/jump.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/jump_if.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/jump_if_false.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/parsing/comments.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/parsing/crlf.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/parsing/named_addresses.exp
external-crates/move/crates/move-transactional-test-runner/tests/vm_test_harness/print_bytecode.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/basic_poly_enum_type_mismatch.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_jump_same_label.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_mismatch.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/mono/enum_decl_monomorphic.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/mono/mut_ref_update.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/mono/mut_ref_update_variant.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/basic_poly_enum.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/poly_mut_ref_update.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/poly_mut_ref_update_variant.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/variant_switch_loop.exp
external-crates/tests.sh

Fix CI runner for CI for Move (using `set -e` in `test.sh`).
Fix formatting issues for enums in the disassembler. 
CI + ran Move tests locally (including failing tests to make sure the tests fail if any fail)
---

[move] Fix formatting in disassembler + fix CI runner for Move

---

external-crates/move/crates/move-disassembler/src/disassembler.rs
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/declarations/function.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/declarations/let.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/binary_add.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/borrow.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/borrow_mut.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/builtins/vector.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/combined.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/pack.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/unpack.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/assert.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/enums.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/jump.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/jump_if.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/statements/jump_if_false.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/parsing/comments.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/parsing/crlf.exp
external-crates/move/crates/move-ir-compiler-transactional-tests/tests/parsing/named_addresses.exp
external-crates/move/crates/move-transactional-test-runner/tests/vm_test_harness/print_bytecode.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/basic_poly_enum_type_mismatch.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_jump_same_label.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_mismatch.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/mono/enum_decl_monomorphic.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/mono/mut_ref_update.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/mono/mut_ref_update_variant.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/basic_poly_enum.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/poly_mut_ref_update.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/poly_mut_ref_update_variant.exp
external-crates/move/crates/move-vm-transactional-tests/tests/enums/variant_switch_loop.exp
external-crates/tests.sh

Fix CI runner for CI for Move (using `set -e` in `test.sh`).
Fix formatting issues for enums in the disassembler. 
CI + ran Move tests locally (including failing tests to make sure the tests fail if any fail)
---
--- …

[cherry-pick][move] Fix formatting in disassembler + fix CI runner for Move (#20556)

---

crates/sui-indexer/src/indexer_reader.rs
crates/sui-indexer/src/models/objects.rs
crates/sui-mvr-graphql-rpc/src/test_infra/cluster.rs
crates/sui-mvr-graphql-rpc/tests/e2e_tests.rs

Needed to adjust the `ConnectionAsObjectStore`, because `objects` will not be written to in `mvr-mode`. Querying `objects` and querying `objects_history` + `objects_snapshot` should both yield the live object set.
---
---
For …

[mvr][gql] Cherry pick sui mvr graphql rpc tests use mvr mode

---

crates/sui-indexer/src/handlers/mod.rs
crates/sui-indexer/src/handlers/pruner.rs

These tables no longer exist in the indexer schema
---

[easy][indexer] Remove last mentions of tx_recipients and tx_senders tables

---

crates/sui-indexer-alt/src/config.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/obj_info.rs
crates/sui-indexer-alt/src/handlers/obj_info_pruner.rs
crates/sui-indexer-alt/src/lib.rs

This PR implements the obj_info_pruner pipeline.
I refactored the obj_info pipeline so that these two pipelines could share the same process function logic.
For obj_info_pruner, it look at every (obj_id, checkpoint) pair produced from the obj_info processing, and prune accordingly. Within each commit, it does sequential pruning which is less ideal, but hopefully if we have enough concurrent at the outer layer, this is not a huge problem.
---

[indexer-alt] Add pruner pipeline for obj_info

---

crates/sui-mvr-indexer/src/handlers/pruner.rs

…20563)
---
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions …

[mvr] cherry-pick change to drop old tx addresses tables

---

external-crates/move/crates/move-compiler/src/cfgir/translate.rs
external-crates/move/crates/move-compiler/src/hlir/match_compilation.rs
external-crates/move/crates/move-compiler/src/hlir/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/matching/const_lit.move
external-crates/move/crates/move-compiler/tests/move_2024/matching/const_lit_bool.move

This fixes a bug where some match arms' final type was computed based on the inner arm, instead of the expected output type.
New tests past
---

[move][move-2024] Match typing fix

---

crates/sui-indexer-alt-framework/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt-framework/src/pipeline/mod.rs
crates/sui-indexer-alt-framework/src/pipeline/processor.rs
crates/sui-indexer-alt-framework/src/pipeline/sequential/committer.rs

While reading/testing this code I found that it can be tough to reason about limits of channels because each channel may have different units: checkpoints, batches, rows. So this PR made some struct names more explicit according to my understanding and added some comments to make channel limits more clear. 
Existing tests. 
---

[indexer alt] rename a few structs to make their units more clear

---

Cargo.lock
Cargo.toml
consensus/core/src/network/anemo_network.rs
consensus/core/src/network/metrics_layer.rs
consensus/core/src/network/tonic_network.rs
crates/mysten-network/Cargo.toml
crates/mysten-network/src/callback/body.rs
crates/mysten-network/src/callback/future.rs
crates/mysten-network/src/callback/mod.rs
crates/mysten-network/src/callback/service.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-mvr-graphql-rpc/src/server/builder.rs
crates/sui-rpc-api/src/metrics.rs
crates/x/src/lint.rs

* extend the lifetime of callback handlers in order to get a more accurate measurement of inflight requests, since now the handler will be held until the body has been fully exhausted and sent on the wire (or at least fully handed off to hyper).
* updates the path label for metrics to account for gRPC routes
* updates the status label for metrics to use gRPC status codes for grpc requests

rpc: improve metrics for grpc endpoint

---

crates/sui-rpc-api/src/client/mod.rs
crates/sui-rpc-api/src/client/response_ext.rs

Convert Client error type to be a tonic::Status. In addition, ensure
that if http headers (which are wrapped in a
tonic::metadata::MetadataMap) are received, that they are included in
either the response or the error Status so that callers can retrieve
header information even in the event of an error.

rpc: convert Client error to tonic::Status

---

crates/sui/src/client_ptb/ptb.rs
crates/sui/src/displays/dev_inspect.rs

This PR fixes the `sui client ptb --dev-inspect` command to correctly display the result of the dev inspect.
---

[CLI] Fix dev inspect in sui client ptb

---

crates/sui-e2e-tests/tests/rpc/checkpoints.rs
crates/sui-e2e-tests/tests/rpc/objects.rs
crates/sui-rpc-api/openapi/openapi.json
crates/sui-rpc-api/src/client/sdk.rs
crates/sui-rpc-api/src/response.rs
crates/sui-rpc-api/src/rest/accounts.rs
crates/sui-rpc-api/src/rest/checkpoints.rs
crates/sui-rpc-api/src/rest/mod.rs
crates/sui-rpc-api/src/rest/objects.rs
crates/sui-rpc-api/src/rest/openapi.rs

Now that the new gRPC endpoint handles binary wire formatted requests/responses, the only BCS based wire formatted support can be removed from the experimental rest api. 
---

rest: remove bcs content type responses

---

Cargo.lock
crates/sui-faucet/Cargo.toml
crates/sui-faucet/src/server.rs

Previous rate limiter is likely broken. This uses a better one with a per ip address strategy.
---

[fix] faucet new rate limiter

---

crates/sui-core/src/execution_cache/cache_types.rs
crates/sui-core/src/execution_cache/metrics.rs
crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
crates/sui-core/src/execution_cache/writeback_cache.rs

Suppose that a reader thread is trying to cache an object that it just
read, while a writer thread is trying to cache an object that it just
wrote. The writer thread definitionally has the latest version. The
reader thread may be out of date. While we previously took some care to
not replace a new version with an old version, this did not take into
account evictions, and so the following bug was possible:
READER                            WRITER
read object_by_id_cache (miss)
read dirty set (miss)
write to dirty
read db (old version)
write to cache (while holding dirty lock)
cache entry is evicted
write to cache
There is no way for the reader to tell that the value it is caching is
out of date, because the up to date entry is already gone from the
cache.
We fix this by requiring reader …

[Cherry-Pick] Fix bug in object_by_id_cache (#20450)

---

crates/suiop-cli/src/cli/ci/image.rs

Add org optional arg to build from other github orgs
Built from another org successfully 
```
suiop ci image query --repo-name another-repo
Requested query for repo: tomato-contracts
╭────────────────────────┬───────────┬─────────────────────────┬─────────────────────╮
│ name                   │ status    │ Start Time (Local Time) │ End Time            │
├────────────────────────┼───────────┼─────────────────────────┼─────────────────────┤
│ another-repo-pigyh │ Succeeded │ 2024-12-12 11:33:51     │ 2024-12-12 11:44:18 │
╰────────────────────────┴───────────┴─────────────────────────┴─────────────────────╯
```
--- …

Add org support to suiop ci image command for image builds

---

crates/sui-bridge-indexer/src/sui_transaction_handler.rs
crates/sui-bridge/src/events.rs
crates/sui-bridge/src/server/handler.rs
crates/sui-bridge/src/sui_client.rs
crates/sui-graphql-rpc/src/mutation.rs
crates/sui-indexer/src/apis/indexer_api.rs
crates/sui-indexer/src/models/events.rs
crates/sui-json-rpc-types/src/lib.rs
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-json-rpc/src/indexer_api.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-mvr-graphql-rpc/src/mutation.rs
crates/sui-mvr-indexer/src/apis/indexer_api.rs
crates/sui-mvr-indexer/src/models/events.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-open-rpc/src/examples.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/sui_serde.rs
crates/sui/src/client_commands.rs

Inorder to ease the transition of SuiEvent.bcs and DynamicFieldInfo.bcsName to being encoded with base64, introduce a tag ("bcsEncoding") to indicate the encoding and gracefully default to base58 when the tag isn't present.
---

jsonrpc: introduce bcsEncoding tag to ease migration to base64

---

crates/sui-indexer-alt-framework/src/metrics.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt-framework/src/pipeline/sequential/committer.rs

Adds a metric that tracks the number of failed commits.
While we track the number of attempts and number of successes, they cannot be used to track number of errors, because any at moment, the delta can exist but they don't necessarily mean errors.
So if we want to track error rate, we need a dedicated metric.
---

[indexer-alt] Add total_committer_batches_failed metric

---

Cargo.lock
crates/sui-indexer-alt/Cargo.toml
crates/sui-indexer-alt/src/handlers/coin_balance_buckets_pruner.rs
crates/sui-indexer-alt/src/handlers/obj_info_pruner.rs

Instead of delete one by one, delete all in a single sql query.
Tried locally.
---

[indexer-alt] Use batch delete in consistent pruners

---

crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/cache_types.rs
crates/sui-core/src/execution_cache/passthrough_cache.rs
crates/sui-core/src/execution_cache/writeback_cache.rs

Add negative caching for effects and other point-read items. This dramatically reduces requests to the DB during test runs.

Negative caching for point-read items such as transactions and effects

---

crates/sui-benchmark/src/drivers/bench_driver.rs
crates/sui-benchmark/src/options.rs
crates/sui-benchmark/src/workloads/adversarial.rs
crates/sui-benchmark/src/workloads/batch_payment.rs
crates/sui-benchmark/src/workloads/delegation.rs
crates/sui-benchmark/src/workloads/expected_failure.rs
crates/sui-benchmark/src/workloads/mod.rs
crates/sui-benchmark/src/workloads/randomized_transaction.rs
crates/sui-benchmark/src/workloads/randomness.rs
crates/sui-benchmark/src/workloads/shared_counter.rs
crates/sui-benchmark/src/workloads/shared_object_deletion.rs
crates/sui-benchmark/src/workloads/transfer_object.rs
crates/sui-benchmark/src/workloads/workload.rs
crates/sui-benchmark/src/workloads/workload_configuration.rs
crates/sui-benchmark/tests/simtest.rs

Randomized transaction testing.
---

Add a workload that randomly generates different transaction shapes

---

crates/sui-graphql-rpc/src/data/move_registry_data_loader.rs
crates/sui-graphql-rpc/src/metrics.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-mvr-graphql-rpc/README.md
crates/sui-mvr-graphql-rpc/src/data/move_registry_data_loader.rs
crates/sui-mvr-graphql-rpc/src/metrics.rs
crates/sui-mvr-graphql-rpc/src/server/builder.rs

To resolve the mvr table on testnet, we consult the mainnet graphql service. We previously observed some slowness around dns lookup, so this metric will help track whether the issue persists. Also added to `sui-graphql-rpc` crate.
---

[mvr] add external dns lookup metric to track resolving mvr from non-mainnet graphql

---

crates/sui-benchmark/src/workloads/workload.rs

The change of this code block from `Ok(rand::random())` to a custom selector logic overlooked the fact that we must avoid re-selecting variant `0`, as variant `0` is the random variant, causing the code to hit an `unreachable` block meant to avoid infinte recursion.
Re-run test
---

[tests] Fix expected failure type random selector

---

crates/sui-sdk/README.md
crates/sui-sdk/examples/sui_client.rs
crates/sui-sdk/src/lib.rs

This PR adds a new function `build_mainnet` corresponding to the mainnet RPC node for the `SuiClientBuilder` type.
```rust
let sui_mainnet = SuiClientBuilder::default().build_mainnet().await?;
println!("Sui mainnet version: {}", sui_mainnet.api_version());
```
---

add build_mainnet for easy use sui-sdk

---

crates/sui-json-rpc-types/src/lib.rs
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-open-rpc/spec/openrpc.json

jsonrpc: correctly serialize bcsName field

---

crates/sui-indexer/src/restorer/formal_snapshot.rs
crates/sui-mvr-indexer/src/restorer/formal_snapshot.rs
crates/sui-snapshot/src/reader.rs
crates/sui-snapshot/src/tests.rs
crates/sui-tool/src/lib.rs

title, this can be problematic when a file is half-downloaded but useful when all file downloading is complete, which helps to speed up iteration over restore, as each time the .ref files download would take about 30min
local run restorer and verify that it can reuse downloaded files
first run
```
104 out of 673 missing .ref files done
```
second run
```
8 out of 569 missing .ref files done
```
---

snapshot restore: add option to reuse downloaded files

---

crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
crates/sui-indexer-alt/src/handlers/coin_balance_buckets_pruner.rs
crates/sui-indexer-alt/src/handlers/obj_info.rs
crates/sui-indexer-alt/src/handlers/obj_info_pruner.rs

We do not need to prune anything when we create or unwrap objects in a checkpoint, since we know that the object did not exist prior to this checkpoint in the table.
This saves a lot of unnecessary pruning requests.
Deployed in prod.
---

[indexer-alt] Do not prune in the case of object creation

---

crates/sui-benchmark/tests/simtest.rs

Fixes rare test failure in `test_backpressure`

Suppress more types of overload protection in backpressure test

---

crates/sui-core/src/execution_cache/cache_types.rs

Temporary work around for crash

Temporary work around for crash

---

external-crates/move/crates/move-analyzer/src/analyzer.rs
external-crates/move/crates/move-analyzer/src/completions/mod.rs
external-crates/move/crates/move-analyzer/src/symbols.rs
external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs

This PR builds upon the compiler changes supporting partial compilation of of user code (skipping function bodies when compiling specific files designated by the user) to deliver the performance improvements described in the [PR](https://github.com/MystenLabs/sui/pull/20588) containing the compiler changes (reducing compilation time in the IDE for the Deepbook package from over 1s to less than 200ms).
In this PR, in addition to caching dependencies, we also cache user code, fully compile only modified files, and merge result of this compilation with the cached data
All tests must pass. Also tested manually to verify correctness and performance improvements

[move-analyzer] Cache user program

---

crates/sui-proc-macros/src/lib.rs

This adds a missing comma to the `sim_test` procedural macro. Without this, the arguments to the `sim_test` attribute are parsed correctly but propagated without commas, causing an error "error: expected `,`".
All the existing simtests should continue to work.

fix: add missing comma to sim_test macro
