MystenLabs/sui

crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs
crates/sui-node/src/lib.rs

Checkpoint builder may never finish because it misses transactions and consensus on peers has shut down.
CI
`test_simulated_load_reconfig_with_crashes_and_delays`
---

Abort checkpoint service tasks on epoch change

---

crates/sui-core/src/jsonrpc_index.rs

jsonrpc_index: bump coin index version to 1

---

crates/sui-bridge-indexer/README.md

add readme for bridge indexer

---

crates/sui-config/src/p2p.rs
crates/sui-network/build.rs
crates/sui-network/src/discovery/builder.rs
crates/sui-network/src/discovery/mod.rs
crates/sui-network/src/discovery/server.rs
crates/sui-network/src/discovery/tests.rs
crates/sui-tool/src/lib.rs

Remove unsigned version of Discovery protocol

---

crates/sui-bridge-cli/src/lib.rs

allow dry run for eth claim

---

docs/content/standards/deepbookv3/query-the-pool.mdx

deepbook doc query-the-pool fix typo

---

crates/sui-proxy/src/peers.rs

will apply fix to mainnet proxy
---

[fix] support pre-existing paths in provided bridge urls

---

apps/wallet/src/shared/analytics/ampli/index.ts
apps/wallet/src/ui/app/pages/swap/index.tsx

add tracking for provider

---

crates/sui-core/src/jsonrpc_index.rs
crates/typed-store/src/rocks/mod.rs

1.36 index fix

---

crates/sui-rest-api/openapi/openapi.json
crates/sui-rest-api/src/checkpoints.rs
crates/sui-rest-api/src/client/mod.rs
crates/sui-rest-api/src/client/sdk.rs
crates/sui-rest-api/src/lib.rs

This reverts commit 13c1ec7b2a7a18e304444d63277c20f8f52a1bc2.
---

Revert "rest: stabalize some checkpoint apis"

---

docs/content/standards/deepbookv3/query-the-pool.mdx

fix spelling mistake

---

crates/suiop-cli/src/cli/incidents/mod.rs
crates/suiop-cli/src/cli/slack/mod.rs

- create the cache dir if it doesn't exist
- print out the days when given
tested locally
---

[suiop][inc] minor improvements

---

crates/sui-data-ingestion-core/src/reader.rs

Avoid listing all files in the local directory, as this can increase CPU usage in some setups
---

[data ingestion] avoid ls in collocated setup

---

crates/sui-deepbook-indexer/src/models.rs
crates/sui-deepbook-indexer/src/schema.rs
crates/sui-deepbook-indexer/src/server.rs

Added an endpoint that calculates the net deposits at some timestamp.
---

DeepBook V3 TVL endpoint

---

dapps/multisig-toolkit/package.json
dapps/multisig-toolkit/src/routes/offline-signer.tsx
pnpm-lock.yaml

simplify tx ledger hash in multisig toolkit

---

crates/sui-core/src/execution_cache/writeback_cache.rs

Fix crashes in execution_driver due to inability to execute
transactions.
--------
We must hold the lock for the object entry while inserting to the
`object_by_id_cache`. Otherwise, a surprising bug can occur:
1. A thread executing TX1 can write object (O,1) to the dirty set and
then pause.
2. TX2, which reads (O,1) can begin executing, because
TransactionManager immediately
schedules transactions if their inputs are available. It does not matter
that TX1
hasn't finished executing yet.
3. TX2 can write (O,2) to both the dirty set and the object_by_id_cache.
4. The thread executing TX1 can resume and write (O,1) to the
object_by_id_cache.
Now, any subsequent attempt to get the latest version of O will return
(O,1) instead of
(O,2).
This seems very unlikely, but it may be more likely under …

[cherrypick] Fix possible (but probably rare) race condition (#19951)

---

crates/sui-indexer/src/store/pg_indexer_store.rs

[indexer] committers should read watermark hi directly from table

---

.github/actions/diffs/action.yml
.github/workflows/rust.yml
external-crates/move/crates/move-analyzer/trace-adapter/README.md

Adding pre-land tests for Trace Adapter changes
https://github.com/MystenLabs/sui/actions/runs/11488029510/job/31973922001?pr=19985

[ci]: Adding pre-land tests for Trace Adapter changes

---

crates/sui-core/src/authority/authority_per_epoch_store.rs

Fix bug in `load_initial_object_debts`

---

.github/workflows/cargo-llvm-cov.yml
.github/workflows/docs.yml
.github/workflows/nightly.yml
.github/workflows/release-notes-monitor.yml
.github/workflows/simulator-nightly.yml

Upgrading slack api to v1.27.0 and using slack-message instead of json
👀

Upgrading slack api to v1.27.0 and using slack-message instead of json

---

crates/sui-faucet/src/metrics.rs
crates/sui-faucet/src/metrics_layer.rs

Faucet filtering for paths /v1/gas, /gas, and group all /v1/status
More conditional checks to prevent panic
Tested locally, to confirm on testnet

Faucet Filtering

---

crates/sui-replay/src/replay.rs

Support system tx in replay

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/models/epoch.rs

indexer: handle sui safe mode

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/models/epoch.rs

pick: indexer: handle sui safe mode (#20015)

---

apps/wallet/src/ui/app/components/StakeWarning.tsx
apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx

Stake warning

---

crates/sui-indexer/src/handlers/checkpoint_handler.rs
crates/sui-indexer/src/types.rs

cherry-pick https://github.com/MystenLabs/sui/pull/20015 does not work b/c the codes have been changed recently, this is more like a separate patch, so needs review and will test separately.
---

patch indexer 1.35: deal with safe mode

---

crates/sui-deepbook-indexer/src/server.rs

Update the DeepBook indexer API.
Local testing end to end.
---

DeepBook Indexer: update net balances query

---

docs/content/guides/developer/getting-started/local-network.mdx

Fixes anchor to "Persist local network state" section
Before: https://docs.sui.io/guides/developer/getting-started/local-network#persist-local-network
After: https://sui-docs-git-sp-anchor-patch-sui-foundation.vercel.app/guides/developer/getting-started/local-network#persist-local-network-state
---

[Docs] Update local-network.mdx

---

.vscode/extensions.json

Update workspace recommendations, so that VSCode and GH codespaces recommend the right set for the project.
---

[vscode] Update workspace recommendations

---

.github/workflows/cargo-llvm-cov.yml
.github/workflows/docs.yml
.github/workflows/nightly.yml
.github/workflows/release-notes-monitor.yml

Fix slack messages

---

crates/mysten-util-mem/Cargo.toml
crates/sui-archival/Cargo.toml
crates/sui-json/Cargo.toml
crates/sui-open-rpc/Cargo.toml
crates/sui-storage/Cargo.toml
crates/sui/Cargo.toml

Use more consistency with deps which only have `workspace = true`
---

simplify workspace equal true deps

---

crates/sui-indexer-alt/migrations/2024-10-16-002409_tx_affected_objects/up.sql
crates/sui-indexer-alt/src/handlers/ev_emit_mod.rs
crates/sui-indexer-alt/src/handlers/ev_struct_inst.rs
crates/sui-indexer-alt/src/handlers/kv_checkpoints.rs
crates/sui-indexer-alt/src/handlers/kv_objects.rs
crates/sui-indexer-alt/src/handlers/kv_transactions.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/tx_affected_objects.rs
crates/sui-indexer-alt/src/handlers/tx_balance_changes.rs
crates/sui-indexer-alt/src/lib.rs
crates/sui-indexer-alt/src/models/watermarks.rs
crates/sui-indexer-alt/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs
crates/sui-indexer-alt/src/pipeline/concurrent/watermark.rs
crates/sui-indexer-alt/src/pipeline/mod.rs
crates/sui-indexer-alt/src/pipeline/processor.rs
crates/sui-indexer-alt/src/pipeline/sequential/committer.rs
crates/sui-indexer-alt/src/pipeline/sequential/mod.rs

A collection of already reviewed PRs to land, because I messed up the original PR they were staged in (#20050).
CI
---

indexer-alt: sequential pipeline

---

.changeset/chilly-pillows-remember.md
sdk/kiosk/src/client/kiosk-client.ts

Fix doc comment to match the expected arguments on `getKiosk` call.
---

[kiosk sdk] Fix doc comment

---

crates/sui-indexer/migrations/pg/2024-10-30-005153_drop_tx_sender_and_recipient/down.sql
crates/sui-indexer/migrations/pg/2024-10-30-005153_drop_tx_sender_and_recipient/up.sql
crates/sui-indexer/src/schema.rs

[indexer] drop tx_recipients and tx_senders tables from schema

---

.github/workflows/nightly.yml
.github/workflows/simulator-nightly.yml

Add emoji to slack error messages
👀

Add emoji to slack error messages

---

crates/sui-json-rpc/src/coin_api.rs

This PR fixes a minor inefficiency in the coin metadata api.
It does not need to fetch the transaction, as it only needs the effects. This likely avoids a remote KV fetch.
CI
---

[RPC] Fix coin metadata api inefficiency

---

crates/sui-core/src/authority.rs
crates/sui-types/src/error.rs

Clean up local execution

---

crates/sui-graphql-rpc/src/types/move_registry/named_move_package.rs
crates/sui-mvr-indexer/migrations/pg/2023-08-19-044023_objects/up.sql
crates/sui-mvr-indexer/src/handlers/committer.rs
crates/sui-mvr-indexer/tests/ingestion_tests.rs

[mvr] indexer schema subset and reduced persist tasks

---

Cargo.lock
Cargo.toml
crates/sui-data-ingestion/Cargo.toml
crates/sui-data-ingestion/src/main.rs
crates/sui-kvstore/src/bigtable/mod.rs
crates/sui-kvstore/src/bigtable/worker.rs
crates/sui-kvstore/src/lib.rs
crates/sui-kvstore/src/main.rs

adding BigTable KV as a variant to main binary that manages internal workflows
---

[data ingestion] add support for bigtable in main workflow binary

---

.changeset/good-students-care.md
sdk/build-scripts/src/utils/buildPackage.ts

Build will always treat `src` as the base for outputs when building.
---

Fix build, re-publish @mysten/kms

---

crates/sui-kvstore/src/bigtable/client.rs
crates/sui-kvstore/src/bigtable/init.sh
crates/sui-kvstore/src/lib.rs

Adds support for querying checkpoint by digest
---

[kv store] bigtable. Add support for querying checkpoint by digest

---

crates/sui-indexer-alt/migrations/2024-10-30-142219_obj_versions/down.sql
crates/sui-indexer-alt/migrations/2024-10-30-142219_obj_versions/up.sql
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/obj_versions.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/schema.rs

Pipeline to fill `obj_versions` table -- this is the table that serves "parent version" (dynamic field) queries.
```
indexer --remote-url "https://checkpoints.mainnet.sui.io"                      \
--last-checkpoint 5000
```
- #20089 
---

indexer-alt: obj_versions pipeline

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.38.0 version bump

---

Cargo.lock
Cargo.toml
crates/sui-field-count-main/Cargo.toml
crates/sui-field-count-main/src/lib.rs
crates/sui-field-count/Cargo.toml
crates/sui-field-count/src/lib.rs
crates/sui-indexer-alt/src/models/checkpoints.rs
crates/sui-indexer-alt/src/models/events.rs
crates/sui-indexer-alt/src/models/objects.rs
crates/sui-indexer-alt/src/models/transactions.rs
crates/sui-indexer-alt/src/models/watermarks.rs

title, followup pr of comment on https://github.com/MystenLabs/sui/pull/20126
added new tests for sui-field-count
---

sui-field-count: test in sui-field-count instead and consolidate crates

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority/shared_object_congestion_tracker.rs

Prevents the test from erroneously picking up current protocol config setting for separate randomness congestion control budget.
Is a test fix
---

Bug fix for `test_simulated_load_shared_object_congestion_control`

---

crates/mysten-util-mem/src/external_impls.rs
narwhal/storage/src/node_store.rs

Switching old code to the v1 structs (should be safe since that data is not being used anymore).
---

[beacon] Remove last uses of dkg_v0

---

.changeset/nervous-ears-swim.md
sdk/typescript/src/client/http-transport.ts
sdk/typescript/test/unit/client/http-transport.test.ts

revert client-request-header

---

docs/content/concepts/cryptography/transaction-auth/keys-addresses.mdx

Errant repetition
baleeted
---

[docs] remove redundant SLIP-0010 mention

---

crates/sui-graphql-rpc/src/types/balance.rs
crates/sui-graphql-rpc/src/types/coin.rs

[graphql][cherry-pick] need to add object_status=0 to use partial indexes (#20176)

---

.github/workflows/changesets-ci.yml
.github/workflows/release.yml
.github/workflows/turborepo.yml

Upgrade Artifact Upload actions
👀

Upgrade Artifact Upload actions

---

crates/sui-graphql-rpc/src/types/balance.rs
crates/sui-graphql-rpc/src/types/coin.rs

[cherry-pick][gql] need to add object_status=0 to use partial indexes (#20176)

---

crates/sui-bridge/src/client/bridge_authority_aggregator.rs

[Bridge Node] CP predelay fix

---

docs/content/standards/kiosk-apps.mdx
docs/content/standards/kiosk.mdx

Updates syntax examples on [Kiosk and Kiosk Apps pages](https://docs.sui.io/standards/kiosk)
---

[docs] Move 2024 Kiosk, Kiosk Apps

---

docs/content/standards/display.mdx

Updates outdated examples on the [display page](https://docs.sui.io/standards/display).
---

[docs] Update Display page

---

Cargo.lock
Cargo.toml
crates/mysten-util-mem/src/external_impls.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/consensus_validator.rs
crates/sui-core/src/epoch/randomness.rs
crates/sui-network/src/randomness/mod.rs
crates/sui-network/src/randomness/tests.rs
crates/sui-types/src/crypto.rs
crates/sui-types/src/messages_consensus.rs
narwhal/storage/src/node_store.rs

Update fastcrypto, including moving some structs between dkg->dkg_v1

---

crates/sui-indexer-alt/migrations/2024-11-02-160143_kv_epochs/down.sql
crates/sui-indexer-alt/migrations/2024-11-02-160143_kv_epochs/up.sql
crates/sui-indexer-alt/src/bootstrap.rs
crates/sui-indexer-alt/src/handlers/kv_epoch_ends.rs
crates/sui-indexer-alt/src/handlers/kv_epoch_starts.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/handlers/tx_calls.rs
crates/sui-indexer-alt/src/main.rs
crates/sui-indexer-alt/src/models/epochs.rs
crates/sui-indexer-alt/src/schema.rs

I partially simplified the naming of `tx_calls_fun` to `tx_calls` but did not do a complete job -- this change completes it.
CI
- #20118 
- #20132 
- #20147 
- #20148 
- #20149 
- #20150
---

chore(indexer-alt): rename tx_calls_fun -> tx_calls

---

crates/sui-indexer-alt/src/pipeline/sequential/committer.rs

If we did not collect anything to the batch, we should not commit to the DB. We should also avoid reporting any metrics.
CI
---

[indexer-alt] Skip commit if batch is empty

---

.changeset/loud-pianos-compare.md
.changeset/witty-adults-notice.md
sdk/zksend/src/links/claim.ts
sdk/zksend/src/wallet/channel/index.ts

[zksend] add claimedBy property when loading assets of claimed link

---

.changeset/healthy-horses-knock.md
sdk/zksend/src/index.test.ts
sdk/zksend/src/links/builder.ts
sdk/zksend/src/links/claim.ts
sdk/zksend/src/links/list-created-links.ts

[zksend] Update garphql query, and use getstashed.com as claim api host

---

crates/sui-data-ingestion/src/main.rs

Pass filename with credential parameters to the ingestion binary 
---

[data ingestion] bigtable: set env credentials parameter

---

crates/sui-indexer-alt/src/metrics.rs
crates/sui-indexer-alt/src/pipeline/processor.rs

[indexer-alt] Add processor lag metrics

---

.github/workflows/release.yml

Use tracing feature for sui builds
👀

Use tracing feature for sui builds

---

docs/content/guides/developer/getting-started/sui-install.mdx
docs/content/references/cli.mdx
docs/content/references/cli/client.mdx

Update docs for installing the Sui CLI to include `--features tracing` so that they work with the trace viewer/debugger.
👀

[docs] Update Sui CLI install instructions to include the tracing feature

---

.changeset/two-shirts-guess.md
sdk/deepbook-v3/src/utils/constants.ts

Create NS Deepbook Pools:
1. NS/SUI
2. NS/USDC
Mainnet and locally

NS Deepbook Pools

---

.changeset/curly-timers-wink.md
sdk/zksend/src/links/claim.ts

zksend sdk fix network detection

---

crates/sui-core/src/traffic_controller/policies.rs

False positives stem from IP collisions during traffic tallying. Because validators tend to see closely correlated transaction  execution traffic patterns, it is possible that a false positive resulting in an erroneously blocked IP could be correlated across many validators at the same time. If this happens on a quorum of validators, this would result in an IP being effectively denied service until the TTL expires.
Luckily, we can exploit this property to lower the effective false positive rate (as observed by the client) by removing this correlation. This PR adds a salt key to the `SketchKey`. The value is generated in memory at startup.
Existing tests
--- …

[TrafficControl] Add salt to TrafficSketch

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui `v1.39.0` Version Bump

---

sdk/move-bytecode-template/README.md

1. The `Coin` example URL has been updated.  
2. The usage of `bcs.vector(bcs.string())` has been changed to `bcs.string()`, based on `test/universal.test`.  
3. A link to the contract deployment documentation has been added to assist developers in the process.
---

Update move-bytecode-template README.md

---

crates/sui-indexer-alt/src/handlers/kv_feature_flags.rs

indexer-alt: fix kv_feature_flags name

---

docs/content/guides/developer/app-examples/tic-tac-toe.mdx

Updates the smart contract section of the tic tac toe app example
---

[docs] Added info box for source code at beginning of doc

---

.changeset/violet-ants-attend.md
sdk/dapp-kit/src/components/connect-modal/views/ConnectionStatus.tsx
sdk/dapp-kit/src/components/connect-modal/wallet-list/WalletListItem.tsx

[dapp-kit] ensure that wallet-icon is a non-empty string

---

.changeset/blue-avocados-float.md
sdk/deepbook-v3/src/transactions/governance.ts

SDK governance bug fix
Locally and testnet
---

SDK Gov Bug

---

package.json
pnpm-lock.yaml

combine pnpm overrides in package.json

---

crates/sui/src/keytool.rs

add some more useful outputs to this command, useful to examine a zklogin signature. 
---

fix: add more details to zklogin sig verify

---

crates/sui-indexer-alt/src/handlers/kv_objects.rs
crates/sui-indexer-alt/src/handlers/obj_versions.rs
crates/sui-indexer-alt/src/handlers/tx_affected_objects.rs
crates/sui-indexer-alt/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs

We are currently bottlenecked on the commit throughput. Increase commit concurrency to improve throughput.
---

[indexer-alt] Increase commit concurrency

---

external-crates/move/crates/move-analyzer/trace-adapter/src/trace_utils.ts
external-crates/move/crates/move-analyzer/trace-debug/README.md
external-crates/move/crates/move-analyzer/trace-debug/package.json
external-crates/move/crates/move-analyzer/trace-debug/src/extension.ts

This PR updates the extension's README file and finesses some checks and error messages issues when traces cannot be found or are empty.
Tested manually

[trace-view] Updated README file and finessed error checks

---

Cargo.lock
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/query.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
crates/sui-json-rpc-api/src/coin.rs
crates/sui-open-rpc/spec/openrpc.json

Document the cases when CoinMetadata RPCs could fail to return a response.
:eyes:
---

docs: document CoinMetadata-related RPCs

---

.changeset/tasty-hotels-occur.md
sdk/deepbook-v3/src/utils/constants.ts

Typus pool
Mainnet Verification
---

Typus pool

---

docs/content/concepts/sui-move-concepts/packages/upgrade.mdx

A small fix in the commands output for publish/upgrade in the docs.
---

Fix the output in the publish/upgrade commands

---

docs/content/references/cli/ptb.mdx

Users often cannot figure it out that they need quotes due to their shell, so let's add them.
---

Add quotes around examples' arrays

---

external-crates/move/crates/move-analyzer/editors/code/README.md

[move-ide] Corrected a link to the trace debugging extension

---

external-crates/move/crates/move-analyzer/editors/code/scripts/create.sh
external-crates/move/crates/move-analyzer/editors/code/scripts/create_from_local.sh

[move-ide] Publishing/packaging scripts fixes

---

crates/sui-indexer-alt/src/pipeline/concurrent/mod.rs

Increase batch size by ~5X
---

[indexer-alt] 5X default chunk row size

---

.changeset/brown-files-smell.md
sdk/deepbook-v3/src/utils/constants.ts

AUSD Coin
Verified https://suiscan.xyz/mainnet/coin/0x2053d08c1e2bd02791056171aab0fd12bd7cd7efad2ab8f6b9c8902f14df2ff2::ausd::AUSD/txs
---

AUSD Coin (Deepbook SDK)

---

crates/sui-rosetta/src/state.rs

fetch transactions in smaller chunks to prevent rpc 502 error
fetch transactions concurrently to improve performance
covered by unit test and tested locally
---

[rosetta] - rosetta multiGetTransactionBlocks performance fix

---

crates/sui-indexer-alt/src/lib.rs

- Catch issues like the one we had with `kv_feature_flags` which was incorrectly named `kv_protocol_configs` (copypasta error). This will now fail when the pipeline is added the second time (by name).
- Produce an error if the a value is passed to the `--pipeline` flag that is not supported at all. This should catch pipeline name typos more easily.
Recreate the scenario with `kv_feature_flags` -- the indexer will panic before it starts in that case.
Test various configurations of the indexer (no pipeline filtering, valid filtering, and invalid filtering):
```
sui$ cargo run -p sui-indexer-alt --release --                                 \
--database-url postgres://postgres:postgrespw@localhost:5432/sui_indexer_alt \
indexer --remote-store-url https://checkpoints.mainnet.sui.io/ …
```

indexer-alt: extra checks for --pipeline

---

apps/wallet/src/shared/sentry-config.ts

Reduce the volume of events sent to sentry from the wallet extension
N/A
---

[wallet-ext]: set sentry sample rate

---

crates/sui-rosetta/src/state.rs

fetch transactions in smaller chunks to prevent rpc 502 error fetch transactions concurrently to improve performance
(cherry picked from commit c57d97cc398b9752f20bad3f50056661a5a77f06)
---

[cherrypick][rosetta] - rosetta multiGetTransactionBlocks performance fix (#20386)

---

crates/sui-rosetta/src/operations.rs

do not attempt to parse programmable transaction for failed transactions to avoid parsing error
---
--- …

[cherrypick][main] - rosetta failed pt fix (#20411)

---

external-crates/move/crates/move-compiler/src/shared/unique_map.rs

- Added ParallelIterator APIs to UniqueMap 
- Used in a later API 
---

[move-compiler] Add rayon parallel iterator API to UniqueMap

---

.changeset/calm-weeks-rescue.md
sdk/bcs/src/bcs.ts

[bcs] accept Array<number> in bcs.bytes(n).serialize

---

crates/sui-indexer-alt/src/pipeline/concurrent/committer.rs

The tx_rows_committed metric was polluted by empty values.
Fixing it by skipping the entire commit if values is empty.
clippy
---

[indexer-alt] Skip all commit metrics if values is empty

---

crates/sui-indexer-alt/src/handlers/tx_affected_addresses.rs
crates/sui-indexer-alt/src/lib.rs

Pluralize it to match the other instances of the name.
CI
- #20459 
- #20460 
- #20461 
- #20462 
- #20463 
- #20464 
---

chore(indexer-alt): rename TxAffectedAddress(es)

---

crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-watchdog/eth_vault_balance.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_bridge_watchdog/eth_vault_balance.rs
crates/sui-bridge/src/sui_bridge_watchdog/metrics.rs
crates/sui-bridge/src/utils.rs
crates/sui-core/src/traffic_controller/policies.rs

[Bridge] Support other vault metrics

---

crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-watchdog/eth_vault_balance.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_bridge_watchdog/eth_vault_balance.rs
crates/sui-bridge/src/sui_bridge_watchdog/metrics.rs
crates/sui-bridge/src/utils.rs

[Bridge] Support other vault metrics (#20431)

---

crates/sui-types/src/object.rs
sui-execution/latest/sui-adapter/src/temporary_store.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs

Implement ConsensusV2 object handling in sui-execution

---

.changeset/hot-melons-do.md
sdk/deepbook-v3/src/utils/constants.ts

Deepbook AUSD Pools
Tested on mainnet
---

Deepbook AUSD Pools

---

crates/sui-bridge-indexer/src/storage.rs
crates/sui-deepbook-indexer/src/sui_deepbook_indexer.rs
crates/sui-indexer-builder/src/indexer_builder.rs
crates/sui-indexer-builder/tests/indexer_test_utils.rs
crates/sui-indexer-builder/tests/indexer_tests.rs

[app indexer] - fix backfill task creation bug

---

crates/sui-deepbook-indexer/src/server.rs

Switch Deepbook Indexer timestamp from on chain timestamp to checkpoint timestamp
Tested locally
---

Switch Deepbook Indexer timestamp

---

apps/wallet/src/ui/app/staking/home/StakedCard.tsx

fix inactive staking principal + reward bug

---

.github/workflows/release.yml

Fix Postgres install for Ubuntu arm64
https://github.com/MystenLabs/sui/actions/runs/12165389193/job/33929259919

Fix postgres install for Ubuntu arm64

---

Cargo.lock
Cargo.toml

This should fix advisory error.
https://github.com/MystenLabs/sui/actions/runs/12173834445/job/33954833316?pr=20511
---

Move pprof to v0.14.0

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.40.0 Version Bump

---

external-crates/move/crates/move-analyzer/trace-debug/src/extension.ts

Inconsequential text update

---

docs/content/concepts/transfers/custom-rules.mdx
docs/content/concepts/transfers/transfer-to-object.mdx
docs/site/src/theme/prism-move.js

- Current examples and code will not compile in the current edition 2024.
- Adds prismJS support for module labels
Hint: when reviewing, use "ignore whitespace changes" flag.
See for yourself.
---

[docs] Fix move examples on the tto page

---

crates/sui-deepbook-indexer/src/migrations/00000000000000_diesel_initial_setup/down.sql
crates/sui-deepbook-indexer/src/migrations/00000000000000_diesel_initial_setup/up.sql
crates/sui-deepbook-indexer/src/schema.rs
crates/sui-deepbook-indexer/src/server.rs

Deepbook Asset Endpoint for Coinmarketcap
Endpoints: `/assets`
Example Response:
`{"NS":{"can_deposit":"true","unified_cryptoasset_id":"32942","can_withdraw":"true","name":"Sui Name Service","contractAddressUrl":"https://suiscan.xyz/mainnet/object/0x5145494a5f5100e645e4b0aa950fa6b68f614e8c59e17bc5ded3495123a79178","contractAddress":"0x5145494a5f5100e645e4b0aa950fa6b68f614e8c59e17bc5ded3495123a79178"},"WUSDT":{"name":"Wormhole USDT","unified_cryptoasset_id":"825","can_deposit":"true","contractAddressUrl":"https://suiscan.xyz/mainnet/object/0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c","contractAddress":"0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c","can_withdraw":"true"},"DEEP":{"contractAddress":"0xdeeb7a4662eec9f2f3def03fb937a663dddaa2e215b8078a …

Deepbook Asset Endpoint

---

crates/sui-deepbook-indexer/src/migrations/00000000000000_diesel_initial_setup/down.sql
crates/sui-deepbook-indexer/src/migrations/00000000000000_diesel_initial_setup/up.sql
crates/sui-deepbook-indexer/src/schema.rs
crates/sui-deepbook-indexer/src/server.rs

`/trades/:pool_name
`Gets the last trade in the pool
`/trades/SUI_USDC
`Response:
`[{"price":4.243,"base_volume":2.4,"quote_volume":10.1832,"timestamp":1733423352023,"type":"buy","trade_id":"170141183460547501266792053343391045163"}]`
Tested locally

Deepbook trades endpoint

---

crates/sui-deepbook-indexer/src/migrations/00000000000000_diesel_initial_setup/down.sql
crates/sui-deepbook-indexer/src/migrations/00000000000000_diesel_initial_setup/up.sql
crates/sui-deepbook-indexer/src/schema.rs
crates/sui-deepbook-indexer/src/server.rs

Deepbook Ticker Endpoint: /ticker
All volumes are last 24 hour volume
Example output:
`{"DEEP_SUI":{"base_volume":9709100.0,"last_price":0.0184,"quote_volume":177605.1862,"isFrozen":0},"TYPUS_SUI":{"base_volume":430297.7,"last_price":0.01833,"isFrozen":0,"quote_volume":8493.539347},"SUI_USDC":{"base_volume":4805064.8,"isFrozen":0,"last_price":4.201,"quote_volume":19079955.3245},"BETH_USDC":{"isFrozen":0,"last_price":2700.0,"base_volume":0.0,"quote_volume":0.0},"WUSDC_USDC":{"last_price":1.0,"isFrozen":0,"quote_volume":2958711.879164,"base_volume":2958725.3},"NS_SUI":{"quote_volume":76370.840897,"base_volume":1079970.7,"last_price":0.0665,"isFrozen":0},"DEEP_USDC":{"quote_volume":2390833.2166,"base_volume":34107590.0,"isFrozen":0,"last_price":0.07713},"NS_USDC":{"quote_volume":610367.235184 …

Deepbook Ticker Endpoint

---

dapps/multisig-toolkit/README.md
dapps/multisig-toolkit/package.json
dapps/multisig-toolkit/src/components/menu.tsx
dapps/multisig-toolkit/src/index.css
dapps/multisig-toolkit/src/plugins/doc-render.ts
dapps/multisig-toolkit/src/routes/help.tsx
dapps/multisig-toolkit/src/routes/index.tsx
dapps/multisig-toolkit/src/schema/Heading.markdoc.js
dapps/multisig-toolkit/tsconfig.node.json
dapps/multisig-toolkit/vite.config.ts
pnpm-lock.yaml

Add Help View to multisig toolkit
(updates/rebases: #20221 )
---

Add Help View to Multisig Toolkit

---

crates/sui-mvr-indexer/src/handlers/pruner.rs

also remove tx_recipients and tx_senders tables from Pruner on MVR

---

crates/sui-deepbook-indexer/src/server.rs

Balance Manager Volume Endpoint in Pool Names:
Endpoint 1: `/historical_volume_by_balance_manager_id/:pool_names/:balance_manager_id`
Example Call: `/historical_volume_by_balance_manager_id/SUI_USDC,DEEP_USDC/0x47dcbbc8561fe3d52198336855f0983878152a12524749e054357ac2e3573d58`
Example Response:
`{"DEEP_USDC":[1938666151700,0],"SUI_USDC":[5934906021900,399057445200]}
`
Endpoint 2: `/historical_volume_by_balance_manager_id_with_interval/:pool_names/:balance_manager_id`
Example Call: `/historical_volume_by_balance_manager_id_with_interval/SUI_USDC,DEEP_USDC/0x47dcbbc8561fe3d52198336855f0983878152a12524749e054357ac2e3573d58`
Example Response:
`{"[1733698873, 1733702473]":{"SUI_USDC":[45030523600,200939800],"DEEP_USDC":[50335077700,0]},"[1733738473, …

Balance Manager Volume Endpoint in Pool Names (Deepbook Indexer)

---

Cargo.lock
Cargo.toml
crates/sui-rpc-api/src/client/mod.rs

grpc: properly configure a tls config on clients when https is requested

---

crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-types/src/dynamic_field.rs
crates/sui-types/src/sui_serde.rs

types: support decoding from both base64 as well as base58

---

sdk/signers/tests/e2e-aws-kms.test.ts
sdk/signers/tests/e2e-gcp-kms.test.ts

[sdk][signers]: add e2e enable flag check

---

crates/sui-indexer-alt-framework/src/pipeline/concurrent/commit_watermark.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
crates/sui-indexer-alt-framework/src/pipeline/logging.rs
crates/sui-indexer-alt-framework/src/pipeline/mod.rs
crates/sui-indexer-alt-framework/src/pipeline/sequential/committer.rs

[indexer-alt] Log TPS and CPS in all pipelines

---

crates/sui-framework/docs/sui-framework/package.md
crates/sui-framework/packages/sui-framework/sources/package.move

Community request

---

.github/workflows/turborepo.yml

Updated action version

---

crates/sui-indexer-alt/src/config.rs
crates/sui-indexer-alt/src/handlers/coin_balance_buckets_pruner.rs
crates/sui-indexer-alt/src/handlers/mod.rs
crates/sui-indexer-alt/src/lib.rs

[indexer-alt] Add coin_balance_buckets_pruner

---

docs/content/concepts/tokenomics/sui-bridging.mdx

Wormhole has published a great tutorial for Wormhole Connect X Sui. Adding a link to that tutorial.
---

[docs][easy] Adding wormhole link to tutorial

---

crates/sui-graphql-rpc/src/config.rs
crates/sui-mvr-graphql-rpc/src/config.rs

Move to mainnet constants!
---

[mvr] Hardcode mainnet pkg

---

Cargo.lock
deny.toml

cargo-deny: fix some of the warnings and the recent RUSTSEC-2024-0421 advisory

---

crates/sui/src/client_ptb/ptb.rs
crates/sui/src/displays/dev_inspect.rs

This PR fixes the `sui client ptb --dev-inspect` command to correctly display the result of the dev inspect.
---

[CLI][Cherry-Pick] Cherry pick #20599

---

external-crates/move/crates/move-binary-format/src/compatibility.rs
external-crates/move/crates/move-binary-format/src/inclusion_mode.rs
external-crates/move/crates/move-binary-format/src/lib.rs
external-crates/move/crates/move-binary-format/src/unit_tests/compatibility_tests.rs

add mode to inclusion check

---

scripts/update_all_snapshots.sh

scripts: fix update_all_snapshots.sh

---

.changeset/brave-turtles-clap.md
sdk/deepbook-v3/src/utils/constants.ts

DRF token in Deepbook
Constant update only in SDK

New Token in Deepbook

---

apps/wallet/src/background/accounts/index.ts
apps/wallet/src/background/accounts/zklogin/ZkLoginAccount.ts
apps/wallet/src/ui/app/hooks/useQueryTransactionsByAddress.ts

import legacy/non-legacy zklogin accounts

---

apps/wallet/src/background/accounts/zklogin/ZkLoginAccount.ts

[wallet] Always add legacy accounts

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

Add FanTV OIDC provider in prod environment.

---

.changeset/fifty-bottles-sleep.md
sdk/deepbook-v3/src/utils/constants.ts

Deepbook Pool Constant for DRF/SUI
Constant only, tested in mainnet

Deepbook Pool Constant

---

scripts/update_all_snapshots.sh

fix update_all_snapshots.sh

---

crates/sui-graphql-rpc/src/data/move_registry_data_loader.rs
crates/sui-graphql-rpc/src/metrics.rs
crates/sui-graphql-rpc/src/server/builder.rs
crates/sui-mvr-graphql-rpc/README.md
crates/sui-mvr-graphql-rpc/src/data/move_registry_data_loader.rs
crates/sui-mvr-graphql-rpc/src/metrics.rs
crates/sui-mvr-graphql-rpc/src/server/builder.rs

To resolve the mvr table on testnet, we consult the mainnet graphql service. We previously observed some slowness around dns lookup, so this metric will help track whether the issue persists. Also added to `sui-graphql-rpc` crate.
---
--- …

[mvr] Cherry pick mvr external resolution (#20633)

---

crates/sui-json-rpc-types/src/lib.rs
crates/sui-json-rpc-types/src/sui_event.rs
crates/sui-open-rpc/spec/openrpc.json

jsonrpc: correctly serialize bcsName field

---

crates/sui-benchmark/tests/simtest.rs

Seems causing high error rate.
---

Turn off randomized tx workload

---

crates/sui-indexer-alt-framework/src/ingestion/client.rs
crates/sui-indexer-alt-framework/src/metrics.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/commit_watermark.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/committer.rs
crates/sui-indexer-alt-framework/src/pipeline/mod.rs
crates/sui-indexer-alt-framework/src/pipeline/processor.rs

Indexer alt add more lag metrics

---

pnpm-lock.yaml
sdk/docs/pages/typescript/zklogin.mdx

[docs] fix typo in legacyAddress docs

---

.changeset/pretty-rules-sort.md
sdk/typescript/src/transactions/ObjectCache.ts
sdk/typescript/src/transactions/executor/serial.ts

[sdk] remove duplicate call to applyAffects in SerialTransactionExecutor

---

.changeset/cool-mails-confess.md
pnpm-lock.yaml
sdk/typescript/package.json
sdk/typescript/src/keypairs/ed25519/ed25519-hd-key.ts
sdk/typescript/src/keypairs/ed25519/keypair.ts
sdk/typescript/src/keypairs/ed25519/publickey.ts
sdk/typescript/test/e2e/data/coin_metadata/Move.lock
sdk/typescript/test/e2e/data/dynamic_fields/Move.lock
sdk/typescript/test/e2e/data/id_entry_args/Move.lock
sdk/typescript/test/e2e/data/serializer/Move.lock
sdk/typescript/test/unit/cryptography/ed25519-keypair.test.ts

[sdk] remove dependency on tweetnacl

---

.github/workflows/bridge.yml

Update foundry install in workflow

---

scripts/config-traffic-control.sh

A script to somewhat simplify the process of determining how to configure TrafficController in cases where nodes are running behind proxies or other infra. See usage comment in code for more context.
```yaml
ubuntu@jnb-tnt-val-00:~$ journalctl -fu sui-node | ./config-traffic-control.sh "95.217.193.168"
x-forwarded-for contents: 95.217.193.168
Configuration:
client-id-source:
x-forwarded-for: 1
```
---

[Traffic Control] Introduce script to aid in configuration

---

.github/workflows/bridge.yml

Fix install foundryup workflow
---

Fix install foundryup workflow

---

.github/PULL_REQUEST_TEMPLATE.md
scripts/release_notes.py

chore: update PR template

---

crates/sui/src/client_commands.rs

Ensure that the RPC error is correctly propagated when gas estimate fails, because it fails due to some other error.
---

[CLI] Pass the RPC error if estimating gas budget fails

---

CONTRIBUTING.md

PR #17253 moved the location of the Sui environment setup file. This PR adjusts sources to changes.
Checked the doc.
---

fix: update Sui environment setup

---

crates/sui-config/src/node.rs

Should fix performance regression at high TPS

Increase default backpressure threshold

---

crates/sui-benchmark/tests/simtest.rs

Other tests require more fixes.
---

Turn on randomized workload in congestion control simtest

---

docs/content/guides/developer/cryptography/multisig.mdx

Updates the multisig guide topic.
Local
---

[docs] Updates the multisig guide

---

crates/sui-benchmark/tests/simtest.rs

fix congestion control simtest for enabled burst mode

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.41.0 Version Bump

---

docs/content/guides/developer/sui-101/using-events.mdx

Update EventFilter type in guide documentation
---

[docs] Update EventFilter type in guide documentation

---

crates/sui-edge-proxy/README.md
crates/sui-edge-proxy/src/handlers.rs

[edge-proxy] add readme + remove noisy log

---

crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
crates/sui-types/src/test_checkpoint_data_builder.rs

[indexer-alt] Add tests for balance bucket pipeline

---

docker/sui-tools/Dockerfile

[docker] Install git in the sui-tools Docker image

---

crates/suiop-cli/src/cli/incidents/selection.rs

Just add more messaging to make this clearer
https://mysten-labs.slack.com/archives/C03QJ1B6BC0/p1736273598607139
---

[suiop][incident-selection] make it clearer that only newly scheduled incidents are listed

---

docs/content/guides/developer/nft/asset-tokenization.mdx
docs/content/guides/developer/nft/nft-rental.mdx
docs/content/guides/developer/sui-101/sponsor-txn.mdx
nre/ansible/README.md

This PR fixes a number of typos in docs.

fix typos in documentation files

---

crates/sui-rpc-api/generate-grpc-docs.sh
crates/sui-rpc-api/proto/documentation.json

rpc: output grpc documentation to json

---

docs/content/concepts/object-model.mdx
docs/site/src/components/ProtocolConfig/index.tsx

Instead of displaying all fields, display only select ones.
---

[docs] Protocol config

---

crates/sui/src/unit_tests/fixtures/upgrade_errors/enum_errors_v1/sources/UpgradeErrors.move
crates/sui/src/unit_tests/fixtures/upgrade_errors/enum_errors_v2/sources/UpgradeErrors.move
crates/sui/src/unit_tests/fixtures/upgrade_errors/struct_errors_v1/sources/UpgradeErrors.move
crates/sui/src/unit_tests/fixtures/upgrade_errors/struct_errors_v2/sources/UpgradeErrors.move
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__additive.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__addresses_first.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__declarations_missing.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__emoji.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__empty.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__enum.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__package_no_name.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__starts_second_line.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__struct.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__version_mismatch.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__whitespace.snap
crates/sui/src/unit_tests/upgrade_compatibility_tests.rs
crates/sui/src/upgrade_compatibility/formatting.rs
crates/sui/src/upgrade_compatibility/mod.rs

- improves comments
- format type params within structs
- remove dead code
---

improve comments, format type params within structs and enums

---

crates/sui-indexer-alt/src/consistent_pruning.rs
crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
crates/sui-indexer-alt/src/handlers/obj_info.rs

If we cannot prune some checkpoint due to checkpoint not yet processed, we must not remove the any of the prune information from the same batch, since we will need to retry them all together later.
Given how tricky this is, we should definitely make this part of framework, instead of re-implementing it again.
Added tests.
---

[indexer-alt] Fix a bug in consistent pruner due to partial pruning

---

crates/sui-snapshot/src/uploader.rs

fixes a frustrating case where remote bucket listing is failing, but all we see is this single log:
```
{"timestamp":"2025-01-15T19:15:56.553536Z","level":"ERROR","fields":{"message":"Failed to find missing state snapshot in remote store"},"target":"sui_snapshot::uploader","filename":"crates/sui-snapshot/src/uploader.rs","line_number":196}
{"timestamp":"2025-01-15T19:16:56.551386Z","level":"ERROR","fields":{"message":"Failed to find missing state snapshot in remote store"},"target":"sui_snapshot::uploader","filename":"crates/sui-snapshot/src/uploader.rs","line_number":196}
{"timestamp":"2025-01-15T19:17:56.557892Z","level":"ERROR","fields":{"message":"Failed to find missing state snapshot in remote store"},"target":"sui_snapshot::uploader","filename":"crates/sui-snapshot/src/uploader.rs"," …
```

[fix] log error when skipping formal snapshot upload

---

crates/sui-faucet/src/server.rs

The previous code will panic when starting localnet with the faucet needed for running local tests as the two envs are not set!
---

[faucet-fix] Correctly unwrap stuff

---

.github/workflows/github-issues-monitor.yml

Add a comment when a new issue is opened

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.42.0 Version Bump

---

crates/sui-framework/docs/sui/object_table.md
crates/sui-framework/docs/sui/table.md
crates/sui-framework/packages/sui-framework/sources/object_table.move
crates/sui-framework/packages/sui-framework/sources/table.move

docs: fix typo

---

crates/sui-source-validation-service/tests/tests.rs
crates/sui/src/client_commands.rs
crates/sui/src/lib.rs
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__addresses_first.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__declarations_missing.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__deponly.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__emoji.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__empty.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__package_no_name.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__starts_second_line.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__whitespace.snap
crates/sui/src/unit_tests/upgrade_compatibility_tests.rs
crates/sui/src/upgrade_compatibility/formatting.rs
crates/sui/src/upgrade_compatibility/mod.rs
crates/sui/tests/cli_tests.rs

Enable upgrade compatibility checks for package upgrades

---

crates/sui-indexer-alt-schema/migrations/2024-10-30-142219_obj_versions/up.sql

Adds a new index to support bounded query.
I plan to merge this before I nuke the DB and start the race.
---

[indexer-alt] Update obj_version indexes

---

crates/sui-bridge-indexer/README.md
crates/sui-data-ingestion-core/src/reader.rs
docs/content/guides/developer/advanced/custom-indexer.mdx
examples/custom-indexer/rust/remote_reader.rs

Revert "[data ingestion] redirect traffic to the bucket directly"

---

crates/sui-framework/docs/sui/object.md
crates/sui-framework/packages/sui-framework/sources/object.move

typo fix in docs

---

docs/content/guides/developer/app-examples/e2e-counter.mdx
docs/content/guides/developer/app-examples/trustless-swap.mdx
docs/content/guides/developer/getting-started.mdx
docs/content/guides/developer/getting-started/get-coins.mdx
docs/content/snippets/faucet-online.mdx
docs/content/snippets/publish-to-devnet-with-coins.mdx

[docs] Faucet update

---

external-crates/move/crates/move-binary-format/src/errors.rs
external-crates/move/documentation/book/src/method-syntax.md
external-crates/move/documentation/coding_guidelines.md

docs: fix some typos

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/state_accumulator.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-node/src/lib.rs
crates/sui-single-node-benchmark/src/single_node.rs

- Remove EpochFlag::ExecutedInEpochTable
- Remove StateAccumulatorV1
- Remove EpochFlag::WritebackCacheEnabled

Remove old Epoch Flags

---

crates/suiop-cli/src/cli/ci/image.rs
crates/suiop-cli/src/cli/ci/mod.rs
crates/suiop-cli/src/cli/mod.rs
crates/suiop-cli/src/main.rs

Make it so you can simplify 
`suiop ci image query --repo-name sui`
to 
`suiop im -r sui`
and 
`suiop ci image build --repo-name sui-operations --dockerfile docker/example-service/Dockerfile`
to
`suiop build -r sui-operations -d docker/example-service/Dockerfile`
```
suiop image --repo-name sui
Requested query for repo: sui
╭───────────┬───────────┬─────────────────────────┬─────────────────────╮
│ name      │ status    │ Start Time (Local Time) │ End Time            │
├───────────┼───────────┼─────────────────────────┼─────────────────────┤
│ sui-ex2mf │ Succeeded │ 2025-01-22 12:03:14     │ 2025-01-22 12:16:26 │
╰───────────┴───────────┴─────────────────────────┴─────────────────────╯
```
```
suiop build --repo-name sui-operations --dockerfile docker/example-service/Dockerfile
Requested …
```

[suiop] alias "image" command to make it easier to use

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_72.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_73.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_72.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_73.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_73.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Move `use_object_per_epoch_marker_table_v2` to protocol v73

---

crates/sui-config/data/fullnode-template.yaml

add p2p-config to fullnode-template

---

Cargo.lock
crates/sui-deepbook-indexer/Cargo.toml
crates/sui-deepbook-indexer/src/server.rs

CORS Update to allow cross origin requests
Tested locally using a local server calling the endpoint from a different origin

Deepbook Indexer CORS Update

---

crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__deponly.snap
crates/sui/src/upgrade_compatibility/mod.rs

[cli] reword new declaration errors

---

consensus/core/src/block_manager.rs

Blocks reported as missing via the `block_manager.try_fetch_blocks` method because they are not added in the `missing_ancestors` map they are not picked up for cleaning via the Garbage Collection mechanism. Those blocks are then picked up by the periodic synchronizer to fetch - which is unnecessary - and even worse, since the majority of the network might have already rejected them there aren't many many authorities around which actually have the blocks available to serve. That leads to the periodic synchronizer constantly working and not able to fetch any of those blocks.
This PR is fixing this behaviour by adding the blocks in the `missing_ancestors` map so they are properly picked up by GC for clean up.
Wrote a test which confirmed the existing behaviour (blocks are stuck in the block …

[Consensus] fix GC missing blocks reported via the try_fetch_blocks method

---

crates/sui-deepbook-indexer/src/server.rs

1. taker_balance_manager_id and maker_balance_manager_id included with each trade
2. taker_order_id and maker_order_id included with each trade
Optional Filters:
1. limit: defaults to 1 (number of trades to be included in result). Most recent trades are always included first.
2. taker_balance_manager_id: defaults to no filter
3. maker_balance_manager_id: defaults to no filter
4. start_time: unix timestamp in seconds, defaults to 24hrs before end_time
5. end_time: unix timestamp in seconds, defaults to current time
Sample query:
`trades/SUI_USDC?start_time=1738093405&end_time=1738096485&limit=2&maker_balance_manager_id=0x344c2734b1d211bd15212bfb7847c66a3b18803f3f5ab00f5ff6f87b6fe6d27d&taker_balance_manager_id=0x47dcbbc8561fe3d52198336855f0983878152a12524749e054357ac2e3573d58`
Sample …

Deepbook Indexer Trades Endpoint Update

---

crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__additive.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__addresses_first.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__all.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__declarations_missing.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__emoji.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__empty.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__package_no_name.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__starts_second_line.snap
crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__whitespace.snap
crates/sui/src/upgrade_compatibility/mod.rs

- capitalize letter on declarations and notes
- remove unneeded var = var
snapshots
---

[cli] upgrade errors capitalize letter on declarations, remove unneeded format var = var

---

crates/sui-json-rpc/src/lib.rs

The jsonrpsee library is artificially limiting the number of concurrent requests that the server can process to ~100 since its treating each request as a separate connection. In order to work around this we can just set the maximum number of connections for the jsonrpsee service to a high number since its not actually controlling the number of connections.
---

jsonrpc: unlimit the number of concurrent jsonrpc requests

---

crates/sui-faucet/src/metrics.rs
crates/sui-faucet/src/server.rs

Needed to add another route for discord bot, which is unrestricted now. In case it's needed, we can put specific rate limiting to it.
It's been running in prod for a few days now (🙈 )
---

Faucet discord

---

consensus/core/src/core.rs

[consensus] add remaining tests for smart ancestor selection

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.43.0 Version Bump

---

crates/sui-bridge/src/action_executor.rs
crates/sui-bridge/src/metrics.rs
crates/sui-types/src/traffic_control.rs

This will allow us to more easily track progress and volume on bridge node.
Compilation plus existing tests should suffice. 
---

[Bridge] Introduce metric to track successful approvals and claims

---

crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-watchdog/eth_vault_balance.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_bridge_watchdog/eth_vault_balance.rs
crates/sui-bridge/src/sui_bridge_watchdog/metrics.rs
crates/sui-bridge/src/utils.rs

Updates to the sui bridge indexer, bridge watchdog, and bridge node to include metrics for wBTC.
Run locally

[Bridge] Support wbtc vault balance

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/execution_time_estimator.rs
crates/sui-core/src/epoch/epoch_metrics.rs

Add metrics and rate limit for execution time observations

---

crates/sui-types/src/execution.rs

remove errant todo-dns

---

external-crates/move/crates/move-compiler/src/unit_test/filter_test_members.rs
external-crates/move/crates/move-symbol-pool/src/lib.rs

- Switch poison functions
- We can remove them next release
- ran tests 
---

[move-compiler] switch poison functions

---

crates/sui-deepbook-indexer/src/server.rs

Rename trade_updates to order_updates
Tested locally

Rename Endpoint (Deepbook Indexer)

---

docs/content/snippets/info-gas-budget.mdx
docs/content/snippets/libpq-req.mdx

Typo fix in docs snippets - CLI flags are boolean, these are options

Fix docs typo

---

crates/sui-deepbook-indexer/src/server.rs

Deepbook Indexer Summary Endpoint Improvements
Tested locally, query time lowered from 10-15s to ~3-5s

Deepbook Indexer Summary Endpoint Improvements

---

docs/content/guides/developer/getting-started/data-serving.mdx

[docs] Fix image background in dark mode

---

docs/site/vercel.json

[docs] add redirects

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_74.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_74.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_74.snap

Update nitro attestation costs. 
CI + local tests
---

Update nitro attestation costs

---

docs/content/concepts/cryptography/transaction-auth/signatures.mdx

feat(doc): add reference for passkey

---

notes

chore: remove 'notes' file that was mistakenly committed

---

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs

checkpoint_executor: don't build CheckpointData unless its needed

---

docker/sui-indexer-alt-jsonrpc/Dockerfile
docker/sui-indexer-alt-jsonrpc/build.sh

containerize indexer-alt-jsonrpc
---

dockerize indexer-alt-jsonrpc

---

sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs

- Making room for future versions 
- Non functional change 
---

[child effects refactor] Making room for versioning 

---

consensus/core/src/block_manager.rs

There is no reason to try and synchronize blocks that are `<= gc_round` . Updating the `try_find_blocks` to respect gc round. This should lead to less unnecessary synchronization when nodes lag behind in network.
CI/PT
---

[Consensus] try_find_blocks to respect gc threshold

---

consensus/core/src/core.rs
consensus/core/src/dag_state.rs

[consensus] Include links to excluded ancestors that are at the network accepted low quorum round

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui `v1.44.0` Version Bump

---

consensus/core/src/core.rs

PR#21216 incorrectly handled the inclusion of excluded ancestor's ancestor. It should have added the original excluded ancestor as a soft link in this case.
---

[consensus] fix for excluded ancestor inclusion

---

consensus/core/src/core.rs

PR#21216 incorrectly handled the inclusion of excluded ancestor's ancestor. It should have added the original excluded ancestor as a soft link in this case.
---
--- …

[cherrypick] [consensus] fix for excluded ancestor inclusion (#21221)

---

docs/content/guides/developer/advanced/local-fee-markets.mdx

style guide updates

---

docs/content/guides/developer/advanced/congestion-control.mdx
docs/content/guides/developer/advanced/local-fee-markets.mdx
docs/content/sidebars/guides.js

Add advanced guide for congestion control to Sui docs

---

consensus/core/src/commit_syncer.rs
consensus/core/src/metrics.rs

Cherry pick of https://github.com/MystenLabs/sui/pull/21224
CI
---

[Cherrypick][Consensus] add metric for missing ancestors when processing blocks via commit sync

---

docs/content/concepts/tokenomics/vesting-strategies.mdx
docs/content/sidebars/concepts.js
examples/vesting/Move.toml
examples/vesting/sources/backloaded.move
examples/vesting/sources/cliff.move
examples/vesting/sources/hybrid.move
examples/vesting/sources/linear.move
examples/vesting/sources/milestone.move
examples/vesting/tests/backloaded_tests.move
examples/vesting/tests/cliff_tests.move
examples/vesting/tests/hybrid_tests.move
examples/vesting/tests/immediate_tests.move
examples/vesting/tests/linear_tests.move
examples/vesting/tests/milestone_tests.move

[docs] Vesting topic

---

consensus/core/src/core.rs

Smart ancestor selection logic is live on mainnet as of v1.42
---

[consensus] remove non smart ancestor selection logic

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_test_utils.rs
crates/sui-core/src/authority/shared_object_version_manager.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-core/src/rpc_index.rs
crates/sui-core/src/state_accumulator.rs
crates/sui-core/src/test_utils.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/congestion_control_tests.rs
crates/sui-core/src/unit_tests/transaction_deny_tests.rs
crates/sui-single-node-benchmark/src/benchmark_context.rs

Removes async and SuiResult from several APIs where it is not needed.

Clean up various APIs

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_74.snap

[cherry-pick] disable consensus garbage collection for testnet

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_74.snap

[Consensus] do not enable garbage collection for testnet.

---

docker/sui-tools/Dockerfile

remove some unused/unnecessary tools

---

crates/sui-indexer-alt-jsonrpc/src/lib.rs

Port over the configuration that was added to fullnodes after bumping the version of jsonrpsee used there:
https://github.com/MystenLabs/sui/blob/900a69ba0d1b5607a9f11f27a3db5104d02d27c2/crates/sui-json-rpc/src/lib.rs#L209-L219
- Disable batching
- Unlimit response size
- Reword the max connections limit, because really limits the max number of requests in flight.
---

rpc-alt: port configuration from fullnode JSON-RPC

---

docker/sui-tools/Dockerfile

add back sui-faucet to sui-tools

---

docs/content/guides/developer/advanced/randomness-onchain.mdx

We update the documentation on how to use on-chain randomness. The current documentation places a lot of emphasis on gas consumption, when a similar attack can be done by hitting any resource limit.
N/A
---

:memo: docs: improve randomness-onchain

---

docker/sui-tools/Dockerfile

add back sui-faucet to sui-tools (#21265)

---

crates/sui-data-ingestion-core/src/lib.rs
crates/sui-data-ingestion-core/src/reducer.rs

[data ingestion] retry reducer errors

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_75.snap

chore: enable passkey for testnet

---

docs/content/references/cli/client.mdx
docs/site/package.json
docs/site/pnpm-lock.yaml
docs/site/src/plugins/descriptions/index.js

creates llms.txt and llms-full.txt files. llms.txt follows https://llmstxt.org/ and llms-full.txt is the site in markdown with imports and includes resolved.
https://sui-docs-git-fork-ronny-mysten-ronmilton-bbc3ae-sui-foundation.vercel.app/llms.txt
https://sui-docs-git-fork-ronny-mysten-ronmilton-bbc3ae-sui-foundation.vercel.app/llms-full.txt
---

[docs] site to text file

---

crates/sui-core/src/execution_driver.rs

Crash found by antithesis.
I'm also removing the retry loop which has been disabled everywhere except mainnet for some time.

Fix execution driver panic which became possible due to synchronous tx execution

---

crates/sui-framework/docs/sui_system/staking_pool.md
crates/sui-framework/docs/sui_system/storage_fund.md
crates/sui-framework/docs/sui_system/sui_system.md
crates/sui-framework/docs/sui_system/sui_system_state_inner.md
crates/sui-framework/docs/sui_system/validator.md
crates/sui-framework/docs/sui_system/validator_set.md
crates/sui-framework/packages/sui-system/sources/genesis.move
crates/sui-framework/packages/sui-system/sources/stake_subsidy.move
crates/sui-framework/packages/sui-system/sources/staking_pool.move
crates/sui-framework/packages/sui-system/sources/storage_fund.move
crates/sui-framework/packages/sui-system/sources/sui_system.move
crates/sui-framework/packages/sui-system/sources/sui_system_state_inner.move
crates/sui-framework/packages/sui-system/sources/validator.move
crates/sui-framework/packages/sui-system/sources/validator_cap.move
crates/sui-framework/packages/sui-system/sources/validator_set.move
crates/sui-framework/packages/sui-system/sources/validator_wrapper.move
crates/sui-framework/packages/sui-system/sources/voting_power.move
crates/sui-framework/packages/sui-system/tests/delegation_tests.move
crates/sui-framework/packages/sui-system/tests/governance_test_utils.move
crates/sui-framework/packages/sui-system/tests/rewards_distribution_tests.move
crates/sui-framework/packages/sui-system/tests/staking_pool.move
crates/sui-framework/packages/sui-system/tests/sui_system_tests.move
crates/sui-framework/packages/sui-system/tests/validator_set_tests.move
crates/sui-framework/packages/sui-system/tests/validator_tests.move
crates/sui-framework/packages/sui-system/tests/voting_power_tests.move

- **this is not a proper formatting PR**, the only change is module label + reduce indentation
- bytecode must be the same, snapshots should not need regeneration
- closes DVX-772
---
When reviewing, make sure to hide whitespace changes:
- mostly whitespace change
- bytecode must stay the same
- only change besides formatting is doc regen
---

[sui system] use module label

---

crates/sui-indexer-alt-jsonrpc/src/api/transactions/response.rs
crates/sui-indexer-alt-jsonrpc/src/data/kv_loader.rs
crates/sui-indexer-alt-jsonrpc/src/data/transactions.rs

Make transaction lookup use bigtable kvstore as well.
Tested locally against bigtable.
---

[rpc-alt] use bigtable for transaction lookup

---

.github/workflows/docs.yml

changes the slack channel that receives these messages
---

[easy] Update docs.yml

---

deny.toml

Sorry for the churn :( learned my lesson to be a bit more patient.
---

[chore] `ring` is now maintained again, so we can remove the rustsec.

---

crates/sui-config/src/node.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap

chore: remove test tenant

---

crates/sui-node/src/main.rs
external-crates/move/crates/move-vm-profiler/src/lib.rs

Remove allow(unreachable_code) for sui-node main()

---

external-crates/move/documentation/coding_guidelines.md

https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deref.md - error 404
https://github.com/rust-unofficial/patterns/blob/main/src/anti_patterns/deref.md - work link

fix 404 link coding_guidelines.md

---

sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs

- debug assertions are compiled even on release builds, just never checked
- 👀 
---

Fix debug assertions on main

---

docs/content/guides/developer/getting-started/sui-install.mdx

Add Zed to Move extensions

---

docs/site/src/components/Protocol/index.tsx
docs/site/src/plugins/protocol/protocolLoader-json.js

[docs] Services and enums for grpc

---

docs/content/guides/developer/app-examples/reviews-rating.mdx

fix `5 broken link` reviews-rating.mdx

---

external-crates/move/crates/move-vm-types/src/values/value_tests.rs
external-crates/move/crates/move-vm-types/src/values/values_impl.rs

- Following similar recursive enum optimizations, I have boxed variants for a more compact layout
- Wrote a test to assert the size 
---

Optimize ValueImpl layout

---

crates/sui-core/benches/batch_verification_bench.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/signature_verifier.rs
crates/sui-core/src/unit_tests/batch_verification_tests.rs
crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-mvr-graphql-rpc/src/types/zklogin_verify_signature.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_76.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_76.snap
crates/sui-types/src/crypto.rs
crates/sui-types/src/multisig.rs
crates/sui-types/src/signature.rs
crates/sui-types/src/unit_tests/multisig_tests.rs
crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs
crates/sui/src/keytool.rs

feat: allow passkey in multisig

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui `v1.45.0` Version Bump

---

crates/sui-bridge/src/config.rs

[sui-bridge] improve logging and limit gas coin checks

---

crates/sui-indexer-alt-schema/migrations/2024-10-30-214852_wal_obj_types/up.sql
crates/sui-indexer-alt-schema/migrations/2024-10-30-232206_wal_coin_balances/up.sql

fix duplicate the the

---

crates/sui-core/src/authority.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-json-rpc/src/transaction_execution_api.rs
crates/sui-open-rpc/spec/openrpc.json

Return source information in dry run transactions
Added authority.rs tests in sui-core
---

add execution error to response

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_76.snap

Cherry pick of https://github.com/MystenLabs/sui/pull/21397
CI
---

[Consensus] do not enable GC for testnet with version 76

---

consensus/core/src/core.rs

Better having this as `debug` as it tends to get quite noisy as most of the times the decided leaders are `0`.
CI/PT
---

[Consensus] reduce noisy log

---

consensus/core/src/core.rs

Cherry pick of https://github.com/MystenLabs/sui/pull/21395
CI
---

[chore] reduce noisy log

---

.github/CODEOWNERS

codeowners update + guard against changes to docker/

---

crates/sui-core/src/jsonrpc_index.rs

This fixes expensive call sites caused by 0269b42498befb8f4cf628dd16b277d2e9d250dc.
---

[typed store] iterators: fix expensive callsites

---

crates/sui-core/src/jsonrpc_index.rs

This fixes expensive call sites caused by
0269b42498befb8f4cf628dd16b277d2e9d250dc.
---
--- …

[typed store] iterators: fix expensive callsites (#21406)

---

crates/sui-json-rpc-types/src/sui_move.rs
crates/sui-open-rpc/spec/openrpc.json

Reverts MystenLabs/sui#21359
The change in the format is causing breaking issues for clients. Revert back to previous layout for now.

Revert "[json-rpc] Update variants to be returned in declaration order"

---

crates/sui-json-rpc-types/src/sui_move.rs
crates/sui-open-rpc/spec/openrpc.json

Reverts MystenLabs/sui#21359
The change in the format is causing breaking issues for clients. Revert back to previous layout for now.

Revert "[json-rpc] Update variants to be returned in declaration order" (#21413)

---

.github/workflows/cargo-llvm-cov.yml

Fixing https://github.com/MystenLabs/sui/actions/runs/13650059779
Install toolchain for code coverage
👀

Install toolchain for code coverage

---

crates/typed-store/src/rocks/mod.rs

restores delete_file_in_range and partial_merge methods
---

[typed store] restore delete_file_in_range/partial_merge methods

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-storage/src/write_path_pending_tx_log.rs
crates/typed-store-derive/src/lib.rs
crates/typed-store/src/rocks/mod.rs
crates/typed-store/src/rocks/tests.rs
crates/typed-store/tests/macro_tests.rs

removes support for transactional rocksdb database 
---

[typed store] remove transactional support

---

crates/sui-node/src/lib.rs

Fixes a nightly simtest failure

Increase timeout in simulator

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_77.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_77.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_77.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

feat: enable group ops uncompressed in mainnet

---

Cargo.lock
Cargo.toml
crates/sui-tls/src/verifier.rs

Update a number of dependencies:
- anemo
- webpki
- x509-parser
- pkcs8
- ed25519
---

chore: update various dependencies

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_77.snap

Cherry pick of https://github.com/MystenLabs/sui/pull/21420
---

[Consensus] Enable Garbage Collection & New commit rule for testnet on version 77 

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_store_pruner.rs
crates/sui-core/src/jsonrpc_index.rs
crates/sui-tool/src/db_tool/index_search.rs

[pruner] introduce indexes pruner

---

crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_77.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_77.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_77.snap

Make snapshots the exact same
CI

protocol snapshot fixes

---

.github/workflows/ci-docs.yml

Updates the `actions-rs/cargo` action to point to main. Although not preferred to point to a branch, the repo is archived and all its releases point to the problematic version of the fsevents dependency. 
---

Update action to remove problem dependency

---

docker/multisig-toolkit/Dockerfile
docker/multisig-toolkit/README.md
docker/multisig-toolkit/build.sh

Dockerize Multisig Toolkit 
Build + Run as described in README.md 
---

add multisig-toolkit docker image

---

docs/content/standards/wallet-standard.mdx

Documentation typo fix:
singTransaction -> signTransaction
Preview
---

fix: typo on wallet-standard.mdx

---

crates/sui-core/src/authority/execution_time_estimator.rs
crates/sui-types/src/execution.rs

special case handling of execution time estimate for Publish command

---

docker/multisig-toolkit/Dockerfile

Update dockerfile to be more in-line with typescript Dockerfile template: https://github.com/MystenLabs/sui/blob/ff6b7e25522c64a2611941ff695d209dabf335fc/crates/suiop-cli/dockerfile-templates/typescript.Dockerfile
Build + Run Docker Image for multisig toolkit.
` ./docker/multisig-toolkit/build.sh`
`docker run -it --rm -p 4173:4173 multisig-toolkit:latest`
---

update multisig-toolkit docker container to ts suiop style

---

crates/sui/src/displays/dry_run_tx_block.rs

[cli] print execution error source

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/execution_time_estimator.rs
crates/sui-core/src/epoch/epoch_metrics.rs

Add more metrics for execution time estimator

---

scripts/sparse-checkout.py

Persist the base commit used by sparse checkout to lessen the need for rebuilds after rebasing.

Persist the base commit

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.46.0 Version Bump

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_78.snap

Enable missing required features for v78

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_78.snap

[Cherrypick] Enable missing required features for v78

---

crates/sui-archival/src/lib.rs
crates/sui-data-ingestion/src/main.rs
crates/sui-indexer-alt-jsonrpc/src/data/bigtable_reader.rs
crates/sui-kvstore/src/bigtable/client.rs

various adjustments/fixes for backfill process
---

[data ingestion] adjustments for ingestion binary

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-e2e-tests/tests/reconfiguration_tests.rs
crates/sui-node/src/lib.rs
crates/sui-swarm-config/src/network_config_builder.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm/src/memory/swarm.rs
crates/test-cluster/src/lib.rs

Allow Chain to be overridden via config. Add config smoke tests for mainnet and testnet

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/consensus_quarantine.rs
crates/sui-core/src/authority/epoch_start_configuration.rs
crates/sui-core/src/transaction_input_loader.rs
crates/sui-single-node-benchmark/src/mock_storage.rs

Clean up UseVersionAssignmentTablesV3 epoch flag

---

crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
crates/sui-core/src/execution_cache.rs
crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
crates/sui-core/src/execution_cache/writeback_cache.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-core/src/unit_tests/transaction_deny_tests.rs
crates/sui-single-node-benchmark/src/benchmark_context.rs

This facility will be used in a forth-coming PR to optimize checkpoint execution perf

Split batch building and batch writing into two separate phases

---

crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge-watchdog/eth_vault_balance.rs
crates/sui-bridge/src/config.rs
crates/sui-bridge/src/node.rs
crates/sui-bridge/src/sui_bridge_watchdog/eth_vault_balance.rs
crates/sui-bridge/src/sui_bridge_watchdog/metrics.rs
crates/sui-bridge/src/utils.rs

This reverts commit 9459bf91eefaaba032b3cf237abb07f8941d0eda.
---

Revert "[bridge] add lbtc vault monitoring (#21403)"

---

crates/sui-adapter-transactional-tests/tests/dev_inspect/arbitrary_args.move
crates/sui-adapter-transactional-tests/tests/dev_inspect/arbitrary_args.snap
crates/sui-adapter-transactional-tests/tests/dev_inspect/conservation.move
crates/sui-adapter-transactional-tests/tests/dev_inspect/conservation.snap
crates/sui-adapter-transactional-tests/tests/dev_inspect/entry_checks.move
crates/sui-adapter-transactional-tests/tests/dev_inspect/entry_checks.snap
crates/sui-adapter-transactional-tests/tests/dev_inspect/unused_value_without_drop.move
crates/sui-adapter-transactional-tests/tests/dev_inspect/unused_value_without_drop.snap
crates/sui-adapter-transactional-tests/tests/dry_run/arbitrary_args.move
crates/sui-adapter-transactional-tests/tests/dry_run/arbitrary_args.snap
crates/sui-adapter-transactional-tests/tests/dry_run/conservation.move
crates/sui-adapter-transactional-tests/tests/dry_run/conservation.snap
crates/sui-adapter-transactional-tests/tests/dry_run/entry_checks.move
crates/sui-adapter-transactional-tests/tests/dry_run/entry_checks.snap
crates/sui-adapter-transactional-tests/tests/dry_run/gas_missing.move
crates/sui-adapter-transactional-tests/tests/dry_run/gas_missing.snap
crates/sui-adapter-transactional-tests/tests/dry_run/unused_value_without_drop.move
crates/sui-adapter-transactional-tests/tests/dry_run/unused_value_without_drop.snap
crates/sui-adapter-transactional-tests/tests/upgrade/basic.move
crates/sui-adapter-transactional-tests/tests/upgrade/basic.snap
crates/sui-transactional-test-runner/src/args.rs
crates/sui-transactional-test-runner/src/test_adapter.rs

Ensures expected dry run behavior for:
- arbitrary args
- conservation
- entry check
- unused value without drop
- gas tests
adds to test runner: 
- dry-run for upgrades option
- multiple gas payments
context: #20109 
snapshots
---

[tests] Sui transactional dev inspect dry run tests

---

crates/sui-config/src/node.rs

bump default observation channel capacity for execution time observer

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/execution_time_estimator.rs

Add reachability assertions for execution time estimation

---

crates/sui-core/src/authority/execution_time_estimator.rs

remove extraneous async from observer functions

---

crates/sui-benchmark/src/options.rs
crates/sui-benchmark/src/workloads/adversarial.rs
crates/sui-benchmark/src/workloads/data/slow/Move.toml
crates/sui-benchmark/src/workloads/data/slow/sources/slow.move
crates/sui-benchmark/src/workloads/mod.rs
crates/sui-benchmark/src/workloads/slow.rs
crates/sui-benchmark/src/workloads/workload_configuration.rs
crates/sui-benchmark/tests/simtest.rs

- Add slow tx workload for congestion control to benchmark test suite
- Add slow workload to simtests
- Allow runtime specification of workload move dir

Congestion control loadtest changes

---

docs/content/guides/developer/cryptography/zklogin-integration.mdx

https://mysten-labs.slack.com/archives/C04J99F4B2L/p1742572307731239
- 👁️ 

[docs] remove type that doesn't exist from zkLogin docs

---

crates/sui-json-rpc/src/bridge_api.rs
crates/sui-json-rpc/src/coin_api.rs
crates/sui-json-rpc/src/logger.rs
crates/sui-json-rpc/src/read_api.rs

Otherwise they are a bit verbose and don't seem very useful.
CI
---

Reduce log severity from json rpc

---

external-crates/move/crates/move-compiler/src/typing/translate.rs

Fix a lint issue after landing
CI should work now
---

[fixup] Fix clippy in the compiler

---

binary-build-list.json

remove suiop from binary-build-list

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority/execution_time_estimator.rs
crates/sui-core/src/epoch/epoch_metrics.rs

Add per-object utilization metric for use in load tests

---

external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/call_with_mut_and_imm.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/call_with_mut_and_imm.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/enum_variant_factor.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/enum_variant_factor.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/alias_write_after_join.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/alias_write_after_join.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/alias_writes.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/alias_writes.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/extension_after_call.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/extension_after_call.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/extension_writes_after_join.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/extension_writes_after_join.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/multible_mutable_return_values.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/multible_mutable_return_values.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/subtree_writes_release.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/expressivity/subtree_writes_release.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/imm_borrow_on_mut_invalid.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/imm_borrow_on_mut_invalid.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/imm_extends_mut_arg.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/imm_extends_mut_arg.snap
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/imm_extends_mut_arg_field.mvir
external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/imm_extends_mut_arg_field.snap

- Additional tests for reference safety passes
- Pulled in from the regex rewrite
- Tests
---

[bytecode-verifier] Added additional tests

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_79.snap
crates/sui-types/src/nitro_attestation.rs

enable verify function in testnet

---

crates/telemetry-subscribers/src/lib.rs

additional tagging for k8s environments 
do it live
---

[tracing] add namespace, network, and host tags to traces

---

crates/sui-indexer-alt/src/config.rs
crates/sui-indexer-alt/src/lib.rs

[cherry-pick][indexer-alt] add temp obj_info pipeline to config (#21625)

---

crates/sui-kvstore/src/bigtable/client.rs

title, dashboard showd <1ms, which was suspicious and Emma found this bug when we were looking together
ci
---

kv store: fix client latency metrics

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.47.0 version bump

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs
consensus/simtests/src/node.rs
consensus/simtests/src/tests/simtests.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_79.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_79.snap

Improve synchronizer to return more blocks in responses when possible.
When a fetch request contains missing blocks from an authority, the handler will return more blocks from the highest accepted round to the lowest missing round of the authority.
PT
---

[consensus] improve synchronizer batching

---

crates/sui-indexer-alt-jsonrpc/src/context.rs
crates/sui-indexer-alt-jsonrpc/src/data/bigtable_reader.rs
crates/sui-indexer-alt-jsonrpc/src/data/checkpoints.rs
crates/sui-indexer-alt-jsonrpc/src/data/objects.rs
crates/sui-indexer-alt-jsonrpc/src/data/transactions.rs

- add metrics for kv store loads
- log slow kv store loads as warnings
ci
---

jsonrpc alt: log slow kv loads

---

consensus/config/src/parameters.rs
consensus/config/tests/snapshots/parameters_test__parameters.snap
consensus/core/src/authority_node.rs
consensus/core/src/authority_service.rs
consensus/core/src/commit_syncer.rs
consensus/core/src/core.rs
consensus/core/src/dag_state.rs
consensus/core/src/error.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs
consensus/simtests/src/node.rs
consensus/simtests/src/tests/simtests.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_79.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_79.snap

Soak the change in testnet.
CI / PT
---
---

Cherrypick: improve consensus synchronizer batching in testnet

---

crates/typed-store/src/rocks/mod.rs

deprecate usage of WriteOptions
---

[typed store] deprecate usage of WriteOptions

---

crates/sui-framework/CONTRIBUTING.md
crates/sui-framework/docs/sui/poseidon.md
crates/sui-framework/packages/sui-framework/sources/crypto/poseidon.move

docs: Poseidon hash function only available on Devnet 

---

docker/sui-node-deterministic/Dockerfile

Fix sui node output path

---

docs/content/sidebars/references.js
docs/site/src/css/custom.css

Fixes the odd rendering of toml files and updates the sidebar to read alpha for graphql
👀 
---

[docs][easy] Update custom.css

---

crates/sui-bridge-indexer/src/main.rs
crates/sui-bridge/src/node.rs

Fix for LBTC metrics to be optional (for the testnet case wear LBTC is not supported yet) 
Test by running on testnet and mainnet nodes. 
---

[bridge] fix testnet LBTC metrics

---

docs/site/src/plugins/framework/index.js

[docs] Remove deprecated framework

---

external-crates/move/crates/move-compiler/src/typing/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/typing/index_syntax_methods_miscalled.snap
external-crates/move/crates/move-compiler/tests/move_check/borrows/unused_ref.snap
external-crates/move/crates/move-compiler/tests/move_check/typing/module_call.snap
external-crates/move/crates/move-compiler/tests/move_check/typing/module_call_complicated_rhs.snap
external-crates/move/crates/move-compiler/tests/move_check/typing/module_call_wrong_arity.snap

- #21633 Added support for additional location information on for arity checking
- This PR adds information where applicable for function calls
- Updated tests
---

[move-compiler] Add additional location for arity checking in some cases

---

external-crates/move/crates/move-compiler/src/parser/token_set.rs

- Small change left over from compiler parallelism 
- 👀 
---

[move-compiler] TokenSet switches to static str

---

README.md

docs(readme): added a new badge to the documentation

---

external-crates/move/crates/move-package-alt/src/lib.rs

[move] Add missing lib file in move-package-alt

---

Cargo.lock
Cargo.toml

Unpin chrono dependencies. The referenced MR has been merged.

build(deps): unpin chrono 

---

external-crates/move/documentation/book/src/packages.md

pacakge - package
depencies - dependencies
hi ! i fixed minor typos , thanks

minor docstring fixups packages.md

---

crates/sui-rpc-benchmark/src/config.rs
crates/sui-rpc-benchmark/src/direct/query_executor.rs

split from PR https://github.com/MystenLabs/sui/pull/21555 per the suggestion on that PR, also resolved comments on that PR.
local run of direct bench binary
---

rpc benchmark direct easy: optinal timeout

---

crates/sui-core/src/authority/authority_store_migrations.rs

migrate_events: remove span logic that was causing oom

---

crates/sui-core/src/authority.rs

Cherrypick #21714 to 1.46

---

docs/content/concepts/dynamic-fields.mdx
docs/content/concepts/dynamic-fields/tables-bags.mdx
docs/content/sidebars/concepts.js

[docs] Returning beloved topics

---

docs/content/references/contribute/mdx-components.mdx

[docs][easy] Update component use instructions

---

crates/sui-deepbook-indexer/src/server.rs
crates/sui-faucet/src/server.rs

sui-faucet: fix breakage from updating axum

---

Cargo.lock
Cargo.toml
external-crates/move/Cargo.lock
external-crates/move/Cargo.toml
scripts/simtest/cargo-simtest
scripts/simtest/config-patch

chore: update tokio to 1.44.2

---

crates/sui-core/src/authority.rs
crates/sui-json-rpc-types/src/sui_transaction.rs
crates/sui-open-rpc/src/examples.rs
crates/sui-rosetta/src/operations.rs

All the try_from variants share a lot of common code other than the module resolution.
Move the common code to shared helper functions.
CI
---

[nit] Remove duplicated code in sui_transaction

---

crates/sui-rpc-api/src/client/mod.rs

Now that the last release exposes the new beta apis we can convert the client to use them. Once this is out and released we can remove the old apis completely in the following release.
---

grpc: convert client to new beta apis

---

Cargo.lock
Cargo.toml
crates/sui-rpc-api/Cargo.toml
crates/sui-rpc-api/src/grpc/mod.rs

grpc: natively support grpcweb

---

consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs

Help resolve consensus sync issues on testnet validators.
Deploy to Mysten testnet validators.
---

Pick #21749 to 1.46

---

.github/workflows/bridge.yml
.github/workflows/cargo-llvm-cov.yml
.github/workflows/external.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/rust.yml
.github/workflows/split-cluster-bisect.yml
.github/workflows/split-cluster-pr.yml

ubuntu-ghcoud is stuck, moving to ubuntu-ghcloud-2
👀

Move to ubuntu-ghcloud-2 runner

---

crates/sui-types/src/execution_status.rs
sui-execution/latest/sui-adapter/src/execution_engine.rs

Update InputObjectDeleted error message for ConsensusV2

---

.github/workflows/bridge.yml
.github/workflows/cargo-llvm-cov.yml
.github/workflows/external.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/rust.yml
.github/workflows/split-cluster-bisect.yml
.github/workflows/split-cluster-pr.yml

Revert to upgraded `ubuntu-ghcloud` runner
👀

Revert to upgraded `ubuntu-ghcloud` runner

---

crates/sui-analytics-indexer/src/lib.rs

Loading the snowflake password from a file to enable secure Pulumi secret management.

Load snowflake password from a file

---

crates/sui-analytics-indexer/src/lib.rs

Revert "Load snowflake password from a file"

---

crates/sui-indexer-alt-jsonrpc/src/data/pg_reader.rs

From the dashboard I realized this metric never got increased so this PR fixes that.
👀 
---

[easy][rpc-alt] add db request received metrics

---

docs/content/standards/deepbookv3-indexer.mdx
docs/content/standards/deepbookv3/design.mdx

Update Deepbook minimum fees, merge after upgrade
Docs only

Deepbook Docs Update

---

docs/content/concepts/tokenomics/sui-bridging.mdx

A sentence with two dollar signs gets rendered as a latex expression. Replaced with html entities to prevent. Also updated values to the correct ones.
👀 
---

[docs][easy] Fix formatting and outdated data

---

crates/sui-rpc-benchmark/README.md

sui rpc benchmark easy: update README

---

Cargo.lock
external-crates/move/Cargo.lock

Update crossbeam-channel to address RUSTSEC-2025-0024
---

chore: update crossbeam-channel to 0.5.13

---

crates/sui/src/client_commands.rs

[cli] Fix faucet request message

---

scripts/update_all_snapshots.sh

Hash of system package is part of swarm config snapshot, so updating system package first.
CI
---

Update system package before other snapshots

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_80.snap

[consensus] Increase threshold for bad nodes that won't be considered leaders in consensus in mainnet

---

crates/sui-bridge/src/e2e_tests/basic.rs
crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/transaction_metadata.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap

add missing brace and remove redundant word in comment
---

chore: add missing brace and remove redundant word in comment

---

external-crates/move/crates/move-vm-runtime/src/tracing2/tracer.rs

Fixes an issue where references could flow into an initial frame, and where there could be intervening values that are not references/data loads.
Tested it on a repro from @awelc

[move] Fix issue in tracing dataloads

---

crates/sui-core/src/authority/authority_per_epoch_store_pruner.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/epoch/consensus_store_pruner.rs
crates/sui-core/src/rpc_index.rs
crates/sui-node/src/lib.rs
crates/typed-store/src/rocks/mod.rs
crates/typed-store/src/rocks/tests.rs

Avoid std::thread::sleep() in safe_drop_db()

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_80.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_81.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_80.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_81.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_81.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
sui-execution/latest/sui-adapter/src/execution_mode.rs
sui-execution/latest/sui-adapter/src/execution_value.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs

Cherry-pick the fix from the release branch into `main`. This shifts the protocol version 80 features to 81, and replaces it with the protocol version 80 features from the release.
CI

[adapter] Add bounds to PTB values

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.48.0 Version Bump

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-node/src/lib.rs
crates/sui-node/src/metrics.rs
crates/sui-protocol-config/Cargo.toml

For debugging and setting up alerts.
CI
PT
---

Export current, max supported and max configured protocol config versions as metrics

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-node/src/lib.rs
crates/sui-node/src/metrics.rs
crates/sui-protocol-config/Cargo.toml

Allow us to set up alerts with the metrics earlier.
CI
---
---

Pick #21821 to 1.47

---

crates/sui-core/src/authority_aggregator.rs

This fixes a flaky simtest: https://github.com/MystenLabs/sui/actions/runs/14418124154/job/40437321145
In some simtests we crash more than a quorum of validators, and in that case we may not be able to get the object from a quorum of validators. Adding retry here. This function is for testing only so we don't need to be very strict.
Reran simtest
---

Fix flaky get_latest_object_version

---

docs/content/sidebars/standards.js
docs/content/standards/deepbookv3/balance-manager.mdx
docs/content/standards/deepbookv3/design.mdx
docs/content/standards/deepbookv3/flash-loans.mdx
docs/content/standards/deepbookv3/orders.mdx
docs/content/standards/deepbookv3/permissionless-pool.mdx
docs/content/standards/deepbookv3/query-the-pool.mdx
docs/content/standards/deepbookv3/staking-governance.mdx
docs/content/standards/deepbookv3/swaps.mdx

Deepbook Upgrade Docs for 3.1
No testing needed

Deepbook Upgrade Docs

---

Cargo.lock
Cargo.toml
crates/sui-replay-2/Cargo.toml
crates/sui-replay-2/build.rs
crates/sui-replay-2/src/data_store.rs
crates/sui-replay-2/src/environment.rs
crates/sui-replay-2/src/errors.rs
crates/sui-replay-2/src/execution.rs
crates/sui-replay-2/src/gql_queries.rs
crates/sui-replay-2/src/lib.rs
crates/sui-replay-2/src/main.rs
crates/sui-replay-2/src/replay_txn.rs
crates/sui-types/src/sui_sdk_types_conversions.rs

Initial work for the replay tool. 
This is a work in progress that used to be on a branch and we are moving on main so other people (namely @awelc, @stefan-mysten, @tzakian, @amnn) can easily integrate their work.
Not everything works yet, as the data is not yet always available, deny list is not hooked up yet, execution tracing is not finished yet and there are likely random bug.
Overall I think a cgood starting point as we continue to work on it
No test plan, when we are going to plug in the cache we are going to develop some tests
--- …

replay tool [1/N]

---

crates/sui-node/src/lib.rs

If the logic does not crash immediately on start failures, it will still crash later from more obscure places.
CI
---

Crash on sui-node start failures

---

crates/sui-indexer-alt-jsonrpc/src/data/pg_reader.rs

From the dashboard I realized this metric never got increased so this PR fixes that.
👀 
---
--- …

[cherrypick][easy][rpc-alt] add db request received metrics (#21768)

---

crates/sui-core/src/rpc_index.rs
crates/sui-kvstore/src/bigtable/client.rs
crates/sui-kvstore/src/bigtable/init.sh
crates/sui-kvstore/src/bigtable/worker.rs
crates/sui-kvstore/src/lib.rs
crates/sui-types/src/full_checkpoint_content.rs

adds `epochs` table to Bigtable-based KV store
---

[kv store] add epochs table

---

external-crates/move/crates/move-binary-format/src/normalized.rs
external-crates/move/crates/move-model-2/Cargo.toml
external-crates/move/crates/move-model-2/src/json.rs
external-crates/move/crates/move-model-2/src/lib.rs
external-crates/move/crates/move-model-2/src/model.rs
external-crates/move/crates/move-model-2/src/serializable_signatures.rs

- Adds a serializable signature API to the model
- The signatures contain some information that can be populated via the source language 
- 👀 
---

[move-model-2] Add serializable signatures 

---

Cargo.toml

Examples are not part of the workspace and use git dependencies. Fixes vendor problems
---

Exclude examples from workspace members

---

crates/sui-node/src/lib.rs

All transactions in pending_consensus_transactions will eventually be executed once they come out of consensus.
There is no strong need to proactively execute them upfront.
This causes the debug_fatal in the function to be triggered, causing both simtest nightly and antithesis to fail.
CI
---

Do not call reexecute_pending_consensus_certs at startup

---

.github/workflows/move-formatter.yml

[CI] Adds a CI to check formatting

---

crates/sui-core/src/authority.rs

Only log when we are actually resigning the effects, to differentiate from the regular signing case.
CI
---

[nit] Make log clearer when resigning effects

---

crates/sui-indexer-alt-jsonrpc/src/metrics/middleware.rs

Log internal erors at a higher log level and with more information (print the full request params, and a snippet of the response), to help with investigations.
Manually tested
---

jsonrpc-alt: log request params and result for internal errors

---

crates/sui-indexer-alt-jsonrpc/src/metrics/middleware.rs

Log internal erors at a higher log level and with more information (print the full request params, and a snippet of the response), to help with investigations.
Manually tested
---

pick(21897) jsonrpc-alt: log request params and result for internal errors

---

consensus/.clippy.toml
consensus/core/src/authority_node.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs
consensus/core/src/dag_state.rs
consensus/core/src/storage/mem_store.rs
consensus/core/src/storage/mod.rs
consensus/core/src/storage/rocksdb_store.rs
consensus/core/src/storage/store_tests.rs

And a few other cleanups.
CI
---

[consensus] remove unused function in Store trait

---

docs/content/guides/developer/getting-started/sui-install.mdx
docs/content/guides/operator/sui-full-node.mdx

[docs] Include sui-node install from aws

---

docs/content/guides/developer/getting-started/local-network.mdx

Updated documentation for starting Sui local network with an indexer.

fix(docs): update `sui` cli `--with-indexer` flag usage

---

docs/content/guides/operator/data-management.mdx

update pruning suggestion docs
---

[sui docs] update pruning policy suggestions

---

crates/sui-analytics-indexer/src/main.rs

I noticed this was wrong when debugging the heap issues.

nickv fix metrics registry

---

crates/sui-analytics-indexer/src/lib.rs
crates/sui-analytics-indexer/src/main.rs

Bounding the checkpoint queue size to prevent OOMs when something goes wrong.

Bound checkpoint queue

---

external-crates/move/crates/move-model-2/src/compiled_model.rs
external-crates/move/crates/move-model-2/src/lib.rs
external-crates/move/crates/move-model-2/src/model.rs
external-crates/move/crates/move-model-2/src/source_model.rs
external-crates/move/crates/move-model-2/src/summary.rs

- Renamed `serializable_signatures` to `summary` based on @tzakian's name plans
- 👀 
---

[move-model-2] Rename `serializable_signatures` to `summary`

---

.github/workflows/move-formatter.yml
crates/sui-framework/packages/sui-system/tests/delegation_tests.move
crates/sui-framework/packages/sui-system/tests/governance_test_utils.move
crates/sui-framework/packages/sui-system/tests/rewards_distribution_tests.move
crates/sui-framework/packages/sui-system/tests/staking_pool.move
crates/sui-framework/packages/sui-system/tests/sui_system_tests.move
crates/sui-framework/packages/sui-system/tests/validator_set_tests.move
crates/sui-framework/packages/sui-system/tests/validator_tests.move
crates/sui-framework/packages/sui-system/tests/voting_power_tests.move

Runs the formatter on all tests, no other changes introduced.
---

[system] fmt + cleanup - 8/8 - formats all tests

---

docs/content/concepts/tokenomics/sui-bridging.mdx

Fixing typo in sui-bridging.mdx

---

crates/sui-graphql-e2e-tests/tests/stable/call/simple.snap
crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/test_framework/framework.snap
crates/sui-transactional-test-runner/src/test_adapter.rs

[graphql] Fix header map ordering in transactional-test-runner

---

crates/sui-types/src/base_types.rs
crates/sui-types/src/sui_serde.rs

Pick to 1.47

---

crates/sui-analytics-indexer/src/analytics_metrics.rs
crates/sui-analytics-indexer/src/analytics_processor.rs
crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-analytics-indexer/src/handlers/event_handler.rs
crates/sui-analytics-indexer/src/handlers/object_handler.rs
crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
crates/sui-analytics-indexer/src/lib.rs
crates/sui-analytics-indexer/src/main.rs
crates/sui-analytics-indexer/src/package_store.rs
crates/sui-analytics-indexer/src/writers/csv_writer.rs
crates/sui-analytics-indexer/src/writers/mod.rs
crates/sui-analytics-indexer/src/writers/parquet_writer.rs

Occasionally the backwill was stalling because some large checkpoints could not be downloaded in 5s. This allows me to configure it to tune the value as necessary.
It's already running in the backfill stack.

Make remote store timeout configurable

---

crates/sui-analytics-indexer/src/analytics_metrics.rs
crates/sui-analytics-indexer/src/analytics_processor.rs
crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-analytics-indexer/src/handlers/event_handler.rs
crates/sui-analytics-indexer/src/handlers/object_handler.rs
crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
crates/sui-analytics-indexer/src/lib.rs
crates/sui-analytics-indexer/src/main.rs
crates/sui-analytics-indexer/src/package_store.rs
crates/sui-analytics-indexer/src/writers/csv_writer.rs
crates/sui-analytics-indexer/src/writers/mod.rs
crates/sui-analytics-indexer/src/writers/parquet_writer.rs

Enabling support for authenticated GCS connections to reduce throttling risk.
It's already running in the backfill stack

Support native GCS client access

---

crates/sui-analytics-indexer/src/analytics_metrics.rs
crates/sui-analytics-indexer/src/analytics_processor.rs
crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-analytics-indexer/src/handlers/event_handler.rs
crates/sui-analytics-indexer/src/handlers/object_handler.rs
crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
crates/sui-analytics-indexer/src/lib.rs
crates/sui-analytics-indexer/src/main.rs
crates/sui-analytics-indexer/src/package_store.rs
crates/sui-analytics-indexer/src/writers/csv_writer.rs
crates/sui-analytics-indexer/src/writers/mod.rs
crates/sui-analytics-indexer/src/writers/parquet_writer.rs
docker/sui-analytics-indexer/Dockerfile

Just making jemalloc available on this image. env var changes to use it are made in pulumi in a separate PR.

Install jemalloc

---

crates/sui-analytics-indexer/src/analytics_metrics.rs
crates/sui-analytics-indexer/src/analytics_processor.rs
crates/sui-analytics-indexer/src/handlers/checkpoint_handler.rs
crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-analytics-indexer/src/handlers/event_handler.rs
crates/sui-analytics-indexer/src/handlers/move_call_handler.rs
crates/sui-analytics-indexer/src/handlers/object_handler.rs
crates/sui-analytics-indexer/src/handlers/package_handler.rs
crates/sui-analytics-indexer/src/handlers/transaction_bcs_handler.rs
crates/sui-analytics-indexer/src/handlers/transaction_handler.rs
crates/sui-analytics-indexer/src/handlers/transaction_objects_handler.rs
crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
crates/sui-analytics-indexer/src/lib.rs
crates/sui-analytics-indexer/src/main.rs
crates/sui-analytics-indexer/src/package_store.rs
crates/sui-analytics-indexer/src/writers/csv_writer.rs
crates/sui-analytics-indexer/src/writers/mod.rs
crates/sui-analytics-indexer/src/writers/parquet_writer.rs
docker/sui-analytics-indexer/Dockerfile

Trivial change to use take instead of clone to reduce allocation overhead in the hot path.

Get rid of unnecessary clones

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.49.0 Version Bump

---

consensus/core/src/authority_service.rs

Pick #21984 to 1.48

---

crates/sui-data-ingestion-core/src/lib.rs
crates/sui-data-ingestion-core/src/util.rs
crates/sui-data-ingestion/src/workers/blob.rs

populates epochs.json for checkpoint buckets
---

[data ingestion] populate epochs.json

---

external-crates/move/crates/move-analyzer/trace-debug/package.json

What the title says (to publish recent updates related to handling compressed traces)

[trace-view] Bump up extension version for new release

---

docs/content/concepts/tokenomics.mdx
docs/content/guides/operator/validator-committee.mdx
docs/content/snippets/staking-pool-reqs.mdx

embed sui foundation form for new validator onboarding + updating stake requirements 
---

Updating validator docs with sip-39 details

---

docs/content/guides/operator/archives.mdx
docs/content/guides/operator/data-management.mdx

full node config changes related to archive deprecation
---

[docs] archive deprecation

---

external-crates/move/crates/move-package-alt/src/dependency/git.rs
external-crates/move/crates/move-package-alt/src/dependency/mod.rs
external-crates/move/crates/move-package-alt/src/package/manifest.rs
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_invalid/basic_missing_git_dep/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_invalid/invalid_author/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_invalid/invalid_authors/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_invalid/invalid_identifier_package_name/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_invalid/no_path_set_for_dependency/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_invalid/non_string_local_dep_path/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/basic/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/basic_external_resolver/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/basic_implicit_deps/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/basic_no_dep_override_git/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/basic_with_bar/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/basic_with_bar/bar/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/edition_2024/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/edition_2024_beta/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/edition_legacy/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/flavor_global_storage/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/flavor_sui/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/manifest_parsing_valid/flavor_unknown/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/pinning/external_basic/Move@pinned.snap
external-crates/move/crates/move-package-alt/tests/data/pinning/external_different_results/Move@pinned.snap
external-crates/move/crates/move-package-alt/tests/test_runner.rs

Pkg alt deserialize

---

external-crates/move/crates/move-package-alt/DESIGN.md

Migrate design doc

---

crates/sui-framework-snapshot/manifest.json

Update git revision as the commit sha changed when landing...
CI

[cherry-pick] Regenerate now using the landed commit sha

---

crates/sui-types/src/messages_checkpoint.rs
crates/sui-types/src/storage/shared_in_memory_store.rs

Fix possible re-entrant lock bug

---

crates/sui-core/src/authority.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-node/src/lib.rs

- Fix `reexecute_pending_consensus_transactions`
- Address comment TODOs

Fixes for crash recovery

---

crates/sui-framework/docs/sui_system/validator.md
crates/sui-framework/packages/sui-system/sources/staking_pool.move
crates/sui-framework/packages/sui-system/sources/sui_system.move
crates/sui-framework/packages/sui-system/sources/sui_system_state_inner.move
crates/sui-framework/packages/sui-system/sources/validator.move
crates/sui-framework/packages/sui-system/sources/validator_set.move
crates/sui-framework/packages/sui-system/tests/builders/test_runner.move
crates/sui-framework/packages/sui-system/tests/builders/validator_builder.move
crates/sui-framework/packages/sui-system/tests/delegation_tests.move
crates/sui-framework/packages/sui-system/tests/validator_tests.move

Starts tests refactoring, offers new builders for types + tests rewrite one by one
- adds aliases  `validate_metadata(metadata)` -> `metadata.validate()`
- adds more getters for validators in tests
- `delegation_tests.move`
- `validator_tests.move`
This PR is tests.
---

[Sui System] Better Test Framework 1/N

---

docs/content/guides/developer/getting-started/get-address.mdx

[docs] Update wallet section

---

crates/sui-tool/src/db_tool/db_dump.rs
crates/typed-store-derive/src/lib.rs

Otherwise rename derive won't work in the unittest.
CI
---

[db-dump] Use cf name when describe table

---

crates/sui-package-management/src/lib.rs

Walrus intends to avoid using the `SuiClient` within the `WalletContext` since it lacks retry semantics. To this end, we would prefer to avoid relying on Sui functions that force such usage. This PR extracts the internals of `update_lock_file` so that it can be used directly without need to pass in the `WalrusContext`.
CI Pipeline.

chore: expose update_lock_file fn that does not depend on wallet context

---

crates/sui-json-rpc/src/lib.rs
crates/sui-json-rpc/src/metrics.rs

add timeouts to JSON RPC server
---

[json rpc server] add timeout

---

external-crates/move/crates/move-package-alt/src/dependency/dependency_set.rs
external-crates/move/crates/move-package-alt/src/dependency/external.rs
external-crates/move/crates/move-package-alt/src/dependency/mod.rs
external-crates/move/crates/move-package-alt/src/flavor/mod.rs
external-crates/move/crates/move-package-alt/src/package/lockfile.rs
external-crates/move/crates/move-package-alt/src/package/manifest.rs
external-crates/move/crates/move-package-alt/tests/data/basic/Move.toml
external-crates/move/crates/move-package-alt/tests/data/basic/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/basic_external_resolver/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/basic_implicit_deps/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/basic_no_dep_override_git/Move.toml
external-crates/move/crates/move-package-alt/tests/data/basic_no_dep_override_git/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/basic_with_bar/Move.toml
external-crates/move/crates/move-package-alt/tests/data/basic_with_bar/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/basic_with_bar/bar/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/edition_2024/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/edition_2024_beta/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/edition_legacy/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/external_multiple_resolvers/Move@pinned.snap
external-crates/move/crates/move-package-alt/tests/data/flavor_global_storage/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/flavor_sui/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/flavor_unknown/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/invalid_author/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/invalid_authors/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/invalid_identifier_package_name/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/lockfile_parsing_valid/Move@locked.snap
external-crates/move/crates/move-package-alt/tests/data/unknown_toplevel_field/Move@parsed.snap

[package-alt] Rename dep-overrides to replacements

---

crates/sui-analytics-indexer/src/analytics_processor.rs
crates/sui-analytics-indexer/src/handlers/checkpoint_handler.rs
crates/sui-analytics-indexer/src/handlers/df_handler.rs
crates/sui-analytics-indexer/src/handlers/event_handler.rs
crates/sui-analytics-indexer/src/handlers/mod.rs
crates/sui-analytics-indexer/src/handlers/move_call_handler.rs
crates/sui-analytics-indexer/src/handlers/object_handler.rs
crates/sui-analytics-indexer/src/handlers/package_handler.rs
crates/sui-analytics-indexer/src/handlers/transaction_bcs_handler.rs
crates/sui-analytics-indexer/src/handlers/transaction_handler.rs
crates/sui-analytics-indexer/src/handlers/transaction_objects_handler.rs
crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
crates/sui-analytics-indexer/src/writers/csv_writer.rs
crates/sui-analytics-indexer/src/writers/mod.rs
crates/sui-analytics-indexer/src/writers/parquet_writer.rs

Small change to use iterators instead of doing so many vec copies.

Use iterators to reduce allocation

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/transaction_manager.rs

Remove unused pending_execution

---

consensus/core/src/authority_service.rs
consensus/core/src/metrics.rs
consensus/core/src/synchronizer.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_83.snap

This seems to have reduced the round rate dips in testnet.
Also, add a few more metrics and reduce logging verbosity.
CI
PT
---

[consensus] enable batched / depth first synchronization

---

crates/sui-core/src/quorum_driver/tests.rs

This change tries to make the test `test_quorum_driver_object_locked` not fail when QuorumDriver gets response from both nodes that have signed `tx1` instead of validators signing different transactions less flaky, by re-running the quorum driver request again until we get requests from the desired validators instead of failing the whole test and re-running it completely. It does not make sense to fail the test if we are aware of this random factor.
I ran the test and it's more stable than before.
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user …

fix(sui-core): Fix test_quorum_driver_object_locked flaky test.

---

crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_83.snap

Enable some protocol config dependencies of ExecutionTimeEstimate mode

---

crates/sui-benchmark/tests/simtest.rs

Add smoke tests for mainnet and testnet protocol configs

---

crates/sui-indexer-alt-jsonrpc/src/api/name_service/response.rs
crates/sui-indexer-alt-schema/migrations/2024-11-01-182359_kv_genesis/up.sql
docs/content/concepts/grpc-overview.mdx
external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts

remove duplicate word in comment
---

chore: remove duplicate word in comment

---

external-crates/move/crates/move-package-alt/src/dependency/git.rs
external-crates/move/crates/move-package-alt/src/dependency/local.rs
external-crates/move/crates/move-package-alt/src/dependency/mod.rs

This PR adds some comments to functions, and it adds a first implementation for the general `fetch` function.
---

[pkg-alt] impl fetch + cleanup

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui `v1.50.0` Version Bump

---

crates/sui-config/data/fullnode-template.yaml

Update fullnode template to reflect latest archival changes
---

[sui archival] update fullnode template

---

docs/content/standards/deepbookv3.mdx

Deepbook minor doc update
Doc change only

Deepbook minor doc update

---

docs/site/src/plugins/askcookbook/index.js

- Open the main page: https://docs.sui.io
- Navigate to the "Guides" section by clicking the button in the navbar (will get you to https://docs.sui.io/guides)
- The bug:
- On the live site, the "Ask Sui AI" button disappears until the page is refreshed.
- On this branch, the "Ask Sui AI" button stays visible as expected.

fix(docs): Prevent "Ask Sui UI" button from disappearing after site navigation

---

crates/sui-json-rpc/src/error.rs

Show which object ids are effected by `ObjectsDoubleUsed` error
---

[json-rpc] Add object id to locked objects error

---

.github/workflows/move-formatter.yml
crates/sui-framework/docs/bridge/bridge.md
crates/sui-framework/docs/bridge/chain_ids.md
crates/sui-framework/docs/bridge/committee.md
crates/sui-framework/docs/bridge/limiter.md
crates/sui-framework/docs/bridge/message.md
crates/sui-framework/docs/bridge/treasury.md
crates/sui-framework/packages/bridge/sources/bridge.move
crates/sui-framework/packages/bridge/sources/chain_ids.move
crates/sui-framework/packages/bridge/sources/committee.move
crates/sui-framework/packages/bridge/sources/crypto.move
crates/sui-framework/packages/bridge/sources/limiter.move
crates/sui-framework/packages/bridge/sources/message.move
crates/sui-framework/packages/bridge/sources/message_types.move
crates/sui-framework/packages/bridge/sources/treasury.move
crates/sui-framework/packages/bridge/tests/bridge_env.move
crates/sui-framework/packages/bridge/tests/bridge_tests.move
crates/sui-framework/packages/bridge/tests/bridge_txns.move
crates/sui-framework/packages/bridge/tests/commitee_test.move
crates/sui-framework/packages/bridge/tests/limiter_tests.move
crates/sui-framework/packages/bridge/tests/message_tests.move

> When reviewing, make sure to check "hide whitespace changes"
- runs formatter
- minor cleanups in CONSTANT_NAMING
- nits in tests `abort 0` -> `abort` and so on
- bytecode stays the same
- all tests are in place
---

[bridge] format bridge and add it to the formatting CI

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/execution_time_estimator.rs
crates/sui-core/src/authority/shared_object_congestion_tracker.rs
crates/sui-core/src/epoch/epoch_metrics.rs
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_83.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_84.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_78.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_79.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_80.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_81.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_82.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_83.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_84.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_78.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_79.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_80.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_81.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_82.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_83.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_84.snap
crates/sui-types/src/transaction.rs

Add limit to number of stored execution time observations

---

Cargo.lock
crates/sui-bridge-indexer-alt/Cargo.toml
crates/sui-bridge-indexer-alt/src/handlers/governance_action_handler.rs
crates/sui-bridge-indexer-alt/src/handlers/mod.rs
crates/sui-bridge-indexer-alt/src/main.rs
crates/sui-bridge-indexer/src/eth_bridge_indexer.rs
crates/sui-bridge-indexer/src/lib.rs
crates/sui-bridge-indexer/src/sui_bridge_indexer.rs
crates/sui-bridge-schema/src/models.rs

[Bridge indexer alt 3/n] - Governance action handler

---

crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_85.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_85.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_85.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

Move un-cherrypicked items on main to new protocol version

---

crates/sui-bridge-indexer-alt/src/handlers/error_handler.rs
crates/sui-bridge-indexer-alt/src/handlers/mod.rs
crates/sui-bridge-indexer-alt/src/main.rs
crates/sui-bridge-schema/src/models.rs

[Bridge indexer alt 4/n] - added errored bridge transaction indexing

---

crates/sui-security-watchdog/src/scheduler.rs

update logging & alert language to better support multiple jobs

---

crates/sui-tool/src/commands.rs
crates/sui-tool/src/lib.rs

Add default TLS to sui-tool with optional --no-tls flag

---

crates/sui-adapter-transactional-tests/tests/init/create_object.move
crates/sui-adapter-transactional-tests/tests/init/create_object.snap
crates/sui-adapter-transactional-tests/tests/init/emit_event.move
crates/sui-adapter-transactional-tests/tests/init/emit_event.snap
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_85.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_85.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_85.snap
external-crates/move/crates/move-vm-runtime/src/native_functions.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/data_store.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/linkage_view.rs
sui-execution/latest/sui-move-natives/src/config.rs
sui-execution/latest/sui-move-natives/src/dynamic_field.rs
sui-execution/latest/sui-move-natives/src/event.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/latest/sui-move-natives/src/transfer.rs

This updates https://github.com/MystenLabs/sui/pull/22092 to reuse linkage contexts (top commit) and moves it to the next protocol version. 
CI

[3/n][object runtime type tags] Add type tags to object runtime (part 2)

---

crates/typed-store/src/tidehunter_util.rs

Use label instead of prefix for separate tidehunter prometheus registry

---

crates/sui-adapter-transactional-tests/tests/party/merge_coins.move
crates/sui-adapter-transactional-tests/tests/party/merge_coins.snap

Add tests for coin merging of ConsensusAddressOwner coins

---

external-crates/move/crates/move-package-alt/src/dependency/local.rs
external-crates/move/crates/move-package-alt/src/dependency/mod.rs
external-crates/move/crates/move-package-alt/tests/data/basic_implicit_deps/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/basic_with_bar/Move@parsed.snap
external-crates/move/crates/move-package-alt/tests/data/basic_with_bar/bar/Move@parsed.snap

[pkg-alt] Rework local dependency

---

dapps/multisig-toolkit/src/routes/signature-analyzer.tsx

Update signature-analyzer view to include information regarding the Multisg Public Key
- Show multisig threshold and address
- Display all participants with weights (not just signers)
- Add dedicated UI component for multisig metadata
Built locally, tested with multisig signature.
---

[multisig-toolkit] feat: display complete multisig

---

crates/sui-core/src/consensus_handler.rs

This is no longer needed. Instead, we will make it possible to throw away fastpath transactions if they do not get finalized.
---

[mysticeti-fp] Do not insert fp tx into pending consensus tx

---

docs/content/references/cli/ptb.mdx

- adds description for Option
- adds description for `vector[]`
---

[docs] extends documentation for CLI PTBs

---

external-crates/move/crates/move-package-alt/src/cli/graph.rs
external-crates/move/crates/move-package-alt/src/graph/mod.rs

[package-alt] used package cache for building from lockfile

---

Cargo.lock
sui-execution/latest/sui-adapter/Cargo.toml
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs

- Break out parts of existing context for shared usage, most notably the end of Context::finish 
- 👁️ 📎 👁️ 
---

[static ptb] Break out parts for existing Context for shared usage

---

crates/sui-core/src/checkpoints/mod.rs

add open option to checkpoints db with tidehunter
---

[tidehunter] add open option to checkpoints db

---

docs/content/snippets/quick-install.mdx

Fix suiup description

---

crates/sui-e2e-tests/tests/party_objects_tests.rs
examples/move/basics/sources/object_basics.move

Add e2e test for immutable use of party objects

---

crates/sui-core/src/authority.rs

Treat `ConsensusAddressOwner` same as `AddressOwner` for JSON-RPC owner index

---

crates/sui-core/src/authority/execution_time_estimator.rs

Add minimum threshold for overutilization

---

docs/content/guides/developer/getting-started/sui-install.mdx

Fix docs to also mention suiup in quick install header

---

Cargo.lock
Cargo.toml
crates/sui-kv-rpc/Cargo.toml
crates/sui-kv-rpc/src/get_checkpoint.rs
crates/sui-kv-rpc/src/get_epoch.rs
crates/sui-kv-rpc/src/get_object.rs
crates/sui-kv-rpc/src/get_transaction.rs
crates/sui-kv-rpc/src/lib.rs
crates/sui-kvstore/src/bigtable/client.rs
crates/sui-kvstore/src/lib.rs
crates/sui-rpc-api/src/grpc/v2beta/ledger_service/get_object.rs
crates/sui-rpc-api/src/grpc/v2beta/ledger_service/mod.rs
crates/sui-rpc-api/src/grpc/v2beta/mod.rs
crates/sui-rpc-api/src/lib.rs
crates/sui-rpc-api/src/service/mod.rs
crates/sui-rpc-api/src/service/protocol_config.rs

basic implementation of LedgerService on top of the BigTable
---

[kvstore] basic implementation of LedgerService on top of the BigTable

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/execution_time_estimator.rs
crates/sui-core/src/authority/shared_object_congestion_tracker.rs
crates/sui-node/src/admin.rs

- Log transaction execution time
- admin API to query transaction execution cost & dump consensus observations
- Increase utilization threshold for leaky integrator
- Log expensive estimated transactions

Congestion control debugging stuff

---

external-crates/move/crates/move-compiler/src/diagnostics/warning_filters.rs
external-crates/move/crates/move-compiler/src/expansion/translate.rs
external-crates/move/crates/move-compiler/tests/move_2024/typing/deprecation_intra_module_calls.snap
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/typing/deprecated_transitive.move
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/typing/deprecated_transitive.snap
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/typing/deprecated_transitive@unused.snap
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/typing/deprecated_unused_field.move
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/typing/deprecated_unused_field.snap
external-crates/move/crates/move-compiler/tests/sui_mode/move_2024/typing/deprecated_unused_field@unused.snap

Addresses an issue raised in #22242, plus some other mild revisions.
New test cases demonstrating the changes, plus one minor revision that seems like an improvement to me.
---

[move][move-compiler] Improve some warnings around deprecations

---

crates/sui-replay-2/src/replay_txn.rs

Upgrade was missing a package id, added
Verified manually waiting to build a chace so we can check in some tests
---

Fix upgrade in replay tool

---

sui-execution/latest/sui-adapter/src/data_store/cached_data_store.rs
sui-execution/latest/sui-adapter/src/data_store/linkage_view.rs
sui-execution/latest/sui-adapter/src/data_store/mod.rs
sui-execution/latest/sui-adapter/src/data_store/sui_data_store.rs
sui-execution/latest/sui-adapter/src/lib.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/mod.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/env.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/mod.rs
sui-execution/latest/sui-adapter/src/type_layout_resolver.rs

Re-land https://github.com/MystenLabs/sui/pull/22099

[sui-adapter] Add basic package cache (reland of #22099)

---

crates/sui-config/src/node.rs
crates/sui-core/src/authority/execution_time_estimator.rs
crates/sui-core/src/epoch/epoch_metrics.rs

- Increase local observation window size
- Increase observation sharing diff threshold
- Add metric to report reason for observation sharing
---

Tweak some knobs for execution time estimation

---

crates/sui-replay-2/src/gql_queries.rs

Some transactions are hitting the `[GraphQlError { message: "Query payload too large: 7424B > 5000B", locations: None, path: None, extensions: Some(IgnoredAny) }]` error (for whatever the size bigger than 5000 is), so we are breaking up big multi-get queries.
I am not sure how to compute the size and it's not clear to me what the query translates to, so I came up with a number that works for the cases I had and hopefully works in general.
@amnn @stefan-mysten for suggestions if any
replayed all transaction with that error and they all pass
--- …

Break up big queries that hit limits

---

crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
crates/sui-core/src/transaction_outputs.rs
crates/sui-core/tests/staged/sui.yaml
crates/sui-types/src/accumulator_event.rs
crates/sui-types/src/effects/effects_v1.rs
crates/sui-types/src/effects/effects_v2.rs
crates/sui-types/src/effects/mod.rs
crates/sui-types/src/effects/object_change.rs
crates/sui-types/src/execution.rs
crates/sui-types/src/inner_temporary_store.rs
crates/sui-types/src/lib.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
sui-execution/latest/sui-adapter/src/temporary_store.rs
sui-execution/latest/sui-move-natives/src/object_runtime/accumulator.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/v0/sui-adapter/src/temporary_store.rs
sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs
sui-execution/v1/sui-adapter/src/temporary_store.rs
sui-execution/v2/sui-adapter/src/programmable_transactions/context.rs
sui-execution/v2/sui-adapter/src/temporary_store.rs

This PR contains most of the plumbing from #21701, which can be merged more or less as-is.
Since this doesn't do anything on its own yet, the motivation may not be clear in all cases, but #21701 can provide the context.
(Also, there are no tests yet because, again, this doesn't do anything yet.)

Plumbing for accumulator events

---

external-crates/move/crates/move-cli/src/lib.rs
external-crates/move/crates/move-stackless-bytecode-2/src/stackless/ast.rs
external-crates/move/crates/move-stackless-bytecode-2/src/stackless/context.rs
external-crates/move/crates/move-stackless-bytecode-2/src/stackless/translate.rs
external-crates/move/crates/move-stackless-bytecode-2/tests/move/branch/branch::branch@.sbir.snap
external-crates/move/crates/move-stackless-bytecode-2/tests/tests.rs

Add some minor revisions to stackless bytecode
Test updates and revisions, plus some runtime assertions
---

[move][stackless-bytecode] Add a bunch of small stuff to the stackless bytecode

---

crates/sui-indexer-alt-framework/src/pipeline/concurrent/collector.rs
crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs

The current coverage of this file is pretty good, and I just add test cases for the eager batching logic
```
cargo test -p sui-indexer-alt-framework test_collector --lib
```
---

[indexer-alt-framework] Improve test coverage for collector.rs

---

.github/workflows/create-release-announce.yml

update release announce payload
👀

update release announce payload

---

consensus/core/src/synchronizer.rs

Use the correct way to limit number of peers and to avoid division by zero.
CI
---

[consensus] fix num authorities to fetch per peer

---

crates/sui-replay-2/Cargo.toml
crates/sui-replay-2/README.md
external-crates/move/crates/move-analyzer/trace-debug/package.json

[replay] Re-enabled tracing and added trace-related info to README

---

crates/sui-replay-2/README.md
crates/sui-replay-2/src/data_store.rs
crates/sui-replay-2/src/lib.rs

[replay] Updated available RPC endpoints

---

sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs

Fix import to unbreak build
CI + clippy locally

Unbreak build

---

Cargo.lock
crates/sui-kv-rpc/Cargo.toml
crates/sui-kv-rpc/src/lib.rs
crates/sui-kv-rpc/src/main.rs
crates/sui-rpc-api/src/lib.rs

grpc binary for service LedgerService
---

[kv store] grpc binary for service LedgerService

---

crates/sui/tests/snapshots/shell_tests__summaries__summary_address_remapping.sh.snap
crates/sui/tests/snapshots/shell_tests__summaries__summary_hardcoded_addr.sh.snap
external-crates/move/crates/move-cli/tests/build_tests/stdlib_summaries/args.exp
external-crates/move/crates/move-cli/tests/build_tests/summaries/args.exp
external-crates/move/crates/move-cli/tests/build_tests/summary_generation_renames/args.exp
external-crates/move/crates/move-model-2/src/compiled_model.rs
external-crates/move/crates/move-model-2/src/source_model.rs
external-crates/move/crates/move-model-2/src/summary.rs

- Annotate type arguments in phantom positions
- 👓 
---

[move-model[summaries] Annotate summary type arguments in phantom positions

---

crates/sui-kv-rpc/src/main.rs
docker/sui-kv-rpc/Dockerfile

dedicated docker image for sui-kv-store
---

[kv rpc] dedicated docker image

---

external-crates/move/crates/move-package-alt/src/dependency/dependency_set.rs
external-crates/move/crates/move-package-alt/src/dependency/external.rs
external-crates/move/crates/move-package-alt/src/package/manifest.rs
external-crates/move/crates/move-package-alt/tests/data/external_multiple_resolvers/Move@pinned.snap

[pkg-alt] merge default dependencies early and remove from pipeline

---

crates/sui-core/src/authority_server.rs

(waiting for local simtest runs)
---

Return None if output/input objects are empty

---

crates/sui-core/src/validator_tx_finalizer.rs

Do not print the stacktace, and make it a debug instead of error.
---

Reduce error message noise in ValidatorTxFinalizer

---

crates/sui-core/src/authority/consensus_tx_status_cache.rs
crates/sui-core/src/authority_server.rs

Improve the test so that it could catch the previous fixed bug.
Update the name to make it clearer.
CI
---

Minor cleanup on ConsensusTxStatusCache

---

crates/sui-core/src/consensus_handler.rs

Incorrect txn index caused all consensus txn statuses to overwrite the same position for a block. Eventually leading to us violating a state transition invariant in consensus_tx_status_cache. Panic caught when debugging local benchmark
```
Conflicting status updates for transaction ConsensusPosition { block: B434([2],dVqthDN+FJ2ZGiXkbxoej5+S6rfuRKQfUAG0mZL/0K0=), index: 0 }: Rejected -> Finalized
```
Updated unit test
---

[mfp] Return correct txn index in consensus position of certified blocks

---

docs/site/docusaurus.config.js

Injects Microsoft Clarity's integration script. 
---

[docs] Add Microsoft Clarity analytics

---

Cargo.lock
crates/sui-replay-2/Cargo.toml
crates/sui-replay-2/build.rs
crates/sui-replay-2/src/data_store.rs
crates/sui-replay-2/src/gql_queries.rs
crates/sui-replay-2/src/main.rs

Change to using a build file for GraphQL schema, add the binary version and use it in the user-agent header. A few small other cleanups as well
Build + run a tx.z
---

[replay] Add request header and small cleanups

---

Cargo.lock
crates/sui-kv-rpc/Cargo.toml
crates/sui-kv-rpc/src/main.rs

tls support for KV grpc server
---

[sui kv rpc] add tls support

---

sui-execution/latest/sui-adapter/src/static_programmable_transactions/env.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/mod.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/mod.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/translate.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/drop_safety.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/memory_safety.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/move_functions.rs

- Fix typing of publish
- Remove last todo
- ❤️ 
---

[static ptbs] Fix typing of publish and upgrade

---

docs/content/guides/developer/getting-started/get-coins.mdx

`requestSuiFromFaucetV0` was deprecated.

update faucet function

---

crates/sui-indexer-alt-jsonrpc/src/lib.rs
crates/sui-indexer-alt-jsonrpc/src/metrics/middleware.rs

This way we know definitively from metrics which methods we need to add. This is only temporary though as we push for migration of first party apps. We will have to revert if we ever open up to the public.
existing test
---

[rpc-alt] report name of unknown methods in metrics too

---

docs/content/guides/developer/advanced/local-fee-markets.mdx

Update advanced guide on local fee markets for `ExecutionTimeEstimate` congestion control

---

crates/sui-types/src/base_types.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/linkage/analysis.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/linkage/legacy_linkage.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/linkage/resolved_linkage.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/loading/ast.rs

Fix some issues in linkage generation for the static PTBs where we weren't including the self linkage. 
sui-adapter::transfer_objects tests

[static-ptbs] Fix linkage computation to include reflexive linkages

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

sui v1.52 version bump

---

crates/sui-framework/packages/bridge/tests/bridge_env.move
crates/sui-framework/packages/sui-framework/sources/coin.move
crates/sui-framework/packages/sui-framework/sources/registries/coin_metadata_registry.move
crates/sui-framework/packages/sui-framework/tests/registries/coin_metadata_registry_tests.move
examples/move/coin/sources/my_coin.move
examples/move/coin/sources/regcoin.move
examples/move/token/sources/coffee.move
examples/move/token/sources/gems.move
examples/move/token/sources/loyalty.move
examples/move/token/sources/regulated_token.move
examples/move/token/sources/simple_token.move
examples/regulated-coin/move/sources/regulated_coin.move

[framework, cm2] small patches to cm2 PR

---

crates/sui-types/src/base_types.rs
external-crates/move/crates/move-binary-format/src/errors.rs
external-crates/move/crates/move-vm-runtime/src/runtime.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/values.rs

- Fix tx context resolved ID
- Using it somewhere because why nto
- Added debug assert for invariant violation 
- 👁️ 👁️ 
---

[static ptb] Fix TxContext resolution

---

.github/workflows/simulator-nightly.yml

Updates simtest reference to use the new teleport cluster

Update simtest to new teleport cluster

---

crates/sui-core/src/transaction_orchestrator.rs

Fixes test failure: 
```
Starting 1 test across 1 binary (24 tests skipped)
START             sui-benchmark::simtest test::test_simulated_load_with_reconfig_and_correlated_crashes
thread '<unnamed>' panicked at crates/sui-core/src/execution_cache.rs:540:46:
digests must exist
```

Wrap notify_read_effects with within_alive_epoch

---

crates/sui-replay-2/src/execution.rs
crates/sui-replay-2/src/main.rs
crates/sui-replay-2/src/tracing.rs

Save locally published and upgraded packages so tracing of init has code to refer to
Test locally as we do not have a way to test it yet in replay 
---

Save packages for tracing when publishing or upgrading

---

crates/sui-types/src/transaction.rs
external-crates/move/crates/move-core-types/src/identifier.rs
external-crates/move/crates/move-core-types/src/unit_tests/identifier_test.rs
sui-execution/src/verifier.rs

move-core-types: disallow <SELF> as an Identifier

---

crates/sui/src/keytool.rs
crates/sui/src/sui_commands.rs

[cli] CLI cherry picks with fixes!

---

crates/sui-core/src/checkpoints/mod.rs

I find it hard to connect between commit hight and checkpoint seq number. This is particularly challenging when sometimes grafana reorders logs a bit.
---

Add a few more loggings in checkpoint builder

---

consensus/core/src/authority_node.rs
consensus/core/src/commit_consumer.rs
crates/sui-core/src/consensus_manager/mod.rs
crates/sui-core/src/consensus_manager/mysticeti_manager.rs
crates/sui-node/src/lib.rs

Built on top of https://github.com/MystenLabs/sui/pull/22543 which is required to prevent OOM on recovery
---

Run consensus startup async

---

consensus/core/src/authority_node.rs
consensus/core/src/commit_observer.rs
consensus/core/src/core.rs
consensus/core/src/core_thread.rs

[Consensus] avoid monopolising current thread during commit observer recovery

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

sui v1.51.2 version bump

---

crates/sui-core/src/rpc_index.rs

This PR optimizes the RPC index initialization process by batching balance updates in memory before writing to RocksDB,
similar to how balance changes are handled during checkpoint processing.
Previously, during node initialization, each balance update was written directly to RocksDB using the merge operator.
This PR introduces in-memory accumulation of balance changes in a HashMap, flushing to RocksDB only when reaching 10k
records or at the end of processing.
Baseline (no batching): 727 seconds
10k threshold: 525 seconds (~28% improvement)
100k threshold: 586 seconds
1M threshold: 538 seconds
The 10k threshold was chosen as it provides the best performance improvement while keeping memory usage minimal. Higher
thresholds showed no additional benefit.
---

Batching balance updates an initialization

---

crates/sui-adapter-transactional-tests/tests/entry_points/obj_vector_generic_v20.move
crates/sui-adapter-transactional-tests/tests/entry_points/obj_vector_v20.move
crates/sui-adapter-transactional-tests/tests/receive_object/pt_receive_type_fixing@v2.snap
crates/sui-adapter-transactional-tests/tests/receive_object/receive_by_ref@v2.snap
crates/sui-adapter-transactional-tests/tests/receive_object/receive_ticket_coin_operations@v2.snap
crates/sui-transactional-test-runner/src/lib.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/env.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/ast.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/translate.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/input_arguments.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/memory_safety.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/move_functions.rs

- Fixed dirty marker for `entry`
- Fixed borrowing not tracking Move
- Fixed various entry point bugs
- Fixed arity checks 
- More dirs
---

[static ptb] More tests and fixes

---

external-crates/move/crates/move-binary-format/src/normalized.rs

What it says on the tin
They all still pass
---

[move] Add locals signature to normalized module

---

crates/sui-indexer-alt-e2e-tests/packages/coin/Move.toml
crates/sui-indexer-alt-e2e-tests/packages/coin/sources/my_coin.move
crates/sui-indexer-alt-e2e-tests/tests/jsonrpc_fn_delegation_tests.rs
crates/sui-indexer-alt-jsonrpc/src/api/coin.rs

Delegate `get_balance` method to fullnode.
Added a test.
---
---

[pick][rpc-alt] delegate get_balance method (#22505)

---

crates/sui-core/src/execution_scheduler/mod.rs

We have been running this on testnet FNs and a few validators, so far so good.
Enable for all testnet nodes.
---

Enable execution scheduler on testnet

---

crates/sui-data-ingestion/src/main.rs
crates/sui-indexer-alt-reader/src/bigtable_reader.rs
crates/sui-kv-rpc/src/lib.rs
crates/sui-kv-rpc/src/main.rs
crates/sui-kvstore/src/bigtable/client.rs
crates/sui-kvstore/src/main.rs

required in order to support multiregion fallback
---

[kv bigtable] add support for custom app_profile_id

---

crates/sui-rpc-api/src/grpc/v2beta2/live_data_service/simulate/resolve/mod.rs
crates/sui-types/src/rpc_proto_conversions.rs

resolve: bound budget and handle expiration

---

crates/sui-adapter-transactional-tests/tests/entry_points/missing_type.snap
crates/sui-adapter-transactional-tests/tests/upgrade/type_resolution.move
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_87.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_87.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_87.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs

Improve some error messages around type resolution.
CI
---

[cherry-pick] Improve type resolution errors (#22611)

---

consensus/core/src/metrics.rs
consensus/core/src/transaction_certifier.rs
crates/mysten-metrics/src/guards.rs
crates/sui-benchmark/src/bank.rs
crates/sui-benchmark/src/drivers/bench_driver.rs
crates/sui-benchmark/src/lib.rs
crates/sui-benchmark/src/util.rs
crates/sui-benchmark/src/workloads/adversarial.rs
crates/sui-benchmark/src/workloads/party.rs
crates/sui-benchmark/src/workloads/randomized_transaction.rs
crates/sui-benchmark/src/workloads/shared_counter.rs
crates/sui-benchmark/src/workloads/shared_object_deletion.rs
crates/sui-benchmark/src/workloads/slow.rs
crates/sui-core/src/consensus_adapter.rs
crates/sui-core/src/transaction_driver/error.rs
crates/sui-core/src/transaction_driver/mod.rs

[mfp] Add mixed submission through QD & TD and add additional metrics

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_87.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_87.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_87.snap

- Record that execution time messages have been processed
- Update snapshots

[Cherrypick] Record that execution time messages have been processed #22635

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_87.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_88.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_87.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_88.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_87.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_88.snap

Record that execution time estimates are processed.

Record that execution time messages have been processed

---

crates/sui-core/src/authority/execution_time_estimator.rs

Use zero default value for newly added observations to maintain backwards compatibility

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui `v1.53.0` Version Bump

---

.github/workflows/release.yml

Increase timeout for maco os intel builds
👀

Increase timeout for maco os intel builds

---

crates/sui-framework/docs/sui/transfer.md
crates/sui-framework/packages/sui-framework/sources/transfer.move

Tweak party_transfer comments for testnet release

---

crates/sui-benchmark/tests/simtest.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-surfer/src/surfer_state.rs

Tweak simtest epoch duration to avoid occasional zero-tx seeds

---

Cargo.lock
Cargo.toml
scripts/simtest/cargo-simtest
scripts/simtest/config-patch

Pick up recent commits on `mysten-sim` `main` branch.
CI
---

Bump mysten-sim and tokio

---

crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/execution_time_estimator.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_88.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_88.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_88.snap
crates/sui-types/src/messages_consensus.rs

Cherrypick ExecutionTimeEstimate fixes into 1.52

---

consensus/core/src/storage/rocksdb_store.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/authority/authority_store_tables.rs
crates/sui-core/src/authority/consensus_quarantine.rs
crates/sui-core/src/checkpoints/mod.rs
crates/typed-store/src/tidehunter_util.rs

More tidehunter config tuning

---

crates/sui-indexer-alt-graphql/README.md

The old command did not work as the test is not existing
```
cargo nextest run -p sui-indexer-alt-graphql -- test_schema_sdl_export
cargo nextest run -p sui-indexer-alt-graphql --features staging -- test_schema_sdl_export
```
---

chore: Update schema regeneration command

---

docs/site/src/plugins/inject-code/utils.js

Removes the sui dependency from toml files that are pulled from the codebase. The CI still requires them.
---

[docs] Use implicit deps

---

external-crates/move/crates/move-package-alt/src/errors/mod.rs
external-crates/move/crates/move-package-alt/src/graph/mod.rs
external-crates/move/crates/move-package-alt/src/package/root_package.rs
external-crates/move/crates/move-package-alt/src/test_utils/graph_builder.rs

This computes the linkage during `RootPackage` validation to ensure that the package graph is valid.
This needs to be tested along with many other things in `RootPackage`; I will do more comprehensive testing in a future PR
---

Check for linkage in `RootPackage`

---

crates/sui-core/src/rpc_index.rs
crates/sui-rpc-api/src/grpc/v2beta2/ledger_service/get_object.rs
crates/sui-rpc-api/src/grpc/v2beta2/ledger_service/get_transaction.rs
crates/sui-rpc-api/src/grpc/v2beta2/live_data_service/list_owned_objects.rs
crates/sui-rpc-api/src/grpc/v2beta2/mod.rs
crates/sui-types/src/object.rs
crates/sui-types/src/rpc_proto_conversions.rs
crates/typed-store/src/rocks/options.rs

rpc-index: disable write throttling

---

crates/sui-kv-rpc/src/main.rs

adds reflection to v2beta2 service
---

[kv grpc] add reflection to v2beta2

---

external-crates/move/crates/move-package-alt/src/dependency/combine.rs
external-crates/move/crates/move-package-alt/src/package/manifest.rs
external-crates/move/crates/move-package-alt/src/package/package_impl.rs
external-crates/move/crates/move-package-alt/src/package/root_package.rs
external-crates/move/crates/move-package-alt/tests/data/external_bad_schema/Move.toml
external-crates/move/crates/move-package-alt/tests/data/external_multiple_resolvers/Move.toml
external-crates/move/crates/move-package-alt/tests/data/external_multiple_resolvers/Move@pinned.snap
external-crates/move/crates/move-package-alt/tests/data/external_returns_external/Move.toml
external-crates/move/crates/move-package-alt/tests/test_runner.rs

[pkg-alt] Refactor code around combine deps

---

Cargo.lock
crates/sui-package-alt/Cargo.toml
crates/sui-package-alt/src/sui_flavor.rs
external-crates/move/crates/move-package-alt/src/dependency/combine.rs
external-crates/move/crates/move-package-alt/src/flavor/mod.rs
external-crates/move/crates/move-package-alt/src/flavor/vanilla.rs
external-crates/move/crates/move-package-alt/src/git/cache.rs
external-crates/move/crates/move-package-alt/src/package/manifest.rs
external-crates/move/crates/move-package-alt/src/package/package_impl.rs
external-crates/move/crates/move-package-alt/src/package/root_package.rs
external-crates/move/crates/move-package-alt/src/schema/sha.rs
external-crates/move/crates/move-package-alt/tests/test_runner.rs

This PR adds implicit deps support for the new pkg system.
---

[pkg-alt] Add implicit deps support

---

Cargo.lock
crates/mysten-common/src/logging.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/epoch/randomness.rs
crates/sui-e2e-tests/Cargo.toml
crates/sui-e2e-tests/tests/checkpoint_tests.rs
crates/sui-e2e-tests/tests/protocol_version_tests.rs
crates/sui-network/Cargo.toml
crates/typed-store/Cargo.toml

Replace many error! logs with debug_fatal! so that they trigger test failures

Change many error! logs to debug_fatal!

---

crates/sui-core/src/unit_tests/data/move_random/sources/move_random.move
crates/sui-core/src/unit_tests/gas_tests.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_89.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_89.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_89.snap
crates/sui-types/src/gas.rs
crates/sui-types/src/gas_model/gas_v2.rs
sui-execution/latest/sui-adapter/src/gas_charger.rs
sui-execution/v0/sui-adapter/src/gas_charger.rs
sui-execution/v1/sui-adapter/src/gas_charger.rs
sui-execution/v2/sui-adapter/src/gas_charger.rs

Revert protection - Cap gas price when transactions are aborted

---

nre/sui_for_node_operators.md

[nre] improve operator guide

---

crates/sui-benchmark/src/workloads/delegation.rs
crates/sui-benchmark/src/workloads/slow.rs
crates/sui-sdk/Cargo.toml
crates/sui-sdk/src/apis.rs

Fixing a few smallish issues when running sui-benchmark simtests with 50% of traffic through `TRANSACTION_DRIVER`.
CI
---

[TD] various simtest fixes

---

crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/transaction_orchestrator.rs

This is to help full node operators with transaction timeouts to debug and maybe mitigate.
CI
---

Pick #22792 into 1.52

---

crates/typed-store/src/tidehunter_util.rs

Allow to customize TH_FRAG_SIZE

---

.github/workflows/create-release-announce.yml

Use specific commit to release
https://github.com/MystenLabs/sui/actions/runs/16454733007/job/46508780319

Use specific commit to release

---

Cargo.lock
external-crates/move/Cargo.lock
external-crates/move/crates/move-package-alt/Cargo.toml
external-crates/move/crates/move-package-alt/src/dependency/pin.rs
external-crates/move/crates/move-package-alt/src/git/cache.rs
external-crates/move/crates/move-package-alt/src/package/root_package.rs
external-crates/move/crates/move-package-alt/src/schema/sha.rs

[pkg-alt] Clone full history when there's no full sha

---

crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs

Immediate fail execution from checkpoint executor on insufficient withdraw

---

docs/content/guides/suiplay0x1.mdx
docs/content/guides/suiplay0x1/best-practices.mdx
docs/content/guides/suiplay0x1/integration.mdx
docs/content/guides/suiplay0x1/migration-strategies.mdx
docs/content/guides/suiplay0x1/wallet-integration.mdx
docs/content/sidebars/guides.js
docs/content/snippets/suiplay.mdx

[docs] Sui play

---

crates/sui-types/src/README.md
crates/sui-types/src/object.md

Add documentation/spec alongside code for Owner enum

---

external-crates/move/crates/move-cli/src/sandbox/cli.rs
external-crates/move/crates/move-cli/src/sandbox/commands/publish.rs
external-crates/move/crates/move-cli/src/sandbox/utils/on_disk_state_view.rs
external-crates/move/crates/move-transactional-test-runner/src/vm_test_harness.rs
external-crates/move/crates/move-vm-runtime/src/cache/move_cache.rs
external-crates/move/crates/move-vm-runtime/src/dev_utils/compilation_utils.rs
external-crates/move/crates/move-vm-runtime/src/dev_utils/in_memory_test_adapter.rs
external-crates/move/crates/move-vm-runtime/src/dev_utils/storage.rs
external-crates/move/crates/move-vm-runtime/src/dev_utils/vm_test_adapter.rs
external-crates/move/crates/move-vm-runtime/src/execution/dispatch_tables.rs
external-crates/move/crates/move-vm-runtime/src/jit/execution/ast.rs
external-crates/move/crates/move-vm-runtime/src/jit/execution/translate.rs
external-crates/move/crates/move-vm-runtime/src/jit/optimization/ast.rs
external-crates/move/crates/move-vm-runtime/src/jit/optimization/translate.rs
external-crates/move/crates/move-vm-runtime/src/runtime/data_cache.rs
external-crates/move/crates/move-vm-runtime/src/runtime/mod.rs
external-crates/move/crates/move-vm-runtime/src/runtime/package_resolution.rs
external-crates/move/crates/move-vm-runtime/src/shared/linkage_context.rs
external-crates/move/crates/move-vm-runtime/src/shared/types.rs
external-crates/move/crates/move-vm-runtime/src/unit_tests/loader_tests.rs
external-crates/move/crates/move-vm-runtime/src/unit_tests/package_cache_tests.rs
external-crates/move/crates/move-vm-runtime/src/validation/deserialization/ast.rs
external-crates/move/crates/move-vm-runtime/src/validation/mod.rs
external-crates/move/crates/move-vm-runtime/src/validation/verification/ast.rs
external-crates/move/crates/move-vm-runtime/src/validation/verification/linkage.rs
external-crates/move/crates/move-vm-runtime/src/validation/verification/translate.rs
sui-execution/latest/sui-adapter/src/error.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/datastore.rs

Rename package ID types based on discussion
Tests still pass
---

[vm][move-vm][rewrite] Rename package ID types

---

docs/content/guides/operator/exchange-integration.mdx

Fix typos and improve clarity in Sui Exchange Integration Guide

docs: fix typos and improve clarity in exchange integration guide

---

external-crates/move/crates/move-vm-runtime/src/tracing2/tracer.rs

This cherry-pick only affects the CLI. 
This fixes a couple issues that cropped up when replaying more transactions with tracing. In particular:
* We weren't properly tracking aliasing of references
* We were indexing in one place from the bottom of the stack instead off of the top of the stack when looking for a stack value.
* We were recording the store of a value before the taking the snapshot of the initial value.
Ran it on a bunch of transactions to verify it.
---

[cherry-pick][tracing] Fix some issues with global values in traces (#22906)

---

crates/sui-indexer-alt-jsonrpc/src/metrics/middleware.rs

Right now we only log internal errors but there's some unexplainable client errors we would like to investigate as well. This PR adds debug logging for those errors too.
Ran rpc server locally to see that logging works.
---

[easy][rpc-alt] debug log non-internal errors

---

crates/sui-core/benches/batch_verification_bench.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/signature_verifier.rs
crates/sui-core/src/unit_tests/batch_verification_tests.rs
crates/sui-core/src/unit_tests/move_package_tests.rs
crates/sui-core/src/unit_tests/unit_test_utils.rs
crates/sui-e2e-tests/tests/multisig_tests.rs
crates/sui-e2e-tests/tests/protocol_version_tests.rs
crates/sui-graphql-rpc/src/types/zklogin_verify_signature.rs
crates/sui-json-rpc/src/read_api.rs
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_89.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_89.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_89.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
crates/sui-types/src/move_package.rs
crates/sui-types/src/multisig.rs
crates/sui-types/src/object.rs
crates/sui-types/src/signature.rs
crates/sui-types/src/unit_tests/base_types_tests.rs
crates/sui-types/src/unit_tests/multisig_tests.rs
crates/sui-types/src/unit_tests/zk_login_authenticator_test.rs
crates/sui/src/keytool.rs
sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs
sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs
sui-execution/v2/sui-adapter/src/programmable_transactions/context.rs

Add additional signature and linkage checks.
Additional local tests.
---

Add additional signature and linkage checks

---

crates/sui-e2e-tests/tests/address_balance_tests.rs

To unblock CI while we investgiate
---

Temporarily ignore address balance tests

---

external-crates/move/crates/move-package-alt/src/compatibility/legacy_parser.rs

[pkg-alt] Fix

---

docker/sui-indexer-alt-consistent-store/Dockerfile
docker/sui-indexer-alt-consistent-store/build.sh

create docker file for sui-indexer-alt-consistent-store
---

consistent store dockerfile

---

external-crates/move/crates/move-package-alt-compilation/src/build_plan.rs
external-crates/move/crates/move-package-alt-compilation/src/compiled_package.rs
external-crates/move/crates/move-package-alt-compilation/src/lib.rs
external-crates/move/crates/move-package-alt-compilation/src/model_builder.rs
external-crates/move/crates/move-package-alt/src/graph/mod.rs
external-crates/move/crates/move-package-alt/src/package/root_package.rs

[pkg-alt] Few new things

---

.github/workflows/cargo-llvm-cov.yml

Setting swap space is now taking longer
👀

Code coverage: increase timeout

---

docs/content/concepts/sui-move-concepts/packages/automated-address-management.mdx
docs/content/concepts/sui-move-concepts/packages/custom-policies.mdx
docs/content/concepts/sui-move-concepts/packages/upgrade.mdx

Adding description and keyword frontmatter to `concepts/sui-move-concepts/packages` pages.
N/A
---

docs: add frontmatter to `concepts/sui-move-concepts/packages`

---

docs/content/concepts/transactions/gas-smashing.mdx
docs/content/concepts/transactions/prog-txn-blocks.mdx
docs/content/concepts/transactions/sponsored-transactions.mdx

Adding description and keyword frontmatter to `concepts/transactions` pages.
N/A
---

docs: Add frontmatter to `concepts/transactions` pages

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/transaction_driver/error.rs
crates/sui-core/src/transaction_driver/mod.rs
crates/sui-core/src/transaction_orchestrator.rs
crates/sui-e2e-tests/tests/full_node_tests.rs
crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
crates/sui-json-rpc/src/error.rs
crates/sui-node/src/lib.rs
crates/sui-rpc-api/src/error.rs
crates/sui-types/src/quorum_driver_types.rs

Pick #22986 to 1.54

---

docs/content/guides/developer/coin/in-game-token.mdx
docs/content/guides/developer/coin/loyalty.mdx
docs/content/guides/developer/coin/regulated.mdx

Adding description and keyword frontmatter to `coin` pages.
N/A
---

docs: add frontmatter to `coin` pages

---

.github/CODEOWNERS

Add @consensus to client module reviewers

---

crates/sui-types/src/messages_consensus.rs

Address ordinal serialization issue with CheckpointSignatureV2
Existing regression
---

Move CheckpointSignatureV2 to the end of ConsensusTransactionKey

---

docs/content/standards/closed-loop-token.mdx
docs/content/standards/closed-loop-token/action-request.mdx
docs/content/standards/closed-loop-token/coin-token-comparison.mdx
docs/content/standards/closed-loop-token/rules.mdx
docs/content/standards/closed-loop-token/spending.mdx
docs/content/standards/closed-loop-token/token-policy.mdx
docs/content/standards/coin.mdx
docs/content/standards/deepbook.mdx
docs/content/standards/deepbookv2.mdx
docs/content/standards/deepbookv3-indexer.mdx
docs/content/standards/deepbookv3-sdk.mdx
docs/content/standards/deepbookv3.mdx
docs/content/standards/display.mdx
docs/content/standards/kiosk-apps.mdx
docs/content/standards/kiosk.mdx
docs/content/standards/wallet-standard.mdx

Adding description and keyword frontmatter to `standards/*` pages
N/A
---

docs: Add frontmatter to `standards/*` pages

---

Cargo.lock
Cargo.toml
crates/sui-indexer-alt-jsonrpc/Cargo.toml
crates/sui-indexer-alt-jsonrpc/src/lib.rs
crates/sui-indexer-alt-jsonrpc/src/metrics/middleware.rs
crates/sui-indexer-alt-jsonrpc/src/metrics/mod.rs

Cancelled jsonrpc-alt requests are not logged or recored by success/failure metrics because they never reach deeply enough into the `MetricsFuture::poll` method because the future is still in pending state when the request is cancelled. A `Drop` implementation is needed to capture cancelled requests. Since the `inner` of `MetricsFuture` is pinned by `pin_project` where a regular `Drop` impl is not allowed, a `PinnedDrop` impl is needed. This PR implements that. More context under [this
thread](https://mysten-labs.slack.com/archives/C08FWRBHW82/p1754118272614949?thread_ts=1754089823.227799&cid=C08FWRBHW82).
Also logging is added for slow requests even when they succeed to finish.
Tested locally by simulating a long request with `sleep`:
```
2025-08-11T05:37:01.584092Z  INFO …
```

[cherrypick][rpc-alt] implement PinnedDrop for MetricsFuture (#23018)

---

Cargo.lock
crates/simulacrum/src/lib.rs
crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/end_of_epoch.move
crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/end_of_epoch.snap
crates/sui-indexer-alt-graphql/Cargo.toml
crates/sui-indexer-alt-graphql/schema.graphql
crates/sui-indexer-alt-graphql/src/api/types/move_package.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/change_epoch.rs
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
crates/sui-indexer-alt-graphql/staging.graphql
crates/sui-transactional-test-runner/src/args.rs

Support system packages for ChangeEpochTransaction kind
This PR is a follow-up from PR #22955
```
```
---
- #22955
- #23032 ⬅️

[graphql-alt] Support system packages for ChangeEpochTransaction kind

---

Cargo.lock
crates/sui-benchmark/Cargo.toml
crates/sui-benchmark/tests/simtest.rs
crates/sui-config/src/node.rs
crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_per_epoch_store.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-core/src/global_state_hasher.rs
crates/sui-e2e-tests/tests/checkpoint_tests.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-types/src/digests.rs

This change add node config allowing an operator to specify recovery configuration in the event of a fork.
New SIMtest
---

Implement fork recovery and associated testing

---

docker/sui-rpc-benchmark/Dockerfile
docker/sui-rpc-benchmark/build.sh

create dockerfile for sui-rpc-benchmark
---

sui-rpc-benchmark docker

---

crates/sui-core/src/authority_server.rs
crates/sui-core/src/transaction_orchestrator.rs

Return events, input & output objects if requested from local effects

---

crates/sui-core/src/transaction_orchestrator.rs

Do not log if we failed to get effects.
---

Minor logging improvements in transaction_orchestrator

---

docs/content/concepts/app-devs.mdx
docs/content/concepts/components.mdx
docs/content/concepts/cryptography.mdx
docs/content/concepts/dynamic-fields.mdx
docs/content/concepts/gaming.mdx
docs/content/concepts/graphql-rpc.mdx
docs/content/concepts/grpc-overview.mdx
docs/content/concepts/object-model.mdx
docs/content/concepts/object-ownership.mdx
docs/content/concepts/research-papers.mdx
docs/content/concepts/sui-architecture.mdx
docs/content/concepts/sui-move-concepts.mdx
docs/content/concepts/tokenomics.mdx
docs/content/concepts/transactions.mdx
docs/content/concepts/transfers.mdx
docs/content/concepts/versioning.mdx

Adding description and keyword frontmatter to `concepts/*` pages.
N/A
---

docs: add frontmatter to `concepts/*` pages

---

docs/content/guides/developer/getting-started/sui-install.mdx

docs: Misc fixes

---

crates/sui-adapter-transactional-tests/tests/dynamic_fields/shared_object.snap
crates/sui-adapter-transactional-tests/tests/programmable_transaction_examples/split_coin_share.snap
crates/sui-adapter-transactional-tests/tests/programmable_transaction_examples/transfer_shared.snap
crates/sui-adapter-transactional-tests/tests/shared/become_dynamic_field.snap
crates/sui-adapter-transactional-tests/tests/shared/become_dynamic_object_field.snap
crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_make_move_vec.snap
crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_make_move_vec_fails.snap
crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_merge_fails.snap
crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_move_call.snap
crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_move_call_fails.snap
crates/sui-adapter-transactional-tests/tests/shared/freeze.snap
crates/sui-adapter-transactional-tests/tests/shared/transfer.snap
crates/sui-adapter-transactional-tests/tests/shared/wrap.snap
crates/sui-adapter-transactional-tests/tests/transfer_object/shared.snap
crates/sui-core/src/authority/snapshots/sui_core__authority__execution_time_estimator__tests__execution_time_observer_v92.snap
crates/sui-open-rpc/spec/openrpc.json
crates/sui-protocol-config/src/lib.rs
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_92.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_92.snap
crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_92.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap

- Disable per_command_shared_object_transfer_rules
- Updated tests 
---

disable per_command_shared_object_transfer_rules

---

crates/sui-authority-aggregation/src/lib.rs
crates/sui-config/src/node.rs
crates/sui-core/src/authority_aggregator.rs
crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/transaction_orchestrator.rs
crates/sui-swarm-config/src/node_config_builder.rs
crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
crates/sui-types/src/committee.rs

- Experiment with slightly reducing amount of stake to which transctions are sent for signing.
- update snapshots

Experiment with slightly reducing amount of stake to which transctions are sent for signing

---

external-crates/move/crates/move-package-alt-compilation/src/build_config.rs
external-crates/move/crates/move-package-alt-compilation/src/compiled_package.rs

[pkg-alt] add modes to build config

---

docs/content/references/contribute/style-guide.mdx
docs/site/src/css/custom.css

This PR updates the documentation style guide by adding new sections and reorganizing the document's structure.
N/A
---

docs: Style guide updates

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.56.0 Version Bump

---

docs/content/concepts/cryptography/nautilus/using-nautilus.mdx
docs/content/guides/developer/app-examples/coin-flip.mdx
docs/content/guides/developer/app-examples/e2e-counter.mdx
docs/content/guides/developer/app-examples/recaptcha.mdx
docs/content/guides/developer/app-examples/trustless-swap.mdx
docs/content/guides/developer/first-app/publish.mdx
docs/content/guides/operator/observability.mdx
docs/content/references/cli/client.mdx

Applies the style guide rule for exclamation points (!) across the docs. 
N/A
---

docs: Style guide implementation: !

---

Cargo.lock
Cargo.toml
crates/sui-rpc-api/Cargo.toml
crates/sui-rpc-api/src/grpc/v2beta2/live_data_service/simulate/mod.rs
crates/sui-rpc-api/src/grpc/v2beta2/mod.rs
crates/sui-rpc-api/src/grpc/v2beta2/name_service.rs
crates/sui-rpc-api/src/grpc/v2beta2/signature_verification_service.rs
crates/sui-rpc-api/src/grpc/v2beta2/transaction_execution_service.rs

grpc: add support for NameService

---

.github/workflows/generate-branch-cut-prs.yml
scripts/gen_branch_cut_prs.sh

Generates framework bytecode snapshot and version bump PRs
Test Plan:
Two PRs were generated with the shell script:
https://github.com/MystenLabs/sui/pull/23286 and https://github.com/MystenLabs/sui/pull/23287
```
eugene@eugene-dev ~/code/sui/ (ebmifa/gen_branch_cut_prs) $ ./scripts/gen_branch_cut_prs.sh 
Switched to a new branch 'eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809'
Compiling sui-framework-snapshot v1.56.0 (/home/eugene/code/sui/crates/sui-framework-snapshot)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 8.01s
Running `target/debug/sui-framework-snapshot`
Staging all changed files...
[eugene/sui-v1.56.0-bytecode-framework-snapshot-20250825164809 f8d3f845c9] Sui v1.56.0 Framework Bytecode snapshot
6 files changed, 30 insertions(+)
create mode …
```

sui branch cut: generate all required PRs

---

.github/workflows/generate-branch-cut-prs.yml
scripts/gen_branch_cut_prs.sh

Fix the branch cut script
https://github.com/MystenLabs/sui/actions/runs/17251509105
PRs created:
https://github.com/MystenLabs/sui/pull/23315
https://github.com/MystenLabs/sui/pull/23314

Fix branch cut script

---

crates/sui-package-resolver/src/lib.rs
crates/sui-rpc-api/src/grpc/v2beta2/ledger_service/get_transaction.rs
crates/sui-rpc-api/src/grpc/v2beta2/ledger_service/mod.rs
crates/sui-rpc-api/src/grpc/v2beta2/live_data_service/simulate/mod.rs
crates/sui-rpc-api/src/grpc/v2beta2/transaction_execution_service.rs

grpc: populate clever error information

---

external-crates/move/crates/language-benchmarks/src/move_vm.rs

Missed in previous PR.
cargo move-clippy -D warnings 
---

Fix clippy warning

---

crates/sui-core/src/transaction_driver/mod.rs

[MFP] fix transaction type label

---

crates/sui-framework/packages/sui-framework/sources/registries/coin_registry.move
crates/sui-framework/packages/sui-framework/tests/registries/new_coin_registry_tests.move

[registry] wip, migration flows

---

crates/sui-core/src/authority/authority_store.rs

Tidehunter has a limit on number of batch entries(1M), we sometimes exceed it during snapshot restore
---

Limit batch size during snapshot restore

---

.github/workflows/release.yml

Check if tar tarball for the same version was already built
https://github.com/MystenLabs/sui/actions/runs/17442434977/job/49528477060

Check if tar ball for the same version was already built

---

crates/sui-framework/packages/sui-framework/sources/coin.move
crates/sui-framework/packages/sui-framework/sources/registries/coin_registry.move
crates/sui-framework/packages/sui-framework/tests/registries/coin_registry_tests.move

[coin registry] more tests for missed use cases

---

crates/sui-framework/packages/sui-framework/sources/deny_list.move
crates/sui-framework/packages/sui-framework/sources/test/test_scenario.move
crates/sui-framework/packages/sui-framework/tests/coin_tests.move
crates/sui-framework/packages/sui-framework/tests/deny_list_tests.move
crates/sui-framework/packages/sui-framework/tests/test_scenario_tests.move

+ generalizing common operations in `test_scenario`. Preparing for CoinRegistry and DisplayRegistry.
+ minor cleanup in test_scenario_tests
Features tests.
---

[framework] adds `test_scenario::create_system_objects`

---

docs/content/references/framework.mdx

[docs] Updated links

---

crates/sui-benchmark/src/lib.rs
crates/sui-core/src/transaction_driver/mod.rs
crates/sui-core/src/transaction_orchestrator.rs

[mfp] Enabled 50% TD everywhere but mainnet

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

Sui v1.57.0 Version Bump

---

docs/content/sidebars/concepts.js

[docs] Party left the nav

---

docs/content/concepts/object-ownership/party.mdx

Add info about pipelined party object tx to docs

---

Cargo.lock
Cargo.toml
crates/sui-e2e-tests/tests/rpc/v2beta2/ledger_service/get_object.rs
crates/sui-e2e-tests/tests/rpc/v2beta2/live_data_service/balance.rs
crates/sui-e2e-tests/tests/rpc/v2beta2/live_data_service/list_owned_objects.rs
crates/sui-e2e-tests/tests/rpc/v2beta2/mod.rs
crates/sui-types/src/rpc_proto_conversions.rs
crates/sui-types/src/sui_sdk_types_conversions.rs

Using the new helper from <https://github.com/MystenLabs/sui-rust-sdk/pull/147> in e2e tests.

Use new execute_and_wait hlper in e2e tests

---

external-crates/move/crates/move-vm-runtime/src/jit/mod.rs

Test with and without optimizations
cargo test
---

Test translate package

---

docs/content/guides/developer/advanced/randomness-onchain.mdx
docs/content/references/cli.mdx
docs/content/references/cli/client.mdx
docs/content/references/cli/replay.mdx
docs/content/references/cli/trace-analysis.mdx

Update docs for the new way of creating gas profiles form transaction replays.
👀 
---

[docs] Update docs for new gas profiler

---

crates/sui-indexer-alt-e2e-tests/tests/graphql/objects/received_transactions.move
crates/sui-indexer-alt-e2e-tests/tests/graphql/objects/received_transactions.snap
crates/sui-indexer-alt-graphql/schema.graphql
crates/sui-indexer-alt-graphql/src/api/types/coin_metadata.rs
crates/sui-indexer-alt-graphql/src/api/types/dynamic_field.rs
crates/sui-indexer-alt-graphql/src/api/types/move_object.rs
crates/sui-indexer-alt-graphql/src/api/types/move_package.rs
crates/sui-indexer-alt-graphql/src/api/types/object.rs
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
crates/sui-indexer-alt-graphql/staging.graphql

Support received_transactions for IObject
```
cargo nextest run -p sui-indexer-alt-e2e-tests
```
---

[graphql-alt] Support received_transactions for IObject

---

crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/paginate.move
crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/paginate.snap
crates/sui-indexer-alt-graphql/schema.graphql
crates/sui-indexer-alt-graphql/src/api/query.rs
crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
crates/sui-indexer-alt-graphql/staging.graphql

Add support for epoch pagination
---

graphql-alt: Query.epochs

---

crates/sui-kvstore/src/bigtable/client.rs

Transaction Events should be deserialized wrapped inside an `Option`.
Local testing
---

graphql-alt: Fix reading of transaction events

---

docs/content/guides/developer/sui-101/avoid-equivocation.mdx

Revisions for clarity and additional context regarding punishment for equivocation. 
---

docs: Update equivocation page [DOCS-149]

---

crates/sui-kvstore/src/bigtable/client.rs

Add filter for timestamp column when fetching from kv `Transactions` table.
locally connected to testnet kv and pg
---

graphql-alt: fix event timestamp

---

external-crates/move/Cargo.lock
external-crates/move/Cargo.toml
external-crates/move/crates/move-package-alt/Cargo.toml
external-crates/move/crates/move-package-alt/src/dependency/pin.rs
external-crates/move/crates/move-package-alt/src/errors/mod.rs
external-crates/move/crates/move-package-alt/src/graph/linkage.rs
external-crates/move/crates/move-package-alt/src/graph/mod.rs
external-crates/move/crates/move-package-alt/src/graph/package_info.rs
external-crates/move/crates/move-package-alt/src/package/root_package.rs
external-crates/move/crates/move-package-alt/src/schema/shared.rs

[package-alt] switch to top-down linkage computation

---

docs/content/references/contribute/style-guide.mdx
docs/content/references/sui-glossary.mdx

Adds glossary terms to the style guide and adds style guide terms to the glossary.
---

docs: Update glossary w/ style guide terms and style guide w/ glossary terms [DOCS-201]

---

crates/sui-core/src/authority.rs
crates/sui-core/src/authority/authority_store_pruner.rs
crates/sui-core/src/authority/authority_store_tables.rs
crates/sui-core/src/authority/test_authority_builder.rs
crates/sui-core/src/checkpoints/mod.rs
crates/sui-node/src/lib.rs
crates/sui-tool/src/db_tool/db_dump.rs
crates/sui-tool/src/db_tool/mod.rs
crates/sui-tool/src/lib.rs

relocation integration with checkpoints db
---

[tidehunter] intergrate relocation to checkpoint db

---

crates/sui-indexer-alt-consistent-store/src/rpc/metrics.rs

The values passed for labels for the success metric are the path and the status code, not the service name and method name.
CI
---

fix(consistency): request success metric labels

---

external-crates/move/crates/move-binary-format/src/file_format.rs
external-crates/move/crates/move-binary-format/src/lib.rs

It is only used in `signature_token_kind` which is also dead.
---

Remove SignatureTokenKind

---

.github/workflows/pre-build-images.yml

so that we don't even out the build jobs load
might need to land first because this is a new workflow
---

chore: prebuild all commits merged into main and releases

---

crates/sui-core/src/authority/authority_store.rs
crates/sui-core/src/execution_driver.rs
crates/sui-core/src/unit_tests/authority_tests.rs
crates/sui-grpc-rosetta/src/operations.rs
crates/sui-move/Cargo.toml
crates/sui-move/src/unit_test.rs
crates/sui-node/src/lib.rs
crates/sui-replay-2/src/execution.rs
crates/sui-replay/src/replay.rs
crates/sui-transactional-test-runner/src/test_adapter.rs
external-crates/move/crates/move-vm-runtime/src/dev_utils/tiered_gas_schedule.rs
sui-execution/latest/sui-adapter/src/temporary_store.rs
sui-execution/src/latest.rs
sui-execution/v0/sui-adapter/src/execution_value.rs
sui-execution/v0/sui-adapter/src/programmable_transactions/linkage_view.rs
sui-execution/v1/sui-adapter/src/execution_value.rs
sui-execution/v1/sui-adapter/src/programmable_transactions/linkage_view.rs
sui-execution/v2/sui-adapter/src/execution_value.rs
sui-execution/v2/sui-adapter/src/programmable_transactions/linkage_view.rs

Nothing major here. Just removing the last merge conflict markers and fixing all remaining clippy errors + `cargo fmt`.
No tests on the Sui side yet as need to get the values stuff in the new VM + adapter working first.

[4/n][bella-ciao][sui] Finish merge on sui side -- fix remaining merge conflicts and clippy issues

---

.github/workflows/pre-build-images.yml

Add caller_name to pre-build images workflow

---

external-crates/move/crates/move-vm-runtime/src/execution/interpreter/locals.rs
sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/values.rs

Fill out the `BaseHeap` with needed functions, and update things as appropriate on the adapter side.
Currently 👀  however getting very close to getting the adapter up and running (hopefully in the next PR or two). 
---

[6/n][bella-ciao][heap] Move adapter values over to using the heap instead of stack frames

---

crates/sui-indexer-alt-graphql/src/api/types/event/filter.rs
crates/sui-indexer-alt-graphql/src/api/types/event/lookups.rs
crates/sui-indexer-alt-graphql/src/api/types/event/mod.rs
crates/sui-indexer-alt-graphql/src/api/types/lookups.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction/filter.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction/mod.rs

Reduces some of the duplicate code between event and transaction cursors.
Existing tests cover refactor.
---

graphql-alt: join bounds query with filter query

---

crates/sui-indexer-alt-graphql/src/lib.rs

Graphql-beta is not currently handling CORs properly. This PR resolves it.
Before:
```
curl -X OPTIONS -f http://localhost:7000/graphql -H "Content-Type: application/json" -H "Access-Control-Request-Method: PUT" -H "Origin: http://example.com"   --data '{ "query": "query { epoch { epochId } }"}'
curl: (22) The requested URL returned error: 405
```
After:
```
curl -X OPTIONS -f http://localhost:7000/graphql -H "Content-Type: application/json" -H "Access-Control-Request-Method: POST" -H "Origin: http://example.com"   --data '{ "query": "query { epoch { epochId } }"}' -v
* Host localhost:7000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:7000...
* connect to ::1 port 7000 from ::1 port 53024 failed: Connection refused
*   Trying …
```

[graphl-beta] resolve CORs issues

---

docs/site/package.json
docs/site/pnpm-lock.yaml
docs/site/src/theme/DocBreadcrumbs/index.js
docs/site/src/theme/DocBreadcrumbs/styles.module.css

Adds a hamburgler menu above the toc button on mobile devices.
---

[docs] Add mobile nav

---

docker/stress/Dockerfile
docker/sui-tools/Dockerfile

migrate stress off sui-tools

---

crates/sui-core/src/authority/authority_store_tables.rs

More tidehunter configs for testnet

---

Cargo.lock
Cargo.toml
crates/sui-e2e-tests/tests/rpc/v2/ledger_service/get_checkpoint.rs
crates/sui-kv-rpc/src/v2/get_object.rs
crates/sui-rpc-api/src/grpc/v2/ledger_service/get_checkpoint.rs
crates/sui-rpc-api/src/grpc/v2/ledger_service/get_object.rs
crates/sui-rpc-api/src/grpc/v2/state_service/list_dynamic_fields.rs
crates/sui-rpc-api/src/grpc/v2/state_service/list_owned_objects.rs
crates/sui-rpc-api/src/grpc/v2/transaction_execution_service/mod.rs
crates/sui-rpc-api/src/grpc/v2/transaction_execution_service/simulate/mod.rs
crates/sui-types/src/rpc_proto_conversions.rs

grpc: update v2 protos to account for new ObjectSet message

---

docs/content/guides/operator/snapshots.mdx

[docs] Request payer db snapshots only

---

docs/content/standards.mdx

fix: Capitalization

---

external-crates/move/move-execution/v2/crates/move-vm-runtime/src/loader.rs

ModuleCache::calculate_depth_of_type: Error when refs and mut-ref are passed

---

Cargo.lock
Cargo.toml
crates/sui-rpc-api/src/grpc/v2/state_service/list_dynamic_fields.rs

grpc: update DynamicField for v2

---

crates/sui-core/src/transaction_driver/mod.rs

On a latency checks run, spin up all the tasks under the same JoinSet across the tx types. Otherwise, with the current time out setups, it's possible for a latency check run to take more than `15s` and essentially ending up running the latency checks with lower frequency.
CI/PT
---

[MFP] improve latency checks task

---

docker/stress/Dockerfile
docker/sui-tools/Dockerfile

---
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must …

migrate stress off sui-tools (#23603)

---

docs/content/concepts/archival-store.mdx

docs: clean up empty bullet

---

crates/sui-core/src/quorum_driver/mod.rs
crates/sui-core/src/transaction_driver/mod.rs
crates/sui-core/src/transaction_orchestrator.rs
crates/sui-core/src/validator_client_monitor/mod.rs

Current label is reversed.
Also, improve metrics in TransactionOrchestrator and apply some minor cleanups.
CI

[QD] fix tx_type label

---

docs/content/concepts/custom-indexer/pipeline-architecture.mdx
docs/content/concepts/sui-move-concepts/packages/custom-policies.mdx
docs/site/src/components/ImportContent/utils.js

Struct import was broken. Also fixes a few implementation mistakes.
---

[docs] fixes struct import

---

crates/sui-indexer-alt-graphql/schema.graphql
crates/sui-indexer-alt-graphql/src/api/types/validator_set.rs
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
crates/sui-indexer-alt-graphql/staging.graphql

Addresses two comments in the PR that added validator pagination:
https://github.com/MystenLabs/sui/pull/23639#discussion_r2362440662
https://github.com/MystenLabs/sui/pull/23639#discussion_r2362443504
No new functionality.
---

graphql-alt: convert ValidatorSet to Object

---

Cargo.lock
crates/sui-tool/Cargo.toml
crates/sui-tool/src/lib.rs

Export metrics during formal snapshot restore

---

docker/stress/Dockerfile

chore: Add back missing working directory for stress Dockerfile

---

crates/sui-types/src/object.rs

By default, only print basic object metadata in Debug. If full object contents are needed, set `SUI_OBJECT_DEBUG_VERBOSE=1`

Do not print full object contents in Debug impl by default

---

crates/sui-move-build/src/lib.rs
crates/sui-move/src/unit_test.rs
external-crates/move/crates/move-analyzer/src/symbols/compilation.rs
external-crates/move/crates/move-cli/src/base/test.rs
external-crates/move/crates/move-cli/src/sandbox/commands/test.rs
external-crates/move/crates/move-cli/src/sandbox/utils/package_context.rs
external-crates/move/crates/move-docgen-tests/tests/testsuite.rs
external-crates/move/crates/move-package-alt/src/flavor/mod.rs
external-crates/move/crates/move-package-alt/src/package/mod.rs
external-crates/move/crates/move-package-alt/src/package/root_package.rs
external-crates/move/crates/move-stackless-bytecode-2/tests/from_source.rs
external-crates/move/crates/move-stackless-bytecode-2/tests/tests.rs

[pkg-alt] Enable synchronous loading

---

external-crates/move/crates/move-vm-runtime/src/execution/interpreter/eval.rs

Fix gas metering of CastU32 and CastU256

---

external-crates/move/crates/move-binary-format/src/normalized.rs
external-crates/move/crates/move-binary-format/src/unit_tests/equivalence_tests.rs

As it says on the tin.
New tests added to ensure the parameters and return type are not used for equivalence.
---

[move][normalized-binary-format] Add parameters and return to function refs

---

crates/sui-framework/packages/move-stdlib/tests/ascii_tests.move
crates/sui-framework/packages/move-stdlib/tests/bcs_tests.move
crates/sui-framework/packages/move-stdlib/tests/bit_vector_tests.move
crates/sui-framework/packages/move-stdlib/tests/fixedpoint32_tests.move
crates/sui-framework/packages/move-stdlib/tests/hash_tests.move
crates/sui-framework/packages/move-stdlib/tests/option_tests.move
crates/sui-framework/packages/move-stdlib/tests/string_tests.move
crates/sui-framework/packages/move-stdlib/tests/uq32_32_tests.move
crates/sui-framework/packages/move-stdlib/tests/vector_tests.move

[chore, framework] cleanup tests in move-stdlib

---

crates/sui-indexer-alt-graphql/schema.graphql
crates/sui-indexer-alt-graphql/src/api/query.rs
crates/sui-indexer-alt-graphql/src/api/scalars/fq_name_filter.rs
crates/sui-indexer-alt-graphql/src/api/scalars/module_filter.rs
crates/sui-indexer-alt-graphql/src/api/scalars/type_filter.rs
crates/sui-indexer-alt-graphql/src/api/types/checkpoint/mod.rs
crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
crates/sui-indexer-alt-graphql/src/api/types/event/filter.rs
crates/sui-indexer-alt-graphql/src/api/types/event/lookups.rs
crates/sui-indexer-alt-graphql/src/api/types/event/mod.rs
crates/sui-indexer-alt-graphql/src/api/types/gas_input.rs
crates/sui-indexer-alt-graphql/src/api/types/move_module.rs
crates/sui-indexer-alt-graphql/src/api/types/move_package.rs
crates/sui-indexer-alt-graphql/src/api/types/object.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction/mod.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/authenticator_state_update.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/change_epoch.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/end_of_epoch.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/genesis.rs
crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/programmable/mod.rs
crates/sui-indexer-alt-graphql/src/api/types/validator_set.rs
crates/sui-indexer-alt-graphql/src/pagination.rs
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
crates/sui-indexer-alt-graphql/staging.graphql

Some refactorings we discussed as a team to clean up pagination.
Existing tests, these are pure refactorings.
---

refactor(graphql): various pagination related refactorings

---

crates/sui-graphql-rpc/schema.graphql
crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
crates/sui-graphql-rpc/staging.graphql
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
crates/sui-kvstore/src/bigtable/proto/google.bigtable.v2.rs
crates/sui-move-build/src/lib.rs
crates/sui-proxy/src/consumer.rs
crates/sui-sql-macro/src/lib.rs
crates/sui-storage/src/package_object_cache.rs
crates/sui-types/src/proto_value.rs
crates/sui-types/src/transaction_executor.rs
crates/sui/src/client_commands.rs
sui-execution/latest/sui-adapter/src/execution_engine.rs
sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
sui-execution/latest/sui-move-natives/src/test_scenario.rs
sui-execution/v0/sui-adapter/src/execution_engine.rs
sui-execution/v1/sui-adapter/src/execution_engine.rs
sui-execution/v2/sui-adapter/src/execution_engine.rs

Remove redundant words in comments and documentation
---

chore: remove redundant words in comments and documentation

---

docs/site/vercel.json

[docs] redirect deepbookv3

---

.github/workflows/pre-build-images.yml

[prebuild] non main should trigger arm64 builds

---

external-crates/move/crates/move-model-2/src/model.rs

What it says on the tin
Tests still pass
---

[move][move-model-2] Fix type mapping for T::U32 and T::U256

---

docs/content/guides/developer/getting-started/graphql-rpc.mdx

Add a section to "Beta schema changes" explaining the ways in which dry-run, gas estimation, and coin selection have changed since alpha.
:eyes:
---

docs(graphql): explain differences to simulateTransaction

---

crates/sui-core/src/authority/authority_store_tables.rs
crates/sui-core/src/checkpoints/mod.rs
crates/typed-store/src/rocks/mod.rs
crates/typed-store/src/tidehunter_util.rs

More tidehunter-related tuning for validator tables

---

crates/sui-kvstore/src/bigtable/client.rs
crates/sui-kvstore/src/bigtable/init.sh

cherry pick of  alternative watermark implementation in BigTable
---

[kv store] cherry pick of alternative watermark implementation

---

crates/sui-core/src/transaction_driver/mod.rs

Check env var first before checking for current network.
CI
---

[mfp] allow MFP to be enabled via env var on mainnet

---

Cargo.lock
Cargo.toml
crates/sui-open-rpc/spec/openrpc.json

This reverts commit f582e625e7afef6f43104a384b30824f97bbd278.
Revert "Sui v1.59.0 Version Bump (#23825)"
👀

Revert "Sui v1.59.0 Version Bump (#23825)"

---

external-crates/move/crates/move-package-alt-compilation/src/build_config.rs
external-crates/move/crates/move-package-alt-compilation/src/compilation.rs

[pkg-alt] Allow to set unpublished deps' addresses to 0x0 if a flag is set

---

crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_deny_and_undeny_address_balance_receiver.move
crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_deny_and_undeny_address_balance_receiver.snap
crates/sui-adapter-transactional-tests/tests/deny_list_v2/coin_deny_and_undeny_address_balance_receiver@v2.snap

Remove --simulator on transactional test

---

external-crates/move/crates/move-vm-runtime/src/jit/execution/translate.rs

Remove unnecessary unwraps

---

external-crates/move/crates/move-vm-runtime/src/execution/dispatch_tables.rs

Print the datatype.defining_id in error

---

crates/sui-config/src/validator_client_monitor_config.rs
crates/sui-core/src/authority_server.rs
crates/sui-core/src/transaction_driver/effects_certifier.rs
crates/sui-core/src/transaction_driver/mod.rs
crates/sui-core/src/transaction_driver/transaction_submitter.rs
crates/sui-core/src/transaction_driver/unit_tests/effects_certifier_tests.rs
crates/sui-core/src/unit_tests/submit_transaction_tests.rs
crates/sui-core/src/unit_tests/wait_for_effects_tests.rs
crates/sui-types/src/messages_consensus.rs
crates/sui-types/src/messages_grpc.rs

Log transaction submission steps with timestamps, for debugging and latency investigations.
CI

[mfp] log actions during transaction submission

---

crates/sui-rpc-api/src/grpc/v2/transaction_execution_service/mod.rs

Fix a bug where we weren't properly rendering fields based on the provided read_mask leading to empty responses.
---

grpc: fix bug with rendering fields in ExecuteTransaction

---

.github/workflows/simulator-nightly.yml

Update Teleport version and certificate TTL

---

external-crates/move/crates/move-vm-runtime/src/jit/execution/translate.rs

Remove to_owned from Copy types

---

external-crates/move/crates/move-vm-runtime/src/dev_utils/gas_schedule.rs

Also add a comment in instruction_cost to clarify that instr_index starts at 1
---

Move the debug_assert at the right place

---

consensus/core/src/commit_finalizer.rs
consensus/core/src/metrics.rs
crates/sui-core/src/consensus_handler.rs

Also fix the metrics for finalized and rejected transactions post commit.

[mfp] add a counter on reject votes

---

.github/workflows/release-notes-monitor.yml

Make release notes monitor safer still
👀

Make release notes monitor safer still
