- crates/sui-indexer-alt-framework/src/pipeline/concurrent/collector.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs
- Row chunk size should default to `i16::MAX` if the field count is `0`.
- Fold the `if empty { ... }` check into the `debug_assert` so "nothing gets left behind" when we're building for release (in reality the compiler will probably not have a problem with compiling this out, but it's good practice to fold the full condition into assert body).
CI
---
> easy(indexer-alt): small clean-ups

- crates/sui-data-ingestion/src/lib.rs
- crates/sui-data-ingestion/src/main.rs
- crates/sui-data-ingestion/src/progress_store.rs
- crates/sui-kvstore/src/bigtable/client.rs
- crates/sui-kvstore/src/bigtable/init.sh
- crates/sui-kvstore/src/lib.rs
This reverts commit 7eadb135535da670a73b4c1dd790cf829586dbb9.
The hot row-hot cell pattern significantly slows down writes to Bigtable, impacting the ingestion speed of core pipelines
---
> Revert "[kv store] add watermark table to bigtable (#20390)"

- crates/sui-data-ingestion-core/src/reader.rs
temporary PR. Implicitly redirects traffic to the GCS bucket directly making external developers to use a cheaper version of service
---
> [data ingestion] redirect traffic to the bucket directly

- apps/wallet/src/ui/app/components/known-scam-overlay/index.tsx
- apps/wallet/src/ui/app/components/known-scam-overlay/types.ts
- apps/wallet/src/ui/app/components/known-scam-overlay/useShowScamWarning.tsx
- apps/wallet/src/ui/app/components/user-approve-container/index.tsx
Displays optional warnings from the dapp preflight. Adds ability to dismiss the overlay to support the "Proceed" action. "Proceed" simply hides the overlay and allows the user to continue their action.
|With warnings (block disabled)|With hard block|
|-|-|
|<img width="472" alt="image" src="https://github.com/user-attachments/assets/bff4e62b-31da-4ca7-9ddb-c88ce26e0f28" />|<img width="472" alt="image" src="https://github.com/user-attachments/assets/edc65027-a71f-4989-8a2e-e958960da618" />|
--- …
> Display preflight warnings

- crates/sui-deepbook-indexer/src/server.rs
DEEP Supply Endpoint: /deep_supply
Returns: 9997742312719287 (represents 9,997,742,312 DEEP)
Tested locally
> DEEP Supply Endpoint

- crates/sui-benchmark/src/workloads/randomized_transaction.rs
DKG may take seconds to complete, which cause randomness transaction experiencing `TooOldTransactionPendingOnObject`, which has 500ms queue age limit.
Thanks @aschran for the insight!
---
> Add a short wait at the beginning of randomized workload

- Cargo.lock
- Cargo.toml
- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/committer.rs
- crates/sui-indexer-alt-jsonrpc/Cargo.toml
- crates/sui-indexer-alt-jsonrpc/src/api/governance.rs
- crates/sui-indexer-alt-jsonrpc/src/api/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/args.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
- crates/sui-indexer-alt-jsonrpc/src/main.rs
- crates/sui-pg-db/src/lib.rs
Initial scaffolding for a JSONRPC service that talks to the indexer-alt schema. This service only responds to `suix_getReferenceGasPrice` currently, and tries to take as few dependencies as possible on the existing JSONRPC infra, so that it will not hold-up its deprecation and eventual clean up.
We also introduce some clean-ups to supporting crates, in their own commits -- these commits will be landed unsquashed.
Some new unit tests:
```
sui$ cargo nextest run -p sui-indexer-alt-jsonrpc
sui$ cargo nextest run -p sui-pg-db -- test_read_only
```
Run the service:
```
sui$ RUST_LOG="INFO,sui_indexer_alt_jsonrpc=DEBUG" cargo run -p sui-indexer-alt-jsonrpc -- \
--database-url $DB_URL --listen-address 127.0.0.1:5000
```
And query the method:
```
sui$ curl -LX POST  "http://localhost:5000" \ …
```
> rpc-alt: initial scaffold

- crates/sui/src/unit_tests/fixtures/upgrade_errors/function_errors_v1/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/function_errors_v2/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/type_param_errors_v1/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/type_param_errors_v2/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__all.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__function.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__type_param.snap
- crates/sui/src/upgrade_compatibility.rs
function signature upgrade errors test and improve formatting for:
- type params in functions
- vectors
- &
- mut
- structs
---
> upgrade errors advanced function signatures 

- crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
- crates/sui-graphql-rpc/src/server/builder.rs
- crates/sui-mvr-graphql-rpc/src/extensions/query_limits_checker.rs
- crates/sui-mvr-graphql-rpc/src/server/builder.rs
Treat `verifyZkloginSignature`'s `bytes` and `signature` arguments as part of the "transaction payload" for the purposes of enforcing GraphQL request size limits, as this endpoint can be used to verify the signature on a transaction and without this change, it would not be possible to verify signatures on larger transactions (over 5KiB by default).
Fixes #20638
```
sui$ cargo nextest run -p sui-graphql-rpc -p sui-mvr-graphql-rpc -- server::builder::tests
```
---
> graphql: treat verifyZkloginSignature inputs as transaction payload

- .changeset/brown-gorillas-jam.md
- sdk/typescript/src/transactions/Transaction.ts
> [sdk] improve typing of splitCoins and make splitCoins have a concrete size

- external-crates/move/crates/move-package/src/compilation/compiled_package.rs
> add filemap to compiled package

- .github/workflows/bridge.yml
Revet the foundry install workflow.
---
> Revert foundryup install

- crates/sui/src/unit_tests/fixtures/upgrade_errors/enum_errors_v1/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/enum_errors_v2/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/struct_errors_v1/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/struct_errors_v2/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__enum.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__struct.snap
- crates/sui/src/upgrade_compatibility.rs
Adds tests and formatting fixes for:
- positional fields on structs and enums
- more cases  for named fields on enums
- positional struct nested in struct
- positional struct nested in enum
snapshot testing
---
> upgrade errors formatting positional fields, nested fields, named fields on enums

- crates/sui-config/src/node.rs
- crates/sui-e2e-tests/tests/rpc/checkpoints.rs
- crates/sui-e2e-tests/tests/rpc/committee.rs
- crates/sui-e2e-tests/tests/rpc/main.rs
- crates/sui-e2e-tests/tests/rpc/node_info.rs
- crates/sui-e2e-tests/tests/rpc/objects.rs
- crates/sui-e2e-tests/tests/rpc/transactions.rs
- crates/sui-node/src/lib.rs
- crates/sui-rpc-api/openapi/openapi.json
- crates/sui-rpc-api/proto/sui.node.v2.proto
- crates/sui-rpc-api/src/client/sdk.rs
- crates/sui-rpc-api/src/config.rs
- crates/sui-rpc-api/src/lib.rs
- crates/sui-rpc-api/src/proto/generated/sui.node.v2.rs
- crates/sui-rpc-api/src/proto/node.rs
- crates/sui-rpc-api/src/rest/health.rs
- crates/sui-rpc-api/src/rest/mod.rs
- crates/sui-rpc-api/src/types.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Stabilize the MVP of the new Fullnode gRPC api which is intended to eventually obsolesce the existing JSON-RPC api on Fullnodes.
---
Stabilize the MVP of the new Fullnode gRPC api which is intended to eventually obsolesce the existing JSON-RPC api on Fullnodes.
> Stabilize MVP of the new Fullnode gRPC api

- crates/sui-core/src/authority.rs
- crates/sui-json-rpc/src/authority_state.rs
- crates/sui-json-rpc/src/coin_api.rs
- crates/sui-storage/src/bin/http_kv_tool.rs
- crates/sui-storage/src/http_key_value_store.rs
- crates/sui-storage/src/key_value_store.rs
- crates/sui-storage/tests/key_value_tests.rs
query events still accesses old events key  
---
> [kv store] json rpc: remove leftover call sites to old events API

- Cargo.lock
- Cargo.toml
- crates/sui-indexer-alt-restorer/Cargo.toml
- crates/sui-indexer-alt-restorer/src/archives.rs
- crates/sui-indexer-alt-restorer/src/lib.rs
- crates/sui-indexer-alt-restorer/src/main.rs
- crates/sui-indexer-alt-restorer/src/snapshot.rs
- crates/sui-indexer-alt-schema/Cargo.toml
- crates/sui-indexer-alt-schema/src/objects.rs
- crates/sui-indexer-alt/src/handlers/obj_info.rs
title, the main parts are:
- read archival storage for checkpoint info of seq number and chain identifier
- read snapshot files and restore obj_info table
local run
```
cargo run --bin sui-indexer-alt-restorer -- --start-epoch 600 --endpoint "https://formal-snapshot.mainnet.sui.io" --snapshot-bucket "mysten-mainnet-formal" --archive-bucket "mysten-mainnet-archives" --snapshot-local-dir "/Users/gegao/Desktop/formal" --database-url "postgres://postgres:postgres@localhost/gegao"
```
it's worth doing some data integrity check eventually and not done yet. 
--- …
> indexer restorer: init commit and restore object infos

- crates/sui-core/src/consensus_adapter.rs
This is one of the change that is proposed from [SIP-45](https://github.com/sui-foundation/sips/pull/45).
Planning to make another separated PR for protocol config, that is:
- Let K be a part of protocol config.
- Increase max gas price in protocol config.
CI
> Add consensus amplification for SIP-45

- crates/sui-graphql-rpc/src/test_infra/cluster.rs
- crates/sui-graphql-rpc/tests/e2e_tests.rs
- crates/sui-mvr-graphql-rpc/src/test_infra/cluster.rs
- crates/sui-mvr-graphql-rpc/tests/e2e_tests.rs
When we submit a transaction to the test cluster while the nodes are reconfiguring for the new epoch, they will likely time out, causing several tests to frequently flake out.
Flakey tests pass without multiple retries
---
> [gql] Increase EPOCH_DURATION_MS to reduce tests interacting with reconfiguration

- external-crates/move/tooling/prettier-extension/package-lock.json
- external-crates/move/tooling/prettier-extension/package.json
- external-crates/move/tooling/prettier-extension/src/extension.js
- external-crates/move/tooling/prettier-extension/src/formatter-worker.js
Updates the extension dependency to match the most recent plugin version.
---
> [formatter] Update VSCode Extension to V2

- Cargo.lock
- crates/suiop-cli/Cargo.toml
- crates/suiop-cli/src/cli/pulumi/deps.rs
- crates/suiop-cli/src/cli/pulumi/mod.rs
- crates/suiop-cli/src/command.rs
Command to trigger a dependency update for all pulumi programs in the given directory. This will make codemod updates for things like PRO-194 much easier
```
cargo run -- p u ~/mysten/sui-operations/pulumi/apps              
Compiling suiop-cli v1.40.0 (/Users/jkjensen/mysten/sui/crates/suiop-cli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 6.20s
Running `/Users/jkjensen/mysten/sui/target/debug/suiop p u /Users/jkjensen/mysten/sui-operations/pulumi/apps`
2024-12-24T17:23:14.098064Z  INFO suioplib::cli::pulumi::deps: Processing subdirectory: /Users/jkjensen/mysten/sui-operations/pulumi/apps/suifrens
2024-12-24T17:23:14.098584Z  INFO suioplib::cli::pulumi::deps: Updating dependencies for python
2024-12-24T17:23:14.098591Z  INFO suioplib::cli::pulumi::deps: Updating …
```
> [suiop][pulumi] update command

- examples/move/transfer-to-object/shared-no-tto/sources/shared_cash_register.move
- examples/move/transfer-to-object/shared-with-tto/sources/shared_cash_register.move
Remove redundant slash in the example code comment
N/A
---
> [examples] Remove redundant slash

- crates/suiop-cli/src/cli/pulumi/deps.rs
Some projects don't use poetry
Ran locally successfully on the services dir, which includes non-poetry python projects.
---
> [suiop][pulumi] handle non-poetry projects

- crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
- crates/sui-indexer-alt-framework/src/watermarks.rs
Clarified in the doc comment for `prune` that `to` should be exclusive instead of inclusive.
Also updated the prune loop to make it clearer.
We probably want to write some tests.
---
> [indexer-alt] Fix comments in pruner `to`

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-core/src/execution_driver.rs
- crates/sui-core/src/storage.rs
- crates/sui-json-rpc/src/authority_state.rs
- crates/sui-node/src/lib.rs
- crates/sui-node/src/main.rs
- crates/sui-snapshot/src/uploader.rs
- crates/sui-snapshot/src/writer.rs
- crates/sui-telemetry/src/lib.rs
As part of fixing flakey graphql tests, I observed an inconsistency in how the fullnode rpc in TestCluster was reporting chain_identifier. The nodes wrote `0.chk` to file with a particular checkpoint digest->chain_id, but the rpc would report a different chain_id. Conspicuously, the chain_id was the same across tests.
The issue stemmed from using a global static OnceCell<ChainIdentifier>. This global state meant that if the `test_simple_client_validator_cluster` test did not set the `chain_id`, then it would fail. I suppose there might be some production issues as well, for example if someone were to run multiple nodes in the same process to different networks.
To address, I moved chain_identifier into AuthorityState, and modified SuiNode to explicitly pass the chain_identifier to …
> Move static OnceCell ChainIdentifier into AuthorityState

- crates/sui-graphql-rpc/schema.graphql
- crates/sui-graphql-rpc/src/config.rs
- crates/sui-graphql-rpc/src/extensions/query_limits_checker.rs
- crates/sui-graphql-rpc/src/server/builder.rs
- crates/sui-graphql-rpc/src/types/object.rs
- crates/sui-graphql-rpc/src/types/query.rs
- crates/sui-graphql-rpc/staging.graphql
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
- crates/sui-mvr-graphql-rpc/schema.graphql
- crates/sui-mvr-graphql-rpc/src/config.rs
- crates/sui-mvr-graphql-rpc/src/extensions/query_limits_checker.rs
- crates/sui-mvr-graphql-rpc/src/server/builder.rs
- crates/sui-mvr-graphql-rpc/src/types/object.rs
- crates/sui-mvr-graphql-rpc/src/types/query.rs
- crates/sui-mvr-graphql-rpc/staging.graphql
- crates/sui-mvr-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
- crates/sui-mvr-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
This PR adds a new query for fetching multiple objects by their ids and versions.
Added two new tests to check that the limits work as expected.
- `test_multi_get_objects_query_limits_pass`
- `test_multi_get_objects_query_limits_exceeded`
---
> [GraphQL] Add a new `multiGetObjects` query on `Query`. 

- external-crates/move/crates/move-compiler/src/diagnostics/mod.rs
- external-crates/move/crates/move-compiler/src/typing/deprecation_warnings.rs
- sui-execution/latest/sui-move-natives/src/config.rs
spotted some abundant words in msgs and removed them.
> fix: remove some duplicate words in msgs

- docs/content/guides/developer/cryptography/zklogin-integration.mdx
> Update zklogin-integration.mdx broken heading id

- crates/sui-benchmark/tests/simtest.rs
- crates/sui-core/src/authority/authority_test_utils.rs
- crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/transaction_manager_tests.rs
- crates/sui-types/src/effects/test_effects_builder.rs
- crates/sui-types/src/lib.rs
- crates/sui-types/src/object.rs
- crates/sui-types/src/test_checkpoint_data_builder.rs
This PR adds a builder that could generate arbitrary checkpoint data.
It will make it easy to test the indexer.
Added unit tests.
---
> Add test checkpoint data builder

- crates/sui-indexer-alt/src/handlers/obj_info.rs
Add unit tests for the obj_info pipeline.
---
> [indexer-alt] Add tests for obj_info pipeline

- Cargo.lock
- crates/sui-snapshot/Cargo.toml
- crates/sui-snapshot/src/reader.rs
title, before the local run of checksum took about 30min, after it's about 4 min
ci & local run 
before 
```
[00:33:57] 726 out of 726 ref files checksummed (Checksumming complete)
```
after 
```
[00:04:19] 726 out of 726 ref files checksummed (Checksumming complete)
```
---
> snapshot reader: parallel checksum for speed

- docs/content/guides/developer/sui-101/building-ptb.mdx
fix #20725  
add an example of sending a coin other than sui coin
---
> [docs] add an example of sending a token

- external-crates/move/crates/move-cli/tests/sandbox_tests/module_disassemble/args.exp
- external-crates/move/crates/move-disassembler/src/disassembler.rs
- external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/declarations/function.exp
- external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/borrow.exp
- external-crates/move/crates/move-ir-compiler-transactional-tests/tests/bytecode-generation/expressions/borrow_mut.exp
- external-crates/move/crates/move-vm-transactional-tests/tests/enums/basic_poly_enum_type_mismatch.exp
- external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_jump_same_label.exp
- external-crates/move/crates/move-vm-transactional-tests/tests/enums/enum_variant_mismatch.exp
- external-crates/move/crates/move-vm-transactional-tests/tests/enums/mono/mut_ref_update.exp
- external-crates/move/crates/move-vm-transactional-tests/tests/enums/mono/mut_ref_update_variant.exp
- external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/basic_poly_enum.exp
- external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/poly_mut_ref_update.exp
- external-crates/move/crates/move-vm-transactional-tests/tests/enums/poly/poly_mut_ref_update_variant.exp
It looks like locals are currently not disassembled correctly when running Move disassembler and this PR contains a fix. In particular, consider the following Move code:
```move
module test::M1;
public enum SomeEnum has drop, copy {
NamedVariant { field: u64 },
PositionalVariant(u64),
}
public fun foo(e: SomeEnum, p1: u64, p2: u64): (u64, u64) {
match (e) {
SomeEnum::NamedVariant { field } => {
let mut res = field + p1;
res = res + p2;
(res, res)
},
SomeEnum::PositionalVariant(field) => (field, field)
}
}
#[test]
public fun test() {
let e = SomeEnum::NamedVariant { field: 42 };
foo(e, 42, 7);
}
```
When running disassembler on the `M1` module, the following 3 locals are reported in the disassembly:
```
L0:	__match_tmp%#unpack_subject#1#1#0: SomeEnum
L1:	field#3#0: u64
L2:	res#1#0: u64
``` …
> [move] Fixed locals disassembly

- crates/sui-rpc-api/src/client/mod.rs
Some checkpoints are over 4 MB in size as we noticed in Walrus:
```
{
"timestamp": "2025-01-06T15:32:14.805931Z",
"level": "WARN",
"fields": {
"message": "failed to read next checkpoint",
"next_checkpoint": 128601037,
"status": "Some(Status { code: OutOfRange, message: \"Error, decoded message length too large: found 4520056 bytes, the limit is: 4194304 bytes\", metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"x-sui-chain-id\": \"4c78adac\", \"x-sui-chain\": \"testnet\", \"x-sui-epoch\": \"606\", \"x-sui-checkpoint-height\": \"149661152\", \"x-sui-timestamp-ms\": \"1736177533698\", \"x-sui-lowest-available-checkpoint\": \"0\", \"x-sui-lowest-available-checkpoint-objects\": \"119169201\", \"server-timing\": \"finish_request;dur=186\", \"date\": \"Mon, 06 Jan 2025 …
```
> fix: Increase max decoded size in grpc server to 10 MB

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-core/src/transaction_input_loader.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/congestion_control_tests.rs
- crates/sui-single-node-benchmark/src/mock_storage.rs
- crates/sui-single-node-benchmark/src/single_node.rs
- crates/sui-types/src/storage/mod.rs
It's only ever populated with `AuthorityPerEpochStore`.
Also corrects the misnomer of "shared locks" everywhere to "shared version assignments".
No behavior changes
---
> Remove `GetSharedLocks` trait

- consensus/config/src/parameters.rs
- consensus/config/tests/snapshots/parameters_test__parameters.snap
It seems well functioning validators do not have delay > 3.
CI
---
> [consensus] lower propagation delay threshold to 5

- crates/sui-aws-orchestrator/src/ssh.rs
- crates/sui-benchmark/src/benchmark_setup.rs
- crates/sui-bridge/src/error.rs
- crates/sui-core/src/metrics.rs
- crates/sui-core/src/unit_tests/congestion_control_tests.rs
- external-crates/move/crates/move-analyzer/src/utils.rs
- external-crates/move/crates/move-analyzer/tests/symbols.exp
- external-crates/move/crates/move-stdlib/docs/vector.md
- external-crates/move/crates/move-stdlib/sources/vector.move
- sdk/docs/pages/typescript/migrations/sui-1.0.mdx
This pull request addresses typographical errors in comments and documentation in several files across the codebase. These changes improve the readability and professionalism of the project without affecting functionality.  
1. **Comments:**  
- Corrected "a address" to "an address" in multiple locations.  
- Fixed incorrect usages such as "a HTTP" -> "an HTTP" and "a owned object" -> "an owned object."  
- Fixed redundant words like "preventing preventing" in comments.  
2. **Documentation:**  
- Updated "an vector" to "a vector" in the Move documentation.  
- Clarified phrasing to improve overall comprehension.  
---
**Test Plan:**  
No functionality was changed, so testing was limited to confirming no compilation or linting issues in affected files.
---
**Release Notes:**  
**Impact:** …
> Fix typos in comments and documentation across multiple files

- crates/sui-core/src/traffic_controller/metrics.rs
- crates/sui-core/src/traffic_controller/mod.rs
This will allow us to contextualize blocked request metrics from community nodes given that they control their own configuration.
---
> [Traffic Control] Add metrics for policy config settings

- crates/sui-indexer-alt-framework/src/handlers/cp_sequence_numbers.rs
- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-framework/src/models/cp_sequence_numbers.rs
- crates/sui-indexer-alt-framework/src/models/mod.rs
- crates/sui-indexer-alt/src/README.md
With the `cp_sequence_numbers` table, pruner tasks that need information beyond the pruner checkpoint range can depend on the table for the corresponding interval. A pruner task can now call `tx_interval` or `epoch_interval`, and will throw an anyhow error if the mapping for the checkpoint cannot be retrieved.
---
> [indexer-alt] expose mapping from cp to tx or epoch interval in indexer-alt-framework for pruners if needed

- external-crates/move/crates/move-binary-format/src/compatibility.rs
- external-crates/move/crates/move-binary-format/src/inclusion_mode.rs
Follow the same patter as compatibility check 'compatible' within the inclusion check by flagging name and address differences with the same function to cut down on the size of the trait by one function. Individual checking does not appear to give any benefit and are ignored during client side upgrade checks since it is assumed that the module names are the same and addresses are not yet calculated.
--- …
> [nodes] compatibility checks merge name and address checking to "id" check

- crates/sui/src/unit_tests/fixtures/upgrade_errors/additive_errors_v1/Move.toml
- crates/sui/src/unit_tests/fixtures/upgrade_errors/additive_errors_v1/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/additive_errors_v2/Move.toml
- crates/sui/src/unit_tests/fixtures/upgrade_errors/additive_errors_v2/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/deponly_errors_v1/Move.toml
- crates/sui/src/unit_tests/fixtures/upgrade_errors/deponly_errors_v1/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/fixtures/upgrade_errors/deponly_errors_v2/Move.toml
- crates/sui/src/unit_tests/fixtures/upgrade_errors/deponly_errors_v2/sources/UpgradeErrors.move
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__additive.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__all.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__declarations_missing.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__deponly.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__enum.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__function.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__struct.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__type_param.snap
- crates/sui/src/unit_tests/snapshots/sui__upgrade_compatibility__upgrade_compatibility_tests__version_mismatch.snap
- crates/sui/src/unit_tests/upgrade_compatibility_tests.rs
- crates/sui/src/upgrade_compatibility.rs
- external-crates/move/crates/move-binary-format/src/compatibility.rs
- external-crates/move/crates/move-binary-format/src/inclusion_mode.rs
support additive and deponly policies for upgrade errors
snapshot testing
---
> Upgrade errors for additive and deponly policies

- external-crates/move/crates/move-binary-format/src/deserializer.rs
- external-crates/move/crates/move-binary-format/src/errors.rs
- external-crates/move/crates/move-binary-format/src/proptest_types/functions.rs
- external-crates/move/crates/move-core-types/src/effects.rs
> [move] mute clippy for type complexity, default warning, uppercase

- external-crates/move/crates/move-analyzer/trace-adapter/src/adapter.ts
- external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts
- external-crates/move/crates/move-analyzer/trace-adapter/src/trace_utils.ts
- external-crates/move/crates/move-analyzer/trace-adapter/tests/references_deep/test.exp
When displaying references to structs/enums, we need to store the index path to a specific portion of the struct/enum so that we can display only the "innermost" portion of the whole referenced values. Consider the following code:
```move
public struct SomeStruct has drop {
struct_field: VecStruct,
}
public struct VecStruct has drop, copy {
vec_field: vector<u64>,
}
fun bar(vec_ref: &mut vector<u64>): u64 {
let e = vector::borrow_mut(vec_ref, 0);
*e = 42;
vec_ref[0]
}
fun foo(some_struct_ref: &mut SomeStruct): u64 {
let res = bar(&mut some_struct_ref.struct_field.vec_field);
res + some_struct_ref.struct_field.vec_field[0]
}
fun some_struct(): SomeStruct {
SomeStruct {
struct_field: VecStruct { vec_field: vector::singleton(0) }
}
}
#[test]
fun test() {
let mut some_struct = some_struct(); …
```
> [trace-view] Fixed displaying of compound reference values

- crates/telemetry-subscribers/Cargo.toml
- crates/telemetry-subscribers/src/lib.rs
Remove the feature flags from the `telemetry-subscribers` crate. The existing flags were not being proberly handled which could have lead to broken compilation if features were enabled/disabled and given we don't make use of feature flags in the sui repo it makes things easier to maintain with these removed.
---
> telemetry-subscribers: remove feature flags

- crates/sui-indexer/src/config.rs
Previously I was unable to turn off checkpoint file garbage collection,
since the default value was `true`, the `--gc-checkpoint-files` flag
didn't expect any values and the default `clap` action was to set the
value to `true` when the flag was present. I've tried all of:
- `--gc-checkpoint-files 0`
- `--gc-checkpoint-files false`
- `--gc-checkpoint-files=0`
- `--gc-checkpoint-files=false`
This changes that so that the `false` value is accepted by the argument, i.e., you can set `--gc-checkpoint-files=false`. Default behavior when the argument is missing remains the same as before.
It is based on this [comment](https://github.com/clap-rs/clap/issues/1649#issuecomment-2144879038)
---
Check each box that your changes affect. If none of the boxes …
> fix(sui-indexer): allow setting --gc-checkpoint-files=false

- crates/suins-indexer/src/main.rs
Add initialization so logs actually end up in stdout
logs are flowing
```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.69s
Running `/Users/jordankylejensen/mysten/sui/target/debug/suins-indexer`
Starting indexer with checkpoints dir: /tmp/checkpoints
2025-01-08T22:17:08.413416Z  INFO sui_data_ingestion_core::reader: cleaning processed files, watermark is 99438042
2025-01-08T22:17:08.413325Z  INFO sui_data_ingestion_core::worker_pool: Starting indexing pipeline suins_indexing with concurrency 100. Current watermark is 99438042.
2025-01-08T22:17:08.515215Z  INFO sui_data_ingestion_core::reader: Read from local. Current checkpoint number: 99438042, pruning watermark: 99438042, new updates: 0
2025-01-08T22:17:08.618230Z  INFO sui_data_ingestion_core::reader: Read from …
```
> [suins-indexer] add logging init

- consensus/config/src/committee.rs
- consensus/core/src/authority_node.rs
- consensus/core/src/authority_service.rs
- consensus/core/src/block_manager.rs
- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/subscriber.rs
- consensus/core/src/synchronizer.rs
- crates/sui-core/src/consensus_manager/mysticeti_manager.rs
Improve logging of blocks received through streaming and synchronizations.
CI
PT
---
> [consensus improve logging when receiving blocks

- consensus/config/src/committee.rs
- consensus/core/src/authority_node.rs
- consensus/core/src/authority_service.rs
- consensus/core/src/block_manager.rs
- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/metrics.rs
- consensus/core/src/round_prober.rs
- consensus/core/src/subscriber.rs
- consensus/core/src/synchronizer.rs
- crates/sui-core/src/consensus_manager/mysticeti_manager.rs
> Pick logging and metrics improvements to 1.40

- crates/sui-indexer-alt-schema/src/objects.rs
This will be tested together in https://github.com/MystenLabs/sui/pull/20809
---
> [indexer-alt] Support consensus v2 objects in obj-info

- consensus/core/src/authority_node.rs
- consensus/core/src/commit_observer.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/linearizer.rs
- consensus/core/src/test_dag_builder.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
Currently when committing/collecting the sub dag we always stop the recursion when we come across the highest committed round for an authority. This works well, but with the upcoming Fast Path changes it can lead to uncommitted FP certificates in the presence of blocks that don't form a proper hash chain. 
This could be done if for example an authority `A` produces blocks `A100, A101, A102` , but block `A102` uses as ancestor block `A100` and never references `A101`. `A101` gets broadcasted and participate in the form of an FP certificate and referenced by others. With the current logic in Linearizer, if `A102` gets committed first, then `A101` will never get committed as part of subsequent DAG sequencing as we always stop our recursion to the highest committed round. With the new logic …
> [Consensus] Linearizer to use commit up to gc_round

- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-schema/src/objects.rs
- crates/sui-indexer-alt/src/handlers/obj_info.rs
> [indexer-alt] Add tests for obj_info pruner

- .changeset/rude-doors-retire.md
- sdk/kiosk/src/client/kiosk-transaction.ts
- sdk/kiosk/src/constants.ts
- sdk/kiosk/src/tx/rules/resolve.ts
- sdk/kiosk/src/types/transfer-policy.ts
Updates the fee calculation for kiosks to happen in a separate dry-run transaction so that the split amount is known statically.
---
> Tweak fee calculation for kiosks

- crates/sui-indexer-alt/src/handlers/ev_emit_mod.rs
- crates/sui-indexer-alt/src/handlers/ev_struct_inst.rs
- crates/sui-indexer-alt/src/handlers/kv_checkpoints.rs
- crates/sui-indexer-alt/src/handlers/kv_epoch_ends.rs
- crates/sui-indexer-alt/src/handlers/kv_epoch_starts.rs
- crates/sui-indexer-alt/src/handlers/kv_transactions.rs
- crates/sui-indexer-alt/src/handlers/tx_affected_addresses.rs
- crates/sui-indexer-alt/src/handlers/tx_affected_objects.rs
- crates/sui-indexer-alt/src/handlers/tx_balance_changes.rs
- crates/sui-indexer-alt/src/handlers/tx_calls.rs
- crates/sui-indexer-alt/src/handlers/tx_digests.rs
- crates/sui-indexer-alt/src/handlers/tx_kinds.rs
Added `prune` implementations for pipeline inside indexer alt schema, built upon Will's cp mapping PR.
Will add tests.
---
> [indexer-alt] add prune impls for each pipeline

- crates/sui-indexer-alt-schema/migrations/2025-01-02-201724_cp-sequence-number-index-on-kv-transactions/down.sql
- crates/sui-indexer-alt-schema/migrations/2025-01-02-201724_cp-sequence-number-index-on-kv-transactions/up.sql
add index on cp_sequence_number for kv_transactions, so that we can prune the table while still adhering to kv schema
---
> [indexer-alt] add index on `cp_sequence_number` for `kv_transactions` for pruning

- consensus/core/src/network/tonic_network.rs
[It’s always TCP_NODELAY. Every damn time.](https://brooker.co.za/blog/2024/05/09/nagle.html)
---
> consensus: enable tcp_nodelay for consensus's network interface

- crates/sui-http/src/config.rs
The configuration documentation stated that TCP_NODELAY was enabled by default but the actual default had it disabled. This patch corrects that and enables TCP_NODELAY by default.
---
> sui-http: properly set TCP_NODELAY by default

- crates/sui-types/src/test_checkpoint_data_builder.rs
This will be useful when we need to query data from the DB and sort by object ID.
CI
---
> [test] Ensure stable object id in test checkpoint data builder

- crates/sui-adapter-transactional-tests/tests/programmable/make_vec_non_existent_type.exp
- crates/sui-adapter-transactional-tests/tests/programmable/make_vec_non_existent_type.move
- crates/sui-adapter-transactional-tests/tests/programmable/make_vec_non_existent_type_v71.exp
- crates/sui-adapter-transactional-tests/tests/programmable/make_vec_non_existent_type_v71.move
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_72.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_72.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_72.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
Updates handling of type errors for some PTB commands as we were not properly converting the error type.
CI + new transactional tests. 
---
> [adapter] Update how we handle type errors in some commands

- consensus/core/src/commit_syncer.rs
- consensus/core/src/synchronizer.rs
Turns out the verifier is running in the async thread pool, which may be causing thread stalls.
> Run verifier in blocking pool

- .gitignore
- notes
- scripts/sparse-checkout.py
By using sparse checkouts, you can make rust-analyzer much faster, since it doesn't need to process every crate in the repo.
In a decent sized diff, in which the following crates were checked out
crates/sui-node
crates/sui-single-node-benchmark
crates/sui-benchmark
crates/sui-core
crates/sui-types
crates/sui
crates/mysten-common
rust-analyzer for vscode was much faster both for startup and for running cargo check after a single file was edited.
Startup speed (until cargo check stopped on its own):
- before: 1m6s at best, some runs took many minutes for some reason
- after: 50s on average
Cargo check after editing a single file, no errors:
- before: 2m16s
- after 45s
cargo check, time from introducing a simple error to finishing
- before 12s
- after 7s
Of course, the editor is responsive …
> A script for managing sparse checkouts

- consensus/config/src/parameters.rs
- consensus/config/tests/snapshots/parameters_test__parameters.snap
It should be ok to exclude responses when they are taking >= 2s to return, for quorum round calculations. But it seems better to use a longer timeout to reduce variance in the computed quorum rounds among validators.
CI
---
> [consensus increase round prober default timeout to 4s

- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
Pending tests on private-testnet
> [consensus] Include links to partially propagated blocks from excluded ancestors

- crates/sui-indexer-alt-schema/src/objects.rs
- crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
- crates/sui-types/src/test_checkpoint_data_builder.rs
> [indexer-alt] Add tests for balance bucket pipeline and pruner

- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
> [consensus] cherrypick pr#20845

- crates/sui-core/src/execution_cache/cache_types.rs
- crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
Bug was (likely) as follows:
Reader thread               | Writer thread (state sync)
invalidate tickets
get ticket
miss cache
read database
insert to cache               insert to cache (racing)
ticket is valid
panic
write to database
The writer thread must insert to db first so that the db read
cannot find an old value while holding a valid ticket
> Fix race condition for transaction cache

- crates/sui-core/src/execution_cache/cache_types.rs
- crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
Bug was (likely) as follows:
Reader thread               | Writer thread (state sync)
invalidate tickets
get ticket
miss cache
read database
insert to cache               insert to cache (racing)
ticket is valid
panic
write to database
The writer thread must insert to db first so that the db read
cannot find an old value while holding a valid ticket
---
> [Cherry Pick] Fix race condition for transaction cache (#20875)

- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/gas_tests.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_72.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_72.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_72.snap
- crates/transaction-fuzzer/src/account_universe/transfer_gen.rs
Making a change to move the gas price up to 100Sui and the gas budget at 50_000Sui.
Let's see what breaks and we can go from there
---
> gas price and budget max

- crates/sui-indexer-alt/src/config.rs
- crates/sui-indexer-alt/src/lib.rs
Add back a dedicated top-level configuration for consistency, to control the retention of the consistent range. Now that this range is controlled by the pruner, it can be configured by a `PrunerConfig` as well, rather than a dedicated `ConsistencyConfig`.
The motivation for this is that the E2E testing setup needs to configure the consistent range, and it would be better to avoid having to enumerate all the consistent pipelines in the test harness because it would be easy to forget to update that list, whereas with this approach, we take advantage of the fact that there is an `add_consistent` macro to register the pipeline, and it will do the right thing.
```
sui$ cargo check
sui$ cargo nextest run -p sui-indexer-alt
sui$ cargo run -p sui-indexer-alt -- generate-config
```
---
Check each …
> indexer-alt: configure consistency retention in one place

- crates/sui-edge-proxy/src/handlers.rs
the new logging feature was including a lot of requests we're not interested in
---
> [sui-edge-proxy] add filters for certain reqs we aren't interested in

- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/threshold_clock.rs
Updates threshold clock when blocks are accepted into dag state, so consistency between threshold clock and dag state are easily maintained.
CI
---
> [consensus] advance threshold clock from dag state

- external-crates/move/crates/move-vm-runtime/src/execution/dispatch_tables.rs
- external-crates/move/crates/move-vm-runtime/src/execution/vm.rs
- external-crates/move/crates/move-vm-runtime/src/runtime/mod.rs
- external-crates/move/crates/move-vm-runtime/src/shared/constants.rs
- external-crates/move/crates/move-vm-runtime/src/shared/serialization.rs
- external-crates/move/crates/move-vm-runtime/src/validation/deserialization/translate.rs
Update how we handle deserialization errors so they maintain their specificity. Also updates a bad merge. 
CI
---
> [vm-rewrite] Fix tests

- crates/sui-faucet/src/metrics_layer.rs
This PR updates the logging of 429 errors, to skip them as it floods the logs with them after rate limiting the server.
---
> [faucet] Do not log 429 errors

- crates/sui-indexer-alt-framework/src/models/cp_sequence_numbers.rs
- crates/sui-indexer-alt-schema/src/events.rs
- crates/sui-indexer-alt-schema/src/transactions.rs
- crates/sui-indexer-alt/src/handlers/ev_emit_mod.rs
- crates/sui-indexer-alt/src/handlers/ev_struct_inst.rs
- crates/sui-indexer-alt/src/handlers/obj_info.rs
- crates/sui-indexer-alt/src/handlers/tx_affected_addresses.rs
- crates/sui-indexer-alt/src/handlers/tx_affected_objects.rs
- crates/sui-indexer-alt/src/handlers/tx_balance_changes.rs
- crates/sui-indexer-alt/src/handlers/tx_calls.rs
- crates/sui-indexer-alt/src/handlers/tx_digests.rs
- crates/sui-indexer-alt/src/handlers/tx_kinds.rs
- crates/sui-pg-db/src/lib.rs
- crates/sui-types/src/test_checkpoint_data_builder.rs
pruning tests for pipelines that depend on `CpSequenceNumbers` for tx intervals
All tests!
---
> [indexer-alt] pruning tests for pipelines that depend on `CpSequenceNumbers` for tx intervals

- crates/sui/src/sui_commands.rs
When CLI is set to localnet and a local network is not running, switching to another network in the CLI throws an error. This PR fixes that.
---
> [cli] Allow to switch from localnet that is not running to another network

- scripts/threadstall_analyzer.py
> Add threadstall analyzer script

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/checkpoints/mod.rs
- docker/sui-antithesis/Dockerfile
- docker/sui-antithesis/docker-compose-antithesis.yaml
This PR
- Reduces logging vebosity in general - this was an ad hoc change based on taking high-volume debug logs and changing them to trace if I didn't personally recall looking at them while debugging.
- Reduce log levels for antithesis tests - Attempts to remove a lot of unnecessary logs in antithesis runs.
> Reduce logging verbosity 

- crates/sui-indexer-alt-schema/src/checkpoints.rs
- crates/sui-indexer-alt-schema/src/epochs.rs
- crates/sui-indexer-alt/src/handlers/kv_checkpoints.rs
- crates/sui-indexer-alt/src/handlers/kv_epoch_ends.rs
- crates/sui-indexer-alt/src/handlers/kv_transactions.rs
- crates/sui-types/src/event.rs
- crates/sui-types/src/test_checkpoint_data_builder.rs
Extend `TestCheckpointDataBuilder` to advance an epoch by creating an advance epoch tx with or without the SystemEpochInfoEvent depending on `safe_mode`. Usage:
```
let mut builder = TestCheckpointDataBuilder::new(0);
let checkpoint = Arc::new(builder.advance_epoch(true));
let values = KvEpochEnds.process(&checkpoint).unwrap();
KvEpochEnds::commit(&values, &mut conn).await.unwrap();
```
I had originally considered extending the current tx workflow of `builder.start_transaction()` to then `.advance_epoch().build_checkpoint()`, but ultimately kept it standalone as we'd largely be discarding modifications if any made to the current transaction. A user can still create multiple transactions for the checkpoint, and after `.finish_transaction()`, would call `advance_epoch()` instead of …
> [indexer-alt] pruning tests for kv_epoch_ends and pipelines that don't need `CpSeqeuenceNumbers`

- crates/sui-http/src/connection_handler.rs
Change sui-http to serve an http connection that supports http upgrades.
---
> sui-http: support http upgrades

- crates/sui-rosetta/src/main.rs
- crates/sui-sdk/src/lib.rs
This fixes a panic that was seen when rosetta constructs a jsonrpc client with max_concurrent_requests of usize::MAX by changing how client construction happens to have the default be to disable any limit in concurrent requests (which is essentially what rosetta was trying to do).
---
> sui-rosetta: fix panic when setting usize::MAX max_concurrent_requests

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs
- crates/sui-node/src/lib.rs
This change adds a replay-on-startup phase to checkpoint service construction.
The basic idea is that with data quarantining, if the validator crashes, it will reprocess consensus commits that had already been processed, but whose output had not yet been committed to disk. Constructed checkpoints are one of the outputs of this process.
When the node starts up, it should be in the same state it was in when it crashed. In order to do this, we need to replay all the consensus commits that had been previously processed. This will cause checkpoints to be constructed. The effect of this change is that the node will wait until these checkpoints have been reconstructed before entering normal operations.
> CheckpointService refactoring (for data quarantining)

- crates/sui-keys/src/keystore.rs
- crates/sui-keys/tests/tests.rs
Key aliases uniqueness is enforced by `sui client new-address` but not by `sui keytool update-alias`.
This patch reuses `AccountKeystore::create_alias` in `AccountKeystore::update_alias_value` as it has the exact same body + the uniqueness check.
Porting of https://github.com/iotaledger/iota/pull/4957.
```
thibault@Thibaults-MacBook-Pro-2 ~/i/sui (testnet)> ./target/debug/sui client new-address ed25519 tibo
╭────────────────────────────────────────────────────────────────────────────────────────╮
│ Created new keypair and saved it to keystore.                                          │
├────────────────┬───────────────────────────────────────────────────────────────────────┤
│ alias          │ tibo                                                                  │
│ address        │ …
```
> fix(sui-keys): enforce alias uniqueness in `AccountKeystore::update_alias_value`

- crates/simulacrum/src/epoch_state.rs
- crates/sui-core/src/authority.rs
- crates/sui-genesis-builder/src/lib.rs
- crates/sui-replay/src/replay.rs
- crates/sui-single-node-benchmark/src/single_node.rs
- crates/sui-swarm-config/src/network_config_builder.rs
- crates/sui-types/src/execution.rs
- crates/sui-types/src/sui_system_state/mod.rs
- sui-execution/latest/sui-adapter/src/execution_engine.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/src/executor.rs
- sui-execution/src/latest.rs
- sui-execution/src/v0.rs
- sui-execution/src/v1.rs
- sui-execution/src/v2.rs
- sui-execution/v0/sui-adapter/src/execution_engine.rs
- sui-execution/v1/sui-adapter/src/execution_engine.rs
- sui-execution/v2/sui-adapter/src/execution_engine.rs
The timings are unused for now - they are intended for the congestion control execution time estimator.
> Execution layer reports timings of each executed command

- consensus/core/src/core.rs
~This is a fix for a behaviour that has been observed during the private-testnet test where some nodes started crashing when setting `gc_depth = 5`. The goal was to test GC with very low gc values to reveal possible issues, such as this one.~
~This PR is fixing the block acceptance path after commits happening. As we try to unsuspend blocks after commits have happened, which naturally move the `gc_round` , we should make sure that those blocks are been processed via Core as well and move the threshold clock. Otherwise it's possible - and this mostly becomes visible during bulk processing of blocks - for the following scenario to happen:~
This PR is now including the test only that confirm the issue as described below when we bulk processing blocks under GC conditions. The …
> [Consensus] test to confirm correct threshold clock advancement after GC

- Cargo.toml
Enable Link-Time Optimization (LTO) for the project and other optimization
building process is successfully completed
> feat: enable LTO and codegen-units = 1 optimization

- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/execution_cache.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
This is a temporary change needed to prepare for the upgrade to data quarantining. The data quarantining code will assume that any uncommitted transactions will be replayed from consensus. But upon upgrade, no replay will occur - the non-DQ build will have marked all commits as processed immediately. This change prevents the assert at https://github.com/MystenLabs/sui/blob/791ce9132d98cfff4874e9cff4278419e050d94c/crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs#L1001 from firing during startup of a DQ build.
> persist all transactions and effects during checkpoint construction

- docs/site/src/plugins/framework/index.js
Fixes internal linking in framework docs.
https://app.screencast.com/AbS9YxqhT0jqK shows the issue. Right side of video is current behavior. Clicking links shows the url in the address bar change but no scroll.
I tested, but there was no plan
---
> [docs] Framework linking

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-node/src/lib.rs
- Re-execute pending single writer transactions at startup
- Do not wait forever for checkpoints to be rebuilt (this is thoroughly tested not to happen, but I realized that waiting forever here in prod does not actually buy us anything).
> Re-execute single-writer pending consensus transactions at startup

- Cargo.lock
- crates/sui-rpc-api/Cargo.toml
- crates/sui-rpc-api/src/client/mod.rs
> rpc: add support for basic and bearer auth to grpc client

- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/quorum_driver/metrics.rs
- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/quorum_driver/tests.rs
- crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
- crates/sui-json-rpc/src/error.rs
- crates/sui-rpc-api/src/error.rs
- crates/sui-types/src/quorum_driver_types.rs
The logic in quorum driver to retry conflicting transactions can end up in a situation where it is waiting for responses from all validators which can clog up QD and limit the throughput of our fullnodes. Additionally with `ValidatorTransactionFinalizer` component added recently we no longer need to rely on QD to do this retry of conflicting tx. We still track the conflicting tx digest so that we can return a more useful error to the user in the case that those conflicting tx digests exist.
> [quorum driver] Remove conflicting tx retry logic

- Cargo.lock
- Cargo.toml
- consensus/core/src/network/tonic_network.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_73.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_73.snap
In an effort to save on network egress/ingress and potentially help with latency/throughput we will enable grpc compression for consensus.
Zstd was chosen over Gzip because it offers better compression and decompression speeds. Additionally it claims to achieve better compression ratios, allowing for more efficient use of bandwidth. The flexibility of Zstd in adjusting compression levels can also be explored further if needed.
[With compression](https://metrics.sui.io/goto/u746UAONg?orgId=1)
[Without compression](https://metrics.sui.io/goto/Aqr68AdHR?orgId=1)
--- …
> [consensus] Enable zstd compression in tonic network

- external-crates/move/crates/move-analyzer/trace-adapter/src/runtime.ts
- external-crates/move/crates/move-analyzer/trace-debug/package.json
- external-crates/move/crates/move-analyzer/trace-debug/src/extension.ts
This PR adds the ability to start trace debugging a unit test with an assembly file (rather than a source file) in active editor
Tested manually that one can start debugging with a disassembly file opened
> [trace-view] Start debugging in disassembly

- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/contents.exp
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/contents.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/show_owner.exp
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/show_owner.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/try_get_past_object.exp
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/try_get_past_object.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/try_multi_get_past_objects.exp
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/try_multi_get_past_objects.move
- crates/sui-indexer-alt-jsonrpc/src/api/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/error.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/response.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
Initial support for `tryGetPastObject`, `tryMultiGetPastObjects` and most of the response options. Support for `showDisplay` will come in a follow-up PR.
This PR is a remix of #20962 as it was easier to redo it and fix it forward rather than rebase the stack below this PR on top of that change.
New E2E tests:
```
sui$ cargo nextest run -p sui-indexer-alt-e2e-tests -- objects
```
- #20944 
- #20975 
- #20990 
- #20991 
---
> rpc-alt: (re-adding) `tryGetPastObject`, `tryMultiGetPastObjects`

- crates/sui-json-rpc/src/lib.rs
When we updated the `jsonrpsee` dependency a few configuration changes were made unintentially. Specifically batches were re-enabled and response bodies were limited to 10MB. This patch reverts both these semantic changes to the service by disabling batches and removing the cap on response sizes.
---
> jsonrpc: disable batches and unlimit response sizes

- crates/sui-types/src/multisig_legacy.rs
- examples/move/nft-rental/c4-architecture/workspace.dsl
- examples/move/nft-rental/c4-architecture/workspace.json
- examples/trading/frontend/src/components/escrows/CreateEscrow.tsx
- sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/v1/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/v2/sui-adapter/src/programmable_transactions/execution.rs
- `"optimistacally"` → `"optimistically"`  
- `"sigature"` → `"signature"`  
- `"overlfow"` → `"overflow"`  
- `"currenlty"` → `"currently"`
> Fix spelling error

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_73.snap
This is running on PT nightly for the past couple of days and a very small degradation in performance has been observed. It's not entirely clear whether is due to the new linearizer logic - metrics showcase an increase in the utilisation for the related function - but I am disabling for now until get better clarity. 
CI/PT
---
> [Consensus] Disable the new linearizer logic

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_73.snap
This version of smart ancestor selection also includes the propagation of excluded blocks by default.
---
> [consensus] Enable smart ancestor selection & probing for accepted rounds in mainnet

- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-core/src/consensus_handler.rs
This ensures that we do not stop random partial sig transmission until the randomness update is durably committed to disk
> delay notify_randomness_in_checkpoint until checkpoint is committed

- crates/sui-core/src/consensus_adapter.rs
Right now consensus latency is ~320ms on average, but the median is read to be higher. I believe this is because the buckets are too coarse. Switching to finer grained buckets should improve the precision.
CI
---
> Use finer grained buckets for consensus latency

- docs/site/src/css/custom.css
- docs/site/src/pages/index.module.css
- **Fixed incorrect CSS variable values**:  
Replaced space-separated RGB values with comma-separated values to ensure compatibility with `rgb(var(--color-variable))`.  
- **Removed redundant `margin: 0 auto;` in `index.module.css`**:  
This style was duplicated and unnecessary.
> fix: CSS variable formatting and remove duplicate styles

- external-crates/move/Cargo.lock
- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-analyzer/src/symbols.rs
The rules deciding on how to merge user package files between freshly computed and cached data were incorrect. Luckily (or not actually) they were not fatally incorrect and while the initial merge (when files were actually modified) would not succeed, the subsequent one (where no files were modified - resulting for example from inlay hint request) would, and ultimately the correct data would be generated.
The problem was spotted in the debug build where debug assertions would fail on the initial merge (though all would return to normal after `move-analyzer` restart upon the subsequent request).
I fixed the code and also made it a bit more verbose but also easier to follow the merge logic
Verified that assertions are no longer failing in the debug build on code that was previously …
> [move-analyzer] Cached user program merge fix

- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt/src/benchmark.rs
- crates/sui-indexer-alt/src/lib.rs
- crates/sui-indexer-alt/src/main.rs
Apps indexer might not be managing the DB schema, making migration optional to cater that use case.
---
> [indexer-alt] - make migration optional

- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/get_object.exp
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/get_object.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/multi_get_objects.exp
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/multi_get_objects.move
- crates/sui-indexer-alt-jsonrpc/src/api/governance.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/response.rs
- crates/sui-indexer-alt-jsonrpc/src/data/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/data/object_info.rs
- crates/sui-indexer-alt-jsonrpc/src/data/objects.rs
Implement unfiltered live object set look-ups. They are built on top of an `obj_info` data loader which detects whether the object exists in the live object set at that version.
This PR also pulls out the common loading logic from `fetch_latest_for_system_state` to be used for generally loading latest content by object ID.
New E2E tests:
```
sui$ cargo nextest run -p sui-indexer-alt-e2e-tests \
-- objects/get_object objects/multi_get_objects
```
---
> rpc-alt: getObject, multiGetObjects

- crates/sui-deepbook-indexer/src/server.rs
`order_updates` endpoint
Optional Filters:
1. limit: defaults to 1 (number of trades to be included in result). Most recent trades are always included first.
2. balance_manager_id: defaults to no filter
3. status: "Placed" or "Canceled"
4. start_time: unix timestamp in seconds, defaults to 24hrs before end_time
5. end_time: unix timestamp in seconds, defaults to current time
Sample query:
`/order_updates/DEEP_USDC?start_time=1738703053&end_time=1738704080&limit=2&status=Placed&balance_manager_id=0xd335e8aa19d6dc04273d77e364c936bad69db4905a4ab3b2733d644dd2b31e0a`
Sample Response: 
`[{"original_quantity":8910.0,"remaining_quantity":8910.0,"status":"Placed","type":"sell","price":0.22449,"filled_quantity":0.0,"balance_manager_id":"0xd335e8aa19d6dc04273d77e364c936bad69db4905a4ab3b2733d644dd2b31 …
> Deepbook Indexer Trade Updates Endpoint

- docs/content/concepts/tokenomics.mdx
Fix a broken link in the docs regarding the tokenomics pdf.
Untested.
No release impact.
> fix broken tokenomics.pdf links in docs

- crates/sui-core/src/authority.rs
- crates/sui-core/src/streamer.rs
- crates/sui-core/src/subscription_handler.rs
Subscriptions are already not 100% reliable, and this allows a slow
subscription handler to block execution indefinitely, which we don't
want.
> Sending to the subscription handler should not block execution

- crates/sui-core/src/authority/authority_per_epoch_store.rs
This should be equivalent both functionally and from performance point of view,  but removes requirements from DB to support optimistic transactions, so we can consider migrating epoch db to tidehunter
> Use mutex table for shared version assignment instead of optimistic transaction

- docs/content/references/fullnode-protocol.mdx
- docs/content/sidebars/references.js
- docs/site/docusaurus.config.js
- docs/site/src/components/Protocol/index.tsx
- docs/site/src/plugins/framework/index.js
- docs/site/src/plugins/protocol/index.js
- docs/site/src/plugins/protocol/protocolLoader-json.js
> [docs] Render proto files

- crates/sui-analytics-indexer/src/lib.rs
When a pipeline is provided starting checkpoint sequence number as an arg, we keep going back and start processing from the starting checkpoint upon every restart. This PR fixes that by checking the remote store, and using that if it is ahead.
> fix: Fix pipeline starting checkpoint sequence number

- crates/sui-analytics-indexer/src/handlers/object_handler.rs
- crates/sui-analytics-indexer/src/package_store.rs
Today, we have to restart analytics pipelines with updated package id filter arg when walrus packages are upgraded. This PR fixes the problem by filtering on object's original package id. This means we can provide *any* version of walrus package id as the filter arg and pipeline can filter out objects across *all* versions of the package.
> feat: Make analytics pipeline handle upgraded packages while filtering

- crates/sui/src/sui_commands.rs
If the CLI cannot get the client that should connect to the active environment set in the config, it will error. This creates troubles for when you work on a local network and then stop it. Every client (and a few other) command will now error.
This PR fixes this by relaxing a bit the condition.
---
> [CLI] Don't error if we cannot connect to active env

- external-crates/move/Cargo.lock
- external-crates/move/crates/move-trace-format/Cargo.toml
> [move] Remove unused dependency from move-trace-format's manifest

- crates/sui/src/sui_commands.rs
If the CLI cannot get the client that should connect to the active environment set in the config, it will error. This creates troubles for when you work on a local network and then stop it. Every client (and a few other) command will now error.
This PR fixes this by relaxing a bit the condition.
---
> [Cherry-pick][CLI] Don't error if we cannot connect to active env (#21116)

- crates/sui-source-validation-service/tests/tests.rs
- crates/sui/src/client_commands.rs
- crates/sui/tests/cli_tests.rs
- crates/sui/tests/shell_tests.rs
- crates/sui/tests/shell_tests/with_network/move_build_bytecode_with_address_resolution/move_build_bytecode_with_address_resolution.sh
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/README.md
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/both_flags.sh
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/dependency/Move.toml
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/dependency/sources/dependency.move
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/example/Move.toml
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/example/sources/example.move
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/no_flags.sh
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/skip_dep_verif.sh
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/with_dep_verif.sh
- crates/sui/tests/snapshots/shell_tests__with_network__move_build_bytecode_with_address_resolution__move_build_bytecode_with_address_resolution.sh.snap
- crates/sui/tests/snapshots/shell_tests__with_network__source_verification_deprecation__both_flags.sh.snap
- crates/sui/tests/snapshots/shell_tests__with_network__source_verification_deprecation__no_flags.sh.snap
- crates/sui/tests/snapshots/shell_tests__with_network__source_verification_deprecation__skip_dep_verif.sh.snap
- crates/sui/tests/snapshots/shell_tests__with_network__source_verification_deprecation__with_dep_verif.sh.snap
This adds a warning that source verification will become opt-in instead of opt-out in a future release, along with the `--verify-deps` flag that currently disables the warning.
Several shell tests that cover the behavior with no flags, with both flags, and with each flag independently, on a package with source that has changed since publication. See the snapshot files for the tests and expected output.
> [CLI] cherry pick (#20977) Deprecation warnings for dependency verification 

- Cargo.lock
- crates/sui-cluster-test/src/test_case/coin_index_test.rs
- crates/sui-indexer/src/apis/coin_api.rs
- crates/sui-json-rpc-api/src/coin.rs
- crates/sui-json-rpc-tests/tests/rpc_server_tests.rs
- crates/sui-json-rpc-types/src/sui_coin.rs
- crates/sui-json-rpc/Cargo.toml
- crates/sui-json-rpc/src/coin_api.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-open-rpc/src/examples.rs
- crates/sui-sdk/src/apis.rs
Explicitly make the cursors for get_coins and get_all_coins to be an opaque string instead of an ObjectId encoded as a string.
---
Explicitly make the cursors for GetCoins and GetAllCoins to be an opaque string instead of an ObjectId encoded as a string.
> jsonrpc: make coin_api cursors opaque

- docs/content/guides/operator/data-management.mdx
- nre/config/validator.yaml
- Most of consensus configs do not need to be set explicitly or have been deprecated.
- Many fields in the pruning config do not need to be set because they are already the default.
👀
---
> Remove unnecessary config fields in examples

- crates/sui-sdk/README.md
Description
This PR fixes a minor issue in the coin-read example of the Sui Rust SDK documentation. The previous code used {} to print total_balance, which caused a compilation error. The fix changes it to {:#?} to properly format the output, ensuring the example compiles and runs correctly when copied and pasted.
Original line:
println!("The balances for all coins owned by address: {active_address} are {}", total_balance);
Updated line:
println!("The balances for all coins owned by address: {active_address} are {:#?}", total_balance);
Test plan
The updated example has been tested by copying and running it, verifying that the compilation error is resolved and that the output correctly displays the balances.
Release notes
Protocol:
Nodes (Validators and Full nodes):
gRPC:
JSON-RPC: …
> [rust-sdk] add pretty print formatting and fix compiling issue

- crates/sui-graphql-rpc/src/server/exchange_rates_task.rs
- crates/sui-indexer/src/handlers/tx_processor.rs
- crates/sui-mvr-graphql-rpc/src/server/exchange_rates_task.rs
- Fixed `sui_sytem_state` → `sui_system_state` in `exchange_rates_task.rs` (multiple occurrences).  
- Fixed `inavlid` → `invalid` in `tx_processor.rs`.
> fix(typos): Correct spelling errors in exchange rates task and transaction processor

- crates/sui/src/framework_versions.rs
This changes the behavior of `sui::framework_version::framework_for_protocol` when the requested protocol is newer than the binary (it no longer returns an error - instead it returns a tuple with a differing protocol version)
Existing unit tests were updated.
---
> changed error behavior for `sui::framework_versions::framework_for_protocol`

- crates/sui-indexer/src/config.rs
an issue reported by community 
https://github.com/MystenLabs/sui/issues/21037#issuecomment-2647510698
introduced in 
https://github.com/MystenLabs/sui/pull/20783
the error was 
```
Argument `gc_checkpoint_files`'s selected action SetTrue contradicts `takes_value`
```
```
DB_POOL_SIZE=10 cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgrespw@localhost:5432/gegao" indexer --remote-store-url https://checkpoints.mainnet.sui.io 
DB_POOL_SIZE=10 cargo run --bin sui-indexer -- --db-url "postgres://postgres:postgrespw@localhost:5432/gegao" indexer --remote-store-url https://checkpoints.mainnet.sui.io --gc-checkpoint-files
DB_POOL_SIZE=10 cargo run --bin sui-indexer -- --db-url …
```
> sui-indexer: fix CLI clap error

- crates/sui-config/src/p2p.rs
8084 is mentioned to be the default p2p port in docs: https://docs.sui.io/guides/operator/validator-tasks#connectivity
And validator / transaction RPC port defaults to 8080 already.
So changing the default p2p port from 8080 to 8084 in `P2pConfig`.
I believe the change is backward compatible but lmk otherwise.
CI
---
> Change p2p default port to 8084

- crates/sui/src/client_ptb/ast.rs
Handle serialization for Option< address > in a PTB, since `TypeTag` for an Option is a `vector<T>` it needed to be handled extra
Porting over https://github.com/iotaledger/iota/pull/5143
- Bug fix (a non-breaking change which fixes an issue)
Running this command connected to the testnet
```
cargo run client ptb \
--assign addr "some(@0x2d4b94541bbfcce2ed51e5b0fb73e02bd809e04f1a0601797a6028e6a00b6607)" \
--move-call 0xc9586aae0485f0975167ef0261db81a4011d3255cfa0128dc2f7cc3b72135aaf::example::optional_address_param addr \
--dry-run
```
> fix(sui): fix Option<address> serialization in client_ptb

- external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs
- external-crates/move/crates/move-command-line-common/src/testing.rs
- external-crates/move/crates/move-compiler/tests/move_check_testsuite.rs
- external-crates/move/crates/move-docgen-tests/tests/testsuite.rs
- external-crates/move/crates/move-model/tests/testsuite.rs
- external-crates/move/crates/move-package/tests/test_runner.rs
- external-crates/move/crates/move-stackless-bytecode/tests/testsuite.rs
- external-crates/move/crates/move-transactional-test-runner/src/framework.rs
- external-crates/move/crates/move-unit-test/tests/move_unit_test_testsuite.rs
- Stacked on #21113 
- The name field was the same in all but two cases, as such I made it optional
- ran the tests
---
> [exp-to-insta][14/14] Cleanup of insta_assert macro

- sui-execution/latest/sui-move-natives/src/config.rs
- sui-execution/latest/sui-move-natives/src/dynamic_field.rs
- sui-execution/v0/sui-move-natives/src/dynamic_field.rs
- sui-execution/v1/sui-move-natives/src/dynamic_field.rs
- sui-execution/v2/sui-move-natives/src/dynamic_field.rs
Native functions can have valid reasons to return an `Err` so we shouldn't be logging an `error` log in such cases. This removes them.
> [sui-adapter] Remove error traces from native functions

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_74.snap
Enables the new linearize logic for devnet. Although it had been previously enabled it got later [disabled](https://github.com/MystenLabs/sui/pull/21019) during a regression investigation which appeared to be though unrelated to this logic. 
CI/PT
---
> [Consensus] enable the new linearize logic for devnet.

- Cargo.lock
- consensus/core/src/base_committer.rs
- consensus/core/src/tests/base_committer_declarative_tests.rs
While reviewing [base_committer_tests](https://github.com/MystenLabs/sui/blob/main/consensus/core/src/tests/base_committer_tests.rs), I noticed that that it seems to have been written before DagBuilder and DagParser were introduced by @arun-koshy. Using these tools allows to describe DAG state in a declaratively, making tests both easier to understand and maintain.
By covering key DAG patterns, this PR aims to:
- serve as a useful learning reference for those exploring Sui’s consensus mechanism
- provide a more declarative and maintainable approach to testing
The plan is to continue to cover more cases and also to do the same for UniversalCommitter in the subsequent PRs.
not applicable
---
Check each box that your changes affect. If none of the boxes relate to your changes, release notes …
> BaseCommitter declarative tests

- crates/sui-framework-snapshot/src/lib.rs
Since deployed protocol versions are not guaranteed to be sequential, snapshots are not guaranteed to be sequential (e.g., 45 may exist, 46 may not, but 47 may).
Previously when trying to load a snapshot for a protocol version we would only load a snapshot if there was one for that exact version, otherwise we'd default to the newest version of the framework. This is incorrect, and @dariorussi has run into problems with this.
This updates snapshot loading so if a snapshot for a particular version `v` is not found, the least version greater than the given version is returned.
CI
--- …
> [framework-snaps] Update snapshot loading

- crates/sui-core/src/unit_tests/auth_unit_test_utils.rs
- crates/sui-move-build/src/lib.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
- external-crates/move/crates/move-bytecode-utils/src/lib.rs
A couple of small clean-ups in Move-related code that I noticed while working on other things:
- Removing an unnecessary lifetime parameter on `SuiAdapter` impl block.
- Removing a duplicate function on `CompiledPackage`.
- Richer error message when `Modules` detects a duplicate Module by ID.
CI
- #21010 
- #21085 
- #21119
---
> easy(move-build): assorted clean ups

- Cargo.lock
- crates/sui-core/src/unit_tests/auth_unit_test_utils.rs
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/by_module.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/by_module.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/by_name.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/by_name.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/by_package.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/by_package.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/by_type_params.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/by_type_params.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/owner.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/query/owner.snap
- crates/sui-indexer-alt-jsonrpc/Cargo.toml
- crates/sui-indexer-alt-jsonrpc/src/api/objects/error.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/response.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
- crates/sui-indexer-alt-jsonrpc/src/paginate.rs
- crates/sui-move-build/src/lib.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
- external-crates/move/crates/move-bytecode-utils/src/lib.rs
Implement querying objects by owner and type. Also introduce BCS-serialized cursors (to keep size down).
New E2E tests:
```
sui$ cargo nextest run -p sui-indexer-alt-e2e-tests \
-- objects/query
```
- #21010 
- #21085
---
> rpc-alt: getOwnedObjects

- crates/sui/src/client_commands.rs
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/both_flags.sh
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/no_flags.sh
- crates/sui/tests/shell_tests/with_network/source_verification_deprecation/skip_dep_verif.sh
- crates/sui/tests/snapshots/shell_tests__with_network__source_verification_deprecation__both_flags.sh.snap
- crates/sui/tests/snapshots/shell_tests__with_network__source_verification_deprecation__no_flags.sh.snap
- crates/sui/tests/snapshots/shell_tests__with_network__source_verification_deprecation__skip_dep_verif.sh.snap
Switch source dependency verification from opt-out to opt-in; update warnings and tests accordingly.
Existing integration tests are updated.
---
> [CLI] Make source verification opt-in instead of opt-out (dvx-699)

- crates/sui-core/src/authority.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-core/src/congestion_tracker.rs
- crates/sui-core/src/lib.rs
- crates/sui-types/src/execution_status.rs
- Witnesses congestion failures from checkpointed effects
- Returns a suggested gas price given a set of input objects
> CongestionTracker:

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_74.snap
Enables the Consensus garbage collection for testnet. `gc_depth` is set to `60` , which with the current round rate of 12-15 rounds/sec it should allow the network to include blocks in a window of `4-5 seconds`.
CI
---
> [Consensus] enable consensus garbage collection for testnet

- crates/sui-genesis-builder/src/lib.rs
- sui-execution/latest/sui-adapter/src/execution_engine.rs
- sui-execution/src/executor.rs
- sui-execution/src/latest.rs
- sui-execution/src/v0.rs
- sui-execution/src/v1.rs
- sui-execution/src/v2.rs
> Remove `TxContext` from executor API

- sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
- `loaded_child_object_format` and `loaded_child_object_format_type` are always true in this execution version
- Ran tests
---
> [child effects refactor] Cleanup protocol config checks

- crates/sui-types/src/base_types.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/v0/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/v1/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/v2/sui-adapter/src/programmable_transactions/execution.rs
The code should be pretty straightforward and properly commented.
We basically make `MoveLegacyTxContext` the Rust equivalent of Move `TxContext`.
After this PR the Rust `TxContext` does not track the Move `TxContext` any longer and can evolve as needed.
Subsequent PRs will introduce new functionality.
This effectively changes nothing of the current behavior
Current tests
---
> Make MoveLegacyTxContext to track Move TxContext

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority/authority_test_utils.rs
- crates/sui-core/src/authority/consensus_quarantine.rs
- crates/sui-core/src/authority/epoch_start_configuration.rs
- crates/sui-core/src/authority/shared_object_congestion_tracker.rs
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/consensus_manager/mysticeti_manager.rs
- crates/sui-core/src/epoch/epoch_metrics.rs
- crates/sui-core/src/epoch/randomness.rs
- crates/sui-core/src/execution_cache.rs
- crates/sui-core/src/execution_cache/cache_types.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
- crates/sui-core/src/fallback_fetch.rs
- crates/sui-core/src/lib.rs
- crates/sui-core/src/mock_consensus.rs
- crates/sui-core/src/transaction_input_loader.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/consensus_tests.rs
- crates/sui-core/src/unit_tests/transaction_manager_tests.rs
- crates/sui-e2e-tests/tests/reconfiguration_tests.rs
- crates/sui-node/src/lib.rs
- crates/sui-single-node-benchmark/src/mock_storage.rs
- All consensus output is held in memory until all checkpoints built from that output have been committed. This ensures that the epoch db is not corrupted in the event of a fork.
- Consensus therefor becomes the primary replay log for all crash recovery.
- Additionally this means there are several tables that we no longer need to write to, and their contents can live in memory.
Extensive testing with both simtest and antithesis. In particular the upgrade flow (from non-DQ to DQ build) has been tested extensively with antithesis.
> Consensus Data Quarantining

- consensus/core/src/commit_syncer.rs
- consensus/core/src/metrics.rs
An additional metric to better track the missing ancestors exclusively coming from the commit sync.
Will cherry pick in 1.43
CI/PT
---
> [Consensus] add metric for missing ancestors when processing blocks via commit sync

- scripts/simtest/simtest-run.sh
Seems like env vars weren't passed to `cargo-simtest` in `scripts/simtest/simtest-run.sh`
This PR fixes passing env vars to cargo-simtest
Tested simtests only
Ran the simtest script locally
> fix(simtests): pass env vars to cargo-simtest

- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/authority/shared_object_congestion_tracker.rs
- crates/sui-types/src/execution.rs
> Make 1.5s the total-tx estimated default time, not the per-command default

- crates/sui-core/src/unit_tests/subscription_handler_tests.rs
- crates/sui-graphql-rpc/src/types/move_value.rs
- crates/sui-json/src/tests.rs
- crates/sui-mvr-graphql-rpc/src/types/move_value.rs
- crates/sui-open-rpc/src/examples.rs
- crates/sui-package-resolver/src/lib.rs
- crates/sui-types/src/balance.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/coin.rs
- crates/sui-types/src/id.rs
- crates/sui-types/src/object/balance_traversal.rs
- crates/sui-types/src/object/bounded_visitor.rs
- external-crates/move/Cargo.lock
- external-crates/move/crates/move-bytecode-utils/src/layout.rs
- external-crates/move/crates/move-core-types/src/annotated_value.rs
- external-crates/move/crates/move-core-types/src/unit_tests/value_test.rs
- external-crates/move/crates/move-core-types/src/unit_tests/visitor_test.rs
The `MoveFieldLayout` struct `fields` was wrapped in a box as part of https://github.com/MystenLabs/sui/pull/19310, which states in its reasoning:
> Boxes fields in the MoveTypeLayout to make the enum size smaller for type layouts.
However, this field being boxed does not affect the enums which this was referring to as it is also boxed in the variants. This means that the variant size of those enums is always the size of a pointer. Thus, this additional box around the vec serves only to create an additional indirection.
--- …
> fix!: Remove double indirection in `MoveFieldLayout`

- Cargo.lock
- Cargo.toml
- crates/sui-rpc-benchmark/Cargo.toml
- crates/sui-rpc-benchmark/README.md
- crates/sui-rpc-benchmark/src/direct/benchmark_config.rs
- crates/sui-rpc-benchmark/src/direct/metrics.rs
- crates/sui-rpc-benchmark/src/direct/mod.rs
- crates/sui-rpc-benchmark/src/direct/query_enricher.rs
- crates/sui-rpc-benchmark/src/direct/query_executor.rs
- crates/sui-rpc-benchmark/src/direct/query_generator.rs
- crates/sui-rpc-benchmark/src/direct/query_template_generator.rs
- crates/sui-rpc-benchmark/src/lib.rs
- crates/sui-rpc-benchmark/src/main.rs
main things in this pr
- generate template queries based on tables in the DB, excluding `__diesel_schema_migrations`
- enrich the template with values read from DB and execute queries in parallel
- configs of concurrency and duration time
- metrics collection and reports
- local run with a local DB populated with latest `sui-indexer-alt-schema`
```
cargo run --bin sui-rpc-benchmark -- direct \
--db-url "postgres://postgres:postgres@localhost/gegao" \
--concurrency 10 \
--duration-secs 10
```
report with local DB
```
Total queries: 211772
Total errors: 0
Average latency: 0.46ms
Per-table statistics:
obj_info                       queries: 33526    errors: 0        avg latency: 0.49ms
ev_struct_inst                 queries: 31598    errors: 0        avg latency: 0.47ms
tx_calls …
```
> rpc benchmark init: directly read DB based on schema

- crates/sui-rpc-benchmark/src/config.rs
- crates/sui-rpc-benchmark/src/direct/mod.rs
- crates/sui-rpc-benchmark/src/direct/query_executor.rs
- crates/sui-rpc-benchmark/src/json_rpc/mod.rs
- crates/sui-rpc-benchmark/src/json_rpc/request_loader.rs
- crates/sui-rpc-benchmark/src/json_rpc/runner.rs
- crates/sui-rpc-benchmark/src/lib.rs
- load requests from jsonl file
- generate and file JSON RPC requests concurrently
- collect total and per-method metrics
will collect more logs from production and stress test with logs pulled from loki API
local run and verify on report
```
Benchmark results:
=== Overall Statistics ===
Total requests sent: 3
Total errors: 0
Average latency: 1360.67ms
Success rate: 100.0%
=== Per-Method Statistics ===
Method: sui_getLatestCheckpointSequenceNumber
Requests: 1
Errors: 0
Avg latency: 1298.00ms
Success rate: 100.0%
Method: sui_multiGetTransactionBlocks
Requests: 1
Errors: 0
Avg latency: 1486.00ms
Success rate: 100.0%
Method: suix_queryTransactionBlocks
Requests: 1
Errors: 0
Avg latency: 1298.00ms
Success rate: 100.0%
```
---
Check each box that your changes affect. If none of the boxes …
> rpc benchmark: json rpc benchmark

- .github/workflows/external.yml
- .github/workflows/rust.yml
- external-crates/move/deny.toml
Currently the external crates cargo deny job runs at the top level and thus does not check the external crates manifest/lock file. This PR adds an additional `deny.toml` specific to the external crates and updates the CI job so that it uses the correct manifest. Also adds the `--hide-inclusion-graph` flag as this helps to reduce the spam in the CI logs.
NOTE: If only the top level `deny.toml` is used for both, then warnings are emitted for ignored RUSTSEC, licenses, etc. that do not apply to the manifest which cannot be silenced.
Currently, running with the top-level `deny.toml` on the external crates reports several issues:
```sh
sui git:(main) cargo deny --manifest-path=external-crates/move/Cargo.toml check --hide-inclusion-graph 
warning[unmatched-source]: allowed source was not …
```
> chore: Add cargo deny check for external crates

- docs/content/guides/developer/first-app/build-test.mdx
- docs/content/guides/developer/first-app/write-package.mdx
There's a confusing bit of documentation to follow on the pages "Write a move package" and "Build and Test packages".
On the instructions to "Write a move package", it states to create a file called my_module.move. However, in the source code it is referenced as example.move.
This can confuse the reader of the document as later on in the "Build and Test packages" section, that same file is referenced as example.move
I have renamed the my_module references to example for a consistent user experience.
I changed the my_module.move markdown to example.move.
---
For each box you select, include information after the relevant heading that describes the impact of your changes that …
> changed references to my_module to example

- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/query/by_checkpoint.snap
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/mod.rs
If the transaction query returns an empty result and a cursor was supplied, then return that cursor back in the response, so that the client can poll for new results by repeatedly requesting new pages.
This matches the revised behaviour for pagination in `sui-indexer`'s `reader`. Note that in `rpc-alt`, this behaviour is currently only applicable to paginating transactions -- object and coin pagination flow backwards through time, so if you reach an empty result, there is no point retrying it.
```
sui$ cargo nextest run -p sui-indexer-alt-e2e-tests
```
---
For each box you select, include information after the relevant heading that describes the impact of your changes that …
> rpc-alt: fix transactions next cursor behavior

- crates/sui-indexer-alt-jsonrpc/src/api/objects/response.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/response.rs
It's possible (and cleaner) to use `anyhow`'s `Context` on an `Option<T>` to convert it into an `anyhow::Result`.
```
sui$ cargo nextest run         \
-p sui-indexer-alt-e2e-tests \
-p sui-indexer-alt-jsonrpc
```
---
> refactor(rpc-alt): use context instead of ok_or_else

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/consensus_adapter.rs
- crates/sui-core/src/epoch/randomness.rs
- crates/sui-core/src/unit_tests/consensus_tests.rs
- crates/sui-core/src/unit_tests/execution_driver_tests.rs
- crates/sui-node/src/lib.rs
- crates/sui-single-node-benchmark/src/single_node.rs
This removes the redundant synced checkpoint notification from epoch store.
> Remove redundant synced checkpoint notifications.

- crates/sui-replay-2/src/execution.rs
Based on a discussion in https://github.com/MystenLabs/sui/pull/21241, this PR refines directory structure for saving traces to create a subdirectory in the root dir named after transaction digest. This way, one can replay multiple transactions without changing/customizing output directory
> Trace output directory refinement

- crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
- crates/sui-indexer-alt/src/consistent_pruning.rs
- crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
- crates/sui-indexer-alt/src/handlers/obj_info.rs
The current delete query causes contention when pruning concurrency > 1. This is because the `with to_prune_data` query submits deletion requests such that we may potentially have overlapping deletes for the same obj upper-bounded at different checkpoints. The `RowExclusiveLock`s eventually escalate to exclusive locks.
One way to circumvent this is by having the first deletion of an object be `(obj, < cp)`, and subsequent deletions be bounded on both sides. But this requires additional orchestration. Alternatively, we can modify the deletion query so that each deletion entry searches for its immediate predecessor. This means a small change on `get_prune_info` to return a vector of `(obj, cp)` instead of a mapping deduplicating same-object entries. Each tuple represents the exclusive …
> [indexer-alt] immediate predecessor pruning query for consistent pipelines

- external-crates/move/crates/move-cli/README.md
- external-crates/move/crates/move-compiler-transactional-tests/tests/dependencies/dependency_order.move
- external-crates/move/crates/move-compiler/tests/sui_mode/struct_with_key/key_struct_first_field_not_id.move
- external-crates/move/crates/move-ir-to-bytecode/src/compiler.rs
- external-crates/move/crates/move-package/tests/test_additional_addresses.rs
- external-crates/move/crates/move-vm-integration-tests/src/tests/exec_func_effects_tests.rs
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `funciton` to `function`
Corrected `depedencies` to `dependencies`
Corrected `ojbect` to `object`
Corrected `valeu` to `value`
Corrected `additonal` to `additional`
Corrected `unecessary` to `unnecessary`
Please review the changes and let me know if any additional changes are needed.
> fix: typos in documentation files

- Cargo.lock
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/try_get_past_object.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/objects/try_multi_get_past_objects.snap
- crates/sui-indexer-alt-jsonrpc/Cargo.toml
- crates/sui-indexer-alt-jsonrpc/src/api/checkpoints.rs
- crates/sui-indexer-alt-jsonrpc/src/api/dynamic_fields.rs
- crates/sui-indexer-alt-jsonrpc/src/api/governance.rs
- crates/sui-indexer-alt-jsonrpc/src/api/name_service/response.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/response.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/response.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/context.rs
- crates/sui-indexer-alt-jsonrpc/src/data/bigtable_reader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/checkpoints.rs
- crates/sui-indexer-alt-jsonrpc/src/data/error.rs
- crates/sui-indexer-alt-jsonrpc/src/data/kv_loader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/data/object_info.rs
- crates/sui-indexer-alt-jsonrpc/src/data/object_versions.rs
- crates/sui-indexer-alt-jsonrpc/src/data/objects.rs
- crates/sui-indexer-alt-jsonrpc/src/data/package_resolver.rs
- crates/sui-indexer-alt-jsonrpc/src/data/pg_reader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/read_error.rs
- crates/sui-indexer-alt-jsonrpc/src/data/system_package_task.rs
- crates/sui-indexer-alt-jsonrpc/src/data/transactions.rs
- crates/sui-indexer-alt-jsonrpc/src/data/tx_balance_changes.rs
- crates/sui-indexer-alt-jsonrpc/src/data/tx_digests.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
This PR adds the support for point lookups backed by Bigtable kv store and use it for objects and checkpoints.
Support for transactions is coming in another commit/PR. 
Connected to Bigtable and tested locally.
---
> [rpc-alt] set up bigtable kvstore and use it for objects + checkpoints

- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/deleted.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/deleted.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/inconsistency.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/inconsistency.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/pagination.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/pagination.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/transferred.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/transferred.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/type_filter.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/type_filter.snap
- crates/sui-indexer-alt-jsonrpc/src/api/coin.rs
- crates/sui-indexer-alt-jsonrpc/src/api/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
This PR added indexer alt jsonrpc reader implementation for `getCoins` and `getAllCoins`. I ported over `raw_query` from graphql crate for usage here.
Added e2e tests.
---
> [indexer-alt] add coin jsonrpc impl

- external-crates/move/crates/bytecode-verifier-transactional-tests/tests/reference_safety/borrow_enum_field_mutable_invalid.mvir
- external-crates/move/crates/move-cli/tools.md
- external-crates/move/crates/move-ir-to-bytecode/src/context.rs
- external-crates/move/crates/move-package/src/resolution/dependency_graph.rs
- external-crates/move/crates/move-package/tests/test_sources/diamond_problem_dep_incorrect_nested/Move.toml
- external-crates/move/crates/move-vm-integration-tests/src/tests/instantiation_tests.rs
**This PR includes several minor text improvements:**
1. Fixed spelling of `different` in `borrow_enum_field_mutable_invalid.mvir`
2. Standardized `libraries` casing in `move-cli/tools.md`
3. Fixed spelling of `CompiledDependencyView` in `context.rs`
4. Corrected `because` spelling in multiple files
5. Fixed capitalization in `Instantiation test` message
These changes improve code readability and maintain consistent terminology throughout the codebase. All modifications are text-only and do not affect functionality.
> Fix typos and improve text consistency across codebase

- external-crates/move/crates/move-vm-integration-tests/src/tests/instantiation_tests.rs
- external-crates/move/crates/move-vm-runtime/src/move_vm.rs
- external-crates/move/crates/move-vm-runtime/src/tracing2/tracer.rs
- external-crates/move/crates/move-vm-runtime/src/unit_tests/vm_arguments_tests.rs
- external-crates/move/crates/move-vm-test-utils/src/tiered_gas_schedule.rs
- external-crates/move/crates/move-vm-types/src/natives/function.rs
external-crates/move/crates/move-vm-integration-tests/src/tests/instantiation_tests.rs
withing - within
Instantion - Instantiation
external-crates/move/crates/move-vm-runtime/src/move_vm.rs
envrionment - environment
external-crates/move/crates/move-vm-runtime/src/tracing2/tracer.rs
specifice - specific
external-crates/move/crates/move-vm-runtime/src/unit_tests/vm_arguments_tests.rs
mising - missing
external-crates/move/crates/move-vm-test-utils/src/tiered_gas_schedule.rs
contstant - constant
external-crates/move/crates/move-vm-types/src/natives/function.rs
funciton - function
> fix spelling issues in comments 

- Cargo.lock
- crates/sui-config/src/node.rs
- crates/sui-core/Cargo.toml
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/data_ingestion_handler.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/utils.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/state_accumulator.rs
- crates/sui-core/src/transaction_manager.rs
- crates/sui-node/src/lib.rs
- crates/sui-single-node-benchmark/src/benchmark_context.rs
- crates/sui-single-node-benchmark/src/single_node.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-tool/src/db_tool/mod.rs
- crates/test-cluster/Cargo.toml
- crates/test-cluster/src/lib.rs
Stacked on #21232, #21233 and #21235
This simplifies CheckpointExecutor massively, in preparation for optimizations which will be needed for throughput improvements
TODO
> Rewrite and simplify CheckpointExecutor

- crates/simulacrum/src/epoch_state.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-genesis-builder/src/lib.rs
- crates/sui-replay/src/replay.rs
- crates/sui-replay/src/types.rs
- crates/sui-single-node-benchmark/src/single_node.rs
- crates/sui-swarm-config/src/network_config_builder.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/gas.rs
- crates/sui-types/src/gas_model/gas_v2.rs
- crates/sui-types/src/transaction.rs
- sui-execution/latest/sui-adapter/src/execution_engine.rs
- sui-execution/src/executor.rs
- sui-execution/src/latest.rs
- sui-execution/src/v0.rs
- sui-execution/src/v1.rs
- sui-execution/src/v2.rs
- sui-execution/v0/sui-adapter/src/execution_engine.rs
- sui-execution/v1/sui-adapter/src/execution_engine.rs
- sui-execution/v2/sui-adapter/src/execution_engine.rs
Changed executor API to take `GasData` instead of gas payments only (`Vec<ObjectRef>`). That allows us to expose more info about gas and sponsor to the `TxContext` in execution.
I wondered whether the info about sponsor and more (e.g. gas price and budget) should be computed on the client of the executor (e.g. in `authority.rs` and I had the code initially that way) but it makes for a more intrusive change. 
Passing the `GasData` allows the executor to compute everything is needed for execution with a more stable API. Thoughts welcome.
This PR should change nothing in the current implementation and though `sponsor` and `gas_price` are exposed to the `TxContext` (the Rust side) they are unused at the moment (in this PR, later PRs will use that).
`authority::dev_inspect_transaction_block` …
> Expose `GasData` through executor

- consensus/core/src/authority_service.rs
- consensus/core/src/base_committer.rs
- consensus/core/src/block_manager.rs
- consensus/core/src/commit.rs
- consensus/core/src/commit_syncer.rs
- consensus/core/src/core.rs
- consensus/core/src/core_thread.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/error.rs
- consensus/core/src/leader_timeout.rs
- consensus/core/src/metrics.rs
- consensus/core/src/round_prober.rs
- consensus/core/src/test_dag_builder.rs
- consensus/core/src/universal_committer.rs
The PR is changing the way we are processing the synchronized committed sub dags when GC is enabled. This was a necessity given that it's possible during GC for committed sub dags to drop dependencies that are necessary to accept vote and decision round blocks, effectively leading us to having to fetch the missing blocks via the synchronizer. By empirical examination there is a correlation between the missing blocks and the gc depth - the lower the gc depth the higher the number of missing blocks that need to be fetched. 
With this new approach we attempt to commit the synchronized committed sub dag without waiting for the commit rule to run (hence wait to have accepted blocks to form the voting & decision rounds). Attention needs to be given that to avoid edge cases we need to make sure …
> [Consensus] process sync committed sub dags

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-node/src/lib.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- Use LruCache for local estimates
- Ensure estimator receive loop exigts at end of epoch
> Various estimator fixes

- docker/sui-node-deterministic/Dockerfile
Dramatically simplified build setup based on new stagex release.
Reproduces with: sha256:9e16f65dfddd8fd9e00b3b1496dd7f3543e5134847ff95084ecad2ee56153521 provided you hardcode 2025-02-14 as the build date.
Tested reproduction across one intel xeon machine and one threadripper.
I am not sure why build date is embedded in the build in the first place as it makes reproduction complicated, but I left it alone for the scope of this PR.
> Refactor/update sui-node-deterministic to latest stagex

- Cargo.lock
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/get_all_balances.exp
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/get_all_balances.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/coin/get_all_balances.snap
- crates/sui-indexer-alt-jsonrpc/src/api/coin.rs
Add initial implementation for `getAllBalances`, reusing most of the infra already built for other APIs. Note that this method does not support pagination and we may have to add optimizations later to improve performance when fetching whale's balances, based on benchmarking results.
Added e2e tests.
---
> [rpc-alt] add getAllBalances

- Cargo.lock
- crates/simulacrum/src/lib.rs
- crates/sui-indexer-alt-e2e-tests/packages/type_limits/Move.toml
- crates/sui-indexer-alt-e2e-tests/packages/type_limits/sources/type_limits.move
- crates/sui-indexer-alt-e2e-tests/src/lib.rs
- crates/sui-indexer-alt-e2e-tests/tests/name_service_tests.rs
- crates/sui-indexer-alt-e2e-tests/tests/type_limit_tests.rs
- crates/sui-indexer-alt-jsonrpc/Cargo.toml
- crates/sui-indexer-alt-jsonrpc/src/api/dynamic_fields.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/response.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/context.rs
- crates/sui-indexer-alt-jsonrpc/src/error.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
When initialising the RPC service's package resolver, configure its limits (previously it did not impose any). The limits are set in the RPC's config file, and default to the limits in the latest protocol version the RPC binary is aware of.
This PR also includes a new helper to `Simulacrum` to create a fresh funded account (in a separate commit).
New E2E test:
```
sui$ cargo nextest run -p sui-indexer-alt-e2e-tests --test type_limit_tests
```
---
> rpc-alt: apply limits to package resolver

- deny.toml
Latest PRs started to fail on the cargo deny job: https://github.com/MystenLabs/sui/actions/runs/13467427723/job/37635981270?pr=21302
---
> [deny] Add `ring` rustsec to ignore

- Cargo.lock
- Cargo.toml
- crates/sui-indexer-alt-framework/Cargo.toml
- crates/sui-indexer-alt-framework/src/models/watermarks.rs
- crates/sui-indexer-alt-jsonrpc/Cargo.toml
- crates/sui-indexer-alt-jsonrpc/src/api/coin.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/filter.rs
- crates/sui-sql-macro/Cargo.toml
- crates/sui-sql-macro/src/lexer.rs
- crates/sui-sql-macro/src/lib.rs
- crates/sui-sql-macro/src/parser.rs
Introduce a macro that allows for building a `SqlLiteral` using a format-string-like syntax.
`SqlLiteral` should allow us to keep using `diesel` and not have to worry about how to handle scenarios where we need to introduce snippets of raw SQL -- it makes it possible to do so while still taking advantage of strong typing on the boundary and diesel's support for escaping values.
However, it has poor ergonomics, requiring lots of boilerplate (chains of function calls and type annotations) which break up and hide the query being built. The newly introduced macro allows for building the same structure using a format string. See diff for docs and examples of usage.
Some features that were not included in the initial implementation, but could be added later include:
- inlining binds (similar to …
> rpc-alt: Macro for building diesel `SqlLiteral`s

- crates/sui-indexer-alt-schema/migrations/2025-02-17-182226_tx_digests_tx_digest/down.sql
- crates/sui-indexer-alt-schema/migrations/2025-02-17-182226_tx_digests_tx_digest/up.sql
- crates/sui-indexer-alt-schema/migrations/2025-02-17-183604_obj_info_object_id_desc/down.sql
- crates/sui-indexer-alt-schema/migrations/2025-02-17-183604_obj_info_object_id_desc/up.sql
Two changes to the indexer-alt schema to support efficient querying in rpc-alt:
- I mistakenly added an index on `tx_digests` for `tx_sequence_number` but one already exists (it is the primary key). I meant to add an index on `tx_digest` to support fetching a transaction's balance changes.
- `cp_sequence_number` and `object_id` should be ordered the same in `obj_info` indices to make efficient use of indices while bounding results because of cursors.
These migrations may need to be run proactively on our production instances (if we have any) before landing to prevent stalling deployments.
Run the following locally:
```
sui-indexer-alt-schema$ ./generate_schema.sh
sui-indexer-alt-schema$ cargo run -p sui-indexer-alt -- reset-database
```
Also run the indexer locally and confirm that …
> rpc-alt: fix indices

- crates/sui-indexer-alt-schema/migrations/2025-02-05-232254_coin_balance_buckets_object_id_desc/down.sql
- crates/sui-indexer-alt-schema/migrations/2025-02-05-232254_coin_balance_buckets_object_id_desc/up.sql
As titled. This way we can more efficiently fetch coin balances and use the index to its fullest potential like in #20931.
---
> [indexer-alt] modify coin balance bucket index to sort object id in descending order

- Cargo.lock
- Cargo.toml
- crates/sui-security-watchdog/Cargo.toml
- deny.toml
Removes RUSTSEC-2023-0086 by updating snowflake, lexical-util, arrow,parquet versions. It also updates `object_store` to only have one version in the lock file.
---
> [chore] Remove RUSTSEC-2023-0086 

- crates/sui-faucet/src/faucet/simple_faucet.rs
This PR fixes the issue of the localnet failing to start in this specific scenario:
- local network started from genesis: `sui start --with-faucet`
- new address was created and requested gas, and switched to being the active address.
- stop the network
- start the network again with `sui start --with-faucet`.
What happens is that the `active-address` does not have the objects yet, depending on how the indexing of the DB goes, so the faucet cannot start without gas coins.
Should close issue #21255.
Re-run the tests + run `sui start` with different flags.
---
For each box you select, include information after the relevant heading that describes the impact of your changes …
> [faucet] Try to find an address with sufficient gas coins

- Cargo.lock
- Cargo.toml
- crates/sui-e2e-tests/tests/passkey_e2e_tests.rs
- crates/sui-types/src/unit_tests/passkey_authenticator_test.rs
- deny.toml
Updates `passkey` crates to `v0.4.0` which uses `idna v1.0.3`. Any `idna` with a version >=1.0.0 is good for this RUSTSEC-2024-0421. 
Note: updated the passkey's `UserValidationMethod` trait impl for `MyUserValidationMethod` by following the changes to the example here:
https://github.com/1Password/passkey-rs/pull/24/files#diff-b96910ff4357fe0cced6689937c8ff57c8b232150b132c781fc8098de95fce7cR12-R26
---
> [chore] Remove RUSTSEC-2024-0421

- crates/sui-json-rpc-tests/tests/transaction_tests.rs
- crates/sui-json-rpc-types/src/sui_transaction.rs
Formatting an instance of `SuiTransactionBlockResponse` using an empty format `{}` panics if the instance contains an empty vector of balance changes, which occurs for system transactions like `ConsensusCommitPrologueV3`.
Porting over https://github.com/iotaledger/iota/issues/5366
_Describe the changes or additions included in this PR._
In the `Display` implementation for `SuiTransactionBlockResponse`, add a check for a vector of balance changes being non-empty -- only then a build a table and safely operate on it. A similar check is done in the `Display` implementation for `SuiTransactionBlockEvents`.
_How did you test the new or updated feature?_
Added `test_display_transaction_block_with_empty_balance_changes` test:
```console
cargo test -p sui-json-rpc-tests …
```
> fix(sui-json-rpc-types): fix `Display` of `SuiTransactionBlockResponse` with empty balance changes

- crates/sui-core/src/mock_consensus.rs
> change MockConsensusClient to return error on overflow instead of panic

- consensus/core/src/authority_service.rs
- consensus/core/src/commit.rs
- consensus/core/src/commit_syncer.rs
- consensus/core/src/core.rs
- consensus/core/src/core_thread.rs
- consensus/core/src/leader_timeout.rs
- consensus/core/src/linearizer.rs
- consensus/core/src/metrics.rs
- consensus/core/src/round_prober.rs
- consensus/core/src/stake_aggregator.rs
- consensus/core/src/synchronizer.rs
- consensus/core/src/test_dag_builder.rs
The PR is utilising further the `CertifiedCommit` struct to piggy back the votes that certify a commit. It is also extending the `CommitSyncer` so it does utilise now internally the `CertifiedCommit` and better manage the fetched blocks etc. The received votes are attempted to be optimistically accepted via the normal path of the block manager. Pay attention that in order to avoid kicking off the scheduled synchronizer due to missing dependencies, the earlier mechanism that was introduced which would allow missing ancestors to be fetched up to above a certain threshold from the highest accepted round, will now need to get disabled. This was added due to this https://github.com/MystenLabs/sui/pull/19763 . But now that we commit the certified commits directly, this won't be an issue.
CI/PT …
> [Consensus] Optimistically accept certified commits votes.

- crates/sui-field-count-derive/src/lib.rs
make the FieldCount trait support Enum type as well to extend the further logic when implementing handler in alt-indexer-framework
for example, we might want to handle multiple related data in single processor instead of handling them in individual processors which might be down to efficiency
```
#[derive(Clone, Debug)]
pub enum DeepBookData {
Flashloan(Flashloan),
OrderUpdate(OrderUpdate),
OrderFill(OrderFill),
PoolPrice(PoolPrice),
Balances(Balances),
Proposals(Proposals),
Rebates(Rebates),
Stakes(Stakes),
TradeParamsUpdate(TradeParamsUpdate),
Votes(Votes),
Error(SuiTxnError),
}
impl Processor for DeepBookEventsBuckets {
const NAME: &'static str = "deepbook_buckets";
type Value = DeepBookData;
fn process(&self, checkpoint: &Arc<CheckpointData>) -> Result<Vec<Self::Value>> {
...
}
```
> feat: extend FieldCount trait for enum type

- consensus/core/src/network/tonic_network.rs
- consensus/core/src/round_prober.rs
Validator operators cannot do much against unavailable peers, so the warnings are a bit noisy.
CI
---
> [consensus] turn a few noisy warnings into debug severity

- external-crates/move/crates/move-cli/src/sandbox/utils/on_disk_state_view.rs
- external-crates/move/crates/move-transactional-test-runner/src/tasks.rs
- external-crates/move/crates/move-vm-runtime/src/cache/arena.rs
- external-crates/move/crates/move-vm-runtime/src/cache/identifier_interner.rs
- external-crates/move/crates/move-vm-runtime/src/dev_utils/in_memory_test_adapter.rs
- external-crates/move/crates/move-vm-runtime/src/execution/dispatch_tables.rs
- external-crates/move/crates/move-vm-runtime/src/execution/interpreter/eval.rs
- external-crates/move/crates/move-vm-runtime/src/execution/values/values_impl.rs
- external-crates/move/crates/move-vm-runtime/src/execution/vm.rs
- external-crates/move/crates/move-vm-runtime/src/jit/execution/ast.rs
- external-crates/move/crates/move-vm-runtime/src/jit/execution/translate.rs
- external-crates/move/crates/move-vm-runtime/src/lib.rs
- external-crates/move/crates/move-vm-runtime/src/shared/mod.rs
- external-crates/move/crates/move-vm-runtime/src/unit_tests/loader_tests.rs
- external-crates/move/crates/move-vm-runtime/src/unit_tests/package_cache_tests.rs
This replaces `Identifier`s in the execution AST with `IdentifierKey`, because identifiers (and the strings they hold) led to memory leaks -- the string bytes were heap-allocated, so leaked when the Identifiers were dropped.
This also refactors the interner to be more self-contained.
Tests all pass, plus this command reported no leaks:
```
RUSTFLAGS="-Zsanitizer=address" cargo +nightly test -j 1 -Zbuild-std --target x86_64-unknown-linux-gnu
```
This now reports no leaks.
---
> [move][move-vm][rewrite][cleanup 4/n] Replace AST Identifiers with IdentifierKey

- crates/sui/src/client_ptb/ast.rs
Support passing `sui::object::ID` values as pure transaction inputs for `sui client ptb`.
Call a move function that accepts an `ID` parameter using `sui client ptb` (the ID is accepted as an address literal).
---
> cli(ptb): support serializing `sui::object::ID`

- crates/suiop-cli/src/cli/env/mod.rs
- crates/suiop-cli/src/main.rs
- remove old error checking for an env file
- add a new message to indicate that a subshell is being created
```
suiop-cli [jkj/suiop-env-msg-fix] suiop env                    
> Select an environment: mysten/default/vultr-api
Starting a subshell with the environment set... exit the shell (usually ctrl-d) to exit the env
error This project's package.json defines "packageManager": "yarn@pnpm@9.1.1". However the current global version of Yarn is 1.22.22.                                                                                                                                                                                
Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js …
```
> [suiop][env] fix messaging, remove error

- crates/sui-analytics-indexer/src/handlers/object_handler.rs
- crates/sui-analytics-indexer/src/package_store.rs
Enhanced the package filtering logic in `ObjectHandler` to check the entire type hierarchy of objects, including nested type parameters. Previously, the filter only checked the top-level package address, which meant objects with matching package addresses in their type parameters were not being captured. This impacted our ability to read dynamic fields in walrus objects for instance.  For example - `0x2::dynamic_field::Field<u64, 0x795ddbc26b8cfff2551f45e198b87fc19473f2df50f995376b924ac80e56f88b::staking_inner::StakingInnerV1>` is not getting filtered through but contains important info that data science needs.
Added some unit tests
--- …
> feat(analytics-indexer): Filter nested object types in handler

- crates/sui-indexer-alt-e2e-tests/tests/name_service_tests.rs
- crates/sui-indexer-alt-e2e-tests/tests/transaction_pruning_tests.rs
- crates/sui-indexer-alt-e2e-tests/tests/transactional_tests.rs
- crates/sui-indexer-alt-e2e-tests/tests/type_limit_tests.rs
- crates/sui-indexer-alt-jsonrpc/src/api/coin.rs
- crates/sui-indexer-alt-jsonrpc/src/api/move_utils/response.rs
- crates/sui-indexer-alt-jsonrpc/src/api/name_service/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/name_service/response.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/objects/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/context.rs
- crates/sui-indexer-alt-jsonrpc/src/data/bigtable_reader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/checkpoints.rs
- crates/sui-indexer-alt-jsonrpc/src/data/kv_loader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/object_info.rs
- crates/sui-indexer-alt-jsonrpc/src/data/object_versions.rs
- crates/sui-indexer-alt-jsonrpc/src/data/objects.rs
- crates/sui-indexer-alt-jsonrpc/src/data/pg_reader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/transactions.rs
- crates/sui-indexer-alt-jsonrpc/src/data/tx_balance_changes.rs
- crates/sui-indexer-alt-jsonrpc/src/data/tx_digests.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
- crates/sui-indexer-alt-jsonrpc/src/main.rs
- crates/sui-package-resolver/src/lib.rs
A couple of refactorings, mostly to do with configs:
- The main change is that instead of breaking apart the config and giving it to each module that needed it, it is now stored in the `Context` where all modules can access it. The motivation for this came from working on `showDisplay` which is relevant to a multiple modules but is quite deeply nested, so threading the config into the right place became quite tedious/noisy.
- As part of this change, I split apart the old `RpcConfig` into an `RpcLayer` and `RpcConfig` -- this was so that the `Context` could hold on to one value (of `RpcConfig`) rather than having to pass each module's config to it individually (and access them individually through their own modifiers).
- This PR also cleans up various imports across the `rpc-alt` codebase, …
> refactor(rpc-alt): pass configs via Context

- crates/sui-json-rpc-types/src/sui_move.rs
- crates/sui-open-rpc/spec/openrpc.json
We were collecting these into a `BTreeMap` when building up the json response which was leading to the variants in an enum type to be returned in lexicographic order instead of declaration order.
This updates this to collect into a vector of tuples instead so that declaration order of the variants is preserved in the json output. This closes the issue in #20914.
Ran this on the repro in #20914 and confirmed that the enum variants are returned in order. 
---
> [json-rpc] Update variants to be returned in declaration order

- docker/fullnode/README.md
- docker/stress/readme.md
- docker/sui-antithesis/README.md
docker/fullnode/README.md
Before: "by select it" → After: "by selecting it"
Fix: Corrected verb form for grammatical accuracy.
docker/stress/readme.md
Before: "eg:" → After: "e.g.,"
Fix: Proper abbreviation formatting.
docker/sui-antithesis/README.md
Before: "much be" → After: "must be"
Fix: Fixed typo and improved clarity.
> Fixing Grammar and Typographical Errors in Documentation

- crates/sui-core/src/authority/shared_object_congestion_tracker.rs
Fixed multiple typos in comments:
- Changed "burst limit bust be" to "burst limit must be" in assertion message
- Removed duplicate backticks in "Insert tx" comments (2 instances)
> Fix typos in shared_object_congestion_tracker.rs

- crates/sui-move/src/new.rs
- crates/sui/tests/shell_tests/new_tests/new_uppercase_name.sh
- crates/sui/tests/snapshots/shell_tests__new_tests__new_uppercase_name.sh.snap
- external-crates/move/crates/move-cli/src/base/new.rs
Creating a new Move package with the `sui move new` command using only the required argument `<NAME>` fails with `No such file or directory (os error 2)` if `<NAME>` contains uppercase letter(s).
Porting over [iotaledger/iota/issues/4895](https://github.com/iotaledger/iota/issues/4895).
_Describe the changes or additions included in this PR._
- Use the provided `<NAME>` instead of its lowercase variant to obtain the correct and existing path for writing.
- Update `<NAME>` validation error message: since `<NAME>` is validated as an `Identifier`, a valid `<NAME>` can also start with an uppercase letter or underscore.
_How did you test the new or updated feature?_
The issue can be tested before and after the proposed changes as follows:
```console
cargo build -p sui
./target/debug/sui move …
```
> fix(sui-move): `sui move new` command fails with `os error 2` if using `<NAME>` with uppercase letter(s)

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_76.snap
Enables the consensus garbage collection and the new commit rule for testnet.
CI/PT
---
> [Consensus] Enable Garbage Collection & New commit rule for testnet

- crates/sui-graphql-e2e-tests/tests/stable/consistency/multi_get_objects.move
- crates/sui-graphql-e2e-tests/tests/stable/consistency/multi_get_objects.snap
- crates/sui-graphql-e2e-tests/tests/stable/consistency/objects_pagination.move
- crates/sui-graphql-e2e-tests/tests/stable/consistency/objects_pagination.snap
- crates/sui-graphql-e2e-tests/tests/stable/consistency/performance/many_objects.move
- crates/sui-graphql-e2e-tests/tests/stable/consistency/performance/many_objects.snap
- crates/sui-graphql-rpc/schema.graphql
- crates/sui-graphql-rpc/src/types/gas.rs
- crates/sui-graphql-rpc/src/types/object.rs
- crates/sui-graphql-rpc/src/types/query.rs
- crates/sui-graphql-rpc/staging.graphql
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__schema.graphql.snap
- crates/sui-graphql-rpc/tests/snapshots/snapshot_tests__staging.graphql.snap
This PR removes the `objectKeys` field from `ObjectFilter` as per the previous deprecation notice. Use `multiGetObjects` instead.
Updated tests accordingly and ensured all existing tests pass.
---
> [GraphQL] Try to remove objectKeys

- .github/workflows/release.yml
Remove `bmwill/rust-cache` from rust builds. I meant to do this earlier and forgot. 
See https://mysten-labs.slack.com/archives/C02L5JL88JV/p1740681175394449 for contexgt.
👀
> Remove `bmwill/rust-cache` from rust builds

- external-crates/move/crates/move-analyzer/editors/code/CONTRIBUTING.md
- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-analyzer/editors/code/src/configuration.ts
- external-crates/move/crates/move-analyzer/editors/code/src/context.ts
I recently encountered a user problem when their VSCode was picking up their on-path `sui` binary to get `move-analyzer` functionality out of it but it did not work. What did work was to keep using the bundled `move-analyzer` but there wasn't a convenient option to force it. This PR adds this kind of option to the extension's config.
Generally, we want people to use `move-analyzer` from `sui` binary if available so that they have consistent compiler behavior (mostly with respect to diagnostics), That's why the new option defaults to `false`.
Another use for this option is if someone is savvy enough to have a custom `sui` binary on their path but it's a debug version - we definitely don't want `move-analyzer` running in debug mode
Tested manually that flipping the flag back and forth …
> [move-ide] Added an option to force bundled move-analyzer

- crates/sui-framework/packages/move-stdlib/sources/unit_test.move
- examples/vesting/Move.toml
- external-crates/move/crates/move-stdlib-natives/src/lib.rs
- external-crates/move/crates/move-stdlib-natives/src/unit_test.rs
- external-crates/move/crates/move-stdlib/sources/unit_test.move
- external-crates/move/crates/move-unit-test/tests/test_sources/use_unit_test_module.move
- external-crates/move/crates/move-unit-test/tests/test_sources/use_unit_test_module.snap
- Remove create_signers_for_testing as it is no longer used
- Updated IDE to 1.43 and verified there were no errors about missing functions 
---
> [move-stdlib] remove deprecated poison function

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/consensus_quarantine.rs
This fixes a bug in how we handle the end of epoch pre- and post- data quarantining.
In the old code, we check if there were any deferred txns loaded in the current commit with this code: https://github.com/MystenLabs/sui/blob/2f52a7283e5f805b728ce1570cb66d27f0a95648/crates/sui-core/src/authority/authority_per_epoch_store.rs#L2150
Because this looks at the table, it does not reflect that the fact that we may have already scheduled deletes from the table.
In the new code, we look at the in-memory map https://github.com/MystenLabs/sui/blob/67fea6a41b90e6b49d9829766a29b4f74cfa4900/crates/sui-core/src/authority/authority_per_epoch_store.rs#L2038 - keys are removed from this map immediately upon loading them at https://github.com/MystenLabs/sui/blob/67fea6a41b90e6b49d9829766a29b4f74cfa4900/crat …
> Delay delete of deferred transactions until end of commit handler

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_76.snap
Will enable on the second testnet 1.44 release behind a new protocol version (77).
CI
---
> [Consensus] do not enable GC for testnet with version 76

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/consensus_quarantine.rs
This fixes a bug in how we handle the end of epoch pre- and post- data
quarantining.
In the old code, we check if there were any deferred txns loaded in the
current commit with this code:
https://github.com/MystenLabs/sui/blob/2f52a7283e5f805b728ce1570cb66d27f0a95648/crates/sui-core/src/authority/authority_per_epoch_store.rs#L2150
Because this looks at the table, it does not reflect that the fact that
we may have already scheduled deletes from the table.
In the new code, we look at the in-memory map
https://github.com/MystenLabs/sui/blob/67fea6a41b90e6b49d9829766a29b4f74cfa4900/crates/sui-core/src/authority/authority_per_epoch_store.rs#L2038
- keys are removed from this map immediately upon loading them at
https://github.com/MystenLabs/sui/blob/67fea6a41b90e6b49d9829766a29b4f74cfa4900/crat …
> [Cherry Pick] Delay delete of deferred transactions until end of commit handler (#21376)

- external-crates/move/documentation/book/src/functions.md
Description:
Fixed a typo in functions.md where "pbulic" was incorrectly used instead of "public" in the entry functions section.
> Fix typo in functions documentation: "pbulic" -> "public"

- deny.toml
This PR adds Apache 2.0 with LLVM exceptions to the allow list. This enables PR #21329 to be merged!
---
> Allow Apache 2.0 with LLVM Exceptions

- Cargo.lock
- crates/sui-indexer-alt-e2e-tests/Cargo.toml
- crates/sui-indexer-alt-e2e-tests/tests/write_tests.rs
- crates/sui-indexer-alt-jsonrpc/Cargo.toml
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
Write tests are flaky when run as normal tests in CI, and I couldn't repro locally. Based on ci logging, the issue was with sui test cluster that introduced the flakiness. This PR makes them sim tests so they can at least fail deterministically.
edited tests.
---
> [rpc-alt] make flaky write test sim tests

- Cargo.lock
- crates/sui-indexer-alt-e2e-tests/src/lib.rs
- crates/sui-indexer-alt-e2e-tests/tests/transactional_tests.rs
- crates/sui-indexer-alt-framework/Cargo.toml
- crates/sui-indexer-alt-framework/src/cluster.rs
- crates/sui-indexer-alt-framework/src/ingestion/client.rs
- crates/sui-indexer-alt-framework/src/ingestion/error.rs
- crates/sui-indexer-alt-framework/src/ingestion/local_client.rs
- crates/sui-indexer-alt-framework/src/ingestion/mod.rs
- crates/sui-indexer-alt-framework/src/ingestion/remote_client.rs
- crates/sui-indexer-alt-framework/src/ingestion/rpc_client.rs
- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-framework/src/metrics.rs
- crates/sui-indexer-alt/src/benchmark.rs
- crates/sui-rpc-api/Cargo.toml
- crates/sui-rpc-api/src/client/mod.rs
add rpc api ingestion to indexer-alt, this is to unblock a private-net app indexer.
---
> [indexer-alt] - add rpc api ingestion to indexer-alt

- crates/sui-bridge-indexer/src/main.rs
- crates/sui-bridge-watchdog/eth_vault_balance.rs
- crates/sui-bridge/src/config.rs
- crates/sui-bridge/src/node.rs
- crates/sui-bridge/src/sui_bridge_watchdog/eth_vault_balance.rs
- crates/sui-bridge/src/sui_bridge_watchdog/metrics.rs
- crates/sui-bridge/src/utils.rs
A PR to enable LBTC monitoring. @williampsmith we'll want to add this to one of our nodes for the LBTC launch. Because LBTC (token ID 6) is not added to testnet, we'll need to either enable LBTC to testnet (no code change required) before landing this PR OR come up with an alternative (maybe only push metrics for a token ID if its actually enabled? right now address of token ID 6 on testnet will return 0x0 so may break node. anyways not going to land this until we decide (after offsite) 
--- …
> [bridge] add lbtc vault monitoring

- crates/sui-node/src/lib.rs
- deny.toml
- external-crates/move/deny.toml
This should fix client-side panics in antithesis caused by validators serving requests after restart, but before they have replayed all pending consensus transactions.
> Apparently bind() is what initiates request handling, so it must be delayed

- consensus/core/src/transaction.rs
I noticed that the import path for `TapFallible` was incorrect. In crate **tap** (version 1.0 and above), the correct path is `tap::TapFallible`, not `tap::tap::TapFallible`. This is confirmed by both the official documentation and the source code.  
This change ensures that the import is valid and aligns with the expected usage.  
- Verified the correct import path in the crate **tap** documentation and source code.  
- Ensured that the code compiles successfully with the corrected import.  
---
> chore: fix incorrect import path for TapFallible in crate tap

- crates/sui-json-rpc-tests/tests/balance_changes_tests.rs
- crates/sui-json-rpc-tests/tests/rpc_server_tests.rs
- crates/sui-move-build/src/lib.rs
- crates/sui-proc-macros/src/lib.rs
- crates/sui-rosetta/tests/custom_coins/test_coin_utils.rs
- crates/sui-source-validation/src/tests.rs
- crates/sui/src/client_ptb/builder.rs
- crates/sui/tests/cli_tests.rs
This removes `sui_move_build::BuildConfig::default` and makes other small changes
#21204 Add implicit Sui dependencies
#21384 Refactors to BuildConfig
#21383 Add support for implicits to move package management
This also depends on @stefan-mysten 's ongoing tree-shaking work in #21356 
Since no behavior should change, existing tests are sufficient
---
> Refactors to `BuildConfig`

- crates/sui-indexer-alt-e2e-tests/src/lib.rs
- crates/sui-indexer-alt-e2e-tests/tests/write_tests.rs
- crates/sui-indexer-alt-jsonrpc/src/api/write.rs
- crates/sui-indexer-alt-jsonrpc/src/args.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
I realized the way we handled the write arg (fullnode rpc url) was incorrect. We wanted it to be an optional arg but it's not actually optional due to the `#[command(flatten)]` attribute and causes this error when a fullnode url is not provided:
```
error: the following required arguments were not provided:
<FULLNODE_RPC_URL>
Usage: sui-indexer-alt-jsonrpc rpc --database-url <DATABASE_URL> --config <CONFIG> <FULLNODE_RPC_URL>
```
edited tests
---
> [rpc-alt] fix fullnode rpc url arg

- crates/sui-data-ingestion/src/main.rs
- crates/sui-indexer-alt-jsonrpc/src/context.rs
- crates/sui-indexer-alt-jsonrpc/src/data/bigtable_reader.rs
- crates/sui-kvstore/src/bigtable/client.rs
- crates/sui-kvstore/src/bigtable/metrics.rs
- crates/sui-kvstore/src/bigtable/mod.rs
> [kv store] add metrics

- consensus/config/src/parameters.rs
- consensus/config/tests/snapshots/parameters_test__parameters.snap
With round interval of 70-80ms, using 250ms for leader timeout seems a bit excessive.
PT
---
> [consensus] reduce leader timeout to 200ms

- crates/sui-bridge/src/storage.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-core/src/authority/transaction_deferral.rs
- crates/sui-core/src/epoch/committee_store.rs
- crates/sui-core/src/stake_aggregator.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-core/src/verify_indexes.rs
- crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
- crates/sui-node/src/lib.rs
- crates/sui-storage/src/write_path_pending_tx_log.rs
- crates/sui-tool/src/db_tool/db_dump.rs
- crates/sui-tool/src/db_tool/mod.rs
- crates/sui-transactional-test-runner/src/simulator_persisted_store.rs
- crates/typed-store-derive/src/lib.rs
- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/rocks/tests.rs
- crates/typed-store/src/traits.rs
* migrates unbounded_iter call sites to safe_iter
* removes unused range_iter method
* deprecates iterator_cf method
---
> [typed store] iterators: migrate unbounded_iter callsites

- consensus/simtests/src/node.rs
I fixed an issue with the log formatting where there was no space after the equals sign, and a `%` symbol appeared right before the variable value without a space. This fix ensures proper syntax for clearer and more readable logs.
---
1. Run the application and check the log outputs.  
2. Verify that there is a space after the equals sign and no `%` symbol directly before the variable value.  
3. Ensure that the logs are syntactically correct and readable.
---
> chore: fixed formatting issue in log output for better syntax

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_77.snap
Enabling the consensus garbage collection & the new lineariser commit logic for testnet on protocol version 77.
CI/PT
---
> [Consensus] Enable Garbage Collection & New commit rule for testnet on version 77

- external-crates/move/documentation/book/src/primitive-types/tuples.md
external-crates/move/documentation/book/src/primitive-types/tuples.md
- They cannot be bound to local variables.
> deleted duplicate tuples.md

- crates/sui-framework-snapshot/src/lib.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_77.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_78.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_77.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_78.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_78.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
Shift the protocol config variables for the native context from 77 -> 78 (77 was cherry-picked into the previous release). 
CI
---
> [protocol] Shift native tx context up a protocol version

- crates/sui-data-ingestion-core/src/reducer.rs
- crates/sui-data-ingestion/src/workers/archival.rs
caused by rust upgrade.
(+ added extra assert)
---
> archival: fix the issue where checkpoints from different epochs are appearing in the same batch

- Cargo.lock
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-config/Cargo.toml
- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/authority/shared_object_congestion_tracker.rs
- crates/sui-node/src/lib.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-swarm-config/src/node_config_builder.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
> Move config parameters for ExecutionTimeEstimate mode into protocol and node configs

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/consensus_quarantine.rs
- crates/sui-core/src/authority/epoch_start_configuration.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-e2e-tests/tests/reconfiguration_tests.rs
The table is replaced with:
- An in-memory "dirty set" which holds executed but un-checkpointed
transaction digests. Transactions are removed from the dirty set by
CheckpointExecutor.
- An additional bounded cache intended to lessen the number of db reads
by CheckpointBuilder
- Last-resort reads go to the `executed_transactions_to_checkpoint` table.
The only purpose of the table was to allow CheckpointBuilder to prune
transaction dependencies from prior epochs, and the above approach
suffices while removing a surprisingly expensive source of db writes.
> Remove `executed_in_epoch` table.

- crates/sui-benchmark/tests/simtest.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/authority/shared_object_congestion_tracker.rs
- crates/sui-core/src/unit_tests/congestion_control_tests.rs
- crates/sui-protocol-config/src/lib.rs
Also includes some minor cleanups, most notably removing the absolute
limit param for this mode since we always set it to u64::MAX.
---
> Restore separate budget for randomness tx in ExecutionTimeEstimate mode

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
Without this, some entrypoints could get stuck at high estimates with no way of adjusting back down.
---
> Add debt-based trigger for observation sharing

- .github/workflows/rust.yml
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/base/sources/sui_system.move
- crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/base/sources/sui_system_state_inner.move
- crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/deep_upgrade/sources/sui_system.move
- crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/deep_upgrade/sources/sui_system_state_inner.move
- crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/shallow_upgrade/sources/sui_system.move
- crates/sui-e2e-tests/tests/framework_upgrades/mock_sui_systems/shallow_upgrade/sources/sui_system_state_inner.move
- crates/sui-e2e-tests/tests/reconfiguration_tests.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_78.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_78.snap
This enables a new congestion control mode that uses a predictive model for PTB command transaction time collaboratively built through consensus by validators.
Unit tests, performance backtesting with tool in separate repo, manual inspection.
---
> Enable ExecutionTimeEstimate mode for congestion control in testnet

- consensus/core/src/authority_node.rs
- consensus/core/src/authority_service.rs
- consensus/core/src/base_committer.rs
- consensus/core/src/block.rs
- consensus/core/src/commit.rs
- consensus/core/src/commit_consumer.rs
- consensus/core/src/commit_observer.rs
- consensus/core/src/commit_syncer.rs
- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/lib.rs
- consensus/core/src/proposed_block_handler.rs
- consensus/core/src/stake_aggregator.rs
- consensus/core/src/synchronizer.rs
- consensus/core/src/test_dag_builder.rs
- consensus/core/src/transaction_certifier.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/consensus_manager/mysticeti_manager.rs
This PR adds a `TransactionCertifier` component. It keeps track of votes on transactions and support certifying them for fastpath. Blocks and local votes are added to `TransactionCertifier` from block handler, block sync, and proposed block handler.
CI
> [consensus] support fastpath certification of transactions

- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/get_transaction_block.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/get_transaction_block.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/object_changes/create_delete.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/object_changes/create_wrap_unwrap_delete.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/object_changes/publish_upgrade.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/object_changes/transfer.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/object_changes/unwrap.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/object_changes/wrap.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/query/all.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/query/by_address.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/query/by_call.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/query/by_checkpoint.snap
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/transactions/query/by_object.snap
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/response.rs
- crates/sui-indexer-alt-jsonrpc/src/data/kv_loader.rs
There are some discrepancies between our transaction API and fullnode rpc's so this PR aims to close that gap.
Most of the changes are test snapshot changes due to the addition of checkpoint sequence number and timestamp.
Added a test and modified some tests.
---
> [rpc-alt] bring transaction response to parity with fullnode rpc

- crates/sui-indexer-alt-jsonrpc/src/data/object_versions.rs
- crates/sui-indexer-alt-schema/src/objects.rs
Two improvements to the object versions data loader:
- Only fetch the columns we care about (that are covered by the index), so the query can be performed as an index only scan.
- Switch to a JOIN using `UNNEST(ARRAY[...])` to supply the keys, as it is more efficient than `SELECT DISTINCT ON (...)`.
```
sui$ cargo nextest run -p sui-indexer-alt-e2e-tests
```
---
> rpc-alt: better latest object version data-loader

- consensus/core/src/authority_node.rs
- consensus/core/src/authority_service.rs
- consensus/core/src/block_manager.rs
- consensus/core/src/commit_observer.rs
- consensus/core/src/commit_syncer.rs
- consensus/core/src/context.rs
- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/lib.rs
- consensus/core/src/linearizer.rs
- consensus/core/src/metrics.rs
- consensus/core/src/synchronizer.rs
- consensus/core/src/test_dag_builder.rs
- consensus/simtests/src/node.rs
- consensus/simtests/src/tests/simtests.rs
- crates/sui-core/src/consensus_manager/mysticeti_manager.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
This PR is doing the following:
1. Is dropping the timestamp monotonicity block ancestor checks. We'll no longer check whether a block's ancestors timestamps are strictly lower than the block in question.
2. Calculating the commit's timestamp by using the leader's strong ancestors timestamps median. The calculation is stake based.
As it has been discussed, this will make the protocol more robust when it comes to block validity verification and repercussions of it. It is also simplifying the block acceptance path.
CI/PT
--- …
> [Consensus] rework commit & block timestamps

- crates/sui-indexer-alt-e2e-tests/tests/name_service_tests.rs
- crates/sui-indexer-alt-jsonrpc/src/api/name_service/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/name_service/response.rs
Implement reverse resolution for SuiNS.
Add new assertions to existing name service tests:
```
sui$ cargo nextest run -p sui-indexer-alt-e2e-tests \
--test name_service_tests
```
- #21471 
---
> rpc-alt: resolveNameServiceNames

- consensus/core/src/tests/base_committer_declarative_tests.rs
Here we setup a situation where theres is an undecided leader (D), but later we encounter B which votes for D to make it committed directly.
---
> Base committer equivocating test case

- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/dynamic_fields/deleted.move
- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc/dynamic_fields/deleted.snap
- crates/sui-indexer-alt-jsonrpc/src/api/dynamic_fields.rs
If a dynamic field has been deleted or wrapped, we should indicate that it has not been found (rather than fetching the last live version).
```
sui$ cargo nextest run -p sui-indexer-alt-e2e-tests \
-- dynamic_fields/deleted
```
- #21471 
- #21482 
---
> rpc-alt: track deletes/wraps for dynamic (object)? fields

- docs/content/concepts/sui-move-concepts.mdx
- docs/content/guides/developer/app-examples/e2e-counter.mdx
Updates the [move concepts page](https://docs.sui.io/concepts/sui-move-concepts) to have up to date info on the `entry` keyword. Removes the circular link to the [move reference](https://move-book.com/reference/functions.html#entry-modifier).
---
> [docs] Update to docs regarding the `entry` keyword in Move

- crates/sui-core/src/execution_cache/cache_types.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
Since these structures are created once at startup, this should have very little downside
> Increase dashmap shards and use segmented Moka cache to reduce lock contention

- crates/sui-proxy/src/admin.rs
- crates/sui-proxy/src/lib.rs
- crates/sui-proxy/src/main.rs
remove `std::env::set_var` from tests and allow timeout to be set without relying on an env var
for: https://github.com/MystenLabs/sui/pull/21488
local tests
> [sui-proxy] remove std::env::set_var

- Cargo.lock
- Cargo.toml
- crates/mysten-common/Cargo.toml
- crates/mysten-common/src/lib.rs
- crates/mysten-common/src/logging.rs
- crates/mysten-common/src/random.rs
- crates/mysten-common/src/util.rs
- crates/sui-core/Cargo.toml
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/consensus_quarantine.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
- crates/sui-core/src/execution_driver.rs
- crates/sui-core/src/transaction_manager.rs
- crates/sui-macros/src/lib.rs
- crates/sui-node/Cargo.toml
- crates/sui-node/src/main.rs
- Integrate Antithesis SDK
- Add reachability assertions
- Use antithesis RNG when available.
- `debug_fatal!` panics on antithesis
- randomize cache capacities to exercise cache miss/eviction paths
> Test infra improvements

- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-package/src/resolution/dependency_cache.rs
This fixes a package build problem on Windows where one has to specify input/output for OS commands explicitly. This is a generalization of a previous [fix](https://github.com/MystenLabs/sui/pull/19003) to all Git commands
Verified that the build proceeds correctly
> [move-analyzer] VSCode package build fix for Windows

- crates/sui-core/src/execution_cache/cache_types.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
This avoids the following crash:
```
thread '<unnamed>' panicked at crates/sui-core/src/execution_cache/cache_types.rs:307:17:
entry is newer than value 0x86aacc42979583a6797f4bb0cab20d436a1f41e215b2c87cb6e99ffdda5ec7db
stack backtrace:
0: rust_begin_unwind
at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:692:5
1: core::panicking::panic_fmt
at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:75:14
2: sui_core::execution_cache::cache_types::MonotonicCache<K,V>::insert
at /Users/marklogan/dev/sui-wb/crates/sui-core/src/execution_cache/cache_types.rs:307:17
3: sui_core::execution_cache::writeback_cache::WritebackCache::cache_latest_object_by_id
at /Users/marklogan/dev/sui-wb/crates/sui-core/src/execution_cache/writeback_cache.rs:1210 …
```
> Avoid a spurious assert in tests

- Cargo.lock
- Cargo.toml
Bump cynic to 3.10.0 to match sui-rust-sdk: https://github.com/MystenLabs/sui-rust-sdk/pull/102
---
> [chore] Bump cynic to 3.10.0 to match sui-rust-sdk

- external-crates/move/crates/move-vm-runtime/src/native_extensions.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/latest/sui-move-natives/src/address.rs
- sui-execution/latest/sui-move-natives/src/config.rs
- sui-execution/latest/sui-move-natives/src/crypto/bls12381.rs
- sui-execution/latest/sui-move-natives/src/crypto/ecdsa_k1.rs
- sui-execution/latest/sui-move-natives/src/crypto/ecdsa_r1.rs
- sui-execution/latest/sui-move-natives/src/crypto/ecvrf.rs
- sui-execution/latest/sui-move-natives/src/crypto/ed25519.rs
- sui-execution/latest/sui-move-natives/src/crypto/groth16.rs
- sui-execution/latest/sui-move-natives/src/crypto/group_ops.rs
- sui-execution/latest/sui-move-natives/src/crypto/hash.rs
- sui-execution/latest/sui-move-natives/src/crypto/hmac.rs
- sui-execution/latest/sui-move-natives/src/crypto/nitro_attestation.rs
- sui-execution/latest/sui-move-natives/src/crypto/poseidon.rs
- sui-execution/latest/sui-move-natives/src/crypto/vdf.rs
- sui-execution/latest/sui-move-natives/src/crypto/zklogin.rs
- sui-execution/latest/sui-move-natives/src/dynamic_field.rs
- sui-execution/latest/sui-move-natives/src/event.rs
- sui-execution/latest/sui-move-natives/src/object.rs
- sui-execution/latest/sui-move-natives/src/test_scenario.rs
- sui-execution/latest/sui-move-natives/src/transfer.rs
- sui-execution/latest/sui-move-natives/src/tx_context.rs
- sui-execution/latest/sui-move-natives/src/types.rs
- sui-execution/latest/sui-move-natives/src/validator.rs
It always annoyed me that this API was infallible as it should really return invariant violations if the extension is not found.
The bottom commit is the  core of the change and the other two commits on top are just the updates on the adapter side based on those changes. 
> [move/adapter] Make native extensions API fallible

- external-crates/move/crates/move-compiler-transactional-tests/tests/functions/identity_with_struct_unpack.move
- external-crates/move/crates/move-compiler-transactional-tests/tests/functions/identity_with_struct_unpack.snap
- external-crates/move/crates/move-compiler/src/cfgir/optimize/eliminate_locals.rs
- external-crates/move/crates/move-compiler/src/cfgir/optimize/mod.rs
- Fixed assignment optimization bug reported by https://pi2.network/ 
- Inlining did not consider assignments from struct unpacks/matches 
- Added a new test 
---
> [move-compiler] Fix assignment optimization 

- external-crates/move/crates/move-unit-test/src/extensions.rs
- external-crates/move/crates/move-vm-runtime/src/native_extensions.rs
- sui-execution/latest/sui-move-natives/src/lib.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
- sui-execution/latest/sui-move-natives/src/test_scenario.rs
- sui-execution/latest/sui-move-natives/src/transaction_context.rs
Replaces the usage of `TidAble<'a>` for `NativeExtensionMarker<'a>` in the interface for native extensions. This makes trying to query for a type in the native context extensions without registering the _exact_ type a static error. This explicitly does not have blanket implementations for wrappers of an underlying type that implements the trait unlike [`TidAble`](https://docs.rs/better_any/latest/better_any/trait.TidAble.html). This means you must register the exact type that you will be adding to the extensions with the `NativeExtensionMarker` trait.
> [move] Add static explicit marker for Move native extensions

- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-package/src/resolution/dependency_cache.rs
A previous PR attempting to fix `move-analyzer` on Windows introduced a more general [problem](https://github.com/MystenLabs/sui/issues/21528#issuecomment-2740119331) by accidentally removing some code. This PR fixes this problem.
Made sure that the server shutdown no longer happens
> [move-analyzer] Git IO fix

- Cargo.lock
- crates/sui-move-lsp/Cargo.toml
- crates/sui-move-lsp/src/bin/move-analyzer.rs
- crates/sui/src/sui_commands.rs
- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-analyzer/src/analyzer.rs
- external-crates/move/crates/move-analyzer/src/bin/move-analyzer.rs
- external-crates/move/crates/move-analyzer/src/completions/mod.rs
- external-crates/move/crates/move-analyzer/src/symbols.rs
- external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs
This PR gets `move-analyzer` to work with recently introduced implicit dependencies
Tested manually that when no "standard" dependencies are specified, Move VSCode extension does not report missing deps
> [move-analyzer] Updates to support implicit dependencies

- crates/sui-core/src/authority.rs
- crates/sui-core/src/jsonrpc_index.rs
- crates/sui-core/src/verify_indexes.rs
- crates/sui-json-rpc-tests/tests/data/tto/Move.toml
- crates/sui-json-rpc-tests/tests/data/tto/sources/tto.move
- crates/sui-json-rpc-tests/tests/tto.rs
Fix incorrect indexing of coin objects with tto as well as introduce a temporary background task to repair the indexes.
Closes: #21230
Closes: #21229
---
> jsonrpc: fix incorrect indexing of coin objects with tto

- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/consensus_adapter.rs
- crates/sui-core/src/mock_consensus.rs
To be used for consensus submissions which do not require commit confirmation
> Add `submit_best_effort` to SubmitToConsensus

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/consensus_adapter.rs
- crates/sui-core/src/mock_consensus.rs
To be used for consensus submissions which do not require commit
confirmation
Fix for issue which can cause all consensus submission permits to be consumed
- Load test in PTN
- Antithesis tests (ongoing)
---
> [Cherrypick] Add `submit_best_effort` to SubmitToConsensus (#21561)

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-node/src/lib.rs
- docker/sui-antithesis/docker-compose-antithesis.yaml
* pass the `SUI_PROTOCOL_CONFIG_CHAIN_OVERRIDE` environment variable on the Antithesis `docker-compose` file.
* retrieve the `chain_identifier` via the `epoch store` which does already perform overrides as introduced on https://github.com/MystenLabs/sui/pull/21516
CI
---
> [Consensus] fix passing the protocol config override

- external-crates/move/crates/move-vm-runtime/src/interpreter.rs
- external-crates/move/crates/move-vm-runtime/src/tracing2/mod.rs
- external-crates/move/crates/move-vm-runtime/src/tracing2/tracer.rs
Fixes a bug that @awelc found when implementing the tracer for PTBs. In particular tracing never allowed/accounted for external references being able to flow into- and out-of entrypoints (and native entrypoints). This fixes this problem by issuing global data loads in the trace + recording the proper value fills in locals in the frame for external references.
This also renames the function/macro `close_initial_frame` to `close_initial_native_frame` as this function is only called in the case where the entrypoint is a native function. Otherwise the normal `close_frame` is called. 
Ran it against the repro that @awelc had and verified it worked and made sure existing tests passed.
> [move][tracing] Allow references to flow in and out of entrypoints

- crates/simulacrum/src/lib.rs
- crates/simulacrum/src/store/in_mem_store.rs
- crates/simulacrum/src/store/mod.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority/authority_store_migrations.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/data_ingestion_handler.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/execution_cache.rs
- crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
- crates/sui-core/src/storage.rs
- crates/sui-core/src/test_authority_clients.rs
- crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs
- crates/sui-core/src/validator_tx_finalizer.rs
- crates/sui-rpc-api/src/reader.rs
- crates/sui-transactional-test-runner/src/lib.rs
- crates/sui-transactional-test-runner/src/simulator_persisted_store.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/storage/read_store.rs
- crates/sui-types/src/storage/shared_in_memory_store.rs
store: introduce events_2 table to store events keyed by transaction digest
In Sui TransactionEvents are not unique and multiple transactions can
produce the exact same set of TransactionEvents. Today these events are
stored in a table keyed by TransactionEventsDigest which can lead to an
unfortunate scenario when pruning is enabled. If we have two
transactions `A` and `B`, both of which produced events `E`, when the
pruner goes to prune transaction `A` it will also remove events `E` from
the database. This will lead to a situation where the node will be
unable to find locally the events produced by transaction `B`.
In order to fix this bug this patch introduces a new `events_2` table to
store events keyed by the transaction digest of the transaction that
produced them. It also updates …
> store: introduce events_2 table to store events keyed by transaction digest

- crates/sui-indexer-alt-jsonrpc/src/api/dynamic_fields.rs
- crates/sui-indexer-alt-jsonrpc/src/api/move_utils/response.rs
- crates/sui-package-resolver/src/error.rs
- crates/sui-package-resolver/src/lib.rs
- crates/sui-package-resolver/src/snapshots/sui_package_resolver__tests__pure_input_layouts_conflicting.snap
If it appears based on context that a pure input is being used as multiple types, produce no layout for that input, rather than erroring out pure input layout calculation.
Updated tests.
---
> rpc-alt: loosen pure input layouts calculation

- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/main.rs
There is a long-standing off-by-1 bug when initializing a new pipeline. The pipeline would be initialized to process checkpoint 1 first instead of checkpoint 0 first in the case where there was no existing state for the pipeline in the object store. This causes a panic which causes the whole process to crash on release builds.
This PR just fixes the off-by-1 bug.
Manually verified the off-by-1 bug no longer occurs
> Fix analytics pipeline initialization bug

- crates/sui-analytics-indexer/src/analytics_processor.rs
- crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/main.rs
No-op refactor that reduces overall LoC by like ~200 and makes it easier to change the pipeline initialization code.
* Introduces a new "TaskContext" struct that groups the process-level config with a single task's config, along with other task-specific structs like metrics, them TempDir, etc. This allows us to pass the single context struct everywhere instead of 4+ indepedent structs. 
* Eliminates need for the OnceLock introduced in [pull/21577](https://github.com/MystenLabs/sui/pull/21577)
* Makes it so we only need to define the checkpoint_root config once at the job level instead of repeating it on each task's config.
* "Eagerly" create the checkpoint_dirs when the process starts rather than "lazily"
Manual testing
> Refactor Analytics Indexer

- crates/sui-analytics-indexer/src/analytics_processor.rs
- crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/main.rs
This is fixing a bug in [pull/21486](https://github.com/MystenLabs/sui/pull/21486). Each task was sharing a "checkpoint_dir" which is where the output parquet/csv is temporarily stored until it is sync'd in the background to the object store. This could create problems if two pipelines for the same "type" (objects, transactions, etc) are running in the same process since this directory would end up conflicting (each pipeline creates a subdirectory named after its type in the checkpoint_dir).
The fix is to create a unique temporary directory per task to ensure there are no conflicts within a process.
Note that this PR motivated me to do [this subsequent refactor](https://github.com/MystenLabs/sui/pull/21578) to clean up this code a bit.
Manual testing.
> Give each pipeline it's own checkpoint directory.

- crates/sui-analytics-indexer/src/analytics_processor.rs
- crates/sui-analytics-indexer/src/handlers/df_handler.rs
- crates/sui-analytics-indexer/src/handlers/event_handler.rs
- crates/sui-analytics-indexer/src/handlers/object_handler.rs
- crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/main.rs
This is addressing a mistake in [pull/21486](https://github.com/MystenLabs/sui/pull/21486). All pipelines should share a LocalDBPackageStore. It's simply a local cache of on-chain package data so there is no reason to re-create it per stack.
Manual testing.
> Share local package DB

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_79.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_79.snap
> [consensus] Change leader (exclusion) stake threshold percent from 20 -> 30

- external-crates/move/crates/move-vm-runtime/src/interpreter.rs
Fix small mistake found in what simple instruction was used for casts. Change does not need to be protocol versioned as the underlying abstract size for these is the same. 
> [move] Fix simple instruction typos in VM

- crates/sui/src/client_commands.rs
- crates/sui/src/sui_commands.rs
The `--dump-bytecode-as-base64` lives in the `sui_commands.rs` in the CLI because of the need to pass in a client to have access to the network. We forgot to add the implicit deps flag there, which this PR fixes.
Should fix and close #21581
Locally
---
> [CLI] Fix the --dump-bytecode-as-base64 to work with implicit deps

- crates/sui-indexer-alt-jsonrpc/src/data/coin_metadata.rs
- crates/sui-indexer-alt-jsonrpc/src/data/displays.rs
Both these data-loaders follow a pattern where they generate some probes into the DB, based on the data loader key, form a set of these to query the DB with and then later try to zip that set with the original sequence of keys they were generated from.
If that sequence of keys is in a different order or contains duplicates, then keys are going to end up mis-aligned with their equivalent probes.
:eyes:
---
> fix(rpc-alt): fix CoinMetadata and Display data-loader ordering

- crates/sui/src/client_commands.rs
- crates/sui/src/sui_commands.rs
The `--dump-bytecode-as-base64` lives in the `sui_commands.rs` in the CLI because of the need to pass in a client to have access to the network. We forgot to add the implicit deps flag there, which this PR fixes.
Locally
---
> [Cherry-pick][CLI] Cherry pick fix cli dump basecode as base64

- crates/sui-rpc-benchmark/src/bin/pull_grafana_logs.rs
- crates/sui-rpc-benchmark/src/config.rs
- crates/sui-rpc-benchmark/src/direct/query_executor.rs
- crates/sui-rpc-benchmark/src/json_rpc/mod.rs
- crates/sui-rpc-benchmark/src/json_rpc/runner.rs
- crates/sui-rpc-benchmark/src/lib.rs
title
local run of the pull script
---
> rpc benchmark easy: custom file path as log dest.

- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-compiler/src/typing/translate.rs
- external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/wrong_completion_before_dot_call.move
- external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/wrong_completion_before_dot_call.snap
- external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/wrong_completion_before_dot_call@ide.snap
When method's access chain was incorrect, no auto-completion was generated even for correctly typed prefix of this chain, such as in this example:
```move
public struct SomeStruct {
some_field: u64,
}
public fun bar(_some_struct: &SomeStruct):u64 {
42
}
public fun foo(some_struct: &mut SomeStruct): u64 {
some_struct.
some_struct.bar()
}
```
Additionally, this behavior was inconsistent with the auto-completion behavior for a similar chain but ending in a (supposed) field access instead of a method call, where auto-completion for the dot following the first `some_struct` would be generated:
```move
public fun foo(some_struct: &mut SomeStruct): u64 {
some_struct.
some_struct.some_field
}
```
This PR fixes this issue
Added a new test. All tests must pass
> [move-ide] Fixed auto-completion for unresolved method chains

- consensus/core/src/authority_node.rs
- consensus/core/src/block.rs
- consensus/core/src/commit_syncer.rs
- consensus/core/src/core.rs
- consensus/core/src/core_thread.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/proposed_block_handler.rs
- consensus/core/src/transaction_certifier.rs
- Recover transaction votes after restarts, by re-evaluating transactions that need to be rejected, on blocks that has not been linked by proposed blocks.
- Include reject transaction votes from blocks newly linked by proposed blocks.
CI
---
> [fastpath] propose blocks with transaction votes

- crates/sui-types/src/effects/effects_v2.rs
- crates/sui-types/src/full_checkpoint_content.rs
This PR removes all direct uses of the `changed_objects` from effects v2.
We should always access effects through APIs (i.e. effects trait) for reads. Otherwise it will make it difficult to evolve effects.
Most changes are in full_checkpoint_contents. This PR also simplifies these functions a bit.
CI
---
> [effects] Do not expose internal effects state

- crates/sui-move/Cargo.toml
- crates/sui-move/src/unit_test.rs
- crates/sui/Cargo.toml
There was a remaining check in `sui-move/src/unit-test.rs` that checked for debug builds if you wanted to collect coverage, however this is no longer true or necessary since we enabled this with the `tracing` feature flag.
Updated this locally and verified that it both works in release builds with the tracing feature enabled, and that if you try to collect coverage in a build not built with the `tracing` featur e that you get the error. 
Ran it locally.
> [sui-move] Allow coverage gathering in release builds

- crates/sui-indexer-alt-schema/migrations/2025-03-26-050918_temp_obj_info_backfill/down.sql
- crates/sui-indexer-alt-schema/migrations/2025-03-26-050918_temp_obj_info_backfill/up.sql
- crates/sui-indexer-alt-schema/src/objects.rs
- crates/sui-indexer-alt-schema/src/schema.rs
- crates/sui-indexer-alt/src/handlers/mod.rs
- crates/sui-indexer-alt/src/handlers/obj_info_temp.rs
- crates/sui-indexer-alt/src/lib.rs
Duplicate `obj_info` table and pipeline for backfilling. This is temporary and will be removed once backfilling is done.
Duplicated tests as well.
---
> [indexer-alt] set up a temporary obj_info pipeline for backfilling

- external-crates/move/documentation/book/src/method-syntax.md
hey ! I found simple errors
convience - convenience
fom - from
> fix spelling issues method-syntax.md

- crates/sui-indexer-alt-schema/migrations/2025-03-26-050918_temp_obj_info_backfill/down.sql
- crates/sui-indexer-alt-schema/migrations/2025-03-26-050918_temp_obj_info_backfill/up.sql
- crates/sui-indexer-alt-schema/src/objects.rs
- crates/sui-indexer-alt-schema/src/schema.rs
- crates/sui-indexer-alt/src/handlers/mod.rs
- crates/sui-indexer-alt/src/handlers/obj_info_temp.rs
- crates/sui-indexer-alt/src/lib.rs
Duplicate `obj_info` table and pipeline for backfilling. This is temporary and will be removed once backfilling is done.
Duplicated tests as well.
---
---
For each box you select, include information after the relevant heading that describes the impact of your changes that …
> [cherry-pick][indexer-alt] set up a temporary obj_info pipeline for backfilling (#21619)

- Cargo.lock
- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/transaction_tests.rs
- crates/sui-transaction-checks/src/lib.rs
- crates/sui-types/src/object.rs
- crates/sui-types/src/programmable_transaction_builder.rs
- crates/sui-types/src/transaction.rs
- sui-execution/latest/sui-adapter/Cargo.toml
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
Verify object ownership at signing time.
No checks currently needed post-execution becuase SingleOwner has all permissions, but added a placeholder for the future.
---
> Implement authentication checks for ConsensusV2 objects

- crates/sui-indexer-alt-framework/src/ingestion/mod.rs
- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-framework/src/metrics.rs
Changes visibility of IngestionService and Indexer metrics to public.
This is useful for cases where the IngestionService is needed in a standalone mode and out of the context of the Indexer. 
For example, when a custom range of checkpoints need to be parsed.
```
let mut ingestion_service = IngestionService::new(
client_args,
IngestionConfig::default(),
metrics,
cancel.clone(),
)?;
let (mut rx, _) = ingestion_service.subscribe();
// Fetch malicious transactions and start ingestion
let checkpoint_ids = pipeline.fetch_malicious_trxs().await?;
println!("Found {} checkpoint IDs to process", checkpoint_ids.len());
let (_, _) = ingestion_service
.run(checkpoint_ids)
.await
.context("Failed to start ingestion service")?;
```
Existing tests pass
---
Check each box that your changes affect. If …
> [indexer-alt]: Changes visibility of IngestionService and Indexer metrics

- crates/sui-indexer-alt/src/config.rs
- crates/sui-indexer-alt/src/lib.rs
I realized the previous PR #21619 did not include `obj_info_temp`  in the pipeline layer config so the config wouldn't be passed in properly. This PR fixes that.
Ran indexer locally with a config for `obj_info_temp` pipeline.
---
> [indexer-alt] add temp obj_info pipeline to config

- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
> Correct ObjectRuntime::transfer result for ConsensusV2 transfers to same owner

- crates/sui-types/src/execution.rs
> Record start version for new ConsensusV2 object streams

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_79.snap
Enables consensus garbage collection and new linearizer logic in mainnet.
CI/PT/Antithesis
---
> [Consensus] enable consensus garbage collection on mainnet.

- external-crates/move/crates/move-compiler/src/naming/ast.rs
- external-crates/move/crates/move-compiler/src/naming/resolve_use_funs.rs
- external-crates/move/crates/move-compiler/src/naming/translate.rs
- external-crates/move/crates/move-compiler/src/typing/core.rs
- external-crates/move/crates/move-compiler/src/typing/macro_expand.rs
- external-crates/move/crates/move-compiler/src/typing/translate.rs
- external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/macro_types.move
- external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/macro_types.snap
- external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/macro_types@ide.snap
- external-crates/move/crates/move-compiler/tests/move_2024/ide_mode/macro_types@ide.snap.new
- external-crates/move/crates/move-compiler/tests/move_2024/typing/annotated_lambda.move
- external-crates/move/crates/move-compiler/tests/move_2024/typing/annotated_lambda.snap
- external-crates/move/crates/move-compiler/tests/move_2024/typing/annotated_lambda_type_inference.move
- external-crates/move/crates/move-compiler/tests/move_2024/typing/annotated_lambda_type_inference.snap
- external-crates/move/crates/move-compiler/tests/move_2024/typing/annotated_lambda_type_inference_invalid.move
- external-crates/move/crates/move-compiler/tests/move_2024/typing/annotated_lambda_type_inference_invalid.snap
- external-crates/move/crates/move-compiler/tests/move_2024/typing/lambda_expression_annotation.move
- external-crates/move/crates/move-compiler/tests/move_2024/typing/lambda_expression_annotation.snap
- external-crates/move/crates/move-compiler/tests/move_2024/typing/lambda_expression_annotation_invalid.move
- external-crates/move/crates/move-compiler/tests/move_2024/typing/lambda_expression_annotation_invalid.snap
- external-crates/move/crates/move-compiler/tests/move_2024/typing/macros_lambdas_checked_invalid_arity.snap
- external-crates/move/crates/move-compiler/tests/move_2024/typing/mismatched_lambda_arity.snap
- The compiler now supports type annotations on lambdas, e.g. `(|x| { x }: |u64| -> u64)`
- This support was added simply because it is the same issue around dropping types on lambdas during expansion
- New IDE test
- New annotations tests
---
> [move-compiler] Fix annotation support for macro lambdas

- external-crates/move/crates/move-analyzer/editors/code/package.json
In order to publish the extension, we need to bump its version number. The reason for publishing is a recent fix to `move-analyzer` implemented by @tnowacki (great thanks!) in https://github.com/MystenLabs/sui/pull/21633
Tested in https://github.com/MystenLabs/sui/pull/21633
> [move-ide] Publish with recently implemented macro fix

- docker/sui-node-deterministic/Dockerfile
- Use env vars vs flags (cleaner)
- upgrade to latest stagex (Rust 1.85.0)
> Update deterministic sui-node for rust 1.85 + cleanup

- crates/sui-core/src/transaction_input_loader.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/object.rs
- crates/sui-types/src/programmable_transaction_builder.rs
- crates/sui-types/src/storage/mod.rs
- crates/sui-types/src/transaction.rs
Previously this did not correctly account for the possibility of `initial_shared_version` not matching between the requested input and the object that was loaded.
---
> Update transaction input loader logic for ConsensusV2 objects

- crates/sui/src/client_ptb/ast.rs
- crates/sui/src/client_ptb/builder.rs
- crates/sui/src/client_ptb/lexer.rs
- crates/sui/src/client_ptb/parser.rs
- crates/sui/src/client_ptb/ptb.rs
- crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_commands.snap
- crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_mvr_names_invalid.snap
- crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_mvr_names_valid.snap
- crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_publish.snap
- crates/sui/src/client_ptb/token.rs
- crates/sui/src/lib.rs
- crates/sui/src/mvr_resolver.rs
- crates/sui/tests/cli_tests.rs
- crates/sui/tests/ptb_files_tests.rs
This PR adds support for MVR in `sui client ptb`.
Existing tests and added new tests for parsing mvr names.
---
> [CLI] Support for MVR in `sui client ptb`

- Cargo.lock
- crates/sui-protocol-config/Cargo.toml
- crates/sui-protocol-config/src/lib.rs
For the `simtests` and `antithesis` environments we would like to exercise an as much low as possible GC so we can stress the limits of GC.
CI
---
> [Consensus] exercise low gc_depth for simtests and antithesis.

- crates/sui/src/client_ptb/ast.rs
- crates/sui/src/client_ptb/builder.rs
- crates/sui/src/client_ptb/lexer.rs
- crates/sui/src/client_ptb/parser.rs
- crates/sui/src/client_ptb/ptb.rs
- crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_commands.snap
- crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_mvr_names_invalid.snap
- crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_mvr_names_valid.snap
- crates/sui/src/client_ptb/snapshots/sui__client_ptb__parser__tests__parse_publish.snap
- crates/sui/src/client_ptb/token.rs
- crates/sui/src/lib.rs
- crates/sui/src/mvr_resolver.rs
- crates/sui/tests/cli_tests.rs
- crates/sui/tests/ptb_files_tests.rs
This PR adds support for MVR in `sui client ptb`.
Existing tests and added new tests for parsing mvr names.
---
> [CherryPick][CLI] Support for MVR in `sui client ptb` (#21609)

- Cargo.lock
- crates/sui-protocol-config/Cargo.toml
- crates/sui-protocol-config/src/lib.rs
Reverts MystenLabs/sui#21635
Break antithesis upgrade test, since the previous version does not support this override.
> Revert "[Consensus] exercise low gc_depth for simtests and antithesis."

- crates/sui-framework/docs/sui/group_ops.md
- crates/sui-framework/docs/sui/poseidon.md
- crates/sui-framework/docs/sui/vdf.md
- crates/sui-framework/packages/sui-framework/sources/crypto/group_ops.move
- crates/sui-framework/packages/sui-framework/sources/crypto/poseidon.move
- crates/sui-framework/packages/sui-framework/sources/crypto/vdf.move
Add a note to the function docs of Sui framework functions that are only enabled on Devnet. Currently, this is oblivious to anyone reading the docs.
No functional changes, so no tests are needed.
---
> Docs: Add note to functions only available on Devnet

- crates/sui-core/src/authority/authority_per_epoch_store.rs
> Relax shared object init version check when reshare_at_same_initial_version is false

- external-crates/move/crates/move-analyzer/Cargo.toml
For full Sui support, `move-analyzer` binary should be built with the following command:
```shell
cargo install --git https://github.com/MystenLabs/sui sui-move-lsp
```
However, prior to this PR, it was also possible to build it with the following command which resulted in a binary that lacked some of the features (e.g., support for implicit deps):
```shell
cargo install --git https://github.com/MystenLabs/sui move-analyzer
````
This was confusing, particularly for people that use `move-analyzer` binary to support editors other than VSCode. Hence the decision to only allow creation of a binary from `sui-move-lsp` crate.
Verified that the binary can no longer be built from `move-analyzer` external crate
> [move-ide] Disable building of move-analyzer binary in external crates

- crates/sui-indexer-alt-e2e-tests/src/lib.rs
- crates/sui-indexer-alt-e2e-tests/tests/fn_delegation_tests.rs
- crates/sui-indexer-alt-jsonrpc/src/args.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/context.rs
- crates/sui-indexer-alt-jsonrpc/src/data/bigtable_reader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/checkpoints.rs
- crates/sui-indexer-alt-jsonrpc/src/data/objects.rs
- crates/sui-indexer-alt-jsonrpc/src/data/pg_reader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/transactions.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
- crates/sui-indexer-alt-jsonrpc/src/main.rs
- crates/sui-indexer-alt-jsonrpc/src/metrics/middleware.rs
Various clean-ups for JSONRPC-alt's readers, ahead of factoring them out into their own crate to re-use in GraphQL:
- Avoid copying `RpcArgs` to get one field from it out, by introducing an accessor function for that field.
- Clean up a stale comment.
- Standardise slow request threshold logs (parameter order and units).
- Encapsulate logging within `BigtableReader`.
- Standardise `warn` message for `BigtableReader` to appear like the same message in `PgReader`.
- Configure Bigtable's `instance-id` using a CLI arg, rather than in the TOML, as it is conceptually closest to `--database-url` (parameters related to connections conventionally go in the CLI args, because it's more common to configure them differently for different instances that are otherwise configured the same).
Existing …
> jsonrpc-alt: assorted reader clean-ups

- crates/sui-indexer-alt-e2e-tests/src/lib.rs
- crates/sui-indexer-alt-e2e-tests/tests/fn_delegation_tests.rs
- crates/sui-indexer-alt-jsonrpc/src/args.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/context.rs
- crates/sui-indexer-alt-jsonrpc/src/data/bigtable_reader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/checkpoints.rs
- crates/sui-indexer-alt-jsonrpc/src/data/objects.rs
- crates/sui-indexer-alt-jsonrpc/src/data/pg_reader.rs
- crates/sui-indexer-alt-jsonrpc/src/data/transactions.rs
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
- crates/sui-indexer-alt-jsonrpc/src/main.rs
- crates/sui-indexer-alt-jsonrpc/src/metrics/middleware.rs
Picking various indexing and RPC related changes to our current testnet branch, so that we can deploy RPC and Indexer from the same release branch.
Picking the following to bring the release version of `jsonrpc-alt` up to speed with recent fixes we landed and deployed from `main`:
- #21605
- #21622
This change has not landed yet, but once it does, it needs to be picked to all release branches so that they all agree on how the RPC service accepts the bigtable config.
- #21657 
```
sui$ cargo nextest run       \
-p sui-indexer-alt         \
-p sui-indexer-alt-jsonrpc \
-p sui-indexer-alt-e2e-tests
```
--- …
> rpc-alt: testnet picks

- crates/sui-http/src/lib.rs
- crates/sui-node/src/lib.rs
- crates/sui-rpc-api/src/config.rs
Introduce the ability to serve rpc traffic over https by providing a TLS
cert and private key via config.
The relevant section of the node yaml config:
```
rpc:
https_address: 0.0.0.0:9443 # This is the default if not provided
tls:
cert: /path/to/cert.pem
key: /path/to/key.pem
```
---
> rpc: enable serving rpc traffic over https

- Cargo.lock
- Cargo.toml
- crates/sui-indexer-alt-framework/Cargo.toml
- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-framework/src/models/watermarks.rs
- crates/sui-indexer-alt-framework/src/pg_store.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/commit_watermark.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/reader_watermark.rs
- crates/sui-indexer-alt-framework/src/pipeline/logging.rs
- crates/sui-indexer-alt-framework/src/pipeline/mod.rs
- crates/sui-indexer-alt-framework/src/pipeline/sequential/committer.rs
- crates/sui-indexer-alt-framework/src/pipeline/sequential/mod.rs
- crates/sui-indexer-alt-framework/src/store.rs
- crates/sui-indexer-alt/src/handlers/sum_displays.rs
- crates/sui-indexer-alt/src/handlers/sum_packages.rs
- Introduce the `DbConnection` and `Store` traits. `DbConnection` has methods for handling `watermarks`, while `Store` exposes a `DbConnection`. The `TransactionalStore` additionally has a `transaction` method for sequential pipelines.
- Demonstrate implementation with `pg_store`, in the framework for now due to all the tests within the crate.
- Sequential pipelines has been updated to demonstrate. the `sequential::Handler` now has an associated type, `Store: TransactionalStore`, which allows us to eventually make `Indexer` generic over `Store`, and the handlers aware of the `Store` type
- Most of the structs and implementations within `framework/model/watermark.rs`  has been inlined to the `DbConnection` methods. This will make it easier to lift `pg_store` out of the framework later, and …
> [indexer-alt][db-agnostic framework][2/n]  pg-agnostic `DbConnection` and `Store`, update sequential pipelines accordingly

- crates/sui-core/src/authority.rs
- crates/sui-core/src/checkpoints/causal_order.rs
- crates/sui-core/src/congestion_tracker.rs
- crates/sui-core/src/execution_cache.rs
- crates/sui-core/src/transaction_input_loader.rs
- crates/sui-core/src/transaction_outputs.rs
- crates/sui-core/src/unit_tests/shared_object_deletion_tests.rs
- crates/sui-core/tests/staged/sui.yaml
- crates/sui-graphql-rpc/src/types/unchanged_shared_object.rs
- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-mvr-graphql-rpc/src/types/unchanged_shared_object.rs
- crates/sui-replay/src/replay.rs
- crates/sui-transaction-checks/src/lib.rs
- crates/sui-types/src/effects/effects_v1.rs
- crates/sui-types/src/effects/effects_v2.rs
- crates/sui-types/src/effects/mod.rs
- crates/sui-types/src/execution.rs
- crates/sui-types/src/inner_temporary_store.rs
- crates/sui-types/src/storage/mod.rs
- crates/sui-types/src/sui_sdk_types_conversions.rs
- crates/sui-types/src/transaction.rs
- sui-execution/latest/sui-adapter/src/execution_engine.rs
- sui-execution/latest/sui-adapter/src/temporary_store.rs
- sui-execution/v0/sui-adapter/src/temporary_store.rs
- sui-execution/v1/sui-adapter/src/execution_engine.rs
- sui-execution/v1/sui-adapter/src/temporary_store.rs
- sui-execution/v2/sui-adapter/src/execution_engine.rs
- sui-execution/v2/sui-adapter/src/temporary_store.rs
These are now referred to as "consensus stream ended" (or similar). ConsensusV2 objects may be removed from consensus without being deleted.
Note:
- GraphQL RPC updates are left for a future PR.
- Actual implementation of marker table writes when a ConsensusV2 object is transferred to a different owner type is left for a future PR.
Name changes only
---
> Update name of "shared deletion" indicators across the codebase

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_80.snap
> [consensus] Enable consensus median based timestamp for mainnet

- crates/sui-core/src/authority.rs
Locally computed checkpoints may be pruned.
---
> Check both local and certified checkpoints tables in create_execution_time_observations_tx

- crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
- crates/sui-indexer-alt/src/handlers/mod.rs
- crates/sui-indexer-alt/src/handlers/obj_info.rs
- crates/sui-indexer-alt/src/handlers/obj_info_temp.rs
- crates/sui-types/src/full_checkpoint_content.rs
- crates/sui-types/src/test_checkpoint_data_builder.rs
Move checkpoint_input_objects fn into framework out of sui-types. use tx.effects.object_changes() as source of truth.
---
> [indexer-alt] move checkpoint_input_objects fn into framework out of sui-types, use object_changes api

- Cargo.lock
- external-crates/move/Cargo.lock
- external-crates/move/Cargo.toml
- external-crates/move/crates/move-package-alt/Cargo.toml
- external-crates/move/crates/move-package-alt/src/package/lockfile.rs
This PR uses a substring operation to extract the env name from a `Move.env.lock` file, instead of using `lazy-regex`.
Added a new test.
---
> [mp-alt] Switch to using a substring operation instead of lazy regex

- crates/sui-indexer/src/config.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/handlers/committer.rs
- crates/sui-indexer/src/indexer.rs
- crates/sui-indexer/src/main.rs
- crates/sui-indexer/src/test_utils.rs
- crates/sui-indexer/tests/ingestion_tests.rs
Similar as #21732 , removes code variants that were used to test the core indexer behaviour with mvr variant.
Hopefully CI passes 🤞 
---
> [2/2] Remove indexer references to MVR (on the base one)

- Cargo.lock
- Cargo.toml
- crates/mysten-network/src/grpc_timeout.rs
- crates/mysten-network/src/server.rs
- crates/sui-bridge/src/server/mod.rs
- crates/sui-faucet/Cargo.toml
- crates/sui-faucet/src/server.rs
- crates/sui-graphql-rpc/Cargo.toml
- crates/sui-http/Cargo.toml
- crates/sui-indexer-alt-jsonrpc/Cargo.toml
- crates/sui-proxy/src/middleware.rs
- crates/sui-rpc-api/Cargo.toml
- crates/sui-rpc-api/src/grpc/mod.rs
- crates/sui-rpc-api/src/lib.rs
- crates/sui-rpc-api/src/proto/generated/sui.node.v2.rs
- crates/sui-rpc-api/src/proto/generated/sui.rpc.v2alpha.rs
- crates/sui-rpc-api/src/proto/generated/sui.rpc.v2beta.rs
- crates/x/src/lint.rs
- scripts/simtest/cargo-simtest
- scripts/simtest/config-patch
This updates axum to 0.8 and tonic to 0.13 almost everywhere. We're unable to upgrade to axum 0.8 in the graphql crates due to async-graphql requiring 0.7, that and its non-trivial to update async-graphql due to the large number of breaking changes (which are a violation of semver...)
---
> chore: update axum to 0.8 and tonic to 0.13

- Cargo.lock
- external-crates/move/Cargo.lock
- external-crates/move/Cargo.toml
- external-crates/move/crates/move-package-alt/src/package/lockfile.rs
- external-crates/move/crates/move-package/src/compilation/build_plan.rs
- external-crates/move/crates/move-package/src/lock_file/schema.rs
- external-crates/move/crates/move-package/src/resolution/dependency_graph.rs
This PR bumps the `toml-edit` version to a newer one which has support for spans and `serde_spanned`. We want to use that in the new move-package-alt, so this PR separates this change from others.
---
> [move] Move bump toml edit

- external-crates/move/crates/move-package/src/resolution/dependency_graph.rs
- external-crates/move/crates/move-package/tests/test_sources/external/Move@progress.snap
- external-crates/move/crates/move-package/tests/test_sources/external_dev_dep/Move@progress.snap
- external-crates/move/crates/move-package/tests/test_sources/external_failing/Move@progress.snap
- external-crates/move/crates/move-package/tests/test_sources/external_package_batch_response/Move@progress.snap
Currently if an external resolver outputs anything it is marked as an error; this PR removes that line. The output from the resolver is still printed, and if the resolver exits with an error code, that is still reported as an error.
No additional tests; change is trivial.
---
> [CLI] removed scary external resolver output

- external-crates/move/crates/move-package/src/resolution/dependency_graph.rs
- external-crates/move/crates/move-package/tests/test_sources/external/Move@progress.snap
- external-crates/move/crates/move-package/tests/test_sources/external_dev_dep/Move@progress.snap
- external-crates/move/crates/move-package/tests/test_sources/external_failing/Move@progress.snap
- external-crates/move/crates/move-package/tests/test_sources/external_package_batch_response/Move@progress.snap
Currently if an external resolver outputs anything it is marked as an error; this PR removes that line. The output from the resolver is still printed, and if the resolver exits with an error code, that is still reported as an error.
No additional tests; change is trivial.
---
--- …
> [CLI] cherry-pick: removed scary external resolver output (#21742)

- crates/sui-core/src/authority/authority_store_tables.rs
- crates/typed-store/src/lib.rs
- crates/typed-store/src/memstore.rs
- crates/typed-store/src/rocks/errors.rs
- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/rocks/rocks_util.rs
- crates/typed-store/src/rocks/safe_iter.rs
- crates/typed-store/src/rocks/tests.rs
- crates/typed-store/src/tidehunter_util.rs
- crates/typed-store/src/traits.rs
- crates/typed-store/src/util.rs
- crates/typed-store/tests/macro_tests.rs
PR enables iterator methods for in_memory_db and tidehunter
---
> [typed store] enable iterator methods for in_memory_db and tidehunter

- crates/bin-version/src/lib.rs
- crates/sui-core/src/runtime.rs
- crates/sui-graphql-rpc/src/test_infra/cluster.rs
- crates/sui-indexer/src/test_utils.rs
- crates/sui-node/src/lib.rs
- crates/sui-node/src/main.rs
- crates/sui-rosetta/src/main.rs
- crates/sui-rpc-api/src/grpc/v2beta/ledger_service/get_service_info.rs
- crates/sui-rpc-api/src/lib.rs
- crates/sui-rpc-api/src/response.rs
- crates/sui-rpc-api/src/service/info.rs
- crates/sui-swarm/src/memory/container-sim.rs
- crates/sui-swarm/src/memory/container.rs
bin-version: remove trailing '-' when GIT_REVISION is empty
Also do a small cleanup and remove an unused tokio runtime that was being started.
---
> bin-version: remove trailing '-' when GIT_REVISION is empty

- consensus/core/src/metrics.rs
- consensus/core/src/synchronizer.rs
Remove a few validation checks for fetched blocks which are incompatible with the new synchronization batching logic.
Reduce SYNCHRONIZER_TIMEOUT / PERIODIC_FETCH_INTERVAL: reduce the lag of periodic background fetching.
Reduce MAX_RETRIES: it is unnecessary to retry failures during "live" block sync too hard, since the blocks can arrive on its own or via periodic fetch.
Deployed to Mysten-3 on testnet.
---
> [consensus] fix processing of fetched blocks

- docker/sui-analytics-indexer/Dockerfile
Adding a Dockerfile to enable running sui-analytics-indexer in Kubernetes.
I have a branch of sui-operations where I am working on a Pulumi stack where I have tested this.
> Adding a dockerfile for sui-analytics-indexer

- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/rocks/tests.rs
Regular Arc causes `safe_drop_db` call to fail with `lock hold by current process` exception
---
> [typed store] use weak ref for metrics thread

- crates/sui-analytics-indexer/src/package_store.rs
- crates/sui-bridge/src/storage.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/sui-core/src/authority/transaction_deferral.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/epoch/committee_store.rs
- crates/sui-core/src/jsonrpc_index.rs
- crates/sui-core/src/rpc_index.rs
- crates/sui-faucet/src/faucet/write_ahead_log.rs
- crates/sui-storage/src/lib.rs
- crates/sui-storage/src/write_path_pending_tx_log.rs
- crates/sui-transactional-test-runner/src/simulator_persisted_store.rs
- crates/typed-store-derive/src/lib.rs
- crates/typed-store/src/lib.rs
- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/rocks/options.rs
- crates/typed-store/src/rocks/tests.rs
- crates/typed-store/src/traits.rs
- crates/typed-store/tests/macro_tests.rs
noop PR
- removes few methods from typed store macros crate
- deprecates TypedStoreDebug trait
- moves rocksdb options construction into a separate module 
---
> [typed store] cleanup of macros crate

- Cargo.lock
- crates/typed-store/Cargo.toml
- crates/typed-store/src/rocks/mod.rs
Mitigates the race between the destructor and metric threads. Reason: `rocksdb::DB::Destroy` returns an error immediately if any other reference is still alive
---
> [typed store] add backoff to safe_drop_db

- consensus/core/src/authority_node.rs
- consensus/core/src/metrics.rs
Retrieving the current authority index and protocol version from logs can be a bit slow, so exporting them as metrics. 
CI
PT
---
> [consensus] add debugging metrics

- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-e2e-tests/tests/checkpoint_tests.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_80.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_80.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_80.snap
First consensus commit in an epoch does not have knowledge of the last consensus commit of the previous epoch right now. So the first commit timestamp may be less than the previous commit timestamp. Adding this logic to ensure checkpoints have non decreasing timestamps.
CI
---
> Force checkpoint timestamp to be non decreasing

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/shared_object_version_manager.rs
This PR delays the merging of non randomness certificates and randomness certificates when processing consensus transactions.
We keep them separated until we are done with assigning shared object versions.
This should be a non-functional-change.
This will be necessary for supporting accumulators, because we need to settle accumulators per pending checkpoint. In this case, if we are generating two pending checkpoints (one for non randomness and one for randomness), we need to assign versions for the accumulator object twice.
To make things simpler, this PR also removes the randomness-specific logic in the version manager, instead it generates a placeholder randomness state update transaction, and let version manager to assign versions automatically.
CI
---
Check each box that your changes …
> [consensus_handler] Process non_randomness and randomness transactions separately

- crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
- crates/sui-indexer-alt/src/handlers/mod.rs
- crates/sui-indexer-alt/src/handlers/obj_info.rs
- crates/sui-indexer-alt/src/handlers/obj_info_temp.rs
- crates/sui-types/src/effects/test_effects_builder.rs
- crates/sui-types/src/test_checkpoint_data_builder.rs
Couple of clean-ups on top of the new `obj_info` pipelines:
- Move `use` above `mod`.
- Early return style inside the loop body.
- Use `entry` API to reduce number of hash table look ups.
- Return a `Result` instead of panicking.
- Use `object_changes` to figure out what the output objects are, (not `tx.output_objects`).
- Adding true support for reading frozen objects and modifying shared inputs to `TestCheckpointBuilder`, and use it to write tests directly for `checkpoint_input_objects` and update the tests for handlers.
```
sui$ cargo nextest run -p sui-indexer-alt
```
---
For each box you select, include information after the relevant heading that describes the impact …
> indexer-alt: Clean-ups from #21721

- consensus/core/src/authority_node.rs
- consensus/core/src/block.rs
- consensus/core/src/block_verifier.rs
- consensus/core/src/context.rs
- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/test_dag.rs
- consensus/core/src/test_dag_builder.rs
- consensus/simtests/src/node.rs
- crates/sui-core/src/consensus_manager/mysticeti_manager.rs
This makes the 1st consensus commit timestamp of an epoch the same as the last checkpoint timestamp of the previous epoch.
Reusing the `enforce_checkpoint_timestamp_monotonicity` feature flag, since both changes should roll out with the same schedule.
CI
---
> [consensus] start epoch from last checkpoint timestamp

- consensus/core/src/metrics.rs
This commit implements the TODO in metrics.rs by adding a "status" label 
to the invalid_blocks counter vector. The new label will provide more 
detailed information about the status of invalid blocks, allowing for 
better monitoring and debugging of consensus issues. This enhancement 
improves the observability of block validation failures in the system.
> Add status label to invalid_blocks metrics

- crates/sui-core/src/checkpoints/mod.rs
This seems to reduce failure rate of simtests.
CI
`python ./scripts/simtest/seed-search.py test_simulated_load_reconfig_with_crashes_and_delays --test simtest --num-seeds 2000` passed
---
> Increase wait_for_rebuilt_checkpoints() timeout from 60s to 120s

- consensus/core/src/commit_consumer.rs
- crates/sui-core/src/consensus_handler.rs
Otherwise, replaying commits that Sui consensus handler already observed do not update this watermark, so waiting on `replay_complete()` never finishes.
CI
```
python ./scripts/simtest/seed-search.py test_simulated_load_rolling_restarts_all_validators --test simtest --num-seeds 2000
```
---
> Always acknowledge handled consensus commits

- consensus/core/src/commit_consumer.rs
- crates/sui-core/src/consensus_handler.rs
This issue should be rare in production, but it seems better to have it fixed.
CI
---
> Pick #21824 to 1.47

- crates/sui-indexer-alt/src/handlers/kv_feature_flags.rs
- crates/sui-indexer-alt/src/handlers/kv_protocol_configs.rs
- crates/sui-types/src/test_checkpoint_data_builder.rs
Use `ProtocolConfig::get_for_version_if_supported` instead of `ProtocolConfig::get_for_version`, so that if the version is not supported, we don't panic and have a chance to propagate an error.
If this pipeline is running in the same process as other pipelines, this will allow those other pipelines to continue making progress.
New unit test for this behaviour.
```
sui$ cargo nextest run -p sui-indexer-alt
```
---
> indexer-alt: avoid panic in kv_protocol_configs

- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-analyzer/editors/code/src/configuration.ts
- external-crates/move/crates/move-analyzer/editors/code/src/context.ts
- external-crates/move/crates/move-analyzer/src/analyzer.rs
- external-crates/move/crates/move-analyzer/src/completions/mod.rs
- external-crates/move/crates/move-analyzer/src/context.rs
This PR introduces a Move plugin option to disable auto-imports during auto-completion. The two main reasons are:
- the auto-completion list gets much longer with auto-imports and if someone does not want them, it may get annoying
- it's easy to introduce edits to a file this way and formatting of these edits is at the moment rather rudimentary
Tested manually that the option works
> [move-ide] Added option to disable auto-imports during auto-completion

- docs/content/guides/operator/snapshots.mdx
Addressing feedback shared via discord:
> would be nice for the snapshots instructions in the docs to be updated, they've been somewhat incorrect for many months now: 
> 1. Sample sui-tool command uses --snapshot-bucket, --snapshot-bucket-type and --no-sign-request, an incompatible combination 
> 2. Paths referenced in the Info block for full nodes are incorrect (my full node does not have an authorities_db directory in the db) 
> 3. point 2 in the restoring using rocksdb refers to db-config but I have db-path and it points to the db top level directory /opt/sui/db not the additional authorities_db/fullnode_db as indicated in the guide
--- …
>  [docs] fix db-path name & use working sui-tool example command

- crates/sui-replay-2/src/lib.rs
I changed the `verify` flag to be `true` by default but it's not possible to make it `false` the way the flag is declared.
So reverting back to the old behavior where you have to pass `-v` or `--verify` to verify the transaction
tried...
---
> simple fix

- Cargo.lock
- crates/simulacrum/Cargo.toml
- crates/simulacrum/src/lib.rs
- crates/sui-archival/src/tests.rs
- crates/sui-archival/src/writer.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-core/src/storage.rs
- crates/sui-network/src/state_sync/mod.rs
- crates/sui-network/src/state_sync/server.rs
- crates/sui-network/src/state_sync/tests.rs
- crates/sui-tool/src/lib.rs
- crates/sui-transactional-test-runner/src/lib.rs
- crates/sui-transactional-test-runner/src/simulator_persisted_store.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/storage/read_store.rs
- crates/sui-types/src/storage/shared_in_memory_store.rs
We have seen cases where there is db correction when trying to deserialize full checkpoint content from db.
Since this is not required by the protocol, we could tolerate the error. This would allow the node to re-fetch these contents.
CI
---
> Tolerate db error when getting full checkpoint contents

- crates/mysten-network/src/client.rs
- crates/mysten-network/src/multiaddr.rs
- crates/sui-core/src/authority_client.rs
- crates/sui-swarm/src/memory/node.rs
- crates/sui-tool/src/lib.rs
> Enable TLS by default for validator gRPC client

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/jsonrpc_index.rs
- crates/sui-node/src/lib.rs
- crates/sui-tool/src/db_tool/mod.rs
- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/rocks/tests.rs
- crates/typed-store/src/traits.rs
PR deprecates following typed store methods: unsafe_clear, create_cf, flush
---
> [typed store] remove unsafe_clear/create_cf/flush methods

- crates/sui-node/src/lib.rs
The debug fatal in this function has been triggered in both simtests and antithesis.
Adding more debug information that would help us root cause the issue.
---
> Add more logging when reexecute_pending_consensus_certs fails

- crates/sui-json-rpc-types/src/sui_move.rs
- crates/sui/src/upgrade_compatibility/mod.rs
- external-crates/move/crates/move-binary-format/src/compatibility.rs
- external-crates/move/crates/move-binary-format/src/normalized.rs
- external-crates/move/crates/move-binary-format/src/unit_tests/compatibility_tests.rs
- external-crates/move/crates/move-bytecode-utils/src/layout.rs
- Separates changes from #21778 that are a bit more involved than I would have hoped
- Adds more uses of IndexMap and explicit indications of how equality is treated, whether it is this sort of "set based", key-value equality OR if it should be treated as an ordered, indexed collection.
- Ran tests
---
> [normalized module] Restructure equality for explicit treatment of maps

- crates/sui-move/src/build.rs
- crates/sui/src/sui_commands.rs
This PR tries to fix a bug in the `sui move build --dump-bytecode-as-base64 --ignore-chain` as the previous code did not correctly account for `--ignore-chain` flag. The main issue is that when `--ignore-chain` is used, the tree shaking algorithm will not work anymore.
Should fix #21846 
---
> [cli] Try to fix the `sui-move-build --dump-bytecode-as-base64 --ignore-chain`

- crates/sui-core/src/checkpoints/checkpoint_executor/utils.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-node/src/lib.rs
Looks like later on the code will also attempt to rebuild all checkpoints, which depends on all pending transactions executed. Antithesis starts to report failures after the previous change.
So this PR partially revert the code, but with some important differences:
1. Instead of just re-scheduling transactions with locally signed effects, we schedule all fast-path pending consensus transactions.
2. We no longer wait here. Instead, when it rebuild all checkpoints, it will wait anyway.
Let's see if antithesis would be happy after this.
--- …
> Re-execute all pending consensus transactions at startup

- external-crates/move/crates/move-model-2/Cargo.toml
- external-crates/move/crates/move-model-2/src/compiled_model.rs
- external-crates/move/crates/move-model-2/src/lib.rs
- external-crates/move/crates/move-model-2/src/model.rs
- external-crates/move/crates/move-model-2/src/normalized.rs
- external-crates/move/crates/move-model-2/src/serializable_signatures.rs
- external-crates/move/crates/move-model-2/src/source_kind.rs
- external-crates/move/crates/move-model-2/src/source_model.rs
- Replaces the const generic based markers with trait based ones. 
- The benefit of which is that we can "upcast" into `Model<AnyKind>` so that functions can return either. Today you cannot write `if cond { Model::from_source(...) } else { Model::from_compiled(...) }` and that can be potentially limiting 
- Originally I tried using `dyn SourceKind` but this still requires manual upcasting unless [CoerceUnsized](https://doc.rust-lang.org/std/ops/trait.CoerceUnsized.html) is stabilized. Since it requires manual upcasting, I instead opted for a "parent" type of `AnyKind`. 
- The additional benefit of not using `dyn SourceKind` is that I can have an associated type for the `FormSource` annotations, this ensures that they are correctly instantiated always
- 👀 
---
Check each box that your …
> [move-model-2] Replace const generics with trait-based markers 

- Cargo.toml
- crates/sui-core/Cargo.toml
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/typed-store-derive/src/lib.rs
- crates/typed-store/src/lib.rs
- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/tidehunter_util.rs
- crates/typed-store/tests/macro_tests.rs
Notes:
* added TH support to DBMapUtils macros
* added rm_prefix support to TH's column family
* alternative AuthorityPerpetualTables::open implementation for TH
* to enable TH locally:
- uncomment `//#[tidehunter]` at the top of the `AuthorityPerpetualTables` struct definition
- enable the `tide_hunter` feature for `sui-core` in `Cargo.toml`
---
> [typed store] add tidehunter option to DBMapUtils macros

- crates/sui-keys/src/keystore.rs
- crates/sui-keys/tests/tests.rs
- crates/sui/src/client_commands.rs
- crates/sui/tests/cli_tests.rs
Remove an existing address by its alias or hexadecimal string
Usage: `sui client remove-address  <ALIAS_OR_ADDRESS>`
Closes #21845
---
> [CLI] New Command to remove an address in sui client

- Cargo.lock
- crates/telemetry-subscribers/Cargo.toml
- crates/telemetry-subscribers/src/bin/import-trace.rs
This PR uses `try_get_u64_varint` function instead of the `get_u64_varint` function which was deprecated. Sometimes clippy complains so decided to fix it.
---
> [telemetry] Fix varint deprecation warning

- crates/sui-core/src/authority/authority_store_tables.rs
This is the correct key size in this table, otherwise it fails unit tests that uses this table
> Use 32 bytes key for event_2 table with tidehunter

- crates/sui-analytics-indexer/src/analytics_metrics.rs
- crates/sui-analytics-indexer/src/analytics_processor.rs
- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/writers/csv_writer.rs
- crates/sui-analytics-indexer/src/writers/mod.rs
- crates/sui-analytics-indexer/src/writers/parquet_writer.rs
This PR makes two significant improvements:
1. It adds a row counter to the parquet writer that allows us to flush after "N" rows have been buffered in memory. Previously we were going back checkpoint count which could be unpredictable. Large checkpoints were blowing up these buffers and causing use to hit an internal buffer size limit in arrow. We still only try to flush at the checkpoint interval, which should be fine so long as a single checkpoint fits in memory.
```
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-array-54.2.0/src/builder/generic_bytes_builder.rs:86:57:
byte array offset overflow
stack backtrace:
2025-04-21T17:42:19.534828Z ERROR telemetry_subscribers: panicked at …
```
> Rewrite parquet writer to use less memory

- crates/sui-analytics-indexer/src/analytics_metrics.rs
- crates/sui-analytics-indexer/src/analytics_processor.rs
- crates/sui-analytics-indexer/src/handlers/df_handler.rs
- crates/sui-analytics-indexer/src/handlers/event_handler.rs
- crates/sui-analytics-indexer/src/handlers/object_handler.rs
- crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
- crates/sui-analytics-indexer/src/lib.rs
- crates/sui-analytics-indexer/src/package_store.rs
- crates/sui-analytics-indexer/src/writers/csv_writer.rs
- crates/sui-analytics-indexer/src/writers/mod.rs
- crates/sui-analytics-indexer/src/writers/parquet_writer.rs
This change ensures all pipelines run using the same LRU package cache instance. Previously, all of the pipelines would have their own instance which bloats memory use.
It's already running in the backfill stack
> Encapsulate and share package cache

- crates/sui-core/src/authority.rs
- crates/sui-json-rpc/src/coin_api.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-storage/src/http_key_value_store.rs
- crates/sui-storage/src/key_value_store.rs
- crates/sui-storage/tests/key_value_tests.rs
Prefetch objects needed for balance change calculations as well as
leveraging multi_get_objects in order to parallelize the fetching of
objects.
---
> jsonrpc: prefetch objects for balance change calculations 

- Cargo.lock
- crates/typed-store/Cargo.toml
- crates/typed-store/src/rocks/mod.rs
The previous attempt triggered write stalling and stopping on archival full nodes. Since write stalling have been disabled on full node indexes and perpetual tables (via `disable_write_throttling()`), it should no longer be an issue. 
Rollout to full nodes
---
> Upgrade rocksdb to 0.22

- consensus/core/src/authority_service.rs
- consensus/core/src/broadcaster.rs
- consensus/core/src/commit_syncer.rs
- consensus/core/src/network/anemo_network.rs
- consensus/core/src/network/mod.rs
- consensus/core/src/network/test_network.rs
- consensus/core/src/network/tonic_network.rs
- consensus/core/src/round_prober.rs
- consensus/core/src/subscriber.rs
- consensus/core/src/synchronizer.rs
This mode is similar to the mode before `consensus_batched_block_sync` is added. The difference is that missing ancestor blocks are deduped and selected randomly, to reduce duplicated blocks fetched.
CI
PT
---
> [consensus] add breadth first block sync

- consensus/core/src/authority_service.rs
> [consensus] avoid holding DagState read lock for too long

- crates/sui-cluster-test/src/cluster.rs
- crates/sui-faucet/src/server.rs
- crates/sui-oracle/src/main.rs
- crates/sui-sdk/examples/utils.rs
- crates/sui-sdk/src/wallet_context.rs
- crates/sui/src/client_commands.rs
- crates/sui/src/sui_commands.rs
- crates/sui/src/validator_commands.rs
- crates/sui/tests/shell_tests/env_overrides/basic_override.sh
- crates/sui/tests/shell_tests/env_overrides/config.yaml
- crates/sui/tests/snapshots/shell_tests__env_overrides__basic_override.sh.snap
- crates/test-cluster/src/lib.rs
This enables the ability for `move` and `client` subcommands to accept a `--client.env <network-name>` flag to use the specified `network-name` for the single command (overriding the current active-env).
`network-name` must be a valid environment in the current config in order to be used. E.g., a raw RPC URL for the `--client.env` name is invalid.
Added test to make sure the `--client.env` flag properly overrides the environment. The best way I could find to test this in a repeatable/sane way was with `envs` and `active-env` calls. 
--- …
> [sui][cli] Add ability to specify network in command

- docs/content/concepts/cryptography/passkeys.mdx
- docs/content/concepts/sui-architecture/transaction-lifecycle.mdx
- docs/content/standards/deepbookv3-sdk/orders.mdx
- docs/content/standards/deepbookv3-sdk/pools.mdx
This PR fixes `tip` and `warning` formatting to render correctly. Added new, improved `tip` for how the SDK handles decimals. The previous message was confusing and did not explain how the decimals should be adjusted. 
I build it locally and tested the formatting. 
---
> [docs] Fix formatting and improve tip message 

- crates/sui-benchmark/src/lib.rs
- crates/sui-benchmark/src/workloads/slow.rs
slow.rs workload transactions shouldn't abort, but they can be cancelled
> Fix debug assert

- Cargo.lock
- Cargo.toml
Patch to fix:
https://github.com/async-graphql/async-graphql/issues/1703,
Cherry-picking the fix from:
https://github.com/async-graphql/async-graphql/pull/1705
Until it is merged, at which point we can upgrade our dependency.
Run the GraphQL service locally, and confirm that its GraphiQL IDE works now.
---
> pick(#22053) async-graphql: Patch to upgrade to React 18

- docker/sui-node-deterministic/Dockerfile
Update deterministic sui-node to use latest stagex release, using clang and lld to link the final binary.
This helps resolve an issue with `RUST_BACKTRACE=1`, where gcc would link the system's libunwind, resulting in an error when retrieving the call stack.
Requesting help from @jnaulty to get this run on testnet for a bit.
After building the container, load and run with a set of commands known to cause a crash, with `RUST_BACKTRACE=1`.
```sh
bash ./docker/sui-node-deterministic/build.sh
env -C build/oci/sui-node tar c . | docker load
docker run -e RUST_BACKTRACE=1 sui-node /opt/sui/bin/sui-node --config-path /validator.yaml
```
--- …
> update stagex to 2025.04.1, fix linker errors

- external-crates/move/crates/move-stdlib-natives/src/vector.rs
- external-crates/move/crates/move-vm-runtime/src/interpreter.rs
- external-crates/move/crates/move-vm-types/src/values/value_tests.rs
- external-crates/move/crates/move-vm-types/src/values/values_impl.rs
- sui-execution/latest/sui-move-natives/src/config.rs
- sui-execution/latest/sui-move-natives/src/crypto/nitro_attestation.rs
- sui-execution/latest/sui-move-natives/src/event.rs
- sui-execution/latest/sui-move-natives/src/test_scenario.rs
- Remove the need for a `Type` in `Vector::pack` by adding a new `VectorSpecialization` enum
- Removed `Value::vector_for_testing_only`
- Updated tests
---
> [move-values] Clean up vector pack

- external-crates/move/crates/move-analyzer/trace-adapter/package-lock.json
- external-crates/move/crates/move-analyzer/trace-adapter/package.json
- external-crates/move/crates/move-analyzer/trace-adapter/src/trace_utils.ts
- external-crates/move/crates/move-analyzer/trace-debug/package-lock.json
- external-crates/move/crates/move-analyzer/trace-debug/package.json
- external-crates/move/crates/move-analyzer/trace-debug/src/extension.ts
As it appears, mongodb's zstd library does not have bindings on some platforms (e.g. [this](https://github.com/MystenLabs/sui/issues/22033) bug report)
Tested that it works on Linux (when it previously did not)
> [trace-view] Replaced platform-dependent zstd library with platform-independent one

- docker/sui-indexer-alt-graphql/Dockerfile
- docker/sui-indexer-alt-graphql/build.sh
Create Dockerfile for sui-indexer-alt-graphql
---
> indexer-alt-graphql dockerfile

- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/data_store.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/mod.rs
Pulls the `SuiDataStore` into a separate module, and cleans up formatting of `use`s. 
No semantic changes.
CI
> [1/n][object runtime type tags][cleanup-only] Pull `SuiDataStore` into a separate module

- .github/workflows/simulator-nightly.yml
Moves the proxy server to teleport cloud and updates to newest teleport-actions/ auth
---
> Update simtest reference to new teleport instance

- crates/sui-json-rpc-types/src/unit_tests/rpc_types_tests.rs
PR landed that merged cleanly, but broke the build as it was using an old version of `SuiMoveNormalizedStruct`. This updates the usage to unbreak the build.
CI
> Update test to unbreak build

- crates/sui-json-rpc-types/src/sui_move.rs
- crates/sui-json-rpc-types/src/unit_tests/rpc_types_tests.rs
- crates/sui-json-rpc-types/src/unit_tests/snapshots/sui_json_rpc_types__rpc_types_tests__move_type_serde.snap
- crates/sui-open-rpc/spec/openrpc.json
A different way of returning variants in order
Updated existing test that was added in the PR below this one.
> [json-rpc-types] Return variants in declaration order

- crates/sui-adapter-transactional-tests/tests/upgrade/type_resolution.move
- crates/sui-adapter-transactional-tests/tests/upgrade/type_resolution.snap
- crates/sui-adapter-transactional-tests/tests/upgrade/type_resolution_v82.move
- crates/sui-adapter-transactional-tests/tests/upgrade/type_resolution_v82.snap
- crates/sui-graphql-rpc/src/types/move_type.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_83.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_83.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_83.snap
- crates/sui-replay-2/src/replay_txn.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-types/src/type_input.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
When converting `TypeInput`s to `TypeTag`s in the adapter also remap all IDs to be defining-id based. This should not cause any discernible change in behavior outside of error cases.
This adds the invariant that all typetags will be defining ID based from the adapter down into (and including) the object runtime, with the exception of where we explicitly want runtime IDs for typename in natives.
CI + new tests
---
> [2/n][object runtime type tags][adapter-only] Normalize to defining ID when converting from `TypeInput` to `TypeTag`

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
This gives us an easy way to monitor utilization without creating high cardinality metrics.
> Report utilization metrics by hash(obj_id) % 16

- crates/sui-core/src/execution_cache.rs
- crates/sui-core/src/execution_cache/unit_tests/notify_read_input_objects_tests.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
This PR adds an object notify in the writeback cache. It will allow us to replace transaction manager.
A transaction to be scheduled will call the notify wait to wait for input object to become available.
The notify wait function is very similar to `multi_input_objects_available` in execution cache.
Added tests
---
> Add input object notify in the writeback cache

- docs/content/guides/operator/snapshots.mdx
Docs were missing a little piece.
---
> docs: fix aws s3 cp command

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_83.snap
> Enable ExecutionTimeEstimate mode for congestion control on mainnet

- docs/README.md
Replaces the outdated URL `https://docs.sui.io/contribute/code-of-conduct` with the live URL `https://docs.sui.io/code-of-conduct` so contributors can access the Code of Conduct without hitting a 404.
> Fix broken “Code of Conduct” link in docs

- crates/sui-analytics-indexer/src/analytics_processor.rs
- crates/sui-analytics-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-analytics-indexer/src/handlers/df_handler.rs
- crates/sui-analytics-indexer/src/handlers/event_handler.rs
- crates/sui-analytics-indexer/src/handlers/mod.rs
- crates/sui-analytics-indexer/src/handlers/move_call_handler.rs
- crates/sui-analytics-indexer/src/handlers/object_handler.rs
- crates/sui-analytics-indexer/src/handlers/package_handler.rs
- crates/sui-analytics-indexer/src/handlers/transaction_bcs_handler.rs
- crates/sui-analytics-indexer/src/handlers/transaction_handler.rs
- crates/sui-analytics-indexer/src/handlers/transaction_objects_handler.rs
- crates/sui-analytics-indexer/src/handlers/wrapped_object_handler.rs
- crates/sui-analytics-indexer/src/writers/csv_writer.rs
- crates/sui-analytics-indexer/src/writers/mod.rs
- crates/sui-analytics-indexer/src/writers/parquet_writer.rs
We were writing to the parquet file from an async block, which can block the tokio threads for a long time and cause issues with throughput/stalled pipelines. This moves the blocking write to a tokio blocking task.
> Fix writer blocking tokio worker threads

- crates/sui-adapter-transactional-tests/tests/init/create_object.move
- crates/sui-adapter-transactional-tests/tests/init/create_object.snap
- crates/sui-adapter-transactional-tests/tests/init/emit_event.move
- crates/sui-adapter-transactional-tests/tests/init/emit_event.snap
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_83.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_83.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_83.snap
- external-crates/move/crates/move-vm-runtime/src/native_functions.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/data_store.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/linkage_view.rs
- sui-execution/latest/sui-move-natives/src/config.rs
- sui-execution/latest/sui-move-natives/src/dynamic_field.rs
- sui-execution/latest/sui-move-natives/src/event.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
- sui-execution/latest/sui-move-natives/src/test_scenario.rs
- sui-execution/latest/sui-move-natives/src/transfer.rs
This updates the object runtime to only hold `TypeTag`s (or `MoveObjecType`s where appropriate) instead of VM runtime `Type`s. 
It's generally a pretty straightforward change, however there are a couple places worth calling out specifically and I've done so in-line. 
CI + adding new tests to make sure type tags coming from the object runtime are correctly resolved in newly-published packages.
---
> [3/n][object runtime type tags] Add type tags to object runtime update adapter to handle them

- external-crates/move/crates/move-package-alt/TODO.md
- external-crates/move/crates/move-package-alt/src/dependency/dependency_set.rs
- external-crates/move/crates/move-package-alt/src/dependency/external.rs
- external-crates/move/crates/move-package-alt/src/dependency/git.rs
- external-crates/move/crates/move-package-alt/src/dependency/local.rs
- external-crates/move/crates/move-package-alt/src/dependency/mod.rs
- external-crates/move/crates/move-package-alt/src/jsonrpc/client.rs
- external-crates/move/crates/move-package-alt/src/package/manifest.rs
- external-crates/move/crates/move-package-alt/src/package/mod.rs
mdgeorge review of package-alt, adding TODOs
---
> @mdgeorge4153 review of package-alt

- sui-execution/latest/sui-adapter/src/data_store/cached_data_store.rs
- sui-execution/latest/sui-adapter/src/data_store/linkage_view.rs
- sui-execution/latest/sui-adapter/src/data_store/mod.rs
- sui-execution/latest/sui-adapter/src/data_store/sui_data_store.rs
- sui-execution/latest/sui-adapter/src/lib.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/execution.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/mod.rs
- sui-execution/latest/sui-adapter/src/type_layout_resolver.rs
Now that we have the `PackageStore` abstraction in the adapter layer, this adds in a very simple caching layer for `MovePackage`s. Currently the cache size is bounded at 200 packages, after that we drop the cache and reload (we could also go for an LRU if we wanted, but I think that will just be more complexity than is most likely needed here). The cache is only held for the lifetime of the transaction. 
This also does a bit of reorganization around the data store, and related "store" functionality into its own directory under the programmable transactions. 
Next up: will work on refactoring `LinkageView`
CI
> [sui-adapter] Add basic package cache

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-tool/src/db_tool/db_dump.rs
removes deprecated tables from AuthorityEpochTables
---
> AuthorityEpochTables: remove deprecated tables

- Cargo.lock
- crates/sui-kvstore/Cargo.toml
- crates/sui-kvstore/src/lib.rs
- crates/sui-kvstore/src/main.rs
adds ability to do point lookups with read only access to kv store binary
---
> [kv store] add binary subcommand to fetch entries from tables

- docs/content/guides/developer/app-examples/oracle.mdx
Just fixed the URL pointing to the Switchboard oracle's guide for Sui.
> Update oracle.mdx - broken URL to Switchboard oracle

- crates/sui-indexer-alt-framework/src/ingestion/broadcaster.rs
- crates/sui-indexer-alt-framework/src/ingestion/client.rs
- crates/sui-indexer-alt-framework/src/ingestion/local_client.rs
- crates/sui-indexer-alt-framework/src/ingestion/mod.rs
- crates/sui-indexer-alt-framework/src/ingestion/remote_client.rs
- crates/sui-indexer-alt/src/bootstrap.rs
Previously, the indexing framework would only retry a subset of remote checkpoint fetching errors, and would wind down the indexer in response to others.
This change makes it so that all errors (except "not found" errors) are treated as transient and are retried with an exponential back-off. It also simplifies the logic around cancellation, pulling it out from the ingestion client, and introducing an outer, wrapping `select!` statement that checks for cancellation instead.
Updtaed tests:
```
sui$ cargo nextest run         \
-p sui-indexer-alt-framework \
-p sui-indexer-alt           \
-p sui-indexer-alt-e2e-tests
```
---
For each box you select, include information after …
> indexer-alt: retry all checkpoint fetch errors

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/consensus_tx_status_cache.rs
- crates/sui-core/src/authority_client.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/consensus_types/consensus_output_api.rs
- crates/sui-core/src/lib.rs
- crates/sui-core/src/test_authority_clients.rs
- crates/sui-core/src/unit_tests/wait_for_effects_tests.rs
- crates/sui-core/src/validator_tx_finalizer.rs
- crates/sui-core/src/wait_for_effects_request.rs
- crates/sui-network/build.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/messages_consensus.rs
- crates/sui-types/src/messages_grpc.rs
This PR implements the wait_for_effects gRPC API on validators to support the second query for mysticeti-fastpath, that is waiting for effects on a validator.
The implementation matches the design in https://www.notion.so/mystenlabs/Transaction-Driver-Mysticeti-FPC-client-1356d9dcb4e980559ee1cb5331fbe439?pvs=4#1de6d9dcb4e980238247e5f9553d934f.
A status cache is introduced to remember the current consensus status of for each consensus position (instead of transaction digest). The cache is GCed periodically. When waiting for effects, we first acquire the first status update to ensure that it is not rejected by consensus, then we wait for effects while making sure it is not eventually rejected post-commit.
In the new request, use a single boolean `include_details` to indicate whether we want …
> [mysticeti-fp] Implement wait_for_effects grpc API

- crates/sui/src/client_commands.rs
This PP adds `-c` as a short flag for `--upgrade-capability`.
---
> [cli] Allow upgrade-capability to be passed as `-c` short flag

- Cargo.lock
- crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
- crates/sui-json-rpc-types/src/sui_object.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_84.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_84.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_84.snap
- crates/sui-types/Cargo.toml
- crates/sui-types/src/object.rs
- crates/sui-types/src/sui_system_state/mod.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/v2/sui-adapter/src/programmable_transactions/context.rs
Allows objects created/mutated by system transactions to not be bounded by normal limits and brings it in-line with the rest of the way we treat system transactions and limit interactions.
CI
---
> Remove object size bounds on system transactions

- crates/sui-benchmark/tests/simtest.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/authority/shared_object_congestion_tracker.rs
- crates/sui-core/src/epoch/epoch_metrics.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_83.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_84.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_79.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_80.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_81.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_82.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_83.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_84.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_78.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_79.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_80.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_81.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_82.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_83.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_84.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-types/src/transaction.rs
Cherry-pick #22167 into 1.49
---
> Add limit to number of stored execution time observations (#22167)

- Cargo.lock
- crates/sui-indexer-alt/src/handlers/coin_balance_buckets.rs
- crates/sui-json-rpc-types/src/sui_object.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_84.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_84.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_84.snap
- crates/sui-types/Cargo.toml
- crates/sui-types/src/object.rs
- crates/sui-types/src/sui_system_state/mod.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/v2/sui-adapter/src/programmable_transactions/context.rs
Allows objects created/mutated by system transactions to not be bounded by normal limits and brings it in-line with the rest of the way we treat system transactions and limit interactions.
CI
---
> Remove object size bounds on system transactions (#22173)

- crates/sui-types/src/object.rs
- crates/sui-types/src/sui_system_state/mod.rs
Forgot to add in the protocol gating when switching from a larger bound to a feature flag. This adds in the proper protocol gating.
CI
> Protocol gate unbounded system objects

- crates/sui-types/src/object.rs
- crates/sui-types/src/sui_system_state/mod.rs
Forgot to add in the protocol gating when switching from a larger bound to a feature flag. This adds in the proper protocol gating. This is a reverse cherry pick so this has already landed in the release branch.
CI
> Protocol gate unbounded system objects (#22187)

- crates/sui-core/src/consensus_handler.rs
Before post-commit finalization is implemented, there can be discrepancies in transaction status between block handler vs commit handler.
CI
---
> [fastpath] disable setting transactions status in block handler

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-types/src/traffic_control.rs
In order for the traffic controller to be enabled in any form, validators must add a `policy-config:` block to their nodes, copying the examples from: https://gist.github.com/williampsmith/4de166d8be9bb9e183594d631452fb19
I can't see good reason not to turn traffic controller on in dry-run mode by default, since it's essentially what we're asking operators to do in the above guide. The configs I used in `default_dos_protection_policy()` are just cut and paste from that gist (I'm not certain those are the best defaults, but seems that Will thought so)
I've tested these changes locally.
we currently have 37 mainnet validators with some type of `PolicyConfig` enabled
and 56 testnet validators:
---
Check each box that your changes affect. If none of the boxes relate to your changes, release …
> [TrafficControl] Enable DOS protection by default (dryRun) 

- consensus/core/src/authority_node.rs
- consensus/simtests/src/tests/simtests.rs
- crates/mysten-metrics/src/lib.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-node/src/lib.rs
- crates/typed-store-derive/src/lib.rs
- crates/typed-store/src/metrics.rs
- crates/typed-store/src/tidehunter_util.rs
- crates/typed-store/tests/macro_tests.rs
adds support for AuthorityEpochTables
---
> [tidehunter] add support for AuthorityEpochTables

- Cargo.lock
- Cargo.toml
This bumps the patch for `tonic` to `v0.13.1` as folks cannot do `cargo install --git ....`.
Should close #22198 and #22162
---
> [chore] Fix toml tonic

- crates/sui-indexer-alt-framework-store-traits/src/lib.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
- crates/sui-pg-db/src/store.rs
Previously:
wait_for was an i64 field on PrunerWatermark (since PrunerWatermark represented the "stored" datatype)
The fn wait_for on PrunerWatermark checked self.wait_for > 0 then Duration::from_millis, which works since self.wait_for is still an i64, and thus can represent negative values
https://github.com/MystenLabs/sui/pull/21537/files#diff-e91aff7d4e8968395eb4a363dc2f6b5affae2cd76042e5ec1029661c80c1522b
Currently:
fn pruner_watermark of the Connection trait has the same query "CAST({BigInt} + 1000 * EXTRACT(EPOCH FROM pruner_timestamp - NOW()) AS BIGINT)", but now we immediately set it as a field on PrunerWatermark - as u64, so that causes the underflow, turning potentially negative numbers into a massive positive one
Later, the check self.wait_for_ms > 0 will return true, and …
> Fix potential underflow on `PrunerWatermark.wait_for`

- crates/sui-indexer-alt-framework/src/pg_store.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
- crates/sui-indexer-alt-framework/src/store.rs
Previously:
wait_for was an i64 field on PrunerWatermark (since PrunerWatermark represented the "stored" datatype)
The fn wait_for on PrunerWatermark checked self.wait_for > 0 then Duration::from_millis, which works since self.wait_for is still an i64, and thus can represent negative values
https://github.com/MystenLabs/sui/pull/21537/files#diff-e91aff7d4e8968395eb4a363dc2f6b5affae2cd76042e5ec1029661c80c1522b
Currently:
fn pruner_watermark of the Connection trait has the same query "CAST({BigInt} + 1000 * EXTRACT(EPOCH FROM pruner_timestamp - NOW()) AS BIGINT)", but now we immediately set it as a field on PrunerWatermark - as u64, so that causes the underflow, turning potentially negative numbers into a massive positive one
Later, the check self.wait_for_ms > 0 will return true, and …
> Fix potential underflow on `PrunerWatermark.wait_for` (#22171)

- Cargo.toml
- crates/sui-core/Cargo.toml
- crates/sui-core/build.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/typed-store/Cargo.toml
- crates/typed-store/build.rs
- crates/typed-store/src/lib.rs
- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/tests/macro_tests.rs
This means that even when cargo is run with `--all-features` it won't enable tidehunter by default. This also allows for more concise check for `#[cfg(tidehunter)]` in code.
With this PR to build with tidehunter one needs to run the following
```
USE_TIDEHUNTER=1 cargo --features typed-store/tidehunter <command>
```
---
> Enable tidehunter with cfg rather then feature

- Cargo.lock
- crates/sui-graphql-e2e-tests/tests/stable/objects/display.snap
- crates/sui-graphql-rpc/Cargo.toml
- crates/sui-graphql-rpc/src/types/display.rs
- crates/sui-graphql-rpc/src/types/object.rs
- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/indexer_reader.rs
- crates/sui-json-rpc/Cargo.toml
- crates/sui-json-rpc/src/read_api.rs
Remove support for Display in `sui-indexer`'s JSON-RPC implementation (which is not in use), and use `sui_display::v1` to implement Display everywhere else (JSON-RPC on fullnodes and legacy GraphQL) so we can get rid of the legacy implementation.
This is mostly a behaviour preserving change and clean-up, but it reduces restrictions around running Display on very large objects (too large to deserialize whole), replacing it with a restriction on the overall Display size.
--- …
> display: replace legacy Display impl with sui-display

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
- crates/sui-core/src/test_authority_clients.rs
- crates/sui-core/src/transaction_outputs.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/transfer_to_object_tests.rs
- crates/sui-single-node-benchmark/src/single_node.rs
- crates/sui-transactional-test-runner/src/lib.rs
This is a non-functional change that moves around the authority code during certificate execution.
The goal is to make sure that prepare_certificate function returns a TransactionOutput. This will allow us to skip committing the result for mysticeti fastpath certificates.
---
> Restructure authority execution code

- crates/sui-core/src/authority.rs
Otherwise there is potential risk of epoch mismatch
CI
---
> process_object_index should use the same epoch store as origin

- crates/sui/src/client_ptb/ptb.rs
A previous PR #22272 added support for setting the `sender` in a transaction. This PR adds this new argument to the ptb help menu. 
---
> [cli] Add `sender` to `ptb` help menu

- crates/sui-rpc-api/src/proto/rpc/v2beta/checkpoint.rs
- crates/sui-rpc-api/src/proto/rpc/v2beta/effects.rs
- crates/sui-rpc-api/src/proto/rpc/v2beta/events.rs
- crates/sui-rpc-api/src/proto/rpc/v2beta/object.rs
- crates/sui-rpc-api/src/proto/rpc/v2beta/transaction.rs
Based on feedback received, populate the Bcs.name field for core types.
---
> proto: populate Bcs.name field for core types

- crates/sui-core/src/traffic_controller/mod.rs
This metric was bumping in such a way that it would give the false impression that we are blocking requests when in dry run mode. 
👀 
---
> [Traffic Control] Fix blocked metric

- Cargo.lock
- external-crates/move/Cargo.lock
- external-crates/move/crates/bytecode-verifier-tests/src/unit_tests/control_flow_graph_tests.rs
- external-crates/move/crates/move-abstract-interpreter/Cargo.toml
- external-crates/move/crates/move-abstract-interpreter/src/absint.rs
- external-crates/move/crates/move-abstract-interpreter/src/control_flow_graph.rs
- external-crates/move/crates/move-abstract-interpreter/src/lib.rs
- external-crates/move/crates/move-abstract-interpreter/src/unit_tests/mod.rs
- external-crates/move/crates/move-binary-format/Cargo.toml
- external-crates/move/crates/move-binary-format/src/file_format.rs
- external-crates/move/crates/move-bytecode-verifier/src/absint.rs
- external-crates/move/crates/move-bytecode-verifier/src/code_unit_verifier.rs
- external-crates/move/crates/move-bytecode-verifier/src/control_flow.rs
- external-crates/move/crates/move-bytecode-verifier/src/lib.rs
- external-crates/move/crates/move-bytecode-verifier/src/locals_safety/abstract_state.rs
- external-crates/move/crates/move-bytecode-verifier/src/locals_safety/mod.rs
- external-crates/move/crates/move-bytecode-verifier/src/loop_summary.rs
- external-crates/move/crates/move-bytecode-verifier/src/reference_safety/abstract_state.rs
- external-crates/move/crates/move-bytecode-verifier/src/reference_safety/mod.rs
- external-crates/move/crates/move-bytecode-verifier/src/stack_usage_verifier.rs
- external-crates/move/crates/move-bytecode-verifier/src/type_safety.rs
- external-crates/move/crates/move-coverage/Cargo.toml
- external-crates/move/crates/move-coverage/src/lcov.rs
- external-crates/move/crates/move-coverage/src/summary.rs
- external-crates/move/crates/move-ir-compiler/src/unit_tests/cfg_tests.rs
- sui-execution/latest/sui-verifier/Cargo.toml
- sui-execution/latest/sui-verifier/src/id_leak_verifier.rs
- Makes the abstract interpreter more general and removes the dependency on the file format
- Added the necessary wrapper traits in the verifier 
- Stacked on #21573
- This will let us use the same infrastructure in the move-model-2 and move-compiler
- Non functional
---
> [move-abstract-interpreter] Make move-abstract-interpreter more general

- scripts/simtest/cargo-simtest
I've noticed that cargo-simtest will sometimes leave behind a mutated Cargo.toml file when it is killed via SIGTERM. This change ensures that (barring SIGKILL being used, the Cargo.toml will be cleaned up). I've also taken some liberties and introduced some minor changes to the BASH syntax, etc...
CI Pipeline.
> ensure that cargo-simtest cleans up the Cargo.toml changes

- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/consensus_manager/mod.rs
- crates/sui-core/src/consensus_manager/mysticeti_manager.rs
- crates/sui-core/src/unit_tests/mysticeti_manager_tests.rs
- crates/sui-node/src/lib.rs
Checkpoint builder is the only component that needs to wait for consensus to finish replay. It seems better to wait in checkpoint builder instead of during consensus startup.
This also improves the parallelism between starting consensus and other components. Currently, starting up other components are blocked on consensus starting, without a timeout.
CI
---
> Wait for replaying consensus commits before checkpoint builder starts

- external-crates/move/crates/move-vm-runtime/src/loader.rs
- external-crates/move/crates/move-vm-runtime/src/runtime.rs
Add a defining-id cache in the `ModuleCache` to allow for cached type resolution for typetags. This will then be used in the PR above this adding type tags to the object runtime.
CI + CI/sandbox tests
> [move][vm] Add defining-id cache and cached-type lookup

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- Share upward observations only for overutilized objects
- Share downward observations only for indebted objects
added unit test
---
> Share new execution time observations unidirectionally

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_test_utils.rs
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/execution_cache.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
- crates/sui-core/src/execution_driver.rs
- crates/sui-core/src/execution_scheduler/execution_scheduler_impl.rs
- crates/sui-core/src/execution_scheduler/mod.rs
- crates/sui-core/src/execution_scheduler/transaction_manager.rs
- crates/sui-core/src/lib.rs
- crates/sui-core/src/transaction_outputs.rs
- crates/sui-core/src/unit_tests/consensus_tests.rs
- crates/sui-core/src/unit_tests/mysticeti_fastpath_execution_tests.rs
- crates/sui-core/src/unit_tests/wait_for_effects_tests.rs
- crates/sui-core/src/validator_tx_finalizer.rs
- crates/sui-node/src/lib.rs
- crates/sui-single-node-benchmark/src/single_node.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Temporarily put fastpath execution results in a separate in the writeback cache.
These results will be flushed to the normal dirty cache if it ever gets executed from non fastpath.
Added unittests.
---
> Buffer mysticeti fastpath execution results

- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-analyzer/src/analysis/parsing_analysis.rs
This fixes a problem with auto-imports being tagged on the literally latest existing `use` statement in the module, even if this statement is interleaved with other module members and higher/top-level `use` statement block exists (which is where the new `use` statement should be placed)
Tested manually that the new `use` statement is tagged onto the first `use` statement block in the module
> [move-ide] Auto-import location fix

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/epoch/epoch_metrics.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_85.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_85.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_85.snap
- [Cherry pick] Tweak some knobs for execution time estimation (#22331)
- [Cherry pick] Share new execution time observations unidirectionally (#22338)
- [Cherry-pick] Increase utilization target and burst limit
---
> congestion control cherry picks

- crates/sui-core/src/traffic_controller/metrics.rs
- crates/sui-core/src/traffic_controller/mod.rs
add a metric so we can discern if any validators have dry run disabled
Fine to only update the metric in `init()` right now. I'll update https://github.com/MystenLabs/sui/pull/20887 to keep the metric correctly synced
---
> [traffic controller] show dry run status via metric

- crates/sui-transactional-test-runner/src/test_adapter.rs
- external-crates/move/crates/language-benchmarks/src/move_vm.rs
- external-crates/move/crates/move-compiler/tests/move_check_testsuite.rs
- external-crates/move/crates/move-stackless-bytecode/tests/testsuite.rs
- external-crates/move/crates/move-stdlib/src/lib.rs
- external-crates/move/crates/move-stdlib/src/main.rs
- external-crates/move/crates/move-stdlib/src/tests.rs
- external-crates/move/crates/move-transactional-test-runner/src/vm_test_harness.rs
- external-crates/move/crates/move-unit-test/tests/move_unit_test_testsuite.rs
- external-crates/move/crates/move-unit-test/tests/test_deps.rs
- external-crates/move/crates/move-vm-integration-tests/src/compiler.rs
- external-crates/move/crates/test-generation/src/lib.rs
- We don't need to repeat all of these names. That is `move_stdlib::move_stdlib_*` is a bit silly.
- clippy
---
> [chore] Small cleanup of naming of rust functions

- external-crates/move/crates/move-stdlib-natives/src/bcs.rs
- external-crates/move/crates/move-vm-runtime/src/runtime.rs
- external-crates/move/crates/move-vm-types/Cargo.toml
- external-crates/move/crates/move-vm-types/src/values/mod.rs
- external-crates/move/crates/move-vm-types/src/values/value_prop_tests.rs
- external-crates/move/crates/move-vm-types/src/values/value_tests.rs
- external-crates/move/crates/move-vm-types/src/values/values_impl.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/values.rs
- sui-execution/latest/sui-move-natives/src/dynamic_field.rs
- sui-execution/latest/sui-move-natives/src/test_scenario.rs
We don't need a type layout when serializing a Move value in order to produce valid serialized bytes.
This adds this function, renames the existing `simple_serialize` to `typed_serialize`, and updates the usage of the the `typed_serialize` function in the new static ptbs to use the serialization function that does not require the type layout.
Added an additional test for one interesting case, re-enabled values-impl proptests and in this we ensure that the serialized bytes for values are the same whether using `typed_serialize` or `serialize`.
> [static-ptbs] Add ability to serialize values without needing layouts

- crates/sui-core/src/authority/consensus_tx_status_cache.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/messages_consensus.rs
Return early from `set_transaction_status()` when a status update to `FastpathCertified` is ignored, instead of continuing to notify.
Also, remove per-transaction tracking in status cache. And use `u32` for Round in Sui unless for legacy compatibility. Consensus already uses u32 for Round.
CI
---
> [fastpath] do not notify when there is no transaction status update

- crates/sui-move-build/src/lib.rs
- crates/sui/src/client_commands.rs
- crates/sui/src/sui_commands.rs
- crates/sui/tests/cli_tests.rs
This PR fixes missing a check on conflicting addresses after compiling when publishing or when calling `build --dump-bytecode-as-base64`.
---
> [cli] Fix missing check on conflicting addresses after compiling

- external-crates/move/crates/move-coverage/src/source_coverage.rs
Expanded macros pull in source locations from other files. This can lead to errors when computing source coverage (spans that refer to locations outside of the current file). 
When computing the coverage map for a file, we remove any locations not located within that file (i.e., locations from macro expansion). Sadly this means that we lose some level of coverage information about the macro call, but hopefully in the future with some nicer locations we can improve this. But for now, this at least stops it from erroring out completely. 
CI + tested it on a local repro.
> [move][easy] Filter out macro-locations when computing source coverage

- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/balance_read.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/mod.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/naive_scheduler.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/scheduler.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/tests.rs
- crates/sui-core/src/execution_scheduler/mod.rs
This PR implements a naive balance withdraw scheduler, that always wait for the previous accumulator version to be settled before scheduling the next set of withdraws.
It is meant to serve a few purposes:
1. Set up the interface so we can all see how the system should interact with it.
2. Allow us to make progress in testing the rest of the system
3. We can use this naive implementation to test a more optimistic implementation.
The scheduler exposes 2 APIs:
1. schedule_withdraws. This will be called from ConsensusHandler, on every batch of consensus commits, providing the list of withdraws as well as the version of the accumulator root object they will be reading from. This will immediately return a list of notify receivers, which will be carried into the ExecutionScheduler. It will use …
> Implement naive balance withdraw scheduler

- Cargo.lock
- crates/sui-protocol-config/Cargo.toml
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_86.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_86.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_86.snap
- external-crates/move/crates/move-binary-format/src/deserializer.rs
- external-crates/move/crates/move-binary-format/src/file_format_common.rs
- external-crates/move/crates/move-binary-format/src/proptest_types/functions.rs
- external-crates/move/crates/move-binary-format/src/serializer.rs
- external-crates/move/crates/move-core-types/src/annotated_value.rs
- external-crates/move/crates/move-core-types/src/annotated_visitor.rs
- external-crates/move/crates/move-core-types/src/lib.rs
- external-crates/move/crates/move-core-types/src/runtime_value.rs
- external-crates/move/crates/move-core-types/src/unit_tests/visitor_test.rs
- external-crates/move/crates/move-vm-types/src/values/values_impl.rs
Cleanup the naming and usage of the constant names and do a bit of cleanup/administrivia around variant bounds. 
CI
---
> [move][cleanup] Cleanup tag bounding constant names

- Cargo.lock
- external-crates/move/Cargo.lock
- external-crates/move/crates/move-abstract-interpreter/src/absint.rs
- external-crates/move/crates/move-abstract-interpreter/src/control_flow_graph.rs
- external-crates/move/crates/move-bytecode-verifier/src/absint.rs
- external-crates/move/crates/move-bytecode-verifier/src/code_unit_verifier.rs
- external-crates/move/crates/move-bytecode-verifier/src/loop_summary.rs
- external-crates/move/crates/move-compiler/Cargo.toml
- external-crates/move/crates/move-compiler/src/cfgir/absint.rs
- external-crates/move/crates/move-compiler/src/cfgir/borrows/mod.rs
- external-crates/move/crates/move-compiler/src/cfgir/cfg.rs
- external-crates/move/crates/move-compiler/src/cfgir/liveness/mod.rs
- external-crates/move/crates/move-compiler/src/cfgir/locals/mod.rs
- external-crates/move/crates/move-compiler/src/cfgir/visitor.rs
- external-crates/move/crates/move-coverage/src/lcov.rs
- external-crates/move/crates/move-coverage/src/summary.rs
- external-crates/move/crates/move-disassembler/src/disassembler.rs
- external-crates/move/crates/move-ir-compiler/src/unit_tests/cfg_tests.rs
- Use the shared abstract interpreter in the compiler
- Some funny business has to be done to pipe through diagnostics, open to suggestions there--even if it means changing the trait 
- 👀 
- cargo test
---
> [move-abstract-interpreter] Use shared abstract interpreter in the compiler 

- sui-execution/latest/sui-adapter/src/static_programmable_transactions/env.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
Add loading of types for move calls, and cleanup some of the error handling/use `convert_linked_vm_error` where applicable.
👀
> [static-ptbs] Add loading of types for move calls

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/traffic_controller/mod.rs
- crates/sui-core/src/traffic_controller/policies.rs
- crates/sui-e2e-tests/tests/traffic_control_tests.rs
- crates/sui-json-rpc/src/lib.rs
- crates/sui-json-rpc/src/traffic_control.rs
- crates/sui-node/src/admin.rs
- crates/sui-node/src/lib.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/traffic_control.rs
Implement an admin API endpoint to do a hot reconfiguration of the traffic control policy without clearing blocklists or existing count min sketch.
To facilitate this, the PR introduces a refactor that allows AuthorityState to hold a reference to TrafficController, and for all sui callsites to reference this rather than instantiating separately. This is ok for our purposes (and indeed is much cleaner) because sui-node enforces that validators do not run json rpc server. Additionally, we need to make the policy a member of the traffic controller struct in order to reference it from the main thread.
Things to note:
For now, this only works when the node is previously running traffic controller with a blocklist policy. i.e. it will fail if used to enable traffic control on a node that did …
> [Traffic Control] Add dynamic config via admin api

- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_61.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_61.snap
CI run (Checking protocol compatibility) fails due to a recent change in [this commit](https://github.com/MystenLabs/sui/commit/7ccbb5c62e0a083d80c0c64cde31dc2599946ef0)
adding back the deleted empty line
ran https://github.com/MystenLabs/sui-operations/actions/runs/15747972002 against my fix branch and it works
---
> chore: fix ci failure because of the removal of an empty line

- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/committer.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
- crates/sui-indexer-alt-framework/src/testing/mock_store.rs
- crates/sui-indexer-alt-framework/src/testing/mod.rs
Improve test coverage for concurrent/committers.rs
Test coverage includes:
* Commit received BatchRows
* Commit with exponential backoff for failed commit
* Commit with exponential backoff for failed DB connection
Also, I refactored the `MockStore` and `MockConnection` logic, moving it from `pruner.rs` to `mock_store.rs` to make it reusable by other files.
```
cargo test -p sui-indexer-alt-framework  committer  --lib
```
- #22359
- #22366
- #22393
--- …
> [indexer-alt-framework] Improve test coverage for concurrent/committer

- crates/sui-core/src/unit_tests/config_tests.rs
- crates/sui-protocol-config/src/lib.rs
- sui-execution/latest/sui-adapter/src/temporary_store.rs
Fixes an issue where we were adding in additional config objects accessed without protocol gating it.
CI + added new tests
> [execution] protocol gate adding additional configs to unchanged shared objects

- consensus/core/src/dag_state.rs
- consensus/core/src/metrics.rs
- consensus/core/src/threshold_clock.rs
- consensus/core/src/transaction_certifier.rs
Add metrics to help investigate delays between rounds.
Fix counting `consensus_certifier_output_blocks`.
---
> [consensus] add metrics to measure per-round delays when receiving blocks

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_86.snap
> Enable Party objects in testnet

- examples/move/random/random_nft/sources/example.move
It seems that there is no need to add `#[allow(unused_function)]` before the `init` function
> [examples] Remove unnecessary prompts

- crates/sui/tests/shell_tests.rs
- crates/sui/tests/shell_tests/summaries/data/move_package/Move.toml
- crates/sui/tests/shell_tests/summaries/data/overlapping_summaries/Move.toml
- crates/sui/tests/shell_tests/summaries/data/overlapping_summaries/child_pkg/Move.toml
- crates/sui/tests/shell_tests/summaries/data/overlapping_summaries/other_child/Move.toml
- crates/sui/tests/shell_tests/summaries/data/pkg_with_hardcoded_addr/Move.toml
- crates/sui/tests/snapshots/shell_tests__summaries__summarize_json.sh.snap
- crates/sui/tests/snapshots/shell_tests__summaries__summarize_yaml.sh.snap
- crates/sui/tests/snapshots/shell_tests__summaries__summary_address_remapping.sh.snap
- crates/sui/tests/snapshots/shell_tests__summaries__summary_hardcoded_addr.sh.snap
Switch to using a local dependency of the sui-framework when generating package summaries to keep it in-line with other local references of the sui-framework in the repo.
Updated tests + CI
> [cli/summaries] Use local framework dependencies when generating summaries in tests

- docs/content/guides/developer/sui-101/building-ptb.mdx
Using `tx.pure(value)` directly in the new version of TS SDK will result in an error, so the usage in the document is updated to support the format of the new version.
> Update `tx.pure` to be compatible with new version

- external-crates/move/documentation/book/src/control-flow/labeled-control-flow.md
Pass in the correct parameters and add semicolons at the appropriate locations
> Fix code errors in `labeled-control-flow.md`

- crates/sui-indexer-alt-framework/src/pipeline/concurrent/committer.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/reader_watermark.rs
- crates/sui-indexer-alt-framework/src/testing/mock_store.rs
Improve test coverage for concurrent/reader_watermark.rs
Test coverage includes:
* Basic watermark update
* Watermark no update with smaller reader_lo
* DB connection failure
* DB set_reader_watermark falure
```
cargo test -p sui-indexer-alt-framework  reader_watermark  --lib
```
---
- #22359
- #22366
- #22393
- #22397 
- #22400 
> [indexer-alt-framework] Improve test coverage for reader_watermark

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/shared_object_congestion_tracker.rs
- crates/sui-core/src/authority/shared_object_version_manager.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/mock_consensus.rs
- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/transaction_driver/mod.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-core/src/unit_tests/transaction_tests.rs
- crates/sui-node/src/lib.rs
- crates/sui-single-node-benchmark/src/benchmark_context.rs
- crates/sui-single-node-benchmark/src/single_node.rs
- crates/sui-transactional-test-runner/src/lib.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/transaction.rs
- crates/sui-types/src/unit_tests/messages_tests.rs
We will no longer be able to simply use shared objects to determine whether a transaction is a consensus transaction, due to withdraws.
Removing this interface to make it less error prone.
---
> Rename contains_shared_object to is_consensus_tx

- crates/sui-benchmark/src/lib.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/authority_test_utils.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/consensus_validator.rs
- crates/sui-core/src/generate_format.rs
- crates/sui-core/src/test_utils.rs
- crates/sui-core/tests/staged/sui.yaml
- crates/sui-graphql-rpc/src/types/transaction_block_kind/programmable.rs
- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-replay/src/displays/transaction_displays.rs
- crates/sui-types/src/accumulator_root.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/executable_transaction.rs
- crates/sui-types/src/programmable_transaction_builder.rs
- crates/sui-types/src/sui_sdk_types_conversions.rs
- crates/sui-types/src/transaction.rs
- crates/sui-types/src/unit_tests/balance_withdraw_tests.rs
- crates/sui/tests/ptb_files_tests.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/loading/translate.rs
- sui-execution/v0/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/v1/sui-adapter/src/programmable_transactions/context.rs
- sui-execution/v2/sui-adapter/src/programmable_transactions/context.rs
Add a new CallArg to represent balance withdraw reservation.
This is not necessarily the final form. Adding it to support e2e testing and development.
Since this is all gated behind a protocol config, no transactions with withdraw reservation can be committed on-chain right now.
CI
---
> Add withdraw reservation to Transaction

- Cargo.lock
- Cargo.toml
- crates/sui-move/Cargo.toml
- crates/sui-node/Cargo.toml
- crates/sui-node/src/main.rs
- crates/sui/Cargo.toml
- crates/typed-store/Cargo.toml
- docker/sui-node-deterministic/Dockerfile
Use the `tikv-jemallocator` crate to define a `#[global_allocator]`, and enable the `jemalloc` feature of `librocksdb-sys` to leverage builtin jemalloc.
builds on top of: #22214 
Build + test on private testnet
https://metrics.sui.io/goto/sBTvy8PHR?orgId=1 
---
> Static Link Jemalloc

- crates/sui-analytics-indexer/src/analytics_processor.rs
This morning Michael and I shut off the pipes for the legacy stack, which caused me to get a few lag alerts. Currently we can "disable" this metric, but we still emit a -1 value when it is disabled. I am changing this behavior to just completely not emit the metric instead, which will silence the alerts.
> Only spawn metric task if reporting is enabled

- Cargo.lock
- crates/sui-indexer-alt-framework/Cargo.toml
- crates/sui-indexer-alt-framework/src/ingestion/client.rs
- crates/sui-indexer-alt-framework/src/ingestion/mod.rs
- crates/sui-indexer-alt-framework/src/ingestion/remote_client.rs
- crates/sui-indexer-alt-framework/src/ingestion/slow_future_monitor.rs
From the bug where the MVR Indexer was stalling ([Linear](https://linear.app/mysten-labs/issue/DVX-1198/mvr-indexer-pipeline-stopped-committing-watermark)), one potential culprit for the stall was that remote checkpoint fetching was somehow taking forever. However, there's currently no way to confirm this hypothesis, so this PR adds warnings when remote checkpoint fetching takes too long while still allowing the fetching to run until successful.
SlowFutureMonitor's implementation is based on the same idea of [`crates/sui-indexer-alt-jsonrpc/src/timeout.rs`](https://github.com/MystenLabs/sui/blob/cfef00b4e656d99d2450bc2505fb37902f65cdee/crates/sui-indexer-alt-jsonrpc/src/timeout.rs), but for monitoring rather than cancellation.
```
cargo test -p …
```
> [indexer-alt-framework] Implement slow operation warnings to remote checkpoint fetching

- crates/sui-core/src/authority/consensus_tx_status_cache.rs
- crates/sui-core/src/authority_server.rs
Otherwise, it is possible for a thread to read out / get notified about `Finalized` first, then receive a notification on `FastpathCertified`.
PT
---
> Serialize transaction status change notifications

- crates/sui/src/keytool.rs
Make the  `sui keytool export` to show the `alias` field correctly.
`sui keytool export --key-identity temp-user`
**Before**
```
sui keytool export --key-identity temp-user
╭────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────╮
│ exportedPrivateKey │  suiprivkey1qzs65v9kxhhaxm9wxr25d28r2e2kn5d3dtax7wd6v27znmtk59r4275rjfq                    │
│ key                │ ╭─────────────────┬──────────────────────────────────────────────────────────────────────╮ │
│                    │ │ alias           │                                                                      │ │
│                    │ │ suiAddress      │  0x9161de6c0d4e6d7d72c4b96208978e71b1e066c8decbadc0fb2f091b3ceb29b9  │ │
│                    │ │ publicBase64Key │ …
```
> [cli] Fix keytool export to  show alias

- crates/sui/src/sui_commands.rs
This PR fixes a bug where `sui move build --dump-bytecode-as-base64` uses a published address in the resolved table for the root package being built instead of `0x0`, leading to inconsistencies when this interacts with automated feature management. 
👀 
---
> [cli] Fix `sui move build --dump-bytecode-as-base64` to correctly take into account Move.lock addresses

- Cargo.lock
- Cargo.toml
GraphiQL is currently not working because of an issue with `unpkg` knowing that `graphiql` `5.0.0` has been released but not having the resources for it.
The fix is to cherry-pick some upstream changes to `async-graphql` that pins the version of GraphiQL to use.
Run the GraphQL service locally -- previously the UI would not load, and after this change it does.
---
> pick(22535) graphql: fix graphiql dependency

- external-crates/move/crates/move-package-alt/src/graph/builder.rs
- external-crates/move/crates/move-package-alt/src/graph/mod.rs
- external-crates/move/crates/move-package-alt/src/graph/to_lockfile.rs
This PR just moves things out of `graph/mod.rs` - code is not changed
---
> [package-alt] split package graph into multiple submodules

- crates/sui-config/src/node.rs
- crates/sui-data-ingestion-core/src/executor.rs
- crates/sui-data-ingestion-core/src/lib.rs
- crates/sui-network/src/state_sync/mod.rs
- crates/sui-network/src/state_sync/tests.rs
will be used for `requester pays` feature
---
> [state sync] allow passing remote store options to the archive fallback

- crates/sui-config/src/node.rs
- crates/sui-data-ingestion-core/src/executor.rs
- crates/sui-data-ingestion-core/src/lib.rs
- crates/sui-network/src/state_sync/mod.rs
- crates/sui-network/src/state_sync/tests.rs
will be used for requester pays feature
---
The default bucket for state sync archive fallback now uses a requester pays policy.
Update sui node's state-archive-read-config section according to the [docs](https://docs.sui.io/guides/operator/archives)
> cherry pick: [state sync] allow passing remote store options to the archive fallback

- consensus/core/src/authority_node.rs
- consensus/core/src/commit_observer.rs
- consensus/core/src/dag_state.rs
- consensus/core/src/metrics.rs
- consensus/core/src/transaction_certifier.rs
* Do not attempt to recover on the transaction certifier when mysticeti fast path is disabled
* Refactor commit consumer so commits are recovered in batches. This ensures we do the recovery gracefully and do not attempt to load all the data at once in memory resulting in OOM under stress conditions (ex authority quarantining commits for long period)
CI
---
> [Consensus] disable the recovery of the transaction certifier & refactor commit consumer recovery

- crates/sui-sdk/src/error.rs
- crates/sui-sdk/src/lib.rs
- Creates a new `CustomHeadersError` Error for `SuiRpcResult`.
- Adds support for custom user defined headers in the `SuiClientBuilder`.
Tested the initialization locally with the new Enoki RPC apikey protected RPC.
```rust
let mut headers = std::collections::HashMap::new();
let api_key = String::from("apikey");
let value = String::from("<a key here>");
headers.insert(api_key, value);
let sui_custom_headers = SuiClientBuilder::default()
.custom_headers(headers)
.build("https://enoki-rpc.mystenlabs.com/")
.await?;
let balanced = sui_custom_headers
.coin_read_api()
.get_all_balances(
SuiAddress::from_str(
"an address here",
)
.unwrap(),
)
.await
.unwrap();
```
---
For each …
> [rust-sdk] Adds custom header support in the SuiClientBuilder struct

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/shared_object_version_manager.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/balance_read.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/e2e_tests.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/mod.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/naive_scheduler.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/scheduler.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/tests.rs
- crates/sui-core/src/execution_scheduler/execution_scheduler_impl.rs
- crates/sui-core/src/execution_scheduler/mod.rs
- crates/sui-core/src/execution_scheduler/transaction_manager.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-types/src/accumulator_root.rs
- crates/sui-types/src/executable_transaction.rs
This PR connects the ExecutionScheduler and balance withdraw scheduler.
We add a new variant to `Schedulable` that represents a transaction with withdraw reservations.
Such a transaction will not get scheduled immediately, instead, similar to randomness update transactions, it will wait until its withdraw is scheduled. The scheduling result is passed as part of the ExecutionEnv which then can be used by authority (not included in this PR). 
Added end-to-end scheduling test.
---
> Connect ExecutionScheduler and balance withdraw scheduler

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-core/src/authority/weighted_moving_average.rs
Sui's congestion control system relies on execution time estimates to make deferral decisions and calculate transaction costs. Currently, this system uses a simple moving average of execution times per command. This change gives greater weight to higher gas-price transaction measurements when calculating time estimates, both providing a higher degree of accuracy in scenarios where contention is likely.
- Unit tested that averages are in fact gas weighted
--- …
> Weight execution time observations by gas price

- external-crates/move/crates/move-analyzer/editors/code/package-lock.json
- external-crates/move/crates/move-analyzer/editors/code/src/context.ts
What the subject says. The function could actually return `undefined` (instead of just `string` or `null`) which would cause the extension startup to fail if one of the versions was not available during installation
Tested manually
> [move-ide] Version check fix

- Cargo.lock
- Cargo.toml
- crates/sui-move/Cargo.toml
- crates/sui-node/Cargo.toml
- crates/sui-node/src/main.rs
- crates/sui/Cargo.toml
- crates/typed-store/Cargo.toml
- docker/sui-node-deterministic/Dockerfile
- docker/sui-node/Dockerfile
Fix issue with segfault when running sui-node in kubernetes.
Update tikv-jemallocator features to enable profiling
Remove extra jemalloc LD_PRELOAD'ed into container now that jemalloc is statically linked in rust buildd 
* run benchmark against commit in sui-operations `pulumi up -s benchmark-mainnet`
* run asymptotic run `./scripts/run-antithesis-tests -t 0.25 -d testing_jemalloc` [initial-run](https://github.com/MystenLabs/sui-operations/actions/runs/16042081694)
---
> Kubernetes Benchmark Issue

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-node/src/lib.rs
This reverts commit d4c0059ff5e066819631ef25fc59ff519efe6134.
The fix in that commit is no longer necessary now that we have recovered from the testnet incident
> Revert "Insert missing tx keys at start up (#22545)"

- crates/sui-indexer-alt-jsonrpc/src/api/transactions/error.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/response.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/data.rs
- crates/sui-indexer-alt-jsonrpc/src/metrics/mod.rs
From traffic shadowing we see that internal errors can arise due to kv objects and tx_digests table being behind other objects/tx tables. This PR aims to resolve these internal errors by retrying the reads.
tested with a local jsonrpc server
---
> [rpc-alt] retry kv and tx_digest read operations

- docs/content/guides/operator/data-management.mdx
Validators and SSFNs do not need to serve read traffic. So it is fine to prune object versions aggressively on them.
n/a
---
> Recommend aggressive object version pruning to validators

- crates/sui-indexer-alt-jsonrpc/src/api/transactions/error.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/response.rs
- crates/sui-indexer-alt-jsonrpc/src/config.rs
- crates/sui-indexer-alt-jsonrpc/src/data.rs
- crates/sui-indexer-alt-jsonrpc/src/metrics/mod.rs
From traffic shadowing we see that internal errors can arise due to kv objects and tx_digests table being behind other objects/tx tables. This PR aims to resolve these internal errors by retrying the reads.
tested with a local jsonrpc server
---
--- …
> [cherrypick][rpc-alt] retry kv and tx_digest read operations (#22586)

- crates/sui-indexer-alt-framework/src/ingestion/slow_future_monitor.rs
The original `SlowFutureMonitor` implementation could not detect futures that get "stuck" (never wake their waker). It only checked elapsed time during poll() calls, but if a future returns Poll::Pending without scheduling a wake, it will never be polled again, and the warning callback would never fire.
**Solution**
Replaced the polling-based approach with a tokio::select!-based implementation that races the monitored future against a timer:
```
tokio::select! {
result = &mut future => return result,  // Future completed first
_ = sleep(threshold) => callback(),     // Timer expired - fire warning
}
```
```
cargo test -p sui-indexer-alt-framework  remote_client  --lib
```
---
- #22516
Check each box that your changes affect. If none of the …
> [indexer-alt-framework] Update slow_future_monitor

- crates/sui-indexer-alt-framework/src/cluster.rs
Refactors `IndexerCluster` to use the Builder pattern for better API stability and extensibility.
**Motivation**
As we continue to evolve the indexer framework, we have an opportunity to improve the API design. The current constructor-based approach requires all users to update their code when we add new configuration options.
By adopting the Builder pattern, we can:
* Add new optional parameters without affecting existing code
* Provide a more intuitive API where users only specify what they need
* Follow established Rust patterns that developers are familiar with
**Changes**
* Added IndexerClusterBuilder with fluent API using with_ prefixed methods
* Removed the existing constructor methods 
* Updated tests and documentation
```
cargo test -p …
```
> [indexer-alt-framework] Implement IndexerClusterBuilder

- Cargo.lock
- crates/sui-replay-2/src/data_store.rs
- crates/sui/Cargo.toml
- crates/sui/src/client_commands.rs
Switch over replay support in the Sui CLI to use the new replay2 transaction replayer.
Currently a draft, but please leave comments! 
CI
---
> [cli] Add replay2 to Sui CLI

- consensus/core/src/commit_finalizer.rs
- consensus/core/src/core.rs
- consensus/core/src/dag_state.rs
It is unnecessary to restrict commit flushing to finalized commits only. Sui / execution replays consensus from last processed commit, and replaying commits rerun the transaction finalization logic. Also it is incorrect to flush blocks without flushing the commit that sets the GC round at the time. The GC round determines which ancestors of a block must exist, so it should be flushed together with the ancestors before persisting a block.
CI
---
> [consensus] flush all pending commits

- crates/sui-adapter-transactional-tests/tests/size_limits/deleted_id_limits_tests@v2.snap
- crates/sui-adapter-transactional-tests/tests/size_limits/new_id_limits_tests@v2.snap
- crates/sui-adapter-transactional-tests/tests/size_limits/object_runtime_limits@v2.snap
- crates/sui-adapter-transactional-tests/tests/size_limits/transfered_id_limits_tests@v2.snap
- crates/sui-types/src/base_types.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/env.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/loading/ast.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/ast.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/translate.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/drop_safety.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/input_arguments.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/memory_safety.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/move_functions.rs
- There were a few spots where TxContext was special cased as a parameter at the end
- Now TxContext is a location that is borrowed like anything else
- Updated tests... though I'm surprised they changed
---
> [static ptb] Switch TxContext to a Location 

- external-crates/move/crates/move-compiler/src/typing/core.rs
- external-crates/move/crates/move-compiler/src/typing/translate.rs
This generalizes type variable constraints in the compiler, toward #22593
Tests all still pass
---
> [move][move-compiler][typing] Extend var typing constraints in type inference

- crates/sui-replay-2/src/lib.rs
Raise an error if you try to replay a transaction and the replay tool hasn't been compiled with the `tracing` feature flag. 
Tested locally
> [replay] Raise an error if you try to trace without the tracer enabled

- crates/sui-benchmark/tests/simtest.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-protocol-config/src/lib.rs
Simulate execution time to trigger congestion control in test environments
As described. Test-only, no impact to production.
Antithesis + SIM testing
---
> simulate execution time to trigger congestion control in test - alt

- .github/workflows/release.yml
Always upload tar balls to s3 to save build time
👀
> Always upload tar balls to s3 to save build time

- crates/sui-graphql-e2e-tests/tests/stable/prune/events.move
- crates/sui-graphql-e2e-tests/tests/stable/prune/events.snap
- crates/sui-graphql-rpc/src/server/builder.rs
- crates/sui-graphql-rpc/src/server/watermark_task.rs
- crates/sui-graphql-rpc/src/types/event/lookups.rs
- crates/sui-graphql-rpc/src/types/event/mod.rs
- crates/sui-graphql-rpc/src/types/query.rs
Watermark task now reads from watermarks table instead of checkpoints table. This is used for Event::paginate, so we can correctly bound the available range of data
Pointed local graphql to current mainnet db. Ran the query below:
```
query Event {
events(filter:{eventType:"0x3::validator::StakingRequestEvent"})
{
pageInfo {
hasNextPage
endCursor
}
nodes {
sendingModule {
name
package {
address
}
}
sender {
address
}
contents {
json
}
timestamp
}
}
}
```
Received expected page of results instead of erroneous result,
```
{
"data": {
"events": {
"pageInfo": {
"hasNextPage": true,
"endCursor": null
},
"nodes": []
}
}
}
```
---
For each box you select, include information after …
> [gql] Watermark task reads from watermarks table, use watermarks for `Event::paginate`

- crates/sui-framework/packages/sui-framework/sources/test/test_scenario.move
- crates/sui-framework/packages/sui-framework/tests/test_scenario_tests.move
the `sponsor` field in `TxContextBuilder` is an option like `rgp` but did not have a set/unset API.
Originally I did not care to do that too because the sponsor is truly an `option` whereas the `rgp` is an `option` just to mean set it or ignore it.
For consistency a `set/unset` API seems more proper, not sure what others think, so this is the PR in case we want it. I'll cherry pick tomorrow if accepted it
changed the tests to use the set/unset API
---
Describe the changes or additions …
> Move the sponsor to a set/unset api (#22674)

- crates/sui-benchmark/src/lib.rs
- crates/sui-core/src/transaction_driver/effects_certifier.rs
- crates/sui-core/src/transaction_driver/error.rs
- crates/sui-core/src/transaction_driver/message_types.rs
- crates/sui-core/src/transaction_driver/metrics.rs
- crates/sui-core/src/transaction_driver/mod.rs
- crates/sui-core/src/transaction_driver/transaction_submitter.rs
`EffectsCertifier` will concurrently wait for full effects from one validator and acks for quorum of effects digest from all validators. Once `ErrorCategorizer` component is added we will modify `EffectsCertifier` & `TransactionSubmitter` to use this and retry more intelligently
> [mfp] Add effects certifier

- crates/sui-benchmark/tests/simtest.rs
> Fix end of epoch stored observation bug on simtest for all protocol versions before 88

- sdk/suins-toolkit/README.md
The suins-toolkit codebase was fully removed in [#148](https://github.com/MystenLabs/ts-sdks/pull/148).  
This PR remove the leftover README file in the suins-toolkit directory, as the documentation is no longer relevant.
> chore: remove leftover suins-toolkit docs

- .github/CODEOWNERS
This adds the newly created `devx-indexers-and-rpcs` team to the crates the team owns in CODEOWNERS.
The `devx-indexers-and-rpcs` team needs permissions set up before this is merged. The permissions can be verified by being able to add the team as a reviewer to this PR.
---
> Setup devx-indexers-and-rpcs team in CODEOWNERS

- crates/sui-indexer-alt-e2e-tests/README.md
- crates/sui-pg-db/src/temp.rs
Improve the error output to include additional details (exit code, message, log dir) in output when postgres fails to start.
Example output:
```
Failed to create off-chain cluster: Failed to create database
Caused by:
0: Unable to start postgres, check dir /var/folders/5d/ppmp0h310tnbrgf8xn1vrpnw0000gn/T/.tmpZReFSd for logs
1: Not running - exit status: exit status: 1
Stack backtrace:
0: std::backtrace_rs::backtrace::libunwind::trace
at /rustc/4eb161250e340c8f48f66e2b929ef4a5bed7c181/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
...
```
Add instructions for running transactional tests in the RustRover debugger.
Ran `test -p sui-indexer-alt-e2e-tests --test transactional_tests graphql/epochs/query.move` and was able to set breakpoints.
---
Check each box that your …
> Improve postgres error output, add debugging instructions

- sui-execution/latest/sui-move-natives/src/tx_context.rs
`TxContext::replace` was changed in the number of args from 8 to 9. We thought that was ok given implicit deps and the test only function.
It turns out that because of the release schedule and the multiple versions of the CLI that can be used having both version work would be ideal, maybe necessary.
This PR makes the native work both when 8 or 9 args are provided. Basically the native works for both the old and the new version of the framework
Tested manually on the cli run that fails
--- …
> Make `replace` in `TxContext` Move "variadic"

- sui-execution/latest/sui-move-natives/src/tx_context.rs
`TxContext::replace` was changed in the number of args from 8 to 9. We thought that was ok given implicit deps and the test only function. It turns out that because of the release schedule and the multiple versions of the CLI that can be used having both version work would be ideal, maybe necessary.
This PR makes the native work both when 8 or 9 args are provided. Basically the native works for both the old and the new version of the framework
Tested manually on the cli run that fails
--- …
> Make `replace` in `TxContext` Move "variadic" (#22701)

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/expiration.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/expiration.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
- crates/sui-transactional-test-runner/src/args.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
Implement expiration field support for `Transaction` type.
Within this PR, I also added support for `expiration` for ProgrammableTransactionCommand, which allows us to implementation snapshot test for `Transaction.expiration`
```
```
---
> [graphql-alt] Support Expiration for Transaction

- crates/sui-indexer-alt-framework/src/cluster.rs
- crates/sui-indexer-alt-framework/src/ingestion/mod.rs
Extends `IndexerClusterBuilder` with individual fluent API methods for `IndexerArgs`, `ClientArgs`, and `MetricsArgs` components, implementing "Last Write Wins" semantics as described in [Approach 2](https://www.notion.so/mystenlabs/IndexerClusterBuilder-Improvement-Options-22b6d9dcb4e9800d8da4c91170f668a2?source=copy_link#22d6d9dcb4e9800e8fd1f548c3773dd1) from my design doc.
---
> [indexer-alt] Implement fluent Args API Builder with last-write-win semantics

- crates/sui/tests/snapshots/shell_tests__sui_move_new_tests__gitignore_exists.sh.snap
- crates/sui/tests/snapshots/shell_tests__sui_move_new_tests__gitignore_has_build.sh.snap
- external-crates/move/crates/move-cli/src/base/new.rs
- external-crates/move/crates/move-cli/tests/build_tests/new_clobber/gitignore_exists/args.exp
- external-crates/move/crates/move-cli/tests/build_tests/new_simple/args.exp
Extends default `.gitignore`
---
> [move, cli] adds .trace and .coverage to gitignore

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/gas_input.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/gas_input.snap
- crates/sui-indexer-alt-graphql/src/api/types/gas_input.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
Following discussion on PR #22652, this PR does following things:
1. Update advance-clock to assign transaction digests
2. Adding a test to gas_input on how it will behaving with a system transaction.
```
```
---
- #22652 
> [graphql-alt] Update advance-clock to assign transaction digests

- crates/sui-benchmark/src/util.rs
- crates/sui-cluster-test/src/cluster.rs
- crates/sui-e2e-tests/tests/full_node_tests.rs
- crates/sui-keys/src/key_identity.rs
- crates/sui-keys/src/keystore.rs
- crates/sui-keys/src/lib.rs
- crates/sui-keys/tests/tests.rs
- crates/sui-rosetta/src/main.rs
- crates/sui-rosetta/tests/end_to_end_tests.rs
- crates/sui-rosetta/tests/gas_budget_tests.rs
- crates/sui-rosetta/tests/rosetta_client.rs
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-sdk/examples/utils.rs
- crates/sui-sdk/src/wallet_context.rs
- crates/sui-sdk/tests/tests.rs
- crates/sui/src/client_commands.rs
- crates/sui/src/keytool.rs
- crates/sui/src/lib.rs
- crates/sui/src/sui_commands.rs
- crates/sui/src/unit_tests/keytool_tests.rs
- crates/sui/src/validator_commands.rs
- crates/sui/src/zklogin_commands_util.rs
- crates/sui/tests/cli_tests.rs
- crates/test-cluster/src/lib.rs
"key" now implied in function names, "export" and "import" used to be more inline with wallet terminology and disambiguate between "generate" and "import".
- add_key -> import
- get_key -> export
- remove_key -> remove
- get_key -> export
- keys -> entries
pushed the identity module into sui-keys, KeyIdentity helper function into wallet context
- get_alias_by_address -> get_alias
- get_address_by_alias -> replaced via get_by_identity
- alias_names -> now a test helper outside of trait
Good coverage exists with unit tests.
--- …
> [cli] sui keys interface rework

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/endTimestamp/endTimestamp_end_epoch_checkpoint.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/endTimestamp/endTimestamp_end_epoch_checkpoint.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/totalCheckpoints/totalCheckpoints_empty_epoch.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/totalCheckpoints/totalCheckpoints_empty_epoch.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/totalCheckpoints/totalCheckpoints_with_checkpoint.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/totalCheckpoints/totalCheckpoints_with_checkpoint.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/scope.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
1. Implements `Epoch.totalCheckpoints` based on https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/epoch.rs#L125-L137
2. Fixes a bug with epoch end bounds
1. Added `totalCheckpoints` to the `query.move` snapshot test.
2. Added new tests for `totalCheckpoints` and `startTimestamp`/`endTimestamp`.
---
> graphql-alt: Add Epoch.totalCheckpoints

- crates/sui-core/src/authority.rs
This PR moves commit_certificates out of process_certificates. This will allow us address the mysticeti-fastpath re-execution issue much more cleanly by resusing the right code.
CI
---
> [core] Break up process_certificates

- crates/sui-adapter-transactional-tests/tests/programmable/pure_arg_mut.move
- crates/sui-adapter-transactional-tests/tests/programmable/pure_arg_mut.snap
- crates/sui-adapter-transactional-tests/tests/programmable/pure_arg_mut@v2.snap
- crates/sui-adapter-transactional-tests/tests/programmable/pure_arg_type_change.move
- crates/sui-adapter-transactional-tests/tests/programmable/pure_arg_type_change.snap
- crates/sui-adapter-transactional-tests/tests/programmable/pure_arg_type_change@v2.snap
- crates/sui-adapter-transactional-tests/tests/receive_object/pt_receive_type_fixing.move
- crates/sui-adapter-transactional-tests/tests/receive_object/pt_receive_type_fixing.snap
- crates/sui-adapter-transactional-tests/tests/receive_object/pt_receive_type_fixing@v2.snap
- crates/sui-adapter-transactional-tests/tests/receive_object/pt_receive_type_separation.move
- crates/sui-adapter-transactional-tests/tests/receive_object/pt_receive_type_separation.snap
- crates/sui-adapter-transactional-tests/tests/receive_object/pt_receive_type_separation@v2.snap
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/interpreter.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/values.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/loading/ast.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/ast.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/invariant_checks/defining_ids_in_types.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/invariant_checks/type_check.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/translate.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/drop_safety.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/input_arguments.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/memory_safety.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/typing/verify/move_functions.rs
- Each pure value now gets a separate local per input, per type 
- This greatly reduces the complexity in type checking, verification, and runtime value tracking (no more input metadata. no more temporary locals)
- A few new tests
---
> [static ptb] Refactor Pure values into separate locals

- Cargo.lock
- Cargo.toml
GraphiQL is currently not working because of an issue with `unpkg` knowing that `graphiql` `5.0.0` has been released but not having the resources for it.
The fix is to cherry-pick some upstream changes to `async-graphql` that pins the version of GraphiQL to use.
Run the GraphQL service locally -- previously the UI would not load, and after this change it does.
---
---
Check each box that …
> [re-pick] pick(22535) graphql: fix graphiql dependency (#22537)

- external-crates/move/crates/move-package-alt/src/errors/mod.rs
- external-crates/move/crates/move-package-alt/src/graph/mod.rs
- external-crates/move/crates/move-package-alt/src/package/root_package.rs
- external-crates/move/crates/move-package-alt/src/test_utils/graph_builder.rs
This adds a call to the rename-from check to the root package loading.
#22767 Call rename-from in main workflow
#22763 Rename-from test implementation
#22766 Linkage bug fixes
Added a unit test to root package.
---
> [package-alt] Call rename-from in main workflow

- external-crates/move/crates/move-package-alt/src/compatibility/legacy_parser.rs
- external-crates/move/crates/move-package-alt/src/dependency/dependency_set.rs
- external-crates/move/crates/move-package-alt/src/schema/manifest.rs
- external-crates/move/crates/move-package-alt/tests/data/basic/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/basic_external_resolver/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/basic_implicit_deps/Move.toml
- external-crates/move/crates/move-package-alt/tests/data/basic_implicit_deps/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/basic_no_dep_override_git/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/basic_with_bar/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/basic_with_bar/bar/Move.toml
- external-crates/move/crates/move-package-alt/tests/data/basic_with_bar/bar/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/flavor_global_storage/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/flavor_sui/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/flavor_unknown/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/invalid_author/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/invalid_authors/Move@parsed.snap
- external-crates/move/crates/move-package-alt/tests/data/non_identifier_address_name_in_subst/Move@parsed.snap
This adds the `implicit-deps` field to the manifest format. There are 4 modes: enabled and disabled are clear. Legacy is only used for legacy packages - for those, implicit deps are enabled unless any of them are present. Finally, I added a "testing" mode as a way for us to do implicit deps differently in the monorepo for our internal tests (this is something that has been a headache with our existing implicit deps).
I added unit tests. In principle these could be integration tests, but my goal is to start migrating those back so I'm trying out the unit test format.
--- …
> [pkg-alt] added implicit-deps field to manifest

- crates/sui-core/src/traffic_controller/mod.rs
the blocklist len metric often reports as being a negative number, which shouldn't be possible. This fixes a possible race condition where the same IP is triggering `check_and_clear_blocklist` in parallel, causing the blocklist to be decremented multiple times when only a single IP is being removed. 
---
> [traffic controller] fix race condition in blocklist metric dec() call

- .github/workflows/rust.yml
- .github/workflows/simulator-nightly.yml
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-core/src/unit_tests/transaction_tests.rs
- crates/sui-e2e-tests/tests/multisig_tests.rs
- crates/sui-e2e-tests/tests/party_objects_tests.rs
- crates/sui-e2e-tests/tests/passkey_e2e_tests.rs
- crates/sui-e2e-tests/tests/reconfiguration_tests.rs
- crates/sui-e2e-tests/tests/rpc/v2beta2/signature_verification_service.rs
- crates/sui-e2e-tests/tests/zklogin_tests.rs
- crates/sui-json-rpc-tests/tests/rpc_server_tests.rs
- crates/sui-sdk/tests/tests.rs
- crates/sui-simulator/src/lib.rs
- crates/sui-types/src/digests.rs
It is common to have a feature enabled in simtests and optionally testnet, but not mainnet. A feature can be in this state for months. But mainnet protocol config is only tested in a few upgrade related tests. It is important to make sure changes do not accidentally break the `mainnet` protocol while passing tests with the latest protocol config via features enabled in dev environments.
CI
---
> Add workflows to test with mainnet protocol config

- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/safe_client.rs
- crates/sui-core/src/test_authority_clients.rs
- crates/sui-core/src/transaction_driver/effects_certifier.rs
- crates/sui-core/src/transaction_driver/message_types.rs
- crates/sui-core/src/transaction_driver/mod.rs
- crates/sui-core/src/transaction_driver/transaction_submitter.rs
- crates/sui-core/src/unit_tests/submit_transaction_tests.rs
- crates/sui-core/src/unit_tests/wait_for_effects_tests.rs
- crates/sui-types/src/messages_grpc.rs
During transaction submission, if it is found that the transaction already has finalized effects, the full effects will be returned instead of consensus position.
Then effects certifier and authority handler will proceed assuming the transaction has finalized.
CI
> [TD] certify effects when the transaction has already finalized

- crates/sui-data-ingestion-core/src/reader.rs
Hello Sui team.
I'm downloading the formal snapshot, notably with `--all-checkpoints`, but this never succeeds. The download progress gets stuck after 200k-1M checkpoints are downloaded. I tried this for 3-4 times and it can stuck on download any random single object for 20+ hours. I also tried to adjust the parallel parameters from 4 to 8192 but no luck.
I can confirm by `bmon` that when the downloading is not stuck, the download speed is roughly 950Mbps and that's exactly the bandwidth our ISP provides and I got ~1k checkpoints per seconds. However, when it gets stuck, the download throughput is dropped to 50-100Kbps and no new checkpoint can be downloaded due to this slow connection (and original backoff mechanism will always wait), where I suspect some sort of QoS is applied by our …
> Fix download formal snapshot stuck on single connection

- crates/sui-kvstore/src/bigtable/client.rs
- crates/sui-kvstore/src/bigtable/metrics.rs
enables extra bigtable stats on gRPC level
---
> kv store: enable extra stats on bigtable

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/totalGasFees/totalGasFees.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/totalGasFees/totalGasFees.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements `Epoch.totalGasFees` based on
https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/epoch.rs#L149-L151
1. Added totalCheckpoints to the `query.move` snapshot test.
2. Added new `totalGasFees.move` test file.
---
> graphql-alt: Add Epoch.totalGasFees

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/status.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/status.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implement `status` field support for `TransactionEffects` type.
Reference: Based on legacy implementation in sui/crates/sui-graphql-rpc/src/types /transaction_block_effects.rs
```
```
---
> [graphql-alt] Support status for TransactionEffects

- crates/sui-bridge-indexer/src/config.rs
- crates/sui-bridge-indexer/src/main.rs
- crates/sui-bridge-indexer/tests/indexer_tests.rs
added optional config to run eth only indexer, in preparation to split out Sui indexing using indexer-alt framework
---
> [Bridge Indexer] - added optional config to run eth only indexer

- crates/sui-benchmark/tests/simtest.rs
This should fix many test failures that result from the fullnode simply losing history
> Disable fullnode pruning in simtests

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/totalStakeRewards/totalStakeRewards.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/totalStakeRewards/totalStakeRewards.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements `Epoch.totalStakeRewards` based on
https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/epoch.rs#L154-L158
1. Added `totalStakeRewards` to the `query.move` snapshot test.
2. Added new `totalStakeRewards.move` test file.
---
> graphql-alt: Add Epoch.totalStakeRewards

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/execution_cache.rs
- crates/sui-core/src/execution_cache/unit_tests/notify_read_input_objects_tests.rs
- crates/sui-core/src/execution_cache/writeback_cache.rs
- crates/sui-core/src/execution_scheduler/execution_scheduler_impl.rs
- crates/sui-core/src/execution_scheduler/transaction_manager.rs
- crates/sui-core/src/test_utils.rs
After fastpath transaction executes through Mysticeti fastpath, input objects are not immediately available for locking. This adds a wait on the input objects to become available before running the signing / voting logic.
CI
PT
---
> [TD] wait for fastpath input objects before signing and submission

- Cargo.lock
- crates/sui-core/Cargo.toml
- crates/sui-core/src/lib.rs
- crates/sui-core/src/status_aggregator.rs
- crates/sui-core/src/transaction_driver/effects_certifier.rs
- crates/sui-core/src/transaction_driver/error.rs
- crates/sui-core/src/transaction_driver/mod.rs
- crates/sui-core/src/transaction_driver/transaction_retrier.rs
- crates/sui-core/src/transaction_driver/transaction_submitter.rs
Transactions submission and full effects query follow the same pattern:
1. Retries against each validator (may change to parallel requests during retries).
2. The process succeeds when one validator returns a good response.
3. After getting back f+1 permanent failures, the whole operation should abort.
Components are added to abstract the pattern for retries and calling into error categorization.
CI
PT
---
> [TD] add common components to retry submission and getting full effects

- external-crates/move/crates/move-package-alt-compilation/src/build_plan.rs
- external-crates/move/crates/move-package-alt-compilation/src/compiled_package.rs
- external-crates/move/crates/move-package-alt-compilation/src/lib.rs
- external-crates/move/crates/move-package-alt/src/cli/build.rs
- external-crates/move/crates/move-package-alt/src/graph/mod.rs
- external-crates/move/crates/move-package-alt/src/graph/rename_from.rs
- external-crates/move/crates/move-package-alt/src/main.rs
- external-crates/move/crates/move-package-alt/src/package/package_impl.rs
- external-crates/move/crates/move-package-alt/src/package/root_package.rs
This adds a `PackageInfo` type which is a thin wrapper around a node in the package graph; this allows the compilation crate to not make use of the `Package` and `PackageGraph` internal types.
It is currently untested
---
> [pkg-alt] simpler package / compilation interface

- external-crates/move/crates/move-package-alt/src/compatibility/mod.rs
Fixes the issue where doc comments caused trouble on figuring out the modern name for a package.
---
> [pkg-alt] fix modern name discovery bug

- docs/content/guides/developer/app-examples/e2e-counter.mdx
The file path mentioned in the example guide should refer to the `sources` directory, instead it refers to the parent. This can be confusing for beginners.
> [docs] fix file path in e2e counter example docs

- crates/sui-replay-2/src/tracing.rs
- external-crates/move/crates/move-analyzer/trace-adapter/src/trace_utils.ts
This PR fixes a problem with replay and trace-debugging transactions that include calls into upgraded packages. The problem was related to modules being represented as belonging to the original package rather than the defining (upgraded) package. This was manifested in two places:
- `OpenFrame` event in the trace
- debug info
The result of the former was that a function that did not exist in the original package could not be found during trace debugging as the debugger, seeing module name and original package ID, would look for this function in debug info representing a module from the original package, where this function indeed does not exist.
The result of the latter was that debug info (key-ed in the debugger on the module name and package ID) for different versions of the module …
> [trace-view] Fixed a problem related to using incorrect pkg IDs

- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/checkpoint_bcs.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/checkpoint_bcs.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/checkpoint.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Description
Added support for `Checkpoint.summaryBcs` and `Checkpoint.contentBcs`
Test plan
E2E tests:
cargo nextest run -p sui-indexer-alt-e2e-tests  -- graphql/checkpoints
Schema tests:
cargo nextest run -p sui-indexer-alt-graphql -- schema
cargo nextest run -p sui-indexer-alt-graphql --features staging -- schema
Stack:
https://github.com/MystenLabs/sui/pull/22651
https://github.com/MystenLabs/sui/pull/22686
https://github.com/MystenLabs/sui/pull/22688
https://github.com/MystenLabs/sui/pull/22690
https://github.com/MystenLabs/sui/pull/22691
https://github.com/MystenLabs/sui/pull/22708 👈 
--- …
> graphql-alt: Checkpoint.summaryBcs, Checkpoint.contentBcs

- crates/sui-benchmark/tests/simtest.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-e2e-tests/tests/full_node_tests.rs
- crates/sui-e2e-tests/tests/traffic_control_tests.rs
- crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
- crates/sui-json-rpc/src/error.rs
- crates/sui-json-rpc/src/transaction_execution_api.rs
- crates/sui-node/src/lib.rs
- crates/sui-rpc-api/src/error.rs
- crates/sui-types/src/quorum_driver_types.rs
Use TD for a percentage of submission through transaction orchestrator with TRANSACTION_DRIVER env var set. Additionally we will abort submission of a transaction if effects become available locally for both TD & QD submission.
CI/PT
---
> [TD] Add TD path to TO & abort submission on local execution

- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/checkpoint_bcs.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/checkpoint_bcs.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/network_total_transactions.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/network_total_transactions.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/rolling_gas_summary.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/rolling_gas_summary.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/checkpoint.rs
- crates/sui-indexer-alt-graphql/src/api/types/gas.rs
- crates/sui-indexer-alt-graphql/src/api/types/mod.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Description
Added support for:
`Checkpoint.networkTotalTransactions` 
`Checkpoint.rollingGasSummary` 
`Checkpoint.summaryBcs` 
`Checkpoint.contentBcs`
Test plan
E2E tests:
`cargo nextest run -p sui-indexer-alt-e2e-tests  -- graphql/checkpoints`
Schema tests:
`cargo nextest run -p sui-indexer-alt-graphql -- schema`
`cargo nextest run -p sui-indexer-alt-graphql --features staging -- schema`
Stack:
https://github.com/MystenLabs/sui/pull/22651 
https://github.com/MystenLabs/sui/pull/22686 
https://github.com/MystenLabs/sui/pull/22688 
https://github.com/MystenLabs/sui/pull/22690 👈
https://github.com/MystenLabs/sui/pull/22691
https://github.com/MystenLabs/sui/pull/22708
---
For …
> graphql-alt: Checkpoint.networkTotalTransactions, Checkpoint.rollingGasSummary, Checkpoint.summaryBcs, Checkpoint.contentBcs

- crates/sui-benchmark/src/lib.rs
- crates/sui-core/src/transaction_driver/mod.rs
- crates/sui-types/src/digests.rs
Enable exercising TD in simtests.
Also, retries `ObjectNotFound` and `DependentPackageNotFound` errors in QD. Because fastpath execution results go to fastpath cache when using TD, making sure QD retrying these errors allow QD and TD to operate on the same objects.
CI
---
> [TD] Use TransactionDriver to submit 50% of benchmark workload in simtests

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/fundSize/fundSize.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/fundSize/fundSize.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements `Epoch.fundSize` based on
https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/epoch.rs#L168-L170
1. Added `fundSize` to the `query.move` snapshot test.
2. Added new `fundSize.move` test file.
3. 
---
> graphql-alt: Add Epoch.fundSize

- crates/bin-version/src/lib.rs
- crates/sui-framework-snapshot/manifest.json
- crates/sui-framework-snapshot/src/main.rs
This PR updates the short shas to full shas where possible in the already existing `sui-framework-snapshot/manifest.json`. The reason for this change is that the new pkg management system benefits from using full shas to avoid downloading the whole history to be able to checkout with only the short sha.
It also adds a new `GIT_FULL_SHA_REVISION` macro on `bin-version` crate to allow us to get the full 40 characters SHA to be used in `update_snapshot` in the `sui-framework-snapshot` crate.
Existing tests
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take …
> [sui-framework-snapshot] Set full shas where possible

- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/error.rs
Implements `From<bcs::Error> for RpcError<E>` to allow using `?` operator.
No functional changes so existing tests should pass.
---
> Implement From<bcs::Error> for RpcError<E>

- external-crates/move/crates/move-package-alt/src/git/cache.rs
- external-crates/move/crates/move-package-alt/src/test_utils/git.rs
- external-crates/move/crates/move-package-alt/src/test_utils/mod.rs
Previously, git would only convert branches to shas, but would fail with tags.
Added a unit test for a valid tag lookup
---
> [pkg-alt] Fix converting tags to git SHAs

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/fundInflow/fundInflow.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/fundInflow/fundInflow.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/fundOutflow/fundOutflow.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/fundOutflow/fundOutflow.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/netInflow/netInflow.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/netInflow/netInflow.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements
1. `Epoch.netInflow` based on https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/epoch.rs#L174-L182
2. `Epoch.fundInflow` based on https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/epoch.rs#L185-L187
3. `Epoch.fundOutflow` based on https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/epoch.rs#L191-L193
1. Added `netInflow`, `fundInflow`, `fundOutflow` to the `query.move` snapshot test.
2. Added new `netInflow.move` test file.
3. Added new `fundInflow.move` test file.
4. Added new `fundOutflow.move` test file.
--- …
> graphql-alt: Add Epoch.netInflow, Epoch.fundInflow, Epoch.fundOutflow

- crates/sui-e2e-tests/tests/passkey_e2e_tests.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_88.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_89.snap
- crates/sui-types/src/passkey_authenticator.rs
- crates/sui-types/src/unit_tests/passkey_authenticator_test.rs
> enable passkey mainnet

- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_88.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_89.snap
Fixing:
```
eugene@eugene-dev ~/code/sui/scripts/compatibility (main) $ ./check-protocol-compatibility.sh mainnet
Found following versions on mainnet:
175 1.52.2-7f45ba185ff0
19 1.51.5-5a3745526511
4 1.52.2-7f45ba185f
2 1.51.5-5a37455265
2 1.49.2-62b9f371e37e
1 1.50.1-197ebfbc1ff0
1 1.48.2-17a9eb8e1914
1 1.47.1-74c8e45b63a1
1 1.46.2-3c894a0ab474
1 1.43.1-b3766e5fed72
Using most frequent version 1.52.2-7f45ba185ff0 for compatibility check
Source commit: 08d9fca206ca63be6e85c30c0b752f08567fa68e
Source branch: main
Checking protocol compatibility with mainnet (7f45ba185ff0)
Checking out mainnet snapshot files
Checking for changes to snapshot files matching *__Mainnet_version_*
Error: Detected changes to snapshot files since 7f45ba185ff0 - not safe to release
diff --git …
```
> remove some autogenerated lines

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_89.snap
Validator side logic, although still experimental, is ready to be enabled on public testnet.
CI
---
> [MFP] enable validator logic in testnet

- crates/sui-e2e-tests/tests/address_balance_tests.rs
- crates/sui-json-rpc-types/src/displays/transaction_displays.rs
- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-open-rpc/spec/openrpc.json
- sui-execution/latest/sui-adapter/src/execution_value.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
This PR accepts (but ignores) withdraw reservation arguments in a transaction.
This will allow us to provide withdraw reservation in a transaction and test balance withdraw scheduling end to end.
CI
---
> Accept balance withdraw in execution layer

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/timestamp.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/timestamp.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implement `timestamp` field support for `TransactionEffects` type.
Reference: Based on legacy implementation in sui/crates/sui-graphql-rpc/src/types /transaction_block_effects.rs
```
```
---
- #22789 
- #22790 
- #22822 
- #22823 ⬅️
> [graphql-alt] Support timestamp for TransactionEffects

- crates/sui-indexer-alt-jsonrpc/src/api/transactions/filter.rs
- crates/sui-indexer-alt-jsonrpc/src/api/transactions/mod.rs
- crates/sui-indexer-alt-jsonrpc/src/data.rs
- crates/sui-indexer-alt-jsonrpc/src/metrics/mod.rs
We have observed some unexplained high e2e latencies of jsonrpc-alt requests that might be related to multiple high-latency read retries from the kv store. This PR adds a metric recording the number of read retries per request, in order to better explain the high latencies.
Ran rpc server locally and existing tests.
---
> [rpc-alt] record the number of read retries per request

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/epoch.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/epoch.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implement `epoch` field support for `TransactionEffects` type.
Reference: Based on legacy implementation in sui/crates/sui-graphql-rpc/src/types /transaction_block_effects.rs
```
```
---
- #22789 
- #22790 
- #22822 
- #22823 
- #22825 ⬅️
> [graphql-alt] Support epoch for TransactionEffects

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/events.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/events.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/event.rs
- crates/sui-indexer-alt-graphql/src/api/types/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implement `events` field for `TransactionEffects` type.
Within this PR, I also create a scheme for new `Event` type with following fields:
* eventBcs
* sequenceNumber
* sender
* transaction
* timestamp
Currently, we cannot support 2 fields `sendingModule` and `contents` as `MoveModule` ([DVX-1205](https://linear.app/mysten-labs/issue/DVX-1205/movemodule)) and `MoveValue` ([DVX-1206](https://linear.app/mysten-labs/issue/DVX-1206/movevalue)) have not yet been supported. I already added a TODO to support that field later after getting unblocked.
```
```
---
- #22789 
- #22790 
- #22822 
- #22823 
- …
> [graphql-alt] Support events for TransactionEffects

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/execution_error.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/execution_error.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/execution_error.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implement `constant` field support for `ExectionError` type.
```
```
---
- #22791
- #22864 
- #22865
- #22866 
- #22867 ⬅️
> [graphql-alt] Support constant for ExectionError

- crates/sui-core/src/authority/authority_test_utils.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/execution_cache/unit_tests/writeback_cache_tests.rs
- crates/sui-core/src/test_utils.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/batch_transaction_tests.rs
- crates/sui-core/src/unit_tests/gas_tests.rs
- crates/sui-core/src/unit_tests/transaction_tests.rs
- crates/sui-core/src/unit_tests/transfer_to_object_tests.rs
- crates/sui-cost/tests/empirical_transaction_cost.rs
- crates/sui-e2e-tests/tests/full_node_tests.rs
- crates/sui-e2e-tests/tests/party_objects_tests.rs
- crates/sui-e2e-tests/tests/protocol_version_tests.rs
- crates/sui-e2e-tests/tests/rpc/main.rs
- crates/sui-indexer-alt-e2e-tests/tests/consistent_store_list_owned_objects_tests.rs
- crates/sui-open-rpc/src/examples.rs
- crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs
- crates/sui-sdk/src/wallet_context.rs
- crates/sui-single-node-benchmark/src/tx_generator/move_tx_generator.rs
- crates/sui-storage/tests/key_value_tests.rs
- crates/sui-test-transaction-builder/src/lib.rs
- crates/sui-transaction-builder/src/lib.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/messages_checkpoint.rs
- crates/sui-types/src/programmable_transaction_builder.rs
- crates/sui-types/src/transaction.rs
- crates/sui-types/src/unit_tests/messages_tests.rs
- Enables sui CLI `transfer` command to work on party input objects
- Unifies separate functions for FullObjectRef vs. ObjectRef transfers and updates all callers/tests
Many tests updated
---
> Use FullObjectRef everywhere for transfers

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/query.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements `Epoch.liveObjectSetDigest` based on
https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/epoch.rs#L214-L228
Added `liveObjectSetDigest` to the `query.move` snapshot test.
---
> graphql-alt: Add Epoch.liveObjectSetDigest

- external-crates/move/crates/move-cli/src/base/test.rs
- external-crates/move/crates/move-package-alt-compilation/src/compiled_package.rs
- external-crates/move/crates/move-package-alt/src/cli/build.rs
- external-crates/move/crates/move-package-alt/src/compatibility/legacy_parser.rs
- external-crates/move/crates/move-package-alt/src/graph/linkage.rs
- external-crates/move/crates/move-package-alt/src/graph/mod.rs
- external-crates/move/crates/move-package-alt/src/package/package_impl.rs
- external-crates/move/crates/move-package-alt/src/package/root_package.rs
Fixes:
1. Uses the linkage table & unpublished addresses to remove duplicates
2. Uses the manifest's edition to pass in the compiler
---
> [pkg-alt] Use linkage table to list packages, instead of having duplicates

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/gas_effects.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/gas_effects.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/gas_effects.rs
- crates/sui-indexer-alt-graphql/src/api/types/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implement `gas_effects` field support for `TransactionEffects` type.
Reference: Based on legacy implementation in sui/crates/sui-graphql-rpc/src/types /transaction_block_effects.rs
```
```
---
- #22789 
- #22790 
- #22822 ⬅️
> [graphql-alt] Support GasEffects for TransactionEffects

- crates/sui-protocol-config/src/lib.rs
- crates/sui-transaction-builder/src/lib.rs
- crates/sui/src/client_commands.rs
- crates/sui/tests/cli_tests.rs
Makes it easy to transfer an object to single-address party ownership (ConsensusAddressOwned).
Manual testing
---
> Add `party-transfer` command to sui CLI tool

- external-crates/move/crates/move-analyzer/src/symbols/compilation.rs
- external-crates/move/crates/move-analyzer/src/symbols/mod.rs
This PR fixes merge between new and cached program components in the face of incremental compilation. The new algorithm is really simple. As input, we have a list of modified files, and a mapping from hashes to file paths for both the new version of the (compiled) program and the cached version of the (compiled) program. In order to determine if the module has been modified or not (and thus whether we need a new version or the cached version), we get the path for the module based on its hash from the respective map and check if that path is in the modified files set
Tested manually that the whole thing works correctly now
> [move-ide] Fixed cached and new program components merge

- crates/sui-adapter-transactional-tests/tests/upgrade/multiple_diff_deps.move
- crates/sui-adapter-transactional-tests/tests/upgrade/multiple_diff_deps.snap
- crates/sui-adapter-transactional-tests/tests/upgrade/multiple_diff_deps@v2.snap
- crates/sui-core/src/unit_tests/data/move_package/F/Move.toml
- crates/sui-core/src/unit_tests/data/move_package/F/sources/f.move
- crates/sui-core/src/unit_tests/data/move_package/H/Move.toml
- crates/sui-core/src/unit_tests/data/move_package/H/sources/f.move
- crates/sui-core/src/unit_tests/move_package_tests.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/linkage/config.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/linkage/legacy_linkage.rs
Use `add_and_unify` to build the publication and upgrade linkages instead of just directly building it up.
Ran some local tests 
---
> [static-ptbs] unify publication linkages

- external-crates/move/crates/move-trace-format/Cargo.toml
- external-crates/move/crates/move-trace-format/src/format.rs
Remove `arbitrary_precision` feature flag from the `move-trace-format` crate as it is no longer needed after we switched to a typed-serialized value representation.
CI + new tests to make sure we handle numbers that are outside the normal `Number` ranges in JSON.
---
> [move][trace-format] remove `arbitrary_precision` requirement for `serde_json`

- crates/sui-core/src/unit_tests/wait_for_effects_tests.rs
- crates/sui-types/src/error.rs
* Adding some errors that should not be retriable during tx submission. We can probably expand the list, but used only the ones that look certain that shouldn't be retried
* Exercise the vote reject cache on the `wait_for_effects` integration test.
CI
---
> [MFP] enhance non-retryable error list & test 

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/genesis.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/genesis.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/object.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/genesis.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/mod.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
This is the first PR to support `TransactionKind` for `Transaction`:
1. Implement a foundation for `TransactionKind` type by using Union which allows us to easily add other types (e.g. ChangeEpochTransaction, Programmable, etc) in upcoming PRs
2. Implement the first kind `GenesisTransaction`
```
```
---
- #22652 
- #22718 
- #22788 
- #22943 ⬅️
For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and …
> [graphql-alt] Support GenesisTransaction kind for TransactionKind [1/n]

- crates/sui-indexer-alt-graphql/src/api/types/object.rs
The previous implementation of object version pagination resulted in an index scan backwards that could, in pathological cases, end up scanning through an object's full history (for example if a version lowerbound was given which was actually in the future.
The core issue was that the query planner did not know that object versions grew monotonically with checkpoint sequence numbers. The new implementation gives the query planner this information by translating the checkpoint bound into a version bound.
Run the existing E2E tests, for correctness:
```
$ cargo nextest run -p sui-indexer-alt-e2e-tests -- graphql
```
Run the following GraphQL queries, which would previously have taken a long time to run:
```graphql
query InFuture {
objectVersions(address:"0x6", filter: {afterVersion: …
```
> graphql-alt: improve object version pagination performance

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/consensus_commit_prologue.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/consensus_commit_prologue.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/consensus_commit_prologue.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/mod.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Adding the new `ConsensusCommitPrologueTransaction` as a new enum field within `TransactionKind` union
```
```
---
- #22652 
- #22718 
- #22788 
- #22943
- #22950 ⬅️
> [graphql-alt] Support ConsensusCommitPrologueTransaction kind for TransactionKind [2/n]

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/randomness_state_update.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/randomness_state_update.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/randomness_state_update.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Adding the new `RandomnessStateUpdate` as a new enum field within `TransactionKind` union
The new schema is on par with old GraphQL schema: https://github.com/MystenLabs/sui/blob/b8d28ddbd06253373d2c02d001b3ba6c1ce8ea4f/crates/sui-graphql-rpc/schema.graphql#L3449-L3466
```
```
---
- #22652 
- #22718 
- #22788 
- #22943
- #22950
- #22953 ⬅️ …
> [graphql-alt] Support RandomnessStateUpdate kind for TransactionKind [3/n]

- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/change_epoch.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/mod.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Adding the new `ChangeEpochTransaction` as a new enum field within `TransactionKind` union
The new schema is on par with old GraphQL schema:
https://github.com/MystenLabs/sui/blob/b8d28ddbd06253373d2c02d001b3ba6c1ce8ea4f/crates/sui-graphql-rpc/schema.graphql#L355-L391
There are 2 points that are worth mentioning:
1. systemPackages is blocked by MovePackage work ([DVX-818](https://linear.app/mysten-labs/issue/DVX-818/movepackage)), and I have added a TODO to add it later.
2. no snapshot tests for this as this is already deprecated in protocol, and `Simulacrum` crate is just having support for `EndOfEpochTransaction`, which will be added in upcoming PRs
``` …
```
> [graphql-alt] Support ChangeEpochTransaction kind for TransactionKind [4/n]

- crates/sui-benchmark/tests/simtest.rs
- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/execution_time_estimator.rs
- crates/sui-swarm-config/src/network_config_builder.rs
- crates/sui-swarm/src/memory/swarm.rs
- crates/test-cluster/src/lib.rs
[Cherrypick] Do not inject simulated execution latency by default
Cherry-picking commit eecbb502a64daf708c8c086e6a797e5811c3e7d4 from main branch.
Original PR: #22978
This cherry-pick brings the fix to the 1.53 release branch.
> [Cherrypick] Do not inject simulated execution latency by default

- Cargo.lock
- crates/mysten-common/Cargo.toml
- crates/mysten-common/src/logging.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/execution_scheduler/execution_scheduler_impl.rs
Also, we no longer panic for debug_fatal in antithesis. This is preferable because now we can both:
- learn that debug_fatal was hit in antithesis
- find out if the fact that we hit debug_fatal leads to even worse problems later
> Use antithesis_sdk::assert_unreachable to get better reports

- Cargo.lock
- crates/sui-pg-db/Cargo.toml
- crates/sui-pg-db/src/lib.rs
- crates/sui-pg-db/src/tls.rs
Extend sui-pg-db to provide TLS support that diesel-async doesn't offer through its connection methods by default. Two new fields on `DbArgs`, `tls_verify_cert` and `tls_ca_cert_path` which defaults to false and None.
If `tls_verify_cert` is true, attempt to verify server cert with root certs, and if `tls_ca_cert_path`, tries to parse PEM or DER certificates.
The new default is TLS-enabled, no server cert verification, like libpq. Still works if db url explicitly has `?sslmode=disable`, or `=prefer` or left empty.
Locally, created self-signed CA certificate
Configured PostgreSQL to require SSL-only connections (hostssl entries, commented out plain host entries)
Verified server rejects plain connections: sslmode=disable properly fails with "no encryption" error
Then `cargo run` …
> [sui-pg-db][sui-indexer-alt] support tls/ssl connections to postgres

- crates/sui-config/src/node.rs
- crates/sui-core/src/unit_tests/execution_driver_tests.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
These thresholds are meant only as a backstop to protect against failure of scheduling-time congestion control. The existing values were low enough to prevent tx from being signed under normal conditions.
---
> Increase signing-time congestion check thresholds

- crates/sui-config/src/node.rs
- crates/sui-core/src/unit_tests/execution_driver_tests.rs
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
These thresholds are meant only as a backstop to protect against failure of scheduling-time congestion control. The existing values were low enough to prevent tx from being signed under normal conditions.
---
--- …
> Cherry-pick: Increase signing-time congestion check thresholds (#22998)

- crates/sui-adapter-transactional-tests/tests/init/tx_digest.move
- crates/sui-adapter-transactional-tests/tests/init/tx_digest.snap
- crates/sui-adapter-transactional-tests/tests/init/tx_digest@v2.snap
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/values.rs
- I fixed TxContext borrowing but forgot to fix it for init, whoops
- New test (verified it hit the bug without the fix)
---
> [static ptb] Fix init

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/end_of_epoch.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/end_of_epoch.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/end_of_epoch.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/mod.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Adding the new `EndOfEpochTransaction` as a new enum field within `TransactionKind` union.
The new schema is on par with old GraphQL schema:
https://github.com/MystenLabs/sui/blob/b8d28ddbd06253373d2c02d001b3ba6c1ce8ea4f/crates/sui-graphql-rpc/schema.graphql#L1042-L1047
This PR only supports the enum `ChangeEpochTransaction`. Other types will be added in upcoming PRs
```
```
---
- #22652 
- #22718 
- #22788 
- #22943
- #22950
- #22953
- #22955 
- #22972 
- #22989 ⬅️ …
> [graphql-alt] Support EndOfEpoch-ChangeEpochTransaction kind for TransactionKind [6/n]

- crates/simulacrum/src/lib.rs
- crates/sui-graphql-rpc/src/test_infra/cluster.rs
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/end_of_epoch.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/end_of_epoch.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/end_of_epoch.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
- crates/sui-indexer/tests/ingestion_tests.rs
- crates/sui-transactional-test-runner/src/args.rs
- crates/sui-transactional-test-runner/src/lib.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
Support all empty variants of `EndOfEpoch`:
* AuthenticatorStateCreate,
* RandomnessStateCreate,
* CoinDenyListStateCreate,
* StoreExecutionTimeObservations,
* AccumulatorRootCreate,
The new schema is on par with old GraphQL schema:
https://github.com/MystenLabs/sui/blob/b8d28ddbd06253373d2c02d001b3ba6c1ce8ea4f/crates/sui-graphql-rpc/schema.graphql#L1049
For testings, not all types are simple to support and I just added supports for `RandomnessStateCreateTransaction`, `AuthenticatorStateCreateTransaction`, and `CoinDenyListStateCreateTransaction`
```
```
---
- #22652 
- #22718 
- #22788 
- #22943
- …
> [graphql-alt] Support all empty types for EndOfEpoch kind for TransactionKind [7/n]

- crates/sui-indexer-alt-e2e-tests/README.md
Add instructions to output cluster logs in tests to help with debugging.
No tests needed for readme update.
---
> sui-indexer-alt-e2e-tests: add steps to output cluster logs in tests

- external-crates/move/crates/move-vm-runtime/src/unit_tests/vm_arguments_tests.rs
the CompiledModule::serialize has cfg test and errors out on `cargo test` for vm_arguments_tests.rs
cargo test
---
> Use serialize_with_version to get around build error

- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/test_authority_clients.rs
- crates/sui-core/src/transaction_driver/effects_certifier.rs
- crates/sui-core/src/transaction_driver/error.rs
- crates/sui-core/src/transaction_driver/message_types.rs
- crates/sui-core/src/transaction_driver/unit_tests/effects_certifier_tests.rs
- crates/sui-core/src/unit_tests/submit_transaction_tests.rs
- crates/sui-core/src/unit_tests/wait_for_effects_tests.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/messages_grpc.rs
When a validator observes consensus rejecting a txn but did not reject the txn itself, do not treat its WaitForEffects response an error. This allows more accurate categorization of errors when there are conflicting votes on the transaction. For example when there are f+1 lock conflict errors and 2f accept votes on a transaction, current logic will abort with retriable error after seeing enough accept votes. After this change, EffectsCertifier will wait until f+1 lock conflict errors are observed and do not retry the txn afterwards.
Change RPC API to support this. Also change RPC API to allow submitting multiple transactions in the same request.
CI & PT
--- …
> [TD] improve handling of transactions rejected by consensus but accepted by some validators

- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/safe_client.rs
- crates/sui-core/src/transaction_driver/request_retrier.rs
- crates/sui-core/src/unit_tests/authority_aggregator_tests.rs
- crates/sui-core/src/unit_tests/unit_test_utils.rs
These logic are unused now.
CI
---
> Remove unused transaction_info request logic in authority aggregator

- external-crates/move/documentation/spec/vm.md
Fixed broken internal link references in Move VM specification document by correcting anchor case format and removing invalid links, eliminating 404 errors during document navigation.
> docs: Fix broken internal links

- docs/content/concepts/cryptography/transaction-auth/intent-signing.mdx
- docs/content/concepts/cryptography/transaction-auth/keys-addresses.mdx
- docs/content/concepts/cryptography/transaction-auth/multisig.mdx
- docs/content/concepts/cryptography/transaction-auth/offline-signing.mdx
- docs/content/concepts/cryptography/transaction-auth/signatures.mdx
Adding description and keyword frontmatter to the `concepts/cryptography/transaction-auth` pages.
Also a few misc capitalization/spelling fixes.
N/A - docs
---
> docs: Add frontmatter to `concepts/cryptography/transaction-auth` pages

- crates/sui-core/src/authority/consensus_quarantine.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-protocol-config/src/lib.rs
Pending checkpoint height is computed in `calculate_pending_checkpoint_height()` with consensus round as input. One consensus commit results in one pending checkpoint and checkpoint height. But a consensus commit and pending checkpoint can result in building multiple actual checkpoints when the commit contains more transactions than `max_transactions_per_checkpoint`. So multiple (built) checkpoints can share the same commit height and we cannot assert on (built) checkpoint height always increasing.
The original problem can be observed by using `max_transactions_per_checkpoint = 10` in simtests.
CI
---
For each box you select, include information after the relevant heading …
> Allow checkpoint height to be non-increasing

- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/transaction_driver/error.rs
- crates/sui-core/src/transaction_driver/mod.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-e2e-tests/tests/full_node_tests.rs
- crates/sui-e2e-tests/tests/transaction_orchestrator_tests.rs
- crates/sui-json-rpc/src/error.rs
- crates/sui-node/src/lib.rs
- crates/sui-rpc-api/src/error.rs
- crates/sui-types/src/quorum_driver_types.rs
Additional changes
- Check for effects after handle_vote_transaction failures
- Add both TD & QD to subscription stream provided by TO
- Dedupe tx submitted by either TD or QD
---
> Enable 50% TD through TO in simtests

- docs/content/guides/developer/first-app/build-test.mdx
- docs/content/guides/developer/first-app/client-tssdk.mdx
- docs/content/guides/developer/first-app/debug.mdx
- docs/content/guides/developer/first-app/publish.mdx
- docs/content/guides/developer/first-app/write-package.mdx
Adding description and keyword frontmatter to the `first-app` pages.
N/A
---
> docs: add frontmatter to `first-app` pages

- docs/content/guides/developer/getting-started/connect.mdx
- docs/content/guides/developer/getting-started/data-serving.mdx
- docs/content/guides/developer/getting-started/get-address.mdx
- docs/content/guides/developer/getting-started/get-coins.mdx
- docs/content/guides/developer/getting-started/graphql-rpc.mdx
- docs/content/guides/developer/getting-started/local-network.mdx
- docs/content/guides/developer/getting-started/sui-install.mdx
Adding description and keyword frontmatter to `getting-started` pages.
N/A
---
> docs: add frontmatter to `getting-started` pages

- crates/sui-core/src/authority/snapshots/sui_core__authority__execution_time_estimator__tests__execution_time_observer_v92.snap
- crates/sui-core/src/consensus_validator.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_91.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_92.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_92.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_91.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_92.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
91 had already been included in 1.54.0
> Move CheckpointSignatureV2 to protocol version 92

- crates/sui-cluster-test/src/cluster.rs
- crates/sui-keys/src/external.rs
- crates/sui-keys/src/keystore.rs
- crates/sui-sdk/src/sui_client_config.rs
- crates/sui-sdk/src/wallet_context.rs
- crates/sui-sdk/tests/tests.rs
- crates/sui/src/client_commands.rs
- crates/sui/src/keytool.rs
- crates/sui/src/sui_commands.rs
- crates/test-cluster/src/lib.rs
Add external signer to SDK
- SuiClientConfig added optional external signer
- try both file based storage and external signer storage when signing/accessing keystore by address
---
> [sdk] add external signer to sui sdk

- crates/sui-benchmark/src/lib.rs
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-json-rpc-types/src/sui_object.rs
This tests the more common full node transaction submission path, and potentially allows edge cases to be handled better with access to authority state.
Avoid calling `ProtocolConfig::get_for_min_version()` from benchmark workloads.
CI
Nightly simtests: https://github.com/MystenLabs/sui/actions/runs/16893267529
> Use fullnode proxy for benchmark worload in simtests

- crates/sui-benchmark/src/drivers/bench_driver.rs
- crates/sui-core/src/transaction_driver/effects_certifier.rs
- crates/sui-core/src/transaction_driver/unit_tests/effects_certifier_tests.rs
Otherwise, TD may keep retrying even though it could have gathered a few more responses and see a non-retriable aggregated error.
CI
PT
---
> [TD] return aggregated retriable error only when non-retriable error becomes impossible

- Cargo.lock
- Cargo.toml
- crates/sui-indexer-alt-jsonrpc/Cargo.toml
- crates/sui-indexer-alt-jsonrpc/src/lib.rs
- crates/sui-indexer-alt-jsonrpc/src/metrics/middleware.rs
- crates/sui-indexer-alt-jsonrpc/src/metrics/mod.rs
Cancelled jsonrpc-alt requests are not logged or recored by success/failure metrics because they never reach deeply enough into the `MetricsFuture::poll` method because the future is still in pending state when the request is cancelled. A `Drop` implementation is needed to capture cancelled requests. Since the `inner` of `MetricsFuture` is pinned by `pin_project` where a regular `Drop` impl is not allowed, a `PinnedDrop` impl is needed. This PR implements that. More context under [this thread](https://mysten-labs.slack.com/archives/C08FWRBHW82/p1754118272614949?thread_ts=1754089823.227799&cid=C08FWRBHW82).
Also logging is added for slow requests even when they succeed to finish.
Tested locally by simulating a long request with `sleep`:
```
2025-08-11T05:37:01.584092Z  INFO …
```
> [rpc-alt] implement PinnedDrop for MetricsFuture

- Cargo.lock
- crates/sui-core/src/authority.rs
- crates/sui-e2e-tests/Cargo.toml
- crates/sui-e2e-tests/tests/randomness_tests.rs
- crates/sui-e2e-tests/tests/zklogin_tests.rs
- crates/sui-framework-snapshot/tests/compatibility_tests.rs
Some of the state creation tests were problematic due to very very large protocol version bumps on a single epoch (e.g., 22 -> 90). This would cause issues with execution versioning, and other features that may have had intermediate protocol gates that were skipped over.
This also updates the snapshot compatibility tests to only test back 10 snapshots instead of the entire history, as otherwise binary compatibility and how that has evolved over the lifespan of the network becomes an issue and is overly restrictive (e.g., being able to deserialize the current framework with the binary config from protocol version 2 isn't guaranteed, and too restrictive of a requirement).
---
Check each box that your changes affect. If none of the boxes relate to your changes, …
> [sui-framework] Update snapshot compatibility test

- Cargo.lock
- Cargo.toml
- scripts/simtest/cargo-simtest
- scripts/simtest/config-patch
cargo deny is failing. See: https://github.com/MystenLabs/sui/actions/runs/16915822740/job/47929366066
Ran: `cargo update -p slab`
---
> Fix cargo-deny, upgrade slab

- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc_fn_delegation_tests.rs
- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-package-management/src/lib.rs
- crates/sui-source-validation/src/tests.rs
- crates/sui-test-transaction-builder/src/lib.rs
- crates/sui/tests/cli_tests.rs
Make them struct methods instead of open functions.
CI
---
> Make a few APIs in SuiTransactionBlockResponse more discoverable

- crates/sui-indexer-alt-e2e-tests/tests/jsonrpc_fn_delegation_tests.rs
Changing the epoch duration to 5 minutes so we don't accidentally trigger epoch changes in this test, which can change the response of stake and validator related tests.
---
> [easy][rpc-alt] use longer epoch duration to avoid flaky tests

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-types/src/transaction.rs
Otherwise, transactions using already consumed input objects can wait unnecessarily long.
CI
Nightly simtest: https://github.com/MystenLabs/sui/actions/runs/16927743964
> [TD] avoid waiting for unavailable input objects

- crates/sui-core/tests/staged/sui.yaml
- crates/sui-e2e-tests/tests/address_balance_tests.rs
- crates/sui-types/src/accumulator_root.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/unit_tests/accumulator_types_tests.rs
Use an efficient type representation for balance accumulators, to save over 100 bytes per accumulator object.
This also makes accumulators easier to work with, as they can be identified without deeply nested type comparisons.
> Efficient type representation for balance accumulator types

- crates/sui-rpc-benchmark/src/bin/pull_grafana_logs.rs
- crates/sui-rpc-benchmark/src/json_rpc/runner.rs
The sui-rpc-benchmark tool currently only supports fetching logs from the edge proxy which can contain requests from all over. This PR adds support for fetching logs from the mainnet proxy as well, which only contains the requests we care about.
Tested fetching locally.
---
> [rpc-benchmark] add support to pull logs from mainnet jsonrpc-alt proxy

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/dependencies.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/dependencies.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implement `dependencies` field support for TransactionEffects type.
```
```
---
- #22789 
- #22790 
- #22822 
- #22823 
- #22825 
- #22835
- #22843 
- #22873
- #23106 ⬅️
> [graphql-alt] Support dependencies for TransactionEffects

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/programmable/split_coins.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/programmable/split_coins.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/programmable/commands/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/programmable/commands/split_coins.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Support `SplitObjects` command for Programmable TransactionKind
The new schema is on par with old schema:
https://github.com/MystenLabs/sui/blob/b8d28ddbd06253373d2c02d001b3ba6c1ce8ea4f/crates/sui-graphql-rpc/schema.graphql#L3715-L3724
```
```
---
- #22997 
- #23000 
- #23008
- #23009 
- #23010 ⬅️
> [graphql-alt] Support SplitObjects command for Programmable TransactionKind [5/n]

- external-crates/move/Cargo.lock
- external-crates/move/crates/move-package-alt-compilation/Cargo.toml
- external-crates/move/crates/move-package-alt-compilation/src/compiled_package.rs
- external-crates/move/crates/move-package-alt-compilation/tests/install_dir_tests.rs
This PR fixes the issue with `--install-dir` not being used for saving the build artifacts.
Added new tests.
```
cargo nextest run -p move-package-alt-compilation
```
---
> [pkg-alt] Use install dir when passed to the build config

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/programmable/publish.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/programmable/publish.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/programmable/commands/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/programmable/commands/publish.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Support `Publish` command for Programmable TransactionKind
The new schema is on par with old schema:
https://github.com/MystenLabs/sui/blob/b8d28ddbd06253373d2c02d001b3ba6c1ce8ea4f/crates/sui-graphql-rpc/schema.graphql#L3217-L3226
```
```
---
- #22997 
- #23000 
- #23008
- #23009 
- #23010
- #23011 
- #23019 ⬅️ …
> [graphql-alt] Support Publish command for Programmable TransactionKind [7/n]

- crates/sui-bridge/src/e2e_tests/basic.rs
- Removes `test_create_bridge_state_object` which is no longer needed since the bridge object exists 
- Removed the test 
---
> Remove outdated bridge test

- crates/sui-adapter-transactional-tests/tests/dynamic_fields/shared_object.snap
- crates/sui-adapter-transactional-tests/tests/programmable_transaction_examples/split_coin_share.snap
- crates/sui-adapter-transactional-tests/tests/programmable_transaction_examples/transfer_shared.snap
- crates/sui-adapter-transactional-tests/tests/shared/become_dynamic_field.snap
- crates/sui-adapter-transactional-tests/tests/shared/become_dynamic_object_field.snap
- crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_make_move_vec.snap
- crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_make_move_vec_fails.snap
- crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_merge_fails.snap
- crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_move_call.snap
- crates/sui-adapter-transactional-tests/tests/shared/by_value_shared_object_deletion_via_move_call_fails.snap
- crates/sui-adapter-transactional-tests/tests/shared/freeze.snap
- crates/sui-adapter-transactional-tests/tests/shared/transfer.snap
- crates/sui-adapter-transactional-tests/tests/shared/wrap.snap
- crates/sui-adapter-transactional-tests/tests/transfer_object/shared.snap
- crates/sui-core/src/authority/snapshots/sui_core__authority__execution_time_estimator__tests__execution_time_observer_v93.snap
- crates/sui-core/src/consensus_validator.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_92.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_93.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_92.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_93.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_93.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-swarm-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- To keep in line with changes of #23163, this disables `per_command_shared_object_transfer_rules`
- Shifts config 92 on main to 93
- Updated tests 
---
> [cherry pick] Disable per_command_shared_object_transfer_rules

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/consensus_tx_status_cache.rs
- crates/sui-core/src/authority/transaction_reject_reason_cache.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/unit_tests/wait_for_effects_tests.rs
Also,
- Track fastpath certified statuses in `ConsensusTxStatusCache`, which will be used in future for end of publish.
- Use the same const across status and reject reason caches for expiration limit.
CI
---
> [mfp] stop fastpath execution when the epoch starts to close

- external-crates/move/crates/language-benchmarks/src/move_vm.rs
- external-crates/move/crates/language-benchmarks/tests/arith.move
- external-crates/move/crates/language-benchmarks/tests/arith_2.move
- external-crates/move/crates/language-benchmarks/tests/basic_alloc.move
- external-crates/move/crates/language-benchmarks/tests/call.move
- external-crates/move/crates/language-benchmarks/tests/call_2.move
- external-crates/move/crates/language-benchmarks/tests/natives.move
- external-crates/move/crates/language-benchmarks/tests/transfers.move
- external-crates/move/crates/language-benchmarks/tests/vector.move
Current setup only looked for function named `bench`. That approach is not scalable to bench all ops and types. This patch enables benching of all functions starting with `bench`. This way every module can test several related things. e.g., arith can test all arithmetic operations.
With this patch the output will have be of form `module_name::function_name`
```
arith.move::bench_add   time:   [5.7281 ms 5.7358 ms 5.7432 ms]
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) low mild
arith_2.move::bench_add time:   [1.3407 ms 1.3494 ms 1.3580 ms]
Found 20 outliers among 100 measurements (20.00%)
7 (7.00%) high mild
13 (13.00%) high severe
basic_alloc.move::bench_inner
time:   [4.9826 ms 4.9929 ms 5.0036 ms]
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild …
```
> Bench all the functions starting with bench in move files

- crates/sui-indexer-alt-e2e-tests/tests/graphql/packages/module_bcs.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/packages/module_bcs.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/move_package.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements `MovePackage.moduleBcs` based on 
https://github.com/MystenLabs/sui/blob/4275c1a55988d28b638be8720aebdf1e7da3b06b/crates/sui-graphql-rpc/src/types/move_package.rs#L564-L573
Added new `moduleBcs` snapshot test.
---
> graphql-alt: Add MovePackage.moduleBcs

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/consensus_tx_status_cache.rs
- crates/sui-core/src/checkpoints/checkpoint_output.rs
- crates/sui-core/src/consensus_adapter.rs
- crates/sui-core/src/consensus_handler.rs
- crates/sui-node/src/lib.rs
Send end of publish (EOP) message when both there is no pending consensus certificates (from QuorumDriver), or `FastpathCertified` status in `ConsensusTxStatusCache` (from TransactionDriver).
Avoid inserting UserTransaction into pending consensus tables. `UserTransaction` from MFP does not need to be reverted on epoch change, or resubmitted after recovery.
This change does not need to be gated behind protocol config. `UserTransaction` will be skipped from `pending_consensus_certificates` after restarting with this change. 
`FastpathCertified` transactions should already be recovered on restart so no additional crash recovery work should be needed.
CI
Nightly simtests: https://github.com/MystenLabs/sui/actions/runs/17062274693
> [MFP] gate sending EndOfPublish with draining FastpathCertified transactions

- .cargo/config.toml
- Cargo.toml
disable mismatched_lifetime_syntaxes lint in the cargo build config and lint config.
cargo build with rust 1.89, no more mismatched_lifetime_syntaxes warnnings.
> chore: disable mismatched_lifetime_syntaxes lint

- crates/sui-rosetta/src/operations.rs
- crates/sui-rosetta/tests/custom_coins_tests.rs
- crates/sui-rosetta/tests/end_to_end_tests.rs
> Rosetta: Handle single GasCoin transfers

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_94.snap
> Enable single-owner party objects on mainnet

- Cargo.lock
- crates/sui-indexer-alt-e2e-tests/tests/graphql/addressable/coins.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/addressable/coins.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/addressable/objects.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/addressable/objects.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/objects/as_move_object.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/objects/as_move_object.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/objects/object_versions.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/objects/object_versions.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/events.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/events.snap
- crates/sui-indexer-alt-graphql/Cargo.toml
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/scalars/json.rs
- crates/sui-indexer-alt-graphql/src/api/scalars/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/event.rs
- crates/sui-indexer-alt-graphql/src/api/types/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/move_object.rs
- crates/sui-indexer-alt-graphql/src/api/types/move_type.rs
- crates/sui-indexer-alt-graphql/src/api/types/move_value.rs
- crates/sui-indexer-alt-graphql/src/api/types/service_config.rs
- crates/sui-indexer-alt-graphql/src/config.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
`MoveValue` exposes a structured representation of a Move value. The implementation uses gRPC's visitor to convert to the Move value to JSON, for consistency.
New E2E tests:
```
$ cargo nextest run -p sui-indexer-alt-e2e-tests -- graphql
```
- #23127 
- #23128 
- #23129 
- #23130 
- #23172 
- #23188
- #23210
---
> graphql-alt: MoveValue

- docs/content/standards/wallet-standard.mdx
This PR updates our Wallet Standard documentation to reflect our new recommendations/patterns. For a summary of changes:
- Updated the documentation around how account authorization works (based on https://github.com/wallet-standard/wallet-standard/pull/128#discussion_r2056842722). Generally, I think using the terminology `connect` is confusing and leads to misunderstandings of how the standard works at a technical level
- Removed the documentation around `reportTransactionEffects` since we are going to deprecate it and don't recommend using it
- Fixed various code typos and syntax errors
JFYI: Some of this is AI generated with manual edits and tweaking so no offense taken for any writing feedback
- https://sui-docs-7xvpqgady-sui-foundation.vercel.app/standards/wallet-standard 👁️ 
--- …
> [docs] update wallet standard docs to be more technically accurate

- Cargo.lock
- crates/simulacrum/Cargo.toml
- crates/simulacrum/src/lib.rs
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/end_of_epoch.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/end_of_epoch.snap
- crates/sui-transactional-test-runner/src/args.rs
End of epoch transaction test uses the current system packages as fixtures, which means that every time someone updates those system packages, they will need to be updated. 
This PR fixed that by implementing `system-packages-snapshot` flag which allows e2e test to use framework snapshot from [`sui-framework-snapshot`](https://github.com/MystenLabs/sui/tree/9dddc8e190f6865574060c8c9f3664c438341b6d/crates/sui-framework-snapshot)
```
cargo nextest run -p sui-indexer-alt-e2e-tests
```
--- …
> [graphql-alt] Implement system-packages-snapshot for end-of-epoch snapshot test

- Cargo.lock
- crates/sui/Cargo.toml
- crates/sui/src/lib.rs
- crates/sui/src/sui_commands.rs
- crates/sui/src/trace_analysis_commands.rs
This adds tha `analyze-trace` command to `sui client` that is meant to house the different trace analysises and adds a `gas-profile` analysis as the first such analysis.
---
> [cli] Add `analyze-trace` command to `sui client` and add `gas-profile` subcommand

- sui-execution/latest/sui-adapter/src/execution_engine.rs
- sui-execution/latest/sui-adapter/src/temporary_store.rs
This updates the expensive ownership invariant checks to handle receiving an object off of a derived address and tightens up some of the invariant enforcement so gas coins are not special-cased.
CI + ran test cases for derived addresses on a separate PR locally against this.
---
> [sui-execution][derived-addresses] Update expensive ownership invariant checks for derived addresses

- crates/sui-indexer-alt-reader/src/bigtable_reader.rs
- crates/sui-indexer-alt-reader/src/events.rs
- crates/sui-indexer-alt-reader/src/kv_loader.rs
- crates/sui-indexer-alt-reader/src/lib.rs
- crates/sui-kvstore/src/bigtable/client.rs
- crates/sui-kvstore/src/lib.rs
Changes:
- Added events.rs module with `TransactionEventsKey` and
`StoredTransactionEvents` types for fetching transaction event data by digest
- `kv_loader.rs` support for loading transaction events from Bigtable and Postgres
- Added`get_events_for_transactions` method to bigtable client
https://github.com/MystenLabs/sui/pull/23222
https://github.com/MystenLabs/sui/pull/23223 👈 
https://github.com/MystenLabs/sui/pull/23224 
```
cargo nextest run -p sui-indexer-alt-graphql schema_sdl
cargo nextest run -p sui-indexer-alt-e2e-tests -- graphql/
```
---
For each box you select, include information after the relevant heading that describes the impact of your changes that a user …
> graphql-alt: reader and kv loader for transaction events [2/n]

- external-crates/move/crates/move-analyzer/editors/code/package-lock.json
- external-crates/move/crates/move-analyzer/editors/code/tsconfig.json
Without the addition in tsconfig, TS compiler could not build the code (`Cannot find name 'Blob'`). Also re-generated lock file
Manually verified that the build succeeds
> [move-ide] Fixed a build error

- crates/sui-config/src/node.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-node/src/lib.rs
Instead of applying checkpoint overrides in CheckpointBuilder, we simply detect and clear invalid local checkpoints when the node starts. This handles both the case when we rebuild a local checkpoint with an different result and the case where we insert a verified checkpoint with a different digest than a locally built checkpoint.
Simtests pass, new UT. verified with one-off devnet test for both txn fork detected and checkpoint fork detected.
---
> Fork recovery: clear local checkpoints on validator start

- crates/sui-indexer-alt-consistent-store/src/db/config.rs
- crates/sui-indexer-alt-consistent-store/src/schema/balances.rs
- crates/sui-indexer-alt-consistent-store/src/schema/mod.rs
- crates/sui-indexer-alt-consistent-store/src/schema/object_by_owner.rs
- crates/sui-indexer-alt-consistent-store/src/schema/object_by_type.rs
- crates/sui-indexer-alt-consistent-store/src/store/mod.rs
Today, we allow database-level configurations, and the consistent store in testnet and mainnet are configured as such:
```
[rocksdb]
write-buffer-size-mb = 4096
max-wal-size-mb = 4096
block-size-kb = 32
block-cache-slots = 8192
db-parallelism = 8
```
The issue is that rocksdb will privilege cf-level configs if provided, and the consistent store code creates default options for all cfs with some cfs having additional configs (set_merge_operator_associative, set_compaction_filter). But this means that the configured values are not being respected, resulting in the cfs defaulting to 65 mb buffer size (memtable) instead of 4096 mb, for example. This PR passes database-level configs to the Schema's `cfs` function as the `base_options` that each cf can then extend on. Later on, we likely want …
> [consistent-store] Respect top-level rocksdb configuration

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/unit_tests/consensus_manager_tests.rs
- crates/sui-node/src/lib.rs
This removes a race condition during the previous shutdown method. What was happening was:
- Validator reconfigures
- We call `abort_all()` on the JoinSet
- The state hasher shuts down first
- builder sends a checkpoint to state hasher
- send() call fails because receiver is closed
- we get a spurious antithesis failure from checkpoint builder failing
> Use within_alive_epoch to shut down checkpoint tasks

- crates/sui-e2e-tests/tests/object_deletion_tests.rs
The removed check could sometimes run after pruning was complete, and fail.
> Remove unneeded check that child is wrapped (fixes `object_pruning_test`)

- crates/sui-replay-2/src/data-stores/data_store.rs
- crates/sui-replay-2/src/execution.rs
- crates/sui-replay-2/src/lib.rs
- crates/sui-replay-2/src/replay_txn.rs
- crates/sui-replay-2/src/summary_metrics.rs
The key change in in data_store.rs and it's picking a proper tokio runtime. The code before was hanging in mysterious ways after a number of transactions. After investigations the hang appeared related to tokio and the runtime picked to block on. The code as is now executes thousands of transactions and it seems stable.
There is a bunch of logging changes that I am adding because they helped me diagnose the issue with the hang/deadlock. Also they provide a good overview of what is going on. So I am leaving them here for now. The file `summary_metrics.rs` si questionable but it is ok for now in my opinion
Run a subset of a few thousands transactions to verify code works
--- …
> tokio runtime fix

- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/latest.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/checkpoints/latest.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/mutation.rs
- crates/sui-indexer-alt-graphql/src/api/query.rs
- crates/sui-indexer-alt-graphql/src/api/types/address.rs
- crates/sui-indexer-alt-graphql/src/api/types/balance.rs
- crates/sui-indexer-alt-graphql/src/api/types/checkpoint/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/dynamic_field.rs
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/api/types/event/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/move_object.rs
- crates/sui-indexer-alt-graphql/src/api/types/move_package.rs
- crates/sui-indexer-alt-graphql/src/api/types/object.rs
- crates/sui-indexer-alt-graphql/src/api/types/protocol_configs.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
- crates/sui-indexer-alt-graphql/src/scope.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
When executing transactions via `executeTransaction`, the effects haven't been indexed into a checkpoint yet. Using the RPC's latest checkpoint as reference is incorrect.
This PR will fix that problem by updating `Scope::checkpoint_viewed_at` from `u64` → `Option<u64>`
**Pattern Applied**
With `checkpoint_viewed_at` being `None` in execution scope, we implemented a consistent "fail early" pattern. For some common operations below, here is what we returned when `checkpoint_viewed_at` is None:
* Pagination (e.g. transaction/mod.rs, event/mod.rs): Return empty Connection
* Object lookups (e.g. object.rs, move_package.rs): Return None or empty contents
* Epoch queries (e.g. epoch.rs): Return None
```
cargo nextest run -p sui-indexer-alt-e2e-tests …
```
> [graphql-alt] Refactor Scope to Optional checkpoint_viewed_at [4/n]

- crates/sui/src/client_commands.rs
This PR fixes the issue for upgrade compatibility checks which appears when trying to do an upgrade with an older CLI than the current protocol version on the network, but without passing the `--verify-compatibility` flag. The code is moved in the if branch as `--verify-compatibility` is false by default.
---
> [cli] Move the protocol config loading into the flag branch

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/filter/affected_address.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/filter/sent_address.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/filter/sent_address.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction/filter.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction/mod.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements the `TransactionFilter.sentAddress` filter both as an extension to the `affectedAddress` filter and as its own filter.
Added a new test case to the `affected_address.move` test and a new `sent_address.move` test file.
---
> graphql-alt: Add TransactionFilter.sentAddress

- crates/sui-indexer-alt-e2e-tests/tests/graphql_execute_transaction_tests.rs
- crates/sui-indexer-alt-graphql/src/api/types/object.rs
- crates/sui-indexer-alt-graphql/src/api/types/object_change.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_effects.rs
- crates/sui-indexer-alt-graphql/src/scope.rs
- crates/sui-indexer-alt-reader/src/kv_loader.rs
- crates/sui-rpc-api/src/client/mod.rs
This PR implements the logic to load object contents (under `objectChanges` in `TransactionEffects`) from just-executed transaction data. This will help us avoid unnecessary DB lookup since the data is already returned by gRPC execution method
```
cargo check -p sui-indexer-alt-graphql
```
---
- #23145 
- #23332 
- #23351 
- #23398
- #23426 ⬅️
> [graphql-alt] Load input and output objects change from just-executed transaction [5/n]

- Cargo.lock
In order to successfully build on my Intel Mac I had to update a `blst` dependency to  "0.3.13". With  the version "0.3.11" I'm getting the following:
```
warning: blst@0.3.11: /var/folders/6v/s4b4wws53_j3ym0gc4wgmzqr0000gn/T/assembly-71e81e.s:8561:1: error: invalid CFI advance_loc expression
warning: blst@0.3.11: .cfi_adjust_cfa_offset 8
warning: blst@0.3.11: ^
warning: blst@0.3.11: ToolExecError: Command env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "--target=x86_64-apple-darwin" "-mmacosx-version-min=15.2" "-Wall" "-Wextra" "-mno-avx" "-fno-builtin" "-Wno-unused-function" "-Wno-unused-command-line-argument" "-D__ADX__" "-o" "/var/folders/6v/s4b4wws53_j3ym0gc4wgmzqr0000gn/T/cargo-installTiPaPX/rel …
```
> Update "blst" from "0.3.11" to "0.3.13" to fix build on x86 Mac

- external-crates/move/crates/move-cli/src/sandbox/commands/publish.rs
- external-crates/move/crates/move-unit-test/src/extensions.rs
- external-crates/move/crates/move-unit-test/src/test_runner.rs
- external-crates/move/crates/move-vm-runtime/src/dev_utils/in_memory_test_adapter.rs
- external-crates/move/crates/move-vm-runtime/src/dev_utils/vm_test_adapter.rs
- external-crates/move/crates/move-vm-runtime/src/execution/vm.rs
- external-crates/move/crates/move-vm-runtime/src/natives/extensions.rs
- external-crates/move/crates/move-vm-runtime/src/natives/functions.rs
- external-crates/move/crates/move-vm-runtime/src/runtime/mod.rs
This wraps the `NativeContextExtensions` in an `Arc<RwLock<` to allow cloneability and interior mutability. We could probably use a `RefCell` or `Mutex` instead of an `RwLock`, but figured this was the most in keeping with what we have elsewhere, and the most "safe" option. Happy to take feedback on it being something else though.
> [1/n][bella-ciao][move-vm] Update native extensions to be cloneable

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/programmable/make_move_vec.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/kind/programmable/make_move_vec.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/move_type.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/programmable/commands/make_move_vec.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/programmable/commands/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction_kind/programmable/mod.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Support a new `type` fields for `MakeMoveVec` as the `MoveType` is available right now.
This field is also available in GraphQL alpha:
https://github.com/MystenLabs/sui/blob/main/crates/sui-graphql-rpc/schema.graphql#L1731
---
> [graphql-alt] Implement type fields for MakeMoveVec

- crates/sui-indexer-alt-e2e-tests/tests/graphql/addressable/transactions.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/addressable/transactions.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/address.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Support a new type `transactions` field for `Address`.
This field is also available in GraphQL alpha:
https://github.com/MystenLabs/sui/blob/2cddd9d8d403e41541a451940ac9f14458b2dba2/crates/sui-graphql-rpc/src/types/address.rs#L160
---
> [graphql-alt] Support Transactions fields for Address

- crates/sui-indexer-alt-e2e-tests/tests/graphql/objects/dynamic_field.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/objects/dynamic_field.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/address.rs
- crates/sui-indexer-alt-graphql/src/api/types/coin_metadata.rs
- crates/sui-indexer-alt-graphql/src/api/types/dynamic_field.rs
- crates/sui-indexer-alt-graphql/src/api/types/move_object.rs
- crates/sui-indexer-alt-graphql/src/api/types/object.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Add dynamic fields to `Object`. Previously these functions existed on `Address` and on `MoveObject` but not on `Object`, but I spotted based on the example queries that we did used to have it there.
The reason it's not part of the `IAddress` interface is that this would require us to implement it on `MovePackage` where it would be entirely redundant.
Updated E2E tests:
```
$ cargo nextest run -p sui-indexer-alt-e2e-tests -- graphql/objects/dynamic_field
```
---
> graphql-alt: Object.dynamicField et al

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/execution_error.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/execution_error.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/execution_error.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
This PR added support for `message`, `module`, and `function` field for `ExecutionError` given that `module` and `function` is now available.
For `message` field, the implementation is similar to errors field in old GraphQL:
https://github.com/MystenLabs/sui/blob/9940de1951d784eee527cc429e9e391022818679/crates/sui-graphql-rpc/src/types/transaction_block_effects.rs#L123
---
> [graphql-alt] Support message, module, and function in ExecutionError

- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/filter/affected_object.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/filter/affected_object.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/filter/transaction_filter_validator.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transactions/filter/transaction_filter_validator.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/transaction/filter.rs
- crates/sui-indexer-alt-graphql/src/api/types/transaction/mod.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements the `TransactionFilter.affectedObject` filter and adds validation that it cannot be used with `function`, `kind`, or `affectedAddress`.
Adds new `affected_object.move` test file and `transaction_filter_validator.move` test cases.
---
> graphql-alt: Add TransactionFilter.affectedObject

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_96.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Testnet_version_96.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_96.snap
This change makes the current commit handler compatible with the new one, without forcing the new one to mimic the old behavior exactly, which would be awkward
> Change timing of dkg-failure cancellation for easier compatability with new the commit handler.

- crates/sui-adapter-transactional-tests/tests/call/clever_error_code_resolution.move
- crates/sui-adapter-transactional-tests/tests/call/clever_error_code_resolution.snap
- crates/sui-adapter-transactional-tests/tests/call/clever_error_code_resolution@v2.snap
- crates/sui-adapter-transactional-tests/tests/derived_objects/claim_twice.snap
- crates/sui-adapter-transactional-tests/tests/derived_objects/claim_twice@v2.snap
- crates/sui-adapter-transactional-tests/tests/programmable/pure_arg_mut.snap
- crates/sui-adapter-transactional-tests/tests/programmable/pure_arg_mut@v2.snap
- crates/sui-graphql-e2e-tests/tests/stable/errors/clever_errors.snap
- crates/sui-graphql-e2e-tests/tests/stable/errors/clever_errors_in_macros.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql/transaction_effects/execution_error.snap
- crates/sui-transactional-test-runner/src/test_adapter.rs
This PR enhances the error reporting in adapter transactional tests by rendering "clever error codes" with their associated line numbers and error codes when Move aborts occur. 
- Updated test adapter to extract line numbers and error codes from abort codes when available
- Added new test case `clever_error_code_resolution.move` to verify the enhanced error reporting
- Updated existing test snapshots to reflect the improved error message format
Previously, Move aborts in tests would display raw abort codes like:
``` 
Move Runtime Abort. Location: sui::derived_object::claim (function index 0) at offset 20, Abort Code: 13835058231375822849
```
Now they provide more readable information:
```
Move Abort in sui::derived_object::claim (function index 0) at offset 20 at line 41 with clever code …
```
> [adapter-tests] Render clever error abort codes/line numbers in adapter transactional tests

- external-crates/move/crates/move-package-alt/DESIGN.md
- external-crates/move/crates/move-package-alt/src/package/paths.rs
- external-crates/move/crates/move-package-alt/src/test_utils/graph_builder.rs
This PR just revisits the design document to bring it in line with what we're currently working on. The important changes are:
- Change from `[published]` section of `Move.lock` to separate `Move.published` file
- Make all operations single-environment
- Remove some of the features around ephemeral environments; our thinking here is changing and I will produce an update in a future PR
- Added some description of compilation and linkage steps
- Clean up TODOs and open questions section
#23356 Misc design doc updates that we're pretty committed to
#23358 Modes to support test-only dependencies
#23429 Ephemeral environments and test-publish
--- …
> [package-alt] updated design doc to reflect what we're doing

- crates/sui-kvstore/src/bigtable/client.rs
Bigtable multi_get does not return the results in order of keys  (digests) resulting in an incorrect mapping between digests and transaction events when zipping keys and results. This leads to incorrect lookups on `Query.events` when trying to map `tx_sequence_numbers` -> `digest` -> `events`
- local test connected to testnet kv and db
---
> graphql-alt: Query.events stable sorting

- crates/sui-indexer-alt-graphql/src/api/query.rs
- crates/sui-indexer-alt-graphql/src/api/types/address.rs
- crates/sui-indexer-alt-graphql/src/api/types/coin_metadata.rs
- crates/sui-indexer-alt-graphql/src/api/types/dynamic_field.rs
- crates/sui-indexer-alt-graphql/src/api/types/move_object.rs
- crates/sui-indexer-alt-graphql/src/api/types/move_package.rs
- crates/sui-indexer-alt-graphql/src/api/types/object.rs
- crates/sui-indexer-alt-graphql/src/api/types/object_filter.rs
This helps distinguish the object filter validator which is a GraphQL input validator with the SUI validator model added in https://github.com/MystenLabs/sui/pull/23582. It follows the naming convention of [TransactionFilterValidator](https://github.com/MystenLabs/sui/blob/2a4de175579d35869f9520d7fdeba375741b5087/crates/sui-indexer-alt-graphql/src/api/types/transaction/filter.rs#L51).
Rename only - no testing changes.
---
> graphql-alt: rename object_filter::Validator to ObjectFilterValidator

- external-crates/move/crates/move-package-alt/src/package/paths.rs
Changes package paths to be relative (but cleaned) instead of canonicalized
---
> [package-alt] clean paths instead of canonicalizing them

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-protocol-config/src/lib.rs
- sui-execution/latest/sui-move-natives/src/accumulator.rs
- sui-execution/latest/sui-move-natives/src/address.rs
- sui-execution/latest/sui-move-natives/src/config.rs
- sui-execution/latest/sui-move-natives/src/crypto/bls12381.rs
- sui-execution/latest/sui-move-natives/src/crypto/ecdsa_k1.rs
- sui-execution/latest/sui-move-natives/src/crypto/ecdsa_r1.rs
- sui-execution/latest/sui-move-natives/src/crypto/ecvrf.rs
- sui-execution/latest/sui-move-natives/src/crypto/ed25519.rs
- sui-execution/latest/sui-move-natives/src/crypto/groth16.rs
- sui-execution/latest/sui-move-natives/src/crypto/group_ops.rs
- sui-execution/latest/sui-move-natives/src/crypto/hash.rs
- sui-execution/latest/sui-move-natives/src/crypto/hmac.rs
- sui-execution/latest/sui-move-natives/src/crypto/nitro_attestation.rs
- sui-execution/latest/sui-move-natives/src/crypto/poseidon.rs
- sui-execution/latest/sui-move-natives/src/crypto/vdf.rs
- sui-execution/latest/sui-move-natives/src/crypto/zklogin.rs
- sui-execution/latest/sui-move-natives/src/dynamic_field.rs
- sui-execution/latest/sui-move-natives/src/event.rs
- sui-execution/latest/sui-move-natives/src/lib.rs
- sui-execution/latest/sui-move-natives/src/object.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/mod.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
- sui-execution/latest/sui-move-natives/src/test_scenario.rs
- sui-execution/latest/sui-move-natives/src/transfer.rs
- sui-execution/latest/sui-move-natives/src/tx_context.rs
- sui-execution/latest/sui-move-natives/src/types.rs
- sui-execution/latest/sui-move-natives/src/validator.rs
Update the last remaining calls to `legacy_size` to use `abstract_memory_size`.
This means that we will no longer have any calls to `legacy_size` in the next execution version (🥳), and  be able to remove it at that time. We should be able to actually convert all the `legacy_size` calls over to `abstract_memory_size` calls today I believe without gating, but decided to keep the old function around + protocol gate just to be on the safe side....
The changes are protocol gated and the protocol config is not enabled. That will be done at a later date :) 
CI -- nothing should change.
--- …
> [3/n][sui-adapter] Update (but dont enable) object runtime to use abstract memory size

- crates/sui-json-rpc-types/src/sui_coin.rs
- crates/sui-json-rpc/src/coin_api.rs
Checking CoinRegistry for metadata/supply before falling back to indexes.
Added unit tests with mocked coin registry data.
> jsonrpc CoinRegistry integration

- sui-execution/latest/sui-adapter/src/data_store/linked_data_store.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/env.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/execution/context.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/linkage/analysis.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/linkage/resolved_linkage.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/loading/ast.rs
- sui-execution/latest/sui-adapter/src/static_programmable_transactions/loading/translate.rs
- sui-execution/latest/sui-adapter/src/type_layout_resolver.rs
In the new VM we no longer need the link context and therefore no longer need a "rooted" linkage so rename it to `ExecutableLinkage` and remove the link context. This cleans up a bunch of little areas where we were creating linkages (esp. from types).
> [3/n][bella-ciao][sui-adapter] Remove link context from `RootedLinkage` and rename to `ExecutableLinkage`

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/validator_set/active_validators.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/validator_set/active_validators.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/mod.rs
- crates/sui-indexer-alt-graphql/src/api/types/validator.rs
- crates/sui-indexer-alt-graphql/src/api/types/validator_set.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
1. Adds `ValidatorSet.activeValidators` based on a new `Validator` type.
2. Implements `Validator` fields that depend on `ValidatorV1`.
Adds a new `active_validators.move` test file. Some fields are currently not populated and are marked with a `todo`.
---
> graphql-alt: Add Validator model with ValidatorV1 fields

- external-crates/move/crates/move-vm-runtime/src/execution/values/values_impl.rs
- external-crates/move/crates/move-vm-runtime/src/unit_tests/value_tests.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/fingerprint.rs
- sui-execution/latest/sui-move-natives/src/object_runtime/object_store.rs
@tnowacki added global value fingerprints to the object runtime a while ago in anticipation of this. This completes the job by removing the hacky global fingerprints that we used as an interim solution in the VM.
This removes mutation tracking for global values from the VM values (and instead this is the underlying responsibility of the runtime). This allows us to simplify the internal representation of global values so they are no longer a four-state value but instead a two-state (empty or filled).
Move tests are green. 
--- …
> [5/n][bella-ciao][values] Remove old global fingerprint for values and use the object runtime's fingerprints

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/scheduler.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/tests.rs
- crates/sui-core/src/execution_scheduler/execution_scheduler_impl.rs
This PR adds reconfigure API to balance withdraw scheduler.
This is necessary because if a node promotes from fullnode to validator during epoch change, we need to set the last settled version at that time, since when the node is running as fullnode we never settle.
---
> Add reconfigure to balance withdraw scheduler

- Cargo.lock
- crates/sui-e2e-tests/tests/rpc/v2/state_service/get_coin_info.rs
- crates/sui-e2e-tests/tests/rpc/v2beta2/live_data_service/get_coin_info.rs
- crates/sui-indexer-alt-e2e-tests/Cargo.toml
- crates/sui-indexer-alt-e2e-tests/packages/coin/sources/my_coin.move
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/burn_only/Move.toml
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/burn_only/sources/burn.move
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/dynamic/Move.toml
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/dynamic/sources/dynamic.move
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/fixed_supply/Move.toml
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/fixed_supply/sources/fixed.move
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/legacy/Move.toml
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/legacy/sources/legacy.move
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/unknown/Move.toml
- crates/sui-indexer-alt-e2e-tests/packages/coin_registry/unknown/sources/unknown.move
- crates/sui-indexer-alt-e2e-tests/src/lib.rs
- crates/sui-indexer-alt-e2e-tests/tests/graphql/coin_metadata.snap
- crates/sui-indexer-alt-e2e-tests/tests/graphql_coin_registry_tests.rs
- crates/sui-indexer-alt-graphql/src/api/types/coin_metadata.rs
- crates/sui-json-rpc-types/src/sui_coin.rs
- crates/sui-json-rpc/src/coin_api.rs
- crates/sui-rpc-api/src/grpc/v2/state_service/get_coin_info.rs
- crates/sui-rpc-api/src/grpc/v2beta2/live_data_service/get_coin_info.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/coin_registry.rs
Support fetching Coin Metadata via the `Currency<T>` objects, rather than via `CoinMetadata<T>`.
New E2E tests:
```
$ cargo nextest run            \
-p sui-indexer-alt-e2e-tests \
--test graphql_coin_registry_tests
```
---
> graphql-alt: Support Coin Registry

- crates/sui-rpc-api/src/grpc/v2/state_service/get_coin_info.rs
- crates/sui-types/src/rpc_proto_conversions.rs
Moving the conversion logic for get_coin_info into the rpc_proto_conversions module to be consistent with other APIs.
Unit tests all pass.
> Move conversions to dedicated conversions module

- crates/sui-rosetta/src/unit_tests/lib_tests.rs
The rosetta test was flaky because it was randomly selecting any coin from the example coin package, including coins using the new coin_registry API (MY_COIN_NEW, REGCOIN_NEW) which require finalize_registration to be called before their metadata is accessible. Since the test never calls finalize_registration, these coins would fail the metadata lookup. The fix ensures the test specifically selects MY_COIN, which uses the old coin::create_currency API that directly creates and freezes metadata without requiring registration.
> Fix non-deterministic metadata query bug

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/validator_set/active_validators.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/validator_set/active_validators.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/address.rs
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/api/types/validator.rs
- crates/sui-indexer-alt-graphql/src/api/types/validator_set.rs
- crates/sui-indexer-alt-graphql/src/scope.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implement `IAddressable` with `Validator` by delegating to the methods on `Address`.
Added new fields to `validator_set.move `.
---
> graphql-alt: Implement IAddressable with Validator

- crates/sui-core/src/accumulators/mod.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/e2e_tests.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/mod.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/naive_scheduler.rs
- crates/sui-core/src/execution_scheduler/balance_withdraw_scheduler/tests.rs
This PR passes the next accumulator version in the BalanceSettlement. This allows us to do invariant check against the internal version tracked by the balance withdraw scheduler. Useful for catching bugs then the scheduler runs out of sync.
---
> Pass next accumulator version to BalanceSettlement

- crates/sui-benchmark/src/lib.rs
- crates/sui-config/src/validator_client_monitor_config.rs
- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/transaction_driver/effects_certifier.rs
- crates/sui-core/src/transaction_driver/metrics.rs
- crates/sui-core/src/transaction_driver/mod.rs
- crates/sui-core/src/transaction_driver/request_retrier.rs
- crates/sui-core/src/transaction_driver/transaction_submitter.rs
- crates/sui-core/src/transaction_driver/unit_tests/effects_certifier_tests.rs
- crates/sui-core/src/transaction_driver/unit_tests/transaction_submitter_tests.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-core/src/unit_tests/submit_transaction_tests.rs
- crates/sui-core/src/validator_client_monitor/mod.rs
- crates/sui-core/src/validator_client_monitor/monitor.rs
- crates/sui-core/src/validator_client_monitor/stats.rs
- crates/sui-core/src/validator_client_monitor/tests.rs
- crates/sui-types/src/messages_grpc.rs
Spinning up a task in transaction driver to periodically send ping requests to measure the e2e latency for every validator for both the:
* fast path
* consensus
CI/PT
---
> [MFP] Run periodic latency checks using the transaction driver

- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__Mainnet_version_96.snap
> [MFP] Enable Mysticeti fastpath handlers on mainnet

- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/transaction_driver/effects_certifier.rs
- crates/sui-core/src/transaction_driver/error.rs
- crates/sui-core/src/transaction_driver/mod.rs
- crates/sui-core/src/transaction_driver/request_retrier.rs
- crates/sui-core/src/transaction_driver/transaction_submitter.rs
- crates/sui-core/src/transaction_driver/unit_tests/effects_certifier_tests.rs
- crates/sui-core/src/transaction_driver/unit_tests/transaction_submitter_tests.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-core/src/unit_tests/submit_transaction_tests.rs
- crates/sui-json-rpc/src/error.rs
- crates/sui-rpc-api/src/error.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/messages_grpc.rs
- crates/sui-types/src/quorum_driver_types.rs
Use finer error categories for RPC error codes.
Use enum to represent request type for RawSubmitTxRequest.
CI
---
> [TransactionDriver] improve error categorization

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/validator_set/active_validators.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/validator_set/active_validators.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/validator.rs
- crates/sui-indexer-alt-graphql/src/api/types/validator_set.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Adds `Validator.asRisk` based on https://github.com/MystenLabs/sui/blob/f0c3f7efc875f000f7bfbdd0a9bbf465a72be1bf/crates/sui-graphql-rpc/src/types/validator.rs#L324-L326
Adds `atRisk` to `active_validators.move` snapshot test with a `todo` to populate it.
---
> graphql-alt: Add Validator.atRisk

- external-crates/move/crates/move-analyzer/editors/code/package-lock.json
- external-crates/move/crates/move-analyzer/editors/code/package.json
- external-crates/move/crates/move-analyzer/src/analyzer.rs
- external-crates/move/crates/move-analyzer/src/code_action.rs
- external-crates/move/crates/move-analyzer/src/completions/mod.rs
- external-crates/move/crates/move-analyzer/src/symbols/compilation.rs
- external-crates/move/crates/move-analyzer/src/symbols/mod.rs
- external-crates/move/crates/move-analyzer/src/symbols/runner.rs
- external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs
This fixes a problem with incremental symbolication. What we attempted before was to collect information about which files are modified (i.e., which ones have to be fully compiled) from the messages sent by the client to the LSP server. In some cases, however, this seemed to have led to problems.
In particular, a file might have been deemed unmodified by the analysis but be actually modified before mapped files structure (including file hashes) used throughout analysis was constructed. This would result in the discrepancy in the hash for this file seen by the compiler (as it would used cached data for this file) and mapped files structure (as it would have a hash after modification). This could cause `move-analyzer` to crash.
This PR implements a much more robust way of determining which …
> [move-ide] Incremental symbolication fix

- external-crates/move/crates/move-package-alt-compilation/src/compiled_package.rs
#23646 don't change to 0 address except for publish
#23643 sui-pkg-alt
#23637 move-cli and move-analyzer tests
---
> [pkg-alt] no longer converting published root package to 0 address

- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-framework/src/mocks/mod.rs
- crates/sui-indexer-alt-framework/src/mocks/store.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/commit_watermark.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/committer.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/reader_watermark.rs
- crates/sui-indexer-alt-framework/src/pipeline/sequential/committer.rs
- crates/sui-indexer-alt-framework/src/pipeline/sequential/mod.rs
- crates/sui-indexer-alt-framework/src/testing/mock_store.rs
Currently, if `first_checkpoint` is configured and a pipeline with no watermark row is added to the indexer, it'll essentially stall since the pipeline's committer task creates a default watermark with checkpoint_hi_inclusive = 0 and waits for this checkpoint. This prevents someone from using `first_checkpoint` to arbitrarily seed the starting point of pipelines for the first time. Consequently, indexer operators have to manually update the watermarks table to set a starting point that isn't 0. 
In this PR, the indexer is now responsible for determining the `next_checkpoint` to commit and make watermark updates for each pipeline. In practice, for a valid `first_checkpoint` (`next_checkpoint`), sequential pipelines will wait to commit the next processed checkpoint after its watermark, …
> [sui-indexer-alt-framework] Address `first_checkpoint` + pipeline with no watermark row commit stall

- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/coin_deny_list_tests.rs
- crates/sui-types/src/deny_list_v1.rs
- crates/sui-types/src/deny_list_v2.rs
- crates/sui-types/src/transaction.rs
- sui-execution/latest/sui-adapter/src/programmable_transactions/context.rs
When checking coin deny list during signing, we also include all the coin types from balance withdraw reservations.
TODO: We also need to do this during execution for coin deny list v2. That's a bit more involving and will come in a separate PR.
Added test
---
> Check coin deny list during signing for address balances

- .gitignore
- CLAUDE.local.md
- CLAUDE.md
- README.md
- crates/sui-e2e-tests/tests/rpc/v2beta2/live_data_service/get_coin_info.rs
- scripts/lint.sh
A few minor housekeeping and convenience items:
- README.md updated to remove pre-Mainnet verbiage
- scripts/lint.sh added to apply all linting and formatting checks to ensure PRs pass CI checks
- CLAUDE.md updated to know about lint.sh
- CLAUDE.md updated to use explicit import of canonical CLAUDE.local.md (refer to [claude docs](https://docs.claude.com/en/docs/claude-code/memory))
- Empty CLAUDE.local.md added for demonstrative purposes
- Build warning suppressed on get_coin_info in test
Ran script on clean workspace
--- …
> Add lint.sh, update CLAUDE.md, minor housekeeping

- crates/sui-indexer-alt-framework/src/lib.rs
- crates/sui-indexer-alt-framework/src/mocks/mod.rs
- crates/sui-indexer-alt-framework/src/mocks/store.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/commit_watermark.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/committer.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/mod.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/pruner.rs
- crates/sui-indexer-alt-framework/src/pipeline/concurrent/reader_watermark.rs
- crates/sui-indexer-alt-framework/src/pipeline/sequential/committer.rs
- crates/sui-indexer-alt-framework/src/pipeline/sequential/mod.rs
Currently, if `first_checkpoint` is configured and a pipeline with no watermark row is added to the indexer, it'll essentially stall since the pipeline's committer task creates a default watermark with checkpoint_hi_inclusive = 0 and waits for this checkpoint. This prevents someone from using `first_checkpoint` to arbitrarily seed the starting point of pipelines for the first time. Consequently, indexer operators have to manually update the watermarks table to set a starting point that isn't 0.
In this PR, the indexer is now responsible for determining the `next_checkpoint` to commit and make watermark updates for each pipeline. In practice, for a valid `first_checkpoint` (`next_checkpoint`), sequential pipelines will wait to commit the next processed checkpoint after its watermark, while …
> [sui-indexer-alt-framework] Address `first_checkpoint` + pipeline with no watermark row commit stall (#23209)

- crates/sui-core/src/jsonrpc_index.rs
My team found a bug in JSON-RPC index store, that causes missing results in the `get_transactions_by_move_function`. The iter bounds are not set correctly.
`'z' > 'Z`, thus max_string should have `'z'` instead of `'Z'`
See also the discussion here for more info: https://github.com/iotaledger/iota/issues/8360
We added a test case.
---
> fix(json-rpc): fix wrong iter bounds that cause missing results in `get_transactions_by_move_function`

- crates/sui-network/src/discovery/mod.rs
Peers in the discovery will send up to `MAX_PEERS_TO_SEND` as a response to `get_known_peers_v2`. In the receiving node, the `own_info` of the sending peer is added to the end of the `found_peers` vector. Later in `update_known_peers` this vector is capped at `MAX_PEERS_TO_SEND` again. This causes that basically no node is able to update their `own_info` if there are more than `MAX_PEERS_TO_SEND` known peers in the network.
---
> fix(discovery): fix processing of `own_info` from peers

- external-crates/move/crates/move-model-2/src/compiled_model.rs
- external-crates/move/crates/move-model-2/src/model.rs
- external-crates/move/crates/move-model-2/src/source_model.rs
This adds a `ModelBuilderConfig` and a flag to allow missing dependencies when generating a move model.
Testing was done downstream in the decompiler.
---
> [move][move-model] Allow missing dependencies via configuration

- crates/sui-kvstore/src/bigtable/client.rs
- crates/sui-kvstore/src/bigtable/init.sh
Alternative implementation of the watermark table.
Instead of using multiple keys and a scan operation, it uses a single key.
For conflict resolution with multiple writers, a timestamp is used (instead of the timestamp watermark itself being passed).
The current version of the client limits the number of returned cell versions to 1, so the latest one (the largest) should be returned.
The same GC policy (maxversions=1) is applied to the table.
This creates a single-key hotspot, so alternative suggestions are welcome, but it may be worth a shot given the poor performance of the existing table
--- …
> [kv store] alternative watermark implementation

- external-crates/move/crates/move-model-2/src/compiled_model.rs
- external-crates/move/crates/move-model-2/src/model.rs
- external-crates/move/crates/move-model-2/src/source_model.rs
- external-crates/move/crates/move-model-2/src/summary.rs
This updates summary generation to use the config, and updates phantom type flag determination to not panic when `allow_missing_deps` is set to true in the config.
Still works, plus downstream decompiler tests no longer panic when resolving types using the summary.
---
> [move][move-model-2] Allow phantom type flags to be missing in summary generation when missing dependencies are allowed.

- crates/sui-display/src/v2/error.rs
- crates/sui-display/src/v2/meter.rs
- crates/sui-display/src/v2/mod.rs
- crates/sui-display/src/v2/parser.rs
Count the number of AST nodes parsed, and the depth that the parser reaches, and make sure they stay within limits, to avoid display strings using too many resources during parsing.
```
sui$ cargo nextest run -p sui-display -- test_metering
```
- #22216
- #22280
---
> display-v2: parser metering

- crates/simulacrum/src/lib.rs
- crates/sui-indexer-alt-consistent-store/src/handlers/mod.rs
- crates/sui-indexer-alt-e2e-tests/tests/consistent_store_list_owned_objects_tests.rs
In Effects V1, the input state of modified objects doesn't include the digest. The consistent store expected the input state to have both the version and the digest, so it wasn't correctly deleting the previous version of the modified object.
New regression test:
```
$ cargo nextest run            \
-p sui-indexer-alt-e2e-tests \
--test consistent_store_list_owned_objects_tests
```
---
> bugfix(consistency): Correctly index Effects V1 input objects

- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/validator_set/report_records.move
- crates/sui-indexer-alt-e2e-tests/tests/graphql/epochs/validator_set/report_records.snap
- crates/sui-indexer-alt-graphql/schema.graphql
- crates/sui-indexer-alt-graphql/src/api/types/epoch.rs
- crates/sui-indexer-alt-graphql/src/api/types/validator.rs
- crates/sui-indexer-alt-graphql/src/api/types/validator_set.rs
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__schema.graphql.snap
- crates/sui-indexer-alt-graphql/src/snapshots/sui_indexer_alt_graphql__tests__staging.graphql.snap
- crates/sui-indexer-alt-graphql/staging.graphql
Implements `reportRecords` based on https://github.com/MystenLabs/sui/blob/7e9cd53ef28bf64470790c6b1ffb978fc07512b7/crates/sui-graphql-rpc/src/types/validator.rs#L329-L364.
The return type is now `Validator` instead of `Address`.
This PR adds new `report_records.move` snapshot test file. Testing pagination is left as a `todo`.
---
> graphql-alt: Add Validator.reportRecords

- crates/sui-core/src/authority.rs
This should suppress the spurious alerts we've been getting for this issue
> Suppress debug_fatal! when validator is simply an old binary

- Cargo.lock
- crates/sui-move-lsp/Cargo.toml
- crates/sui-move-lsp/src/bin/move-analyzer.rs
- crates/sui/src/sui_commands.rs
- external-crates/move/crates/move-analyzer/src/analyzer.rs
- external-crates/move/crates/move-analyzer/src/bin/move-analyzer.rs
- external-crates/move/crates/move-analyzer/src/code_action.rs
- external-crates/move/crates/move-analyzer/src/completions/mod.rs
- external-crates/move/crates/move-analyzer/src/symbols/compilation.rs
- external-crates/move/crates/move-analyzer/src/symbols/mod.rs
- external-crates/move/crates/move-analyzer/src/symbols/runner.rs
- external-crates/move/crates/move-analyzer/tests/ide_testsuite.rs
This PR fixes a long-standing annoyance of unrecognized manifest file fields being incorrectly reported in the logs due to not setting Sui package hooks correctly.
Additionally, this PR makes `move-analyzer` implementation in `external-crates` more Move-flavor independent by moving Sui-specific bits to `crates`
Verified manually that unrecognized field warnings no longer pop up in the logs
> [move-ide] Fixed manifest file warnings

- Cargo.lock
In order to successfully build on my Intel Mac I had to update a `blst` dependency to "0.3.13". With the version "0.3.11" I'm getting the following:
```
warning: blst@0.3.11: /var/folders/6v/s4b4wws53_j3ym0gc4wgmzqr0000gn/T/assembly-71e81e.s:8561:1: error: invalid CFI advance_loc expression
warning: blst@0.3.11: .cfi_adjust_cfa_offset 8
warning: blst@0.3.11: ^
warning: blst@0.3.11: ToolExecError: Command env -u IPHONEOS_DEPLOYMENT_TARGET "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "--target=x86_64-apple-darwin" "-mmacosx-version-min=15.2" "-Wall" "-Wextra" "-mno-avx" "-fno-builtin" "-Wno-unused-function" "-Wno-unused-command-line-argument" "-D__ADX__" "-o" "/var/folders/6v/s4b4wws53_j3ym0gc4wgmzqr0000gn/T/cargo-installTiPaPX/relea …
```
> Update "blst" from "0.3.11" to "0.3.13" to fix build on x86 Mac (#20921)
