MystenLabs/sui

- apps/wallet/src/ui/app/components/receipt-card/index.tsx
- apps/wallet/src/ui/app/redux/slices/txresults/index.ts
> Bug fix on transaction activity 

- sdk/typescript/README.md
Fixes: https://github.com/MystenLabs/sui/issues/7380
> [docs] Fix wrong README code in the typescript sdk

- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
Also ensure we are not skipping checkpoints for the end of epoch case
> [CheckpointExecutor] Bump highest executed metric in end of epoch case

- crates/sui-adapter/src/execution_engine.rs
- crates/sui-cost/tests/snapshots/empirical_transaction_cost__good_snapshot-2.snap
- crates/sui-framework/docs/sui_system.md
- crates/sui-framework/docs/validator.md
- crates/sui-framework/docs/validator_set.md
- crates/sui-framework/sources/governance/sui_system.move
- crates/sui-framework/sources/governance/validator.move
- crates/sui-framework/sources/governance/validator_set.move
- crates/sui-framework/tests/delegation_tests.move
- crates/sui-framework/tests/governance_test_utils.move
- crates/sui-framework/tests/rewards_distribution_tests.move
- crates/sui-framework/tests/validator_set_tests.move
- crates/sui-protocol-constants/src/lib.rs
This PR adds reward slashing to reward distribution.
> use tallying rule results to affect reward distribution

- crates/sui-indexer/migrations/2023-01-16-233119_checkpoint/down.sql
- crates/sui-indexer/migrations/2023-01-16-233119_checkpoint/up.sql
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/handlers/handler_orchestrator.rs
- crates/sui-indexer/src/handlers/mod.rs
- crates/sui-indexer/src/metrics.rs
- crates/sui-indexer/src/models/checkpoint_logs.rs
- crates/sui-indexer/src/models/checkpoints.rs
- crates/sui-indexer/src/models/mod.rs
- crates/sui-indexer/src/schema.rs
- crates/sui-sdk/src/apis.rs
- crates/sui-types/src/messages_checkpoint.rs
Add checkpoint handler to indexer.
This include metrics needed for wave 2:
- total txns since genesis
- total gas cost including computation, storage and rebate since genesis of the current epoch
> indexer: add checkpoint handler

- .changeset/spotty-bags-raise.md
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/providers/provider.ts
- sdk/typescript/src/providers/void-provider.ts
- sdk/typescript/src/types/dynamic_fields.ts
- sdk/typescript/test/e2e/data/dynamic_fields/Move.toml
- sdk/typescript/test/e2e/data/dynamic_fields/sources/dynamic_fields.move
- sdk/typescript/test/e2e/dynamic-fields.test.ts
PR for [#7130](https://github.com/MystenLabs/sui/issues/7130)
- Added methods for getDynamicFields and getDynamicFieldObject
- Added type dynamic fields in ts sdk
> [TypeScript SDK] Add methods for getDynamicFields and getDynamicFieldObject

- Cargo.lock
- crates/sui-rosetta/Cargo.toml
- crates/sui-rosetta/src/account.rs
- crates/sui-rosetta/src/construction.rs
- crates/sui-rosetta/src/operations.rs
- crates/sui-rosetta/src/state.rs
- crates/sui-rosetta/src/types.rs
- crates/sui-rosetta/src/unit_tests/operations_tests.rs
- crates/sui-rosetta/tests/staking_tests.rs
- crates/sui-sdk/Cargo.toml
https://github.com/MystenLabs/sui/issues/6423
https://github.com/MystenLabs/sui/issues/6422
This PR added 2 main features to Sui-rosetta,
1, Account balance query for `LockedSui`, `DelegatedSui` and `PendingDelegation` by using rosetta's sub account.
2, added `Delegation` operation which allow user to delegate Sui and Locked Sui to a validator using rosetta api.
example rosette delegation operation request:
```
curl --location --request POST '0.0.0.0:9003/construction/preprocess' \
--data-raw '{
"network_identifier": {
"blockchain": "sui",
"network": "localnet"
},
"operations": [
{
"operation_identifier": {
"index": 0
},
"type": "Delegation",
"account": {
"address": "0xb5e92aa6556fa0c27c4f6b5a659768b2d4141680"
},
"amount": {
"value": "-1000000", …
```
> [Sui Rosetta] - Delegation and balance queries

- sui_programmability/examples/frenemies/sources/assignment.move
- sui_programmability/examples/frenemies/sources/frenemies.move
- sui_programmability/examples/frenemies/sources/leaderboard.move
- sui_programmability/examples/frenemies/tests/frenemies_tests.move
This will make it easier to show scorecard history
> [frenemies] emit events for scorecard updates

- crates/sui/tests/reconfiguration_tests.rs
Even with https://github.com/MystenLabs/sui/pull/7182, the test case could still fail due to race conditions. 
I don't see a way to remove the race conditions completely so update the test case to tolerate it.
> tolerate reconfig_with_revert_end_to_end_test when tx2 goes through before reconfig

- crates/sui-config/src/node.rs
> enhance key load error

- crates/sui-cost/tests/snapshots/empirical_transaction_cost__good_snapshot-2.snap
- crates/sui-framework/docs/linked_table.md
- crates/sui-framework/docs/object_table.md
- crates/sui-framework/docs/table.md
- crates/sui-framework/sources/linked_table.move
- crates/sui-framework/sources/object_table.move
- crates/sui-framework/sources/table.move
- crates/sui-framework/tests/address_tests.move
- crates/sui-framework/tests/linked_table_tests.move
- Added a linked table type, where the nodes are connected by a doublly linked list.
- Supporting an object variant of this table would be either innefficient or a bit invasive, so it is not included in this PR
> [sui framework] Added Linked Table

- crates/sui-benchmark/src/benchmark_setup.rs
Fullnode client connecting to server and fullnode server spawning race today. PR adds a barrier, so client only connects after the server spawn is done
> Fix race b/w fullnode spawn and fullnode client

- narwhal/consensus/src/consensus.rs
When a node crashes, it is possible for consensus DAG to contain certificates but have never committed any. In this case, the DAG still needs to be recovered from the certificate store. Otherwise, there would be a divergence between certificate store and DAG, which can result in the DAG containing a certificate without necessary parents.
In another PR, I plan to harden consensus a bit on accepting incoming certificates to ensure parents exist or have committed.
Closes #7537
> [Narwhal] Always recover consensus dag on restart

- apps/wallet/src/shared/utils/index.ts
This will let us target features by version and for beta.
> [wallet-ext] Add beta attributes for growthbook

- apps/wallet/src/ui/app/helpers/getEventsSummary.ts
> Fix staking delegation

- apps/wallet/src/ui/app/shared/text/index.tsx
- apps/wallet/src/ui/app/staking/validators/SelectValidatorCard.tsx
- apps/wallet/src/ui/app/staking/validators/ValidatorListItem.tsx
- apps/wallet/src/ui/app/staking/validators/index.tsx
https://user-images.githubusercontent.com/8676844/213897773-84bf14d3-dc00-41c9-8b53-a430a437cce8.mov
https://user-images.githubusercontent.com/8676844/214136581-c5bb37d5-7f20-4b9e-9e97-7b690f5d8c5f.mov
> Wallet sort validator list

- .changeset/metal-flowers-rule.md
- sdk/typescript/src/signers/signer-with-provider.ts
- sdk/typescript/src/types/transactions.ts
Fixes https://github.com/MystenLabs/sui/issues/7536
> use tx gas upper bound without rebate

- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/quorum_driver/tests.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-node/src/lib.rs
- crates/sui-types/src/quorum_driver_types.rs
- crates/sui/tests/full_node_tests.rs
see https://github.com/MystenLabs/sui/pull/7614
> send to effects queue upon failure

- .github/workflows/bench.yml
- .github/workflows/rust.yml
Fixes narwhal benchmark failure: https://github.com/MystenLabs/sui/actions/runs/3992811014/jobs/6848977238#step:8:37
> [Bench] update pyopenssl before running Narwhal benchmark

- apps/wallet/src/ui/app/components/explorer-link/Explorer.ts
- apps/wallet/src/ui/app/components/explorer-link/index.tsx
This shows the explorer link for custom RPC. 
https://user-images.githubusercontent.com/8676844/214201614-f5769a1e-3b28-4ba8-b42d-5d0d8f27a06f.mov
> Enable explorer link on custom RPC

- .github/workflows/e2e.yml
- apps/wallet/tests/utils/auth.ts
Noticed e2e tests for the wallet broke, this fixes them and makes sure they run on wallet PRs.
> [wallet-ext] Fix e2e tests for wallet

- .github/workflows/rust.yml
Test passes: https://github.com/MystenLabs/sui/actions/runs/4000578027/jobs/6865877074
>  Re-enable sui benchmark in ci workflows

- dapps/frenemies/src/components/Card.tsx
- dapps/frenemies/src/components/Layout.tsx
- dapps/frenemies/src/components/Scoreboard/index.tsx
- dapps/frenemies/src/components/leaderboard/Leaderboard.tsx
- dapps/frenemies/src/components/your-score/YourScore.tsx
- dapps/frenemies/src/routes/Home.tsx
- dapps/frenemies/src/utils/useAutoconnect.ts
> [frenemies] Autoconnect and leaderboard

- crates/sui-core/src/authority.rs
- crates/sui-json-rpc-types/src/lib.rs
- crates/sui-json-rpc/src/api.rs
- crates/sui-json-rpc/src/coin_api.rs
- crates/sui-open-rpc/spec/openrpc.json
- sdk/typescript/package.json
- sdk/typescript/test/e2e/utils/setup.ts
Fixed https://github.com/MystenLabs/sui/issues/6120 by normalizing user input
> [rpc] Parse Struct tag for RPC API endpoints

- crates/sui-json-rpc/src/metrics.rs
> [RPC] Track JSON RPC errors in errors_by_route metric

- sdk/typescript/README.md
Add documentation for the new CoinRead endpoints
> Add Documentation for CoinRead endpoints

- apps/wallet/configs/environment/.env.defaults
Don't merge until we're ready for this.
> [wallet-ext] Switch default network to testnet

- apps/explorer/src/context.ts
- apps/explorer/src/hooks/usePageView.ts
- apps/explorer/src/utils/envUtil.ts
This changes the default network to testnet. Do not merge until Testnet is live.
> [explorer] Default network to testnet

- apps/explorer/src/components/HomeMetrics/MetricGroup.tsx
- apps/explorer/src/components/HomeMetrics/index.tsx
- apps/explorer/src/components/node-map/index.tsx
- apps/explorer/src/components/top-validators-card/TopValidatorsCard.tsx
- apps/explorer/src/components/transaction-card/RecentTxCard.module.css
- apps/explorer/src/components/validator/ValidatorMeta.tsx
- apps/explorer/src/components/validator/ValidatorStats.tsx
- apps/explorer/src/context.ts
- apps/explorer/src/hooks/useAppsBackend.ts
- apps/explorer/src/hooks/useFormatCoin.ts
- apps/explorer/src/hooks/useGetObject.ts
- apps/explorer/src/pages/home/Home.tsx
- apps/explorer/src/pages/validators/Validators.tsx
- apps/explorer/src/ui/DescriptionList.tsx
- apps/explorer/src/ui/Stats.tsx
- apps/explorer/src/ui/Text.tsx
- apps/explorer/src/utils/formatAmount.ts
- apps/explorer/src/utils/growthbook.ts
- apps/explorer/tailwind.config.js
- sdk/typescript/src/types/validator.ts
This updates the home page to fetch metrics from the apps backend. Currently metrics aren't stable anywhere, so for now only enabling for testnet and local env.  Also updated some colors that were updated in design.
> [explorer] Home page metrics from indexer

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-types/src/messages_checkpoint.rs
a related convo is here
https://mysten-labs.slack.com/archives/C043CJH1HCK/p1674671492694109
> rpc doc: note of next_epoch_committee in checkpoint summary

- apps/wallet/src/ui/app/staking/validators/SelectValidatorCard.tsx
- apps/wallet/src/ui/app/staking/validators/ValidatorListItem.tsx
- apps/wallet/src/ui/app/staking/validators/ValidatorLogo.tsx
> show validation icon on wallet

- apps/wallet/src/shared/utils/index.ts
- apps/wallet/src/ui/app/experimentation/feature-gating.ts
- apps/wallet/src/ui/index.tsx
This resolves all attributes whenever we set them. This lets us resolve features consistently.
> [wallet-ext] Resolve all attributes always

- crates/sui-framework/sources/tx_context.move
- sui_programmability/examples/games/tests/drand_based_scratch_card_tests.move
- Sui framework dummy_tx_hash_with_hint must be unique per hint
> [sui framework] Fix dummy_tx_hash_with_hint

- narwhal/primary/src/metrics.rs
- narwhal/primary/src/proposer.rs
Addressing feedback from https://github.com/MystenLabs/sui/pull/7730
> [Narwhal] improve proposer metrics

- apps/explorer/src/components/HomeMetrics/index.tsx
- apps/explorer/src/components/recent-packages-card/RecentPackagesCard.tsx
This fixes the text overflow issue on the homepage metrics, and also bumps recent modules to 10.
> [explorer] Homepage UI tweaks

- dapps/frenemies/src/utils/coins.ts
It was selecting the biggest gas instead of the smallest
> [frenemies] fix gas selection

- apps/explorer/src/components/validator/calculateAPY.ts
- apps/wallet/src/ui/app/staking/calculateAPY.ts
> Set APYs greater than 100_000 percent to 0

- apps/wallet/src/ui/app/staking/getStakingRewards.ts
- apps/wallet/src/ui/app/staking/stake/StakeForm.tsx
- apps/wallet/src/ui/app/staking/stake/StakingCard.tsx
- apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx
- Removed the form component from unstake 
- added Available SUI balance
- Fixed unstaking bug requiring Amount field
- set rewards to absolute value. 
- fixed typo
> Wallet fix unstaking bug

- apps/wallet/src/ui/app/staking/stake/StakeForm.tsx
- apps/wallet/src/ui/app/staking/stake/StakingCard.tsx
- Show available balance without substracting input amout 
- fix spacing issue 
https://user-images.githubusercontent.com/8676844/215168754-9b979479-54a7-40bd-8262-3ebd3ed74145.mov
> Wallet staking available update

- CONTRIBUTING.md
- crates/sui-framework/CONTRIBUTING.md
Some useful information for those wishing to contribute to Sui framework.
> [docs] Added documentation for Sui framework contributors

- .github/workflows/bench.yml
Example output: https://github.com/MystenLabs/sui/commit/2c30acff0f3a1a0d70dc0422059f9a4995e4c562#commitcomment-98364768
> [Stress] add more test runs with different TPS and committee sizes in CI

- crates/sui-config/src/p2p.rs
- crates/sui-network/src/state_sync/mod.rs
> state-sync: enable configuring the rpc timeout

- apps/wallet/src/ui/app/pages/home/receipt/index.tsx
This will reduce the latency when clicking into a receipt page. Will do some more involved rework later.
> [wallet-ext] Remove refetch on receipt page

- crates/sui-json-rpc/src/read_api.rs
Tested locally it still take ~2 seconds to render the CoinBalanceChanges events for TX `4ogyNqUEnUwsDv2i44x9fsurqyAvTMQqALHrMrtMZsX1`
> [wave2 hotfix] - remove delete object, new object and some events from transaction effect for ChangeEpoch tx to reduce response size

- crates/sui-core/src/narwhal_manager/mod.rs
- crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
- crates/sui-node/src/lib.rs
Replacing the current metrics with some more fine-grained ones to allow us calculate the start/shutdown times for Narwhal
> [narwhal] adding more fine-grained narwhal_manager metrics

- apps/wallet/src/ui/app/ApiProvider.ts
* fixes not reloading recent transactions
before
https://user-images.githubusercontent.com/10210143/215542870-99550c70-7968-469c-a045-d51a5a00d9bc.mov
after
https://user-images.githubusercontent.com/10210143/215542997-f89922b6-63fe-47de-9765-715732e1de93.mov
> wallet-ext: clear and reset query client when changing api provider

- crates/sui-core/src/checkpoints/mod.rs
This PR adds additional monitored scopes to checkpoint builder to break down checkpoint creation time
> [checkpoints] Break down checkpoint builder scope for better visibility

- apps/wallet/src/ui/app/hooks/useOriginbyteNft.ts
fix the following errors in nft details view
> wallet-ext: fix query data complaining for undefined

- crates/sui-core/src/histogram.rs
For the values that are not updated frequently we should try to 'align' histogram refresh time with the prometheus poll frequency. The default prometheus poll frequency is once a minute, so we should have similar value for histogram update frequency.
> [Histogram] Correct histogram reporting to prometheus

- doc/src/learn/why-move.md
> Update why-move.md – grammar

- crates/sui-core/src/transaction_manager.rs
- crates/sui-types/src/messages.rs
> [Fix fork] TransactionManager respects type argument dependencies

- crates/sui-source-validation/src/tests.rs
Fix for a test that may flake based on some of my recent changes on main (introduced in https://github.com/MystenLabs/sui/commit/22292d60f35545fa87cc29fcf183c07ffddfdca7)
So far I've only seen it flake locally but it's bound to crop up for others.
> test: label random address consistently

- crates/sui-source-validation/fixture/c/Move.toml
- crates/sui-source-validation/fixture/c/sources/b.move
- crates/sui-source-validation/fixture/c/sources/c.move
- crates/sui-source-validation/fixture/c/sources/d.move
- crates/sui-source-validation/fixture/d/Move.toml
- crates/sui-source-validation/fixture/d/sources/a.move
- crates/sui-source-validation/src/lib.rs
- crates/sui-source-validation/src/tests.rs
Same as https://github.com/MystenLabs/sui/pull/7898, please just stamp.
Closes https://github.com/MystenLabs/sui/issues/7474
I accidentally force pushed an empty commit when rebasing and this causes GH to auto close the PR 🤦
> source validation: emit multiple errors

- doc/src/learn/how-sui-works.md
Not valid hyperlink in "How Sui Works" sections. 
I wasn't able to find any detailed information about Sui Gateway services in the docs.
> hyperlink fix

- apps/explorer/src/pages/search-result/SearchResult.tsx
- apps/explorer/src/utils/api/searchUtil.ts
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/signers/signer-with-provider.ts
- sdk/typescript/src/types/common.ts
- sdk/typescript/test/unit/types/common.test.ts
- sdk/typescript/test/unit/types/stringTypes.test.ts
This pr is for https://github.com/MystenLabs/sui/issues/7541.
> refactor: clean up outdated version gated code

- doc/src/explore/move-examples/additional-resources.md
- doc/src/explore/move-examples/index.md
Fix for broken links in the "Sui Move by Example" section
> fix broken links in move-example section

- doc/src/build/install.md
Fix hyperlinks on the "Install Sui" page
> fix hyperlinks

- crates/mysten-metrics/Cargo.toml
revert https://github.com/MystenLabs/sui/pull/8019
> chore: remove dup dep of tokio

- apps/wallet/src/ui/app/components/transactions-card/NoActivityCard.tsx
- apps/wallet/src/ui/app/hooks/index.ts
- apps/wallet/src/ui/app/hooks/useGetTransactionsByAddress.ts
- apps/wallet/src/ui/app/pages/home/transactions/index.tsx
- Added `NoActivityCard` 
- move transaction query to Hook
> Added no activity card

- crates/sui-framework/src/natives/dynamic_field.rs
- Improved ID generation by hashing
Thanks for the fix @embe221ed and @otter-sec !
> [dynamic fields] Improve hashing generation

- doc/src/build/fullnode.md
Added SSD to Hardware requirements and fixed minor typos
> Added SSD to fullnode hardware requirements

- Cargo.lock
- crates/sui-rosetta/Cargo.toml
- crates/sui-rosetta/src/network.rs
- crates/sui-rosetta/src/operations.rs
- crates/sui-rosetta/src/state.rs
- crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs
Also:
* [bugfix] - fixed incorrect `target_index`
* added more checkpoint indexing logging to sui-rosetta
* some minor refactoring
> [sui-rosetta][bugfix] - Sui delegation balance fix

- crates/sui-network/src/state_sync/mod.rs
Be more resilient to nodes sending us bad checkpoints by removing checkpoints we can't verify from our temporary store. Also, if we receive a checkpoint from consensus try to eagerly advance our highest synced checkpoint.
> state-sync: be more resilient to nodes sending us bad checkpoints

- apps/explorer/src/components/top-validators-card/TopValidatorsCard.tsx
- apps/explorer/src/pages/validators/Validators.tsx
- adjustments to sort order for validators. random order on home page, ascending by stake on validators page
> [explorer] - sort top validators randomly, ascending on all validators table

- crates/sui-types/src/messages.rs
Some checks were not performed in batch for certain transaction kinds. While this might not be a problem now, it feels like it might cause an issue later if these rules are changed without changing them also for batch.
> [transaction input checker] Make batch rules more robust

- crates/sui-benchmark/src/system_state_observer.rs
A temporary fix to compute reference gas price the correct way in stress instead of reading directly from system state obj.
> [stress] compute correct reference gas price in stress

- crates/sui-benchmark/src/options.rs
- crates/sui-benchmark/src/util.rs
- crates/sui-benchmark/src/workloads/workload_configuration.rs
- crates/sui-benchmark/tests/simtest.rs
This PR fixes the problem with too large transaction payload we see while generating high tps traffic
> Chunkify gas requests

- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
- apps/wallet/src/ui/app/shared/button/Button.module.scss
- apps/wallet/src/ui/app/shared/faucet/request-button/FaucetDiscordLink.tsx
- apps/wallet/src/ui/app/shared/faucet/request-button/index.tsx
- Added request token from Discord 
- added Plausible event tracking 
https://user-images.githubusercontent.com/8676844/216609502-4d1934ea-d63c-4a06-a4dc-4643058e4efe.mov
> add Request Testnet SUI on Discord button

- apps/explorer/src/ui/InternalLink.tsx
- apps/explorer/src/utils/stringUtils.ts
> Remove 0x from transaction Ids from the table list 

- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
(ref: https://github.com/MystenLabs/sui/pull/8003)
select! must handle error cases of the mailbox.recv properly.
> [Checkpoint Exec] Fix select branch

- narwhal/primary/src/proposer.rs
This is a small optimisation on the proposer for the leader. Mainly when we receive a fresh set of parents for next round, and we are supposed to be the leader, we immediately reset the clock to take advantage of faster proposal dissemination.
> [narwhal] small optimisation in proposer for leader

- apps/explorer/src/components/search/Search.tsx
- apps/explorer/src/hooks/useSearch.ts
- apps/explorer/src/ui/Search.tsx
- apps/explorer/tests/search.spec.ts
- fix search icon position
- improve object / address disambiguation
- fix issue when pressing enter before results are loaded
> [explorer] - search - fixes

- apps/explorer/src/pages/validators/Validators.tsx
- fixes sorting by name in the validators table with a custom sort fn 
https://user-images.githubusercontent.com/122397493/216794761-6029ff73-ed27-4660-aa33-642c9ac456da.mov
> [explorer] - fix sort by name in validators table

- dapps/frenemies/src/routes/Setup.tsx
- sdk/wallet-adapter/wallet-kit/src/AccountModal.tsx
> [frenemies] Gas fix

- dapps/frenemies/src/components/Assignment/index.tsx
- dapps/frenemies/src/components/Validators/Target.tsx
> [frenemies] Copy tweak

- dapps/frenemies/src/components/Card.tsx
- dapps/frenemies/src/components/Spinner.tsx
- dapps/frenemies/src/components/Validators/Balance.tsx
- dapps/frenemies/src/components/Validators/Validator.tsx
- dapps/frenemies/src/network/queries/coin.ts
- dapps/frenemies/src/routes/Connect.tsx
- dapps/frenemies/src/routes/Setup.tsx
- dapps/frenemies/src/utils/format.ts
Some UI tweaks dealing with registration.
- Added spinner when loading
- Added new balance warning during registration
- Added new copy to connect wallet page.
- Removed dry run before execute.
- Tweak SUI balance formatting
> [frenemies] Tweak UIs

- apps/wallet/src/ui/app/shared/button/Button.module.scss
- apps/wallet/src/ui/app/staking/delegation-detail/DelegationDetailCard.tsx
- apps/wallet/src/ui/styles/values/colors.scss
> fix staking button issue

- crates/sui-rosetta/src/operations.rs
- crates/sui-rosetta/src/types.rs
- crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs
- crates/sui-transaction-builder/src/lib.rs
added unit test to ensure TransactionData <> Operations conversion is correct for delegation
> [sui-rosetta] - Delegation transaction data <> Rosetta operations conversion bug fix

- Cargo.lock
- Cargo.toml
- crates/sui-tool/Cargo.toml
- crates/sui-tool/src/commands.rs
- crates/sui-tool/src/db_tool/db_dump.rs
- crates/sui-tool/src/db_tool/mod.rs
- crates/sui-tool/src/lib.rs
- crates/workspace-hack/Cargo.toml
Includes manual definitions for Sui and Narwhal services.
> Add anemo CLI features to sui-tool.

- Cargo.lock
- crates/sui-benchmark/Cargo.toml
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-config/src/node.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-node/src/lib.rs
- crates/sui/tests/full_node_tests.rs
This reverts commit 711dd7e3a6e94e2c9d09b096af184419bb04cfea.
> Reenable: [objects pruner] live pruner support

- apps/wallet/src/ui/app/components/nft-display/NftImage.tsx
- apps/wallet/src/ui/app/components/transactions-card/TxnImage.tsx
> Use a default single color for broken NFT image

- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/rocks/tests.rs
This PR allows taking rocksdb checkpoint which allow for taking efficient point in time snapshot of the db (created using hard links)
> Allow taking db checkpoint for state snapshot creation

- apps/wallet/src/ui/app/components/menu/content/Account.tsx
- apps/wallet/src/ui/app/components/menu/content/AccountsSettings.tsx
- apps/wallet/src/ui/app/components/menu/content/MenuLayout.tsx
- apps/wallet/src/ui/app/components/menu/content/index.tsx
- apps/wallet/src/ui/app/shared/text/index.tsx
- apps/wallet/src/ui/app/staking/delegation-detail/DelegationDetailCard.tsx
- apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx
* display all the accounts of the user
* update the ui
https://user-images.githubusercontent.com/10210143/219118290-e619926e-1928-4c38-a09b-a4c4c4b53f53.mov
closes APPS-286
> wallet-ext: account settings view support multiple accounts

- crates/typed-store/src/sally/mod.rs
- crates/typed-store/src/test_db.rs
Adds the missing iter functions which are needed for migrating perpetual db
> [sally-api] Add missing sally iter functions

- apps/wallet/src/background/keyring/index.ts
- apps/wallet/src/shared/messaging/messages/payloads/keyring/index.ts
- apps/wallet/src/ui/app/background-client/index.ts
- apps/wallet/src/ui/app/components/menu/content/AccountsSettings.tsx
- apps/wallet/src/ui/app/redux/slices/account/index.ts
https://user-images.githubusercontent.com/10210143/218893872-378b65d4-18cd-49bd-92a0-f5fdb1a57fc6.mov
closes APPS-287
> wallet-ext: accounts settings view create new account from mnemonic

- crates/sui-protocol-constants/src/lib.rs
- crates/sui-types/src/temporary_store.rs
as in https://github.com/MystenLabs/sui/pull/8102
the idea is to remove the f64 to be on the safer side
> Do not use f64 for STORAGE_REBATE_RATE

- crates/sui-core/src/authority.rs
Today we check shared object locks twice in the certificate processing path (`fn prepare certificate`).
1. We first load objects with `transaction_input_checker::check_certificate_input` which calls `check_sequenced_input_objects`. The latter checks shared object lock for each input shared object, load the object with that version, and return the object.
2. The returned object list is then [used as the input for `fn check_shared_locks`](https://github.com/MystenLabs/sui/blob/main/crates/sui-core/src/authority.rs#L984). What `check_shared_locks` does is checking the shared object lock exists (again), and verify the object version matches the object list (returned from `check_certificate_input`). This is no reason that the object version would mismatch because we just load them a few steps …
> do not check shared locks twice

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-node/src/lib.rs
This modifies slightly how `EpochStartConfiguration` is initialized, hopefully making it cleaner
> [epoch_data] Cache EpochStartConfiguration in AuthorityPerEpochStore (2/n)

- Cargo.lock
- Cargo.toml
- crates/sui-types/src/sui_system_state.rs
- crates/workspace-hack/Cargo.toml
Includes fix to module-handle order stability issue in move-language/move#904
```
$ cargo nextest run
```
> [move] Bump Move version

- apps/explorer/src/ui/Search.tsx
search box styles were off following the css reset changes. fixed the styling issues and removed some unnecessary css to be more resilient against future changes
> [explorer] - fix search styling

- crates/sui-adapter/src/adapter.rs
- crates/sui-adapter/src/execution_engine.rs
- crates/sui-adapter/src/lib.rs
- crates/sui-core/tests/staged/sui.yaml
- crates/sui-framework/src/natives/object_runtime/mod.rs
- crates/sui-framework/src/natives/test_scenario.rs
- crates/sui-types/src/coin.rs
- crates/sui-types/src/messages.rs
- crates/sui-types/src/object.rs
- crates/sui-types/src/storage.rs
- Small changes needed for programmable transaction runtime
> [2/x][programmable transactions] Small changes to adapter and types

- crates/sui-config/data/fullnode-template-with-path.yaml
- crates/sui-config/data/fullnode-template.yaml
The WS port config here is outdated, removing it to avoid confusion.
https://mysten-labs.slack.com/archives/C04HS54LHUM/p1676848336490189
> remove unused ws port in config

- crates/sui-rosetta/Cargo.toml
- crates/sui-rosetta/src/construction.rs
- crates/sui-rosetta/src/lib.rs
- crates/sui-rosetta/src/state.rs
- crates/sui-rosetta/src/types.rs
- crates/sui-rosetta/tests/end_to_end_tests.rs
- crates/sui-rosetta/tests/rosetta_client.rs
- crates/workspace-hack/Cargo.toml
cherrypick fixes and e2e test from the rosetta-testnet branch
> rosetta testnet cherrypick

- crates/sui-framework/tests/pay_tests.move
Adds test coverage to previously uncovered functions:
- `pay::split_vec`
- `pay::split_and_transfer`
- `pay::split`
- `pay::join_vec_and_transfer`
- `pay::join_vec`
bumps `pay.move` coverage [`72% -> 95%`](https://app.codecov.io/github/rvantonder/sui-framework-coverage-test/commit/698873150e4a21308f193b368137ba8d8575121c/blob/bytecode/pay.move.bytecode)
> move: add more tests for pay

- crates/sui-framework/tests/safe_tests.move
This makes some tests consistent with others by factoring out constant addresses and simplifying the need to pass `&mut` in arguments. This because I've been bouncing between Move tests and noticed the small differences make it difficult to reuse/copy-paste standard setups or calls.
Semantics-preserving. Setup for https://github.com/MystenLabs/sui/pull/8398
> move: consistent helpers in safe test

- crates/sui-framework/tests/safe_tests.move
Stacked on https://github.com/MystenLabs/sui/pull/8397.
Exercises previously uncovered functions in `safe.move`:
- `safe::withdraw` -- for this we update an existing test for `withdraw_` (which is wrapped in `withdraw`) plus an assertion on the balance
- `safe::self_revoke_transfer_capability`
> move: improve tests for safe

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-types/src/messages.rs
- sdk/typescript/src/signers/txn-data-serializers/local-txn-data-serializer.ts
- sdk/typescript/src/types/sui-bcs.ts
- sdk/typescript/test/e2e/txn-serializer.test.ts
- sdk/typescript/test/unit/types/common.test.ts
Adds an expiration field to TransactionData. This PR just adds the field and doesn't attempt to use it, that will be added in a future PR
Fixes: #8272
> types: add transaction expiration field to TransactionData

- crates/sui-json-rpc-types/src/lib.rs
- crates/sui-json-rpc/src/api.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-open-rpc/src/examples.rs
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/transactions.ts
- sdk/typescript/test/e2e/read-transactions.test.ts
Fullnodes will no longer have tx certificates.
> [rpc] Remove get_transaction_auth_signers

- crates/sui-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- narwhal/benchmark/README.md
- narwhal/config/src/lib.rs
- narwhal/config/tests/snapshots/config_tests__parameters.snap
- narwhal/config/tests/snapshots/config_tests__parameters_import.snap
Also set `min_header_delay` to .5s (down from 1s) by default
> Update default NW parameters

- crates/sui/multisig.md
- crates/sui/offline_signing.md
- crates/sui/src/client_commands.rs
discussed with kostas that we will have a crypto sections for docs.sui.io. here we add a readme to instruct usage before its migrated to a proper doc page. 
some minor updates to offline_signing.md (also not in docs.sui.io yet) due to CLI tool changes.
> crypto: Add doc for multisig

- crates/sui-core/src/checkpoints/mod.rs
This has no callsites/listeners, and is a source of nondeterministic bugs based on simtests.
> [core] Remove CheckpointTailer

- crates/sui-indexer/migrations/2023-01-16-233119_checkpoint/up.sql
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/models/checkpoints.rs
- crates/sui-indexer/src/schema.rs
This PR uses the new combined API and added several new columns to the checkpoint table, the notable one is the txns in the current checkpoint.
Tested with local validator, FN and indexer as the combined API is not in devnet:
> indexer: add txns etc. to checkpoints

- crates/sui-adapter/src/programmable_transactions/context.rs
- crates/sui-adapter/src/programmable_transactions/execution.rs
- Added module publishing
- In anticipation of module init having args, much of the logic has be reimplemented from the adapter
> [5/x][programmable transactions] Add module publishing

- crates/sui-core/src/authority/authority_store.rs
> Assert never revert shared object tx

- narwhal/primary/src/certificate_fetcher.rs
- narwhal/primary/src/primary.rs
- narwhal/primary/src/synchronizer.rs
- narwhal/primary/src/tests/certificate_fetcher_tests.rs
Also avoid re-verification of own certificate.
> [Narwhal] avoid re-verification of fetched certificates

- .github/PULL_REQUEST_TEMPLATE.md
Adding a new Sui Pull Request Template
See for details https://mysten-labs.slack.com/archives/C04FG4Q7YJ3/p1676668847677349
> Adding a new Sui Pull Request Template

- crates/sui-benchmark/src/drivers/bench_driver.rs
- crates/sui-benchmark/src/lib.rs
- crates/sui-benchmark/src/util.rs
- crates/sui-benchmark/src/workloads/shared_counter.rs
- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/quorum_driver/mod.rs
- crates/sui-core/src/quorum_driver/tests.rs
- crates/sui-core/src/transaction_orchestrator.rs
- crates/sui-json-rpc/src/transaction_execution_api.rs
- crates/sui-types/src/messages.rs
- crates/sui/tests/full_node_tests.rs
- crates/sui/tests/transaction_orchestrator_tests.rs
> [QuorumDriver] Remove certificate from all responses

- doc/src/build/install.md
This commit update binary install document missing which refered in #8562 
#pass
> Update binary install document

- narwhal/consensus/src/bullshark.rs
- narwhal/consensus/src/consensus.rs
- narwhal/consensus/src/lib.rs
- narwhal/consensus/src/tests/bullshark_tests.rs
- narwhal/consensus/src/tusk.rs
* small refactoring in the consensus behaviour when trying to insert a certificate of round lower that the last committed for the authority
* additional tests
> [narwhal] additional consensus tests

- apps/wallet/src/ui/app/components/menu/content/MenuList.tsx
- apps/wallet/src/ui/app/shared/ConfirmationModal.stories.tsx
- apps/wallet/src/ui/app/shared/ConfirmationModal.tsx
- apps/wallet/src/ui/app/shared/ModalDialog.stories.tsx
- apps/wallet/src/ui/app/shared/ModalDialog.tsx
- apps/wallet/tailwind.config.js
* make sure user actually wants to logout using a modal to avoid accidental logouts
https://user-images.githubusercontent.com/10210143/220646312-f8c1fca6-5d17-4d3c-b74c-edb49fc489c5.mov
https://user-images.githubusercontent.com/10210143/220646355-a9ff9611-5e27-4cd6-b19b-9e6209ae3176.mov
closes APPS-501
> wallet-ext: logout confirmation dialog

- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/rpc/client.ts
Clean up gating code since 0.27.0 has been released.
1. CI test 
2. Verified that explorer is working properly https://explorer-git-chris-cleanup-version-mysten-labs.vercel.app/
> [TypeScript SDK] clean up headers gating

- crates/sui-indexer/README.md
- updated architecture image
- easier DB reset cmd
eyeballs
> indexer: update README

- .github/workflows/e2e.yml
- apps/explorer/vercel.json
- dapps/frenemies/vercel.json
- sdk/wallet-adapter/example/vercel.json
> [apps][ts-sdk] Disable devnet tests, stop releases

- apps/explorer/src/utils/api/DefaultRpcClient.ts
- apps/explorer/src/utils/api/SentryRpcClient.ts
- apps/wallet/src/ui/app/ApiProvider.ts
- apps/wallet/src/ui/app/SentryRpcClient.ts
> [wallet-ext] Add sentry logging to wallet

- crates/sui-json-rpc/src/read_api.rs
Today txn timestamp is a local FN timestamp, which is not consistent across FNs, now as we have timestamp in checkpoint, this PR uses that as the consistent txn timestamp.
read a checkpoint locally, verify that the timestamp of txns in the checkpoint matches the checkpoint timestamp
```
curl --location --request POST http://127.0.0.1:9000 \
--data-raw '{ "jsonrpc":"2.0", "id":1, "method":"sui_getCheckpoint", "params":[20]}'
{"jsonrpc":"2.0","result":{"epoch":0,"sequenceNumber":20,"digest":"4TyV6KjrdPUVVyF1GV2P8tsg4QFdnMDjK7HdKWbJruT6","networkTotalTransactions":4,"previousDigest":"95NLNPr8v1gEtME35rgPzCchnviz77oXkpaw5kUSPqNe","epochRollingGasCostSummary":{"computation_cost":435,"storage_cost":144,"storage_rebate":64},"timestampMs":1677254340992," …
```
> json rpc: use checkpoint timestamp for txn response instead

- crates/sui/src/sui_commands.rs
`sui client` only allows interactive initialization of the local configs (in `~/.sui`). This makes it possible to use the client in automation via a `-y` flag to accept the defaults of using devnet as the network and generating a new ed25519 key.
`cargo nextest run` succeeds for all but one or two few flaky tests:
```
» c nextest run --no-fail-fast
...
Summary [ 246.873s] 898 tests run: 898 passed (4 slow), 9 skipped
```
Works with a new env (after `rm -rf ~/.sui`):
```
» sui client -y                                      
Creating config file ["/Users/jordankylejensen/.sui/sui_config/client.yaml"] with default (devnet) full node server and ed25519 key scheme.Generated new keypair for address with scheme "ed25519" [0xadb80fbfea1e98869f939f83bbc24f343e657745]
Secret Recovery Phrase : …
```
> Add `-y` flag to accept defaults for `sui client`

- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-framework/docs/validator_set.md
- crates/sui-framework/sources/governance/validator_set.move
- crates/sui-types/src/messages.rs
- crates/sui/tests/reconfiguration_tests.rs
Add a new test that exercise the flow of a new validator joining the network, and then leaving.\
Lots of dark magic in how the test is written.
> [reconfig] Add committee change tests

- .changeset/strange-fireants-burn.md
- apps/explorer/src/components/module/module-functions-interaction/ModuleFunction.tsx
- apps/wallet/src/dapp-interface/WalletStandardInterface.ts
- dapps/frenemies/src/components/Validators/actions/AddDelegation.tsx
- dapps/frenemies/src/components/Validators/actions/CancelDelegation.tsx
- dapps/frenemies/src/components/Validators/actions/WithdrawDelegation.tsx
- dapps/frenemies/src/network/queries/coin.ts
- dapps/frenemies/src/network/queries/scorecard.ts
- dapps/frenemies/src/network/queries/use-raw.ts
- dapps/frenemies/src/routes/Claim.tsx
- dapps/frenemies/src/routes/Migrate.tsx
- dapps/frenemies/src/routes/Setup.tsx
- dapps/frenemies/src/utils/coins.ts
- pnpm-lock.yaml
- sdk/wallet-adapter/adapters/base-adapter/package.json
- sdk/wallet-adapter/adapters/base-adapter/src/index.ts
- sdk/wallet-adapter/adapters/base-adapter/tsconfig.json
- sdk/wallet-adapter/adapters/unsafe-burner/package.json
- sdk/wallet-adapter/adapters/unsafe-burner/src/index.ts
- sdk/wallet-adapter/adapters/unsafe-burner/tsconfig.json
- sdk/wallet-adapter/adapters/wallet-standard-adapter/src/StandardWalletAdapter.ts
- sdk/wallet-adapter/example/src/App.tsx
- sdk/wallet-adapter/wallet-kit-core/package.json
- sdk/wallet-adapter/wallet-kit-core/src/index.ts
- sdk/wallet-adapter/wallet-kit-core/tsconfig.json
- sdk/wallet-adapter/wallet-kit/src/AccountModal.tsx
- sdk/wallet-adapter/wallet-kit/src/ConnectButton.tsx
- sdk/wallet-adapter/wallet-standard/src/features/suiSignAndExecuteTransaction.ts
- sdk/wallet-adapter/wallet-standard/src/features/suiSignTransaction.ts
- sdk/wallet-adapter/wallet-standard/src/index.ts
* allow dapps/wallet-kit specify the chain and account for a transaction
part of APPS-281
> wallet-adapters,wallet-standard: support chain and account transaction parameters

- crates/sui-json-rpc/src/metrics.rs
New rpc request/response metrics
Run rpc server locally and inspect Prometheus metrics endpoint
> [rpc metrics] - add request and response size metrics

- doc/src/doc-updates/index.md
- doc/src/learn/sponsored-transactions.md
- doc/src/navconfig.json
Adds a new doc topic for Sponsored Transactions
Content technical review and manually verified links in the topic.
---
Added a new topic for Sui [Sponsored Transactions](https://docs.sui.io/learn/sponsored-transactions).
> Adding new Sponsored Transactions topic

- Cargo.lock
- Cargo.toml
- crates/sui-cost-tables/src/bytecode_tables.rs
- crates/sui-move/src/prove.rs
- crates/workspace-hack/Cargo.toml
This PR updates the Move pointer, which is needed for new new natives logic.
N/A
---
> Update move ptr

- .changeset/config.json
- dapps/frenemies/README.md
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
> Disable frenemies

- .changeset/rare-jars-hunt.md
- sdk/wallet-adapter/adapters/wallet-standard-adapter/src/index.ts
- sdk/wallet-adapter/example/src/index.tsx
- sdk/wallet-adapter/wallet-kit/src/WalletKitContext.tsx
- sdk/wallet-adapter/wallet-standard/src/detect.ts
This adds the ability to add features that are required in the `features` prop in Wallet Kit.
Using the demo app
> [wallet-kit] Add ability to define required features

- crates/sui-indexer/migrations/2023-01-16-233119_checkpoint/up.sql
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/errors.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/handlers/event_handler.rs
- crates/sui-indexer/src/handlers/move_event_handler.rs
- crates/sui-indexer/src/handlers/object_event_handler.rs
- crates/sui-indexer/src/handlers/publish_event_handler.rs
- crates/sui-indexer/src/models/checkpoints.rs
- crates/sui-indexer/src/schema.rs
- crates/sui-types/src/digests.rs
Implement indexer native API for checkpoints
run with local validator and curl locally
```
--data-raw '{ "jsonrpc":"2.0", "id":1, "method":"sui_getCheckpoint", "params":[1]}'
{"jsonrpc":"2.0","result":{"epoch":0,"sequenceNumber":1,"digest":"4pijCwoi386MQkR4zfg7wNHgdqSGfxoFrwb9ud1r3cyZ","networkTotalTransactions":2,"previousDigest":"FeN6drNDysV5HC2VQnChoeKZRrwm5b5Wy2dXSp2Vexxc","epochRollingGasCostSummary":{"computation_cost":0,"storage_cost":0,"storage_rebate":0},"timestampMs":1677621185088,"endOfEpochData":null,"transactions":["Ac1NiAh87MvMTJGnziwdx6j4xTzD1mrcdGKGbNUm55na"]},"id":1}%      
curl --location --request POST http://127.0.0.1:9000 \ …
```
> indexer: checkpoint API

- Cargo.lock
- crates/sui-framework/Cargo.toml
- crates/sui-framework/docs/validator.md
- crates/sui-framework/sources/governance/validator.move
- crates/sui-framework/src/natives/mod.rs
- crates/sui-framework/src/natives/validator.rs
- crates/sui-framework/tests/governance_test_utils.move
- crates/sui-framework/tests/validator_tests.move
- crates/sui-types/src/sui_system_state.rs
This PR adds extra verification for validator's metadata in an attempt to resolve https://github.com/MystenLabs/sui/issues/7323
New tests have been added.
> [move] Added native verification of validator's metadata

- crates/sui-indexer/migrations/2022-11-18-195259_transactions/up.sql
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/models/transactions.rs
- crates/sui-indexer/src/schema.rs
implement `get_transaction` and `get_total_transaction_number`.
On top of #8683 and will rebase.
Local run against local validator, curl local url with the newly added endpoints, verify that results from different sources are the same:
```
curl --location --request POST http://127.0.0.1:9000 \
--data-raw '{ "jsonrpc":"2.0", "id":1, "method":"sui_getTransaction", "params":["7EFD6WubSsWP2DzP8PW3ZgPnmvEi7Xhvj4S8QJdHH8Wf"]}'
{"jsonrpc":"2.0","result":{"transaction":{"data":{"transactions":[{"ConsensusCommitPrologue":{"epoch":0,"round":268,"commit_timestamp_ms":1677624091055}}],"sender":"0x0000000000000000000000000000000000000000000000000000000000000000","gasData":{"payment":{"objectId":"0x00000000000000000000000000000000000000000000000000000000000000 …
```
> indexer: txn API 1/N

- narwhal/network/src/admin.rs
- narwhal/network/src/p2p.rs
- narwhal/node/src/generate_format.rs
- narwhal/node/tests/staged/narwhal.yaml
- narwhal/primary/src/block_synchronizer/tests/block_synchronizer_tests.rs
- narwhal/primary/src/metrics.rs
- narwhal/primary/src/primary.rs
- narwhal/primary/src/tests/common.rs
- narwhal/test-utils/src/lib.rs
- narwhal/types/build.rs
- narwhal/types/src/primary.rs
- narwhal/worker/src/handlers.rs
- narwhal/worker/src/worker.rs
Realised we never removed that (obsolete) part of the code when refactored reconfiguration.
---
> [chore] clean up left over reconfiguration code

- crates/sui-node/src/lib.rs
as title. Also move the call to `self.reconfigure_state` out from the if/else statement.
unit/integration tests
---
Remove outdated TODO.
> remove outdated TODO in reconfig

- crates/sui-config/src/builder.rs
- crates/sui-config/src/node.rs
- crates/sui-config/src/swarm.rs
- crates/sui-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-node/src/lib.rs
- crates/typed-store-derive/src/lib.rs
- crates/typed-store/src/rocks/errors.rs
- crates/typed-store/src/rocks/mod.rs
Tested by running it locally with a smaller epoch duration, and see the checkpoints getting created. The directory after checkpoint looks like:
```
ls -lrt /var/folders/gw/zb4g8bvx3152swglmgp_4q100000gn/T/.tmpvNyZdX/authorities_db/addeef94d898/store/perpetual/
total 85744
-rw-r--r--   1 sadhansood  staff         0 Feb 14 17:05 LOCK
-rw-r--r--   1 sadhansood  staff        36 Feb 14 17:05 IDENTITY
-rw-r--r--   1 sadhansood  staff        16 Feb 14 17:05 CURRENT
-rw-r--r--   1 sadhansood  staff     42047 Feb 14 17:05 OPTIONS-000023
-rw-r--r--   2 sadhansood  staff     42047 Feb 14 17:05 OPTIONS-000025
-rw-r--r--   2 sadhansood  staff   3165161 Feb 14 17:06 000027.sst
-rw-r--r--   2 sadhansood  staff    641468 Feb 14 17:06 000028.sst
-rw-r--r--   2 sadhansood  staff   2662720 Feb 14 17:06 …
```
> Take db checkpoint at epoch boundary for state snapshot

- narwhal/worker/src/batch_maker.rs
- narwhal/worker/src/tests/batch_maker_tests.rs
- narwhal/worker/src/tests/quorum_waiter_tests.rs
Rename variable so the channel it represents is more obvious. 
existing unit tests
---
> [Narwhal] Rename variable to indicate it represents the channel to quorum waiter

- crates/sui-indexer/src/lib.rs
RT
Test in devnet for trouble shooting
> indexer: limit RPC client concurrency to 5

- .config/nextest.toml
- .github/workflows/simulator-nightly.yml
- scripts/simtest/cargo-simtest
- scripts/simtest/simtest-run.sh
Simulator Test workflow improvements
> Simulator Test workflow improvements

- .github/workflows/simulator-nightly.yml
> Simtest: increase timeout to 2 hours

- crates/sui-config/data/fullnode-template-with-path.yaml
- crates/sui-config/data/fullnode-template.yaml
- crates/sui-config/src/node.rs
- crates/sui-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-node/src/lib.rs
initial version didn't manage to keep up with narwhal
adding batching to resolve the issue
> [objects pruner] add batching

- crates/sui-benchmark/src/lib.rs
Currently bench mode assumes all nodes are up, which often is not the case. Tolerate down nodes when submitting certificates, by only waiting for at most 2s to send certificates to peers after quorum is reached. This should not affect TPS, since stress client uses max inflight ratio ~ 15.
Deployed to private testnet.
---
> [Stress] Tolerate down nodes in BENCH_MODE

- Cargo.lock
- narwhal/consensus/Cargo.toml
> Add missing bcs dependency

- .github/workflows/simulator-nightly.yml
Making the link to logs drill down to job log (less clicks)
👁️
> [simtest]: making logs link more explicit

- apps/explorer/src/pages/transaction-result/TransactionView.tsx
- crates/sui-adapter/src/execution_engine.rs
- crates/sui-config/src/genesis.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/transaction_input_checker.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/gas_tests.rs
- crates/sui-json-rpc-types/src/lib.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-rosetta/src/construction.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/coin.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/gas.rs
- crates/sui-types/src/messages.rs
- crates/sui-types/src/temporary_store.rs
- crates/sui-types/src/unit_tests/messages_tests.rs
- crates/sui/tests/full_node_tests.rs
- crates/test-utils/src/transaction.rs
- sdk/typescript/src/signers/txn-data-serializers/local-txn-data-serializer.ts
- sdk/typescript/src/types/objects.ts
- sdk/typescript/src/types/sui-bcs.ts
- sdk/typescript/src/types/transactions.ts
- sdk/typescript/test/e2e/txn-serializer.test.ts
- sdk/typescript/test/unit/types/common.test.ts
gas smashing per se is working and there are tests for it.
There are conversations in flight about how to do for the braking change with SDK and Wallet (@patrickkuo @666lcz @Jordan-Mysten).
Integration with Programmable Transaction (@tnowacki) should be good to go modulo some corrections.
@oxade please take a look if you can
Added unit tests
---
> Gas Smashing

- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/providers/provider.ts
- sdk/typescript/src/signers/signer-with-provider.ts
- sdk/typescript/src/signers/txn-data-serializers/call-arg-serializer.ts
- sdk/typescript/src/signers/txn-data-serializers/local-txn-data-serializer.ts
- sdk/typescript/src/types/coin.ts
- sdk/typescript/src/types/common.ts
- sdk/typescript/src/types/transactions.ts
- sdk/typescript/src/types/validator.ts
- sdk/typescript/test/e2e/checkpoint.test.ts
This removes some of the TODOs that exist in the SDK source code, cleans up some un-used code, and refines some types that should be safe to change given the network version.
Tests should continue to pass.
> [ts-sdk] Remove some TODOs, cleanup unused code

- crates/sui-types/src/committee.rs
- crates/sui-types/src/messages.rs
> Remove CommitteeInfo

- .github/workflows/simulator-nightly.yml
Fixing slack msg for simtest results
👁️ 👁️
> simtest: fixing slack msg

- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-json/src/lib.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-rosetta/src/types.rs
- Added Sui JSON Programmable Transaction types
I am not sure, how are these normally tested?
---
> [programmable transactions] Add Sui JSON types

- apps/wallet/src/ui/app/components/DAppInfoCard.tsx
- apps/wallet/src/ui/app/components/user-approve-container/UserApproveContainer.module.scss
- apps/wallet/src/ui/app/components/user-approve-container/index.tsx
* DAppInfoCard now can show an address
* use DAppInfoCard in site-connect view
| - | - |
| <img width="364" alt="Screenshot 2023-03-06 at 20 49 50" src="https://user-images.githubusercontent.com/10210143/223227758-2e9a57a0-af7e-4784-aa85-20e1c88460f7.png"> | <img width="364" alt="Screenshot 2023-03-06 at 20 45 03" src="https://user-images.githubusercontent.com/10210143/223227833-bd9dc836-a962-44e3-8d36-f11517de4729.png"> |
| <img width="364" alt="Screenshot 2023-03-06 at 20 49 54" src="https://user-images.githubusercontent.com/10210143/223227906-7078a226-fea5-44f6-93db-027b234b25e1.png"> | <img width="364" alt="Screenshot 2023-03-06 at 20 45 11" src="https://user-images.githubusercontent.com/10210143/223227960-5da07329-ba77-4772-8131-60c4a79b2559.png"> |
| <img …
> wallet-ext: DAppInfoCard add connected address

- sdk/typescript/src/builder/Commands.ts
- sdk/typescript/src/builder/Transaction.ts
- sdk/typescript/src/builder/legacy.ts
- sdk/typescript/src/framework/sui-system-state.ts
- sdk/typescript/src/signers/signer-with-provider.ts
- sdk/typescript/src/types/transactions.ts
- sdk/typescript/test/e2e/governance.test.ts
Initial version of coin selection, which currently just selects all coins. We'll refine this over time.
Tests should pass.
> [ts-sdk] Transaction builder coin selection

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-types/src/sui_system_state/sui_system_state_inner_v1.rs
- crates/sui-types/src/sui_system_state/sui_system_state_summary.rs
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/providers/provider.ts
- sdk/typescript/src/providers/void-provider.ts
- sdk/typescript/src/types/validator.ts
- sdk/typescript/test/e2e/governance.test.ts
Adds a new TS SDK API to get the latest sui system state using the new flat data structure.
> Add getLatestSuiSystemState to TS SDK

- .github/workflows/simtest.yml
Creating a new simtest workflow for executing on the remote server
Nothing is using this workflow yet
> Creating a new simtest workflow for executing on the remote server

- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-node/src/lib.rs
- crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs
Figured we had a race in PR merging again.
cargo is my friend.
---
> adapt to EpochStartSystemState

- narwhal/consensus/src/bullshark.rs
- narwhal/consensus/src/tusk.rs
- narwhal/primary/src/synchronizer.rs
1. Annotate logs with `sub_dag_index` to make debugging easier.
2. Ensure state lock is held when persisting certificate and sending it to consensus.
n/a
---
> [Narwhal] add additional logs

- crates/sui-core/src/authority.rs
- crates/sui-core/src/transaction_input_checker.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_1.snap
- crates/sui-swarm/src/memory/swarm.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/message_envelope.rs
- crates/sui-types/src/messages.rs
- crates/sui/tests/protocol_version_tests.rs
- crates/test-utils/src/network.rs
This PR contains the bits of #8835 that are worth merging.
> More prep work for advancing protocol versions

- .changeset/kind-dots-smell.md
- apps/core/src/api/SentryRpcClient.ts
- apps/core/src/hooks/useFormatCoin.ts
- apps/wallet/src/ui/app/hooks/useGetAllBalances.ts
- apps/wallet/src/ui/app/hooks/useGetCoinBalance.ts
- apps/wallet/src/ui/app/hooks/useGetCoins.ts
- dapps/frenemies/src/network/queries/coin.ts
- sdk/typescript/README.md
- sdk/typescript/src/builder/Transaction.ts
- sdk/typescript/src/builder/legacy.ts
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/providers/provider.ts
- sdk/typescript/src/providers/void-provider.ts
- sdk/typescript/src/rpc/client.ts
- sdk/typescript/test/e2e/coin-metadata.test.ts
- sdk/typescript/test/e2e/coin-read.test.ts
- sdk/typescript/test/e2e/governance.test.ts
Doing some of the initial work to rework the TS SDK to make requests with objects instead of positional arguments. Also updating all of the APIs accordingly to take objects.
Tests should continue to pass.
> [ts-sdk] Migrate coin APIs to object-based requests

- .github/workflows/rust.yml
- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/README.md
- crates/sui-indexer/migrations/2022-11-22-222247_error_logs/down.sql
- crates/sui-indexer/migrations/2022-12-01-034426_objects/down.sql
- crates/sui-indexer/migrations/2023-03-01-193733_owner/down.sql
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/tests/indexer_tests.rs
- crates/sui-indexer/tests/integration_tests.rs
- crates/workspace-hack/Cargo.toml
Added skeleton CI integration test with postgesql DB, the test will wipe and rebuild the database using migration schemas and run test using the database.
CI
> [indexer] - CI integration test

- doc/src/doc-updates/sui-breaking-changes.md
Formatting and content changes for accuracy
Manually
---
> Format updates and remove duplicate entry

- apps/wallet/src/ui/app/components/sui-apps/index.tsx
- sdk/typescript/README.md
This removes the devnet NFT mint from the wallet, as it does not use the display standard, and we should remove this module anyway.
Ran wallet locally.
> [wallet-ext] Remove devnet NFT mint

- narwhal/consensus/src/bullshark.rs
- narwhal/consensus/src/tests/bullshark_tests.rs
- narwhal/test-utils/src/lib.rs
This PR is adding a new test which is a combination of different cases to ensure that even with overlaps algorithm still works as expected.
---
> [test] adding a combination of tests cases for consensus

- docker/fullnode/README.md
Added docker command to inspect the consumption of a running fullnode.
> [docker] -  updated fullnode stats

- apps/explorer/tests/utils/localnet.ts
- apps/wallet/src/ui/app/redux/slices/sui-objects/Coin.ts
- sdk/typescript/src/builder/Commands.ts
- sdk/typescript/src/builder/__tests__/Transaction.test.ts
- sdk/typescript/src/builder/bcs.ts
- sdk/typescript/src/builder/legacy.ts
- sdk/typescript/src/framework/sui-system-state.ts
- sdk/typescript/test/e2e/entry-point-string.test.ts
- sdk/typescript/test/e2e/id-entry-args.test.ts
- sdk/typescript/test/e2e/object-vector.test.ts
- sdk/typescript/test/e2e/txn-builder.test.ts
- sdk/typescript/test/e2e/utils/setup.ts
- sdk/wallet-adapter/example/src/App.tsx
The final piece of the puzzle. Supporting `MakeMoveVec` in programmable transactions.
Un-skipped tests.
> [ts-sdk] Support object vectors

- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/migrations/2022-12-01-034426_objects/up.sql
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/errors.rs
- crates/sui-indexer/src/models/checkpoints.rs
- crates/sui-indexer/src/models/objects.rs
- crates/sui-indexer/src/schema.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/tests/indexer_tests.rs
- crates/sui-types/src/digests.rs
Implement object read API with options, with some TODOs
- figure package and object query serving, should both base on `objects` table
- parsed object and display needs impl of module_cache on indexer
- add CI tests for object read
local run agains indexer and FN, verify that other than display and content, other fields are the same
```
--data-raw '{ "jsonrpc":"2.0", "id":1, "method":"sui_getObject", "params":["0x1ace65f54d65a96251b3f46bfa720ab65a7ebe0174caa9fa1dc0d65a56ae7872", [true, true, true, true, true, true, true]]}'
{"jsonrpc":"2.0","result":{"status":"Exists","details":{"objectId":"0x1ace65f54d65a96251b3f46bfa720ab65a7ebe0174caa9fa1dc0d65a56ae7872","version":1,"digest":"89EGgBRsPBnas …
```
> indexer: object read API with options 1/N

- crates/sui-types/src/crypto.rs
Replace ok_or with ok_or_else
All tests pass
> Replace ok_or with ok_or_else

- apps/wallet/src/ui/app/components/receipt-card/index.tsx
- apps/wallet/src/ui/app/components/transactions-card/index.tsx
> Fix transaction errors from rebasing conflicts 

- .github/workflows/rust.yml
- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/migrations/2022-11-18-195259_transactions/up.sql
- crates/sui-indexer/migrations/2022-12-01-034426_objects/up.sql
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/errors.rs
- crates/sui-indexer/src/models/objects.rs
- crates/sui-indexer/src/schema.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/mod.rs
- crates/sui-indexer/src/store/module_resolver.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/tests/indexer_tests.rs
- crates/sui-indexer/tests/integration_tests.rs
Added module cache to indexer for parsing move objects
Added Integration test
> [indexer] -  module cache

- .changeset/hot-coats-mix.md
- sdk/typescript/src/builder/Inputs.ts
- sdk/typescript/src/builder/Transaction.ts
- sdk/typescript/src/builder/TransactionData.ts
- sdk/typescript/src/signers/signer-with-provider.ts
- sdk/typescript/src/types/common.ts
- sdk/typescript/src/types/sui-bcs.ts
- sdk/typescript/test/e2e/txn-serializer.test.ts
Fixed a bug where serializing using deserialized bytes will fail.
Added e2e tests
---
> [TypeScript SDK] Fix re-serialization

- crates/sui-core/src/unit_tests/move_integration_tests.rs
- crates/sui-cost/tests/calibration.rs
- crates/sui-framework-build/src/compiled_package.rs
Just a simplification. Follow up of https://github.com/MystenLabs/sui/pull/8919#discussion_r1130902934.
> chore: use std::io::sink where possible

- crates/sui-framework-build/src/compiled_package.rs
- crates/sui/src/client_commands.rs
Factors out a helper, changes to logic, see inline comments. Follow up of https://github.com/MystenLabs/sui/pull/8919/files#r1130912245.
Stacked on https://github.com/MystenLabs/sui/pull/9074.
Run existing tests.
> client publish: helper for resolution graph construction

- crates/sui-core/src/authority.rs
- crates/sui-core/src/transaction_input_checker.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-types/src/messages.rs
As titled, testing the implications....
Existing and coming
---
> Allow dry-run to take an empty vector of gas coins

- crates/sui-core/src/unit_tests/authority_tests.rs
This test only works as simtest
> Do not run test_sui_system_state_nop_upgrade in non-sim tests

- crates/shared-crypto/src/intent.rs
- crates/sui/intent_signing.md
Add a doc here about intent signing. Before we have the new doc site, this is a place to refer to for any intent signing related questions. 
N/A
---
> crypto: Create intent_signing.md

- crates/sui-tls/src/lib.rs
- crates/sui-tls/src/verifier.rs
* within the metrics proxy, it's useful to invert the control of the allowlist and otherwise remove the concept entirely from ValidatorCertVerifier.
* to accomplish this, the Allower trait is introduced and implemented on CertVerifier.
```
pub trait Allower: Send + Sync {
fn allowed(&self, key: &Ed25519PublicKey) -> bool;
}
```
All keys for the verifier will be public keys (Ed25519PublicKey), but a future optimization could be to allow any key type on the Allower trait.  The old implementation of ValidatorCertVerifier has been removed and a default AllowAll implemenation has been provided.  Callers that use this struct are encouraged to provide their own implementation at their call sites.  Allowers should be written to be threadsafe as they will be used in multiple threads at any given …
> [sui-tls/ refactor ValidatorCertVerifier into CertVerifier

- crates/sui-core/src/unit_tests/authority_tests.rs
Test clean and CI test run
It's a test
---
> Test cleanup

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
> [db] Rename transactions to signed_transactions

- .github/workflows/simulator-nightly.yml
Updating scheduled run time and making sure that we can only run one instance at a time
👀
> [simtest]: Updating scheduled run time

- Cargo.lock
- crates/sui-core/Cargo.toml
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/sui-core/src/authority/epoch_start_configuration.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
- crates/sui-node/src/lib.rs
- crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs
- crates/sui-types/src/sui_system_state/sui_system_state_inner_v1.rs
This PR adds versioning for EpochStartConfiguration and EpochStartSystemState.
Each becomes an enum
> Version epoch start config and state

- crates/sui-faucet/src/faucet/mod.rs
- crates/sui-faucet/src/responses.rs
- sdk/typescript/src/types/faucet.ts
- sdk/typescript/test/e2e/utils/setup.ts
https://github.com/MystenLabs/sui/pull/9054 changed the case on the ts side but not on the rust side
Added new e2e tests
---
> Fix faucet response type

- .github/workflows/simulator-nightly.yml
Unstage Cargo.lock before each run
👀
> Simtest: Unstage Cargo.lock before each run

- crates/sui-framework/docs/staking_pool.md
- crates/sui-framework/sources/governance/staking_pool.move
One suinami rider noticed that the function `withdraw_rewards_and_burn_pool_tokens` is inaccurately named since it doesn't actually burn pool tokens (anymore). This PR fixes that and cleans up the comments a bit in `staking_pool` module.
No functional change
---
> [sui-framework] rename a function and clean up comments

- doc/src/siteconfig.json
Remove DevX roadmap in pull request #8701,so remove doc link
fix doc
no test required
---
> Remove DevX roadmap doc link

- crates/sui-types/src/messages.rs
Missed reordering display output for https://github.com/MystenLabs/sui/pull/9169 👎 
N/A
> programmable transactions: fix upgrade command display

- sdk/typescript/README.md
- sdk/wallet-adapter/wallet-kit/README.md
Update ts-sdk readme to reference new transaction builder.
n/a
> [ts-sdk] Update readme

- Cargo.lock
- Cargo.toml
- crates/sui-framework/src/natives/crypto/groth16.rs
- crates/workspace-hack/Cargo.toml
Update fastcrypto pointer
All tests pass
> Update fastcrypto pointer

- apps/wallet/src/manifest/manifest.json
closes [APPS-332](https://mysten.atlassian.net/browse/APPS-332?atlOrigin=eyJpIjoiMjU3MGVkMGJhNjViNDBjM2JkYWI5NzQzZjFiOWQ0NGEiLCJwIjoiaiJ9)
> wallet-ext: stricter csp

- docker/fullnode/docker-compose.yaml
- docker/sui-node/Dockerfile
- nre/README.md
- nre/ansible/README.md
- nre/ansible/inventory.yaml
- nre/ansible/roles/sui-node/files/journald.conf
- nre/ansible/roles/sui-node/files/sui-node.service
- nre/ansible/roles/sui-node/tasks/iptables.yaml
- nre/ansible/roles/sui-node/tasks/main.yaml
- nre/ansible/roles/sui-node/tasks/monitoring.yaml
- nre/ansible/roles/sui-node/tasks/sui.yaml
- nre/ansible/roles/sui-node/tasks/ubuntu.yaml
- nre/ansible/sui-node.yaml
- nre/config/validator.yaml
- nre/docker/README.md
- nre/docker/docker-compose.yaml
- nre/sui_for_node_operators.md
- nre/systemd/README.md
- nre/systemd/sui-node.service
> add node operator documentation

- crates/sui-node/src/metrics.rs
Summary:
* add a timestamp epoch value to outgoing metrics. this will represent a point of collection time from the node and help avoid out of order metric ingestion.
Test Plan:
* it builds
---
> [sui-node/add metricfamily timestamp]

- crates/sui/src/unit_tests/cli_tests.rs
After changing the default behavior of package publishing the first object in the effects is not guaranteed to be the Move package object, but could instead be the upgrade capability.
Ran the failing test a number of times and observed no more failures.
> [sui-client-tests][test fix] Fix ordering issues in publish effects

- nre/docker/docker-compose.yaml
- nre/sui_for_node_operators.md
> minor updates to node operator docs

- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/tests.rs
`change_epoch` tx is not causally ordered to be executed last, therefore we must manually ensure this. In practice, this means that its effects are persisted last.
Given the following:
1. checkpoints need not be executed in sequence number order, and
2. `TransactionManager` is responsible for persisting tx effects after being scheduled by `CheckpointExecutor`
the most obviously correct solution is to do the following (which is the approach taken in this PR):
1. At checkpoint execution time, if the checkpoint is the final of the epoch, remove `change_epoch` tx from the list of txes enqueued to `TransactionManager` (if not final checkpoint, nothing changes)
2. Once we have verified that all checkpoints but the last of the epoch has been fully executed (and all other tx effects persisited), …
> [core] Ensure change_epoch tx is executed last

- narwhal/node/src/generate_format.rs
- narwhal/node/tests/staged/narwhal.yaml
- narwhal/primary/src/block_synchronizer/mod.rs
- narwhal/primary/src/primary.rs
- narwhal/primary/src/synchronizer.rs
- narwhal/primary/src/tests/synchronizer_tests.rs
- narwhal/types/src/primary.rs
- narwhal/worker/src/handlers.rs
- narwhal/worker/src/tests/handlers_tests.rs
Unit Tests / Labnet / Benchmark
> Skip batch validation for certified batches

- doc/src/doc-updates/sui-breaking-changes.md
> Adding new Breaking Changes in Release .28 entries for 10-13

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
Bumping sui version to v0.29.0
👀
> Bumping sui version to v0.29.0

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-3.snap
- crates/sui-framework/docs/genesis.md
- crates/sui-framework/docs/stake_subsidy.md
- crates/sui-framework/sources/governance/genesis.move
- crates/sui-framework/sources/governance/stake_subsidy.move
This PR changes various constants related to stake subsidies advised by @econmysten .
---
> [sui-framework] change stake subsidy schedule

- doc/book/examples/sources/basics/display.move
- doc/book/examples/sources/basics/owned-objects.move
- doc/book/examples/sources/basics/publisher.move
- doc/book/src/SUMMARY.md
- doc/book/src/basics/display.md
- doc/book/src/basics/publisher.md
Sui Examples update - adds pages for new features: `package::Publisher` and `display`.
> [sui examples] Adds "publisher" and "display" pages

- apps/wallet/src/background/Alarms.ts
- apps/wallet/src/ui/app/components/menu/content/AutoLockTimerSelector.tsx
- apps/wallet/src/ui/app/hooks/useAutoLockInterval.ts
- apps/wallet/src/ui/app/pages/home/transfer-coin/SendTokenForm.tsx
- apps/wallet/src/ui/app/shared/InputWithAction.tsx
* add numberInput type InputWithAction component
* ensure auto-lock stores and retrieves interval always as number
closes APPS-330
> wallet-ext: fix auto lock

- .github/workflows/simulator-nightly.yml
- scripts/simtest/simtest-run.sh
1. clean up /tmpfs dir
2. Allow setting number of CPU threads in the workflow
https://github.com/MystenLabs/sui/actions/runs/4418509222/jobs/7745727449
> [simtest]: clean up /tmpfs dir and decrease number of threads

- .github/workflows/e2e.yml
This should save on some resources.
N/A
> Cancel localnet changes when in-progress

- pnpm-lock.yaml
- sdk/typescript/package.json
- sdk/typescript/tsconfig.json
Follow-up for #9262, removes a package that's no longer used.
Tests should pass.
> [ts-sdk] Remove unused packages

- crates/sui-core/src/transaction_input_checker.rs
- crates/sui-core/src/unit_tests/gas_tests.rs
- crates/sui-types/src/gas.rs
I looked at some of the TODOs and I believe some of them are MUSTFIX. Let me know if I got them wrong.
> Flag gas related MUSTFIX

- doc/src/doc-updates/sui-breaking-changes.md
- doc/src/doc-updates/sui-migration-guide.md
- doc/src/siteconfig.json
> New Migration Guide for release .28

- doc/src/build/comms.md
- doc/src/build/event_api.md
- doc/src/build/fullnode.md
- doc/src/build/index.md
- doc/src/build/install.md
- doc/src/build/json-rpc.md
- doc/src/build/rust-sdk.md
- doc/src/explore/tutorials.md
> Misc updates for style, code changes, etc

- doc/src/build/move/manifest.md
- doc/src/build/move/write-package.md
Added a topic for the move manifest, Move.toml. Navigation entry to follow in a different PR.
Local
---
> Added a move.toml topic

- doc/src/learn/object-package-versions.md
- doc/src/navconfig.json
Added versioning topic for objects and packages. Updated navigation to include all new, recent topics.
Local
---
> Added versioning topic and updated nav

- crates/sui/src/fire_drill.rs
- crates/sui/src/lib.rs
- crates/sui/src/sui_commands.rs
as title. This is still rudimentary at the moment, and we will gradually add more automation.
Ran this in labnet for all 8 validators.
---
Added a basic Firedrill tool.
> Add a Firedrill tool to Sui CLI

- doc/src/navconfig.json
Fixed a broken nav link from previous PR
Local
---
> Fixed broken nav link

- crates/sui-framework/docs/stake_subsidy.md
- crates/sui-framework/docs/sui_system.md
- crates/sui-framework/docs/sui_system_state_inner.md
- crates/sui-framework/docs/validator.md
- crates/sui-framework/sources/balance.move
- crates/sui-framework/sources/governance/stake_subsidy.move
- crates/sui-framework/sources/governance/sui_system.move
- crates/sui-framework/sources/governance/sui_system_state_inner.move
- crates/sui-framework/sources/governance/validator.move
- crates/sui-framework/sources/governance/validator_cap.move
- crates/sui-framework/sources/governance/validator_set.move
- crates/sui-framework/tests/sui_system_tests.move
This will make it easier for us to introduce new versions in the future, since we don't have to grow in the same file.
> Move sui system state inner to a separate file

- doc/src/learn/exchange-integration-guide.md
Closes https://github.com/MystenLabs/sui/issues/9317 also linked signing/multisig page here that I think its useful for exchanges. 
---
> doc: update exchange integration

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/in_memory_storage.rs
- crates/sui-types/src/storage.rs
Removed a few TODOs. Cleaned up some code duplications.
Flagged a potential bug in get move objects with MUSTFIX
> Audit Move related TODOs in sui_core

- crates/sui-rosetta/src/account.rs
- crates/sui-rosetta/src/block.rs
- crates/sui-rosetta/src/construction.rs
- crates/sui-rosetta/src/errors.rs
- crates/sui-rosetta/src/operations.rs
- crates/sui-rosetta/src/state.rs
- crates/sui-rosetta/src/types.rs
- crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs
- crates/sui-rosetta/src/unit_tests/operations_tests.rs
- crates/sui-rosetta/tests/end_to_end_tests.rs
- crates/sui-rosetta/tests/rosetta_client.rs
- crates/sui-types/src/governance.rs
* Added Stake and WithdrawStake operation using programable TX
* Added ability to query Stake, PendingStake and EstimatedReward sub accounts.
* Added more e2e test.
Unit tests and local tests
> [rosetta] - Update rosetta post Staking and Programable TX changes

- narwhal/worker/src/handlers.rs
Should save 1s per request where batch does not exist locally because of delay before retry if we just break from loop.
Unit tests
> [Narwhal] Return immediately when all missing digests have been found  in synchronizer

- crates/sui-benchmark/src/options.rs
- crates/sui-benchmark/src/workloads/batch_payment.rs
- crates/sui-benchmark/src/workloads/workload_configuration.rs
- crates/sui-benchmark/tests/simtest.rs
Adds a cli param to configure batch size for batch payment workload.
Existing tests
> Add batch configuration cli param

- crates/sui-core/src/authority.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/data/publish_with_event/Move.toml
- crates/sui-core/src/unit_tests/data/publish_with_event/sources/publish.move
- crates/sui-types/src/temporary_store.rs
Cherrypicked from main
original PR #9307
> [0.28.1 cherrypick] - [bugfix] - Parsing event might fail if the event was emitted by a new package in dev inspect (#9307)

- apps/explorer/src/pages/checkpoints/CheckpointDetail.tsx
- apps/explorer/src/pages/index.tsx
Accept digest or sequence number in Checkpoint route
---
> [explorer] - allow sequence number in checkpoint route

- crates/sui-faucet/src/errors.rs
- crates/sui-faucet/src/faucet/simple_faucet.rs
- crates/sui-faucet/src/main.rs
- crates/sui-sdk/src/apis.rs
Quick fix for the gas budget to unblock testnet. Will follow up with a PR to change rust SDK to support deriving gas price from dryrun/computation bucket.
CI
> [faucet] consider reference gas price

- apps/explorer/src/components/search/Search.tsx
- apps/explorer/src/ui/stories/Search.stories.tsx
| - | - |
| <img width="593" alt="Screenshot 2023-03-15 at 23 08 41" src="https://user-images.githubusercontent.com/10210143/225463377-4485e42e-f6ee-48f0-96ec-a5b566da294d.png"> | <img width="593" alt="Screenshot 2023-03-15 at 23 08 47" src="https://user-images.githubusercontent.com/10210143/225463441-7c8ba45b-2a8e-4c80-b497-08e028ae01b9.png"> |
closes APPS-632
> explorer: remove epochs from search placeholder

- apps/explorer/src/ui/header/NetworkSelect.tsx
Includes the version number on the Network Selector for Custom RPC
---
> [explorer] - show version for custom RPC

- crates/sui-core/src/consensus_adapter.rs
This reduces amplification from 2x (we used to get 5k narwhal TPS with 2.4k user TPS) to 20% (3.8 [narwhal TPS](https://mysten.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%228Xt1pVoVk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%228Xt1pVoVk%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28consensus_handler_processed%7Bnetwork%3D%5C%22private-testnet%5C%22,%20host%3D%5C%22ams-ptn-val-00%5C%22%7D%5B5m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-15m%22,%22to%22:%22now%22%7D%7D) with [3.2 user TPS](https://mysten.grafana.net/explore?left=%7B%22datasource%22:%228Xt1pVoVk%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%2 …
> [consensus_adapter] Measure actual consensus latency when calculating delays

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-open-rpc/src/examples.rs
> [rpc] Fix API docs

- crates/sui-framework/docs/sui_system_state_inner.md
- crates/sui-framework/docs/validator_set.md
- crates/sui-framework/docs/validator_wrapper.md
- crates/sui-framework/sources/governance/sui_system_state_inner.move
- crates/sui-framework/sources/governance/validator_set.move
- crates/sui-framework/sources/governance/validator_wrapper.move
- crates/sui-framework/tests/validator_set_tests.move
This PR migrates validator_candidates to also use ValidatorWrapper.
> Use ValidatorWrapper for validator_candidates

- crates/sui-benchmark/src/benchmark_setup.rs
- crates/sui-config/Cargo.toml
- crates/sui-config/src/builder.rs
- crates/sui-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-cost/tests/empirical_transaction_cost.rs
- crates/sui/tests/checkpoint_tests.rs
- crates/sui/tests/onsite_reconfig_observer_tests.rs
- crates/sui/tests/reconfiguration_tests.rs
- crates/sui/tests/shared_objects_tests.rs
- crates/sui/tests/shared_objects_version_tests.rs
- crates/sui/tests/transaction_orchestrator_tests.rs
- crates/test-utils/src/authority.rs
- crates/test-utils/src/messages.rs
Had to do this for #8556 and would like to get it merged earlier.
(@williampsmith did most of the work on this, i just pulled the changes out into a new PR)
> Fix all tests that insert objects into db instead of using genesis.

- crates/sui/offline_signing.md
Got asked on some questions, this is to clarify them in the doc for future reference. 
Peer review
---
> doc: Some clarifications on signatures

- nre/docker/README.md
> Update README.md small typo

- crates/sui/tests/protocol_version_tests.rs
- crates/sui/tests/reconfiguration_tests.rs
> [simtests] Add some simtests with restarting validators

- apps/wallet/src/ui/app/components/address-input/index.tsx
- apps/wallet/src/ui/app/shared/card/index.tsx
- apps/wallet/src/ui/app/staking/stake/StakingCard.tsx
- apps/wallet/src/ui/app/staking/validators/ValidatorLogo.tsx
- Update the address input to support the new address size
- added validateOnMount to the stake form 
- Center validatorLogo
---
> Wallet nit 

- crates/sui-indexer/README.md
Update sui-indexer readme w.r.t db setup
No test needed
---
> add context on db setup with diesel

- doc/src/build/sui-local-network.md
Update local network topic to use sui-test-validator binary.
Local
---
> Sui test val

- crates/sui-indexer/src/models/objects.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
cherry-picks of PRs below to testnet
https://github.com/MystenLabs/sui/pull/9315
https://github.com/MystenLabs/sui/pull/9352
> Obj delete and chunk commit cherry

- crates/sui-proxy/src/admin.rs
- crates/sui-proxy/src/config.rs
- crates/sui-proxy/src/lib.rs
- crates/sui-proxy/src/main.rs
- crates/sui-proxy/src/peers.rs
- crates/sui-proxy/src/prom_to_mimir.rs
Summary:
* addressing comments from https://github.com/MystenLabs/sui/pull/9123
Test Plan:
cargo build/test/clippy
---
> [sui-proxy/ requested comments]

- sdk/typescript/test/e2e/data/serializer/sources/serializer.move
- sdk/typescript/test/e2e/txn-builder.test.ts
> [ts-sdk] Add test for clock

- crates/sui-proxy/src/main.rs
- crates/sui-proxy/src/peers.rs
Summary:
* add a unit test that binds our fate to SuiSystemStateSummary
Test Plan:
unit tests
---
> [sui-proxy/ add unit test]

- crates/sui-core/src/unit_tests/authority_tests.rs
Three new tests exercising various error cases:
- A direct dependency missing from the `deps` list.
- An indirect dependency missing from the `deps` list.
- A dependency that is an object, and not a package.
```
$ cargo nextest run -- test_publish_missing_dependency
$ cargo nextest run -- test_publish_missing_transitive_dependency
$ cargo nextest run -- test_publish_not_a_package_dependency
```
> [upgrades] E2E Publish tests for error cases

- crates/sui-adapter-transactional-tests/tests/sui/coin_transfer.exp
- crates/sui-adapter-transactional-tests/tests/transfer_object/transfer_coin.exp
- crates/sui-adapter/src/execution_engine.rs
- crates/sui-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-3.snap
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/gas_tests.rs
- crates/sui-core/src/unit_tests/pay_sui_tests.rs
- crates/sui-cost/tests/snapshots/empirical_transaction_cost__good_snapshot.snap
- crates/sui-indexer/tests/integration_tests.rs
- crates/sui-json-rpc/src/unit_tests/rpc_server_tests.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_2.snap
- crates/sui-rosetta/src/construction.rs
- crates/sui-types/src/gas.rs
- crates/sui-types/src/object.rs
- crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs
- crates/sui-types/src/temporary_store.rs
- crates/sui/tests/protocol_version_tests.rs
Correct a couple of problems with gas. One of the change is gated by feature flag and requires a protocol version. 
So let's make sure to check that code carefully and see the tests that had to change too.
The other change is going in without protocol version and it's explained in a comment. I would love to get feedback on that.
Let me know what else you would like to see here
Existing tests. 
The indexer failure is unrelated to this change and fixes are being deployed
---
> Fixes for gas

- sdk/typescript/test/e2e/dynamic-fields.test.ts
> [ts sdk] removing comment

- crates/sui-indexer/README.md
- crates/sui-indexer/tests/integration_tests.rs
https://mysten.atlassian.net/browse/SUI-1740
---
> Indexer event query e2e

- apps/explorer/src/components/transaction-card/RecentTxCard.tsx
- apps/explorer/src/components/transaction-card/TxCardUtils.tsx
- apps/explorer/src/ui/Button.tsx
- apps/explorer/src/ui/Link.tsx
- apps/explorer/src/ui/TableCard.tsx
- apps/explorer/src/ui/stories/Icons.stories.tsx
- Update main table
- Add a story for all icons
https://mysten.atlassian.net/browse/APPS-641
---
> [Explorer]: update main table

- apps/core/src/utils/calculateAPY.ts
Fix APY calculation off by 100. Based on recent breaking changes, the calculated percentage value is off by 100, as pointed out by Alonso.
---
> Multiply apy by 100

- crates/sui/src/validator_commands.rs
> fix worker key network key mixup

- Cargo.lock
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_per_epoch_store.rs
- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-macros/Cargo.toml
- crates/sui-macros/src/lib.rs
- crates/sui-node/Cargo.toml
- crates/sui-node/src/admin.rs
- crates/sui-node/src/lib.rs
- crates/sui-node/src/main.rs
- crates/sui-simulator/src/lib.rs
- crates/sui/tests/protocol_version_tests.rs
- crates/sui/tests/reconfiguration_tests.rs
> Cherry picks for 8979 and 9497

- crates/sui-config/tests/snapshot_tests.rs
- crates/sui-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/crypto.rs
- doc/src/learn/exchange-integration-guide.md
Closes https://github.com/MystenLabs/sui/issues/9488
---
> fix: remove incorrect SuiAddress derive

- crates/sui/src/client_commands.rs
We received feedback that full transaction response is needed for debugging. Right now the output is quite verbose, but we can improve it in the future.
```
./target/debug/sui client publish --gas-budget 1000000 /Users/chrisli/sui/sdk/typescript/test/e2e/data/coin_metadata
INCLUDING DEPENDENCY Sui
INCLUDING DEPENDENCY MoveStdlib
BUILDING coin_metadata
Successfully verified dependencies on-chain against source.
----- Transaction Digest ----
7pMoKsnEraqX7y3VrZ3gg2CEeGj25FAsKjvP3j6rkGTL
----- Transaction Data ----
Transaction Signature: [Signature(Ed25519SuiSignature(Ed25519SuiSignature([0, 146, 9, 239, 39, 102, 35, 94, 77, 134, 177, 249, 123, 130, 228, 120, 72, 126, 238, 181, 195, 109, 161, 199, 15, 141, 163, 200, 214, 15, 98, 54, 204, 191, 204, 19, 238, 120, 149, 35, 39, 146, 163, 103, 53, …
```
> [cli] print out full transaction response

- doc/src/build/sui-local-network.md
> Add instruction for CLI connection in sui-local-network.md

- Cargo.lock
- crates/sui-adapter/src/execution_mode.rs
- crates/sui-config/Cargo.toml
- crates/sui-config/src/genesis.rs
- crates/sui-config/src/genesis_config.rs
- crates/sui-config/tests/snapshot_tests.rs
- crates/sui-config/tests/snapshots/snapshot_tests__genesis_config_snapshot_matches.snap
- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/epoch_time_lock.md
- crates/sui-framework/docs/genesis.md
- crates/sui-framework/docs/locked_coin.md
- crates/sui-framework/docs/sui_system_state_inner.md
- crates/sui-framework/docs/validator.md
- crates/sui-framework/docs/validator_set.md
- crates/sui-framework/sources/epoch_time_lock.move
- crates/sui-framework/sources/governance/genesis.move
- crates/sui-framework/sources/governance/sui_system_state_inner.move
- crates/sui-framework/sources/governance/validator.move
- crates/sui-framework/sources/governance/validator_set.move
- crates/sui-framework/sources/locked_coin.move
- crates/sui-framework/tests/validator_tests.move
- crates/workspace-hack/Cargo.toml
> genesis: initial work of integrating a distribution schedule

- .changeset/polite-owls-begin.md
- crates/sui-core/src/authority.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-json-rpc-types/src/sui_checkpoint.rs
- crates/sui-json-rpc/src/api/mod.rs
- crates/sui-json-rpc/src/api/read.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-types/src/messages_checkpoint.rs
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/checkpoints.ts
- sdk/typescript/test/e2e/checkpoint.test.ts
add getCheckpoints paginated
added test_get_checkpoints() in rpc_server_tests.rs
---
> getCheckpoints

- crates/sui/src/fire_drill.rs
- crates/sui/src/validator_commands.rs
Increase gas budget to unblock validators while we are investigating a potential issue.
---
> up gas budget for request_add_validator_candidate

- .changeset/polite-owls-begin.md
- crates/sui-core/src/authority.rs
- crates/sui-core/src/checkpoints/mod.rs
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-json-rpc-types/src/sui_checkpoint.rs
- crates/sui-json-rpc/src/api/mod.rs
- crates/sui-json-rpc/src/api/read.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-types/src/messages_checkpoint.rs
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/checkpoints.ts
- sdk/typescript/test/e2e/checkpoint.test.ts
add getCheckpoints paginated
added test_get_checkpoints() in rpc_server_tests.rs
---
---------
---
> [cherrypick] getCheckpoints (#9263)

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/models/addresses.rs
- crates/sui-indexer/src/models/transactions.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/types.rs
- crates/sui-indexer/tests/integration_tests.rs
Per feedback from Adeniyi on wave 2, we want to include recipients in address table as well
future work: talk with FE team to see how they plan to query address and plan accordingly
Added test and CI
> Indexer: add recipients to address table and address number API

- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/tests/integration_tests.rs
construct cmd line config for method migration gatekeeper, also flip the default logic to better map the progress from empty array.
CI
> indexer easy: migration method gatekeeper config

- crates/sui/src/sui_commands.rs
Minor copyedit changes to Client CLI user-facing strings
---
> Update user strings in CLI commands

- nre/sui_for_node_operators.md
> [minor doc fix] include gas-budget in candidate joining command

- crates/sui-cluster-test/src/cluster.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/tests/integration_tests.rs
> [easy][indexer] use migrated endpoints for sui-test-validator

- crates/sui-indexer/src/store/pg_indexer_store.rs
Thanks to Jian who found this bug.
> easy: fix indexer all txn pagination

- crates/sui-core/src/authority.rs
- crates/sui-core/src/scoring_decision.rs
This will make it easier to visualize the score breakdown. Since we didn't have a tag before for host also, the data emitted was not clear. 
---
> update metric type for scoring

- crates/sui-framework/docs/devnet_nft.md
- crates/sui-framework/docs/sui_system_state_inner.md
- crates/sui-framework/docs/validator.md
- crates/sui-framework/docs/validator_cap.md
- crates/sui-framework/docs/voting_power.md
- crates/sui-framework/sources/devnet_nft.move
- crates/sui-framework/sources/governance/sui_system.move
- crates/sui-framework/sources/governance/sui_system_state_inner.move
- crates/sui-framework/sources/governance/validator.move
- crates/sui-framework/sources/governance/validator_cap.move
- crates/sui-framework/sources/governance/voting_power.move
> Audit Move framework TODOs

- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-types/src/gas.rs
- crates/sui-types/src/messages.rs
- crates/sui-types/src/temporary_store.rs
A few last TODOs in sui-types, turning some to MUSTFIX.
> Audit TODOs in sui-types

- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/migrations/2023-03-20-041133_epoch/down.sql
- crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql
- crates/sui-indexer/migrations/2023-03-20-042226_system_state/down.sql
- crates/sui-indexer/migrations/2023-03-20-042226_system_state/up.sql
- crates/sui-indexer/src/apis/extended_api.rs
- crates/sui-indexer/src/apis/mod.rs
- crates/sui-indexer/src/errors.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/models/epoch.rs
- crates/sui-indexer/src/models/mod.rs
- crates/sui-indexer/src/models/system_state.rs
- crates/sui-indexer/src/schema.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/tests/integration_tests.rs
- crates/sui-json-rpc-types/src/lib.rs
- crates/sui-json-rpc-types/src/sui_extended.rs
- crates/sui-json-rpc/src/api/extended.rs
- crates/sui-json-rpc/src/api/mod.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-open-rpc/src/generate_json_rpc_spec.rs
- crates/sui-types/src/sui_system_state/sui_system_state_summary.rs
- crates/workspace-hack/Cargo.toml
* store system_state
* store epoch
* added get_epochs and get_current_epoch methods.
added integration test for getting epochs
> [indexer] - suix_getEpochs and suix_getCurrentEpoch APIs

- crates/sui-indexer/tests/integration_tests.rs
Not a new feature, but ci should still pass.
---
> e2e test for get_object_with_options, testing out some data options and when object does not exist

- crates/shared-crypto/src/intent.rs
- crates/sui-adapter-transactional-tests/tests/child_count/non_zero_child_count_valid.exp
- crates/sui-adapter-transactional-tests/tests/child_count/non_zero_child_count_valid.move
- crates/sui-adapter-transactional-tests/tests/children/child_of_shared_object.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/add_duplicate_object.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/borrow_wrong_type_object.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/exhaustive_object.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/remove_wrong_type_object.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/wrap_object.exp
- crates/sui-adapter-transactional-tests/tests/dynamic_fields/wrap_object.move
- crates/sui-adapter-transactional-tests/tests/entry_points/obj_vector.exp
- crates/sui-adapter-transactional-tests/tests/entry_points/obj_vector_generic.exp
- crates/sui-adapter-transactional-tests/tests/shared/upgrade.exp
- crates/sui-adapter-transactional-tests/tests/transfer_object/package.exp
- crates/sui-adapter-transactional-tests/tests/transfer_object/quasi_shared.exp
- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-types/src/crypto.rs
- sui_programmability/examples/games/tests/drand_based_scratch_card_tests.move
Closes https://github.com/MystenLabs/sui/issues/9544
Existing tests
---
> crypto: ensure domain separator between address and object id

- scripts/update_move.sh
Script automatically bumps the commit of Move that Sui depends on (defaults to the current tip of `sui-move` in `move-language/move`).
Going to be used in anger in the following PR
> [chore] Script to bump Move dependency

- crates/sui-framework/src/natives/object_runtime/object_store.rs
If there is a bug `ChildObjectResolver::read_child_object` that allows an attacker to look up a child object that does not belong to the parent (e.g., I believe the bug fixed by https://github.com/MystenLabs/sui/pull/7937 falls into this category), we will detect it and fail at runtime with an `InvariantViolation`.
---
> [hardening] dynamic check for child object authentication

- .config/hakari.toml
- Cargo.lock
- Cargo.toml
- crates/sui-adapter/src/adapter.rs
- crates/sui-adapter/src/programmable_transactions/types.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/temporary_store.rs
- crates/workspace-hack/Cargo.toml
Move bump to introduce relinking support in the loader.
```
$ cargo nextest run
```
> [move] Move Bump

- apps/core/tailwind.config.js
- apps/explorer/src/ui/Pagination.tsx
- apps/explorer/src/ui/stories/Pagination.stories.tsx
- apps/icons/src/PaginationFirst24.tsx
- apps/icons/src/PaginationNext24.tsx
- apps/icons/src/PaginationPrev24.tsx
- apps/icons/svgrrc.config.js
Adds a new pagination component, based on the current figma designs.
Storybook.
> [explorer] Add new pagination component

- apps/explorer/src/components/transaction-card/TxCardUtils.tsx
- apps/explorer/src/pages/transaction-result/TransactionView.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Command.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Commands.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Inputs.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/__test__/utils.test.ts
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/index.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/utils.ts
- apps/explorer/src/ui/InternalLink.tsx
- sdk/typescript/src/types/transactions.ts
- First draft for Prog Txns
https://mysten.atlassian.net/browse/APPS-557
more changes to follow after https://github.com/MystenLabs/sui/pull/9448
- Need advice on formatting data, will connect with Ux on specifics
- Should we check for Address vs Object types here. I am seeing them being all Addresses so far. Open for suggestions
- Tests will follow on subsequent PRs
---
> [Explorer]: Programmable Txns Input and Command section

- apps/explorer/src/pages/transaction-result/Signatures.tsx
> [explorer] fix signatures panel being squished together

- narwhal/node/src/main.rs
> [DO NOT LAND] Experiment w/ NW parameters

- doc/src/build/move/debug-publish.md
Small changes not saved for previous PR
Locally
---
> Small format changes

- crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs
This is https://github.com/MystenLabs/sui/pull/9675 but merge to main (we may not need this in main but it doesn't hurt anyway).
---
> ignore invalid p2p address

- narwhal/node/src/main.rs
> Revert "[DO NOT LAND] Experiment w/ NW parameters"

- crates/sui-core/src/narwhal_manager/mod.rs
- narwhal/node/src/main.rs
> Nw experiment

- nre/sui_for_node_operators.md
update docs link to validator metadata update functions
> update sui_for_node_operators.md docs code pointer

- .github/workflows/simulator-nightly.yml
Switch over to use teleport on a separate gh runner
Tested via the my branch https://github.com/MystenLabs/sui/actions/runs/4494648554
> Simtest: Switch over to use teleport and separate gh runner

- Cargo.lock
- Cargo.toml
- crates/sui-rpc-loadgen/Cargo.toml
- crates/sui-rpc-loadgen/README.md
- crates/sui-rpc-loadgen/src/load_test.rs
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
> [loadgen][1/n] RPC load generator

- crates/sui-node/src/lib.rs
After processing CapabilityNotification, not key is written to the `consensus_message_processed` table, so waiters in ConsensusAdapter will never get notified.
Similar for CheckpointSignature, submit to Narwhal directly.
Also, block if the submission of CapabilityNotification to Narwhal failed.
Existing tests
---
> Submit CapabilityNotification directly to Narwhal

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/tests/integration_tests.rs
Fixed CI, it was b/c the splitting that happened in https://github.com/MystenLabs/sui/pull/9618
A couple of other changes:
- added checkpoint read test around epoch boundary
- add timeout to wait_until
integration test both locally and on CI
> indexer: fix indexer CI

- crates/sui-indexer/src/test_utils.rs
- crates/sui-indexer/tests/integration_tests.rs
Update SuiTransaction builder to just take in the full response and build the test object accordingly.
ci
---
> fix transaction integration test

- crates/sui-json-rpc/src/read_api.rs
- crates/sui-json-rpc/src/unit_tests/rpc_server_tests.rs
do not return error when get package with display option
Changes coved by unit test
> do not return error when get package with display option

- crates/sui-core/src/narwhal_manager/mod.rs
- narwhal/node/src/main.rs
> Revert "Nw experiment"

- crates/sui-core/src/narwhal_manager/mod.rs
> [DO NOT LAND] nw_1

- crates/sui-indexer/src/apis/extended_api.rs
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/tests/integration_tests.rs
- crates/sui-json-rpc/src/api/extended.rs
- crates/sui-open-rpc/spec/openrpc.json
Count for this section on Explorer
Added CI tests
> indexer: count metrics APIs

- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/models/transactions.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/utils.rs
- crates/sui-indexer/tests/integration_tests.rs
- crates/sui-json-rpc-types/src/balance_changes.rs
- crates/sui-json-rpc-types/src/object_changes.rs
- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-json-rpc/src/balance_changes.rs
- crates/sui-json-rpc/src/object_changes.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-json-rpc/src/transaction_execution_api.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-open-rpc/src/examples.rs
- crates/sui-rosetta/src/construction.rs
- crates/sui-rosetta/src/operations.rs
- crates/test-utils/src/transaction.rs
- sdk/typescript/src/types/transactions.ts
main things are:
- balance changes and object changes refactoring on JSON RPC to unblock indexer
- indexer balance and object changes impl
- read events from PG
CI with integration test changes
> json rpc & indexer: last piece to make indexer txn response complete

- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/tests/integration_tests.rs
The return results should respect the input digest order.
Added CI tests
> Indexer: respect input transaction digest order

- crates/sui-rpc-loadgen/README.md
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
> consolidate multiGetTransactions into GetCheckpoints(verify_transaction)

- crates/sui-config/src/genesis.rs
- crates/sui/src/genesis_ceremony.rs
> genesis: introduce logic for validating input and output data

- narwhal/consensus/benches/process_certificates.rs
Fixing linter errors in the process-certificates microbenchmark
---
> [fix] fix linter error

- doc/src/learn/sponsored-transactions.md
Remove the section as it's no longer relevant 
---
remove the consideration section for Sponsored transaction doc
> remove the consideration section for Sponsored transaction doc

- crates/sui-framework/docs/hmac.md
- crates/sui-framework/packages/sui-framework/sources/crypto/hmac.spec.move
The name of the spec block should match the function name.
---
> [sui-framework] change hmac function name in spec to match source

- crates/sui-rpc-loadgen/README.md
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
> Loadgen support verify objects

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/voting_power.md
- crates/sui-framework/packages/sui-system/sources/voting_power.move
Fix two issues reported:
1. Wrong variable. Rename to a/b for better visual clarity.
2. No need for public interface
> Fix voting power issue

- crates/sui-rosetta/src/construction.rs
- crates/sui-rosetta/src/state.rs
This PR contains fixes for incorrect gas price and balance extraction error.
These changes are tested manually in testnet
> [rosetta] - cherrypick hotfixs from rosetta-testnet branch

- Cargo.lock
- crates/sui-rpc-loadgen/Cargo.toml
- crates/sui-rpc-loadgen/src/load_test.rs
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
- crates/workspace-hack/Cargo.toml
> [loadgen] refactor paySui

- crates/sui-indexer/tests/integration_tests.rs
e2e test for get_checkpoint on indexer
ci
---
> Indexer get checkpoint e2e

- crates/sui-json-rpc/src/read_api.rs
- crates/sui-storage/src/indexes.rs
- crates/sui/src/unit_tests/cli_tests.rs
> [rust sdk] adding pagination testing and fixing owned_object bug

- narwhal/primary/src/proposer.rs
> [DO NOT LAND] Changing proposer logic to wait for more leader support

- apps/wallet/src/ui/app/components/user-approve-container/index.tsx
- apps/wallet/src/ui/app/pages/approval-request/SignMessageRequest.tsx
- apps/wallet/src/ui/app/pages/approval-request/transaction-request/index.tsx
- apps/wallet/src/ui/app/pages/site-connect/index.tsx
* fix loading state for user approve container
Before
https://user-images.githubusercontent.com/10210143/227625971-11a45bf1-1035-431b-baff-a91057c7aafb.mov
After
https://user-images.githubusercontent.com/10210143/227626011-2dc44bdc-ef88-4f51-9644-5b380d8e7aee.mov
> wallet-ext: user-approve-container fix submitting state

- apps/explorer/src/components/validator/ValidatorStats.tsx
- apps/explorer/src/hooks/useGetValidatorsEvents.ts
- apps/explorer/src/pages/validator/ValidatorDetails.tsx
- apps/explorer/src/pages/validators/Validators.tsx
Add epoch rewards to the validator page
---
> fix last epoch rewards

- crates/sui-indexer/migrations/2022-11-18-195259_transactions/up.sql
- crates/sui-indexer/src/models/transactions.rs
- crates/sui-indexer/src/schema.rs
Related to https://github.com/MystenLabs/sui/pull/9758
CI
Local run to make sure he field is populated.
> Indexer: add non_refundable_storage_fee from cost summary

- crates/sui-indexer/migrations/2023-03-05-165748_transaction_index/up.sql
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/apis/transaction_builder_api.rs
- crates/sui-indexer/src/bin/indexer_data_validation.rs
- crates/sui-indexer/src/models/checkpoints.rs
- crates/sui-indexer/src/models/transaction_index.rs
- crates/sui-indexer/src/models/transactions.rs
- crates/sui-indexer/src/schema.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/types.rs
- crates/sui-indexer/tests/integration_tests.rs
- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-storage/src/indexes.rs
- crates/sui-types/src/query.rs
- Per feature request of FE team, added these 2 query types.
- Also renamed txn to tx
Added CI tests and CI
> indexer: support tx query by kind and fromTo

- crates/sui-config/tests/snapshot_tests.rs
> Temporarily disable snapshot test

- crates/sui-config/tests/snapshot_tests.rs
- crates/sui-framework/docs/versioned.md
- crates/sui-framework/packages/sui-framework/sources/versioned.move
- crates/sui-framework/packages/sui-framework/tests/versioned_tests.move
The cost of not having a test.
Will add a test latter.
> Fix a bug in versioned

- .config/hakari.toml
- Cargo.lock
- Cargo.toml
- crates/sui-adapter/src/programmable_transactions/execution.rs
- crates/sui/tests/reconfiguration_tests.rs
- crates/workspace-hack/Cargo.toml
This bump incorporates:
- Linker support for type origin table ("defining module").
- Fix for temporary lock files not honouring `BuildConfig::install_dir`.
- Additional information in normalized modules.
Also regenerates `sui-framework` docs which were, for some reason, stale.
```
```
> [move] Bump Move pointer

- narwhal/executor/src/subscriber.rs
- narwhal/primary/src/proposer.rs
Reduce verbosity for two log entries that have not been very useful.
n/a
---
> [Narwhal] reduce log verbosity

- crates/mysten-network/src/multiaddr.rs
- crates/sui-config/src/genesis.rs
- crates/sui-framework/docs/sui_system_state_inner.md
- crates/sui-framework/docs/validator.md
- crates/sui-framework/packages/sui-system/sources/sui_system_state_inner.move
- crates/sui-framework/packages/sui-system/sources/validator.move
- crates/sui-framework/packages/sui-system/tests/validator_tests.move
As title
Existing move tests.
---
Add more restrictions for validator metadata
> add more restrictions for validator metadata

- crates/sui-indexer/tests/integration_tests.rs
- crates/sui-json-rpc-types/src/sui_object.rs
- crates/sui-transaction-builder/src/lib.rs
> [indexer] fix ci flakiness

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/metrics.rs
Indexer metrics have been out of date after recent changes.
CI
> indexer: metrics on the writing path

- .changeset/ten-phones-thank.md
- sdk/typescript/README.md
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/sui-bcs.ts
- Update Readme
- bump TARGETED_RPC_VERSION to 0.28.0 
CI
> [ts-sdk] update readme + bump TARGETED_RPC_VERSION

- Cargo.lock
- Cargo.toml
- crates/typed-store/src/rocks/mod.rs
- narwhal/primary/src/primary.rs
- narwhal/primary/src/proposer.rs
- narwhal/worker/src/worker.rs
> Private testnet 0325

- .changeset/ten-phones-thank.md
- sdk/typescript/README.md
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/sui-bcs.ts
- Update Readme
- bump TARGETED_RPC_VERSION to 0.28.0 
CI
---
> [cherrypick][ts-sdk] update readme + bump TARGETED_RPC_VERSION (#9259)

- Cargo.lock
- crates/sui-core/src/authority.rs
- crates/sui-indexer/src/apis/extended_api.rs
- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-indexer/src/store/query.rs
- crates/sui-indexer/tests/integration_tests.rs
- crates/sui-json-rpc-types/src/sui_object.rs
- crates/sui-json-rpc/src/api/extended.rs
- crates/sui-json-rpc/src/api/indexer.rs
- crates/sui-json-rpc/src/coin_api.rs
- crates/sui-json-rpc/src/indexer_api.rs
- crates/sui-json-rpc/src/transaction_builder_api.rs
- crates/sui-json-rpc/src/unit_tests/rpc_server_tests.rs
- crates/sui-json-rpc/src/unit_tests/transaction_tests.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs
- crates/sui-sdk/Cargo.toml
- crates/sui-sdk/examples/get_owned_objects.rs
- crates/sui-sdk/src/apis.rs
- crates/sui-sdk/src/lib.rs
- crates/sui-storage/src/indexes.rs
- crates/sui-transaction-builder/src/lib.rs
- crates/sui-types/src/object.rs
- crates/sui/src/client_commands.rs
- crates/sui/src/unit_tests/cli_tests.rs
- crates/test-utils/src/transaction.rs
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/objects.ts
implement get own object in indexer
added at checkpoint to cursor instead of separated parameter
Integration tests
> [indexer] - implement get own object in indexer

- crates/sui-json-rpc/src/read_api.rs
Multiple tx share the same event could happen, because event doesn't have id or timestamp, if the content is the same they will have the same digest
Build
---
> [rpc] Fix wrong assumption about event digests

- doc/src/doc-updates/sui-migration-guide.md
> Add Framework split migration info

- apps/explorer/vercel.json
- dapps/frenemies/vercel.json
- sdk/wallet-adapter/example/vercel.json
Re-enabling releases from main.
N/A
> [apps] Re-enable releases

- crates/sui-types/src/base_types.rs
- crates/sui-types/src/multisig.rs
- crates/sui-types/src/signature.rs
- crates/sui-types/src/unit_tests/multisig_tests.rs
Small changes of multisig
Unit tests
> Small changes of multisig

- .github/workflows/bench.yml
- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/benches/indexer_benchmark.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/main.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/test_utils.rs
- crates/sui-indexer/tests/integration_tests.rs
- crates/workspace-hack/Cargo.toml
Added benchmark for checkpoint read and write
tested locally by running `cargo +nightly bench --bench indexer_benchmark` (need to have a pgdb running locally)
Not sure how to test GitHub action which will be triggered by merging to main.
> [indexer] - indexer benchmark

- narwhal/primary/src/aggregators.rs
- narwhal/primary/src/certifier.rs
- narwhal/primary/src/primary.rs
- narwhal/primary/src/tests/certificate_tests.rs
- narwhal/storage/src/vote_digest_store.rs
- narwhal/test-utils/src/lib.rs
- narwhal/types/src/primary.rs
> Wrap NW Vote/VoteInfo in versioned enum

- Cargo.lock
- narwhal/storage/Cargo.toml
- narwhal/storage/src/certificate_store.rs
- narwhal/storage/src/lib.rs
- narwhal/storage/src/payload_store.rs
Follow up from https://github.com/MystenLabs/sui/pull/9387#discussion_r1139439908
---
> [refactor] extract NotifyRead and use in Narwhal store

- crates/sui-core/src/consensus_handler.rs
- crates/sui-core/src/consensus_validator.rs
- crates/sui-core/src/unit_tests/narwhal_manager_tests.rs
- narwhal/executor/src/subscriber.rs
- narwhal/node/src/execution_state.rs
- narwhal/node/tests/staged/narwhal.yaml
- narwhal/primary/src/grpc_server/validator.rs
- narwhal/primary/src/tests/block_waiter_tests.rs
- narwhal/primary/tests/integration_tests_validator_api.rs
- narwhal/types/src/primary.rs
- narwhal/types/src/tests/batch_serde.rs
- narwhal/worker/src/batch_maker.rs
- narwhal/worker/src/tests/batch_maker_tests.rs
- narwhal/worker/src/tests/worker_tests.rs
> Wrap NW Batch in versioned enum

- crates/sui-protocol-config/src/lib.rs
> state digest feature flag bug fix

- .github/actions/diffs/action.yml
The filters are pretty out of date. This PR updates them.
---
> update isMove filter in actions

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Command.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Commands.tsx
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/__test__/utils.test.ts
- apps/explorer/src/pages/transaction-result/programmable-transaction-view/index.tsx
- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-open-rpc/spec/openrpc.json
- sdk/typescript/src/types/transactions.ts
> Cherry-pick command RPC reference removal (#9984)

- crates/sui-faucet/src/metrics_layer.rs
Adding some additional logging in faucet to get visibility in errors produced probably via some middleware, as the only thing we currently see is:
```
sui_faucet::metrics_layer: Request failed in 0.00s
```
---
> [refactor] additional error login in faucet

- crates/sui-faucet/src/metrics_layer.rs
Adding some additional logging in faucet to get visibility in errors produced probably via some middleware, as the only thing we currently see is:
```
sui_faucet::metrics_layer: Request failed in 0.00s
```
---
--- …
> [cherrypick][refactor] additional error login in faucet (#9987)

- .github/workflows/release.yml
Add indexer binary to release builds
> Add indexer binary to release builds

- .github/workflows/rust.yml
- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/sui_system.md
- crates/sui-framework/docs/validator_wrapper.md
- crates/sui-framework/packages/sui-system/sources/sui_system.move
- crates/sui-framework/packages/sui-system/sources/validator_wrapper.move
- crates/sui/tests/protocol_version_tests.rs
Wrote documentation on how to upgrade sui system state, and added a template test that we could use whenever we need to upgrade in prod.
> Sui System State Upgrade Guide

- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
> indexer: return full contents for query transactions

- .changeset/gold-coins-visit.md
- apps/explorer/src/components/HomeMetrics/index.tsx
- apps/explorer/src/pages/home/Home.tsx
- apps/explorer/src/ui/Card.tsx
- apps/explorer/src/ui/Stats.tsx
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/metrics.ts
This migrates explorer to use the new enhanced FN metrics instead of the apps backend.
Ran locally.
> [explorer] Use enhanced fn metrics

- Cargo.lock
- crates/sui-rpc-loadgen/Cargo.toml
- crates/sui-rpc-loadgen/src/load_test.rs
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/get_checkpoints.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
- crates/sui-rpc-loadgen/src/payload/validation.rs
> Add entity caches to rpc_command_processor to be written to file when tests are finished

- .github/actions/turbo-diffs/action.yml
- .github/workflows/changesets-ci.yml
- .github/workflows/changesets.yml
- .github/workflows/e2e.yml
- .github/workflows/turborepo.yml
- pnpm-lock.yaml
Updates pnpm to the `@latest` tag.
CI
> [pnpm] Update to 8.0.0

- apps/wallet/src/ui/app/ApiProvider.ts
Adding back testnet faucet.
simple change
> [wallet-ext] Add back testnet faucet

- apps/core/src/hooks/useTimeAgo.ts
Fix the bug that prevent count down on transaction table
https://user-images.githubusercontent.com/126525197/228353286-c94f5a9b-5c12-4e5e-a4a7-1b65d058575a.mov
https://user-images.githubusercontent.com/126525197/228353383-cea1771e-18f5-4cd6-aa7d-375460884fac.mov
---
> fix timeAgo bug

- .github/workflows/simulator-nightly.yml
- scripts/simtest/simtest-run.sh
fix setting env. variables
https://github.com/MystenLabs/sui/actions/runs/4545908860/jobs/8013867414
> simtest: fix setting env. variables

- crates/sui-config/tests/snapshots/snapshot_tests__populated_genesis_snapshot_matches-2.snap
- crates/sui-framework/docs/genesis.md
- crates/sui-framework/docs/stake_subsidy.md
- crates/sui-framework/docs/sui_system.md
- crates/sui-framework/docs/sui_system_state_inner.md
- crates/sui-framework/docs/validator.md
- crates/sui-framework/docs/validator_set.md
- crates/sui-framework/packages/sui-system/sources/genesis.move
- crates/sui-framework/packages/sui-system/sources/stake_subsidy.move
- crates/sui-framework/packages/sui-system/sources/sui_system.move
- crates/sui-framework/packages/sui-system/sources/sui_system_state_inner.move
- crates/sui-framework/packages/sui-system/sources/validator.move
- crates/sui-framework/packages/sui-system/sources/validator_set.move
- crates/sui-framework/packages/sui-system/tests/rewards_distribution_tests.move
Give names to error codes in `sui-system` package modules.
Existing tests should pass.
---
> [sui-system] clean up error codes

- crates/typed-store/src/rocks/mod.rs
See https://github.com/facebook/rocksdb/wiki/Pipelined-Write
> Possible rocksdb performance enhancement

- doc/src/build/snapshot.md
- doc/src/navconfig.json
Database snapshot document.
Locally
---
> Adding snapshot document

- apps/wallet/src/ui/index.tsx
Small change to turn on strict mode for the wallet to find potential issues during development (the Explorer already has strict mode enabled).
- Nothing obvious broke in development mode 🤷🏼‍♂️ 
---
N/A
> [wallet-ext] enable React strict mode 

- crates/sui-core/src/authority.rs
- crates/sui-types/src/messages.rs
As title
CI
---
Added sponsored tx number as metrics
> Add sponsored tx num as metrics

- crates/sui-core/src/checkpoints/mod.rs
we're still apparently deserializing sigs slowly, so this may actually help a bit.
> Quick optimization for consensus task

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority_server.rs
- crates/sui-core/src/unit_tests/execution_driver_tests.rs
We already check transaction manager pending queue and per-object dependencies during the handle_transaction in AuthorityState. It makes more sense to not sign the transaction in case the system is overloaded, than to sign the transaction and refuse handling the certificate.
---
> Move overload checks from handle_certificate to handle_transaction

- doc/src/build/fullnode.md
- doc/src/build/install.md
- doc/src/doc-updates/index.md
Adding new content and updates for recent releases.
---
> Updating doc history for recent changes

- .changeset/perfect-waves-bake.md
- sdk/typescript/src/types/objects.ts
- sdk/typescript/src/utils/errors.ts
> [ts-sdk] improve error handling and fix PaginatedObjectResponse

- crates/sui-json-rpc/src/read_api.rs
Adding logging to RPC layer for objects for better debugging.
---
> [rust API][1/n] adding logging to RPC layer for objects

- .github/workflows/e2e.yml
see inline comments
https://github.com/MystenLabs/sui/pull/10071/files
> Add retry for ts e2e test

- sdk/typescript/README.md
> [sdk] Fix README - add transfer of the UpgradeCap

- crates/sui-indexer/src/models/events.rs
- crates/sui-indexer/src/store/query.rs
- crates/sui-json-rpc-types/src/balance_changes.rs
- crates/sui-json-rpc-types/src/object_changes.rs
- crates/sui-json-rpc-types/src/sui_event.rs
- crates/sui-json-rpc-types/src/sui_move.rs
- crates/sui-json-rpc-types/src/sui_object.rs
- crates/sui-json-rpc-types/src/sui_transaction.rs
- crates/sui-json-rpc-types/src/unit_tests/rpc_types_tests.rs
- crates/sui-open-rpc/src/examples.rs
- crates/sui-types/src/dynamic_field.rs
- crates/sui-types/src/sui_serde.rs
> [bugfix] - invalid struct tag: 0x1::address::MyType, expected name, got AddressType

- Cargo.toml
Make it easier to build with debug symbols.
n/a
---
> Add build mode with debug symbols

- apps/explorer/src/pages/checkpoints/CheckpointDetail.tsx
- apps/explorer/src/pages/checkpoints/CheckpointTransactionBlocks.tsx
- apps/explorer/src/pages/checkpoints/CheckpointsTable.tsx
Rename Transaction -> Transaction Blocks in Checkpoint details
👀 
---
> [explorer] - checkpoints - rename transactions 

- apps/core/tailwind.config.js
- apps/explorer/.prettierignore
- apps/explorer/src/components/Activity/index.tsx
- apps/explorer/src/components/HomeMetrics/index.tsx
- apps/explorer/src/components/validator/ValidatorStats.tsx
- apps/explorer/src/hooks/useEnhancedRpc.ts
- apps/explorer/src/pages/checkpoints/CheckpointsTable.tsx
- apps/explorer/src/pages/epochs/EpochDetail.tsx
- apps/explorer/src/pages/epochs/EpochTimer.tsx
- apps/explorer/src/pages/epochs/EpochsTable.tsx
- apps/explorer/src/pages/epochs/stats/EpochProgress.tsx
- apps/explorer/src/pages/epochs/stats/ValidatorStatus.tsx
- apps/explorer/src/pages/epochs/useEpochProgress.ts
- apps/explorer/src/pages/index.tsx
- apps/explorer/src/pages/validators/Validators.tsx
- apps/explorer/src/ui/InternalLink.tsx
- apps/explorer/src/ui/Pagination.tsx
- apps/explorer/src/ui/ProgressCircle.tsx
- apps/explorer/src/ui/RingChart.tsx
- apps/explorer/src/ui/stories/ProgressCircle.stories.tsx
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/epochs.ts
- sdk/typescript/src/types/validator.ts
Adds Epochs pages to Explorer 
---
> [explorer] - add epochs pages

- doc/src/build/fullnode.md
Format fix so lists display correctly.
local
---
> Format change on Full node topic

- crates/sui-json-rpc/src/read_api.rs
adding logging on transactions digest and checkpoint ids
---
> [rust api][2/n] adding logging on transactions digest and checkpoint ids

- apps/explorer/src/context.ts
- apps/explorer/src/utils/api/DefaultRpcClient.ts
- apps/wallet/configs/environment/.env.defaults
Set the default network for explorer to Testnet
---
> set explorer default network to Testnet

- apps/explorer/src/pages/epochs/EpochDetail.tsx
- apps/explorer/src/pages/validators/Validators.tsx
- apps/wallet/src/ui/app/staking/validators/SelectValidatorCard.tsx
* by default the list of validators is now random
https://user-images.githubusercontent.com/10210143/228676249-8782a1dd-f27f-4de3-a0da-083ceabcd829.mov
https://user-images.githubusercontent.com/10210143/228676252-d8723e4f-5eb3-4e60-b495-8a70d8e80b8a.mov
closes APPS-702
> wallet-ext:explorer: random sorting for validators list

- apps/explorer/src/components/transactions/TxCardUtils.tsx
- apps/explorer/src/hooks/useGetTransaction.ts
Reworks transaction block table to remove amounts and show transaction count.
Ran locally.
> [explorer] Tweak to show transactions count

- crates/sui-core/src/authority.rs
> [dry-transaction] Update storage gas price returned

- crates/sui-json-rpc/src/read_api.rs
Full Node's `get_transaction_block` tries to handle temp txs by checking if a given transaction digest can be mapped to a checkpoint.
This leads to unexpected behavior where a digest for a nonexistent transaction with options=None will return a success response. This is because `get_transaction_block` doesn't actually check if the transaction exists in the first place. We now unconditionally make a `get_executed_transaction` check to avoid this state.
---
> error on temp txs

- crates/sui-benchmark/src/workloads/batch_payment.rs
- crates/sui-core/src/test_utils.rs
Increase gas coin budget and primary coin value to support large batch sizes
Deployed in labnet
> Increase coin value and gas budget for large batch sizes

- crates/sui-types/src/crypto.rs
Clean-up in the crypto.rs file.
Unit tests.
> Crypto cleanup

- apps/explorer/src/components/transactions/TxCardUtils.tsx
- apps/explorer/src/pages/transaction-result/Signatures.tsx
- Update both success and failure to use Icons
- https://mysten.atlassian.net/browse/APPS-704
---
> [explorer]: update styling

- apps/core/src/hooks/useGetValidatorsEvents.ts
- sdk/typescript/src/framework/framework.ts
- sdk/typescript/src/providers/json-rpc-provider.ts
- sdk/typescript/src/types/checkpoints.ts
- sdk/typescript/src/types/coin.ts
- sdk/typescript/src/types/dynamic_fields.ts
- sdk/typescript/src/types/epochs.ts
- sdk/typescript/src/types/events.ts
- sdk/typescript/src/types/objects.ts
- sdk/typescript/src/types/transactions.ts
Fix pagination types with the SDK.
Tests should pass.
> [ts-sdk] Fix pagination types

- crates/sui-cluster-test/src/faucet.rs
- crates/sui-faucet/src/faucet/mod.rs
- crates/sui-faucet/src/faucet/simple_faucet.rs
- crates/sui-faucet/src/main.rs
- crates/sui/src/client_commands.rs
Adding Pagination to get_gas_objects
CI
---
> Adding Pagination to get_gas_objects

- crates/sui-core/src/state_accumulator.rs
Mitigating issue with removing wrapped tombstones by erroring rather than asserting. Will have to root cause and fix later.
---
> [StateAccumulator] Mitigate inc_238 in devnet

- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/lib.rs
1. some tx -> tx block rename leftovers
2. _with_options renaming leftovers
3. add `query_events` to implemented method
> indexer: tx -> tx block leftovers

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
fix failure when processing safe mode epoch because of missing epoch events
Tested locally
> [indexer] - fix failure when processing safe mode epoch

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
> [indexer ] - fix failure when processing safe mode epoch - cherry pick #10186

- crates/sui-core/src/authority.rs
- crates/sui-core/src/transaction_input_checker.rs
- I see no reason to support them, and might lead to some weirdness
- No tests
---
> Ban system transactions from dry run

- crates/sui-adapter/src/execution_engine.rs
- crates/sui-framework/docs/sui_system.md
- crates/sui-framework/docs/sui_system_state_inner.md
- crates/sui-framework/packages/sui-system/sources/sui_system.move
- crates/sui-framework/packages/sui-system/sources/sui_system_state_inner.move
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_1.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_2.snap
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_3.snap
- crates/sui/tests/framework_upgrades/mock_sui_systems/base/sources/sui_system.move
- crates/sui/tests/framework_upgrades/mock_sui_systems/base/sources/sui_system_state_inner.move
- crates/sui/tests/framework_upgrades/mock_sui_systems/safe_mode/sources/sui_system.move
- crates/sui/tests/framework_upgrades/mock_sui_systems/safe_mode/sources/sui_system_state_inner.move
- crates/sui/tests/framework_upgrades/mock_sui_systems/shallow_upgrade/sources/sui_system.move
- crates/sui/tests/framework_upgrades/mock_sui_systems/shallow_upgrade/sources/sui_system_state_inner.move
Cherry-pick safe mode timestamp fix to main branch.
> update epoch start time stamp in safe mode too (#10151)

- crates/sui-indexer/src/apis/indexer_api.rs
PR of https://github.com/MystenLabs/sui/commit/cc8d6e68108b7c28b1ae427d3d0ed763ca7f303e
> Cherry pick GetOwnedObjects gating 

- crates/sui-adapter-transactional-tests/tests/programmable/coin_negative.exp
- crates/sui-adapter-transactional-tests/tests/programmable/coin_negative.move
- crates/sui-adapter-transactional-tests/tests/programmable/gas_coin_by_reference.move
- crates/sui-adapter-transactional-tests/tests/programmable/gas_coin_by_value.exp
- crates/sui-adapter-transactional-tests/tests/programmable/gas_coin_by_value_invalid.move
- crates/sui-adapter-transactional-tests/tests/programmable/private_entry_value_restriction_by_ref_input_valid.move
- crates/sui-adapter-transactional-tests/tests/programmable/transfer_objects.exp
- crates/sui-adapter-transactional-tests/tests/programmable_transaction_examples/coin_limit.move
- crates/sui-adapter-transactional-tests/tests/size_limits/deleted_id_limits_tests.move
- crates/sui-adapter-transactional-tests/tests/size_limits/event_limits_tests.move
- crates/sui-adapter-transactional-tests/tests/size_limits/move_object_size_limit.move
- crates/sui-adapter-transactional-tests/tests/size_limits/new_id_limits_tests.exp
- crates/sui-adapter-transactional-tests/tests/size_limits/new_id_limits_tests.move
- crates/sui-adapter-transactional-tests/tests/size_limits/object_runtime_limits.move
- crates/sui-adapter-transactional-tests/tests/size_limits/transfered_id_limits_tests.move
- crates/sui-adapter-transactional-tests/tests/size_limits/vector_len_limits.move
- crates/sui-adapter-transactional-tests/tests/sui/coin_transfer.exp
- crates/sui-adapter-transactional-tests/tests/transfer_object/transfer_coin.exp
- crates/sui-transactional-test-runner/Cargo.toml
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/temporary_store.rs
Fixes broken tests in adapter transactional tests
---
> fixes for adapter transactional tests

- crates/sui-core/src/test_utils.rs
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui-core/src/unit_tests/batch_transaction_tests.rs
- crates/sui-core/src/unit_tests/move_integration_tests.rs
- crates/sui-open-rpc/src/examples.rs
- crates/sui-types/src/object.rs
- crates/sui-types/src/unit_tests/messages_tests.rs
- Fixed authority_tests
- Fixed move_integration tests
Tests, I fixed them. 
---
> Fixed authority_tests and move_integration_tests

- crates/sui/tests/reconfiguration_tests.rs
- crates/test-utils/src/transaction.rs
Fixes test in the sui-crate. Not ready to be merged just yet.
> Fix tests in sui crate

- crates/sui/src/unit_tests/cli_tests.rs
> [gas] Fixed CLI tests

- crates/sui-cost/tests/snapshots/empirical_transaction_cost__good_snapshot.snap
> empiritcal costs fixes in sui-cost crate

- crates/sui-faucet/src/faucet/simple_faucet.rs
Update budget for tests in Sui-faucet.
> Update budget in sui-faucet test

- apps/explorer/src/pages/validators/Validators.tsx
- apps/wallet/src/ui/app/components/receipt-card/StakeTxnCard.tsx
- apps/wallet/src/ui/app/staking/home/StakedCard.tsx
- apps/wallet/src/ui/app/staking/stake/ValidatorFormDetail.tsx
Show 0% APY and -- when APY is unavailable 
Fix StakeCard padding
---
> update APY to show 0%

- crates/sui-adapter-transactional-tests/tests/size_limits/new_id_limits_tests.exp
- crates/sui-json-rpc/src/unit_tests/rpc_server_tests.rs
- crates/sui-open-rpc/Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
Fixes json rpc tests, updates open rpc spec, and updates an exp-file in the transactional tests.
> Fix json-rpc tests

- apps/explorer/src/hooks/useSearch.ts
Minimize the data fetching for checkpoints by checking if the digest is valid first. This also reorganizes conditions so that we prefer early return instead.
---
> [explorer] minimize checkpoint fetching

- crates/sui-framework/docs/validator_set.md
- crates/sui-framework/packages/sui-system/sources/validator_set.move
We should include the voting power of validators in emitted events too.
---
> [sui-system] add voting power to epoch info event

- crates/sui-benchmark/src/bank.rs
- crates/sui-benchmark/src/util.rs
- crates/sui-cluster-test/src/test_case/coin_merge_split_test.rs
- crates/sui-cluster-test/src/test_case/fullnode_build_publish_transaction_test.rs
- crates/sui-cluster-test/src/test_case/native_transfer_test.rs
- crates/sui-indexer/tests/integration_tests.rs
> Fix benchmark simtests

- .github/workflows/simulator-nightly.yml
Decrease number of threads to 12
👀
> Decrease number of threads to 12

- crates/sui/src/validator_commands.rs
> use higher gas budget for valdiator tool

- crates/sui-core/src/lib.rs
- crates/sui-core/src/unit_tests/data/type_params/Move.toml
- crates/sui-core/src/unit_tests/data/type_params/sources/m1.move
- crates/sui-core/src/unit_tests/data/type_params/sources/m2.move
- crates/sui-core/src/unit_tests/data/type_params/sources/m3.move
- crates/sui-core/src/unit_tests/data/type_params_extra/Move.toml
- crates/sui-core/src/unit_tests/data/type_params_extra/sources/m1.move
- crates/sui-core/src/unit_tests/type_param_tests.rs
Added tests for type parameters.
> [package-upgrades] Type param testing

- crates/sui-cluster-test/src/lib.rs
- crates/sui-cluster-test/src/test_case/fullnode_build_publish_transaction_test.rs
- crates/sui-cluster-test/src/test_case/fullnode_execute_transaction_test.rs
- crates/test-utils/src/messages.rs
Fixes some gas budget calculations in cluster test
> [cluster-test] Fix cluster test gas budget calculations

- crates/sui/src/client_commands.rs
Added an error check on the object responses returned.
CI / Locally
---
> [Cli fix] Adding error check on cli

- crates/mysten-metrics/src/lib.rs
This allows to narrow down which scope is stuck by looking at the metrics
> Measure number of entrances in monitored scope

- narwhal/network/src/connectivity.rs
Accidentally used active peers instead of known peers to collect connection stats which is empty when ConnectionMonitor first spawns
[Labnet](https://metrics.sui.io/d/k1e0Y8BVz/anemo-metrics?orgId=1&var-Environment=mysten-metrics-internal&var-network=labnet&var-validator=All&from=1680400403542&to=1680402424452) & added unit test
> Fix known peer list in ConnectionMonitor

- crates/sui-rpc-loadgen/src/load_test.rs
- crates/sui-rpc-loadgen/src/payload/checkpoint_utils.rs
- crates/sui-rpc-loadgen/src/payload/get_checkpoints.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/pay_sui.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
- crates/sui-rpc-loadgen/src/payload/validation.rs
> [rpc-loadgen][10/n] Log checkpoint stats at repeat boundary

- crates/sui-keys/src/key_derive.rs
- crates/sui-keys/src/keystore.rs
- crates/sui/src/unit_tests/keytool_tests.rs
Clean up sui-keys
All tests pass
> Clean up sui-keys

- doc/src/build/index.md
- doc/src/build/programming-with-objects/index.md
- doc/src/learn/objects.md
- doc/src/learn/transactions.md
> Adding link to transaction limits

- .changeset/shiny-paws-wave.md
- sdk/typescript/src/types/objects.ts
> ts sdk: backward compatible getOwnedObject

- Cargo.lock
- crates/sui-rpc-loadgen/Cargo.toml
- crates/sui-rpc-loadgen/README.md
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/get_checkpoints.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/query_transactions.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
> support loading from cache on file for query_transactions

- crates/sui-core/src/authority_aggregator.rs
Record RPC errors from validators.
---
> record rpc errors

- crates/sui-config/src/node.rs
- crates/sui-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
Make pruner run after current epoch changes
Existing tests
> Make pruner run after current epoch

- crates/sui-rpc-loadgen/README.md
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/get_all_balances.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
> get all balances

- crates/sui-rpc-loadgen/README.md
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/get_checkpoints.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
- crates/sui-rpc-loadgen/src/payload/validation.rs
> [rpc-loadgen][11/n] increase default gas budget

- sdk/typescript/test/e2e/txn-serializer.test.ts
> Disable flaky test

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/main.rs
- added a couple of flags for benchmark puspose
- also added err messages before `backoff` retrials start
CI
> indexer: configs for benchmarks

- crates/sui-adapter/src/execution_engine.rs
> Fix gas v1 panic

- crates/sui-proxy/src/histogram_relay.rs
Summary:
* cleanup the variables we use to record prom data, removing type from the name and fixing the description a bit.
Test Plan:
local
---
> [sui-proxy/ remove type from name]

- crates/sui-proxy/src/histogram_relay.rs
Summary:
* the submit counter included all metric types. originally i wanted it this way but it's easier to grok if it's a filtered count that we actually submit vs a count of all metrics we get before we filter the histograms.
Test Plan:
local
---
> [sui-proxy/adjust submit counter]

- crates/sui-tool/src/db_tool/db_dump.rs
> [trivial] Make table print properly

- apps/explorer/src/components/HomeMetrics/index.tsx
https://mysten.atlassian.net/browse/APPS-729
---
> [explorer]: update addresses tooltip

- crates/sui-adapter/src/programmable_transactions/execution.rs
Fixing publish transaction backwards compatibility (introduced at the time of upgrades).  The backwards compatible implementation changed the order of operations (execute `init` functions before fetching packages), which resulted in a change in the amount of gas charged, because we were executing instructions on one path and not on the other.
```
```
And run a fullnode on devnet and ensure it catches up past checkpoint 32314 (the checkpoint that was previously failing).
---
> [publish] Preserve execution order for publish in backward compat

- apps/core/src/hooks/useGetRollingAverageApys.ts
The current APY calc is missing a scalar of 100. Multiply the final APY calc by 100 
---
> Multiply APY result by 100

- crates/sui-rpc-loadgen/README.md
- crates/sui-rpc-loadgen/src/main.rs
- crates/sui-rpc-loadgen/src/payload/get_all_balances.rs
- crates/sui-rpc-loadgen/src/payload/get_object.rs
- crates/sui-rpc-loadgen/src/payload/mod.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
> add get_object

- sdk/typescript/src/rpc/connection.ts
Add default testnet connection to the SDK.
Simple change.
> [ts-sdk] Add testnet connection

- vercel.json
This adds a root vercel config to disable builds on ghpages. Apparently this is how you're supposed to do it.
Will merge and see what happens.
> Try disabling deployments using root vercel.json

- apps/explorer/src/components/HomeMetrics/index.tsx
- https://mysten.atlassian.net/browse/APPS-725
- Update text and tooltip for main page metric
---
> [explorer]: update metric

- crates/sui-indexer/src/errors.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/metrics.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/tests/integration_tests.rs
Pipeline Indexer by adding 2 pairs of Sender & Receiver
- checkpoint sender & receiver
- epoch sender & receiver
- local run indexer
- CI
> indexer: pipeline download, checkpoint commit and epoch commit

- crates/shared-crypto/src/intent.rs
- crates/sui-types/src/crypto.rs
- crates/sui-types/src/unit_tests/intent_tests.rs
- doc/src/learn/cryptography/sui-intent-signing.md
Doc and test updates. 
N/A
---
> chore: Improve doc and tests on PoP

- crates/sui-types/src/temporary_store.rs
This reverts commit 609caf3e07f06c9cbc82b234db9fedd7b1eea19c.
👀
> Revert "[hardening] enable simpler conservation checks"

- external-crates/move/move-prover/interpreter/crypto/src/lib.rs
Seeing warnings on latest `main`.
n/a
---
> Remove unused import

- crates/typed-store/src/rocks/mod.rs
Without invoke `try_catchup_to_primary` secondary instances do not have access to unflushed memtable data primary instance is holding. This makes secondary catchup through logs
Existing tests
> Make secondaries catch up to primary db instance

- .github/actions/diffs/action.yml
Otherwise we may miss issues with changes under the directory.
CI
---
> Trigger rust CI with changes under external-crates/

- crates/sui-core/src/authority/authority_per_epoch_store.rs
Since we released 0.30 we can now remove the old table
> [checkpoints] Remove builder_checkpoint_summary table

- Cargo.lock
- crates/sui-benchmark/tests/simtest.rs
- crates/workspace-hack/Cargo.toml
- narwhal/benchmark/README.md
- narwhal/network/Cargo.toml
- narwhal/network/src/failpoints.rs
- narwhal/network/src/p2p.rs
- narwhal/node/Cargo.toml
- narwhal/node/src/main.rs
- narwhal/primary/Cargo.toml
- narwhal/primary/src/certifier.rs
- narwhal/primary/src/primary.rs
- narwhal/storage/Cargo.toml
- narwhal/storage/src/certificate_store.rs
- narwhal/storage/src/header_store.rs
- narwhal/storage/src/payload_store.rs
- narwhal/storage/src/proposer_store.rs
- narwhal/storage/src/vote_digest_store.rs
- Adds failpoints for all storage operations and inbound RPCs.
- Adds delays in Certifier.
Is tests.
> Migrate Narwhal failpoints to simtest, add more

- doc/src/learn/tokenomics/gas-in-sui.md
> updates to gas docs

- sdk/ledgerjs-hw-app-sui/README.md
Fix references to `legerjs-hw-app-sui` in README
None Required
---
> [doc] fix reference to ledgerjs-hw-app-sui in README

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
Bumping sui version in main to `v0.31.0`
👀
> Bumping sui version in main to v0.31.0

- .github/workflows/bench.yml
- Cargo.lock
- Cargo.toml
- crates/sui-network/src/discovery/mod.rs
- crates/sui-network/src/state_sync/mod.rs
- crates/workspace-hack/Cargo.toml
- narwhal/primary/src/certificate_fetcher.rs
- narwhal/primary/src/certifier.rs
Bump anemo to a version to avoid crashing on ungraceful shutdown. Fix more usages of Joinset to avoid crashing on ungraceful shutdown. Increase target TPS in local benchmarks.
https://github.com/MystenLabs/sui/commit/a55e2846ec26c17278f7b166957c85e4931bba3e#comments
---
> [Benchmark] fix crash; increase TPS

- crates/sui-core/src/authority.rs
- crates/sui/tests/protocol_version_tests.rs
This PR generalizes the sui system injection utility to framework injection that supports any framework package.
> Generalize framework injection

- crates/sui-core/src/unit_tests/authority_tests.rs
As title. Also add comment for `fn make_test_transaction`
---
> remove test_handle_certificate_with_shared_object_interrupted_retry

- crates/sui-json-rpc/src/coin_api.rs
- crates/typed-store/src/rocks/mod.rs
> [perf improvement] - use multi get in get balance and get all balances

- crates/sui/src/client_commands.rs
Easy change to make it easier to debug without using `curl`
`sui client tx-block GfGJmJSnx4NgFDaKkyiAcgkAAA86G1pXXxbz8kF6uQfm` (with client pointed at devnet)
---
> [cli][easy] add command to fetch transaction blocks

- apps/explorer/src/components/Layout/LayoutContent.tsx
- apps/explorer/src/index.tsx
- apps/explorer/src/utils/growthbook.ts
- apps/wallet/src/ui/app/components/alert/index.tsx
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
This adds warnings for when the network is known to be having issues.
Manually.
> Add network degrade warnings

- crates/sui-proxy/src/consumer.rs
- crates/sui-proxy/src/handlers.rs
- crates/sui-proxy/src/peers.rs
Summary:
* adjust the buckets used for histograms
Test Plan:
cargo build
---
> [sui-proxy/adjust http histogram buckets]

- crates/typed-store/src/rocks/util.rs
fixes the bug in the full merge operator that reproduces when the original insert is squashed into an empty value between the first and second rounds of compaction
* added unit test
* deployed fix on one of the full nodes, verified that it makes progress now
> fix merge operator for indirect objects

- crates/sui-indexer/migrations/2023-01-16-233119_checkpoint/up.sql
- crates/sui-indexer/migrations/2023-04-07-170935_add_validator_signature_to_checkpoint/down.sql
- crates/sui-indexer/migrations/2023-04-07-170935_add_validator_signature_to_checkpoint/up.sql
- crates/sui-indexer/src/models/checkpoints.rs
- crates/sui-indexer/src/schema.rs
We now have perm testnet, cannot reset DB and start from genesis anymore.
Local run `diesel migration run` to make sure that the schema can be updated.
> indexer: fix indexer checkpoint schema

- crates/sui-config/src/node.rs
- crates/sui-swarm/src/memory/container.rs
- crates/sui/src/fire_drill.rs
- crates/sui/src/sui_commands.rs
- crates/sui/tests/reconfiguration_tests.rs
As title. This is not needed when running a node.
unit tests and tested locally.
---
Remove account key from node config.
> remove account key from node config

- apps/explorer/src/components/Layout/LayoutContent.tsx
This adds the React Router ScrollRestoration which will have better default scrolling behavior in the app.
Locally.
> [explorer] Add scroll restoration

- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/authority/authority_store_tables.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-types/src/in_memory_storage.rs
- crates/sui-types/src/storage.rs
- crates/sui-types/src/temporary_store.rs
- crates/typed-store/src/rocks/mod.rs
- perf.svg
> [cherry-pick] Fix object lookup in gas computation

- apps/core/src/hooks/useGetTransferAmount.ts
- apps/core/src/index.ts
- apps/explorer/src/pages/transaction-result/TransactionView.tsx
- apps/explorer/src/pages/transaction-result/TxLinks.tsx
- apps/explorer/src/ui/TransactionAddressSection.tsx
Add amount back to TransactionView
---
> [explorer] - restore transaction amount

- apps/core/src/hooks/useGetTransferAmount.ts
Fix error on transaction balance without coinType
Before 
https://explorer.sui.io/txblock/BAHqQ7fW9SYEeGEH4AYeo45X4PfGrXfpvpJfdvb8UkiV?network=testnet
After
https://explorer-git-gj-explorer-error-mysten-labs.vercel.app/txblock/BAHqQ7fW9SYEeGEH4AYeo45X4PfGrXfpvpJfdvb8UkiV?network=testnet
> Fix error on transaction balance without coinType

- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
Mitigation for `inc_264`.
This is needed to ensure that we enqueue the tx with write lock last to txn manager, or last in the vec among all txns touching the object.
Existing tests
---
> [CheckpointExecutor] Serialize tx manager enqueue

- crates/sui-core/src/authority/authority_store.rs
- crates/sui-core/src/transaction_manager.rs
For a given shared object ref, current logic does not support executing transactions holding read-only locks, concurrently with executing a transaction that consumes the object ref. This PR adds tracking of transactions holding readonly locks until they finish executions in transaction manager, so another transaction acquiring a default lock on the same object can only succeed after all readonly locks have been released.
TODO
---
> [TransactionManager] do not allow locking object in readonly and default modes concurrently

- crates/sui-faucet/src/faucet/simple_faucet.rs
The clone was to get around the fact that we needed to increment a count in the log while iterating over it, but `DBMap`s contain metrics etc, so it's probably not a good idea to clone them.  Get around this by going over the pending coins in a separate pass to increment the retry count.
```
crates/sui-faucet$ cargo nextest run
```
> [faucet] Avoid cloning WAL DBMap when retrying

- crates/sui-indexer/src/store/pg_indexer_store.rs
To unblock explorer and will investigate the epoch advance logic later.
> indexer: temp turn off partition

- apps/explorer/src/components/HomeMetrics/index.tsx
- apps/explorer/src/components/transactions/index.tsx
- apps/explorer/src/pages/checkpoints/CheckpointsTable.tsx
- apps/explorer/src/pages/epochs/EpochsTable.tsx
disable polling to help API recover
> explorer: disable polling

- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
> Cherry pick indexer worker start fix + epoch advance fix

- apps/explorer/src/components/Activity/index.tsx
> [explorer] - disable play/pause button

- apps/explorer/src/utils/queryClient.ts
* to help API to recover reduce requests
> explorer: disable retrying requests

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v0.32.0 version bump

- crates/sui-cluster-test/src/lib.rs
- crates/sui-cluster-test/src/test_case/coin_merge_split_test.rs
- crates/sui-cluster-test/src/test_case/fullnode_execute_transaction_test.rs
- crates/sui-cluster-test/src/test_case/native_transfer_test.rs
- crates/test-utils/src/transaction.rs
ran cluster tests locally against CI/Staging
> Fix for cluster tests

- crates/sui-indexer/src/utils.rs
- crates/sui-json-rpc/src/balance_changes.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-json-rpc/src/transaction_execution_api.rs
This hardens the `balanceChanges` derivation from tx effects by crashing unless the digest of coin objects in the effects matches the digest of coin objects we fetched from the local store. This way, the RPC provider and validators must be on the same page re: the value of coins.
---
> [hardening] check object digests in get_balance_changes

- .cargo/config
- .github/workflows/rust.yml
- crates/x/src/external_crates_tests.rs
- crates/x/src/main.rs
- external-crates/tests.sh
Adds a CI step for test of Move crates in our new external crates.
CI tests
---
> easy: ci & local tests for Move external crates

- README.md
<p align="center">
Sui is a next-generation smart contract platform with high throughput, low latency, and an asset-oriented programming model powered by the [Move programming language](https://github.com/MystenLabs/awesome-move).
Sui offers the following benefits and capabilities:
* Unmatched scalability, instant settlement
* A safe smart contract language accessible to mainstream developers
* Ability to define rich and composable on-chain assets
* Better user experience for web3 apps
Sui is the only blockchain today that can scale with the growth of web3 while achieving industry-leading performance, cost, programmability, and usability. As we push towards mainnet launch, we will demonstrate capacity beyond the transaction processing capabilities of established systems – traditional and …
> More details about sui

- doc/src/explore/tutorials.md
> fix doc error

- crates/sui-indexer/benches/indexer_benchmark.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/metrics.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/tests/integration_tests.rs
Cherry-pick all changes from https://github.com/MystenLabs/sui/pull/10610
- Local run against main validator
- indexer integration tests broken b/c the parallelism changed many assumptions we prev. had
> Indexer: various optimizations over the weekend

- crates/sui-types/src/base_types.rs
- crates/sui-types/src/crypto.rs
- crates/sui-types/src/error.rs
- crates/sui-types/src/multisig.rs
> chore: differentiate crypto errors

- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/safe_client.rs
> more debug logs

- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-json-rpc/src/api/indexer.rs
- crates/sui-json-rpc/src/indexer_api.rs
> [rpc] mark get_dynamic_field_object as blocking

- apps/explorer/package.json
- apps/explorer/src/components/module/PkgModulesWrapper.tsx
- apps/explorer/src/hooks/useBreakpoint.ts
- apps/explorer/src/hooks/useMediaQuery.ts
- apps/explorer/src/ui/SplitPanes.tsx
- apps/explorer/src/ui/stories/SplitPanes.stories.tsx
- pnpm-lock.yaml
- Add draggable panels
- https://mysten.atlassian.net/browse/APPS-736
---
> [explorer]: add draggable panels

- RELEASES.md
Update RELEASES.md with v0.31.0 release
👀
> Update RELEASES.md with v0.31.0 release

- crates/sui-indexer/src/apis/write_api.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
> Cherry several indexer changes to 0.31

- .changeset/rich-ties-shop.md
> [ts-sdk] add missing changeset

- apps/wallet/src/ui/app/components/menu/content/VerifyLedgerConnectionStatus.tsx
> [wallet-ext] set correct font-weight for "Verify Ledger Connection" link

- apps/explorer/src/components/HomeMetrics/index.tsx
This updates the home stats formatting to use better number formatting.
Ran locally.
> [explorer] Improve formatting of home stats

- apps/explorer/src/components/node-map/index.tsx
Fixes bug where selecting network would trigger tooltip but the data wasn't available.
> [explorer] Fix tooltip bug

- crates/sui-core/src/generate_format.rs
- crates/sui-core/tests/staged/sui.yaml
Add multisig example to sui.yaml
test_format passes
---
> crypto: Add multisig to gen format

- crates/sui-types/src/crypto.rs
> Debug aggregate

- crates/sui-framework/packages/sui-framework/sources/clock.move
Cherry picks #10750 to testnet since this is the branch everyone is using.
---
> [framework] Cherry pick to testnet

- apps/explorer/src/pages/checkpoints/CheckpointDetail.tsx
> [explorer] - add validator signature to checkpoint detail

- crates/sui-faucet/src/faucet/mod.rs
- crates/sui-faucet/src/faucet/simple_faucet.rs
- crates/sui-faucet/src/faucet/write_ahead_log.rs
- crates/sui-faucet/src/main.rs
> [Cherry-pick] Faucet PRs to add worker thread and update metrics

- crates/sui-core/src/authority/authority_store.rs
- crates/sui-node/src/lib.rs
This PR adds some extra logging and metrics for sui conservation checks.
> Add more sui conservation logging

- sdk/wallet-adapter/wallet-standard/README.md
update wallet-standard README.md
> update: wallet-standard README.md

- crates/sui-core/src/unit_tests/data/move_upgrade/dep_on_upgrading_package_transitive/Move.toml
- crates/sui-core/src/unit_tests/data/move_upgrade/dep_on_upgrading_package_transitive/sources/my_module.move
- crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs
Added more tests for package upgrades related to package versioning in presence of transitive dependencies.
These are the actual tests
> [package-upgrades] Added transitive dependency tests

- apps/explorer/src/components/transactions/TxCardUtils.tsx
- apps/explorer/src/pages/epochs/EpochDetail.tsx
Fixes the styling caused by using old components, and mark those as deprecated.
Ran locally.
> Fix styling of sui on epochs page

- Cargo.lock
- crates/sui-indexer/Cargo.toml
- crates/sui-indexer/benches/indexer_benchmark.rs
- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-indexer/src/apis/read_api.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/lib.rs
- crates/sui-indexer/src/main.rs
- crates/sui-indexer/src/metrics.rs
- crates/sui-indexer/src/store/indexer_store.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/test_utils.rs
We want to group (FN, method) regardless of indexer read workers, this PR should give us that
- subsystem will be the label of fn_url.
Test locally and make sure metrics can be bumped
> indexer: add FN RPC trackers to read workers

- .github/actions/ts-e2e/action.yml
- .github/workflows/e2e.yml
- sdk/typescript/src/providers/json-rpc-provider.ts
re-enable backward compatibility test
CI should pass
---
> [ts-sdk][ci] re-enable backward compatibility test

- crates/sui-core/src/authority.rs
> fix object index

- crates/typed-store/src/metrics.rs
- crates/typed-store/src/rocks/mod.rs
These metrics are heavy cpu user, and not very much used for anything.
Existing tests
> Remove expensive mem usage stats

- sdk/ledgerjs-hw-app-sui/README.md
update ledgerj-hw-app README.md
> update ledgerj-hw-app README.md

- crates/sui-json-rpc/src/coin_api.rs
Removing the coin check for Sui type.
Local / CI
---
> [rust sdk] Removing coin check

- crates/sui-json-rpc/src/coin_api.rs
Removing the coin check for Sui type.
src="https://user-images.githubusercontent.com/123408603/231529651-e22dad40-7774-4a7d-9e9f-c7a975b4df6c.png"> Local / CI
---
---
> [Cherry-pick] coinmeta data check removal

- crates/sui-core/src/unit_tests/data/move_upgrade/makes_another_object/Move.toml
- crates/sui-core/src/unit_tests/data/move_upgrade/makes_another_object/sources/base.move
- crates/sui-core/src/unit_tests/data/move_upgrade/makes_another_object/sources/friend_module.move
- crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs
More package upgrade tests.
These are the actual tests
> [package-upgrades] Added more tests for different module, object type, and event type versions

- crates/sui-benchmark/tests/simtest.rs
- crates/sui/tests/full_node_tests.rs
- crates/sui/tests/reconfiguration_tests.rs
Currently running many iterations locally to make sure none of these are flaky.
> Un-ignore tests

- crates/sui-framework/packages/sui-system/tests/rewards_distribution_tests.move
> [sui-system] add unit test testing when everyone's rewards are slashed

- apps/core/src/hooks/__tests__/useFormatCoin.test.ts
- apps/core/src/hooks/useTimeAgo.ts
- apps/core/src/utils/formatAmount.ts
- apps/explorer/src/pages/checkpoints/CheckpointDetail.tsx
- apps/explorer/src/pages/epochs/EpochDetail.tsx
- apps/explorer/src/pages/epochs/stats/EpochProgress.tsx
- apps/explorer/src/pages/epochs/stats/EpochStats.tsx
This updates the epoch page stats to align with the current design.
Ran locally + verified preview.
> Epoch page stats rework

- crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql
- crates/sui-indexer/src/store/pg_indexer_store.rs
fix indexer move call metric bug causing `suix_getMoveCallMetrics` to return wrong results
tested locally, result:
```
{
"result": {
"rank3Days": [
[
{
"package": "0x0000000000000000000000000000000000000000000000000000000000000003",
"module": "sui_system",
"function": "request_add_stake"
},
"36909"
],
[
{
"package": "0xe158e6df182971bb6c85eb9de9fbfb460b68163d19afc45873c8672b5cc521b2",
"module": "TOKEN",
"function": "mint_test_token"
},
"27221"
],
[
{
"package": "0xe158e6df182971bb6c85eb9de9fbfb460b68163d19afc45873c8672b5cc521b2",
"module": "TOKEN",
"function": "mint_test_token_usdt"
},
"25170"
],
[
{
"package": "0xe158e6df182971bb6c85eb9de9fbfb460b68163d19afc45873c8672b5cc521b2",
"module": "TOKEN",
"function": "mint_test_token_btc"
},
"23006"
],
[
{
"package": …
```
> [indexer] - fix indexer move call metric bug

- crates/sui-indexer/migrations/2023-03-20-041133_epoch/up.sql
- crates/sui-indexer/src/errors.rs
- crates/sui-indexer/src/handlers/checkpoint_handler.rs
- crates/sui-indexer/src/metrics.rs
- crates/sui-indexer/src/store/pg_indexer_store.rs
- crates/sui-indexer/src/utils.rs
> Cherry pick indexer 0412

- Cargo.lock
- crates/sui-core/src/unit_tests/authority_tests.rs
- crates/sui/Cargo.toml
- crates/sui/tests/dynamic_committee_tests.rs
First step towards dynamic committee stress tests
> [dynamic-committee-stress] Start dynamic committee stress test

- crates/sui-json/src/lib.rs
try to (de)serialize, and if fails, try to return some semblance of `input` by falling back to `JsonValue::Array`. 
Verify that making the call below yields response with `transaction` when `showInput` is true:
```
curl --location --request POST 'http://ewr-tnt-rpc-12.testnet.sui.io:9000' \
--data-raw '{
"id": 1,
"method": "sui_getTransactionBlock", "params": ["JBBRdsd4UnrQ8haRYS2RoCkEJFFoUduSATZ78oBSdkhC",     {
"showInput": true,
"showRawInput": false,
"showEffects": true,
"showEvents": false,
"showObjectChanges": false,
"showBalanceChanges": false
}]
}'
```
Result:
`{"jsonrpc":"2.0","result":{"digest":"JBBRdsd4UnrQ8haRYS2RoCkEJFFoUduSATZ78oBSdkhC","transaction":{"data":{"messageVersion":"v1","transaction":{"kind":"Programmabl …
> Always try to serialize, fall back to JsonValue::Array

- crates/sui-json-rpc-types/src/sui_move.rs
- crates/sui-json-rpc-types/src/sui_object.rs
- crates/sui-json-rpc-types/src/unit_tests/rpc_types_tests.rs
- crates/sui-open-rpc/spec/openrpc.json
fix https://github.com/MystenLabs/sui/issues/10802
> [bugfix] - move number value do not need to serialize to string

- crates/sui-core/src/unit_tests/move_package_upgrade_tests.rs
Another package upgrade test plus a refinement to the previous one promised on the earlier PR (https://github.com/MystenLabs/sui/pull/10788#discussion_r1164604573)
These are the actual tests
> [package-upgrades] Added cross-version conflicting dependency call test

- crates/sui-adapter-transactional-tests/tests/publish/multi_module_publish.exp
- crates/sui-adapter-transactional-tests/tests/publish/multi_module_publish.move
- crates/sui-transactional-test-runner/src/test_adapter.rs
See title
Only updates test utilities
> move: support multiple module publish for transactional tests

- apps/wallet/src/ui/app/hooks/useQueryTransactionsByAddress.ts
- apps/wallet/src/ui/app/pages/home/tokens/CoinActivityCard.tsx
- apps/wallet/src/ui/app/staking/stake/StakingCard.tsx
- apps/wallet/src/ui/app/staking/stake/UnstakeForm.tsx
- sdk/typescript/src/types/validator.ts
This reduces one `multiGetTransactionBlocks` call by just fetching the data in `queryTransactionBlocks`. Also fixes a small type bug, and removes the recent transactions fetch from the coin details page as the data is currently unused.
> [wallet-ext] Fix incorrect SDK types and optimize requests

- crates/sui-core/src/safe_client.rs
Many node operators only enable INFO and above.
---
> bump the log level to error

- crates/sui-indexer/src/apis/indexer_api.rs
> [indexer] Fix the event api check

- crates/sui-json-rpc/src/api/mod.rs
- crates/sui-json-rpc/src/coin_api.rs
- crates/sui-json-rpc/src/governance_api.rs
- crates/sui-json-rpc/src/indexer_api.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-node/src/lib.rs
Add metrics to json rpc apis that asks for multi-things 
---
> add json rpc metrics

- apps/explorer/src/ui/ImageIcon.tsx
- apps/wallet/src/ui/app/shared/image-icon/index.tsx
- Remove gradient background, unless it is for the fallback plain text
- https://mysten.atlassian.net/browse/APPS-779
---
> [explorer]: remove blue background for logos

- crates/sui-core/src/streamer.rs
Subscribers use an async RWLock. However, part of the subscriber interface is sync, which forces `Streamer::subscribe` to use `block_on` inside tokio task, which causes executor starvation.
From the usage pattern it seem to be not needed, so just replacing it with blocking lock.
> [subscribers] Use blocking RWLock

- narwhal/network/src/connectivity.rs
- narwhal/network/src/metrics.rs
Will add additional detail to anemo DisconnectReason separately.
Manual inspection of added metric
> Add anemo disconnects metric with reason info.

- apps/explorer/src/components/owned-objects/views/ObjectFieldsCard.tsx
Fix Object page fields overflow issue
Before
https://explorer.sui.io/object/0x1e02a55b22f57c3a9c28aa94a184dff40853ab9c3103342fd3f75025b2a8e18f
After
---
> fix object field scroll overflow

- apps/explorer/src/ui/Badge.tsx
- https://mysten.atlassian.net/browse/APPS-697
---
> [explorer]: update badge border

- Cargo.lock
- crates/sui-adapter/src/execution_engine.rs
- crates/sui-benchmark/Cargo.toml
- crates/sui-benchmark/tests/data/deepbook_client/Move.toml
- crates/sui-benchmark/tests/data/deepbook_client/sources/deepbook_client.move
- crates/sui-benchmark/tests/simtest.rs
- crates/sui-framework-build/src/compiled_package.rs
- crates/sui-framework/build.rs
- crates/sui-framework/docs/clob.md
- crates/sui-framework/docs/critbit.md
- crates/sui-framework/docs/custodian.md
- crates/sui-framework/packages/deepbook/Move.toml
- crates/sui-framework/packages/deepbook/README.md
- crates/sui-framework/packages/deepbook/sources/clob.move
- crates/sui-framework/packages/deepbook/sources/critbit.move
- crates/sui-framework/packages/deepbook/sources/custodian.move
- crates/sui-framework/packages/deepbook/sources/math.move
- crates/sui-framework/packages/deepbook/sources/sui.move
- crates/sui-framework/packages/deepbook/sources/usd.move
- crates/sui-framework/src/lib.rs
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/lib.rs
Create a new package for deepbook in the Sui Framework, with special address `0xdee9`. Copy in the MoveX-authored deepbook code from https://github.com/MystenLabs/sui/pull/10896.
New tests for Sui Framework upgrades that add packages, existing deepbook tests.
---
> [sui framework] new framework package for deepbook

- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/safe_client.rs
- crates/sui-types/src/crypto.rs
This combines the changes of the following commits and PR's into and merges them into main:
- https://github.com/MystenLabs/sui/commit/a51401887edf62381e2ab322888dab1493894343
- https://github.com/MystenLabs/sui/commit/5acb4f5c3c561e117c6cebcfeaea6264279c31f5
- https://github.com/MystenLabs/sui/commit/b8bc634d312b49979b801f9d452914c333f90b95
- https://github.com/MystenLabs/sui/pull/10895
- https://github.com/MystenLabs/sui/pull/10900
> Add debug logging

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v0.33.0 version bump

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Inputs.tsx
Fix text overflow issue on mobile 
---
> Fix text overflow on mobile

- apps/explorer/src/pages/object-result/views/TokenView.tsx
Show Storage rebase in the object page
> Show storage rebate in object page

- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-tool/src/db_tool/db_dump.rs
- crates/sui-tool/src/db_tool/mod.rs
PR adds compaction command to the sui tool
> sui tool: compaction

- crates/sui-core/src/authority/authority_store_tables.rs
Added 2 more tables recently, reset them too
> [db-tool] Clear more tables during reset

- .github/workflows/compatibility_checker.yml
- .github/workflows/compatibility_sharded.yml
- scripts/compatibility/fullnode-sync.sh
Also
* Fix sharding scheme to create overlap for full coverage
* Remove `clean` mode, which doesn't seem to work due to boolean weirdness in github actions
* Fix epoch time limit arg
* Put both workflows in the same concurrency group so that a new run of one blocks on completion of an ongoing run of any other
Will test after land as the scripts need to be updated in the repo to do a test run
---
> [CompatibilityChecker] Point sui paths to larger disk partition

- Cargo.lock
- crates/typed-store/Cargo.toml
- crates/typed-store/src/rocks/mod.rs
- crates/typed-store/src/rocks/tests.rs
- crates/typed-store/src/traits.rs
Add rocksdb snapshot and chunk multi get to limit memory usage as reported by FNs.
Add unit test
> Add snapshot and chunked multi get

- crates/sui-json/src/lib.rs
try to (de)serialize, and if fails, try to return some semblance of `input` by falling back to `JsonValue::Array`.
Verify that making the call below yields response with `transaction` when `showInput` is true:
```
curl --location --request POST 'http://ewr-tnt-rpc-12.testnet.sui.io:9000' \
--data-raw '{
"id": 1,
"method": "sui_getTransactionBlock", "params": ["JBBRdsd4UnrQ8haRYS2RoCkEJFFoUduSATZ78oBSdkhC",     {
"showInput": true,
"showRawInput": false,
"showEffects": true,
"showEvents": false,
"showObjectChanges": false,
"showBalanceChanges": false
}]
}'
```
Result:
`{"jsonrpc":"2.0","result":{"digest":"JBBRdsd4UnrQ8haRYS2RoCkEJFFoUduSATZ78oBSdkhC","transaction":{"data":{"messageVersion":"v1","transaction":{"kind":"Programmable …
> Always try to serialize, fall back to JsonValue::Array (#10823)

- crates/sui-core/src/authority/test_authority_builder.rs
This PR only affects tests.
The change is summarized in the comments
> Execute genesis tx after creating a test authority

- narwhal/primary/src/synchronizer.rs
Helper debug statements to diagnose synchronization latency
---
> [chore] add debug messages in synchronizer

- RELEASES.md
> Updating release notes link for v0.32.0

- narwhal/types/src/tests/metered_channel_tests.rs
This is needed as part of the effort of banning `executor::block_on` from our codebase
> [narwhal] Replace block_on with await in metered_channel_tests

- apps/wallet/src/ui/app/components/sui-apps/ConnectedAppsCard.tsx
- apps/wallet/src/ui/app/shared/page-main-layout/PageMainLayout.module.scss
- https://mysten.atlassian.net/browse/APPS-693
---
> [explorer]: update APPS panel (active connections)

- crates/sui-core/src/authority.rs
Transactions submitted via `handle_certificate()` are persisted into the `pending_consensus_transactions` table in consensus adapter, and this ensures the transactions will be propagated to other nodes. It is unnecessary to persist the transaction into the pending_execution table again inside the RPC handler.
Existing crash recovery tests.
---
> Avoid writing owned object transactions into pending_execution table from RPC handler

- Cargo.lock
- Cargo.toml
- crates/sui-core/src/test_utils.rs
- crates/sui-types/Cargo.toml
- crates/sui-types/src/base_types.rs
- crates/sui-types/src/object.rs
- crates/transaction-fuzzer/Cargo.toml
- crates/transaction-fuzzer/src/lib.rs
- crates/transaction-fuzzer/tests/gas_data_tests.rs
- crates/workspace-hack/Cargo.toml
> proptest transactions with randomly generated GasData

- sdk/typescript/src/rpc/faucet-client.ts
> [wallet-ext] fix typo in error message

- apps/explorer/src/pages/transaction-result/programmable-transaction-view/Transaction.tsx
[Before](https://explorer.sui.io/txblock/C4w5Zekb51ToBCTV9HPSWHyKFRLDNKTmMYuUPrsgBax5)
[After](https://explorer-git-gj-explorer-txn-mobile-overflow-mysten-labs.vercel.app/txblock/C4w5Zekb51ToBCTV9HPSWHyKFRLDNKTmMYuUPrsgBax5)
---
> Fix overflow issue on mobile transaction page 

- crates/sui-faucet/src/bin/merge_coins.rs
- crates/sui-faucet/src/main.rs
Adding a helper script for faucet.
Already used to smash some coins together.
---
> [faucet/script] Adding helper script to clean up coins

- apps/wallet/src/ui/app/components/sui-apps/index.tsx
- https://mysten.atlassian.net/browse/APPS-693
---
> [explorer]: update APPS (playground) on wallet

- crates/sui-json-rpc/src/read_api.rs
when options of `show_raw_input`, `show_input` & `show_effects` are `true`, but tx response could not get these accordingly, RPC should return error explicitly.
the related thread: https://mysten-labs.slack.com/archives/C04HS54LHUM/p1681334573378799
CI
> rpc: harden tx block response

- apps/explorer/src/components/displaybox/DisplayBox.module.css
Last fix only fixed in one context. This is the actual correct fix.
Ran locally again
> [explorer] Fix display box

- crates/sui-json-rpc/src/coin_api.rs
> remove wrong check

- crates/sui-core/src/generate_format.rs
- crates/sui-core/tests/staged/sui.yaml
- crates/sui-types/src/signature.rs
- crates/sui-types/src/sui_serde.rs
Add generic signature to format. 
test_format passes. 
---
> crypto: Add GenericSignature to generate format

- doc/src/build/programming-with-objects/ch5-dynamic-fields.md
The issues this is referring to were fixed some time ago.
> [doc] remove outdated section on dynamic fields limitations

- sdk/typescript/src/framework/framework.ts
Update to use `ValidatorEpochInfoEventV2` for querying validator events
---
> [explorer] - update validator event query

- apps/explorer/src/components/TransactionBlocksForAddress/TransactionBlocksForAddress.tsx
- apps/explorer/src/hooks/useGetTransactionBlocksForAddress.ts
A more comprehensive fix to the object page filtering issue.
Ran locally.
> [explorer] Fix object pages issues

- crates/mysten-network/src/codec.rs
IIUC, codegen will take care of applying Snappy to both client and server logic.
I did not bother to only apply compression above a size limit. Most Sui grpc request and response should be decently sized and compression CPU usage should not be significant.
Since changing codec can be incompatible with existing clients, will roll out the switch separately.
CI
---
> Add BcsSnappyCodec for compression in tonic grpc

- crates/sui-faucet/src/faucet/mod.rs
- crates/sui-json-rpc/src/coin_api.rs
> [Cherry-pick] Changes to faucet + removing coin_id check

- crates/sui-cluster-test/src/lib.rs
Faucet behavior changed to give out only 1 coin.
CI/CD
---
> fixing cluster test for faucet

- crates/sui-replay/src/lib.rs
- crates/sui-replay/src/replay.rs
Adds flag to show effects even for success case
Improves the errors reported when a pruning full node is used
Used as `--show-effects` 
Normal tests
---
> Improves error reporting and add effects show flag in success case 

- apps/wallet/src/ui/app/pages/home/transfer-coin/SendTokenForm.tsx
Fix the error we use `setFieldValue` in Formik leading to validation error see [issue](https://github.com/jaredpalmer/formik/issues/2059)
Before
https://user-images.githubusercontent.com/126525197/233100066-e41f0173-e544-4f66-b6eb-da156d84b2d2.mov
After
https://user-images.githubusercontent.com/126525197/233100092-1c0a772a-7442-48d6-b2d8-7db384a854a3.mov
---
> Wallet Fix send max Amount required validator bug

- SECURITY.md
Adding bug bounty program details from documentation provided by Casson.
N/A
> Add bug bounty program info to SECURITY.md

- crates/sui-core/src/authority.rs
- Add missing cfg gating
- cargo build
---
> Fix authority_test_utils

- crates/sui-cluster-test/src/test_case/coin_merge_split_test.rs
- crates/sui-cluster-test/src/test_case/fullnode_execute_transaction_test.rs
- crates/sui-cluster-test/src/test_case/native_transfer_test.rs
> changing all coin expectations from faucet to 1

- crates/sui-storage/src/indexes.rs
- crates/sui-types/src/dynamic_field.rs
- sdk/typescript/test/e2e/dynamic-fields.test.ts
- Fixed lookup for dynamic object fields
- Improved typescript tests
---
> [indexer] Fix dynamic object field lookup

- crates/sui-core/src/consensus_handler.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_6.snap
- crates/sui-types/src/crypto.rs
Cherry pick of #11103 and #11106
> Cherry pick of #11103 and #11106

- apps/explorer/src/components/owned-objects/views/DynamicFieldsCard.tsx
- apps/explorer/src/components/owned-objects/views/UnderlyingObjectCard.tsx
- Show Key for DynamicObject type 
- Remove the trim on ObjectType 
- For DynamicObject type, show the entire object
> Show all dynamic field value struct

- narwhal/consensus/src/tests/randomized_tests.rs
After recent changes of #11033 tests with current settings run in ~2 minutes. As part of this PR I am increasing the number of iterations so we can test more scenarios for higher committee size as well.
---
> [refactor] increase number of test iterations for consensus randomized tests

- crates/sui-adapter-transactional-tests/tests/upgrade/dep_override.exp
- crates/sui-adapter-transactional-tests/tests/upgrade/dep_override.move
- crates/sui-adapter-transactional-tests/tests/upgrade/new_types.exp
- crates/sui-adapter-transactional-tests/tests/upgrade/new_types.move
Added some more tests related to package upgrades.
These are the actual tests
> [package-upgrades] Added transactional tests for package upgrades

- crates/sui-json/src/lib.rs
- crates/sui-json/src/tests.rs
> add struct support to sui_json

- apps/core/src/hooks/useGetValidatorsEvents.ts
> change max event query limit to 50

- apps/wallet/src/ui/app/components/menu/content/MenuList.tsx
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
- apps/wallet/src/ui/app/shared/faucet/FaucetRequestButton.tsx
> [wallet-ext] Remove instrumentation of the "RequestGas" event

- .github/workflows/trigger-builds.yml
Add concurrency limitation
[Testing via my branch](https://github.com/MystenLabs/sui/actions/runs/4758611865/jobs/8456888065)
> Add concurrency limitation

- .github/workflows/rust.yml
Feel free to revert this PR when the check is working again!
> Remove broken check

- apps/wallet/src/ui/app/components/navigation/index.tsx
- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
1. even padding on the left/right for each content section
2. also double check the spacing within each section
3. section title color
https://mysten.atlassian.net/browse/APPS-695
---
> [wallet]: update wallet styling

- crates/sui-adapter-transactional-tests/tests/runtime_behavior/versioned_check_swap_loc_new.exp
- crates/sui-adapter-transactional-tests/tests/runtime_behavior/versioned_check_swap_loc_new.move
- crates/sui-adapter-transactional-tests/tests/runtime_behavior/versioned_check_swap_loc_old.exp
- crates/sui-adapter-transactional-tests/tests/runtime_behavior/versioned_check_swap_loc_old.move
- crates/sui-adapter/src/adapter.rs
- crates/sui-protocol-config/src/lib.rs
- crates/sui-protocol-config/src/snapshots/sui_protocol_config__test__version_7.snap
- crates/sui-transactional-test-runner/src/test_adapter.rs
- external-crates/move/move-vm/runtime/src/config.rs
- external-crates/move/move-vm/runtime/src/interpreter.rs
- external-crates/move/move-vm/runtime/src/runtime.rs
- external-crates/move/move-vm/transactional-tests/tests/instructions/inaccessible_borrowed_local.exp
- external-crates/move/move-vm/transactional-tests/tests/instructions/inaccessible_borrowed_local.mvir
- external-crates/move/move-vm/types/src/values/values_impl.rs
- external-crates/move/testing-infra/transactional-test-runner/src/vm_test_harness.rs
- Remove unnecessary checks in interpreter
- Added tests
---
> [move] Remove unnecessary code

- apps/explorer/src/pages/epochs/EpochDetail.tsx
- apps/explorer/src/pages/epochs/EpochsTable.tsx
- apps/explorer/src/utils/getStorageFundFlow.ts
- sdk/typescript/src/types/index.ts
Update Epochs Table to show Storage Fund Net Inflow in place of Storage Revenue
---
> [explorer] - update epochs table to show inflow

- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
Without this, it is possible for the pending queue to contain finished tasks that are not cleared out as early as the could be, which delays the start of new tasks.
> [CheckpointExecutor] Clear pending queue more aggressively

- crates/sui-config/tests/snapshots/snapshot_tests__network_config_snapshot_matches.snap
- narwhal/config/src/lib.rs
- narwhal/config/tests/snapshots/config_tests__parameters.snap
> Increase NW batch size .5Mb -> 5Mb

- crates/sui-benchmark/tests/simtest.rs
- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
- crates/sui-json-rpc/src/api/mod.rs
- crates/sui-json-rpc/src/transaction_execution_api.rs
- crates/sui-node/src/lib.rs
> add execution latency metrics

- crates/sui-benchmark/src/lib.rs
- crates/sui-core/src/authority_aggregator.rs
- crates/sui-core/src/quorum_driver/mod.rs
These metrics help locate issues when backlogs form at clients.
CI. Deployed to private testnet.
---
> Add inflight metrics in authority aggregator

- scripts/compatibility/monitor_synced.py
We seem to fail this timeout at a certain point. Instead let's log, and at least try and get the workflow to consistently pass eventually.
---
> [CompatibilityChecker] Remove checkpoint progress timeout]

- apps/explorer/src/pages/validators/Validators.tsx
https://mysten.atlassian.net/browse/APPS-809
---
> [explorer]: update for 0 display

- crates/transaction-fuzzer/src/account_universe.rs
- crates/transaction-fuzzer/src/account_universe/transfer_gen.rs
- crates/transaction-fuzzer/src/account_universe/universe.rs
- crates/transaction-fuzzer/tests/p2p_fuzz.rs
Adds generation of random sponsored transactions, both valid and invalid and runs them in the transaction universe.
> [transaction fuzzer] Fuzz sponsored transactions in the txn universe

- crates/sui-cluster-test/src/test_case/coin_index_test.rs
Adding the same sort to the vectors 
CI / Staging runs
---
> [Cluster Test] ensuring both balances are sorted

- crates/sui-benchmark/src/lib.rs
- crates/sui-cluster-test/src/lib.rs
- crates/sui-cluster-test/src/test_case/coin_index_test.rs
- crates/sui-cluster-test/src/test_case/fullnode_execute_transaction_test.rs
- crates/sui-faucet/src/bin/merge_coins.rs
- crates/sui-faucet/src/faucet/simple_faucet.rs
- crates/sui-json-rpc/src/unit_tests/transaction_tests.rs
- crates/sui-rosetta/src/construction.rs
- crates/sui-rosetta/src/unit_tests/balance_changing_tx_tests.rs
- crates/sui-rosetta/tests/end_to_end_tests.rs
- crates/sui-rpc-loadgen/src/payload/rpc_command_processor.rs
- crates/sui-sdk/examples/tic_tac_toe.rs
- crates/sui-sdk/examples/transfer_coins.rs
- crates/sui-sdk/src/apis.rs
- crates/sui-sdk/src/lib.rs
- crates/sui/src/client_commands.rs
- crates/sui/src/fire_drill.rs
- crates/sui/src/validator_commands.rs
- crates/test-utils/src/network.rs
- crates/test-utils/src/transaction.rs
The name was a bit confusing and I think I fell a few times for it (not knowing that this isn't the real QuorumDriver)
> Rename QuoromDriver in SuiClient

- crates/sui-config/src/builder.rs
- crates/sui-config/src/genesis_config.rs
- crates/sui-core/src/authority/authority_test_utils.rs
- crates/sui-core/src/authority/epoch_start_configuration.rs
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-core/src/unit_tests/pay_sui_tests.rs
- crates/sui-types/src/sui_system_state/epoch_start_sui_system_state.rs
Useful for testing / fuzzing
---
> allow setting rgp and protocol config in test authority builder

- crates/sui-indexer/src/lib.rs
I stole this change from https://github.com/MystenLabs/sui/pull/10854 I cannot land that one b/c of a CI failure, retried several times but no luck, so I rebased and created a new PR here.
> Indexer: support ipv6

- crates/sui-sdk/src/apis.rs
> sui-sdk: simplify get_coins_stream impl. with new Page definition

- apps/wallet/src/ui/app/pages/home/transfer-coin/SendTokenForm.tsx
- crates/sui-json-rpc-types/src/sui_coin.rs
- crates/sui-json-rpc/src/coin_api.rs
- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-rosetta/src/construction.rs
- crates/sui-sdk/src/apis.rs
- sdk/typescript/src/framework/framework.ts
- sdk/typescript/src/types/coin.ts
> removing locked_coin_til_epoch

- apps/wallet/src/ui/app/components/receipt-card/index.tsx
Adds a wait time (1m)  before showing the link out to Explorer for recent transactions
---
> [wallet-ext] - add wait time before showing link to view in explorer

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v0.34.0 version bump

- .changeset/eight-terms-itch.md
- pnpm-lock.yaml
- sdk/typescript/package.json
I noticed this creeping into prod builds.
N/A
> [ts-sdk] Move msw to dev deps

- crates/sui-adapter/src/programmable_transactions/execution.rs
If adding abilities on upgrade is allowed, then load all a package's types at their origins.
```
```
> [upgrades] Populate loader with all previous types

- crates/sui-adapter/src/programmable_transactions/execution.rs
If adding abilities on upgrade is allowed, then load all a package's types at their origins.
```
```
> [cherry-pick][upgrades] Populate loader with all previous types (#11296)

- crates/sui-storage/src/indexes.rs
- deny.toml
As requested by Srinath:
Port of https://github.com/MystenLabs/sui/pull/11147
---
> Jian max string fix

- crates/sui-core/src/transaction_orchestrator.rs
We want the wait_for_finality timer to exclude the local execution.
---
> Fix the wait_for_finality timer

- crates/sui/src/keytool.rs
add a cli tool to convert between sui keystore format (base64 of 33 byte flag || private key) vs the wallet format (hex of 32 byte private key). 
```
target/debug/sui keytool convert ABTk0pAIhn4GylSCKycYx+7ItEQim0h6ohIqVmZdRX8C 
2023-04-18T15:33:22.742744Z  INFO sui::keytool: Wallet formatted private key: 0x14e4d29008867e06ca54822b2718c7eec8b444229b487aa2122a56665d457f02
target/debug/sui keytool convert 0x14e4d29008867e06ca54822b2718c7eec8b444229b487aa2122a56665d457f02
2023-04-18T15:33:33.572271Z  INFO sui::keytool: Keystore formatted private key: "ABTk0pAIhn4GylSCKycYx+7ItEQim0h6ohIqVmZdRX8C"
```
--- …
> keytool: conversion btw keystore vs wallet format

- Cargo.lock
- crates/sui-indexer/src/apis/extended_api.rs
- crates/sui-indexer/src/apis/indexer_api.rs
- crates/sui-json-rpc/Cargo.toml
- crates/sui-json-rpc/src/api/extended.rs
- crates/sui-json-rpc/src/api/indexer.rs
- crates/sui-json-rpc/src/api/mod.rs
- crates/sui-json-rpc/src/indexer_api.rs
- crates/sui-json-rpc/src/read_api.rs
- crates/sui-open-rpc/spec/openrpc.json
> configurable max item size in env var

- apps/explorer/src/pages/validators/Validators.tsx
Small PR to add voting power to the validator's page
> Add Voting Power to validators page

- crates/sui-framework/docs/clob.md
- crates/sui-framework/docs/custodian.md
- crates/sui-framework/packages/deepbook/sources/clob.move
- crates/sui-framework/packages/deepbook/sources/custodian.move
- crates/sui-framework/packages/deepbook/tests/clob_tests.move
> Cherrypick of DeepBook change

- crates/sui/tests/snapshot_tests.rs
Fixing snapshot test that was hopefully broken from a bad cherry pick. @tzakian please confirm? 
---
> Fix snapshot test

- apps/wallet/README.md
Removes security disclaimer as we have gone through audits
> Remove the Security Disclaimer

- apps/core/src/hooks/useGetLatestCheckpointSequenceNumber.ts
- apps/core/src/hooks/useGetTotalTransactionBlocks.ts
- apps/core/src/index.ts
- apps/explorer/package.json
- apps/explorer/src/components/HomeMetrics/Checkpoint.tsx
- apps/explorer/src/components/HomeMetrics/CurrentEpoch.tsx
- apps/explorer/src/components/HomeMetrics/FormattedStatsAmount.tsx
- apps/explorer/src/components/HomeMetrics/NetworkStats.tsx
- apps/explorer/src/components/HomeMetrics/NetworkTPS.tsx
- apps/explorer/src/components/HomeMetrics/OnTheNetwork.tsx
- apps/explorer/src/components/HomeMetrics/index.tsx
- apps/explorer/src/components/transactions/index.tsx
- apps/explorer/src/hooks/useGetNetworkMetrics.ts
- apps/explorer/src/pages/checkpoints/CheckpointsTable.tsx
- apps/explorer/src/pages/epochs/utils.ts
- apps/explorer/src/ui/Card.tsx
- apps/explorer/src/ui/Heading.tsx
- apps/explorer/src/ui/ProgressBar.tsx
- pnpm-lock.yaml
- Component for Networks TPS, Checkpoint, On the Network, and Current epoch
- This PR does not add the created component to the home page
> Explorer home page stats update 

- crates/sui-core/src/checkpoints/mod.rs
fixes a race condition which can lead to a crash.
cargo simtest
---
fixes a race condition which can lead to a crash.
> Write full_checkpoint_content and checkpoint_content atomically

- crates/sui-node/src/main.rs
This PR listens for SIGTERM in addition to SIGINT. This is needed so that we can properly stop and wait background RocksDB threads, to avoid RocksDB corruption when run inside supervisor (like docker, systemd, etc).
See also: https://github.com/MystenLabs/sui/pull/11323
> [sui-node] Capture SIGTERM as well as SIGINT

- apps/explorer/src/components/module/PkgModulesWrapper.tsx
- apps/explorer/src/ui/SplitPanes.tsx
- apps/explorer/src/ui/stories/SplitPanes.stories.tsx
https://mysten.atlassian.net/browse/APPS-798
---
> [explorer]: add collapsible panels

- Cargo.lock
- crates/sui-core/src/state_accumulator.rs
- crates/sui-transactional-test-runner/Cargo.toml
- crates/sui-transactional-test-runner/src/test_adapter.rs
- crates/sui-types/src/in_memory_storage.rs
Unfortunately, the transactional tests don't use AuthorityStore, so we have to duplicate some logic here, but I think this is well worth it for the increased coverage.
> Verify accumulator behavior in sui transactional tests

- apps/explorer/src/components/TransactionBlocksForAddress/TransactionBlocksForAddress.tsx
fix object page transactions. data load is outpacing rendering which causes a bug
Locally.
---
> [explorer] object page transactions fix

- crates/sui-core/src/authority/authority_store_pruner.rs
return back pruner limiting by maximum transactions in a batch
> [pruner] max transactions in batch

- apps/icons/src/ChevronLeft12.tsx
> [explorer]: update asset for chevron 12

- crates/sui-core/src/authority_server.rs
> use mystem histogram for some metrics

- crates/sui-core/src/authority_aggregator.rs
> log rpc error code

- Cargo.lock
- crates/sui-core/src/authority.rs
- crates/sui-node/Cargo.toml
- crates/sui-node/src/lib.rs
- crates/sui-node/src/main.rs
- crates/sui-telemetry/Cargo.toml
- crates/sui-telemetry/src/lib.rs
- crates/sui/tests/snapshots/snapshot_tests__basic_read_cmd_snapshot_tests.snap
> add network identifier and send to telemetry

- crates/sui-indexer/src/handlers/checkpoint_handler.rs
move calls are still used by Explorer move call metrics
Test locally and make sure that only move calls can be populated while others are not.
> indexer stability: re-enable move call population

- crates/sui-node/src/handle.rs
Fixes memory leak in multi-iteration tests
---
> Shut down the sim node when SuiNodeHandle is dropped. 

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_store.rs
> Log running consistency checks

- crates/sui-core/src/authority.rs
- crates/sui-core/src/authority/authority_store_pruner.rs
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-node/src/lib.rs
- crates/typed-store/src/rocks/iter.rs
this PR:
* reverts https://github.com/MystenLabs/sui/commit/9ae7afbf6a20466b23cd7d90a46280d284ef9f2f
* disables multi_get objects call in environments that do not have indirect objects
> [pruner] revert 9ae7afbf6a20466b23cd7d90a46280d284ef9f2f

- crates/sui-benchmark/tests/simtest.rs
- crates/sui-sdk/src/wallet_context.rs
- crates/sui/tests/full_node_tests.rs
- crates/test-utils/src/messages.rs
- crates/test-utils/src/transaction.rs
This PR moves all the gas object read code using wallet context into WalletContext.
> [TestInfra] Consolidate WalletContext gas code

- apps/wallet/src/ui/app/pages/home/tokens/TokensDetails.tsx
Scroll 
https://user-images.githubusercontent.com/126525197/234365779-22f9b258-5c3e-4ecd-9d1a-1fb33f58e4c7.mov
> scroll token

- doc/src/build/sui-gas-charges.md
> Correct mists > mist

- doc/src/build/fullnode.md
- doc/src/learn/exchange-integration-guide.md
> Update HW reqs for Full node

- crates/sui-core/src/db_checkpoint_handler.rs
- crates/sui-node/src/lib.rs
> Fix checkpoint store used in db checkpoint handler

- crates/sui-open-rpc/spec/openrpc.json
- crates/sui-open-rpc/src/examples.rs
Examples for rpc api ref. Resubmitting PR to capture updates made to Sui repo since previous submission. A few additional examples added since then, too. 
Locally
---
> Examples for API ref

- dapps/sponsored-transactions/src/App.tsx
- dapps/sponsored-transactions/src/utils/sponsorTransaction.ts
Demo was broken with some recent changes, updates to fix it.
Ran locally.
> Fix sponsored tx demo

- apps/core/tailwind.config.ts
Update typography to match the latest figma designs.
N/A
> [apps] Update typography

- crates/sui-sdk/src/apis.rs
Expose get_checkpoints method to rust sdk
---
> [Sui-sdk] Expose get_checkpoints method to rust sdk

- Cargo.lock
- crates/sui-core/src/authority/test_authority_builder.rs
- crates/sui-node/src/lib.rs
- crates/sui-storage/Cargo.toml
- crates/sui-storage/src/indexes.rs
- crates/sui-types/src/error.rs
Moved from constant length to new length allowed in protocol verifier
Locally,
TODO: check on write
---
> [node] adding error handling and also piping length from config

- crates/sui-json-rpc/src/transaction_execution_api.rs
do not return balance and object change if local execution failed
> [bugfix] - do not return balance and object change if local execution failed

- crates/sui-core/src/db_checkpoint_handler.rs
- crates/sui-storage/src/object_store/util.rs
RocksDB leaves empty .log files after compaction which fails during upload to S3 with errors like:
```
Generic S3 error: Error performing put request epoch_0/store/perpetual/000059.log: response error \"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>MissingContentLength</Code><Message>You must provide the Content-Length HTTP header.</Message><RequestId>PHNPR5VQNTY0GW4Y</RequestId><HostId>D08UaQcJIVUVKFwpo3MrwLAYYqHWNM1FQxHSZfcNiCwkU0cTN0PPN+x+2ot6g1Q+hQ+cuVIsrTw=</HostId></Error>\
```
Adding a filter for such files, as they are also unused during restore.
Also updated the deletion of old checkpoints to directly invoke delete on the directory vs doing it file by file earlier by using object store delete functionality.
Verified with a restore.
> Filter empty log files during snapshot upload

- crates/sui-types/src/README.md
- crates/sui/src/client_commands.rs
- doc/src/learn/architecture/consensus.md
- doc/src/learn/cryptography/index.md
- doc/src/learn/cryptography/sui-intent-signing.md
- doc/src/learn/cryptography/sui-multisig.md
- doc/src/learn/cryptography/sui-offline-signing.md
- doc/src/learn/cryptography/sui-signatures.md
- doc/src/learn/cryptography/sui-wallet-specs.md
- doc/src/learn/exchange-integration-guide.md
- doc/src/navconfig.json
- narwhal/crypto/README.md
- nre/validator_tool.md
add more docs.  i find the signature requirement is hard to find (the offline signing page is more of a practical and concrete example) so i created a new page for sui-signatures. it fits well to discuss crypto agility as well. 
n/a
---
> doc: Add page for signatures and crypto agility

- apps/explorer/src/pages/home/Home.tsx
As the title says ^, gating this behind another feature flag just cause extra safety 🤷🏼‍♂️ 
---
N/A
> [explorer] remove the sui token card from the home page

- sdk/typescript/src/types/transactions.ts
This PR broke devnet and testnet runs: https://github.com/MystenLabs/sui/pull/11163
CI
---
> Fix backwards compat in schema

- .changeset/neat-swans-confess.md
- apps/wallet/configs/environment/.env.defaults
- apps/wallet/src/background/NetworkEnv.ts
- apps/wallet/src/dapp-interface/WalletStandardInterface.ts
- apps/wallet/src/shared/api-env.ts
- apps/wallet/src/shared/experimentation/features.ts
- apps/wallet/src/ui/app/ApiProvider.ts
- apps/wallet/src/ui/app/components/explorer-link/Explorer.ts
- apps/wallet/src/ui/app/components/logo/index.tsx
- sdk/wallet-adapter/wallet-standard/src/chains.ts
> [wallet-ext] - update to wallet

- external-crates/move/move-vm/runtime/src/loader.rs
- Add counting to test only function
- Hardening in the future if it is used outside of tests
---
> [move][test] Fix test code counting

- Cargo.lock
- Cargo.toml
- crates/sui-open-rpc/spec/openrpc.json
> Sui v1.0.0 version change

- apps/wallet/src/ui/app/components/user-approve-container/index.tsx
- apps/wallet/src/ui/app/shared/transaction-summary/cards/BalanceChanges.tsx
> [wallet-ext] - balance change fix

- doc/src/build/dev_cheat_sheet.md
- doc/src/navconfig.json
Fixing my oversights.
Locally
---
> Updates to topic

- doc/src/build/package-upgrades.md
Missed some content to transfer.
Local
---
> Adding missed content

- crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs
> [CheckpointExecutor] Better logging for missing tx effects

- doc/src/learn/cryptography/sui-multisig.md
add differences between multisig and threshold crypto
---
> [crypto][docs] add differences between multisig and threshold crypto

- crates/sui-config/src/lib.rs
- crates/sui-config/src/node_config_metrics.rs
- crates/sui-config/src/transaction_deny_config.rs
- crates/sui-core/src/transaction_signing_filter.rs
- crates/sui-node/src/lib.rs
Report a few metrics based on the NodeConfig, just to give more insights into what goes into the node config.
> Add node config metrics

- doc/src/build/package-upgrades.md
Some very minor tweaks to the package upgrade docs (mostly to whitespace in the code example), but also standardising some of the word-wrapping, bullets, etc in the rest of the snippet I put in.
> [upgrades] Docs snags
